-- ============================================================================
-- Quiz Seed: 1 Chronicles — Part 3 (Chapters 21–29)
-- 3 difficulties × 9 chapters = 144 total questions
-- kids: 3 Qs, teens: 5 Qs, adults: 8 Qs per chapter
-- correct_answer is always 'a'
-- ============================================================================

-- ═══ 1 Chronicles Chapter 21 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 21, 'kids', 1, 'Who provoked David to number Israel?', 'Satan', 'Joab', 'An angel', 'The Philistines', 'a', '1 Chronicles 21:1 — "And Satan stood up against Israel, and provoked David to number Israel."'),
('1 Chronicles', 21, 'kids', 2, 'What did God send as punishment for David''s census?', 'A plague upon Israel', 'A great flood', 'An enemy army', 'A drought for three years', 'a', '1 Chronicles 21:14 — "So the LORD sent pestilence upon Israel: and there fell of Israel seventy thousand men."'),
('1 Chronicles', 21, 'kids', 3, 'Whose threshing floor did David buy to build an altar?', 'Ornan the Jebusite', 'Araunah the priest', 'Zadok the Levite', 'Joab the captain', 'a', '1 Chronicles 21:18 — "The angel of the LORD commanded Gad to say to David, that David should go up, and set up an altar unto the LORD in the threshingfloor of Ornan the Jebusite."'),
-- Teens
('1 Chronicles', 21, 'teens', 1, 'Why did Joab object to David numbering the people?', 'He said it would be a cause of trespass to Israel and asked why David should bring guilt upon them', 'He feared the Philistines would learn Israel''s strength', 'He said the people were too few to count', 'He believed only priests were allowed to number Israel', 'a', '1 Chronicles 21:3 — "Why will he be a cause of trespass to Israel?" Joab warned David the act would bring guilt upon the nation.'),
('1 Chronicles', 21, 'teens', 2, 'What were the three choices of punishment God offered David through the prophet Gad?', 'Three years of famine, three months of destruction by enemies, or three days of pestilence', 'Seven years of famine, seven months of war, or seven days of plague', 'One year of drought, one month of sword, or one week of disease', 'Forty years wandering, forty days of plague, or forty nights of darkness', 'a', '1 Chronicles 21:12 — "Either three years'' famine; or three months to be destroyed before thy foes...or else three days the sword of the LORD, even the pestilence, in the land."'),
('1 Chronicles', 21, 'teens', 3, 'What did David say when he chose his punishment from the three options?', 'Let me fall into the hand of the LORD for his mercies are great, and not into the hand of man', 'Let the pestilence come but spare Jerusalem', 'Let famine come so no sword may devour the innocent', 'Let us trust in the LORD and accept whatever he sends', 'a', '1 Chronicles 21:13 — "Let me fall now into the hand of the LORD; for very great are his mercies: but let me not fall into the hand of man."'),
('1 Chronicles', 21, 'teens', 4, 'What did David see standing between heaven and earth over Jerusalem?', 'The angel of the LORD with a drawn sword stretched over Jerusalem', 'A pillar of fire above the city', 'A cloud of darkness covering the temple mount', 'A white horse with a rider holding a scroll', 'a', '1 Chronicles 21:16 — "David lifted up his eyes, and saw the angel of the LORD stand between the earth and the heaven, having a drawn sword in his hand stretched out over Jerusalem."'),
('1 Chronicles', 21, 'teens', 5, 'How much did David pay Ornan for the threshing floor?', 'Six hundred shekels of gold', 'Fifty shekels of silver', 'One hundred shekels of silver', 'Two hundred shekels of gold', 'a', '1 Chronicles 21:25 — "So David gave to Ornan for the place six hundred shekels of gold by weight."'),
-- Adults
('1 Chronicles', 21, 'adults', 1, 'What was the total count of fighting men Joab reported to David after the census?', 'One million one hundred thousand men in Israel and four hundred seventy thousand in Judah', 'Eight hundred thousand in Israel and five hundred thousand in Judah', 'One million two hundred thousand men across all Israel', 'Seven hundred thousand in Israel and three hundred thousand in Judah', 'a', '1 Chronicles 21:5 — "All they of Israel were a thousand thousand and an hundred thousand men that drew sword: and Judah was four hundred threescore and ten thousand men that drew sword."'),
('1 Chronicles', 21, 'adults', 2, 'Why did Joab not number Levi and Benjamin in the census?', 'Because the king''s word was abominable to him and because God was displeased', 'Because those tribes were exempt by Mosaic law', 'Because their captains refused to supply the numbers', 'Because Joab ran out of time before the plague came', 'a', '1 Chronicles 21:6 — "But Levi and Benjamin counted he not among them: for the king''s word was abominable to Joab."'),
('1 Chronicles', 21, 'adults', 3, 'How many people died in the plague God sent upon Israel?', 'Seventy thousand men', 'Forty thousand men', 'One hundred thousand men', 'Seven thousand men', 'a', '1 Chronicles 21:14 — "So the LORD sent pestilence upon Israel: and there fell of Israel seventy thousand men."'),
('1 Chronicles', 21, 'adults', 4, 'What did God say to the angel of destruction at Jerusalem, causing him to stop the plague?', 'It is enough, stay now thine hand', 'Depart, for my mercy endureth for ever', 'Peace be unto this city, hold back thy sword', 'The king hath humbled himself, cease the plague', 'a', '1 Chronicles 21:15 — "And God said to the angel that destroyed, It is enough, stay now thine hand. And the angel of the LORD stood by the threshingfloor of Ornan the Jebusite."'),
('1 Chronicles', 21, 'adults', 5, 'What did Ornan offer to give David freely for the altar?', 'The threshing floor, the oxen, the threshing instruments, and the wheat', 'Only the land and the altar stones', 'The wheat and the oxen but not the land', 'The threshing floor and the wheat only', 'a', '1 Chronicles 21:23 — "Ornan said unto David, Take it to thee, and let my lord the king do that which is good in his eyes: lo, I give thee the oxen also for burnt offerings, and the threshing instruments for wood, and the wheat for the meat offering; I give it all."'),
('1 Chronicles', 21, 'adults', 6, 'Why did David insist on paying full price for Ornan''s threshing floor?', 'Because he would not offer to God that which cost him nothing', 'Because Mosaic law required a fair market price for all sacrificial sites', 'Because David feared Ornan would later reclaim the land', 'Because God had commanded David to pay the full amount', 'a', '1 Chronicles 21:24 — "I will not take it for the LORD, nor offer burnt offerings without cost. But I will verily buy it for the full price."'),
('1 Chronicles', 21, 'adults', 7, 'What happened when David offered burnt offerings and peace offerings on the new altar?', 'The LORD answered him from heaven by fire upon the altar of burnt offering', 'A cloud of glory filled the threshing floor', 'The angel of the LORD sheathed his sword immediately', 'The plague stopped and a rainbow appeared over Jerusalem', 'a', '1 Chronicles 21:26 — "And David built there an altar unto the LORD, and offered burnt offerings and peace offerings, and called upon the LORD; and he answered him from heaven by fire upon the altar of burnt offering."'),
('1 Chronicles', 21, 'adults', 8, 'What theological significance did this threshing floor hold for the future of Israel?', 'It became the site designated for the temple, for both the tabernacle of Moses and the altar were at that time at Gibeon', 'It was the spot where the Ark of the Covenant was permanently housed', 'It became the burial place of Israel''s kings', 'It was consecrated as the altar for the Levitical priests only', 'a', '1 Chronicles 21:28-29 — David sacrificed there because he was afraid of the angel''s sword, while the tabernacle and altar were still at Gibeon — marking this site as the future temple location.');

-- ═══ 1 Chronicles Chapter 22 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 22, 'kids', 1, 'What did David prepare for Solomon to build?', 'The house of the LORD', 'A great palace in Jerusalem', 'A city for the Levites', 'A wall around all of Israel', 'a', '1 Chronicles 22:5 — "David prepared abundantly before his death" for the building of the house of the LORD.'),
('1 Chronicles', 22, 'kids', 2, 'Who did God say would build the temple instead of David?', 'Solomon, David''s son', 'Joab the commander', 'The high priest Zadok', 'Nathan the prophet', 'a', '1 Chronicles 22:10 — "He shall build an house for my name; and he shall be my son, and I will be his father."'),
('1 Chronicles', 22, 'kids', 3, 'What famous words of encouragement did David give to Solomon?', 'Be strong and of good courage, dread not, nor be dismayed', 'Fear no man, for God is with you always', 'Trust in the LORD with all your heart', 'The battle is the LORD''s; go and prosper', 'a', '1 Chronicles 22:13 — "Be strong, and of good courage; dread not, nor be dismayed."'),
-- Teens
('1 Chronicles', 22, 'teens', 1, 'Why did God tell David he could not build the temple?', 'Because David was a man of war and had shed much blood', 'Because David had sinned with Bathsheba', 'Because David was not from the priestly line', 'Because the time was not yet right in God''s plan', 'a', '1 Chronicles 22:8 — "Thou hast shed blood abundantly, and hast made great wars: thou shalt not build an house unto my name, because thou hast shed much blood upon the earth in my sight."'),
('1 Chronicles', 22, 'teens', 2, 'What enormous amount of iron did David prepare for the temple construction?', 'Iron in abundance without weight', 'One thousand talents of iron', 'Ten thousand talents of iron', 'Five hundred thousand cart-loads of iron', 'a', '1 Chronicles 22:3 — "And David prepared iron in abundance for the nails for the doors of the gates, and for the joinings; and brass in abundance without weight."'),
('1 Chronicles', 22, 'teens', 3, 'How much gold and silver did David say he had prepared for the temple?', 'A hundred thousand talents of gold and a million talents of silver', 'One thousand talents of gold and ten thousand talents of silver', 'Fifty thousand talents of gold and five hundred thousand of silver', 'Two hundred thousand talents of gold and two hundred thousand of silver', 'a', '1 Chronicles 22:14 — "In my trouble I have prepared for the house of the LORD an hundred thousand talents of gold, and a thousand thousand talents of silver."'),
('1 Chronicles', 22, 'teens', 4, 'What condition did David charge Solomon to fulfill for building the temple?', 'To keep the commandments of the LORD and observe his statutes and judgments', 'To first defeat all remaining enemies in the land', 'To gather additional gold from all the princes of Israel', 'To build an altar at Gibeon before beginning the temple', 'a', '1 Chronicles 22:12-13 — "The LORD give thee wisdom and understanding...then shalt thou prosper, if thou takest heed to fulfil the statutes and judgments which the LORD charged Moses with concerning Israel."'),
('1 Chronicles', 22, 'teens', 5, 'What did David tell the leaders of Israel to do once Solomon became king?', 'To help Solomon build the house of the LORD', 'To submit all tithes to Solomon''s treasury', 'To set up guard at the borders of the kingdom', 'To destroy the remaining Canaanite cities', 'a', '1 Chronicles 22:19 — "Arise therefore, and build ye the sanctuary of the LORD God, to bring the ark of the covenant of the LORD, and the holy vessels of God, into the house that is to be built to the name of the LORD."'),
-- Adults
('1 Chronicles', 22, 'adults', 1, 'What specific statement did David make declaring the site of Ornan''s threshing floor?', 'This is the house of the LORD God, and this is the altar of the burnt offering for Israel', 'Let this be the holy mountain of the LORD for ever', 'Here shall the name of the LORD dwell among his people', 'This ground is consecrated to the LORD from this day forward', 'a', '1 Chronicles 22:1 — "Then David said, This is the house of the LORD God, and this is the altar of the burnt offering for Israel."'),
('1 Chronicles', 22, 'adults', 2, 'How did David describe Solomon''s character in commissioning him for the temple work?', 'Young and tender, the work was exceeding magnifical', 'Wise and strong, ready for any great task', 'Humble and obedient, beloved of all Israel', 'Brave and skilled, trained in all wisdom', 'a', '1 Chronicles 22:5 — "Solomon my son is young and tender, and the house that is to be builded for the LORD must be exceeding magnifical, of fame and of glory throughout all countries."'),
('1 Chronicles', 22, 'adults', 3, 'What specific word of the LORD came to David concerning Solomon and the temple?', 'A son shall be born to thee who shall be a man of rest, and his name shall be Solomon, and I will give peace unto Israel in his days', 'Your son shall be greater than you and build what you have desired', 'The LORD will build the house through Solomon and not by strength of arms', 'Solomon shall be called beloved of God and shall build in righteousness', 'a', '1 Chronicles 22:9 — "Behold, a son shall be born to thee, who shall be a man of rest...his name shall be Solomon, and I will give peace and quietness unto Israel in his days."'),
('1 Chronicles', 22, 'adults', 4, 'What specific covenant promise did God make to Solomon through David?', 'I will be his father, he will be my son, and I will not take my mercy away from him, and I will establish his kingdom forever', 'His kingdom shall endure as long as the sun and moon', 'He shall be greater than all the kings of the earth', 'His throne shall be established by righteousness forever', 'a', '1 Chronicles 22:10 — "He shall build an house for my name; and he shall be my son, and I will be his father; and I will establish the throne of his kingdom over Israel for ever."'),
('1 Chronicles', 22, 'adults', 5, 'How many skilled craftsmen — strangers in the land — did David number to work on the temple?', 'An hundred and fifty thousand and three thousand and six hundred', 'Thirty thousand workers and ten thousand overseers', 'Fifty thousand laborers and five thousand foremen', 'Seventy thousand carriers and eighty thousand stonecutters', 'a', '1 Chronicles 22:2 — "David commanded to gather together the strangers that were in the land of Israel; and he set masons to hew wrought stones to build the house of God."'),
('1 Chronicles', 22, 'adults', 6, 'What did David say God had given him to prepare for the temple, enumerating specific materials?', 'Gold, silver, brass, iron, wood, onyx, stones to be set, glistening stones, all manner of precious stones, and marble stones', 'Gold and silver from the nations, cedar from Lebanon, and iron for the gates', 'All the riches of Canaan and the spoils of his wars', 'The tithes of all Israel set aside for forty years', 'a', '1 Chronicles 22:14 — David said "I have prepared for the house of my God the gold, the silver, the brass, the iron, the wood; the onyx stones, and stones to be set, glistening stones, and of divers colours."'),
('1 Chronicles', 22, 'adults', 7, 'To whom did David charge his command concerning the temple besides Solomon?', 'All the princes of Israel', 'The priests and Levites alone', 'The elders of the tribes of Judah and Benjamin', 'The military commanders and the judges', 'a', '1 Chronicles 22:17 — "David also commanded all the princes of Israel to help Solomon his son."'),
('1 Chronicles', 22, 'adults', 8, 'What did David say the LORD had given Israel that made the time right for building the temple?', 'Rest on every side, no adversary and no evil occurrent', 'Victory over all surrounding nations', 'Peace with Egypt and the sea peoples', 'A generation of prosperity and abundance', 'a', '1 Chronicles 22:18 — "Is not the LORD your God with you? and hath he not given you rest on every side? for he hath given the inhabitants of the land into mine hand; and the land is subdued before the LORD."');

-- ═══ 1 Chronicles Chapter 23 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 23, 'kids', 1, 'How old was David when he made Solomon king?', 'Old and full of days', 'Seventy years old', 'Sixty years old', 'Forty years old', 'a', '1 Chronicles 23:1 — "So when David was old and full of days, he made Solomon his son king over Israel."'),
('1 Chronicles', 23, 'kids', 2, 'How many Levites did David count who were thirty years old and above?', 'Thirty and eight thousand', 'Twenty thousand', 'Forty thousand', 'Fifty thousand', 'a', '1 Chronicles 23:3 — "Now the Levites were numbered from the age of thirty years and upward: and their number by their polls, man by man, was thirty and eight thousand."'),
('1 Chronicles', 23, 'kids', 3, 'What was the new minimum age David set for Levites to begin their service?', 'Twenty years old', 'Thirty years old', 'Twenty-five years old', 'Fifteen years old', 'a', '1 Chronicles 23:24 — "These were the sons of Levi after the house of their fathers; even the chief of the fathers, as they were counted by number of names by their polls, that did the work for the service of the house of the LORD, from the age of twenty years and upward."'),
-- Teens
('1 Chronicles', 23, 'teens', 1, 'What were the four roles David assigned to the Levites based on the chapter''s organization?', 'Officers and judges, gatekeepers, musicians, and those who set forward the work of the temple', 'Priests, scribes, warriors, and temple servants', 'Singers, gate guards, teachers, and sacrificers', 'Leaders, workers, worshipers, and builders', 'a', '1 Chronicles 23:4-5 — "Of which, twenty and four thousand were to set forward the work of the house of the LORD; and six thousand were officers and judges: Moreover four thousand were porters; and four thousand praised the LORD with the instruments."'),
('1 Chronicles', 23, 'teens', 2, 'What were the three major families of Levites named in this chapter?', 'Gershon, Kohath, and Merari', 'Aaron, Moses, and Miriam', 'Zadok, Abiathar, and Eli', 'Asaph, Heman, and Jeduthun', 'a', '1 Chronicles 23:6 — "David divided them into courses among the sons of Levi, namely, Gershon, Kohath, and Merari."'),
('1 Chronicles', 23, 'teens', 3, 'Why did David say the Levites no longer needed to carry the tabernacle from place to place?', 'Because the LORD had given Israel rest and would dwell in Jerusalem forever', 'Because the Ark had been brought to Jerusalem permanently', 'Because a temple of stone was stronger than a portable tent', 'Because Moses'' law had been fulfilled when they crossed the Jordan', 'a', '1 Chronicles 23:25-26 — "For David said, The LORD God of Israel hath given rest unto his people, that they may dwell in Jerusalem for ever: And also unto the Levites; they shall no more carry the tabernacle."'),
('1 Chronicles', 23, 'teens', 4, 'What was the specific duty of the Levites who were assigned to assist Aaron''s sons the priests?', 'To purify all holy things, stand every morning to thank and praise the LORD, and offer burnt offerings', 'To teach the law to all Israel and settle legal disputes', 'To guard the temple gates and keep the treasury', 'To serve as musicians and lead the congregation in song', 'a', '1 Chronicles 23:28-30 — Their duty was to wait on Aaron''s sons: "to purify all holy things...to stand every morning to thank and praise the LORD, and likewise at even."'),
('1 Chronicles', 23, 'teens', 5, 'What was notable about Moses'' sons in the Levitical organization?', 'They were named among the tribe of Levi but not set apart as priests like Aaron''s line', 'They became the chief musicians of the temple', 'They were made gatekeepers because of Moses'' sin at Meribah', 'They served as scribes to write down the laws of the temple', 'a', '1 Chronicles 23:14-15 — "But Moses the man of God, his sons were named of the tribe of Levi. The sons of Moses were, Gershom and Eliezer."'),
-- Adults
('1 Chronicles', 23, 'adults', 1, 'What was the total number of Levites counted by David, and from what age were they counted?', 'Thirty and eight thousand from age thirty and upward', 'Twenty-two thousand from age twenty and upward', 'Forty-seven thousand from age thirty and upward', 'Thirty thousand from age twenty-five and upward', 'a', '1 Chronicles 23:3 — "Now the Levites were numbered from the age of thirty years and upward: and their number by their polls, man by man, was thirty and eight thousand."'),
('1 Chronicles', 23, 'adults', 2, 'How were the 38,000 Levites divided among their various tasks?', '24,000 to set forward the work, 6,000 officers and judges, 4,000 gatekeepers, 4,000 musicians', '20,000 workers, 8,000 musicians, 6,000 judges, 4,000 gatekeepers', '18,000 temple workers, 10,000 priests, 6,000 guards, 4,000 singers', '24,000 workers, 8,000 guards, 4,000 judges, 2,000 musicians', 'a', '1 Chronicles 23:4-5 — "Of which, twenty and four thousand were to set forward the work of the house of the LORD; and six thousand were officers and judges: Moreover four thousand were porters; and four thousand praised the LORD."'),
('1 Chronicles', 23, 'adults', 3, 'What does the chapter say about the sons of Gershon and their families?', 'Of Laadan: Jehiel the chief, then Zetham and Joel — three. Of Shimei: Shelomith, Haziel, and Haran — three heads of the fathers', 'They numbered six thousand and were assigned only to the gates', 'All the sons of Gershon became musicians and temple singers', 'They were the fewest Levites and served in the outer courts', 'a', '1 Chronicles 23:8-9 — The sons of Laadan: Jehiel, Zetham, Joel. The sons of Shimei: Shelomith, Haziel, Haran — chiefs of the fathers of Laadan.'),
('1 Chronicles', 23, 'adults', 4, 'What is the stated reason David lowered the minimum service age for Levites from thirty to twenty?', 'Because the Levites would no longer carry heavy burdens and the work of the temple was different from the wilderness tabernacle', 'Because there were not enough older Levites to fill all the positions', 'Because God commanded him directly through a prophet', 'Because the Mosaic law had been amended by the elders of Israel', 'a', '1 Chronicles 23:26 — The Levites "shall no more carry the tabernacle, nor any vessels of it for the service thereof" — the nature of the work had changed, justifying the age reduction.'),
('1 Chronicles', 23, 'adults', 5, 'What specific liturgical duties are listed for the Levites in verses 28-32?', 'Keeping the courts, chambers, purifying holy things, serving in the sanctuary, standing morning and evening to thank and praise, keeping the ark and the shewbread', 'Teaching the law, judging disputes, and collecting tithes from the people', 'Only the musical duties of playing instruments and leading psalms', 'Guarding the temple perimeter and carrying offerings to the altar', 'a', '1 Chronicles 23:28-32 — Their office was to wait on Aaron''s sons, keep courts and chambers, purify holy things, offer sacrifices, thank and praise morning and evening, keep the Sabbaths, set forth the shewbread.'),
('1 Chronicles', 23, 'adults', 6, 'How many sons of Kohath are named, and which line produced the priests?', 'Amram, Izhar, Hebron, and Uzziel; Aaron and his sons were separated for priestly service', 'Only Aaron and Moses, the two sons of Amram', 'Twelve sons, from whom only Aaron''s line ministered', 'Kohath had no named sons; the priests came from Merari', 'a', '1 Chronicles 23:12-13 — "The sons of Kohath; Amram, Izhar, Hebron, and Uzziel, four. The sons of Amram; Aaron and Moses: and Aaron was separated, that he should sanctify the most holy things."'),
('1 Chronicles', 23, 'adults', 7, 'What phrase describes the perpetual nature of the Levitical duty of thanksgiving?', 'To thank and praise the LORD, both morning and evening, and so with the burnt offerings on Sabbaths, new moons, and set feasts', 'To give thanks on the three great feasts only', 'To offer morning prayer every day and evening sacrifice only on the Sabbath', 'To sing praises at every new moon and at the year''s end', 'a', '1 Chronicles 23:30-31 — "And to stand every morning to thank and praise the LORD, and likewise at even; And to offer all burnt sacrifices unto the LORD in the sabbaths, in the new moons, and on the set feasts."'),
('1 Chronicles', 23, 'adults', 8, 'What is the theological significance of David lowering the Levitical service age as it relates to the transition from tabernacle to temple worship?', 'It shows how God''s institutional arrangements adapt to changing circumstances while the underlying purpose of worship and service remains constant', 'It demonstrates that David had authority to override the Mosaic law entirely', 'It proves the temple was more important than the tabernacle in God''s eyes', 'It reflects a purely practical decision with no theological meaning', 'a', '1 Chronicles 23:25-26 — David cited the change from portable tabernacle to permanent temple as justification — God''s rest in Jerusalem transformed the nature of Levitical service, though holiness and worship remained the purpose.');

-- ═══ 1 Chronicles Chapter 24 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, window_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 24, 'kids', 1, 'How many courses or divisions of priests did David organize?', 'Twenty and four courses', 'Twelve courses', 'Forty courses', 'Seven courses', 'a', '1 Chronicles 24:4 — "And there were more chief men found of the sons of Eleazar than of the sons of Ithamar; and thus were they divided. Among the sons of Eleazar there were sixteen chief men...and eight among the sons of Ithamar" — totaling twenty-four courses.'),
('1 Chronicles', 24, 'kids', 2, 'How did David decide which priest would serve first — by choosing favorites or by casting lots?', 'They divided by lot, one portion for the house of Eleazar and another for the house of Ithamar', 'David chose the priests personally based on their faithfulness', 'The eldest priest always went first', 'The high priest Zadok decided the order', 'a', '1 Chronicles 24:5 — "Thus were they divided by lot, one sort with another; for the governors of the sanctuary, and governors of the house of God, were of the sons of Eleazar, and of the sons of Ithamar."'),
('1 Chronicles', 24, 'kids', 3, 'Who were the two main priestly families from Aaron''s sons from whom the 24 courses came?', 'Eleazar and Ithamar', 'Nadab and Abihu', 'Phinehas and Gershom', 'Zadok and Abiathar', 'a', '1 Chronicles 24:1-2 — Aaron''s sons were Nadab, Abihu, Eleazar, and Ithamar; but Nadab and Abihu died early, so Eleazar and Ithamar executed the priest''s office.'),
-- Teens
('1 Chronicles', 24, 'teens', 1, 'Why did the divisions come from only Eleazar and Ithamar and not from Nadab and Abihu?', 'Because Nadab and Abihu died before their father and had no children', 'Because Nadab and Abihu were not yet consecrated as priests', 'Because they had sinned and were disqualified from priestly service', 'Because Moses had reassigned their portions to the Levites', 'a', '1 Chronicles 24:2 — "But Nadab and Abihu died before their father, and had no children: therefore Eleazar and Ithamar executed the priest''s office."'),
('1 Chronicles', 24, 'teens', 2, 'Who assisted David and Zadok in organizing the priestly courses by lot?', 'Ahimelech the son of Abiathar, and the chief of the fathers of the priests and Levites', 'Nathan the prophet and Gad the king''s seer', 'Solomon and the seventy elders of Israel', 'Joab the captain and the princes of the tribes', 'a', '1 Chronicles 24:6 — "Shemaiah the son of Nethaneel the scribe, one of the Levites, wrote them before the king, and the princes, and Zadok the priest, and Ahimelech the son of Abiathar."'),
('1 Chronicles', 24, 'teens', 3, 'How many courses came from Eleazar''s house and how many from Ithamar''s house?', 'Sixteen from Eleazar and eight from Ithamar', 'Twelve from Eleazar and twelve from Ithamar', 'Eighteen from Eleazar and six from Ithamar', 'Twenty from Eleazar and four from Ithamar', 'a', '1 Chronicles 24:4 — "There were more chief men found of the sons of Eleazar than of the sons of Ithamar; and thus were they divided. Among the sons of Eleazar there were sixteen chief men...and eight among the sons of Ithamar."'),
('1 Chronicles', 24, 'teens', 4, 'What was the name of the first course of priests listed?', 'Jehoiarib', 'Jedaiah', 'Harim', 'Seorim', 'a', '1 Chronicles 24:7 — "Now the first lot came forth to Jehoiarib, the second to Jedaiah."'),
('1 Chronicles', 24, 'teens', 5, 'What is the significance of the phrase "governors of the sanctuary" as used in this chapter?', 'It refers to the heads of the priestly divisions who had oversight over the most holy things and the house of God', 'It refers to the gatekeepers who guarded the temple doors', 'It refers to the Levitical scribes who kept the priestly records', 'It refers to the soldiers assigned to protect the temple complex', 'a', '1 Chronicles 24:5 — "For the governors of the sanctuary, and governors of the house of God, were of the sons of Eleazar, and of the sons of Ithamar" — indicating priestly authority over the sanctuary and temple administration.'),
-- Adults
('1 Chronicles', 24, 'adults', 1, 'What phrase justifies the use of lot-casting for the priestly order, emphasizing divine impartiality?', 'One sort with another, for there were princes of the sanctuary and princes of God both of the sons of Eleazar and Ithamar', 'God alone knows the heart of every man, therefore the lot is just', 'The lot is cast into the lap but the whole disposing thereof is of the LORD', 'As it is written in the law of Moses, so shall it be done by lot', 'a', '1 Chronicles 24:5 — "Thus were they divided by lot, one sort with another; for the governors of the sanctuary, and governors of the house of God, were of the sons of Eleazar, and of the sons of Ithamar."'),
('1 Chronicles', 24, 'adults', 2, 'What is the name of the twenty-fourth and final priestly course?', 'Maaziah', 'Delaiah', 'Gamul', 'Jachin', 'a', '1 Chronicles 24:18 — "The four and twentieth to Maaziah."'),
('1 Chronicles', 24, 'adults', 3, 'How does the chapter handle the remaining Levites who were not priests, and by what method were they also ordered?', 'They were also divided by lot in the presence of David and the princes, brethren against brethren', 'They chose their own assignments according to family tradition', 'They served in order of birth rank within each Levitical clan', 'David personally assigned each non-priestly Levite to a specific task', 'a', '1 Chronicles 24:31 — "These likewise cast lots over against their brethren the sons of Aaron in the presence of David the king, and Zadok, and Ahimelech."'),
('1 Chronicles', 24, 'adults', 4, 'Who was the scribe who recorded the lots drawn for the priestly courses?', 'Shemaiah the son of Nethaneel the Levite', 'Ezra the son of Seraiah the priest', 'Jonathan the son of Asahel', 'Ahijah the son of Shiloh', 'a', '1 Chronicles 24:6 — "And Shemaiah the son of Nethaneel the scribe, one of the Levites, wrote them before the king."'),
('1 Chronicles', 24, 'adults', 5, 'What was the lot-drawing process for the Kohathites and Merarites, and who witnessed it?', 'Their lots were cast in the presence of David, Zadok, Ahimelech, and the chief fathers of the priests and Levites', 'Only the heads of each family witnessed and confirmed the results', 'Zadok and Abiathar cast the lots privately and reported to David', 'The lots were cast at the tabernacle in Gibeon by the Levitical priests', 'a', '1 Chronicles 24:31 — "These likewise cast lots over against their brethren the sons of Aaron in the presence of David the king, and Zadok, and Ahimelech, and the chief of the fathers of the priests and Levites."'),
('1 Chronicles', 24, 'adults', 6, 'What happened to Eleazar''s sons Nadab and Abihu that is referenced here, and where is their story recorded?', 'They offered strange fire before the LORD and were devoured, recorded in Leviticus 10', 'They rebelled against Moses and were swallowed by the earth, recorded in Numbers 16', 'They were killed in the battle against the Midianites, recorded in Numbers 31', 'They died of the plague for looking into the ark, recorded in 1 Samuel 6', 'a', '1 Chronicles 24:2 — "But Nadab and Abihu died before their father" — this refers to Leviticus 10:1-2 where they offered unauthorized fire before the LORD and were consumed.'),
('1 Chronicles', 24, 'adults', 7, 'How does the 24-course priestly system described here connect to the New Testament?', 'Zacharias the father of John the Baptist served in the course of Abijah, the eighth course, when the angel appeared to him', 'Jesus was born during the course of Jakim, fulfilling the priestly calendar', 'Paul references the 24 courses in his letter to the Hebrews as types of Christ', 'The book of Revelation mentions 24 elders corresponding to the 24 priestly courses', 'a', '1 Chronicles 24:10 — The eighth course was Abijah; Luke 1:5 says "There was in the days of Herod...a certain priest named Zacharias, of the course of Abia" — linking the birth of John the Baptist to this organizational system.'),
('1 Chronicles', 24, 'adults', 8, 'What is the theological importance of organizing temple worship by lot rather than by human appointment?', 'It removed favoritism and human bias, expressing that God''s service is impartial and that all faithful priests have equal standing before him', 'It ensured the most qualified priests always served at the most important feasts', 'It prevented Zadok''s family from monopolizing the highest priestly roles', 'It fulfilled a specific prophetic requirement given to Moses in the wilderness', 'a', '1 Chronicles 24:5 — The lot-casting system ensured equity: "one sort with another" — no priestly family could claim preference, reflecting that service before God is based on consecration, not human status.');

-- ═══ 1 Chronicles Chapter 25 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 25, 'kids', 1, 'What were the temple musicians doing with their instruments that was described as prophesying?', 'Prophesying with harps, psalteries, and cymbals', 'Singing hymns and reading from scrolls', 'Playing trumpets to announce the sacrifices', 'Dancing before the ark with instruments', 'a', '1 Chronicles 25:1 — "David and the captains of the host separated to the service of the sons of Asaph, and of Heman, and of Jeduthun, who should prophesy with harps, with psalteries, and with cymbals."'),
('1 Chronicles', 25, 'kids', 2, 'How many courses of musicians did David organize for the temple?', 'Twenty and four courses', 'Twelve courses', 'Seven courses', 'Forty courses', 'a', '1 Chronicles 25:31 — "The four and twentieth to Romamtiezer" — the divisions numbered twenty-four in total.'),
('1 Chronicles', 25, 'kids', 3, 'What were the three families of temple musicians?', 'Asaph, Heman, and Jeduthun', 'Aaron, Moses, and Miriam', 'Gershon, Kohath, and Merari', 'Nadab, Abihu, and Eleazar', 'a', '1 Chronicles 25:1 — "David and the captains of the host separated to the service of the sons of Asaph, and of Heman, and of Jeduthun."'),
-- Teens
('1 Chronicles', 25, 'teens', 1, 'How many sons did Heman have, and what title is given to him?', 'Fourteen sons; the king''s seer in the words of God', 'Seven sons; the chief musician of Israel', 'Twenty-four sons; the head of all the Levitical singers', 'Twelve sons; the chief of the sons of Kohath', 'a', '1 Chronicles 25:5-6 — "All these were the sons of Heman the king''s seer in the words of God...And God gave to Heman fourteen sons and three daughters."'),
('1 Chronicles', 25, 'teens', 2, 'What was the total number of all who were instructed and cunning in song for the LORD?', 'Two hundred fourscore and eight', 'One hundred and twenty', 'Three hundred and sixty', 'Two hundred and forty', 'a', '1 Chronicles 25:7 — "So the number of them, with their brethren that were instructed in the songs of the LORD, even all that were cunning, was two hundred fourscore and eight."'),
('1 Chronicles', 25, 'teens', 3, 'How were the 24 lots for the musical courses cast — did the masters go first or was it equal?', 'They cast lots ward against ward, both the small and the great, the teacher as well as the scholar', 'The eldest musician in each family received the first lots', 'David personally chose the order based on skill', 'Asaph''s sons always received the first lots as the chief family', 'a', '1 Chronicles 25:8 — "And they cast lots, ward against ward, as well the small as the great, the teacher as the scholar."'),
('1 Chronicles', 25, 'teens', 4, 'How many people were in each of the 24 musical courses?', 'Twelve', 'Twenty-four', 'Seven', 'Four', 'a', '1 Chronicles 25:9-31 — Each course is listed with twelve people (the family head plus associated musicians), giving 24 × 12 = 288, matching verse 7''s total of 288 instructed musicians.'),
('1 Chronicles', 25, 'teens', 5, 'What sons did Asaph have who served in the musical courses?', 'Zaccur, Joseph, Nethaniah, and Asarelah — four sons', 'Mattaniah, Uzziel, Shebuel, and Jerimoth — four sons', 'Hananiah, Hanani, Eliathah, and Giddalti — four sons', 'Mahazioth, Romamtiezer, Joshbekashah, and Mallothi — four sons', 'a', '1 Chronicles 25:2 — "Of the sons of Asaph; Zaccur, and Joseph, and Nethaniah, and Asarelah, the sons of Asaph under the hands of Asaph, which prophesied according to the order of the king."'),
-- Adults
('1 Chronicles', 25, 'adults', 1, 'What phrase is used to describe Heman''s sons that shows God''s direct blessing on him?', 'God gave to Heman fourteen sons and three daughters to lift up the horn', 'The LORD blessed Heman with more children than any man in Israel', 'Heman''s household was multiplied according to the faithfulness of his service', 'God opened the womb of Heman''s wife for his diligent praise', 'a', '1 Chronicles 25:5 — "All these were the sons of Heman the king''s seer in the words of God, to lift up the horn. And God gave to Heman fourteen sons and three daughters."'),
('1 Chronicles', 25, 'adults', 2, 'What do the names of Heman''s fourteen sons collectively suggest when read as a sequence?', 'Their names form a Hebrew prayer or declaration of praise to God', 'Their names correspond to the twenty-four musical modes of Israel', 'Their names record the history of the exodus in symbolic form', 'Their names encode the books of the Psalms attributed to Heman', 'a', '1 Chronicles 25:4 — Scholars note that Heman''s sons'' names (Hananiah, Hanani, Eliathah, Giddalti, Romamtiezer, Joshbekashah, Mallothi, Hothir, Mahazioth) form a Hebrew prayer of petition and praise when read sequentially.'),
('1 Chronicles', 25, 'adults', 3, 'Under whose hands did the musicians serve, and who directed them?', 'Under the hands of their father for song in the house of the LORD, with cymbals, psalteries, and harps, for the service of the house of God, according to the king''s order', 'Under the high priest Zadok who directed all temple worship', 'Under the prophets Nathan and Gad who composed the liturgy', 'Under the Levitical overseers appointed by Moses'' original ordinance', 'a', '1 Chronicles 25:6 — "All these were under the hands of their father for song in the house of the LORD, with cymbals, psalteries, and harps, for the service of the house of God, according to the king''s order to Asaph, Jeduthun, and Heman."'),
('1 Chronicles', 25, 'adults', 4, 'What specific number of sons and daughters did Heman have, and what does this suggest about his honored status?', 'Fourteen sons and three daughters — an unusually large family suggesting exceptional divine blessing and honor', 'Eight sons and four daughters — an average family for a temple leader', 'Twelve sons and twelve daughters — one for each tribe of Israel', 'Seven sons and seven daughters — representing completeness and perfection', 'a', '1 Chronicles 25:5 — "God gave to Heman fourteen sons and three daughters" — this remarkable family size is explicitly attributed to God''s gift and connected to Heman''s role as "the king''s seer."'),
('1 Chronicles', 25, 'adults', 5, 'What phrase connects the temple musical ministry to the prophetic tradition?', 'The sons of Asaph prophesied according to the order of the king; Jeduthun prophesied with a harp giving thanks and praising the LORD', 'The musicians spoke the oracles of God through their instruments', 'Music was a form of priestly intercession equivalent to burnt offerings', 'The songs of the Levites were counted as binding prophecy for Israel', 'a', '1 Chronicles 25:1-3 — Asaph''s sons "prophesied according to the order of the king"; Jeduthun''s sons "prophesied with a harp, to give thanks and to praise the LORD" — music was inseparably linked to prophetic ministry.'),
('1 Chronicles', 25, 'adults', 6, 'What is the first lot that came forth, establishing who led the first musical course?', 'Joseph of the sons of Asaph', 'Gedaliah of the sons of Jeduthun', 'Mattaniah of the sons of Heman', 'Zaccur of the sons of Asaph', 'a', '1 Chronicles 25:9 — "Now the first lot came forth for Asaph to Joseph."'),
('1 Chronicles', 25, 'adults', 7, 'How many sons did Jeduthun have who served in the musical ministry?', 'Six sons', 'Four sons', 'Eight sons', 'Twelve sons', 'a', '1 Chronicles 25:3 — "Of Jeduthun: the sons of Jeduthun; Gedaliah, and Zeri, and Jeshaiah, Hashabiah, and Mattithiah, six, under the hands of their father Jeduthun, who prophesied with a harp."'),
('1 Chronicles', 25, 'adults', 8, 'What does the organization of temple musicians into 24 rotating courses reveal about David''s theology of worship?', 'That worship was to be continuous, structured, and Spirit-led, blending institutional regularity with prophetic spontaneity', 'That music was merely ceremonial and had no spiritual significance', 'That only the most gifted musicians could enter God''s presence through song', 'That the number 24 had a mystical meaning related to the hours of the day', 'a', '1 Chronicles 25:1 — The combination of "separated to the service" (institutional structure) and "prophesy with harps" (Spirit-led expression) shows that David designed temple worship to be both ordered and Spirit-infused.');

-- ═══ 1 Chronicles Chapter 26 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 26, 'kids', 1, 'What job did the gatekeepers do at the temple?', 'They guarded the gates and doors of the house of the LORD', 'They collected offerings from the people', 'They led worship with musical instruments', 'They served food at the temple feasts', 'a', '1 Chronicles 26:12 — "Among these were the divisions of the porters, even among the chief men, having wards one against another, to minister in the house of the LORD."'),
('1 Chronicles', 26, 'kids', 2, 'What were kept in the treasuries that the Levites guarded?', 'Dedicated things and the spoils won in battles', 'The robes and garments of the priests', 'The food offerings and grain for the feasts', 'The scrolls and books of the law', 'a', '1 Chronicles 26:26-27 — "Which Shelomith and his brethren were over all the treasures of the dedicated things, which David the king...had dedicated...out of the spoils won in battles."'),
('1 Chronicles', 26, 'kids', 3, 'On how many sides of the temple were there gates that the gatekeepers guarded?', 'On every side — south, north, east, and west', 'Only on the east and west sides', 'Only the main entrance on the south', 'On two sides, east and north', 'a', '1 Chronicles 26:13-16 — Lots were cast for gates on every side: the east gate, the north gate, the south gate, the west gate with the Shallecheth gate on the causeway.'),
-- Teens
('1 Chronicles', 26, 'teens', 1, 'Who was the famous ancestor of Obed-edom whose family provided many gatekeepers?', 'Obed-edom himself, whom God had blessed when the ark rested in his house', 'Korah the son of Levi whose descendants were forgiven', 'Phinehas the son of Eleazar who stopped the plague', 'Zeruiah the sister of David whose sons were mighty warriors', 'a', '1 Chronicles 26:4-5 — "Moreover the sons of Obed-edom were, Shemaiah the firstborn...for God blessed him." This refers to the same Obed-edom in whose house the ark rested (1 Chronicles 13:14).'),
('1 Chronicles', 26, 'teens', 2, 'How many gatekeepers were assigned to the south gate and the storehouse?', 'Four toward the south and two at the storehouse', 'Six toward the south and four at the storehouse', 'Two toward the south and two at the storehouse', 'Eight toward the south and four at the storehouse', 'a', '1 Chronicles 26:15 — "To Obed-edom southward; and to his sons the house of Asuppim." The divisions were assigned to specific positions around the temple complex.'),
('1 Chronicles', 26, 'teens', 3, 'What administrative roles did some Levites serve outside the temple itself?', 'Officers and judges over Israel for the outward business, to decide causes and legal matters', 'Tax collectors and census-takers for the king', 'Military commanders over the royal guard', 'Scribes who copied the law for all the cities', 'a', '1 Chronicles 26:29 — "Of the Izharites, Chenaniah and his sons were for the outward business over Israel, for officers and judges."'),
('1 Chronicles', 26, 'teens', 4, 'What was the name of Obed-edom''s firstborn son, and how many able men did Obed-edom''s household provide?', 'Shemaiah was the firstborn; sixty-two able men came from Obed-edom''s household', 'Joah was the firstborn; forty able men came from his household', 'Zabad was the firstborn; thirty able men came from his household', 'Elzabad was the firstborn; twelve able men came from his household', 'a', '1 Chronicles 26:4-8 — "Moreover the sons of Obed-edom were, Shemaiah the firstborn...all the sons of Obed-edom were threescore and two."'),
('1 Chronicles', 26, 'teens', 5, 'Who had oversight over the treasures of the dedicated things that came from the victories of Samuel, Saul, Abner, and Joab?', 'Shelomith and his brethren', 'Ahiah and the sons of Jeduthun', 'Hosah and his relatives from Merari', 'Meshelemiah and the sons of Asaph', 'a', '1 Chronicles 26:26-28 — "Which Shelomith and his brethren were over all the treasures of the dedicated things, which David the king...Samuel the seer...Saul...Abner...Joab...had dedicated."'),
-- Adults
('1 Chronicles', 26, 'adults', 1, 'What family of Levites from Korah provided the chief gatekeepers according to this chapter?', 'Meshelemiah the son of Kore, of the sons of Asaph', 'Obed-edom the son of Jeduthun, of the sons of Merari', 'Hosah the son of Jediah, of the sons of Merari', 'Zechariah the firstborn of Meshelemiah', 'a', '1 Chronicles 26:1 — "Concerning the divisions of the porters: Of the Korhites was Meshelemiah the son of Kore, of the sons of Asaph."'),
('1 Chronicles', 26, 'adults', 2, 'How were the gate assignments determined among the gatekeepers?', 'By lot, according to the house of their fathers, great as well as the small', 'By rank of seniority within each Levitical family', 'By the king''s personal appointment of the most trusted men', 'By a competition of skill and strength among the gatekeepers', 'a', '1 Chronicles 26:13 — "And they cast lots, as well the small as the great, according to the house of their fathers, for every gate."'),
('1 Chronicles', 26, 'adults', 3, 'What specific gate received the lot for Shuppim and Hosah on the west side?', 'The gate Shallecheth by the causeway going up', 'The gate of the north side', 'The gate of the east side', 'The Parbar gate on the west', 'a', '1 Chronicles 26:16 — "To Shuppim and Hosah the lot came forth westward, with the gate Shallecheth, by the causeway of the going up, ward against ward."'),
('1 Chronicles', 26, 'adults', 4, 'How many gatekeepers were assigned daily, and how were the Parbar positions staffed?', 'Four each day for the four gates; six at the causeway, four at the Parbar', 'Three each day; two at each gate of the compass', 'Eight each day; twelve at the Shallecheth gate', 'Two each day; twelve total for all positions combined', 'a', '1 Chronicles 26:17-18 — "Eastward were six Levites, northward four a day, southward four a day, and toward Asuppim two and two. At Parbar westward, four at the causeway, and two at Parbar."'),
('1 Chronicles', 26, 'adults', 5, 'What is said about Zechariah the son of Meshelemiah that distinguishes him among the gatekeepers?', 'He was a wise counsellor who was given the lot for the north gate', 'He was the strongest man and guarded the east gate alone', 'He was the firstborn son and became chief gatekeeper', 'He was appointed treasurer because of his honesty', 'a', '1 Chronicles 26:14 — "And the lot eastward fell to Shelemiah. Then for Zechariah his son, a wise counsellor, they cast lots; and his lot came out northward."'),
('1 Chronicles', 26, 'adults', 6, 'Who was appointed over the treasures of the house of God from the Amramites?', 'Shebuel the son of Gershom, the son of Moses', 'Phinehas the son of Eleazar who was the ruler', 'Ahijah was over the treasures of the dedicated things', 'Meshelemiah the son of Kore kept the treasure rooms', 'a', '1 Chronicles 26:24 — "And Shebuel the son of Gershom, the son of Moses, was ruler of the treasures."'),
('1 Chronicles', 26, 'adults', 7, 'Which territories were mentioned for the Levitical officers who served in the outward business?', 'Beyond Jordan westward, in all business of the LORD, and in the service of the king', 'Only in Jerusalem and the cities of Judah', 'In the northern territories of Ephraim and Manasseh', 'In the wilderness regions where the tabernacle had formerly stood', 'a', '1 Chronicles 26:30 — "And of the Hebronites, Hashabiah and his brethren, men of valour, a thousand and seven hundred, were officers among them of Israel on this side Jordan westward in all the business of the LORD, and in the service of the king."'),
('1 Chronicles', 26, 'adults', 8, 'What does the comprehensive organization of gatekeepers, treasurers, and judges reveal about David''s vision for the temple as an institution?', 'That the temple was to be a complete center of national life — spiritual, administrative, financial, and judicial — not merely a place of sacrifice', 'That David wanted to give the Levites maximum employment opportunities', 'That the temple treasury was the main source of government revenue', 'That gatekeepers were the most important class of temple servants', 'a', '1 Chronicles 26:29-32 — The extension of Levitical oversight to "outward business," "officers and judges," and territory "beyond Jordan" shows David designed the temple community to serve as the administrative heart of the whole nation.');

-- ═══ 1 Chronicles Chapter 27 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 27, 'kids', 1, 'How many military divisions did David organize, one for each month of the year?', 'Twelve divisions', 'Seven divisions', 'Twenty-four divisions', 'Four divisions', 'a', '1 Chronicles 27:1 — "Now the children of Israel after their number, to wit, the chief fathers and captains of thousands and hundreds, and their officers that served the king in any matter of the courses, which came in and went out month by month throughout all the months of the year."'),
('1 Chronicles', 27, 'kids', 2, 'How many men were in each monthly military division?', 'Twenty and four thousand', 'Ten thousand', 'Forty thousand', 'Five thousand', 'a', '1 Chronicles 27:1-2 — Each course had "four and twenty thousand" as seen in verse 2: "Over the first course for the first month was Jashobeam...and in his course were four and twenty thousand."'),
('1 Chronicles', 27, 'kids', 3, 'Who was the prince over the tribe of Judah?', 'Elihu, one of the brethren of David', 'Joab the son of Zeruiah', 'Ahinoam the son of Maaseiah', 'Hashabiah of the tribe of Levi', 'a', '1 Chronicles 27:18 — "Of Judah, Elihu, one of the brethren of David."'),
-- Teens
('1 Chronicles', 27, 'teens', 1, 'Who was over the first division for the first month, and what heroic deed was he known for?', 'Jashobeam the son of Zabdiel; he slew three hundred in a single encounter', 'Dodai the Ahohite; he was one of the thirty mighty men', 'Benaiah the son of Jehoiada; he slew two lion-like men of Moab', 'Shammoth the Harorite; he defended Israel at Bethlehem', 'a', '1 Chronicles 27:2 — "Over the first course for the first month was Jashobeam the son of Zabdiel: and in his course were four and twenty thousand." He is identified with the mighty man of 1 Chronicles 11:11.'),
('1 Chronicles', 27, 'teens', 2, 'Who was commander of the third division, and what month did his course serve?', 'Benaiah the son of Jehoiada, a chief priest, over the third month', 'Shammoth the Harorite for the third month', 'Asahel the brother of Joab for the third month', 'Ikkesh the Tekoite for the third month', 'a', '1 Chronicles 27:5 — "The third captain of the host for the third month was Benaiah the son of Jehoiada, a chief priest: and in his course were four and twenty thousand."'),
('1 Chronicles', 27, 'teens', 3, 'Why did David not number those under twenty years old, according to this chapter?', 'Because the LORD had said he would increase Israel like the stars of heaven', 'Because they were exempt from military service by Mosaic law', 'Because there were already too many men in the monthly divisions', 'Because their fathers paid a ransom for them at birth', 'a', '1 Chronicles 27:23 — "But David took not the number of them from twenty years old and under: because the LORD had said he would increase Israel like to the stars of the heavens."'),
('1 Chronicles', 27, 'teens', 4, 'Who were the two men over David''s herds in Sharon and in the valleys?', 'Shitrai the Sharonite was over the flocks in Sharon; Shaphat the son of Adlai over the herds in the valleys', 'Jaziz the Hagarite and Obil the Ishmaelite', 'Joah the son of Zimmah and Eden the son of Joah', 'Bani the Gadite and Mibhar the son of Haggeri', 'a', '1 Chronicles 27:29 — "And over the herds that fed in Sharon was Shitrai the Sharonite: and over the herds that were in the valleys was Shaphat the son of Adlai."'),
('1 Chronicles', 27, 'teens', 5, 'Who was Ahithophel, and who replaced him as David''s counsellor?', 'Ahithophel was the king''s counsellor; Jehoiada and Abiathar were after him, and Joab commanded the king''s army', 'Ahithophel was the royal scribe; Shemaiah replaced him', 'Ahithophel was the chief of the guard; Benaiah replaced him', 'Ahithophel was commander of the army; Joab succeeded him', 'a', '1 Chronicles 27:33-34 — "And Ahithophel was the king''s counsellor: and Hushai the Archite was the king''s companion: And after Ahithophel was Jehoiada the son of Benaiah, and Abiathar."'),
-- Adults
('1 Chronicles', 27, 'adults', 1, 'What is the total size of the standing army implied by twelve monthly divisions of twenty-four thousand each?', 'Two hundred eighty-eight thousand men on rotation, with twenty-four thousand available each month', 'One hundred forty-four thousand permanently armed soldiers', 'Twelve thousand men available to the king at all times', 'Four hundred thousand men in total including reserves', 'a', '1 Chronicles 27:1-15 — Twelve courses each of 24,000 = 288,000 total on annual rotation; at any given month, 24,000 were in active service while the rest returned to civilian life.'),
('1 Chronicles', 27, 'adults', 2, 'Who was over the king''s vineyards, and who was over the wine cellars?', 'Shimei the Ramathite was over the vineyards; Zabdi the Shiphmite was over the increase of the vineyards for the wine cellars', 'Joah of the tribe of Benjamin and Mattaniah the Levite', 'Ezri the son of Chelub and Ahijah the Pelonite', 'Baal-hanan the Gederite and Joash the storekeeper', 'a', '1 Chronicles 27:27 — "And over the vineyards was Shimei the Ramathite: over the increase of the vineyards for the wine cellars was Zabdi the Shiphmite."'),
('1 Chronicles', 27, 'adults', 3, 'Who was over the olive trees and the sycamore trees in the lowlands?', 'Baal-hanan the Gederite', 'Shaphat the son of Adlai', 'Obil the Ishmaelite', 'Azmaveth the son of Adiel', 'a', '1 Chronicles 27:28 — "And over the olive trees and the sycomore trees that were in the low plains was Baal-hanan the Gederite."'),
('1 Chronicles', 27, 'adults', 4, 'What was the reason that the wrath of God fell on Israel during David''s census, referenced at the end of this chapter?', 'The numbers were not finished because wrath fell on Israel, and the numbers from twenty and below were not put in the account', 'David failed to consult the Urim and Thummim before ordering the count', 'Joab conducted the census without fasting and prayer', 'The census violated a specific prohibition in the law of Moses', 'a', '1 Chronicles 27:24 — "Joab the son of Zeruiah began to number, but he finished not, because there fell wrath for it against Israel."'),
('1 Chronicles', 27, 'adults', 5, 'Who was over the storehouses in the field, in the cities, in the villages, and in the castles?', 'Azmaveth the son of Adiel was over the king''s treasures; Jonathan the son of Uzziah over the storehouses in the fields', 'Obil the Ishmaelite over the camels; Jaziz the Hagarite over the flocks', 'Ezri the son of Chelub over the farming laborers', 'Benaiah the son of Jehoiada over the king''s personal treasury', 'a', '1 Chronicles 27:25 — "And over the king''s treasures was Azmaveth the son of Adiel: and over the storehouses in the fields, in the cities, and in the villages, and in the castles, was Jehonathan the son of Uzziah."'),
('1 Chronicles', 27, 'adults', 6, 'How many tribes of Israel had princes listed in chapter 27, and which tribe was notably absent?', 'Eleven tribes were listed with princes; the tribe of Gad was absent from the listed princes', 'All twelve tribes had princes equally listed', 'Only seven tribes had designated princes', 'Ten tribes were listed; Dan and Naphtali were absent', 'a', '1 Chronicles 27:16-22 — The tribes listed include Reuben, Simeon, Levi, Aaron, Judah, Issachar, Zebulun, Naphtali, Ephraim, half-Manasseh, Benjamin, Dan; Gad and Asher are not mentioned separately.'),
('1 Chronicles', 27, 'adults', 7, 'Who was noted as David''s personal advisor who was also called "the king''s companion"?', 'Hushai the Archite', 'Jonathan the son of Shage', 'Ira the Ithrite', 'Naharai the Berothite', 'a', '1 Chronicles 27:33 — "And Ahithophel was the king''s counsellor: and Hushai the Archite was the king''s companion."'),
('1 Chronicles', 27, 'adults', 8, 'What does the comprehensive administrative structure in chapter 27 reveal about the nature of David''s monarchy?', 'It was a highly organized state where spiritual, military, agricultural, and civil administration were all brought under divinely ordered structure', 'It was primarily a military government that secondarily managed civilian affairs', 'David''s administration was chaotic and this organization was added by later scribes', 'The administration was centralized only in Jerusalem with no outreach to the tribes', 'a', '1 Chronicles 27:1-34 — The chapter covers military (vv. 1-15), tribal leaders (vv. 16-24), agricultural managers (vv. 25-31), and royal advisors (vv. 32-34) — showing a fully integrated national administration undergirded by God''s ordering principle.');

-- ═══ 1 Chronicles Chapter 28 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 28, 'kids', 1, 'What did David give Solomon for building the temple?', 'The pattern of all the temple, its courts, chambers, and treasuries', 'A bag of gold and silver coins', 'A list of workers to help him build', 'The keys to the city of Jerusalem', 'a', '1 Chronicles 28:11-12 — "Then David gave to Solomon his son the pattern of the porch, and of the houses thereof...And the pattern of all that he had by the spirit."'),
('1 Chronicles', 28, 'kids', 2, 'What did God say about Solomon that made him chosen to build the temple?', 'I have chosen him to be my son, and I will be his father', 'He is the wisest man in all the earth', 'He has never sinned before me', 'He is the strongest of all David''s sons', 'a', '1 Chronicles 28:6 — "And he said unto me, Solomon thy son, he shall build my house and my courts: for I have chosen him to be my son, and I will be his father."'),
('1 Chronicles', 28, 'kids', 3, 'What famous words did David tell Solomon to be strong and not to fear?', 'Be strong and courageous and do it; fear not, nor be dismayed, for the LORD God will be with thee', 'The LORD fights for you, so be silent and trust him', 'Do not lean on your own understanding but trust the LORD', 'The battle is the LORD''s and he will deliver the enemy into your hand', 'a', '1 Chronicles 28:20 — "Be strong and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee; he will not fail thee, nor forsake thee."'),
-- Teens
('1 Chronicles', 28, 'teens', 1, 'Why did God say David could not build the temple himself?', 'Because David had shed much blood upon the earth in God''s sight', 'Because David was too old and weak to oversee the construction', 'Because God had chosen Jerusalem only after David''s death', 'Because the law required a priest to dedicate the temple', 'a', '1 Chronicles 28:3 — "But God said unto me, Thou shalt not build an house for my name, because thou hast been a man of war, and hast shed blood."'),
('1 Chronicles', 28, 'teens', 2, 'How did David say he received the temple blueprint — by his own wisdom or another way?', 'He had it in writing from the hand of the LORD upon him, even all the works of the pattern', 'He received it in a vision during the night', 'He designed it himself with the help of skilled craftsmen from Tyre', 'He copied it from the pattern of the tabernacle given to Moses', 'a', '1 Chronicles 28:19 — "All this, said David, the LORD made me understand in writing by his hand upon me, even all the works of this pattern."'),
('1 Chronicles', 28, 'teens', 3, 'What warning did David give Solomon about keeping the commandments?', 'If thou seek him, he will be found of thee; but if thou forsake him, he will cast thee off forever', 'The LORD will bless you if you obey but send enemies if you stray', 'Guard the law with your life, for it is more precious than gold', 'Do not add to or take away from the commandments of Moses', 'a', '1 Chronicles 28:9 — "If thou seek him, he will be found of thee; but if thou forsake him, he will cast thee off for ever."'),
('1 Chronicles', 28, 'teens', 4, 'What does David say God knows about people that should motivate Solomon to serve with a perfect heart?', 'The LORD searcheth all hearts and understandeth all the imaginations of the thoughts', 'The LORD counts the hairs of every man''s head and knows all their ways', 'God watches from heaven and sees every deed done in secret', 'The LORD reads men''s lips and knows every prayer before it is spoken', 'a', '1 Chronicles 28:9 — "For the LORD searcheth all hearts, and understandeth all the imaginations of the thoughts."'),
('1 Chronicles', 28, 'teens', 5, 'What specific details were included in the pattern David gave Solomon for the golden furnishings?', 'The pattern for the chariot of the cherubims, the candlesticks, the tables of shewbread, and all the vessels of gold and silver', 'Only the measurements of the walls and the height of the pillars', 'The names of all the craftsmen who would do the work', 'A list of the sacrifices required for the dedication ceremony', 'a', '1 Chronicles 28:11-18 — David gave patterns for the porch, houses, treasuries, chambers, parlours, place of the mercy seat, the candlesticks, the tables, the fleshhooks, the chariot of the cherubims.'),
-- Adults
('1 Chronicles', 28, 'adults', 1, 'To what assembly did David gather all Israel for this final public charge?', 'All the princes of Israel, the princes of the tribes, the captains of the companies, the stewards, the mighty men, and all the valiant men', 'Only the seventy elders of Israel in Jerusalem', 'The priests, Levites, and prophets only', 'The tribal heads and the judges of the land', 'a', '1 Chronicles 28:1 — "And David assembled all the princes of Israel, the princes of the tribes, and the captains of the companies that ministered to the king by course, and the captains over the thousands, and captains over the hundreds, and the stewards over all the substance and possession of the king, and of his sons, with the officers, and with the mighty men, and with all the valiant men, unto Jerusalem."'),
('1 Chronicles', 28, 'adults', 2, 'What specific theological truth did David declare about God''s choice of Judah, Jesse''s house, and David personally?', 'The LORD chose Judah to be the ruler; out of the house of Judah he chose David''s father''s house; among the sons of Jesse he liked David to make him king over all Israel', 'God chose Israel because they were the smallest of nations', 'The LORD chose David because he was more righteous than all his brothers', 'God selected Judah by lot and David by the counsel of the prophets', 'a', '1 Chronicles 28:4 — "Howbeit the LORD God of Israel chose me before all the house of my father to be king over Israel for ever: for he hath chosen Judah to be the ruler; and of the house of Judah, the house of my father; and among the sons of my father he liked me to make me king over all Israel."'),
('1 Chronicles', 28, 'adults', 3, 'What specific weight of gold did David give for the golden candlesticks by pattern?', 'By weight for every candlestick, and for the lamps thereof, of gold by weight for every lamp', 'One hundred talents of gold per candlestick', 'Fifty shekels of gold for the lampstand and twenty for the lamps', 'David did not specify weight but only the design', 'a', '1 Chronicles 28:15 — "Even the weight for the candlesticks of gold, and for their lamps of gold, by weight for every candlestick, and for the lamps thereof: and for the candlesticks of silver by weight, both for the candlestick, and also for the lamps thereof, according to the use of every candlestick."'),
('1 Chronicles', 28, 'adults', 4, 'What Hebrew phrase describes how David received the temple blueprint, and what does it imply about inspiration?', '"The LORD made me understand in writing by his hand upon me" — implying direct divine inscription or revelation of the architectural plan', 'David studied the tabernacle dimensions and extrapolated the temple design', 'The plans were given through the prophet Nathan in a written scroll', 'David hired Phoenician architects and God approved their design', 'a', '1 Chronicles 28:19 — "All this, said David, the LORD made me understand in writing by his hand upon me, even all the works of this pattern" — the phrase "by his hand upon me" suggests direct prophetic inspiration.'),
('1 Chronicles', 28, 'adults', 5, 'What did David say about Solomon''s character in verse 9 as a charge to him about serving God?', 'To serve God with a perfect heart and a willing mind', 'To pray three times a day and study the law night and day', 'To lead Israel in righteousness and not follow the customs of the nations', 'To love the LORD with all his heart and build the temple without delay', 'a', '1 Chronicles 28:9 — "And thou, Solomon my son, know thou the God of thy father, and serve him with a perfect heart and with a willing mind."'),
('1 Chronicles', 28, 'adults', 6, 'What amount of gold did David designate for the altar of incense and the chariot of the cherubims?', 'Gold by weight for the altar of incense; six hundred talents of refined gold for the chariot of the cherubims', 'One hundred talents for the incense altar; two hundred for the cherubims'' chariot', 'Fifty shekels for the incense altar; one talent for each cherubim', 'David specified design only and left the weight to the craftsmen''s discretion', 'a', '1 Chronicles 28:17-18 — "Also pure gold for the fleshhooks, and the bowls, and the cups: and for the golden basons he gave gold by weight for every bason...and gold for the pattern of the chariot of the cherubims."'),
('1 Chronicles', 28, 'adults', 7, 'What famous promise did David echo from Deuteronomy in his encouragement to Solomon?', 'The LORD thy God is with thee; he will not fail thee nor forsake thee', 'Be strong and very courageous; do not turn to the right or the left', 'I will never leave thee nor forsake thee, saith the LORD of hosts', 'He shall give his angels charge over thee to keep thee in all thy ways', 'a', '1 Chronicles 28:20 — "He will not fail thee, nor forsake thee" — echoing Deuteronomy 31:6 and 31:8 where Moses used the same words when commissioning Joshua for the conquest.'),
('1 Chronicles', 28, 'adults', 8, 'What is the significance of David''s public assembly and charge in chapter 28 in terms of dynastic and theological legacy?', 'It formally transferred divine mandate, architectural revelation, and covenant responsibility from David to Solomon publicly before all Israel, ensuring institutional continuity of the temple project', 'It was primarily a political ceremony to prevent Adonijah from challenging Solomon again', 'David wanted to ensure the craftsmen were properly paid before he died', 'The assembly was required by Mosaic law before any royal succession', 'a', '1 Chronicles 28:1-20 — The assembly gathered "all Israel" as witnesses; David revealed the divine origin of the plans, gave the written pattern, and repeated God''s covenant promises — making Solomon''s task not merely political but covenantally binding before the whole nation.');

-- ═══ 1 Chronicles Chapter 29 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Chronicles', 29, 'kids', 1, 'What did David and all the people bring as offerings for the temple?', 'Gold, silver, brass, iron, and precious stones willingly given', 'Sheep and oxen for burnt offerings', 'Bread and wine for the feast of dedication', 'Logs of cedar and stone from the quarries', 'a', '1 Chronicles 29:6-7 — "Then the chief of the fathers and princes of the tribes of Israel, and the captains of thousands and of hundreds...offered willingly...of gold five thousand talents and ten thousand drams, and of silver ten thousand talents."'),
('1 Chronicles', 29, 'kids', 2, 'What famous words did David pray about all the offerings, saying everything belongs to God?', 'All things come of thee, and of thine own have we given thee', 'We give back to you what you first gave to us', 'Blessed be the LORD who provides for all our needs', 'All our gold and silver belongs to the house of the LORD', 'a', '1 Chronicles 29:14 — "But who am I, and what is my people, that we should be able to offer so willingly after this sort? for all things come of thee, and of thine own have we given thee."'),
('1 Chronicles', 29, 'kids', 3, 'What happened to Solomon at the end of this chapter?', 'He was anointed king and the people accepted him', 'He began building the temple immediately', 'He went to Gibeon to offer sacrifices', 'He traveled to Egypt to get workers', 'a', '1 Chronicles 29:22 — "And they made Solomon the son of David king the second time, and anointed him unto the LORD to be the chief governor, and Zadok to be priest."'),
-- Teens
('1 Chronicles', 29, 'teens', 1, 'How much did David give from his own personal treasure for the temple over and above what he had prepared?', 'Three thousand talents of gold and seven thousand talents of refined silver', 'One hundred thousand talents of gold and a million talents of silver', 'Ten thousand talents of gold and twenty thousand of silver', 'Five hundred talents of gold and a thousand talents of silver', 'a', '1 Chronicles 29:4 — "Even three thousand talents of gold, of the gold of Ophir, and seven thousand talents of refined silver, to overlay the walls of the houses withal."'),
('1 Chronicles', 29, 'teens', 2, 'What was the people''s emotional response when they gave their offerings willingly?', 'They rejoiced with great joy because with perfect heart they offered willingly to the LORD', 'They wept with gratitude and fell on their faces before God', 'They sang praises and danced before the ark', 'They were silent in solemn reverence as the offerings were counted', 'a', '1 Chronicles 29:9 — "Then the people rejoiced, for that they offered willingly, because with perfect heart they offered willingly to the LORD: and David the king also rejoiced with great joy."'),
('1 Chronicles', 29, 'teens', 3, 'What does David''s prayer say about human life on earth, using a metaphor of travelers?', 'We are strangers before thee and sojourners, as were all our fathers; our days on earth are as a shadow, and there is none abiding', 'Man is like a flower of the field that flourishes in the morning and withers at night', 'Our life is a vapor that appears for a moment and then passes away', 'We are pilgrims and wanderers with no city but the heavenly Jerusalem', 'a', '1 Chronicles 29:15 — "For we are strangers before thee, and sojourners, as were all our fathers: our days on the earth are as a shadow, and there is none abiding."'),
('1 Chronicles', 29, 'teens', 4, 'Who was anointed along with Solomon at the assembly, and to what office?', 'Zadok was anointed to be priest', 'Nathan the prophet was anointed as chief counsellor', 'Benaiah the son of Jehoiada was anointed as army commander', 'Joab was anointed as captain of the host', 'a', '1 Chronicles 29:22 — "And they made Solomon the son of David king the second time, and anointed him unto the LORD to be the chief governor, and Zadok to be priest."'),
('1 Chronicles', 29, 'teens', 5, 'How long did David reign as king over all Israel?', 'Forty years — seven years in Hebron and thirty-three years in Jerusalem', 'Thirty-three years — all in Jerusalem', 'Forty years — all in Jerusalem', 'Thirty years — ten in Hebron and twenty in Jerusalem', 'a', '1 Chronicles 29:27 — "And the time that he reigned over Israel was forty years; seven years reigned he in Hebron, and thirty and three years reigned he in Jerusalem."'),
-- Adults
('1 Chronicles', 29, 'adults', 1, 'What total amount of materials does David say he has prepared for the temple in his opening speech?', 'Three million talents of gold, seven million of silver, and countless quantities of brass, iron, wood, stone, marble and precious stones', 'A hundred thousand talents of gold and a thousand thousand of silver along with brass, iron, wood, and stone', 'Five hundred thousand talents of gold and all the spoils of his wars', 'He does not give exact figures but says it was exceedingly magnifical', 'a', '1 Chronicles 29:3-5 — David itemizes the gold of Ophir, refined silver, brass, iron, wood, onyx, and precious stones, stating the temple must be "exceeding magnifical" and inviting the leaders to consecrate themselves by giving.'),
('1 Chronicles', 29, 'adults', 2, 'How much gold and silver did the leaders of Israel collectively give over and above what David contributed personally?', 'Five thousand talents and ten thousand drams of gold; ten thousand talents of silver; eighteen thousand talents of brass; and one hundred thousand talents of iron', 'One thousand talents of gold and five thousand of silver from the princes', 'Two thousand talents of gold and four thousand of silver total', 'The text does not specify the leaders'' contribution separately from David''s', 'a', '1 Chronicles 29:7 — "And gave for the service of the house of God of gold five thousand talents and ten thousand drams, and of silver ten thousand talents, and of brass eighteen thousand talents, and one hundred thousand talents of iron."'),
('1 Chronicles', 29, 'adults', 3, 'What are the six attributes or titles David ascribes to God in his prayer of praise?', 'Greatness, power, glory, victory, majesty, and the kingdom — all in heaven and earth', 'Holiness, righteousness, mercy, faithfulness, wisdom, and love', 'Creator, king, judge, redeemer, shepherd, and father', 'Almighty, eternal, omniscient, omnipresent, sovereign, and merciful', 'a', '1 Chronicles 29:11 — "Thine, O LORD, is the greatness, and the power, and the glory, and the victory, and the majesty: for all that is in the heaven and in the earth is thine; thine is the kingdom, O LORD, and thou art exalted as head above all."'),
('1 Chronicles', 29, 'adults', 4, 'What did David ask God to do for Solomon specifically in the prayer?', 'Give Solomon a perfect heart to keep God''s commandments, testimonies, and statutes, and to build the palace for which David had made provision', 'Make Solomon wiser than all the kings of the earth', 'Give Solomon long life and victory over all his enemies', 'Protect Solomon from the plots of his brothers and the enemies of Israel', 'a', '1 Chronicles 29:19 — "And give unto Solomon my son a perfect heart, to keep thy commandments, thy testimonies, and thy statutes, and to do all these things, and to build the palace, for the which I have made provision."'),
('1 Chronicles', 29, 'adults', 5, 'What does David say about the source of wealth and honor in his prayer — crediting God or human effort?', 'Both riches and honour come of thee, and thou reignest over all; in thine hand is power and might; it is not in any man''s power to do it', 'Hard work and faithfulness bring blessing while laziness brings poverty', 'Those who store up riches in their heart will find God''s favor withdrawn', 'Wealth comes from God but its keeping depends on man''s faithfulness', 'a', '1 Chronicles 29:12 — "Both riches and honour come of thee, and thou reignest over all; and in thine hand is power and might; and in thine hand it is to make great, and to give strength unto all."'),
('1 Chronicles', 29, 'adults', 6, 'What thousand-offering sacrifice did Solomon and all Israel make after the anointing?', 'A thousand bullocks, a thousand rams, a thousand lambs with their drink offerings, and sacrifices in abundance for all Israel', 'Seven thousand bullocks and fourteen thousand sheep', 'Five hundred burnt offerings and five hundred peace offerings', 'One hundred bulls, one hundred rams, and one thousand lambs', 'a', '1 Chronicles 29:21 — "And they sacrificed sacrifices unto the LORD, and offered burnt offerings unto the LORD, on the morrow after that day, even a thousand bullocks, a thousand rams, and a thousand lambs, with their drink offerings."'),
('1 Chronicles', 29, 'adults', 7, 'Where were the acts of David the king, first and last, written down according to the closing verses?', 'In the book of Samuel the seer, in the book of Nathan the prophet, and in the book of Gad the seer', 'In the book of the chronicles of the kings of Israel', 'In the annals of Jerusalem kept by the Levitical scribes', 'In the book of the law found in the house of the LORD', 'a', '1 Chronicles 29:29 — "Now the acts of David the king, first and last, behold, they are written in the book of Samuel the seer, and in the book of Nathan the prophet, and in the book of Gad the seer."'),
('1 Chronicles', 29, 'adults', 8, 'What is the theological climax of 1 Chronicles as expressed in David''s final prayer and the conclusion of chapter 29?', 'That all human endeavor — kingship, wealth, temple-building — flows from God''s sovereign grace, and the proper response is joyful, voluntary worship returned to the God from whom all things come', 'That the temple is the greatest achievement of Israel and secures God''s favor permanently', 'That David''s dynasty will never fail because of the covenant made at Hebron', 'That human obedience is the foundation of divine blessing and the temple proves Israel''s faithfulness', 'a', '1 Chronicles 29:14 — "Of thine own have we given thee" — this phrase, at the center of David''s prayer, captures Chronicles'' theology: God is the source of all, human worship is returning God''s gifts to him, and the temple is the culmination of this divine-human partnership in grace.');
