-- ============================================================================
-- Quiz Seed: Epistle to the Ephesians (Chapters 1–6)
-- 3 difficulties × 6 chapters = 96 total questions
--   kids:   3 per chapter  =  18
--   teens:  5 per chapter  =  30
--   adults: 8 per chapter  =  48
-- ============================================================================

-- ═══════════════════════════════════════════════════════════════════════════
-- CHAPTERS 1 – 3
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══ Ephesians Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Ephesians', 1, 'kids', 1, 'Who wrote the letter to the Ephesians?', 'Paul', 'Peter', 'John', 'James', 'a', 'Ephesians 1:1 — "Paul, an apostle of Jesus Christ by the will of God, to the saints which are at Ephesus."'),
('Ephesians', 1, 'kids', 2, 'What has God blessed us with according to Ephesians 1?', 'All spiritual blessings in heavenly places in Christ', 'Gold and silver', 'Many animals', 'A big house', 'a', 'Ephesians 1:3 — "who hath blessed us with all spiritual blessings in heavenly places in Christ."'),
('Ephesians', 1, 'kids', 3, 'Where is Jesus sitting right now according to Paul?', 'At God''s right hand in heaven', 'On a throne on earth', 'In the temple', 'In a garden', 'a', 'Ephesians 1:20 — "set him at his own right hand in the heavenly places."'),
-- Teens
('Ephesians', 1, 'teens', 1, 'When did God choose us according to Ephesians 1:4?', 'Before the foundation of the world', 'At the moment of our baptism', 'When we first prayed', 'When we joined the church', 'a', 'Ephesians 1:4 — "he hath chosen us in him before the foundation of the world."'),
('Ephesians', 1, 'teens', 2, 'Through what do we have redemption?', 'Through His blood, the forgiveness of sins', 'Through keeping the law', 'Through good works', 'Through animal sacrifices', 'a', 'Ephesians 1:7 — "In whom we have redemption through his blood, the forgiveness of sins."'),
('Ephesians', 1, 'teens', 3, 'What does Paul call the Holy Spirit in relation to our inheritance?', 'The earnest (guarantee/deposit) of our inheritance', 'The seal of our salvation', 'The voice of our conscience', 'The guard of our hearts', 'a', 'Ephesians 1:14 — "Which is the earnest of our inheritance until the redemption of the purchased possession."'),
('Ephesians', 1, 'teens', 4, 'What does Paul pray the Ephesians would receive?', 'The spirit of wisdom and revelation in the knowledge of Him', 'Great wealth and prosperity', 'Freedom from Roman rule', 'The ability to perform miracles', 'a', 'Ephesians 1:17 — "the God of our Lord Jesus Christ… may give unto you the spirit of wisdom and revelation in the knowledge of him."'),
('Ephesians', 1, 'teens', 5, 'What is the church called in relation to Christ?', 'His body, the fulness of him that filleth all in all', 'His building and temple only', 'His servants and slaves', 'His students and pupils', 'a', 'Ephesians 1:22-23 — "gave him to be the head over all things to the church, Which is his body, the fulness of him that filleth all in all."'),
-- Adults
('Ephesians', 1, 'adults', 1, 'What does Paul say about God''s predestination in verse 5?', 'He predestinated us unto the adoption of children by Jesus Christ, according to the good pleasure of His will', 'He predestinated only the apostles', 'Predestination is based on foreseen merit', 'He predestinated the fall of mankind', 'a', 'Ephesians 1:5 — "Having predestinated us unto the adoption of children by Jesus Christ to himself, according to the good pleasure of his will."'),
('Ephesians', 1, 'adults', 2, 'What is the "mystery of His will" Paul mentions?', 'To gather together in one all things in Christ, both in heaven and earth', 'The date of Christ''s return', 'The identity of the Antichrist', 'The location of the lost tribes', 'a', 'Ephesians 1:9-10 — "the mystery of his will… That in the dispensation of the fulness of times he might gather together in one all things in Christ."'),
('Ephesians', 1, 'adults', 3, 'What two things does Paul say believers were sealed with?', 'The Holy Spirit of promise, after hearing the word of truth (the gospel of salvation)', 'Water baptism and circumcision', 'The blood of the Passover lamb and anointing oil', 'The sign of the cross and chrismation', 'a', 'Ephesians 1:13 — "after that ye heard the word of truth, the gospel of your salvation: in whom also after that ye believed, ye were sealed with that holy Spirit of promise."'),
('Ephesians', 1, 'adults', 4, 'What three things does Paul pray the Ephesians would know (eyes of understanding enlightened)?', 'The hope of His calling, the riches of His glorious inheritance in the saints, and the exceeding greatness of His power toward believers', 'Past sins, present duties, and future rewards', 'The law, the prophets, and the writings', 'Their spiritual gifts, their calling, and their church role', 'a', 'Ephesians 1:18-19 — "the hope of his calling… the riches of the glory of his inheritance in the saints, And what is the exceeding greatness of his power to us-ward who believe."'),
('Ephesians', 1, 'adults', 5, 'What does Paul say Christ''s exalted position is far above?', 'All principality, power, might, dominion, and every name that is named in this world and the world to come', 'Only earthly kings and rulers', 'Only the Jewish religious leaders', 'Only the Roman emperor', 'a', 'Ephesians 1:21 — "Far above all principality, and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come."'),
('Ephesians', 1, 'adults', 6, 'What power does Paul compare to God''s power working in believers?', 'The same mighty power that raised Christ from the dead and seated Him at God''s right hand', 'The power that parted the Red Sea', 'The power that created the world in six days', 'The power that held back the flood', 'a', 'Ephesians 1:19-20 — "according to the working of his mighty power, Which he wrought in Christ, when he raised him from the dead."'),
('Ephesians', 1, 'adults', 7, 'What does "to the praise of the glory of his grace" repeated in this chapter emphasize?', 'That God''s ultimate purpose in election, redemption, and sealing is His own glory — the refrain appears in verses 6, 12, and 14', 'That believers should praise loudly in worship', 'That only grace matters, not holiness', 'That God seeks human applause', 'a', 'Ephesians 1:6,12,14 — The phrase "to the praise of his glory" appears three times, emphasizing God''s glory as the ultimate purpose.'),
('Ephesians', 1, 'adults', 8, 'How does Paul describe God''s working in redemption in verse 8?', 'He abounded toward us in all wisdom and prudence', 'He acted in strict justice without mercy', 'He worked through natural human reasoning', 'He revealed everything at once without progression', 'a', 'Ephesians 1:8 — "Wherein he hath abounded toward us in all wisdom and prudence."');

-- ═══ Ephesians Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Ephesians', 2, 'kids', 1, 'What does Paul say we are saved by?', 'Grace through faith', 'Being good', 'Keeping rules', 'Giving money', 'a', 'Ephesians 2:8 — "For by grace are ye saved through faith."'),
('Ephesians', 2, 'kids', 2, 'What does Paul say we are — God''s what?', 'God''s workmanship', 'God''s soldiers', 'God''s servants only', 'God''s students', 'a', 'Ephesians 2:10 — "we are his workmanship, created in Christ Jesus unto good works."'),
('Ephesians', 2, 'kids', 3, 'Who is our peace, making Jews and Gentiles one?', 'Christ Jesus', 'Moses', 'Abraham', 'The Roman emperor', 'a', 'Ephesians 2:14 — "he is our peace, who hath made both one."'),
-- Teens
('Ephesians', 2, 'teens', 1, 'What were believers before God made them alive?', 'Dead in trespasses and sins', 'Slightly sinful', 'Already righteous', 'Spiritually confused', 'a', 'Ephesians 2:1 — "And you hath he quickened, who were dead in trespasses and sins."'),
('Ephesians', 2, 'teens', 2, 'What is salvation NOT of, according to Ephesians 2:8-9?', 'Not of yourselves and not of works, lest any man should boast', 'Not of grace', 'Not of faith', 'Not of God''s plan', 'a', 'Ephesians 2:8-9 — "not of yourselves: it is the gift of God: Not of works, lest any man should boast."'),
('Ephesians', 2, 'teens', 3, 'What did Christ break down between Jews and Gentiles?', 'The middle wall of partition', 'The temple curtain', 'The city gates', 'The stone tablets', 'a', 'Ephesians 2:14 — "hath broken down the middle wall of partition between us."'),
('Ephesians', 2, 'teens', 4, 'What does Paul say Gentile believers are no longer?', 'Strangers and foreigners, but fellowcitizens with the saints and of the household of God', 'Required to follow Jewish law', 'Excluded from worshipping God', 'Second-class members of the church', 'a', 'Ephesians 2:19 — "ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God."'),
('Ephesians', 2, 'teens', 5, 'What is the church built upon according to verse 20?', 'The foundation of the apostles and prophets, Jesus Christ being the chief corner stone', 'The foundation of Peter alone', 'The foundation of the law of Moses', 'The foundation of church tradition', 'a', 'Ephesians 2:20 — "built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner stone."'),
-- Adults
('Ephesians', 2, 'adults', 1, 'What three influences controlled believers before conversion according to verses 2-3?', 'The course of this world, the prince of the power of the air, and the lusts of the flesh and mind', 'Poverty, ignorance, and disease', 'Greek philosophy, Roman law, and Jewish tradition', 'Fear, pride, and laziness', 'a', 'Ephesians 2:2-3 — "the course of this world… the prince of the power of the air, the spirit that now worketh in the children of disobedience… the lusts of our flesh… the desires of the flesh and of the mind."'),
('Ephesians', 2, 'adults', 2, 'What motivated God to save us according to verse 4?', 'His great love and His being rich in mercy', 'Our good works impressed Him', 'We deserved salvation', 'The angels interceded for us', 'a', 'Ephesians 2:4 — "God, who is rich in mercy, for his great love wherewith he loved us."'),
('Ephesians', 2, 'adults', 3, 'What three things has God done for believers "together with Christ" in verses 5-6?', 'Quickened us together, raised us up together, and made us sit together in heavenly places', 'Forgiven us, baptized us, and confirmed us', 'Taught us, disciplined us, and rewarded us', 'Called us, chosen us, and glorified us', 'a', 'Ephesians 2:5-6 — "hath quickened us together with Christ… hath raised us up together, and made us sit together in heavenly places in Christ Jesus."'),
('Ephesians', 2, 'adults', 4, 'What is God''s purpose in the ages to come according to verse 7?', 'To show the exceeding riches of His grace in His kindness toward us through Christ Jesus', 'To establish believers as earthly rulers', 'To demonstrate His wrath against sin', 'To reveal hidden mysteries to angels', 'a', 'Ephesians 2:7 — "That in the ages to come he might shew the exceeding riches of his grace in his kindness toward us through Christ Jesus."'),
('Ephesians', 2, 'adults', 5, 'What does "created in Christ Jesus unto good works" imply about the role of works?', 'Good works are the result and purpose of salvation, not its cause — they were prepared beforehand for believers to walk in', 'Works are required before salvation', 'Works are optional for the saved', 'Works earn additional salvation', 'a', 'Ephesians 2:10 — "created in Christ Jesus unto good works, which God hath before ordained that we should walk in them."'),
('Ephesians', 2, 'adults', 6, 'What does Paul say Christ abolished in His flesh?', 'The enmity, even the law of commandments contained in ordinances, to make of two one new man', 'The Roman legal system', 'The entire Old Testament', 'The priesthood of Aaron', 'a', 'Ephesians 2:15 — "Having abolished in his flesh the enmity, even the law of commandments contained in ordinances; for to make in himself of twain one new man, so making peace."'),
('Ephesians', 2, 'adults', 7, 'How does Paul describe believers'' access to God in verse 18?', 'Through Christ we both (Jews and Gentiles) have access by one Spirit unto the Father', 'Only through a human priest', 'Only through temple sacrifice', 'Through our own merits', 'a', 'Ephesians 2:18 — "For through him we both have access by one Spirit unto the Father."'),
('Ephesians', 2, 'adults', 8, 'What is the church growing into according to verse 21?', 'A holy temple in the Lord, a habitation of God through the Spirit', 'A political force in the Roman Empire', 'A philosophical school of thought', 'A replacement for the Jerusalem temple', 'a', 'Ephesians 2:21-22 — "groweth unto an holy temple in the Lord: In whom ye also are builded together for an habitation of God through the Spirit."');

-- ═══ Ephesians Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Ephesians', 3, 'kids', 1, 'What mystery did God reveal to Paul?', 'That Gentiles are fellow heirs with Jews in Christ', 'The date of Christ''s return', 'Where to build the church', 'How to make gold', 'a', 'Ephesians 3:6 — "the Gentiles should be fellowheirs, and of the same body."'),
('Ephesians', 3, 'kids', 2, 'What does Paul say God can do beyond what we ask?', 'Exceeding abundantly above all that we ask or think', 'Exactly what we pray for', 'Only small things', 'Nothing without our help', 'a', 'Ephesians 3:20 — "able to do exceeding abundantly above all that we ask or think."'),
('Ephesians', 3, 'kids', 3, 'What did Paul pray that Christ would do in the Ephesians'' hearts?', 'Dwell in their hearts by faith', 'Give them riches', 'Make them famous', 'Keep them from all trouble', 'a', 'Ephesians 3:17 — "That Christ may dwell in your hearts by faith."'),
-- Teens
('Ephesians', 3, 'teens', 1, 'What does Paul call himself in relation to the Gentiles?', 'The prisoner of Jesus Christ for you Gentiles', 'The king of the Gentiles', 'The judge of the Gentiles', 'The teacher of the Gentiles only', 'a', 'Ephesians 3:1 — "I Paul, the prisoner of Jesus Christ for you Gentiles."'),
('Ephesians', 3, 'teens', 2, 'What does Paul call himself — the least of what?', 'Less than the least of all saints', 'The greatest of all apostles', 'A Pharisee of Pharisees', 'The chief of sinners', 'a', 'Ephesians 3:8 — "Unto me, who am less than the least of all saints, is this grace given."'),
('Ephesians', 3, 'teens', 3, 'What four dimensions of Christ''s love does Paul pray they would know?', 'The breadth, length, depth, and height', 'Faith, hope, love, and joy', 'Past, present, future, and eternal', 'Grace, mercy, peace, and truth', 'a', 'Ephesians 3:18 — "May be able to comprehend with all saints what is the breadth, and length, and depth, and height."'),
('Ephesians', 3, 'teens', 4, 'What did Paul say the mystery of Christ was hidden from in past ages?', 'Other ages — it was not made known to the sons of men as now revealed to apostles and prophets by the Spirit', 'Only from the Gentiles', 'Only from women', 'Only from children', 'a', 'Ephesians 3:5 — "Which in other ages was not made known unto the sons of men, as it is now revealed unto his holy apostles and prophets by the Spirit."'),
('Ephesians', 3, 'teens', 5, 'What does Paul ask the Ephesians not to lose heart about?', 'His tribulations (sufferings) for them, which are their glory', 'The slow growth of the church', 'The persecution from Rome', 'The cost of building a meeting place', 'a', 'Ephesians 3:13 — "I desire that ye faint not at my tribulations for you, which is your glory."'),
-- Adults
('Ephesians', 3, 'adults', 1, 'What is the "dispensation of the grace of God" given to Paul?', 'The stewardship of proclaiming the mystery that Gentiles are fellow heirs, of the same body, and partakers of the promise in Christ by the gospel', 'A special healing ministry', 'Authority to write all the epistles', 'The role of high priest for the church', 'a', 'Ephesians 3:2,6 — "the dispensation of the grace of God which is given me to you-ward… the Gentiles should be fellowheirs, and of the same body."'),
('Ephesians', 3, 'adults', 2, 'To whom is the manifold wisdom of God made known through the church?', 'Principalities and powers in heavenly places', 'The Roman senate', 'The Jewish Sanhedrin', 'Future generations of humanity', 'a', 'Ephesians 3:10 — "To the intent that now unto the principalities and powers in heavenly places might be known by the church the manifold wisdom of God."'),
('Ephesians', 3, 'adults', 3, 'What does Paul say about boldness and access to God in verse 12?', 'In Christ we have boldness and access with confidence by the faith of Him', 'We must approach God with fear and trembling only', 'Only apostles have direct access to God', 'Access requires priestly mediation', 'a', 'Ephesians 3:12 — "In whom we have boldness and access with confidence by the faith of him."'),
('Ephesians', 3, 'adults', 4, 'What does Paul pray the Father would grant according to the riches of His glory?', 'To be strengthened with might by His Spirit in the inner man', 'To be blessed with material wealth', 'To be given political influence', 'To be made physically strong', 'a', 'Ephesians 3:16 — "he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man."'),
('Ephesians', 3, 'adults', 5, 'What does Paul say Christ''s love surpasses?', 'Knowledge — it passeth knowledge, that they might be filled with all the fulness of God', 'Human experience only', 'Earthly love only', 'The love of angels', 'a', 'Ephesians 3:19 — "to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God."'),
('Ephesians', 3, 'adults', 6, 'According to what power does God work in believers?', 'According to the power that worketh in us — the same power referenced in Ephesians 1:19-20', 'According to our faith level', 'According to our obedience', 'According to our knowledge', 'a', 'Ephesians 3:20 — "according to the power that worketh in us."'),
('Ephesians', 3, 'adults', 7, 'What does Paul''s doxology in 3:20-21 ascribe glory to?', 'God in the church by Christ Jesus throughout all ages, world without end', 'God in the temple at Jerusalem', 'God through the apostles only', 'God in heaven alone, not on earth', 'a', 'Ephesians 3:21 — "Unto him be glory in the church by Christ Jesus throughout all ages, world without end. Amen."'),
('Ephesians', 3, 'adults', 8, 'How does Paul describe his role as a minister of the gospel?', 'He was made a minister according to the gift of the grace of God given by the effectual working of His power', 'He chose the ministry as a career', 'He inherited the role from his family', 'He was appointed by the Jerusalem council', 'a', 'Ephesians 3:7 — "Whereof I was made a minister, according to the gift of the grace of God given unto me by the effectual working of his power."');

-- ═══════════════════════════════════════════════════════════════════════════
-- CHAPTERS 4 – 6
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══ Ephesians Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Ephesians', 4, 'kids', 1, 'How many Lord, faith, and baptism does Paul say there are?', 'One of each', 'Three of each', 'Seven of each', 'Many', 'a', 'Ephesians 4:5 — "One Lord, one faith, one baptism."'),
('Ephesians', 4, 'kids', 2, 'What does Paul say we should speak to each other?', 'The truth in love', 'Whatever makes them happy', 'Only good news', 'Nothing at all', 'a', 'Ephesians 4:15 — "speaking the truth in love."'),
('Ephesians', 4, 'kids', 3, 'What should we do instead of stealing?', 'Work with our hands so we can give to those in need', 'Hide what we take', 'Ask someone else to steal for us', 'Only take small things', 'a', 'Ephesians 4:28 — "let him labour, working with his hands the thing which is good, that he may have to give to him that needeth."'),
-- Teens
('Ephesians', 4, 'teens', 1, 'What does Paul urge believers to walk worthy of?', 'The vocation wherewith they are called, with lowliness, meekness, longsuffering', 'Their social status', 'Their education', 'Their wealth', 'a', 'Ephesians 4:1 — "walk worthy of the vocation wherewith ye are called."'),
('Ephesians', 4, 'teens', 2, 'What five ministry gifts did Christ give to the church?', 'Apostles, prophets, evangelists, pastors, and teachers', 'Deacons, elders, bishops, priests, and monks', 'Healers, miracle workers, speakers, singers, and writers', 'Kings, priests, prophets, judges, and warriors', 'a', 'Ephesians 4:11 — "he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers."'),
('Ephesians', 4, 'teens', 3, 'What does Paul say about not letting the sun go down on?', 'Your wrath (anger)', 'Your prayers', 'Your work', 'Your food', 'a', 'Ephesians 4:26 — "let not the sun go down upon your wrath."'),
('Ephesians', 4, 'teens', 4, 'What should believers put off and put on?', 'Put off the old man (corrupt according to deceitful lusts) and put on the new man (created in righteousness and true holiness)', 'Put off old clothes and put on new ones', 'Put off sadness and put on happiness', 'Put off work and put on rest', 'a', 'Ephesians 4:22-24 — "put off concerning the former conversation the old man… put on the new man, which after God is created in righteousness and true holiness."'),
('Ephesians', 4, 'teens', 5, 'Who does Paul say believers should not grieve?', 'The Holy Spirit of God, by whom they are sealed unto the day of redemption', 'Their parents', 'Their pastors', 'The angels', 'a', 'Ephesians 4:30 — "grieve not the holy Spirit of God, whereby ye are sealed unto the day of redemption."'),
-- Adults
('Ephesians', 4, 'adults', 1, 'What seven unities does Paul list in verses 4-6?', 'One body, one Spirit, one hope, one Lord, one faith, one baptism, one God and Father', 'Seven churches, seven seals, seven trumpets', 'Seven gifts, seven virtues, seven blessings', 'One temple, one priesthood, one sacrifice, one altar, one feast, one law, one covenant', 'a', 'Ephesians 4:4-6 — "One body, and one Spirit… one hope… One Lord, one faith, one baptism, One God and Father of all."'),
('Ephesians', 4, 'adults', 2, 'What Psalm does Paul quote about Christ''s ascension?', '"When he ascended up on high, he led captivity captive, and gave gifts unto men" (Psalm 68:18)', '"The Lord said unto my Lord, Sit thou at my right hand" (Psalm 110:1)', '"Lift up your heads, O ye gates" (Psalm 24:7)', '"The stone which the builders refused is become the head stone" (Psalm 118:22)', 'a', 'Ephesians 4:8 — "When he ascended up on high, he led captivity captive, and gave gifts unto men."'),
('Ephesians', 4, 'adults', 3, 'What is the purpose of the five ministry gifts?', 'For the perfecting of the saints, the work of the ministry, and the edifying of the body of Christ', 'To govern the church politically', 'To replace the Levitical priesthood', 'To collect tithes and manage finances', 'a', 'Ephesians 4:12 — "For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ."'),
('Ephesians', 4, 'adults', 4, 'What does Paul say about Christ descending before ascending?', 'He first descended into the lower parts of the earth before ascending far above all heavens, that He might fill all things', 'He descended from a mountain into a valley', 'He went down to the river for baptism', 'He descended from heaven only once at the incarnation', 'a', 'Ephesians 4:9-10 — "he also descended first into the lower parts of the earth… He that descended is the same also that ascended up far above all heavens, that he might fill all things."'),
('Ephesians', 4, 'adults', 5, 'What does Paul say about Gentile believers'' former manner of thinking?', 'They walked in the vanity of their mind, having the understanding darkened, being alienated from the life of God through ignorance and blindness of heart', 'They were wise philosophers seeking truth', 'They were simple but sincere seekers', 'They were morally superior to Jewish unbelievers', 'a', 'Ephesians 4:17-18 — "walk not as other Gentiles walk, in the vanity of their mind, Having the understanding darkened, being alienated from the life of God."'),
('Ephesians', 4, 'adults', 6, 'What does "being past feeling" describe about unregenerate Gentiles?', 'They gave themselves over unto lasciviousness, to work all uncleanness with greediness — their conscience was seared', 'They could not feel physical pain', 'They were emotionally stable', 'They had no capacity for joy', 'a', 'Ephesians 4:19 — "Who being past feeling have given themselves over unto lasciviousness, to work all uncleanness with greediness."'),
('Ephesians', 4, 'adults', 7, 'What does Paul say about corrupt communication?', '"Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying, that it may minister grace unto the hearers"', '"Only speak in tongues when in church"', '"Never speak to unbelievers"', '"Use only Hebrew in worship"', 'a', 'Ephesians 4:29 — "Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying."'),
('Ephesians', 4, 'adults', 8, 'What six things does Paul say to put away, and what should replace them?', 'Bitterness, wrath, anger, clamour, evil speaking, malice — replaced by kindness, tenderheartedness, and forgiveness as God forgave us in Christ', 'Poverty, sickness, ignorance, weakness, loneliness, fear', 'Fasting, prayer, giving, preaching, teaching, serving', 'Wine, meat, luxury, idleness, travel, entertainment', 'a', 'Ephesians 4:31-32 — "Let all bitterness, and wrath, and anger, and clamour, and evil speaking, be put away from you, with all malice: And be ye kind one to another, tenderhearted, forgiving one another."');

-- ═══ Ephesians Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Ephesians', 5, 'kids', 1, 'What does Paul say children of light should walk in?', 'Love, as Christ also hath loved us', 'Darkness', 'Fear', 'Riches', 'a', 'Ephesians 5:2 — "walk in love, as Christ also hath loved us."'),
('Ephesians', 5, 'kids', 2, 'What does Paul say to find out?', 'What is acceptable unto the Lord', 'How to become rich', 'Where treasure is hidden', 'When school is over', 'a', 'Ephesians 5:10 — "Proving what is acceptable unto the Lord."'),
('Ephesians', 5, 'kids', 3, 'What should we be filled with instead of wine?', 'The Spirit', 'Water', 'Juice', 'Milk', 'a', 'Ephesians 5:18 — "be not drunk with wine, wherein is excess; but be filled with the Spirit."'),
-- Teens
('Ephesians', 5, 'teens', 1, 'What does Paul say Christ gave Himself as?', 'An offering and a sacrifice to God for a sweetsmelling savour', 'A political leader', 'A military general', 'A wealthy benefactor', 'a', 'Ephesians 5:2 — "Christ also hath loved us, and hath given himself for us an offering and a sacrifice to God for a sweetsmelling savour."'),
('Ephesians', 5, 'teens', 2, 'What should have no fellowship with?', 'The unfruitful works of darkness; rather reprove (expose) them', 'Other churches', 'People who are different', 'Anyone outside our group', 'a', 'Ephesians 5:11 — "have no fellowship with the unfruitful works of darkness, but rather reprove them."'),
('Ephesians', 5, 'teens', 3, 'How does Paul say we should walk?', 'Circumspectly (carefully), not as fools but as wise, redeeming the time', 'Slowly and cautiously', 'Only in safe places', 'Without any plan', 'a', 'Ephesians 5:15-16 — "See then that ye walk circumspectly, not as fools, but as wise, Redeeming the time, because the days are evil."'),
('Ephesians', 5, 'teens', 4, 'What relationship does Paul compare to Christ and the church?', 'Husband and wife', 'Parent and child', 'Master and servant', 'King and subject', 'a', 'Ephesians 5:25 — "Husbands, love your wives, even as Christ also loved the church."'),
('Ephesians', 5, 'teens', 5, 'How did Christ love the church?', 'He gave Himself for it, to sanctify and cleanse it', 'He ruled over it with strict laws', 'He taught it theology only', 'He left it to manage itself', 'a', 'Ephesians 5:25-26 — "Christ also loved the church, and gave himself for it; That he might sanctify and cleanse it with the washing of water by the word."'),
-- Adults
('Ephesians', 5, 'adults', 1, 'What does Paul say about the fruit of the Spirit (or Light)?', 'The fruit of the Spirit is in all goodness and righteousness and truth', 'The fruit of the Spirit is in tongues, healing, and prophecy', 'The fruit of the Spirit is only for apostles', 'The fruit of the Spirit replaces moral living', 'a', 'Ephesians 5:9 — "the fruit of the Spirit is in all goodness and righteousness and truth."'),
('Ephesians', 5, 'adults', 2, 'What does Paul quote that says "Awake thou that sleepest"?', '"Awake thou that sleepest, and arise from the dead, and Christ shall give thee light" — likely an early Christian hymn or prophetic adaptation of Isaiah 60:1', '"Arise, shine; for thy light is come" (Isaiah 60:1) exactly as written', 'A quote from the book of Enoch', 'A saying of Jesus from the Gospels', 'a', 'Ephesians 5:14 — "Awake thou that sleepest, and arise from the dead, and Christ shall give thee light."'),
('Ephesians', 5, 'adults', 3, 'What does Paul say about understanding the will of the Lord versus drunkenness?', '"Be not drunk with wine, wherein is excess; but be filled with the Spirit" — contrasting fleshly excess with spiritual fullness', 'Wine is forbidden for all Christians', 'Moderate drinking is encouraged', 'Only priests should abstain from wine', 'a', 'Ephesians 5:17-18 — "Wherefore be ye not unwise, but understanding what the will of the Lord is. And be not drunk with wine, wherein is excess; but be filled with the Spirit."'),
('Ephesians', 5, 'adults', 4, 'What does being filled with the Spirit produce according to verses 19-21?', 'Speaking in psalms, hymns, spiritual songs; giving thanks always; submitting to one another in the fear of God', 'Only speaking in tongues', 'Silent meditation and fasting', 'Withdrawal from all social interaction', 'a', 'Ephesians 5:19-21 — "Speaking to yourselves in psalms and hymns and spiritual songs, singing and making melody in your heart to the Lord; Giving thanks always… Submitting yourselves one to another in the fear of God."'),
('Ephesians', 5, 'adults', 5, 'How does Paul describe Christ''s goal for the church?', 'To present it to Himself a glorious church, not having spot or wrinkle or any such thing, but holy and without blemish', 'To make it the largest organization on earth', 'To give it political power over nations', 'To make it wealthy and influential', 'a', 'Ephesians 5:27 — "That he might present it to himself a glorious church, not having spot, or wrinkle, or any such thing; but that it should be holy and without blemish."'),
('Ephesians', 5, 'adults', 6, 'What Old Testament text does Paul quote about marriage?', '"For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh" (Genesis 2:24)', '"It is not good that the man should be alone" (Genesis 2:18)', '"Be fruitful, and multiply" (Genesis 1:28)', '"Whoso findeth a wife findeth a good thing" (Proverbs 18:22)', 'a', 'Ephesians 5:31 — "For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh."'),
('Ephesians', 5, 'adults', 7, 'What does Paul call the marriage-Christ/church parallel?', '"This is a great mystery: but I speak concerning Christ and the church"', '"This is a simple illustration"', '"This is a temporary arrangement"', '"This is a cultural accommodation"', 'a', 'Ephesians 5:32 — "This is a great mystery: but I speak concerning Christ and the church."'),
('Ephesians', 5, 'adults', 8, 'What does Paul say the wife''s submission is compared to?', 'As the church is subject unto Christ, so let the wives be to their own husbands in every thing', 'As slaves are to masters', 'As children are to teachers', 'As soldiers are to generals', 'a', 'Ephesians 5:24 — "as the church is subject unto Christ, so let the wives be to their own husbands in every thing."');

-- ═══ Ephesians Chapter 6 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Ephesians', 6, 'kids', 1, 'What does Paul tell children to do?', 'Obey your parents in the Lord, for this is right', 'Do whatever they want', 'Argue with their parents', 'Ignore their parents', 'a', 'Ephesians 6:1 — "Children, obey your parents in the Lord: for this is right."'),
('Ephesians', 6, 'kids', 2, 'What armor does Paul say to put on?', 'The whole armour of God', 'A suit of Roman armor', 'A shield made of wood', 'New clothes', 'a', 'Ephesians 6:11 — "Put on the whole armour of God."'),
('Ephesians', 6, 'kids', 3, 'What is the sword of the Spirit?', 'The word of God', 'A real metal sword', 'A magic wand', 'A sharp stick', 'a', 'Ephesians 6:17 — "the sword of the Spirit, which is the word of God."'),
-- Teens
('Ephesians', 6, 'teens', 1, 'What is the first commandment with a promise?', '"Honour thy father and mother; that it may be well with thee, and thou mayest live long on the earth"', '"Thou shalt not steal"', '"Remember the sabbath day"', '"Thou shalt not kill"', 'a', 'Ephesians 6:2-3 — "Honour thy father and mother; which is the first commandment with promise."'),
('Ephesians', 6, 'teens', 2, 'What does Paul say fathers should not do to their children?', 'Provoke them to wrath, but bring them up in the nurture and admonition of the Lord', 'Spoil them with gifts', 'Let them do whatever they want', 'Keep them from attending synagogue', 'a', 'Ephesians 6:4 — "ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord."'),
('Ephesians', 6, 'teens', 3, 'Who is our real enemy according to Ephesians 6?', 'Principalities, powers, rulers of darkness, and spiritual wickedness in high places', 'The Roman government', 'Other religions', 'Our neighbors', 'a', 'Ephesians 6:12 — "we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places."'),
('Ephesians', 6, 'teens', 4, 'Name the six pieces of the armor of God.', 'Belt of truth, breastplate of righteousness, shoes of the gospel of peace, shield of faith, helmet of salvation, sword of the Spirit', 'Sword, spear, shield, helmet, armor, and horse', 'Prayer, fasting, giving, reading, singing, and serving', 'Faith, hope, love, patience, kindness, and goodness', 'a', 'Ephesians 6:14-17 lists the belt of truth, breastplate of righteousness, shoes of the gospel of peace, shield of faith, helmet of salvation, and sword of the Spirit.'),
('Ephesians', 6, 'teens', 5, 'What does the shield of faith quench?', 'All the fiery darts of the wicked', 'Physical arrows', 'Hunger and thirst', 'Fear and doubt', 'a', 'Ephesians 6:16 — "the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked."'),
-- Adults
('Ephesians', 6, 'adults', 1, 'How does Paul instruct servants (bondservants) to work?', 'With fear and trembling, in singleness of heart as unto Christ, not with eyeservice as menpleasers, doing the will of God from the heart', 'Only when the master is watching', 'Reluctantly but obediently', 'With the goal of earning their freedom', 'a', 'Ephesians 6:5-6 — "Servants, be obedient to them that are your masters… with fear and trembling, in singleness of your heart, as unto Christ; Not with eyeservice, as menpleasers; but as the servants of Christ, doing the will of God from the heart."'),
('Ephesians', 6, 'adults', 2, 'What does Paul say masters should do, and why?', 'Do the same things (treat servants well), forbearing threatening, knowing that their Master is in heaven and there is no respect of persons with Him', 'Rule with an iron fist', 'Free all their slaves immediately', 'Pay them wages equal to free men', 'a', 'Ephesians 6:9 — "ye masters, do the same things unto them, forbearing threatening: knowing that your Master also is in heaven; neither is there respect of persons with him."'),
('Ephesians', 6, 'adults', 3, 'Why does Paul say to put on the whole armor of God?', 'To be able to stand against the wiles (schemes) of the devil', 'To impress other churches', 'To fight against the Romans', 'To prove our salvation', 'a', 'Ephesians 6:11 — "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil."'),
('Ephesians', 6, 'adults', 4, 'What does the phrase "having done all, to stand" mean in context?', 'After using every piece of armor and fighting the spiritual battle, the believer remains standing firm — perseverance in spiritual warfare', 'After finishing your daily chores, stand still', 'After preaching a sermon, stand at the door', 'After communion, remain standing', 'a', 'Ephesians 6:13 — "having done all, to stand."'),
('Ephesians', 6, 'adults', 5, 'What kind of prayer does Paul call for in spiritual warfare?', '"Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication for all saints"', 'A specific prayer said once daily', 'Only silent meditation', 'Prayer only during church services', 'a', 'Ephesians 6:18 — "Praying always with all prayer and supplication in the Spirit, and watching thereunto with all perseverance and supplication for all saints."'),
('Ephesians', 6, 'adults', 6, 'What does Paul ask the Ephesians to pray for regarding his ministry?', 'That utterance may be given to him to make known with boldness the mystery of the gospel, for which he is an ambassador in bonds', 'That he be released from prison', 'That he receive financial support', 'That he be given safety in travel', 'a', 'Ephesians 6:19-20 — "that utterance may be given unto me, that I may open my mouth boldly, to make known the mystery of the gospel, For which I am an ambassador in bonds."'),
('Ephesians', 6, 'adults', 7, 'Who does Paul send to the Ephesians and for what purpose?', 'Tychicus, a beloved brother and faithful minister, to inform them of Paul''s affairs and comfort their hearts', 'Timothy, to be their new pastor', 'Luke, to heal the sick', 'Apollos, to teach them eloquence', 'a', 'Ephesians 6:21-22 — "Tychicus, a beloved brother and faithful minister in the Lord, shall make known to you all things… that he might comfort your hearts."'),
('Ephesians', 6, 'adults', 8, 'What unique phrase does Paul use in his closing benediction?', '"Grace be with all them that love our Lord Jesus Christ in sincerity (incorruption)"', '"The grace of our Lord Jesus Christ be with your spirit"', '"May the peace of God guard your hearts"', '"Greet one another with a holy kiss"', 'a', 'Ephesians 6:24 — "Grace be with all them that love our Lord Jesus Christ in sincerity. Amen."');
