-- ============================================================================
-- Quiz Seed: Exodus — Part 1 (Chapters 1–10)
-- 3 difficulties × 10 chapters = 160 total questions
--   kids:   3 per chapter  = 30
--   teens:  5 per chapter  = 50
--   adults: 8 per chapter  = 80
-- ============================================================================

-- ═══════════════ CHAPTERS 1–5 ═══════════════

-- ═══ Exodus Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 1, 'kids', 1, 'What happened to the children of Israel in Egypt?', 'They grew into a very large number of people', 'They all went back to Canaan', 'They became kings of Egypt', 'They disappeared', 'a', 'Exodus 1:7 — "And the children of Israel were fruitful, and increased abundantly, and multiplied, and waxed exceeding mighty; and the land was filled with them."'),
('Exodus', 1, 'kids', 2, 'What did the new king of Egypt make the Israelites do?', 'Hard work as slaves — building cities with bricks and mortar', 'Sing songs for him', 'Go fishing in the Nile', 'Teach in his schools', 'a', 'Exodus 1:13-14 — "And the Egyptians made the children of Israel to serve with rigour: And they made their lives bitter with hard bondage, in morter, and in brick."'),
('Exodus', 1, 'kids', 3, 'What brave thing did the midwives Shiphrah and Puah do?', 'They refused to kill the Hebrew baby boys because they feared God', 'They ran away from Egypt', 'They hid all the food', 'They built a boat', 'a', 'Exodus 1:17 — "But the midwives feared God, and did not as the king of Egypt commanded them, but saved the men children alive."'),
-- Teens
('Exodus', 1, 'teens', 1, 'Why did the new Pharaoh fear the Israelites?', 'They had become more and mightier than the Egyptians, and he feared they would join enemies in war', 'They had better weapons', 'They owned more land', 'They worshipped different gods', 'a', 'Exodus 1:9-10 — "Behold, the people of the children of Israel are more and mightier than we: Come on, let us deal wisely with them; lest they multiply, and it come to pass, that, when there falleth out any war, they join also unto our enemies."'),
('Exodus', 1, 'teens', 2, 'What happened when the Egyptians afflicted the Israelites more?', 'The more they afflicted them, the more they multiplied and grew', 'The Israelites stopped having children', 'The Israelites surrendered completely', 'The Israelites left Egypt', 'a', 'Exodus 1:12 — "But the more they afflicted them, the more they multiplied and grew. And they were grieved because of the children of Israel."'),
('Exodus', 1, 'teens', 3, 'What two treasure cities did the Israelites build for Pharaoh?', 'Pithom and Raamses', 'Memphis and Thebes', 'Cairo and Alexandria', 'Goshen and Beersheba', 'a', 'Exodus 1:11 — "Therefore they did set over them taskmasters to afflict them with their burdens. And they built for Pharaoh treasure cities, Pithom and Raamses."'),
('Exodus', 1, 'teens', 4, 'What excuse did the midwives give Pharaoh for not killing the babies?', 'The Hebrew women are lively and deliver before the midwives arrive', 'They said they forgot the command', 'They said they were too old', 'They said the babies were already dead', 'a', 'Exodus 1:19 — "And the midwives said unto Pharaoh, Because the Hebrew women are not as the Egyptian women; for they are lively, and are delivered ere the midwives come in unto them."'),
('Exodus', 1, 'teens', 5, 'What was Pharaoh''s final decree regarding Hebrew baby boys?', 'Every son that is born shall be cast into the river, but every daughter shall live', 'They should be sent to work in the fields', 'They should be given to Egyptian families', 'They should be sold as slaves', 'a', 'Exodus 1:22 — "And Pharaoh charged all his people, saying, Every son that is born ye shall cast into the river, and every daughter ye shall save alive."'),
-- Adults
('Exodus', 1, 'adults', 1, 'How does Exodus 1:7 use multiple terms to describe Israel''s growth, and what is the significance?', 'Five terms — fruitful, increased abundantly, multiplied, waxed exceeding mighty, land filled — echoing the creation mandate of Genesis 1:28 and God''s promise to Abraham', 'It uses only one term for growth', 'It describes a decline in population', 'It lists the names of the tribes', 'a', 'Exodus 1:7 — "And the children of Israel were fruitful, and increased abundantly, and multiplied, and waxed exceeding mighty; and the land was filled with them." The language deliberately echoes Genesis 1:28 and 9:1, showing God''s covenant faithfulness.'),
('Exodus', 1, 'adults', 2, 'What is the significance of the phrase "a new king over Egypt, which knew not Joseph"?', 'It marks a complete political and cultural break — the new dynasty had no memory of or obligation to Joseph''s legacy, setting the stage for Israel''s oppression', 'It means Joseph was forgotten by his family', 'It refers to a minor change in government', 'It indicates Joseph had moved to another country', 'a', 'Exodus 1:8 — "Now there arose up a new king over Egypt, which knew not Joseph." This likely refers to a dynastic change (possibly the transition from Hyksos to native Egyptian rule), severing the political relationship that had protected Israel.'),
('Exodus', 1, 'adults', 3, 'What three escalating strategies does Pharaoh employ against Israel in chapter 1?', 'Forced labour (v.11), harder bondage and bitter servitude (v.13-14), and infanticide — first through midwives (v.16) then publicly via the Nile (v.22)', 'Only forced labour', 'Only killing firstborns', 'Exile and deportation', 'a', 'Pharaoh''s oppression escalates: taskmasters and construction (v.11), ruthless servitude in mortar, brick, and field work (vv.13-14), covert infanticide via midwives (v.16), and open infanticide by drowning (v.22).'),
('Exodus', 1, 'adults', 4, 'How does the text present the midwives'' fear of God as a theological statement?', 'Their fear of God overrode their fear of Pharaoh — God rewarded them with families of their own, establishing that divine authority supersedes all human authority', 'Fear of God made them weak', 'They feared God and Pharaoh equally', 'Their fear was superstitious', 'a', 'Exodus 1:17,20-21 — "The midwives feared God, and did not as the king of Egypt commanded them... Therefore God dealt well with the midwives... and made them houses." Their civil disobedience is the first recorded act of resistance to unjust authority in Scripture.'),
('Exodus', 1, 'adults', 5, 'What irony pervades Pharaoh''s attempts to suppress Israel in chapter 1?', 'Every measure intended to diminish Israel instead causes them to multiply more — God''s sovereign purpose cannot be thwarted by human schemes', 'Pharaoh''s plans succeeded perfectly', 'The Israelites cooperated willingly', 'There is no irony in the chapter', 'a', 'Exodus 1:12 — "But the more they afflicted them, the more they multiplied and grew." This ironic reversal is a major theological theme: human opposition to God''s purposes paradoxically advances them.'),
('Exodus', 1, 'adults', 6, 'Why does the text name the midwives (Shiphrah and Puah) but not name the Pharaoh?', 'The named midwives are honoured for their faithfulness to God, while the unnamed Pharaoh is diminished — reflecting God''s value system where obedience matters more than political power', 'It was an oversight by the author', 'Pharaoh''s name was unknown', 'Naming kings was forbidden', 'a', 'Shiphrah ("beautiful") and Puah ("splendid") are preserved by name while the supposedly all-powerful Pharaoh remains anonymous. This literary choice elevates humble obedience over worldly power.'),
('Exodus', 1, 'adults', 7, 'What does Pharaoh''s phrase "let us deal wisely with them" reveal about his character?', 'It reveals calculated political cruelty disguised as pragmatic wisdom — his "wisdom" is the opposite of godly wisdom, employing oppression and genocide as state policy', 'It shows genuine concern for his people', 'It demonstrates military strategy', 'It reflects benevolent leadership', 'a', 'Exodus 1:10 — "Come on, let us deal wisely with them." The Hebrew nithchakk''mah ("let us act shrewdly") reveals a cold, calculating approach to genocide — worldly "wisdom" that stands in stark contrast to the midwives'' godly fear.'),
('Exodus', 1, 'adults', 8, 'How does Exodus 1 connect to the broader Genesis-Exodus narrative arc?', 'It fulfils God''s prophecy to Abraham in Genesis 15:13-14 that his descendants would be strangers in a land not theirs, afflicted for four hundred years, but would come out with great substance', 'It contradicts the promises made to Abraham', 'It begins a completely new story unrelated to Genesis', 'It focuses solely on Egyptian history', 'a', 'Genesis 15:13-14 — "Know of a surety that thy seed shall be a stranger in a land that is not theirs, and shall serve them; and they shall afflict them four hundred years... and afterward shall they come out with great substance." Exodus 1 is the direct fulfilment of this prophecy.');

-- ═══ Exodus Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 2, 'kids', 1, 'Where did Moses'' mother hide baby Moses?', 'In a basket made of bulrushes, placed in the river', 'Under a pile of blankets', 'In a cave in the mountains', 'Behind the pyramids', 'a', 'Exodus 2:3 — "And when she could not longer hide him, she took for him an ark of bulrushes, and daubed it with slime and with pitch, and put the child therein; and she laid it in the flags by the river''s brink."'),
('Exodus', 2, 'kids', 2, 'Who found baby Moses in the river?', 'Pharaoh''s daughter', 'A fisherman', 'Moses'' father', 'An Egyptian soldier', 'a', 'Exodus 2:5-6 — "And the daughter of Pharaoh came down to wash herself at the river... and when she had opened it, she saw the child: and, behold, the babe wept."'),
('Exodus', 2, 'kids', 3, 'Where did Moses run away to when he grew up?', 'The land of Midian', 'Back to Canaan', 'To Babylon', 'To the desert of Sinai', 'a', 'Exodus 2:15 — "Now when Pharaoh heard this thing, he sought to slay Moses. But Moses fled from the face of Pharaoh, and dwelt in the land of Midian."'),
-- Teens
('Exodus', 2, 'teens', 1, 'What did Moses'' sister Miriam do when the basket was placed in the river?', 'She stood afar off to watch what would happen to him', 'She went home and forgot about it', 'She jumped in to rescue him', 'She told Pharaoh about the baby', 'a', 'Exodus 2:4 — "And his sister stood afar off, to wit what would be done to him."'),
('Exodus', 2, 'teens', 2, 'What clever suggestion did Miriam make to Pharaoh''s daughter?', 'She offered to find a Hebrew nurse for the baby — and brought Moses'' own mother', 'She asked to keep the baby herself', 'She asked Pharaoh''s daughter to pay gold', 'She told her to throw the baby back', 'a', 'Exodus 2:7-8 — "Then said his sister to Pharaoh''s daughter, Shall I go and call to thee a nurse of the Hebrew women, that she may nurse the child for thee?... And the maid went and called the child''s mother."'),
('Exodus', 2, 'teens', 3, 'Why did Moses kill the Egyptian?', 'He saw the Egyptian beating a Hebrew, one of his brethren, and struck him down', 'The Egyptian insulted Pharaoh', 'The Egyptian stole from him', 'The Egyptian refused to work', 'a', 'Exodus 2:11-12 — "And it came to pass in those days, when Moses was grown, that he went out unto his brethren, and looked on their burdens: and he spied an Egyptian smiting an Hebrew, one of his brethren."'),
('Exodus', 2, 'teens', 4, 'What did Moses do at the well in Midian?', 'He helped the seven daughters of Reuel (Jethro) water their flock by driving away the shepherds who were bothering them', 'He drank water and left', 'He dug a new well', 'He asked for directions to Egypt', 'a', 'Exodus 2:16-17 — "Now the priest of Midian had seven daughters: and they came and drew water... And the shepherds came and drove them away: but Moses stood up and helped them, and watered their flock."'),
('Exodus', 2, 'teens', 5, 'What did Moses name his son and why?', 'Gershom — meaning "a stranger in a strange land," because Moses was a foreigner in Midian', 'Isaac — meaning laughter', 'Aaron — meaning high mountain', 'Joseph — meaning added', 'a', 'Exodus 2:22 — "And she bare him a son, and he called his name Gershom: for he said, I have been a stranger in a strange land."'),
-- Adults
('Exodus', 2, 'adults', 1, 'How does the "ark of bulrushes" (tevah) connect Moses to Noah?', 'The same Hebrew word tevah is used only for Noah''s ark and Moses'' basket — both are vessels of divine deliverance through water, drawing a typological parallel between the two salvation events', 'It is a completely different word', 'The connection is coincidental', 'Tevah means "punishment"', 'a', 'Exodus 2:3 — The Hebrew word tevah (תֵּבָה) is used only twice in the OT: for Noah''s ark (Genesis 6:14) and Moses'' basket. Both preserve a righteous remnant through waters of judgment.'),
('Exodus', 2, 'adults', 2, 'What theological irony exists in Pharaoh''s daughter raising Moses?', 'The instrument of Israel''s future deliverance is raised and educated in Pharaoh''s own household — God uses Pharaoh''s own family and resources to prepare the deliverer against him', 'There is no irony in the situation', 'Pharaoh planned this outcome', 'Moses was never in Pharaoh''s house', 'a', 'Exodus 2:10 — "And the child grew, and she brought him unto Pharaoh''s daughter, and he became her son." The very king who decreed Hebrew infanticide unknowingly funds and trains Israel''s liberator.'),
('Exodus', 2, 'adults', 3, 'What does Moses'' act of killing the Egyptian reveal about his character at this stage?', 'He had genuine concern for his people but acted in human strength and anger rather than by divine commission — resulting in failure, exposure, and forty years of exile', 'He acted perfectly according to God''s plan', 'He was indifferent to Hebrew suffering', 'He was trained by God to kill', 'a', 'Exodus 2:11-14 — Moses'' impulse was right (identifying with his brethren) but his method was wrong (murder and concealment). Acts 7:25 says "he supposed his brethren would have understood," but they did not.'),
('Exodus', 2, 'adults', 4, 'What is the significance of Moses'' forty years in Midian for his later role?', 'God used the desert years to transform Moses from an Egyptian prince into a humble shepherd — learning the wilderness terrain, patience, and dependence on God before leading Israel through the same wilderness', 'The years were wasted time', 'Moses forgot everything about Egypt', 'Midian was a prosperous city', 'a', 'Exodus 2:15-22 — Moses spent forty years shepherding in the very wilderness he would later traverse with Israel (Acts 7:29-30). God''s preparation often involves long seasons of obscurity and humility.'),
('Exodus', 2, 'adults', 5, 'How do the final verses (2:23-25) set up the exodus narrative?', 'Four Hebrew verbs describe God''s response — He heard their groaning, remembered His covenant, looked upon them, and had respect unto them — showing God''s initiative in salvation', 'God was unaware of Israel''s suffering', 'The king of Egypt repented', 'Moses planned the rescue alone', 'a', 'Exodus 2:23-25 — "God heard their groaning, and God remembered his covenant with Abraham, with Isaac, and with Jacob. And God looked upon the children of Israel, and God had respect unto them." Four verbs of divine engagement launch the redemption story.'),
('Exodus', 2, 'adults', 6, 'What does "God remembered his covenant" mean theologically?', 'Not that God had forgotten, but that He now acts on His covenant promises — "remembering" in Hebrew (zakar) means to bring something to active attention and act upon it', 'God had literally forgotten the covenant', 'The covenant had expired', 'A new covenant replaced the old one', 'a', 'Exodus 2:24 — "And God remembered his covenant with Abraham, with Isaac, and with Jacob." The Hebrew zakar does not imply prior forgetfulness but the commencement of purposeful action based on prior commitment.'),
('Exodus', 2, 'adults', 7, 'How does the name Moses (Mosheh) carry a double meaning?', 'Pharaoh''s daughter named him from the Hebrew mashah ("to draw out") because she drew him from water — but Moses would later "draw out" all of Israel from Egypt, making his name prophetic', 'The name has only one meaning', 'Moses named himself', 'The name means "prince of Egypt"', 'a', 'Exodus 2:10 — "And she called his name Moses: and she said, Because I drew him out of the water." The name anticipates his role as the one who draws Israel out of Egyptian bondage.'),
('Exodus', 2, 'adults', 8, 'What tribe was Moses from, and why is this significant?', 'The tribe of Levi (2:1) — the same tribe later appointed for priestly service, connecting Moses'' role as mediator between God and Israel to the priestly function of his tribe', 'The tribe of Judah', 'The tribe of Benjamin', 'The tribe of Ephraim', 'a', 'Exodus 2:1 — "And there went a man of the house of Levi, and took to wife a daughter of Levi." Moses'' Levitical lineage connects to his mediatorial role and the future Levitical priesthood.');

-- ═══ Exodus Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 3, 'kids', 1, 'What strange thing did Moses see on the mountain?', 'A bush that was on fire but did not burn up', 'A rainbow in the sky', 'A giant tree that could talk', 'A river flowing uphill', 'a', 'Exodus 3:2 — "And the angel of the LORD appeared unto him in a flame of fire out of the midst of a bush: and he looked, and, behold, the bush burned with fire, and the bush was not consumed."'),
('Exodus', 3, 'kids', 2, 'What did God tell Moses to take off at the burning bush?', 'His shoes, because the ground was holy', 'His coat', 'His hat', 'His belt', 'a', 'Exodus 3:5 — "And he said, Draw not nigh hither: put off thy shoes from off thy feet, for the place whereon thou standest is holy ground."'),
('Exodus', 3, 'kids', 3, 'What name did God use for Himself when Moses asked?', 'I AM THAT I AM', 'The Great King', 'The Almighty Warrior', 'The Heavenly Father', 'a', 'Exodus 3:14 — "And God said unto Moses, I AM THAT I AM: and he said, Thus shalt thou say unto the children of Israel, I AM hath sent me unto you."'),
-- Teens
('Exodus', 3, 'teens', 1, 'What was Moses doing when he saw the burning bush?', 'Keeping the flock of his father-in-law Jethro on the backside of the desert, at the mountain of God called Horeb', 'Fishing by the river', 'Building a house in Midian', 'Trading in the marketplace', 'a', 'Exodus 3:1 — "Now Moses kept the flock of Jethro his father in law, the priest of Midian: and he led the flock to the backside of the desert, and came to the mountain of God, even to Horeb."'),
('Exodus', 3, 'teens', 2, 'How did God identify Himself to Moses at the bush?', 'As the God of Abraham, the God of Isaac, and the God of Jacob', 'As the god of Egypt', 'As the god of Midian', 'As the god of the mountain', 'a', 'Exodus 3:6 — "Moreover he said, I am the God of thy father, the God of Abraham, the God of Isaac, and the God of Jacob. And Moses hid his face; for he was afraid to look upon God."'),
('Exodus', 3, 'teens', 3, 'What did God say He would do for the Israelites?', 'Bring them out of Egypt into a good and large land flowing with milk and honey', 'Make them rulers of Egypt', 'Give them an army to conquer Pharaoh', 'Send them to Babylon', 'a', 'Exodus 3:8 — "And I am come down to deliver them out of the hand of the Egyptians, and to bring them up out of that land unto a good land and a large, unto a land flowing with milk and honey."'),
('Exodus', 3, 'teens', 4, 'What was Moses'' first objection to God''s call?', '"Who am I, that I should go unto Pharaoh?" — he felt unworthy and inadequate', 'He said he was too busy', 'He said he was too old', 'He said he was too rich', 'a', 'Exodus 3:11 — "And Moses said unto God, Who am I, that I should go unto Pharaoh, and that I should bring forth the children of Israel out of Egypt?"'),
('Exodus', 3, 'teens', 5, 'What sign did God give Moses that He had truly sent him?', '"When thou hast brought forth the people out of Egypt, ye shall serve God upon this mountain"', 'A bolt of lightning', 'A voice from heaven heard by everyone', 'An earthquake', 'a', 'Exodus 3:12 — "And he said, Certainly I will be with thee; and this shall be a token unto thee, that I have sent thee: When thou hast brought forth the people out of Egypt, ye shall serve God upon this mountain."'),
-- Adults
('Exodus', 3, 'adults', 1, 'What is the theological significance of the burning bush?', 'It represents God''s presence that illuminates without consuming — a holy God dwelling with His people without destroying them, and may prefigure the Incarnation where divinity inhabits creation', 'It was a natural desert phenomenon', 'It was Moses'' imagination', 'It symbolised Pharaoh''s power', 'a', 'Exodus 3:2-4 — The bush burns but is not consumed. This paradox — fire (divine holiness) inhabiting a common thornbush without destroying it — illustrates the mystery of divine immanence and transcendence.'),
('Exodus', 3, 'adults', 2, 'What does "I AM THAT I AM" (Ehyeh Asher Ehyeh) reveal about God''s nature?', 'It declares God''s self-existence, eternality, and sovereignty — He is the uncaused cause, dependent on nothing, and His name is a declaration of absolute being, not derived from any external source', 'It is simply a refusal to give a name', 'It means God does not know His own name', 'It is a common name in ancient cultures', 'a', 'Exodus 3:14 — Ehyeh Asher Ehyeh can be rendered "I AM THAT I AM," "I WILL BE WHAT I WILL BE," or "I cause to be what is." It reveals the self-existent, eternal, and covenantally faithful nature of God.'),
('Exodus', 3, 'adults', 3, 'How does Jesus'' use of "I AM" in the Gospel of John connect to Exodus 3:14?', 'Jesus'' seven "I AM" statements (John 8:58 — "Before Abraham was, I am") directly claim the divine name from Exodus 3:14, asserting His deity and pre-existence — which the Jews understood as blasphemy', 'There is no connection between the two', 'Jesus was simply using a common expression', 'The Gospel of John misquotes Exodus', 'a', 'John 8:58 — "Jesus said unto them, Verily, verily, I say unto you, Before Abraham was, I am." The Jews took up stones (v.59), recognising this as a claim to the divine name revealed at the burning bush.'),
('Exodus', 3, 'adults', 4, 'What peoples occupied the Promised Land that God listed in verse 8?', 'The Canaanites, Hittites, Amorites, Perizzites, Hivites, and Jebusites — six nations occupying the land promised to Abraham''s descendants', 'Only the Egyptians', 'Only the Philistines', 'No one occupied the land', 'a', 'Exodus 3:8 — "Unto the place of the Canaanites, and the Hittites, and the Amorites, and the Perizzites, and the Hivites, and the Jebusites." These nations fulfilled Genesis 15:16 where God told Abraham the iniquity of the Amorites was not yet full.'),
('Exodus', 3, 'adults', 5, 'What is the significance of God saying "I am come down to deliver them"?', 'It shows God''s personal intervention in history — not merely directing from heaven but actively entering the situation, a pattern that culminates in the Incarnation', 'God literally descended physically', 'God sent an angel instead', 'God was already living in Egypt', 'a', 'Exodus 3:8 — "I am come down to deliver them." This anthropomorphic language reveals a God who acts within human history. The verb yarad ("come down") appears at crucial moments of divine intervention (Genesis 11:7, 18:21).'),
('Exodus', 3, 'adults', 6, 'Why does God answer Moses'' "Who am I?" with "Certainly I will be with thee" rather than listing Moses'' qualifications?', 'God redirects the question from Moses'' adequacy to God''s sufficiency — the success of the mission depends not on the messenger''s abilities but on God''s presence', 'God did not know Moses'' qualifications', 'God wanted Moses to figure it out himself', 'God was testing Moses'' humility', 'a', 'Exodus 3:11-12 — Moses asks "Who am I?" and God answers "I will be with thee." The divine response shifts the focus from human capacity to divine companionship — a pattern repeated throughout Scripture (Judges 6:12, Jeremiah 1:8, Matthew 28:20).'),
('Exodus', 3, 'adults', 7, 'How does the "land flowing with milk and honey" function as covenant language?', 'It describes agricultural abundance — milk from livestock and honey from wild bees or date palms — symbolising a land of provision that God gives as covenant fulfilment, contrasting Egypt''s land of oppression', 'It is a literal description of rivers of milk and honey', 'It means the land is difficult to farm', 'It refers to Egypt', 'a', 'Exodus 3:8 — "A land flowing with milk and honey" appears over twenty times in the OT as a fixed expression for the Promised Land''s bounty, always connected to covenant promise.'),
('Exodus', 3, 'adults', 8, 'What does the instruction to "spoil the Egyptians" (3:22) reveal about God''s plan?', 'Israel would receive silver, gold, and garments from the Egyptians — fulfilling Genesis 15:14 ("shall come out with great substance") and providing materials later used for the tabernacle', 'God encouraged theft', 'The Egyptians would voluntarily give everything', 'It was a metaphor for spiritual victory', 'a', 'Exodus 3:21-22 — "I will give this people favour in the sight of the Egyptians... ye shall spoil the Egyptians." The Hebrew sha''al means "to ask" — the Israelites asked and the Egyptians willingly gave, fulfilling Genesis 15:14.');

-- ═══ Exodus Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 4, 'kids', 1, 'What did Moses'' rod turn into when he threw it on the ground?', 'A serpent (snake)', 'A bird', 'A fish', 'A flower', 'a', 'Exodus 4:3 — "And he said, Cast it on the ground. And he cast it on the ground, and it became a serpent; and Moses fled from before it."'),
('Exodus', 4, 'kids', 2, 'Who did God say would help Moses speak?', 'His brother Aaron', 'His wife Zipporah', 'His father Jethro', 'His sister Miriam', 'a', 'Exodus 4:14 — "And the anger of the LORD was kindled against Moses, and he said, Is not Aaron the Levite thy brother? I know that he can speak well."'),
('Exodus', 4, 'kids', 3, 'What happened to Moses'' hand when he put it inside his cloak?', 'It became white as snow with leprosy, and when he put it back again it was healed', 'It grew very large', 'It turned into gold', 'It disappeared', 'a', 'Exodus 4:6-7 — "And the LORD said furthermore unto him, Put now thine hand into thy bosom. And when he took it out, behold, his hand was leprous as snow."'),
-- Teens
('Exodus', 4, 'teens', 1, 'What three signs did God give Moses to prove his divine commission?', 'Rod turned to serpent, hand became leprous and healed, and water from the Nile would turn to blood on dry land', 'Thunder, lightning, and earthquake', 'A rainbow, a star, and a cloud', 'Parting the sea, manna, and fire', 'a', 'Exodus 4:2-9 — Three signs of escalating severity: rod/serpent (v.3), leprous hand (v.6), and water to blood (v.9).'),
('Exodus', 4, 'teens', 2, 'What was Moses'' excuse about his speech?', 'He said he was not eloquent but slow of speech and of a slow tongue', 'He said he spoke too quickly', 'He said he only spoke Egyptian', 'He said he was too young', 'a', 'Exodus 4:10 — "And Moses said unto the LORD, O my Lord, I am not eloquent, neither heretofore, nor since thou hast spoken unto thy servant: but I am slow of speech, and of a slow tongue."'),
('Exodus', 4, 'teens', 3, 'How did God respond to Moses'' complaint about not being a good speaker?', '"Who hath made man''s mouth? have not I the LORD? Now therefore go, and I will be with thy mouth, and teach thee what thou shalt say"', 'He agreed Moses was unqualified', 'He found someone else', 'He cancelled the mission', 'a', 'Exodus 4:11-12 — "And the LORD said unto him, Who hath made man''s mouth? or who maketh the dumb, or deaf, or the seeing, or the blind? have not I the LORD?"'),
('Exodus', 4, 'teens', 4, 'What message did God tell Moses to deliver to Pharaoh?', '"Israel is my son, even my firstborn... Let my son go, that he may serve me: and if thou refuse, I will slay thy son, even thy firstborn"', '"Give Israel your gold"', '"Build Israel a new city"', '"Let Israel rule Egypt"', 'a', 'Exodus 4:22-23 — "And thou shalt say unto Pharaoh, Thus saith the LORD, Israel is my son, even my firstborn: And I say unto thee, Let my son go, that he may serve me: and if thou refuse to let him go, behold, I will slay thy son, even thy firstborn."'),
('Exodus', 4, 'teens', 5, 'What did the Israelites do when Aaron told them everything and showed the signs?', 'The people believed, and bowed their heads and worshipped God', 'They refused to listen', 'They ran away from Aaron', 'They complained about Moses', 'a', 'Exodus 4:31 — "And the people believed: and when they heard that the LORD had visited the children of Israel, and that he had looked upon their affliction, then they bowed their heads and worshipped."'),
-- Adults
('Exodus', 4, 'adults', 1, 'How does the rod-to-serpent sign relate to Egyptian religious symbolism?', 'The serpent (nachash) was a symbol of Egyptian royal power (the uraeus cobra on Pharaoh''s crown) — Moses'' rod consuming such imagery demonstrates Yahweh''s authority over Egypt''s gods and king', 'Serpents were irrelevant to Egyptian culture', 'The sign had no symbolic meaning', 'It was simply a magic trick', 'a', 'Exodus 4:3-4 — The serpent was the symbol of Egyptian royalty and divine power (the uraeus). Moses'' rod becoming a serpent and then being recaptured demonstrates God''s sovereignty over the very symbols of Pharaoh''s authority.'),
('Exodus', 4, 'adults', 2, 'What does God''s anger at Moses'' final objection ("send someone else") reveal?', 'Even God''s patience has limits — Moses'' persistent resistance despite four answered objections moved from humble concern to faithless disobedience, yet God graciously accommodated him with Aaron rather than rejecting him', 'God was being unfair', 'Moses was right to refuse', 'God immediately replaced Moses', 'a', 'Exodus 4:13-14 — "And he said, O my Lord, send, I pray thee, by the hand of him whom thou wilt send. And the anger of the LORD was kindled against Moses." Moses'' five excuses (3:11, 3:13, 4:1, 4:10, 4:13) progress from genuine concern to outright refusal.'),
('Exodus', 4, 'adults', 3, 'What is the theological significance of God calling Israel "my son, even my firstborn"?', 'It establishes a corporate sonship — Israel has a unique covenant relationship with God as His firstborn nation, which foreshadows both the plague on Egypt''s firstborn and the ultimate Firstborn, Christ', 'It means Israel was literally God''s physical child', 'It was a common title for all nations', 'It had no special meaning', 'a', 'Exodus 4:22 — "Israel is my son, even my firstborn." This is the first time God calls Israel His son, establishing the theological framework for the final plague (death of Egypt''s firstborn) and Paul''s adoption theology (Romans 9:4).'),
('Exodus', 4, 'adults', 4, 'What is the puzzling incident in verses 24-26 where the LORD sought to kill Moses?', 'Moses had apparently neglected to circumcise his son — a serious breach of the Abrahamic covenant (Genesis 17:14); Zipporah performed the circumcision, calling Moses a "bloody husband," and God relented', 'God was angry about the burning bush conversation', 'It was a test of Zipporah''s faith', 'Moses had broken a Midianite custom', 'a', 'Exodus 4:24-26 — "And it came to pass by the way in the inn, that the LORD met him, and sought to kill him." Moses could not lead Israel into covenant faithfulness while neglecting the covenant sign in his own family.'),
('Exodus', 4, 'adults', 5, 'How does Moses'' relationship with Aaron as "prophet" and "spokesman" mirror God''s relationship with prophets?', 'God tells Moses what to say, Moses tells Aaron, and Aaron speaks to the people — paralleling the prophetic chain where God reveals to the prophet and the prophet speaks to the people', 'Aaron was superior to Moses', 'Moses and Aaron were equals', 'The arrangement was Moses'' idea', 'a', 'Exodus 4:15-16 — "And thou shalt speak unto him, and put words in his mouth... And he shall be thy spokesman unto the people: and he shall be, even he shall be to thee instead of a mouth, and thou shalt be to him instead of God."'),
('Exodus', 4, 'adults', 6, 'What pattern of divine accommodation is seen in God providing Aaron?', 'God adapts His plan to human weakness without abandoning His purposes — Aaron becomes the spokesman, but this accommodation later brings complications (Aaron''s role in the golden calf incident)', 'God''s original plan failed', 'Aaron was always meant to be the leader', 'God had no other options', 'a', 'Exodus 4:14-16 — God''s anger at Moses'' refusal leads to the provision of Aaron. This gracious accommodation has consequences: the same Aaron later fashions the golden calf (ch.32), suggesting that God''s Plan A is always preferable to our negotiated Plan B.'),
('Exodus', 4, 'adults', 7, 'How do the three signs escalate in nature and significance?', 'Rod to serpent (power over nature), leprous hand (power over disease/uncleanness), water to blood (power over Egypt''s lifeblood, the Nile) — each demonstrates increasing divine authority over different domains', 'They are random miracles with no progression', 'They all demonstrate the same thing', 'The order is insignificant', 'a', 'Exodus 4:2-9 — The signs progress from natural world (rod/serpent), to human body (leprosy), to Egypt''s sacred river (blood) — an escalation that foreshadows the plagues and demonstrates God''s total sovereignty.'),
('Exodus', 4, 'adults', 8, 'What does "I will harden Pharaoh''s heart" (4:21) introduce theologically?', 'It introduces the tension between divine sovereignty and human responsibility — God announces He will harden Pharaoh''s heart, yet Pharaoh also hardens his own heart; both are true without contradiction in the Hebrew worldview', 'God forced Pharaoh to sin against his will', 'Pharaoh had no free choice', 'It was a mistranslation', 'a', 'Exodus 4:21 — "I will harden his heart, that he shall not let the people go." Three Hebrew verbs are used: chazaq (strengthen), kaved (make heavy), and qashah (make stubborn). In plagues 1-5, Pharaoh hardens his own heart; from plague 6 onward, God hardens it — confirming Pharaoh''s own choice.');

-- ═══ Exodus Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 5, 'kids', 1, 'What did Moses and Aaron ask Pharaoh to do?', 'Let the people of Israel go so they could worship God in the wilderness', 'Give the Israelites gold', 'Build the Israelites a new city', 'Let the Israelites go swimming', 'a', 'Exodus 5:1 — "And afterward Moses and Aaron went in, and told Pharaoh, Thus saith the LORD God of Israel, Let my people go, that they may hold a feast unto me in the wilderness."'),
('Exodus', 5, 'kids', 2, 'What did Pharaoh say about the LORD?', '"Who is the LORD, that I should obey his voice? I know not the LORD"', '"I will obey the LORD immediately"', '"The LORD is my friend"', '"Tell me more about the LORD"', 'a', 'Exodus 5:2 — "And Pharaoh said, Who is the LORD, that I should obey his voice to let Israel go? I know not the LORD, neither will I let Israel go."'),
('Exodus', 5, 'kids', 3, 'What cruel thing did Pharaoh do to make the Israelites'' work harder?', 'He stopped giving them straw to make bricks, but still demanded the same number of bricks', 'He made them work only at night', 'He took away their food', 'He made them carry heavy rocks', 'a', 'Exodus 5:7-8 — "Ye shall no more give the people straw to make brick, as heretofore: let them go and gather straw for themselves. And the tale of the bricks, which they did make heretofore, ye shall lay upon them."'),
-- Teens
('Exodus', 5, 'teens', 1, 'How did Pharaoh interpret Moses'' request for Israel to worship God?', 'He called it laziness — "Ye are idle, ye are idle" — and saw the request as an excuse to stop working', 'He considered it a reasonable request', 'He asked to learn about their God', 'He offered to worship with them', 'a', 'Exodus 5:8,17 — "For they be idle; therefore they cry, saying, Let us go and sacrifice to our God... Ye are idle, ye are idle: therefore ye say, Let us go and do sacrifice to the LORD."'),
('Exodus', 5, 'teens', 2, 'What did the Israelite officers say to Moses after Pharaoh increased their burdens?', '"The LORD look upon you, and judge; because ye have made our savour to be abhorred in the eyes of Pharaoh" — they blamed Moses for making things worse', 'They thanked Moses for helping', 'They asked Moses to negotiate more', 'They praised God for sending Moses', 'a', 'Exodus 5:21 — "And they said unto them, The LORD look upon you, and judge; because ye have made our savour to be abhorred in the eyes of Pharaoh, and in the eyes of his servants, to put a sword in their hand to slay us."'),
('Exodus', 5, 'teens', 3, 'How did Moses respond to the people''s complaints?', 'He returned to the LORD and asked, "Lord, wherefore hast thou so evil entreated this people? why is it that thou hast sent me?"', 'He yelled at the people', 'He gave up and went home', 'He told them to fight Pharaoh', 'a', 'Exodus 5:22 — "And Moses returned unto the LORD, and said, Lord, wherefore hast thou so evil entreated this people? why is it that thou hast sent me?"'),
('Exodus', 5, 'teens', 4, 'What did the taskmasters and officers tell the people about their brick quota?', 'They said the daily quota would not be reduced at all even though they now had to gather their own straw', 'The quota was reduced by half', 'They were given extra time', 'They could use mud instead of straw', 'a', 'Exodus 5:13-14 — "And the taskmasters hasted them, saying, Fulfil your works, your daily tasks, as when there was straw. And the officers of the children of Israel... were beaten."'),
('Exodus', 5, 'teens', 5, 'What complaint did Moses make to God at the end of the chapter?', '"Since I came to Pharaoh to speak in thy name, he hath done evil to this people; neither hast thou delivered thy people at all"', '"I should have stayed in Midian"', '"Aaron is not helping me"', '"The people love me too much"', 'a', 'Exodus 5:23 — "For since I came to Pharaoh to speak in thy name, he hath done evil to this people; neither hast thou delivered thy people at all."'),
-- Adults
('Exodus', 5, 'adults', 1, 'What does Pharaoh''s question "Who is the LORD?" reveal about the theological conflict?', 'It frames the entire exodus as a contest between Yahweh and Pharaoh (who claimed divine status) — the plagues will progressively answer Pharaoh''s question by demonstrating who the LORD truly is', 'Pharaoh was genuinely curious about God', 'It was a diplomatic formality', 'Pharaoh already knew the LORD', 'a', 'Exodus 5:2 — "Who is the LORD, that I should obey his voice?" This question drives the plague narrative. God later says, "The Egyptians shall know that I am the LORD" (7:5). The plagues are God''s answer to Pharaoh''s arrogant question.'),
('Exodus', 5, 'adults', 2, 'How does Pharaoh''s strategy of removing straw function as psychological warfare?', 'It punishes the Israelites for Moses'' request, turns them against their own leaders, and attempts to break their spirit and will to follow Moses — a divide-and-conquer tactic', 'It was simply an economic decision', 'Straw was genuinely unavailable', 'Pharaoh was being fair', 'a', 'Exodus 5:6-9 — The straw removal serves multiple purposes: increased physical suffering, impossibility of meeting quotas, resulting beatings, and most importantly, turning the Israelite officers against Moses. Pharaoh''s strategy nearly succeeds (v.21).'),
('Exodus', 5, 'adults', 3, 'What pattern does chapter 5 establish for the exodus narrative — things getting worse before they get better?', 'It introduces the principle that divine deliverance often follows increased suffering — obedience to God initially worsens the situation before God acts, testing faith in the process', 'Things always improve immediately when God acts', 'Suffering indicates God has abandoned them', 'Moses made a mistake by going to Pharaoh', 'a', 'The pattern of "worse before better" is a consistent biblical motif: Joseph''s prison before palace, Israel''s Red Sea trap before crossing, Good Friday before Easter. Chapter 5 tests whether Israel and Moses will trust God through the darkening.'),
('Exodus', 5, 'adults', 4, 'How does Moses'' prayer in 5:22-23 model honest prayer?', 'Moses brings his confusion, frustration, and accusation directly to God rather than abandoning the mission — he does not hide his doubts but channels them toward God in prayer', 'Moses was being disrespectful', 'Moses should have kept quiet', 'Moses lost his faith completely', 'a', 'Exodus 5:22-23 — Moses'' raw prayer ("why hast thou so evil entreated this people?") echoes the psalms of lament. Scripture consistently validates bringing honest questions to God (cf. Habakkuk 1:2, Psalm 13:1, Jeremiah 20:18).'),
('Exodus', 5, 'adults', 5, 'What socio-economic detail does the straw requirement reveal about ancient brick-making?', 'Straw (teben) was mixed with Nile clay as a binding agent — its fibres prevent cracking when bricks dry; without straw, bricks crumble, making the quota physically impossible without drastically more labour', 'Straw was purely decorative', 'Straw made bricks lighter', 'Straw was used for colour', 'a', 'Exodus 5:7 — "Ye shall no more give the people straw to make brick." Archaeological finds in Egypt confirm straw-tempered mud bricks. The straw''s organic fibres bind the clay, preventing cracks — its removal made the task genuinely impossible at the required pace.'),
('Exodus', 5, 'adults', 6, 'How does Pharaoh''s accusation of "laziness" function ideologically?', 'It reframes a religious request as insubordination — dismissing Israel''s worship of Yahweh as mere laziness allows Pharaoh to deny the legitimacy of their God while justifying increased oppression', 'Pharaoh was correct about their laziness', 'It was a neutral observation', 'Pharaoh was trying to help', 'a', 'Exodus 5:8,17 — "They be idle" (nirpim). Pharaoh''s ideological strategy redefines worship as sloth and divine mandate as rebellion. This is a recurring tactic of authoritarian power — delegitimising spiritual claims to maintain control.'),
('Exodus', 5, 'adults', 7, 'What role do the Israelite "officers" (shoterim) play in the narrative?', 'They are the middlemen caught between Pharaoh''s demands and the people''s inability to meet them — beaten by the taskmasters and turning their anger on Moses, they represent the tragic position of oppressed collaborators', 'They were Egyptian soldiers', 'They supported Moses fully', 'They were religious leaders', 'a', 'Exodus 5:14-15,19-21 — The shoterim (Israelite foremen) are beaten for the people''s shortfall, then confront Moses. Their plight illustrates how oppressive systems create internal conflict among the oppressed.'),
('Exodus', 5, 'adults', 8, 'How does chapter 5 set up the theology of the divine name revealed in chapter 6?', 'Moses'' failure and complaint ("thou hast not delivered") prompts God in chapter 6 to reveal Himself by His covenant name Yahweh and reaffirm His promises — the crisis of chapter 5 creates the context for deeper revelation', 'Chapter 5 and 6 are unrelated', 'Moses'' complaint was sinful', 'God ignores Moses'' prayer', 'a', 'Exodus 5:22-6:8 — Moses'' honest cry of failure in 5:22-23 is directly answered in 6:1-8 where God says, "Now shalt thou see what I will do to Pharaoh" and reveals Himself as Yahweh in covenant commitment.');

-- ═══════════════ CHAPTERS 6–10 ═══════════════

-- ═══ Exodus Chapter 6 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 6, 'kids', 1, 'What did God promise He would do for the Israelites?', 'Bring them out of Egypt with a stretched out arm and great judgments', 'Give them new clothes', 'Make them live in the desert forever', 'Send them to a different country', 'a', 'Exodus 6:6 — "Wherefore say unto the children of Israel, I am the LORD, and I will bring you out from under the burdens of the Egyptians, and I will rid you out of their bondage, and I will redeem you with a stretched out arm, and with great judgments."'),
('Exodus', 6, 'kids', 2, 'What special name did God say He would be known by?', 'The LORD (Jehovah/Yahweh) — He had not been fully known by this name before', 'The Great Pharaoh', 'The King of the Mountains', 'The Spirit of the River', 'a', 'Exodus 6:3 — "And I appeared unto Abraham, unto Isaac, and unto Jacob, by the name of God Almighty, but by my name JEHOVAH was I not known to them."'),
('Exodus', 6, 'kids', 3, 'Did the Israelites listen to Moses when he told them God''s promises?', 'No, they did not listen because of their cruel bondage and anguish of spirit', 'Yes, they were very happy', 'Yes, they immediately packed to leave', 'They asked for more details', 'a', 'Exodus 6:9 — "And Moses spake so unto the children of Israel: but they hearkened not unto Moses for anguish of spirit, and for cruel bondage."'),
-- Teens
('Exodus', 6, 'teens', 1, 'What four "I will" promises does God make in verses 6-7?', 'I will bring you out, I will rid you of bondage, I will redeem you, and I will take you to me for a people', 'I will give you gold, silver, food, and land', 'I will punish Pharaoh, destroy Egypt, build a temple, and crown a king', 'I will send rain, bring harvest, build homes, and give peace', 'a', 'Exodus 6:6-7 — "I will bring you out... I will rid you... I will redeem you... I will take you to me for a people, and I will be to you a God." These four promises correspond to the four cups of the Passover Seder.'),
('Exodus', 6, 'teens', 2, 'How did God appear to the patriarchs versus how He would now be known?', 'He appeared to Abraham, Isaac, and Jacob as God Almighty (El Shaddai), but by His name Yahweh (LORD) He was not fully known to them', 'He was always known as Yahweh', 'He never appeared to the patriarchs', 'He used a completely different name each time', 'a', 'Exodus 6:3 — "I appeared unto Abraham, unto Isaac, and unto Jacob, by the name of God Almighty, but by my name JEHOVAH was I not known to them." The patriarchs knew the name but not the full redemptive significance now being revealed.'),
('Exodus', 6, 'teens', 3, 'What is the genealogy in this chapter focused on?', 'The lineage of Moses and Aaron through the tribe of Levi — establishing their credentials as God''s chosen leaders', 'The kings of Egypt', 'The twelve tribes of Israel', 'The family of Pharaoh', 'a', 'Exodus 6:14-27 — The genealogy traces Reuben, Simeon, and then focuses on Levi → Kohath → Amram → Moses and Aaron, establishing their Levitical lineage and authority.'),
('Exodus', 6, 'teens', 4, 'Who were the parents of Moses and Aaron?', 'Amram and Jochebed — Amram married his father''s sister', 'Jacob and Rachel', 'Joseph and Asenath', 'Reuben and Leah', 'a', 'Exodus 6:20 — "And Amram took him Jochebed his father''s sister to wife; and she bare him Aaron and Moses."'),
('Exodus', 6, 'teens', 5, 'What objection did Moses repeat to God?', '"I am of uncircumcised lips" — meaning he was a poor speaker and Pharaoh would not listen to him', '"I am too old"', '"I am too young"', '"I have no money"', 'a', 'Exodus 6:12,30 — "And Moses spake before the LORD, saying, Behold, the children of Israel have not hearkened unto me; how then shall Pharaoh hear me, who am of uncircumcised lips?"'),
-- Adults
('Exodus', 6, 'adults', 1, 'What does "by my name JEHOVAH was I not known to them" mean given that the patriarchs used the name?', 'The patriarchs knew the name Yahweh but did not experience the full redemptive significance revealed through the exodus — "know" here means experiential knowledge of God acting in covenant faithfulness to redeem', 'The patriarchs never heard the name', 'The verse is a scribal error', 'It means exactly what it says literally', 'a', 'Exodus 6:3 — The Hebrew yada ("to know") often means experiential knowledge. The patriarchs received promises; this generation would see fulfilment. The name YHWH encompasses covenant-keeping action now being demonstrated.'),
('Exodus', 6, 'adults', 2, 'How do the four "I will" statements in 6:6-7 correspond to the four cups of the Passover Seder?', 'Cup of Sanctification (bring out), Cup of Deliverance (rid of bondage), Cup of Redemption (redeem), Cup of Praise (take as my people) — Jewish tradition links each promise to a cup', 'There is no connection to the Seder', 'The cups were invented later', 'Only two cups match', 'a', 'Exodus 6:6-7 — The four expressions of redemption became the basis for the four cups of wine in the Passover Seder. Jesus likely lifted the third cup (redemption) when He said "This cup is the new testament in my blood" (Luke 22:20).'),
('Exodus', 6, 'adults', 3, 'Why does the genealogy begin with Reuben and Simeon before focusing on Levi?', 'It follows birth order to locate Levi (the third son) within the tribal hierarchy — showing that Moses and Aaron''s authority comes from God''s election, not tribal primacy, since Levi was third-born', 'It was a random order', 'Reuben and Simeon were more important', 'The genealogy is alphabetical', 'a', 'Exodus 6:14-16 — By listing Reuben and Simeon first, the genealogy respects birth order while focusing on Levi. This positions Moses and Aaron within Israel''s tribal structure and legitimises their priestly-mediatorial role.'),
('Exodus', 6, 'adults', 4, 'What is the significance of the phrase "stretched out arm" in 6:6?', 'It is an anthropomorphism for God''s power in action — the "arm of the LORD" becomes a standard metaphor for divine intervention in salvation (cf. Isaiah 53:1, Deuteronomy 4:34)', 'It refers to Moses'' physical arm', 'It describes an Egyptian weapon', 'It is a reference to a statue', 'a', 'Exodus 6:6 — "I will redeem you with a stretched out arm." The Hebrew zeroa netuyah appears repeatedly in Deuteronomy (4:34, 5:15, 7:19, 26:8) and becomes a fixed expression for God''s mighty acts of deliverance.'),
('Exodus', 6, 'adults', 5, 'How does the phrase "I will be to you a God, and ye shall know that I am the LORD your God" encapsulate the covenant formula?', 'It contains the bilateral covenant formula found throughout Scripture — "I will be your God, you will be my people" — which defines the relationship from Sinai to the New Covenant (Jeremiah 31:33)', 'It is a one-sided declaration', 'It applies only to Moses', 'It was spoken to the Egyptians', 'a', 'Exodus 6:7 — "I will take you to me for a people, and I will be to you a God." This covenant formula (Bundesformel) recurs in Leviticus 26:12, Jeremiah 31:33, Ezekiel 36:28, and Revelation 21:3, spanning the entire biblical narrative.'),
('Exodus', 6, 'adults', 6, 'What does Moses'' metaphor "uncircumcised lips" mean?', 'Just as uncircumcised flesh is unfit for covenant, Moses considers his speech unfit for the task — the metaphor applies circumcision language to a non-physical attribute, suggesting inadequacy and unpreparedness', 'His lips were literally injured', 'He spoke a foreign language', 'He had a physical deformity', 'a', 'Exodus 6:12,30 — "Uncircumcised lips" (aral s''fatayim) uses the circumcision metaphor of being "closed" or "blocked" — cf. Jeremiah 6:10 ("uncircumcised ears") and Leviticus 26:41 ("uncircumcised hearts"). It denotes unfitness for sacred use.'),
('Exodus', 6, 'adults', 7, 'Why does the narrative pause for a genealogy at this point?', 'It establishes the legitimate credentials of Moses and Aaron at the critical moment before the plague narrative begins — anchoring the deliverers in Israel''s genealogical record and the tribe of Levi', 'The author ran out of material', 'It was inserted by a later editor randomly', 'Genealogies were required by Egyptian law', 'a', 'Exodus 6:14-27 — The genealogy serves a narrative function: at the threshold of the confrontation with Pharaoh, it formally identifies the protagonists. The concluding verse (6:27) explicitly states: "These are that Moses and Aaron" — authenticating their identity.'),
('Exodus', 6, 'adults', 8, 'How does God''s response in 6:1 ("Now shalt thou see") address Moses'' complaint in 5:22-23?', 'God does not rebuke Moses but reassures him — "Now" implies that the previous failure was within God''s plan; the worsening conditions will make the deliverance more dramatic and unmistakably divine', 'God ignores Moses completely', 'God punishes Moses for complaining', 'God sends someone else', 'a', 'Exodus 6:1 — "Then the LORD said unto Moses, Now shalt thou see what I will do to Pharaoh: for with a strong hand shall he let them go, and with a strong hand shall he drive them out of his land." The emphatic "now" contrasts human failure with imminent divine action.');

-- ═══ Exodus Chapter 7 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 7, 'kids', 1, 'What happened when Aaron threw down his rod before Pharaoh?', 'It became a serpent, and when the magicians did the same, Aaron''s rod swallowed up their rods', 'It broke into pieces', 'It turned into a flower', 'It floated in the air', 'a', 'Exodus 7:10,12 — "And Aaron cast down his rod before Pharaoh, and before his servants, and it became a serpent... but Aaron''s rod swallowed up their rods."'),
('Exodus', 7, 'kids', 2, 'What was the first plague God sent on Egypt?', 'The water of the river Nile was turned into blood', 'Frogs came everywhere', 'It became very dark', 'There was a big earthquake', 'a', 'Exodus 7:20 — "And Moses and Aaron did so, as the LORD commanded; and he lifted up the rod, and smote the waters that were in the river... and all the waters that were in the river were turned to blood."'),
('Exodus', 7, 'kids', 3, 'Did Pharaoh let the people go after the water turned to blood?', 'No, his heart was hardened and he would not listen', 'Yes, he let them go right away', 'He asked for more time', 'He offered them gold instead', 'a', 'Exodus 7:22 — "And Pharaoh''s heart was hardened, neither did he hearken unto them; as the LORD had said."'),
-- Teens
('Exodus', 7, 'teens', 1, 'What role did God assign Moses in relation to Pharaoh?', 'God made Moses "a god to Pharaoh" and Aaron his prophet', 'Moses was to be Pharaoh''s servant', 'Moses was to be Pharaoh''s advisor', 'Moses was to be Pharaoh''s general', 'a', 'Exodus 7:1 — "And the LORD said unto Moses, See, I have made thee a god to Pharaoh: and Aaron thy brother shall be thy prophet."'),
('Exodus', 7, 'teens', 2, 'How old were Moses and Aaron when they spoke to Pharaoh?', 'Moses was eighty years old and Aaron was eighty-three', 'Moses was forty and Aaron was forty-three', 'Moses was sixty and Aaron was sixty-three', 'Moses was one hundred and Aaron was one hundred and three', 'a', 'Exodus 7:7 — "And Moses was fourscore years old, and Aaron fourscore and three years old, when they spake unto Pharaoh."'),
('Exodus', 7, 'teens', 3, 'What did Pharaoh''s magicians do when they saw the water turn to blood?', 'They did the same with their enchantments — they also turned water to blood', 'They fell on their faces in fear', 'They ran away from Pharaoh', 'They begged Moses to stop', 'a', 'Exodus 7:22 — "And the magicians of Egypt did so with their enchantments: and Pharaoh''s heart was hardened, neither did he hearken unto them."'),
('Exodus', 7, 'teens', 4, 'How long did the plague of blood last?', 'Seven days after the LORD had smitten the river', 'Three days', 'One day', 'Forty days', 'a', 'Exodus 7:25 — "And seven days were fulfilled, after that the LORD had smitten the river."'),
('Exodus', 7, 'teens', 5, 'What happened to the fish in the river when it turned to blood?', 'The fish died, the river stank, and the Egyptians could not drink the water', 'The fish grew larger', 'The fish turned gold', 'The fish swam to the sea', 'a', 'Exodus 7:21 — "And the fish that was in the river died; and the river stank, and the Egyptians could not drink of the water of the river; and there was blood throughout all the land of Egypt."'),
-- Adults
('Exodus', 7, 'adults', 1, 'What does it mean that God made Moses "a god to Pharaoh"?', 'Moses functioned as God''s representative with divine authority before Pharaoh — just as Pharaoh claimed divine status, Moses stood before him with the true God''s power and mandate', 'Moses became literally divine', 'Moses replaced Pharaoh', 'Moses became an Egyptian god', 'a', 'Exodus 7:1 — "I have made thee a god to Pharaoh" (elohim l''Pharaoh). This does not deify Moses but establishes him as God''s authorised agent. As Pharaoh claimed to be the incarnation of Horus, Moses now confronts him as the representative of Yahweh.'),
('Exodus', 7, 'adults', 2, 'How does the plague of blood target Egyptian religion?', 'The Nile was worshipped as the god Hapi, and its water was considered sacred and life-giving — turning it to blood demonstrated Yahweh''s power over Egypt''s most vital deity and resource', 'The Nile had no religious significance', 'Blood was sacred in Egypt', 'The plague was coincidental', 'a', 'Exodus 7:17-21 — The Nile was Egypt''s lifeline: irrigation, drinking water, and the basis of the annual flood cycle. The god Hapi personified the Nile''s inundation. Turning it to blood struck at the heart of Egyptian religion and economy.'),
('Exodus', 7, 'adults', 3, 'What is the significance of the magicians replicating the plague?', 'Their ability to imitate (not reverse) the plague gave Pharaoh an excuse to harden his heart — but notably they could only add to the problem, not solve it, revealing the limitations of their power', 'It proved their power was equal to God''s', 'It showed the plague was natural', 'They were more powerful than Moses', 'a', 'Exodus 7:22 — The magicians could replicate the plague but could not reverse it. They could turn water to blood but could not turn blood back to water. This pattern continues — they add frogs but cannot remove them — exposing the futility of opposing God.'),
('Exodus', 7, 'adults', 4, 'Who were Pharaoh''s magicians, and what tradition identifies them?', 'Jewish tradition (2 Timothy 3:8) names them Jannes and Jambres — they were the chief practitioners of Egyptian magic who opposed Moses, representing the power of occult resistance to divine truth', 'They were Greek philosophers', 'They were Israelite spies', 'Their identity is completely unknown', 'a', '2 Timothy 3:8 — "Now as Jannes and Jambres withstood Moses, so do these also resist the truth." While not named in Exodus, Paul preserves the tradition of their names. They represent all who use counterfeit power to oppose God''s work.'),
('Exodus', 7, 'adults', 5, 'What is the pattern of the plague narrative structure seen here?', 'A recurring formula: God''s command to Moses, warning to Pharaoh, execution of the plague, response of the magicians, hardening of Pharaoh''s heart — this structure repeats with variations across the ten plagues', 'Each plague is narrated differently', 'There is no discernible pattern', 'The narrative is random', 'a', 'The plagues follow a structured pattern in three groups of three plus the tenth. Each group has a warning at the river, a warning at the palace, and a plague without warning. This literary structure highlights God''s orderly judgment.'),
('Exodus', 7, 'adults', 6, 'How does the phrase "as the LORD had said" function throughout the plague narrative?', 'It confirms divine foreknowledge and sovereignty — every event, including Pharaoh''s hardening, unfolds exactly as God predicted, demonstrating that God is in complete control of the drama', 'It is a filler phrase with no meaning', 'It refers to Moses'' predictions', 'It was added by later editors', 'a', 'Exodus 7:13,22 — "As the LORD had said" appears repeatedly, anchoring every development to God''s prior announcement. Nothing catches God by surprise; Pharaoh''s resistance was anticipated and serves God''s larger purpose.'),
('Exodus', 7, 'adults', 7, 'What is the three-cycle structure of the ten plagues?', 'Plagues are arranged in three triads (1-3, 4-6, 7-9) plus the tenth: first plague of each triad has a morning warning at the river, second has a palace warning, third comes without warning — escalating in severity', 'They are random and unstructured', 'They come in pairs', 'They follow alphabetical order', 'a', 'The literary structure: Plagues 1,4,7 (morning/river warning), 2,5,8 (palace warning with "go unto Pharaoh"), 3,6,9 (no warning). The tenth stands alone as the climactic judgment. This triad pattern underscores divine order.'),
('Exodus', 7, 'adults', 8, 'What does Exodus 7:5 state as the purpose of the plagues?', '"And the Egyptians shall know that I am the LORD, when I stretch forth mine hand upon Egypt, and bring out the children of Israel from among them" — the plagues are revelatory, designed to demonstrate God''s identity', 'The purpose was solely punishment', 'The plagues had no stated purpose', 'They were natural disasters', 'a', 'Exodus 7:5 — The plagues serve a dual purpose: judgment on Egypt and revelation of Yahweh. The phrase "that ye may know that I am the LORD" appears throughout (7:5, 8:22, 9:14, 10:2), making the plagues a theology lesson for both Egypt and Israel.');

-- ═══ Exodus Chapter 8 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 8, 'kids', 1, 'What was the second plague God sent on Egypt?', 'Frogs came up and covered the whole land — even in their houses, beds, and ovens', 'Darkness', 'Locusts', 'Hail', 'a', 'Exodus 8:6 — "And Aaron stretched out his hand over the waters of Egypt; and the frogs came up, and covered the land of Egypt."'),
('Exodus', 8, 'kids', 2, 'What tiny creatures covered the people and animals in the third plague?', 'Lice (tiny biting insects) appeared from the dust of the ground', 'Butterflies', 'Ladybirds', 'Ants', 'a', 'Exodus 8:16-17 — "And the LORD said unto Moses, Say unto Aaron, Stretch out thy rod, and smite the dust of the land, that it may become lice throughout all the land of Egypt."'),
('Exodus', 8, 'kids', 3, 'What creatures swarmed everywhere in the fourth plague?', 'Great swarms of flies filled Pharaoh''s house and all of Egypt', 'Birds', 'Bees', 'Fish', 'a', 'Exodus 8:24 — "And the LORD did so; and there came a grievous swarm of flies into the house of Pharaoh, and into his servants'' houses, and into all the land of Egypt."'),
-- Teens
('Exodus', 8, 'teens', 1, 'What did Pharaoh promise when the frogs came, and did he keep his promise?', 'He begged Moses to pray for the frogs to leave and promised to let Israel go — but when the frogs died, he hardened his heart and broke his promise', 'He immediately freed the Israelites', 'He ignored the frogs completely', 'He joined Moses in prayer', 'a', 'Exodus 8:8,15 — "Then Pharaoh called for Moses and Aaron, and said, Intreat the LORD, that he may take away the frogs from me... But when Pharaoh saw that there was respite, he hardened his heart, and hearkened not unto them."'),
('Exodus', 8, 'teens', 2, 'What did the magicians say when they could not reproduce the plague of lice?', '"This is the finger of God" — they recognised a power beyond their ability', 'They said it was a coincidence', 'They claimed they could do it tomorrow', 'They said Moses was using tricks', 'a', 'Exodus 8:18-19 — "And the magicians did so with their enchantments to bring forth lice, but they could not... Then the magicians said unto Pharaoh, This is the finger of God."'),
('Exodus', 8, 'teens', 3, 'What distinction did God make between Israel and Egypt during the plague of flies?', 'God put a division — no flies came to the land of Goshen where the Israelites lived', 'The Israelites had worse flies', 'Both lands were equally affected', 'The flies only affected animals', 'a', 'Exodus 8:22-23 — "And I will sever in that day the land of Goshen, in which my people dwell, that no swarms of flies shall be there... I will put a division between my people and thy people."'),
('Exodus', 8, 'teens', 4, 'Why did Moses say they could not sacrifice in the land of Egypt as Pharaoh suggested?', 'Because the Israelites'' sacrifices would be an abomination to the Egyptians, who might stone them for sacrificing animals the Egyptians worshipped', 'Because Egypt was too hot', 'Because they had no animals', 'Because Moses preferred the wilderness', 'a', 'Exodus 8:26 — "And Moses said, It is not meet so to do; for we shall sacrifice the abomination of the Egyptians to the LORD our God: lo, shall we sacrifice the abomination of the Egyptians before their eyes, and will they not stone us?"'),
('Exodus', 8, 'teens', 5, 'What curious request did Moses allow Pharaoh to make about when the frogs should leave?', 'Moses let Pharaoh choose the timing — Pharaoh strangely said "tomorrow" rather than "immediately," showing his stubbornness', 'Pharaoh asked for them to leave in a week', 'Moses chose the time himself', 'Pharaoh asked for more frogs', 'a', 'Exodus 8:9-10 — "And Moses said unto Pharaoh, Glory over me: when shall I intreat for thee... to destroy the frogs? And he said, To morrow." Pharaoh''s choice of "tomorrow" rather than "now" reveals the irrational nature of sin — preferring one more night with frogs over immediate relief.'),
-- Adults
('Exodus', 8, 'adults', 1, 'How does the plague of frogs target Egyptian religion?', 'The frog was associated with Heqet, the Egyptian goddess of fertility and childbirth — the overwhelming proliferation of frogs mocked this deity, turning a symbol of blessing into an instrument of judgment', 'Frogs had no religious meaning in Egypt', 'Frogs were feared by Egyptians', 'The plague was unrelated to religion', 'a', 'Exodus 8:2-6 — Heqet was depicted as a frog or a woman with a frog''s head. Midwives were called "servants of Heqet." The plague turned Egypt''s fertility goddess into a source of revulsion — frogs in beds, ovens, and kneading troughs.'),
('Exodus', 8, 'adults', 2, 'What is the significance of the magicians'' confession "This is the finger of God"?', 'Even the practitioners of Egyptian magic recognised a power categorically beyond their abilities — the phrase "finger of God" implies direct divine action (cf. Exodus 31:18, Luke 11:20), and their confession undermines Pharaoh''s resistance', 'They were being sarcastic', 'They meant a different god', 'It was a standard Egyptian expression', 'a', 'Exodus 8:19 — "This is the finger of God" (etsba Elohim). Jesus references this in Luke 11:20: "If I with the finger of God cast out devils." The magicians'' admission marks the point where human counterfeit power reaches its limit before divine power.'),
('Exodus', 8, 'adults', 3, 'What is the theological significance of God putting "a division" (peduth) between Israel and Egypt?', 'The Hebrew peduth means "redemption/ransom" — God''s distinction between His people and Egypt is based on redemption, not geography; this foreshadows the Passover where the blood distinguishes between those under judgment and those redeemed', 'It was merely a geographical accident', 'Israel was just lucky', 'It was Pharaoh''s decision', 'a', 'Exodus 8:23 — "I will put a division (peduth/redemption) between my people and thy people." The word choice connects God''s protective distinction to His redemptive purpose, anticipating the Passover lamb.'),
('Exodus', 8, 'adults', 4, 'Why is the plague of lice significant as the third plague?', 'It is the first plague the magicians cannot replicate, breaking their progressive opposition — it also arises from the dust (afar), connecting to Genesis 3:19 and symbolising judgment on the ground itself', 'It was the least important plague', 'The magicians easily replicated it', 'It only affected animals', 'a', 'Exodus 8:16-19 — The lice arose from the dust of the earth (afar ha-aretz), the same substance from which Adam was formed (Genesis 2:7). The magicians'' failure here marks a turning point in the narrative.'),
('Exodus', 8, 'adults', 5, 'How does Pharaoh''s negotiation pattern in chapter 8 reveal a strategy of minimal concession?', 'Pharaoh offers increasingly small compromises — first "sacrifice in the land" (v.25), then "not too far" (v.28) — while never truly yielding; each concession is a delaying tactic to retain control', 'Pharaoh was genuinely trying to negotiate fairly', 'Each offer was generous', 'Pharaoh made no offers', 'a', 'Exodus 8:25,28 — Pharaoh says "Go ye, sacrifice to your God in the land" (v.25), then "I will let you go... only ye shall not go very far away" (v.28). Each "concession" actually violates God''s command, representing the sin of partial obedience.'),
('Exodus', 8, 'adults', 6, 'What does Moses'' statement about "the abomination of the Egyptians" reveal about the religious clash?', 'The animals Israel would sacrifice (cattle, sheep) were sacred to Egyptians — sacrificing them publicly would provoke violent reaction, making worship in Egypt impossible and necessitating the wilderness journey', 'Moses was being xenophobic', 'The Egyptians had no sacred animals', 'Moses was making excuses', 'a', 'Exodus 8:26 — The bull was sacred to Apis, the ram to Amun, the cow to Hathor. Israelite sacrifice of these animals before Egyptian eyes would be perceived as deliberate blasphemy against Egyptian deities — hence the necessity of wilderness worship.'),
('Exodus', 8, 'adults', 7, 'How does the plague of flies (arov) connect to the broader judgment pattern?', 'The Hebrew arov likely means "mixture" or "swarm" — possibly a mixture of biting insects. It marks the first plague where God explicitly protects Goshen (v.22), introducing a new dimension: God''s judgment discriminates between His people and their oppressors', 'It is identical to the lice plague', 'It was the mildest plague', 'It had no theological significance', 'a', 'Exodus 8:21-24 — From the fourth plague onward, God explicitly separates Goshen from Egypt''s judgments. This "division" (peduth) introduces the principle of divine discrimination that culminates in the Passover.'),
('Exodus', 8, 'adults', 8, 'What does the detail that "the land was corrupted by reason of the swarm of flies" tell us?', 'The Hebrew tishachet ("was destroyed/corrupted") echoes Genesis 6:11-12 where the earth was "corrupt" before the Flood — suggesting the plagues are a de-creation event, unmaking Egypt''s ordered world', 'The flies caused minor inconvenience', 'Egypt recovered immediately', 'The word has no special significance', 'a', 'Exodus 8:24 — The verb shachath ("corrupt/destroy") links the plagues to the Flood narrative. Just as sin corrupted the pre-Flood world, so Egypt''s sin (oppression and idolatry) brings systematic divine judgment that unmakes the created order.');

-- ═══ Exodus Chapter 9 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 9, 'kids', 1, 'What happened to the animals of Egypt in the fifth plague?', 'A terrible disease killed the Egyptian cattle, horses, donkeys, camels, oxen, and sheep', 'They all ran away', 'They turned different colours', 'They started talking', 'a', 'Exodus 9:3,6 — "Behold, the hand of the LORD is upon thy cattle which is in the field, upon the horses, upon the asses, upon the camels, upon the oxen, and upon the sheep: there shall be a very grievous murrain... and all the cattle of Egypt died."'),
('Exodus', 9, 'kids', 2, 'What happened to the Egyptians'' skin in the sixth plague?', 'Painful boils (sores) broke out on all the people and animals', 'Their skin turned green', 'They became invisible', 'Their skin became soft', 'a', 'Exodus 9:10 — "And they took ashes of the furnace, and stood before Pharaoh; and Moses sprinkled it up toward heaven; and it became a boil breaking forth with blains upon man, and upon beast."'),
('Exodus', 9, 'kids', 3, 'What fell from the sky in the seventh plague?', 'Hail mixed with fire — the worst hailstorm Egypt had ever seen', 'Snow', 'Rain only', 'Stars', 'a', 'Exodus 9:23-24 — "And the LORD sent thunder and hail, and the fire ran along upon the ground... So there was hail, and fire mingled with the hail, very grievous, such as there was none like it in all the land of Egypt since it became a nation."'),
-- Teens
('Exodus', 9, 'teens', 1, 'Did any of the Israelites'' animals die in the fifth plague?', 'Not one — God made a distinction between the livestock of Israel and Egypt', 'Half of them died', 'Only the sheep died', 'They all died too', 'a', 'Exodus 9:4,7 — "And the LORD shall sever between the cattle of Israel and the cattle of Egypt: and there shall nothing die of all that is the children''s of Israel... and there was not one of the cattle of the Israelites dead."'),
('Exodus', 9, 'teens', 2, 'What happened to the magicians during the plague of boils?', 'The magicians could not even stand before Moses because the boils were upon them', 'They healed themselves', 'They were not affected', 'They fled to another country', 'a', 'Exodus 9:11 — "And the magicians could not stand before Moses because of the boils; for the boil was upon the magicians, and upon all the Egyptians."'),
('Exodus', 9, 'teens', 3, 'What reason did God give for raising up Pharaoh?', '"For this cause have I raised thee up, for to shew in thee my power; and that my name may be declared throughout all the earth"', 'To make Egypt wealthy', 'To build great monuments', 'To be the world''s best ruler', 'a', 'Exodus 9:16 — "And in very deed for this cause have I raised thee up, for to shew in thee my power; and that my name may be declared throughout all the earth."'),
('Exodus', 9, 'teens', 4, 'What did Pharaoh confess during the hailstorm?', '"I have sinned this time: the LORD is righteous, and I and my people are wicked"', '"This is just bad weather"', '"I am the greatest ruler"', '"The gods of Egypt are angry"', 'a', 'Exodus 9:27 — "And Pharaoh sent, and called for Moses and Aaron, and said unto them, I have sinned this time: the LORD is righteous, and I and my people are wicked."'),
('Exodus', 9, 'teens', 5, 'Who among the Egyptians were spared from the hail?', 'Those servants of Pharaoh who feared the word of the LORD and brought their servants and cattle indoors', 'No one was spared', 'Only Pharaoh was spared', 'Only the magicians were spared', 'a', 'Exodus 9:20 — "He that feared the word of the LORD among the servants of Pharaoh made his servants and his cattle flee into the houses."'),
-- Adults
('Exodus', 9, 'adults', 1, 'How does the plague of murrain target Egyptian animal worship?', 'The Egyptians worshipped multiple animal deities — Apis (bull), Hathor (cow), Khnum (ram) — the destruction of livestock struck directly at these gods, demonstrating their powerlessness to protect even their own sacred animals', 'Animals had no religious significance', 'Only wild animals were affected', 'The plague was coincidental', 'a', 'Exodus 9:1-7 — The murrain on horses (sacred to Ra''s chariot), donkeys, camels, cattle (Apis, Hathor), and sheep (Khnum) systematically dismantled the animal cult. Cf. Exodus 12:12 — "against all the gods of Egypt I will execute judgment."'),
('Exodus', 9, 'adults', 2, 'What is significant about Moses using "ashes of the furnace" for the boils plague?', 'The Hebrew kibshan (furnace/kiln) likely refers to the brick kilns where Israelites laboured — the instrument of their oppression becomes the instrument of Egypt''s judgment, a poetic justice', 'Ashes had magical properties', 'It was a random choice', 'Moses was cleaning the furnace', 'a', 'Exodus 9:8-10 — "Take to you handfuls of ashes of the furnace" (kibshan). If this refers to the brick kilns, then the very symbol of Israel''s slavery becomes the vehicle of divine judgment on the oppressors — measure-for-measure justice (middah k''neged middah).'),
('Exodus', 9, 'adults', 3, 'How does Paul use Exodus 9:16 in Romans 9:17?', 'Paul quotes it to illustrate God''s sovereign right to raise up individuals for His purposes — even vessels of wrath serve to display God''s power and make His name known, demonstrating divine sovereignty in salvation history', 'Paul misquotes the verse', 'Paul uses it to prove universal salvation', 'Paul contradicts the verse', 'a', 'Romans 9:17 — "For the scripture saith unto Pharaoh, Even for this same purpose have I raised thee up, that I might shew my power in thee, and that my name might be declared throughout all the earth." Paul uses this to argue for God''s sovereign prerogative in mercy and judgment.'),
('Exodus', 9, 'adults', 4, 'What does Pharaoh''s confession in 9:27 reveal about false repentance?', 'His confession uses correct theological language ("the LORD is righteous, I am wicked") but lacks genuine change — once the hail stops, he hardens his heart again (v.34), demonstrating that correct words without heart change are meaningless', 'His repentance was genuine', 'He never spoke these words', 'He permanently changed after this', 'a', 'Exodus 9:27,34-35 — "I have sinned... the LORD is righteous, and I and my people are wicked." But when the plague stopped, "he sinned yet more, and hardened his heart." This is a textbook case of attrition (sorrow from consequences) versus contrition (sorrow from genuine repentance).'),
('Exodus', 9, 'adults', 5, 'What does the detail about "those who feared the word of the LORD" among Pharaoh''s servants show?', 'Even within the oppressing nation, some individuals responded to God''s warnings — God''s judgment is not indiscriminate but provides opportunity for anyone who fears His word, regardless of nationality', 'All Egyptians were equally wicked', 'Only Israelites could fear God', 'The detail is insignificant', 'a', 'Exodus 9:20-21 — A division appears within Egypt itself: some servants "feared the word of the LORD" and took shelter, while others "regarded not the word of the LORD." This anticipates the "mixed multitude" who leave with Israel (12:38).'),
('Exodus', 9, 'adults', 6, 'What agricultural detail in 9:31-32 provides historical precision?', 'The flax and barley were destroyed (they mature early) but the wheat and rie were not (they are later crops) — this detail confirms the plague occurred in late January/early February when barley is in ear and flax in bud in Egypt', 'The crops are mentioned randomly', 'All crops were destroyed', 'No crops are mentioned', 'a', 'Exodus 9:31-32 — "The flax and the barley was smitten: for the barley was in the ear, and the flax was bolled. But the wheat and the rie were not smitten: for they were not grown up." This botanical detail places the seventh plague around January-February, consistent with Egyptian agricultural cycles.'),
('Exodus', 9, 'adults', 7, 'How does "fire mingled with the hail" function as a sign of divine judgment?', 'Fire and ice coexisting is a supernatural impossibility — it demonstrates God''s control over opposing natural forces simultaneously, paralleling theophanic descriptions (Psalm 18:12-13, Ezekiel 1:4) and apocalyptic judgment (Revelation 8:7)', 'It was ordinary lightning', 'It was a volcanic eruption', 'It was a natural phenomenon', 'a', 'Exodus 9:24 — "There was hail, and fire mingled with the hail." The simultaneous occurrence of fire and ice is a sign of divine power transcending natural law. Psalm 148:8 links "fire, and hail" as instruments of God''s command.'),
('Exodus', 9, 'adults', 8, 'What does God''s statement "I could have stretched out my hand and smitten thee" (9:15) reveal about divine restraint?', 'God reveals He has been exercising deliberate restraint — He could have annihilated Egypt instantly but chose graduated judgments to demonstrate His power, elicit repentance, and make His name known worldwide', 'God lacked the power to destroy Egypt', 'God was unsure what to do', 'The restraint shows weakness', 'a', 'Exodus 9:15-16 — "For now I will stretch out my hand, that I may smite thee and thy people with pestilence; and thou shalt be cut off from the earth. And in very deed for this cause have I raised thee up." God''s graduated judgment reveals both patience and purpose.');

-- ═══ Exodus Chapter 10 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 10, 'kids', 1, 'What came and ate all the crops and plants in the eighth plague?', 'Locusts — huge swarms that covered the ground and ate everything green', 'Mice', 'Caterpillars', 'Birds', 'a', 'Exodus 10:14-15 — "And the locusts went up over all the land of Egypt... they covered the face of the whole earth, so that the land was darkened; and they did eat every herb of the land, and all the fruit of the trees."'),
('Exodus', 10, 'kids', 2, 'What happened during the ninth plague?', 'Thick darkness covered all of Egypt for three days — people could not see each other', 'It rained for three days', 'The ground shook', 'All the water dried up', 'a', 'Exodus 10:22-23 — "And Moses stretched forth his hand toward heaven; and there was a thick darkness in all the land of Egypt three days: They saw not one another, neither rose any from his place for three days."'),
('Exodus', 10, 'kids', 3, 'Did the Israelites have darkness too?', 'No — all the children of Israel had light in their dwellings', 'Yes, everyone was in darkness', 'Only the children had light', 'They used candles', 'a', 'Exodus 10:23 — "But all the children of Israel had light in their dwellings."'),
-- Teens
('Exodus', 10, 'teens', 1, 'What did Pharaoh''s own servants say to him before the locust plague?', '"How long shall this man be a snare unto us? let the men go... knowest thou not yet that Egypt is destroyed?"', '"Stay strong and do not give in"', '"We support you completely"', '"Send Moses to prison"', 'a', 'Exodus 10:7 — "And Pharaoh''s servants said unto him, How long shall this man be a snare unto us? let the men go, that they may serve the LORD their God: knowest thou not yet that Egypt is destroyed?"'),
('Exodus', 10, 'teens', 2, 'What compromise did Pharaoh try to make before the locust plague?', 'He would let only the men go to worship, but not the children, women, or flocks', 'He offered gold instead', 'He said they could worship in Egypt', 'He asked to come with them', 'a', 'Exodus 10:10-11 — "And he said unto them, Let the LORD be so with you, as I will let you go, and your little ones: look to it; for evil is before you. Not so: go now ye that are men, and serve the LORD."'),
('Exodus', 10, 'teens', 3, 'What brought the locusts and what took them away?', 'An east wind brought the locusts; a mighty strong west wind cast them into the Red Sea', 'They came and left on their own', 'Rain brought them and rain took them', 'Moses waved his hand', 'a', 'Exodus 10:13,19 — "The LORD brought an east wind upon the land all that day, and all that night; and when it was morning, the east wind brought the locusts... And the LORD turned a mighty strong west wind, which took away the locusts, and cast them into the Red sea."'),
('Exodus', 10, 'teens', 4, 'What was Pharaoh''s final offer before Moses left his presence?', 'Go serve the LORD with your families but leave your flocks and herds behind', 'Take everything and go', 'Stay one more year', 'Take only the children', 'a', 'Exodus 10:24 — "And Pharaoh called unto Moses, and said, Go ye, serve the LORD; only let your flocks and your herds be stayed: let your little ones also go with you."'),
('Exodus', 10, 'teens', 5, 'What was Moses'' response about the livestock?', '"Our cattle also shall go with us; there shall not an hoof be left behind" — they needed animals for sacrifices to the LORD', 'He agreed to leave the animals', 'He offered half the animals', 'He said they had no animals', 'a', 'Exodus 10:26 — "Our cattle also shall go with us; there shall not an hoof be left behind; for thereof must we take to serve the LORD our God; and we know not with what we must serve the LORD, until we come thither."'),
-- Adults
('Exodus', 10, 'adults', 1, 'What additional purpose for the plagues does God reveal in 10:1-2?', 'Beyond judgment, the plagues serve as a testimony for future generations — "that thou mayest tell in the ears of thy son, and of thy son''s son" — making them an educational tool for covenant memory', 'The plagues had no future significance', 'Only Egyptians would remember', 'The plagues were meant to be forgotten', 'a', 'Exodus 10:1-2 — "That thou mayest tell in the ears of thy son, and of thy son''s son, what things I have wrought in Egypt... that ye may know how that I am the LORD." The plagues become the founding narrative of Israel''s faith, retold at every Passover.'),
('Exodus', 10, 'adults', 2, 'How does the locust plague target Egyptian religion and economy?', 'Locusts consumed what the hail spared — destroying the remaining wheat and rie crops, devastating Egypt''s agricultural economy and mocking Isis and Seth (deities of agriculture and storms) who failed to protect the harvest', 'Locusts were sacred in Egypt', 'The plague had no economic impact', 'Only flowers were eaten', 'a', 'Exodus 10:15 — "They did eat every herb of the land, and all the fruit of the trees which the hail had left: and there remained not any green thing in the trees, or in the herbs of the field, through all the land of Egypt." Agricultural annihilation was economic and theological devastation.'),
('Exodus', 10, 'adults', 3, 'What is the theological significance of the darkness plague targeting Ra, the sun god?', 'Ra was the supreme deity of Egypt — Pharaoh was considered "Son of Ra" — three days of impenetrable darkness demonstrated Yahweh''s absolute power over Egypt''s highest god and Pharaoh''s own divine claim', 'Darkness had no religious meaning', 'Ra was a minor deity', 'The Egyptians did not worship the sun', 'a', 'Exodus 10:21-23 — Ra (or Re/Amun-Ra) was Egypt''s supreme deity; the sun was the source of life, order, and Pharaoh''s legitimacy. Three days of "darkness which may be felt" was a direct assault on Egypt''s highest theological claim.'),
('Exodus', 10, 'adults', 4, 'What does the phrase "darkness which may be felt" suggest about the nature of this plague?', 'The Hebrew choshekh aphilah suggests a supernatural darkness of tangible, oppressive quality — beyond mere absence of light, it was a paralyzing darkness that immobilized people, possibly echoing the primordial darkness of Genesis 1:2', 'It was ordinary nighttime', 'It was a solar eclipse', 'It was a sandstorm', 'a', 'Exodus 10:21 — "A darkness which may be felt" (v''yamesh choshekh). The darkness was so dense it could be "touched" or "groped." This supernatural darkness reversed creation (Genesis 1:3-4), returning Egypt to a pre-creation state of chaos.'),
('Exodus', 10, 'adults', 5, 'How do Pharaoh''s escalating compromises reveal a pattern of partial obedience?', 'Sacrifice in the land (8:25), not too far away (8:28), men only (10:11), leave livestock (10:24) — each offer gives something while retaining control, mirroring how sin offers partial surrender while keeping the heart', 'Pharaoh was being genuinely generous', 'Each offer was fully acceptable', 'The compromises were Moses'' idea', 'a', 'Pharaoh''s four compromises progressively concede more while always holding something back — a master class in "almost obedience." Moses rejects every partial offer because God demands total allegiance: "not an hoof left behind" (10:26).'),
('Exodus', 10, 'adults', 6, 'What does Pharaoh''s threat "Get thee from me, take heed to thyself, see my face no more; for in that day thou seest my face thou shalt die" foreshadow?', 'It ironically foreshadows Pharaoh''s own destruction — he who threatens death will himself experience death (of his firstborn and his army at the Red Sea); Moses agrees: "I will see thy face again no more"', 'Moses was genuinely afraid', 'Pharaoh had the power to kill Moses', 'Moses returned the next day', 'a', 'Exodus 10:28-29 — Pharaoh''s threat is dramatic irony: he pronounces death on God''s messenger while his own death sentence (the tenth plague) is about to be announced. Moses'' agreement ("Thou hast spoken well, I will see thy face again no more") is both acceptance and judgment.'),
('Exodus', 10, 'adults', 7, 'How does the phrase "Israel had light in their dwellings" function theologically?', 'It demonstrates God''s ability to discriminate between His people and the world — light and darkness coexist geographically but are separated by covenant relationship, foreshadowing the pillar of cloud and fire that would guide Israel', 'It was a coincidence of geography', 'The Israelites had oil lamps', 'Goshen had different weather', 'a', 'Exodus 10:23 — Light in Goshen amidst Egypt''s darkness is a powerful image of salvation: God''s people dwell in light while the world around them is in darkness (cf. 1 John 1:5, John 8:12, Isaiah 60:1-2).'),
('Exodus', 10, 'adults', 8, 'How does the rebellion of Pharaoh''s own servants (10:7) function in the narrative?', 'It shows that even Pharaoh''s inner circle recognised Egypt''s destruction before he did — his hardened heart made him more stubborn than his own advisors, isolating him in his defiance and demonstrating how sin blinds even to obvious reality', 'His servants supported his decision', 'His servants were punished for speaking', 'His servants were Israelites', 'a', 'Exodus 10:7 — "Knowest thou not yet that Egypt is destroyed?" The servants'' desperate plea contrasts with Pharaoh''s intransigence. When subordinates see what the leader refuses to acknowledge, it highlights the blinding effect of a hardened heart.');
