-- ============================================================================
-- Quiz Seed: 2 Timothy (Chapters 1–4)
-- 3 difficulties × 4 chapters = 64 total questions
--   kids:   3 per chapter  = 12
--   teens:  5 per chapter  = 20
--   adults: 8 per chapter  = 32
-- ============================================================================

-- ═══ 2 Timothy Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Timothy', 1, 'kids', 1, 'Who wrote this letter to Timothy?', 'Paul', 'Peter', 'James', 'John', 'a', '2 Timothy 1:1 — "Paul, an apostle of Jesus Christ by the will of God."'),
('2 Timothy', 1, 'kids', 2, 'What did Paul say God has NOT given us?', 'The spirit of fear', 'The spirit of love', 'The spirit of power', 'The spirit of a sound mind', 'a', '2 Timothy 1:7 — "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."'),
('2 Timothy', 1, 'kids', 3, 'What family member of Timothy had sincere faith?', 'His grandmother Lois and mother Eunice', 'His father and uncle', 'His brother and sister', 'His cousin and aunt', 'a', '2 Timothy 1:5 — "The unfeigned faith that is in thee, which dwelt first in thy grandmother Lois, and thy mother Eunice."'),
-- Teens
('2 Timothy', 1, 'teens', 1, 'What three things did God give believers instead of fear according to verse 7?', 'Power, love, and a sound mind', 'Wealth, health, and happiness', 'Wisdom, strength, and courage', 'Faith, hope, and charity', 'a', '2 Timothy 1:7 — "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."'),
('2 Timothy', 1, 'teens', 2, 'What does Paul say God called us with according to verse 9?', 'A holy calling, not according to our works', 'A calling based on our good deeds', 'A calling for the Jewish people only', 'A calling that can be earned by study', 'a', '2 Timothy 1:9 — "Who hath saved us, and called us with an holy calling, not according to our works."'),
('2 Timothy', 1, 'teens', 3, 'What did Paul urge Timothy to stir up in verse 6?', 'The gift of God which is in thee', 'The fire in the temple', 'The congregation of believers', 'The anger against false teachers', 'a', '2 Timothy 1:6 — "Stir up the gift of God, which is in thee by the putting on of my hands."'),
('2 Timothy', 1, 'teens', 4, 'What has Christ abolished according to verse 10?', 'Death, and brought life and immortality to light', 'The law of Moses entirely', 'The Roman government', 'The power of the Pharisees', 'a', '2 Timothy 1:10 — "Who hath abolished death, and hath brought life and immortality to light through the gospel."'),
('2 Timothy', 1, 'teens', 5, 'Who does Paul say turned away from him in Asia?', 'All they which are in Asia, including Phygellus and Hermogenes', 'Timothy and his family', 'Luke and Barnabas', 'Peter and James', 'a', '2 Timothy 1:15 — "All they which are in Asia be turned away from me; of whom are Phygellus and Hermogenes."'),
-- Adults
('2 Timothy', 1, 'adults', 1, 'What does Paul say was given to believers "before the world began" in verse 9?', 'Grace in Christ Jesus', 'The law of Moses', 'The gift of prophecy', 'The written Scriptures', 'a', '2 Timothy 1:9 — "According to his own purpose and grace, which was given us in Christ Jesus before the world began."'),
('2 Timothy', 1, 'adults', 2, 'What does Paul say he is persuaded about in verse 12?', 'That God is able to keep that which he committed unto him against that day', 'That Timothy will come to him soon', 'That Rome will fall', 'That all of Asia will repent', 'a', '2 Timothy 1:12 — "For I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him against that day."'),
('2 Timothy', 1, 'adults', 3, 'What does Paul tell Timothy to hold fast in verse 13?', 'The form of sound words which thou hast heard of me', 'The traditions of the elders', 'The writings of the philosophers', 'The opinions of the majority', 'a', '2 Timothy 1:13 — "Hold fast the form of sound words, which thou hast heard of me, in faith and love which is in Christ Jesus."'),
('2 Timothy', 1, 'adults', 4, 'What does Paul say to guard by the Holy Ghost in verse 14?', 'That good thing which was committed unto thee', 'The gold in the treasury', 'The temple building', 'The apostolic succession', 'a', '2 Timothy 1:14 — "That good thing which was committed unto thee keep by the Holy Ghost which dwelleth in us."'),
('2 Timothy', 1, 'adults', 5, 'Who does Paul commend for not being ashamed of his chain?', 'Onesiphorus', 'Timothy', 'Luke', 'Titus', 'a', '2 Timothy 1:16 — "The Lord give mercy unto the house of Onesiphorus; for he oft refreshed me, and was not ashamed of my chain."'),
('2 Timothy', 1, 'adults', 6, 'What does Paul say Onesiphorus did when he was in Rome?', 'He sought Paul out very diligently and found him', 'He avoided Paul out of fear', 'He reported Paul to the authorities', 'He left Rome immediately', 'a', '2 Timothy 1:17 — "But, when he was in Rome, he sought me out very diligently, and found me."'),
('2 Timothy', 1, 'adults', 7, 'How does Paul describe his relationship to Timothy in verse 2?', 'My dearly beloved son', 'My fellow apostle', 'My trusted servant', 'My brother in the faith', 'a', '2 Timothy 1:2 — "To Timothy, my dearly beloved son: Grace, mercy, and peace."'),
('2 Timothy', 1, 'adults', 8, 'What does the phrase "the laying on of my hands" in verse 6 refer to?', 'Paul''s ordination of Timothy for ministry', 'A healing miracle Paul performed', 'A Jewish blessing ceremony', 'A Roman greeting custom', 'a', '2 Timothy 1:6 — "The gift of God, which is in thee by the putting on of my hands." This refers to Timothy''s ordination and commissioning for ministry.');

-- ═══ 2 Timothy Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Timothy', 2, 'kids', 1, 'What does Paul tell Timothy to be strong in?', 'The grace that is in Christ Jesus', 'His own muscles', 'His fighting skills', 'His knowledge of languages', 'a', '2 Timothy 2:1 — "Thou therefore, my son, be strong in the grace that is in Christ Jesus."'),
('2 Timothy', 2, 'kids', 2, 'What three examples does Paul use to describe a Christian?', 'A soldier, an athlete, and a farmer', 'A king, a priest, and a prophet', 'A lion, an eagle, and a lamb', 'A teacher, a doctor, and a builder', 'a', '2 Timothy 2:3-6 — Paul uses the images of a soldier (v.3-4), an athlete (v.5), and a husbandman/farmer (v.6).'),
('2 Timothy', 2, 'kids', 3, 'What does Paul say we should avoid?', 'Foolish and unlearned questions', 'Reading the Scriptures', 'Praying every day', 'Going to church', 'a', '2 Timothy 2:23 — "But foolish and unlearned questions avoid, knowing that they do gender strifes."'),
-- Teens
('2 Timothy', 2, 'teens', 1, 'What does Paul say a good soldier does NOT do?', 'Entangle himself with the affairs of this life', 'Train for battle', 'Follow his commander', 'Wear his armor', 'a', '2 Timothy 2:4 — "No man that warreth entangleth himself with the affairs of this life; that he may please him who hath chosen him to be a soldier."'),
('2 Timothy', 2, 'teens', 2, 'What must happen to an athlete to receive a crown according to verse 5?', 'He must strive lawfully (compete by the rules)', 'He must win every single race', 'He must defeat every opponent', 'He must train for ten years', 'a', '2 Timothy 2:5 — "If a man also strive for masteries, yet is he not crowned, except he strive lawfully."'),
('2 Timothy', 2, 'teens', 3, 'What is the faithful saying in verses 11-12?', 'If we be dead with him, we shall also live with him; if we suffer, we shall also reign with him', 'If we pray enough, we will be rich', 'If we study hard, we will be wise', 'If we fast often, we will be holy', 'a', '2 Timothy 2:11-12 — "If we be dead with him, we shall also live with him: If we suffer, we shall also reign with him."'),
('2 Timothy', 2, 'teens', 4, 'What does Paul say about God''s foundation in verse 19?', 'It standeth sure, having this seal: The Lord knoweth them that are his', 'It was laid in Jerusalem only', 'It can be shaken by false teachers', 'It needs to be rebuilt each generation', 'a', '2 Timothy 2:19 — "The foundation of God standeth sure, having this seal, The Lord knoweth them that are his."'),
('2 Timothy', 2, 'teens', 5, 'What should Timothy flee from according to verse 22?', 'Youthful lusts', 'Responsibility', 'Hard work', 'Public speaking', 'a', '2 Timothy 2:22 — "Flee also youthful lusts: but follow righteousness, faith, charity, peace."'),
-- Adults
('2 Timothy', 2, 'adults', 1, 'What principle of faithful ministry does Paul establish in verse 2?', 'Commit the teaching to faithful men who shall be able to teach others also', 'Keep the teaching secret among apostles', 'Write everything down for future generations', 'Only share with those who pay for instruction', 'a', '2 Timothy 2:2 — "The things that thou hast heard of me among many witnesses, the same commit thou to faithful men, who shall be able to teach others also."'),
('2 Timothy', 2, 'adults', 2, 'What does Paul say about the word of God in verse 9?', 'The word of God is not bound', 'The word of God is limited to Israel', 'The word of God needs human defense', 'The word of God changes with culture', 'a', '2 Timothy 2:9 — "Wherein I suffer trouble, as an evil doer, even unto bonds; but the word of God is not bound."'),
('2 Timothy', 2, 'adults', 3, 'What happens if we deny Christ according to verse 12?', 'He also will deny us', 'He will forgive us anyway', 'Nothing happens', 'He will give us more time', 'a', '2 Timothy 2:12 — "If we deny him, he also will deny us."'),
('2 Timothy', 2, 'adults', 4, 'What does Paul say about God''s faithfulness even when we are faithless (v. 13)?', 'He abideth faithful: he cannot deny himself', 'He becomes unfaithful too', 'He punishes us immediately', 'He withdraws his Spirit', 'a', '2 Timothy 2:13 — "If we believe not, yet he abideth faithful: he cannot deny himself."'),
('2 Timothy', 2, 'adults', 5, 'What does Paul say the workman approved unto God should do?', 'Rightly divide the word of truth', 'Memorize every verse exactly', 'Debate all opponents publicly', 'Build large congregations', 'a', '2 Timothy 2:15 — "Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth."'),
('2 Timothy', 2, 'adults', 6, 'What two men does Paul name as having erred concerning the truth?', 'Hymenaeus and Philetus', 'Phygellus and Hermogenes', 'Demas and Alexander', 'Jannes and Jambres', 'a', '2 Timothy 2:17-18 — "Of whom is Hymenaeus and Philetus; Who concerning the truth have erred, saying that the resurrection is past already."'),
('2 Timothy', 2, 'adults', 7, 'What false teaching did Hymenaeus and Philetus spread?', 'That the resurrection is past already', 'That Jesus never rose from the dead', 'That there is no God', 'That the law should be abolished', 'a', '2 Timothy 2:18 — "Who concerning the truth have erred, saying that the resurrection is past already; and overthrow the faith of some."'),
('2 Timothy', 2, 'adults', 8, 'In the analogy of vessels in verse 20-21, what kind of vessel should a believer be?', 'A vessel unto honour, sanctified and meet for the master''s use', 'A vessel of gold only', 'A vessel that is never used', 'A vessel displayed for decoration', 'a', '2 Timothy 2:21 — "If a man therefore purge himself from these, he shall be a vessel unto honour, sanctified, and meet for the master''s use."');

-- ═══ 2 Timothy Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Timothy', 3, 'kids', 1, 'What did Paul say the last days would be like?', 'Perilous (dangerous) times', 'Easy and fun times', 'Very peaceful times', 'Boring and quiet times', 'a', '2 Timothy 3:1 — "This know also, that in the last days perilous times shall come."'),
('2 Timothy', 3, 'kids', 2, 'What did Timothy know from childhood?', 'The holy scriptures', 'How to build houses', 'How to fish', 'How to cook', 'a', '2 Timothy 3:15 — "From a child thou hast known the holy scriptures."'),
('2 Timothy', 3, 'kids', 3, 'What does Paul say all scripture is given by?', 'Inspiration of God', 'Human wisdom', 'Angel dictation', 'King''s command', 'a', '2 Timothy 3:16 — "All scripture is given by inspiration of God."'),
-- Teens
('2 Timothy', 3, 'teens', 1, 'What characteristics of people in the last days does Paul list first in verse 2?', 'Lovers of their own selves, covetous, boasters, proud', 'Loving, generous, humble, kind', 'Faithful, honest, gentle, patient', 'Brave, courageous, strong, wise', 'a', '2 Timothy 3:2 — "For men shall be lovers of their own selves, covetous, boasters, proud."'),
('2 Timothy', 3, 'teens', 2, 'What does Paul say about people having a form of godliness?', 'They deny the power thereof', 'They truly follow God', 'They are the best Christians', 'They will be saved first', 'a', '2 Timothy 3:5 — "Having a form of godliness, but denying the power thereof: from such turn away."'),
('2 Timothy', 3, 'teens', 3, 'Who does Paul compare false teachers to in verse 8?', 'Jannes and Jambres who withstood Moses', 'Goliath who fought David', 'Pharaoh who chased Israel', 'Balaam who cursed Israel', 'a', '2 Timothy 3:8 — "Now as Jannes and Jambres withstood Moses, so do these also resist the truth."'),
('2 Timothy', 3, 'teens', 4, 'What happened to Paul in Antioch, Iconium, and Lystra?', 'He suffered persecutions, but the Lord delivered him', 'He built three large churches', 'He performed many miracles', 'He was welcomed by everyone', 'a', '2 Timothy 3:11 — "Persecutions, afflictions, which came unto me at Antioch, at Iconium, at Lystra; what persecutions I endured: but out of them all the Lord delivered me."'),
('2 Timothy', 3, 'teens', 5, 'What does Paul say will happen to all who live godly in Christ Jesus?', 'They shall suffer persecution', 'They will become wealthy', 'They will never have problems', 'They will be famous', 'a', '2 Timothy 3:12 — "Yea, and all that will live godly in Christ Jesus shall suffer persecution."'),
-- Adults
('2 Timothy', 3, 'adults', 1, 'How many negative characteristics of last-days people does Paul list in verses 2-4?', 'Eighteen or nineteen distinct characteristics', 'Five characteristics', 'Ten characteristics', 'Three characteristics', 'a', '2 Timothy 3:2-4 lists: lovers of own selves, covetous, boasters, proud, blasphemers, disobedient to parents, unthankful, unholy, without natural affection, trucebreakers, false accusers, incontinent, fierce, despisers of those that are good, traitors, heady, highminded, lovers of pleasures more than lovers of God.'),
('2 Timothy', 3, 'adults', 2, 'What does Paul say evil men and seducers will do in verse 13?', 'Wax worse and worse, deceiving and being deceived', 'Eventually repent and turn to God', 'Slowly improve over time', 'Remain exactly the same', 'a', '2 Timothy 3:13 — "But evil men and seducers shall wax worse and worse, deceiving, and being deceived."'),
('2 Timothy', 3, 'adults', 3, 'What four purposes of Scripture does Paul list in verse 16?', 'Doctrine, reproof, correction, instruction in righteousness', 'Entertainment, history, poetry, philosophy', 'Prophecy, genealogy, law, ceremony', 'Prayer, fasting, meditation, worship', 'a', '2 Timothy 3:16 — "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness."'),
('2 Timothy', 3, 'adults', 4, 'What is the ultimate goal of Scripture according to verse 17?', 'That the man of God may be perfect, throughly furnished unto all good works', 'That believers may become wealthy', 'That the church may grow large', 'That all nations may be converted', 'a', '2 Timothy 3:17 — "That the man of God may be perfect, throughly furnished unto all good works."'),
('2 Timothy', 3, 'adults', 5, 'What does the phrase "given by inspiration of God" literally mean in Greek?', 'God-breathed (theopneustos)', 'God-written', 'God-spoken', 'God-thought', 'a', '2 Timothy 3:16 — "All scripture is given by inspiration of God." The Greek word theopneustos means "God-breathed," indicating divine origin.'),
('2 Timothy', 3, 'adults', 6, 'What does Paul say about the type of women deceived by false teachers in verse 6?', 'Silly women laden with sins, led away with divers lusts', 'Wise and discerning women', 'Women who study Scripture daily', 'Women who lead the churches', 'a', '2 Timothy 3:6 — "For of this sort are they which creep into houses, and lead captive silly women laden with sins, led away with divers lusts."'),
('2 Timothy', 3, 'adults', 7, 'What does Paul say about the folly of false teachers in verse 9?', 'They shall proceed no further: for their folly shall be manifest unto all men', 'They will succeed in deceiving the whole world', 'They will repent when confronted', 'They will be destroyed by angels', 'a', '2 Timothy 3:9 — "But they shall proceed no further: for their folly shall be manifest unto all men, as theirs also was."'),
('2 Timothy', 3, 'adults', 8, 'What is the significance of Paul mentioning Timothy''s knowledge of Scripture "from a child"?', 'It demonstrates the importance of teaching Scripture to children from a young age and shows Timothy''s Jewish upbringing', 'It suggests Timothy was a child prodigy', 'It implies only children can understand Scripture', 'It means Timothy wrote Scripture as a child', 'a', '2 Timothy 3:15 — "And that from a child thou hast known the holy scriptures, which are able to make thee wise unto salvation through faith which is in Christ Jesus."');

-- ═══ 2 Timothy Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Timothy', 4, 'kids', 1, 'What does Paul tell Timothy to preach?', 'The word', 'His own ideas', 'Funny stories', 'Political opinions', 'a', '2 Timothy 4:2 — "Preach the word; be instant in season, out of season."'),
('2 Timothy', 4, 'kids', 2, 'What does Paul say he has finished?', 'His course (race)', 'Building a house', 'Writing a book', 'Traveling the world', 'a', '2 Timothy 4:7 — "I have fought a good fight, I have finished my course."'),
('2 Timothy', 4, 'kids', 3, 'What is laid up (waiting) for Paul?', 'A crown of righteousness', 'A bag of gold', 'A new house', 'A fancy robe', 'a', '2 Timothy 4:8 — "Henceforth there is laid up for me a crown of righteousness."'),
-- Teens
('2 Timothy', 4, 'teens', 1, 'What three things does Paul say he has done in verse 7?', 'Fought a good fight, finished his course, kept the faith', 'Built many churches, healed many sick, raised the dead', 'Written many letters, traveled many miles, made many converts', 'Preached many sermons, baptized many converts, planted many churches', 'a', '2 Timothy 4:7 — "I have fought a good fight, I have finished my course, I have kept the faith."'),
('2 Timothy', 4, 'teens', 2, 'Why did Demas forsake Paul according to verse 10?', 'Having loved this present world', 'He was sick and needed rest', 'He was called to another ministry', 'He was afraid of persecution', 'a', '2 Timothy 4:10 — "For Demas hath forsaken me, having loved this present world, and is departed unto Thessalonica."'),
('2 Timothy', 4, 'teens', 3, 'Who was the only companion still with Paul?', 'Luke', 'Timothy', 'Titus', 'Barnabas', 'a', '2 Timothy 4:11 — "Only Luke is with me."'),
('2 Timothy', 4, 'teens', 4, 'What does Paul say people will want instead of sound doctrine?', 'Teachers who tell them what they want to hear (having itching ears)', 'Stricter rules and regulations', 'More miracles and signs', 'Longer worship services', 'a', '2 Timothy 4:3 — "For the time will come when they will not endure sound doctrine; but after their own lusts shall they heap to themselves teachers, having itching ears."'),
('2 Timothy', 4, 'teens', 5, 'Who does Paul say did him much evil?', 'Alexander the coppersmith', 'Demas the tentmaker', 'Trophimus the Ephesian', 'Erastus the chamberlain', 'a', '2 Timothy 4:14 — "Alexander the coppersmith did me much evil: the Lord reward him according to his works."'),
-- Adults
('2 Timothy', 4, 'adults', 1, 'Before whom does Paul charge Timothy to preach the word in verse 1?', 'Before God and the Lord Jesus Christ, who shall judge the quick and the dead', 'Before the church elders', 'Before the Roman authorities', 'Before the Jewish Sanhedrin', 'a', '2 Timothy 4:1 — "I charge thee therefore before God, and the Lord Jesus Christ, who shall judge the quick and the dead at his appearing and his kingdom."'),
('2 Timothy', 4, 'adults', 2, 'What five imperatives does Paul give Timothy in verse 2?', 'Preach, reprove, rebuke, exhort with all longsuffering and doctrine', 'Pray, fast, study, teach, and baptize', 'Heal, prophesy, cast out, deliver, and raise', 'Build, organize, lead, manage, and grow', 'a', '2 Timothy 4:2 — "Preach the word; be instant in season, out of season; reprove, rebuke, exhort with all longsuffering and doctrine."'),
('2 Timothy', 4, 'adults', 3, 'What metaphor does Paul use for his approaching death in verse 6?', 'Being poured out as a drink offering (ready to be offered)', 'Being consumed by fire', 'Being swept away by a flood', 'Being carried away by eagles', 'a', '2 Timothy 4:6 — "For I am now ready to be offered, and the time of my departure is at hand." The word "offered" (spendomai) means poured out as a drink offering.'),
('2 Timothy', 4, 'adults', 4, 'Who will receive the crown of righteousness according to verse 8?', 'All them that love his appearing', 'Only Paul and the apostles', 'Only those who are martyred', 'Only those who preach', 'a', '2 Timothy 4:8 — "Not to me only, but unto all them also that love his appearing."'),
('2 Timothy', 4, 'adults', 5, 'What personal items does Paul ask Timothy to bring in verse 13?', 'The cloke, the books, and especially the parchments', 'His sandals and staff', 'His money and provisions', 'His sword and shield', 'a', '2 Timothy 4:13 — "The cloke that I left at Troas with Carpus, when thou comest, bring with thee, and the books, but especially the parchments."'),
('2 Timothy', 4, 'adults', 6, 'What happened at Paul''s first answer (defense) according to verse 16?', 'No man stood with him, but all men forsook him', 'The whole church supported him', 'He was immediately released', 'He was condemned to death', 'a', '2 Timothy 4:16 — "At my first answer no man stood with me, but all men forsook me: I pray God that it may not be laid to their charge."'),
('2 Timothy', 4, 'adults', 7, 'Despite being forsaken, what does Paul say the Lord did in verse 17?', 'The Lord stood with him and strengthened him so the message could be fully known', 'The Lord sent angels to break him out', 'The Lord struck his enemies blind', 'The Lord destroyed the courtroom', 'a', '2 Timothy 4:17 — "Notwithstanding the Lord stood with me, and strengthened me; that by me the preaching might be fully known."'),
('2 Timothy', 4, 'adults', 8, 'What does Paul say the Lord delivered him from in verse 17?', 'The mouth of the lion', 'The Roman soldiers', 'The Jewish leaders', 'The stormy sea', 'a', '2 Timothy 4:17 — "And I was delivered out of the mouth of the lion." This likely refers to Nero or the danger of the Roman court.');
