-- ============================================================================
-- Quiz Seed: Matthew — Part 1 (Chapters 1–6)
-- 3 difficulties × 6 chapters = 96 total questions
--   kids:   3 per chapter  = 18
--   teens:  5 per chapter  = 30
--   adults: 8 per chapter  = 48
-- ============================================================================

-- ═══════════════ CHAPTERS 1–3 ═══════════════

-- ═══ Matthew Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 1, 'kids', 1, 'What was the name of the baby that the angel said Mary would have?', 'Jesus', 'John', 'David', 'Moses', 'a', 'Matthew 1:21 — "And she shall bring forth a son, and thou shalt call his name JESUS: for he shall save his people from their sins."'),
('Matthew', 1, 'kids', 2, 'Who was told in a dream not to be afraid to take Mary as his wife?', 'Joseph', 'Zacharias', 'Simeon', 'Peter', 'a', 'Matthew 1:20 — "But while he thought on these things, behold, the angel of the Lord appeared unto him in a dream, saying, Joseph, thou son of David, fear not to take unto thee Mary thy wife."'),
('Matthew', 1, 'kids', 3, 'What does the name "Emmanuel" mean?', 'God with us', 'Prince of Peace', 'Mighty King', 'Son of Man', 'a', 'Matthew 1:23 — "Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us."'),
-- Teens
('Matthew', 1, 'teens', 1, 'Why does Matthew begin his Gospel with a genealogy of Jesus?', 'To prove that Jesus is the son of David and the son of Abraham, fulfilling Old Testament messianic promises', 'To list all the important people in Israel', 'To show that Jesus came from a wealthy family', 'To compare Jesus with Roman emperors', 'a', 'Matthew 1:1 — "The book of the generation of Jesus Christ, the son of David, the son of Abraham." Matthew establishes Jesus'' legal right to the Davidic throne and His connection to the Abrahamic covenant.'),
('Matthew', 1, 'teens', 2, 'What unusual women are mentioned in Jesus'' genealogy?', 'Tamar, Rahab, Ruth, and Bathsheba (wife of Uriah) — all with irregular or Gentile backgrounds, showing God''s grace reaches beyond expected boundaries', 'Only queens and princesses', 'No women are mentioned at all', 'Only Mary is mentioned', 'a', 'Matthew 1:3,5,6 — The inclusion of Tamar (Canaanite situation), Rahab (Canaanite prostitute), Ruth (Moabitess), and Bathsheba (adultery scandal) foreshadows the gospel''s reach to sinners and Gentiles.'),
('Matthew', 1, 'teens', 3, 'What did Joseph initially plan to do when he found out Mary was pregnant?', 'Put her away privily (divorce her quietly), because he was a just man and did not want to make her a public example', 'Announce the pregnancy to the whole village', 'Take her immediately to the temple', 'Leave the country with her', 'a', 'Matthew 1:19 — "Then Joseph her husband, being a just man, and not willing to make her a publick example, was minded to put her away privily."'),
('Matthew', 1, 'teens', 4, 'What Old Testament prophecy does Matthew say the virgin birth fulfils?', 'Isaiah 7:14 — "Behold, a virgin shall be with child, and shall bring forth a son, and they shall call his name Emmanuel"', 'Micah 5:2 about Bethlehem', 'Jeremiah 31:15 about Rachel weeping', 'Hosea 11:1 about calling a son out of Egypt', 'a', 'Matthew 1:22-23 — "Now all this was done, that it might be fulfilled which was spoken of the Lord by the prophet, saying, Behold, a virgin shall be with child."'),
('Matthew', 1, 'teens', 5, 'What does the name "Jesus" mean and why was He given that name?', 'It means "Jehovah saves" — He was given this name because He shall save His people from their sins', 'It means "mighty ruler" because He would reign on earth', 'It means "wise teacher" because He would teach in the temple', 'It means "beloved son" because He was God''s favourite', 'a', 'Matthew 1:21 — "Thou shalt call his name JESUS: for he shall save his people from their sins." The name Iesous (Greek) comes from the Hebrew Yeshua/Yehoshua meaning "Yahweh saves."'),
-- Adults
('Matthew', 1, 'adults', 1, 'What is the significance of Matthew structuring the genealogy into three sets of fourteen generations?', 'The number fourteen is the numerical value of David''s name in Hebrew (D=4, V=6, D=4), so the threefold structure emphasises Jesus'' Davidic kingship. It organises history into three epochs: Abraham to David (promise), David to Babylonian exile (monarchy/failure), exile to Christ (restoration)', 'It was simply a convenient round number', 'Fourteen was a sacred temple number', 'Matthew was following Roman counting methods', 'a', 'Matthew 1:17 — "So all the generations from Abraham to David are fourteen generations; and from David until the carrying away into Babylon are fourteen generations; and from the carrying away into Babylon unto Christ are fourteen generations." The gematria of David (דוד = 4+6+4 = 14) underscores the Davidic theme.'),
('Matthew', 1, 'adults', 2, 'Why does Matthew trace the genealogy through Joseph if Jesus was born of a virgin?', 'Joseph provided Jesus'' legal lineage and royal right to the Davidic throne — in Jewish law, legal paternity (not biological) determined inheritance rights. Matthew establishes Jesus'' legal claim to kingship through Joseph''s line from David and Solomon', 'Matthew made an error in the genealogy', 'Joseph was actually Jesus'' biological father', 'The genealogy was added by later editors', 'a', 'Matthew 1:16 — "And Jacob begat Joseph the husband of Mary, of whom was born Jesus." Note Matthew carefully says Jesus was born "of Mary" (not "begotten by Joseph"), preserving the virgin birth while establishing legal Davidic descent.'),
('Matthew', 1, 'adults', 3, 'What does Matthew''s use of "begat" (egennesen) throughout the genealogy and its absence in verse 16 signify?', 'Matthew deliberately breaks the "begat" pattern at verse 16, saying Joseph was "the husband of Mary, of whom was born Jesus" — the passive voice and shift in language carefully distinguishes Jesus'' birth from natural generation, affirming the virgin birth within the genealogical framework', 'It was a scribal copying error', 'The word simply ran out of use', 'There is no change in wording', 'a', 'Matthew 1:16 — The consistent pattern "A begat B" breaks at the climax. Instead of "Joseph begat Jesus," Matthew writes "Joseph the husband of Mary, of whom [feminine singular, referring to Mary alone] was born Jesus." The grammar itself proclaims the virgin conception.'),
('Matthew', 1, 'adults', 4, 'How does the inclusion of Rahab and Ruth in the genealogy foreshadow a key theme of Matthew''s Gospel?', 'Their inclusion as Gentile women foreshadows the Great Commission''s universal scope (28:19 "all nations") — the Messiah''s lineage already includes non-Israelites, demonstrating that God''s redemptive plan was never exclusively ethnic', 'They were included only because they were famous', 'Matthew was required to include all ancestors', 'These women were all Jewish by birth', 'a', 'Matthew 1:5 — Rahab was a Canaanite from Jericho (Joshua 2), Ruth was a Moabitess (Ruth 1:4). Their presence in the Messiah''s line shows God''s grace crossing ethnic boundaries long before the Great Commission.'),
('Matthew', 1, 'adults', 5, 'What does the angel''s phrase "that which is conceived in her is of the Holy Ghost" establish doctrinally?', 'It establishes the doctrine of the virginal conception — Jesus'' human nature was supernaturally generated by the Holy Spirit within Mary''s womb, making Him truly human (born of woman) yet without inherited sin, and truly divine (conceived by the Spirit)', 'Joseph was the biological father', 'Jesus was adopted by God at baptism', 'The Spirit merely blessed a natural conception', 'a', 'Matthew 1:20 — "That which is conceived in her is of the Holy Ghost." The preposition "ek" (of/from) indicates the Holy Spirit as the generative agent. This is not adoptionism but incarnation: the eternal Son taking human nature through a miraculous conception.'),
('Matthew', 1, 'adults', 6, 'How does the title "Christ" (Christos) in verse 1 function differently from how we use it today?', 'In Matthew 1:1, "Christ" is a title meaning "the Anointed One" (Hebrew: Mashiach/Messiah) — it designates Jesus as the long-awaited anointed King, Priest, and Prophet. Over time it became used as a surname, but originally it was a royal messianic title', 'Christ was always Jesus'' surname', 'It was a common Jewish first name', 'It was a Roman honorary title', 'a', 'Matthew 1:1 — "Jesus Christ" = "Jesus the Messiah." Christos translates the Hebrew Mashiach (anointed one). In the OT, kings (1 Samuel 16:13), priests (Exodus 28:41), and prophets (1 Kings 19:16) were anointed. Jesus fulfils all three offices.'),
('Matthew', 1, 'adults', 7, 'What does Joseph''s obedience after the dream reveal about his character and role?', 'Joseph acts immediately in faith — "he did as the angel of the Lord had bidden him" — demonstrating quiet, righteous obedience. He serves as Jesus'' legal father, protector, and the one through whom Davidic lineage is transmitted, despite personal cost to his reputation', 'Joseph was passive and indifferent', 'Joseph resisted the angel''s command', 'Joseph sought a second opinion first', 'a', 'Matthew 1:24 — "Then Joseph being raised from sleep did as the angel of the Lord had bidden him, and took unto him his wife." Joseph''s immediate obedience mirrors Abraham''s faith-response. He becomes the silent, faithful guardian of the incarnation.'),
('Matthew', 1, 'adults', 8, 'What does Matthew 1:25 mean by "he knew her not till she had brought forth her firstborn son"?', 'The verse affirms that Joseph had no marital relations with Mary until after Jesus'' birth, emphasising the virgin birth. The word "till" (heos) indicates the state before the birth; whether the marriage was consummated afterward is not the verse''s concern — its purpose is to confirm Jesus'' virginal conception', 'Joseph never had relations with Mary at any point', 'The verse denies the virgin birth', 'This is a later textual addition', 'a', 'Matthew 1:25 — "And knew her not till she had brought forth her firstborn son." The focus of "heos" (until) is to guarantee virginity before and during the birth. Matthew''s concern is Christological (virgin birth), not Mariological.');

-- ═══ Matthew Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 2, 'kids', 1, 'Who followed a star to find baby Jesus?', 'Wise men from the east', 'Shepherds from nearby fields', 'Roman soldiers', 'Temple priests', 'a', 'Matthew 2:1-2 — "There came wise men from the east to Jerusalem, Saying, Where is he that is born King of the Jews? for we have seen his star in the east, and are come to worship him."'),
('Matthew', 2, 'kids', 2, 'What gifts did the wise men bring to Jesus?', 'Gold, frankincense, and myrrh', 'Silver, bread, and wine', 'Jewels, silk, and spices', 'Crowns, swords, and shields', 'a', 'Matthew 2:11 — "And when they had opened their treasures, they presented unto him gifts; gold, and frankincense, and myrrh."'),
('Matthew', 2, 'kids', 3, 'Where did Joseph take Mary and baby Jesus to keep them safe from King Herod?', 'Egypt', 'Rome', 'Babylon', 'Damascus', 'a', 'Matthew 2:14 — "When he arose, he took the young child and his mother by night, and departed into Egypt."'),
-- Teens
('Matthew', 2, 'teens', 1, 'Why was King Herod troubled when the wise men asked about the newborn king?', 'He saw the child as a threat to his throne and wanted to destroy any rival king', 'He was happy to hear about a new king', 'He wanted to worship the child himself', 'He did not believe in prophecy', 'a', 'Matthew 2:3 — "When Herod the king had heard these things, he was troubled, and all Jerusalem with him." Herod the Great was notoriously paranoid and had already killed his own sons to protect his throne.'),
('Matthew', 2, 'teens', 2, 'What Old Testament prophecy told the chief priests where the Messiah would be born?', 'Micah 5:2 — "And thou Bethlehem, in the land of Juda, art not the least among the princes of Juda: for out of thee shall come a Governor, that shall rule my people Israel"', 'Isaiah 7:14 about a virgin birth', 'Malachi 3:1 about a messenger', 'Daniel 9:25 about seventy weeks', 'a', 'Matthew 2:5-6 — The chief priests and scribes quote Micah 5:2, identifying Bethlehem as the Messiah''s birthplace. They knew the prophecy but did not act on it.'),
('Matthew', 2, 'teens', 3, 'What did God tell the wise men in a dream?', 'They should not return to Herod but depart into their own country another way', 'They should stay in Bethlehem forever', 'They should go and tell Herod everything', 'They should bring more gifts to Jerusalem', 'a', 'Matthew 2:12 — "And being warned of God in a dream that they should not return to Herod, they departed into their own country another way."'),
('Matthew', 2, 'teens', 4, 'What terrible thing did Herod do when the wise men did not return?', 'He sent soldiers to kill all the male children in Bethlehem who were two years old and under', 'He sent soldiers to arrest the wise men', 'He closed the temple in Jerusalem', 'He banished all foreigners from the land', 'a', 'Matthew 2:16 — "Then Herod... sent forth, and slew all the children that were in Bethlehem, and in all the coasts thereof, from two years old and under."'),
('Matthew', 2, 'teens', 5, 'Where did Joseph settle with his family when they returned from Egypt?', 'Nazareth in Galilee, fulfilling the prophecy "He shall be called a Nazarene"', 'Bethlehem in Judaea', 'Jerusalem near the temple', 'Jericho by the Jordan', 'a', 'Matthew 2:23 — "And he came and dwelt in a city called Nazareth: that it might be fulfilled which was spoken by the prophets, He shall be called a Nazarene."'),
-- Adults
('Matthew', 2, 'adults', 1, 'What is the significance of the three gifts — gold, frankincense, and myrrh — brought by the Magi?', 'They symbolise Jesus'' threefold office: gold for His kingship, frankincense for His deity/priesthood (used in temple worship), and myrrh for His suffering and death (used in embalming) — each gift prophetically reveals an aspect of His identity and mission', 'They were simply the most expensive items available', 'They were standard diplomatic gifts for any ruler', 'They had no symbolic meaning', 'a', 'Matthew 2:11 — Gold (royal tribute, cf. Psalm 72:15), frankincense (priestly incense, cf. Exodus 30:34), myrrh (burial spice, cf. John 19:39). The gifts anticipate Jesus as King, Priest, and Sacrifice.'),
('Matthew', 2, 'adults', 2, 'How does Matthew''s "fulfilment formula" function in chapter 2, and how many OT prophecies does he cite?', 'Matthew cites four OT fulfilment prophecies in chapter 2 alone: Micah 5:2 (born in Bethlehem, v.6), Hosea 11:1 (out of Egypt, v.15), Jeremiah 31:15 (Rachel weeping, v.18), and the Nazarene prophecy (v.23) — establishing a pattern of showing Jesus as the fulfilment of Israel''s story', 'Matthew cites only one prophecy', 'Matthew does not use fulfilment language', 'These prophecies were added later', 'a', 'Matthew uses "that it might be fulfilled" (hina plerothe) as a recurring formula (1:22; 2:15,17,23). Each citation shows Jesus recapitulating Israel''s experience: born in David''s city, called from Egypt, mourned by Rachel, raised in obscurity.'),
('Matthew', 2, 'adults', 3, 'What does "Out of Egypt have I called my son" (Hosea 11:1) mean in its original context, and how does Matthew apply it to Jesus?', 'In Hosea 11:1 "my son" refers to Israel as a nation called out of Egyptian bondage. Matthew applies it typologically to Jesus — as the true Israel, Jesus recapitulates Israel''s exodus, succeeding where Israel failed. This is typological fulfilment, not simple prediction', 'Hosea was directly predicting Jesus'' trip to Egypt', 'Matthew misquoted Hosea', 'The passage only refers to Moses', 'a', 'Matthew 2:15 — "That it might be fulfilled which was spoken of the Lord by the prophet, saying, Out of Egypt have I called my son." Matthew sees Jesus as the embodiment of Israel — the true Son who relives and redeems Israel''s story.'),
('Matthew', 2, 'adults', 4, 'Who were the Magi historically, and what does their visit signify theologically?', 'The Magi were likely Zoroastrian priest-astronomers from Persia or Babylon. Their visit signifies Gentile recognition of the Jewish Messiah — pagan scholars travel to worship while Jewish leaders (who knew the prophecies) remained in Jerusalem. This foreshadows the Great Commission', 'They were Jewish rabbis from Alexandria', 'They were Roman diplomats', 'They were three kings from Africa', 'a', 'Matthew 2:1-2 — "Wise men from the east" (magoi apo anatolon) were likely Persian astrologer-priests. Their long journey to worship contrasts sharply with the chief priests'' indifference (v.4-6), previewing the pattern in Acts where Gentiles receive what Israel rejects.'),
('Matthew', 2, 'adults', 5, 'What does the massacre of the innocents reveal about the nature of opposition to Christ?', 'Herod''s massacre reveals that opposition to Christ is violent, irrational, and ultimately futile — earthly power sees divine kingship as a mortal threat. Herod represents all human attempts to destroy God''s purposes, which invariably fail while causing great suffering to the innocent', 'Herod was acting rationally and justly', 'The massacre was purely political with no spiritual dimension', 'God could have prevented innocent suffering but chose not to', 'a', 'Matthew 2:16-18 — Herod''s slaughter echoes Pharaoh''s killing of Hebrew infants (Exodus 1:22). Both tyrants tried to destroy God''s deliverer and failed. The pattern recurs: human power rages against God''s anointed (Psalm 2:1-4) but cannot prevail.'),
('Matthew', 2, 'adults', 6, 'What is the likely meaning of "He shall be called a Nazarene" since no single OT verse says this?', 'Matthew says "prophets" (plural), suggesting a composite allusion — most likely to the Hebrew word "netzer" (branch) in Isaiah 11:1, connecting Jesus to the messianic Branch, and possibly to the lowly reputation of Nazareth, fulfilling the theme that the Messiah would be despised (Isaiah 53:3)', 'Matthew made up the prophecy', 'There is a lost book of the Bible that contained it', 'It refers to the Nazirite vow of Numbers 6', 'a', 'Matthew 2:23 — "He shall be called a Nazarene." The plural "prophets" points to a thematic fulfilment. "Nazareth" likely derives from "netzer" (branch, Isaiah 11:1). The town''s insignificance (John 1:46 "Can any good thing come out of Nazareth?") fits the despised-servant motif.'),
('Matthew', 2, 'adults', 7, 'How does Matthew''s application of Jeremiah 31:15 ("Rachel weeping for her children") work as typological fulfilment?', 'Jeremiah 31:15 originally described Rachel (buried near Bethlehem) symbolically weeping over Israel''s exile to Babylon. Matthew sees a deeper fulfilment: the Bethlehem mothers weeping over their slaughtered sons, with Rachel as the archetypal grieving mother of Israel. But in Jeremiah, hope follows weeping (31:16-17) — pointing to ultimate restoration', 'Matthew quoted the wrong passage', 'Rachel was literally alive and weeping', 'The passage has nothing to do with Bethlehem', 'a', 'Matthew 2:17-18 — Jeremiah 31:15 sits in a context of hope: "Refrain thy voice from weeping... they shall come again from the land of the enemy" (31:16-17). Matthew''s typology implies that even this horrific tragedy exists within God''s redemptive plan.'),
('Matthew', 2, 'adults', 8, 'What does the pattern of divine guidance through dreams in Matthew 1-2 suggest about God''s providence?', 'God directs events through five dreams in chapters 1-2 (1:20 to Joseph; 2:12 to the Magi; 2:13, 2:19, 2:22 to Joseph) — each dream steers events to fulfil prophecy while protecting the child. This demonstrates that God''s sovereign providence works through ordinary means (dreams, travel decisions) to accomplish His purposes', 'Dreams were unreliable and God would not use them', 'Only one dream occurs in these chapters', 'The dreams were Joseph''s imagination', 'a', 'Five dreams in Matthew 1-2 guide every critical decision: taking Mary as wife, the Magi''s departure route, the flight to Egypt, the return from Egypt, and the settlement in Nazareth. God''s invisible hand directs visible history.');

-- ═══ Matthew Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 3, 'kids', 1, 'Who preached in the wilderness saying "Repent ye: for the kingdom of heaven is at hand"?', 'John the Baptist', 'Jesus', 'Peter', 'Moses', 'a', 'Matthew 3:1-2 — "In those days came John the Baptist, preaching in the wilderness of Judaea, And saying, Repent ye: for the kingdom of heaven is at hand."'),
('Matthew', 3, 'kids', 2, 'What did John the Baptist eat in the wilderness?', 'Locusts and wild honey', 'Bread and fish', 'Fruit and vegetables', 'Meat and cheese', 'a', 'Matthew 3:4 — "And his meat was locusts and wild honey."'),
('Matthew', 3, 'kids', 3, 'What happened when Jesus was baptised in the Jordan River?', 'The heavens were opened, the Spirit of God descended like a dove, and a voice from heaven said "This is my beloved Son"', 'The river stopped flowing', 'A rainbow appeared in the sky', 'Thunder and lightning filled the sky', 'a', 'Matthew 3:16-17 — "The heavens were opened unto him, and he saw the Spirit of God descending like a dove, and lighting upon him: And lo a voice from heaven, saying, This is my beloved Son, in whom I am well pleased."'),
-- Teens
('Matthew', 3, 'teens', 1, 'What Old Testament prophet did John the Baptist fulfil?', 'Isaiah, who prophesied "The voice of one crying in the wilderness, Prepare ye the way of the Lord, make his paths straight"', 'Ezekiel, who saw the valley of dry bones', 'Daniel, who interpreted dreams', 'Jeremiah, who wept over Jerusalem', 'a', 'Matthew 3:3 — "For this is he that was spoken of by the prophet Esaias, saying, The voice of one crying in the wilderness, Prepare ye the way of the Lord, make his paths straight."'),
('Matthew', 3, 'teens', 2, 'What did John the Baptist call the Pharisees and Sadducees who came to his baptism?', 'A generation of vipers — and he warned them to bring forth fruits worthy of repentance', 'Distinguished guests and honoured leaders', 'The most righteous men in Israel', 'Friends and fellow workers', 'a', 'Matthew 3:7-8 — "But when he saw many of the Pharisees and Sadducees come to his baptism, he said unto them, O generation of vipers, who hath warned you to flee from the wrath to come? Bring forth therefore fruits meet for repentance."'),
('Matthew', 3, 'teens', 3, 'What warning did John give about relying on being descendants of Abraham?', 'He said God is able to raise up children unto Abraham from stones — ancestry alone does not save; repentance and fruit are required', 'He said Abraham''s descendants are automatically saved', 'He praised them for their family heritage', 'He said only Abraham''s children could be baptised', 'a', 'Matthew 3:9 — "And think not to say within yourselves, We have Abraham to our father: for I say unto you, that God is able of these stones to raise up children unto Abraham."'),
('Matthew', 3, 'teens', 4, 'How did John describe the One who would come after him?', 'He is mightier than I, whose shoes I am not worthy to bear — He shall baptise you with the Holy Ghost, and with fire', 'He will be a great military leader', 'He will be a wealthy merchant', 'He will be a political king from Rome', 'a', 'Matthew 3:11 — "He that cometh after me is mightier than I, whose shoes I am not worthy to bear: he shall baptize you with the Holy Ghost, and with fire."'),
('Matthew', 3, 'teens', 5, 'Why did Jesus say He needed to be baptised by John?', 'To fulfil all righteousness — Jesus identified with sinful humanity and publicly inaugurated His ministry by submitting to God''s plan', 'Because Jesus needed to repent of sin', 'Because John was more important than Jesus', 'Because it was a Roman requirement', 'a', 'Matthew 3:15 — "And Jesus answering said unto him, Suffer it to be now: for thus it becometh us to fulfil all righteousness."'),
-- Adults
('Matthew', 3, 'adults', 1, 'What does "the kingdom of heaven is at hand" mean, and why does Matthew use "kingdom of heaven" instead of "kingdom of God"?', 'It means God''s sovereign rule is breaking into human history through the Messiah''s arrival. Matthew uses "heaven" as a Jewish reverential circumlocution for God''s name (avoiding speaking it directly), not to describe a different kingdom — it is synonymous with "kingdom of God" in Mark and Luke', 'The kingdom is a physical place in the sky', 'Matthew describes a different kingdom than Mark', 'It refers only to the afterlife', 'a', 'Matthew 3:2 — "The kingdom of heaven is at hand." "At hand" (engiken) means "has drawn near" — the eschatological kingdom is arriving in Jesus'' person. Matthew''s "heaven" (ouranos) substitutes for "God" out of Jewish reverence, as confirmed by parallel passages in Mark/Luke.'),
('Matthew', 3, 'adults', 2, 'What does John''s imagery of the axe, winnowing fan, and unquenchable fire communicate about the coming Messiah?', 'John presents the Messiah as an eschatological judge — the axe at the tree root (v.10), the winnowing fork separating wheat from chaff (v.12), and unquenchable fire all depict imminent, decisive judgment. John expected the Messiah to bring both salvation and judgment simultaneously', 'These are farming tips for his audience', 'John was describing natural disasters', 'The images are purely decorative rhetoric', 'a', 'Matthew 3:10-12 — "The axe is laid unto the root of the trees... he will throughly purge his floor, and gather his wheat into the garner; but he will burn up the chaff with unquenchable fire." John''s Baptist ministry prepared Israel for this dual advent of grace and judgment.'),
('Matthew', 3, 'adults', 3, 'What is the significance of Jesus'' baptism being a Trinitarian theophany?', 'All three persons of the Trinity are simultaneously manifest: the Son is baptised, the Spirit descends as a dove, and the Father speaks from heaven — this is the most explicit Trinitarian revelation in the Gospels, inaugurating Jesus'' public ministry with divine endorsement', 'Only two persons of the Trinity are present', 'The Trinity doctrine was invented later', 'The dove was simply a natural bird', 'a', 'Matthew 3:16-17 — Son (being baptised), Spirit (descending as a dove), Father (speaking from heaven). This triune manifestation at the ministry''s inauguration parallels the Great Commission''s Trinitarian baptismal formula (28:19).'),
('Matthew', 3, 'adults', 4, 'What does "to fulfil all righteousness" mean in the context of Jesus'' sinless nature?', 'Jesus was not baptised for repentance but to identify with sinful humanity, to inaugurate His messianic ministry, and to submit to the Father''s will — "fulfilling all righteousness" means completing every aspect of God''s righteous requirements, foreshadowing His vicarious role as the representative of His people', 'Jesus was confessing personal sins', 'It was simply a cultural formality', 'Jesus was setting an example for swimming', 'a', 'Matthew 3:15 — "To fulfil all righteousness" (plerosai pasan dikaiosunen) means to accomplish all that God''s righteous plan requires. Jesus'' baptism identifies Him with sinners (cf. Isaiah 53:12), anticipates His death/resurrection (Romans 6:3-4), and receives the Father''s public endorsement.'),
('Matthew', 3, 'adults', 5, 'What does the Father''s declaration "This is my beloved Son, in whom I am well pleased" echo from the Old Testament?', 'It combines Psalm 2:7 ("Thou art my Son") — a royal enthronement psalm — with Isaiah 42:1 ("my servant... in whom my soul delighteth") — the Suffering Servant. This fusion identifies Jesus as both the Davidic King and the Suffering Servant, uniting two messianic streams', 'It quotes only from Genesis 1', 'It has no Old Testament background', 'It comes from Proverbs', 'a', 'Matthew 3:17 — "This is my beloved Son, in whom I am well pleased." Psalm 2:7 declares the Messiah as Son/King; Isaiah 42:1 introduces the Servant who will suffer. The Father''s words fuse kingship and servanthood in one person.'),
('Matthew', 3, 'adults', 6, 'What does the Spirit descending "like a dove" signify?', 'The dove imagery recalls Genesis 1:2 (Spirit hovering over waters) and Genesis 8:8-12 (Noah''s dove signalling new creation). The Spirit''s descent marks Jesus as the bearer of a new creation, anointing Him for His messianic mission as prophesied in Isaiah 61:1', 'Doves were simply common in the area', 'The dove was the Baptist''s pet bird', 'It was a hallucination from the heat', 'a', 'Matthew 3:16 — "The Spirit of God descending like a dove." The dove connects to creation (Genesis 1:2, Spirit over waters) and new beginning (Genesis 8:11, dove with olive branch). Jesus'' baptism inaugurates the new creation; the Spirit anoints the new Adam.'),
('Matthew', 3, 'adults', 7, 'How does John''s statement "I am not worthy to bear his shoes" position Jesus relative to John?', 'Carrying or untying a master''s sandals was the task of the lowest slave — a task so menial that Jewish tradition said even a Hebrew slave should not be required to do it. John declares himself unworthy of even slave-status before the Messiah, establishing an infinite qualitative difference between them', 'John was being falsely modest', 'Shoe-bearing was a prestigious honour', 'John literally could not lift the sandals', 'a', 'Matthew 3:11 — "Whose shoes I am not worthy to bear." The Talmud (b. Ketubbot 96a) states a disciple does everything a slave does for a master except removing sandals. John places himself below even a slave — the greatest prophet (11:11) acknowledges absolute subordination to Jesus.'),
('Matthew', 3, 'adults', 8, 'What is the relationship between John''s baptism with water and the Messiah''s baptism with the Holy Ghost and fire?', 'John''s water baptism was preparatory and symbolic — signifying repentance and readiness. The Messiah''s baptism with the Holy Spirit (Pentecost, Acts 2) brings regeneration and empowerment, while baptism with fire represents either purifying judgment or the purging fire of the Spirit. The two baptisms fulfil what John''s could only prefigure', 'They are identical in effect', 'Fire baptism means physical burning', 'John''s baptism was superior', 'a', 'Matthew 3:11 — "He shall baptize you with the Holy Ghost, and with fire." Water baptism symbolises; Spirit baptism actualises. "Fire" likely refers to judgment (v.12, "burn up the chaff") or purification (Malachi 3:2-3). Christ''s baptism accomplishes what John''s anticipated.');

-- ═══════════════ CHAPTERS 4–6 ═══════════════

-- ═══ Matthew Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 4, 'kids', 1, 'How many days did Jesus fast in the wilderness before the devil tempted Him?', 'Forty days and forty nights', 'Seven days', 'Three days', 'Ten days', 'a', 'Matthew 4:2 — "And when he had fasted forty days and forty nights, he was afterward an hungred."'),
('Matthew', 4, 'kids', 2, 'What did Jesus say when the devil told Him to turn stones into bread?', 'Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God', 'I am too tired to do miracles', 'That sounds like a good idea', 'I will turn them into fish instead', 'a', 'Matthew 4:4 — "But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God."'),
('Matthew', 4, 'kids', 3, 'What did Jesus say to His first disciples, Peter and Andrew?', 'Follow me, and I will make you fishers of men', 'Stay here and keep fishing', 'Go and build a temple', 'Sell your boats and buy land', 'a', 'Matthew 4:19 — "And he saith unto them, Follow me, and I will make you fishers of men."'),
-- Teens
('Matthew', 4, 'teens', 1, 'How did Jesus respond to each of the devil''s three temptations?', 'He quoted Scripture each time — "It is written" — using Deuteronomy 8:3, 6:16, and 6:13 to defeat every temptation with God''s Word', 'He used His own reasoning and logic', 'He asked the angels for help', 'He simply ignored the devil', 'a', 'Matthew 4:4,7,10 — Jesus responded to each temptation with "It is written" followed by quotes from Deuteronomy. He modelled fighting temptation with the Word of God.'),
('Matthew', 4, 'teens', 2, 'What did the devil offer Jesus if He would fall down and worship him?', 'All the kingdoms of the world and the glory of them', 'A palace in Jerusalem', 'The ability to fly through the air', 'Eternal life without suffering', 'a', 'Matthew 4:8-9 — "The devil taketh him up into an exceeding high mountain, and sheweth him all the kingdoms of the world, and the glory of them; And saith unto him, All these things will I give thee, if thou wilt fall down and worship me."'),
('Matthew', 4, 'teens', 3, 'Where did Jesus begin His public ministry of preaching?', 'In Galilee, specifically in Capernaum by the sea, fulfilling Isaiah''s prophecy about light dawning on those in darkness', 'In Jerusalem at the temple', 'In Bethlehem where He was born', 'In Egypt where He had lived as a child', 'a', 'Matthew 4:12-16 — "Jesus... departed into Galilee; And leaving Nazareth, he came and dwelt in Capernaum... That it might be fulfilled which was spoken by Esaias the prophet."'),
('Matthew', 4, 'teens', 4, 'What did James and John leave behind to follow Jesus?', 'They left the ship and their father Zebedee and followed Him immediately', 'They asked for time to think about it', 'They brought their whole family along', 'They continued fishing part-time', 'a', 'Matthew 4:22 — "And they immediately left the ship and their father, and followed him."'),
('Matthew', 4, 'teens', 5, 'What three things did Jesus do throughout Galilee?', 'Teaching in their synagogues, preaching the gospel of the kingdom, and healing all manner of sickness and disease among the people', 'Trading goods, building homes, and planting crops', 'Writing books, training soldiers, and collecting taxes', 'Judging disputes, making laws, and governing cities', 'a', 'Matthew 4:23 — "And Jesus went about all Galilee, teaching in their synagogues, and preaching the gospel of the kingdom, and healing all manner of sickness and all manner of disease among the people."'),
-- Adults
('Matthew', 4, 'adults', 1, 'How do the three temptations of Jesus parallel Israel''s wilderness failures?', 'Jesus succeeds where Israel failed: Israel craved bread/manna (Exodus 16) — Jesus trusts God''s word; Israel tested God at Massah (Exodus 17) — Jesus refuses to test God; Israel worshipped the golden calf (Exodus 32) — Jesus worships God alone. All three responses quote Deuteronomy, Israel''s wilderness book', 'There is no parallel with Israel', 'Jesus was tempted in completely different ways', 'The temptations only relate to Adam''s fall', 'a', 'Matthew 4:1-11 — Jesus quotes Deuteronomy 8:3, 6:16, and 6:13 — all from Israel''s wilderness narratives. As the true Israel/Son of God, He relives the wilderness test and succeeds, demonstrating perfect obedience where the nation failed.'),
('Matthew', 4, 'adults', 2, 'What does the devil''s use of Scripture (Psalm 91:11-12) in the second temptation teach about handling God''s Word?', 'Satan can quote Scripture accurately but apply it deceptively — Psalm 91 promises God''s protection for those walking in faithful obedience, not for those who manufacture danger to force God''s hand. Jesus corrects the misapplication with Deuteronomy 6:16: "Thou shalt not tempt the Lord thy God"', 'Satan cannot quote Scripture', 'Any use of Scripture is automatically valid', 'Jesus agreed with Satan''s interpretation', 'a', 'Matthew 4:6-7 — Satan quotes Psalm 91:11-12 to suggest Jesus jump from the temple pinnacle. Jesus'' counter-quote (Deuteronomy 6:16) shows that Scripture must interpret Scripture — no verse can be used to contradict the whole counsel of God.'),
('Matthew', 4, 'adults', 3, 'What is the significance of Jesus being "led up of the Spirit" into the wilderness to be tempted?', 'The temptation was divinely ordained, not an accident — the Spirit deliberately led Jesus into confrontation with Satan, showing that testing is part of God''s plan for proving and demonstrating faithfulness. Jesus'' victory over Satan inaugurates His ministry with authority over the enemy', 'Jesus wandered into the wilderness by mistake', 'The Spirit had no involvement', 'Satan forced Jesus into the wilderness', 'a', 'Matthew 4:1 — "Then was Jesus led up of the Spirit into the wilderness to be tempted of the devil." The divine passive ("led up of the Spirit") shows God''s sovereign initiative. Jesus enters ministry not with a miracle but with a battle — and a victory.'),
('Matthew', 4, 'adults', 4, 'How does Isaiah 9:1-2 relate to Jesus beginning His ministry in Galilee?', 'Isaiah prophesied that "Galilee of the Gentiles" — a region despised by Jerusalem''s elite — would see a great light. Jesus choosing Galilee (not Jerusalem) as His ministry base fulfils this prophecy and signals that the gospel starts at the margins, not the centres of power', 'Isaiah never mentioned Galilee', 'Jesus chose Galilee for its wealth', 'Galilee was the religious capital of Israel', 'a', 'Matthew 4:14-16 — "The land of Zabulon, and the land of Nephthalim... Galilee of the Gentiles; The people which sat in darkness saw great light." Galilee''s mixed population and distance from Jerusalem made it "lesser" — yet God chose it for revelation.'),
('Matthew', 4, 'adults', 5, 'What does the immediate response of the fishermen-disciples ("straightway they left their nets") reveal about the nature of Jesus'' call?', 'Jesus'' call carried inherent divine authority that compelled an immediate, total response — leaving nets, boats, and family represents the cost of discipleship. The immediacy suggests a prior relationship (John 1:35-42) but emphasises that Jesus'' word demands and deserves complete allegiance', 'They were bored with fishing', 'They had already sold their boats', 'The call was tentative and optional', 'a', 'Matthew 4:20,22 — "And they straightway left their nets, and followed him... they immediately left the ship and their father, and followed him." The pattern of immediate, costly obedience establishes the standard for all discipleship.'),
('Matthew', 4, 'adults', 6, 'What does "fishers of men" imply about the nature of gospel ministry?', 'The metaphor transforms their existing skill into kingdom service — fishing involves going where the fish are, using appropriate methods, patience, and bringing in a catch. It reframes evangelism as active, intentional work that Jesus Himself will teach them, connecting their past experience to their future calling', 'It means they should literally keep fishing', 'It refers only to catching criminals', 'The phrase was a common Jewish idiom for teachers', 'a', 'Matthew 4:19 — "Follow me, and I will make you fishers of men." The phrase echoes Jeremiah 16:16 (God sending "fishers" to gather Israel). Jesus redefines their vocation: the same initiative, skill, and perseverance used in fishing will now be directed toward rescuing people.'),
('Matthew', 4, 'adults', 7, 'What does the summary statement in verse 23 reveal about the comprehensive nature of Jesus'' ministry?', 'Teaching (didactic), preaching (kerygmatic), and healing (therapeutic) form a threefold ministry pattern — Jesus addresses the whole person: mind (teaching), spirit (preaching the gospel), and body (healing). This holistic model becomes the pattern for apostolic ministry', 'Jesus only taught in synagogues', 'Healing was not part of His ministry', 'Preaching and teaching are identical', 'a', 'Matthew 4:23 — "Teaching in their synagogues, and preaching the gospel of the kingdom, and healing all manner of sickness." Three verbs, three modes of ministry. Teaching instructs the mind, preaching announces the kingdom, healing demonstrates its power.'),
('Matthew', 4, 'adults', 8, 'Why is it significant that Jesus'' message "Repent: for the kingdom of heaven is at hand" (4:17) is identical to John the Baptist''s (3:2)?', 'The identical message creates continuity between John and Jesus while also marking a transition — John prepared the way, Jesus inaugurates the kingdom. Both demand the same response (repentance), but Jesus brings what John only announced. After John''s arrest (v.12), Jesus takes up the proclamation, fulfilling John''s role as forerunner', 'Jesus copied John because He had no original message', 'The similarity is coincidental', 'John and Jesus were teaching different kingdoms', 'a', 'Matthew 4:17 — "From that time Jesus began to preach, and to say, Repent: for the kingdom of heaven is at hand." The verbal identity (3:2 = 4:17) shows Jesus validates John''s ministry while surpassing it — the kingdom John announced has now arrived in Jesus'' person.');

-- ═══ Matthew Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 5, 'kids', 1, 'Where did Jesus sit down to teach His famous Sermon on the Mount?', 'On a mountain', 'In the temple', 'On a boat', 'In a cave', 'a', 'Matthew 5:1 — "And seeing the multitudes, he went up into a mountain: and when he was set, his disciples came unto him."'),
('Matthew', 5, 'kids', 2, 'What did Jesus say we should be like in the world?', 'The salt of the earth and the light of the world', 'The biggest and strongest people', 'The richest people in town', 'The rulers of every country', 'a', 'Matthew 5:13-14 — "Ye are the salt of the earth... Ye are the light of the world."'),
('Matthew', 5, 'kids', 3, 'What did Jesus say about people who are peacemakers?', 'They shall be called the children of God', 'They will become kings', 'They will never have problems', 'They will always be popular', 'a', 'Matthew 5:9 — "Blessed are the peacemakers: for they shall be called the children of God."'),
-- Teens
('Matthew', 5, 'teens', 1, 'What are the Beatitudes?', 'A series of blessings Jesus pronounced on those who are poor in spirit, mourning, meek, hungry for righteousness, merciful, pure in heart, peacemakers, and persecuted', 'A list of rules that everyone must obey', 'A collection of punishments for sinners', 'A set of prayers to recite daily', 'a', 'Matthew 5:3-12 — The eight Beatitudes describe the character of kingdom citizens: "Blessed are the poor in spirit... Blessed are they that mourn... Blessed are the meek..." Each begins with "Blessed" (makarioi) meaning deeply happy or spiritually fortunate.'),
('Matthew', 5, 'teens', 2, 'What did Jesus say about the Law of Moses?', 'Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil', 'The law is no longer important at all', 'The law was written by men, not God', 'The law applies only to Pharisees', 'a', 'Matthew 5:17 — "Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil."'),
('Matthew', 5, 'teens', 3, 'How did Jesus raise the standard beyond the commandment "Thou shalt not kill"?', 'He said that even being angry with a brother without cause and calling someone "thou fool" puts you in danger of judgment — the commandment goes deeper than actions to the heart', 'He lowered the standard to make it easier', 'He said only murder matters, not anger', 'He removed the commandment entirely', 'a', 'Matthew 5:22 — "But I say unto you, That whosoever is angry with his brother without a cause shall be in danger of the judgment: and whosoever shall say to his brother, Raca, shall be in danger of the council: but whosoever shall say, Thou fool, shall be in danger of hell fire."'),
('Matthew', 5, 'teens', 4, 'What did Jesus teach about loving your enemies?', 'Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you and persecute you', 'Only love people who love you back', 'Avoid your enemies completely', 'Seek revenge on those who hurt you', 'a', 'Matthew 5:44 — "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you."'),
('Matthew', 5, 'teens', 5, 'What impossible-sounding standard did Jesus set at the end of chapter 5?', 'Be ye therefore perfect, even as your Father which is in heaven is perfect', 'Try your best and that is enough', 'Follow the Pharisees'' example', 'Perfection is not possible so do not try', 'a', 'Matthew 5:48 — "Be ye therefore perfect, even as your Father which is in heaven is perfect."'),
-- Adults
('Matthew', 5, 'adults', 1, 'How do the Beatitudes subvert conventional expectations of blessing and power?', 'Every beatitude blesses those whom the world considers weak or unfortunate — the poor in spirit, mourners, meek, persecuted. Jesus inverts worldly values: true blessedness belongs not to the powerful, wealthy, and celebrated but to the humble, suffering, and righteous. This is a kingdom manifesto that redefines success', 'The Beatitudes bless the strong and wealthy', 'They describe temporary emotional states', 'They apply only to monks and nuns', 'a', 'Matthew 5:3-12 — Each beatitude overturns human expectations: the poor inherit the kingdom, the meek inherit the earth, the persecuted are congratulated. Jesus'' kingdom operates on an entirely different value system than any earthly power structure.'),
('Matthew', 5, 'adults', 2, 'What does "poor in spirit" mean, and why does it receive the first blessing?', 'Being "poor in spirit" means recognising one''s spiritual bankruptcy before God — total dependence on divine grace rather than self-sufficiency. It is first because it is the foundation of all other beatitudes: only those who know their need can receive God''s kingdom', 'It means being financially poor', 'It means lacking courage or confidence', 'It refers to being unintelligent', 'a', 'Matthew 5:3 — "Blessed are the poor in spirit: for theirs is the kingdom of heaven." The phrase echoes Isaiah 66:2 ("him that is poor and of a contrite spirit, and trembleth at my word"). Spiritual poverty is the gateway to kingdom riches — the opposite of Pharisaic self-righteousness.'),
('Matthew', 5, 'adults', 3, 'What does Jesus mean by "fulfil" the Law in verse 17, and how does this differ from "destroy"?', 'To "fulfil" (plerosai) means to bring to full expression and intended completion — Jesus does not abolish the Law but reveals its deepest meaning, embodies its demands, and accomplishes its purpose. The antitheses that follow ("ye have heard... but I say unto you") do not contradict Moses but expose the Law''s full depth', 'Jesus replaced the Law with new rules', 'Fulfil means to repeat the Law exactly as given', 'Jesus destroyed some laws and kept others', 'a', 'Matthew 5:17 — "I am not come to destroy, but to fulfil." The six antitheses (5:21-48) demonstrate fulfilment: Jesus does not lower the standard but deepens it from external compliance to internal transformation. Murder → anger; adultery → lust; oaths → transparent speech.'),
('Matthew', 5, 'adults', 4, 'How do the six antitheses ("Ye have heard... but I say unto you") demonstrate Jesus'' authority?', 'Jesus speaks with unparalleled authority — not "thus saith the Lord" (prophetic) nor "Rabbi X says" (scribal), but "I say unto you." He claims authority to authoritatively interpret and intensify the Mosaic Law, positioning Himself as the divine Lawgiver, not merely a teacher or commentator', 'Jesus was simply offering personal opinions', 'He was contradicting Moses', 'The Pharisees gave Him permission to teach', 'a', 'Matthew 5:21-22,27-28,31-32,33-34,38-39,43-44 — Six times Jesus uses the formula "Ye have heard that it was said... But I say unto you." The authoritative "ego" (I) places Jesus above Moses, the prophets, and rabbinic tradition — an implicit claim to deity.'),
('Matthew', 5, 'adults', 5, 'What does the salt and light imagery teach about the Christian''s relationship to the world?', 'Salt preserves and seasons — Christians prevent moral decay and add "flavour" to society. Light illuminates — Christians are to be visible witnesses whose good works point others to God. Both metaphors assume engagement with the world, not withdrawal. Salt that loses its savour and hidden light both fail their purpose', 'Christians should withdraw from the world entirely', 'Salt and light are decorative metaphors', 'Only religious leaders are salt and light', 'a', 'Matthew 5:13-16 — "Ye are the salt of the earth... Ye are the light of the world. A city that is set on an hill cannot be hid." Both metaphors require contact (salt must touch food; light must be visible) and both can fail (tasteless salt, hidden lamp). The purpose: "that they may see your good works, and glorify your Father."'),
('Matthew', 5, 'adults', 6, 'What does Jesus'' teaching on anger (5:21-26) reveal about the relationship between the heart and outward behaviour?', 'Jesus traces murder to its root in anger and contempt — "Raca" (empty-headed fool) and "thou fool" (moral reprobate) show escalating contempt. By equating heart-attitudes with the sixth commandment''s scope, Jesus teaches that God judges the inner person, not just external actions', 'Only physical violence matters to God', 'Anger is never sinful', 'Jesus was exaggerating for effect', 'a', 'Matthew 5:21-22 — Jesus moves from the external act (murder) to internal dispositions (anger, contempt, verbal abuse). Each receives escalating consequences: judgment, council, hell fire. The heart is the battlefield; behaviour is merely the symptom.'),
('Matthew', 5, 'adults', 7, 'How does "turning the other cheek" (5:39) function in its original context?', 'A slap on the right cheek (with the back of the hand) was an insult of contempt, not a life-threatening attack. Jesus teaches not passive acceptance of injustice but refusal to retaliate with violence in the face of personal insult — breaking the cycle of honour-shame revenge without endorsing abuse or injustice', 'Christians must accept all forms of violence passively', 'Jesus was speaking only about literal slaps', 'This teaching applies only to monks', 'a', 'Matthew 5:39 — "Whosoever shall smite thee on thy right cheek, turn to him the other also." A right-handed slap on the right cheek is a backhand — a gesture of insult and social dominance. Jesus'' command subverts the honour-revenge cycle by refusing to play by its rules.'),
('Matthew', 5, 'adults', 8, 'What does "Be ye therefore perfect, even as your Father which is in heaven is perfect" demand?', 'The Greek "teleios" means complete, whole, or mature — not sinless perfection but wholeness of character, especially in love. The context (v.43-47) defines this perfection as loving without discrimination: God sends rain on the just and unjust alike. We are to love with the same undiscriminating wholeness', 'Absolute sinless perfection is required for salvation', 'Perfection means following every ritual law', 'Jesus was being sarcastic', 'a', 'Matthew 5:48 — "Perfect" (teleios) means whole, complete, all-encompassing. In context, it summarises the love-ethic: love enemies as well as friends, just as God blesses all people indiscriminately (v.45). Luke''s parallel (6:36) says "merciful" — confirming the meaning is wholeness of love.');

-- ═══ Matthew Chapter 6 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 6, 'kids', 1, 'What famous prayer did Jesus teach His disciples?', 'The Lord''s Prayer — "Our Father which art in heaven, Hallowed be thy name"', 'The Prayer of Moses', 'The Song of Solomon', 'The Psalm of David', 'a', 'Matthew 6:9 — "After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name."'),
('Matthew', 6, 'kids', 2, 'What did Jesus say about the birds of the air?', 'They do not sow or reap or gather into barns, yet your heavenly Father feeds them — and you are worth more than they are', 'Birds have to work very hard for their food', 'Birds are smarter than people', 'Birds do not need any food at all', 'a', 'Matthew 6:26 — "Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?"'),
('Matthew', 6, 'kids', 3, 'What did Jesus say we should seek first?', 'The kingdom of God and His righteousness', 'Money and nice things', 'Fame and popularity', 'A big house and fancy clothes', 'a', 'Matthew 6:33 — "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."'),
-- Teens
('Matthew', 6, 'teens', 1, 'What did Jesus say about people who pray loudly in public to be seen?', 'They are like hypocrites who love to pray standing in the synagogues and corners of streets to be seen of men — they have their reward already (human praise)', 'Public prayer is always wrong', 'Only loud prayers are heard by God', 'Praying in the synagogue is forbidden', 'a', 'Matthew 6:5 — "And when thou prayest, thou shalt not be as the hypocrites are: for they love to pray standing in the synagogues and in the corners of the streets, that they may be seen of men. Verily I say unto you, They have their reward."'),
('Matthew', 6, 'teens', 2, 'What does Jesus say about forgiveness in relation to prayer?', 'If ye forgive men their trespasses, your heavenly Father will also forgive you: but if ye forgive not men their trespasses, neither will your Father forgive your trespasses', 'Forgiveness is optional', 'God forgives everyone automatically', 'You only need to forgive your friends', 'a', 'Matthew 6:14-15 — "For if ye forgive men their trespasses, your heavenly Father will also forgive you: But if ye forgive not men their trespasses, neither will your Father forgive your trespasses."'),
('Matthew', 6, 'teens', 3, 'What did Jesus say about serving two masters?', 'No man can serve two masters: ye cannot serve God and mammon (money/wealth)', 'It is possible to serve two masters equally', 'Mammon is the name of an angel', 'Serving money is acceptable if you also serve God', 'a', 'Matthew 6:24 — "No man can serve two masters: for either he will hate the one, and love the other; or else he will hold to the one, and despise the other. Ye cannot serve God and mammon."'),
('Matthew', 6, 'teens', 4, 'How does Jesus use the lilies of the field to teach about worry?', 'The lilies do not toil or spin, yet Solomon in all his glory was not arrayed like one of them — if God clothes grass so beautifully, He will surely clothe His people', 'Lilies are more important than people', 'Everyone should become a farmer', 'Clothing is not important at all', 'a', 'Matthew 6:28-29 — "Consider the lilies of the field, how they grow; they toil not, neither do they spin: And yet I say unto you, That even Solomon in all his glory was not arrayed like one of these."'),
('Matthew', 6, 'teens', 5, 'What does Jesus say about worrying about tomorrow?', 'Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof', 'Planning for tomorrow is sinful', 'Tomorrow will always be better', 'Worrying helps you prepare better', 'a', 'Matthew 6:34 — "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof."'),
-- Adults
('Matthew', 6, 'adults', 1, 'How does the Lord''s Prayer function as a model for all prayer?', 'It establishes a pattern: begin with worship (hallowed be thy name), submit to God''s purposes (thy kingdom come, thy will be done), then bring personal needs (daily bread), relational needs (forgive our debts), and spiritual protection (lead us not into temptation, deliver us from evil). God''s glory precedes human need', 'It is the only prayer Christians should ever pray', 'Each phrase must be repeated exactly', 'The prayer was only for the apostles', 'a', 'Matthew 6:9-13 — The prayer moves from God-ward petitions (name, kingdom, will) to human-ward petitions (bread, forgiveness, protection). This order teaches that prayer begins with God''s glory, not our needs. It is a model ("after this manner"), not merely a formula.'),
('Matthew', 6, 'adults', 2, 'What does "Hallowed be thy name" mean, and why does it come first?', 'To "hallow" means to treat as holy, sacred, and set apart. By placing this first, Jesus teaches that the primary purpose of prayer (and life) is God''s glory — His name being honoured, revered, and treated as supremely holy. All other petitions flow from this desire for God''s honour', 'It is a greeting like "hello"', 'It refers to making God''s name a secret', 'It is a request for God to reveal His name', 'a', 'Matthew 6:9 — "Hallowed be thy name." The passive voice ("be hallowed") asks God to cause His name to be treated as holy — both by us and in the world. This echoes the third commandment (Exodus 20:7) and Ezekiel 36:23. God''s glory is prayer''s first and highest concern.'),
('Matthew', 6, 'adults', 3, 'What does Jesus mean by "lay not up for yourselves treasures upon earth... but lay up for yourselves treasures in heaven"?', 'Jesus contrasts temporal, vulnerable wealth (moth, rust, thieves) with eternal, secure investment in God''s kingdom. "Where your treasure is, there will your heart be also" reveals that treasure placement determines heart orientation — giving and kingdom investment redirect the heart toward God', 'Christians must have no possessions', 'Saving money is always sinful', 'Heaven is a literal treasure vault', 'a', 'Matthew 6:19-21 — "Lay not up... treasures upon earth, where moth and rust doth corrupt, and where thieves break through and steal: But lay up... treasures in heaven." The point is not poverty but priority: treasure in heaven means investing in what has eternal value. The heart follows the treasure.'),
('Matthew', 6, 'adults', 4, 'What does "the eye is the lamp of the body" (6:22-23) mean in context between the treasures and mammon passages?', 'The "single" (haplous) eye means generous, undivided loyalty to God, while the "evil" (poneros) eye means stinginess and divided allegiance. Placed between teachings on treasure (v.19-21) and mammon (v.24), it warns that our spiritual vision — what we focus on — determines whether we walk in light or darkness', 'Jesus was giving medical advice about eyesight', 'This is about literal night vision', 'The eye passage is unrelated to the surrounding context', 'a', 'Matthew 6:22-23 — "The light of the body is the eye: if therefore thine eye be single, thy whole body shall be full of light." In Jewish idiom, a "good eye" meant generosity and a "bad eye" meant stinginess (cf. Deuteronomy 15:9; Proverbs 22:9). Jesus connects seeing rightly with living rightly.'),
('Matthew', 6, 'adults', 5, 'How does Jesus'' teaching on anxiety (6:25-34) address the root cause of worry?', 'Jesus identifies the root of worry as insufficient trust in God''s fatherly provision — worry is a practical form of functional atheism. He uses lesser-to-greater arguments (birds, lilies, grass) to show that if God cares for lesser creation, He will certainly care for His children. The antidote is not stoicism but faith: "seek ye first the kingdom"', 'Worry is merely a psychological problem', 'Jesus says all planning is sinful', 'Anxiety is unrelated to faith', 'a', 'Matthew 6:30-33 — "If God so clothe the grass of the field... shall he not much more clothe you, O ye of little faith?... seek ye first the kingdom of God." Jesus diagnoses worry as "little faith" (oligopistia), not a neurological condition. The cure is reorienting priorities toward God''s kingdom.'),
('Matthew', 6, 'adults', 6, 'What does "Give us this day our daily bread" reveal about the nature of dependence on God?', 'It teaches daily dependence — asking for "this day" echoes Israel''s daily manna (Exodus 16), where God provided one day at a time. The petition acknowledges that even physical sustenance comes from God, and that faith means trusting Him for today''s needs without hoarding for tomorrow', 'We should only eat bread and nothing else', 'Daily bread refers to spiritual food only', 'This prayer was for impoverished people only', 'a', 'Matthew 6:11 — "Give us this day our daily bread." The Greek "epiousios" (daily) is rare and debated, but the connection to Exodus 16 (daily manna) is clear. God provides not in bulk but daily, cultivating ongoing trust. "Our" (not "my") bread makes it communal.'),
('Matthew', 6, 'adults', 7, 'What is the relationship between divine and human forgiveness in verses 14-15?', 'Our willingness to forgive others is the evidence (not the cause) of having received God''s forgiveness — an unforgiving heart demonstrates that one has not truly grasped grace. Jesus does not teach that human forgiveness earns divine forgiveness, but that receiving God''s mercy necessarily transforms how we treat others', 'We must forgive others before God will forgive us', 'Forgiving others is optional for Christians', 'God''s forgiveness has no connection to our behaviour', 'a', 'Matthew 6:14-15 — "If ye forgive men... your heavenly Father will also forgive you." This is not forgiveness-by-works but a kingdom principle: those who have truly received mercy become merciful (cf. 18:21-35, the unforgiving servant). An unforgiving heart contradicts a claim to have received forgiveness.'),
('Matthew', 6, 'adults', 8, 'What does "mammon" represent, and why does Jesus personalise wealth as a rival master?', 'Mammon (Aramaic mamona, meaning wealth/possessions) is personalised as a competing lord to expose the idolatrous potential of money. Jesus does not say money is evil but that devotion to it is functionally a rival religion — you will either serve God with money as a tool, or serve money with God as an excuse. There is no middle ground', 'Mammon was a Canaanite god of wealth', 'Money is inherently evil and must be avoided', 'Mammon only refers to dishonest money', 'a', 'Matthew 6:24 — "Ye cannot serve God and mammon." By personifying wealth as "mammon," Jesus elevates it to the status of a rival deity. The word "serve" (douleuein) means to serve as a slave — total allegiance. Dual-allegiance is impossible; one master always wins.');
