-- ============================================================
-- Quiz Seed: Joshua Chapters 21–24
-- Target table: chapter_quizzes
-- Difficulties: kids (3 Qs), teens (5 Qs), adults (8 Qs)
-- ============================================================

-- ═══════════════════════════════════════════
-- CHAPTERS 21 – 24
-- ═══════════════════════════════════════════

-- ═══ Joshua Chapter 21 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 21, 'kids', 1, 'How many cities were given to the Levites to live in throughout all of Israel?', 'Twelve cities', 'Twenty-four cities', 'Forty-eight cities', 'Thirty-six cities', 'a', 'Joshua 21:41 — "All the cities of the Levites within the possession of the children of Israel were forty and eight cities with their suburbs."'),
('Joshua', 21, 'kids', 2, 'Did any of God''s promises to Israel fail at the end of chapter 21?', 'Yes, some promises were not kept', 'No, not one thing failed', 'Some were delayed for later generations', 'Only the small promises were kept', 'a', 'Joshua 21:45 — "There failed not ought of any good thing which the LORD had spoken unto the house of Israel; all came to pass."'),
('Joshua', 21, 'kids', 3, 'Which priestly family received the first group of Levitical cities because the high priest came from them?', 'The sons of Merari', 'The sons of Gershom', 'The sons of Kohath from the family of Aaron', 'The sons of Ithamar', 'a', 'Joshua 21:4 — "And the lot came out for the families of the Kohathites: and the children of Aaron the priest, which were of the Levites, had by lot out of the tribe of Judah... thirteen cities."'),
-- Teens
('Joshua', 21, 'teens', 1, 'Who came to Eleazar and Joshua at Shiloh to ask for the Levitical cities as Moses had commanded?', 'The Levitical heads of the fathers'' houses', 'The high priest Phinehas', 'The sons of Merari alone', 'All the Levites assembled at Shiloh', 'a', 'Joshua 21:1 — "Then came near the heads of the fathers of the Levites unto Eleazar the priest, and unto Joshua the son of Nun, and unto the heads of the fathers of the tribes of the children of Israel."'),
('Joshua', 21, 'teens', 2, 'How many cities did the sons of Aaron (the priestly branch of Kohath) receive from the tribes of Judah, Simeon, and Benjamin?', 'Nine cities', 'Ten cities', 'Twelve cities', 'Thirteen cities', 'a', 'Joshua 21:4 — "The children of Aaron the priest, which were of the Levites, had by lot out of the tribe of Judah, and out of the tribe of Simeon, and out of the tribe of Benjamin, thirteen cities."'),
('Joshua', 21, 'teens', 3, 'Which city of refuge in Judah''s hill country was given to the sons of Aaron as a Levitical city?', 'Shechem', 'Kedesh', 'Bezer', 'Hebron (Kirjath-arba)', 'a', 'Joshua 21:13 — "Thus they gave to the children of Aaron the priest, Hebron with her suburbs, to be a city of refuge for the slayer."'),
('Joshua', 21, 'teens', 4, 'What grand promise about Israel''s rest is stated in Joshua 21:44?', 'Israel would possess the land forever', 'The LORD gave them rest round about, according to all that he sware unto their fathers', 'Not one enemy stood before Israel in all the land', 'The LORD would fight for Israel in every future battle', 'a', 'Joshua 21:44 — "And the LORD gave them rest round about, according to all that he sware unto their fathers: and there stood not a man of all their enemies before them."'),
('Joshua', 21, 'teens', 5, 'How many cities did the remaining Kohathite families (non-Aaronic) receive from the tribes of Ephraim, Dan, and half-Manasseh?', 'Eight cities', 'Ten cities', 'Twelve cities', 'Fourteen cities', 'a', 'Joshua 21:5 — "And the rest of the children of Kohath had by lot out of the families of the tribe of Ephraim, and out of the tribe of Dan, and out of the half tribe of Manasseh, ten cities."'),
-- Adults
('Joshua', 21, 'adults', 1, 'What Mosaic command does the Levites'' request for cities fulfill, and in which book was it originally given?', 'Exodus 18 — Jethro''s advice to give Levites towns', 'Numbers 35 — God''s command to give Levites cities and pasture lands from the tribes'' inheritances', 'Deuteronomy 12 — the command to choose a central sanctuary', 'Leviticus 25 — the law of the Jubilee year', 'a', 'Joshua 21:2 — "The LORD commanded by the hand of Moses to give us cities to dwell in, with the suburbs thereof for our cattle" — this fulfills Numbers 35:1-8 where God specifically commanded the tribes to give cities with pastureland to the Levites.'),
('Joshua', 21, 'adults', 2, 'What is significant about the Levitical cities being distributed among all twelve tribes rather than concentrated in one region?', 'It ensured the Levites could trade with all tribes equally', 'It dispersed priestly ministry and teaching throughout all Israel, fulfilling the Levites'' role as Israel''s spiritual teachers', 'The Levites preferred to live in different regions', 'It fulfilled Jacob''s curse on Levi by scattering them throughout Israel', 'a', 'The distribution of 48 Levitical cities across all tribal territories (Joshua 21:3-42) ensured that every Israelite family had access to Levitical teaching and priestly service, fulfilling Deuteronomy 33:10 — "They shall teach Jacob thy judgments, and Israel thy law."'),
('Joshua', 21, 'adults', 3, 'How many cities did the Gershonite families receive, and from which tribes were they drawn?', 'Thirteen cities from Issachar, Asher, Naphtali, and east Manasseh', 'Ten cities from Zebulun, Reuben, and Gad', 'Twelve cities from all the northern tribes', 'Nine cities from Judah and Benjamin', 'a', 'Joshua 21:6 — "And the children of Gershon had by lot out of the families of the tribe of Issachar, and out of the tribe of Asher, and out of the tribe of Naphtali, and out of the half tribe of Manasseh in Bashan, thirteen cities."'),
('Joshua', 21, 'adults', 4, 'How many cities did the Merarite families receive and from which tribes?', 'Ten cities from Reuben, Gad, and Zebulun', 'Twelve cities from Reuben, Gad, and Zebulun', 'Eight cities from Reuben and Gad only', 'Fourteen cities from the eastern tribes', 'a', 'Joshua 21:7 — "The children of Merari by their families had out of the tribe of Reuben, and out of the tribe of Gad, and out of the tribe of Zebulun, twelve cities."'),
('Joshua', 21, 'adults', 5, 'What does the careful breakdown of Kohathite, Gershonite, and Merarite city assignments reveal about the organization of Levitical ministry?', 'The three Levitical branches had entirely equal status', 'Each Levitical family branch had distinct assigned regions corresponding to their specific duties at the tabernacle', 'The assignments were random with no connection to family roles', 'Only Aaron''s sons had sacred duties; other Levites were simply administrators', 'a', 'Numbers 3-4 assigns the Kohathites the most holy objects (ark, etc.), the Gershonites the tabernacle coverings, and the Merarites the frames and pillars. Their geographic distribution in Joshua 21 continues this organizational structure in the settled land.'),
('Joshua', 21, 'adults', 6, 'What theological climax does Joshua 21:43-45 provide for the entire book of Joshua?', 'It announces the coming of the monarchy', 'It declares the complete fulfillment of every promise God made to the fathers — land, rest, and victory', 'It warns Israel about the consequences of future disobedience', 'It calls Israel to renew the covenant at Shechem', 'a', 'Joshua 21:43-45 — "The LORD gave unto Israel all the land which he sware to give unto their fathers... There failed not ought of any good thing which the LORD had spoken unto the house of Israel; all came to pass." This is the theological summit of the book.'),
('Joshua', 21, 'adults', 7, 'Which city in the list of Levitical cities would later become famous as the home of Samuel and a major religious center of early Israel?', 'Shiloh', 'Ramah', 'Gibeon', 'Anathoth', 'a', 'Among the Levitical cities, Ramah (Joshua 21:18, from Benjamin) was the home of Samuel (1 Samuel 1:19, 7:17). Anathoth was also a Levitical city in Benjamin (Joshua 21:18) that later became the birthplace of Jeremiah (Jeremiah 1:1).'),
('Joshua', 21, 'adults', 8, 'What tension exists between Joshua 21:43-45 (all promises fulfilled) and passages like Joshua 13:1 and Judges 1 (land still unconquered)?', 'The author of Joshua made a historical error', 'The fulfillment was complete in terms of major military victory and covenantal possession, even though pockets of Canaanites remained in certain cities', 'The promises only referred to spiritual blessings, not physical land', 'Joshua 21 was written before the conquest was complete', 'a', 'The "fulfillment" language in 21:43-45 speaks of the covenantal promise being realized — Israel possessed the land as God swore — while passages elsewhere acknowledge that the mandate to drive out all inhabitants was not fully completed due to Israel''s disobedience (Joshua 15:63, 16:10, Judges 1).');

-- ═══ Joshua Chapter 22 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 22, 'kids', 1, 'What did the tribes of Reuben, Gad, and half-Manasseh build at the Jordan River that caused concern?', 'A new city', 'A great altar', 'A bridge to cross the Jordan', 'A wall of protection', 'a', 'Joshua 22:10 — "And when they came unto the borders of Jordan, that are in the land of Canaan, the children of Reuben and the children of Gad and the half tribe of Manasseh built there an altar by Jordan, a great altar to see to."'),
('Joshua', 22, 'kids', 2, 'Why were the western tribes upset about the altar the eastern tribes built?', 'It was built in the wrong location', 'They thought the eastern tribes were turning away from God', 'It was too big and used too many stones', 'The eastern tribes did not ask permission', 'a', 'Joshua 22:16 — "Thus saith the whole congregation of the LORD, What trespass is this that ye have committed against the God of Israel, to turn away this day from following the LORD?"'),
('Joshua', 22, 'kids', 3, 'What did the eastern tribes say the altar was actually for?', 'To offer sacrifices to other gods', 'As a witness between them and the western tribes that they also serve God', 'As a monument to their military victories', 'As a place for their priests to live', 'a', 'Joshua 22:27 — "But that it may be a witness between us, and you, and our generations after us, that we might do the service of the LORD before him with our burnt offerings."'),
-- Teens
('Joshua', 22, 'teens', 1, 'What did Joshua say the eastern tribes had done that earned his praise before he sent them home?', 'They built the most cities in the land', 'They had kept all that Moses commanded and had obeyed Joshua''s voice', 'They had converted the Moabites to follow God', 'They brought more tribute than any other tribe', 'a', 'Joshua 22:2-3 — "Ye have kept all that Moses the servant of the LORD commanded you, and have obeyed my voice in all that I commanded you: Ye have not left your brethren these many days unto this day."'),
('Joshua', 22, 'teens', 2, 'What warning did Joshua give the eastern tribes as they departed toward their inheritance?', 'Do not settle near the Ammonites', 'Take great heed to do the commandment and the law which Moses commanded — love the LORD and serve him with all your heart', 'Build strong cities to protect yourselves', 'Do not let your children intermarry with the Moabites', 'a', 'Joshua 22:5 — "But take diligent heed to do the commandment and the law, which Moses the servant of the LORD charged you, to love the LORD your God, and to walk in all his ways, and to keep his commandments, and to cleave unto him, and to serve him with all your heart and with all your soul."'),
('Joshua', 22, 'teens', 3, 'Who led the delegation of western tribes sent to confront the eastern tribes about the altar?', 'Joshua himself', 'Phinehas the son of Eleazar the priest', 'Caleb the son of Jephunneh', 'The elders of Judah', 'a', 'Joshua 22:13 — "And the children of Israel sent unto the children of Reuben, and to the children of Gad, and to the half tribe of Manasseh, into the land of Gilead, Phinehas the son of Eleazar the priest."'),
('Joshua', 22, 'teens', 4, 'What offer did the western tribes make if the eastern tribes felt their land was unclean?', 'Come and share our land', 'Offer sacrifices at Shiloh to purify yourselves', 'Leave Jordan and settle among us in the LORD''s tabernacle land', 'Submit to the rule of the western tribal elders', 'a', 'Joshua 22:19 — "Notwithstanding, if the land of your possession be unclean, then pass ye over unto the land of the possession of the LORD, wherein the LORD''s tabernacle dwelleth, and take possession among us."'),
('Joshua', 22, 'teens', 5, 'What name did the eastern tribes give to the altar, and what does it mean?', 'Peniel, meaning "face of God"', 'Ed, meaning "a witness between us that the LORD is God"', 'Mizpah, meaning "watchtower"', 'Jehovah-Shammah, meaning "the LORD is there"', 'a', 'Joshua 22:34 — "And the children of Reuben and the children of Gad called the altar Ed: for it shall be a witness between us that the LORD is God."'),
-- Adults
('Joshua', 22, 'adults', 1, 'What is the full wealth Joshua sent the eastern tribes home with, and what was its source?', 'Gold from the spoil of Jericho', 'Great riches — silver, gold, cattle, iron, and raiment divided from the spoil of enemies', 'The tribute paid by Canaanite cities', 'Offerings collected at Shiloh', 'a', 'Joshua 22:8 — "With much riches unto your tents, and with very much cattle, with silver, and with gold, and with brass, and with iron, and with very much raiment: divide the spoil of your enemies with your brethren."'),
('Joshua', 22, 'adults', 2, 'What historical parallel did Phinehas invoke to warn the eastern tribes of the danger of their action?', 'The sin of the golden calf at Sinai', 'The sin of Peor and the sin of Achan which brought plague on all Israel', 'The rebellion of Korah against Moses''s authority', 'The sin of Nadab and Abihu with strange fire', 'a', 'Joshua 22:17-18, 20 — "Is the iniquity of Peor too little for us... And, behold, Achan the son of Zerah committed a trespass in the accursed thing, and wrath fell on all the congregation of Israel."'),
('Joshua', 22, 'adults', 3, 'What key theological argument did the eastern tribes make to prove their altar was not for burnt offerings or sacrifices?', 'The altar had no wood or fire prepared on it', 'God forbid — rather it is a pattern and copy as a witness, not for burnt offering', 'The altar faced away from Jerusalem as a sign of non-worship', 'It was built with unhewn stones unlike the tabernacle altar', 'a', 'Joshua 22:23, 26-27 — "The LORD himself require it... But that it may be a witness between us, and you, and our generations after us, that we might do the service of the LORD before him with our burnt offerings."'),
('Joshua', 22, 'adults', 4, 'What did Phinehas and the ten princes declare when they heard the explanation of the eastern tribes?', 'They demanded the altar be destroyed anyway', 'This day we perceive that the LORD is among us, because ye have not committed this trespass', 'They returned without answering and consulted Joshua', 'They accepted the explanation but required an oath from the eastern tribes', 'a', 'Joshua 22:31 — "And Phinehas the son of Eleazar the priest said unto the children of Reuben, and to the children of Gad, and to the children of Manasseh, This day we perceive that the LORD is among us, because ye have not committed this trespass against the LORD."'),
('Joshua', 22, 'adults', 5, 'What does the near-civil-war in Joshua 22 reveal about the unity requirements of Israel''s covenant with God?', 'Tribal loyalty was more important than religious unity', 'Any act that appeared to deviate from the covenant worship could fracture national unity because Israel''s covenant relationship with God was a collective responsibility', 'The western tribes were overly suspicious of the eastern tribes', 'Religious disputes were to be settled by military force', 'a', 'Joshua 22:18 — "That ye might rebel to day against the LORD, and that he will be wroth with the whole congregation of Israel" — the entire community could bear the consequences of one tribe''s sin, reflecting the covenant solidarity demonstrated in the Achan episode (ch. 7).'),
('Joshua', 22, 'adults', 6, 'How does Phinehas''s leading role in this delegation connect to his earlier action at Peor (Numbers 25)?', 'Phinehas was the most experienced diplomat in Israel', 'As the one who stopped the plague at Peor by zeal for God''s honor, Phinehas was uniquely qualified to investigate potential apostasy', 'Phinehas was chosen because he was the youngest priest', 'Phinehas had previously negotiated treaties with eastern nations', 'a', 'Numbers 25:7-13 records Phinehas''s zealous action against the Peor apostasy, for which God granted him "an everlasting priesthood." He was therefore the right person to lead a delegation investigating potential idolatry — he had proven his commitment to covenant fidelity.'),
('Joshua', 22, 'adults', 7, 'What concern about future generations motivated the eastern tribes to build the altar, and is this concern justified by later biblical history?', 'They feared their children would forget Hebrew and lose all religious knowledge', 'They feared that future generations of western tribes might deny the eastern tribes'' right to worship the LORD, since they were separated by the Jordan', 'They wanted a permanent monument to their military service', 'They feared their children would intermarry with Moabites and lose their inheritance', 'a', 'Joshua 22:24-25 — "In time to come your children might speak unto our children, saying, What have ye to do with the LORD God of Israel? For the LORD hath made Jordan a border between us and you." The Jordan as a physical division was a real threat to religious unity, later realized in the division of the kingdom.'),
('Joshua', 22, 'adults', 8, 'What does the resolution of the altar controversy demonstrate about the proper means of addressing suspected covenant violations within Israel?', 'Military force was always the first resort', 'Sending a priestly-led inquiry delegation first, allowing explanation before war, reflects the Torah''s requirement to investigate fully before judgment', 'Only the high priest could resolve religious disputes', 'The accused must prove innocence through ordeal', 'a', 'Joshua 22:13-15 shows Israel sending Phinehas and the ten princes to investigate before mobilizing for war (22:12). This reflects Deuteronomy 13:14 — "Then shalt thou inquire, and make search, and ask diligently" before taking action against suspected apostasy.');

-- ═══ Joshua Chapter 23 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 23, 'kids', 1, 'Who gathered all Israel together to give them a farewell speech near the end of Joshua''s life?', 'Eleazar the priest', 'Joshua', 'Caleb', 'Phinehas', 'a', 'Joshua 23:1-2 — "And it came to pass a long time after that the LORD had given rest unto Israel... that Joshua called for all Israel, and for their elders, and for their heads, and for their judges, and for their officers."'),
('Joshua', 23, 'kids', 2, 'Who did Joshua say would fight for Israel against their enemies?', 'The army of Israel alone', 'The LORD their God', 'The angels of heaven', 'The priests with the ark', 'a', 'Joshua 23:10 — "One man of you shall chase a thousand: for the LORD your God, he it is that fighteth for you, as he hath promised you."'),
('Joshua', 23, 'kids', 3, 'What did Joshua warn Israel would happen if they married people from the remaining Canaanite nations?', 'They would become wealthy', 'God would no longer fight for them and those nations would be snares to them', 'They would lose their language', 'They would have to pay tribute', 'a', 'Joshua 23:12-13 — "If ye do in any wise go back, and cleave unto the remnant of these nations... they shall be snares and traps unto you, and scourges in your sides, and thorns in your eyes."'),
-- Teens
('Joshua', 23, 'teens', 1, 'What two things did Joshua say Israel must do in order to keep the blessings they had received?', 'Sacrifice regularly at Shiloh and pay tithes faithfully', 'Be courageous to keep the law of Moses and not turn to the right or left', 'Build cities and raise armies', 'Keep the Sabbath and the festivals', 'a', 'Joshua 23:6 — "Be ye therefore very courageous to keep and to do all that is written in the book of the law of Moses, that ye turn not aside therefrom to the right hand or to the left."'),
('Joshua', 23, 'teens', 2, 'What specific religious compromise did Joshua forbid Israel from making with the remaining nations?', 'Sharing farming techniques', 'Making mention of the names of their gods, swearing by them, serving or bowing to them', 'Trading at their markets', 'Learning their languages', 'a', 'Joshua 23:7 — "That ye come not among these nations, these that remain among you; neither make mention of the name of their gods, nor cause to swear by them, neither serve them, nor bow yourselves unto them."'),
('Joshua', 23, 'teens', 3, 'What was Joshua''s age description when he gave this farewell address?', 'He was old, stricken in age, a hundred years old', 'He was old and well stricken in years', 'He was fourscore and ten years old', 'He was the oldest man in Israel', 'a', 'Joshua 23:1-2 — "A long time after... Joshua waxed old and stricken in age" — and Joshua 24:29 records he died at 110, placing this speech near the very end of his life.'),
('Joshua', 23, 'teens', 4, 'What did Joshua say the LORD had done with the nations before Israel, and what would He continue to do?', 'God had destroyed all the nations', 'God had driven out great and strong nations and no man had stood before Israel, and He would continue to drive out remaining nations', 'God had given all the land into Israel''s hand permanently', 'God had made peace with the remaining nations on Israel''s behalf', 'a', 'Joshua 23:9 — "For the LORD hath driven out from before you great nations and strong: but as for you, no man hath been able to stand before you unto this day."'),
('Joshua', 23, 'teens', 5, 'What did Joshua say would happen to Israel if they broke the covenant and served other gods?', 'They would be enslaved in Egypt again', 'They would quickly perish from off the good land God had given them', 'God would raise up enemies from within Israel', 'Their children would inherit a curse', 'a', 'Joshua 23:16 — "Then shall the anger of the LORD be kindled against you, and ye shall perish quickly from off the good land which he hath given unto you."'),
-- Adults
('Joshua', 23, 'adults', 1, 'What does Joshua''s statement that God had driven out "great nations and strong" validate about the nature of the conquest?', 'Israel''s military superiority was the decisive factor', 'The victory was entirely God''s miraculous work, not Israel''s strength, removing any basis for national pride', 'The Canaanite nations were actually weak and not a real challenge', 'God only helped in a few key battles and Israel fought the rest alone', 'a', 'Joshua 23:9-10 — "For the LORD hath driven out from before you great nations and strong: but as for you, no man hath been able to stand before you unto this day. One man of you shall chase a thousand: for the LORD your God, he it is that fighteth for you." The supernaturally disproportionate ratio emphasizes divine agency.'),
('Joshua', 23, 'adults', 2, 'What does the phrase "cleave unto the LORD" in Joshua 23:8 imply about the nature of Israel''s covenant relationship?', 'Obedience to law was the core of the covenant', 'The covenant demanded personal devotion and intimate attachment to God, not just religious formality', 'Cleaving meant physical proximity to the tabernacle', 'Cleaving referred to military alliance with God''s angels', 'a', 'Joshua 23:8 — "But cleave unto the LORD your God, as ye have done unto this day." The word "cleave" (dabaq in Hebrew) describes the intimate bonding of marriage (Genesis 2:24) — the same devotion husbands give wives was to characterize Israel''s relationship with God.'),
('Joshua', 23, 'adults', 3, 'How does Joshua 23:14 frame the faithfulness of God by referencing Joshua''s own mortality?', 'Joshua uses his coming death as a warning to Israel', 'He declares that as he is dying, so does he know with certainty that not one word of all God''s good promises has failed', 'He asks Israel to mourn his death as a sign of faithfulness', 'He calls God as witness against Israel at his death', 'a', 'Joshua 23:14 — "And, behold, this day I am going the way of all the earth: and ye know in all your hearts and in all your souls, that not one thing hath failed of all the good things which the LORD your God spake concerning you; all are come to pass unto you, and not one thing hath failed thereof."'),
('Joshua', 23, 'adults', 4, 'What is the double-edged nature of the covenant stated in Joshua 23:15-16 — how does God''s faithfulness in blessing become a warning?', 'God''s past faithfulness is irrelevant to future judgment', 'As surely as every good word of God came to pass, so every curse and judgment will come to pass if Israel disobeys', 'God''s blessings were conditional but His curses were unconditional', 'Israel could earn back God''s favor after judgment through sacrifice', 'a', 'Joshua 23:15 — "Therefore it shall come to pass, that as all good things are come upon you, which the LORD your God promised you; so shall the LORD bring upon you all evil things, until he have destroyed you from off this good land." God''s perfect track record of fulfillment guarantees both blessings and curses.'),
('Joshua', 23, 'adults', 5, 'Why did Joshua specify intermarriage as a particularly dangerous form of compromise in his farewell address?', 'Intermarriage caused economic losses through dowry payments to Canaanites', 'Intermarriage was the gateway to adopting Canaanite religion and abandoning covenant worship entirely', 'The Canaanites practiced polygamy which violated Mosaic law', 'Intermarriage diluted the tribal genealogical records', 'a', 'Joshua 23:12-13 — "If ye do in any wise go back, and cleave unto the remnant of these nations... and shall make marriages with them... Know for a certainty that the LORD your God will no more drive out any of these nations from before you." Intermarriage was the historical gateway to Baal worship (Numbers 25:1-3; 1 Kings 11:1-8).'),
('Joshua', 23, 'adults', 6, 'What does Joshua''s farewell address draw from the content of the Mosaic covenant, particularly Deuteronomy?', 'It summarizes the Ten Commandments for a new generation', 'It echoes the blessings and curses structure of Deuteronomy 28 — obedience brings continued blessing, disobedience brings swift destruction', 'It establishes new laws not found in Moses''s writings', 'It cancels the ceremonial laws for the settled land period', 'a', 'Joshua 23 draws heavily from Deuteronomy''s framework: keep the law (Deut. 5:32), do not associate with these nations (Deut. 7:2-3), no other gods (Deut. 6:14-15), God fights for you (Deut. 20:4), and the perish-from-the-land curse (Deut. 28:63). Joshua''s farewell is a renewal of Deuteronomy''s covenant theology.'),
('Joshua', 23, 'adults', 7, 'What is the literary and theological relationship between Joshua 23 and Joshua 24?', 'They are contradictory accounts of the same speech', 'Chapter 23 is a private address to leaders, while chapter 24 is a formal public covenant renewal ceremony at Shechem', 'Chapter 23 replaces the Mosaic covenant with a new Joshuanic covenant', 'Both chapters record identical speeches given on different occasions', 'a', 'Joshua 23 is addressed to Israel''s leaders (elders, heads, judges, officers) with a warning-focused farewell, while Joshua 24 is a formal covenantal assembly at Shechem involving all the people with a historical recitation, challenge, and formal covenant renewal — two distinct but complementary final acts of Joshua.'),
('Joshua', 23, 'adults', 8, 'What does Joshua''s description of the land as something God "gave" Israel (used repeatedly in ch. 23) emphasize about Israel''s proper attitude toward their possession?', 'Israel earned the land through military conquest', 'The land was an unmerited gift of grace requiring gratitude and covenant faithfulness, not pride of ownership', 'The land was a payment for Abraham''s obedience', 'The land belonged to Israel by natural right as a people group', 'a', 'Joshua 23:13, 15, 16 repeatedly calls it "this good land which the LORD your God hath given you" — the gift language emphasizes that Israel held the land as stewards of God''s grace, not as independent owners, making covenant faithfulness not merely obligatory but the proper response to unmerited divine generosity.');

-- ═══ Joshua Chapter 24 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 24, 'kids', 1, 'Where did Joshua gather all the tribes of Israel for his final covenant address?', 'Jericho', 'Jerusalem', 'Shechem', 'Shiloh', 'a', 'Joshua 24:1 — "And Joshua gathered all the tribes of Israel to Shechem, and called for the elders of Israel, and for their heads, and for their judges, and for their officers; and they presented themselves before God."'),
('Joshua', 24, 'kids', 2, 'What famous choice did Joshua challenge all Israel to make?', 'Choose between Moses''s law and new laws', 'Choose ye this day whom ye will serve', 'Choose between the land of Canaan and returning to Egypt', 'Choose a new leader after Joshua', 'a', 'Joshua 24:15 — "Choose you this day whom ye will serve... but as for me and my house, we will serve the LORD."'),
('Joshua', 24, 'kids', 3, 'How old was Joshua when he died?', 'A hundred years old', 'A hundred and ten years old', 'A hundred and twenty years old', 'Eighty-five years old', 'a', 'Joshua 24:29 — "And it came to pass after these things, that Joshua the son of Nun, the servant of the LORD, died, being an hundred and ten years old."'),
-- Teens
('Joshua', 24, 'teens', 1, 'What did Joshua say about the gods Abraham''s ancestors served beyond the river Euphrates?', 'They were powerless idols made of wood and stone', 'Your fathers dwelt on the other side of the flood in old time, and they served other gods', 'They were forgotten and no longer worshipped', 'They were angels who had rebelled against God', 'a', 'Joshua 24:2 — "Thus saith the LORD God of Israel, Your fathers dwelt on the other side of the flood in old time, even Terah, the father of Abraham, and the father of Nachor: and they served other gods."'),
('Joshua', 24, 'teens', 2, 'In the historical summary God gave through Joshua, which miraculous event at the Red Sea is highlighted?', 'The cloud pillar protected Israel from Egypt', 'God put darkness between Israel and the Egyptians, and the sea drowned the Egyptians', 'Moses stretched his rod and the sea opened', 'God sent angels to protect Israel''s rear guard', 'a', 'Joshua 24:7 — "And when they cried unto the LORD, he put darkness between you and the Egyptians, and brought the sea upon them, and covered them; and your eyes have seen what I have done in Egypt."'),
('Joshua', 24, 'teens', 3, 'What did Joshua set up as a "witness" to the covenant Israel had made at Shechem?', 'A new altar', 'A great stone under an oak tree by the sanctuary of the LORD', 'A written scroll sealed by the priests', 'Twelve pillars for the twelve tribes', 'a', 'Joshua 24:26-27 — "And Joshua wrote these words in the book of the law of God, and took a great stone, and set it up there under an oak, that was by the sanctuary of the LORD. And Joshua said unto all the people, Behold, this stone shall be a witness unto us."'),
('Joshua', 24, 'teens', 4, 'Whose bones were buried at Shechem in the parcel of ground Jacob had purchased, fulfilling a request made in Egypt?', 'Jacob''s bones', 'Abraham''s bones', 'The bones of Joseph', 'Moses''s bones', 'a', 'Joshua 24:32 — "And the bones of Joseph, which the children of Israel brought up out of Egypt, buried they in Shechem, in a parcel of ground which Jacob bought." This fulfilled Genesis 50:25 and Exodus 13:19.'),
('Joshua', 24, 'teens', 5, 'Where was Eleazar the son of Aaron buried after his death?', 'In Shiloh near the tabernacle', 'In a hill that pertained to Phinehas his son in mount Ephraim', 'In the city of Hebron with the patriarchs', 'In the plot of land near Shechem', 'a', 'Joshua 24:33 — "And Eleazar the son of Aaron died; and they buried him in a hill that pertained to Phinehas his son, which was given him in mount Ephraim."'),
-- Adults
('Joshua', 24, 'adults', 1, 'What rhetorical technique does Joshua''s speech in 24:2-13 use, and why is it powerful in the covenant renewal context?', 'A legal indictment listing Israel''s sins', 'A historical recital (Heilsgeschichte) of God''s saving acts, grounding the covenant demand in divine grace already demonstrated', 'A prophetic vision of future judgment', 'A wisdom poem contrasting the righteous and the wicked', 'a', 'Joshua 24:2-13 follows the pattern of Heilsgeschichte (salvation history): from Abraham''s call through the Exodus and conquest, God is presented as the sole actor of Israel''s history. This grounds the covenant challenge — "choose whom ye will serve" — in already-demonstrated grace rather than abstract obligation.'),
('Joshua', 24, 'adults', 2, 'What does Joshua''s statement "I am not able to serve the LORD" in response to Israel''s first pledge (v.19-20) reveal about covenant theology?', 'Joshua had lost his faith near death', 'God is a holy and jealous God who will not forgive transgression; Israel must count the cost before making a glib covenant pledge', 'Joshua was testing whether Israel would argue with him', 'Joshua believed Israel was incapable of obedience due to original sin', 'a', 'Joshua 24:19-20 — "And Joshua said unto the people, Ye cannot serve the LORD: for he is an holy God; he is a jealous God; he will not forgive your transgressions nor your sins. If ye forsake the LORD, and serve strange gods, then he will turn and do you hurt." Joshua pushes back on easy commitment to ensure the covenant is entered seriously.'),
('Joshua', 24, 'adults', 3, 'What specific idols did Joshua tell Israel to put away before they could commit to serving the LORD?', 'The gods their forefathers served in Egypt and Mesopotamia only', 'The strange gods which are among you, and the gods which your fathers served beyond the flood and in Egypt', 'The golden calves set up by Jeroboam', 'The Baals and Ashtoreths of Canaan', 'a', 'Joshua 24:14 — "Now therefore fear the LORD, and serve him in sincerity and in truth: and put away the gods which your fathers served on the other side of the flood, and in Egypt; and serve ye the LORD." This implies some Israelites had retained foreign idols even through the conquest.'),
('Joshua', 24, 'adults', 4, 'What does the threefold repetition of Israel''s pledge ("we will serve the LORD") followed by Joshua''s warnings and Israel''s reaffirmation reveal about ancient covenant ratification procedures?', 'Israel was being forced to pledge against their will', 'It reflects the formal question-and-answer structure of ancient Near Eastern covenant making, ensuring voluntary and informed consent', 'Joshua did not trust Israel''s first answer', 'The repetition was a magical formula to bind the covenant', 'a', 'Joshua 24:16-24 records three rounds of Israel pledging, Joshua warning, and Israel reaffirming. This mirrors the formal suzerainty treaty structure where the vassal must demonstrate understanding of the covenant''s obligations — Joshua ensures Israel enters the covenant with full knowledge, not ignorance.'),
('Joshua', 24, 'adults', 5, 'What does Joshua''s phrase "for he is an holy God; he is a jealous God" (v.19) echo from earlier Torah, and what does it teach about God''s character?', 'It echoes the Aaronic blessing in Numbers 6', 'It echoes Exodus 20:5 and 34:14, establishing that God''s exclusive claim on Israel''s worship arises from his very nature as holy and jealous', 'It echoes Deuteronomy 6:4 — the Shema', 'It echoes Moses''s prayer in Numbers 14', 'a', 'Joshua 24:19 echoes Exodus 20:5 ("I the LORD thy God am a jealous God") and Exodus 34:14 ("For thou shalt worship no other god: for the LORD, whose name is Jealous, is a jealous God"), establishing that God''s intolerance of idolatry is not arbitrary but flows from his essential holy nature.'),
('Joshua', 24, 'adults', 6, 'What is the theological significance of the location of Shechem for this covenant renewal ceremony?', 'Shechem was the nearest city to the tabernacle at Shiloh', 'Shechem was the site of Abraham''s first altar in Canaan and the covenant renewal at Ebal/Gerizim commanded by Moses, making it the preeminent covenant location', 'Shechem was Joshua''s home city', 'Shechem was where the Israelites had defeated the most dangerous Canaanite king', 'a', 'Shechem was where Abraham first entered Canaan and built an altar (Genesis 12:6-7), where Jacob bought land and built an altar (Genesis 33:18-20), and where Moses commanded the covenant renewal ceremony on Ebal and Gerizim (Deuteronomy 27; Joshua 8:30-35). Joshua''s choice of Shechem deliberately connects this final covenant renewal to all preceding covenant history.'),
('Joshua', 24, 'adults', 7, 'How does Joshua''s burial at Timnath-serah and the phrase "served the LORD all the days of Joshua, and all the days of the elders that overlived Joshua" set up the book of Judges?', 'It shows Israel was faithful and the book of Judges records their continued faithfulness', 'It establishes a transition — with Joshua and his eyewitness generation gone, the next generation who "knew not the LORD" would be the subject of Judges'' cycle of apostasy', 'It closes the history of Israel permanently with no future narrative needed', 'It predicts specifically that the tribe of Dan would be the first to apostatize', 'a', 'Joshua 24:31 — "And Israel served the LORD all the days of Joshua, and all the days of the elders that overlived Joshua, and which had known all the works of the LORD." Judges 2:10 completes this: "And also all that generation were gathered unto their fathers: and there arose another generation after them, which knew not the LORD" — directly linking Joshua''s closing verse to Judges'' opening downward spiral.'),
('Joshua', 24, 'adults', 8, 'What is the theological message of ending the book of Joshua with three burials — Joshua, Joseph''s bones, and Eleazar?', 'The book ends on a note of death and failure', 'It affirms the fulfillment of promises across generations: Joseph''s faith in the Exodus was vindicated, Joshua''s life of service was honored, and the priestly line continued through Eleazar''s burial — all three lives ending in the Promised Land', 'The three burials mark the end of the Mosaic era permanently', 'It was customary to record burials to conclude historical books in Israel', 'a', 'Joshua 24:29-33 — Joshua dies at 110 (v.29), Joseph''s bones are finally buried (v.32, fulfilling Genesis 50:25), and Eleazar dies and is buried (v.33). Together these closures declare: God''s promises are kept across all generations — the faith of the patriarchs, the labor of Moses''s generation, and the priestly ministry all find their rest and fulfillment in the Promised Land.');
