-- ============================================================================
-- Quiz Seed: 1 Samuel — Part 2 (Chapters 11–20)
-- 3 difficulties × 10 chapters = 160 total questions
-- kids: 3 Qs, teens: 5 Qs, adults: 8 Qs per chapter
-- correct_answer is always 'a'
-- ============================================================================

-- ═══ 1 Samuel Chapter 11 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 11, 'kids', 1, 'Who threatened to put out the right eye of every man in Jabesh-gilead?', 'Nahash the Ammonite', 'Goliath the Philistine', 'Saul the king', 'Samuel the prophet', 'a', '1 Samuel 11:2 — "Nahash the Ammonite answered them, On this condition will I make a covenant with you, that I may thrust out all your right eyes."'),
('1 Samuel', 11, 'kids', 2, 'Who came to rescue the people of Jabesh-gilead?', 'Saul', 'David', 'Jonathan', 'Samuel', 'a', '1 Samuel 11:11 — "Saul put the people in three companies; and they came into the midst of the host in the morning watch, and slew the Ammonites."'),
('1 Samuel', 11, 'kids', 3, 'Where did the people go to renew the kingdom after the victory?', 'Gilgal', 'Bethlehem', 'Mizpeh', 'Shiloh', 'a', '1 Samuel 11:14 — "Then said Samuel to the people, Come, and let us go to Gilgal, and renew the kingdom there."'),
-- Teens
('1 Samuel', 11, 'teens', 1, 'What caused Saul''s anger to be kindled when he heard the news from Jabesh-gilead?', 'The Spirit of God came upon him', 'He heard the people weeping', 'Samuel commanded him', 'The elders urged him', 'a', '1 Samuel 11:6 — "And the Spirit of God came upon Saul when he heard those tidings, and his anger was kindled greatly."'),
('1 Samuel', 11, 'teens', 2, 'How many men did Saul number at Bezek before the battle?', 'Three hundred thousand men of Israel and thirty thousand of Judah', 'A hundred thousand men of Israel', 'Fifty thousand chosen men', 'Ten thousand mighty men', 'a', '1 Samuel 11:8 — "He numbered them in Bezek: and the children of Israel were three hundred thousand, and the men of Judah thirty thousand."'),
('1 Samuel', 11, 'teens', 3, 'What message did Saul send to the men of Jabesh-gilead?', 'Tomorrow, by that time the sun be hot, ye shall have help', 'Fear not, I will deliver you before morning', 'Gather your men and meet me at Gilgal', 'The LORD your God shall fight for you', 'a', '1 Samuel 11:9 — "Tomorrow, by that time the sun be hot, ye shall have help. And the messengers came and shewed it to the men of Jabesh; and they were glad."'),
('1 Samuel', 11, 'teens', 4, 'What did Samuel say to the people who wanted to execute those who had previously despised Saul?', 'There shall not a man be put to death this day', 'Let justice be done upon them', 'Saul shall decide their fate', 'Hand them over to the elders', 'a', '1 Samuel 11:13 — "And Saul said, There shall not a man be put to death this day: for to day the LORD hath wrought salvation in Israel."'),
('1 Samuel', 11, 'teens', 5, 'What event followed the victory over the Ammonites at Gilgal?', 'Saul and all the men of Israel rejoiced greatly', 'Samuel anointed Saul a second time privately', 'Jonathan was made captain of the host', 'The Philistines came up to fight', 'a', '1 Samuel 11:15 — "And all the people went to Gilgal; and there they made Saul king before the LORD in Gilgal; and there they sacrificed sacrifices of peace offerings before the LORD; and there Saul and all the men of Israel rejoiced greatly."'),
-- Adults
('1 Samuel', 11, 'adults', 1, 'What was the condition Nahash demanded of the men of Jabesh-gilead before making a covenant with them?', 'To thrust out all their right eyes as a reproach upon all Israel', 'To surrender their city and pay tribute annually', 'To give up their sons as servants to the Ammonites', 'To demolish their city walls and live among the Ammonites', 'a', '1 Samuel 11:2 — "Nahash the Ammonite answered them, On this condition will I make a covenant with you, that I may thrust out all your right eyes, and lay it for a reproach upon all Israel."'),
('1 Samuel', 11, 'adults', 2, 'How many days did the men of Jabesh ask of Nahash, and for what purpose?', 'Seven days, to send messengers throughout all the coasts of Israel', 'Three days, to bury their dead and mourn', 'Ten days, to gather their soldiers', 'One day, to seek the LORD in prayer', 'a', '1 Samuel 11:3 — "The elders of Jabesh said unto him, Give us seven days'' respite, that we may send messengers unto all the coasts of Israel: and then, if there be no man to save us, we will come out to thee."'),
('1 Samuel', 11, 'adults', 3, 'What was Saul doing when the messengers from Jabesh arrived, and what did it signify about his station?', 'He was coming after the herd out of the field, showing he was still a farmer before fully taking up the kingship', 'He was sitting at the city gate judging the people', 'He was training soldiers in the field', 'He was offering sacrifice at the altar', 'a', '1 Samuel 11:5 — "And, behold, Saul came after the herd out of the field; and Saul said, What aileth the people that they weep?"'),
('1 Samuel', 11, 'adults', 4, 'How did Saul summon all Israel to war, and what threat did he add?', 'He hewed a yoke of oxen and sent pieces throughout Israel saying whosoever cometh not after Saul and Samuel so shall it be done unto his oxen', 'He sent trumpeters to every tribe declaring war', 'He commanded the Levites to announce war at every sanctuary', 'He burned the fields of those who would not follow', 'a', '1 Samuel 11:7 — "And he took a yoke of oxen, and hewed them in pieces, and sent them throughout all the coasts of Israel...saying, Whosoever cometh not forth after Saul and after Samuel, so shall it be done unto his oxen."'),
('1 Samuel', 11, 'adults', 5, 'In how many companies did Saul divide the army for the attack, and at what time did they strike?', 'Three companies, in the morning watch', 'Two companies, at noon', 'Four companies, at midnight', 'Five companies, at dawn', 'a', '1 Samuel 11:11 — "And it was so on the morrow, that Saul put the people in three companies; and they came into the midst of the host in the morning watch."'),
('1 Samuel', 11, 'adults', 6, 'What did Saul attribute the victory to, when he refused to let those who doubted him be killed?', 'The LORD hath wrought salvation in Israel', 'The bravery of all Israel''s soldiers', 'Samuel''s intercession before God', 'The fear of the Ammonites', 'a', '1 Samuel 11:13 — "Saul said, There shall not a man be put to death this day: for to day the LORD hath wrought salvation in Israel."'),
('1 Samuel', 11, 'adults', 7, 'What sacrifices were offered at the renewal of the kingdom in Gilgal?', 'Sacrifices of peace offerings before the LORD', 'Burnt offerings and sin offerings', 'Wave offerings and firstfruit offerings', 'Trespass offerings for the nation', 'a', '1 Samuel 11:15 — "And there they sacrificed sacrifices of peace offerings before the LORD; and there Saul and all the men of Israel rejoiced greatly."'),
('1 Samuel', 11, 'adults', 8, 'What theological significance does the Jabesh-gilead rescue have for understanding Saul''s kingship?', 'It confirmed Saul as king through a military deliverance empowered by God''s Spirit, validating his rule before all Israel', 'It showed Saul was superior to Samuel in leadership', 'It proved the Ammonites were the chief enemies of Israel', 'It demonstrated that Israel no longer needed a judge', 'a', '1 Samuel 11:6,13 — The Spirit of God empowered Saul, and he attributed the win to the LORD, showing his kingship was God-ordained. "The LORD hath wrought salvation in Israel."');

-- ═══ 1 Samuel Chapter 12 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 12, 'kids', 1, 'What unusual sign did God send during the wheat harvest to show His displeasure with Israel?', 'Thunder and rain', 'Fire from heaven', 'An earthquake', 'A great wind', 'a', '1 Samuel 12:18 — "So Samuel called unto the LORD; and the LORD sent thunder and rain that day."'),
('1 Samuel', 12, 'kids', 2, 'What did Samuel say he had never done to show he had been a fair leader?', 'He had never taken anyone''s ox or donkey or cheated anyone', 'He had never missed a single day of prayer', 'He had never spoken a false prophecy', 'He had never left his post at the gate', 'a', '1 Samuel 12:3 — "Whose ox have I taken? or whose ass have I taken? or whom have I defrauded?...bear witness against me."'),
('1 Samuel', 12, 'kids', 3, 'What did Samuel tell the people to do so things would go well for them?', 'Fear the LORD and serve him in truth with all your heart', 'Offer many sacrifices at the tabernacle', 'Follow only the priests'' instructions', 'Move to a new land', 'a', '1 Samuel 12:24 — "Only fear the LORD, and serve him in truth with all your heart: for consider how great things he hath done for you."'),
-- Teens
('1 Samuel', 12, 'teens', 1, 'What leaders did Samuel list to show how God had delivered Israel throughout history?', 'Moses and Aaron, then Jerubbaal, Bedan, Jephthah, and Samuel', 'Abraham, Isaac, Jacob, Moses, and Joshua', 'Gideon, Samson, Eli, and Samuel', 'Joshua, Caleb, Deborah, and Barak', 'a', '1 Samuel 12:11 — "The LORD sent Jerubbaal, and Bedan, and Jephthah, and Samuel, and delivered you out of the hand of your enemies."'),
('1 Samuel', 12, 'teens', 2, 'Why did Samuel say Israel had sinned in asking for a king?', 'Because the LORD your God was your king', 'Because they already had good leaders in the judges', 'Because no nation around them had kings', 'Because Samuel had been chosen to rule forever', 'a', '1 Samuel 12:12 — "When ye saw that Nahash the king of the children of Ammon came against you, ye said unto me, Nay; but a king shall reign over us: when the LORD your God was your king."'),
('1 Samuel', 12, 'teens', 3, 'What was the people''s reaction when God sent thunder and rain at the wheat harvest?', 'They greatly feared the LORD and Samuel', 'They rejoiced and praised God', 'They offered sacrifices on the spot', 'They ran to the tabernacle in Shiloh', 'a', '1 Samuel 12:18 — "And all the people greatly feared the LORD and Samuel."'),
('1 Samuel', 12, 'teens', 4, 'What did the people ask Samuel to do after they feared the thunder and rain?', 'Pray unto the LORD thy God for thy servants that we die not', 'Offer a great sacrifice on their behalf', 'Write down God''s laws for them', 'Anoint Saul again before all the people', 'a', '1 Samuel 12:19 — "And all the people said unto Samuel, Pray for thy servants unto the LORD thy God, that we die not: for we have added unto all our sins this evil, to ask us a king."'),
('1 Samuel', 12, 'teens', 5, 'What did Samuel promise he would never stop doing for the people of Israel?', 'Praying for them and teaching them the good and right way', 'Visiting every tribe each year', 'Anointing new kings on God''s command', 'Building altars throughout the land', 'a', '1 Samuel 12:23 — "Moreover as for me, God forbid that I should sin against the LORD in ceasing to pray for you: but I will teach you the good and the right way."'),
-- Adults
('1 Samuel', 12, 'adults', 1, 'What was Samuel''s public challenge to Israel regarding his integrity as a leader?', 'Whose ox have I taken, whose ass taken, whom defrauded, oppressed, or from whose hand taken a bribe to blind mine eyes therewith — and he will restore it', 'Whether he had ever spoken a false word in the name of the LORD', 'Whether he had ever favored one tribe over another in judgment', 'Whether he had collected any taxes or levies during his years as judge', 'a', '1 Samuel 12:3 — "Whose ox have I taken? or whose ass have I taken? or whom have I defrauded? whom have I oppressed? or of whose hand have I received any bribe to blind mine eyes therewith?"'),
('1 Samuel', 12, 'adults', 2, 'How did Samuel trace Israel''s pattern of sin and deliverance from Egypt to his own day?', 'They forgot the LORD, He sold them to enemies, they cried out, He sent deliverers — a cycle repeated many times', 'They kept the law, prospered, then grew proud and fell', 'They followed God until each new generation arose that forgot Samuel', 'They trusted in idols, were judged, repented, then forgot again', 'a', '1 Samuel 12:9-11 — "They forgat the LORD their God...he sold them into the hand of Sisera...and into the hand of the Philistines...they cried unto the LORD...and the LORD sent Jerubbaal...and delivered you."'),
('1 Samuel', 12, 'adults', 3, 'What specific act of kingship-requesting did Samuel call a great wickedness in chapter 12?', 'Asking for a king when the LORD your God was your king', 'Rejecting the counsel of the priests and Levites', 'Refusing to renew the covenant at Shechem', 'Seeking alliances with surrounding nations', 'a', '1 Samuel 12:17 — "Is it not wheat harvest to day? I will call unto the LORD...that ye may perceive and see that your wickedness is great, which ye have done in the sight of the LORD, in asking you a king."'),
('1 Samuel', 12, 'adults', 4, 'What conditional promise did Samuel give regarding Saul''s kingship?', 'If both ye and the king that reigneth over you will follow the LORD your God it shall be well, but if ye rebel both ye and your king shall be consumed', 'If Saul obeyed all the commandments he would reign forever', 'If the people paid tithes faithfully God would bless the king', 'If Israel remained at peace the kingship would pass to Saul''s sons', 'a', '1 Samuel 12:14-15 — "If ye will fear the LORD...and obey his voice...then shall both ye and also the king that reigneth over you continue following the LORD your God."'),
('1 Samuel', 12, 'adults', 5, 'What season made the sending of thunder and rain a particularly striking miracle?', 'Wheat harvest, when rain was unusual in Palestine', 'The dry summer when no cloud had appeared for months', 'The Feast of Tabernacles in autumn', 'The spring planting season before the rains normally began', 'a', '1 Samuel 12:17 — "Is it not wheat harvest to day? I will call unto the LORD, and he shall send thunder and rain." Wheat harvest was typically a dry season in Canaan.'),
('1 Samuel', 12, 'adults', 6, 'What sin did Samuel say would be committed if he stopped praying for the people?', 'Sinning against the LORD in ceasing to pray for you', 'Abandoning his prophetic office before God', 'Neglecting the covenant duties of a seer', 'Failing the nation before the eyes of the Gentiles', 'a', '1 Samuel 12:23 — "Moreover as for me, God forbid that I should sin against the LORD in ceasing to pray for you."'),
('1 Samuel', 12, 'adults', 7, 'What does Samuel identify as the root of Israel''s past troubles in his farewell address?', 'They forgat the LORD their God and served Baalim and Ashtaroth', 'They followed foreign kings instead of their own judges', 'They broke the Sabbath throughout the generations', 'They intermarried with the Canaanites', 'a', '1 Samuel 12:9-10 — "They forgat the LORD their God, and he sold them into the hand of Sisera...then they cried unto the LORD...We have sinned, because we have forsaken the LORD, and have served Baalim and Ashtaroth."'),
('1 Samuel', 12, 'adults', 8, 'What warning did Samuel close with regarding the consequences if both people and king did wickedly?', 'Ye shall be consumed, both ye and your king', 'The kingdom would be divided and given to another nation', 'God would raise up enemies from every side', 'Samuel would anoint a new king from a different tribe', 'a', '1 Samuel 12:25 — "But if ye shall still do wickedly, ye shall be consumed, both ye and your king."');

-- ═══ 1 Samuel Chapter 13 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 13, 'kids', 1, 'What did Saul do at Gilgal that he was not supposed to do?', 'He offered the burnt offering himself without waiting for Samuel', 'He attacked the Philistines without God''s permission', 'He sent the army home before the battle', 'He built an altar without the priests'' blessing', 'a', '1 Samuel 13:12-13 — Saul said "I offered a burnt offering." Samuel said "Thou hast done foolishly: thou hast not kept the commandment of the LORD."'),
('1 Samuel', 13, 'kids', 2, 'What did Samuel tell Saul because he had disobeyed God at Gilgal?', 'Thy kingdom shall not continue', 'Thou shalt be given over to thy enemies', 'Thou shalt no longer be king after today', 'Thou shalt lose thy firstborn son', 'a', '1 Samuel 13:14 — "But now thy kingdom shall not continue: the LORD hath sought him a man after his own heart."'),
('1 Samuel', 13, 'kids', 3, 'Why were there no swords or spears for most of Israel''s soldiers?', 'The Philistines had made sure there were no blacksmiths in Israel', 'They had been captured in a previous battle', 'The army had sold them for food', 'God had commanded them not to use iron weapons', 'a', '1 Samuel 13:19 — "Now there was no smith found throughout all the land of Israel: for the Philistines said, Lest the Hebrews make them swords or spears."'),
-- Teens
('1 Samuel', 13, 'teens', 1, 'What triggered the gathering of the Philistines to fight Israel in chapter 13?', 'Jonathan smote a garrison of the Philistines and Israel was had in abomination with them', 'Saul refused to pay tribute to the Philistines', 'Israel attacked a Philistine city without warning', 'Samuel declared war on the Philistines', 'a', '1 Samuel 13:3-4 — "Jonathan smote the garrison of the Philistines...and the Philistines heard of it...and Israel was had in abomination with the Philistines."'),
('1 Samuel', 13, 'teens', 2, 'How large was the Philistine army that gathered against Israel?', 'Thirty thousand chariots, six thousand horsemen, and people as the sand of the sea', 'Ten thousand chariots and a hundred thousand footmen', 'Twenty thousand men in three companies', 'Fifty thousand soldiers with chariots and spears', 'a', '1 Samuel 13:5 — "The Philistines gathered themselves together to fight with Israel, thirty thousand chariots, and six thousand horsemen, and people as the sand which is on the sea shore."'),
('1 Samuel', 13, 'teens', 3, 'Why did Saul say he felt forced to offer the sacrifice himself?', 'Because the people were scattering, Samuel had not come, and the Philistines were gathering', 'Because the priests had all fled in fear', 'Because Samuel had sent word he was unable to come', 'Because Jonathan urged him to act before it was too late', 'a', '1 Samuel 13:11-12 — "Saul said...The people were scattered from me, and thou camest not within the days appointed...therefore I forced myself, and offered a burnt offering."'),
('1 Samuel', 13, 'teens', 4, 'What did Samuel say God had done because of Saul''s disobedience?', 'The LORD hath sought him a man after his own heart and commanded him to be captain over his people', 'God had removed His Spirit from Saul that very day', 'The LORD had given the kingdom to the Philistines temporarily', 'God had decreed that Jonathan would replace Saul', 'a', '1 Samuel 13:14 — "But now thy kingdom shall not continue: the LORD hath sought him a man after his own heart, and the LORD hath commanded him to be captain over his people."'),
('1 Samuel', 13, 'teens', 5, 'How many men remained with Saul after the people scattered in fear of the Philistines?', 'About six hundred men', 'Three thousand chosen soldiers', 'One thousand men of Benjamin', 'Only his bodyguard of thirty men', 'a', '1 Samuel 13:15 — "And Samuel arose, and gat him up from Gilgal...And Saul numbered the people that were present with him, about six hundred men."'),
-- Adults
('1 Samuel', 13, 'adults', 1, 'What specific charge did Samuel level at Saul for offering the sacrifice?', 'Thou hast done foolishly: thou hast not kept the commandment of the LORD thy God, which he commanded thee', 'Thou hast stolen the glory of the priesthood for thyself', 'Thou hast sinned against the covenant of Moses by touching holy things', 'Thou hast despised the word of Samuel the prophet of God', 'a', '1 Samuel 13:13 — "Samuel said to Saul, Thou hast done foolishly: thou hast not kept the commandment of the LORD thy God, which he commanded thee."'),
('1 Samuel', 13, 'adults', 2, 'What consequence did Samuel pronounce on Saul''s dynasty as a result of his disobedience?', 'His kingdom would not continue and the LORD had sought a man after his own heart to be captain over his people', 'His sons would be stripped of the throne within three generations', 'The tribe of Benjamin would lose its leadership role in Israel', 'Saul himself would be removed from the throne before the year ended', 'a', '1 Samuel 13:13-14 — "Thy kingdom shall not continue...the LORD hath sought him a man after his own heart, and the LORD hath commanded him to be captain over his people, because thou hast not kept that which the LORD commanded thee."'),
('1 Samuel', 13, 'adults', 3, 'What was the Philistine strategy for suppressing Israel''s military capability?', 'Eliminating all smiths from Israel so no swords or spears could be made', 'Requiring Israel to surrender all iron weapons each year', 'Stationing garrisons at all the mountain passes', 'Taking the eldest sons as hostages to prevent rebellion', 'a', '1 Samuel 13:19 — "Now there was no smith found throughout all the land of Israel: for the Philistines said, Lest the Hebrews make them swords or spears."'),
('1 Samuel', 13, 'adults', 4, 'What agricultural tools did the Israelites have to take to the Philistines for sharpening, and how much were they charged?', 'Shares, coulters, axes, and mattocks — a pim for shares, coulters, forks, and axes, and to sharpen the goads', 'Plows, sickles, and grinding stones at one shekel each', 'Hoes and mattocks only, at half a shekel', 'All iron tools at a standard rate set by the Philistine governors', 'a', '1 Samuel 13:20-21 — "All the Israelites went down to the Philistines, to sharpen every man his share, and his coulter...And the file was a pim for the mattocks, and for the coulters."'),
('1 Samuel', 13, 'adults', 5, 'How many men did Saul keep with him at Michmash and how many did Jonathan command at Gibeah?', 'Saul kept two thousand at Michmash and Jonathan had a thousand at Gibeah of Benjamin', 'Saul had three thousand at Gilgal and Jonathan led five hundred', 'Saul kept a thousand at Ramah and Jonathan had two thousand', 'Saul commanded all six hundred while Jonathan served under him', 'a', '1 Samuel 13:2 — "Saul chose him three thousand men of Israel; whereof two thousand were with Saul in Michmash...and a thousand were with Jonathan in Gibeah of Benjamin."'),
('1 Samuel', 13, 'adults', 6, 'In what direction did the Philistine raiders go out from their camp at Michmash?', 'One company turned toward Ophrah, one toward Beth-horon, and one toward the border of the valley of Zeboim', 'They attacked Gilgal from three sides simultaneously', 'They swept northward toward the Jordan River', 'They divided into two forces heading toward Jerusalem and Bethlehem', 'a', '1 Samuel 13:17-18 — "The spoilers came out of the camp of the Philistines in three companies: one company turned unto the way that leadeth to Ophrah, unto the land of Shual: And another company turned the way to Beth-horon."'),
('1 Samuel', 13, 'adults', 7, 'What weapons did only Saul and Jonathan possess in the entire Israelite army?', 'A sword and a spear', 'Iron shields and bronze helmets', 'Chariots and bows', 'Javelins and coats of mail', 'a', '1 Samuel 13:22 — "So it came to pass in the day of battle, that there was neither sword nor spear found in the hand of any of the people that were with Saul and Jonathan: but with Saul and with Jonathan his son was there found."'),
('1 Samuel', 13, 'adults', 8, 'What theological principle does Saul''s unlawful sacrifice illustrate about the separation of civil and religious authority?', 'The king had no right to usurp the priestly function; religious authority was reserved for those God appointed to it, and violating that boundary cost Saul his dynasty', 'Kings could perform sacrifices only in times of national emergency', 'The priesthood was corrupt and needed royal oversight in Saul''s day', 'Samuel was testing Saul''s patience rather than enforcing a genuine law', 'a', '1 Samuel 13:13 — "Samuel said to Saul, Thou hast done foolishly: thou hast not kept the commandment of the LORD thy God." The commandment required waiting for the appointed priest-prophet.');

-- ═══ 1 Samuel Chapter 14 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 14, 'kids', 1, 'Who made a secret attack on the Philistine garrison with only his armorbearer?', 'Jonathan', 'Saul', 'David', 'Samuel', 'a', '1 Samuel 14:1 — "Jonathan the son of Saul said unto the young man that bare his armour, Come, and let us go over to the Philistines'' garrison."'),
('1 Samuel', 14, 'kids', 2, 'What sweet food did Jonathan eat during the battle that Saul had forbidden?', 'Honey', 'Figs', 'Grapes', 'Bread', 'a', '1 Samuel 14:27 — "Jonathan...put forth the end of the rod that was in his hand, and dipped it in an honeycomb, and his hand returned to him: wherefore his eyes were enlightened."'),
('1 Samuel', 14, 'kids', 3, 'What would have happened to Jonathan because he broke his father''s oath?', 'He would have been put to death', 'He would have lost his position as captain', 'He would have been sent away from the army', 'He would have fasted for seven days', 'a', '1 Samuel 14:44 — "Saul answered, God do so and more also: for thou shalt surely die, Jonathan."'),
-- Teens
('1 Samuel', 14, 'teens', 1, 'What sign did Jonathan say would tell him whether God had given the Philistines into their hand?', 'If the Philistines said come up unto us, that would be the sign', 'If the sun stood still they would go forward', 'If a cloud appeared over the garrison they would attack', 'If his armorbearer agreed they would fight', 'a', '1 Samuel 14:10 — "If they say thus, Come up unto us; then we will go up: for the LORD hath delivered them into our hand: and this shall be a sign unto us."'),
('1 Samuel', 14, 'teens', 2, 'How many men did Jonathan and his armorbearer kill in their first attack?', 'About twenty men in about half an acre of land', 'Thirty Philistines in the garrison', 'A hundred soldiers at the gate', 'Fifty men in the first charge', 'a', '1 Samuel 14:14 — "And that first slaughter, which Jonathan and his armourbearer made, was about twenty men, within as it were an half acre of land."'),
('1 Samuel', 14, 'teens', 3, 'What oath did Saul make that caused problems for his soldiers during the battle?', 'Cursed be any man that eateth food until evening, until I have avenged me on mine enemies', 'No man shall return home until the Philistines are destroyed', 'Whosoever flees from battle shall be put to death', 'The spoil of the enemy belongs to the LORD and none shall touch it', 'a', '1 Samuel 14:24 — "Saul had adjured the people, saying, Cursed be the man that eateth any food until evening, that I may be avenged on mine enemies. So none of the people tasted any food."'),
('1 Samuel', 14, 'teens', 4, 'How were the people saved from executing Jonathan after the people recognized he had won a great victory?', 'The people ransomed Jonathan that he died not', 'Saul withdrew the oath when he saw Jonathan''s bravery', 'Samuel intervened and declared Jonathan innocent', 'Jonathan offered a sacrifice to atone for his transgression', 'a', '1 Samuel 14:45 — "And the people said unto Saul, Shall Jonathan die, who hath wrought this great salvation in Israel? God forbid: as the LORD liveth, there shall not one hair of his head fall to the ground; for he hath wrought with God this day. So the people rescued Jonathan, that he died not."'),
('1 Samuel', 14, 'teens', 5, 'Against which of Israel''s enemies did Saul fight throughout his reign, according to the summary in chapter 14?', 'Moab, Ammon, Edom, Zobah, Philistines, and Amalek', 'Egypt, Canaan, Syria, and the sea peoples', 'Only the Philistines and the Ammonites', 'All the nations from Egypt to the Euphrates', 'a', '1 Samuel 14:47 — "So Saul took the kingdom over Israel, and fought against all his enemies on every side, against Moab, and against the children of Ammon, and against Edom, and against the kings of Zobah, and against the Philistines."'),
-- Adults
('1 Samuel', 14, 'adults', 1, 'What was Jonathan''s theological basis for expecting victory with only two men against the Philistine garrison?', 'There is no restraint to the LORD to save by many or by few', 'The LORD fights for Israel when His people trust Him', 'God had shown him a vision of victory the night before', 'The Spirit of God had spoken the promise of deliverance to him', 'a', '1 Samuel 14:6 — "Jonathan said...Come, let us go over unto the garrison of these uncircumcised; it may be that the LORD will work for us: for there is no restraint to the LORD to save by many or by few."'),
('1 Samuel', 14, 'adults', 2, 'What physical phenomenon accompanied God''s confusion of the Philistine camp after Jonathan''s attack?', 'A very great trembling in the host, in the field, and among all the people: the garrison, the spoilers, and the earth quaked', 'A dark cloud descended over the Philistine camp', 'Fire fell from heaven on the Philistine tents', 'A mighty wind drove the Philistines into confusion', 'a', '1 Samuel 14:15 — "And there was trembling in the host, in the field, and among all the people: the garrison, and the spoilers, they also trembled, and the earth quaked: so it was a very great trembling."'),
('1 Samuel', 14, 'adults', 3, 'How did Saul use the Urim and Thummim in this chapter, and what was the outcome of the inquiry?', 'He sought God''s guidance about pursuing the Philistines but stopped the inquiry when the tumult in the Philistine camp grew louder', 'God clearly told him to attack immediately', 'The lot confirmed that Jonathan was guilty of breaking the oath', 'The priest refused to answer and withdrew the ephod', 'a', '1 Samuel 14:19 — "And it came to pass, while Saul talked unto the priest, that the noise that was in the host of the Philistines went on and increased: and Saul said unto the priest, Withdraw thine hand."'),
('1 Samuel', 14, 'adults', 4, 'What was the physical effect of the honey on Jonathan, and what does this reveal about Saul''s rash oath?', 'His eyes were enlightened, showing the oath had weakened the soldiers and hindered the victory', 'He gained supernatural strength for battle', 'He was able to see in the darkness of the cave', 'He recovered from a wound he had received in battle', 'a', '1 Samuel 14:27,29 — "Jonathan...his eyes were enlightened." He said, "My father hath troubled the land: see, I pray you, how mine eyes have been enlightened, because I tasted a little of this honey."'),
('1 Samuel', 14, 'adults', 5, 'How did the people sin against the LORD after the battle because of their extreme hunger from Saul''s oath?', 'They flew upon the spoil and ate meat with the blood, which violated Mosaic law', 'They worshipped at a Philistine altar to give thanks', 'They violated the Sabbath to prepare food immediately', 'They stole from the Philistine temple treasury', 'a', '1 Samuel 14:32 — "And the people flew upon the spoil, and took sheep, and oxen, and calves, and slew them on the ground: and the people did eat them with the blood."'),
('1 Samuel', 14, 'adults', 6, 'How did the casting of lots identify Jonathan as the one who had eaten, and what had Jonathan told Saul openly?', 'Jonathan said he had tasted a little honey and was ready to die for it, having not heard his father''s oath', 'Jonathan denied eating and the lot fell on him as a false positive', 'Jonathan confessed before the lot was cast to spare the people delay', 'The lot first identified the tribe of Benjamin and then the family of Kish', 'a', '1 Samuel 14:43 — "Jonathan told him, and said, I did but taste a little honey with the end of the rod that was in mine hand, and, lo, I must die."'),
('1 Samuel', 14, 'adults', 7, 'What summary is given of Saul''s family and military commander at the end of chapter 14?', 'His sons were Jonathan, Ishui, and Melchishua; daughters Merab and Michal; wife Ahinoam; and captain of the host was Abner the son of Ner', 'His chief warrior was Doeg the Edomite and his sons served as captains', 'Samuel served as spiritual advisor and Ahijah as high priest of the army', 'Jonathan was made heir and Abner led the cavalry', 'a', '1 Samuel 14:49-50 — "The sons of Saul were Jonathan, and Ishui, and Melchishua: and the names of his two daughters...Merab...and Michal. And the name of Saul''s wife was Ahinoam...and the name of the captain of his host was Abner the son of Ner."'),
('1 Samuel', 14, 'adults', 8, 'What does Jonathan''s unauthorized but God-blessed attack reveal about the relationship between human initiative and divine sovereignty in this narrative?', 'God used Jonathan''s bold faith even without explicit command, showing His sovereignty can work through individual courage while also exposing the contrast with Saul''s cautious but disobedient leadership', 'It shows God always blesses military initiative regardless of orders', 'Jonathan''s attack was fully sanctioned by the priestly oracle', 'God blessed Jonathan despite his disobedience to honor his father''s house', 'a', '1 Samuel 14:6,45 — Jonathan said "it may be that the LORD will work for us." The people declared "he hath wrought with God this day."');

-- ═══ 1 Samuel Chapter 15 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 15, 'kids', 1, 'What people did God command Saul to destroy completely?', 'The Amalekites', 'The Philistines', 'The Ammonites', 'The Moabites', 'a', '1 Samuel 15:3 — "Now go and smite Amalek, and utterly destroy all that they have, and spare them not."'),
('1 Samuel', 15, 'kids', 2, 'What famous saying did Samuel tell Saul about obeying God?', 'To obey is better than sacrifice', 'To trust God is greater than any offering', 'Fear God more than any king', 'Love God above all earthly riches', 'a', '1 Samuel 15:22 — "Behold, to obey is better than sacrifice, and to hearken than the fat of rams."'),
('1 Samuel', 15, 'kids', 3, 'Who did Samuel kill at Gilgal because Saul had spared him?', 'Agag the king of the Amalekites', 'Nahash the Ammonite king', 'The chief priest of Baal', 'A Philistine captain', 'a', '1 Samuel 15:33 — "And Samuel hewed Agag in pieces before the LORD in Gilgal."'),
-- Teens
('1 Samuel', 15, 'teens', 1, 'Why did God command the destruction of the Amalekites?', 'Because they lay in wait for Israel when they came up out of Egypt', 'Because they had attacked Saul''s father Kish', 'Because they had stolen the ark of the covenant', 'Because they had corrupted Israel with idol worship', 'a', '1 Samuel 15:2 — "Thus saith the LORD of hosts, I remember that which Amalek did to Israel, how he laid wait for him in the way, when he came up from Egypt."'),
('1 Samuel', 15, 'teens', 2, 'What did Saul do that disobeyed God''s command to utterly destroy the Amalekites?', 'He spared Agag and the best of the sheep, oxen, fatlings, and lambs', 'He allowed the Amalekite women and children to live', 'He kept Amalekite gold and silver as tribute', 'He made a treaty with the Amalekite nobles', 'a', '1 Samuel 15:9 — "But Saul and the people spared Agag, and the best of the sheep, and of the oxen, and of the fatlings, and the lambs, and all that was good, and would not utterly destroy them."'),
('1 Samuel', 15, 'teens', 3, 'What excuse did Saul give for keeping the best animals?', 'The people spared the best of the sheep and oxen to sacrifice unto the LORD thy God', 'He planned to trade them for weapons and armor', 'He needed them to feed the army on the march home', 'He was saving them as gifts for Samuel', 'a', '1 Samuel 15:15 — "Saul said, They have brought them from the Amalekites: for the people spared the best of the sheep and of the oxen, to sacrifice unto the LORD thy God."'),
('1 Samuel', 15, 'teens', 4, 'What did Samuel say rebellion was equal to, and stubbornness equal to?', 'Rebellion is as the sin of witchcraft, and stubbornness is as iniquity and idolatry', 'Rebellion is like murder and stubbornness like theft', 'Rebellion brings death and stubbornness brings exile', 'Rebellion destroys a nation and stubbornness destroys a family', 'a', '1 Samuel 15:23 — "For rebellion is as the sin of witchcraft, and stubbornness is as iniquity and idolatry."'),
('1 Samuel', 15, 'teens', 5, 'What did Samuel tell Saul that the LORD had done because of his disobedience?', 'The LORD hath rejected thee from being king over Israel', 'The LORD hath given thy throne to thy brother', 'The LORD hath taken away the Spirit from thee', 'The LORD hath cursed thy house unto the third generation', 'a', '1 Samuel 15:26 — "Samuel said unto Saul, I will not return with thee: for thou hast rejected the word of the LORD, and the LORD hath rejected thee from being king over Israel."'),
-- Adults
('1 Samuel', 15, 'adults', 1, 'What specific command about the Amalekites did Samuel relay to Saul, and what was the total scope of destruction required?', 'Utterly destroy all they have, spare not, kill man and woman, infant and suckling, ox and sheep, camel and ass', 'Destroy all fighting men and confiscate all their goods for the LORD', 'Drive them out of the land and leave nothing standing', 'Kill the king and leaders, then give the people to slavery', 'a', '1 Samuel 15:3 — "Now go and smite Amalek, and utterly destroy all that they have, and spare them not; but slay both man and woman, infant and suckling, ox and sheep, camel and ass."'),
('1 Samuel', 15, 'adults', 2, 'How many men of Israel and Judah did Saul number for the campaign against Amalek?', 'Two hundred thousand footmen of Israel and ten thousand men of Judah', 'Three hundred thousand total soldiers from all tribes', 'A hundred thousand horsemen and fifty thousand infantry', 'Thirty thousand chariots and a great multitude on foot', 'a', '1 Samuel 15:4 — "Saul gathered the people together, and numbered them in Telaim, two hundred thousand footmen, and ten thousand men of Judah."'),
('1 Samuel', 15, 'adults', 3, 'Who did Saul warn before the battle, and why?', 'The Kenites, because they had showed kindness to Israel when they came up from Egypt', 'The Edomites, because they were distant cousins of Israel through Esau', 'The Moabites, because of the covenant made with them through Ruth', 'The Midianites, because Moses had married among them', 'a', '1 Samuel 15:6 — "Saul said unto the Kenites, Go, depart, get you down from among the Amalekites, lest I destroy you with them: for ye shewed kindness to all the children of Israel, when they came up out of Egypt."'),
('1 Samuel', 15, 'adults', 4, 'How did Samuel respond when God told him He repented of making Saul king, and what does Samuel''s reaction reveal?', 'He was grieved and cried unto the LORD all night, showing his deep pastoral sorrow for Saul and for Israel', 'He immediately went to anoint a new king', 'He accepted the news calmly as a prophet already prepared for this outcome', 'He rebuked Saul publicly without any personal grief', 'a', '1 Samuel 15:11 — "It repenteth me that I have set up Saul to be king: for he is turned back from following me...And it grieved Samuel; and he cried unto the LORD all night."'),
('1 Samuel', 15, 'adults', 5, 'What was the exact exchange about the sheep when Saul claimed he had obeyed God''s voice?', 'Samuel asked what is this bleating of the sheep and lowing of oxen; Saul said the people brought them to sacrifice to the LORD', 'Saul said the animals were for the priests and Samuel accepted this', 'Jonathan admitted the animals were kept against the command', 'Saul was silent when Samuel pointed to the animals', 'a', '1 Samuel 15:14-15 — "Samuel said, What meaneth then this bleating of the sheep in mine ears, and the lowing of the oxen which I hear? And Saul said...the people spared the best of the sheep and of the oxen, to sacrifice unto the LORD thy God."'),
('1 Samuel', 15, 'adults', 6, 'What illustration did Samuel use from the tribe of Benjamin to rebuke Saul''s self-importance?', 'When thou wast little in thine own sight, wast thou not made the head of the tribes of Israel — God anointed thee king', 'A great tree falls by its own pride, as Saul fell by his', 'As the least shepherd becomes king, so the king becomes a shepherd of shame', 'Benjamin was the youngest tribe yet given the highest honor', 'a', '1 Samuel 15:17 — "Samuel said, When thou wast little in thine own sight, wast thou not made the head of the tribes of Israel, and the LORD anointed thee king over Israel?"'),
('1 Samuel', 15, 'adults', 7, 'What was Agag''s remark when Samuel came to him, and what does it reveal about his expectation?', 'Surely the bitterness of death is past — he thought he had been spared permanently', 'I am a great king and you will not kill a king before God', 'Do what you will, for my god Baal will avenge me', 'I submit to your God and ask for mercy', 'a', '1 Samuel 15:32 — "Agag came unto him delicately. And Agag said, Surely the bitterness of death is past."'),
('1 Samuel', 15, 'adults', 8, 'What does the statement "the Strength of Israel will not lie nor repent: for he is not a man, that he should repent" teach about divine immutability in contrast with Saul''s behavior?', 'God''s decrees regarding Saul''s rejection were irreversible because God''s character is unchanging; unlike humans God does not revoke decisions made in perfect holiness and foreknowledge', 'God never changes His mind about anything in any sense', 'Samuel was correcting a false belief that God had repented of creation', 'The statement means Saul could never be forgiven for his sin', 'a', '1 Samuel 15:29 — "And also the Strength of Israel will not lie nor repent: for he is not a man, that he should repent."');

-- ═══ 1 Samuel Chapter 16 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 16, 'kids', 1, 'Which of Jesse''s sons did God choose to be the next king?', 'David, the youngest son', 'Eliab, the eldest son', 'Abinadab, the second son', 'Shammah, the third son', 'a', '1 Samuel 16:13 — "Then Samuel took the horn of oil, and anointed him in the midst of his brethren: and the Spirit of the LORD came upon David from that day forward."'),
('1 Samuel', 16, 'kids', 2, 'What does God look at that is different from what people look at?', 'The heart', 'The strength', 'The appearance', 'The family', 'a', '1 Samuel 16:7 — "The LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart."'),
('1 Samuel', 16, 'kids', 3, 'What skill did David use to help Saul feel better when an evil spirit troubled him?', 'Playing the harp', 'Singing psalms aloud', 'Dancing before the king', 'Praying over him', 'a', '1 Samuel 16:23 — "David took an harp, and played with his hand: so Saul was refreshed, and was well."'),
-- Teens
('1 Samuel', 16, 'teens', 1, 'What was Samuel''s fear when God sent him to anoint a new king, and how did God address it?', 'He feared Saul would kill him; God told him to take a heifer and say he came to sacrifice to the LORD', 'He feared the people would riot; God said he should anoint David secretly', 'He feared the journey was too dangerous; God promised angelic protection', 'He feared he had misheard God; God confirmed the message by a sign', 'a', '1 Samuel 16:2 — "Samuel said, How can I go? if Saul hear it, he will kill me. And the LORD said, Take an heifer with thee, and say, I am come to sacrifice to the LORD."'),
('1 Samuel', 16, 'teens', 2, 'Why did God reject each of Jesse''s first seven sons from being anointed king?', 'Because the LORD looketh on the heart, not the outward appearance', 'Because none of them had military experience', 'Because they were all older than the age God required', 'Because they had each sinned against the LORD', 'a', '1 Samuel 16:7 — "The LORD said unto Samuel, Look not on his countenance, or on the height of his stature...for the LORD seeth not as man seeth; for man looketh on the outward appearance, but the LORD looketh on the heart."'),
('1 Samuel', 16, 'teens', 3, 'Where was David when Samuel asked Jesse if he had any more sons?', 'Keeping the sheep', 'Working in the fields', 'Training with the army', 'Studying the law with the elders', 'a', '1 Samuel 16:11 — "Samuel said unto Jesse, Are here all thy children? And he said, There remaineth yet the youngest, and, behold, he keepeth the sheep."'),
('1 Samuel', 16, 'teens', 4, 'What happened to Saul when the Spirit of God departed from him?', 'An evil spirit from the LORD troubled him', 'He fell into a deep sleep for three days', 'He lost his ability to speak', 'He became blind for a season', 'a', '1 Samuel 16:14 — "But the Spirit of the LORD departed from Saul, and an evil spirit from the LORD troubled him."'),
('1 Samuel', 16, 'teens', 5, 'How did David come to serve in Saul''s court?', 'One of Saul''s servants recommended him as a cunning player on the harp, a valiant man, and one whom the LORD was with', 'Samuel commanded Saul to take David as his armor bearer', 'Jesse brought David as a tribute to the king', 'David won a contest among young men of Israel', 'a', '1 Samuel 16:18 — "Then answered one of the servants, and said, Behold, I have seen a son of Jesse the Bethlehemite, that is cunning in playing, and a mighty valiant man, and a man of war, and prudent in matters, and a comely person, and the LORD is with him."'),
-- Adults
('1 Samuel', 16, 'adults', 1, 'How long did God tell Samuel to mourn for Saul before sending him to anoint a new king?', 'God did not specify a time but rebuked Samuel for mourning too long and told him to fill his horn with oil and go', 'Samuel was told to mourn thirty days as for the dead', 'Samuel was given a year to grieve before God spoke again', 'God said one week of mourning was sufficient', 'a', '1 Samuel 16:1 — "The LORD said unto Samuel, How long wilt thou mourn for Saul, seeing I have rejected him from reigning over Israel? fill thine horn with oil, and go."'),
('1 Samuel', 16, 'adults', 2, 'How many of Jesse''s sons passed before Samuel, and what was Samuel''s reaction to the first?', 'Seven sons passed before him; Samuel looked at Eliab and said Surely the LORD''s anointed is before him — but God rejected him', 'All eight sons were presented at once and Samuel chose the youngest immediately', 'Three sons were rejected before David was called from the field', 'Jesse''s sons came one by one and Samuel prayed after each one', 'a', '1 Samuel 16:6,10 — "When they were come, that he looked on Eliab, and said, Surely the LORD''s anointed is before him...Again, Jesse made seven of his sons to pass before Samuel."'),
('1 Samuel', 16, 'adults', 3, 'What was the description of David''s physical appearance when he was brought in from the fields?', 'He was ruddy, and withal of a beautiful countenance, and goodly to look to', 'He was tall and strong like his brothers', 'He was small of stature but with bright eyes', 'He was dark-skinned with curly hair and a shepherd''s staff', 'a', '1 Samuel 16:12 — "He sent, and brought him in. Now he was ruddy, and withal of a beautiful countenance, and goodly to look to. And the LORD said, Arise, anoint him: for this is he."'),
('1 Samuel', 16, 'adults', 4, 'What exactly did the Spirit of the LORD do when Samuel anointed David?', 'Came upon David from that day forward', 'Filled him with wisdom and power for one year', 'Rested upon him like a dove descending', 'Gave him the gift of prophecy immediately', 'a', '1 Samuel 16:13 — "Then Samuel took the horn of oil, and anointed him in the midst of his brethren: and the Spirit of the LORD came upon David from that day forward."'),
('1 Samuel', 16, 'adults', 5, 'What qualities did Saul''s servant use to recommend David, and how many distinct attributes were listed?', 'Six attributes: cunning in playing, mighty valiant man, man of war, prudent in matters, comely person, and the LORD is with him', 'Three qualities: brave, skilled with weapons, and of good family', 'Four traits: wisdom, strength, beauty, and musical skill', 'Two characteristics: musical ability and loyalty to the king', 'a', '1 Samuel 16:18 — "A son of Jesse...that is cunning in playing, and a mighty valiant man, and a man of war, and prudent in matters, and a comely person, and the LORD is with him."'),
('1 Samuel', 16, 'adults', 6, 'What gift did Jesse send with David when Saul sent for him?', 'An ass laden with bread, and a bottle of wine, and a kid', 'A talent of silver and a golden vessel', 'A sheaf of wheat and a jar of honey', 'Fine linen and a sword of iron', 'a', '1 Samuel 16:20 — "Jesse took an ass laden with bread, and a bottle of wine, and a kid, and sent them by David his son unto Saul."'),
('1 Samuel', 16, 'adults', 7, 'What role specifically did Saul give David in the court, and what did Saul write to Jesse?', 'David became Saul''s armourbearer and Saul asked Jesse to let David stand before him for he had found favour in his sight', 'David was made chief musician of the royal court by decree', 'Saul appointed David as a commander of ten in his army', 'David served as royal messenger between Saul and Samuel', 'a', '1 Samuel 16:21-22 — "David came to Saul, and stood before him: and he loved him greatly; and he became his armourbearer. And Saul sent to Jesse, saying, Let David, I pray thee, stand before me; for he hath found favour in my sight."'),
('1 Samuel', 16, 'adults', 8, 'What theological question does the phrase "an evil spirit from the LORD" raise, and how has it been interpreted?', 'It raises questions about divine permission and causation; traditionally understood as God permitting or sending a tormenting spirit as judgment on Saul after His Spirit departed, not implying God is the author of evil', 'It proves the Old Testament teaches God created evil spirits for His purposes', 'It shows Saul was demon-possessed because of his sin against Samuel', 'It indicates a mental illness that ancient authors attributed to divine cause', 'a', '1 Samuel 16:14 — "The Spirit of the LORD departed from Saul, and an evil spirit from the LORD troubled him." The phrase indicates divine sovereignty over all spirits, with the evil spirit permitted as a consequence of Saul''s rejection.');

-- ═══ 1 Samuel Chapter 17 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 17, 'kids', 1, 'How many smooth stones did David pick up from the brook to fight Goliath?', 'Five', 'One', 'Three', 'Seven', 'a', '1 Samuel 17:40 — "He chose him five smooth stones out of the brook...and his sling was in his hand."'),
('1 Samuel', 17, 'kids', 2, 'In whose name did David say he came to fight Goliath?', 'In the name of the LORD of hosts', 'In the name of King Saul', 'In the name of all Israel', 'In the name of his father Jesse', 'a', '1 Samuel 17:45 — "David said to the Philistine, Thou comest to me with a sword...but I come to thee in the name of the LORD of hosts."'),
('1 Samuel', 17, 'kids', 3, 'What happened to Goliath when David''s stone hit him?', 'He fell upon his face to the earth', 'He stumbled and ran away', 'He fell into the brook', 'He sank to his knees and surrendered', 'a', '1 Samuel 17:49 — "The stone sunk into his forehead; and he fell upon his face to the earth."'),
-- Teens
('1 Samuel', 17, 'teens', 1, 'How tall was Goliath according to 1 Samuel 17?', 'Six cubits and a span', 'Seven cubits tall', 'Five cubits and two spans', 'Eight feet tall', 'a', '1 Samuel 17:4 — "A champion out of the camp of the Philistines, named Goliath of Gath, whose height was six cubits and a span."'),
('1 Samuel', 17, 'teens', 2, 'What reward did Saul offer to the man who killed Goliath?', 'Great riches, his daughter in marriage, and his father''s house free in Israel', 'Command of a thousand soldiers and a city', 'A full share of the king''s treasury', 'The position of captain over all the army', 'a', '1 Samuel 17:25 — "It shall be, that the man who killeth him, the king will enrich him with great riches, and will give him his daughter, and make his father''s house free in Israel."'),
('1 Samuel', 17, 'teens', 3, 'What experience did David use to convince Saul he could fight Goliath?', 'He had killed both a lion and a bear that attacked his sheep', 'He had trained with the army of Israel for two years', 'He had wrestled a wild ox in the wilderness', 'He had defeated three Philistine raiders as a young man', 'a', '1 Samuel 17:36 — "Thy servant slew both the lion and the bear: and this uncircumcised Philistine shall be as one of them, seeing he hath defied the armies of the living God."'),
('1 Samuel', 17, 'teens', 4, 'Why did David refuse Saul''s armor?', 'He had not proved it — he was not used to it', 'It was too heavy for him to walk in', 'A prophet had told him not to use it', 'He trusted only in the LORD without earthly armor', 'a', '1 Samuel 17:39 — "David girded his sword upon his armour, and he assayed to go; for he had not proved it. And David said unto Saul, I cannot go with these; for I have not proved them. And David put them off him."'),
('1 Samuel', 17, 'teens', 5, 'What did David say the battle would prove to all the earth?', 'That there is a God in Israel', 'That Saul was the greatest king in the world', 'That Israel''s army was stronger than all nations', 'That the LORD rewards faith more than size', 'a', '1 Samuel 17:46 — "This day will the LORD deliver thee into mine hand...that all the earth may know that there is a God in Israel."'),
-- Adults
('1 Samuel', 17, 'adults', 1, 'What was the weight of Goliath''s coat of mail and the weight of the head of his spear?', 'Five thousand shekels of brass for the coat of mail and six hundred shekels of iron for the spear head', 'Three thousand shekels of iron for the coat and a thousand shekels for the spear', 'Ten thousand shekels total armor weight with a two-hundred-shekel spear', 'A talent of bronze for the coat and four hundred shekels for the spear', 'a', '1 Samuel 17:5,7 — "He had an helmet of brass upon his head...and the weight of the coat was five thousand shekels of brass...and the staff of his spear was like a weaver''s beam; and his spear''s head weighed six hundred shekels of iron."'),
('1 Samuel', 17, 'adults', 2, 'How long did Goliath present his challenge, and how did Israel respond?', 'Forty days, morning and evening; all the men of Israel fled from him and were sore afraid', 'Seven days until Saul prepared a champion to meet him', 'One month before David arrived at the camp', 'Ten days, twice a day, until Jonathan answered him', 'a', '1 Samuel 17:16 — "The Philistine drew near morning and evening, and presented himself forty days."  17:24 — "All the men of Israel, when they saw the man, fled from him, and were sore afraid."'),
('1 Samuel', 17, 'adults', 3, 'What was David''s purpose in coming to the camp, and who questioned his motives?', 'He came to bring food to his brothers; Eliab his eldest brother accused him of pride and naughtiness of heart', 'He came to enlist in the army and Saul''s generals doubted him', 'He came with a message from Samuel and Saul''s servants challenged him', 'He came voluntarily to fight and his brothers praised his courage', 'a', '1 Samuel 17:17,28 — Jesse sent David with food for his brothers. Eliab said, "I know thy pride, and the naughtiness of thine heart; for thou art come down that thou mightest see the battle."'),
('1 Samuel', 17, 'adults', 4, 'What theological argument did David make to Saul about why the LORD would deliver him from Goliath?', 'The LORD that delivered me out of the paw of the lion and out of the paw of the bear, he will deliver me out of the hand of this Philistine', 'The LORD had promised victory to all who trust in Him', 'God had shown him in a vision that he would defeat Goliath', 'The anointing of Samuel guaranteed his protection in battle', 'a', '1 Samuel 17:37 — "David said moreover, The LORD that delivered me out of the paw of the lion, and out of the paw of the bear, he will deliver me out of the hand of this Philistine."'),
('1 Samuel', 17, 'adults', 5, 'What did Goliath say when he saw David coming, and what did he swear by?', 'He disdained him, cursed David by his gods, and said he would give his flesh to the fowls and the beasts', 'He laughed and told his men to let the boy come as a joke', 'He was alarmed and sent for more Philistine soldiers', 'He challenged David to lay down his weapons before approaching', 'a', '1 Samuel 17:43-44 — "The Philistine cursed David by his gods. And the Philistine said to David, Come to me, and I will give thy flesh unto the fowls of the air, and to the beasts of the field."'),
('1 Samuel', 17, 'adults', 6, 'What did David say the LORD would do beyond just killing Goliath?', 'The LORD would deliver the Philistine host into Israel''s hand and the carcases would be given to the fowls and the beasts so all the earth would know there is a God in Israel', 'God would strike the whole Philistine nation with plague', 'The LORD would give Israel victory over all enemies that day', 'God would set Israel free from all tribute to Philistia forever', 'a', '1 Samuel 17:46 — "The LORD will deliver thee into mine hand; and I will smite thee...I will give the carcases of the host of the Philistines this day unto the fowls of the air...that all the earth may know that there is a God in Israel."'),
('1 Samuel', 17, 'adults', 7, 'After killing Goliath, what did David do with the Philistine''s head, and what did he do with Goliath''s weapons?', 'He brought the head to Jerusalem and put Goliath''s armour in his tent', 'He displayed the head at the entrance to the Israelite camp as a trophy', 'He buried the head with full military honors as was custom', 'He sent the armor to Samuel at Ramah and buried the head', 'a', '1 Samuel 17:54 — "David took the head of the Philistine, and brought it to Jerusalem; but he put his armour in his tent."'),
('1 Samuel', 17, 'adults', 8, 'What does David''s statement "the battle is the LORD''s" reveal about his theology of holy war distinct from mere nationalism?', 'David understood Israel''s battles as fought on the LORD''s behalf and by His power, not by human might, making Goliath''s defiance an offense against God requiring divine vindication rather than merely a military problem', 'David was simply encouraging the troops with a traditional war cry', 'It shows David believed God would miraculously fight so Israel needed no soldiers', 'David was quoting a law given to Moses about warfare', 'a', '1 Samuel 17:47 — "All this assembly shall know that the LORD saveth not with sword and spear: for the battle is the LORD''s, and he will give you into our hands."');

-- ═══ 1 Samuel Chapter 18 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 18, 'kids', 1, 'Who made a covenant of friendship with David and gave him his own robe?', 'Jonathan', 'Saul', 'Samuel', 'Abner', 'a', '1 Samuel 18:3-4 — "Jonathan and David made a covenant...And Jonathan stripped himself of the robe that was upon him, and gave it to David."'),
('1 Samuel', 18, 'kids', 2, 'What did the women sing that made Saul very angry?', 'Saul hath slain his thousands, and David his ten thousands', 'David is greater than all the kings of Israel', 'The LORD loves David more than Saul', 'David''s glory fills the land like the sun', 'a', '1 Samuel 18:7 — "The women answered one another as they played, and said, Saul hath slain his thousands, and David his ten thousands."'),
('1 Samuel', 18, 'kids', 3, 'What did Saul throw at David while David was playing the harp?', 'A javelin', 'A sword', 'A stone', 'A spear', 'a', '1 Samuel 18:11 — "Saul cast the javelin; for he said, I will smite David even to the wall with it. And David avoided out of his presence twice."'),
-- Teens
('1 Samuel', 18, 'teens', 1, 'How did Jonathan feel about David after David spoke with Saul following the Goliath victory?', 'The soul of Jonathan was knit with the soul of David, and Jonathan loved him as his own soul', 'Jonathan admired David as the greatest warrior in Israel', 'Jonathan felt threatened by David''s popularity with the people', 'Jonathan respected David as a skilled musician and soldier', 'a', '1 Samuel 18:1 — "The soul of Jonathan was knit with the soul of David, and Jonathan loved him as his own soul."'),
('1 Samuel', 18, 'teens', 2, 'What items did Jonathan give David as part of their covenant?', 'His robe, garments, sword, bow, and girdle', 'His armor, helmet, and shield', 'His silver ring and a written covenant', 'His father''s blessing and a portion of land', 'a', '1 Samuel 18:4 — "Jonathan stripped himself of the robe that was upon him, and gave it to David, and his garments, even to his sword, and to his bow, and to his girdle."'),
('1 Samuel', 18, 'teens', 3, 'Why did Saul become afraid of David?', 'Because the LORD was with David and had departed from Saul', 'Because David had become more popular than the king', 'Because David refused to obey Saul''s commands', 'Because David had more soldiers loyal to him than to Saul', 'a', '1 Samuel 18:12 — "And Saul was afraid of David, because the LORD was with him, and was departed from Saul."'),
('1 Samuel', 18, 'teens', 4, 'What task did Saul send David to do, hoping he would be killed by the Philistines?', 'Fight the Philistines as captain over a thousand men, going out and coming in before the people', 'Lead a small raiding party deep into Philistine territory', 'Carry a message to the Philistine king alone', 'Guard the most dangerous section of the battle line with only ten men', 'a', '1 Samuel 18:13 — "Therefore Saul removed him from him, and made him his captain over a thousand; and he went out and came in before the people."'),
('1 Samuel', 18, 'teens', 5, 'What bride price did Saul demand of David to marry Michal, hoping to use it to get David killed by the Philistines?', 'A hundred foreskins of the Philistines', 'Thirty Philistine captains brought alive to Saul', 'The sword of Goliath of Gath', 'Three battles won without losing a man of Israel', 'a', '1 Samuel 18:25 — "Saul said, Thus shall ye say to David, The king desireth not any dowry, but an hundred foreskins of the Philistines, to be avenged of the king''s enemies. But Saul thought to make David fall by the hand of the Philistines."'),
-- Adults
('1 Samuel', 18, 'adults', 1, 'What phrase in 1 Samuel 18 describes the depth of Jonathan''s love for David, and what covenant did they make?', 'Jonathan loved him as his own soul and they made a covenant, with Jonathan giving David his royal garments and weapons', 'They swore by the LORD to be allies in every battle', 'Jonathan pledged to make David his heir if he died without sons', 'They exchanged names as was the custom of blood brothers in Israel', 'a', '1 Samuel 18:1,3-4 — "The soul of Jonathan was knit with the soul of David, and Jonathan loved him as his own soul...Jonathan and David made a covenant...And Jonathan stripped himself of the robe."'),
('1 Samuel', 18, 'adults', 2, 'How did Saul''s initial promotion of David set the stage for his growing jealousy?', 'David behaved wisely in all his ways and the LORD was with him, so Saul set him over the men of war; all Israel and Judah loved David', 'David was given command of the temple guard which gave him access to religious authority', 'Saul promoted David hoping he would fail and be disgraced publicly', 'David was given the position of court scribe which gave him influence over Saul''s advisors', 'a', '1 Samuel 18:5 — "David went out whithersoever Saul sent him, and behaved himself wisely: and Saul set him over the men of war, and he was accepted in the sight of all the people."'),
('1 Samuel', 18, 'adults', 3, 'How many times does the text record that Saul eyed David from this point forward, and what specifically was he afraid of?', 'He eyed David from that day and forward; he was afraid because the LORD was with David and had departed from Saul, and because of what the women''s song implied about David''s superiority', 'He eyed him three specific times the narrative records', 'He watched David only when the evil spirit was upon him', 'He eyed him once at court then sent him away permanently', 'a', '1 Samuel 18:9 — "Saul eyed David from that day and forward." 18:12 — "Saul was afraid of David, because the LORD was with him, and was departed from Saul."'),
('1 Samuel', 18, 'adults', 4, 'What did Saul promise David as a bride, and why did he not follow through with his first daughter Merab?', 'He had promised Merab but gave her to Adriel the Meholathite when the time came; he used the promise as a way to put David in danger from the Philistines', 'Merab refused to marry David because he was of lowly birth', 'Saul gave Merab to another man before the matter was arranged with David', 'David refused Merab saying he was unworthy of the king''s daughter', 'a', '1 Samuel 18:17,19 — "Saul said to David...Behold my elder daughter Merab, her will I give thee to wife...But...Merab Saul''s daughter should have been given to David...she was given unto Adriel the Meholathite to wife."'),
('1 Samuel', 18, 'adults', 5, 'How many Philistine foreskins did David actually bring to Saul, and by when?', 'Two hundred, before the days were expired', 'A hundred, the exact number required', 'Three hundred, to show his excess of zeal', 'Fifty, all he could gather before the deadline', 'a', '1 Samuel 18:27 — "David arose and went, he and his men, and slew of the Philistines two hundred men; and David brought their foreskins, and they gave them in full tale to the king."'),
('1 Samuel', 18, 'adults', 6, 'What was Saul''s response when he realized that both his son Jonathan and his daughter Michal loved David?', 'Saul became yet more afraid of David and was his enemy continually', 'Saul planned to use his children''s love to spy on David', 'Saul rejoiced briefly thinking family bonds would keep David loyal', 'Saul was indifferent, focusing only on the military threat David posed', 'a', '1 Samuel 18:28-29 — "Saul saw and knew that the LORD was with David...And Saul was yet the more afraid of David; and Saul became David''s enemy continually."'),
('1 Samuel', 18, 'adults', 7, 'What phrase is used repeatedly in chapter 18 to explain David''s success in every mission Saul assigned?', 'He behaved himself wisely / more wisely than all the servants of Saul, and the LORD was with him', 'The hand of God was upon him in every battle', 'He was beloved of all the people and the army', 'Samuel''s anointing went before him like a shield', 'a', '1 Samuel 18:5,14-15 — "David behaved himself wisely in all his ways; and the LORD was with him. Wherefore when Saul saw that he behaved himself very wisely, he was afraid of him."'),
('1 Samuel', 18, 'adults', 8, 'What does Saul''s repeated attempts to use marriage, military exposure, and the Philistines to destroy David reveal about his spiritual state?', 'Saul was operating in fear, envy, and scheming deception rather than trusting God, a pattern consistent with a man from whom God''s Spirit had departed', 'Saul was acting as a rational king protecting his throne from a potential usurper', 'Saul genuinely wanted to promote David but feared popular opinion', 'The narrator portrays Saul sympathetically as a man trapped by an impossible situation', 'a', '1 Samuel 18:25 — "Saul thought to make David fall by the hand of the Philistines." This pattern of deception contrasts with the LORD''s evident blessing on David.');

-- ═══ 1 Samuel Chapter 19 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 19, 'kids', 1, 'Who helped David escape from Saul by letting him down through a window?', 'Michal, David''s wife', 'Jonathan, David''s friend', 'Samuel the prophet', 'Abigail, a wise woman', 'a', '1 Samuel 19:12 — "Michal let David down through a window: and he went, and fled, and escaped."'),
('1 Samuel', 19, 'kids', 2, 'Where did David flee to after escaping from Saul?', 'To Samuel at Ramah', 'To Jonathan''s house', 'Into the wilderness', 'To the cave of Adullam', 'a', '1 Samuel 19:18 — "David fled, and escaped, and came to Samuel to Ramah."'),
('1 Samuel', 19, 'kids', 3, 'What happened to Saul when he sent messengers to capture David at Naioth?', 'The Spirit of God came upon them and they prophesied', 'They were turned back by an angel', 'They fell asleep before reaching Naioth', 'They refused to obey the king''s command', 'a', '1 Samuel 19:20 — "When they saw the company of the prophets prophesying, and Samuel standing as appointed over them, the Spirit of God was upon the messengers of Saul, and they also prophesied."'),
-- Teens
('1 Samuel', 19, 'teens', 1, 'What did Jonathan do when Saul told him to kill David?', 'He spoke well of David and reminded Saul how David had risked his life to kill the Philistine and won a great victory for Israel', 'He refused and left Saul''s court in anger', 'He warned David secretly without confronting Saul', 'He asked Samuel to speak to Saul on David''s behalf', 'a', '1 Samuel 19:4-5 — "Jonathan spake good of David unto Saul his father, and said unto him, Let not the king sin against his servant David; because he hath not sinned against thee, and because his works have been to thee-ward very good."'),
('1 Samuel', 19, 'teens', 2, 'What happened to Saul that temporarily reversed his desire to kill David after Jonathan pleaded for David?', 'Saul hearkened unto Jonathan and swore that David shall not be slain', 'God struck Saul with illness until he relented', 'The people threatened to revolt if Saul killed David', 'Samuel pronounced a curse on any who touched David', 'a', '1 Samuel 19:6 — "Saul hearkened unto the voice of Jonathan: and Saul sware, As the LORD liveth, he shall not be slain."'),
('1 Samuel', 19, 'teens', 3, 'What triggered Saul''s fresh attempt to kill David after he had sworn not to harm him?', 'The evil spirit came upon Saul while David played harp before him', 'David was promoted above Abner and Saul was jealous', 'The women''s song was sung again before Saul''s court', 'A new military victory by David inflamed Saul''s envy', 'a', '1 Samuel 19:9-10 — "The evil spirit from the LORD was upon Saul, as he sat in his house with his javelin in his hand: and David played with his hand. And Saul sought to smite David even to the wall with the javelin."'),
('1 Samuel', 19, 'teens', 4, 'What did Michal put in David''s bed to deceive Saul''s messengers into thinking David was sick?', 'An image and a pillow of goats'' hair for his bolster', 'A bundle of clothing shaped like a person', 'A statue of a man with a cloth covering', 'A pillow and rolled-up blankets', 'a', '1 Samuel 19:13 — "Michal took an image, and laid it in the bed, and put a pillow of goats'' hair for his bolster, and covered it with a cloth."'),
('1 Samuel', 19, 'teens', 5, 'What happened when Saul himself went to Naioth to seize David?', 'The Spirit of God came upon Saul and he stripped off his clothes and prophesied before Samuel all day and night', 'Saul was struck blind and could not find David', 'Saul repented before Samuel and vowed to spare David', 'An angel of the LORD blocked Saul''s path', 'a', '1 Samuel 19:24 — "He stripped off his clothes also, and prophesied before Samuel in like manner, and lay down naked all that day and all that night."'),
-- Adults
('1 Samuel', 19, 'adults', 1, 'What specific theological argument did Jonathan use when he pleaded for David''s life before Saul?', 'David had not sinned against Saul, his works had been very good, he had put his life in his hand to kill the Philistine, the LORD wrought a great salvation for all Israel, Saul saw it and rejoiced — wherefore wilt thou sin against innocent blood', 'Jonathan argued from the covenant of friendship they had made', 'Jonathan claimed David was protected by Samuel''s anointing', 'Jonathan said killing David would be a violation of the covenant with Jesse', 'a', '1 Samuel 19:4-5 — "Jonathan said...David hath not sinned against thee, and because his works have been to thee-ward very good...he did put his life in his hand, and slew the Philistine, and the LORD wrought a great salvation for all Israel...wherefore then wilt thou sin against innocent blood?"'),
('1 Samuel', 19, 'adults', 2, 'What is significant about the teraphim (image) that Michal used, and what does its presence in David''s home suggest?', 'It was a household idol whose size could substitute for a sleeping figure; its presence suggests even David''s household retained some idolatrous objects, a detail the text records without explicit approval', 'It was a sacred statue from the tabernacle used for healing', 'It was a life-size wooden figure carved by David as a craftsman', 'It was a mold of David''s face made by court artists', 'a', '1 Samuel 19:13 — "Michal took an image, and laid it in the bed." The Hebrew word is teraphim, household idols mentioned elsewhere in the OT as prohibited cult objects.'),
('1 Samuel', 19, 'adults', 3, 'What excuse did Michal give Saul when questioned about helping David escape?', 'She said David had told her to let him go or he would kill her', 'She claimed David threatened her life if she did not help him', 'She said she did not know David had left until morning', 'She told Saul she was commanded by the LORD in a dream', 'a', '1 Samuel 19:17 — "Saul said to Michal, Why hast thou deceived me so, and sent away mine enemy, that he is escaped? And Michal answered Saul, He said unto me, Let me go; why should I kill thee?"'),
('1 Samuel', 19, 'adults', 4, 'What was the place called where David and Samuel stayed together, and what was happening there?', 'Naioth in Ramah, where a company of prophets was prophesying with Samuel standing over them as appointed head', 'The school of the prophets at Shiloh with the ark nearby', 'The high place at Mizpeh where Samuel regularly judged', 'A cave near Ramah where Samuel met with elders', 'a', '1 Samuel 19:18-20 — "David fled...to Samuel to Ramah...and they went to Naioth. And it was told Saul, saying, Behold, David is at Naioth in Ramah...and they saw the company of the prophets prophesying, and Samuel standing as appointed over them."'),
('1 Samuel', 19, 'adults', 5, 'How many sets of messengers did Saul send before going himself, and what happened to each?', 'Three groups of messengers — all three companies were overcome by the Spirit and prophesied, so Saul went himself', 'Two groups who turned back, then Saul''s personal guard, then Saul himself', 'One group of thirty soldiers then Saul went personally when they failed', 'Five groups were sent over five days before Saul went himself', 'a', '1 Samuel 19:20-21 — "Saul sent messengers to take David...the Spirit of God was upon the messengers...and they also prophesied. And when it was told Saul, he sent other messengers, and they prophesied likewise. And Saul sent messengers again the third time, and they prophesied also."'),
('1 Samuel', 19, 'adults', 6, 'What proverbial saying originated from Saul''s experience of prophesying at Naioth?', 'Is Saul also among the prophets?', 'The Spirit blows where it wills and no man can stop it', 'Even a king must bow before the word of the LORD', 'No weapon formed against God''s anointed shall prosper', 'a', '1 Samuel 19:24 — "And one of the same place answered and said, And who is their father? Therefore it became a proverb, Is Saul also among the prophets?"'),
('1 Samuel', 19, 'adults', 7, 'How does the sequence of events in chapter 19 — Jonathan''s intercession, Saul''s oath, the evil spirit, Michal''s rescue, the messengers prophesying, Saul prophesying — function as a narrative unit?', 'It shows the progressive deterioration of Saul''s kingship as each divine intervention protects David while Saul repeatedly breaks his oaths and is overcome by spiritual forces beyond his control', 'It is a disjointed collection of independent stories about David''s escapes', 'It demonstrates that Saul was never truly wicked but only mentally ill', 'It shows that prophecy was the highest power in Israel above kingship', 'a', '1 Samuel 19:9 — "The evil spirit from the LORD was upon Saul." The entire chapter illustrates God''s protection of David and Saul''s increasing inability to harm him.'),
('1 Samuel', 19, 'adults', 8, 'What does Saul''s compelled prophesying at Naioth demonstrate about the nature of God''s Spirit in the Old Testament?', 'The Spirit''s power could override human will even for those who had forfeited God''s favor, serving to protect David while simultaneously humiliating Saul before all observers', 'The Spirit was given unconditionally to all who entered the prophets'' school', 'Prophesying was always a sign of divine approval and Saul was briefly restored', 'The event shows that spiritual gifts once given cannot be permanently removed', 'a', '1 Samuel 19:23-24 — "The Spirit of God was upon him also, and he went on, and prophesied...And he stripped off his clothes also, and prophesied before Samuel...and lay down naked all that day and all that night."');

-- ═══ 1 Samuel Chapter 20 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 20, 'kids', 1, 'What signal did Jonathan use to tell David whether it was safe to return or if he must flee?', 'He shot arrows and told a lad where they landed', 'He sent a dove with a message to David''s hiding place', 'He lit a torch on the hillside to signal safety', 'He blew a trumpet once for safe and twice for danger', 'a', '1 Samuel 20:20-22 — "I will shoot three arrows on the side thereof, as though I shot at a mark...if I say unto the young man, Behold, the arrows are on this side of thee, take them; then come thou: for there is peace...But if I say thus unto the young man, Behold, the arrows are beyond thee; go thy way: for the LORD hath sent thee away."'),
('1 Samuel', 20, 'kids', 2, 'What did David and Jonathan do when they met for the last time before David fled?', 'They kissed one another and wept', 'They prayed together and sang a psalm', 'They embraced and exchanged swords', 'They broke bread together and said farewell', 'a', '1 Samuel 20:41 — "David...fell on his face to the ground, and bowed himself three times: and they kissed one another, and wept one with another."'),
('1 Samuel', 20, 'kids', 3, 'What did Jonathan and David promise to one another in their covenant?', 'The LORD be between me and thee, and between my seed and thy seed for ever', 'We will always protect each other''s family', 'We shall never fight against each other in battle', 'We will share whatever the LORD gives us', 'a', '1 Samuel 20:42 — "Jonathan said to David, Go in peace, forasmuch as we have sworn both of us in the name of the LORD, saying, The LORD be between me and thee, and between my seed and thy seed for ever."'),
-- Teens
('1 Samuel', 20, 'teens', 1, 'Why did David say he needed to miss Saul''s New Moon feast?', 'He asked Jonathan to say he had gone to Bethlehem for a yearly sacrifice with his family', 'He told Jonathan he was too afraid to come to court', 'He sent word that he was ill and could not travel', 'He claimed he was on a military mission for the king', 'a', '1 Samuel 20:6 — "If thy father at all miss me, then say, David earnestly asked leave of me that he might run to Beth-lehem his city: for there is a yearly sacrifice there for all the family."'),
('1 Samuel', 20, 'teens', 2, 'How did Jonathan plan to find out Saul''s true intentions toward David?', 'He would observe Saul''s reaction when David''s seat was empty at the feast for two days', 'He would ask Saul directly whether he intended to kill David', 'He would consult the Urim and Thummim at the tabernacle', 'He would send a trusted servant to spy on Saul''s private conversations', 'a', '1 Samuel 20:12 — "Jonathan said unto David, O LORD God of Israel, when I have sounded my father about to morrow any time, or the third day, and, behold, if there be good toward David."'),
('1 Samuel', 20, 'teens', 3, 'How did Saul react when David''s place was empty the second day at the feast?', 'Saul''s anger was kindled against Jonathan and he called David the son of the perverse rebellious woman', 'Saul asked calmly where David was and accepted the answer', 'Saul sent soldiers immediately to arrest David', 'Saul wept and grieved because he feared David was already gone', 'a', '1 Samuel 20:30 — "Saul''s anger was kindled against Jonathan, and he said unto him, Thou son of the perverse rebellious woman, do not I know that thou hast chosen the son of Jesse to thine own confusion?"'),
('1 Samuel', 20, 'teens', 4, 'What did Saul throw at Jonathan when Jonathan defended David?', 'His javelin to smite him', 'A cup of wine in his rage', 'His crown in fury', 'A sandal as a sign of contempt', 'a', '1 Samuel 20:33 — "Saul cast a javelin at him to smite him: whereby Jonathan knew that it was determined of his father to slay David."'),
('1 Samuel', 20, 'teens', 5, 'What reason did Jonathan give David for why Saul must be stopped from killing him?', 'For Jonathan knew that it was determined of his father to slay David', 'Because David was the LORD''s anointed and untouchable', 'Because Israel needed David to protect them from the Philistines', 'Because killing David would break Jonathan''s covenant oath', 'a', '1 Samuel 20:33 — "Saul cast a javelin at him to smite him: whereby Jonathan knew that it was determined of his father to slay David."'),
-- Adults
('1 Samuel', 20, 'adults', 1, 'What was David''s opening complaint to Jonathan in chapter 20, and how did it frame the entire chapter?', 'He asked what his iniquity was, what his sin before Saul was, that Saul sought his life — David saw no reason for Saul''s murderous intent', 'David asked Jonathan to use his influence to restore him to court favor', 'David reported that Saul had just made another direct attempt on his life', 'David asked Jonathan to verify a rumor he had heard from Abner', 'a', '1 Samuel 20:1 — "David fled from Naioth in Ramah, and came and said before Jonathan, What have I done? what is mine iniquity? and what is my sin before thy father, that he seeketh my life?"'),
('1 Samuel', 20, 'adults', 2, 'What covenant terms did Jonathan propose, and what kindness did he ask of David?', 'That David would show kindness to Jonathan''s house forever, not cut off kindness from his house even when the LORD had cut off David''s enemies', 'That David would give Jonathan''s sons positions of honor when he became king', 'That Jonathan would always fight beside David and David would honor Jonathan above all other men', 'That they would share equally in any kingdom God gave to either of them', 'a', '1 Samuel 20:14-15 — "Thou shalt not only while yet I live shew me the kindness of the LORD, that I die not: But also thou shalt not cut off thy kindness from my house for ever: no, not when the LORD hath cut off the enemies of David every one from the face of the earth."'),
('1 Samuel', 20, 'adults', 3, 'What was the specific agreed signal: what words to the lad meant safety, and what words meant flee?', 'If Jonathan said the arrows are on this side of thee, take them — peace; if he said the arrows are beyond thee — flee, for the LORD hath sent thee away', 'One arrow shot high meant safety; three arrows shot low meant danger', 'If Jonathan whistled once David should come; twice meant danger', 'The position of the sun when Jonathan arrived at the field was the signal', 'a', '1 Samuel 20:21-22 — "If I say unto the young man, Behold, the arrows are on this side of thee; take them: then come thou...But if I say thus unto the young man, Behold, the arrows are beyond thee; go thy way: for the LORD hath sent thee away."'),
('1 Samuel', 20, 'adults', 4, 'What argument did Saul use to Jonathan to justify killing David, rooted in dynastic self-interest?', 'As long as David lives thou shalt not be established nor thy kingdom; send and fetch him for he shall surely die', 'David was a rebel against anointed kingship and must be punished', 'Letting David live would shame Saul before all the tribes of Israel', 'David''s popularity would lead to civil war that only his death could prevent', 'a', '1 Samuel 20:31 — "For as long as the son of Jesse liveth upon the ground, thou shalt not be established, nor thy kingdom. Wherefore now send and fetch him unto me, for he shall surely die."'),
('1 Samuel', 20, 'adults', 5, 'Why was Jonathan angry when he left the table after the second day of the feast, and what was his emotional state?', 'He arose in fierce anger and did eat no meat the second day because he was grieved for David because his father had done him shame', 'He was angry at David for putting him in a difficult position with his father', 'He was furious that Saul had questioned his loyalty as a son', 'He was grieved because Saul had revealed plans to make Abner king instead of Jonathan', 'a', '1 Samuel 20:34 — "So Jonathan arose from the table in fierce anger, and did eat no meat the second day of the month: for he was grieved for David, because his father had done him shame."'),
('1 Samuel', 20, 'adults', 6, 'After the arrow signal, how did the two friends find a private moment to speak, and what was the nature of their parting?', 'After Jonathan sent the lad away, David came out from the south side and they kissed, wept, and David exceeded in weeping', 'They met secretly at night after Saul''s guards had changed', 'Jonathan came alone to David''s cave and they spoke through the night', 'They exchanged final words only through the signal and never met face to face again', 'a', '1 Samuel 20:41 — "As soon as the lad was gone, David arose out of a place toward the south...and fell on his face to the ground...and they kissed one another, and wept one with another: and David exceeded."'),
('1 Samuel', 20, 'adults', 7, 'What was the full text of the covenant oath Jonathan pronounced at their parting, and what did it extend to?', 'Go in peace, forasmuch as we have sworn both of us in the name of the LORD, saying, The LORD be between me and thee, and between my seed and thy seed for ever', 'I swear by the LORD your God that you shall be king and I shall be at your right hand', 'The LORD witness that I will always be your shield and you my right arm', 'By the oath of our fathers, we are bound as one soul before God and men', 'a', '1 Samuel 20:42 — "Jonathan said to David, Go in peace, forasmuch as we have sworn both of us in the name of the LORD, saying, The LORD be between me and thee, and between my seed and thy seed for ever."'),
('1 Samuel', 20, 'adults', 8, 'What does Jonathan''s willingness to defy his father, endure a javelin attack, and aid his rival for the throne reveal about the nature of covenant love (hesed) in the Old Testament?', 'Jonathan exemplified hesed — steadfast covenant loyalty that goes beyond self-interest, prioritizing faithfulness to God''s purposes and love for David above personal gain, dynastic ambition, or filial loyalty to Saul', 'Jonathan acted primarily out of romantic friendship rather than theological commitment', 'Jonathan was strategically positioning himself to share David''s future kingdom', 'The narrative shows Jonathan was more righteous than David and deserved the kingship', 'a', '1 Samuel 20:14 — "Thou shalt not only while yet I live shew me the kindness of the LORD." The Hebrew word chesed (covenant love) underlies Jonathan''s entire posture toward David.');
