-- ============================================================================
-- Quiz Seed: Judges — Part 1 (Chapters 1–10)
-- 3 difficulties × 10 chapters = 160 total questions
-- ============================================================================

-- ═══ Judges Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 1, 'kids', 1, 'Which tribe of Israel went up first to fight the Canaanites after Joshua died?', 'Judah', 'Benjamin', 'Dan', 'Simeon', 'a', 'Judges 1:2 — "The LORD said, Judah shall go up: behold, I have delivered the land into his hand."'),
('Judges', 1, 'kids', 2, 'What did the men of Judah do to the king called Adoni-bezek when they caught him?', 'They cut off his thumbs and big toes', 'They put him in prison', 'They made him their servant', 'They sent him back to his city', 'a', 'Judges 1:6 — "They cut off his thumbs and his great toes."'),
('Judges', 1, 'kids', 3, 'What did Caleb offer as a reward to whoever captured the city of Debir?', 'Gold and silver', 'His daughter Achsah as a wife', 'A piece of land by the sea', 'A thousand sheep', 'a', 'Judges 1:12 — "Caleb said, He that smiteth Kirjath-sepher, and taketh it, to him will I give Achsah my daughter to wife."'),
-- Teens
('Judges', 1, 'teens', 1, 'Who captured Kirjath-sepher and received Caleb''s daughter Achsah as his wife?', 'Othniel the son of Kenaz', 'Ehud the son of Gera', 'Shamgar the son of Anath', 'Caleb''s eldest son', 'a', 'Judges 1:13 — "Othniel the son of Kenaz, Caleb''s younger brother, took it: and he gave him Achsah his daughter to wife."'),
('Judges', 1, 'teens', 2, 'What did Achsah ask her father Caleb to give her, besides the south land he had given?', 'Springs of water', 'A city of her own', 'Flocks of sheep', 'An inheritance in Canaan', 'a', 'Judges 1:15 — "Give me also springs of water. And Caleb gave her the upper springs and the nether springs."'),
('Judges', 1, 'teens', 3, 'What did Adoni-bezek confess had been done to him as a just punishment?', 'Seventy kings with thumbs and great toes cut off had gathered scraps under his table', 'He had been defeated by his own army', 'He had broken the covenant of the gods', 'He had wrongly ruled for thirty years', 'a', 'Judges 1:7 — "Threescore and ten kings, having their thumbs and their great toes cut off, gathered their meat under my table: as I have done, so God hath requited me."'),
('Judges', 1, 'teens', 4, 'The tribe of Benjamin failed to drive out which people from Jerusalem?', 'The Jebusites', 'The Philistines', 'The Amorites', 'The Hittites', 'a', 'Judges 1:21 — "And the children of Benjamin did not drive out the Jebusites that inhabited Jerusalem; but the Jebusites dwell with the children of Benjamin in Jerusalem unto this day."'),
('Judges', 1, 'teens', 5, 'What tribe was put to forced labour because Israel could not drive them out entirely?', 'The Canaanites', 'The Perizzites', 'The Hivites', 'The Hittites', 'a', 'Judges 1:28 — "When Israel was strong, that they put the Canaanites to tribute, and did not utterly drive them out."'),
-- Adults
('Judges', 1, 'adults', 1, 'What divine instruction opened the military campaign described in Judges 1, and who gave it?', 'The LORD told Judah to go up first, and confirmed He had delivered the land', 'An angel commanded all tribes to march together', 'Moses spoke from beyond the grave', 'Joshua''s written scroll was opened', 'a', 'Judges 1:2 — "The LORD said, Judah shall go up: behold, I have delivered the land into his hand."'),
('Judges', 1, 'adults', 2, 'Which two tribes joined forces at the opening of Judges 1, and what does this alliance reveal?', 'Judah and Simeon, fulfilling their mutual covenant of military brotherhood', 'Judah and Levi, honouring priestly leadership', 'Judah and Benjamin, defending the southern border', 'Judah and Reuben, following the order of encampment', 'a', 'Judges 1:3 — "Judah said unto Simeon his brother, Come up with me into my lot...So Simeon went with him."'),
('Judges', 1, 'adults', 3, 'What is the theological significance of Adoni-bezek''s own confession in Judges 1:7?', 'He acknowledged the justice of God in repaying him according to his own cruelty', 'He converted to the faith of Israel', 'He predicted Israel''s future apostasy', 'He identified Judah as the chosen tribe', 'a', 'Judges 1:7 — "As I have done, so God hath requited me." His words affirm the principle of lex talionis operating under divine providence.'),
('Judges', 1, 'adults', 4, 'The house of Joseph''s capture of Bethel is introduced in Judges 1:22. What intelligence method helped them take the city?', 'A man from the city showed them the entrance in exchange for his family''s safety', 'They used a secret tunnel under the walls', 'A spy had been living there for a year', 'They bribed the city''s gatekeeper', 'a', 'Judges 1:24-25 — "The spies saw a man come forth out of the city, and they said...Shew us...the entrance...and we will shew thee mercy."'),
('Judges', 1, 'adults', 5, 'According to Judges 1:19, what military advantage did the inhabitants of the valley have that hindered Judah?', 'Chariots of iron', 'Superior archery from high walls', 'Alliances with surrounding nations', 'Fortified underground cities', 'a', 'Judges 1:19 — "He could not drive out the inhabitants of the valley, because they had chariots of iron."'),
('Judges', 1, 'adults', 6, 'List three tribes mentioned in Judges 1 that failed to drive out Canaanites and instead allowed them to dwell among them.', 'Manasseh, Ephraim, and Zebulun', 'Judah, Issachar, and Naphtali', 'Reuben, Gad, and Asher', 'Dan, Levi, and Benjamin', 'a', 'Judges 1:27-33 — Manasseh (v.27), Ephraim (v.29), Zebulun (v.30), Asher (v.31), and Naphtali (v.33) all failed to expel Canaanites.'),
('Judges', 1, 'adults', 7, 'What happened to the Amorites when they pressed Dan back into the hill country?', 'The Amorites forced Dan into the hill country and would not allow them to come down to the valley', 'Dan allied with Judah and drove them back', 'The Amorites were eventually put to tribute by the house of Joseph', 'Dan appealed to the LORD and received a victory', 'a', 'Judges 1:34-35 — "The Amorites forced the children of Dan into the mountain: for they would not suffer them to come down to the valley." The Amorites were later put to tribute by the house of Joseph.'),
('Judges', 1, 'adults', 8, 'What is the literary purpose of the repeated phrase "did not drive out" throughout Judges 1, and how does it set up the rest of the book?', 'It establishes the pattern of incomplete obedience that will lead to the cycles of apostasy and oppression throughout Judges', 'It records a census of Canaanite survivors', 'It explains the geography of Canaan', 'It justifies Israel''s tolerance of pagan neighbours', 'a', 'Judges 1:19,21,27,28,29,30,31,33 — The repeated phrase forms a theological indictment: Israel''s failure to obey the ban (herem) directly causes the crises of Judges 2 onward.');

-- ═══ Judges Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 2, 'kids', 1, 'Where did the angel of the LORD appear to all the children of Israel in Judges 2?', 'Bochim', 'Bethel', 'Jerusalem', 'Shiloh', 'a', 'Judges 2:1 — "And an angel of the LORD came up from Gilgal to Bochim."'),
('Judges', 2, 'kids', 2, 'What did the people do when they heard the angel''s message at Bochim?', 'They lifted up their voice and wept', 'They sang a song of praise', 'They built an altar', 'They went home', 'a', 'Judges 2:4 — "The people lifted up their voice, and wept."'),
('Judges', 2, 'kids', 3, 'What did the LORD give Israel when they were in trouble from their enemies?', 'A judge who saved them', 'A strong king', 'A new land', 'An army from heaven', 'a', 'Judges 2:16 — "Nevertheless the LORD raised up judges, which delivered them out of the hand of those that spoiled them."'),
-- Teens
('Judges', 2, 'teens', 1, 'What covenant violation did the angel of the LORD rebuke Israel for at Bochim?', 'Making a league with the inhabitants of the land and not throwing down their altars', 'Failing to circumcise their children', 'Refusing to offer sacrifices', 'Worshipping at Shiloh instead of Jerusalem', 'a', 'Judges 2:2 — "Ye shall make no league with the inhabitants of this land; ye shall throw down their altars: but ye have not obeyed my voice."'),
('Judges', 2, 'teens', 2, 'How old was Joshua when he died, according to Judges 2?', 'One hundred and ten years old', 'One hundred and twenty years old', 'Ninety years old', 'One hundred years old', 'a', 'Judges 2:8 — "Joshua the son of Nun, the servant of the LORD, died, being an hundred and ten years old."'),
('Judges', 2, 'teens', 3, 'What generation after Joshua did not know the LORD or the works He had done for Israel?', 'The generation that arose after them', 'The generation of Joshua''s children', 'The third generation after Moses', 'The Levites who replaced Phinehas', 'a', 'Judges 2:10 — "There arose another generation after them, which knew not the LORD, nor yet the works which he had done for Israel."'),
('Judges', 2, 'teens', 4, 'According to Judges 2, what did Israel do that provoked the LORD to anger?', 'They forsook the LORD and served Baal and Ashtaroth', 'They refused to pay tithes to the priests', 'They intermarried with the Philistines', 'They stopped going to war against the Canaanites', 'a', 'Judges 2:13 — "They forsook the LORD, and served Baal and Ashtaroth."'),
('Judges', 2, 'teens', 5, 'In the cycle described in Judges 2, what happened when a judge died?', 'Israel returned to idolatry and behaved worse than their fathers', 'A new judge immediately arose', 'Israel kept the covenant for a generation', 'The LORD sent a prophet to warn them', 'a', 'Judges 2:19 — "When the judge was dead...they returned, and corrupted themselves more than their fathers."'),
-- Adults
('Judges', 2, 'adults', 1, 'What is the theological name scholars give to the pattern introduced in Judges 2:11-19, and what are its stages?', 'The Deuteronomic Cycle: sin, oppression, cry, deliverance by a judge, rest, then relapse', 'The Covenant Spiral: blessing, testing, failure, punishment, and renewal', 'The Priestly Pattern: sacrifice, atonement, cleansing, and restoration', 'The Prophetic Sequence: warning, rejection, exile, and return', 'a', 'Judges 2:11-19 outlines the recurring cycle: Israel sins (v.11-13), the LORD delivers them to enemies (v.14), they cry out (v.18), the LORD raises a judge (v.16), rest comes, and then they relapse (v.19).'),
('Judges', 2, 'adults', 2, 'What specific reason does Judges 2:22 give for the LORD leaving nations in the land after Joshua?', 'To prove Israel — whether they would keep the way of the LORD or not', 'To punish Israel for their sins for forty years', 'To provide labourers for Israel''s building projects', 'To fulfil the covenant with the Canaanites', 'a', 'Judges 2:22 — "That through them I may prove Israel, whether they will keep the way of the LORD to walk therein, as their fathers did keep it, or not."'),
('Judges', 2, 'adults', 3, 'What does the angel''s statement "I will not drive them out from before you" in Judges 2:3 reveal about God''s covenantal response?', 'God conditionally withdrew His promise of conquest due to Israel''s breach of covenant terms', 'God permanently abandoned Israel as His people', 'God transferred the promise to another nation', 'God was testing the angel''s authority', 'a', 'Judges 2:3 — "I also said, I will not drive them out...but they shall be as thorns in your sides, and their gods shall be a snare." This is a covenant curse responding to covenant breach.'),
('Judges', 2, 'adults', 4, 'Judges 2:17 says Israel would not hearken unto their judges but went a whoring after other gods. What does this marital metaphor for idolatry convey?', 'Israel''s covenant with God was like a marriage, and idolatry was adultery against that covenant', 'The judges themselves were immoral men', 'Canaanite fertility rites involved literal immorality', 'The metaphor only describes the women of Israel', 'a', 'Judges 2:17 — "Yet they would not hearken unto their judges, but they went a whoring after other gods." The marriage covenant metaphor (used throughout the prophets) frames idolatry as covenant unfaithfulness.'),
('Judges', 2, 'adults', 5, 'What does Judges 2:18 reveal about the emotional response of the LORD toward His people''s suffering under oppressors?', 'It repented the LORD because of their groanings — He was moved with compassion', 'The LORD remained unmoved until Israel repented fully', 'The LORD delegated His grief to the angels', 'The LORD punished the oppressors without regarding Israel''s suffering', 'a', 'Judges 2:18 — "It repented the LORD because of their groanings by reason of them that oppressed them and vexed them."'),
('Judges', 2, 'adults', 6, 'Where was Joshua buried, and what is the significance of that location?', 'In the border of his inheritance in Timnath-heres in mount Ephraim, tying his burial to the land he helped conquer', 'In Shiloh beside the tabernacle, near the ark', 'In Hebron alongside Caleb, his faithful companion', 'In the valley of Jordan where Israel crossed', 'a', 'Judges 2:9 — "They buried him in the border of his inheritance in Timnath-heres, in the mount of Ephraim." His burial in the promised land sealed his identity as its conqueror.'),
('Judges', 2, 'adults', 7, 'According to Judges 2:14, what two specific consequences did God''s anger bring upon Israel?', 'He delivered them into the hands of spoilers and sold them into the hands of their enemies', 'He sent famine and plague upon the land', 'He withdrew the ark and removed the priesthood', 'He caused division between the tribes and civil war', 'a', 'Judges 2:14 — "The anger of the LORD was hot against Israel, and he delivered them into the hands of spoilers that spoiled them, and he sold them into the hands of their enemies round about."'),
('Judges', 2, 'adults', 8, 'What nations does Judges 2:23 say the LORD left to remain in Canaan, and what dual purpose did this serve?', 'He left them to test Israel and because He would not drive them out speedily, leaving them in the hand of Joshua — a bridge to chapter 3''s list', 'He left only the Philistines because no judge could defeat them', 'He left the Jebusites and Canaanites as permanent residents', 'He left the Amorites to teach Israel chariot warfare', 'a', 'Judges 2:23 — "Therefore the LORD left those nations, without driving them out hastily; neither delivered he them into the hand of Joshua." This bridges to the testing purpose elaborated in Judges 3:1-4.');

-- ═══ Judges Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 3, 'kids', 1, 'Who was the first judge God raised up to save Israel?', 'Othniel', 'Ehud', 'Gideon', 'Shamgar', 'a', 'Judges 3:9 — "The LORD raised up a deliverer to the children of Israel, who delivered them, even Othniel the son of Kenaz."'),
('Judges', 3, 'kids', 2, 'What special characteristic did Ehud the judge have?', 'He was very tall', 'He was left-handed', 'He could run very fast', 'He had very long hair', 'a', 'Judges 3:15 — "The LORD raised them up a deliverer, Ehud the son of Gera, a Benjamite, a man lefthanded."'),
('Judges', 3, 'kids', 3, 'What did Shamgar use to kill six hundred Philistines?', 'A sword', 'An ox goad', 'A sling and stones', 'A bow and arrows', 'a', 'Judges 3:31 — "Shamgar the son of Anath...slew of the Philistines six hundred men with an ox goad."'),
-- Teens
('Judges', 3, 'teens', 1, 'Who was Othniel, and how was he related to Caleb?', 'He was Caleb''s younger brother''s son — his nephew', 'He was Caleb''s eldest son', 'He was Caleb''s son-in-law only, with no blood relation', 'He was from the tribe of Judah but unrelated to Caleb', 'a', 'Judges 3:9 — "Othniel the son of Kenaz, Caleb''s younger brother." He was Caleb''s nephew and also Caleb''s son-in-law (Judges 1:13).'),
('Judges', 3, 'teens', 2, 'Which king oppressed Israel for eight years before Othniel delivered them?', 'Chushan-rishathaim king of Mesopotamia', 'Eglon king of Moab', 'Jabin king of Canaan', 'Cushan king of Edom', 'a', 'Judges 3:8 — "The LORD sold them into the hand of Chushan-rishathaim king of Mesopotamia: and the children of Israel served Chushan-rishathaim eight years."'),
('Judges', 3, 'teens', 3, 'How long did Ehud serve as judge, indicated by the land having rest?', 'Eighty years', 'Forty years', 'Twenty years', 'Sixty years', 'a', 'Judges 3:30 — "So Moab was subdued that day under the hand of Israel. And the land had rest fourscore years." Eighty years of peace followed Ehud''s deliverance.'),
('Judges', 3, 'teens', 4, 'What did Ehud say to King Eglon to get a private audience with him?', 'I have a secret errand unto thee, O king', 'I bring tribute from Israel to honour thee', 'I have a message from God for thee alone', 'I must speak to thee about peace between our peoples', 'a', 'Judges 3:19 — "Ehud said, I have a secret errand unto thee, O king: who said, Keep silence. And all that stood by him went out from him."'),
('Judges', 3, 'teens', 5, 'What detail about Ehud''s dagger is given, and how did it aid his escape?', 'It was eighteen inches long and hidden on his right thigh; Eglon''s fat closed over it so Ehud did not pull it out', 'It was a double-edged sword hidden under his robe', 'It was a bronze knife concealed in his sandal', 'It was strapped to his back beneath his garment', 'a', 'Judges 3:16,22 — The dagger was a cubit long, strapped on his right thigh. "The haft also went in after the blade; and the fat closed upon the blade...he could not draw the dagger out."'),
-- Adults
('Judges', 3, 'adults', 1, 'What is the purpose stated in Judges 3:2 for leaving nations in Canaan to test Israel?', 'That the generations of Israel that had not known the wars of Canaan might be taught war', 'That Israel would remain humble before the LORD', 'That the land would not be desolate without inhabitants', 'That Israel''s population would not grow too quickly', 'a', 'Judges 3:2 — "Only that the generations of the children of Israel might know, to teach them war, at the least such as before knew nothing thereof."'),
('Judges', 3, 'adults', 2, 'What five nations are specifically listed in Judges 3:3 as the ones left to test Israel?', 'Five lords of the Philistines, Canaanites, Sidonians, Hivites of Lebanon, and inhabitants of mount Baal-hermon', 'Philistines, Moabites, Ammonites, Amorites, and Jebusites', 'Hittites, Perizzites, Hivites, Canaanites, and Girgashites', 'Midianites, Amalekites, Edomites, Moabites, and Egyptians', 'a', 'Judges 3:3 — "Five lords of the Philistines, and all the Canaanites, and the Sidonians, and the Hivites that dwelt in mount Lebanon, from mount Baal-hermon unto the entering in of Hamath."'),
('Judges', 3, 'adults', 3, 'What is the significance of Eglon''s obesity in the Ehud narrative?', 'The fat closing over the dagger explains why the weapon was not retrieved and prevented discovery; it also satirises Moabite excess', 'It fulfilled a prophecy about fat kings being overthrown', 'It symbolised the wealth of Moab that Israel desired', 'It showed that Eglon was a man of great feasting who lacked military alertness', 'a', 'Judges 3:22 — "The fat closed upon the blade...he could not draw the dagger out." The detail is both practical (hiding the crime) and satirical (Eglon''s bloated oppression literally consuming itself).'),
('Judges', 3, 'adults', 4, 'How did Ehud escape after killing Eglon, and how did Eglon''s servants delay the discovery of his body?', 'Ehud locked the parlour doors from outside; servants assumed Eglon was covering his feet and waited until they were ashamed', 'Ehud disguised himself as a servant and walked out; servants found the body after midnight', 'Ehud escaped through a window and the servants were forbidden to enter the chamber', 'Ehud hid in the garden and left after dark', 'a', 'Judges 3:23-25 — "Ehud went forth through the porch...and locked the doors...His servants...said, Surely he covereth his feet in his summer chamber...they were ashamed: and behold their lord was fallen down dead."'),
('Judges', 3, 'adults', 5, 'What rallying device did Ehud use to gather Israel''s troops, and what was the geographic strategy for the battle?', 'He blew a trumpet in mount Ephraim and led Israel to seize the fords of Jordan, cutting off Moab''s retreat', 'He sent messengers to all tribes and attacked at night from the hills', 'He lit signal fires on the heights of Benjamin', 'He gathered the elders and marched straight to the Jordan plain', 'a', 'Judges 3:27-28 — "He blew a trumpet in the mountain of Ephraim...Follow after me: for the LORD hath delivered your enemies the Moabites into your hand. And they went down after him, and took the fords of Jordan toward Moab."'),
('Judges', 3, 'adults', 6, 'How many Moabites were killed in the battle following Ehud''s assassination of Eglon?', 'About ten thousand men — all lusty and strong, no man escaped', 'Five thousand soldiers at the Jordan fords', 'Twenty thousand over three days of battle', 'An uncounted multitude, described as the whole army of Moab', 'a', 'Judges 3:29 — "They slew of Moab at that time about ten thousand men, all lusty, and all men of valour; and there escaped not a man."'),
('Judges', 3, 'adults', 7, 'What does the name Chushan-rishathaim mean, and why might the author have included its meaning?', 'Cushan of double wickedness — a theological epithet emphasising his evil character and divine justice in his defeat', 'Cushan the mighty king — celebrating his temporary power', 'Cushan of the two rivers — describing his Mesopotamian homeland', 'Cushan the oppressor — simply a title of his role over Israel', 'a', 'The name Chushan-rishathaim is widely understood as meaning "Cushan of double wickedness," serving as an ironic characterisation that frames his oppression as deserving the divine response described in Judges 3:10.'),
('Judges', 3, 'adults', 8, 'How does Othniel''s judgeship in Judges 3:7-11 function as the paradigmatic or model example of the Deuteronomic cycle?', 'It presents all four stages in their clearest form — sin, servitude, supplication, salvation — without complicating details, establishing the template for all subsequent judge narratives', 'It is the longest judge narrative and therefore sets the standard by length', 'It is unique because the Spirit of God is mentioned, making it more important than the others', 'It is the only narrative where the judge is from the tribe of Judah, setting the royal template', 'a', 'Judges 3:7-11 is the shortest and most formulaic judge narrative: sin (v.7), anger and servitude (v.8), cry and raising of deliverer (v.9), Spirit empowerment (v.10), conquest and rest (v.11) — textbook Deuteronomic cycle.');

-- ═══ Judges Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 4, 'kids', 1, 'Who was the prophetess that judged Israel in Judges 4?', 'Deborah', 'Miriam', 'Hannah', 'Ruth', 'a', 'Judges 4:4 — "Deborah, a prophetess, the wife of Lapidoth, she judged Israel at that time."'),
('Judges', 4, 'kids', 2, 'Who was the commander of the enemy army that Deborah and Barak fought against?', 'Sisera', 'Eglon', 'Goliath', 'Jabin', 'a', 'Judges 4:2 — "The captain of whose host was Sisera, which dwelt in Harosheth of the Gentiles."'),
('Judges', 4, 'kids', 3, 'Who killed Sisera by driving a tent peg through his head?', 'Jael the wife of Heber', 'Deborah the prophetess', 'Barak the soldier', 'A woman from the city walls', 'a', 'Judges 4:21 — "Jael...took a nail of the tent, and took an hammer in her hand, and went softly unto him, and smote the nail into his temples."'),
-- Teens
('Judges', 4, 'teens', 1, 'Under which king did Israel suffer oppression when Deborah judged, and how many years did it last?', 'Jabin king of Canaan, for twenty years', 'Eglon king of Moab, for eighteen years', 'Chushan-rishathaim, for eight years', 'The Midianites, for seven years', 'a', 'Judges 4:2-3 — "The LORD sold them into the hand of Jabin king of Canaan...And the children of Israel cried unto the LORD: for he had nine hundred chariots of iron; and twenty years he mightily oppressed the children of Israel."'),
('Judges', 4, 'teens', 2, 'What condition did Barak place on leading the army against Sisera?', 'If Deborah would go with him, he would go; but if not, he would not go', 'If God would speak from heaven he would obey', 'If ten thousand men volunteered he would lead them', 'If Deborah would fast for seven days he would trust the victory', 'a', 'Judges 4:8 — "Barak said unto her, If thou wilt go with me, then I will go: but if thou wilt not go with me, then I will not go."'),
('Judges', 4, 'teens', 3, 'What consequence did Deborah prophesy for Barak''s hesitation?', 'The honour of the victory would go to a woman, not to him', 'He would lose his position as commander', 'He would be captured in battle', 'He would be struck with fear at the critical moment', 'a', 'Judges 4:9 — "Deborah said...the journey that thou takest shall not be for thine honour; for the LORD shall sell Sisera into the hand of a woman."'),
('Judges', 4, 'teens', 4, 'How did the LORD rout Sisera''s army according to Judges 4:15?', 'The LORD discomfited Sisera and all his chariots and all his host with the edge of the sword', 'The LORD sent rain to flood the plain', 'The LORD sent fire from heaven upon the chariots', 'The LORD caused Sisera''s soldiers to fight one another', 'a', 'Judges 4:15 — "The LORD discomfited Sisera, and all his chariots, and all his host, with the edge of the sword before Barak."'),
('Judges', 4, 'teens', 5, 'How did Jael lure Sisera into her tent before killing him?', 'She invited him in, gave him milk to drink, covered him, and told him not to fear', 'She pretended to be wounded and asked for his help', 'She offered him food and told him she had seen his enemies pass', 'She appeared to be a servant at the city gate and guided him to a hiding place', 'a', 'Judges 4:18-19 — "Jael went out to meet Sisera, and said...Turn in, my lord...And she covered him...And he said...Give me, I pray thee, a little water to drink...And she opened a bottle of milk, and gave him drink, and covered him."'),
-- Adults
('Judges', 4, 'adults', 1, 'What does the detail that Deborah judged Israel "under the palm tree of Deborah between Ramah and Beth-el" reveal about her judicial function?', 'She held a fixed, public location where Israelites came to her for judgment, indicating a formal judicial role distinct from the military deliverers', 'She was a nature worshipper who held court outdoors', 'She was too poor to have a proper building', 'The palm tree was a sacred site associated with the tabernacle', 'a', 'Judges 4:5 — "She dwelt under the palm tree of Deborah between Ramah and Beth-el in mount Ephraim: and the children of Israel came up to her for judgment." This establishes her as a civil judge, not merely a military leader.'),
('Judges', 4, 'adults', 2, 'What is the theological irony in Sisera fleeing on foot to Jael''s tent, given the earlier emphasis on his nine hundred iron chariots?', 'The very military might Israel feared most (iron chariots) proved useless, and their commander fled on foot, showing that the LORD''s power trumps all human military advantage', 'It shows that Sisera had planned the escape route in advance', 'It demonstrates that iron chariots could not cross certain terrain', 'It fulfilled a specific prophecy about enemy generals fleeing', 'a', 'Judges 4:3 established nine hundred iron chariots as the source of Israel''s oppression; Judges 4:15,17 show Sisera abandoning them and fleeing on foot, inverting Israel''s greatest fear.'),
('Judges', 4, 'adults', 3, 'What covenant context explains Jael''s act of killing Sisera, despite her husband Heber''s peace with Jabin?', 'Heber had separated from the Kenites and made his own peace; Jael acted on loyalty to Israel — whose God she apparently honoured — overriding her husband''s political alliance', 'Jael was under a vow to destroy all enemies of God''s people regardless of her husband''s decisions', 'Jael killed Sisera because he had personally wronged her family', 'The text does not provide sufficient context to evaluate her motive', 'a', 'Judges 4:11,17 — Heber the Kenite had separated from Moses'' father-in-law''s clan and made peace with Jabin. Jael''s act defied that alliance, and Judges 5:24 celebrates her as "blessed above women," indicating the narrator views her as acting in fidelity to Israel''s God.'),
('Judges', 4, 'adults', 4, 'What does the phrase "the LORD discomfited Sisera" (Judges 4:15) indicate about who receives credit for the victory?', 'Divine agency is the ultimate cause of the military rout, with human actors (Barak, Jael) as instruments, fulfilling Deborah''s prophetic assurance in Judges 4:7', 'Barak''s superior strategy was vindicated by God''s blessing', 'The phrase is a formulaic ending with no theological weight', 'It means God caused a storm but the soldiers did all the fighting', 'a', 'Judges 4:7 Deborah declared "I will deliver him into thine hand"; Judges 4:15 confirms "the LORD discomfited Sisera." The divine passive frames the whole narrative as God''s victory, not Israel''s alone.'),
('Judges', 4, 'adults', 5, 'How does Barak''s inclusion in the Hebrews 11 faith hall of fame (Hebrews 11:32) reframe the judgment implied by Deborah''s prophecy in Judges 4:9?', 'His faith was genuine even if imperfect; his hesitation did not disqualify him but the honour of the killing blow went to Jael as prophesied', 'Barak replaced Deborah as the primary hero in later tradition', 'The New Testament passage contradicts the Old Testament account', 'Barak''s inclusion suggests the prophecy was not fulfilled', 'a', 'Hebrews 11:32 lists Barak among faith heroes. This suggests that his condition in Judges 4:8 was an expression of faith needing Deborah''s prophetic presence, not cowardice — yet God''s word through Deborah (Judges 4:9) still stood.'),
('Judges', 4, 'adults', 6, 'What geographic and tactical significance did the river Kishon hold in the battle?', 'According to Judges 5:21 it swept away Sisera''s troops, likely flooding and immobilising the iron chariots that were his chief military asset', 'It served as Israel''s defensive barrier protecting Barak''s camp', 'It was a sacred river associated with divine appearances', 'It divided the Canaanite forces into two groups', 'a', 'Judges 4:7 directs the battle to "the river Kishon"; Judges 5:21 — "The river of Kishon swept them away." The flooding Kishon likely neutralised Sisera''s iron chariots, transforming his advantage into a liability.'),
('Judges', 4, 'adults', 7, 'The clan of Heber the Kenite descended from Moses'' father-in-law. What does the mention of Heber''s separation in Judges 4:11 foreshadow within the chapter?', 'It explains why Sisera would consider Jael''s tent a safe neutral refuge — setting up the dramatic irony of his death there', 'It introduces a sub-plot about Kenite politics', 'It explains why Jael had the skills to use a tent peg as a weapon', 'It provides a genealogical link between Deborah and Jael', 'a', 'Judges 4:11 establishes Heber''s separate peace with Jabin, which in Judges 4:17 Sisera relies upon for safety. The narrator''s advance notice creates dramatic irony: the supposed safe house becomes his tomb.'),
('Judges', 4, 'adults', 8, 'How does chapter 4 illustrate the theme of reversal of expectations that runs through the book of Judges?', 'A woman judges Israel, a woman is given the military honour, and the feared iron chariot commander dies ignominiously by a tent peg in a woman''s hand', 'A Canaanite king becomes a worshipper of the LORD', 'The smallest tribe leads the greatest military victory', 'An old man defeats a young warrior in single combat', 'a', 'Judges 4 systematically inverts military and social expectations: Deborah (female) judges, Barak (military leader) defers, Sisera (iron chariot general) flees on foot, and Jael (homemaker) executes the final blow with domestic tools (Judges 4:4, 8, 17, 21).');

-- ═══ Judges Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 5, 'kids', 1, 'Who sang a song of praise after Israel defeated Sisera?', 'Deborah and Barak', 'Miriam and Moses', 'David and Jonathan', 'Hannah and Eli', 'a', 'Judges 5:1 — "Then sang Deborah and Barak the son of Abinoam on that day."'),
('Judges', 5, 'kids', 2, 'What does the Song of Deborah say the stars did in the battle?', 'They fought from their courses against Sisera', 'They fell from heaven upon the enemy', 'They guided Israel through the night', 'They shone so brightly the enemy was blinded', 'a', 'Judges 5:20 — "They fought from heaven; the stars in their courses fought against Sisera."'),
('Judges', 5, 'kids', 3, 'What city was cursed by the angel of the LORD in the Song of Deborah?', 'Meroz', 'Jericho', 'Beth-shan', 'Hazor', 'a', 'Judges 5:23 — "Curse ye Meroz, said the angel of the LORD, curse ye bitterly the inhabitants thereof; because they came not to the help of the LORD."'),
-- Teens
('Judges', 5, 'teens', 1, 'How does the Song of Deborah describe the state of the roads and villages before Israel''s deliverance?', 'The highways were unoccupied and the villages ceased until Deborah arose', 'The roads were filled with enemies and the villages burned', 'The paths were blocked by iron chariots for forty years', 'The villages paid tribute and the roads were patrolled by Canaanites', 'a', 'Judges 5:6-7 — "In the days of Shamgar...the highways were unoccupied, and the travellers walked through byways...The villages ceased in Israel, until that I Deborah arose."'),
('Judges', 5, 'teens', 2, 'Which tribes are praised in the Song of Deborah for willingly offering themselves to battle?', 'Ephraim, Benjamin, Machir, Zebulun, Issachar, and Naphtali', 'Judah, Simeon, Dan, and Reuben', 'Gad, Asher, and Levi', 'Manasseh, Joseph, and Benjamin', 'a', 'Judges 5:14-15,18 — Ephraim, Benjamin, Machir, Zebulun, Issachar, and Naphtali are praised for joining the battle.'),
('Judges', 5, 'teens', 3, 'Which tribes are rebuked in the Song of Deborah for not coming to help?', 'Reuben, Gilead, Dan, and Asher', 'Judah, Levi, and Simeon', 'Gad, Manasseh, and Ephraim', 'Benjamin and Issachar', 'a', 'Judges 5:15-17 — "In the divisions of Reuben there were great searchings of heart...Gilead abode beyond Jordan: and why did Dan remain in ships? Asher continued on the sea shore."'),
('Judges', 5, 'teens', 4, 'How does the song describe the death blow Jael gave to Sisera?', 'She smote off his head, she wounded and struck him down between her feet he bowed and fell', 'She drove the peg through his neck as he slept on his side', 'She struck him with the hammer as he stood drinking', 'She stabbed him with his own sword as he lay sleeping', 'a', 'Judges 5:26-27 — "She put her hand to the nail...and smote Sisera, she smote off his head...At her feet he bowed, he fell: where he bowed, there he fell down dead."'),
('Judges', 5, 'teens', 5, 'What was Sisera''s mother doing as the song ends, and what is the poignant irony?', 'She was watching through the window for his return, expecting plunder — unaware he was dead', 'She was celebrating victory with the other women of Canaan', 'She was already mourning, having dreamed of his death', 'She was sending a messenger to ask about the delay in battle', 'a', 'Judges 5:28-30 — "The mother of Sisera looked out at a window...Why is his chariot so long in coming?...Have they not sped? have they not divided the prey?" The irony is that she anticipates his triumph while he lies dead.'),
-- Adults
('Judges', 5, 'adults', 1, 'What is the literary genre and approximate date of the Song of Deborah, and why is it significant for biblical scholarship?', 'It is archaic Hebrew victory poetry, widely dated to the 12th century BC, making it among the oldest pieces of biblical literature and a primary historical source for the period of the judges', 'It is a late editorial composition inserted to interpret the prose narrative', 'It is a liturgical hymn composed for temple worship during the monarchy', 'It is a translation from Canaanite victory hymns adapted for Israelite use', 'a', 'The Song of Deborah (Judges 5) is widely regarded by scholars as archaic Hebrew poetry of high antiquity, its linguistic features (archaic pronoun forms, unusual vocabulary) suggesting composition close to the events of the 12th century BC.'),
('Judges', 5, 'adults', 2, 'The Song of Deborah in Judges 5:4-5 describes the LORD coming from Seir and Edom with cosmic effects. What theological tradition does this invoke?', 'The theophanic warrior tradition — the LORD marches from his southern holy mountain bringing storm, earthquake, and victory for His people', 'A reference to Edom''s conversion to Israelite religion', 'A geographical explanation of how Deborah''s forces moved', 'A polemic against Edomite deities', 'a', 'Judges 5:4-5 — "LORD, when thou wentest out of Seir...the earth trembled...the mountains melted." This is the theophanic warrior pattern seen also in Deut. 33:2, Hab. 3:3, and Psalm 68 — God marching from Sinai/Edom to fight for Israel.'),
('Judges', 5, 'adults', 3, 'What does the curse on Meroz (Judges 5:23) reveal about the theology of holy war in Israel?', 'Failure to join the LORD''s battle when called is itself a covenant violation worthy of curse, not merely civic cowardice', 'Meroz was a Canaanite city allied with Sisera', 'The curse was later lifted when Meroz joined subsequent battles', 'Only the tribe of Levi was exempt from military service in holy war', 'a', 'Judges 5:23 — "Curse ye Meroz...because they came not to the help of the LORD, to the help of the LORD against the mighty." The curse implies that participation in holy war was a covenant obligation; non-participation was apostasy.'),
('Judges', 5, 'adults', 4, 'How does Judges 5:31 function as a doxological conclusion to the Song, and what petition does it contain?', 'It prays that all God''s enemies perish as Sisera did, while those who love Him shine as the sun in its strength — framing the victory as a paradigm for eschatological hope', 'It summarises the casualties of the battle and calls for mourning', 'It warns Israel not to repeat their sins lest they be oppressed again', 'It records the number of years of peace that followed', 'a', 'Judges 5:31 — "So let all thine enemies perish, O LORD: but let them that love him be as the sun when he goeth forth in his might." This doxological close transforms a historical victory into an eschatological prayer.'),
('Judges', 5, 'adults', 5, 'What does the Song''s vivid portrayal of Sisera''s mother''s futile waiting (Judges 5:28-30) accomplish literarily and theologically?', 'It humanises the enemy and shows the tragedy of war while simultaneously celebrating God''s justice — the very plunder she expects never comes because her son was the one judged', 'It creates sympathy for Canaanite women as victims of Israelite aggression', 'It is an editorial addition to balance the Israelite celebration with Canaanite grief', 'It fulfils Deborah''s prophecy that the honour would go to a woman', 'a', 'Judges 5:28-30 gives Sisera''s mother a voice anticipating her son''s return with plunder. The reader knows Sisera is dead. The passage creates tragic irony and implicitly addresses the plunder theme that runs through Judges, showing the oppressor''s plan (v.30, "a damsel or two; to Sisera a prey") reversed.'),
('Judges', 5, 'adults', 6, 'What does the phrase "the stars in their courses fought against Sisera" (Judges 5:20) indicate about the song''s cosmological theology?', 'The entire created order — heavenly bodies and the Kishon river — participated in Israel''s deliverance, presenting the battle as a cosmic event orchestrated by the LORD of hosts', 'The battle literally involved a meteor shower', 'It is a metaphor for Israel''s tribal confederacy rallying from across the region', 'It reflects Canaanite astral theology that the poet ironically co-opts', 'a', 'Judges 5:20-21 — "The stars in their courses fought against Sisera. The river of Kishon swept them away." Both heavenly (stars) and earthly (river) elements are mobilised, presenting the LORD as commander of the whole cosmos (a "hosts" theology), not merely a tribal deity.'),
('Judges', 5, 'adults', 7, 'In the Song, Deborah calls herself "a mother in Israel" (Judges 5:7). What does this title claim about her role?', 'She functioned as a nurturing, protective authority figure for the whole nation — a leadership role that transcended gender conventions of the ancient Near East', 'She was literally the oldest woman in Israel at the time', 'She was the mother of Barak the commander', 'She adopted orphans left by the Canaanite wars', 'a', 'Judges 5:7 — "Until that I Deborah arose, that I arose a mother in Israel." "Mother in Israel" is a title of respected national authority (cf. 2 Sam. 20:19 for a city), here applied to Deborah as Israel''s protector and deliverer.'),
('Judges', 5, 'adults', 8, 'How does the Song of Deborah''s treatment of the tribes who did not come (Reuben, Dan, Asher, Gilead) reflect the political reality of the tribal confederacy in the period of the judges?', 'The song reveals a loose, voluntary confederacy where tribes pursued their own economic interests — Reuben with his flocks, Dan with his ships, Asher with his trade — rather than a unified national army under central command', 'It shows that only southern tribes were ever loyal to the covenant', 'It reflects punishment for these tribes'' earlier apostasy during Othniel''s time', 'It indicates these tribes were geographically too distant to participate', 'a', 'Judges 5:15-17 — Reuben''s "great searchings of heart," Dan remaining "in ships," Asher on "the sea shore." The tribal interests portrayed (pastoralism, maritime trade) show Israel as a confederacy of economically diverse groups whose unity was voluntary and fragile.');

-- ═══ Judges Chapter 6 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 6, 'kids', 1, 'Who appeared to Gideon under the oak tree in Ophrah?', 'An angel of the LORD', 'A prophet named Samuel', 'Moses in a dream', 'The high priest', 'a', 'Judges 6:11-12 — "There came an angel of the LORD, and sat under an oak which was in Ophrah...And the LORD looked upon him, and said, The LORD is with thee, thou mighty man of valour."'),
('Judges', 6, 'kids', 2, 'What were the Midianites doing to Israel that made them very poor?', 'Destroying their crops and taking their animals every harvest', 'Burning their houses and cities', 'Taking their children as slaves', 'Blocking their roads and stopping trade', 'a', 'Judges 6:4-5 — "They...destroyed the increase of the earth...and left no sustenance for Israel, neither sheep, nor ox, nor ass."'),
('Judges', 6, 'kids', 3, 'What test did Gideon use to confirm that God would save Israel through him?', 'The fleece test — dew on fleece and dry ground, then dry fleece and wet ground', 'He threw a stone and asked God to make it float', 'He prayed for fire from heaven on an altar', 'He asked the sun to stand still for one hour', 'a', 'Judges 6:36-40 — Gideon asked God to put dew only on a fleece (v.37-38), then to make only the ground wet and the fleece dry (v.39-40). Both signs were given.'),
-- Teens
('Judges', 6, 'teens', 1, 'How long did the Midianite oppression last, and what caused God to send a prophet to rebuke Israel?', 'Seven years; Israel cried to the LORD because of Midian''s destruction', 'Twenty years; Israel stopped offering sacrifices', 'Forty years; Israel worshipped Baal openly', 'Twelve years; Israel paid tribute to Midian', 'a', 'Judges 6:1-2 — "The children of Israel did evil in the sight of the LORD: and the LORD delivered them into the hand of Midian seven years." Judges 6:6-8 — they cried to the LORD and He sent a prophet.'),
('Judges', 6, 'teens', 2, 'Where was Gideon threshing wheat when the angel of the LORD appeared to him, and why was this location significant?', 'In the winepress, to hide it from the Midianites', 'On the threshing floor on a hilltop to catch the wind', 'In the fields openly, unafraid of the enemy', 'In the city gate where many could witness', 'a', 'Judges 6:11 — "Gideon threshed wheat by the winepress, to hide it from the Midianites." Threshing in a winepress (a hollow, concealed space) shows the depth of Israel''s fear and oppression.'),
('Judges', 6, 'teens', 3, 'What was Gideon''s first act of obedience, and what did he risk by doing it?', 'He threw down his father''s altar to Baal and cut down the grove — risking his life since the townspeople wanted to kill him', 'He gathered an army of thirty-two thousand men', 'He offered a sacrifice at the tabernacle at Shiloh', 'He tore down Midianite shrines in the valley', 'a', 'Judges 6:25-30 — God commanded Gideon to throw down Baal''s altar. Judges 6:30 — "the men of the city said unto Joash, Bring out thy son, that he may die: because he hath cast down the altar of Baal."'),
('Judges', 6, 'teens', 4, 'What name was Gideon given after he destroyed Baal''s altar, and what does it mean?', 'Jerubbaal, meaning let Baal plead against him', 'Gideon the mighty, meaning warrior of God', 'Baal-breaker, meaning destroyer of idols', 'El-Gideon, meaning God is my strength', 'a', 'Judges 6:32 — "Therefore on that day he called him Jerubbaal, saying, Let Baal plead against him, because he hath thrown down his altar."'),
('Judges', 6, 'teens', 5, 'What was the sign that confirmed the angel of the LORD''s identity when Gideon offered a meal?', 'Fire rose out of the rock and consumed the offering, then the angel vanished', 'The angel ate the food and blessed Gideon with visible light', 'The offering floated up into the sky', 'The bread turned to stone as a permanent memorial', 'a', 'Judges 6:21 — "Then the angel of the LORD put forth the end of the staff...and there rose up fire out of the rock, and consumed the flesh and the unleavened cakes. Then the angel of the LORD departed out of his sight."'),
-- Adults
('Judges', 6, 'adults', 1, 'What is the theological problem Gideon raises with the prophet''s message, and how does it reflect a genuine crisis of faith?', 'Gideon contrasts the tradition of God''s past acts (Exodus miracles) with present abandonment, asking "where be all his miracles?" — a lament that God''s covenant faithfulness seems absent', 'He denies that the oppression is punishment for sin', 'He challenges the prophet''s authority to speak for God', 'He argues that Israel had been obedient and did not deserve punishment', 'a', 'Judges 6:13 — "Oh my Lord, if the LORD be with us, why then is all this befallen us? and where be all his miracles which our fathers told us of?" Gideon''s question is a theodicy challenge rooted in the Exodus tradition.'),
('Judges', 6, 'adults', 2, 'How does the divine response to Gideon''s objection "my family is poor in Manasseh, and I am the least in my father''s house" follow a recurring biblical pattern?', 'God chooses the weak and least significant to display His own strength — the pattern of Moses, David, and Paul''s "strength in weakness" theology', 'God confirms that military rank and family status are irrelevant to divine calling', 'God promises to make Gideon''s family the greatest in Manasseh', 'God corrects Gideon''s self-assessment and reveals his true lineage', 'a', 'Judges 6:15-16 — "I am the least...And the LORD said unto him, Surely I will be with thee." This "least" motif recurs: Moses (Exodus 3:11), Saul (1 Sam. 9:21), David (1 Sam. 16:11), and Paul (1 Cor. 1:27-28).'),
('Judges', 6, 'adults', 3, 'What is the theological significance of the name Gideon builds for the altar — Jehovah-shalom — in the context of the military crisis?', 'It declares "the LORD is peace" as an act of trust before battle, affirming that true peace comes only from God despite surrounding war and oppression', 'It was a peace offering to appease the local Baal deity', 'It memorialised the peace treaty Gideon''s father made with Midian', 'It fulfilled a vow Gideon made to build an altar if Israel prevailed', 'a', 'Judges 6:24 — "Then Gideon built an altar there unto the LORD, and called it Jehovah-shalom: unto this day it is yet in Ophrah." The name is a confession of trust in God as the source of peace amid the oppression.'),
('Judges', 6, 'adults', 4, 'What is the narrative function of Joash''s defense of Gideon in Judges 6:31, and what principle does he invoke?', 'Joash argues that if Baal is truly a god he can plead his own cause — a sarcastic challenge that exposes the impotence of idols and defends Gideon''s act', 'Joash feared the townspeople and so deflected blame from his son', 'Joash was secretly a believer in the LORD and saw an opportunity to testify', 'Joash invoked the tribal law that a father must defend his son''s deeds', 'a', 'Judges 6:31 — "Will ye plead for Baal? will ye save him? he that will plead for him, let him be put to death...if he be a god, let him plead for himself." Joash''s argument mirrors Elijah''s challenge to Baal''s prophets (1 Kings 18).'),
('Judges', 6, 'adults', 5, 'What does Judges 6:34 say came upon Gideon when he blew the trumpet to gather Israel, and what is the significance of this?', 'The Spirit of the LORD came upon Gideon — divine empowerment for leadership, the same pattern seen in the judges Othniel and later Samson', 'Gideon was filled with great courage of his own making', 'An angel accompanied him visibly as he marched', 'A great army appeared miraculously around Gideon', 'a', 'Judges 6:34 — "But the Spirit of the LORD came upon Gideon, and he blew a trumpet." This Spirit-empowerment formula appears in Judges 3:10 (Othniel), 11:29 (Jephthah), 13:25, 14:6,19 (Samson), marking the judges as Spirit-endowed deliverers.'),
('Judges', 6, 'adults', 6, 'Gideon''s fleece test in Judges 6:36-40 involves two requests. What does the progression from first test to second test reveal about the nature of Gideon''s faith?', 'His faith is growing but still tentative; the reversal of the second test (harder to achieve naturally) shows he genuinely seeks divine confirmation rather than natural coincidence', 'Gideon doubted God more after the first sign was given', 'The two tests represent two different covenants God was establishing', 'The second test was demanded by the elders of Israel, not by Gideon alone', 'a', 'Judges 6:39 — "Let not thine anger be hot against me...let me prove, I pray thee, but this once." The reversal (dry fleece, wet ground) makes a natural dew explanation impossible, showing Gideon seeking incontrovertible divine confirmation.'),
('Judges', 6, 'adults', 7, 'What does the LORD''s instruction in Judges 6:25-26 to use the second bullock of seven years old reveal symbolically?', 'The seven-year-old bullock matches the seven years of Midianite oppression, symbolising the reversal of that oppression beginning with the destruction of Baal worship at its source', 'The second bull was the largest available and thus the most honourable sacrifice', 'Seven years was the legal minimum age for sacrifice in Levitical law', 'The bull was Baal''s sacred animal and its sacrifice directly challenged Baal''s authority', 'a', 'Judges 6:25 — "Take thy father''s young bullock, even the second bullock of seven years old, and throw down the altar of Baal." The seven-year parallel to the period of oppression (Judges 6:1) invites a symbolic reading: the sacrifice begins to reverse the seven years of judgment.'),
('Judges', 6, 'adults', 8, 'What does the sending of a prophet (Judges 6:8-10) before the raising of a deliverer reveal about God''s pedagogical method in the book of Judges?', 'God first diagnoses the spiritual root of Israel''s suffering (covenant violation) through prophetic word before providing military deliverance — addressing cause before symptom', 'God always sent two witnesses before acting, following the Mosaic legal requirement', 'The prophet was sent to identify which individual would become the next judge', 'God used the prophet to announce the end of the Mosaic covenant', 'a', 'Judges 6:8-10 — The unnamed prophet rehearses the Exodus and covenant, then diagnoses: "ye have not obeyed my voice." God''s pattern in Judges: prophetic diagnosis precedes deliverance, so Israel understands WHY they suffered, not merely that they are rescued.');

-- ═══ Judges Chapter 7 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 7, 'kids', 1, 'How many men did Gideon start with, and how many did God reduce the army to?', 'Started with 32,000 and reduced to 300', 'Started with 10,000 and reduced to 100', 'Started with 50,000 and reduced to 500', 'Started with 5,000 and reduced to 300', 'a', 'Judges 7:3,7 — Thirty-two thousand men began; the fearful left (22,000), then the water test reduced the army to 300 men.'),
('Judges', 7, 'kids', 2, 'What three things did Gideon''s 300 men carry into battle?', 'Trumpets, empty pitchers, and lamps inside the pitchers', 'Swords, shields, and torches', 'Trumpets, bows, and war clubs', 'Spears, banners, and fire pots', 'a', 'Judges 7:16 — "He divided the three hundred men into three companies, and he put a trumpet in every man''s hand, with empty pitchers, and lamps within the pitchers."'),
('Judges', 7, 'kids', 3, 'What did Gideon''s men shout when they broke their pitchers and blew their trumpets?', 'The sword of the LORD and of Gideon', 'Victory belongs to the LORD', 'Israel shall prevail this day', 'The LORD our God is one', 'a', 'Judges 7:20 — "And they cried, The sword of the LORD, and of Gideon."'),
-- Teens
('Judges', 7, 'teens', 1, 'Why did God reduce Gideon''s army, according to Judges 7:2?', 'Lest Israel vaunt themselves against God, saying their own hand saved them', 'So that the battle would be won quickly without a long siege', 'To test Gideon''s obedience and courage', 'Because the Midianite army was small and did not need many soldiers', 'a', 'Judges 7:2 — "The LORD said unto Gideon, The people that are with thee are too many for me to give the Midianites into their hands, lest Israel vaunt themselves against me, saying, Mine own hand hath saved me."'),
('Judges', 7, 'teens', 2, 'How were the 300 men who remained chosen, and what was the selection criterion at the water?', 'Those who lapped water with their tongue like a dog were kept; those who bowed on their knees to drink were sent away', 'Those who were not afraid were kept; the fearful were dismissed', 'Those from the tribe of Manasseh were kept; others were sent home', 'The tallest and strongest three hundred were selected', 'a', 'Judges 7:5-6 — "Everyone that lappeth of the water with his tongue, as a dog lappeth, him shalt thou set by himself...And the number of them that lapped, putting their hand to their mouth, were three hundred men."'),
('Judges', 7, 'teens', 3, 'What was the dream that a Midianite soldier told his companion, and how was it interpreted?', 'A barley cake tumbled into the Midianite camp and overturned a tent — interpreted as the sword of Gideon delivering Midian into his hand', 'A great fire swept from the hills and burned the Midianite tents — meaning God would send fire from heaven', 'A mighty warrior appeared and threw the camp into the sea — meaning Israel would pursue them to the Jordan', 'A trumpet sounded three times and all soldiers fell asleep — meaning God would cause them to sleep through the attack', 'a', 'Judges 7:13-14 — "A cake of barley bread tumbled into the host of Midian...This is nothing else save the sword of Gideon the son of Joash, a man of Israel: for into his hand hath God delivered Midian."'),
('Judges', 7, 'teens', 4, 'Into how many companies did Gideon divide his 300 men, and when did they blow the trumpets and break the pitchers?', 'Three companies; at the beginning of the middle watch, just after the changing of the guard', 'Two companies; at midnight when the enemy was deepest asleep', 'Four companies; at dawn when the enemy first awoke', 'Three companies; at sunset as darkness fell', 'a', 'Judges 7:16,19 — "He divided the three hundred men into three companies...So Gideon, and the hundred men that were with him, came unto the outside of the camp in the beginning of the middle watch...and they blew the trumpets, and brake the pitchers."'),
('Judges', 7, 'teens', 5, 'What happened among the Midianite soldiers when Gideon''s men blew the trumpets?', 'The LORD set every man''s sword against his fellow throughout all the host and they fled', 'The Midianites surrendered immediately upon hearing the trumpets', 'Half the Midianites fled to Egypt and the rest were captured', 'The Midianites formed ranks but were struck blind by the lamps', 'a', 'Judges 7:22 — "And the LORD set every man''s sword against his fellow, even throughout all the host: and the host fled."'),
-- Adults
('Judges', 7, 'adults', 1, 'What is the theological principle demonstrated by the successive reduction of Gideon''s army from 32,000 to 10,000 to 300?', 'The extreme reduction ensures that the victory cannot be attributed to human military strength, forcing Israel to credit God alone — a central Deuteronomic principle', 'God was testing which soldiers were the most disciplined for unconventional warfare', 'God preferred small armies because they were easier to supply', 'The reduction fulfilled an ancient prophecy about Manasseh fighting with a handful', 'a', 'Judges 7:2 states the purpose explicitly: "lest Israel vaunt themselves against me." The reduction makes the human impossibility of victory undeniable, so divine credit is inescapable.'),
('Judges', 7, 'adults', 2, 'What is the most plausible tactical explanation for the water-lapping test, and how does it serve the narrative?', 'The lappers remained visually alert (heads up, drinking from cupped hands) while kneeling drinkers were temporarily vulnerable — selecting men with battlefield situational awareness; the narrative uses a mundane test to show divine wisdom in selection', 'The lappers were chosen purely by divine arbitrary election with no practical significance', 'The test selected men physically stronger than those who knelt', 'The test identified men from Gideon''s own clan to ensure loyalty', 'a', 'Judges 7:5-6 — The lapping test is not explained in the text, but the contrast between hand-to-mouth lappers (heads up, hands free) and those who bowed down suggests the former maintained alertness. The text''s silence on the reason emphasises divine sovereignty in the selection.'),
('Judges', 7, 'adults', 3, 'What is the significance of the barley cake in the Midianite soldier''s dream (Judges 7:13), and why does the interpretation identify it with Gideon?', 'Barley was the poor man''s grain and the bread of the oppressed; the dream symbol of the lowly barley cake overthrowing the great tent captures the theme of the weak confounding the mighty — the Gideon motif throughout chapter 6', 'Barley was Manasseh''s tribal crop and thus specifically identified with Gideon', 'The barley harvest season was when Gideon began gathering his army', 'Barley cakes were used in Midianite divination and thus the dream spoke in their own symbolic language', 'a', 'Judges 7:13-14 — The barley cake tumbling and overturning a Midianite tent is interpreted as "the sword of Gideon." Barley was the inferior grain (cf. Ruth 2; John 6:9), fitting Gideon''s "least of my father''s house" status (Judges 6:15).'),
('Judges', 7, 'adults', 4, 'Why did God direct Gideon to eavesdrop on the Midianite camp at night before the battle (Judges 7:9-11), and what psychological purpose did it serve?', 'God gave Gideon the option to hear the dream "if thou fear to go down" — it was a mercy provision to strengthen Gideon''s confidence before battle, not a military requirement', 'God needed Gideon to gather intelligence about Midianite troop positions', 'It was a test to see if Gideon would obey an unusual command', 'God wanted Gideon to hear Midianite prayers and learn their weakness', 'a', 'Judges 7:10-11 — "But if thou fear to go down, go thou with Phurah thy servant down to the host: And thou shalt hear what they say; and afterward shall thine hands be strengthened." God diagnoses Gideon''s persistent fear and prescribes an encouraging word from the enemy''s own mouth.'),
('Judges', 7, 'adults', 5, 'How does the battle tactic of trumpets, pitchers, and lamps (Judges 7:16-20) achieve the desired military effect without conventional weapons?', 'The simultaneous explosion of sound (300 trumpets), light (300 lamps), and battle cry from three surrounding directions at night created total disorientation, triggering panic and friendly-fire confusion in the camp — confirmed by Judges 7:22', 'The lamps signalled a larger unseen army waiting in the hills', 'The trumpets fulfilled the priestly pattern of the walls of Jericho', 'The broken pitchers were ceramic containers filled with burning pitch that set the camp alight', 'a', 'Judges 7:19-22 — The attack at the middle watch (when sentries changed and alertness was lowest), from three directions simultaneously, with 300 trumpet blasts and sudden light, "every man in his place round about the camp." The result: LORD-induced confusion and mutual slaughter (v.22).'),
('Judges', 7, 'adults', 6, 'Gideon sends messengers throughout mount Ephraim to cut off Midianite escape at the Jordan crossings (Judges 7:24). What does this reveal about the scope of tribal cooperation and the battle''s second phase?', 'The initial 300-man surprise attack is followed by a broader tribal mobilisation, showing the battle had two phases: divine panic and pursuit, requiring Ephraim''s cooperation to seal the victory', 'Ephraim had already been gathered as a reserve force and was waiting for the signal', 'The Ephraimites were angry at being excluded and thus mobilised independently', 'Gideon had planned both phases before the battle began', 'a', 'Judges 7:24-25 — "Gideon sent messengers throughout all mount Ephraim, saying, Come down against the Midianites, and take before them the waters unto Beth-barah and Jordan." The pursuit requires a larger force than 300 to seal escape routes.'),
('Judges', 7, 'adults', 7, 'The Ephraimites capture and kill two Midianite princes named Oreb and Zeeb. What do their names mean, and what is the irony of their fate?', 'Oreb means raven and Zeeb means wolf — predatory animals; these princes named as predators are themselves killed at a rock and a winepress, the very sites of Israelite vulnerability and hiding', 'Oreb means mighty and Zeeb means swift — warrior epithets that are ironic given their capture', 'Oreb means north wind and Zeeb means east wind — directional names indicating their Midianite clans', 'Oreb means thorn and Zeeb means lion — common Midianite warrior names without special irony', 'a', 'Judges 7:25 — Oreb (raven) slain at the rock of Oreb, Zeeb (wolf) at the winepress of Zeeb. The winepress (like Gideon''s hiding place in Judges 6:11) is now a site of victory, not fear — the irony of reversal.'),
('Judges', 7, 'adults', 8, 'How does the Gideon narrative in Judges 7 serve as a paradigm for the New Testament principle articulated in 1 Corinthians 1:27-29?', 'God chose 300 "foolish" men with pitchers and trumpets to confound 135,000 Midianites (Judges 8:10), directly illustrating Paul''s principle that God chooses the weak and foolish to shame the strong, so no flesh may glory', 'Paul''s principle is about spiritual gifts, not military tactics', 'The parallel is coincidental; Paul drew from Greek philosophical tradition, not Judges', 'The principle applies only to Paul''s church context and cannot be mapped back to Old Testament narratives', 'a', '1 Corinthians 1:27-29 — "God hath chosen the weak things of the world to confound the things which are mighty...That no flesh should glory." The Gideon account is a paradigmatic illustration: 300 men, no conventional weapons, total dependence on God, total victory.');

-- ═══ Judges Chapter 8 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 8, 'kids', 1, 'What did the people of Israel ask Gideon to do after he defeated the Midianites?', 'Rule over them as their king', 'Be their high priest', 'Lead them to a new land', 'Build them a great city', 'a', 'Judges 8:22 — "The men of Israel said unto Gideon, Rule thou over us, both thou, and thy son, and thy son''s son also: for thou hast delivered us from the hand of Midian."'),
('Judges', 8, 'kids', 2, 'What did Gideon say when the people asked him to be their king?', 'I will not rule over you; the LORD shall rule over you', 'I will rule over you for forty years', 'Let my firstborn son rule instead', 'I must pray before I can answer', 'a', 'Judges 8:23 — "Gideon said unto them, I will not rule over you, neither shall my son rule over you: the LORD shall rule over you."'),
('Judges', 8, 'kids', 3, 'How long did the land have peace during Gideon''s lifetime?', 'Forty years', 'Twenty years', 'Eighty years', 'Fifty years', 'a', 'Judges 8:28 — "Thus was Midian subdued before the children of Israel...And the country was in quietness forty years in the days of Gideon."'),
-- Teens
('Judges', 8, 'teens', 1, 'Why were the men of Ephraim angry with Gideon at the beginning of chapter 8?', 'He had not called them at the beginning of the fight against Midian', 'He had given their land to another tribe', 'He had taken Midianite treasure without sharing it', 'He had made a treaty with the Midianites without consulting them', 'a', 'Judges 8:1 — "The men of Ephraim said unto him, Why hast thou served us thus, that thou calledst us not, when thou wentest to fight with the Midianites?"'),
('Judges', 8, 'teens', 2, 'How did Gideon wisely pacify the angry Ephraimites?', 'He said their gleanings (capturing the Midianite princes) were better than his vintage, honouring their contribution above his own', 'He gave them a share of the Midianite spoil', 'He promised to call them first in all future battles', 'He invited their elders to be advisors in his household', 'a', 'Judges 8:2-3 — "Is not the gleaning of the grapes of Ephraim better than the vintage of Abiezer?...Then their anger was abated toward him, when he had said that."'),
('Judges', 8, 'teens', 3, 'What did the men of Succoth and Penuel do when Gideon asked them for bread for his exhausted troops?', 'They refused, mocking Gideon by asking if he had already captured Zebah and Zalmunna', 'They generously provided food and supplies', 'They threatened to alert the Midianites of Gideon''s approach', 'They demanded payment before giving any bread', 'a', 'Judges 8:6 — "The princes of Succoth said, Are the hands of Zebah and Zalmunna now in thine hand, that we should give bread unto thine army?"'),
('Judges', 8, 'teens', 4, 'What did Gideon do to the men of Succoth as punishment for refusing to help?', 'He tore their flesh with thorns and briers of the wilderness', 'He destroyed their city and killed their leaders', 'He took their food supply and gave it to others', 'He made them servants of the tribe of Manasseh', 'a', 'Judges 8:16 — "He took the elders of the city, and thorns of the wilderness and briers, and with them he taught the men of Succoth."'),
('Judges', 8, 'teens', 5, 'What spiritual failure did Gideon make after the victory, despite refusing the kingship?', 'He made a golden ephod from the spoils and Israel went a-whoring after it as a snare', 'He took multiple wives from among the Canaanites', 'He stopped worshipping at the tabernacle in Shiloh', 'He set up a high place and offered unauthorised sacrifices', 'a', 'Judges 8:27 — "Gideon made an ephod thereof, and put it in his city, even in Ophrah: and all Israel went thither a-whoring after it: which thing became a snare unto Gideon, and to his house."'),
-- Adults
('Judges', 8, 'adults', 1, 'What rhetorical device does Gideon use to defuse Ephraim''s anger in Judges 8:2-3, and what does it reveal about his political intelligence?', 'He uses the proverb of gleaning vs. vintage — elevating Ephraim''s achievement above his own through self-deprecation — showing mastery of ANE honour culture to prevent intertribal conflict', 'He uses a legal argument about the rules of holy war spoil division', 'He invokes the Mosaic law about tribal military obligations', 'He appeals to the LORD''s verdict rather than human honour calculations', 'a', 'Judges 8:2 — "Is not the gleaning of the grapes of Ephraim better than the vintage of Abiezer?" This viniculture metaphor in an honour-shame society allows Ephraim to feel their contribution was greater, ending the dispute without capitulation.'),
('Judges', 8, 'adults', 2, 'How does Gideon''s treatment of Succoth and Penuel (Judges 8:7-9, 15-17) raise a moral tension within the narrative?', 'His punishment of fellow Israelites for non-cooperation during the pursuit is severe — thorns and demolishing the tower of Penuel — raising the question of whether his leadership is becoming vindictive and tyrannical', 'The text condemns his actions explicitly as sin', 'His treatment was legally prescribed by Mosaic law for treason', 'The punishment is presented as entirely just with no narrative ambiguity', 'a', 'Judges 8:7,17 — Gideon threatens then executes thorning of Succoth''s elders and demolishing Penuel''s tower with its men. The narrator gives no explicit evaluation, creating moral ambiguity characteristic of the Judges'' portrayal of flawed deliverers.'),
('Judges', 8, 'adults', 3, 'What does the interrogation and execution of Zebah and Zalmunna in Judges 8:18-21 reveal about Gideon''s personal motivation?', 'Their killing of Gideon''s brothers at Tabor transforms this from holy war into personal blood vengeance — the honour-code demand that he avenge his family', 'Gideon killed them purely to fulfil the LORD''s command', 'He killed them to prevent future Midianite retaliation', 'He killed them because the elders of Israel demanded it', 'a', 'Judges 8:19-20 — "They were my brethren, even the sons of my mother...Then he said unto Jether his firstborn, Up, and slay them." The personal dimension of blood-vengeance intersects with holy war, complicating Gideon''s moral portrait.'),
('Judges', 8, 'adults', 4, 'What is the theological irony of the ephod Gideon creates in Judges 8:24-27?', 'The man who destroyed Baal''s altar creates a religious object that itself becomes an idol causing Israel to go "a-whoring" — his greatest victory is followed by his deepest spiritual failure', 'The ephod was a legitimate priestly garment and the problem was only its location in Ophrah', 'The ephod was intended as a war memorial and only later became an object of worship', 'The text approves of the ephod''s creation but condemns its misuse by later generations', 'a', 'Judges 8:27 — "All Israel went thither a-whoring after it: which thing became a snare unto Gideon, and to his house." The warrior who began by tearing down Baal''s altar (Judges 6:25) ends by creating a new object of idolatrous devotion.'),
('Judges', 8, 'adults', 5, 'How many wives and sons did Gideon have, and what does this signal within the Judges narrative about the coming dynastic problem?', 'He had many wives and 70 sons, plus a concubine in Shechem who bore Abimelech — the proliferation of heirs directly sets up the fratricidal chaos of Judges 9', 'He had one wife and twelve sons representing the twelve tribes', 'He had three wives from different tribes to create political alliances', 'He had many wives as a sign of blessing, with no negative narrative implication', 'a', 'Judges 8:30-31 — "Gideon had threescore and ten sons of his body begotten: for he had many wives. And his concubine that was in Shechem, she also bare him a son, whose name he called Abimelech." This genealogy plants the seeds for chapter 9''s catastrophe.'),
('Judges', 8, 'adults', 6, 'What does the sudden return to Baal worship after Gideon''s death (Judges 8:33-35) reveal about the nature of Israel''s covenant loyalty under the judges?', 'It was superficial and personality-dependent — tied to the deliverer''s presence rather than genuine heart transformation, confirming the cycle''s structural inevitability', 'Israel was gradually improving in covenant loyalty across the judges period', 'Gideon''s ephod was the primary cause of the relapse into Baal worship', 'The return to Baal was caused by Midianite survivors returning to influence Israel', 'a', 'Judges 8:33-35 — "As soon as Gideon was dead...the children of Israel turned again, and went a-whoring after Baalim...and remembered not the LORD...Neither shewed they kindness to the house of Jerubbaal." The speed of the relapse ("as soon as") underscores its superficiality.'),
('Judges', 8, 'adults', 7, 'Gideon''s refusal of kingship in Judges 8:23 is theologically significant. How does it contrast with Israel''s later request to Samuel for a king?', 'Gideon''s refusal affirms theocracy — "the LORD shall rule over you" — while Samuel''s Israel rejects theocracy (1 Sam. 8:7) by demanding a king, marking a progressive deterioration of covenant loyalty', 'Gideon refused because he was already functioning as a de facto king in all but name', 'The situations are not comparable because Gideon was from Manasseh, not Judah', 'Samuel''s situation involved a genuine monarchy; Gideon''s refusal was only of a tribal chieftainship', 'a', 'Judges 8:23 — "The LORD shall rule over you." This theocratic principle is the constitutional ideal the judges embody. When Israel demands a king in 1 Samuel 8:7, God interprets it as rejecting divine rule — the same principle Gideon upheld.'),
('Judges', 8, 'adults', 8, 'What is the weight of gold Gideon collected from the Ishmaelite earrings, and what broader cultural pattern does this reflect?', 'A thousand and seven hundred shekels of gold, reflecting the ancient Near Eastern practice of dedicating metals from military spoil to religious purposes — but here corrupted into an idolatrous object', 'Five hundred shekels, dedicated to the tabernacle as an offering to the LORD', 'Three thousand shekels, shared equally among the 300 warriors', 'An unstated amount but described as very great, filling a cart', 'a', 'Judges 8:26 — "The weight of the golden earrings that he requested was a thousand and seven hundred shekels of gold." The dedication of metal spoil to religion mirrors the tabernacle offerings, but here the application becomes a "snare" — an ironic inversion of proper worship.');

-- ═══ Judges Chapter 9 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 9, 'kids', 1, 'Who was Abimelech''s father?', 'Gideon (Jerubbaal)', 'Barak', 'Ehud', 'Othniel', 'a', 'Judges 9:1 — "Abimelech the son of Jerubbaal went to Shechem unto his mother''s brethren." Jerubbaal is Gideon''s other name (Judges 8:35).'),
('Judges', 9, 'kids', 2, 'How many of his brothers did Abimelech kill to become ruler?', 'Seventy brothers', 'Twelve brothers', 'Forty brothers', 'Seven brothers', 'a', 'Judges 9:5 — "He went unto his father''s house at Ophrah, and slew his brethren the sons of Jerubbaal, being threescore and ten persons, upon one stone."'),
('Judges', 9, 'kids', 3, 'How did Abimelech die?', 'A woman dropped a millstone on his head', 'He was killed by his own soldiers', 'He was struck by lightning', 'He fell off his horse in battle', 'a', 'Judges 9:53 — "A certain woman cast a piece of a millstone upon Abimelech''s head, and all to brake his skull."'),
-- Teens
('Judges', 9, 'teens', 1, 'What parable did Jotham tell to rebuke the men of Shechem for making Abimelech king?', 'The parable of the trees seeking a king — the bramble accepted where the olive, fig, and vine all refused', 'The parable of the lion and the lamb in the vineyard', 'The parable of the sower and the rocky ground', 'The parable of the eagle and the cedar of Lebanon', 'a', 'Judges 9:8-15 — The trees ask the olive, fig, and vine to be king; all refuse because they have productive work. The bramble accepts and threatens to devour the cedars of Lebanon.'),
('Judges', 9, 'teens', 2, 'Who was the one son of Gideon who escaped Abimelech''s massacre, and what did he do after warning Shechem?', 'Jotham, who escaped by hiding; he delivered his parable from mount Gerizim and then fled to Beer for fear of Abimelech', 'Tola, who fled to mount Ephraim and became a judge', 'Jair, who escaped to Gilead and raised an army against Abimelech', 'Abdon, who hid in a cave and later returned to claim his inheritance', 'a', 'Judges 9:5 — "Yet Jotham the youngest son of Jerubbaal was left; for he hid himself." Judges 9:7,21 — He proclaimed his parable from Gerizim and "fled, and ran away, and went to Beer."'),
('Judges', 9, 'teens', 3, 'How did God bring judgment on Abimelech and the men of Shechem, according to Judges 9:23-24?', 'God sent an evil spirit between Abimelech and the men of Shechem so that they dealt treacherously with one another', 'God sent a plague upon Shechem that weakened their army', 'God raised up enemies from Midian to attack them both', 'God caused an earthquake to destroy the tower of Shechem', 'a', 'Judges 9:23-24 — "God sent an evil spirit between Abimelech and the men of Shechem; and the men of Shechem dealt treacherously with Abimelech: that the cruelty done to the threescore and ten sons of Jerubbaal might come."'),
('Judges', 9, 'teens', 4, 'Who was Gaal the son of Ebed, and what role did he play in the narrative?', 'He stirred up the men of Shechem against Abimelech, claiming they should serve him instead', 'He was a Canaanite general who attacked Abimelech from without', 'He was the officer of the tower of Shechem who betrayed the city to Abimelech', 'He was a prophet who predicted Abimelech''s downfall', 'a', 'Judges 9:28 — "Gaal the son of Ebed said, Who is Abimelech...that we should serve him?" He led the rebellion inside Shechem until Zebul drove him out (Judges 9:40-41).'),
('Judges', 9, 'teens', 5, 'What instruction did Abimelech give his armour-bearer after a woman dropped the millstone on him, and why?', 'He told his armour-bearer to thrust him through with his sword, so that men would not say a woman killed him', 'He told his armour-bearer to carry him from the battlefield to a physician', 'He told his armour-bearer to sound the retreat and negotiate surrender', 'He told his armour-bearer to avenge him by killing the woman', 'a', 'Judges 9:54 — "Abimelech called hastily unto the young man his armourbearer, and said unto him, Draw thy sword, and slay me, that men say not of me, A woman slew him."'),
-- Adults
('Judges', 9, 'adults', 1, 'What is the literary genre of Jotham''s speech in Judges 9:7-20, and how does it function within the narrative?', 'It is a political fable using an allegory of trees choosing a king, followed by a prophetic curse — the first fable in Scripture, functioning as a legal indictment of Shechem''s treachery against Gideon''s house', 'It is a wisdom poem in the tradition of Proverbs, inserted editorially', 'It is a lament over the death of Gideon''s sons', 'It is a treaty curse formula borrowed from Hittite suzerainty documents', 'a', 'Judges 9:8-15 is widely identified as the earliest fable in the Bible. It functions as Jotham''s legal case: if the men of Shechem acted rightly (v.16,19), good; if not (v.20), let fire devour them — a conditional curse.'),
('Judges', 9, 'adults', 2, 'What is the theological significance of the "evil spirit" God sends between Abimelech and Shechem (Judges 9:23)?', 'It demonstrates divine retributive justice operating through secondary causes — God does not intervene directly but uses the seeds of treachery already present in Abimelech''s violent rule to bring about proportionate punishment', 'The evil spirit was a demonic being acting independently of God''s will', 'It fulfilled a specific Mosaic curse on fratricide', 'The evil spirit was a metaphor for political discord with no supernatural content', 'a', 'Judges 9:23-24 — "God sent an evil spirit between Abimelech and the men of Shechem...that the cruelty done to the sons of Jerubbaal might come." The narrator explicitly credits God as the agent of retributive justice through providential means.'),
('Judges', 9, 'adults', 3, 'How does the fable''s bramble (Judges 9:14-15) serve as a self-commentary on Abimelech''s character and rule?', 'The bramble is the least noble plant — no fruit, only thorns — and its grandiose self-promotion ("come and put your trust in my shadow") and its threat to burn down the cedars mirrors Abimelech''s worthlessness and destructive violence', 'The bramble represents the Shechemite people who chose a bad leader', 'The bramble is a symbol of Canaanite culture dominating Israelite politics', 'The bramble''s threat is purely defensive — warning against enemies of Shechem', 'a', 'Judges 9:14-15 — The bramble alone accepts kingship and immediately threatens destruction. The productive trees (olive, fig, vine) represent Gideon''s legitimate sons; the bramble represents the half-Canaanite, fruitless Abimelech.'),
('Judges', 9, 'adults', 4, 'What role does Zebul play in the Abimelech narrative, and what does his character illustrate about political loyalty?', 'As governor of Shechem, Zebul secretly alerts Abimelech to Gaal''s rebellion, then manipulates Gaal into a military confrontation — illustrating the political informant who serves power regardless of principle', 'Zebul is a righteous official who tries to prevent bloodshed between Abimelech and Shechem', 'Zebul switches sides from Abimelech to Gaal and back, representing the common people''s uncertainty', 'Zebul is the commander of Abimelech''s army, loyal only because of military rank', 'a', 'Judges 9:30-33 — Zebul sends secret intelligence to Abimelech and then (Judges 9:36-38) taunts Gaal to fight, engineering a confrontation that destroys Gaal''s influence. His motives are entirely political, not theological.'),
('Judges', 9, 'adults', 5, 'How does Jotham''s parable in Judges 9:16-20 structure the conditions for its curse, and what double irony is fulfilled in Judges 9:57?', 'The curse is conditional on whether Shechem acted "in truth and sincerity"; since they did not, fire from Abimelech should devour Shechem and fire from Shechem devour Abimelech — ironic fulfilment: Abimelech burns the tower of Shechem (v.49) but is then killed at Thebez (v.53)', 'The curse was unconditional and applied regardless of Shechem''s choices', 'The curse was fulfilled when the Midianites destroyed Shechem a generation later', 'Jotham''s curse was considered legally null because he had no priestly authority', 'a', 'Judges 9:20 — "Let fire come out from Abimelech, and devour the men of Shechem...and let fire come out from the men of Shechem...and devour Abimelech." Fulfilled: Abimelech burns the tower (v.49, about 1000 die) and is killed at another tower (v.53).'),
('Judges', 9, 'adults', 6, 'What does the detail that Abimelech used seventy pieces of silver from the house of Baal-berith to hire "vain and light persons" (Judges 9:4) reveal about his rule''s character?', 'Temple silver used to fund a mercenary coup shows the intersection of idolatry and political violence — his kingship is funded by pagan religion and executed by moral nihilists, entirely outside covenantal legitimacy', 'The silver amount was a customary payment for tribal leadership transfer', 'Baal-berith was a benevolent deity whose silver was appropriate for political use', 'The "vain and light persons" were simply young volunteers, not morally suspect individuals', 'a', 'Judges 9:4 — "They gave him threescore and ten pieces of silver out of the house of Baal-berith, wherewith Abimelech hired vain and light persons, which followed him." The source (pagan temple) and agents (morally worthless men) define his regime from its inception.'),
('Judges', 9, 'adults', 7, 'What is the significance of Abimelech''s death at Thebez — killed by a woman with a millstone — within the book''s theology of divine justice?', 'It fulfils Jotham''s curse through ironic reversal: the man who slaughtered 70 on one stone (Judges 9:5) dies by a stone, and the man who suppressed women''s honour is shamed by a woman — proportionate, poetic divine retribution', 'It was a random accident with no theological significance in the narrative', 'It fulfils Deborah''s prophecy that military honour belongs to women', 'It shows the weakness of Abimelech''s siege strategy rather than divine judgment', 'a', 'Judges 9:5 — sons killed on one stone; Judges 9:53 — Abimelech killed by a millstone. The stone-for-stone symmetry is narratively deliberate. Judges 9:56 explicitly confirms: "God rendered the wickedness of Abimelech...upon his head."'),
('Judges', 9, 'adults', 8, 'How does the Abimelech episode function as a sustained anti-monarchical argument within the book of Judges and the broader Deuteronomic History?', 'By showing that illegitimate kingship — born of violence, funded by idolatry, maintained by terror — leads inevitably to fratricidal destruction, it provides a cautionary case study informing the later debates about monarchy in 1 Samuel', 'The episode is purely historical with no political theology', 'It argues only against half-Canaanite rulers, not against monarchy in general', 'The Deuteronomic History favours monarchy and uses Abimelech only as a negative example of the wrong individual, not the institution', 'a', 'Judges 9 is the only "kingship" episode in Judges before the monarchy. Its catastrophic ending and explicit divine retribution (v.56-57) inform Samuel''s warning about kings (1 Sam. 8:11-18) and Jotham''s fable remains the clearest anti-monarchical argument in the pre-monarchical corpus.');

-- ═══ Judges Chapter 10 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Judges', 10, 'kids', 1, 'Who judged Israel after Abimelech and was from the tribe of Issachar?', 'Tola the son of Puah', 'Jair the Gileadite', 'Jephthah the Gileadite', 'Ibzan of Bethlehem', 'a', 'Judges 10:1 — "After Abimelech there arose to defend Israel Tola the son of Puah, the son of Dodo, a man of Issachar."'),
('Judges', 10, 'kids', 2, 'Jair the Gileadite had thirty sons. What did they ride on?', 'Thirty ass colts', 'Thirty horses', 'Thirty camels', 'Thirty mules', 'a', 'Judges 10:4 — "He had thirty sons that rode on thirty ass colts, and they had thirty cities."'),
('Judges', 10, 'kids', 3, 'What did Israel do when they were sorry for worshipping idols, according to Judges 10:16?', 'They put away the strange gods from among them and served the LORD', 'They offered sacrifices at the tabernacle', 'They went to fight their enemies immediately', 'They asked a prophet to pray for them', 'a', 'Judges 10:16 — "They put away the strange gods from among them, and served the LORD: and his soul was grieved for the misery of Israel."'),
-- Teens
('Judges', 10, 'teens', 1, 'How many years did Tola judge Israel, and in what city did he dwell?', 'Twenty-three years; he dwelt in Shamir in mount Ephraim', 'Forty years; he dwelt in Shiloh', 'Eighteen years; he dwelt in Bethlehem', 'Thirty years; he dwelt in Ramah in Benjamin', 'a', 'Judges 10:2-3 — "He judged Israel twenty and three years, and died, and was buried in Shamir."'),
('Judges', 10, 'teens', 2, 'How many years did Jair judge Israel, and what was remarkable about the cities his sons controlled?', 'Twenty-two years; his thirty sons had thirty cities called Havoth-jair in Gilead', 'Forty years; he built thirty new cities in the wilderness', 'Fifteen years; his sons governed thirty districts of Canaan', 'Thirty years; his sons built the thirty cities of the Levites', 'a', 'Judges 10:3-4 — "Jair the Gileadite judged Israel twenty and two years...his sons had thirty cities, which are called Havoth-jair unto this day, which are in the land of Gilead."'),
('Judges', 10, 'teens', 3, 'Which peoples oppressed Israel when they again did evil after Jair''s death?', 'The Philistines and the children of Ammon', 'The Midianites and the Moabites', 'The Amorites and the Hittites', 'The Edomites and the Syrians', 'a', 'Judges 10:7 — "The anger of the LORD was hot against Israel, and he sold them into the hands of the Philistines, and into the hands of the children of Ammon."'),
('Judges', 10, 'teens', 4, 'How long did the Ammonite and Philistine oppression last before Israel cried to the LORD?', 'Eighteen years', 'Seven years', 'Forty years', 'Twenty years', 'a', 'Judges 10:8 — "That year they vexed and oppressed the children of Israel eighteen years, all the children of Israel that were on the other side Jordan in the land of the Amorites, which is in Gilead."'),
('Judges', 10, 'teens', 5, 'How did the LORD initially respond when Israel cried out for deliverance from Ammonite oppression?', 'The LORD refused, recounting all the times He had saved them and been forsaken, and told them to cry to the gods they had chosen', 'The LORD immediately raised up Jephthah as a deliverer', 'The LORD sent a prophet to give them instructions for repentance', 'The LORD sent an angel to tell them to gather their army', 'a', 'Judges 10:13-14 — "Yet ye have forsaken me, and served other gods: wherefore I will deliver you no more. Go and cry unto the gods which ye have chosen; let them deliver you in the time of your tribulation."'),
-- Adults
('Judges', 10, 'adults', 1, 'How many gods does Judges 10:6 specifically list that Israel served, and what is the significance of the comprehensive list?', 'Seven foreign gods: Baalim, Ashtaroth, gods of Syria, Sidon, Moab, Ammon, and Philistia — a comprehensive indictment showing Israel had adopted the idolatry of every surrounding nation', 'Three gods: Baal, Asherah, and Molech — the principal Canaanite deities', 'Five gods, representing the five Philistine city-states', 'Ten gods, one for each of the northern tribes', 'a', 'Judges 10:6 — "Served Baalim, and Ashtaroth, and the gods of Syria, and the gods of Zidon, and the gods of Moab, and the gods of the children of Ammon, and the gods of the Philistines." The exhaustive list marks the nadir of Israel''s apostasy.'),
('Judges', 10, 'adults', 2, 'What is theologically unusual about the LORD''s response in Judges 10:13-14, and how does it differ from earlier judge narratives?', 'God explicitly refuses to deliver Israel again and sarcastically redirects them to their chosen gods — a direct divine speech of rejection that intensifies the cycle and marks a turning point toward more ambiguous deliverances', 'God refuses then immediately relents without any change in Israel''s behaviour', 'God sends a plague before agreeing to send a deliverer', 'God''s refusal is temporary and standard, identical to all previous cycles', 'a', 'Judges 10:13-14 — God''s direct speech of refusal ("I will deliver you no more...Go and cry unto the gods which ye have chosen") is unprecedented in the judge narratives. It raises the theological stakes and frames the Jephthah narrative that follows under divine reluctance.'),
('Judges', 10, 'adults', 3, 'What is significant about Judges 10:16''s description of Israel putting away foreign gods and the LORD''s response that "his soul was grieved for the misery of Israel"?', 'The divine pathos expressed — God''s soul being grieved or vexed — shows that even after threatening abandonment, God''s compassion is moved by genuine repentance, revealing the tension between divine justice and divine mercy', 'The phrase is anthropomorphic only and means God had no emotional involvement', 'It proves that Israel''s repentance was complete and fully accepted', 'God''s grief is a metaphor for the suffering He would experience in providing a deliverer', 'a', 'Judges 10:16 — "His soul was grieved for the misery of Israel." The Hebrew naphsho qatsarah (his soul was shortened/vexed) expresses genuine divine compassion despite the preceding statement of refusal — the tension between justice and mercy that characterises the whole book.'),
('Judges', 10, 'adults', 4, 'Tola and Jair are classified as "minor judges." What distinguishes minor judges from major judges in terms of narrative function?', 'Minor judges receive no deliverance narrative — only tenure length, lineage, and administrative detail — suggesting they functioned as civil leaders maintaining order rather than as Spirit-empowered military deliverers', 'Minor judges were from smaller tribes and therefore received less narrative attention', 'Minor judges were illegitimate leaders rejected by some tribes', 'The distinction is modern and has no basis in the Hebrew text''s presentation', 'a', 'Tola (Judges 10:1-2) and Jair (Judges 10:3-5) are presented with only genealogical and tenure data, no enemy, no deliverance, no Spirit. This formulaic brevity contrasts with major judge narratives and suggests a different (civil/administrative) function.'),
('Judges', 10, 'adults', 5, 'What geographical scope does Judges 10:8-9 give to the Ammonite oppression, and what does this signal about the crisis''s severity?', 'The Ammonites oppressed all Israel beyond the Jordan and crossed over to fight Judah, Benjamin, and Ephraim — pan-Israelite scope indicating the most widespread oppression since the book began', 'The oppression was limited to the Transjordanian tribes of Gad and Reuben', 'Only the tribe of Manasseh was affected because Jephthah was from Gilead', 'The Ammonites controlled the coastal plain but did not penetrate the hill country', 'a', 'Judges 10:8-9 — "They vexed and oppressed...all the children of Israel that were on the other side Jordan...Moreover the children of Ammon passed over Jordan to fight also against Judah, and against Benjamin, and against the house of Ephraim." The breadth creates urgency for a deliverer.'),
('Judges', 10, 'adults', 6, 'How does Israel''s confession in Judges 10:10 — "We have sinned against thee, both because we have forsaken our God, and also served Baalim" — compare to earlier repentance statements in Judges?', 'It is the most theologically explicit confession in the book: it names the sin precisely (forsaking God and serving Baal) rather than simply crying in distress, yet it follows the same structural pattern of cry after oppression', 'It is the first time Israel ever confessed sin in the book of Judges', 'It is less sincere than earlier confessions because it comes after eighteen years rather than immediately', 'The confession is evaluated positively and immediately accepted by God', 'a', 'Judges 10:10 — "We have sinned against thee, both because we have forsaken our God, and also served Baalim." Compared to Judges 3:9, 15; 4:3 (simple cries), this confession includes theological self-diagnosis, though God''s initial response (Judges 10:13) is still refusal.'),
('Judges', 10, 'adults', 7, 'What does the list of Jair''s thirty sons riding thirty ass colts governing thirty cities (Judges 10:4) reveal about the social development of the judge period?', 'It indicates a dynastic, hereditary leadership pattern with administrative territorial control — a move toward proto-monarchical governance that anticipates and explains the eventual demand for a king', 'It was a sign of divine blessing with no political implications', 'The thirty cities were all Levitical cities assigned for priestly administration', 'The ass colts were military mounts showing Jair maintained a cavalry force', 'a', 'Judges 10:4 — The thirty sons each governing a named city (Havoth-jair) with their own mount (a status symbol, cf. Judges 5:10; 12:14) reveals administrative infrastructure more associated with kingship than with the Spirit-called deliverers of the major judge narratives.'),
('Judges', 10, 'adults', 8, 'How does Judges 10 serve as the theological hinge between the Abimelech episode and the Jephthah narrative, and what does this structural placement accomplish?', 'It resets the Deuteronomic cycle after the anomalous Abimelech anti-kingship episode, escalates the apostasy to an all-time catalogue of seven gods, introduces the most severe divine refusal yet, then establishes the desperation that will make Jephthah''s flawed leadership understandable', 'It serves as a purely transitional chapter with no theological content of its own', 'It introduces the Philistine threat that will dominate Samson''s narrative', 'It explains why the Ammonites and Philistines were simultaneously powerful enough to double-oppress Israel', 'a', 'Judges 10 functions as a theological escalation point: the seven-god apostasy (v.6) exceeds all previous sin catalogs; the divine refusal (v.13-14) is unprecedented; the genuine repentance (v.16) and divine compassion introduce Jephthah''s ambiguous deliverance in chapters 11-12 under conditions of maximum crisis.');
