-- ============================================================================
-- Quiz Seed: Exodus — Part 4 (Chapters 31–40)
-- 3 difficulties × 10 chapters = 160 total questions
--   kids:   3 per chapter  = 30
--   teens:  5 per chapter  = 50
--   adults: 8 per chapter  = 80
-- ============================================================================

-- ═══════════════ CHAPTERS 31–35 ═══════════════

-- ═══ Exodus Chapter 31 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 31, 'kids', 1, 'Who did God choose to be the chief craftsman for building the tabernacle?', 'Bezaleel the son of Uri — God filled him with His Spirit to have special skills in craftsmanship', 'Moses', 'Aaron', 'Joshua', 'a', 'Exodus 31:2-3 — "See, I have called by name Bezaleel the son of Uri... And I have filled him with the spirit of God, in wisdom, and in understanding, and in knowledge, and in all manner of workmanship."'),
('Exodus', 31, 'kids', 2, 'Who was Bezaleel''s helper?', 'Aholiab the son of Ahisamach from the tribe of Dan', 'Aaron', 'Miriam', 'Caleb', 'a', 'Exodus 31:6 — "And I, behold, I have given with him Aholiab, the son of Ahisamach, of the tribe of Dan."'),
('Exodus', 31, 'kids', 3, 'What special day did God remind the Israelites to keep?', 'The Sabbath — a day of rest, holy to the LORD', 'Tuesday', 'The first day of each month', 'Every tenth day', 'a', 'Exodus 31:13 — "Verily my sabbaths ye shall keep: for it is a sign between me and you throughout your generations."'),
-- Teens
('Exodus', 31, 'teens', 1, 'What skills did God give Bezaleel through the Spirit?', 'Wisdom, understanding, knowledge, and skill in all manner of workmanship — gold, silver, brass, stone cutting, wood carving, and every craft', 'Only stone cutting', 'Only weaving', 'Only painting', 'a', 'Exodus 31:3-5 — "I have filled him with the spirit of God, in wisdom, and in understanding, and in knowledge, and in all manner of workmanship, To devise cunning works, to work in gold, and in silver, and in brass."'),
('Exodus', 31, 'teens', 2, 'What penalty did God prescribe for breaking the Sabbath?', 'Death — "every one that defileth it shall surely be put to death"', 'A fine of one shekel', 'A warning only', 'Extra work the next day', 'a', 'Exodus 31:14 — "Ye shall keep the sabbath therefore; for it is holy unto you: every one that defileth it shall surely be put to death."'),
('Exodus', 31, 'teens', 3, 'What did God call the Sabbath?', 'A sign between God and Israel forever — and a perpetual covenant', 'A suggestion for rest', 'An Egyptian custom', 'A temporary arrangement', 'a', 'Exodus 31:16-17 — "Wherefore the children of Israel shall keep the sabbath, to observe the sabbath throughout their generations, for a perpetual covenant. It is a sign between me and the children of Israel for ever."'),
('Exodus', 31, 'teens', 4, 'What did God give Moses at the end of their forty days on the mountain?', 'Two tables (tablets) of testimony — tables of stone, written with the finger of God', 'A golden crown', 'A new rod', 'A book of prophecy', 'a', 'Exodus 31:18 — "And he gave unto Moses, when he had made an end of communing with him upon mount Sinai, two tables of testimony, tables of stone, written with the finger of God."'),
('Exodus', 31, 'teens', 5, 'Why does God connect the Sabbath to creation?', '"For in six days the LORD made heaven and earth, and on the seventh day he rested, and was refreshed" — the Sabbath mirrors God''s own pattern', 'There is no creation connection', 'The Sabbath was invented in Egypt', 'The Sabbath was Moses'' idea', 'a', 'Exodus 31:17 — "For in six days the LORD made heaven and earth, and on the seventh day he rested, and was refreshed."'),
-- Adults
('Exodus', 31, 'adults', 1, 'What is the significance of the Spirit filling Bezaleel for artistic work?', 'It demonstrates that the Holy Spirit empowers not only prophetic speech but also artistic skill — craftsmanship is a spiritual gift; this is the first explicit mention of the Spirit filling someone for a specific task, expanding our understanding of spiritual giftedness beyond preaching', 'The Spirit only empowers preaching', 'Bezaleel was naturally talented', 'The Spirit''s role was minor', 'a', 'Exodus 31:3 — "I have filled him with the spirit of God" for craftsmanship. This broadens the Spirit''s work beyond prophecy to include artistic creativity. Every good work — from preaching to painting to plumbing — can be a Spirit-empowered vocation.'),
('Exodus', 31, 'adults', 2, 'Why is the Sabbath command repeated here in the context of tabernacle construction?', 'It prevents the logical assumption that building God''s house exempts one from God''s day — even sacred work must yield to sacred rest; the Sabbath takes priority over the tabernacle itself, teaching that relationship with God supersedes even service for God', 'The placement is accidental', 'Building the tabernacle was Sabbath-exempt', 'The Sabbath was less important than building', 'a', 'Exodus 31:12-17 — The Sabbath command''s placement immediately after tabernacle instructions is deliberate: building the tabernacle does not override the Sabbath. Rabbinic tradition derived the 39 categories of prohibited Sabbath work from the tabernacle tasks.'),
('Exodus', 31, 'adults', 3, 'What does "written with the finger of God" (31:18) teach about the nature of the law?', 'It emphasises divine authorship — the law is not Moses'' invention or Israel''s consensus but God''s direct inscription; the "finger of God" language conveys personal, intimate, authoritative communication from the Creator to His creatures', 'Moses wrote the tablets himself', 'The phrase is metaphorical', 'Angels wrote the tablets', 'a', 'Exodus 31:18 — "Written with the finger of God." Jesus references the "finger of God" in Luke 11:20 (cf. Matthew 12:28: "Spirit of God"). The phrase denotes direct, unmediated divine action — the law bears God''s personal imprint.'),
('Exodus', 31, 'adults', 4, 'How does the Sabbath function as a "sign" (oth) of the covenant?', 'A sign makes the invisible visible — the Sabbath is an outward, weekly practice that embodies Israel''s covenant identity; like circumcision (another oth), it distinguishes Israel from the nations and declares God''s sovereignty over time itself', 'It was merely a day off', 'The sign was temporary', 'Other nations observed the same day', 'a', 'Exodus 31:13,17 — "It is a sign (oth) between me and you." Covenant signs include rainbow (Genesis 9:12), circumcision (Genesis 17:11), and Sabbath. Each makes an invisible covenant relationship tangibly visible in regular practice.'),
('Exodus', 31, 'adults', 5, 'What does "rested and was refreshed" (31:17) in anthropomorphic language teach about the Sabbath?', 'The Hebrew vayinnaphash ("was refreshed" — from nephesh/soul) describes God being "ensouled" or "re-spirited" — this audacious anthropomorphism teaches that rest is not merely ceasing from labour but active renewal; if even God "refreshes," how much more do humans need it', 'God literally needed rest', 'The phrase is meaningless', 'God was exhausted from creation', 'a', 'Exodus 31:17 — The verb naphash (related to nephesh — soul/life) applied to God is striking anthropomorphism. It does not imply divine fatigue but establishes rest as inherently valuable — part of the divine rhythm, not merely a concession to human weakness.'),
('Exodus', 31, 'adults', 6, 'How does naming Bezaleel "by name" (31:2) demonstrate God''s personal call?', 'God does not merely fill a role but calls a specific person — Bezaleel ben Uri ben Hur of the tribe of Judah; the personal naming echoes God''s call of Moses (3:4) and demonstrates that God''s purposes involve specific individuals chosen for specific tasks', 'Any skilled person could have been chosen', 'The naming was ceremonial', 'Bezaleel volunteered', 'a', 'Exodus 31:2 — "See, I have called by name Bezaleel." The personal divine call — with full genealogy (son of Uri, son of Hur, of Judah) — demonstrates purposeful divine election for service. God does not need generic workers but calls specific people with their particular gifts.'),
('Exodus', 31, 'adults', 7, 'What does the death penalty for Sabbath-breaking reveal about the Sabbath''s covenantal weight?', 'The severity reflects covenant priority — breaking the Sabbath was not merely a scheduling infraction but covenant treason; the sign of the covenant (Sabbath) carried the same weight as the covenant itself; violating the sign rejected the relationship', 'The punishment was disproportionate', 'It was never enforced', 'It applied only to leaders', 'a', 'Exodus 31:14-15 — The death penalty for Sabbath violation (cf. Numbers 15:32-36) shows that the Sabbath is not optional but covenantally binding. As covenant sign, its violation repudiates the covenant relationship — equivalent to removing one''s wedding ring in ancient near eastern custom.'),
('Exodus', 31, 'adults', 8, 'How does the pairing of Bezaleel (Judah) and Aholiab (Dan) unite the tribes?', 'Judah was the leading tribe and Dan one of the lowest-ranked — their partnership in building the tabernacle demonstrates that God''s work requires cooperation across social boundaries; every tribe contributes to God''s dwelling, not just the prominent ones', 'The tribal pairing was coincidental', 'Only Judah''s contribution mattered', 'Dan was excluded from other duties', 'a', 'Exodus 31:2,6 — Bezaleel from Judah (firstborn of Leah) and Aholiab from Dan (firstborn of Bilhah) represent the full spectrum of Israel — from noble to humble. God''s house is built by all His people working together across tribal and social lines.');

-- ═══ Exodus Chapter 32 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 32, 'kids', 1, 'What terrible thing did the people do while Moses was on the mountain?', 'They made a golden calf idol and worshipped it, saying "These be thy gods, O Israel"', 'They sang happy songs', 'They planted a garden', 'They built a house', 'a', 'Exodus 32:4 — "And he received them at their hand, and fashioned it with a graving tool, after he had made it a molten calf: and they said, These be thy gods, O Israel, which brought thee up out of the land of Egypt."'),
('Exodus', 32, 'kids', 2, 'What did Moses do with the two stone tablets when he saw the golden calf?', 'He threw them down and broke them at the bottom of the mountain', 'He carefully put them away', 'He gave them to Aaron', 'He hid them in a cave', 'a', 'Exodus 32:19 — "And it came to pass, as soon as he came nigh unto the camp, that he saw the calf, and the dancing: and Moses'' anger waxed hot, and he cast the tables out of his hands, and brake them beneath the mount."'),
('Exodus', 32, 'kids', 3, 'What did Moses do with the golden calf?', 'He burnt it in the fire, ground it into powder, scattered it on the water, and made the people drink it', 'He buried it in the ground', 'He sent it to Egypt', 'He put it in the tabernacle', 'a', 'Exodus 32:20 — "And he took the calf which they had made, and burnt it in the fire, and ground it to powder, and strawed it upon the water, and made the children of Israel drink of it."'),
-- Teens
('Exodus', 32, 'teens', 1, 'What excuse did Aaron give Moses for making the golden calf?', '"I cast the gold into the fire, and there came out this calf" — he blamed the result on the fire rather than accepting responsibility', '"The people forced me to do it"', '"God told me to make it"', '"Moses was gone too long"', 'a', 'Exodus 32:24 — "And I said unto them, Whosoever hath any gold, let them break it off. So they gave it to me: then I cast it into the fire, and there came out this calf."'),
('Exodus', 32, 'teens', 2, 'How did Moses intercede for the people before God?', 'He reminded God of His promises to Abraham, Isaac, and Jacob, and asked God not to destroy them — and the LORD repented (relented) of the evil He planned', 'He agreed the people should be destroyed', 'He said nothing', 'He asked to replace them with new people', 'a', 'Exodus 32:11-14 — "And Moses besought the LORD his God... Remember Abraham, Isaac, and Israel, thy servants, to whom thou swarest by thine own self... And the LORD repented of the evil which he thought to do unto his people."'),
('Exodus', 32, 'teens', 3, 'Who rallied to Moses'' side when he said "Who is on the LORD''s side?"', 'All the sons of Levi gathered to him and carried out God''s judgment, slaying about three thousand men', 'All the people came to him', 'No one responded', 'Only Aaron came', 'a', 'Exodus 32:26-28 — "Then Moses stood in the gate of the camp, and said, Who is on the LORD''s side? let him come unto me. And all the sons of Levi gathered themselves together unto him... and there fell of the people that day about three thousand men."'),
('Exodus', 32, 'teens', 4, 'What extraordinary offer did Moses make to God on behalf of the people?', '"If thou wilt forgive their sin—; and if not, blot me, I pray thee, out of thy book which thou hast written" — Moses offered his own eternal destiny for the people', '"Punish me instead of them"', '"Give me a sign"', '"Let me go back to Midian"', 'a', 'Exodus 32:32 — "Yet now, if thou wilt forgive their sin—; and if not, blot me, I pray thee, out of thy book which thou hast written."'),
('Exodus', 32, 'teens', 5, 'What was God''s initial offer to Moses regarding the sinful people?', 'God offered to destroy Israel and make a great nation from Moses instead — but Moses refused this honour and interceded for Israel', 'God offered to forgive everyone immediately', 'God offered to send them all back to Egypt', 'God offered to split them into two groups', 'a', 'Exodus 32:10 — "Now therefore let me alone, that my wrath may wax hot against them, and that I may consume them: and I will make of thee a great nation."'),
-- Adults
('Exodus', 32, 'adults', 1, 'How does Moses'' intercession in chapter 32 foreshadow Christ''s mediatorial work?', 'Moses stands between a holy God and a sinful people, offers his own life, and appeals to God''s covenant promises — prefiguring Christ who is the one mediator (1 Timothy 2:5), offers Himself for sinners, and intercedes based on covenant faithfulness', 'Moses'' intercession has no Christological significance', 'Moses was superior to Christ', 'Christ does not intercede', 'a', 'Exodus 32:11-14,30-32 — Moses'' willingness to be "blotted out" for the people echoes Paul''s wish in Romans 9:3 and ultimately prefigures Christ who "was made a curse for us" (Galatians 3:13). Moses models substitutionary intercession that Christ fulfils perfectly.'),
('Exodus', 32, 'adults', 2, 'What does the golden calf incident reveal about the nature of idolatry?', 'The people did not abandon Yahweh entirely but syncretised — Aaron declared a "feast to the LORD" (32:5) while worshipping through the calf; idolatry often takes the form of worshipping the true God through false means rather than inventing entirely new gods', 'They completely abandoned Yahweh', 'The calf worship was acceptable', 'It was a minor cultural expression', 'a', 'Exodus 32:4-5 — "These be thy gods, O Israel" followed by "To morrow is a feast to the LORD." The most dangerous idolatry is not overt paganism but subtle syncretism — worshipping the right God in the wrong way, blending truth with falsehood.'),
('Exodus', 32, 'adults', 3, 'How does God''s statement "let me alone, that my wrath may wax hot" paradoxically invite intercession?', 'By saying "let me alone," God implicitly reveals that Moses'' intercession can make a difference — if Moses'' prayer were irrelevant, God would not need to tell him to stand aside; the command to desist is actually an invitation to persist', 'God wanted Moses to stop praying', 'Moses'' prayer was unwelcome', 'God had already decided', 'a', 'Exodus 32:10 — "Let me alone" (hannichah li) paradoxically opens the door to intercession. If Moses'' prayer could not change the situation, there would be no need to tell him to step back. God''s "resistance" to intercession is a divine invitation to persist — a pattern seen in Jesus'' parable of the persistent widow.'),
('Exodus', 32, 'adults', 4, 'What does Moses'' breaking of the tablets symbolise?', 'The broken tablets represent the broken covenant — Israel''s idolatry shattered the agreement before it was fully ratified; Moses'' physical act makes visible the spiritual reality that covenant fidelity has been destroyed by Israel''s unfaithfulness', 'Moses was simply angry and clumsy', 'The tablets were accidentally dropped', 'Breaking them was disrespectful to God', 'a', 'Exodus 32:19 — The breaking of the tablets is a prophetic act: the covenant document is destroyed because the covenant has been violated. In ancient Near Eastern practice, breaking a treaty tablet symbolised the treaty''s annulment. Moses makes the invisible spiritual breach physically visible.'),
('Exodus', 32, 'adults', 5, 'What does Aaron''s excuse reveal about the dynamics of failed leadership?', 'Aaron blames the people ("they are set on mischief," v.22), minimises his role ("I cast it into the fire," v.24), and obscures agency ("there came out this calf") — a textbook example of deflection, denial, and abdication of responsibility', 'Aaron was telling the truth', 'Aaron was blameless', 'The people were entirely responsible', 'a', 'Exodus 32:22-24 — Aaron''s excuse employs three evasion tactics: blame-shifting ("thou knowest the people"), minimisation ("I cast it into the fire"), and mystification ("there came out this calf"). Leadership failure begins when those in authority refuse to accept responsibility.'),
('Exodus', 32, 'adults', 6, 'How does Paul use the golden calf incident in 1 Corinthians 10?', 'Paul cites it as a warning against idolatry: "Neither be ye idolaters, as were some of them; as it is written, The people sat down to eat and drink, and rose up to play" (1 Corinthians 10:7) — past failures serve as present warnings', 'Paul never references Exodus 32', 'Paul excuses the golden calf', 'The passage applies only to Israel', 'a', '1 Corinthians 10:6-7,11 — Paul treats the golden calf as a typological warning: "Now these things were our examples... these things happened unto them for ensamples: and they are written for our admonition." Israel''s failure warns the church against repeating the same sins.'),
('Exodus', 32, 'adults', 7, 'What is the significance of the Levites'' action in executing judgment?', 'The Levites'' willingness to judge even their own families demonstrated covenant loyalty above family loyalty — this "ordination" (v.29: "consecrate yourselves today to the LORD") earns them the priestly role, as faithfulness under pressure reveals true dedication', 'The Levites were bloodthirsty', 'It was unjust collective punishment', 'Only Moses wanted the judgment', 'a', 'Exodus 32:26-29 — "Who is on the LORD''s side?" The Levites'' response, even against "son" and "brother," demonstrated absolute covenant loyalty. Moses says "Consecrate yourselves today to the LORD" — their priestly commission was earned through painful faithfulness.'),
('Exodus', 32, 'adults', 8, 'What does Moses'' offer to be "blotted out of thy book" reveal about sacrificial love?', 'Moses'' willingness to surrender his own eternal destiny for the people is the highest form of intercessory love — anticipating Paul''s similar wish (Romans 9:3) and ultimately fulfilled by Christ who was "made sin for us" (2 Corinthians 5:21)', 'Moses was being dramatic', 'The offer was insincere', 'God immediately accepted the offer', 'a', 'Exodus 32:32, Romans 9:3 — Moses'' offer represents substitutionary love: he would rather perish than see his people destroyed. God declines the offer ("Whosoever hath sinned against me, him will I blot out," v.33), but the willingness reveals a Christlike heart.');

-- ═══ Exodus Chapter 33 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 33, 'kids', 1, 'What did Moses ask God to show him?', 'God''s glory — Moses said "I beseech thee, shew me thy glory"', 'The Promised Land', 'The golden calf', 'The ten plagues again', 'a', 'Exodus 33:18 — "And he said, I beseech thee, shew me thy glory."'),
('Exodus', 33, 'kids', 2, 'Where did Moses meet and talk with God?', 'In a special tent called the tabernacle of the congregation (tent of meeting) set up outside the camp', 'In his bedroom', 'On a boat', 'Inside a cave', 'a', 'Exodus 33:7-9 — "And Moses took the tabernacle, and pitched it without the camp, afar off from the camp... and the cloudy pillar descended, and stood at the door of the tabernacle, and the LORD talked with Moses."'),
('Exodus', 33, 'kids', 3, 'How did God speak with Moses?', 'Face to face, as a man speaketh unto his friend', 'Only in dreams', 'Only through other people', 'Only through thunder', 'a', 'Exodus 33:11 — "And the LORD spake unto Moses face to face, as a man speaketh unto his friend."'),
-- Teens
('Exodus', 33, 'teens', 1, 'Why was Moses concerned about continuing the journey without God''s personal presence?', 'Moses said without God''s presence, Israel would be no different from any other nation — "wherein shall it be known here that I and thy people have found grace in thy sight?"', 'He was worried about food', 'He was afraid of wild animals', 'He wanted to return to Egypt', 'a', 'Exodus 33:15-16 — "And he said unto him, If thy presence go not with me, carry us not up hence. For wherein shall it be known here that I and thy people have found grace in thy sight? is it not in that thou goest with us?"'),
('Exodus', 33, 'teens', 2, 'What did God say when Moses asked to see His glory?', '"Thou canst not see my face: for there shall no man see me, and live" — but God would show Moses His goodness and proclaim His name', 'He immediately showed His full glory', 'He refused completely', 'He told Moses to ask again later', 'a', 'Exodus 33:20 — "And he said, Thou canst not see my face: for there shall no man see me, and live."'),
('Exodus', 33, 'teens', 3, 'How did God protect Moses while showing him His glory?', 'God placed Moses in a cleft of the rock and covered him with His hand while He passed by — Moses could see God''s back but not His face', 'Moses wore special clothing', 'Moses closed his eyes', 'God sent an angel instead', 'a', 'Exodus 33:22-23 — "And it shall come to pass, while my glory passeth by, that I will put thee in a clift of the rock, and will cover thee with my hand while I pass by: And I will take away mine hand, and thou shalt see my back parts; but my face shall not be seen."'),
('Exodus', 33, 'teens', 4, 'What did God say He would do regarding Moses'' request for His presence?', '"My presence shall go with thee, and I will give thee rest" — God agreed to personally accompany Israel', '"Send an angel instead"', '"I will come later"', '"You must go alone"', 'a', 'Exodus 33:14 — "And he said, My presence shall go with thee, and I will give thee rest."'),
('Exodus', 33, 'teens', 5, 'What did the people do when they saw the pillar of cloud at the tent of meeting?', 'All the people rose up and worshipped, every man in his tent door', 'They ignored it', 'They complained', 'They ran away', 'a', 'Exodus 33:10 — "And all the people saw the cloudy pillar stand at the tabernacle door: and all the people rose up and worshipped, every man in his tent door."'),
-- Adults
('Exodus', 33, 'adults', 1, 'What does "face to face, as a man speaketh unto his friend" (33:11) mean in light of "thou canst not see my face" (33:20)?', 'The phrases describe different aspects of divine encounter — "face to face" denotes intimate, direct communication (not through dreams or visions), while "cannot see my face" refers to the unmediated fullness of divine glory; Moses experienced unprecedented closeness without seeing the beatific vision', 'The text contradicts itself', 'Moses literally saw God''s face', 'Neither phrase is literal', 'a', 'Exodus 33:11,20 — "Face to face" (panim el panim) describes the quality of relationship — intimate, direct, personal — not literal visual apprehension of God''s essence. Numbers 12:8 adds "mouth to mouth... not in dark speeches, and the similitude of the LORD shall he behold."'),
('Exodus', 33, 'adults', 2, 'How does Moses'' plea "shew me thy glory" represent the deepest human longing?', 'It expresses the ultimate desire of the redeemed heart — not merely for God''s gifts or guidance but for God Himself; Moses has the promised land, the covenant, the law, yet craves something more: direct encounter with God''s glory', 'Moses was simply curious', 'He wanted power', 'He wanted to impress the people', 'a', 'Exodus 33:18 — "Shew me thy glory." Moses had unique access to God yet yearned for more. This insatiable desire for God''s presence is the hallmark of true spirituality — Augustine: "Thou hast made us for Thyself, and our heart is restless until it rests in Thee."'),
('Exodus', 33, 'adults', 3, 'What does the cleft of the rock symbolise in Christian theology?', 'The rock provides both a vantage point and shelter — God''s hand covers Moses while glory passes, showing that God graciously accommodates human limitation; the rock (Christ, 1 Corinthians 10:4) becomes the place where we are both hidden and revealed to God', 'The rock was coincidental geography', 'Moses chose the rock himself', 'The cleft has no symbolism', 'a', 'Exodus 33:22 — "I will put thee in a clift of the rock." The rock as refuge is a major biblical motif: Psalm 18:2, 31:3, 61:2. Paul identifies the rock as Christ (1 Corinthians 10:4). Believers are hidden "in Christ" (Colossians 3:3) — sheltered from glory that would otherwise consume.'),
('Exodus', 33, 'adults', 4, 'Why does God say "I will be gracious to whom I will be gracious" (33:19)?', 'It asserts divine sovereignty in showing mercy — God''s grace is not compelled by human merit or negotiation but flows from His free will; Paul quotes this in Romans 9:15 to demonstrate that salvation depends on God''s initiative, not human effort', 'It limits God''s mercy to Israel', 'It contradicts God''s universal love', 'Paul misuses the quote', 'a', 'Exodus 33:19, Romans 9:15 — "I will have mercy on whom I will have mercy, and I will have compassion on whom I will have compassion." This affirms divine freedom: God''s mercy is sovereign, not earned. Paul uses it to establish that salvation is by grace, not works (Romans 9:16).'),
('Exodus', 33, 'adults', 5, 'What does the tent of meeting "outside the camp" (33:7) signify after the golden calf?', 'After the golden calf, God''s presence withdrew from the center of the camp to outside it — symbolising the disrupted relationship; Moses must go outside to meet God, demonstrating that sin creates distance between God and His people', 'It was simply a new arrangement', 'The tent was always outside', 'The camp was too crowded', 'a', 'Exodus 33:7 — "Moses took the tabernacle, and pitched it without the camp, afar off from the camp." This relocation dramatises the relational fracture: before the golden calf, God dwelt among them; after, He is at a distance. The tent''s position mirrors the state of the covenant.'),
('Exodus', 33, 'adults', 6, 'How does Moses'' argument in 33:15-16 define what makes Israel unique?', 'Israel''s distinctiveness is not their law, their land, or their culture but God''s presence — without it, they are indistinguishable from the nations; this defines Israel''s identity theologically rather than ethnically or politically', 'Their military strength made them unique', 'Their wealth set them apart', 'Their ancestry was sufficient', 'a', 'Exodus 33:16 — "Is it not in that thou goest with us? so shall we be separated, I and thy people, from all the people that are upon the face of the earth." Moses identifies God''s presence as the sole distinctive. This is the church''s identity too — not programs, buildings, or culture, but God''s manifest presence.'),
('Exodus', 33, 'adults', 7, 'What does "thou shalt see my back parts; but my face shall not be seen" teach about the nature of knowing God?', 'We can know God truly but not exhaustively — we see the effects of His passing (His "back") but cannot grasp the totality of His being (His "face"); divine knowledge is real but always partial, inviting humility in theology', 'We can know God completely', 'We cannot know God at all', 'The distinction is meaningless', 'a', 'Exodus 33:23 — The distinction between face and back suggests that God reveals Himself in aftermath — in what He has done — while His full essential glory remains beyond human capacity. We theologise from effects (back) not from essence (face) — genuine but limited knowledge.'),
('Exodus', 33, 'adults', 8, 'How does the "I know thee by name" exchange (33:12,17) model the covenant relationship?', 'God knowing Moses "by name" indicates intimate personal election; Moses'' request to "know thy ways" and see God''s glory seeks reciprocal knowledge; the covenant is fundamentally about mutual knowing — God knowing His people and His people knowing God (Jeremiah 31:34)', 'It was a formal greeting', 'Only Moses was known by name', 'The exchange was diplomatic', 'a', 'Exodus 33:12,17 — "I know thee by name, and thou hast also found grace in my sight." The language of "knowing" defines covenant: Amos 3:2 ("You only have I known of all the families of the earth"). Covenant is personal, intimate, named relationship.');

-- ═══ Exodus Chapter 34 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 34, 'kids', 1, 'What did God tell Moses to bring up the mountain again?', 'Two new stone tablets like the first ones — God would write the commandments on them again', 'A golden cup', 'A lamb for sacrifice', 'A basket of bread', 'a', 'Exodus 34:1 — "And the LORD said unto Moses, Hew thee two tables of stone like unto the first: and I will write upon these tables the words that were in the first tables, which thou brakest."'),
('Exodus', 34, 'kids', 2, 'What happened to Moses'' face after talking with God?', 'His face was shining so brightly that the people were afraid to come near him', 'It turned red', 'It got very dark', 'Nothing changed', 'a', 'Exodus 34:29-30 — "And it came to pass, when Moses came down from mount Sinai... that Moses wist not that the skin of his face shone while he talked with him. And when Aaron and all the children of Israel saw Moses, behold, the skin of his face shone; and they were afraid to come nigh him."'),
('Exodus', 34, 'kids', 3, 'What did Moses put over his face after speaking God''s words?', 'A veil — he covered his face because it was shining so brightly', 'A hat', 'A mask', 'A scarf', 'a', 'Exodus 34:33 — "And till Moses had done speaking with them, he put a vail on his face."'),
-- Teens
('Exodus', 34, 'teens', 1, 'What did God proclaim about His own character when He passed before Moses?', '"The LORD, The LORD God, merciful and gracious, longsuffering, and abundant in goodness and truth, keeping mercy for thousands, forgiving iniquity and transgression and sin"', '"I am a God of judgment only"', '"I am the God of power"', '"I am unknowable"', 'a', 'Exodus 34:6-7 — "And the LORD passed by before him, and proclaimed, The LORD, The LORD God, merciful and gracious, longsuffering, and abundant in goodness and truth."'),
('Exodus', 34, 'teens', 2, 'What warning did God give about making covenants with the people of the Promised Land?', 'Do not make a covenant with them or they will become a snare — destroy their altars, break their images, and cut down their groves', '"Trade freely with them"', '"Intermarry with them"', '"Learn their customs"', 'a', 'Exodus 34:12-13 — "Take heed to thyself, lest thou make a covenant with the inhabitants of the land whither thou goest, lest it be for a snare in the midst of thee: But ye shall destroy their altars, break their images, and cut down their groves."'),
('Exodus', 34, 'teens', 3, 'What did God say about Himself regarding idolatry?', '"For thou shalt worship no other god: for the LORD, whose name is Jealous, is a jealous God"', '"I am indifferent to other gods"', '"Other gods have some power"', '"You may worship others sometimes"', 'a', 'Exodus 34:14 — "For thou shalt worship no other god: for the LORD, whose name is Jealous, is a jealous God."'),
('Exodus', 34, 'teens', 4, 'How long was Moses on the mountain the second time?', 'Forty days and forty nights — again without eating bread or drinking water', 'Seven days', 'Ten days', 'Three days', 'a', 'Exodus 34:28 — "And he was there with the LORD forty days and forty nights; he did neither eat bread, nor drink water. And he wrote upon the tables the words of the covenant, the ten commandments."'),
('Exodus', 34, 'teens', 5, 'What three times a year were all Israelite men required to appear before God?', 'The Feast of Unleavened Bread, the Feast of Weeks (Firstfruits), and the Feast of Ingathering (Tabernacles)', 'Once a year on Passover only', 'Every Sabbath', 'Once in their lifetime', 'a', 'Exodus 34:22-23 — "And thou shalt observe the feast of weeks, of the firstfruits of wheat harvest, and the feast of ingathering at the year''s end. Thrice in the year shall all your men children appear before the Lord GOD, the God of Israel."'),
-- Adults
('Exodus', 34, 'adults', 1, 'Why is Exodus 34:6-7 considered the most important self-revelation of God in the Old Testament?', 'It is the fullest divine self-description in the OT — God defines His character by His own proclamation; this passage is quoted or alluded to more than any other in the OT (Numbers 14:18, Nehemiah 9:17, Psalm 86:15, Joel 2:13, Jonah 4:2, Nahum 1:3), making it the theological center of Israel''s understanding of God', 'It is rarely referenced', 'Other passages are more important', 'It is merely one description among many', 'a', 'Exodus 34:6-7 — This passage (the "Thirteen Attributes of Mercy" in Jewish tradition) is the most frequently cited OT text by other OT authors. It defines the character of God around which all theology orbits: mercy, grace, patience, covenant faithfulness, and justice.'),
('Exodus', 34, 'adults', 2, 'How does God''s name "Jealous" (Qanna) function theologically?', 'Divine jealousy is not petty envy but covenant passion — as a husband is rightly jealous for exclusive devotion from his wife, God demands exclusive worship because He is exclusively worthy; jealousy here is a virtue, not a vice', 'God''s jealousy is a flaw', 'It contradicts God''s love', 'It applies only to Sinai', 'a', 'Exodus 34:14 — "The LORD, whose name is Jealous (Qanna), is a jealous God." Biblical jealousy (qin''ah) is righteous zeal for exclusive covenant loyalty. It is the proper response of infinite love betrayed by idolatrous infidelity (Hosea uses marriage as the metaphor).'),
('Exodus', 34, 'adults', 3, 'How does Paul interpret Moses'' veil in 2 Corinthians 3:7-18?', 'Paul says the veil symbolises the fading nature of the old covenant glory — Moses veiled his face so Israel would not see the glory fading; the veil also represents Israel''s spiritual blindness to Christ, removed only through faith in Him', 'Paul ignores the veil entirely', 'Paul says the veil was permanent', 'The veil had no allegorical meaning', 'a', '2 Corinthians 3:13-16 — "Moses, which put a vail over his face, that the children of Israel could not stedfastly look to the end of that which is abolished... But when it shall turn to the Lord, the vail shall be taken away." Paul uses the veil as an extended metaphor for old covenant blindness versus new covenant clarity.'),
('Exodus', 34, 'adults', 4, 'What is the theological tension in "forgiving iniquity" yet "will by no means clear the guilty" (34:7)?', 'God is simultaneously merciful and just — He forgives but does not ignore sin; this tension is resolved at the cross where God''s justice punishes sin in Christ while His mercy forgives the sinner, satisfying both attributes simultaneously', 'It is a contradiction', 'Justice overrides mercy', 'Mercy cancels justice', 'a', 'Exodus 34:7 — The same God who "forgiveth iniquity and transgression and sin" also "will by no means clear the guilty." This is the great problem of theology: how can God be both just and the justifier of sinners? Romans 3:26 answers: "through the redemption that is in Christ Jesus."'),
('Exodus', 34, 'adults', 5, 'What does Moses'' shining face teach about spiritual transformation?', 'Prolonged communion with God produces visible transformation — Moses'' radiance was the by-product, not the goal, of intimacy with God; 2 Corinthians 3:18 extends this to all believers who "are changed into the same image from glory to glory"', 'The shining was temporary and meaningless', 'Only Moses could shine', 'It was a physical condition', 'a', 'Exodus 34:29, 2 Corinthians 3:18 — Moses'' face shone because of proximity to God. Paul generalises: all believers "with open face beholding as in a glass the glory of the Lord, are changed into the same image from glory to glory." Spiritual transformation results from sustained divine encounter.'),
('Exodus', 34, 'adults', 6, 'How does the second set of tablets represent covenant renewal?', 'The first tablets (broken) symbolised the broken covenant; the second tablets (intact) symbolise covenant restoration — God''s willingness to rewrite the covenant demonstrates grace that persists despite human failure; the covenant is renewed, not abandoned', 'The second set was identical in every way', 'The new covenant replaced the old completely', 'God was reluctant to make new tablets', 'a', 'Exodus 34:1 — "Hew thee two tables of stone like unto the first." The replacement tablets are a physical sign of covenant renewal — grace after judgment. Notably, Moses must cut the stones (human effort), but God writes the words (divine authority). Restoration requires both divine initiative and human response.'),
('Exodus', 34, 'adults', 7, 'What does the prohibition against intermarriage with Canaanites (34:15-16) protect?', 'It guards covenant fidelity — the concern is not ethnic but religious: Canaanite spouses would lead Israel into idolatry (as happened with Solomon, 1 Kings 11:1-4); the prohibition protects Israel''s exclusive worship of Yahweh, not ethnic purity', 'It was about racial purity', 'It was about economic protection', 'It applied to all foreigners equally', 'a', 'Exodus 34:15-16 — "Lest thou make a covenant with the inhabitants of the land, and they go a whoring after their gods... And thou take of their daughters unto thy sons, and their daughters go a whoring after their gods." The issue is theological, not ethnic — as proven by Rahab and Ruth joining Israel through faith.'),
('Exodus', 34, 'adults', 8, 'How do the "Thirteen Attributes of Mercy" (34:6-7) shape Jewish liturgical tradition?', 'These attributes are recited in synagogue worship during the High Holy Days and whenever the Torah scroll is removed — they form the core of Jewish penitential prayer (Selichot) and express confidence in God''s forgiving nature even after the greatest sin (the golden calf)', 'They are not used in Jewish worship', 'Only rabbis recite them', 'They were abandoned after the exile', 'a', 'Exodus 34:6-7 — The Shelosh Esreh Middot (Thirteen Attributes) are central to Jewish liturgy, especially on Yom Kippur. Their context — God''s self-revelation after the golden calf — gives them power: God revealed His deepest character at the moment of Israel''s deepest failure.');

-- ═══ Exodus Chapter 35 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 35, 'kids', 1, 'What did Moses ask the people to bring for building the tabernacle?', 'Willing offerings — gold, silver, brass, coloured fabrics, wood, oil, spices, and gemstones', 'Only money', 'Only food', 'Nothing at all', 'a', 'Exodus 35:5 — "Take ye from among you an offering unto the LORD: whosoever is of a willing heart, let him bring it."'),
('Exodus', 35, 'kids', 2, 'Who brought offerings for the tabernacle?', 'Everyone whose heart was willing — both men and women brought bracelets, earrings, rings, gold, fabrics, and precious materials', 'Only the rich people', 'Only the priests', 'Only the leaders', 'a', 'Exodus 35:21-22 — "And they came, every one whose heart stirred him up, and every one whom his spirit made willing, and they brought the LORD''s offering."'),
('Exodus', 35, 'kids', 3, 'What special skill did some women contribute?', 'They spun yarn with their hands — making the blue, purple, scarlet, and fine linen fabrics needed for the tabernacle', 'They cooked food', 'They sang songs', 'They wrote stories', 'a', 'Exodus 35:25-26 — "And all the women that were wise hearted did spin with their hands, and brought that which they had spun... And all the women whose heart stirred them up in wisdom spun goats'' hair."'),
-- Teens
('Exodus', 35, 'teens', 1, 'What did Moses say about the Sabbath before discussing the tabernacle?', '"Six days shall work be done, but on the seventh day there shall be to you an holy day, a sabbath of rest to the LORD: whosoever doeth work therein shall be put to death"', '"Work on the Sabbath if needed for the tabernacle"', '"The Sabbath is optional during construction"', '"Only priests rest on the Sabbath"', 'a', 'Exodus 35:2 — "Six days shall work be done, but on the seventh day there shall be to you an holy day, a sabbath of rest to the LORD."'),
('Exodus', 35, 'teens', 2, 'What motivated the people to give?', 'Their hearts were stirred and their spirits were willing — they gave freely out of devotion to God', 'They were forced by Moses', 'They were promised rewards', 'They were competing with each other', 'a', 'Exodus 35:21 — "And they came, every one whose heart stirred him up, and every one whom his spirit made willing."'),
('Exodus', 35, 'teens', 3, 'What did Moses say God had done for Bezaleel?', 'God had filled him with the Spirit of God, in wisdom, understanding, knowledge, and all manner of workmanship — and given him the ability to teach others', 'God made him the richest man', 'God gave him magical powers', 'God made him a priest', 'a', 'Exodus 35:31,34 — "And he hath filled him with the spirit of God, in wisdom, in understanding, and in knowledge... And he hath put in his heart that he may teach."'),
('Exodus', 35, 'teens', 4, 'What specific prohibition about the Sabbath is added in this chapter?', '"Ye shall kindle no fire throughout your habitations upon the sabbath day" — even fire-making was prohibited', 'No eating on the Sabbath', 'No talking on the Sabbath', 'No sleeping on the Sabbath', 'a', 'Exodus 35:3 — "Ye shall kindle no fire throughout your habitations upon the sabbath day."'),
('Exodus', 35, 'teens', 5, 'What leadership role did the rulers (princes) of Israel play?', 'They brought the onyx stones and gemstones for the ephod and breastplate, along with spices and oil — providing the most expensive materials', 'They supervised the workers', 'They did no work at all', 'They only contributed labour', 'a', 'Exodus 35:27-28 — "And the rulers brought onyx stones, and stones to be set, for the ephod, and for the breastplate; And spice, and oil for the light, and for the anointing oil, and for the sweet incense."'),
-- Adults
('Exodus', 35, 'adults', 1, 'How does the voluntary nature of giving in chapter 35 inform biblical principles of stewardship?', 'The pattern establishes that true worship offering flows from a "stirred heart" and "willing spirit" — compelled giving is not worship; Paul later echoes this: "not grudgingly, or of necessity: for God loveth a cheerful giver" (2 Corinthians 9:7)', 'Tithing was mandatory regardless', 'Heart attitude was irrelevant', 'Only large gifts mattered', 'a', 'Exodus 35:21-29 — The emphasis on willing hearts (lev nadiv) establishes the theology of voluntary generosity. This is not taxation but worship — the overflow of hearts moved by God''s grace. The model informs all subsequent biblical teaching on giving.'),
('Exodus', 35, 'adults', 2, 'What is the significance of both men and women contributing to the tabernacle?', 'It demonstrates that God''s dwelling is built by the entire community — women''s spinning (v.25-26), men''s skilled work, rulers'' gemstones, and everyone''s gifts all contribute; no one is excluded from the privilege and responsibility of building God''s house', 'Only men contributed', 'Women''s contributions were secondary', 'The text does not mention women', 'a', 'Exodus 35:22,25-26,29 — Women are explicitly mentioned bringing jewellery and spinning fabric. The phrase "both men and women" (v.22) and "every man and woman" (v.29) emphasises universal participation. God''s house requires every member''s gifts.'),
('Exodus', 35, 'adults', 3, 'How does the ability to teach (35:34) expand the understanding of spiritual gifting?', 'Bezaleel was given not only the skill to create but also the ability to instruct others — the gift includes multiplication; true spiritual gifts are not merely for personal use but for equipping others, anticipating Ephesians 4:11-12', 'Teaching was not part of his gift', 'Only prophets could teach', 'Skills were not transferable', 'a', 'Exodus 35:34 — "He hath put in his heart that he may teach." The gift of teaching extends craftsmanship beyond Bezaleel — God wants the skills multiplied. This models Ephesians 4:12: gifts are given "for the perfecting of the saints, for the work of the ministry."'),
('Exodus', 35, 'adults', 4, 'Why does chapter 35 repeat the Sabbath command yet again before tabernacle construction begins?', 'The Sabbath-then-building sequence is a structural pattern: chs.25-31 end with Sabbath before the golden calf; ch.35 begins with Sabbath before construction; the repetition reinforces that no work — even God''s work — supersedes God''s rest', 'The repetition is editorial redundancy', 'The Sabbath was forgotten', 'It was inserted from another source', 'a', 'The Sabbath bookends frame the entire tabernacle section: 31:12-17 (before sin) and 35:1-3 (after restoration). This literary structure teaches that Sabbath observance is the context for, not an interruption to, sacred work.'),
('Exodus', 35, 'adults', 5, 'How does the outpouring of generosity in chapter 35 contrast with the golden calf?', 'The same people who gave gold for the calf (32:2-3) now give gold for the tabernacle (35:22) — demonstrating that redeemed hearts redirect their resources from idolatry to worship; the same material (gold) can serve either destruction or devotion', 'The people were different', 'No gold was used for the calf', 'There is no connection', 'a', 'Exodus 32:2-3 vs. 35:22 — Gold earrings torn off for the calf now become offerings for the tabernacle. The same wealth, the same people, but transformed hearts. This dramatic contrast teaches that conversion redirects existing resources toward God''s purposes.'),
('Exodus', 35, 'adults', 6, 'What does the fire prohibition on the Sabbath (35:3) contribute to Sabbath theology?', 'Kindling fire required substantial labour in the ancient world (gathering fuel, using friction tools) — this prohibition eliminated the primary domestic work, ensuring genuine rest; it also prevented the argument that tabernacle metalwork could continue on the Sabbath', 'It was about fire safety', 'Only ceremonial fires were prohibited', 'The prohibition was impractical', 'a', 'Exodus 35:3 — "Ye shall kindle no fire throughout your habitations upon the sabbath day." Since tabernacle construction involved metalwork requiring fire, this prohibition explicitly prevents using sacred work as an excuse for Sabbath violation.'),
('Exodus', 35, 'adults', 7, 'How does the repetition of construction instructions in chapters 35-39 serve a literary purpose?', 'The near-verbatim repetition of chapters 25-31 in 35-39 demonstrates exact obedience — what God commanded was precisely what Israel built; the literary correspondence teaches that faithful execution matches divine instruction point by point', 'The repetition is editing error', 'It was for readers who missed earlier chapters', 'It fills space arbitrarily', 'a', 'Chapters 35-39 mirror 25-31 because the narrative makes a theological point through literary structure: God speaks (25-31), sin interrupts (32-34), then obedient construction restores the plan (35-39). The match between command and execution demonstrates covenant faithfulness restored.'),
('Exodus', 35, 'adults', 8, 'What does the phrase "wise hearted" (chakham lev) reveal about the biblical concept of wisdom?', 'Biblical wisdom is not merely intellectual but involves the heart — skilled craftswomen are called "wise hearted" (35:25), showing that wisdom in Scripture includes practical skill, artistic ability, and manual dexterity; wisdom is embodied competence, not just abstract knowledge', 'Wisdom applies only to theology', 'Practical skills are not wisdom', 'Heart and mind are separate', 'a', 'Exodus 35:25 — "All the women that were wise hearted (chakhmot lev) did spin." Hebrew wisdom (chokmah) is broader than intellect: it includes artistic skill (31:3), practical ability (35:25), and ethical discernment (Proverbs 1:7). Biblical wisdom is holistic — head, heart, and hands.');

-- ═══════════════ CHAPTERS 36–40 ═══════════════

-- ═══ Exodus Chapter 36 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 36, 'kids', 1, 'Did the people bring enough materials for building the tabernacle?', 'They brought too much! Moses had to tell them to stop giving because there was more than enough', 'They did not bring enough', 'They brought exactly the right amount', 'They had to buy more from other nations', 'a', 'Exodus 36:5-7 — "The people bring much more than enough for the service of the work... So the people were restrained from bringing. For the stuff they had was sufficient for all the work to make it, and too much."'),
('Exodus', 36, 'kids', 2, 'What did the skilled workers begin to make first?', 'The beautiful curtains of the tabernacle — with cherubim woven in blue, purple, and scarlet', 'A golden throne', 'A stone wall', 'A wooden house', 'a', 'Exodus 36:8 — "And every wise hearted man among them that wrought the work of the tabernacle made ten curtains of fine twined linen, and blue, and purple, and scarlet: with cherubims of cunning work made he them."'),
('Exodus', 36, 'kids', 3, 'Who led the construction work?', 'Bezaleel and Aholiab, along with every wise-hearted person whom God had gifted', 'Moses built everything himself', 'Aaron directed the work', 'The elders did it all', 'a', 'Exodus 36:1-2 — "Then wrought Bezaleel and Aholiab, and every wise hearted man, in whom the LORD put wisdom and understanding."'),
-- Teens
('Exodus', 36, 'teens', 1, 'What remarkable problem did Moses face with the offerings?', 'He had to issue a command to stop giving because the people had given far more than needed — an overflow of generosity', 'No one was giving anything', 'People were giving the wrong materials', 'The offerings were being stolen', 'a', 'Exodus 36:6 — "And Moses gave commandment, and they caused it to be proclaimed throughout the camp, saying, Let neither man nor woman make any more work for the offering of the sanctuary. So the people were restrained from bringing."'),
('Exodus', 36, 'teens', 2, 'How did the construction of the tabernacle curtains follow God''s instructions?', 'Exactly as God specified — ten curtains of fine linen with cherubim, joined in two sets of five by fifty gold clasps', 'They modified the design slightly', 'They used different colours', 'They made fewer curtains', 'a', 'Exodus 36:8-13 — The construction precisely mirrors the instructions of chapter 26, demonstrating careful obedience.'),
('Exodus', 36, 'teens', 3, 'What materials were used for the four layers of covering?', 'Inner: fine linen with cherubim; second: goats'' hair curtains; third: rams'' skins dyed red; outer: badgers'' skins', 'One layer of gold cloth', 'Animal skins only', 'Wooden boards only', 'a', 'Exodus 36:8,14,19 — Four coverings as specified in chapter 26.'),
('Exodus', 36, 'teens', 4, 'What held the wooden boards of the tabernacle upright?', 'Silver sockets — two under each board, providing a stable foundation', 'Stone pedestals', 'Iron stakes', 'Sand and gravel', 'a', 'Exodus 36:24 — "And forty sockets of silver he made under the twenty boards."'),
('Exodus', 36, 'teens', 5, 'What was the veil made of, and what was its purpose?', 'Blue, purple, scarlet, and fine linen with cherubim — it separated the Holy Place from the Most Holy Place', 'Plain white cloth', 'Goats'' hair only', 'Animal skins', 'a', 'Exodus 36:35 — "And he made a vail of blue, and purple, and scarlet, and fine twined linen: with cherubims made he it of cunning work."'),
-- Adults
('Exodus', 36, 'adults', 1, 'What does the overflow of giving (36:5-7) teach about the relationship between grace and generosity?', 'Hearts transformed by covenant renewal (ch.34) produce abundance — the overflow is evidence of genuine revival; when God''s grace moves hearts, the practical result is sacrificial generosity that exceeds the need', 'The people were coerced', 'The overflow was coincidental', 'Generosity proves nothing about spiritual state', 'a', 'Exodus 36:5-7 — The overflow stands in deliberate contrast to the golden calf episode: the same people who eagerly gave gold for an idol now overflow with gifts for God. True spiritual renewal manifests in transformed stewardship.'),
('Exodus', 36, 'adults', 2, 'How does the command to stop giving contrast with typical human religious experience?', 'In most religious contexts, leaders plead for more giving — here Moses must command people to stop; this unique situation demonstrates the power of Spirit-motivated generosity versus guilt-driven obligation', 'This situation was normal', 'Moses wanted more', 'The people were wasteful', 'a', 'Exodus 36:6 — "Moses gave commandment... Let neither man nor woman make any more work for the offering." This is perhaps the only recorded instance of a spiritual leader telling people to stop giving. It testifies to the extraordinary spiritual state of the people after covenant renewal.'),
('Exodus', 36, 'adults', 3, 'What does the phrase "as the LORD commanded Moses" (repeated throughout chapters 36-39) establish?', 'It is a refrain of obedience — appearing approximately 18 times in these chapters, it corresponds to God''s creative commands in Genesis 1 ("and God said"), suggesting that tabernacle construction is a new creation narrative paralleling the original', 'It is a redundant editorial note', 'It was added by later editors', 'It has no structural significance', 'a', 'The repetition of "as the LORD commanded Moses" in the construction narrative parallels "and God said" in Genesis 1. Both are creative acts of divine speech fulfilled in material reality. The tabernacle is a microcosm — a new creation in miniature.'),
('Exodus', 36, 'adults', 4, 'How do chapters 36-39 function as a literary parallel to Genesis 1?', 'Both move from divine speech to material reality: God speaks the design (chs.25-31, cf. Genesis 1:3ff), then it is constructed exactly as spoken (chs.36-39, cf. Genesis 1); both end with divine inspection and approval ("God saw that it was good" / "Moses blessed them")', 'There is no connection to Genesis', 'The parallel is modern invention', 'Only the Sabbath connects them', 'a', 'The creation-tabernacle parallel is extensively documented: (1) both begin with divine speech, (2) both are completed, (3) both end with divine/human blessing, (4) both conclude with rest/Sabbath. The tabernacle is the restoration of Eden — God dwelling with His people.'),
('Exodus', 36, 'adults', 5, 'What is the theological significance of the exact correspondence between instruction and construction?', 'Precise obedience demonstrates that worship must conform to God''s pattern, not human innovation — the tabernacle is God''s design, and human creativity serves rather than replaces divine instruction; this underlies the regulative principle of worship', 'Approximate obedience was sufficient', 'Creative additions were encouraged', 'The correspondence is coincidental', 'a', 'The instruction-execution correspondence (chs.25-31 ≈ chs.35-39) teaches the regulative principle: God determines acceptable worship. Human skill and creativity (Bezaleel''s artistry) operate within divine parameters, not outside them.'),
('Exodus', 36, 'adults', 6, 'How does the community-wide participation in construction reflect ecclesiology?', 'Every member contributes according to their gift — craftsmen build, women spin, rulers provide gemstones, all give materials; no single person or class builds God''s house; this anticipates Paul''s body metaphor where every member is essential (1 Corinthians 12)', 'Only professionals built the tabernacle', 'Women were excluded', 'The rulers did everything', 'a', 'The tabernacle is built by the entire community: wise-hearted craftsmen (36:1), spinning women (35:25), generous donors (35:21-29), and princely givers (35:27). This comprehensive participation models the church where "the whole body fitly joined together" builds up itself (Ephesians 4:16).'),
('Exodus', 36, 'adults', 7, 'What does the superabundance of materials (more than enough) picture spiritually?', 'God''s provision through His people always exceeds the need — this is a physical picture of grace that overflows: "God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work" (2 Corinthians 9:8)', 'The excess was wasteful', 'It was poor planning', 'Extra materials were discarded', 'a', 'The surplus (dayam — "enough and too much") demonstrates the principle of divine superabundance. When God moves hearts, the result is more than sufficient. This anticipates the feeding of the 5,000 with twelve baskets left over — God''s economy produces overflow.'),
('Exodus', 36, 'adults', 8, 'How does the construction narrative demonstrate the restoration of Israel after the golden calf?', 'After the covenant crisis (ch.32), renewal (ch.34), and renewed generosity (ch.35), the actual building (ch.36ff) proves that the relationship has been restored — Israel is now doing what God commanded rather than what they devised; obedience has replaced rebellion', 'The construction was unrelated to the golden calf', 'Israel never fully recovered', 'The building was forced', 'a', 'The construction chapters are the narrative proof of restored covenant. The same community that broke the covenant by making the calf now fulfils the covenant by building the tabernacle. Obedient construction is the concrete evidence of genuine repentance and renewal.');

-- ═══ Exodus Chapters 37-39 (combined — construction details) ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Chapter 37: Ark, Table, Candlestick, Incense Altar
-- Kids
('Exodus', 37, 'kids', 1, 'What did Bezaleel make first?', 'The Ark of the Covenant — a chest of acacia wood covered inside and outside with pure gold', 'A golden calf', 'A stone altar', 'A wooden house', 'a', 'Exodus 37:1 — "And Bezaleel made the ark of shittim wood."'),
('Exodus', 37, 'kids', 2, 'How did Bezaleel make the cherubim on the mercy seat?', 'He beat them out of one piece of gold — they were not separate pieces attached later', 'He carved them from wood', 'He moulded them from clay', 'He cut them from stone', 'a', 'Exodus 37:7 — "And he made two cherubims of gold, beaten out of one piece made he them, on the two ends of the mercy seat."'),
('Exodus', 37, 'kids', 3, 'What was the golden candlestick (menorah) made of?', 'One talent of pure gold — the entire candlestick with its branches, cups, and flowers was beaten from a single piece', 'Bronze and silver', 'Wood covered with gold', 'Many pieces of gold welded together', 'a', 'Exodus 37:22-24 — "Their knops and their branches were of the same: all of it was one beaten work of pure gold. And he made his seven lamps.."'),
-- Teens
('Exodus', 37, 'teens', 1, 'What were the rings and staves on the Ark for?', 'For carrying the Ark — poles of acacia wood overlaid with gold were slid through gold rings so the Ark could be transported without touching it', 'For decoration', 'For hanging curtains', 'For tying it to the ground', 'a', 'Exodus 37:3-5 — "And he cast for it four rings of gold... And he made staves of shittim wood, and overlaid them with gold. And he put the staves into the rings by the sides of the ark, to bear the ark."'),
('Exodus', 37, 'teens', 2, 'How many items of golden furniture did Bezaleel make according to this chapter?', 'Four: the Ark with mercy seat, the Table of Shewbread, the Golden Candlestick (menorah), and the Altar of Incense', 'Only two items', 'Six items', 'One item', 'a', 'Exodus 37 records the construction of four golden pieces: Ark (vv.1-9), Table (vv.10-16), Candlestick (vv.17-24), and Incense Altar (vv.25-28).'),
('Exodus', 37, 'teens', 3, 'What vessels did Bezaleel make for the Table of Shewbread?', 'Dishes, spoons, covers, and bowls of pure gold — used for the bread and drink offerings', 'Silver plates', 'Clay pots', 'Bronze cups', 'a', 'Exodus 37:16 — "And he made the vessels which were upon the table, his dishes, and his spoons, and his bowls, and his covers to cover withal, of pure gold."'),
('Exodus', 37, 'teens', 4, 'What special anointing oil and incense did they make?', 'The holy anointing oil and the pure incense of sweet spices, according to the work of the apothecary — exactly as God commanded', 'Common cooking oil and random spices', 'Egyptian perfumes', 'Water and flowers', 'a', 'Exodus 37:29 — "And he made the holy anointing oil, and the pure incense of sweet spices, according to the work of the apothecary."'),
('Exodus', 37, 'teens', 5, 'What floral designs decorated the menorah?', 'Almond blossoms — with knops (buds), flowers, and bowls shaped like almonds on each branch', 'Roses and lilies', 'Olive branches', 'Palm leaves', 'a', 'Exodus 37:19-20 — "Three bowls made after the fashion of almonds in one branch, a knop and a flower... their knops and their branches were of the same."'),
-- Adults
('Exodus', 37, 'adults', 1, 'What is the significance of each tabernacle piece being made by Bezaleel personally?', 'The chapter emphasises Bezaleel by name seven times, connecting the Spirit-filled craftsman to each sacred object — demonstrating that Spirit-empowered work produces sacred results; human hands guided by divine Spirit create what human ingenuity alone cannot', 'Any craftsman could have made them', 'Bezaleel was merely a supervisor', 'The emphasis on Bezaleel is accidental', 'a', 'Exodus 37:1 — "And Bezaleel made..." The personal attribution emphasises that the Spirit filling of 31:3 produces specific, tangible sacred objects. Spirit-filled work is not abstract but practical, producing real things for God''s glory.'),
('Exodus', 37, 'adults', 2, 'Why is the menorah beaten from a single piece of gold rather than assembled from parts?', 'The one-piece construction signifies unity and integrity — like the seamless garment of Christ (John 19:23), the menorah''s wholeness pictures the indivisible nature of divine light; it cannot be broken into components because truth and revelation are unified', 'One piece was stronger structurally', 'Gold was scarce and this saved material', 'Assembly was too difficult', 'a', 'Exodus 37:17,22 — "All of it was one beaten work of pure gold." The artistic unity of the menorah from a single mass of gold pictures the organic unity of divine truth — it cannot be divided into separate pieces without destroying the whole.'),
('Exodus', 37, 'adults', 3, 'How do these construction chapters demonstrate Israel''s recovery from the golden calf?', 'The meticulous craftsmanship proves that gold is now being used rightly — the same metal that was melted for an idol is now fashioned into the Ark, mercy seat, and menorah; redemption transforms resources from serving sin to serving God', 'Gold should never have been used', 'The golden calf was acceptable', 'There is no connection', 'a', 'The gold that once formed a calf (32:4) now forms the mercy seat where God dwells. This transformation of material from idolatrous to sacred use is one of the most powerful images of redemption in the Bible — same material, opposite purpose.'),
('Exodus', 37, 'adults', 4, 'What does the repetitive "as the LORD commanded Moses" accomplish in the narrative?', 'Each occurrence serves as a verification mark — confirming point by point that God''s design has been faithfully executed; the cumulative effect creates a liturgical rhythm of obedience that contrasts sharply with the disobedience of chapter 32', 'It is tedious repetition', 'It was added by a later editor', 'It serves no purpose', 'a', 'The refrain functions like a quality assurance checklist — each "as the LORD commanded" confirms one element of the divine blueprint has been faithfully implemented. The repetition is not boring but beautiful: it is the sound of covenant faithfulness.'),
('Exodus', 37, 'adults', 5, 'How does the almond motif on the menorah connect to Aaron''s rod and the resurrection?', 'The almond (shaqed — "watcher/waker") is the first tree to blossom in spring, symbolising resurrection life; Aaron''s rod budded almonds (Numbers 17:8) confirming his priesthood; Jesus is the "resurrection and the life" — the ultimate blossoming from death', 'Almonds were purely decorative', 'The almond had no symbolic meaning', 'Aaron''s rod is unrelated', 'a', 'The Hebrew shaqed ("almond") sounds like shoqed ("watcher/waker"). Jeremiah 1:11-12 plays on this: "I am watching over my word to perform it." The almond''s early blooming pictures God''s watchful faithfulness and resurrection life.'),
('Exodus', 37, 'adults', 6, 'What theological truth does the incense altar''s gold crown (zer) symbolise?', 'The gold crown (zer zahav) around the incense altar''s top — like the crowns on the Ark and Table — signifies divine royalty; the altar of prayer bears a crown because prayer enters the presence of the King; intercession is audience with royalty', 'The crown was merely a rim to prevent items falling', 'Only the Ark had a crown', 'Crowns were decorative borders', 'a', 'Exodus 37:26 — "He made thereunto a crown of gold round about." All three golden pieces bear crowns (zer): Ark (v.2), Table (v.11), Incense Altar (v.26). The triple crown motif declares God''s sovereignty over covenant (Ark), provision (Table), and prayer (Incense).'),
('Exodus', 37, 'adults', 7, 'How does the construction of the holy anointing oil (37:29) relate to the prohibition against replication?', 'The sacred recipe was made according to the "work of the apothecary" — professional compounding of a unique, irreproducible formula; its exclusivity teaches that God''s consecrating work cannot be humanly replicated; only God can truly set apart', 'The oil could be reproduced', 'It was common perfume', 'Anyone could make it', 'a', 'Exodus 37:29, 30:32-33 — The holy anointing oil and incense were unique sacred compounds whose replication was punishable by excommunication. This exclusivity teaches that divine consecration is inimitable — we cannot manufacture holiness.'),
('Exodus', 37, 'adults', 8, 'What overall theological picture emerges from the complete inventory of golden furniture?', 'Together, the four golden pieces reveal a complete theology: God''s presence and mercy (Ark/mercy seat), God''s provision and fellowship (Table/bread), God''s illumination and truth (Candlestick/light), God''s communion through prayer (Incense Altar) — a comprehensive picture of the life of faith', 'The pieces were randomly designed', 'Only the Ark mattered', 'The other pieces were secondary', 'a', 'The golden furniture provides a complete spiritual anatomy: the Ark (God''s throne/mercy), Table (God''s provision), Candlestick (God''s revelation), Incense Altar (God''s accessibility through prayer). Together they describe the fullness of life with God — presence, sustenance, illumination, and communion.');

-- Chapter 38: Brazen Altar, Laver, Court, Material Inventory
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 38, 'kids', 1, 'What was the big altar in the courtyard made of?', 'Acacia wood covered with brass (bronze) — the altar of burnt offering where animal sacrifices were made', 'Pure gold', 'Silver plates', 'Stone blocks', 'a', 'Exodus 38:1-2 — "And he made the altar of burnt offering of shittim wood... And he overlaid it with brass."'),
('Exodus', 38, 'kids', 2, 'What was the laver (washing basin) made from?', 'The brass mirrors of the women who served at the door of the tabernacle', 'River stones', 'Clay pots', 'Gold bowls', 'a', 'Exodus 38:8 — "And he made the laver of brass, and the foot of it of brass, of the lookingglasses of the women assembling, which assembled at the door of the tabernacle of the congregation."'),
('Exodus', 38, 'kids', 3, 'How much gold was used for the tabernacle?', 'Twenty-nine talents and 730 shekels — an enormous amount of pure gold', 'A tiny amount', 'One bag full', 'No gold was used', 'a', 'Exodus 38:24 — "All the gold that was occupied for the work in all the work of the holy place, even the gold of the offering, was twenty and nine talents, and seven hundred and thirty shekels."'),
-- Teens
('Exodus', 38, 'teens', 1, 'What did the women donate to make the bronze laver?', 'Their polished bronze mirrors — instruments of vanity transformed into instruments of priestly purification', 'Gold earrings', 'Silver bracelets', 'Precious gems', 'a', 'Exodus 38:8 — "The lookingglasses of the women assembling." The mirrors, used for personal beauty, were repurposed for the laver where priests washed — vanity transformed into holiness.'),
('Exodus', 38, 'teens', 2, 'What was the total amount of silver used, and where did it come from?', 'One hundred talents and 1,775 shekels — from the half-shekel atonement money of 603,550 men', 'It was mined in the wilderness', 'It came from Egyptian plunder only', 'It was donated by the rulers', 'a', 'Exodus 38:25-26 — "And the silver of them that were numbered of the congregation was an hundred talents, and a thousand seven hundred and threescore and fifteen shekels... A bekah for every man, that is, half a shekel."'),
('Exodus', 38, 'teens', 3, 'What were the silver sockets used for?', 'The foundation of the tabernacle — one hundred sockets supporting the boards, made from the atonement money', 'Decoration on the altar', 'Coins for trade', 'Covers for the poles', 'a', 'Exodus 38:27 — "And of the hundred talents of silver were cast the sockets of the sanctuary, and the sockets of the vail; an hundred sockets of the hundred talents, a talent for a socket."'),
('Exodus', 38, 'teens', 4, 'How much brass (bronze) was used?', 'Seventy talents and 2,400 shekels — used for the altar, laver, sockets of the court, and all pins and hardware', 'A very small amount', 'More than the gold', 'Less than the silver', 'a', 'Exodus 38:29 — "And the brass of the offering was seventy talents, and two thousand and four hundred shekels."'),
('Exodus', 38, 'teens', 5, 'Who kept the official inventory of all the materials?', 'Ithamar, son of Aaron the priest, directed the Levites who kept the accounts', 'Moses counted everything himself', 'Bezaleel kept the records', 'No records were kept', 'a', 'Exodus 38:21 — "This is the sum of the tabernacle... as it was counted, according to the commandment of Moses, for the service of the Levites, by the hand of Ithamar, son to Aaron the priest."'),
-- Adults
('Exodus', 38, 'adults', 1, 'What is the theological symbolism of women''s mirrors becoming the laver?', 'Objects of self-reflection (vanity/self-focus) are transformed into instruments of purification (service/holiness) — the transformation pictures conversion, where self-centred resources are redirected toward God-centred purposes', 'The mirrors were the only available bronze', 'Women were forced to give them', 'The symbolism is modern invention', 'a', 'Exodus 38:8 — Mirrors of bronze were valuable personal possessions used for self-adornment. Their transformation into the laver (where priests cleansed themselves for service) pictures the Christian call to turn from self-contemplation to self-purification: "Cleanse your hands, ye sinners; and purify your hearts" (James 4:8).'),
('Exodus', 38, 'adults', 2, 'What does the precise material inventory (38:21-31) teach about accountability in sacred work?', 'Every talent and shekel is accounted for — demonstrating financial transparency in religious work; God''s work requires honest stewardship; this inventory establishes the principle that those handling sacred resources must be accountable for every detail', 'The inventory was bureaucratic', 'No one checked the numbers', 'Accountability was unnecessary', 'a', 'Exodus 38:21-31 — The detailed accounting (gold: 29 talents 730 shekels; silver: 100 talents 1,775 shekels; brass: 70 talents 2,400 shekels) establishes transparent stewardship. Those handling God''s resources must account for every unit — a principle for all church and ministry finances.'),
('Exodus', 38, 'adults', 3, 'How does the silver foundation (from atonement money) connect to the doctrine of redemption?', 'The entire tabernacle literally rests on the atonement payments of every counted Israelite — God''s dwelling place is founded on redemption; without atonement, there is no foundation for God to dwell with humanity; this pictures Ephesians 2:20: built upon the foundation of the apostles and prophets, with Christ as the cornerstone', 'The foundation was merely structural', 'Silver was the strongest available metal', 'Atonement money was unrelated', 'a', 'Exodus 38:25-27 — 100 silver talents from 603,550 men''s ransom = the foundation. The tabernacle''s entire structure rests on redemption money. Similarly, the church is built on Christ''s redemptive work — without the cross, there is no dwelling of God with humanity.'),
('Exodus', 38, 'adults', 4, 'What can be estimated about the value and weight of the tabernacle materials?', 'Approximately 2,200 pounds of gold, 7,500 pounds of silver, and 5,300 pounds of bronze — representing an enormous wealth concentration, all voluntarily given, demonstrating both the plunder of Egypt and Israel''s extraordinary generosity', 'The amounts were exaggerated', 'Very little material was used', 'Only the gold was valuable', 'a', 'The material totals represent staggering wealth: gold (~1 metric ton), silver (~3.4 metric tons), bronze (~2.4 metric tons). This wealth, largely from the plunder of Egypt (12:35-36), was voluntarily redirected from personal use to sacred purpose — Egypt''s riches serving Israel''s God.'),
('Exodus', 38, 'adults', 5, 'How does the 603,550 census number connect the material inventory to Israel''s corporate identity?', 'Each counted man''s half-shekel is embedded in the tabernacle''s foundation — literally, every Israelite is built into God''s dwelling; the tabernacle is not an impersonal structure but a corporate expression of the entire redeemed community', 'The number was approximate', 'Not all contributed', 'The census was unrelated to the tabernacle', 'a', 'Exodus 38:26 — 603,550 men each contributing a half-shekel means every counted Israelite has a personal stake in the tabernacle''s foundation. This pictures the New Testament truth that believers are "living stones" built into a spiritual house (1 Peter 2:5).'),
('Exodus', 38, 'adults', 6, 'What does the brass (bronze) altar''s prominence as the first and largest piece teach?', 'The altar of burnt offering is the gateway piece — largest, most visible, first encountered; its brass (judgment) material and sacrificial function establish that the way to God begins with atoning sacrifice, not prayer (incense), illumination (lamp), or even God''s word (shewbread)', 'The altar was secondary to the Ark', 'Its size was arbitrary', 'Bronze was cheaper', 'a', 'The brazen altar''s size (5×5×3 cubits — the largest piece), material (bronze/judgment), and position (first upon entry) make a theological statement: atonement is the prerequisite for everything else. No one approaches the golden furniture without first passing the place of sacrifice.'),
('Exodus', 38, 'adults', 7, 'What is the significance of Ithamar overseeing the material accounts?', 'Priestly oversight of construction finances establishes that sacred work requires both skilled labour (Bezaleel) and priestly accountability (Ithamar) — separating execution from oversight prevents corruption and maintains trust', 'Ithamar had no real authority', 'Only Bezaleel was accountable', 'Financial oversight was unnecessary', 'a', 'Exodus 38:21 — Ithamar''s role as auditor separates the builder (Bezaleel) from the accountant (Ithamar). This separation of duties — execution and oversight — is a foundational governance principle that prevents both incompetence and corruption.'),
('Exodus', 38, 'adults', 8, 'How do the three metals (gold, silver, bronze) map onto the tabernacle''s theology?', 'Gold (Holy of Holies/Most Holy Place — God''s glory and presence), Silver (foundation sockets — redemption/atonement), Bronze (outer court — judgment/sacrifice): the metal hierarchy mirrors the progressive approach to God from judgment through redemption to glory', 'The metals were randomly assigned', 'Cost determined placement', 'All metals had equal significance', 'a', 'The metal gradient (bronze→silver→gold) corresponds to theological progression: judgment (bronze court), redemption (silver foundation), glory (gold furniture). Moving from outer court to Holy of Holies, both metal value and theological significance increase.');

-- Chapter 39: Priestly Garments
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 39, 'kids', 1, 'What did the workers make for Aaron in this chapter?', 'The beautiful priestly garments — the ephod, breastplate, robe, coat, mitre, and girdle', 'A crown and sceptre', 'A suit of armour', 'A golden throne', 'a', 'Exodus 39:1 — "And of the blue, and purple, and scarlet, they made cloths of service, to do service in the holy place, and made the holy garments for Aaron."'),
('Exodus', 39, 'kids', 2, 'What was engraved on each of the twelve stones of the breastplate?', 'The name of one of the twelve tribes of Israel — like a signet ring engraving', 'The name of Moses', 'Egyptian symbols', 'Animal pictures', 'a', 'Exodus 39:14 — "And the stones were according to the names of the children of Israel, twelve, according to their names, like the engravings of a signet, every one with his name, according to the twelve tribes."'),
('Exodus', 39, 'kids', 3, 'What did Moses say when he saw all the finished work?', 'Moses blessed them — they had done everything exactly as the LORD had commanded', 'He said it was wrong', 'He asked them to start over', 'He said nothing', 'a', 'Exodus 39:43 — "And Moses did look upon all the work, and, behold, they had done it as the LORD had commanded, even so had they done it: and Moses blessed them."'),
-- Teens
('Exodus', 39, 'teens', 1, 'How was gold incorporated into the ephod''s fabric?', 'They beat gold into thin plates, cut it into wires, and wove the gold thread into the blue, purple, scarlet, and fine linen — a unique technique', 'Gold was painted on', 'Gold beads were sewn on', 'Gold dust was sprinkled', 'a', 'Exodus 39:3 — "And they did beat the gold into thin plates, and cut it into wires, to work it in the blue, and in the purple, and in the scarlet, and in the fine linen, with cunning work."'),
('Exodus', 39, 'teens', 2, 'What was the golden plate on the mitre (turban) engraved with?', '"HOLINESS TO THE LORD" — written like the engraving of a signet and fastened to the mitre with a lace of blue', '"King of Israel"', '"Aaron the Priest"', '"Servant of God"', 'a', 'Exodus 39:30 — "And they made the plate of the holy crown of pure gold, and wrote upon it a writing, like to the engravings of a signet, HOLINESS TO THE LORD."'),
('Exodus', 39, 'teens', 3, 'How many times does "as the LORD commanded Moses" appear in this chapter?', 'Seven times — emphasising complete obedience in every detail of the priestly garments', 'Once', 'Three times', 'Never', 'a', 'Exodus 39:1,5,7,21,26,29,31 — The sevenfold repetition of "as the LORD commanded Moses" echoes the seven days of creation and emphasises perfect, complete obedience.'),
('Exodus', 39, 'teens', 4, 'What was brought to Moses for final inspection?', 'The entire tabernacle with all its furnishings — tent, coverings, boards, bars, pillars, sockets, and all the furniture and utensils', 'Only the Ark', 'Only the priestly garments', 'Only the altar', 'a', 'Exodus 39:33-41 — Everything was brought to Moses: the tabernacle, all its components, furniture, garments, oil, incense — a complete inventory for final approval.'),
('Exodus', 39, 'teens', 5, 'What did Moses'' inspection and blessing parallel in Genesis?', 'Just as God surveyed creation and declared it "very good" (Genesis 1:31), Moses surveyed the tabernacle work and blessed the workers — the tabernacle is a new creation', 'It paralleled the Flood narrative', 'It paralleled Abraham''s journey', 'It paralleled nothing', 'a', 'Exodus 39:43 — "Moses did look upon all the work, and, behold, they had done it... and Moses blessed them." This echoes Genesis 1:31: "And God saw every thing that he had made, and, behold, it was very good." Both survey completed work and pronounce blessing.'),
-- Adults
('Exodus', 39, 'adults', 1, 'How does the sevenfold "as the LORD commanded Moses" in chapter 39 parallel the seven days of creation?', 'Just as God spoke seven creative commands in Genesis 1, the sevenfold obedience formula shows the tabernacle as a new creation — both are completed through divine speech fulfilled in material reality, and both end with inspection and blessing', 'The sevenfold pattern is coincidental', 'Only six occurrences exist', 'Genesis and Exodus are unrelated', 'a', 'The seven occurrences of "as the LORD commanded Moses" in chapter 39 mirror the seven creative fiats of Genesis 1. The tabernacle construction is a creation narrative: divine speech → obedient execution → divine/human approval → rest.'),
('Exodus', 39, 'adults', 2, 'What does Moses'' final inspection and blessing (39:43) parallel about God''s role?', 'Moses acts in God''s place — inspecting, approving, and blessing, as God did with creation (Genesis 1:31, 2:3); this positions Moses as God''s vice-regent, whose approval validates the community''s obedient work and pronounces divine favour', 'Moses was simply being polite', 'The inspection was routine', 'No parallel to Genesis exists', 'a', 'Exodus 39:43 — Moses'' triple action (look/behold/bless) mirrors God''s triple action in Genesis (saw/behold/blessed). This literary parallel positions the tabernacle completion as the climax of Israel''s new-creation story.'),
('Exodus', 39, 'adults', 3, 'How does the gold-thread technique (39:3) demonstrate the integration of divine design and human skill?', 'Beating gold into plates, cutting wires, and weaving them into fabric required extraordinary metallurgical and textile skill — God''s design demanded the highest level of human artistry; divine instruction does not suppress human creativity but channels and elevates it', 'The technique was simple', 'Anyone could have done it', 'Human skill was irrelevant', 'a', 'Exodus 39:3 — The gold-thread technique is remarkably sophisticated: sheet gold → thin plates → wire strips → woven into fabric. This process required both metallurgical and textile expertise, demonstrating that serving God calls for the highest excellence in our craft.'),
('Exodus', 39, 'adults', 4, 'What does the complete listing of every tabernacle component in 39:33-41 accomplish?', 'The comprehensive inventory demonstrates completeness — nothing is missing, nothing is added, nothing is modified; the tabernacle is exactly what God ordered, establishing the principle that God''s work must be delivered whole, not partial or embellished', 'The list is tedious inventory', 'It was a shipping manifest', 'The list was added later', 'a', 'Exodus 39:33-41 — The inventory checklist verifies that every component specified in chapters 25-31 has been faithfully produced. This thoroughness teaches that obedience is measured not by effort or enthusiasm but by completeness — delivering exactly what was asked.'),
('Exodus', 39, 'adults', 5, 'How does the phrase "cloths of service" (bigdei haserad, 39:1) distinguish sacred vestments from ordinary clothing?', 'These garments are specifically "for service" (serad — ministry/sacred duty) — they transform the wearer from ordinary person to consecrated minister; putting on the priestly garments is not merely dressing but becoming; the clothing effects a change in status and function', 'They were fancy everyday clothes', 'All Israelites wore them', 'The distinction was minor', 'a', 'Exodus 39:1 — "Cloths of service to do service in the holy place." The garments are defined by their function: they are not worn for personal adornment but for sacred ministry. Putting on the priestly vestments enacted a role transformation — from Levite to priest, from common to consecrated.');

-- ═══ Exodus Chapter 40 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Exodus', 40, 'kids', 1, 'When did God tell Moses to set up the tabernacle?', 'On the first day of the first month — exactly one year after leaving Egypt', 'On the seventh day', 'After forty years', 'Whenever Moses was ready', 'a', 'Exodus 40:2,17 — "On the first day of the first month shalt thou set up the tabernacle... And it came to pass in the first month in the second year, on the first day of the month, that the tabernacle was reared up."'),
('Exodus', 40, 'kids', 2, 'What amazing thing happened when the tabernacle was set up?', 'A cloud covered the tent and the glory of the LORD filled the tabernacle — God had come to live with His people!', 'Lightning struck the tent', 'Nothing special happened', 'It rained for three days', 'a', 'Exodus 40:34 — "Then a cloud covered the tent of the congregation, and the glory of the LORD filled the tabernacle."'),
('Exodus', 40, 'kids', 3, 'How did the cloud guide the Israelites on their journeys?', 'When the cloud lifted up, they travelled; when it stayed, they stayed — the cloud guided them all through their journeys', 'They followed a map', 'They followed the stars', 'They followed the wind', 'a', 'Exodus 40:36-37 — "And when the cloud was taken up from over the tabernacle, the children of Israel went onward in all their journeys: But if the cloud were not taken up, then they journeyed not."'),
-- Teens
('Exodus', 40, 'teens', 1, 'What did Moses place inside the Ark before putting it in the Most Holy Place?', 'The Testimony (the two stone tablets of the law) — and he placed the mercy seat on top', 'Gold and silver', 'Manna and Aaron''s rod', 'A scroll of the covenant', 'a', 'Exodus 40:20 — "And he took and put the testimony into the ark, and set the staves on the ark, and put the mercy seat above upon the ark."'),
('Exodus', 40, 'teens', 2, 'In what order did Moses set up the tabernacle furnishings?', 'Ark with mercy seat (innermost), then table with shewbread, candlestick with lamps, golden altar of incense, then the brazen altar and laver in the courtyard', 'Everything at once', 'Outside to inside', 'In random order', 'a', 'Exodus 40:20-33 — Moses assembled from most holy to least: Ark (v.20-21), Table (v.22-23), Candlestick (v.24-25), Incense Altar (v.26-27), Brazen Altar (v.29), Laver (v.30-32), Court (v.33).'),
('Exodus', 40, 'teens', 3, 'Could Moses enter the tabernacle after the glory filled it?', 'No — Moses was not able to enter because the cloud rested on it and the glory of the LORD filled it', 'Yes, he entered freely', 'He entered with Aaron', 'He entered after praying', 'a', 'Exodus 40:35 — "And Moses was not able to enter into the tent of the congregation, because the cloud abode thereon, and the glory of the LORD filled the tabernacle."'),
('Exodus', 40, 'teens', 4, 'What did Moses do to Aaron and his sons at the tabernacle?', 'He washed them, dressed them in the priestly garments, and anointed them — consecrating them for service', 'He sent them home', 'He gave them swords', 'He tested them with questions', 'a', 'Exodus 40:12-15 — "And thou shalt bring Aaron and his sons unto the door of the tabernacle of the congregation, and wash them with water. And thou shalt put upon Aaron the holy garments, and anoint him."'),
('Exodus', 40, 'teens', 5, 'What was visible to all the Israelites throughout their journeys?', 'The cloud of the LORD was upon the tabernacle by day, and fire was on it by night — visible to all the house of Israel in all their journeys', 'A bright star', 'A pillar of smoke', 'A hovering angel', 'a', 'Exodus 40:38 — "For the cloud of the LORD was upon the tabernacle by day, and fire was on it by night, in the sight of all the house of Israel, throughout all their journeys."'),
-- Adults
('Exodus', 40, 'adults', 1, 'How does the glory filling the tabernacle (40:34) consummate the entire Exodus narrative?', 'The exodus began with Israel enslaved far from God; it ends with God dwelling among them — the glory cloud that led them from Egypt now fills their midst; redemption''s purpose is achieved: "that I may dwell among them" (25:8)', 'The glory cloud was anticlimactic', 'The tabernacle was not the narrative''s climax', 'God''s presence was temporary', 'a', 'Exodus 40:34 — "The glory of the LORD filled the tabernacle." This is the ultimate fulfilment of the book''s purpose. Exodus 25:8 ("let them make me a sanctuary; that I may dwell among them") finds its answer in 40:34. God''s dwelling with humanity is the telos of redemption.'),
('Exodus', 40, 'adults', 2, 'How does the glory cloud in 40:34-35 parallel Solomon''s temple dedication?', '1 Kings 8:10-11 describes the same phenomenon: "the cloud filled the house of the LORD, so that the priests could not stand to minister... for the glory of the LORD had filled the house." Both events demonstrate divine approval and occupation of the sacred space', 'Solomon''s temple had no cloud', 'The events are unrelated', 'Only the tabernacle had God''s glory', 'a', 'Exodus 40:34-35, 1 Kings 8:10-11 — The identical phenomenon (cloud/glory filling + inability to minister) confirms continuity between tabernacle and temple. God''s glory validates both structures as His chosen dwelling. 2 Chronicles 7:1 adds fire descending.'),
('Exodus', 40, 'adults', 3, 'What does Moses'' inability to enter (40:35) teach about divine transcendence?', 'Even Moses — who spoke to God face to face — cannot enter when glory fills the tabernacle; this demonstrates that God remains ultimately transcendent even while becoming immanent; intimacy with God does not domesticate Him', 'Moses was being punished', 'He could have entered if he tried', 'The prohibition was temporary', 'a', 'Exodus 40:35 — Even the greatest human mediator cannot stand before the unmediated glory. This tension between God''s accessibility (33:11 — "face to face") and God''s overwhelming glory (40:35 — "unable to enter") defines the paradox of biblical faith: God is near yet incomprehensible.'),
('Exodus', 40, 'adults', 4, 'How does the book of Exodus end with movement rather than settlement?', 'The final verses describe the cloud leading Israel forward — Exodus ends not with arrival but with journey; God''s people are pilgrims following divine guidance, and the story continues into Leviticus and Numbers; Exodus achieves purpose (God''s presence) while maintaining pilgrimage', 'Exodus ends with rest', 'The journey was complete', 'Israel had arrived at the Promised Land', 'a', 'Exodus 40:36-38 — The book ends with ongoing movement: cloud up = travel, cloud down = stay. This dynamic ending shows that God''s presence is not static but leading — the same God who brought them out of Egypt now leads them toward the Promised Land. The journey continues.'),
('Exodus', 40, 'adults', 5, 'How does the date "first day of the first month" (40:2,17) connect to the Passover and new creation?', 'The tabernacle is erected on New Year''s Day — the same month as the Passover (12:2), marking a new beginning; the first day of the first month echoes Genesis 1:1; the tabernacle inauguration is simultaneously a Passover anniversary and a new creation event', 'The date was arbitrary', 'It was chosen for practical reasons', 'No symbolic meaning exists', 'a', 'Exodus 40:2,17 — The first day of the first month connects three horizons: creation (beginning of time), Passover (beginning of Israel''s redemptive calendar), and tabernacle (beginning of God''s dwelling with Israel). Each "beginning" marks a new epoch in God''s purposes.'),
('Exodus', 40, 'adults', 6, 'How does the cloud-and-fire guidance (40:36-38) connect to the broader biblical theology of guidance?', 'The visible divine presence directing Israel''s movement establishes the principle that God leads His people step by step — not giving the entire route in advance but providing day-by-day guidance; this patience-requiring pattern continues through the Holy Spirit''s leading in the New Testament (Acts 16:6-10)', 'God gave them a complete map', 'They navigated independently', 'The cloud was unreliable', 'a', 'Exodus 40:36-38 — The cloud-guidance model is step-by-step: wait for the cloud, follow the cloud, stop when it stops. This teaches that God''s guidance is processual, not programmatic — believers must learn to follow the Spirit''s leading in real-time (Romans 8:14, Galatians 5:25).'),
('Exodus', 40, 'adults', 7, 'How does the conclusion of Exodus set up the rest of the Pentateuch?', 'Exodus ends with God dwelling among Israel and leading them — Leviticus provides the manual for living with a holy God in their midst, Numbers narrates the journey under the cloud, and Deuteronomy prepares them for life in the land; Exodus is the pivotal book that transforms slaves into a covenant nation with God''s presence', 'Exodus stands alone', 'The Pentateuch is disconnected', 'Leviticus repeats Exodus', 'a', 'Exodus 40:34-38 transitions seamlessly into Leviticus 1:1 ("The LORD called unto Moses... out of the tabernacle"). The glory that fills the tabernacle in Exodus''s finale becomes the speaking presence in Leviticus''s opening — one continuous narrative of God dwelling and speaking with His people.'),
('Exodus', 40, 'adults', 8, 'What is the grand theological arc of the book of Exodus?', 'From slavery in Egypt to God''s glory filling the tabernacle — from bondage to worship, from Pharaoh''s brickyard to Yahweh''s sanctuary; the book traces redemption from its necessity (oppression) through its execution (plagues, Passover, Red Sea) to its purpose (divine dwelling); it is the gospel in narrative form', 'Exodus is merely historical', 'It covers only the plagues', 'The theological arc is unclear', 'a', 'Exodus moves from enslavement (ch.1) to divine presence (ch.40): oppression → deliverance → covenant → tabernacle → glory. This arc is the gospel pattern: bondage to sin → redemption by blood → covenant relationship → Spirit-filled communion. Exodus is the Old Testament''s gospel.');
