-- ============================================================================
-- Quiz Seed: 1 Samuel — Part 1 (Chapters 1–10)
-- 3 difficulties × 10 chapters = 160 total questions
-- kids: 3 Qs, teens: 5 Qs, adults: 8 Qs per chapter
-- correct_answer is always 'a'
-- ============================================================================

-- ═══ 1 Samuel Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 1, 'kids', 1, 'What did Hannah ask God to give her?', 'A son', 'More food', 'A house', 'A husband', 'a', '1 Samuel 1:11 — "O LORD of hosts... give unto thine handmaid a man child."'),
('1 Samuel', 1, 'kids', 2, 'Who was the priest at Shiloh that spoke to Hannah?', 'Eli', 'Samuel', 'Elkanah', 'Peninnah', 'a', '1 Samuel 1:9 — "Now Eli the priest sat upon a seat by a post of the temple of the LORD."'),
('1 Samuel', 1, 'kids', 3, 'What did Hannah name her baby boy?', 'Samuel', 'Elkanah', 'Phinehas', 'Eli', 'a', '1 Samuel 1:20 — "She bare a son, and called his name Samuel, saying, Because I have asked him of the LORD."'),
-- Teens
('1 Samuel', 1, 'teens', 1, 'Why was Hannah weeping and not eating at Shiloh?', 'She was sick with a fever', 'The LORD had shut up her womb and her rival provoked her', 'She had lost her offering', 'Eli had rebuked her', 'a', '1 Samuel 1:6-7 — "Her adversary also provoked her sore... therefore she wept, and did not eat."'),
('1 Samuel', 1, 'teens', 2, 'What did Hannah vow to do with the child if God gave her a son?', 'Give him to the temple all his life and no razor shall come upon his head', 'Teach him the law at home', 'Name him after Eli', 'Offer him as a burnt offering', 'a', '1 Samuel 1:11 — "I will give him unto the LORD all the days of his life, and there shall no razor come upon his head."'),
('1 Samuel', 1, 'teens', 3, 'What did Eli think was wrong with Hannah when he saw her praying silently?', 'She was sleeping in the temple', 'She was drunk with wine', 'She was making an idol', 'She was mourning the dead', 'a', '1 Samuel 1:13 — "Eli thought she had been drunken."'),
('1 Samuel', 1, 'teens', 4, 'What did Hannah say she had poured out before the LORD?', 'Her heart', 'Oil and wine', 'Her offering', 'Her tears only', 'a', '1 Samuel 1:15 — "I have poured out my soul before the LORD."'),
('1 Samuel', 1, 'teens', 5, 'Where did Hannah bring Samuel after he was weaned?', 'To the tabernacle at Shiloh', 'To Jerusalem', 'To Hebron', 'To the city of Ramah', 'a', '1 Samuel 1:24 — "She brought him unto the house of the LORD in Shiloh."'),
-- Adults
('1 Samuel', 1, 'adults', 1, 'What was the name of Hannah''s husband, and from what tribe was he?', 'Elkanah, an Ephrathite', 'Eli, a Levite', 'Elkanah, a Benjamite', 'Eliezer, an Ephrathite', 'a', '1 Samuel 1:1 — "There was a certain man of Ramathaim-zophim... whose name was Elkanah... an Ephrathite."'),
('1 Samuel', 1, 'adults', 2, 'How many wives did Elkanah have, and what distinguished Hannah from the other wife?', 'Two wives; Peninnah had children but Hannah had none', 'Two wives; Hannah was older', 'Three wives; Hannah was youngest', 'Two wives; Hannah was barren and older', 'a', '1 Samuel 1:2 — "He had two wives; the name of the one was Hannah, and the name of the other Peninnah: and Peninnah had children, but Hannah had no children."'),
('1 Samuel', 1, 'adults', 3, 'What portion did Elkanah give Hannah at the yearly sacrifice?', 'A worthy portion, for he loved her', 'A double portion', 'The firstfruits', 'Nothing, because she was barren', 'a', '1 Samuel 1:5 — "But unto Hannah he gave a worthy portion; for he loved Hannah."'),
('1 Samuel', 1, 'adults', 4, 'What specific type of prayer did Hannah make — how did she pray?', 'She prayed in her heart, with only her lips moving and no voice heard', 'She prayed aloud with weeping before the altar', 'She prayed silently with closed eyes and hands folded', 'She prayed through Eli as intercessor', 'a', '1 Samuel 1:13 — "Hannah, she spake in her heart; only her lips moved, but her voice was not heard."'),
('1 Samuel', 1, 'adults', 5, 'After Eli blessed Hannah and she departed, what change came over her?', 'Her countenance was no longer sad and she ate', 'She immediately conceived', 'She gave an offering of thanksgiving', 'She sang a song of praise', 'a', '1 Samuel 1:18 — "So the woman went her way, and did eat, and her countenance was no more sad."'),
('1 Samuel', 1, 'adults', 6, 'What is the meaning of the name Samuel as explained by Hannah in 1 Samuel 1:20?', 'Asked of the LORD', 'Heard by God', 'Gift of God', 'Dedicated to the LORD', 'a', '1 Samuel 1:20 — "She called his name Samuel, saying, Because I have asked him of the LORD."'),
('1 Samuel', 1, 'adults', 7, 'What offerings did Hannah''s husband bring when presenting Samuel to Eli?', 'Three bullocks, one ephah of flour, and a bottle of wine', 'A burnt offering and a peace offering', 'Seven lambs and loaves of bread', 'A bullock and a basket of firstfruits', 'a', '1 Samuel 1:24 — "She went up with three bullocks, and one ephah of flour, and a bottle of wine."'),
('1 Samuel', 1, 'adults', 8, 'What declaration did Hannah make to Eli when she presented Samuel, connecting the child to her earlier prayer?', 'She said she was the woman who prayed, and that the LORD had granted her petition', 'She said the child was holy from birth', 'She said she had fulfilled her Nazirite vow', 'She said Eli had predicted the child''s birth', 'a', '1 Samuel 1:27 — "For this child I prayed; and the LORD hath given me my petition which I asked of him."');

-- ═══ 1 Samuel Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 2, 'kids', 1, 'What did Hannah do at the start of chapter 2?', 'She prayed and praised God', 'She went home to Ramah', 'She wept before the altar', 'She taught Samuel to read', 'a', '1 Samuel 2:1 — "And Hannah prayed, and said, My heart rejoiceth in the LORD."'),
('1 Samuel', 2, 'kids', 2, 'What were the names of Eli''s two wicked sons?', 'Hophni and Phinehas', 'Samuel and Ichabod', 'Joel and Abijah', 'Elkanah and Peninnah', 'a', '1 Samuel 2:34 — "This shall be a sign unto thee, that shall come upon thy two sons, on Hophni and Phinehas."'),
('1 Samuel', 2, 'kids', 3, 'Who told Eli that his family would be punished?', 'A man of God', 'Samuel', 'The LORD in a dream', 'An angel', 'a', '1 Samuel 2:27 — "And there came a man of God unto Eli, and said unto him, Thus saith the LORD."'),
-- Teens
('1 Samuel', 2, 'teens', 1, 'In Hannah''s prayer, whom does she say the LORD kills and makes alive?', 'The LORD kills the wicked and makes the righteous alive', 'The LORD killeth and maketh alive; he bringeth down to the grave and bringeth up', 'The LORD destroys enemies and raises His servants', 'The LORD kills the proud and restores the humble', 'a', '1 Samuel 2:6 — "The LORD killeth, and maketh alive: he bringeth down to the grave, and bringeth up."'),
('1 Samuel', 2, 'teens', 2, 'What sin did Hophni and Phinehas commit with the offerings?', 'They took raw flesh by force before the fat was burned', 'They sold the offerings for money', 'They offered foreign animals', 'They ate the offerings outside the tabernacle', 'a', '1 Samuel 2:15-16 — "The priest''s servant came... Give flesh to roast for the priest; for he will not have sodden flesh of thee, but raw."'),
('1 Samuel', 2, 'teens', 3, 'How did Hannah''s son Samuel grow up, according to chapter 2?', 'He grew before the LORD, wearing a linen ephod', 'He grew wise and studied under Eli daily', 'He grew strong and became a warrior', 'He grew in the temple courts among the priests', 'a', '1 Samuel 2:18 — "But Samuel ministered before the LORD, being a child, girded with a linen ephod."'),
('1 Samuel', 2, 'teens', 4, 'What additional blessing did God give Hannah after she gave Samuel to the LORD?', 'Three sons and two daughters', 'Long life and honour', 'Riches and a large household', 'A house in Shiloh', 'a', '1 Samuel 2:21 — "The LORD visited Hannah, so that she conceived, and bare three sons and two daughters."'),
('1 Samuel', 2, 'teens', 5, 'What did the man of God prophesy would happen to Eli''s two sons on the same day?', 'Both of them shall die in one day', 'They would be exiled from Israel', 'They would be removed from the priesthood', 'They would be struck blind', 'a', '1 Samuel 2:34 — "And this shall be a sign unto thee... they shall die both of them in one day."'),
-- Adults
('1 Samuel', 2, 'adults', 1, 'In Hannah''s song, what imagery does she use to describe God''s reversal of human fortunes with the bow?', 'The bows of the mighty men are broken, and they that stumbled are girded with strength', 'The bow of the proud is shattered and the weak are raised up', 'The bow of the wicked is bent low and the righteous stand tall', 'The arrows of the enemy are broken before the LORD', 'a', '1 Samuel 2:4 — "The bows of the mighty men are broken, and they that stumbled are girded with strength."'),
('1 Samuel', 2, 'adults', 2, 'What does Hannah declare about the pillars of the earth in her prayer?', 'The pillars of the earth are the LORD''s, and he hath set the world upon them', 'The pillars of the earth tremble before the LORD', 'The LORD laid the pillars of the earth in the beginning', 'The earth''s pillars shall be shaken at the last day', 'a', '1 Samuel 2:8 — "For the pillars of the earth are the LORD''s, and he hath set the world upon them."'),
('1 Samuel', 2, 'adults', 3, 'What was the specific sin the sons of Eli committed regarding women?', 'They lay with the women that assembled at the door of the tabernacle', 'They married foreign wives against the law', 'They prevented women from bringing offerings', 'They took the women''s grain offerings by force', 'a', '1 Samuel 2:22 — "They lay with the women that assembled at the door of the tabernacle of the congregation."'),
('1 Samuel', 2, 'adults', 4, 'What question did Eli ask his sons to rebuke them, concerning sin against God versus man?', 'If one man sin against another, God shall judge him; but if a man sin against the LORD, who shall intreat for him?', 'How long will you sin against the LORD and bring shame upon His house?', 'Will the LORD forgive those who sin willfully against His anointed?', 'What will you do when the LORD requires your souls at the day of judgment?', 'a', '1 Samuel 2:25 — "If one man sin against another, the judge shall judge him: but if a man sin against the LORD, who shall intreat for him?"'),
('1 Samuel', 2, 'adults', 5, 'What did the man of God say the LORD had originally promised regarding Eli''s priestly house?', 'That his house and his father''s house should walk before the LORD for ever', 'That Eli''s sons would rule Israel as judges', 'That Eli would be the last of the high priests', 'That Eli''s line would keep the ark for generations', 'a', '1 Samuel 2:30 — "I said indeed that thy house, and the house of thy father, should walk before me for ever."'),
('1 Samuel', 2, 'adults', 6, 'What reversal did God announce regarding the honour of Eli''s house?', 'Those who honour God will be honoured; those who despise Him shall be lightly esteemed', 'The priests of Eli''s house would serve the new priest', 'Eli''s descendants would be scattered among the tribes', 'The high priesthood would pass to the tribe of Judah', 'a', '1 Samuel 2:30 — "Them that honour me I will honour, and they that despise me shall be lightly esteemed."'),
('1 Samuel', 2, 'adults', 7, 'What sign would confirm the prophecy against Eli''s house, mentioned in verse 34?', 'Both Hophni and Phinehas dying in one day', 'The ark being taken from Shiloh', 'A famine striking Eli''s household', 'The tabernacle curtain being torn', 'a', '1 Samuel 2:34 — "And this shall be a sign unto thee... they shall die both of them in one day."'),
('1 Samuel', 2, 'adults', 8, 'What faithful priest did God promise to raise up in place of Eli''s line, and what would He build for him?', 'A faithful priest who shall do what is in God''s heart, and God would build him a sure house', 'A priest from Levi who would restore true worship', 'Samuel himself, who would be priest and king', 'A new high priest from the line of Aaron''s eldest son', 'a', '1 Samuel 2:35 — "I will raise me up a faithful priest... and I will build him a sure house; and he shall walk before mine anointed for ever."');

-- ═══ 1 Samuel Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 3, 'kids', 1, 'Who called Samuel by name in the night?', 'The LORD', 'Eli', 'His mother Hannah', 'An angel', 'a', '1 Samuel 3:4 — "The LORD called Samuel: and he answered, Here am I."'),
('1 Samuel', 3, 'kids', 2, 'How many times did God call Samuel before Eli understood it was the LORD?', 'Three times', 'Once', 'Twice', 'Four times', 'a', '1 Samuel 3:8 — "And the LORD called Samuel again the third time... Eli perceived that the LORD had called the child."'),
('1 Samuel', 3, 'kids', 3, 'What did Eli tell Samuel to say when called again?', 'Speak, LORD; for thy servant heareth', 'Here am I, LORD', 'I am listening, LORD', 'Thy servant is ready', 'a', '1 Samuel 3:9 — "Therefore Eli said unto Samuel, Go, lie down: and it shall be, if he call thee, that thou shalt say, Speak, LORD; for thy servant heareth."'),
-- Teens
('1 Samuel', 3, 'teens', 1, 'What was rare in Israel before this chapter, according to the opening verse?', 'The word of the LORD was precious, and there was no open vision', 'Priests were few and the temple was poorly kept', 'Prophecy had ceased since Moses', 'The ark had been hidden from Israel', 'a', '1 Samuel 3:1 — "The word of the LORD was precious in those days; there was no open vision."'),
('1 Samuel', 3, 'teens', 2, 'Where was Samuel sleeping when God called him?', 'In the temple of the LORD, where the ark of God was', 'In Eli''s house outside Shiloh', 'In the outer court of the tabernacle', 'At his mother''s home in Ramah', 'a', '1 Samuel 3:3 — "Samuel was laid down to sleep in the temple of the LORD, where the ark of God was."'),
('1 Samuel', 3, 'teens', 3, 'What message did God reveal to Samuel about Eli''s family?', 'That He would judge Eli''s house for ever because his sons made themselves vile and he restrained them not', 'That Hophni and Phinehas would be removed from the priesthood', 'That Eli would die that same night', 'That the ark would be taken as punishment for Eli''s sin', 'a', '1 Samuel 3:13 — "For I have told him that I will judge his house for ever for the iniquity which he knoweth; because his sons made themselves vile, and he restrained them not."'),
('1 Samuel', 3, 'teens', 4, 'How did Samuel feel about telling Eli the vision in the morning?', 'He feared to shew Eli the vision', 'He was eager to tell Eli at once', 'He prayed first before speaking', 'He was not afraid and told him immediately', 'a', '1 Samuel 3:15 — "Samuel feared to shew Eli the vision."'),
('1 Samuel', 3, 'teens', 5, 'How did Eli respond when Samuel told him everything God had said?', 'It is the LORD: let him do what seemeth him good', 'He wept and tore his garments', 'He refused to believe Samuel', 'He prayed for forgiveness', 'a', '1 Samuel 3:18 — "And he said, It is the LORD: let him do what seemeth him good."'),
-- Adults
('1 Samuel', 3, 'adults', 1, 'What does the text say about the condition of Eli''s eyes at the time of this chapter?', 'His eyes had begun to wax dim, that he could not see', 'Eli was completely blind by this time', 'Eli''s eyes were clear but his hearing was failing', 'Eli had a disease but could still see shapes', 'a', '1 Samuel 3:2 — "And it came to pass... Eli was laid down in his place, and his eyes began to wax dim, that he could not see."'),
('1 Samuel', 3, 'adults', 2, 'What is the significance of the lamp of God mentioned in 1 Samuel 3:3?', 'The lamp had not yet gone out, placing the call before dawn during the morning watch', 'The lamp was the symbol of God''s presence departing', 'The lamp was lit to help Samuel find his way to Eli', 'The lamp indicates God was still watching over the tabernacle', 'a', '1 Samuel 3:3 — "And ere the lamp of God went out in the temple of the LORD, where the ark of God was, and Samuel was laid down to sleep."'),
('1 Samuel', 3, 'adults', 3, 'What did God say at the start of His message that would cause both ears of every hearer to tingle?', 'I will do a thing in Israel, at which both the ears of every one that heareth it shall tingle', 'I will bring judgment on the house of Eli this very night', 'I will send a sign to all Israel that Samuel is my prophet', 'I will remove my glory from Shiloh and give it to a new place', 'a', '1 Samuel 3:11 — "Behold, I will do a thing in Israel, at which both the ears of every one that heareth it shall tingle."'),
('1 Samuel', 3, 'adults', 4, 'What phrase describes how God confirmed that Samuel was established as a prophet throughout all Israel?', 'All Israel from Dan even to Beer-sheba knew that Samuel was established to be a prophet of the LORD', 'Samuel''s word went out to all the cities of Judah', 'The priests at Shiloh testified to Samuel''s calling', 'God appeared to the elders of Israel and named Samuel His prophet', 'a', '1 Samuel 3:20 — "And all Israel from Dan even to Beer-sheba knew that Samuel was established to be a prophet of the LORD."'),
('1 Samuel', 3, 'adults', 5, 'How did God continue to reveal Himself to Samuel after this first call?', 'The LORD appeared again in Shiloh: for the LORD revealed himself to Samuel in Shiloh by the word of the LORD', 'God spoke to Samuel in dreams every night thereafter', 'God sent angels to instruct Samuel each morning', 'Samuel went to the high places and God met him there', 'a', '1 Samuel 3:21 — "And the LORD appeared again in Shiloh: for the LORD revealed himself to Samuel in Shiloh by the word of the LORD."'),
('1 Samuel', 3, 'adults', 6, 'What does the phrase "none of his words fall to the ground" mean in the context of Samuel''s ministry?', 'All of Samuel''s prophecies were fulfilled; he was a true prophet', 'Samuel never made a mistake in his priestly duties', 'Samuel''s prayers were always answered by God', 'Samuel wrote down every word God gave him', 'a', '1 Samuel 3:19 — "And Samuel grew, and the LORD was with him, and did let none of his words fall to the ground."'),
('1 Samuel', 3, 'adults', 7, 'Why was God''s judgment against Eli''s house said to be without remedy, according to verse 14?', 'Because the iniquity of Eli''s house shall not be purged with sacrifice nor offering for ever', 'Because Eli had sinned willfully after being warned', 'Because Hophni and Phinehas had refused all correction', 'Because the priesthood had been permanently transferred to another line', 'a', '1 Samuel 3:14 — "And therefore I have sworn unto the house of Eli, that the iniquity of Eli''s house shall not be purged with sacrifice nor offering for ever."'),
('1 Samuel', 3, 'adults', 8, 'What does the chapter reveal about Samuel''s track record as a prophet from his early ministry onward?', 'The LORD was with him and let none of his words fall to the ground, and all Israel knew he was established as prophet', 'Samuel performed signs and wonders to prove his calling', 'Samuel was tested by the elders before being accepted', 'Samuel prophesied first to the tribe of Ephraim before speaking to all Israel', 'a', '1 Samuel 3:19-20 — "The LORD was with him, and did let none of his words fall to the ground... all Israel from Dan even to Beer-sheba knew that Samuel was established to be a prophet of the LORD."');

-- ═══ 1 Samuel Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 4, 'kids', 1, 'What happened to the ark of God in this chapter?', 'The Philistines captured it', 'It was hidden by Samuel', 'It was taken to Jerusalem', 'It was destroyed in battle', 'a', '1 Samuel 4:11 — "And the ark of God was taken; and the two sons of Eli, Hophni and Phinehas, were slain."'),
('1 Samuel', 4, 'kids', 2, 'What happened to Eli when he heard the ark was taken?', 'He fell off his seat and died', 'He went to battle to recover it', 'He prayed all night long', 'He wept and tore his clothes', 'a', '1 Samuel 4:18 — "And it came to pass, when he made mention of the ark of God, that he fell from off the seat backward... and his neck brake, and he died."'),
('1 Samuel', 4, 'kids', 3, 'What name did Phinehas''s wife give her baby, meaning "the glory is departed"?', 'Ichabod', 'Elkanah', 'Samuel', 'Abijah', 'a', '1 Samuel 4:21 — "And she named the child Ichabod, saying, The glory is departed from Israel."'),
-- Teens
('1 Samuel', 4, 'teens', 1, 'What did the Israelites decide to bring from Shiloh to help them in battle against the Philistines?', 'The ark of the covenant of the LORD', 'The sacred vessels of the tabernacle', 'The breastplate of judgment', 'The swords of the priests', 'a', '1 Samuel 4:3 — "Let us fetch the ark of the covenant of the LORD out of Shiloh unto us, that, when it cometh among us, it may save us out of the hand of our enemies."'),
('1 Samuel', 4, 'teens', 2, 'How did the Philistines react when they heard the great shout as the ark entered the Israelite camp?', 'They were afraid, saying God had come into the camp', 'They prepared a larger attack', 'They sent a message of peace to Israel', 'They retreated to the sea', 'a', '1 Samuel 4:7 — "The Philistines were afraid, for they said, God is come into the camp."'),
('1 Samuel', 4, 'teens', 3, 'What was the total Israelite casualty count in the battle where the ark was captured?', 'Thirty thousand footmen of Israel fell', 'Ten thousand men of Israel died', 'Five thousand soldiers were killed', 'Twenty-four thousand men fell in battle', 'a', '1 Samuel 4:10 — "And Israel was smitten, and they fled every man into his tent: and there was a very great slaughter; for there fell of Israel thirty thousand footmen."'),
('1 Samuel', 4, 'teens', 4, 'How old was Eli when he died, and how long had he judged Israel?', 'Ninety-eight years old, and he had judged Israel forty years', 'One hundred years old, judged Israel thirty years', 'Eighty years old, judged Israel twenty years', 'Ninety years old, judged Israel fifty years', 'a', '1 Samuel 4:15,18 — "Eli was ninety and eight years old... and he had judged Israel forty years."'),
('1 Samuel', 4, 'teens', 5, 'Why did Phinehas''s wife say "the glory is departed from Israel" as the focus of her grief?', 'Because the ark of God was taken and her husband and father-in-law were dead', 'Because the tabernacle had been burned', 'Because Samuel had left Shiloh', 'Because Israel had no king to lead them', 'a', '1 Samuel 4:21-22 — "She said, The glory is departed from Israel: for the ark of God is taken."'),
-- Adults
('1 Samuel', 4, 'adults', 1, 'Where was Israel encamped when the battle against the Philistines took place, and where were the Philistines?', 'Israel in Ebenezer, Philistines in Aphek', 'Israel at Mizpeh, Philistines at Ashdod', 'Israel at Gilgal, Philistines at Gaza', 'Israel at Shiloh, Philistines at Gath', 'a', '1 Samuel 4:1 — "Israel went out against the Philistines to battle... Israel pitched beside Ebenezer, and the Philistines pitched in Aphek."'),
('1 Samuel', 4, 'adults', 2, 'What reasoning did the elders of Israel use for fetching the ark, and what was the fatal flaw in their thinking?', 'They believed the ark itself would save them, treating it as a magical object rather than trusting God', 'They misunderstood the covenant God made with Moses', 'They did not have Samuel''s prophetic direction', 'They forgot that the ark had not left Shiloh since the days of Moses', 'a', '1 Samuel 4:3 — "Let us fetch the ark... that, when it cometh among us, it may save us." They treated the ark as a talisman rather than seeking God''s will.'),
('1 Samuel', 4, 'adults', 3, 'What did the Philistines say in their exhortation to themselves before the battle when they learned the ark had arrived?', 'Be strong, and quit yourselves like men, O ye Philistines, that ye be not servants unto the Hebrews', 'Fight to the last man or face slavery', 'The God of Israel is powerful but we have numbers on our side', 'Fear not — their God is contained in a box of wood', 'a', '1 Samuel 4:9 — "Be strong, and quit yourselves like men, O ye Philistines, that ye be not servants unto the Hebrews, as they have been to you: quit yourselves like men, and fight."'),
('1 Samuel', 4, 'adults', 4, 'What physical characteristic of Eli is emphasised in the account of his death?', 'He was a very heavy man, which is why his fall broke his neck', 'He was old and had been blind for years', 'He was crippled and could not flee', 'He was kneeling in prayer when he died', 'a', '1 Samuel 4:18 — "He was an old man, and heavy. And he had judged Israel forty years."'),
('1 Samuel', 4, 'adults', 5, 'How do the Philistines describe the God of Israel in their fearful speech, referencing the Egyptian plagues?', 'These are the gods that smote the Egyptians with all the plagues in the wilderness', 'The God of Israel broke Pharaoh and his armies in the sea', 'Their God destroyed Egypt and parted the sea for them', 'This is the God who sent ten plagues and led them out of Egypt', 'a', '1 Samuel 4:8 — "These are the gods that smote the Egyptians with all the plagues in the wilderness."'),
('1 Samuel', 4, 'adults', 6, 'What was the name of Phinehas''s wife''s newborn son, and what three griefs did she cite for naming him so?', 'Ichabod — the ark taken, her father-in-law dead, and her husband dead', 'Ichabod — Israel''s defeat, the priesthood ended, and Samuel''s departure', 'Ichabod — God''s judgment, the ark lost, and Eli''s blindness', 'Ichabod — the temple destroyed, the priests slain, and God silent', 'a', '1 Samuel 4:21 — "She named the child Ichabod... because the ark of God was taken, and because of her father in law and her husband."'),
('1 Samuel', 4, 'adults', 7, 'What does "Ichabod" mean as explained in the text?', 'The glory is departed from Israel', 'God has forsaken us', 'Without honour before the LORD', 'Israel is cast down', 'a', '1 Samuel 4:21 — "She named the child Ichabod, saying, The glory is departed from Israel: because the ark of God was taken."'),
('1 Samuel', 4, 'adults', 8, 'How does the capture of the ark in chapter 4 fulfil the prophecy given earlier in 1 Samuel?', 'It fulfils the man of God''s prophecy in chapter 2 that Eli''s house would be cut off and both sons die in one day', 'It fulfils Samuel''s night vision that Israel would be defeated', 'It fulfils Hannah''s song that the mighty would be brought low', 'It fulfils the word that the ark would travel among the nations', 'a', '1 Samuel 2:34 — "And this shall be a sign... they shall die both of them in one day." Both Hophni and Phinehas were slain when the ark was taken (1 Samuel 4:11).');

-- ═══ 1 Samuel Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 5, 'kids', 1, 'Where did the Philistines take the ark of God after capturing it?', 'Ashdod, and put it in the house of Dagon', 'Gath, and placed it in their temple', 'Gaza, in the house of their god', 'Ekron, before their king', 'a', '1 Samuel 5:1-2 — "The Philistines took the ark of God, and brought it... into Ashdod... and set it by Dagon."'),
('1 Samuel', 5, 'kids', 2, 'What happened to the idol Dagon when the ark of God was placed near it?', 'It fell on its face before the ark', 'It cracked and broke into pieces', 'It was moved across the room', 'It fell into the sea', 'a', '1 Samuel 5:3 — "When they of Ashdod arose early on the morrow, behold, Dagon was fallen upon his face to the earth before the ark of the LORD."'),
('1 Samuel', 5, 'kids', 3, 'What plague did God send on the people of Ashdod because of the ark?', 'Emerods (tumours)', 'Locusts', 'Darkness', 'Frogs', 'a', '1 Samuel 5:6 — "The hand of the LORD was heavy upon them of Ashdod, and he destroyed them, and smote them with emerods."'),
-- Teens
('1 Samuel', 5, 'teens', 1, 'What was the full extent of Dagon''s destruction when he fell the second time before the ark?', 'His head and both the palms of his hands were cut off upon the threshold', 'The whole idol was smashed into dust', 'Only his head fell and broke in two', 'Both his arms and legs were severed', 'a', '1 Samuel 5:4 — "Dagon was fallen upon his face to the ground before the ark of the LORD; and the head of Dagon and both the palms of his hands were cut off upon the threshold."'),
('1 Samuel', 5, 'teens', 2, 'What custom among the Philistines arose from the fall of Dagon, mentioned in verse 5?', 'The priests of Dagon tread not on the threshold of Dagon in Ashdod unto this day', 'They no longer worshipped Dagon after that day', 'They moved the idol outside the city', 'They offered double sacrifices to Dagon each year', 'a', '1 Samuel 5:5 — "Therefore neither the priests of Dagon, nor any that come into Dagon''s house, tread on the threshold of Dagon in Ashdod unto this day."'),
('1 Samuel', 5, 'teens', 3, 'After the men of Ashdod saw the plague, what did they decide to do with the ark?', 'Send the ark away to Gath', 'Return it to Israel immediately', 'Hide it in the wilderness', 'Bury it outside the city', 'a', '1 Samuel 5:8 — "They sent therefore and gathered all the lords of the Philistines unto them, and said, What shall we do with the ark of the God of Israel? And they answered, Let the ark of the God of Israel be carried about unto Gath."'),
('1 Samuel', 5, 'teens', 4, 'What happened to the people of Gath after the ark was brought there?', 'God smote the men of the city, both small and great, with emerods', 'They were struck with a great famine', 'They were defeated in battle by Israel', 'A great fire consumed part of the city', 'a', '1 Samuel 5:9 — "And it was so, that, after they had carried it about, the hand of the LORD was against the city with a very great destruction: and he smote the men of the city, both small and great, and they had emerods in their secret parts."'),
('1 Samuel', 5, 'teens', 5, 'What did the men of Ekron cry out when the ark was sent to their city?', 'They have brought about the ark of the God of Israel to slay us and our people', 'We will not receive the ark of the enemy''s God', 'Send back this ark before we all perish', 'The God of Israel has come to destroy Ekron', 'a', '1 Samuel 5:10 — "They sent therefore and gathered together all the lords of the Philistines, and said, Send away the ark of the God of Israel, and let it go again to his own place, that it slay us not, and our people."'),
-- Adults
('1 Samuel', 5, 'adults', 1, 'What is the theological significance of Dagon falling before the ark of the LORD?', 'God demonstrated His supremacy over the chief god of the Philistines, showing that all idols bow before the living God', 'The ark had a miraculous power that knocked down whatever was near it', 'The Philistine priests had set Dagon up carelessly and it fell by accident', 'God was punishing the Philistines for their treatment of Israelite prisoners', 'a', '1 Samuel 5:3-4 — Dagon fell twice before the ark, with his head and hands severed, symbolising total defeat of a false god before the LORD.'),
('1 Samuel', 5, 'adults', 2, 'What phrase is used repeatedly in chapter 5 to describe the source of the plagues, emphasising divine agency?', 'The hand of the LORD was heavy upon them', 'The wrath of God was poured out', 'The LORD smote the city with His power', 'The judgment of God came upon the Philistines', 'a', '1 Samuel 5:6 — "But the hand of the LORD was heavy upon them of Ashdod, and he destroyed them, and smote them with emerods."'),
('1 Samuel', 5, 'adults', 3, 'What does the cutting off of Dagon''s head and hands on the threshold symbolise in the ancient Near Eastern context?', 'Total humiliation and defeat — the hands represented Dagon''s power and the head his authority, both severed before the LORD', 'An earthquake that toppled the idol', 'The Philistines'' own vandalism of Dagon after the plague began', 'God''s rejection of Philistine worship as unclean', 'a', '1 Samuel 5:4 — "The head of Dagon and both the palms of his hands were cut off upon the threshold." In ancient war, captives were beheaded and hands cut off as trophies of victory.'),
('1 Samuel', 5, 'adults', 4, 'How does chapter 5 parallel the plagues of Egypt in its theological message?', 'As God judged Egypt''s gods through the plagues, He now judges Dagon and afflicts the Philistines, proving His sovereignty over all nations', 'The emerods mirror the boils of the sixth Egyptian plague, deliberately echoing Exodus', 'The darkness that fell on Ashdod recalled the ninth plague of Egypt', 'The death of Dagon recalls the death of the Egyptian firstborn', 'a', '1 Samuel 4:8 refers to the plagues of Egypt, and chapter 5 continues that theme: God defeats the gods and peoples of those who oppose Him.'),
('1 Samuel', 5, 'adults', 5, 'Which three Philistine cities did the ark pass through in chapter 5, and what happened in each?', 'Ashdod — Dagon fell and emerods; Gath — emerods small and great; Ekron — deadly destruction and emerods', 'Ashdod, Gaza, and Ekron — all struck with famine', 'Ashdod, Gath, and Ashkelon — struck with plague', 'Ashdod, Gath, and Ekron — fire consumed each city', 'a', '1 Samuel 5:1-12 — Ashdod: Dagon destroyed + emerods (v.6); Gath: great destruction + emerods (v.9); Ekron: deadly confusion + emerods (v.12).'),
('1 Samuel', 5, 'adults', 6, 'What did the cry of Ekron ascend to, according to verse 12?', 'The cry of the city went up to heaven', 'The cry was heard throughout all Philistia', 'The noise of Ekron reached the walls of Jerusalem', 'The sound of mourning was heard as far as Ashdod', 'a', '1 Samuel 5:12 — "And the men that died not were smitten with the emerods: and the cry of the city went up to heaven."'),
('1 Samuel', 5, 'adults', 7, 'What does the phrase "the hand of God was very heavy there" communicate about the nature of the judgment in Gath?', 'The judgment was intensified — a divine weight of affliction pressing upon the whole city', 'God was physically present and tangible in the city', 'The Gathites bore a heavier plague than Ashdod because they were stronger warriors', 'The hand of God refers to the ark''s physical weight crushing the idol', 'a', '1 Samuel 5:11 — "There was a deadly destruction throughout all the city; the hand of God was very heavy there."'),
('1 Samuel', 5, 'adults', 8, 'What does the response of the Philistine lords in gathering to discuss the ark''s fate reveal about their political-religious structure?', 'The five lords of the Philistines governed collectively and religious decisions required their joint counsel', 'The Philistines had no king and were ruled only by priests', 'Each city acted independently with no central leadership', 'The lords believed the ark had magical powers they wanted to control', 'a', '1 Samuel 5:8 — "They sent therefore and gathered all the lords of the Philistines unto them." The Philistine pentapolis (five city-state lords) governed together on matters of national significance.');

-- ═══ 1 Samuel Chapter 6 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 6, 'kids', 1, 'How long was the ark of God in Philistine territory?', 'Seven months', 'Seven years', 'Forty days', 'One year', 'a', '1 Samuel 6:1 — "And the ark of the LORD was in the country of the Philistines seven months."'),
('1 Samuel', 6, 'kids', 2, 'What kind of animals pulled the cart that carried the ark back to Israel?', 'Two milch cows', 'Two oxen', 'Two horses', 'Two donkeys', 'a', '1 Samuel 6:7 — "Now therefore make a new cart, and take two milch kine, on which there hath come no yoke, and tie the kine to the cart."'),
('1 Samuel', 6, 'kids', 3, 'To which Israelite city did the cows carry the ark?', 'Beth-shemesh', 'Shiloh', 'Mizpeh', 'Jerusalem', 'a', '1 Samuel 6:12 — "The kine took the straight way to the way of Beth-shemesh... and turned not aside to the right hand or to the left."'),
-- Teens
('1 Samuel', 6, 'teens', 1, 'What golden objects did the Philistines send with the ark as a trespass offering?', 'Five golden emerods and five golden mice, according to the number of the lords of the Philistines', 'Seven golden vessels and golden statues of Dagon', 'Gold and silver from the Philistine treasury', 'Golden images of their five cities', 'a', '1 Samuel 6:4 — "Then said they, What shall be the trespass offering which we shall return to him? They answered, Five golden emerods, and five golden mice."'),
('1 Samuel', 6, 'teens', 2, 'What test did the Philistine priests and diviners propose to confirm whether the plagues came from God?', 'Put the ark on a new cart with untrained cows that had never been yoked; if they go to Beth-shemesh, God did it', 'Place the ark by the Dagon temple again and see if the plague continued', 'Have the high priest carry the ark to the border of Israel', 'Ask the women of Ashdod to carry the ark to the boundary of Israel', 'a', '1 Samuel 6:7-9 — "Take... two milch kine, on which there hath come no yoke, and tie the kine to the cart, and bring their calves home from them... If it goeth up by the way of his own coast to Beth-shemesh, then he hath done us this great evil."'),
('1 Samuel', 6, 'teens', 3, 'What did the men of Beth-shemesh use to make a burnt offering to the LORD when the ark arrived?', 'The wood of the cart and the two cows', 'The golden offerings the Philistines sent', 'Lambs from their flocks', 'Wood from the great stone in the field', 'a', '1 Samuel 6:14 — "And they clave the wood of the cart, and offered the milch kine a burnt offering unto the LORD."'),
('1 Samuel', 6, 'teens', 4, 'What serious sin did the men of Beth-shemesh commit that caused God to strike them?', 'They looked into the ark of the LORD', 'They moved the ark without proper covering', 'They failed to offer the correct sacrifice', 'They touched the ark with unconsecrated hands', 'a', '1 Samuel 6:19 — "And he smote the men of Beth-shemesh, because they had looked into the ark of the LORD."'),
('1 Samuel', 6, 'teens', 5, 'What question did the survivors of Beth-shemesh ask after God struck them?', 'Who is able to stand before this holy LORD God?', 'Why has the LORD struck us so severely?', 'Shall we send the ark away from our city?', 'How can we make atonement for this sin?', 'a', '1 Samuel 6:20 — "Who is able to stand before this holy LORD God? and to whom shall he go up from us?"'),
-- Adults
('1 Samuel', 6, 'adults', 1, 'What theological argument did the Philistine diviners make by referencing Pharaoh hardening his heart?', 'Pharaoh hardened his heart and suffered more plagues, warning the Philistines not to harden their hearts but to send the ark with honour', 'They used Pharaoh as proof that fighting God was futile', 'They reminded the lords that God had plagued Egypt before sending Moses as deliverer', 'They argued that as God spared Egypt eventually, He would spare Philistia too', 'a', '1 Samuel 6:6 — "Wherefore then do ye harden your hearts, as the Egyptians and Pharaoh hardened their hearts? when he had wrought wonderfully among them, did they not let the people go?"'),
('1 Samuel', 6, 'adults', 2, 'What is the significance of using cows that had never been yoked and keeping their calves home in the Philistines'' test?', 'Untrained cows with calves at home would naturally return home, not go to Beth-shemesh, so their going to Israel proved divine direction', 'It fulfilled a pagan purification ritual for sending a sacred object', 'The priests wanted to show respect by using the finest animals', 'The cows symbolised the Philistines'' willingness to send new things to God', 'a', '1 Samuel 6:7-9 — The cows going straight to Beth-shemesh against their natural instinct proved the plagues were from the LORD, not chance.'),
('1 Samuel', 6, 'adults', 3, 'What is the large stone called in verse 14-15, and what role did it play in the arrival of the ark?', 'A great stone in the field of Joshua the Beth-shemite — it served as the resting place for the ark and the altar for the burnt offering', 'The stone of Ebenezer — it marked the boundary between Israel and Philistia', 'The stone of remembrance — it was inscribed with the record of the ark''s return', 'The threshing stone — it was used to grind the offerings', 'a', '1 Samuel 6:14-15 — "The cart came into the field of Joshua, a Beth-shemite, and stood there, where there was a great stone: and they clave the wood of the cart... the Levites took down the ark of the LORD."'),
('1 Samuel', 6, 'adults', 4, 'What do the five golden mice represent, according to the Philistine priests'' counsel?', 'The five lords of the Philistines and the five cities that were plagued — a representative offering for all Philistia', 'The five plagues that afflicted Philistia', 'The five months of plague before the first lord sought counsel', 'The five priests of Dagon who were killed in Ashdod', 'a', '1 Samuel 6:4 — "Five golden emerods, and five golden mice, according to the number of the lords of the Philistines: for one plague was on you all, and on your lords."'),
('1 Samuel', 6, 'adults', 5, 'How many men of Beth-shemesh did the LORD strike, and how is this number recorded in the KJV?', 'Fifty thousand and threescore and ten men', 'Three hundred men of the city', 'Seventy men of the elders of Beth-shemesh', 'Five hundred men who touched the ark', 'a', '1 Samuel 6:19 — "He smote of the men of Beth-shemesh, because they had looked into the ark of the LORD, even he smote of the people fifty thousand and threescore and ten men."'),
('1 Samuel', 6, 'adults', 6, 'To whom did the men of Beth-shemesh send messengers asking them to take the ark?', 'The inhabitants of Kirjath-jearim', 'The priests of Shiloh', 'The elders of Judah', 'Samuel at Ramah', 'a', '1 Samuel 6:21 — "They sent messengers to the inhabitants of Kirjath-jearim, saying, The Philistines have brought again the ark of the LORD; come ye down, and fetch it up to you."'),
('1 Samuel', 6, 'adults', 7, 'What was the trespass offering system the Philistines employed, and what ancient principle does it reflect?', 'Images of the affliction sent as guilt offerings — reflecting ancient Near Eastern practice of returning a plague in effigy to its divine source', 'A system of monetary fines paid to the temple treasury', 'A covenant ceremony to seal peace between Philistia and Israel''s God', 'A purification rite from Egyptian religious practice', 'a', '1 Samuel 6:4-5 — "Ye shall make images of your emerods, and images of your mice that mar the land... give glory unto the God of Israel: peradventure he will lighten his hand from off you."'),
('1 Samuel', 6, 'adults', 8, 'What does the straight path of the untrained cows directly to Beth-shemesh reveal about God''s sovereign guidance in this narrative?', 'God overruled natural instinct to confirm to both Israel and Philistia that the plagues were His work and the ark was His sacred property', 'The cows had been trained by the Philistines to go toward Israel', 'Providence used the geographical terrain to guide the cows naturally', 'The Levites at the border directed the cows from a distance', 'a', '1 Samuel 6:12 — "The kine took the straight way to the way of Beth-shemesh... and turned not aside to the right hand or to the left." This direct route against all natural instinct confirmed divine sovereignty.');

-- ═══ 1 Samuel Chapter 7 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 7, 'kids', 1, 'Where was the ark kept after it left Beth-shemesh?', 'Kirjath-jearim', 'Shiloh', 'Jerusalem', 'Ramah', 'a', '1 Samuel 7:1 — "The men of Kirjath-jearim came, and fetched up the ark of the LORD, and brought it into the house of Abinadab."'),
('1 Samuel', 7, 'kids', 2, 'What stone did Samuel set up to remember God''s help against the Philistines?', 'Ebenezer', 'Bethel', 'Gilgal', 'Mizpeh', 'a', '1 Samuel 7:12 — "Samuel took a stone, and set it between Mizpeh and Shen, and called the name of it Ebenezer, saying, Hitherto hath the LORD helped us."'),
('1 Samuel', 7, 'kids', 3, 'What did Samuel tell the Israelites to put away before God would help them?', 'Strange gods and Ashtaroth', 'Their weapons and armour', 'Their golden jewellery', 'Their foreign wives', 'a', '1 Samuel 7:3 — "Samuel spake unto all the house of Israel, saying... put away the strange gods and Ashtaroth from among you."'),
-- Teens
('1 Samuel', 7, 'teens', 1, 'How long did the ark remain at Kirjath-jearim before Israel began to seek the LORD again?', 'Twenty years', 'Seven years', 'Forty years', 'Ten years', 'a', '1 Samuel 7:2 — "And it came to pass, while the ark abode in Kirjath-jearim, that the time was long; for it was twenty years."'),
('1 Samuel', 7, 'teens', 2, 'What was Samuel''s instruction to Israel when they gathered at Mizpeh for national repentance?', 'Draw water and pour it out before the LORD and fast that day, saying We have sinned against the LORD', 'Offer burnt offerings and peace offerings for seven days', 'Every man return to his own city and pray to the LORD', 'Build altars in every tribe and offer sacrifices', 'a', '1 Samuel 7:6 — "They gathered together to Mizpeh, and drew water, and poured it out before the LORD, and fasted on that day, and said there, We have sinned against the LORD."'),
('1 Samuel', 7, 'teens', 3, 'How did God intervene when the Philistines attacked Israel while they were gathered at Mizpeh?', 'The LORD thundered with a great thunder upon the Philistines and discomfited them', 'God sent a plague to strike the Philistine army', 'An earthquake opened the ground under the Philistines', 'Angels with flaming swords appeared before the Philistines', 'a', '1 Samuel 7:10 — "The LORD thundered with a great thunder on that day upon the Philistines, and discomfited them; and they were smitten before Israel."'),
('1 Samuel', 7, 'teens', 4, 'What does "Ebenezer" mean?', 'Stone of help', 'Memorial of victory', 'Rock of remembrance', 'Pillar of God''s covenant', 'a', '1 Samuel 7:12 — "He called the name of it Ebenezer, saying, Hitherto hath the LORD helped us." Ebenezer means "stone of help."'),
('1 Samuel', 7, 'teens', 5, 'In what cities did Samuel judge Israel each year by making a circuit?', 'Bethel, Gilgal, and Mizpeh — and then returned to Ramah', 'Shiloh, Hebron, and Beersheba', 'Ramah, Gibeah, and Jerusalem', 'Dan, Bethel, and Gilgal', 'a', '1 Samuel 7:16 — "He went from year to year in circuit to Bethel, and Gilgal, and Mizpeh, and judged Israel in all those places."'),
-- Adults
('1 Samuel', 7, 'adults', 1, 'Who was consecrated to keep the ark at Kirjath-jearim, and what was his role?', 'Eleazar the son of Abinadab was sanctified to keep the ark of the LORD', 'The whole house of Abinadab served as keepers of the ark', 'A Levite named Uzzah was appointed guardian of the ark', 'Phinehas''s son was given charge of the ark', 'a', '1 Samuel 7:1 — "They sanctified Eleazar his son to keep the ark of the LORD."'),
('1 Samuel', 7, 'adults', 2, 'What does the pouring out of water before the LORD at Mizpeh signify in this context?', 'It was a symbolic act of total humility and self-emptying before God, an outward sign of inward contrition', 'It was a libation offering prescribed in the law of Moses', 'Water was poured to purify the gathering place before sacrifice', 'It demonstrated that Israel''s strength was poured out and they depended wholly on God', 'a', '1 Samuel 7:6 — "They drew water, and poured it out before the LORD." This unique act expressed self-abasement and surrender before God.'),
('1 Samuel', 7, 'adults', 3, 'What burnt offering did Samuel offer during the battle, and at what critical moment did God intervene?', 'Samuel offered a suckling lamb; the LORD thundered upon the Philistines while Samuel was offering it', 'Samuel offered a ram as the Philistines advanced', 'Samuel offered the first of the harvest when the Philistines drew near', 'Samuel offered two doves before the Philistines reached Mizpeh', 'a', '1 Samuel 7:9-10 — "Samuel took a sucking lamb, and offered it for a burnt offering wholly unto the LORD... And as Samuel was offering up the burnt offering, the Philistines drew near... the LORD thundered."'),
('1 Samuel', 7, 'adults', 4, 'What territorial consequence followed the Philistine defeat at Mizpeh in Samuel''s time?', 'The cities which the Philistines had taken from Israel were restored to Israel, from Ekron even unto Gath', 'Israel captured Ashdod and Gaza in the following campaign', 'The Philistines paid tribute to Israel for twenty years', 'Philistia lost its five-lord system and was reduced to two cities', 'a', '1 Samuel 7:14 — "The cities which the Philistines had taken from Israel were restored to Israel, from Ekron even unto Gath: and the coasts thereof did Israel deliver out of the hands of the Philistines."'),
('1 Samuel', 7, 'adults', 5, 'What is the significance of the statement that the Philistines "came no more into the coast of Israel" during Samuel''s time?', 'It demonstrates that genuine national repentance and obedience to God results in security from enemies, validating the Deuteronomic principle', 'It shows that Samuel''s military prowess defeated Philistia permanently', 'It confirms that the ark''s return removed all supernatural power from Philistia', 'It means the Philistines turned to worshipping the God of Israel', 'a', '1 Samuel 7:13 — "So the Philistines were subdued, and they came no more into the coast of Israel: and the hand of the LORD was against the Philistines all the days of Samuel."'),
('1 Samuel', 7, 'adults', 6, 'What does Samuel''s annual circuit of Bethel, Gilgal, and Mizpeh tell us about his role in Israel''s governance?', 'He served as a travelling judge bringing covenant justice to multiple tribal centres throughout the land', 'He was primarily a military commander who inspected the tribal armies', 'He collected tithes on behalf of the Levites at each city', 'He served as high priest performing sacrifices at each location', 'a', '1 Samuel 7:15-17 — "Samuel judged Israel all the days of his life. And he went from year to year in circuit to Bethel, and Gilgal, and Mizpeh, and judged Israel."'),
('1 Samuel', 7, 'adults', 7, 'Where was Samuel''s home base and where did he build an altar to the LORD?', 'Ramah — his house was there, and he built an altar to the LORD there', 'Shiloh — he remained at the tabernacle site', 'Bethel — he built the altar at the central sanctuary', 'Mizpeh — where the great assembly had been held', 'a', '1 Samuel 7:17 — "His return was to Ramah; for there was his house; and there he judged Israel; and there he built an altar unto the LORD."'),
('1 Samuel', 7, 'adults', 8, 'How does chapter 7 establish Samuel as the last and greatest of the judges of Israel?', 'He combines the roles of prophet, priest, and judge; brings national repentance; delivers Israel militarily; and administers justice throughout the land', 'He is the only judge who never sinned against Israel', 'He served longer than any other judge recorded in Scripture', 'He was chosen by God through direct appointment rather than by military victory', 'a', '1 Samuel 7:6,9,15-17 — Samuel judged Israel, interceded as priest, prophesied, and delivered them from Philistines, fulfilling all three offices of prophet, priest, and judge.');

-- ═══ 1 Samuel Chapter 8 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 8, 'kids', 1, 'What did the people of Israel ask Samuel to give them?', 'A king to judge them like all the nations', 'More soldiers to fight the Philistines', 'A new priest to lead them', 'A temple like other nations had', 'a', '1 Samuel 8:5 — "Make us a king to judge us like all the nations."'),
('1 Samuel', 8, 'kids', 2, 'How did Samuel feel when the people asked for a king?', 'The thing displeased Samuel', 'Samuel was happy and agreed at once', 'Samuel wept for many days', 'Samuel refused and sent them away', 'a', '1 Samuel 8:6 — "But the thing displeased Samuel, when they said, Give us a king to judge us."'),
('1 Samuel', 8, 'kids', 3, 'What did God tell Samuel the people were really rejecting by asking for a king?', 'They had not rejected Samuel, but they had rejected God that He should not reign over them', 'They were rejecting the priesthood and the temple', 'They were rejecting the covenant God made with Abraham', 'They were rejecting Samuel''s sons as judges', 'a', '1 Samuel 8:7 — "The LORD said unto Samuel... they have not rejected thee, but they have rejected me, that I should not reign over them."'),
-- Teens
('1 Samuel', 8, 'teens', 1, 'Why did the elders of Israel give as their reason for wanting a king?', 'Samuel was old and his sons walked not in his ways', 'The Philistines had grown too strong for Israel', 'God had not spoken to Israel for many years', 'Samuel had moved too far away to judge them', 'a', '1 Samuel 8:5 — "Behold, thou art old, and thy sons walk not in thy ways: now make us a king to judge us like all the nations."'),
('1 Samuel', 8, 'teens', 2, 'What were the names of Samuel''s sons who were corrupt judges?', 'Joel and Abijah', 'Hophni and Phinehas', 'Phineas and Gershom', 'Nadab and Abihu', 'a', '1 Samuel 8:2-3 — "The name of his firstborn was Joel; and the name of his second, Abiah... and his sons walked not in his ways, but turned aside after lucre, and took bribes."'),
('1 Samuel', 8, 'teens', 3, 'What would a king do with the people''s sons, according to Samuel''s warning?', 'He will take your sons and appoint them for his chariots and to be his horsemen and to run before his chariots', 'He will tax their sons at one-tenth of all they earn', 'He will press their sons into service as temple workers', 'He will take their sons as hostages to guarantee loyalty', 'a', '1 Samuel 8:11 — "He will take your sons, and appoint them for himself, for his chariots, and to be his horsemen; and some shall run before his chariots."'),
('1 Samuel', 8, 'teens', 4, 'What proportion of the people''s grain, vineyards, and flocks would the king take, according to Samuel?', 'A tenth of their seed, vineyards, and flocks', 'A fifth of all their produce each year', 'A third of their crops and half their flocks', 'Half of their land and a quarter of their harvest', 'a', '1 Samuel 8:15,17 — "He will take the tenth of your seed, and of your vineyards... He will take the tenth of your sheep."'),
('1 Samuel', 8, 'teens', 5, 'What did God tell Samuel to do after the people insisted on having a king despite the warning?', 'Hearken unto their voice, and make them a king', 'Refuse them a second time and pray for three days', 'Cast lots to determine God''s will', 'Anoint Samuel''s eldest son as a compromise', 'a', '1 Samuel 8:22 — "The LORD said to Samuel, Hearken unto their voice, and make them a king."'),
-- Adults
('1 Samuel', 8, 'adults', 1, 'What parallel does God draw between Israel''s demand for a king and their historical pattern of idolatry?', 'According as they have forsaken me and served other gods, so do they also unto thee', 'The people had rejected every prophet since Moses in the same way', 'Their desire for a king was like their earlier desire to return to Egypt', 'They had rejected every covenant renewal from the time of Joshua', 'a', '1 Samuel 8:8 — "According to all the works which they have done since the day that I brought them up out of Egypt even unto this day, wherewith they have forsaken me, and served other gods, so do they also unto thee."'),
('1 Samuel', 8, 'adults', 2, 'What does God''s instruction to Samuel — "protest solemnly unto them" — reveal about divine governance even when granting sinful requests?', 'God permits what He does not approve, but ensures the people are warned and accept full responsibility for consequences', 'God was unsure whether to grant their request and needed time to decide', 'God required a formal legal process before changing Israel''s government', 'God was testing Samuel''s willingness to obey even when disagreeing', 'a', '1 Samuel 8:9 — "Howbeit yet protest solemnly unto them, and shew them the manner of the king that shall reign over them."'),
('1 Samuel', 8, 'adults', 3, 'What would a king do with the Israelites'' daughters, according to Samuel''s warning?', 'He will take your daughters to be confectionaries, and to be cooks, and to be bakers', 'He will make their daughters work in his fields', 'He will take their daughters as wives for his sons', 'He will put their daughters in charge of the royal storehouses', 'a', '1 Samuel 8:13 — "He will take your daughters to be confectionaries, and to be cooks, and to be bakers."'),
('1 Samuel', 8, 'adults', 4, 'What is the ultimate economic consequence Samuel predicts will reduce Israel to servitude?', 'Ye shall be his servants', 'They will lose their land and become tenant farmers', 'The king will sell them into foreign slavery', 'They will owe perpetual military service with no wages', 'a', '1 Samuel 8:17 — "He will take the tenth of your sheep: and ye shall be his servants."'),
('1 Samuel', 8, 'adults', 5, 'What warning did God give about Israel''s future prayers when they cry out because of their king?', 'The LORD will not hear them in that day', 'God would answer their prayers but add to their suffering', 'Their prayers would be delayed forty years', 'God would hear them but the king would remain', 'a', '1 Samuel 8:18 — "Ye shall cry out in that day because of your king which ye shall have chosen you; and the LORD will not hear you in that day."'),
('1 Samuel', 8, 'adults', 6, 'What theological significance lies in the phrase "like all the nations" (v.5,20)?', 'Israel was called to be distinct from the nations under God''s kingship; desiring conformity to the nations was a rejection of their covenant identity', 'The phrase shows Israel wanted military strength comparable to their neighbours', 'It reflects the people''s desire for stability and predictable governance', 'It shows that Israel admired Canaanite administrative systems', 'a', '1 Samuel 8:5,20 — "Make us a king to judge us like all the nations... that we also may be like all the nations." Israel''s calling was to be holy and separate (Deuteronomy 7:6).'),
('1 Samuel', 8, 'adults', 7, 'What does God''s statement "they have rejected me, that I should not reign over them" reveal about the nature of Israel''s theocracy?', 'Israel was meant to be a theocracy with God as their direct sovereign King; demanding a human king was a constitutional rejection of divine rule', 'God was disappointed but had expected this outcome from the beginning', 'The statement shows God''s kingship had been only symbolic since the time of the judges', 'God''s reign referred only to His religious authority, not civil governance', 'a', '1 Samuel 8:7 — "They have not rejected thee, but they have rejected me, that I should not reign over them." This reveals God''s direct kingship over Israel as the fundamental principle of the Mosaic covenant.'),
('1 Samuel', 8, 'adults', 8, 'How does Samuel''s warning about the "manner of the king" (mishpat hammelek) reflect the cautions God gave about kings in Deuteronomy 17?', 'Both passages warn that a king will accumulate wealth, horses, and power, leading the people away from dependence on God', 'Samuel''s warning contradicts Deuteronomy by opposing kingship entirely', 'Deuteronomy 17 only addresses foreign kings, not Israelite ones', 'Samuel''s warning adds economic details not present in Deuteronomy 17', 'a', 'Deuteronomy 17:16-17 warns the king not to multiply horses, wives, or silver and gold. Samuel''s warning in 1 Samuel 8:11-18 details exactly these abuses, showing the king''s "manner" would violate Deuteronomic limits.');

-- ═══ 1 Samuel Chapter 9 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 9, 'kids', 1, 'What was Saul looking for when he met Samuel?', 'His father''s donkeys that were lost', 'His brother who had run away', 'Sheep that had strayed from the flock', 'A place to build a house', 'a', '1 Samuel 9:3 — "The asses of Kish Saul''s father were lost. And Kish said to Saul his son, Take now one of the servants with thee, and arise, go seek the asses."'),
('1 Samuel', 9, 'kids', 2, 'From which tribe was Saul, the man God chose to be king?', 'Benjamin', 'Judah', 'Ephraim', 'Levi', 'a', '1 Samuel 9:1 — "There was a man of Benjamin, whose name was Kish... And he had a son, whose name was Saul."'),
('1 Samuel', 9, 'kids', 3, 'How tall was Saul compared to all the people of Israel?', 'From his shoulders and upward he was higher than any of the people', 'He was the tallest man in all the world', 'He was twice as tall as other men', 'He was taller than all men by a full cubit', 'a', '1 Samuel 9:2 — "From his shoulders and upward he was higher than any of the people."'),
-- Teens
('1 Samuel', 9, 'teens', 1, 'What offering did Saul''s servant suggest they bring to the man of God, since Saul had nothing?', 'The fourth part of a shekel of silver', 'A loaf of bread from their provision', 'A young goat from the flock', 'Nothing, for men of God do not take payment', 'a', '1 Samuel 9:8 — "The servant answered Saul again, and said, Behold, I have here at hand the fourth part of a shekel of silver: that will I give to the man of God."'),
('1 Samuel', 9, 'teens', 2, 'What had God told Samuel the day before Saul arrived?', 'To morrow about this time I will send thee a man out of the land of Benjamin, and thou shalt anoint him to be captain', 'That the king of Israel would come to him from the north', 'That a man seeking lost sheep would become king', 'That Samuel should wait at the gate of the city for the chosen man', 'a', '1 Samuel 9:16 — "To morrow about this time I will send thee a man out of the land of Benjamin, and thou shalt anoint him to be captain over my people Israel."'),
('1 Samuel', 9, 'teens', 3, 'What did Samuel tell Saul about the donkeys as soon as they met?', 'The asses which were lost three days ago have been found — set not thy mind on them', 'The donkeys had been found and were safe in the city', 'Forget the donkeys; God has greater things for you', 'The donkeys were lost but would be returned by morning', 'a', '1 Samuel 9:20 — "As for thine asses that were lost three days ago, set not thy mind on them; for they are found."'),
('1 Samuel', 9, 'teens', 4, 'What surprised Saul about Samuel''s words regarding "all the desire of Israel"?', 'He was from the smallest tribe of Benjamin, the least family — why was such honour spoken to him?', 'He was too young to be king and had no experience in battle', 'He had not sought the kingship and wanted to remain a farmer', 'He could not understand how a lost donkey search led to a throne', 'a', '1 Samuel 9:21 — "Saul answered and said, Am not I a Benjamite, of the smallest of the tribes of Israel? and my family the least of all the families of the tribe of Benjamin?"'),
('1 Samuel', 9, 'teens', 5, 'What honour did Samuel give Saul at the feast with the thirty invited guests?', 'He set before him the shoulder and that which was upon it, saying it was kept for him', 'He gave Saul the seat of honour at the head of the table', 'He poured wine for Saul with his own hand before all the guests', 'He announced Saul as the future king before all thirty men', 'a', '1 Samuel 9:24 — "The cook took up the shoulder, and that which was upon it, and set it before Saul. And Samuel said, Behold that which is left! set it before thee, and eat: for unto this time hath it been kept for thee."'),
-- Adults
('1 Samuel', 9, 'adults', 1, 'Who was Saul''s father, and how is Saul''s physical description given in the opening verses?', 'His father was Kish, a Benjamite; Saul was a choice young man and goodly, and there was not among the children of Israel a goodlier person than he', 'His father was Abiel, a warrior; Saul was mighty in stature and renowned for strength', 'His father was Kish; Saul was wise and learned in all the ways of the judges', 'His father was Ner; Saul was humble and devoted to the LORD from youth', 'a', '1 Samuel 9:1-2 — "Kish... a Benjamite... had a son, whose name was Saul, a choice young man, and a goodly: and there was not among the children of Israel a goodlier person than he."'),
('1 Samuel', 9, 'adults', 2, 'What does the parenthetical note in verse 9 tell us about the changing title from "seer" to "prophet"?', 'Beforetime in Israel, when a man went to inquire of God, he said, Come let us go to the seer — for he that is now called a Prophet was beforetime called a Seer', 'Samuel was called a seer because he had visions, not because he spoke God''s word', 'The note explains that seer and prophet were two different offices in Israel', 'The author notes that Samuel preferred the title of priest over prophet', 'a', '1 Samuel 9:9 — "Beforetime in Israel, when a man went to enquire of God, thus he spake, Come, and let us go to the seer: for he that is now called a Prophet was beforetime called a Seer."'),
('1 Samuel', 9, 'adults', 3, 'What did God say was His purpose in sending Saul as captain over Israel?', 'That he may save my people out of the hand of the Philistines: for I have looked upon my people, because their cry is come unto me', 'To establish the kingdom of Israel among the nations', 'To build a house for the LORD at Jerusalem', 'To bring the twelve tribes under one administration', 'a', '1 Samuel 9:16 — "He shall save my people out of the hand of the Philistines: for I have looked upon my people, because their cry is come unto me."'),
('1 Samuel', 9, 'adults', 4, 'When Samuel saw Saul, what did the LORD tell him?', 'Behold the man whom I spake to thee of! this same shall reign over my people', 'This is the man chosen before the foundation of the world', 'Anoint him now while the people are gathered', 'Test him first to see if he will obey', 'a', '1 Samuel 9:17 — "When Samuel saw Saul, the LORD said unto him, Behold the man whom I spake to thee of! this same shall reign over my people."'),
('1 Samuel', 9, 'adults', 5, 'How does Saul''s route in searching for the donkeys — through Mount Ephraim, Shalisha, Shalim, and Zuph — serve the narrative purpose?', 'It shows how God''s providence guides even mundane events (a lost donkey search) to fulfil His sovereign plan for Israel''s king', 'It demonstrates Saul''s thoroughness and perseverance as a future leader', 'It maps the territory Saul would one day govern as king', 'It reveals Saul''s knowledge of all the tribes'' territories', 'a', '1 Samuel 9:4-6 — The circuitous search through multiple districts brought Saul precisely to Ramah where Samuel waited, illustrating divine providence in ordinary circumstances.'),
('1 Samuel', 9, 'adults', 6, 'What does the detail that Samuel told the cook to set aside the shoulder portion specifically for Saul suggest?', 'Samuel had been divinely informed to expect Saul and had prepared the choicest portion for him — God orchestrated every detail', 'The shoulder was a standard gift for honoured guests in Israelite custom', 'Samuel was showing Saul that he would bear Israel''s burden as king', 'The cook had kept the portion because no suitable guest had come to claim it', 'a', '1 Samuel 9:24 — "Set it before thee, and eat: for unto this time hath it been kept for thee." Samuel had prepared this before Saul arrived, confirming God''s foreknowledge and direction.'),
('1 Samuel', 9, 'adults', 7, 'What does Saul''s humility about his tribe and family reveal about God''s principle of election in choosing Israel''s first king?', 'God chose the man from the smallest tribe and least family to show that His election defies human calculations of greatness', 'Saul''s humility was a pretence covering his ambition for power', 'God chose Benjamin because they were fierce warriors despite their small number', 'Saul''s small tribe made him acceptable to all twelve tribes without jealousy', 'a', '1 Samuel 9:21 — "Am not I a Benjamite, of the smallest of the tribes of Israel? and my family the least of all the families?" God''s election operates by grace, not human merit (cf. 1 Corinthians 1:27).'),
('1 Samuel', 9, 'adults', 8, 'Where did Samuel and Saul speak together at length, and what does this private dialogue before the public anointing signify?', 'They communed on the top of the house — this private preparation before the public announcement reflects God''s personal calling preceding public commission', 'They spoke in the tabernacle before the ark — showing the anointing was a sacred covenant', 'They talked at the city gate where judges sat — indicating Saul was already judged worthy', 'They communed in the field outside the city — to avoid being overheard by the thirty guests', 'a', '1 Samuel 9:25 — "When they were come down from the high place into the city, Samuel communed with Saul upon the top of the house." This rooftop meeting prefigures the private anointing in chapter 10.');

-- ═══ 1 Samuel Chapter 10 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 Samuel', 10, 'kids', 1, 'What did Samuel pour on Saul''s head when he anointed him?', 'A vial of oil', 'Water from the Jordan', 'Precious perfume', 'Holy water from the tabernacle', 'a', '1 Samuel 10:1 — "Samuel took a vial of oil, and poured it upon his head, and kissed him."'),
('1 Samuel', 10, 'kids', 2, 'What happened to Saul when the Spirit of God came upon him?', 'He prophesied among the prophets', 'He fell to the ground in a trance', 'He spoke in a strange tongue', 'He ran to tell his family', 'a', '1 Samuel 10:10 — "The Spirit of God came upon him, and he prophesied among them."'),
('1 Samuel', 10, 'kids', 3, 'How was Saul chosen as king before all the people at Mizpeh?', 'He was taken by lot', 'Samuel called him forward by name', 'An angel pointed to him', 'He won a contest of strength', 'a', '1 Samuel 10:20-21 — "Samuel had caused all the tribes of Israel to come near... and Saul the son of Kish was taken."'),
-- Teens
('1 Samuel', 10, 'teens', 1, 'What three signs did Samuel tell Saul would happen to confirm his anointing?', 'He would meet two men by Rachel''s sepulchre about the asses, then three men going to Bethel, then a company of prophets from the high place', 'He would find a white horse, a burning bush, and an angel', 'He would hear his name called three times, find silver in his bag, and see the ark move', 'He would receive a message from God at dawn, see a vision at noon, and hear thunder at sunset', 'a', '1 Samuel 10:2-5 — Samuel predicted three consecutive signs: men at Rachel''s sepulchre confirming the asses were found (v.2), three men with goats/loaves/wine at the oak of Tabor (v.3-4), and prophets prophesying at the Philistine hill (v.5).'),
('1 Samuel', 10, 'teens', 2, 'What were the prophets doing when Saul met them coming down from the high place?', 'Prophesying with a psaltery, tabret, pipe, and harp before them', 'Reading the law aloud in the streets', 'Praying with their faces to the ground', 'Carrying the ark on their shoulders', 'a', '1 Samuel 10:5 — "A company of prophets coming down from the high place with a psaltery, and a tabret, and a pipe, and a harp, before them; and they shall prophesy."'),
('1 Samuel', 10, 'teens', 3, 'What question became a proverb in Israel about Saul''s prophesying?', 'Is Saul also among the prophets?', 'Has the Spirit of God changed Saul''s heart?', 'Why does the son of Kish speak like a prophet?', 'Who made Saul a prophet over Israel?', 'a', '1 Samuel 10:11 — "And it came to pass, when all that knew him beforetime saw that, behold, he prophesied among the prophets, then the people said one to another, Is Saul also among the prophets?"'),
('1 Samuel', 10, 'teens', 4, 'What did God promise to do to Saul as a result of the Spirit coming upon him?', 'Turn him into another man and the signs would come to pass', 'Give him victory over the Philistines in three battles', 'Show him the full plan for his kingdom', 'Keep the Spirit upon him all the days of his reign', 'a', '1 Samuel 10:6-7 — "The Spirit of the LORD will come upon thee, and thou shalt prophesy with them, and shalt be turned into another man."'),
('1 Samuel', 10, 'teens', 5, 'Where did Saul hide when the time came to present him as king before all Israel?', 'Among the stuff (baggage)', 'In his father''s house', 'In the fields outside Mizpeh', 'Behind the great stone Ebenezer', 'a', '1 Samuel 10:22 — "The LORD answered, Behold, he hath hid himself among the stuff."'),
-- Adults
('1 Samuel', 10, 'adults', 1, 'What did Samuel declare to Saul at the moment of anointing regarding Israel and God''s command?', 'Is it not because the LORD hath anointed thee to be captain over his inheritance?', 'From this day thou art king over Israel by the will of the LORD', 'God has chosen thee to deliver Israel from all her enemies', 'Thou art appointed shepherd over the people of the LORD', 'a', '1 Samuel 10:1 — "Samuel took a vial of oil, and poured it upon his head... and said, Is it not because the LORD hath anointed thee to be captain over his inheritance?"'),
('1 Samuel', 10, 'adults', 2, 'In the second sign, what three things were the three men carrying when Saul would meet them at the plain of Tabor?', 'Three kids, three loaves of bread, and a bottle of wine', 'Three lambs, seven loaves, and a skin of oil', 'Two doves, five loaves, and a flask of wine', 'Three bullocks, three ephah of flour, and three bottles of wine', 'a', '1 Samuel 10:3 — "Three men going up to God to Bethel, one carrying three kids, and another carrying three loaves of bread, and another carrying a bottle of wine."'),
('1 Samuel', 10, 'adults', 3, 'What instruction did Samuel give Saul about the garrison of the Philistines at Gibeah?', 'That he should do as occasion serve thee; for God is with thee', 'That he should gather Israel and attack the garrison at once', 'That he should wait for Samuel''s signal before acting', 'That the garrison would flee at the sound of his trumpet', 'a', '1 Samuel 10:7 — "And let it be, when these signs are come unto thee, that thou do as occasion serve thee; for God is with thee."'),
('1 Samuel', 10, 'adults', 4, 'What were the two loaves of bread that the three men gave Saul, and what does his receiving them signify?', 'They gave him two loaves and he received them out of their hand — signifying God''s provision confirming the anointing through a spontaneous gift from strangers', 'Two loaves were the prescribed gift to a newly anointed king in Israel', 'The loaves were a tithe offering which Saul was to bring to the high place', 'The loaves represented the double portion of a firstborn, confirming Saul''s royal birthright', 'a', '1 Samuel 10:4 — "They will salute thee, and give thee two loaves of bread; which thou shalt receive of their hands."'),
('1 Samuel', 10, 'adults', 5, 'What does Samuel command Saul to do at Gilgal, and for how long is he to wait?', 'Go down to Gilgal before him; he will come down to offer burnt offerings and peace offerings — Saul must tarry seven days', 'Go to Gilgal and gather the elders of Israel to confirm the kingdom', 'Wait at Gilgal until the Philistine threat passes then receive further instruction', 'Arrive at Gilgal by the third day and pray until Samuel arrives', 'a', '1 Samuel 10:8 — "Thou shalt go down before me to Gilgal; and, behold, I will come down unto thee, to offer burnt offerings... seven days shalt thou tarry, till I come to thee."'),
('1 Samuel', 10, 'adults', 6, 'What is the theological significance of Saul being "turned into another man" when the Spirit came upon him?', 'The transformation showed that God''s Spirit equips for His purposes — the new Saul was fitted for kingship by divine enablement, not natural ability', 'Saul underwent a physical change making him even taller and stronger', 'The phrase means Saul''s personality changed permanently for the better', 'Saul received a new name from God as a sign of his calling', 'a', '1 Samuel 10:6 — "Thou shalt be turned into another man." God supernaturally equipped Saul for the role He assigned him, as He does with all He calls (cf. Ezekiel 36:26).'),
('1 Samuel', 10, 'adults', 7, 'How did Samuel present Saul to the assembled people, and what was Samuel''s speech about the LORD''s salvation before the lot was cast?', 'Samuel rehearsed the LORD''s deeds in delivering Israel from Egypt and all kingdoms, noting they had asked for a king and now stood before the LORD by tribes', 'Samuel rebuked the people again for wanting a king before proceeding to the lot', 'Samuel read the law of the king from Deuteronomy and then cast the lot', 'Samuel prayed silently and then announced that God had shown him the chosen man directly', 'a', '1 Samuel 10:18-19 — "Thus saith the LORD God of Israel, I brought up Israel out of Egypt... ye have this day rejected your God... present yourselves before the LORD by your tribes."'),
('1 Samuel', 10, 'adults', 8, 'What did some sons of Belial say about Saul, and what was Saul''s response that reveals his character at this stage?', 'They despised him and brought no presents; he held his peace', 'They challenged him to prove his worth in battle; Saul called an assembly', 'They demanded Samuel rescind the anointing; Saul rebuked them publicly', 'They questioned his lineage; Saul showed them his genealogy', 'a', '1 Samuel 10:27 — "But the children of Belial said, How shall this man save us? And they despised him, and brought him no presents. But he held his peace."');
