-- ============================================================================
-- Quiz Seed: 2 Peter (Chapters 1–3)
-- 3 difficulties × 3 chapters = 48 total questions
--   kids:   3 per chapter  =  9
--   teens:  5 per chapter  = 15
--   adults: 8 per chapter  = 24
-- ============================================================================

-- ═══ 2 Peter Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Peter', 1, 'kids', 1, 'Who wrote the book of 2 Peter?', 'Simon Peter', 'Paul', 'John', 'James', 'a', '2 Peter 1:1 — "Simon Peter, a servant and an apostle of Jesus Christ."'),
('2 Peter', 1, 'kids', 2, 'What did Peter say we should add to our faith?', 'Virtue, knowledge, temperance, patience, godliness, brotherly kindness, and charity', 'Money and possessions', 'Buildings and land', 'Horses and chariots', 'a', '2 Peter 1:5-7 lists the virtues to add to faith.'),
('2 Peter', 1, 'kids', 3, 'Where did Peter hear God''s voice about Jesus?', 'On the holy mount (mountain)', 'In the temple', 'At the river', 'In a cave', 'a', '2 Peter 1:18 — "this voice which came from heaven we heard, when we were with him in the holy mount."'),
-- Teens
('2 Peter', 1, 'teens', 1, 'What has God''s divine power given us?', 'All things that pertain unto life and godliness, through the knowledge of Him', 'Wealth and political influence', 'Physical strength and health', 'Freedom from all suffering', 'a', '2 Peter 1:3 — "his divine power hath given unto us all things that pertain unto life and godliness."'),
('2 Peter', 1, 'teens', 2, 'What do the exceeding great and precious promises allow us to be?', 'Partakers of the divine nature, having escaped the corruption in the world through lust', 'Equal to God in power', 'Free from all earthly responsibilities', 'Immune to physical death', 'a', '2 Peter 1:4 — "ye might be partakers of the divine nature, having escaped the corruption that is in the world through lust."'),
('2 Peter', 1, 'teens', 3, 'What did God the Father say about Jesus on the mount?', '"This is my beloved Son, in whom I am well pleased"', '"This is my servant whom I have chosen"', '"This is the prophet like Moses"', '"This is the angel of the covenant"', 'a', '2 Peter 1:17 — "This is my beloved Son, in whom I am well pleased."'),
('2 Peter', 1, 'teens', 4, 'What does Peter say about prophecy of Scripture?', 'No prophecy of the scripture is of any private interpretation — holy men spake as moved by the Holy Ghost', 'Anyone can interpret prophecy however they wish', 'Prophecy is outdated and no longer relevant', 'Only priests can understand prophecy', 'a', '2 Peter 1:20-21 — "no prophecy of the scripture is of any private interpretation. For the prophecy came not in old time by the will of man: but holy men of God spake as they were moved by the Holy Ghost."'),
('2 Peter', 1, 'teens', 5, 'What does Peter compare to a light shining in a dark place?', 'The word of prophecy (Scripture), which believers do well to heed', 'A candle in a window', 'The moon at night', 'A campfire in the wilderness', 'a', '2 Peter 1:19 — "We have also a more sure word of prophecy; whereunto ye do well that ye take heed, as unto a light that shineth in a dark place."'),
-- Adults
('2 Peter', 1, 'adults', 1, 'What does Peter say about those who lack the virtues listed in verses 5-7?', 'He that lacketh these things is blind and cannot see afar off, and hath forgotten that he was purged from his old sins', 'He is in danger of losing his salvation', 'He will be excommunicated from the church', 'He will not receive spiritual gifts', 'a', '2 Peter 1:9 — "he that lacketh these things is blind, and cannot see afar off, and hath forgotten that he was purged from his old sins."'),
('2 Peter', 1, 'adults', 2, 'What does Peter say about making your calling and election sure?', 'Give diligence to make your calling and election sure, for if ye do these things ye shall never fall', 'Election is automatic and requires no effort', 'Only apostles need to make their calling sure', 'Calling and election are the same thing', 'a', '2 Peter 1:10 — "give diligence to make your calling and election sure: for if ye do these things, ye shall never fall."'),
('2 Peter', 1, 'adults', 3, 'What will be ministered abundantly to those who practice these virtues?', 'An entrance into the everlasting kingdom of our Lord and Saviour Jesus Christ', 'Material blessings in this life', 'Visions and revelations', 'Authority over other believers', 'a', '2 Peter 1:11 — "so an entrance shall be ministered unto you abundantly into the everlasting kingdom of our Lord and Saviour Jesus Christ."'),
('2 Peter', 1, 'adults', 4, 'Why does Peter say he will always remind them of these things?', 'Because he knows his departure (death) is soon, as the Lord Jesus Christ showed him', 'Because they are forgetful by nature', 'Because he has nothing else to write about', 'Because other apostles asked him to', 'a', '2 Peter 1:14 — "Knowing that shortly I must put off this my tabernacle, even as our Lord Jesus Christ hath shewed me."'),
('2 Peter', 1, 'adults', 5, 'What does Peter claim about following "cunningly devised fables"?', 'They did NOT follow cunningly devised fables — they were eyewitnesses of Christ''s majesty', 'They sometimes used fables for teaching purposes', 'They inherited fables from Jewish tradition', 'They created parables similar to fables', 'a', '2 Peter 1:16 — "we have not followed cunningly devised fables, when we made known unto you the power and coming of our Lord Jesus Christ, but were eyewitnesses of his majesty."'),
('2 Peter', 1, 'adults', 6, 'What does "the day star arise in your hearts" refer to?', 'The dawning of full understanding and hope in Christ, connected to His return — until prophetic Scripture''s truth fully illuminates', 'The morning star Venus appearing in the sky', 'A literal star that appeared at Jesus'' birth', 'The sun rising each morning', 'a', '2 Peter 1:19 — "until the day dawn, and the day star arise in your hearts."'),
('2 Peter', 1, 'adults', 7, 'What does 2 Peter 1:21 say about the origin of Scripture?', 'Prophecy came not by the will of man, but holy men of God spake as they were moved by the Holy Ghost', 'Prophets wrote from their own ideas and experiences', 'Scripture was dictated word-for-word like dictation', 'Prophets received visions but wrote in their own words without guidance', 'a', '2 Peter 1:21 — "the prophecy came not in old time by the will of man: but holy men of God spake as they were moved by the Holy Ghost."'),
('2 Peter', 1, 'adults', 8, 'What does Peter mean by putting off his "tabernacle"?', 'His physical death — he compares his body to a tent that will be taken down, as Jesus Christ revealed to him', 'Leaving his house in Jerusalem', 'Resigning from church leadership', 'Ending his missionary journeys', 'a', '2 Peter 1:14 — "Knowing that shortly I must put off this my tabernacle, even as our Lord Jesus Christ hath shewed me."');

-- ═══ 2 Peter Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Peter', 2, 'kids', 1, 'What did Peter warn would come among believers?', 'False teachers', 'Friendly visitors', 'Rich kings', 'Wild animals', 'a', '2 Peter 2:1 — "there shall be false teachers among you."'),
('2 Peter', 2, 'kids', 2, 'Who did God save when He destroyed the old world with a flood?', 'Noah and seven others (eight people total)', 'Only Noah', 'Noah and twelve others', 'Nobody survived', 'a', '2 Peter 2:5 — "saved Noah the eighth person, a preacher of righteousness."'),
('2 Peter', 2, 'kids', 3, 'What cities did God destroy as an example of punishment?', 'Sodom and Gomorrha', 'Jerusalem and Bethlehem', 'Rome and Athens', 'Babylon and Nineveh', 'a', '2 Peter 2:6 — "turning the cities of Sodom and Gomorrha into ashes condemned them."'),
-- Teens
('2 Peter', 2, 'teens', 1, 'What do the false teachers secretly bring in?', 'Damnable heresies, even denying the Lord that bought them', 'New worship songs', 'Greek philosophy', 'Pagan festivals', 'a', '2 Peter 2:1 — "who privily shall bring in damnable heresies, even denying the Lord that bought them."'),
('2 Peter', 2, 'teens', 2, 'What happened to the angels that sinned?', 'God cast them down to hell (Tartarus) and delivered them into chains of darkness', 'They were forgiven and restored', 'They became human beings', 'They were sent to rule other planets', 'a', '2 Peter 2:4 — "God spared not the angels that sinned, but cast them down to hell, and delivered them into chains of darkness."'),
('2 Peter', 2, 'teens', 3, 'What Old Testament man is called "just Lot" in this chapter?', 'Lot, who was vexed with the filthy conversation of the wicked in Sodom', 'Lot who chose the plains of Jordan greedily', 'Lot who fled from Abraham', 'Lot who built the tower of Babel', 'a', '2 Peter 2:7-8 — "delivered just Lot, vexed with the filthy conversation of the wicked."'),
('2 Peter', 2, 'teens', 4, 'What animal metaphor does Peter use for the false teachers?', 'A dog returning to its own vomit and a washed sow returning to wallow in the mire', 'Wolves in sheep''s clothing', 'Foxes in a henhouse', 'Serpents in the grass', 'a', '2 Peter 2:22 — "The dog is turned to his own vomit again; and the sow that was washed to her wallowing in the mire."'),
('2 Peter', 2, 'teens', 5, 'What does Peter say false teachers promise others?', 'Liberty (freedom), while they themselves are servants of corruption', 'Salvation through good works', 'Earthly riches and power', 'Secret knowledge of the future', 'a', '2 Peter 2:19 — "While they promise them liberty, they themselves are the servants of corruption."'),
-- Adults
('2 Peter', 2, 'adults', 1, 'What does Peter say about God''s ability to distinguish the righteous from the wicked?', 'The Lord knoweth how to deliver the godly out of temptations and to reserve the unjust unto the day of judgment to be punished', 'God treats the righteous and wicked exactly the same', 'God will sort everyone out only at the final judgment', 'God cannot distinguish between them in this life', 'a', '2 Peter 2:9 — "The Lord knoweth how to deliver the godly out of temptations, and to reserve the unjust unto the day of judgment to be punished."'),
('2 Peter', 2, 'adults', 2, 'What does Peter say the false teachers are not afraid to do?', 'Speak evil of dignities (glorious ones), whereas angels who are greater in power do not bring a railing accusation before the Lord', 'They are not afraid to preach in public', 'They are not afraid to fast for many days', 'They are not afraid to visit the sick', 'a', '2 Peter 2:10-11 — "not afraid to speak evil of dignities. Whereas angels, which are greater in power and might, bring not railing accusation against them before the Lord."'),
('2 Peter', 2, 'adults', 3, 'How does Peter describe these false teachers?', 'Natural brute beasts, made to be taken and destroyed — they speak evil of things they understand not and shall utterly perish in their own corruption', 'Educated philosophers who got slightly off track', 'Former good teachers who became discouraged', 'Young converts who need more training', 'a', '2 Peter 2:12 — "as natural brute beasts, made to be taken and destroyed, speak evil of the things that they understand not; and shall utterly perish in their own corruption."'),
('2 Peter', 2, 'adults', 4, 'What does Peter say about Balaam the son of Bosor?', 'He loved the wages of unrighteousness but was rebuked by a dumb ass speaking with man''s voice', 'He was a faithful prophet who never sinned', 'He cursed Israel successfully', 'He repented and became a follower of God', 'a', '2 Peter 2:15-16 — "following the way of Balaam the son of Bosor, who loved the wages of unrighteousness; But was rebuked for his iniquity: the dumb ass speaking with man''s voice forbad the madness of the prophet."'),
('2 Peter', 2, 'adults', 5, 'What does Peter say about those who knew Christ but turned back?', 'The latter end is worse than the beginning — it would have been better for them not to have known the way of righteousness than to turn from the holy commandment', 'They can easily return at any time', 'They were never truly saved', 'God understands and forgives automatically', 'a', '2 Peter 2:20-21 — "the latter end is worse with them than the beginning. For it had been better for them not to have known the way of righteousness."'),
('2 Peter', 2, 'adults', 6, 'What imagery does Peter use for the emptiness of false teachers?', 'Wells without water and clouds carried with a tempest, to whom the mist of darkness is reserved for ever', 'Bright stars that will eventually fade', 'Strong trees that bear no fruit', 'Beautiful birds that cannot sing', 'a', '2 Peter 2:17 — "These are wells without water, clouds that are carried with a tempest; to whom the mist of darkness is reserved for ever."'),
('2 Peter', 2, 'adults', 7, 'What great swelling words do the false teachers use?', 'Great swelling words of vanity to allure through the lusts of the flesh those who had barely escaped from error', 'Precise theological terminology', 'Direct quotations from Scripture', 'Simple parables about farming', 'a', '2 Peter 2:18 — "they speak great swelling words of vanity, they allure through the lusts of the flesh, through much wantonness, those that were clean escaped from them who live in error."'),
('2 Peter', 2, 'adults', 8, 'What principle does Peter state about slavery to sin?', '"Of whom a man is overcome, of the same is he brought in bondage" — whatever masters a person enslaves them', 'Sin can never enslave a believer', 'Only willful sin leads to bondage', 'Bondage only applies to physical slavery', 'a', '2 Peter 2:19 — "of whom a man is overcome, of the same is he brought in bondage."');

-- ═══ 2 Peter Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Peter', 3, 'kids', 1, 'What does Peter say the Lord''s return will come like?', 'A thief in the night', 'A loud trumpet', 'A slow sunrise', 'A gentle rain', 'a', '2 Peter 3:10 — "the day of the Lord will come as a thief in the night."'),
('2 Peter', 3, 'kids', 2, 'Why does God wait patiently before coming back?', 'He does not want anyone to perish but wants all to come to repentance', 'He forgot about us', 'He is too busy', 'He changed His mind', 'a', '2 Peter 3:9 — "not willing that any should perish, but that all should come to repentance."'),
('2 Peter', 3, 'kids', 3, 'What new thing does Peter say believers are looking forward to?', 'New heavens and a new earth where righteousness dwells', 'A new temple', 'A new king', 'A new garden', 'a', '2 Peter 3:13 — "we, according to his promise, look for new heavens and a new earth, wherein dwelleth righteousness."'),
-- Teens
('2 Peter', 3, 'teens', 1, 'What do scoffers say in the last days?', '"Where is the promise of His coming? All things continue as they were from the beginning"', '"We believe God will come tomorrow"', '"Let us prepare for the Lord''s return"', '"The prophets were right about everything"', 'a', '2 Peter 3:4 — "Where is the promise of his coming? for since the fathers fell asleep, all things continue as they were from the beginning of the creation."'),
('2 Peter', 3, 'teens', 2, 'How long is one day with the Lord?', 'As a thousand years, and a thousand years as one day', 'Exactly 24 hours', 'As one hour', 'As one minute', 'a', '2 Peter 3:8 — "one day is with the Lord as a thousand years, and a thousand years as one day."'),
('2 Peter', 3, 'teens', 3, 'What will happen to the heavens and earth on the day of the Lord?', 'The heavens shall pass away with a great noise, the elements shall melt with fervent heat, and the earth and its works shall be burned up', 'They will be renovated and cleaned', 'They will remain exactly as they are', 'They will be given to the angels', 'a', '2 Peter 3:10 — "the heavens shall pass away with a great noise, and the elements shall melt with fervent heat, the earth also and the works that are therein shall be burned up."'),
('2 Peter', 3, 'teens', 4, 'What does Peter say about Paul''s writings?', 'They contain some things hard to understand, which the unlearned and unstable wrest (distort) to their own destruction', 'They are perfectly clear and easy to understand', 'They are not as authoritative as Peter''s', 'They should only be read by scholars', 'a', '2 Peter 3:16 — "in which are some things hard to be understood, which they that are unlearned and unstable wrest, as they do also the other scriptures, unto their own destruction."'),
('2 Peter', 3, 'teens', 5, 'What does Peter exhort believers to grow in?', 'Grace and in the knowledge of our Lord and Saviour Jesus Christ', 'Wealth and influence', 'Military strength', 'Political connections', 'a', '2 Peter 3:18 — "grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ."'),
-- Adults
('2 Peter', 3, 'adults', 1, 'What do scoffers willingly forget according to Peter?', 'That the heavens were of old, and the earth standing out of the water and in the water by the word of God, and the world was destroyed by water', 'That Moses parted the Red Sea', 'That God created light on the first day', 'That the temple was built by Solomon', 'a', '2 Peter 3:5-6 — "they willingly are ignorant of, that by the word of God the heavens were of old… the world that then was, being overflowed with water, perished."'),
('2 Peter', 3, 'adults', 2, 'What does Peter say God''s apparent "slowness" actually represents?', 'Longsuffering toward us — He is not slack concerning His promise but is patient, not willing that any should perish', 'God has forgotten His promise', 'God is unable to fulfill His promise', 'God has changed His plans', 'a', '2 Peter 3:9 — "The Lord is not slack concerning his promise… but is longsuffering to us-ward, not willing that any should perish, but that all should come to repentance."'),
('2 Peter', 3, 'adults', 3, 'What does Peter say the present heavens and earth are reserved for?', 'Fire, being kept unto the day of judgment and perdition of ungodly men', 'Eternal preservation without change', 'Gradual improvement over millennia', 'Division among the righteous', 'a', '2 Peter 3:7 — "the heavens and the earth, which are now, by the same word are kept in store, reserved unto fire against the day of judgment and perdition of ungodly men."'),
('2 Peter', 3, 'adults', 4, 'What does Peter''s reference to Paul''s epistles imply about their status?', 'Peter groups them with "the other scriptures," implying they are recognized as Scripture', 'They are merely helpful letters with no special authority', 'They are equal to but not greater than rabbinical writings', 'They should be treated as personal opinions', 'a', '2 Peter 3:16 — "as they do also the other scriptures" — placing Paul''s writings alongside recognized Scripture.'),
('2 Peter', 3, 'adults', 5, 'What practical question does Peter ask in light of the coming dissolution?', '"What manner of persons ought ye to be in all holy conversation and godliness?" — eschatology should drive holy living', '"How much money should you save for retirement?"', '"Where should you build your houses?"', '"Which political party should you support?"', 'a', '2 Peter 3:11 — "Seeing then that all these things shall be dissolved, what manner of persons ought ye to be in all holy conversation and godliness."'),
('2 Peter', 3, 'adults', 6, 'What does Peter say believers should be looking for and hasting?', 'The coming of the day of God, wherein the heavens being on fire shall be dissolved and elements melt', 'The coming of the Messiah to establish an earthly kingdom', 'The rapture of the church before tribulation', 'The millennium of peace on earth', 'a', '2 Peter 3:12 — "Looking for and hasting unto the coming of the day of God, wherein the heavens being on fire shall be dissolved, and the elements shall melt with fervent heat."'),
('2 Peter', 3, 'adults', 7, 'What does Peter warn believers to beware of?', 'Being led away with the error of the wicked and falling from their own stedfastness', 'Studying too much theology', 'Traveling to foreign countries', 'Making friends outside the church', 'a', '2 Peter 3:17 — "beware lest ye also, being led away with the error of the wicked, fall from your own stedfastness."'),
('2 Peter', 3, 'adults', 8, 'How does 2 Peter end?', 'With a doxology: "To him be glory both now and for ever. Amen." — ascribing glory to Christ eternally', 'With a list of greetings to named individuals', 'With a travel itinerary', 'With a request for financial support', 'a', '2 Peter 3:18 — "To him be glory both now and for ever. Amen."');
