-- ============================================================================
-- Quiz Seed: Joshua — Part 1 (Chapters 1–10)
-- 3 difficulties × 10 chapters = 160 total questions
-- ============================================================================

-- ═══ Joshua Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 1, 'kids', 1, 'Who told Joshua to be strong and of a good courage?', 'God', 'Moses', 'Aaron', 'An angel', 'a', 'Joshua 1:9 — "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."'),
('Joshua', 1, 'kids', 2, 'What land was God giving to the Israelites?', 'Egypt', 'Canaan', 'Babylon', 'Sinai', 'a', 'Joshua 1:2 — "Moses my servant is dead; now therefore arise, go over this Jordan, thou, and all this people, unto the land which I do give to them."'),
('Joshua', 1, 'kids', 3, 'What river did God tell Joshua and the people to cross?', 'The Nile', 'The Euphrates', 'The Jordan', 'The Red Sea', 'a', 'Joshua 1:2 — "Arise, go over this Jordan, thou, and all this people, unto the land which I do give to them."'),
-- Teens
('Joshua', 1, 'teens', 1, 'What did God tell Joshua to meditate on day and night?', 'The stories of the patriarchs', 'This book of the law', 'The songs of Moses', 'The words of the priests', 'a', 'Joshua 1:8 — "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night."'),
('Joshua', 1, 'teens', 2, 'What promise did God give about Joshua''s territory?', 'Every city he attacked would fall', 'Every place the sole of his foot trod upon He would give him', 'He would defeat all enemies in one year', 'His borders would match those of Moses', 'a', 'Joshua 1:3 — "Every place that the sole of your foot shall tread upon, that have I given unto you, as I said unto Moses."'),
('Joshua', 1, 'teens', 3, 'Which two tribes and a half tribe had already received their inheritance on the east side of Jordan?', 'Judah, Benjamin, and half of Ephraim', 'Reuben, Gad, and half of Manasseh', 'Simeon, Levi, and half of Dan', 'Issachar, Zebulun, and half of Naphtali', 'a', 'Joshua 1:12-13 — "And to the Reubenites, and to the Gadites, and to half the tribe of Manasseh, spake Joshua, saying, Remember the word which Moses the servant of the LORD commanded you."'),
('Joshua', 1, 'teens', 4, 'What did the people promise they would do to anyone who rebelled against Joshua''s commands?', 'He would be cast out of the camp', 'He would be put to death', 'He would lose his inheritance', 'He would serve as a slave', 'a', 'Joshua 1:18 — "Whosoever he be that doth rebel against thy commandment, and will not hearken unto thy words in all that thou commandest him, he shall be put to death."'),
('Joshua', 1, 'teens', 5, 'What condition did God attach to Joshua''s prosperity and success?', 'That he offer sacrifices daily', 'That he observe to do all the law and not turn from it', 'That he appoint wise judges over the people', 'That he build an altar at the Jordan', 'a', 'Joshua 1:7-8 — "Only be thou strong and very courageous, that thou mayest observe to do according to all the law...that thou mayest prosper whithersoever thou goest."'),
-- Adults
('Joshua', 1, 'adults', 1, 'What were the exact northern and southern geographical boundaries God promised to Joshua?', 'From the Sea of Galilee to the Negev', 'From the wilderness and Lebanon to the great river Euphrates and the great sea', 'From the Jordan to the Mediterranean coast', 'From Sinai to Damascus', 'a', 'Joshua 1:4 — "From the wilderness and this Lebanon even unto the great river, the river Euphrates...and unto the great sea toward the going down of the sun, shall be your coast."'),
('Joshua', 1, 'adults', 2, 'What specific promise concerning enemies did God give Joshua in verse 5?', 'No enemy would enter the camp', 'There shall not any man be able to stand before thee all the days of thy life', 'He would defeat every enemy in battle', 'His army would never suffer losses', 'a', 'Joshua 1:5 — "There shall not any man be able to stand before thee all the days of thy life: as I was with Moses, so I will be with thee: I will not fail thee, nor forsake thee."'),
('Joshua', 1, 'adults', 3, 'How many times does God command Joshua to "be strong and courageous" in chapter 1?', 'Once', 'Twice', 'Three times', 'Four times', 'a', 'Joshua 1:6, 1:7, and 1:9 each contain a form of the command "be strong and of a good courage," appearing three times in the chapter.'),
('Joshua', 1, 'adults', 4, 'What theological condition for success did God give in Joshua 1:8?', 'Build a tabernacle before entering the land', 'Meditate on the law day and night and observe to do all that is written therein', 'Consult the Urim and Thummim before each battle', 'Offer burnt offerings on the first day of each month', 'a', 'Joshua 1:8 — "This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous."'),
('Joshua', 1, 'adults', 5, 'What was required of the two and a half tribes who had already received their portion east of Jordan?', 'They were excused from further warfare', 'Their armed men were to pass before their brethren and help them take the land', 'They were to remain and guard their cities only', 'They were to send half their warriors', 'a', 'Joshua 1:14 — "Your wives, your little ones, and your cattle, shall remain in the land which Moses gave you...but ye shall pass before your brethren armed."'),
('Joshua', 1, 'adults', 6, 'What was the people''s formal response to Joshua''s leadership, and what precedent did they cite?', 'They pledged their swords to him', 'All that thou commandest us we will do, as we hearkened unto Moses', 'They offered a sacrifice in his honour', 'They proclaimed him king over Israel', 'a', 'Joshua 1:16-17 — "All that thou commandest us we will do, and whithersoever thou sendest us, we will go. According as we hearkened unto Moses in all things, so will we hearken unto thee."'),
('Joshua', 1, 'adults', 7, 'What is the theological significance of God saying "I will not fail thee, nor forsake thee" to Joshua?', 'It was a military guarantee only', 'It is a covenantal assurance echoed in Hebrews 13:5, showing God''s unchanging faithfulness to his servants', 'It was a one-time promise limited to the conquest', 'It showed Joshua was sinless', 'a', 'Joshua 1:5 and Hebrews 13:5 — "I will never leave thee, nor forsake thee" — demonstrate that God''s commitment to Joshua reflects his eternal covenant faithfulness to all who trust him.'),
('Joshua', 1, 'adults', 8, 'Why were the two and a half tribes'' fighting men obligated to cross the Jordan with their brethren even though their own land was already secured?', 'Moses had forced them', 'Their agreement with Moses required them to assist their brethren until the whole land was given rest', 'They had no cities to defend yet', 'God commanded them at Sinai', 'a', 'Joshua 1:13-15 — "Remember the word which Moses the servant of the LORD commanded you...ye shall return unto the land of your possession, and enjoy it, which Moses the LORD''s servant gave you on this side Jordan."');

-- ═══ Joshua Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 2, 'kids', 1, 'What woman hid the two spies that Joshua sent to Jericho?', 'Rahab', 'Deborah', 'Ruth', 'Hannah', 'a', 'Joshua 2:1 — "Joshua...sent out of Shittim two men to spy secretly...and they came into an harlot''s house, named Rahab, and lodged there."'),
('Joshua', 2, 'kids', 2, 'Where did Rahab hide the two spies?', 'In a well', 'Under the stalks of flax on the roof', 'In a cave outside the city', 'In a cellar beneath her house', 'a', 'Joshua 2:6 — "But she had brought them up to the roof of the house, and hid them with the stalks of flax, which she had laid in order upon the roof."'),
('Joshua', 2, 'kids', 3, 'What sign did Rahab hang in her window so the Israelites would spare her family?', 'A white flag', 'A line of scarlet thread', 'A bunch of hyssop', 'A lamb''s bone', 'a', 'Joshua 2:21 — "And she bound the scarlet line in the window."'),
-- Teens
('Joshua', 2, 'teens', 1, 'What had the people of Jericho heard that caused their hearts to melt in fear?', 'That Joshua was a mighty warrior', 'That the LORD dried up the Red Sea and what Israel did to the Amorite kings', 'That Israel had a great army', 'That God spoke to Joshua from a cloud', 'a', 'Joshua 2:10-11 — "For we have heard how the LORD dried up the water of the Red sea...and as soon as we had heard these things, our hearts did melt."'),
('Joshua', 2, 'teens', 2, 'What did Rahab confess about the LORD?', 'That he was a God of war', 'That the LORD your God, he is God in heaven above and in earth beneath', 'That he was stronger than Baal', 'That he would forgive all nations', 'a', 'Joshua 2:11 — "For the LORD your God, he is God in heaven above, and in earth beneath."'),
('Joshua', 2, 'teens', 3, 'What condition did the spies place on their oath to Rahab?', 'She had to leave the city before they came', 'She had to bind the scarlet thread in the window and gather all her family into her house', 'She had to tell no one', 'She had to provide food for the army', 'a', 'Joshua 2:18-19 — "Thou shalt bind this line of scarlet thread in the window...and thou shalt bring thy father, and thy mother, and thy brethren, and all thy father''s household, home unto thee."'),
('Joshua', 2, 'teens', 4, 'What route did Rahab use to let the spies down from her house?', 'She bribed the guards to open the gate', 'She let them down by a cord through the window, for her house was on the city wall', 'She dressed them as merchants', 'She led them through a tunnel', 'a', 'Joshua 2:15 — "Then she let them down by a cord through the window: for her house was upon the town wall, and she dwelt upon the wall."'),
('Joshua', 2, 'teens', 5, 'Where did the spies hide for three days at Rahab''s instruction before returning to Joshua?', 'In the house of a friendly merchant', 'In the mountain', 'In a cave near the river', 'In the fields outside the city', 'a', 'Joshua 2:16 — "Get you to the mountain, lest the pursuers meet you; and hide yourselves there three days, until the pursuers be returned."'),
-- Adults
('Joshua', 2, 'adults', 1, 'What theological significance does Rahab''s faith carry in the New Testament?', 'She is mentioned only in genealogies', 'She is cited in Hebrews 11:31 and James 2:25 as an example of saving faith demonstrated by works', 'She represents the conversion of all Canaanites', 'She is a type of the church', 'a', 'Hebrews 11:31 — "By faith the harlot Rahab perished not with them that believed not." James 2:25 — "Was not Rahab the harlot justified by works, when she had received the messengers?"'),
('Joshua', 2, 'adults', 2, 'What specific intelligence did the spies report to Joshua after returning from Jericho?', 'The city''s walls were weakest at the north', 'Truly the LORD hath delivered into our hands all the land; for even all the inhabitants of the country do faint because of us', 'The city had a large army but few supplies', 'The gates were guarded by night only', 'a', 'Joshua 2:24 — "And they said unto Joshua, Truly the LORD hath delivered into our hands all the land; for even all the inhabitants of the country do faint because of us."'),
('Joshua', 2, 'adults', 3, 'What was Rahab''s request in exchange for protecting the spies?', 'A portion of land in Canaan', 'That the Israelites would show kindness to her father''s house and give a true token', 'That she be made a princess in Israel', 'That her debts be forgiven', 'a', 'Joshua 2:12 — "Now therefore, I pray you, swear unto me by the LORD, since I have shewed you kindness, that ye will also shew kindness unto my father''s house, and give me a true token."'),
('Joshua', 2, 'adults', 4, 'What was the kings'' response when told the spies had come to Jericho?', 'He ordered the city gates sealed', 'He sent men to Rahab''s house demanding she bring out the men', 'He sent soldiers to the Jordan to intercept them', 'He consulted his priests', 'a', 'Joshua 2:3 — "And the king of Jericho sent unto Rahab, saying, Bring forth the men that are come to thee, which are entered into thine house: for they be come to search out all the country."'),
('Joshua', 2, 'adults', 5, 'What lie did Rahab tell the king''s messengers, and what does this raise theologically?', 'She said they had never arrived', 'She said the men had gone out before the gate shut at dark and she did not know where they went', 'She said they were merchants', 'She said they had already left for Egypt', 'a', 'Joshua 2:4-5 — "She said, There came men unto me, but I wist not whence they were...the men went out: whither the men went I wot not." This raises theological debate about deception in service of a greater good.'),
('Joshua', 2, 'adults', 6, 'What does the scarlet cord hung by Rahab typologically foreshadow in Christian interpretation?', 'The law given at Sinai', 'The blood of Christ that marks believers for salvation, parallel to the Passover blood on the doorposts', 'The priestly garments of Aaron', 'The red heifer offering', 'a', 'The scarlet thread in Rahab''s window (Joshua 2:21) has been interpreted by church fathers as a type of Christ''s blood, analogous to the blood on the doorposts at Passover (Exodus 12:13).'),
('Joshua', 2, 'adults', 7, 'How does Rahab appear in the genealogy of Jesus in the New Testament?', 'She is not mentioned', 'She is listed in Matthew 1:5 as the mother of Boaz, placing her in the Messianic line', 'She is mentioned in Luke''s genealogy only', 'She is listed as an ancestor of John the Baptist', 'a', 'Matthew 1:5 — "And Salmon begat Booz of Rachab; and Booz begat Obed of Ruth; and Obed begat Jesse." Rahab is in the direct line leading to David and Christ.'),
('Joshua', 2, 'adults', 8, 'What phrase did Rahab use to describe the psychological state of Jericho''s inhabitants, and what does this fulfil?', 'They were angry and preparing for war', 'All the inhabitants of the country do faint because of us — fulfilling the fear God had promised to send before Israel', 'They were confident in their walls', 'They were unaware of Israel''s approach', 'a', 'Joshua 2:24 and Exodus 23:27 — "I will send my fear before thee, and will destroy all the people to whom thou shalt come." Rahab''s report confirms this divine promise was already being fulfilled.');

-- ═══ Joshua Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 3, 'kids', 1, 'What did the priests carry into the Jordan River?', 'The tabernacle', 'The ark of the covenant', 'The bronze altar', 'The golden lampstand', 'a', 'Joshua 3:15 — "And as they that bare the ark were come unto Jordan, and the feet of the priests that bare the ark were dipped in the brim of the water."'),
('Joshua', 3, 'kids', 2, 'What happened to the Jordan River when the priests stepped into it?', 'It flooded over its banks', 'The waters stopped flowing and the people crossed on dry ground', 'It turned to blood', 'The water became shallow', 'a', 'Joshua 3:16-17 — "The waters...rose up upon an heap...and the people passed over right against Jericho."'),
('Joshua', 3, 'kids', 3, 'How far behind the ark were the people told to stay?', 'About ten feet', 'About two thousand cubits', 'As close as possible', 'Half a mile', 'a', 'Joshua 3:4 — "Yet there shall be a space between you and it, about two thousand cubits by measure: come not near unto it."'),
-- Teens
('Joshua', 3, 'teens', 1, 'Why did Joshua tell the people to sanctify themselves before crossing the Jordan?', 'Because they were entering enemy territory', 'Because tomorrow the LORD would do wonders among them', 'Because they needed to be pure to fight', 'Because the priests required it', 'a', 'Joshua 3:5 — "And Joshua said unto the people, Sanctify yourselves: for to morrow the LORD will do wonders among you."'),
('Joshua', 3, 'teens', 2, 'What purpose did God give for parting the Jordan before all Israel?', 'To prove Joshua was a great general', 'That all people might know the hand of the LORD is mighty and that they might fear him', 'To show the Canaanites Israel''s power', 'To fulfil a promise made to Abraham', 'a', 'Joshua 4:24 — "That all the people of the earth might know the hand of the LORD, that it is mighty: that ye might fear the LORD your God for ever."'),
('Joshua', 3, 'teens', 3, 'Who bore the ark of the covenant during the Jordan crossing?', 'The Levites', 'The priests the sons of Levi', 'The elders of Israel', 'The warriors of Judah', 'a', 'Joshua 3:3 — "When ye see the ark of the covenant of the LORD your God, and the priests the Levites bearing it, then ye shall remove from your place."'),
('Joshua', 3, 'teens', 4, 'Where did the waters of Jordan pile up when they were cut off?', 'At the Dead Sea', 'Very far from Adam, the city beside Zaretan', 'At the Sea of Galilee', 'At the crossing near Gilgal', 'a', 'Joshua 3:16 — "The waters which came down from above stood and rose up upon an heap very far from the city Adam, that is beside Zaretan."'),
('Joshua', 3, 'teens', 5, 'At what season was Israel crossing the Jordan, and why was this significant?', 'In summer when it was low', 'At harvest time when it overflowed all its banks, making the miracle greater', 'In winter when it was frozen', 'In spring before the rains came', 'a', 'Joshua 3:15 — "And Jordan overfloweth all his banks all the time of harvest." The flood-stage crossing magnified the miracle.'),
-- Adults
('Joshua', 3, 'adults', 1, 'What title is given to the ark in Joshua 3:11, and what theological significance does it carry?', 'The ark of God''s glory', 'The ark of the covenant of the Lord of all the earth, declaring God''s universal sovereignty', 'The ark of the testimony', 'The ark of the God of Israel', 'a', 'Joshua 3:11 — "Behold, the ark of the covenant of the LORD of all the earth passeth over before you into Jordan." The title "LORD of all the earth" asserts divine sovereignty over Canaan and its gods.'),
('Joshua', 3, 'adults', 2, 'What parallel does the Jordan crossing draw with the Exodus event?', 'Both involved manna falling from heaven', 'Both involved God miraculously dividing waters to deliver Israel, establishing Joshua as a new Moses', 'Both required the death of an enemy king', 'Both occurred on the Passover', 'a', 'Joshua 3:7 — "This day will I begin to magnify thee in the sight of all Israel, that they may know that, as I was with Moses, so I will be with thee." The Jordan miracle mirrors the Red Sea crossing (Exodus 14).'),
('Joshua', 3, 'adults', 3, 'What instruction was given about the distance to maintain from the ark, and what reason was given?', 'Stay close to follow its guidance', 'About two thousand cubits, that ye may know the way by which ye must go, for ye have not passed this way heretofore', 'One hundred cubits, to show reverence', 'Five hundred cubits, to avoid the cloud', 'a', 'Joshua 3:4 — "Yet there shall be a space between you and it, about two thousand cubits by measure: come not near unto it, that ye may know the way by which ye must go: for ye have not passed this way heretofore."'),
('Joshua', 3, 'adults', 4, 'What divine promise was given to Joshua personally at the Jordan crossing?', 'He would live one hundred and twenty years', 'God would magnify him in the sight of all Israel as he had magnified Moses', 'He would never lose a battle', 'He would build the first temple', 'a', 'Joshua 3:7 — "The LORD said unto Joshua, This day will I begin to magnify thee in the sight of all Israel, that they may know that, as I was with Moses, so I will be with thee."'),
('Joshua', 3, 'adults', 5, 'What were the twelve men Joshua chose to do, and from where were they selected?', 'They were priests to lead worship', 'One man from each tribe to take stones from the midst of Jordan', 'Twelve warriors to scout the land', 'Twelve scribes to record the miracle', 'a', 'Joshua 4:2 — "Take you twelve men out of the people, out of every tribe a man." (The selection is announced in chapter 3 context.)'),
('Joshua', 3, 'adults', 6, 'How does the Jordan crossing theologically connect to Christian baptism in patristic interpretation?', 'It has no connection', 'Early church fathers saw it as a type of baptism — passing through water into the promised inheritance, as believers pass through baptism into new life', 'It represents the law being set aside', 'It prefigures the Lord''s Supper', 'a', 'The Jordan crossing (Joshua 3) has been interpreted typologically as prefiguring baptism, just as Paul connects the Red Sea crossing with baptism in 1 Corinthians 10:1-2.'),
('Joshua', 3, 'adults', 7, 'Where did the priests bearing the ark stand during the entire crossing?', 'They walked through ahead of the people', 'They stood firm on dry ground in the midst of Jordan until all the people had passed clean over', 'They waited on the east bank', 'They moved slowly at the pace of the slowest person', 'a', 'Joshua 3:17 — "And the priests that bare the ark of the covenant of the LORD stood firm on dry ground in the midst of Jordan, and all the Israelites passed over on dry ground."'),
('Joshua', 3, 'adults', 8, 'What did God tell Joshua would happen to the waters once the priests'' feet touched dry ground on the other side?', 'They would freeze', 'The waters of Jordan should return unto their place and flow over all his banks as before', 'They would drain into the earth', 'They would be parted for forty days', 'a', 'Joshua 4:18 — "And it came to pass...the feet of the priests were lifted up unto the dry land, that the waters of Jordan returned unto their place, and flowed over all his banks, as they did before."');

-- ═══ Joshua Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 4, 'kids', 1, 'How many stones were taken from the middle of the Jordan River?', 'Seven', 'Ten', 'Twelve', 'Forty', 'a', 'Joshua 4:9 — "And Joshua set up twelve stones in the midst of Jordan, in the place where the feet of the priests which bare the ark of the covenant stood."'),
('Joshua', 4, 'kids', 2, 'Where did Joshua set up the twelve stones after crossing the Jordan?', 'In the desert', 'At Gilgal', 'In Jericho', 'On Mount Ebal', 'a', 'Joshua 4:20 — "And those twelve stones, which they took out of Jordan, did Joshua pitch in Gilgal."'),
('Joshua', 4, 'kids', 3, 'Why were the twelve stones set up?', 'To mark the graves of those who died', 'As a memorial so future generations would remember God stopping the Jordan', 'To build an altar for sacrifices', 'To mark the boundary of the promised land', 'a', 'Joshua 4:7 — "These stones shall be for a memorial unto the children of Israel for ever."'),
-- Teens
('Joshua', 4, 'teens', 1, 'What question did Joshua say children would ask when they saw the memorial stones?', 'Who built these stones?', 'What mean ye by these stones?', 'Why are these stones here?', 'How old are these stones?', 'a', 'Joshua 4:6 — "That this may be a sign among you, that when your children ask their fathers in time to come, saying, What mean ye by these stones?"'),
('Joshua', 4, 'teens', 2, 'How many men bore the ark across the Jordan and when did the waters return?', 'The priests bore the ark; the waters returned after their feet touched dry land on the western bank', 'Seven priests bore it; waters returned at sunset', 'Twelve priests; waters returned after three days', 'Levites bore it; waters returned immediately', 'a', 'Joshua 4:17-18 — "Joshua therefore commanded the priests, saying, Come ye up out of Jordan. And the feet of the priests were lifted up unto the dry land, that the waters of Jordan returned."'),
('Joshua', 4, 'teens', 3, 'How many armed men crossed the Jordan, and from which tribes?', 'Forty thousand from all Israel', 'About forty thousand prepared for war, from the tribes of Reuben, Gad, and half of Manasseh', 'Twelve thousand from the tribe of Judah', 'One hundred thousand from all Israel', 'a', 'Joshua 4:12-13 — "And the children of Reuben, and the children of Gad, and half the tribe of Manasseh, passed over armed before the children of Israel...about forty thousand prepared for war."'),
('Joshua', 4, 'teens', 4, 'What effect did the Jordan crossing have on the kings of the Amorites and Canaanites?', 'They prepared for war', 'Their heart melted, neither was there spirit in them any more', 'They sent peace offerings', 'They fled to Egypt', 'a', 'Joshua 5:1 — "All the kings of the Amorites...and all the kings of the Canaanites...heard that the LORD had dried up the waters of Jordan...their heart melted, neither was there spirit in them any more."'),
('Joshua', 4, 'teens', 5, 'What day did Israel cross the Jordan, and where did they encamp?', 'The first day of the first month, in Gilgal on the east border of Jericho', 'The fifteenth day of the seventh month, at Shittim', 'The tenth day of the fifth month, at Bethel', 'The first day of the third month, at Shechem', 'a', 'Joshua 4:19 — "And the people came up out of Jordan on the tenth day of the first month, and encamped in Gilgal, in the east border of Jericho."'),
-- Adults
('Joshua', 4, 'adults', 1, 'What dual set of memorial stones was placed at the crossing, and where were they located?', 'Only one set at Gilgal', 'One set in the midst of Jordan where the priests stood, and one set at Gilgal on the western bank', 'Stones only on the eastern bank', 'Stones only at the tabernacle site', 'a', 'Joshua 4:9,20 — "Joshua set up twelve stones in the midst of Jordan...And those twelve stones, which they took out of Jordan, did Joshua pitch in Gilgal." Two sets of twelve stones are mentioned.'),
('Joshua', 4, 'adults', 2, 'What twofold divine purpose did God state for the Jordan miracle in Joshua 4:24?', 'To punish Canaan and reward Israel', 'That all the people of the earth might know the hand of the LORD is mighty and that Israel might fear the LORD their God for ever', 'To prove Joshua was a prophet and the priests were holy', 'To signal the beginning of the Jubilee year', 'a', 'Joshua 4:24 — "That all the people of the earth might know the hand of the LORD, that it is mighty: that ye might fear the LORD your God for ever."'),
('Joshua', 4, 'adults', 3, 'How does the Jordan crossing connect to the stated purpose of magnifying Joshua (Joshua 3:7 and 4:14)?', 'It was a military victory', 'The LORD magnified Joshua in the sight of all Israel that day, fulfilling the promise, and they feared him as they feared Moses', 'It established Joshua as a priest', 'It gave Joshua authority to levy taxes', 'a', 'Joshua 4:14 — "On that day the LORD magnified Joshua in the sight of all Israel; and they feared him, as they feared Moses, all the days of his life."'),
('Joshua', 4, 'adults', 4, 'What instruction did God give regarding how fathers were to answer their children about the memorial stones?', 'To say God is great', 'To recount how Israel came over on dry ground and how God dried up Jordan as he had dried the Red Sea', 'To say the stones were built by angels', 'To refer the children to the priests', 'a', 'Joshua 4:22-23 — "Then ye shall let your children know, saying, Israel came over this Jordan on dry land. For the LORD your God dried up the waters of Jordan...as the LORD your God did to the Red sea."'),
('Joshua', 4, 'adults', 5, 'What does the specific date — the tenth day of the first month — carry significance with in Israel''s calendar?', 'It was the Day of Atonement', 'It was the day for selecting the Passover lamb (Exodus 12:3), connecting the crossing to redemptive history', 'It was the first day of the Feast of Tabernacles', 'It was the anniversary of the giving of the law', 'a', 'Joshua 4:19 states Israel entered Canaan on the tenth of the first month. Exodus 12:3 says the Passover lamb was to be selected on this same day, connecting the entrance into the land with the Passover redemption.'),
('Joshua', 4, 'adults', 6, 'How does the two-and-a-half tribes'' participation illustrate the principle of corporate obligation in Israel?', 'Their participation was optional', 'Though their own inheritance was secured east of Jordan, their covenant solidarity required them to serve their brethren until all Israel received rest', 'They were being punished for past rebellion', 'They participated to earn more land', 'a', 'Joshua 4:12-13 and Numbers 32 — The Reubenites and Gadites had pledged to Moses to cross armed with their brethren. Their fulfilment illustrates that covenant obligation binds the community together.'),
('Joshua', 4, 'adults', 7, 'What rhetorical device do the memorial stones represent in the context of Israel''s catechetical tradition?', 'They were merely boundary markers', 'They were a visible curriculum that prompted children to ask questions, creating structured opportunities to transmit faith and history', 'They were monuments to Joshua''s glory', 'They marked sites for future temples', 'a', 'Joshua 4:6-7 — "When your children ask their fathers in time to come, saying, What mean ye by these stones? Then ye shall answer them..." The stones function as pedagogical prompts for generational faith transmission.'),
('Joshua', 4, 'adults', 8, 'What does the phrase "all the days of his life" in Joshua 4:14 imply about Joshua''s continued authority?', 'It implies Joshua was immortal', 'It establishes that Joshua''s God-given authority persisted throughout his entire life, comparable to Moses, grounded in this single miraculous event', 'It means Joshua never sinned', 'It refers only to his military command', 'a', 'Joshua 4:14 — "The LORD magnified Joshua in the sight of all Israel...and they feared him, as they feared Moses, all the days of his life." The Jordan crossing established lifelong leadership credibility for Joshua.');

-- ═══ Joshua Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 5, 'kids', 1, 'What special food did God provide for Israel in the desert that stopped when they entered Canaan?', 'Quail', 'Manna', 'Bread from Egypt', 'Figs and pomegranates', 'a', 'Joshua 5:12 — "And the manna ceased on the morrow after they had eaten of the old corn of the land...the children of Israel had manna no more."'),
('Joshua', 5, 'kids', 2, 'What feast did Israel keep after crossing the Jordan?', 'The Feast of Tabernacles', 'The Passover', 'The Feast of Weeks', 'The Day of Atonement', 'a', 'Joshua 5:10 — "And the children of Israel encamped in Gilgal, and kept the passover on the fourteenth day of the month at even in the plains of Jericho."'),
('Joshua', 5, 'kids', 3, 'Who appeared to Joshua with a drawn sword before the battle of Jericho?', 'An angel of God', 'The captain of the host of the LORD', 'Moses in a vision', 'The high priest', 'a', 'Joshua 5:14 — "And he said, Nay; but as captain of the host of the LORD am I now come."'),
-- Teens
('Joshua', 5, 'teens', 1, 'Why did God command the circumcision of Israel at Gilgal?', 'As a new covenant sign', 'Because all the men born in the wilderness had not been circumcised during the forty years of wandering', 'Because the Egyptians had stopped the practice', 'Because Moses had forbidden it in the desert', 'a', 'Joshua 5:5-6 — "All the people that were born in the wilderness by the way as they came forth out of Egypt, them they had not circumcised...for the children of Israel walked forty years in the wilderness."'),
('Joshua', 5, 'teens', 2, 'What name was given to Gilgal, and what did it mean?', 'Gilgal, meaning "place of crossing"', 'Gilgal, meaning "I have rolled away the reproach of Egypt"', 'Gilgal, meaning "land of promise"', 'Gilgal, meaning "place of the ark"', 'a', 'Joshua 5:9 — "And the LORD said unto Joshua, This day have I rolled away the reproach of Egypt from off you. Wherefore the name of the place is called Gilgal unto this day."'),
('Joshua', 5, 'teens', 3, 'What did Israel eat at their first Passover in Canaan?', 'Manna and water', 'The old corn of the land, unleavened cakes and parched corn', 'Lamb and bitter herbs only', 'Food brought from Shittim', 'a', 'Joshua 5:11 — "And they did eat of the old corn of the land on the morrow after the passover, unleavened cakes, and parched corn in the selfsame day."'),
('Joshua', 5, 'teens', 4, 'What did Joshua do when he recognized the captain of the LORD''s host?', 'He drew his own sword', 'He fell on his face to the earth and worshipped and asked what his lord would say', 'He called the elders of Israel', 'He ran back to the camp', 'a', 'Joshua 5:14 — "And Joshua fell on his face to the earth, and did worship, and said unto him, What saith my lord unto his servant?"'),
('Joshua', 5, 'teens', 5, 'What command did the captain of the LORD''s host give Joshua?', 'Go quickly and attack Jericho', 'Loose thy shoe from off thy foot; for the place whereon thou standest is holy', 'Fast for seven days before the battle', 'Build an altar on this spot', 'a', 'Joshua 5:15 — "And the captain of the LORD''s host said unto Joshua, Loose thy shoe from off thy foot; for the place whereon thou standest is holy. And Joshua did so."'),
-- Adults
('Joshua', 5, 'adults', 1, 'What theological significance does the flint knives used at Gilgal have, and what was the location named?', 'They symbolised new beginnings', 'Flint knives were the traditional instrument; the hill was named Gibeah-haaraloth (hill of the foreskins), marking the restoration of covenant sign', 'They were used to mark the boundary stones', 'Flint was sacred metal in Israel', 'a', 'Joshua 5:3 — "And Joshua made him sharp knives, and circumcised the children of Israel at the hill of the foreskins." The use of stone knives (as in Exodus 4:25) connects the rite to ancient covenant tradition.'),
('Joshua', 5, 'adults', 2, 'What does "the reproach of Egypt" that God rolled away at Gilgal likely refer to?', 'The memory of slavery', 'Israel''s uncircumcised state — making them covenant-deficient and unable to keep Passover — a reproach that Egypt and Canaan could mock', 'The plagues of Egypt', 'The shame of Moses'' death', 'a', 'Joshua 5:9 — "This day have I rolled away the reproach of Egypt." The uncircumcised generation could not celebrate Passover (Exodus 12:48), and their covenant deficiency was a reproach now removed upon entering the land.'),
('Joshua', 5, 'adults', 3, 'What is the theological significance of manna ceasing on the day after they ate the produce of Canaan?', 'It was a coincidence of timing', 'It shows God''s provision is always precisely calibrated — the supernatural provision ceased exactly when natural provision became available, demonstrating divine faithfulness throughout', 'The manna ran out naturally', 'It marked the end of the Mosaic era entirely', 'a', 'Joshua 5:12 — "And the manna ceased on the morrow after they had eaten of the old corn of the land." The precision of timing demonstrates God''s intimate providential care.'),
('Joshua', 5, 'adults', 4, 'How does the identity of the "captain of the LORD''s host" connect to the burning bush episode?', 'There is no connection', 'Both involve a divine commander on holy ground, with the command to remove shoes linking the two theophanic encounters and suggesting the same divine figure', 'Both involve the ark of the covenant', 'Both occurred on mountains', 'a', 'Joshua 5:15 mirrors Exodus 3:5 — "Put off thy shoes from off thy feet, for the place whereon thou standest is holy ground." Many scholars identify this figure as the pre-incarnate Christ or the Angel of the LORD.'),
('Joshua', 5, 'adults', 5, 'Why was it strategically risky to circumcise all Israel''s fighting men at Gilgal before any battle?', 'There was no risk', 'Circumcision left all fighting men temporarily incapacitated in enemy territory, as seen with Shechem in Genesis 34, requiring complete faith in God''s protection', 'The men recovered in one hour', 'Only a few men were circumcised at a time', 'a', 'Joshua 5:8 — "When they had done circumcising all the people...they abode in their places in the camp, till they were whole." The parallel to Genesis 34:25 shows this was a real military vulnerability requiring extraordinary trust.'),
('Joshua', 5, 'adults', 6, 'What does the Passover celebration at Gilgal signal about the transition from wilderness to land?', 'It was a routine religious observance', 'It marks the completion of the Exodus narrative — Israel could now keep the Passover in the promised land as a covenant people fully restored', 'It was required before any military action', 'It replaced the circumcision rite', 'a', 'Joshua 5:10 — "And the children of Israel...kept the passover on the fourteenth day of the month at even in the plains of Jericho." This is the third recorded Passover (after Exodus 12 and Numbers 9) and marks Israel''s covenantal renewal in the land.'),
('Joshua', 5, 'adults', 7, 'What answer did the captain of the LORD''s host give when Joshua asked if he was for Israel or for their adversaries?', 'He declared himself for Israel', 'He said "Nay" — he came as commander of the LORD''s army, transcending human partisan categories', 'He said he was sent from God to fight for Israel', 'He said he was neutral', 'a', 'Joshua 5:13-14 — "Art thou for us, or for our adversaries? And he said, Nay; but as captain of the host of the LORD am I now come." The answer indicates God is not a tool of human agendas but the sovereign commander.'),
('Joshua', 5, 'adults', 8, 'How do the events of Joshua 5 (circumcision, Passover, manna ceasing, theophany) collectively prepare Israel spiritually for the conquest?', 'They were administrative preparations only', 'They restored covenant identity (circumcision), commemorated redemption (Passover), transitioned from miraculous provision to natural blessing (manna ceased), and established divine authority (theophany) — fully equipping Israel spiritually before any battle', 'They were commanded by the priests without divine instruction', 'They were simply traditional ceremonies', 'a', 'Joshua 5 contains four preparatory events — circumcision (v.2-9), Passover (v.10), manna ceasing (v.11-12), and the captain''s appearance (v.13-15) — each renewing Israel''s covenant standing before the LORD prior to the conquest.');

-- ═══ Joshua Chapter 6 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 6, 'kids', 1, 'How many days did Israel march around Jericho?', 'Three days', 'Seven days', 'Forty days', 'One day', 'a', 'Joshua 6:14-15 — "And the second day they compassed the city once...So they did six days. And it came to pass on the seventh day, that they rose early about the dawning of the day, and compassed the city after the same manner seven times."'),
('Joshua', 6, 'kids', 2, 'How many priests carried trumpets before the ark at Jericho?', 'Two', 'Seven', 'Twelve', 'Forty', 'a', 'Joshua 6:4 — "And seven priests shall bear before the ark seven trumpets of rams'' horns."'),
('Joshua', 6, 'kids', 3, 'What happened to the walls of Jericho?', 'They were burned down', 'They fell down flat', 'The gates were opened by a traitor', 'They were broken by battering rams', 'a', 'Joshua 6:20 — "The wall fell down flat, so that the people went up into the city, every man straight before him, and they took the city."'),
-- Teens
('Joshua', 6, 'teens', 1, 'What were the people told to do on the seventh day of the march?', 'March once around and then attack', 'Compass the city seven times and then shout when the priests blew the trumpets', 'Fast and pray all day', 'Blow the trumpets continuously for one hour', 'a', 'Joshua 6:4 — "And ye shall compass the city seven times, and the priests shall blow with the trumpets. And it shall come to pass, that when they make a long blast with the ram''s horn...all the people shall shout."'),
('Joshua', 6, 'teens', 2, 'What was done with the silver, gold, brass, and iron found in Jericho?', 'Divided among the soldiers', 'Consecrated unto the LORD and put into the treasury of the house of the LORD', 'Given to the Levites', 'Destroyed along with the city', 'a', 'Joshua 6:19 — "But all the silver, and gold, and vessels of brass and iron, are consecrated unto the LORD: they shall come into the treasury of the LORD."'),
('Joshua', 6, 'teens', 3, 'What specific instruction was given to Joshua about silence during the march?', 'To pray quietly throughout the march', 'The people were to make no noise nor let any word proceed out of their mouth until the day Joshua bid them shout', 'To sing the songs of Moses', 'Only the priests could speak', 'a', 'Joshua 6:10 — "And Joshua had commanded the people, saying, Ye shall not shout, nor make any noise with your voice, neither shall any word proceed out of your mouth, until the day I bid you shout; then shall ye shout."'),
('Joshua', 6, 'teens', 4, 'Who was saved when Jericho fell?', 'All the people of Jericho', 'Rahab the harlot and all who were in her house', 'The king of Jericho and his household', 'The priests of Jericho', 'a', 'Joshua 6:25 — "And Joshua saved Rahab the harlot alive, and her father''s household, and all that she had...because she hid the messengers, which Joshua sent to spy out Jericho."'),
('Joshua', 6, 'teens', 5, 'What curse did Joshua pronounce over Jericho after its destruction?', 'No Israelite would ever settle there', 'Cursed be the man before the LORD that riseth up and buildeth this city Jericho — he shall lose his sons at its foundations and gates', 'The land would be barren for forty years', 'Anyone who entered would be struck blind', 'a', 'Joshua 6:26 — "Cursed be the man before the LORD, that riseth up and buildeth this city Jericho: he shall lay the foundation thereof in his firstborn, and in his youngest son shall he set up the gates of it."'),
-- Adults
('Joshua', 6, 'adults', 1, 'What grammatical and theological feature of Joshua 6:2 signals that Jericho''s fall was already certain before any march?', 'God promised to think about it', 'God used the perfect tense — "I have given into thine hand Jericho" — treating the victory as accomplished fact before it occurred', 'God gave a conditional promise', 'The text is uncertain', 'a', 'Joshua 6:2 — "And the LORD said unto Joshua, See, I have given into thine hand Jericho, and the king thereof, and the mighty men of valour." The perfect tense expresses divine certainty of fulfilment.'),
('Joshua', 6, 'adults', 2, 'What does the Hebrew word "cherem" (translated "accursed" or "devoted") mean in the context of Jericho?', 'A military siege', 'Total consecration to God for destruction — the city and its contents were set apart as God''s holy war offering, not to be plundered for personal gain', 'A peace offering', 'A temporary ban on trade', 'a', 'Joshua 6:17-18 — "And the city shall be accursed (cherem)...lest ye make yourselves accursed, when ye take of the accursed thing." Cherem designated Jericho as the firstfruits of Canaan, entirely devoted to God.'),
('Joshua', 6, 'adults', 3, 'How does the fall of Jericho fulfil the theme of holy war (herem) theology in Deuteronomy?', 'Deuteronomy has no connection to Joshua', 'Deuteronomy 7:1-2 commanded Israel to utterly destroy the Canaanite nations; Jericho as the first city becomes the paradigmatic holy war fulfilment of that command', 'It fulfilled the law of the firstfruits only', 'It was a purely military campaign with no theological component', 'a', 'Deuteronomy 7:2 — "Thou shalt utterly destroy them." Joshua 6:21 — "They utterly destroyed all that was in the city." Jericho''s total destruction establishes the pattern of herem warfare.'),
('Joshua', 6, 'adults', 4, 'What prophetic detail in Joshua 6:26 was literally fulfilled centuries later, and where is this recorded?', 'It was never fulfilled', 'Hiel the Bethelite rebuilt Jericho during Ahab''s reign, laying the foundation at the cost of his firstborn Abiram and setting up the gates at the cost of Segub, as recorded in 1 Kings 16:34', 'It was fulfilled in the Babylonian captivity', 'It was fulfilled in the days of Nehemiah', 'a', '1 Kings 16:34 — "In his days did Hiel the Bethelite build Jericho: he laid the foundation thereof in Abiram his firstborn, and set up the gates thereof in his youngest son Segub, according to the word of the LORD, which he spake by Joshua." This demonstrates the reliability of Joshua''s prophecy.'),
('Joshua', 6, 'adults', 5, 'How does Rahab''s scarlet cord relate to the concept of covenant faithfulness (hesed) in the narrative?', 'It was merely a military signal', 'The spies swore hesed (lovingkindness) to Rahab contingent on the scarlet cord; God''s faithfulness is expressed through Israel honouring its oath to a pagan woman of faith', 'It was a priestly symbol', 'It replaced the blood of the Passover', 'a', 'Joshua 2:12 — "Swear unto me by the LORD...that ye will also shew kindness (hesed) unto my father''s house." Joshua 6:25 — the oath was kept. God''s covenant faithfulness extends even to those outside Israel who trust him.'),
('Joshua', 6, 'adults', 6, 'What is the significance of the seven-fold repetition in the Jericho account (seven priests, seven trumpets, seven days, seven circuits on day seven)?', 'Seven was simply the Israelite lucky number', 'Seven is the biblical number of completeness and divine perfection; the sevenfold pattern signals this victory is entirely God''s work, not human military strategy', 'It was a random military decision', 'It echoed seven days of creation with no further meaning', 'a', 'The sevenfold pattern in Joshua 6 (7 priests, 7 trumpets, 7 days, 7 circuits) mirrors the 7-day creation pattern and establishes the conquest as a divine creative act — God is creating his holy land.'),
('Joshua', 6, 'adults', 7, 'What does Hebrews 11:30 say about the fall of Jericho''s walls?', 'The walls fell by military strategy', 'By faith the walls of Jericho fell down, after they were compassed about seven days', 'The walls fell because of an earthquake', 'The walls fell because of superior Israelite weapons', 'a', 'Hebrews 11:30 — "By faith the walls of Jericho fell down, after they were compassed about seven days." The author of Hebrews attributes the miracle entirely to Israel''s faith-obedience, not military prowess.'),
('Joshua', 6, 'adults', 8, 'What does Rahab''s inclusion in the genealogy of Christ (Matthew 1:5) and the hall of faith (Hebrews 11:31) together teach about grace?', 'They show social status matters in salvation', 'They demonstrate that God''s saving grace reaches beyond ethnic and moral barriers — a Canaanite harlot becomes an ancestor of Christ by faith', 'They show the law was sufficient for salvation', 'They prove that Rahab was secretly an Israelite', 'a', 'Matthew 1:5 and Hebrews 11:31 together present Rahab — a Gentile and a harlot — as both a woman of faith and a direct ancestor of Jesus Christ, showcasing the breadth of divine grace.');

-- ═══ Joshua Chapter 7 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 7, 'kids', 1, 'What was the name of the man who stole things from Jericho that were supposed to belong to God?', 'Achan', 'Caleb', 'Phinehas', 'Zimri', 'a', 'Joshua 7:1 — "Achan, the son of Carmi, the son of Zabdi, the son of Zerah, of the tribe of Judah, took of the accursed thing."'),
('Joshua', 7, 'kids', 2, 'What city did Israel fail to defeat because of Achan''s sin?', 'Jericho', 'Ai', 'Gibeon', 'Bethel', 'a', 'Joshua 7:4-5 — "So there went up thither of the people about three thousand men: and they fled before the men of Ai."'),
('Joshua', 7, 'kids', 3, 'Where did Achan hide the things he stole?', 'In a cave outside the camp', 'In the earth in the midst of his tent', 'Under the river Jordan', 'With a neighbour in his tribe', 'a', 'Joshua 7:21 — "And I took them; and, behold, they are hid in the earth in the midst of my tent."'),
-- Teens
('Joshua', 7, 'teens', 1, 'What three items did Achan confess to stealing from Jericho?', 'Gold, frankincense, and myrrh', 'A goodly Babylonish garment, two hundred shekels of silver, and a wedge of gold of fifty shekels', 'Weapons, food, and cloth', 'A golden idol, silver cups, and a sword', 'a', 'Joshua 7:21 — "When I saw among the spoils a goodly Babylonish garment, and two hundred shekels of silver, and a wedge of gold of fifty shekels weight, then I coveted them, and took them."'),
('Joshua', 7, 'teens', 2, 'What did Joshua do before God to express Israel''s grief after the defeat at Ai?', 'He offered a great sacrifice', 'He fell to the earth upon his face before the ark of the LORD and put dust on his head', 'He gathered the army to pray', 'He retreated to Shittim', 'a', 'Joshua 7:6 — "And Joshua rent his clothes, and fell to the earth upon his face before the ark of the LORD until the eventide, he and the elders of Israel, and put dust upon their heads."'),
('Joshua', 7, 'teens', 3, 'How was Achan identified as the guilty man?', 'A witness came forward', 'God revealed him through a process of casting lots by tribe, family, household, and man', 'The stolen goods were found in his tent first', 'Achan confessed spontaneously', 'a', 'Joshua 7:14-18 — Israel came tribe by tribe, then family, then household, then man by man, and Achan was taken. This systematic narrowing was by divine lot.'),
('Joshua', 7, 'teens', 4, 'What was Achan''s punishment?', 'He was exiled from Israel', 'He and his household and all that he had were stoned and burned in the valley of Achor', 'He was made a slave', 'He had to repay double', 'a', 'Joshua 7:25 — "And Joshua said, Why hast thou troubled us? the LORD shall trouble thee this day. And all Israel stoned him with stones, and burned them with fire, after they had stoned them with stones."'),
('Joshua', 7, 'teens', 5, 'What did God tell Joshua was the reason Israel could not stand before their enemies?', 'Their army was too small', 'Israel had sinned and taken of the accursed thing and also stolen and dissembled', 'Their weapons were inferior', 'They had not prayed enough', 'a', 'Joshua 7:11 — "Israel hath sinned, and they have also transgressed my covenant which I commanded them: for they have even taken of the accursed thing, and have also stolen, and dissembled also."'),
-- Adults
('Joshua', 7, 'adults', 1, 'What does Joshua 7:1 reveal about the corporate nature of sin in covenant Israel?', 'Only Achan was held responsible', 'The anger of the LORD was kindled against the children of Israel — demonstrating that one man''s sin brought corporate guilt and consequence upon the whole nation under the covenant', 'Sin was always treated individually in Israel', 'God was angry at Ai, not Israel', 'a', 'Joshua 7:1 — "The children of Israel committed a trespass in the accursed thing...and the anger of the LORD was kindled against the children of Israel." The covenant community was corporately implicated by Achan''s individual act.'),
('Joshua', 7, 'adults', 2, 'What does Achan''s confession (Joshua 7:21) reveal about the progression of temptation?', 'He was forced to take the items', 'He saw, he coveted, and he took — a three-stage sequence mirroring Eve''s temptation in Genesis 3:6 and James 1:14-15', 'He took the items without noticing their value', 'He was tricked by a Canaanite', 'a', 'Joshua 7:21 — "When I saw...then I coveted them, and took them." This mirrors Genesis 3:6 "she saw...it was to be desired...she took" and James 1:15 "when lust hath conceived, it bringeth forth sin."'),
('Joshua', 7, 'adults', 3, 'What theological tension does Joshua''s lament in verses 7-9 create?', 'No tension — Joshua was sinning by questioning God', 'It raises the problem of theodicy and covenant reputation: if Israel is defeated, how will God''s name be glorified among the nations?', 'Joshua was doubting the existence of God', 'It is a purely military concern', 'a', 'Joshua 7:9 — "What wilt thou do unto thy great name?" Joshua''s concern echoes Moses in Exodus 32:12 and Numbers 14:13-16 — God''s honour among the nations was at stake, not merely Israel''s military success.'),
('Joshua', 7, 'adults', 4, 'What does the location "valley of Achor" mean, and how does the prophet Hosea later reinterpret it?', 'It means "valley of peace"', 'Achor means "trouble"; Hosea 2:15 promises God will make the valley of Achor a door of hope, transforming judgment''s site into a symbol of restoration', 'It means "valley of fire"', 'Achor means "valley of the dead"', 'a', 'Joshua 7:26 — "called, The valley of Achor, unto this day." Hosea 2:15 — "I will give her...the valley of Achor for a door of hope." The place of Israel''s shame becomes a prophetic image of covenant renewal.'),
('Joshua', 7, 'adults', 5, 'What does the divine command to sanctify the people (Joshua 7:13) before the lot-casting reveal about approaching God?', 'Sanctification was unnecessary', 'Corporate guilt requires corporate purification before the holy God can be approached through divination — holiness is prerequisite to divine communication', 'It was merely a ritual formality', 'Only the priests needed to be sanctified', 'a', 'Joshua 7:13 — "Sanctify the people, and say, Sanctify yourselves against to morrow: for thus saith the LORD God of Israel, There is an accursed thing in the midst of thee." Holiness must be addressed before Israel could stand in God''s presence.'),
('Joshua', 7, 'adults', 6, 'How does the destruction of Achan''s entire household raise ethical questions about collective punishment?', 'The household was innocent and unjustly punished', 'The text is debated: some argue the family was complicit since the goods were hidden in the family tent; others see it as a severe covenantal deterrent; Deuteronomy 24:16 later qualifies individual accountability', 'Collective punishment is always justified in Scripture', 'Only Achan''s children were punished', 'a', 'Joshua 7:24-25 includes Achan''s sons and daughters in the punishment. Deuteronomy 24:16 — "The fathers shall not be put to death for the children." Scholars note the family''s probable complicity (goods in the family tent) and the unique covenantal context.'),
('Joshua', 7, 'adults', 7, 'What name was given to the site of Achan''s execution, and what does it signify?', 'Valley of Gehenna — place of eternal fire', 'The valley of Achor — meaning trouble; it became a perpetual reminder that sin troubles the entire covenant community', 'The valley of Rephaim — place of the giants', 'The valley of Kidron — place of mourning', 'a', 'Joshua 7:25-26 — "Why hast thou troubled us? The LORD shall trouble thee this day...Wherefore the name of that place was called, The valley of Achor." Achor (trouble) memorialises the consequence of covenant violation.'),
('Joshua', 7, 'adults', 8, 'What does the divine reversal of God''s anger after Achan''s execution (Joshua 7:26) teach about atonement?', 'God''s anger was permanent and could not be removed', 'Judgment executed according to God''s word satisfies divine wrath and restores covenant relationship — the community is cleansed and God''s presence can continue with them', 'God was pleased merely by the death, not by justice', 'God''s anger was never real, only symbolic', 'a', 'Joshua 7:26 — "And the LORD turned from the fierceness of his anger." The execution of covenant justice restored divine favour — a principle pointing toward the satisfaction of divine justice in the atonement of Christ (Romans 3:25-26).');

-- ═══ Joshua Chapter 8 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 8, 'kids', 1, 'How did Israel defeat the city of Ai the second time?', 'By marching around it seven times', 'By using an ambush — hiding soldiers behind the city', 'By attacking at night', 'By bribing the king of Ai', 'a', 'Joshua 8:2 — "And thou shalt do to Ai and her king as thou didst unto Jericho and her king: only the spoil thereof, and the cattle thereof, shall ye take for a prey unto yourselves: lay thee an ambush for the city behind it."'),
('Joshua', 8, 'kids', 2, 'Where did Joshua build an altar to God after defeating Ai?', 'In Jericho', 'On Mount Ebal', 'In Gilgal', 'On Mount Sinai', 'a', 'Joshua 8:30 — "Then Joshua built an altar unto the LORD God of Israel in mount Ebal."'),
('Joshua', 8, 'kids', 3, 'What did Joshua read to all the people after the battle of Ai?', 'The Psalms of Moses', 'All the words of the law', 'The ten commandments only', 'The book of Genesis', 'a', 'Joshua 8:34 — "And afterward he read all the words of the law, the blessings and cursings, according to all that is written in the book of the law."'),
-- Teens
('Joshua', 8, 'teens', 1, 'What was the battle plan God gave Joshua for taking Ai?', 'A direct frontal assault at dawn', 'Draw the men of Ai out by feigning retreat, while an ambush of thirty thousand men hidden behind the city entered and burned it', 'Besiege the city until it surrendered', 'Send spies to open the gates from inside', 'a', 'Joshua 8:4-7 — "And he commanded them, saying, Behold, ye shall lie in wait against the city...when they come out against us, as at the first, then we will flee before them...then ye shall rise up from the ambush, and seize upon the city."'),
('Joshua', 8, 'teens', 2, 'How many soldiers did Joshua set in ambush west of Ai?', 'Three thousand', 'Five thousand', 'Thirty thousand', 'Twelve thousand', 'a', 'Joshua 8:3 — "So Joshua arose, and all the people of war, to go up against Ai: and Joshua chose out thirty thousand mighty men of valour, and sent them away by night."'),
('Joshua', 8, 'teens', 3, 'What was the signal Joshua used to direct the ambush to enter Ai?', 'A trumpet blast', 'He stretched out the javelin in his hand toward Ai', 'He sent a runner to the hidden troops', 'He lit a signal fire on the hill', 'a', 'Joshua 8:18 — "And the LORD said unto Joshua, Stretch out the spear that is in thy hand toward Ai; for I will give it into thine hand. And Joshua stretched out the spear that he had in his hand toward the city."'),
('Joshua', 8, 'teens', 4, 'What was done with the king of Ai after the battle?', 'He was spared and became a servant', 'He was hanged on a tree until evening, then his body cast at the entering of the city gate under a heap of stones', 'He was sold as a slave in Egypt', 'He fled and was never found', 'a', 'Joshua 8:29 — "And the king of Ai he hanged on a tree until eventide: and as soon as the sun was down, Joshua commanded that they should take his carcase down from the tree...and raise thereon a great heap of stones."'),
('Joshua', 8, 'teens', 5, 'What was unique about the altar Joshua built on Mount Ebal according to the law of Moses?', 'It was made of cedar wood', 'It was built of whole stones upon which no iron tool had been lifted', 'It was overlaid with bronze', 'It was built on the highest point of the mountain', 'a', 'Joshua 8:31 — "As Moses the servant of the LORD commanded the children of Israel, as it is written in the book of the law of Moses, an altar of whole stones, over which no man hath lift up any iron: and they offered thereon burnt offerings unto the LORD."'),
-- Adults
('Joshua', 8, 'adults', 1, 'What does the specific detail of Joshua holding the javelin extended toward Ai (Joshua 8:18, 26) parallel in the narrative of Moses?', 'It has no parallel', 'It parallels Moses holding up his staff over the Red Sea and during the battle with Amalek (Exodus 17:11), where the held instrument symbolises divine authority and ongoing victory', 'It parallels the ark being raised in the wilderness', 'It mirrors Abraham lifting the knife over Isaac', 'a', 'Joshua 8:26 — "Joshua drew not his hand back...until he had utterly destroyed all the inhabitants of Ai." This mirrors Exodus 17:11 — "when Moses held up his hand, Israel prevailed...when he let down his hand, Amalek prevailed."'),
('Joshua', 8, 'adults', 2, 'What permission was granted regarding the spoil of Ai that was not granted at Jericho, and what does this teach?', 'No spoil was permitted at Ai', 'The cattle and spoil were permitted to be taken for Israel — unlike Jericho''s total cherem, showing that Jericho was a unique firstfruits offering while subsequent conquests allowed normal warfare rules', 'All spoil at Ai also went to the temple treasury', 'Only the priests could take spoil from Ai', 'a', 'Joshua 8:27 — "Only the cattle and the spoil of that city Israel took for a prey unto themselves, according unto the word of the LORD which he commanded Joshua." Contrast Joshua 6:17-19 where Jericho''s spoil was entirely devoted to God.'),
('Joshua', 8, 'adults', 3, 'What commandment of Moses was Joshua fulfilling in Joshua 8:30-35, and where was it originally given?', 'The law of the Passover', 'Deuteronomy 27:2-8 commanded building an altar on Mount Ebal and writing the law on plastered stones when Israel crossed the Jordan', 'The law of tithes in Leviticus 27', 'The commandment to build the tabernacle', 'a', 'Deuteronomy 27:4-8 — "Therefore it shall be when ye be gone over Jordan...ye shall set up these stones in mount Ebal...and thou shalt write upon the stones all the words of this law." Joshua 8:30-35 faithfully fulfils this command.'),
('Joshua', 8, 'adults', 4, 'What was the geographic significance of the covenant renewal at Mounts Ebal and Gerizim?', 'They were the highest mountains in Canaan', 'They stood in the geographical centre of Canaan, making the public reading of the law a central claiming of the whole land for God''s covenant', 'They were on the boundary with Philistia', 'They were where Moses had died', 'a', 'Shechem between Ebal and Gerizim lies in the geographic heart of Canaan. Joshua 8:33-35 — the covenant ceremony there claimed the entire land under the law of God, as Deuteronomy 27-28 prescribed.'),
('Joshua', 8, 'adults', 5, 'How completely was the law read at the covenant ceremony on Ebal, and who was included?', 'Only the ten commandments were read to the priests', 'Joshua read all that Moses had commanded before all Israel — men, women, children, and the stranger that walked among them — not one word was omitted', 'The law was summarised for the people', 'Only the heads of tribes heard the full reading', 'a', 'Joshua 8:34-35 — "There was not a word of all that Moses commanded, which Joshua read not before all the congregation of Israel, with the women, and the little ones, and the strangers that were conversant among them."'),
('Joshua', 8, 'adults', 6, 'What does the inclusion of "strangers" (gerim) in the covenant assembly at Ebal reveal about the scope of Israel''s covenant?', 'Strangers were excluded from the covenant', 'It shows the covenant community was not exclusively ethnic — those who sojourned with Israel were bound by and included in the covenant obligations and blessings', 'Strangers heard but were not bound', 'Only strangers who converted to Judaism were included', 'a', 'Joshua 8:35 — "the strangers that were conversant among them." Deuteronomy 31:12 commanded the same: "Gather the people together, men, women, and children, and thy stranger that is within thy gates."'),
('Joshua', 8, 'adults', 7, 'What is the typological significance of the altar on Mount Ebal being an altar of uncut stones?', 'It was practical — there were no tools available', 'Uncut stones represent God''s work unaltered by human craft (Exodus 20:25) — the altar must be wholly of God''s making, not shaped by human hands, pointing to salvation entirely by God''s work', 'It was an older pre-Mosaic tradition', 'It was to prevent idolatrous symbols being carved', 'a', 'Exodus 20:25 — "If thou wilt make me an altar of stone, thou shalt not build it of hewn stone: for if thou lift up thy tool upon it, thou hast polluted it." The uncut stone altar embodies the principle that approach to God cannot be improved by human effort.'),
('Joshua', 8, 'adults', 8, 'Why is it theologically significant that the covenant ceremony occurs on Mount Ebal — the mount of curses — rather than Mount Gerizim — the mount of blessings?', 'It was a mistake by Joshua', 'The altar on Ebal acknowledges Israel''s sin and need for atonement; burnt and peace offerings on the curse mountain declare that through sacrifice the curse is absorbed, transforming the place of cursing into a site of worship', 'Ebal was taller and more visible', 'God chose randomly between the two mountains', 'a', 'Deuteronomy 27:13 places the curses on Ebal. Joshua builds the altar there (Joshua 8:30), and burnt offerings and peace offerings are made (8:31). The sacrifices on the mount of curses typologically foreshadow Christ bearing the curse (Galatians 3:13).');

-- ═══ Joshua Chapter 9 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 9, 'kids', 1, 'What group of people tricked Israel into making a peace treaty?', 'The men of Ai', 'The Gibeonites', 'The Philistines', 'The Egyptians', 'a', 'Joshua 9:3-4 — "And when the inhabitants of Gibeon heard what Joshua had done unto Jericho and to Ai, they did work wilily."'),
('Joshua', 9, 'kids', 2, 'What did the Gibeonites pretend to be when they came to Joshua?', 'Servants of the king of Ai', 'Men who had come from a very far country', 'Traders from Egypt', 'Pilgrims from the desert', 'a', 'Joshua 9:6 — "They went to Joshua unto the camp at Gilgal, and said unto him, and to the men of Israel, We be come from a far country."'),
('Joshua', 9, 'kids', 3, 'What were the Gibeonites made to do as their punishment for the trick?', 'To be put in prison', 'Hewers of wood and drawers of water for Israel', 'To pay a large fine', 'To leave Canaan', 'a', 'Joshua 9:21 — "Let them live; but let them be hewers of wood and drawers of water unto all the congregation."'),
-- Teens
('Joshua', 9, 'teens', 1, 'What false evidence did the Gibeonites bring to appear as if they came from far away?', 'Letters from a distant king', 'Old dry mouldy bread, worn-out sacks and bottles, old shoes, and worn garments', 'Spices and goods not found in Canaan', 'A chart of far-off lands', 'a', 'Joshua 9:12-13 — "This our bread we took hot for our provision out of our houses on the day we came forth to go unto you; but now, behold, it is dry, and it is mouldy: And these bottles of wine...were new; and, behold, they be rent...these our garments and our shoes are become old."'),
('Joshua', 9, 'teens', 2, 'What critical mistake did the leaders of Israel make when making the league with the Gibeonites?', 'They accepted gifts from them', 'They asked not counsel at the mouth of the LORD', 'They did not consult Joshua', 'They trusted the bread samples', 'a', 'Joshua 9:14 — "And the men took of their victuals, and asked not counsel at the mouth of the LORD."'),
('Joshua', 9, 'teens', 3, 'How soon after making the league did Israel discover the Gibeonites'' true identity?', 'Three years later', 'Three days after, when they came to their cities of Chephirah, Beeroth, and Kirjath-jearim', 'After the next battle', 'When the Gibeonites admitted their deception', 'a', 'Joshua 9:16-17 — "It came to pass at the end of three days after they had made a league with them, that they heard that they were their neighbours, and that they dwelt among them."'),
('Joshua', 9, 'teens', 4, 'Why could not the Israelites attack the Gibeonites once the deception was discovered?', 'The Gibeonites were too strong', 'The princes had sworn an oath by the LORD God of Israel and could not break it', 'Joshua forbade it', 'God appeared and stopped them', 'a', 'Joshua 9:19 — "All the princes said unto all the congregation, We have sworn unto them by the LORD God of Israel: now therefore we may not touch them."'),
('Joshua', 9, 'teens', 5, 'What specific task of service were the Gibeonites assigned within God''s sanctuary?', 'Priests who offered sacrifices', 'Hewers of wood and drawers of water for the house of God and congregation', 'Guards of the tabernacle gates', 'Scribes who copied the law', 'a', 'Joshua 9:23,27 — "Now therefore ye are cursed, and there shall none of you be freed from being bondmen, and hewers of wood and drawers of water for the house of my God...hewers of wood and drawers of water for the congregation, and for the altar of the LORD."'),
-- Adults
('Joshua', 9, 'adults', 1, 'What does Joshua 9:14 reveal as the hermeneutical lesson of the Gibeonite episode?', 'That Israelites were gullible', 'That seeking God''s counsel before major decisions is essential — neglecting prayer opens the door to being deceived by appearances', 'That Gibeon was a great nation', 'That Joshua was at fault for everything', 'a', 'Joshua 9:14 — "The men took of their victuals, and asked not counsel at the mouth of the LORD." The text explicitly identifies this as the cause of the error, teaching that human judgment without divine guidance is insufficient.'),
('Joshua', 9, 'adults', 2, 'What was the Gibeonites'' stated motivation for the deception, and what does it reveal about their faith?', 'They wanted to exploit Israel', 'They had heard of the LORD''s mighty deeds and feared for their lives — Rahab-like faith led them to seek refuge under the God of Israel', 'They were purely self-serving', 'They wanted to be slaves', 'a', 'Joshua 9:24 — "It was certainly told thy servants, how that the LORD thy God commanded his servant Moses to give you all the land, and to destroy all the inhabitants of the land before you: therefore we were sore afraid of our lives because of you."'),
('Joshua', 9, 'adults', 3, 'What covenant principle was tested by the Gibeonite treaty, and how did God later vindicate it?', 'The treaty had no lasting significance', 'The inviolability of oaths sworn in God''s name — God later punished Saul''s house for violating it (2 Samuel 21:1-2), showing that sworn oaths bind even when obtained by fraud', 'God permitted breaking oaths made under deception', 'The Gibeonites eventually forfeited their protection', 'a', '2 Samuel 21:1-2 — "There is blood upon Saul, and upon his house, because he slew the Gibeonites." Centuries later, God sent famine on Israel for Saul breaking the Joshua 9 oath, confirming its binding nature even across generations.'),
('Joshua', 9, 'adults', 4, 'How does the Gibeonite deception relate to the Deuteronomic command to destroy the Canaanite nations?', 'It shows Deuteronomy was wrong', 'Deuteronomy 20:10-18 permitted peace treaties with distant cities but commanded destruction of the seven Canaanite nations — the Gibeonites exploited this distinction by claiming to be from afar', 'The Gibeonites were not Canaanites', 'The treaty automatically fulfilled the destruction command', 'a', 'Deuteronomy 20:10-11 permits making peace with distant cities. The Gibeonites (Joshua 9:7 identifies them as Hivites, a Canaanite group) exploited this legal distinction, knowing a distant-city claim would secure a treaty.'),
('Joshua', 9, 'adults', 5, 'What does Joshua''s response to the Gibeonites after discovering the deception reveal about his commitment to covenant faithfulness?', 'He immediately broke the treaty', 'He maintained the oath despite the deception, showing that covenant integrity requires honouring sworn commitments even when wrongfully obtained, because the oath was sworn by God''s name', 'He sought a legal way to void the treaty', 'He punished the Gibeonites severely and then annulled the treaty', 'a', 'Joshua 9:19-20 — "We have sworn unto them by the LORD God of Israel: now therefore we may not touch them...lest wrath be upon us, because of the oath which we sware unto them." Covenant faithfulness superseded the offence of deception.'),
('Joshua', 9, 'adults', 6, 'What is the irony of the Gibeonites'' assigned role as "hewers of wood and drawers of water for the house of my God"?', 'It was not ironic — it was purely punitive', 'Those who came seeking to serve as servants ended up serving the very temple of the God they feared — their deception led them into proximity with the God of Israel, potentially becoming a means of their salvation', 'The Gibeonites were angered by this assignment', 'The role was temporary only', 'a', 'Joshua 9:27 — "hewers of wood and drawers of water for the congregation, and for the altar of the LORD." The Gibeonites'' fear of God led them into covenantal proximity with Israel''s worship — a remarkable grace hidden within judgment.'),
('Joshua', 9, 'adults', 7, 'What does the reaction of the congregation against the princes (Joshua 9:18) reveal about Israel''s corporate ethic?', 'The people were right to be angry', 'It shows tension between popular outrage and leadership accountability to sworn oaths — the princes rightly overrode popular opinion because covenant faithfulness to God''s name took precedence', 'The princes should have annulled the treaty', 'The congregation had the final authority', 'a', 'Joshua 9:18 — "The whole congregation murmured against the princes." Numbers 30:2 — "If a man vow a vow unto the LORD...he shall not break his word." The princes stood firm against popular pressure because the oath was sworn by God''s name.'),
('Joshua', 9, 'adults', 8, 'How does the Gibeonite story prefigure the place of Gentiles in redemptive history?', 'It has no redemptive significance', 'Gibeonites — a condemned Canaanite people — found grace through faith-driven submission to Israel''s God; their descendants served at the temple, foreshadowing Gentiles grafted into the covenant community by faith', 'It shows Gentiles could never enter the covenant', 'It was a unique exception with no broader meaning', 'a', 'Joshua 9:24-27 — the Gibeonites'' fearful faith brought them into the service of the LORD''s altar. Isaiah 56:6-7 later promises Gentiles who join themselves to the LORD will minister in his temple, fulfilling a pattern begun at Gibeon.');

-- ═══ Joshua Chapter 10 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Joshua', 10, 'kids', 1, 'What miracle did God perform to help Joshua fight the five kings?', 'He sent angels to fight', 'He made the sun and moon stand still', 'He sent a great storm', 'He made the enemies blind', 'a', 'Joshua 10:13 — "And the sun stood still, and the moon stayed, until the people had avenged themselves upon their enemies."'),
('Joshua', 10, 'kids', 2, 'Who were the five kings that joined together to fight against Gibeon?', 'Kings of Egypt, Babylon, Assyria, Persia, and Media', 'Kings of Jerusalem, Hebron, Jarmuth, Lachish, and Eglon', 'Kings of Jericho, Ai, Bethel, Gibeon, and Lachish', 'Kings of Canaan, Hittites, Amorites, Perizzites, and Hivites', 'a', 'Joshua 10:3-5 — "Wherefore Adoni-zedek king of Jerusalem...Hoham king of Hebron...Piram king of Jarmuth...Japhia king of Lachish...Debir king of Eglon, gathered themselves together...and fought against Gibeon."'),
('Joshua', 10, 'kids', 3, 'Where were the five kings hiding when Israel found them?', 'In a tower in Jerusalem', 'In a cave at Makkedah', 'Under the ground in Ai', 'On Mount Gerizim', 'a', 'Joshua 10:16 — "But these five kings fled, and hid themselves in a cave at Makkedah."'),
-- Teens
('Joshua', 10, 'teens', 1, 'Why did the five Canaanite kings attack Gibeon?', 'To take Gibeon''s treasure', 'Because Gibeon had made peace with Israel and they feared other cities would do the same', 'Because the Gibeonites had insulted their king', 'Because Gibeon controlled the water supply', 'a', 'Joshua 10:1-2 — "Adoni-zedek king of Jerusalem had heard how Joshua had taken Ai...and how the inhabitants of Gibeon had made peace with Israel...wherefore the five kings of the Amorites...gathered themselves together."'),
('Joshua', 10, 'teens', 2, 'What did the LORD do to the enemies of Israel with great stones from heaven?', 'He rained fire on them', 'He cast down great stones of hail upon them, so that more died from hailstones than from Israel''s sword', 'He caused an earthquake under them', 'He flooded the valley', 'a', 'Joshua 10:11 — "The LORD cast down great stones from heaven upon them unto Azekah, and they died: they were more which died with hailstones than they whom the children of Israel slew with the sword."'),
('Joshua', 10, 'teens', 3, 'What did Joshua command the sun and moon to do, and how long did the sun stop?', 'To brighten and the sun stopped for one hour', 'Sun to stand still upon Gibeon and moon over Ajalon; the sun hastened not to go down about a whole day', 'To set quickly so Israel could rest', 'To rise twice on the same day', 'a', 'Joshua 10:12-13 — "Sun, stand thou still upon Gibeon; and thou, Moon, in the valley of Ajalon...So the sun stood still in the midst of heaven, and hasted not to go down about a whole day."'),
('Joshua', 10, 'teens', 4, 'What was done with the five kings at Makkedah?', 'They were imprisoned in Jericho', 'Joshua smote them, slew them, hanged them on five trees until evening, then cast them into the cave and rolled great stones on the mouth', 'They were spared and made servants', 'They escaped to Egypt', 'a', 'Joshua 10:26-27 — "Joshua smote them, and slew them, and hanged them on five trees...Joshua commanded, and they took them down off the trees, and cast them into the cave wherein they had been hid, and laid great stones in the cave''s mouth."'),
('Joshua', 10, 'teens', 5, 'What cities did Joshua conquer in the southern campaign of chapter 10?', 'Nazareth, Bethlehem, Hebron, and Bethel', 'Makkedah, Libnah, Lachish, Eglon, Hebron, and Debir', 'Damascus, Sidon, Tyre, and Megiddo', 'Samaria, Shechem, Shiloh, and Bethel', 'a', 'Joshua 10:28-39 — "And that day Joshua took Makkedah...then Joshua passed from Makkedah, and all Israel with him, unto Libnah...and from Libnah unto Lachish...and from Lachish unto Eglon...and from Eglon unto Hebron...and Joshua returned, and all Israel with him, to Debir."'),
-- Adults
('Joshua', 10, 'adults', 1, 'What does Joshua 10:14 declare is the unique aspect of the long day miracle?', 'That it was the first miracle in Canaan', 'There was no day like that before it or after it that the LORD hearkened unto the voice of a man — the LORD fought for Israel', 'That it lasted exactly twelve hours', 'That the moon also stood still for the first time', 'a', 'Joshua 10:14 — "And there was no day like that before it or after it, that the LORD hearkened unto the voice of a man: for the LORD fought for Israel."'),
('Joshua', 10, 'adults', 2, 'What does the phrase "the LORD hearkened unto the voice of a man" (Joshua 10:14) reveal about prayer and divine responsiveness?', 'God never hears human requests', 'God, who governs all creation, sovereignly responded to Joshua''s bold intercessory command, showing that earnest prayer can shape the course of cosmic events according to God''s will', 'Joshua had special magical powers', 'This was a coincidence of natural events', 'a', 'Joshua 10:12-14 — Joshua spoke to the LORD (v.12) and the LORD hearkened (v.14). James 5:16 — "The effectual fervent prayer of a righteous man availeth much." God''s sovereignty does not eliminate but enables effective prayer.'),
('Joshua', 10, 'adults', 3, 'What ancient source does Joshua 10:13 cite as corroborating the long-day account, and what does this citation suggest?', 'The priestly records of the tabernacle', 'The Book of Jasher — an ancient Israelite poetry collection — suggesting the event was celebrated in national memory through song and recorded in a recognised historical source', 'The genealogies of Judges', 'The letters of Moses to Pharaoh', 'a', 'Joshua 10:13 — "Is not this written in the book of Jasher?" This citation of a separate source (also mentioned in 2 Samuel 1:18) indicates the author of Joshua drew on established records, lending historical credibility to the account.'),
('Joshua', 10, 'adults', 4, 'How does God''s encouragement to Joshua before the battle (Joshua 10:8) function theologically?', 'It was merely tactical advice', 'It is a renewal of the divine promise of victory — "Fear them not: for I have delivered them into thine hand" — spoken before the battle to require faith that acts on God''s word before seeing the outcome', 'It guaranteed Joshua would not be wounded', 'It was a conditional promise requiring Israel''s perfection', 'a', 'Joshua 10:8 — "The LORD said unto Joshua, Fear them not: for I have delivered them into thine hand; there shall not a man of them stand before thee." The perfect tense "I have delivered" requires faith-action before visible fulfilment.'),
('Joshua', 10, 'adults', 5, 'What does the execution and public display of the five kings on trees communicate within the ancient Near Eastern context?', 'It was a standard military procedure', 'Public hanging on trees communicated total dominion over defeated enemies and declared God''s victory — while Deuteronomy 21:22-23 required removal before sunset to prevent land defilement, which Joshua carefully observed', 'It was done to terrify neighbouring nations only', 'It had no symbolic significance', 'a', 'Joshua 10:26-27 — Joshua hanged the five kings but "commanded that they should take them down off the trees" before evening. Deuteronomy 21:23 — "His body shall not remain all night upon the tree...for he that is hanged is accursed of God."'),
('Joshua', 10, 'adults', 6, 'What does the rapid conquest of six cities in one chapter (Joshua 10:28-39) emphasise about the nature of the campaign?', 'Joshua was an unusually fast marcher', 'The conquest is portrayed as a sweeping divine victory — the rapid succession of defeats demonstrates that God''s hand, not Israel''s military genius, drove the campaign', 'The cities were small and undefended', 'The narrative compresses centuries of warfare', 'a', 'Joshua 10:30,32,42 — "The LORD delivered it also...into the hand of Israel...The LORD God of Israel fought for Israel." The repeated attribution of each victory to God''s direct action is the theological point of the rapid conquest narrative.'),
('Joshua', 10, 'adults', 7, 'How does the southern campaign of Joshua 10 fulfil the covenant promises made to Abraham?', 'Abraham was never promised this land', 'Genesis 15:18-21 promised Abraham''s descendants the land from Egypt to Euphrates including the territories of the Hittites, Amorites, Canaanites, and others — the southern campaign begins the fulfilment of these specific nations'' defeat', 'The fulfilment was only spiritual, not geographic', 'The Abrahamic covenant was fulfilled at the Red Sea', 'a', 'Genesis 15:18-21 lists specific nations whose land God promised to Abraham. Joshua 10 records the defeat of the Amorites in the southern hill country — a direct step in the geographical fulfilment of the Abrahamic land grant.'),
('Joshua', 10, 'adults', 8, 'What principle of holy war does the phrase "utterly destroyed all that breathed" (Joshua 10:40) illustrate, and how has this been theologically wrestled with?', 'It illustrates that Israel was cruel and God approved of genocide', 'It embodies the herem principle — total consecration of Canaan as God''s holy war judgment on nations whose sin had reached fullness (Genesis 15:16) — theologically grounded in divine judgment, not ethnic hatred, though its application is rightly subject to careful theological reflection', 'It means Joshua killed only soldiers', 'It was an exaggeration common to ancient military reports', 'a', 'Joshua 10:40 and Genesis 15:16 — "For the iniquity of the Amorites is not yet full." The herem destruction of Canaan is rooted in God''s delayed but certain judgment on deeply entrenched sin, not arbitrary violence, while scholars note the formulaic nature of total-destruction language in ancient Near Eastern military texts.');
