-- ============================================================================
-- Quiz Seed: Acts — Part 2 (Chapters 7–12)
-- 3 difficulties × 6 chapters = 96 total questions
--   kids:   3 per chapter  = 18
--   teens:  5 per chapter  = 30
--   adults: 8 per chapter  = 48
-- ============================================================================

-- ═══════════════ CHAPTERS 7–9 ═══════════════

-- ═══ Acts Chapter 7 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Acts', 7, 'kids', 1, 'What did Stephen see when he looked up into heaven before he died?', 'The glory of God and Jesus standing on the right hand of God', 'A rainbow stretching across the sky', 'A host of angels singing', 'A bright star above the temple', 'a', 'Acts 7:55-56 — "But he, being full of the Holy Ghost, looked up stedfastly into heaven, and saw the glory of God, and Jesus standing on the right hand of God, And said, Behold, I see the heavens opened, and the Son of man standing on the right hand of God."'),
('Acts', 7, 'kids', 2, 'What did Stephen pray for the people who were killing him?', 'Lord, lay not this sin to their charge', 'Lord, punish them for what they are doing', 'Lord, send fire from heaven upon them', 'Lord, let me escape from them', 'a', 'Acts 7:60 — "And he kneeled down, and cried with a loud voice, Lord, lay not this sin to their charge."'),
('Acts', 7, 'kids', 3, 'How did Stephen die?', 'The people stoned him with stones', 'He was put on a cross', 'He was thrown into the sea', 'He was put in a lions'' den', 'a', 'Acts 7:58-59 — "And cast him out of the city, and stoned him... And they stoned Stephen, calling upon God, and saying, Lord Jesus, receive my spirit."'),
-- Teens
('Acts', 7, 'teens', 1, 'What was Stephen''s main argument in his long speech to the Sanhedrin?', 'That throughout Israel''s history, the people repeatedly rejected God''s chosen leaders — Joseph, Moses, and the prophets — just as they had now rejected Jesus, the Righteous One', 'That the temple should be made bigger', 'That Rome should be overthrown immediately', 'That the Pharisees were the true leaders of Israel', 'a', 'Acts 7:51-52 — "Ye stiffnecked and uncircumcised in heart and ears, ye do always resist the Holy Ghost: as your fathers did, so do ye. Which of the prophets have not your fathers persecuted? and they have slain them which shewed before of the coming of the Just One; of whom ye have been now the betrayers and murderers."'),
('Acts', 7, 'teens', 2, 'Why did Stephen''s vision of Jesus "standing" at God''s right hand matter?', 'Jesus is usually described as seated at God''s right hand — standing suggests He rose to welcome Stephen, His faithful martyr, showing that heaven takes notice of those who suffer for Christ', 'Standing was a normal position with no significance', 'Jesus was about to leave heaven', 'Stephen imagined it because he was in pain', 'a', 'Acts 7:56 — "Behold, I see the heavens opened, and the Son of man standing on the right hand of God." Elsewhere Jesus is seated (Hebrews 1:3, Colossians 3:1). Standing suggests He rose to receive His first martyr — an honour guard for a faithful witness.'),
('Acts', 7, 'teens', 3, 'What young man was watching and approving of Stephen''s death?', 'Saul, who later became the apostle Paul', 'Timothy, who later became a pastor', 'Barnabas, who later became a missionary', 'Luke, who later wrote the Gospel', 'a', 'Acts 7:58, 8:1 — "The witnesses laid down their clothes at a young man''s feet, whose name was Saul... And Saul was consenting unto his death."'),
('Acts', 7, 'teens', 4, 'What did Stephen say about the Most High God and temples made with hands?', 'The most High dwelleth not in temples made with hands — heaven is His throne and earth is His footstool', 'God lives only in the temple in Jerusalem', 'Every building is equally God''s house', 'God needs temples built by humans to dwell in', 'a', 'Acts 7:48-49 — "Howbeit the most High dwelleth not in temples made with hands; as saith the prophet, Heaven is my throne, and earth is my footstool: what house will ye build me? saith the Lord."'),
('Acts', 7, 'teens', 5, 'How did Stephen describe Moses'' experience at the burning bush?', 'Moses saw a burning bush in the wilderness of mount Sinai, and the Lord spoke to him saying the ground was holy, for He was the God of Abraham, Isaac, and Jacob', 'Moses found a treasure hidden under a bush', 'Moses was attacked by a wild animal near a bush', 'Moses planted a bush that grew miraculously', 'a', 'Acts 7:30-33 — "There appeared to him in the wilderness of mount Sina an angel of the Lord in a flame of fire in a bush... the voice of the Lord came unto him, Saying, I am the God of thy fathers, the God of Abraham, and the God of Isaac, and the God of Jacob."'),
-- Adults
('Acts', 7, 'adults', 1, 'How does Stephen''s speech function as a theological reinterpretation of Israel''s history?', 'Stephen recasts Israel''s history as a pattern of repeated rejection of God''s chosen deliverers: Joseph rejected by his brothers, Moses rejected twice by Israel, and the prophets persecuted. The pattern culminates in the rejection of the "Just One" (Jesus). Stephen argues that the Sanhedrin stands in the tradition of Israel''s rebels, not its faithful', 'Stephen simply repeated the Old Testament without interpretation', 'His speech was irrelevant to the charges', 'He praised Israel''s faithfulness throughout history', 'a', 'Acts 7:9,27,35,39,51-52 — Joseph: "the patriarchs, moved with envy, sold Joseph" (v.9); Moses: "Who made thee a ruler and a judge?" (v.27,35); prophets: "which of the prophets have not your fathers persecuted?" (v.52). The pattern of rejection is the sermon''s backbone.'),
('Acts', 7, 'adults', 2, 'What is the significance of Stephen''s argument that God appeared to Abraham "before he dwelt in Charran" (Haran) and that Moses met God in the Sinai wilderness?', 'Stephen demonstrates that God is not confined to the Promised Land or the temple — He met Abraham in Mesopotamia, Moses in Sinai, and gave the tabernacle as a portable dwelling. This undermines the charge that Stephen blasphemed the "holy place" by showing God has always been active beyond fixed locations', 'Stephen was correcting geographic errors in the Torah', 'These locations were unimportant', 'Only Jerusalem encounters with God count', 'a', 'Acts 7:2,30,44 — God appeared in Mesopotamia (v.2), Sinai (v.30), and the portable tabernacle (v.44) — all outside Jerusalem and before the temple existed. Stephen''s implicit argument: God''s presence transcends buildings, so rejecting the temple-centric view is not blasphemy.'),
('Acts', 7, 'adults', 3, 'How does Stephen''s quotation of Amos 5:25-27 (Acts 7:42-43) function in his argument?', 'Stephen cites Amos to show that even during the wilderness period Israel was idolatrous — they carried the tabernacle of Moloch and the star of Remphan (Saturn worship). This proves that Israel''s rebellion is not a later development but a persistent character. The temple itself became an idol when trust was placed in the building rather than the God it represented', 'Stephen was discussing astronomy', 'The quotation supports temple worship', 'Amos 5 is about agricultural practices', 'a', 'Acts 7:42-43 — "Then God turned, and gave them up to worship the host of heaven... Yea, ye took up the tabernacle of Moloch, and the star of your god Remphan, figures which ye made to worship them." Stephen shows that Israel''s worship history includes both legitimate worship and persistent idolatry.'),
('Acts', 7, 'adults', 4, 'What does Stephen''s death have in common with Jesus'' death, and why does Luke draw these parallels?', 'Stephen echoes Jesus in multiple ways: he sees the Son of Man (cf. Luke 22:69), prays "Lord Jesus, receive my spirit" (cf. Luke 23:46 "Father, into thy hands"), and asks forgiveness for his killers (cf. Luke 23:34). Luke presents Stephen as the first imitator of Christ — his death demonstrates that following Jesus includes sharing in His suffering and His grace', 'There are no parallels between the two deaths', 'Stephen copied Jesus'' words for dramatic effect', 'Only the method of execution is similar', 'a', 'Acts 7:56,59,60 — Son of Man vision (cf. Luke 22:69), "receive my spirit" (cf. Luke 23:46), "lay not this sin to their charge" (cf. Luke 23:34). Luke deliberately patterns Stephen''s death on Jesus'' death. The disciple mirrors the Master.'),
('Acts', 7, 'adults', 5, 'What is the theological significance of Stephen calling the council "stiffnecked and uncircumcised in heart and ears" (7:51)?', 'Stephen inverts their self-understanding: the physically circumcised Sanhedrin is spiritually uncircumcised — a devastating charge using Moses'' own language (Deuteronomy 10:16, Jeremiah 4:4). They claim to defend Moses but embody the very rebellion Moses condemned. The "stiffnecked" language echoes Exodus 32:9 (golden calf incident), equating the council with the idolaters', 'Stephen was using random insults', 'Uncircumcised in heart was a compliment', 'The phrase has no Old Testament background', 'a', 'Acts 7:51 — "Ye stiffnecked and uncircumcised in heart and ears." Deuteronomy 10:16: "Circumcise therefore the foreskin of your heart, and be no more stiffnecked." Jeremiah 4:4: "Circumcise yourselves to the LORD, and take away the foreskins of your heart." Stephen''s accusers are Moses'' true violators.'),
('Acts', 7, 'adults', 6, 'How does Stephen''s reference to Moses as a "type" of Christ advance his Christological argument?', 'Stephen presents Moses as a deliverer rejected by his own people twice (7:25,35) — "Who made thee a ruler and a judge?" — yet God sent him back as both ruler and deliverer. The parallel to Jesus is explicit: the one Israel rejected is the one God sent as Saviour. Moses himself predicted "A prophet shall the Lord your God raise up unto you... like unto me" (v.37)', 'Moses and Jesus have nothing in common', 'Stephen was replacing Moses with Jesus', 'Moses was greater than Jesus in Stephen''s view', 'a', 'Acts 7:35-37 — "This Moses whom they refused, saying, Who made thee a ruler and a judge? the same did God send to be a ruler and a deliverer... This is that Moses, which said... A prophet shall the Lord your God raise up unto you of your brethren, like unto me." The rejection-then-vindication pattern links Moses and Jesus.'),
('Acts', 7, 'adults', 7, 'What does the phrase "the Just One" (7:52) signify as a Christological title?', 'The "Just One" (ho dikaios) is a messianic title rooted in Isaiah 53:11 ("my righteous servant") and Jeremiah 23:5 ("a righteous Branch"). It affirms Jesus'' sinless perfection and His role as the righteous one who justifies sinners. Stephen accuses the council of murdering the very embodiment of the righteousness they claim to defend', 'It was a common nickname for any good person', 'Stephen invented this title', 'The title refers to John the Baptist', 'a', 'Acts 7:52 — "The Just One" (ho dikaios) echoes Isaiah 53:11, Jeremiah 23:5-6, and Zechariah 9:9. Peter also used it (Acts 3:14). The title''s irony is devastating: those who condemn Stephen for lawlessness have murdered the Righteous One Himself.'),
('Acts', 7, 'adults', 8, 'What is the narrative significance of Saul''s introduction at Stephen''s death?', 'Luke introduces Saul at the moment of maximum hostility to the gospel — "consenting unto his death" and later "made havock of the church" (8:1,3). This sets up the dramatic reversal of Saul''s conversion (chapter 9). Stephen''s prayer for his killers may be implicitly answered in Saul''s salvation — the church''s first martyr''s prayer produces its greatest missionary', 'Saul''s presence was coincidental', 'Saul tried to stop the stoning', 'Luke mentions Saul only for historical accuracy', 'a', 'Acts 7:58, 8:1 — "Whose name was Saul... And Saul was consenting unto his death." Augustine reportedly said, "If Stephen had not prayed, the church would not have had Paul." Whether or not directly causal, Luke''s juxtaposition of Stephen''s prayer and Saul''s presence is narratively purposeful.');

-- ═══ Acts Chapter 8 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Acts', 8, 'kids', 1, 'Where did Philip go to preach the gospel after the believers scattered?', 'To the city of Samaria', 'To Rome', 'To Egypt', 'To Babylon', 'a', 'Acts 8:5 — "Then Philip went down to the city of Samaria, and preached Christ unto them."'),
('Acts', 8, 'kids', 2, 'What was the Ethiopian man reading when Philip met him on the road?', 'The book of Isaiah the prophet', 'The book of Psalms', 'The book of Genesis', 'The book of Proverbs', 'a', 'Acts 8:28,30 — "Was returning, and sitting in his chariot read Esaias the prophet... and heard him read the prophet Esaias."'),
('Acts', 8, 'kids', 3, 'What happened after Philip baptised the Ethiopian man?', 'The Spirit of the Lord caught away Philip and the Ethiopian went on his way rejoicing', 'They travelled together to Jerusalem', 'Philip stayed in Ethiopia forever', 'The Ethiopian became sad and went home', 'a', 'Acts 8:39 — "The Spirit of the Lord caught away Philip, that the eunuch saw him no more: and he went on his way rejoicing."'),
-- Teens
('Acts', 8, 'teens', 1, 'What caused the believers to scatter from Jerusalem?', 'A great persecution arose against the church after Stephen''s death, and Saul was ravaging the church, entering houses and dragging men and women to prison', 'A famine struck Jerusalem', 'An earthquake destroyed their homes', 'The Romans expelled all Jews from the city', 'a', 'Acts 8:1,3 — "And at that time there was a great persecution against the church which was at Jerusalem... As for Saul, he made havock of the church, entering into every house, and haling men and women committed them to prison."'),
('Acts', 8, 'teens', 2, 'Who was Simon the sorcerer, and what did he want from the apostles?', 'A magician in Samaria who believed and was baptised, but then offered money to buy the power to give the Holy Spirit — Peter rebuked him sharply', 'A Roman official who wanted to learn magic tricks', 'A Pharisee who wanted to join the apostles', 'A merchant who sold spiritual books', 'a', 'Acts 8:18-20 — "And when Simon saw that through laying on of the apostles'' hands the Holy Ghost was given, he offered them money, Saying, Give me also this power... But Peter said unto him, Thy money perish with thee, because thou hast thought that the gift of God may be purchased with money."'),
('Acts', 8, 'teens', 3, 'What passage from Isaiah was the Ethiopian reading?', 'Isaiah 53 — "He was led as a sheep to the slaughter; and like a lamb dumb before his shearer, so opened he not his mouth"', 'Isaiah 6 about the vision in the temple', 'Isaiah 9 about a child being born', 'Isaiah 40 about comforting God''s people', 'a', 'Acts 8:32-33 — "The place of the scripture which he read was this, He was led as a sheep to the slaughter; and like a lamb dumb before his shearer, so opened he not his mouth."'),
('Acts', 8, 'teens', 4, 'What question did the Ethiopian ask Philip about the passage in Isaiah?', 'I pray thee, of whom speaketh the prophet this? of himself, or of some other man?', 'Can you teach me to read Hebrew?', 'Why do the Jews not accept Gentiles?', 'Where can I find a copy of this scroll?', 'a', 'Acts 8:34 — "And the eunuch answered Philip, and said, I pray thee, of whom speaketh the prophet this? of himself, or of some other man?"'),
('Acts', 8, 'teens', 5, 'What did the Ethiopian say when they came to some water?', 'See, here is water; what doth hinder me to be baptised?', 'Let us stop and rest by the water', 'I need to wash before I continue my journey', 'This water reminds me of the Jordan River', 'a', 'Acts 8:36 — "And as they went on their way, they came unto a certain water: and the eunuch said, See, here is water; what doth hinder me to be baptized?"'),
-- Adults
('Acts', 8, 'adults', 1, 'How does the persecution in Acts 8:1 paradoxically fulfil Acts 1:8?', 'The scattering of believers from Jerusalem into Judaea and Samaria exactly follows the geographic pattern Jesus predicted in Acts 1:8. Persecution becomes the mechanism of mission — what the enemy intended to destroy the church, God used to spread it. The believers "went every where preaching the word" (8:4)', 'The persecution stopped the gospel temporarily', 'The scattering was unrelated to Acts 1:8', 'Believers scattered but stopped preaching', 'a', 'Acts 8:1,4 — "They were all scattered abroad throughout the regions of Judaea and Samaria... Therefore they that were scattered abroad went every where preaching the word." The gospel reaches Judaea and Samaria not through a planned mission but through persecution-driven displacement.'),
('Acts', 8, 'adults', 2, 'What is the theological significance of the gospel going to Samaria?', 'Samaria was a region of mixed Jewish-Gentile heritage, despised by Jews (John 4:9). The gospel''s arrival in Samaria breaks a major ethnic-religious barrier and fulfils Jesus'' words to the Samaritan woman (John 4:21-24). It represents the middle step between Jewish Jerusalem and the Gentile world — a bridge community', 'Samaria was just another Jewish region', 'The gospel was not welcome there', 'Samaria had no religious significance', 'a', 'Acts 8:5-8 — Philip preaches in Samaria with great success. Samaritans had their own Pentateuch, temple (Gerizim), and messianic expectations. Their inclusion shows the gospel transcending the Jewish-Samaritan divide (cf. John 4:9,39-42). Acts 1:8''s "Samaria" step is being fulfilled.'),
('Acts', 8, 'adults', 3, 'What does the Simon Magus episode (8:9-24) warn about regarding the relationship between faith and genuine conversion?', 'Simon "believed" and was baptised yet his heart was "not right in the sight of God" (v.21) — he was still in "the bond of iniquity" (v.23). This warns that profession of faith and even baptism do not guarantee genuine conversion. Simon''s desire to purchase spiritual power reveals a heart still shaped by self-interest rather than surrender to Christ', 'Simon was genuinely converted', 'Baptism automatically guarantees salvation', 'Simon''s sin was minor and insignificant', 'a', 'Acts 8:13,20-23 — Simon "believed also: and when he was baptized..." Yet Peter says: "Thy heart is not right in the sight of God... thou art in the gall of bitterness, and in the bond of iniquity." Simon''s "belief" was attracted to power, not to Christ. The episode is a cautionary tale about superficial faith.'),
('Acts', 8, 'adults', 4, 'Why did the apostles send Peter and John to Samaria, and what does the delayed gift of the Spirit signify?', 'The Samaritans believed and were baptised but had not received the Spirit until Peter and John laid hands on them. This unique delay ensured that the Samaritan believers were visibly connected to the Jerusalem apostles — preventing a separate Samaritan church. The Spirit''s coming through apostolic hands unified the church across the Jewish-Samaritan divide', 'The Spirit was late due to distance from Jerusalem', 'Philip had performed the baptism incorrectly', 'Samaritans were inferior believers', 'a', 'Acts 8:14-17 — "They sent unto them Peter and John... they laid their hands on them, and they received the Holy Ghost." This is not normative for all conversion but a unique Samaritan Pentecost — mirroring Acts 2 (Jewish) and anticipating Acts 10 (Gentile). The apostolic connection prevents schism.'),
('Acts', 8, 'adults', 5, 'How does Philip''s encounter with the Ethiopian eunuch advance Luke''s theme of gospel expansion?', 'The Ethiopian is a God-fearer — a Gentile on the margins of Judaism (eunuchs were excluded from the assembly, Deuteronomy 23:1, though Isaiah 56:3-5 promises their inclusion). His conversion represents the gospel reaching Africa and the margins of Jewish acceptability. Philip''s Spirit-directed encounter shows God orchestrating individual salvation within the larger mission', 'The Ethiopian was already a Christian', 'The encounter had no theological significance', 'Philip met the Ethiopian by accident', 'a', 'Acts 8:26-29 — "The angel of the Lord spake unto Philip... the Spirit said unto Philip, Go near, and join thyself to this chariot." Divine direction at every step. The Ethiopian''s identity — eunuch, African, God-fearer — fulfils Isaiah 56:3-5: "Neither let the eunuch say, Behold, I am a dry tree."'),
('Acts', 8, 'adults', 6, 'What does Philip''s use of Isaiah 53 to preach "Jesus" reveal about early Christological interpretation?', 'The early church read Isaiah''s Suffering Servant as a direct prophecy of Jesus'' atoning death. Philip "began at the same scripture, and preached unto him Jesus" (v.35) — showing that Isaiah 53 was central to apostolic Christology. The passage''s language of substitutionary suffering, silent submission, and unjust death mapped perfectly onto the cross', 'Isaiah 53 was not used by the early church', 'Philip discussed a different topic entirely', 'The Suffering Servant refers to Israel, not Jesus', 'a', 'Acts 8:35 — "Then Philip opened his mouth, and began at the same scripture, and preached unto him Jesus." The Ethiopian was reading Isaiah 53:7-8 — the heart of the Suffering Servant passage. Philip showed how Jesus fulfilled every detail: silent before accusers, unjust trial, atoning death.'),
('Acts', 8, 'adults', 7, 'What is the significance of the Spirit "catching away" Philip (8:39)?', 'Philip''s supernatural removal echoes Elijah''s translation (1 Kings 18:12, 2 Kings 2:16) and demonstrates that the Spirit sovereignly directs the missionary enterprise. The Spirit brought Philip to the Ethiopian and then removed him — human agents serve at the Spirit''s initiative and disposal. Mission is Spirit-driven, not humanly managed', 'Philip simply walked away quickly', 'The "catching away" is a metaphor for death', 'Philip was taken to heaven permanently', 'a', 'Acts 8:39 — "The Spirit of the Lord caught away Philip." The verb "harpazo" (caught/snatched) is the same word used for Paul''s rapture to the third heaven (2 Corinthians 12:2). Philip''s sudden removal underscores the Spirit''s absolute sovereignty over the mission.'),
('Acts', 8, 'adults', 8, 'How does Acts 8 bridge the transition from Jewish to Gentile mission?', 'Chapter 8 presents two intermediate steps: Samaritans (half-Jewish/half-Gentile) and an Ethiopian God-fearer (Gentile proselyte). Neither is a full Jew nor a full pagan — they represent a gradual widening. The full Gentile breakthrough comes in chapter 10 with Cornelius. Luke carefully shows the gospel crossing boundaries incrementally, building theological precedent for the Gentile mission', 'The Gentile mission began in chapter 8', 'There was no gradual transition', 'Only Jews were converted in chapter 8', 'a', 'Acts 8 moves from Jewish believers scattered (v.1-4) to Samaritans (v.5-25) to an Ethiopian eunuch (v.26-40). Each step widens the circle: mixed heritage → Gentile God-fearer. The full breakthrough to uncircumcised Gentiles awaits Peter and Cornelius (chapter 10).');

-- ═══ Acts Chapter 9 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Acts', 9, 'kids', 1, 'What happened to Saul on the road to Damascus?', 'A bright light from heaven shone around him and he heard Jesus'' voice saying "Saul, Saul, why persecutest thou me?"', 'He was attacked by robbers', 'A storm blew him off his horse', 'He found a treasure chest', 'a', 'Acts 9:3-4 — "And as he journeyed, he came near Damascus: and suddenly there shined round about him a light from heaven: And he fell to the earth, and heard a voice saying unto him, Saul, Saul, why persecutest thou me?"'),
('Acts', 9, 'kids', 2, 'What happened to Saul''s eyes after he saw the bright light?', 'He was blind for three days', 'They turned a different colour', 'He could see better than before', 'Nothing happened to his eyes', 'a', 'Acts 9:8-9 — "And Saul arose from the earth; and when his eyes were opened, he saw no man: but they led him by the hand, and brought him into Damascus. And he was three days without sight."'),
('Acts', 9, 'kids', 3, 'Who did God send to help Saul get his sight back?', 'Ananias, a disciple in Damascus', 'Peter, the apostle', 'John, the beloved disciple', 'Luke, the doctor', 'a', 'Acts 9:10,17 — "And there was a certain disciple at Damascus, named Ananias... And Ananias went his way, and entered into the house; and putting his hands on him said, Brother Saul, the Lord, even Jesus... hath sent me, that thou mightest receive thy sight."'),
-- Teens
('Acts', 9, 'teens', 1, 'Why was Saul going to Damascus?', 'He had letters from the high priest to arrest any Christians he found and bring them bound to Jerusalem', 'He was going on a holiday', 'He was delivering temple supplies', 'He was escaping from the Romans', 'a', 'Acts 9:1-2 — "And Saul, yet breathing out threatenings and slaughter against the disciples of the Lord, went unto the high priest, And desired of him letters to Damascus to the synagogues, that if he found any of this way, whether they were men or women, he might bring them bound unto Jerusalem."'),
('Acts', 9, 'teens', 2, 'What did Jesus call Saul that He wanted him to be?', 'A chosen vessel to bear His name before the Gentiles, kings, and the children of Israel', 'The new high priest of Israel', 'A wealthy merchant for the church', 'A military leader for the believers', 'a', 'Acts 9:15 — "He is a chosen vessel unto me, to bear my name before the Gentiles, and kings, and the children of Israel."'),
('Acts', 9, 'teens', 3, 'What did Saul immediately begin to do after his conversion?', 'He preached Christ in the synagogues, that Jesus is the Son of God', 'He went home and rested for a year', 'He wrote letters to all the churches', 'He travelled to Rome to preach', 'a', 'Acts 9:20 — "And straightway he preached Christ in the synagogues, that he is the Son of God."'),
('Acts', 9, 'teens', 4, 'How did Saul escape from Damascus when the Jews plotted to kill him?', 'The disciples let him down through the wall in a basket by night', 'He disguised himself as a merchant', 'He fought his way through the city gate', 'The Roman guards escorted him out safely', 'a', 'Acts 9:25 — "Then the disciples took him by night, and let him down by the wall in a basket."'),
('Acts', 9, 'teens', 5, 'What miracle did Peter perform in Joppa?', 'He raised Tabitha (Dorcas) from the dead after the saints called for him', 'He healed a man born blind', 'He multiplied loaves of bread', 'He calmed a storm at sea', 'a', 'Acts 9:40-41 — "But Peter put them all forth, and kneeled down, and prayed; and turning him to the body said, Tabitha, arise. And she opened her eyes: and when she saw Peter, she sat up. And he gave her his hand, and lifted her up."'),
-- Adults
('Acts', 9, 'adults', 1, 'What does Jesus'' question "why persecutest thou me?" reveal about the relationship between Christ and the church?', 'Jesus identifies personally with His persecuted church — to persecute believers is to persecute Christ Himself. This establishes the mystical union between Christ and His body (cf. 1 Corinthians 12:27). Saul was attacking Christians but Jesus says "me" — the Head suffers when the body suffers', 'Jesus was speaking metaphorically with no real union', 'Saul was literally attacking Jesus', 'The "me" refers to God the Father', 'a', 'Acts 9:4-5 — "Saul, Saul, why persecutest thou me?... I am Jesus whom thou persecutest." The identification of Christ with His church is the foundation of Paul''s later "body of Christ" theology (1 Corinthians 12:12-27, Ephesians 5:29-30). What is done to believers is done to their Lord.'),
('Acts', 9, 'adults', 2, 'How does Saul''s conversion demonstrate the sovereign, initiative-taking nature of divine grace?', 'Saul was not seeking Christ — he was actively persecuting Him. His conversion was wholly God''s initiative: the light, the voice, the commission through Ananias were all divine actions. Saul contributed nothing but hostility. This is the paradigmatic case of grace overcoming opposition, demonstrating that conversion is God''s work, not human achievement', 'Saul was already sympathetic to Christianity', 'Saul chose to convert on his own', 'Ananias persuaded Saul through arguments', 'a', 'Acts 9:1-6 — Saul was "breathing out threatenings and slaughter" (v.1) when Christ intercepted him. He was the most unlikely convert. Paul himself later reflects: "By the grace of God I am what I am" (1 Corinthians 15:10). His conversion is Exhibit A of prevenient, sovereign grace.'),
('Acts', 9, 'adults', 3, 'What is the significance of Jesus telling Ananias that Saul would suffer "great things" for His name?', 'Jesus reveals that Saul''s calling includes suffering as an essential component, not an accidental obstacle. The persecutor will become the persecuted. This redefines apostleship: bearing Christ''s name means bearing His cross. Paul''s later catalogue of sufferings (2 Corinthians 11:23-28) fulfils this prediction precisely', 'Suffering was optional for Paul', 'This prediction was never fulfilled', 'Jesus was threatening Saul as punishment', 'a', 'Acts 9:16 — "For I will shew him how great things he must suffer for my name''s sake." The word "must" (dei) indicates divine necessity. Suffering is not incidental to Paul''s mission but integral to it (cf. Philippians 3:10, Colossians 1:24).'),
('Acts', 9, 'adults', 4, 'What role does Ananias play in Saul''s conversion, and what does this reveal about the body of Christ?', 'Ananias is an ordinary disciple — not an apostle — yet God uses him to lay hands on the church''s greatest persecutor. This demonstrates that God mediates grace through the community of believers. Even the apostle to the Gentiles needed a simple disciple to welcome him, heal him, and connect him to the church', 'Ananias was one of the twelve apostles', 'Saul did not need Ananias at all', 'Ananias converted Saul through persuasion', 'a', 'Acts 9:10-18 — Ananias is called simply "a certain disciple" (v.10). He overcomes understandable fear to obey God, addresses Saul as "Brother Saul" (v.17), and mediates healing and the Spirit. God could have done everything directly but chose to use a community member — showing the church is Christ''s instrument.'),
('Acts', 9, 'adults', 5, 'How does Barnabas''s advocacy for Saul (9:26-27) illustrate the role of mediators in the community of faith?', 'When the Jerusalem disciples feared Saul (understandably), Barnabas ("son of encouragement") risked his reputation by vouching for him, bringing him to the apostles and testifying to his conversion. Without Barnabas''s bridge-building, Saul might have been permanently excluded. This shows the crucial role of trusted intermediaries in reconciliation', 'Barnabas was required to vouch for all newcomers', 'The apostles accepted Saul immediately', 'Barnabas acted selfishly for personal gain', 'a', 'Acts 9:26-27 — "When Saul was come to Jerusalem... they were all afraid of him... But Barnabas took him, and brought him to the apostles, and declared unto them how he had seen the Lord." Barnabas bridges distrust with testimony, risking his standing to include the converted persecutor.'),
('Acts', 9, 'adults', 6, 'What is the significance of Peter''s miracles at Lydda and Joppa (healing Aeneas, raising Tabitha)?', 'These miracles parallel Jesus'' healings and Elijah/Elisha''s miracles, validating Peter''s apostolic authority. They also serve narratively to position Peter in Joppa — on the coast, near Gentile territory — setting the stage for the Cornelius episode in chapter 10. Luke shows that the same power that worked through Jesus now works through His apostles', 'They were Peter''s only miracles', 'The miracles had no narrative purpose', 'Peter performed them for personal fame', 'a', 'Acts 9:34,40 — "Aeneas, Jesus Christ maketh thee whole" (v.34) and "Tabitha, arise" (v.40, cf. Jesus'' "Talitha cumi," Mark 5:41). The Tabitha miracle echoes Elisha raising the Shunammite''s son (2 Kings 4:32-35). Peter at Joppa (=Jonah''s embarkation port) prepares for the Gentile mission call.'),
('Acts', 9, 'adults', 7, 'Why does Luke record Paul''s conversion three times in Acts (chapters 9, 22, and 26)?', 'The triple telling underscores its supreme importance in Luke''s narrative — Saul''s conversion is the pivotal event that redirects the mission from exclusively Jewish to universally Gentile. Each retelling adapts the story to its audience (narrator, Jewish crowd, King Agrippa), revealing new details and emphasising different aspects of the calling', 'Luke made a copying error', 'Each account contradicts the others', 'Only one account is historically accurate', 'a', 'Acts 9 (third-person narrative), 22 (Paul''s defence to Jewish crowd), 26 (Paul before Agrippa). The triple repetition is Luke''s literary equivalent of triple emphasis — this event is foundational. Each version adds context appropriate to the audience while maintaining essential consistency.'),
('Acts', 9, 'adults', 8, 'What does Peter staying with Simon the tanner (9:43) subtly foreshadow?', 'Tanners were considered ritually unclean by Jews because they handled dead animal skins. Peter lodging with a tanner shows his ritual boundaries already loosening — preparing him for the vision in chapter 10 where God declares all foods clean. Luke subtly shows Peter being moved by the Spirit toward Gentile inclusion before the explicit revelation', 'Tanning was a prestigious Jewish profession', 'Peter chose the house randomly', 'Simon the tanner was a Pharisee', 'a', 'Acts 9:43 — "He tarried many days in Joppa with one Simon a tanner." Tanners worked with dead animals (ritually defiling in Jewish law). Peter''s willingness to stay in a tanner''s house signals his readiness for the revolutionary vision of Acts 10. Luke''s detail is theologically purposeful.');

-- ═══════════════ CHAPTERS 10–12 ═══════════════

-- ═══ Acts Chapter 10 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Acts', 10, 'kids', 1, 'Who was Cornelius?', 'A Roman centurion who prayed to God and gave much money to the poor', 'A Jewish priest in the temple', 'A fisherman from Galilee', 'A merchant from Egypt', 'a', 'Acts 10:1-2 — "There was a certain man in Caesarea called Cornelius, a centurion of the band called the Italian band, A devout man, and one that feared God with all his house, which gave much alms to the people, and prayed to God alway."'),
('Acts', 10, 'kids', 2, 'What strange vision did Peter see on the rooftop?', 'A great sheet coming down from heaven full of all kinds of animals, and God told him to eat', 'A ladder reaching up to heaven', 'A burning bush', 'A star falling from the sky', 'a', 'Acts 10:11-13 — "And saw heaven opened, and a certain vessel descending unto him, as it had been a great sheet... Wherein were all manner of fourfooted beasts... And there came a voice to him, Rise, Peter; kill, and eat."'),
('Acts', 10, 'kids', 3, 'What happened while Peter was still speaking to Cornelius and his household?', 'The Holy Ghost fell on all of them and they began speaking in tongues and praising God', 'A storm destroyed the house', 'The Roman soldiers arrived', 'Everyone fell asleep', 'a', 'Acts 10:44-46 — "While Peter yet spake these words, the Holy Ghost fell on all them which heard the word... For they heard them speak with tongues, and magnify God."'),
-- Teens
('Acts', 10, 'teens', 1, 'What did Peter learn from his vision of the sheet with unclean animals?', 'God told him "What God hath cleansed, that call not thou common" — meaning he should not call any person unclean or refuse to visit Gentiles', 'He should eat more meat in his diet', 'All dietary laws were originally wrong', 'He should become a farmer instead of a fisherman', 'a', 'Acts 10:15,28 — "What God hath cleansed, that call not thou common... God hath shewed me that I should not call any man common or unclean."'),
('Acts', 10, 'teens', 2, 'What important truth did Peter declare at Cornelius''s house?', 'God is no respecter of persons — in every nation he that feareth him, and worketh righteousness, is accepted with him', 'Only Jews can receive salvation', 'Roman citizens are superior to all others', 'Only people in Jerusalem can be saved', 'a', 'Acts 10:34-35 — "Of a truth I perceive that God is no respecter of persons: But in every nation he that feareth him, and worketh righteousness, is accepted with him."'),
('Acts', 10, 'teens', 3, 'How did the Jewish believers who came with Peter react to the Gentiles receiving the Holy Spirit?', 'They were astonished that the gift of the Holy Ghost was poured out on the Gentiles also', 'They were angry and wanted to leave', 'They expected this to happen', 'They did not notice anything unusual', 'a', 'Acts 10:45 — "And they of the circumcision which believed were astonished, as many as came with Peter, because that on the Gentiles also was poured out the gift of the Holy Ghost."'),
('Acts', 10, 'teens', 4, 'What did Peter command after the Holy Spirit fell on the Gentiles?', 'He commanded them to be baptised in the name of the Lord', 'He told them to go to Jerusalem first', 'He said they must be circumcised before baptism', 'He asked them to wait for further instructions', 'a', 'Acts 10:48 — "And he commanded them to be baptized in the name of the Lord."'),
('Acts', 10, 'teens', 5, 'What did the angel tell Cornelius to do?', 'Send men to Joppa and call for Simon Peter, who would tell him words by which he and his house would be saved', 'Build an altar and offer sacrifices', 'Travel to Jerusalem to visit the temple', 'Give all his money to the poor immediately', 'a', 'Acts 10:5-6 and 11:14 — "Send men to Joppa, and call for Simon, whose surname is Peter... Who shall tell thee words, whereby thou and all thy house shall be saved."'),
-- Adults
('Acts', 10, 'adults', 1, 'Why is the Cornelius episode the most significant turning point in Acts?', 'It marks the definitive inclusion of Gentiles in the people of God without requiring circumcision or Torah observance. God initiates at every level — sending an angel to Cornelius, giving Peter the vision, directing the Spirit to fall on uncircumcised Gentiles. The episode establishes the theological precedent that Peter cites at the Jerusalem Council (15:7-11)', 'It was a minor incident quickly forgotten', 'Gentiles were already fully included before this', 'Only Cornelius''s household was affected', 'a', 'Acts 10 is the Gentile Pentecost. God acts at every stage: angel to Cornelius (v.3), vision to Peter (v.10-16), Spirit''s command (v.19-20), Spirit falling on Gentiles (v.44). Peter later cites this event as decisive proof that God accepted Gentiles (15:7-9). It changes the church forever.'),
('Acts', 10, 'adults', 2, 'How does Peter''s rooftop vision function on multiple levels?', 'The vision operates literally (clean/unclean foods) and metaphorically (clean/unclean people). Peter initially understands it as about food, but the Spirit''s instruction to go with Cornelius''s men reveals its deeper meaning: the Jewish purity system that separated Jews from Gentiles has been transcended in Christ. "What God hath cleansed, call not thou common" applies to people, not just food', 'The vision was only about dietary laws', 'Peter never understood the vision', 'The vision was a hallucination from hunger', 'a', 'Acts 10:14-15,28 — Peter says "Not so, Lord; for I have never eaten any thing that is common or unclean." Three repetitions (v.16) emphasise the point. Peter''s own interpretation (v.28): "God hath shewed me that I should not call any man common or unclean." The food vision is a parable about people.'),
('Acts', 10, 'adults', 3, 'What does the Holy Spirit falling on Gentiles before baptism (10:44-48) establish theologically?', 'The Spirit''s sovereign descent on unbaptised, uncircumcised Gentiles demonstrates that God accepts Gentiles on the basis of faith alone — not through Jewish ritual prerequisites. This reverses the expected order (believe → baptise → receive Spirit) and removes any basis for requiring Gentile conversion to Judaism as a precondition for salvation', 'Baptism is unnecessary', 'The order was normal and expected', 'The Spirit came because of Cornelius''s good works', 'a', 'Acts 10:44-47 — "While Peter yet spake... the Holy Ghost fell on all them which heard the word." Peter''s response: "Can any man forbid water, that these should not be baptized, which have received the Holy Ghost as well as we?" God''s initiative precedes human ritual — grace is not mediated through ceremony.'),
('Acts', 10, 'adults', 4, 'How does Peter''s sermon to Cornelius (10:34-43) represent a gospel summary for Gentile audiences?', 'Peter adapts the kerygma for a Gentile audience: he begins with God''s impartiality (v.34-35), summarises Jesus'' ministry from baptism to crucifixion (v.37-39), proclaims the resurrection with eyewitness testimony (v.40-41), and announces universal judgment and forgiveness through faith in His name (v.42-43). It is the template for Gentile evangelism', 'Peter preached the same sermon as at Pentecost', 'The sermon had no structure', 'Peter only discussed Jewish law', 'a', 'Acts 10:34-43 — The sermon moves from universal principle (God is no respecter of persons) through historical narrative (Jesus'' baptism, ministry, death, resurrection) to universal application (forgiveness through His name to all who believe). It adapts the core kerygma for non-Jewish ears.'),
('Acts', 10, 'adults', 5, 'What does "God is no respecter of persons" (10:34) mean in its original context?', 'The Greek prosopolemptes means God does not "receive faces" — He does not judge by external markers of ethnicity, social status, or religious heritage. Peter''s realisation overturns a lifetime of Jewish exclusivism. It does not mean all religions are equally valid but that God''s salvation is available to all nations on equal terms through Christ', 'God treats everyone the same regardless of their response to Him', 'All religions are equally true', 'Only Peter learned this truth', 'a', 'Acts 10:34-35 — "God is no respecter of persons: But in every nation he that feareth him, and worketh righteousness, is accepted with him." This echoes Deuteronomy 10:17 but extends it: access to God is not ethnically restricted. The qualifier — "feareth him and worketh righteousness" — shows response to God still matters.'),
('Acts', 10, 'adults', 6, 'What is the significance of the parallel between the Jewish Pentecost (Acts 2) and the Gentile Pentecost (Acts 10)?', 'Peter explicitly connects the two events: "the Holy Ghost fell on them, as on us at the beginning" (11:15). The same Spirit, same manifestation (tongues), same gift — God makes no distinction. This parallel demonstrates that Gentile inclusion is not a secondary category but equal participation in the same Pentecostal reality', 'There is no parallel between the two events', 'The Gentile experience was inferior', 'Only Jerusalem believers received the true Spirit', 'a', 'Acts 10:47, 11:15,17 — "The Holy Ghost fell on them, as on us at the beginning." "God gave them the like gift as he did unto us." Peter sees Cornelius''s experience as a repeat of Pentecost — same God, same Spirit, same gift, no distinction. The parallel is theologically decisive.'),
('Acts', 10, 'adults', 7, 'How does Luke''s threefold repetition of the Cornelius story (chapters 10, 11, 15) indicate its importance?', 'Like Paul''s conversion (3 tellings), the Cornelius event is narrated three times — in chapter 10 (event), chapter 11 (Peter''s defence to Jerusalem), and chapter 15 (Peter''s argument at the council). Triple repetition in Luke''s narrative signals supreme importance. The Gentile inclusion is the second most pivotal event in Acts after Pentecost', 'Luke was being repetitive by mistake', 'Each account describes a different event', 'Only one telling is accurate', 'a', 'Acts 10 (narrative), 11:1-18 (Peter''s retelling to Jerusalem), 15:7-11 (Peter''s testimony at the council). Each repetition serves a different function: establishing the event, defending it to sceptics, and using it as precedent for church policy.'),
('Acts', 10, 'adults', 8, 'What does Cornelius''s character (devout, prayerful, generous, God-fearing) teach about the relationship between pre-conversion piety and saving faith?', 'Cornelius was genuinely pious and his prayers "came up for a memorial before God" (v.4), yet he still needed to hear the gospel and believe in Jesus for salvation (11:14). His piety made him receptive but did not save him — it prepared the soil but only the gospel seed produces salvation. Pre-conversion seeking is real but insufficient without Christ', 'Cornelius was already saved before Peter arrived', 'His good works earned him salvation', 'Pre-conversion piety is irrelevant to God', 'a', 'Acts 10:2,4 and 11:14 — Cornelius was devout, prayerful, and generous, and God heard his prayers. Yet the angel says Peter will "tell thee words, whereby thou and all thy house shall be saved" — implying he was not yet saved. Piety prepared him for the gospel but did not replace it.');

-- ═══ Acts Chapter 11 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Acts', 11, 'kids', 1, 'What did the Jewish believers in Jerusalem criticise Peter for?', 'Going into the home of uncircumcised Gentiles and eating with them', 'Not praying enough', 'Spending too much money', 'Travelling too far from Jerusalem', 'a', 'Acts 11:2-3 — "And when Peter was come up to Jerusalem, they that were of the circumcision contended with him, Saying, Thou wentest in to men uncircumcised, and didst eat with them."'),
('Acts', 11, 'kids', 2, 'In what city were believers first called Christians?', 'Antioch', 'Jerusalem', 'Rome', 'Athens', 'a', 'Acts 11:26 — "And the disciples were called Christians first in Antioch."'),
('Acts', 11, 'kids', 3, 'What did the believers in Antioch do when they heard about a famine?', 'They sent relief to the brethren in Judaea, each according to their ability', 'They moved to another country', 'They stored food only for themselves', 'They asked Rome for help', 'a', 'Acts 11:29 — "Then the disciples, every man according to his ability, determined to send relief unto the brethren which dwelt in Judaea."'),
-- Teens
('Acts', 11, 'teens', 1, 'How did Peter defend his visit to Cornelius?', 'He told the whole story from beginning to end — the vision, the Spirit''s command, and how the Holy Ghost fell on the Gentiles — and asked "What was I, that I could withstand God?"', 'He refused to explain himself', 'He apologised and said he would not do it again', 'He said Cornelius was really a Jew', 'a', 'Acts 11:4-17 — Peter rehearsed the matter in order, concluding: "Forasmuch then as God gave them the like gift as he did unto us, who believed on the Lord Jesus Christ; what was I, that I could withstand God?"'),
('Acts', 11, 'teens', 2, 'How did the Jerusalem believers respond after hearing Peter''s explanation?', 'They held their peace and glorified God, saying "Then hath God also to the Gentiles granted repentance unto life"', 'They expelled Peter from the church', 'They decided Gentiles needed circumcision first', 'They ignored Peter completely', 'a', 'Acts 11:18 — "When they heard these things, they held their peace, and glorified God, saying, Then hath God also to the Gentiles granted repentance unto life."'),
('Acts', 11, 'teens', 3, 'Who was sent by the Jerusalem church to encourage the believers in Antioch?', 'Barnabas, who was glad when he saw the grace of God and exhorted them all to cleave unto the Lord', 'Peter, who established a new church there', 'James, who laid down the law', 'John, who wrote them a letter', 'a', 'Acts 11:22-23 — "They sent forth Barnabas, that he should go as far as Antioch. Who, when he came, and had seen the grace of God, was glad, and exhorted them all, that with purpose of heart they would cleave unto the Lord."'),
('Acts', 11, 'teens', 4, 'Who did Barnabas go and find to help him in the work at Antioch?', 'Saul, whom he brought from Tarsus — and they taught together for a whole year', 'Peter, from Jerusalem', 'John Mark, from Antioch', 'Timothy, from Lystra', 'a', 'Acts 11:25-26 — "Then departed Barnabas to Tarsus, for to seek Saul: And when he had found him, he brought him unto Antioch. And it came to pass, that a whole year they assembled themselves with the church, and taught much people."'),
('Acts', 11, 'teens', 5, 'What prophet predicted the great famine that happened under Emperor Claudius?', 'Agabus, who signified by the Spirit that there would be a great dearth throughout all the world', 'Isaiah, who wrote about it centuries earlier', 'Elijah, who appeared in a vision', 'John the Baptist, who had warned about it', 'a', 'Acts 11:28 — "And there stood up one of them named Agabus, and signified by the Spirit that there should be great dearth throughout all the world: which came to pass in the days of Claudius Caesar."'),
-- Adults
('Acts', 11, 'adults', 1, 'What does the Jerusalem church''s initial reaction to Peter (11:2-3) reveal about the challenge of Gentile inclusion?', 'Even after Pentecost, the Jerusalem believers'' instinct was to maintain Jewish-Gentile boundaries. Their objection was not about conversion but about table fellowship — eating with uncircumcised Gentiles violated purity norms. This shows that theological breakthroughs (God accepts Gentiles) must also become practical realities (Jews and Gentiles eat together)', 'The Jerusalem church was immediately supportive', 'Table fellowship was unimportant', 'Peter was criticised for the wrong reasons', 'a', 'Acts 11:2-3 — "They of the circumcision contended with him, Saying, Thou wentest in to men uncircumcised, and didst eat with them." The issue is table fellowship — the social expression of spiritual inclusion. This same tension erupts again in Galatians 2:11-14. Theology must reshape practice.'),
('Acts', 11, 'adults', 2, 'What is the significance of Antioch becoming the new centre of Gentile Christianity?', 'Antioch (third-largest city in the Roman Empire) becomes the base for Gentile mission, shifting the church''s centre of gravity from Jerusalem. Its mixed Jewish-Gentile church models the new community that transcends ethnic boundaries. From Antioch, the missionary journeys launch (13:1-3). It represents the church becoming truly universal', 'Antioch was unimportant in early Christianity', 'Jerusalem remained the sole centre throughout', 'Antioch was chosen for its climate', 'a', 'Acts 11:19-26 — Scattered believers preach to "Grecians" (Hellenistic Gentiles) in Antioch. The church grows, Barnabas and Saul teach for a year, and "the disciples were called Christians first in Antioch." The shift from Jerusalem to Antioch mirrors the shift from Jewish to Gentile mission.'),
('Acts', 11, 'adults', 3, 'What does the name "Christian" (Christianos) tell us about how the early church was perceived?', 'The suffix "-ianos" was used for followers of a political leader (like Caesariani, Herodiani). Being called "Christians" meant outsiders saw the disciples as followers/partisans of Christos (Messiah/Christ). The name reflects that the early church''s identity was so defined by Christ that pagans coined a political-style label for them', 'The disciples named themselves Christians', 'The term was a Jewish insult', 'It was an official Roman designation', 'a', 'Acts 11:26 — "The disciples were called Christians first in Antioch." The passive "were called" (chrematisai) may indicate divine designation or public labelling. The "-ianos" suffix (Latin formation) suggests Gentile pagans coined it — identifying the movement by its allegiance to Christos.'),
('Acts', 11, 'adults', 4, 'How does the Antioch church''s famine relief (11:27-30) establish a pattern for inter-church relationships?', 'The Antioch church''s collection for Jerusalem establishes reciprocity: Jerusalem gave Antioch the gospel; Antioch gives Jerusalem material support. This pattern of spiritual and material sharing across ethnic and geographic lines becomes central to Paul''s theology (Romans 15:26-27) and practice (the great collection, 2 Corinthians 8-9)', 'It was a one-time emergency with no lasting impact', 'Antioch was required to pay tribute to Jerusalem', 'The relief was never actually delivered', 'a', 'Acts 11:29-30 — "Then the disciples, every man according to his ability, determined to send relief unto the brethren which dwelt in Judaea." This voluntary, proportional giving establishes the principle Paul later develops: "If the Gentiles have been made partakers of their spiritual things, their duty is also to minister unto them in carnal things" (Romans 15:27).'),
('Acts', 11, 'adults', 5, 'What does "Then hath God also to the Gentiles granted repentance unto life" (11:18) imply about the nature of repentance?', 'The Jerusalem church recognises repentance as a divine gift — God "grants" it, not merely demands it. Repentance unto life is something God gives (cf. 2 Timothy 2:25). This theological insight shapes the church''s understanding: Gentile conversion is not human achievement but divine bestowal, just as with Jewish conversion', 'Repentance is purely a human decision', 'Only Jews can truly repent', 'Repentance is unnecessary for Gentiles', 'a', 'Acts 11:18 — "Then hath God also to the Gentiles granted repentance unto life." The verb "granted" (edoken = gave) presents repentance as God''s gift. This matches Acts 5:31 ("to give repentance to Israel") and 2 Timothy 2:25 ("if God peradventure will give them repentance"). Salvation is grace-initiated from start to finish.'),
('Acts', 11, 'adults', 6, 'What role does Barnabas play in the development of Pauline ministry?', 'Barnabas is the catalyst for Paul''s re-entry into active ministry — he sought Saul out in Tarsus (where Saul had been for perhaps a decade) and brought him to Antioch. Without Barnabas''s initiative, Paul might have remained in obscurity. Barnabas''s gift of encouragement and willingness to share leadership prepared the way for the Gentile mission', 'Barnabas was Paul''s superior throughout Acts', 'Paul would have succeeded without any help', 'Barnabas hindered Paul''s ministry', 'a', 'Acts 11:25-26 — "Then departed Barnabas to Tarsus, for to seek Saul." Barnabas had already vouched for Saul in Jerusalem (9:27). Now he retrieves him from Tarsus and gives him a year of co-ministry in Antioch. Barnabas consistently uses his reputation to open doors for others.'),
('Acts', 11, 'adults', 7, 'How do the prophets mentioned in 11:27-28 function in the early church?', 'New Testament prophets like Agabus provided Spirit-prompted revelation about future events and current situations. They served alongside teachers (cf. 13:1) as part of the church''s leadership. Agabus''s famine prediction led to concrete action — prophecy functioned not merely as prediction but as a catalyst for practical ministry and preparation', 'Prophets had no role in the early church', 'Agabus was the only prophet', 'Prophets only repeated Old Testament passages', 'a', 'Acts 11:27-28 — "And in these days came prophets from Jerusalem unto Antioch. And there stood up one of them named Agabus, and signified by the Spirit that there should be great dearth." Agabus reappears in 21:10-11. NT prophets complemented apostles and teachers, providing Spirit-directed insight that prompted practical response.'),
('Acts', 11, 'adults', 8, 'What does the phrase "the hand of the Lord was with them" (11:21) signify about the Antioch mission?', 'The "hand of the Lord" is an Old Testament expression for God''s active power and favour (cf. 1 Kings 18:46, Ezra 7:9). Applied to the Antioch mission, it attributes the church''s growth to divine action, not human strategy. "A great number believed, and turned unto the Lord" — the turning was empowered by God''s hand, not merely by human eloquence', 'The phrase is a casual expression with no deep meaning', 'It refers to a literal hand appearing', 'Only the apostles experienced God''s hand', 'a', 'Acts 11:21 — "And the hand of the Lord was with them: and a great number believed, and turned unto the Lord." The OT "hand of the Lord" denotes divine power in action (Exodus 9:3, Isaiah 59:1). Luke attributes Antioch''s explosive growth not to methodology but to divine empowerment.');

-- ═══ Acts Chapter 12 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Acts', 12, 'kids', 1, 'What happened to Peter when he was in prison?', 'An angel came at night, woke him up, and led him out of prison while the chains fell off his hands', 'He dug a tunnel and escaped', 'The guards let him go', 'He climbed over the prison wall', 'a', 'Acts 12:7-10 — "And, behold, the angel of the Lord came upon him, and a light shined in the prison: and he smote Peter on the side, and raised him up, saying, Arise up quickly. And his chains fell off from his hands."'),
('Acts', 12, 'kids', 2, 'Who was praying for Peter while he was in prison?', 'The church was praying without ceasing for him', 'No one was praying', 'Only his family prayed', 'The Roman soldiers prayed', 'a', 'Acts 12:5 — "Peter therefore was kept in prison: but prayer was made without ceasing of the church unto God for him."'),
('Acts', 12, 'kids', 3, 'What did the servant girl Rhoda do when she heard Peter''s voice at the gate?', 'She was so happy that she forgot to open the gate and ran to tell the others', 'She opened the gate right away', 'She screamed and ran away', 'She did not recognise his voice', 'a', 'Acts 12:13-14 — "And as Peter knocked at the door of the gate, a damsel came to hearken, named Rhoda. And when she knew Peter''s voice, she opened not the gate for gladness, but ran in, and told how Peter stood before the gate."'),
-- Teens
('Acts', 12, 'teens', 1, 'What did King Herod (Agrippa I) do to the apostle James?', 'He killed James the brother of John with the sword', 'He put James in prison for a year', 'He banished James from Jerusalem', 'He fined James a large sum of money', 'a', 'Acts 12:1-2 — "Now about that time Herod the king stretched forth his hands to vex certain of the church. And he killed James the brother of John with the sword."'),
('Acts', 12, 'teens', 2, 'Why did Herod arrest Peter after killing James?', 'Because he saw it pleased the Jews, and he wanted to gain more popularity by persecuting Christians', 'Peter had committed a crime against Rome', 'Peter owed Herod money', 'The apostles asked Herod to arrest Peter', 'a', 'Acts 12:3 — "And because he saw it pleased the Jews, he proceeded further to take Peter also."'),
('Acts', 12, 'teens', 3, 'How was Peter guarded in prison?', 'He was chained between two soldiers, with guards at the door — four squads of four soldiers each', 'He was in an unlocked room', 'One guard watched the door', 'He was in chains in a deep dungeon alone', 'a', 'Acts 12:4,6 — "Delivered him to four quaternions of soldiers to keep him... Peter was sleeping between two soldiers, bound with two chains: and the keepers before the door kept the prison."'),
('Acts', 12, 'teens', 4, 'What happened to King Herod when the people shouted that his voice was the voice of a god?', 'An angel of the Lord smote him because he gave not God the glory, and he was eaten of worms and died', 'He became the most powerful ruler in the world', 'He was immediately crowned emperor', 'Nothing happened and he lived many more years', 'a', 'Acts 12:22-23 — "And the people gave a shout, saying, It is the voice of a god, and not of a man. And immediately the angel of the Lord smote him, because he gave not God the glory: and he was eaten of worms, and gave up the ghost."'),
('Acts', 12, 'teens', 5, 'What did the believers say when Rhoda told them Peter was at the gate?', 'They said she was mad — and when she kept insisting, they said it must be his angel', 'They immediately ran to open the gate', 'They did not believe because they were not praying', 'They asked her to bring Peter inside', 'a', 'Acts 12:15 — "And they said unto her, Thou art mad. But she constantly affirmed that it was even so. Then said they, It is his angel."'),
-- Adults
('Acts', 12, 'adults', 1, 'Why does Luke juxtapose James''s martyrdom and Peter''s miraculous deliverance?', 'The contrast demonstrates that God''s sovereignty does not guarantee identical outcomes for all believers — James dies but Peter is delivered. Both were faithful apostles; the difference in outcome is divine prerogative, not a measure of faith or faithfulness. Luke shows that God''s purposes sometimes include martyrdom and sometimes include deliverance, and both are within His sovereign will', 'Luke is showing that Peter was more faithful than James', 'James''s death was a mistake by God', 'Peter escaped through his own cleverness', 'a', 'Acts 12:2,11 — James killed, Peter delivered. Luke offers no explanation for the different outcomes. This mirrors Hebrews 11:33-38 where some by faith "escaped the edge of the sword" and others by faith "were slain with the sword." Faith does not determine outcome; God does.'),
('Acts', 12, 'adults', 2, 'What does the church praying "without ceasing" while Peter was in prison teach about prayer and God''s sovereignty?', 'The church prayed earnestly yet were shocked when their prayer was answered (v.15-16). This reveals that persistent prayer and imperfect faith can coexist — God answers prayer even when the pray-ers doubt. Their astonishment at the answer does not invalidate the prayer. God''s faithfulness exceeds human faith', 'The church''s prayer had no effect', 'Perfect faith is required for answered prayer', 'The angel would have come without prayer', 'a', 'Acts 12:5,15-16 — "Prayer was made without ceasing of the church unto God for him." Yet when Peter appears, "they said unto her, Thou art mad." The irony: they pray for deliverance but cannot believe it when it comes. God answers prayer despite the weakness of the pray-ers'' faith.'),
('Acts', 12, 'adults', 3, 'What does Herod Agrippa I''s death by divine judgment reveal about the theme of opposition to God in Acts?', 'Herod represents the ultimate futility of opposing God — he killed James, imprisoned Peter, and accepted divine worship. His gruesome death contrasts with the church''s growth: "But the word of God grew and multiplied" (v.24). The pattern throughout Acts: opponents of the gospel are defeated while the word advances', 'Herod''s death was coincidental', 'God does not judge political leaders', 'Herod was punished for a minor offence', 'a', 'Acts 12:23-24 — Herod "gave not God the glory: and he was eaten of worms, and gave up the ghost. But the word of God grew and multiplied." The juxtaposition is deliberate: the persecutor dies, the word lives. Josephus confirms Herod Agrippa''s sudden death (Antiquities 19.8.2), corroborating Luke.'),
('Acts', 12, 'adults', 4, 'What is the narrative significance of Peter''s escape echoing the Passover/Exodus?', 'The timing is during Passover (v.3-4, "after Easter" = after Passover). Peter is chained between soldiers (like Israel in Egypt), delivered at night by an angel (like the Passover angel), passes through gates that open of their own accord (like the Red Sea), and is freed from a tyrant (Herod, like Pharaoh). Luke patterns Peter''s deliverance on the Exodus', 'The Passover timing is coincidental', 'There are no Exodus parallels', 'Only the timing connects them', 'a', 'Acts 12:3-11 — Passover context (v.3-4), night deliverance (v.6), angel strikes (v.7, like the death angel), chains fall (v.7, like bondage broken), iron gate opens automatically (v.10, like the sea parting). Luke''s Exodus typology shows God''s delivering power is the same across generations.'),
('Acts', 12, 'adults', 5, 'What does Peter''s initial confusion ("he wist not that it was true which was done by the angel; but thought he saw a vision," v.9) add to the narrative?', 'Peter''s confusion humanises the miraculous — even the apostle cannot immediately distinguish between vision and reality. It emphasises the angel''s initiative: Peter is passive throughout the escape, simply following instructions. The deliverance is entirely divine — Peter contributes nothing but obedience. This underscores that salvation is God''s work', 'Peter was too sleepy to understand', 'Angels always cause confusion', 'Peter frequently confused visions with reality', 'a', 'Acts 12:9,11 — Peter follows the angel''s commands mechanically, unable to distinguish vision from reality. Only outside does he say: "Now I know of a surety, that the Lord hath sent his angel, and hath delivered me." The passive apostle and active angel dramatise divine initiative.'),
('Acts', 12, 'adults', 6, 'How does Acts 12:24 function as a structural marker in the book?', 'This is one of Luke''s progress reports (cf. 6:7, 9:31, 16:5, 19:20, 28:31) that mark major narrative transitions. "The word of God grew and multiplied" concludes the Jerusalem section of Acts. After this, the focus shifts to the Antioch church and Paul''s missionary journeys. The verb "grew" (euxanen) echoes the parable of the sower — the word is seed that cannot be suppressed', 'Verse 24 is an insignificant summary', 'It only applies to Jerusalem', 'Luke accidentally repeated himself', 'a', 'Acts 12:24 — "But the word of God grew and multiplied." This progress report closes the first half of Acts (Jerusalem-centred, Peter-focused). Chapter 13 begins the second half (Antioch-centred, Paul-focused). The word''s growth contrasts with Herod''s death — the persecutor falls, the gospel advances.'),
('Acts', 12, 'adults', 7, 'What does the believers'' suggestion that "it is his angel" (12:15) reveal about early Jewish-Christian belief?', 'The response reflects a Jewish belief in guardian angels who could appear in the likeness of the person they guarded (cf. Matthew 18:10). The believers found it easier to believe Peter''s angel appeared than that Peter himself was freed — revealing both their angel theology and their limited expectations of God''s power despite their own prayers', 'They literally thought Peter was dead and his ghost appeared', 'Guardian angel beliefs were pagan, not Jewish', 'They were joking about Rhoda''s claim', 'a', 'Acts 12:15 — "It is his angel." Jewish angelology included the concept of personal guardian angels (cf. Matthew 18:10, "their angels do always behold the face of my Father"). The believers'' explanation reveals their theological framework: they believed in angels more readily than in answered prayer.'),
('Acts', 12, 'adults', 8, 'How does Acts 12 close the "Peter section" of Acts and transition to the "Paul section"?', 'After Peter''s deliverance and departure to "another place" (v.17), he largely disappears from Acts (appearing only at the council in chapter 15). Herod''s death removes the primary Jewish persecutor. Barnabas and Saul return from their relief mission (v.25). The stage is set for the Antioch church to commission the first missionary journey — the gospel goes to the Gentile world', 'Peter remains the central figure throughout Acts', 'Acts 12 has no transitional function', 'Paul was already the main character', 'a', 'Acts 12:17,25 — Peter goes to "another place" (likely outside Jerusalem, perhaps Antioch or Rome). Barnabas and Saul return to Antioch with John Mark. Chapter 13 opens with the Antioch church sending Barnabas and Saul. Luke masterfully transitions from Peter''s story to Paul''s story at the hinge of Acts.');
