-- ============================================================================
-- Quiz Seed: 2 Corinthians — Part 2 (Chapters 8–13)
-- 3 difficulties × 6 chapters = 96 total questions
--   kids:   3 per chapter  = 18
--   teens:  5 per chapter  = 30
--   adults: 8 per chapter  = 48
-- ============================================================================

-- ═══════════════ CHAPTERS 8–10 ═══════════════

-- ═══ 2 Corinthians Chapter 8 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Corinthians', 8, 'kids', 1, 'What did the churches in Macedonia do even though they were poor?', 'They gave generously to help other Christians', 'They kept all their money for themselves', 'They asked Paul for more money', 'They complained about being poor', 'a', '2 Corinthians 8:2 — "How that in a great trial of affliction the abundance of their joy and their deep poverty abounded unto the riches of their liberality."'),
('2 Corinthians', 8, 'kids', 2, 'What did Jesus do for us even though he was rich?', 'He became poor so that we could become rich', 'He stayed rich and gave us gold', 'He kept his riches in heaven', 'He asked us to make him richer', 'a', '2 Corinthians 8:9 — "For ye know the grace of our Lord Jesus Christ, that, though he was rich, yet for your sakes he became poor, that ye through his poverty might be rich."'),
('2 Corinthians', 8, 'kids', 3, 'Who did Paul send to help the Corinthians with their giving?', 'Titus', 'Peter', 'James', 'John', 'a', '2 Corinthians 8:6 — "Insomuch that we desired Titus, that as he had begun, so he would also finish in you the same grace also."'),
-- Teens
('2 Corinthians', 8, 'teens', 1, 'How did the Macedonian churches give beyond Paul''s expectation?', 'They first gave their own selves to the Lord, and unto Paul by the will of God — and gave beyond their power willingly', 'They gave exactly what was requested', 'They gave only after much persuasion', 'They gave reluctantly and with complaints', 'a', '2 Corinthians 8:3-5 — "For to their power, I bear record, yea, and beyond their power they were willing of themselves... and this they did, not as we hoped, but first gave their own selves to the Lord, and unto us by the will of God."'),
('2 Corinthians', 8, 'teens', 2, 'What seven things does Paul say the Corinthians abound in?', 'Faith, utterance, knowledge, all diligence, love — Paul urges them to abound in this grace of giving also', 'Gold, silver, land, houses, and servants', 'Miracles, signs, wonders, and healings', 'Political power, social status, and fame', 'a', '2 Corinthians 8:7 — "Therefore, as ye abound in every thing, in faith, and utterance, and knowledge, and in all diligence, and in your love to us, see that ye abound in this grace also."'),
('2 Corinthians', 8, 'teens', 3, 'What principle does Paul give about willing giving?', 'If there be first a willing mind, it is accepted according to that a man hath, and not according to that he hath not', 'Give only if you can afford it after all your needs', 'Give everything you have with nothing left', 'Give only what is specifically demanded', 'a', '2 Corinthians 8:12 — "For if there be first a willing mind, it is accepted according to that a man hath, and not according to that he hath not."'),
('2 Corinthians', 8, 'teens', 4, 'What does Paul say about equality in giving?', 'That there be equality — your abundance now should supply their want, and their abundance may supply your want', 'The rich should give everything to the poor', 'Everyone should give exactly the same amount', 'Only the wealthiest members should give', 'a', '2 Corinthians 8:14 — "But by an equality, that now at this time your abundance may be a supply for their want, that their abundance also may be a supply for your want: that there may be equality."'),
('2 Corinthians', 8, 'teens', 5, 'What Old Testament example does Paul cite about equality?', 'He that had gathered much had nothing over, and he that had gathered little had no lack — referring to the manna', 'The division of the promised land', 'The building of Solomon''s temple', 'The offering of Abraham''s tithe', 'a', '2 Corinthians 8:15 — "As it is written, He that had gathered much had nothing over; and he that had gathered little had no lack." This quotes Exodus 16:18 about gathering manna.'),
-- Adults
('2 Corinthians', 8, 'adults', 1, 'What does Paul reveal about the grace of God bestowed on the Macedonian churches?', 'In a great trial of affliction, the abundance of their joy and deep poverty abounded unto the riches of their liberality', 'God gave them great financial prosperity', 'They received miraculous provision of food', 'They were exempted from the Roman tax', 'a', '2 Corinthians 8:1-2 — "Moreover, brethren, we do you to wit of the grace of God bestowed on the churches of Macedonia; How that in a great trial of affliction the abundance of their joy and their deep poverty abounded unto the riches of their liberality."'),
('2 Corinthians', 8, 'adults', 2, 'What is the Christological basis for generous giving in verse 9?', 'The grace of our Lord Jesus Christ: though he was rich, yet for your sakes he became poor, that ye through his poverty might be rich', 'The example of Abraham tithing to Melchizedek', 'The command of Moses regarding temple offerings', 'The parable of the talents', 'a', '2 Corinthians 8:9 — "For ye know the grace of our Lord Jesus Christ, that, though he was rich, yet for your sakes he became poor, that ye through his poverty might be rich."'),
('2 Corinthians', 8, 'adults', 3, 'What does Paul say about the Corinthians'' readiness a year ago?', 'They were the first to begin, not only to do but also to be forward (willing) a year ago — now he urges them to complete what they started', 'They had already completed the collection', 'They had never shown any interest in giving', 'They had given more than any other church', 'a', '2 Corinthians 8:10-11 — "For this is expedient for you, who have begun before, not only to do, but also to be forward a year ago. Now therefore perform the doing of it."'),
('2 Corinthians', 8, 'adults', 4, 'How does Paul describe Titus'' role in the collection?', 'Titus accepted the exhortation and being more forward went of his own accord unto them — he is Paul''s partner and fellowhelper', 'Titus reluctantly agreed to go', 'Titus refused the assignment', 'Titus went only because Paul commanded him', 'a', '2 Corinthians 8:17,23 — "For indeed he accepted the exhortation; but being more forward, of his own accord he went unto you... he is my partner and fellowhelper concerning you."'),
('2 Corinthians', 8, 'adults', 5, 'Who is the brother "whose praise is in the gospel throughout all the churches"?', 'An unnamed brother chosen by the churches to travel with Paul, whose praise in the gospel is widely known', 'Luke, the physician and author', 'Barnabas, Paul''s former companion', 'Apollos, the eloquent teacher', 'a', '2 Corinthians 8:18-19 — "And we have sent with him the brother, whose praise is in the gospel throughout all the churches; And not that only, but who was also chosen of the churches to travel with us."'),
('2 Corinthians', 8, 'adults', 6, 'Why does Paul take precautions about the administration of the gift?', 'Avoiding that any man should blame them in this abundance — providing for honest things not only before the Lord but also before men', 'To ensure the gift reaches the maximum amount', 'To track each individual''s donation', 'To create a public record for tax purposes', 'a', '2 Corinthians 8:20-21 — "Avoiding this, that no man should blame us in this abundance which is administered by us: Providing for honest things, not only in the sight of the Lord, but also in the sight of men."'),
('2 Corinthians', 8, 'adults', 7, 'What does Paul call the messengers of the churches?', 'The messengers of the churches and the glory of Christ', 'The servants of the apostles', 'The rulers of the congregations', 'The prophets of the new covenant', 'a', '2 Corinthians 8:23 — "Whether any do enquire of Titus, he is my partner and fellowhelper concerning you: or our brethren be enquired of, they are the messengers of the churches, and the glory of Christ."'),
('2 Corinthians', 8, 'adults', 8, 'What proof does Paul ask the Corinthians to show?', 'The proof of their love and of Paul''s boasting on their behalf before the churches', 'The proof of their theological knowledge', 'The proof of their spiritual gifts', 'The proof of their church attendance', 'a', '2 Corinthians 8:24 — "Wherefore shew ye to them, and before the churches, the proof of your love, and of our boasting on your behalf."');

-- ═══ 2 Corinthians Chapter 9 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Corinthians', 9, 'kids', 1, 'What kind of giver does God love?', 'A cheerful giver', 'A rich giver', 'A sad giver', 'A forced giver', 'a', '2 Corinthians 9:7 — "God loveth a cheerful giver."'),
('2 Corinthians', 9, 'kids', 2, 'If you plant a lot of seeds, what happens?', 'You get a big harvest — he which soweth bountifully shall reap also bountifully', 'You get nothing at all', 'The seeds all die', 'You get fewer plants', 'a', '2 Corinthians 9:6 — "He which soweth bountifully shall reap also bountifully."'),
('2 Corinthians', 9, 'kids', 3, 'What special gift from God can we never fully describe?', 'His unspeakable gift (Jesus)', 'A box of gold', 'A beautiful garden', 'A brand new house', 'a', '2 Corinthians 9:15 — "Thanks be unto God for his unspeakable gift."'),
-- Teens
('2 Corinthians', 9, 'teens', 1, 'Why did Paul send the brethren ahead to Corinth?', 'That their bounty might be ready as a matter of bounty and not as of covetousness', 'To start new churches in the area', 'To collect payment for Paul''s expenses', 'To investigate reports of false teaching', 'a', '2 Corinthians 9:5 — "Therefore I thought it necessary to exhort the brethren, that they would go before unto you, and make up beforehand your bounty... that the same might be ready, as a matter of bounty, and not as of covetousness."'),
('2 Corinthians', 9, 'teens', 2, 'How should each person decide what to give?', 'Every man according as he purposeth in his heart, not grudgingly or of necessity, for God loveth a cheerful giver', 'According to a fixed percentage required by the church', 'Based on what others are giving', 'Only what the apostles demand', 'a', '2 Corinthians 9:7 — "Every man according as he purposeth in his heart, so let him give; not grudgingly, or of necessity: for God loveth a cheerful giver."'),
('2 Corinthians', 9, 'teens', 3, 'What does Paul say God is able to make abound toward believers?', 'All grace — that ye, always having all sufficiency in all things, may abound to every good work', 'Only financial blessings', 'Only spiritual gifts', 'Only physical health', 'a', '2 Corinthians 9:8 — "And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work."'),
('2 Corinthians', 9, 'teens', 4, 'What does the Corinthians'' generosity cause others to do?', 'Glorify God — their generosity causes thanksgiving to God and proves their obedience to the gospel', 'Become jealous of the Corinthians', 'Leave their own churches', 'Start competing with each other', 'a', '2 Corinthians 9:13 — "Whiles by the experiment of this ministration they glorify God for your professed subjection unto the gospel of Christ, and for your liberal distribution unto them, and unto all men."'),
('2 Corinthians', 9, 'teens', 5, 'What is God''s "unspeakable gift"?', 'The gift of Jesus Christ — a gift so wonderful it cannot be fully expressed in words', 'A treasure chest of gold', 'The ability to speak in tongues', 'A special prayer language', 'a', '2 Corinthians 9:15 — "Thanks be unto God for his unspeakable gift." This refers to the supreme gift of God''s Son.'),
-- Adults
('2 Corinthians', 9, 'adults', 1, 'What does Paul say about the Corinthians'' readiness to give?', 'He boasted to Macedonia that Achaia (Corinth) was ready a year ago, and their zeal provoked very many', 'The Corinthians had already completed the collection', 'The Corinthians showed no interest in giving', 'The Corinthians were the least generous church', 'a', '2 Corinthians 9:2 — "For I know the forwardness of your mind, for which I boast of you to them of Macedonia, that Achaia was ready a year ago; and your zeal hath provoked very many."'),
('2 Corinthians', 9, 'adults', 2, 'What agricultural principle does Paul apply to giving?', 'He which soweth sparingly shall reap also sparingly; and he which soweth bountifully shall reap also bountifully', 'Those who sow will always reap exactly the same amount', 'Sowing and reaping have no connection', 'Only professional farmers can reap a harvest', 'a', '2 Corinthians 9:6 — "But this I say, He which soweth sparingly shall reap also sparingly; and he which soweth bountifully shall reap also bountifully."'),
('2 Corinthians', 9, 'adults', 3, 'What Old Testament passage does Paul reference about God''s provision?', 'He hath dispersed abroad; he hath given to the poor: his righteousness remaineth for ever — quoting Psalm 112:9', 'The provision of manna in the wilderness', 'The feeding of Elijah by ravens', 'The multiplication of the widow''s oil', 'a', '2 Corinthians 9:9 — "As it is written, He hath dispersed abroad; he hath given to the poor: his righteousness remaineth for ever." This quotes Psalm 112:9.'),
('2 Corinthians', 9, 'adults', 4, 'What does Paul say about God supplying seed to the sower?', 'He that ministereth seed to the sower both minister bread for your food, and multiply your seed sown, and increase the fruits of your righteousness', 'God gives seed only to wealthy farmers', 'Seed is always in limited supply', 'Sowers must provide their own seed', 'a', '2 Corinthians 9:10 — "Now he that ministereth seed to the sower both minister bread for your food, and multiply your seed sown, and increase the fruits of your righteousness."'),
('2 Corinthians', 9, 'adults', 5, 'What is the purpose of being enriched in every thing?', 'Being enriched in every thing to all bountifulness, which causeth through us thanksgiving to God', 'To accumulate personal wealth', 'To gain social status in the church', 'To prove one''s spiritual maturity', 'a', '2 Corinthians 9:11 — "Being enriched in every thing to all bountifulness, which causeth through us thanksgiving to God."'),
('2 Corinthians', 9, 'adults', 6, 'What does Paul say the administration of this service does?', 'It not only supplieth the want of the saints but is abundant also by many thanksgivings unto God', 'It creates division in the church', 'It burdens the wealthy members', 'It causes jealousy among the recipients', 'a', '2 Corinthians 9:12 — "For the administration of this service not only supplieth the want of the saints, but is abundant also by many thanksgivings unto God."'),
('2 Corinthians', 9, 'adults', 7, 'What do the recipients pray for regarding the Corinthians?', 'They long after the Corinthians and pray for them because of the exceeding grace of God in them', 'They demand more financial support', 'They criticise the Corinthians'' doctrine', 'They request the Corinthians visit them', 'a', '2 Corinthians 9:14 — "And by their prayer for you, which long after you for the exceeding grace of God in you."'),
('2 Corinthians', 9, 'adults', 8, 'How does Paul describe the "all sufficiency" God provides?', 'Always having all sufficiency in all things — the Greek word "autarkeia" means contentment and self-sufficiency that comes from God''s provision enabling every good work', 'A bare minimum to survive', 'Unlimited material wealth', 'Only spiritual blessings with no material provision', 'a', '2 Corinthians 9:8 — "And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work."');

-- ═══════════════ CHAPTERS 11–13 ═══════════════

-- ═══ 2 Corinthians Chapter 10 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Corinthians', 10, 'kids', 1, 'What kind of weapons does Paul say Christians use?', 'Not swords or spears — our weapons are mighty through God', 'Swords and shields', 'Bows and arrows', 'Rocks and sticks', 'a', '2 Corinthians 10:4 — "For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds."'),
('2 Corinthians', 10, 'kids', 2, 'What should we bring every thought to obey?', 'Christ — bringing every thought into captivity to the obedience of Christ', 'Our parents only', 'Our own feelings', 'Our best friends', 'a', '2 Corinthians 10:5 — "Bringing into captivity every thought to the obedience of Christ."'),
('2 Corinthians', 10, 'kids', 3, 'Who is the right person to praise you?', 'The Lord — not he that commendeth himself is approved, but whom the Lord commendeth', 'Yourself', 'Your best friend', 'The most popular person', 'a', '2 Corinthians 10:18 — "For not he that commendeth himself is approved, but whom the Lord commendeth."'),
-- Teens
('2 Corinthians', 10, 'teens', 1, 'What are the weapons of our warfare?', 'Not carnal but mighty through God to the pulling down of strong holds', 'Made of the finest Roman steel', 'Only the sword of the Spirit', 'Human arguments and debate skills', 'a', '2 Corinthians 10:4 — "For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds."'),
('2 Corinthians', 10, 'teens', 2, 'What do we cast down with these spiritual weapons?', 'Imaginations, and every high thing that exalteth itself against the knowledge of God', 'Physical fortresses and city walls', 'Enemy armies and their equipment', 'Only personal sins and habits', 'a', '2 Corinthians 10:5 — "Casting down imaginations, and every high thing that exalteth itself against the knowledge of God, and bringing into captivity every thought to the obedience of Christ."'),
('2 Corinthians', 10, 'teens', 3, 'What does Paul say about comparing themselves with others?', 'They that measure themselves by themselves and compare themselves among themselves are not wise', 'Comparison is helpful for growth', 'Christians should always compete with each other', 'Self-comparison is the best motivation', 'a', '2 Corinthians 10:12 — "For we dare not make ourselves of the number, or compare ourselves with some that commend themselves: but they measuring themselves by themselves, and comparing themselves among themselves, are not wise."'),
('2 Corinthians', 10, 'teens', 4, 'What does Paul say about boasting?', 'He that glorieth, let him glory in the Lord — quoting Jeremiah 9:24', 'Boasting about achievements is always good', 'Boasting builds confidence in others', 'Boasting is acceptable for church leaders', 'a', '2 Corinthians 10:17 — "But he that glorieth, let him glory in the Lord."'),
('2 Corinthians', 10, 'teens', 5, 'What does Paul say about his authority from the Lord?', 'The Lord gave him authority for edification (building up) and not for destruction of the Corinthians', 'His authority was unlimited with no boundaries', 'His authority was only over the Corinthian church', 'His authority was given by the Jerusalem council', 'a', '2 Corinthians 10:8 — "For though I should boast somewhat more of our authority, which the Lord hath given us for edification, and not for your destruction, I should not be ashamed."'),
-- Adults
('2 Corinthians', 10, 'adults', 1, 'What accusation did Paul''s opponents make about his presence?', 'His bodily presence is weak and his speech contemptible — but Paul warns that what he is in word by letters when absent, such will he be in deed when present', 'He was too aggressive and intimidating', 'He was too wealthy and arrogant', 'He was too young and inexperienced', 'a', '2 Corinthians 10:10-11 — "For his letters, say they, are weighty and powerful; but his bodily presence is weak, and his speech contemptible. Let such an one think this, that, such as we are in word by letters when we are absent, such will we be also in deed when we are present."'),
('2 Corinthians', 10, 'adults', 2, 'What does Paul say about the measure or rule God has distributed to him?', 'God has distributed to him a measure to reach even unto the Corinthians — he is not overextending himself because he came to them with the gospel of Christ', 'His measure was limited to Jerusalem only', 'His measure covered only the Jewish diaspora', 'His measure excluded the Greek-speaking world', 'a', '2 Corinthians 10:13-14 — "But we will not boast of things without our measure, but according to the measure of the rule which God hath distributed to us, a measure to reach even unto you. For we stretch not ourselves beyond our measure, as though we reached not unto you: for we are come as far as to you also in preaching the gospel of Christ."'),
('2 Corinthians', 10, 'adults', 3, 'What does Paul hope will happen as the Corinthians'' faith increases?', 'He will be enlarged by them according to his rule abundantly, to preach the gospel in regions beyond them', 'They will send him more financial support', 'They will build a larger church building', 'They will stop all contact with other apostles', 'a', '2 Corinthians 10:15-16 — "Not boasting of things without our measure, that is, of other men''s labours; but having hope, when your faith is increased, that we shall be enlarged by you according to our rule abundantly, To preach the gospel in the regions beyond you."'),
('2 Corinthians', 10, 'adults', 4, 'What does Paul say about those who commend themselves?', 'Not he that commendeth himself is approved, but whom the Lord commendeth', 'Self-commendation is always appropriate for leaders', 'Those who commend themselves deserve honour', 'Self-promotion is necessary for effective ministry', 'a', '2 Corinthians 10:18 — "For not he that commendeth himself is approved, but whom the Lord commendeth."'),
('2 Corinthians', 10, 'adults', 5, 'What does "bringing into captivity every thought to the obedience of Christ" mean?', 'Every intellectual and philosophical argument must be submitted to Christ''s lordship — the mind is a battlefield where obedience to Christ must be established', 'Only sinful thoughts need to be controlled', 'Thinking is discouraged for believers', 'Only theological thoughts matter to Christ', 'a', '2 Corinthians 10:5 — "Casting down imaginations, and every high thing that exalteth itself against the knowledge of God, and bringing into captivity every thought to the obedience of Christ."'),
('2 Corinthians', 10, 'adults', 6, 'What does Paul say about not boasting in another man''s line of things?', 'He will not boast of things without his measure or of other men''s labours — he builds on his own apostolic foundation, not another''s', 'He freely takes credit for others'' work', 'He considers all churches equally his', 'He competes with other apostles for credit', 'a', '2 Corinthians 10:15-16 — "Not boasting of things without our measure, that is, of other men''s labours; but having hope... To preach the gospel in the regions beyond you, and not to boast in another man''s line of things made ready to our hand."'),
('2 Corinthians', 10, 'adults', 7, 'By what meekness and gentleness does Paul beseech the Corinthians?', 'By the meekness and gentleness of Christ — though some think Paul is base (bold only in letters, timid in person)', 'By the authority of the Jerusalem council', 'By the power of the Roman government', 'By the traditions of the Pharisees', 'a', '2 Corinthians 10:1 — "Now I Paul myself beseech you by the meekness and gentleness of Christ, who in presence am base among you, but being absent am bold toward you."'),
('2 Corinthians', 10, 'adults', 8, 'What readiness does Paul have regarding disobedience?', 'A readiness to revenge all disobedience when the Corinthians'' obedience is fulfilled — disciplinary action is postponed to give them time to comply', 'Immediate punishment without warning', 'Complete indifference to disobedience', 'A plan to report them to Roman authorities', 'a', '2 Corinthians 10:6 — "And having in a readiness to revenge all disobedience, when your obedience is fulfilled."');

-- ═══ 2 Corinthians Chapter 11 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Corinthians', 11, 'kids', 1, 'Who can disguise himself as an angel of light?', 'Satan', 'Moses', 'Gabriel', 'Michael', 'a', '2 Corinthians 11:14 — "And no marvel; for Satan himself is transformed into an angel of light."'),
('2 Corinthians', 11, 'kids', 2, 'How many times was Paul shipwrecked?', 'Three times', 'One time', 'Five times', 'Never', 'a', '2 Corinthians 11:25 — "Thrice I suffered shipwreck."'),
('2 Corinthians', 11, 'kids', 3, 'Did Paul take money from the Corinthians for preaching?', 'No, he preached the gospel to them freely', 'Yes, he charged a high price', 'Yes, but only a small amount', 'He asked for gold and silver', 'a', '2 Corinthians 11:7 — "Have I committed an offence in abasing myself that ye might be exalted, because I have preached to you the gospel of God freely?"'),
-- Teens
('2 Corinthians', 11, 'teens', 1, 'What does Paul fear about the Corinthians being deceived?', 'As the serpent beguiled Eve through his subtilty, their minds should be corrupted from the simplicity that is in Christ', 'That they will forget how to read Scripture', 'That they will stop attending church', 'That they will move to another city', 'a', '2 Corinthians 11:3 — "But I fear, lest by any means, as the serpent beguiled Eve through his subtilty, so your minds should be corrupted from the simplicity that is in Christ."'),
('2 Corinthians', 11, 'teens', 2, 'What does Paul call the false teachers at Corinth?', 'False apostles, deceitful workers, transforming themselves into the apostles of Christ', 'Honourable leaders with different opinions', 'Well-meaning but misguided teachers', 'Temporary substitutes for Paul', 'a', '2 Corinthians 11:13 — "For such are false apostles, deceitful workers, transforming themselves into the apostles of Christ."'),
('2 Corinthians', 11, 'teens', 3, 'How does Satan disguise himself?', 'Satan himself is transformed into an angel of light — therefore his ministers also transform themselves as ministers of righteousness', 'He appears as a terrifying monster', 'He never disguises himself', 'He only appears as a serpent', 'a', '2 Corinthians 11:14-15 — "And no marvel; for Satan himself is transformed into an angel of light. Therefore it is no great thing if his ministers also be transformed as the ministers of righteousness."'),
('2 Corinthians', 11, 'teens', 4, 'What kinds of dangers did Paul face in his travels?', 'Perils of waters, robbers, his own countrymen, the heathen, the city, the wilderness, the sea, and false brethren', 'Only dangers from wild animals', 'Only dangers from the Roman government', 'He faced no real dangers at all', 'a', '2 Corinthians 11:26 — "In journeyings often, in perils of waters, in perils of robbers, in perils by mine own countrymen, in perils by the heathen, in perils in the city, in perils in the wilderness, in perils in the sea, in perils among false brethren."'),
('2 Corinthians', 11, 'teens', 5, 'What daily burden did Paul carry besides physical suffering?', 'The care of all the churches — who is weak and Paul is not weak? Who is offended and he burns not?', 'The weight of his personal finances', 'The responsibility of running a business', 'The task of writing Roman law', 'a', '2 Corinthians 11:28-29 — "Beside those things that are without, that which cometh upon me daily, the care of all the churches. Who is weak, and I am not weak? who is offended, and I burn not?"'),
-- Adults
('2 Corinthians', 11, 'adults', 1, 'What does Paul say about presenting the Corinthians to Christ?', 'He espoused them to one husband, to present them as a chaste virgin to Christ — jealous with a godly jealousy', 'He wanted them to be independent of Christ', 'He planned for them to follow multiple teachers', 'He had no particular concern for their faithfulness', 'a', '2 Corinthians 11:2 — "For I am jealous over you with godly jealousy: for I have espoused you to one husband, that I may present you as a chaste virgin to Christ."'),
('2 Corinthians', 11, 'adults', 2, 'What does Paul accuse the false teachers of preaching?', 'Another Jesus whom Paul had not preached, another spirit, and another gospel', 'The same gospel with minor variations', 'A complementary message to Paul''s teaching', 'A more advanced version of Paul''s gospel', 'a', '2 Corinthians 11:4 — "For if he that cometh preacheth another Jesus, whom we have not preached, or if ye receive another spirit, which ye have not received, or another gospel, which ye have not accepted, ye might well bear with him."'),
('2 Corinthians', 11, 'adults', 3, 'What does Paul say about being inferior to the "chiefest apostles"?', 'He is not a whit behind the very chiefest apostles — though he be rude in speech, yet not in knowledge', 'He admits he is inferior to them', 'He considers them his superiors in every way', 'He has never met the chiefest apostles', 'a', '2 Corinthians 11:5-6 — "For I suppose I was not a whit behind the very chiefest apostles. But though I be rude in speech, yet not in knowledge."'),
('2 Corinthians', 11, 'adults', 4, 'How did Paul fund his ministry at Corinth?', 'He robbed other churches, taking wages of them to serve the Corinthians, and when in want the brethren from Macedonia supplied him', 'The Corinthians paid him a generous salary', 'He worked as a tentmaker only', 'He received funding from the Roman government', 'a', '2 Corinthians 11:8-9 — "I robbed other churches, taking wages of them, to do you service. And when I was present with you, and wanted, I was chargeable to no man: for that which was lacking to me the brethren which came from Macedonia supplied."'),
('2 Corinthians', 11, 'adults', 5, 'What physical sufferings does Paul catalogue in verses 24-25?', 'Five times forty stripes save one from the Jews; thrice beaten with rods; once stoned; thrice shipwrecked; a night and a day in the deep', 'He was never physically harmed', 'He was imprisoned once and beaten twice', 'He suffered only verbal persecution', 'a', '2 Corinthians 11:24-25 — "Of the Jews five times received I forty stripes save one. Thrice was I beaten with rods, once was I stoned, thrice I suffered shipwreck, a night and a day I have been in the deep."'),
('2 Corinthians', 11, 'adults', 6, 'What additional hardships does Paul list in verse 27?', 'Weariness and painfulness, watchings often, hunger and thirst, fastings often, cold and nakedness', 'Wealth, comfort, and luxurious living', 'Only spiritual struggles and prayer', 'Academic challenges and debate', 'a', '2 Corinthians 11:27 — "In weariness and painfulness, in watchings often, in hunger and thirst, in fastings often, in cold and nakedness."'),
('2 Corinthians', 11, 'adults', 7, 'If Paul must boast, what will he boast of?', 'The things which concern his infirmities (weaknesses)', 'His miraculous powers and signs', 'His education and credentials', 'His many converts and churches', 'a', '2 Corinthians 11:30 — "If I must needs glory, I will glory of the things which concern mine infirmities."'),
('2 Corinthians', 11, 'adults', 8, 'What happened to Paul in Damascus?', 'The governor under Aretas the king kept the city with a garrison to apprehend him, and through a window in a basket was he let down by the wall and escaped', 'He was publicly honoured by the governor', 'He established the largest church in Syria', 'He debated Greek philosophers in the marketplace', 'a', '2 Corinthians 11:32-33 — "In Damascus the governor under Aretas the king kept the city of the Damascenes with a garrison, desirous to apprehend me: And through a window in a basket was I let down by the wall, and escaped his hands."');

-- ═══ 2 Corinthians Chapter 12 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Corinthians', 12, 'kids', 1, 'Where was Paul caught up to in a vision?', 'The third heaven (paradise)', 'The moon', 'A tall mountain', 'A high tower', 'a', '2 Corinthians 12:2 — "I knew a man in Christ above fourteen years ago... such an one caught up to the third heaven."'),
('2 Corinthians', 12, 'kids', 2, 'What did God say when Paul asked for his problem to be removed?', 'My grace is sufficient for thee', 'I will take it away right now', 'You must try harder', 'Ask someone else for help', 'a', '2 Corinthians 12:9 — "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness."'),
('2 Corinthians', 12, 'kids', 3, 'When is Paul strong?', 'When he is weak — for God''s power works best in weakness', 'When he exercises a lot', 'When he eats good food', 'When he has lots of money', 'a', '2 Corinthians 12:10 — "For when I am weak, then am I strong."'),
-- Teens
('2 Corinthians', 12, 'teens', 1, 'What did Paul hear in paradise?', 'Unspeakable words, which it is not lawful for a man to utter', 'A list of future events', 'The names of all the saved', 'Instructions for building a church', 'a', '2 Corinthians 12:4 — "How that he was caught up into paradise, and heard unspeakable words, which it is not lawful for a man to utter."'),
('2 Corinthians', 12, 'teens', 2, 'What was the thorn in the flesh given to Paul?', 'A messenger of Satan to buffet him, lest he should be exalted above measure through the abundance of revelations', 'A physical injury from a shipwreck', 'A difficult church member', 'A Roman imprisonment', 'a', '2 Corinthians 12:7 — "And lest I should be exalted above measure through the abundance of the revelations, there was given to me a thorn in the flesh, the messenger of Satan to buffet me, lest I should be exalted above measure."'),
('2 Corinthians', 12, 'teens', 3, 'How many times did Paul pray for the thorn to be removed?', 'Three times — and the Lord said my grace is sufficient for thee', 'Once and God immediately removed it', 'Seven times and God finally agreed', 'He never prayed about it', 'a', '2 Corinthians 12:8 — "For this thing I besought the Lord thrice, that it might depart from me."'),
('2 Corinthians', 12, 'teens', 4, 'What does Paul take pleasure in because of Christ?', 'Infirmities, reproaches, necessities, persecutions, and distresses — for when I am weak then am I strong', 'Wealth, fame, and earthly success', 'Comfort, ease, and leisure', 'Political power and influence', 'a', '2 Corinthians 12:10 — "Therefore I take pleasure in infirmities, in reproaches, in necessities, in persecutions, in distresses for Christ''s sake: for when I am weak, then am I strong."'),
('2 Corinthians', 12, 'teens', 5, 'What signs proved Paul was truly an apostle?', 'The signs of an apostle were wrought among them — signs, wonders, and mighty deeds', 'A certificate from the Jerusalem church', 'His wealth and social status', 'His Roman citizenship', 'a', '2 Corinthians 12:12 — "Truly the signs of an apostle were wrought among you in all patience, in signs, and wonders, and mighty deeds."'),
-- Adults
('2 Corinthians', 12, 'adults', 1, 'How does Paul describe his heavenly experience?', 'A man in Christ caught up to the third heaven fourteen years ago — whether in the body or out of the body he cannot tell, God knoweth', 'He had a vivid dream about heaven', 'An angel described heaven to him in detail', 'He read about heaven in a prophetic scroll', 'a', '2 Corinthians 12:2-3 — "I knew a man in Christ above fourteen years ago, (whether in the body, I cannot tell; or whether out of the body, I cannot tell: God knoweth;) such an one caught up to the third heaven."'),
('2 Corinthians', 12, 'adults', 2, 'Why was the thorn in the flesh given to Paul?', 'Lest he should be exalted above measure through the abundance of the revelations — a messenger of Satan to buffet him', 'As punishment for persecuting Christians', 'As a test of his physical endurance', 'Because he had committed a specific sin', 'a', '2 Corinthians 12:7 — "And lest I should be exalted above measure through the abundance of the revelations, there was given to me a thorn in the flesh, the messenger of Satan to buffet me."'),
('2 Corinthians', 12, 'adults', 3, 'What is the complete statement of God''s response about the thorn?', 'My grace is sufficient for thee: for my strength is made perfect in weakness', 'I will remove it when you have suffered enough', 'Your faith is not strong enough to overcome it', 'This thorn will make you a better preacher', 'a', '2 Corinthians 12:9 — "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness."'),
('2 Corinthians', 12, 'adults', 4, 'What is Paul''s response to God''s answer about the thorn?', 'Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me', 'He was disappointed and frustrated', 'He immediately stopped praying entirely', 'He sought healing from other sources', 'a', '2 Corinthians 12:9 — "Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me."'),
('2 Corinthians', 12, 'adults', 5, 'What does Paul say about what he will not boast of?', 'He will glory of his infirmities but of himself he will not glory, except in his infirmities — lest any man should think of him above what he sees or hears', 'He will boast freely of all his accomplishments', 'He will boast only of his revelations', 'He has nothing worth boasting about', 'a', '2 Corinthians 12:5-6 — "Of such an one will I glory: yet of myself I will not glory, but in mine infirmities. For though I would desire to glory, I shall not be a fool; for I will say the truth: but now I forbear, lest any man should think of me above that which he seeth me to be, or that he heareth of me."'),
('2 Corinthians', 12, 'adults', 6, 'What does Paul say about how he treated the Corinthians compared to other churches?', 'In what were they inferior to other churches except that Paul himself was not burdensome to them? He asks them to forgive him this wrong', 'He treated them more harshly than other churches', 'He gave them more money than other churches', 'He spent more time with them than any other church', 'a', '2 Corinthians 12:13 — "For what is it wherein ye were inferior to other churches, except it be that I myself was not burdensome to you? forgive me this wrong."'),
('2 Corinthians', 12, 'adults', 7, 'What does Paul say about his upcoming third visit?', 'He will not be burdensome to them, for he seeks not theirs but them — the children ought not to lay up for the parents but the parents for the children', 'He plans to collect a large offering', 'He will demand payment for his preaching', 'He expects them to provide luxury accommodations', 'a', '2 Corinthians 12:14 — "Behold, the third time I am ready to come to you; and I will not be burdensome to you: for I seek not yours, but you: for the children ought not to lay up for the parents, but the parents for the children."'),
('2 Corinthians', 12, 'adults', 8, 'What does Paul fear he may find when he visits Corinth?', 'Debates, envyings, wraths, strifes, backbitings, whisperings, swellings, and tumults — and that God will humble him and he will bewail many who have sinned and not repented', 'A perfect and sinless church', 'A church that has grown very wealthy', 'A church that has forgotten his name', 'a', '2 Corinthians 12:20-21 — "For I fear, lest, when I come, I shall not find you such as I would... lest there be debates, envyings, wraths, strifes, backbitings, whisperings, swellings, tumults."');

-- ═══ 2 Corinthians Chapter 13 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('2 Corinthians', 13, 'kids', 1, 'What does Paul tell the Corinthians to do to check their faith?', 'Examine yourselves whether ye be in the faith', 'Ask a priest to check for them', 'Read a special book about it', 'Wait for a sign from heaven', 'a', '2 Corinthians 13:5 — "Examine yourselves, whether ye be in the faith; prove your own selves."'),
('2 Corinthians', 13, 'kids', 2, 'What does Paul want the Corinthians to be?', 'Perfect (complete) — be of good comfort, be of one mind, live in peace', 'The richest church in the world', 'The biggest church in the world', 'The most famous church in the world', 'a', '2 Corinthians 13:11 — "Finally, brethren, farewell. Be perfect, be of good comfort, be of one mind, live in peace."'),
('2 Corinthians', 13, 'kids', 3, 'Who does Paul say will be with believers?', 'The God of love and peace', 'Only angels', 'Only good people', 'Only rich people', 'a', '2 Corinthians 13:11 — "And the God of love and peace shall be with you."'),
-- Teens
('2 Corinthians', 13, 'teens', 1, 'What Old Testament principle does Paul invoke about witnesses?', 'In the mouth of two or three witnesses shall every word be established', 'One witness is sufficient for all matters', 'No witnesses are needed if the apostle is present', 'Only written testimony is valid', 'a', '2 Corinthians 13:1 — "In the mouth of two or three witnesses shall every word be established." This quotes Deuteronomy 19:15.'),
('2 Corinthians', 13, 'teens', 2, 'What does Paul tell the Corinthians to do about their faith?', 'Examine yourselves whether ye be in the faith; prove your own selves — know ye not that Jesus Christ is in you except ye be reprobates?', 'Let others examine your faith for you', 'Faith cannot be examined or tested', 'Only apostles can verify genuine faith', 'a', '2 Corinthians 13:5 — "Examine yourselves, whether ye be in the faith; prove your own selves. Know ye not your own selves, how that Jesus Christ is in you, except ye be reprobates?"'),
('2 Corinthians', 13, 'teens', 3, 'What four commands does Paul give in his farewell?', 'Be perfect, be of good comfort, be of one mind, live in peace', 'Be wealthy, be powerful, be famous, be feared', 'Be silent, be still, be hidden, be separate', 'Be strong, be brave, be bold, be loud', 'a', '2 Corinthians 13:11 — "Finally, brethren, farewell. Be perfect, be of good comfort, be of one mind, live in peace."'),
('2 Corinthians', 13, 'teens', 4, 'How does Paul tell the Corinthians to greet one another?', 'With an holy kiss', 'With a formal handshake', 'With a bow from a distance', 'With a wave of the hand', 'a', '2 Corinthians 13:12 — "Greet one another with an holy kiss."'),
('2 Corinthians', 13, 'teens', 5, 'What famous blessing does Paul give at the end of this letter?', 'The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all', 'May the force be with you', 'Peace and prosperity to all', 'May your wealth increase forever', 'a', '2 Corinthians 13:14 — "The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen."'),
-- Adults
('2 Corinthians', 13, 'adults', 1, 'What warning does Paul give about his third visit?', 'He will not spare — if he comes again he will not spare those who have sinned, since they seek a proof of Christ speaking in him', 'He will be gentle and overlook all sins', 'He will not visit if they don''t repent first', 'He will send Titus in his place', 'a', '2 Corinthians 13:2 — "I told you before, and foretell you, as if I were present, the second time; and being absent now I write to them which heretofore have sinned, and to all other, that, if I come again, I will not spare."'),
('2 Corinthians', 13, 'adults', 2, 'What does Paul say about Christ''s apparent weakness and power?', 'Though he was crucified through weakness, yet he liveth by the power of God; we also are weak in him but shall live with him by the power of God toward you', 'Christ was never truly weak', 'Christ''s weakness disproves his divinity', 'Power and weakness cannot coexist', 'a', '2 Corinthians 13:4 — "For though he was crucified through weakness, yet he liveth by the power of God. For we also are weak in him, but we shall live with him by the power of God toward you."'),
('2 Corinthians', 13, 'adults', 3, 'What does Paul pray for regarding the Corinthians?', 'That they do no evil — not that Paul should appear approved, but that they should do that which is honest, though Paul be as reprobates', 'That they send him more money', 'That they build a larger church building', 'That they submit to his authority without question', 'a', '2 Corinthians 13:7 — "Now I pray to God that ye do no evil; not that we should appear approved, but that ye should do that which is honest, though we be as reprobates."'),
('2 Corinthians', 13, 'adults', 4, 'What does Paul say about doing anything against the truth?', 'We can do nothing against the truth, but for the truth', 'Truth is relative to each person', 'Truth can be suppressed by authority', 'Truth is whatever the majority believes', 'a', '2 Corinthians 13:8 — "For we can do nothing against the truth, but for the truth."'),
('2 Corinthians', 13, 'adults', 5, 'When is Paul glad about his own weakness?', 'When the Corinthians are strong — he wishes for their perfection (spiritual maturity)', 'When it brings him sympathy', 'When it excuses him from work', 'When it makes others feel better about themselves', 'a', '2 Corinthians 13:9 — "For we are glad, when we are weak, and ye are strong: and this also we wish, even your perfection."'),
('2 Corinthians', 13, 'adults', 6, 'Why does Paul write these things while absent?', 'Lest being present he should use sharpness, according to the power the Lord gave him for edification and not destruction', 'Because he is afraid to confront them in person', 'Because writing is easier than speaking', 'Because the postal service is faster than travel', 'a', '2 Corinthians 13:10 — "Therefore I write these things being absent, lest being present I should use sharpness, according to the power which the Lord hath given me to edification, and not to destruction."'),
('2 Corinthians', 13, 'adults', 7, 'What is the theological significance of the Trinitarian benediction in verse 14?', 'It is one of the clearest Trinitarian formulas in Scripture — attributing grace to Christ, love to God the Father, and communion (fellowship) to the Holy Ghost as three distinct persons in one blessing', 'It is simply a poetic closing with no doctrinal significance', 'It mentions three attributes of one divine person', 'It refers to three separate gods working together', 'a', '2 Corinthians 13:14 — "The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen." This Trinitarian benediction distinctly names all three persons of the Godhead.'),
('2 Corinthians', 13, 'adults', 8, 'What does Paul mean by "examine yourselves whether ye be in the faith"?', 'Believers should conduct honest self-examination to test whether their faith is genuine — not presuming salvation but verifying that Christ is truly in them', 'Only church leaders should examine their faith', 'Self-examination is a sign of weak faith', 'Examination means checking others'' faith', 'a', '2 Corinthians 13:5 — "Examine yourselves, whether ye be in the faith; prove your own selves. Know ye not your own selves, how that Jesus Christ is in you, except ye be reprobates?"');
