-- ============================================================
-- Quiz Seed: Job Chapters 1–10
-- Target table: chapter_quizzes
-- Difficulties: kids (3 Qs), teens (5 Qs), adults (8 Qs)
-- ============================================================

-- ═══════════════════════════════════════════
-- CHAPTERS 1 – 10
-- ═══════════════════════════════════════════

-- ═══ Job Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 1, 'kids', 1, 'Where did Job live?', 'The land of Uz', 'The land of Canaan', 'The land of Egypt', 'The land of Nod', 'a', 'The very first verse tells us: "There was a man in the land of Uz, whose name was Job" (Job 1:1).'),
('Job', 1, 'kids', 2, 'What did Job do every morning for his children?', 'Gave them gifts', 'Offered burnt offerings for them', 'Taught them the law', 'Prayed with them at the altar', 'b', 'Job rose up early in the morning, and offered burnt offerings according to the number of his children (Job 1:5).'),
('Job', 1, 'kids', 3, 'What did Job say after he lost everything?', 'The LORD gave, and the LORD hath taken away', 'I am ruined and destroyed', 'Why hath God done this to me', 'I will seek the LORD no more', 'a', 'Job said, "The LORD gave, and the LORD hath taken away; blessed be the name of the LORD" (Job 1:21).'),
-- Teens
('Job', 1, 'teens', 1, 'How is Job described at the very beginning of the book?', 'Rich and powerful in Egypt', 'Perfect and upright, one that feared God and eschewed evil', 'A prophet and a priest in Israel', 'A warrior and a king in Uz', 'b', 'Job was "perfect and upright, and one that feared God, and eschewed evil" (Job 1:1).'),
('Job', 1, 'teens', 2, 'What did Satan claim was the reason Job feared God?', 'Job was too ignorant to know better', 'God had blessed and protected him with a hedge', 'Job had made a covenant with God', 'Job feared the punishment of death', 'b', 'Satan said, "Hast not thou made an hedge about him...? but put forth thine hand now, and touch all that he hath" (Job 1:10-11).'),
('Job', 1, 'teens', 3, 'Which group of raiders stole Job''s oxen and asses and killed his servants?', 'The Philistines', 'The Sabeans', 'The Chaldeans', 'The Amalekites', 'b', 'A messenger told Job, "The Sabeans fell upon them, and took them away; yea, they have slain the servants with the edge of the sword" (Job 1:15).'),
('Job', 1, 'teens', 4, 'What happened to Job''s sons and daughters?', 'They fled to another land', 'A great wind struck the house and they died', 'They were taken captive by the Chaldeans', 'They fell sick and died of a plague', 'b', 'A great wind smote the four corners of the house, and it fell upon the young men, and they are dead (Job 1:19).'),
('Job', 1, 'teens', 5, 'What did Job do immediately after hearing of all his losses?', 'He sat in silence for seven days', 'He rent his mantle, shaved his head, fell down, and worshipped', 'He went to the temple to pray', 'He cursed the day he was born', 'b', 'Job rent his mantle, and shaved his head, and fell down upon the ground, and worshipped (Job 1:20).'),
-- Adults
('Job', 1, 'adults', 1, 'How many children, livestock categories, and servants made Job the greatest man in the East?', 'Three children, four herds, five hundred servants', 'Ten children; 7,000 sheep, 3,000 camels, 500 yoke of oxen, 500 she asses; a very great household', 'Seven sons, five daughters, ten thousand cattle', 'Twelve sons, great flocks, and a hundred servants', 'b', 'Job had seven sons, three daughters, 7,000 sheep, 3,000 camels, 500 yoke of oxen, 500 she asses, and a very great household (Job 1:2-3).'),
('Job', 1, 'adults', 2, 'What was the occasion when Satan appeared before God in Job chapter 1?', 'The Feast of Tabernacles', 'When the sons of God came to present themselves before the LORD', 'The Day of Atonement', 'When God summoned the angels to judgment', 'b', 'There was a day when the sons of God came to present themselves before the LORD, and Satan came also among them (Job 1:6).'),
('Job', 1, 'adults', 3, 'What specific question did the LORD ask Satan in Job 1:8?', 'Why hast thou come before me?', 'Hast thou considered my servant Job, that there is none like him in the earth?', 'Where hast thou been that thou knowest my servant?', 'How dost thou regard my servant Job?', 'b', 'The LORD said unto Satan, "Hast thou considered my servant Job, that there is none like him in the earth, a perfect and an upright man?" (Job 1:8).'),
('Job', 1, 'adults', 4, 'What limitation did God place on Satan when He permitted him to test Job?', 'Satan could not leave the land of Uz', 'Satan could not touch any of Job''s property', 'Satan could only afflict Job''s livestock', 'Only upon himself put not forth thine hand — Job''s person was protected', 'b', 'The LORD said, "Behold, all that he hath is in thy power; only upon himself put not forth thine hand" (Job 1:12).'),
('Job', 1, 'adults', 5, 'How many separate messengers brought news of disaster to Job, and what made each message worse?', 'Two, each worse than the last', 'Four, each arriving before the previous had finished speaking', 'Three, arriving on three consecutive days', 'Five, one for each disaster', 'b', 'Four messengers came, each saying "I only am escaped to tell thee," each arriving before the last finished speaking (Job 1:14-19).'),
('Job', 1, 'adults', 6, 'What disaster specifically destroyed Job''s sheep and the servants tending them?', 'A raid by the Sabeans', 'A whirlwind from the wilderness', 'The fire of God fell from heaven', 'The Chaldeans took them in three bands', 'c', '"The fire of God is fallen from heaven, and hath burned up the sheep, and the servants, and consumed them" (Job 1:16).'),
('Job', 1, 'adults', 7, 'Who took Job''s camels and slew his servants with the sword?', 'The Sabeans', 'A great whirlwind', 'The Chaldeans in three bands', 'Soldiers from the east', 'c', '"The Chaldeans made out three bands, and fell upon the camels, and have carried them away, yea, and slain the servants with the edge of the sword" (Job 1:17).'),
('Job', 1, 'adults', 8, 'What theological truth does the narrator affirm in Job 1:22 regarding Job''s response to his suffering?', 'Job was confused and did not know what to believe', 'In all this Job sinned not, nor charged God foolishly', 'Job''s faith was shaken but he recovered', 'Job immediately understood it was a test from God', 'b', '"In all this Job sinned not, nor charged God foolishly" (Job 1:22), affirming Job''s integrity under extreme trial.');

-- ═══ Job Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 2, 'kids', 1, 'What did Satan afflict Job with after the second meeting with God?', 'Blindness', 'Sore boils from head to foot', 'A fever and great thirst', 'Lameness in both legs', 'b', 'Satan smote Job with sore boils from the sole of his foot unto his crown (Job 2:7).'),
('Job', 2, 'kids', 2, 'What did Job use to scrape his sores?', 'A cloth', 'A potsherd', 'A stone', 'A piece of wood', 'b', 'Job took a potsherd to scrape himself; and he sat down among the ashes (Job 2:8).'),
('Job', 2, 'kids', 3, 'How many friends came to comfort Job?', 'Two', 'Three', 'Four', 'Five', 'b', 'Three friends heard of all the evil that had come upon Job: Eliphaz, Bildad, and Zophar (Job 2:11).'),
-- Teens
('Job', 2, 'teens', 1, 'What did Job''s wife tell him to do in his suffering?', 'Pray without ceasing', 'Curse God and die', 'Flee to another land', 'Offer a sacrifice', 'b', 'Job''s wife said unto him, "Dost thou still retain thine integrity? curse God, and die" (Job 2:9).'),
('Job', 2, 'teens', 2, 'How did Job rebuke his wife''s advice?', 'He told her to be silent and pray', 'He called her one of the foolish women and said we must receive both good and evil from God', 'He wept and refused to answer her', 'He sent her away from his sight', 'b', 'Job said, "Thou speakest as one of the foolish women speaketh...shall we not receive evil?" (Job 2:10).'),
('Job', 2, 'teens', 3, 'What are the names of Job''s three friends who came to him?', 'Abraham, Isaac, and Jacob', 'Eliphaz, Bildad, and Zophar', 'Nathan, Gad, and Samuel', 'Shadrach, Meshach, and Abednego', 'b', 'Now when Job''s three friends heard...Eliphaz the Temanite, and Bildad the Shuhite, and Zophar the Naamathite (Job 2:11).'),
('Job', 2, 'teens', 4, 'What did Job''s friends do when they saw him from afar?', 'They ran to embrace him', 'They lifted up their voice and wept, rent their mantles, and sprinkled dust on their heads', 'They turned back in fear', 'They brought him food and medicine', 'b', 'They lifted up their voice, and wept; and they rent every one his mantle, and sprinkled dust upon their heads toward heaven (Job 2:12).'),
('Job', 2, 'teens', 5, 'How long did Job''s friends sit with him in silence before anyone spoke?', 'One day', 'Three days and three nights', 'Seven days and seven nights', 'Forty days', 'c', 'They sat down with him upon the ground seven days and seven nights, and none spake a word unto him (Job 2:13).'),
-- Adults
('Job', 2, 'adults', 1, 'What phrase did God use a second time to commend Job before Satan in chapter 2?', 'He is a man after mine own heart', 'Hast thou considered my servant Job, that there is none like him in the earth', 'My servant Job hath done well in all things', 'Job standeth perfect before me', 'b', 'The LORD said unto Satan, "Hast thou considered my servant Job, that there is none like him in the earth, a perfect and an upright man?" (Job 2:3).'),
('Job', 2, 'adults', 2, 'What accusation did God level at Satan in Job 2:3 regarding Job''s suffering in chapter 1?', 'Satan had exceeded his authority', 'Satan had moved God against Job without cause', 'Satan had cheated in the wager', 'Satan had lied about Job''s faithfulness', 'b', 'God said, "thou movedst me against him, to destroy him without cause" (Job 2:3).'),
('Job', 2, 'adults', 3, 'What is the meaning of Satan''s reply "Skin for skin" in Job 2:4?', 'Job would trade another''s skin to save his own life', 'Job would give up everything to preserve his own life', 'Job''s outer suffering had not yet touched his inner self', 'Suffering increases in layers like skin upon skin', 'b', '"Skin for skin, yea, all that a man hath will he give for his life" (Job 2:4) — Satan argues Job will sacrifice anything to preserve himself.'),
('Job', 2, 'adults', 4, 'What new boundary did God set for Satan in Job 2:6?', 'Satan could not touch his children', 'Behold, he is in thine hand; but save his life', 'Satan could only afflict him for thirty days', 'Satan could not use disease', 'b', 'The LORD said unto Satan, "Behold, he is in thine hand; but save his life" (Job 2:6).'),
('Job', 2, 'adults', 5, 'Where did Job sit after being afflicted with boils?', 'In his house among his family', 'Among the ashes', 'In the city gate', 'In the field outside the city', 'b', 'Job went and sat down among the ashes (Job 2:8).'),
('Job', 2, 'adults', 6, 'What does Job''s response to his wife in Job 2:10 reveal about his theology of suffering?', 'He believed suffering was always a punishment', 'He accepted that God sovereignly sends both good and evil', 'He thought God was not in control', 'He was angry but suppressed it', 'b', 'Job said, "What? shall we receive good at the hand of God, and shall we not receive evil?" (Job 2:10).'),
('Job', 2, 'adults', 7, 'From where did each of Job''s three friends come respectively?', 'Jerusalem, Bethlehem, and Nazareth', 'Teman, Shuah, and Naamah', 'Egypt, Babylon, and Persia', 'Uz, Buz, and Chesed', 'b', 'Eliphaz the Temanite, and Bildad the Shuhite, and Zophar the Naamathite came to mourn with Job (Job 2:11).'),
('Job', 2, 'adults', 8, 'What does the narrator affirm about Job''s speech after Satan''s second attack?', 'Job cried out in bitterness and questioned God', 'In all this did not Job sin with his lips', 'Job was silent for seven days without any word', 'Job confessed secret sins he had committed', 'b', '"In all this did not Job sin with his lips" (Job 2:10) — Job''s verbal integrity was maintained even in extreme physical suffering.');

-- ═══ Job Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 3, 'kids', 1, 'After the seven days of silence, what did Job do?', 'He thanked God for his trials', 'He cursed the day he was born', 'He asked his friends to pray for him', 'He offered a sacrifice to God', 'b', 'After this opened Job his mouth, and cursed his day (Job 3:1).'),
('Job', 3, 'kids', 2, 'What did Job wish had happened to the night he was born?', 'That it had been a great feast', 'That darkness and gloom had covered it', 'That a star had shone brightly', 'That it had been a holy day', 'b', 'Job said, "let that night be solitary, let no joyful voice come therein" and wished darkness upon it (Job 3:7).'),
('Job', 3, 'kids', 3, 'What did Job long for in his great sadness?', 'More friends to comfort him', 'For death and rest in the grave', 'For God to speak to him', 'For his family to return', 'b', 'Job asked, "Why died I not from the womb?" longing for rest like those who lie down in the grave (Job 3:11, 17).'),
-- Teens
('Job', 3, 'teens', 1, 'What is the main subject of Job''s opening speech in chapter 3?', 'A prayer asking God to restore his wealth', 'A lament cursing the day of his birth and wishing he had never lived', 'A confession of sin to his three friends', 'A poem praising God in the midst of suffering', 'b', 'Job opened his mouth and cursed his day, saying "Let the day perish wherein I was born" (Job 3:1-3).'),
('Job', 3, 'teens', 2, 'What does Job wish had happened at the moment of his birth?', 'That an angel had announced it', 'That the day had perished and never been seen', 'That his father had rejoiced greatly', 'That God had marked it as holy', 'b', 'Job said, "Let the day perish wherein I was born, and the night in which it was said, There is a man child conceived" (Job 3:3).'),
('Job', 3, 'teens', 3, 'What state does Job describe for those who die at birth or in infancy?', 'They are lost forever in darkness', 'They rest in peace, untroubled like kings in their graves', 'They wander without rest', 'They wait for the resurrection', 'b', 'Job says the stillborn and those who never saw light rest like kings and counsellors who built desolate places (Job 3:13-16).'),
('Job', 3, 'teens', 4, 'Who does Job say finds light grievous and longs for death that does not come?', 'Those who are in poverty', 'Those whose way is hid, and whom God hath hedged in', 'Those who have lost their children', 'Those who have sinned greatly', 'b', 'Job says those whose way is hid, and whom God hath hedged in, long for death but it cometh not (Job 3:23).'),
('Job', 3, 'teens', 5, 'What poetic image does Job use to describe the relentlessness of his sighing?', 'My sighing is like the waves of the sea', 'My sighing cometh before I eat, and my roarings are poured out like the waters', 'My sighing fills the heavens above me', 'My sighing is a burden too great to bear', 'b', '"For my sighing cometh before I eat, and my roarings are poured out like the waters" (Job 3:24).'),
-- Adults
('Job', 3, 'adults', 1, 'What is the literary form of Job''s curse in chapter 3, and how does it mirror the creation account?', 'It is a hymn that praises God''s creation in reverse', 'It is a reverse-creation lament calling for darkness and chaos to unmake the day of his birth', 'It is a legal complaint structured as a court petition', 'It is a wisdom poem comparing life to a shadow', 'b', 'Job calls for darkness (3:4), cursing the light — an inversion of Genesis 1:3 — wishing uncreation on the day of his birth.'),
('Job', 3, 'adults', 2, 'What mythological figure is referenced in Job 3:8 as one who could curse the day?', 'Leviathan', 'Those who curse the day, who are ready to rouse up Leviathan', 'The serpent of chaos', 'The ancient dragon', 'b', '"Let them curse it that curse the day, who are ready to raise up their mourning" — KJV margin reads those ready to raise up Leviathan (Job 3:8).'),
('Job', 3, 'adults', 3, 'What does Job mean when he says in Job 3:23 that his way "is hid" and God "hath hedged him in"?', 'Job could not see the road in front of him', 'Job felt trapped by God''s providence with no escape and no understanding of his situation', 'Job was lost in the wilderness', 'Job was confined to his house by his illness', 'b', '"Why is light given to a man whose way is hid, and whom God hath hedged in?" (Job 3:23) — Job feels providentially trapped with no way forward.'),
('Job', 3, 'adults', 4, 'What contrast does Job draw in Job 3:17-19 about the realm of the dead?', 'The dead suffer more than the living', 'In the grave the wicked cease troubling and the weary are at rest — all are equal regardless of status', 'The righteous rest but the wicked are tormented', 'Only kings and nobles find rest in death', 'b', '"There the wicked cease from troubling; and there the weary be at rest...the small and great are there" (Job 3:17-19).'),
('Job', 3, 'adults', 5, 'What does Job say in Job 3:25 about his fears?', 'He feared God''s wrath from his youth', 'The thing which he greatly feared had come upon him', 'He feared that his friends would abandon him', 'He feared that he would lose his faith', 'b', '"For the thing which I greatly feared is come upon me, and that which I was afraid of is come unto me" (Job 3:25).'),
('Job', 3, 'adults', 6, 'How does Job describe the state of those who dig for death as for hidden treasure in Job 3:21?', 'They die quickly and find rest', 'They rejoice exceedingly and are glad when they find the grave', 'They search in vain and are forgotten', 'They are punished for seeking death', 'b', '"Which long for death, but it cometh not; and dig for it more than for hid treasures; Which rejoice exceedingly, and are glad, when they can find the grave?" (Job 3:21-22).'),
('Job', 3, 'adults', 7, 'What is the significance of Job''s lament in chapter 3 in the overall structure of the book?', 'It proves Job was secretly sinful', 'It marks the transition from narrative prologue to the poetic dialogues and shows even the righteous may cry out in pain', 'It is the climax of the book resolved by the friends'' comfort', 'It establishes Job as an unbeliever', 'b', 'Chapter 3''s lament opens the poetic dialogues and shows that authentic faith does not preclude anguished lamentation, setting the stage for the debates.'),
('Job', 3, 'adults', 8, 'What does the phrase "I was not in safety, neither had I rest, neither was I quiet; yet trouble came" (Job 3:26) communicate?', 'Job had been careless before his sufferings', 'Even in previous peace Job had no true security, and now suffering has overwhelmed all rest', 'Job confesses he had sinned in prosperity', 'Job admits he deserved the trouble that came', 'b', '"I was not in safety, neither had I rest, neither was I quiet; yet trouble came" (Job 3:26) — Job''s peace was already fragile, making the sudden onslaught of suffering total.');

-- ═══ Job Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 4, 'kids', 1, 'Who speaks first among Job''s three friends?', 'Bildad', 'Zophar', 'Eliphaz', 'Elihu', 'c', 'Then Eliphaz the Temanite answered and said... (Job 4:1).'),
('Job', 4, 'kids', 2, 'What did Eliphaz say Job had done for others in the past?', 'Taught them the law of Moses', 'Instructed many and strengthened weak hands', 'Built them houses and fed their families', 'Led them in prayer every morning', 'b', 'Eliphaz said, "Behold, thou hast instructed many, and thou hast strengthened the weak hands" (Job 4:3).'),
('Job', 4, 'kids', 3, 'According to Eliphaz, can a truly good person be destroyed?', 'Yes, anyone can be destroyed', 'No, the innocent are never destroyed', 'Only if they stop praying', 'Only if God wills it for a reason', 'b', 'Eliphaz asks, "who ever perished, being innocent? or where were the righteous cut off?" (Job 4:7).'),
-- Teens
('Job', 4, 'teens', 1, 'What is the main argument Eliphaz makes in his first speech?', 'Job is being tested by God and will be restored', 'The innocent do not perish — suffering proves Job has sinned', 'God is distant and does not concern himself with men', 'Job should accept his suffering and make no complaint', 'b', 'Eliphaz argues that "they that plow iniquity...reap the same" (Job 4:8), implying Job''s suffering reveals hidden sin.'),
('Job', 4, 'teens', 2, 'What natural illustration does Eliphaz use to describe how the wicked perish?', 'A tree that is cut down at the root', 'The lion — its roaring, teeth, and whelps all perish', 'A river that runs dry in summer', 'A storm that passes over and is gone', 'b', 'Eliphaz says the roaring of the lion and the teeth of the young lions are broken — a picture of the wicked''s destruction (Job 4:10-11).'),
('Job', 4, 'teens', 3, 'How did Eliphaz receive the revelation he shares with Job?', 'Through reading the scriptures', 'A thing was secretly brought to him in a vision of the night', 'Through the counsel of wise men', 'An angel appeared to him in broad daylight', 'b', '"Now a thing was secretly brought to me, and mine ear received a little thereof. In thoughts from the visions of the night" (Job 4:12-13).'),
('Job', 4, 'teens', 4, 'What question does the spirit in Eliphaz''s vision ask?', 'Why dost thou complain against the Lord?', 'Shall mortal man be more just than God? shall a man be more pure than his maker?', 'Hast thou considered thy ways before the LORD?', 'Who art thou that rebukes the Almighty?', 'b', '"Shall mortal man be more just than God? shall a man be more pure than his maker?" (Job 4:17).'),
('Job', 4, 'teens', 5, 'What does Eliphaz say about the angels in Job 4:18?', 'The angels worship God perfectly without error', 'God charged his angels with folly', 'The angels are more righteous than man', 'The angels cannot see the ways of men', 'b', '"Behold, he put no trust in his servants; and his angels he charged with folly" (Job 4:18).'),
-- Adults
('Job', 4, 'adults', 1, 'What does the phrase "thy fear" and "thy confidence" in Job 4:6 refer to in Eliphaz''s opening appeal?', 'Job''s fear of death and confidence in his wealth', 'Job''s piety (fear of God) and his hope as an upright man', 'Job''s fear of his enemies and his self-confidence', 'Job''s trembling and his boasting', 'b', 'Eliphaz says, "Is not this thy fear, thy confidence, thy hope, and the uprightness of thy ways?" (Job 4:6) — appealing to Job''s own professed piety.'),
('Job', 4, 'adults', 2, 'What agricultural metaphor does Eliphaz use in Job 4:8 to describe the fate of the wicked?', 'Those who plant thorns will harvest them', 'They that plow iniquity, and sow wickedness, reap the same', 'The field of the wicked is never watered', 'The harvest of evil men is left to rot', 'b', '"Even as I have seen, they that plow iniquity, and sow wickedness, reap the same" (Job 4:8).'),
('Job', 4, 'adults', 3, 'What physical effect did the vision have on Eliphaz before the spirit spoke?', 'He was filled with joy and peace', 'Fear came upon him, trembling, which made all his bones shake', 'He fell into a deep sleep and could not move', 'He wept and tore his clothing', 'b', '"Fear came upon me, and trembling, which made all my bones to shake" (Job 4:14).'),
('Job', 4, 'adults', 4, 'How does Eliphaz describe the appearance of the spirit in his vision?', 'A bright angel in white robes', 'An image was before his eyes with still silence and a voice', 'A pillar of fire and cloud', 'A whirlwind that spoke with thunder', 'b', '"Then a spirit passed before my face; the hair of my flesh stood up...there was silence, and I heard a voice" (Job 4:15-16).'),
('Job', 4, 'adults', 5, 'What does Eliphaz say about humans who dwell in houses of clay in Job 4:19-21?', 'They are blessed by God because of their frailty', 'Their foundation is in the dust; they are crushed before the moth and perish without wisdom', 'They shall be raised up by God in the last day', 'Their weakness makes them innocent before God', 'b', '"How much less in them that dwell in houses of clay, whose foundation is in the dust, which are crushed before the moth...They are destroyed from morning to evening" (Job 4:19-20).'),
('Job', 4, 'adults', 6, 'What does Eliphaz mean by asking if Job''s "hope" and "confidence" should be his source of strength (Job 4:6)?', 'He is encouraging Job to rely on optimism', 'He uses Job''s own stated piety as evidence that Job should be able to bear this, implying Job''s complaint undermines his claim of righteousness', 'He is complimenting Job on his great faith', 'He reminds Job that wealth will return', 'b', 'Eliphaz subtly argues that if Job were truly righteous (as he claims), his piety itself should sustain him — making Job''s lament look hypocritical (Job 4:6).'),
('Job', 4, 'adults', 7, 'In the context of the lion imagery in Job 4:10-11, what theological point is Eliphaz making?', 'Wild animals are more dangerous than humans', 'Even the fiercest and most powerful wicked man is ultimately destroyed', 'God protects the righteous from lions', 'Lions are a symbol of God''s wrath against nations', 'b', 'The roaring lion, old lion, stout lion cubs, and lion''s whelps all perish — a graduated image of how completely the wicked are wiped out (Job 4:10-11).'),
('Job', 4, 'adults', 8, 'What is the theological problem with Eliphaz''s vision-based argument that God charges even angels with folly (Job 4:18)?', 'Angels do not exist in Eliphaz''s worldview', 'He uses it to argue that Job, being merely human, must certainly be impure — but this denies Job''s God-attested integrity', 'The vision was from a demonic source', 'Eliphaz misquotes the scripture he received', 'b', 'Eliphaz argues from the angels'' impurity downward to human impurity (Job 4:17-19), but this ignores the fact that God Himself twice declared Job blameless (Job 1:8; 2:3).');

-- ═══ Job Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 5, 'kids', 1, 'What does Eliphaz say God does for the poor?', 'God ignores the poor until they repent', 'God saveth the poor from the sword and from their mouth', 'God gives the poor riches if they are faithful', 'God sends angels to protect the poor', 'b', 'Eliphaz says God "saveth the poor from the sword, from their mouth, and from the hand of the mighty" (Job 5:15).'),
('Job', 5, 'kids', 2, 'According to Eliphaz, what does God do to the humble?', 'He leaves them in their trouble', 'He sets on high those who mourn', 'He rewards them with children', 'He speaks to them in dreams', 'b', 'Eliphaz says God "setteth up on high those that be low; that those which mourn may be exalted to safety" (Job 5:11).'),
('Job', 5, 'kids', 3, 'What does Eliphaz say is true of the man whom God corrects?', 'He will suffer forever', 'He is a happy man', 'He is forgotten by God', 'He must offer more sacrifices', 'b', 'Eliphaz says "Behold, happy is the man whom God correcteth: therefore despise not thou the chastening of the Almighty" (Job 5:17).'),
-- Teens
('Job', 5, 'teens', 1, 'What does Eliphaz say about calling to the holy ones (saints) for help?', 'They will immediately answer the righteous', 'There is no one among the holy ones to answer Job — he should turn to God', 'The holy ones intercede before God for the afflicted', 'They are more powerful than men but less than God', 'b', 'Eliphaz asks, "Call now, if there be any that will answer thee; and to which of the saints wilt thou turn?" (Job 5:1).'),
('Job', 5, 'teens', 2, 'What does Eliphaz say happens to the foolish man who takes root?', 'His house is blessed with peace', 'He is suddenly cursed and his children are far from safety', 'He grows wealthy for a season before he is cut off', 'He repents and is restored', 'b', 'Eliphaz says, "Wrath killeth the foolish man, and envy slayeth the silly one...his children are far from safety" (Job 5:2-4).'),
('Job', 5, 'teens', 3, 'What does Eliphaz claim about the origin of trouble and affliction?', 'It comes from Satan alone', 'Affliction springeth not out of the dust, neither doth trouble spring out of the ground — man brings it on himself', 'It comes randomly with no cause', 'God sends it only as punishment for great sins', 'b', '"Yet man is born unto trouble, as the sparks fly upward" and "affliction springeth not out of the dust" (Job 5:6-7) — Eliphaz says man himself is the cause.'),
('Job', 5, 'teens', 4, 'What does Eliphaz promise Job if he seeks God?', 'That God will immediately give him wealth', 'That God will do great and marvellous things, giving rain and setting the humble on high', 'That his friends will remain with him', 'That his children will be restored in one day', 'b', 'Eliphaz urges Job to seek God "which doeth great things and unsearchable; marvellous things without number" including sending rain and lifting the low (Job 5:8-11).'),
('Job', 5, 'teens', 5, 'What comprehensive blessing does Eliphaz promise will come to Job if he returns to God?', 'Wealth, fame, and long life among kings', 'Protection at home and in the field, peace with beasts and stones, many children, and a full life', 'Healing of his boils and restoration of his cattle', 'A vision of God and understanding of all mysteries', 'b', 'Eliphaz promises safety at home, peace with wild animals, fruitfulness of fields, many descendants, and coming to the grave in full age like a shock of corn (Job 5:23-26).'),
-- Adults
('Job', 5, 'adults', 1, 'What does Eliphaz mean in Job 5:2 when he says "wrath killeth the foolish man, and envy slayeth the silly one"?', 'Anger and jealousy are physical diseases', 'The passionate impatience of the fool — resentment and envy toward God''s dealings — destroys him', 'Foolish men are killed in wars caused by anger', 'Silly people envy the wise and suffer for it', 'b', 'Eliphaz implies that Job''s angry lament (ch. 3) is itself the mark of a fool whose passionate resentment will destroy him (Job 5:2).'),
('Job', 5, 'adults', 2, 'What does the harvest imagery in Job 5:5 communicate about the fate of the foolish man''s family?', 'Their crops are plentiful but stolen', 'Even their harvest is eaten by strangers and the hungry, and their substance is taken', 'Their children will inherit great wealth', 'Their land becomes permanently barren', 'b', '"Whose harvest the hungry eateth up, and taketh it even out of the thorns, and the robber swalloweth up their substance" (Job 5:5).'),
('Job', 5, 'adults', 3, 'How does Eliphaz describe God''s frustration of the devices of the crafty in Job 5:12-13?', 'God ignores their plans and leaves them alone', 'He disappointeth the devices of the crafty so their hands cannot perform enterprise, and He taketh the wise in their own craftiness', 'He punishes them with sickness', 'He sends angels to prevent their plans', 'b', '"He disappointeth the devices of the crafty...He taketh the wise in their own craftiness" (Job 5:12-13).'),
('Job', 5, 'adults', 4, 'What does Eliphaz say about God''s relationship with the poor and needy in Job 5:15-16?', 'God tests the poor before helping them', 'God saveth the poor from the sword and from the hand of the mighty, and the poor hath hope', 'God rewards the poor only after they repent', 'The poor must call on the saints for intercession first', 'b', '"He saveth the poor from the sword, from their mouth, and from the hand of the mighty. So the poor hath hope, and iniquity stoppeth her mouth" (Job 5:15-16).'),
('Job', 5, 'adults', 5, 'What does Eliphaz promise in Job 5:18 about God''s discipline — that He wounds and also does what?', 'He forgets and lets the wound fester', 'He bindeth up, and his hands make whole', 'He replaces what was lost', 'He removes the memory of pain', 'b', '"For he maketh sore, and bindeth up: he woundeth, and his hands make whole" (Job 5:18).'),
('Job', 5, 'adults', 6, 'How many calamities does Eliphaz say God will deliver Job from in Job 5:19?', 'Three', 'Five', 'Six, and in seven no evil shall touch him', 'Ten', 'c', '"He shall deliver thee in six troubles: yea, in seven there shall no evil touch thee" (Job 5:19) — a numerical saying emphasizing complete protection.'),
('Job', 5, 'adults', 7, 'What covenant does Eliphaz promise Job will make in Job 5:23 if he is restored?', 'A covenant with the sons of Abraham', 'A covenant with the stones of the field and with the beasts of the field', 'A covenant of peace with his enemies', 'A covenant with God at the altar', 'b', '"For thou shalt be in league with the stones of the field: and the beasts of the field shall be at peace with thee" (Job 5:23).'),
('Job', 5, 'adults', 8, 'How does Eliphaz conclude his speech in Job 5:27, and what does this claim reveal about his method?', 'He quotes from the law of Moses as his authority', 'He appeals to collective wisdom: "we have searched it, so it is; hear it, and know thou it for thy good"', 'He invites Job to verify his words with a priest', 'He confesses that he may be wrong and asks Job to correct him', 'b', '"Lo this, we have searched it, so it is; hear it, and know thou it for thy good" (Job 5:27) — Eliphaz relies on the authority of traditional wisdom rather than divine revelation.');

-- ═══ Job Chapter 6 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 6, 'kids', 1, 'What does Job say is heavier than the sand of the sea?', 'His illness', 'His grief and calamity', 'His loss of wealth', 'His longing for death', 'b', 'Job says "my grief were throughly weighed...it would be heavier than the sand of the sea" (Job 6:2-3).'),
('Job', 6, 'kids', 2, 'What does Job compare his friends to in this chapter?', 'Strong lions that protect the weak', 'A deceitful brook that dries up', 'A fruitful garden that feeds the hungry', 'A bright light in the darkness', 'b', 'Job says his brethren are like a brook, like streams of brooks that pass away (Job 6:15).'),
('Job', 6, 'kids', 3, 'What does Job ask his friends to do instead of just criticising him?', 'To pray to God on his behalf', 'To teach him and show him where he has gone wrong', 'To leave him alone in peace', 'To bring him food and medicine', 'b', 'Job says "Teach me, and I will hold my tongue: and cause me to understand wherein I have erred" (Job 6:24).'),
-- Teens
('Job', 6, 'teens', 1, 'What does Job say the arrows of the Almighty have done to him?', 'They have strengthened him for battle', 'Their poison drinketh up his spirit and the terrors of God are set against him', 'They have passed over him without harm', 'They have sharpened his understanding', 'b', '"For the arrows of the Almighty are within me, the poison whereof drinketh up my spirit: the terrors of God do set themselves in array against me" (Job 6:4).'),
('Job', 6, 'teens', 2, 'What does Job use in Job 6:6 to illustrate his point that his complaint is not without cause?', 'A lamp that burns with no oil', 'Unsavoury food — can that which is unsavoury be eaten without salt?', 'A broken vessel that holds no water', 'An ox that refuses to plough', 'b', '"Can that which is unsavoury be eaten without salt? or is there any taste in the white of an egg?" (Job 6:6) — Job argues that his lament is a natural response to his situation.'),
('Job', 6, 'teens', 3, 'What one thing does Job ask God to grant him?', 'That God would restore his children', 'That it would please God to destroy him and let him die', 'That God would reveal the reason for his suffering', 'That God would send a comforter', 'b', '"Even that it would please God to destroy me; that he would let loose his hand, and cut me off" (Job 6:9).'),
('Job', 6, 'teens', 4, 'What does Job say his friends have shown him, like a deceitful brook in summer?', 'False loyalty and vain hope', 'True wisdom but poor timing', 'Great love but little understanding', 'Correct doctrine but cold hearts', 'a', 'Job says his brethren have dealt deceitfully as a brook: "My brethren have dealt deceitfully as a brook...ye see my casting down, and are afraid" (Job 6:15, 21).'),
('Job', 6, 'teens', 5, 'What challenge does Job make to his friends regarding his words in Job 6:25-26?', 'He asks them to praise his patience', 'He asks them to show him where he has erred, since honest words do not rebuke, but they only reprove his speeches as wind', 'He dares them to prove their own righteousness', 'He asks them to speak louder so others can hear', 'b', '"How forcible are right words! but what doth your arguing reprove? Do ye imagine to reprove words, and the speeches of one that is desperate, which are as wind?" (Job 6:25-26).'),
-- Adults
('Job', 6, 'adults', 1, 'What does Job mean in Job 6:10 when he says his consolation would be that "I have not concealed the words of the Holy One"?', 'He hopes to receive a special revelation', 'Even in mortal pain he takes comfort that he has remained faithful in speech and has not denied God''s word', 'He believes God will speak to him soon', 'He is claiming perfect sinlessness', 'b', '"Then should I yet have comfort; yea, I would harden myself in sorrow: let him not spare; for I have not concealed the words of the Holy One" (Job 6:10).'),
('Job', 6, 'adults', 2, 'What does Job''s reference to the strength of stones and brass in Job 6:12 communicate?', 'He admires the permanence of creation', 'He protests that he has no superhuman endurance — he is flesh, not stone or brass', 'He praises God for making durable things', 'He asks for strength like stone to endure longer', 'b', '"Is my strength the strength of stones? or is my flesh of brass?" (Job 6:12) — Job rejects Eliphaz''s implied demand that he endure silently as if he had unlimited strength.'),
('Job', 6, 'adults', 3, 'What detailed geography is used for the deceitful brook in Job 6:17-20?', 'It flows from Lebanon to the Dead Sea', 'It is black with ice and snow in winter but vanishes in heat, leaving caravans of Tema and Sheba ashamed', 'It rises in the spring but fails before the harvest', 'It flows underground and cannot be found', 'b', 'The brook is blackish with ice, snow melts into it, but in heat it vanishes, leaving the troops of Tema and Sheba confounded (Job 6:16-20).'),
('Job', 6, 'adults', 4, 'What specific accusation does Job level against his friends in Job 6:21 and 6:27?', 'They are too young to understand suffering', 'They have become nothing, afraid of his condition, and would even cast lots over the fatherless and dig a pit for a friend', 'They have given him bad theological advice', 'They have not prayed enough for his recovery', 'b', '"For now ye are nothing; ye see my casting down, and are afraid...Yea, ye overwhelm the fatherless, and ye dig a pit for your friend" (Job 6:21, 27).'),
('Job', 6, 'adults', 5, 'What commercial or ethical standard does Job invoke in Job 6:28-29 to demand fair treatment from his friends?', 'The law of hospitality to guests', 'He asks them to look at him directly, return again and his righteousness is at stake — it is worth returning', 'The covenant of friendship sworn before God', 'The tradition of the elders', 'b', '"Now therefore be content, look upon me; for it is evident unto you if I lie. Return, I pray you, let it not be iniquity; yea, return again, my righteousness is in it" (Job 6:28-29).'),
('Job', 6, 'adults', 6, 'What does Job say in Job 6:14 about the treatment he deserves from his friend?', 'A friend should rebuke openly', 'To him that is afflicted pity should be shewed from his friend, but he hath forsaken the fear of the Almighty', 'A friend should offer sacrifices on his behalf', 'A friend should speak truth even when it hurts', 'b', '"To him that is afflicted pity should be shewed from his friend; but he forsaketh the fear of the Almighty" (Job 6:14).'),
('Job', 6, 'adults', 7, 'What is the rhetorical force of Job''s question "Did I say, Bring unto me? or, Give a reward for me?" in Job 6:22?', 'Job is asking his friends to pay for his care', 'Job argues he asked nothing of them — making their cold treatment even more inexcusable', 'Job is complaining that no one helped him financially', 'Job demands they testify on his behalf', 'b', '"Did I say, Bring unto me? or, Give a reward for me of your substance?" (Job 6:22) — Job shows he asked for nothing material, heightening the failure of mere compassion.'),
('Job', 6, 'adults', 8, 'What does Job''s closing question in Job 6:30 assert about his moral integrity?', 'He confesses he may have sinned in his speech', 'He asks whether there is iniquity in his tongue and whether his taste cannot discern perverse things — asserting he can tell right from wrong', 'He admits his lament was excessive', 'He asks his friends to judge him fairly', 'b', '"Is there iniquity in my tongue? cannot my taste discern perverse things?" (Job 6:30) — Job closes by reasserting his moral discernment and the legitimacy of his complaint.');

-- ═══ Job Chapter 7 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 7, 'kids', 1, 'What does Job compare his life to in chapter 7?', 'A tall mountain that stands forever', 'A wind that passes away', 'A river that never runs dry', 'A strong tree in the forest', 'b', 'Job says "my life is wind" and "mine eye shall no more see good" (Job 7:7).'),
('Job', 7, 'kids', 2, 'What does Job say happens to a cloud?', 'It brings rain and refreshes the earth', 'It consumeth and vanisheth away and goes down to the grave no more', 'It stays in the sky forever', 'It becomes the dew of the morning', 'b', 'Job says "As the cloud is consumed and vanisheth away: so he that goeth down to the grave shall come up no more" (Job 7:9).'),
('Job', 7, 'kids', 3, 'Why does Job say God watches him so closely?', 'He does not know and asks why God sets him as a target', 'Because Job is a great sinner who must be corrected', 'Because God loves Job more than anyone else', 'Because Job asked God to watch over him', 'a', 'Job asks "Am I a sea, or a whale, that thou settest a watch over me?" (Job 7:12) — he does not understand why God targets him.'),
-- Teens
('Job', 7, 'teens', 1, 'What illustration does Job use at the start of chapter 7 to describe the misery of human life?', 'A sparrow fallen to the ground', 'An appointed time of hard service — like a hireling who longs for his wages', 'A prisoner who waits for pardon', 'A lamp that is almost burnt out', 'b', '"Is there not an appointed time to man upon earth? are not his days also like the days of an hireling?" (Job 7:1).'),
('Job', 7, 'teens', 2, 'How does Job describe his nights in Job 7:3-4?', 'Long months of vanity and wearisome nights; lying down wishing for morning till the dawning', 'Peaceful sleep with vivid dreams', 'Short nights that pass too quickly', 'Nights of prayer and meditation', 'a', '"So am I made to possess months of vanity, and wearisome nights are appointed to me...and the night be gone? and I am full of tossings to and fro unto the dawning of the day" (Job 7:3-4).'),
('Job', 7, 'teens', 3, 'What physical symptoms does Job describe in Job 7:5?', 'Blindness and deafness from his grief', 'His flesh clothed with worms and clods of dust, his skin broken and become loathsome', 'Fever and chills that will not cease', 'Weakness in his limbs so he cannot rise', 'b', '"My flesh is clothed with worms and clods of dust; my skin is broken, and become loathsome" (Job 7:5).'),
('Job', 7, 'teens', 4, 'What famous question does Job ask God in Job 7:17 that echoes Psalm 8?', 'Why hast thou forsaken me?', 'What is man, that thou shouldest magnify him? and that thou shouldest set thine heart upon him?', 'How long wilt thou afflict me?', 'Shall the dust praise thee?', 'b', '"What is man, that thou shouldest magnify him? and that thou shouldest set thine heart upon him?" (Job 7:17) — echoing Psalm 8:4 but in a very different tone.'),
('Job', 7, 'teens', 5, 'What does Job ask God to do in Job 7:19 regarding his suffering?', 'Never leave his side', 'Turn away from him and let him alone till he swallow down his spittle', 'Reveal the reason for his pain', 'Send his children back to him', 'b', '"How long wilt thou not depart from me, nor let me alone till I swallow down my spittle?" (Job 7:19).'),
-- Adults
('Job', 7, 'adults', 1, 'What double image of a slave and a hireling in Job 7:1-2 does Job use to describe the burden of human existence?', 'Both describe total freedom and joy', 'A slave desires the shadow — relief from labour; a hireling earnestly looks for his wages — both long for release from their toil', 'A slave represents the wicked and a hireling the righteous', 'Both images describe the reward of patience', 'b', '"As a servant earnestly desireth the shadow, and as an hireling looketh for the reward of his work" (Job 7:2) — both yearn for release from grinding toil.'),
('Job', 7, 'adults', 2, 'What does the imagery of the weaver''s shuttle in Job 7:6 convey about Job''s perception of his life?', 'Life is intricately woven and beautiful', 'His days are swifter than a weaver''s shuttle, speeding to an end without hope', 'Life requires patient craftsmanship', 'The pattern of his life is determined by God', 'b', '"My days are swifter than a weaver''s shuttle, and are spent without hope" (Job 7:6).'),
('Job', 7, 'adults', 3, 'What does Job mean in Job 7:8-10 when he says the eye that sees him now will see him no more and he shall return no more to his house?', 'He is planning to move to another city', 'He anticipates the finality of death — the dead do not return, their place knows them no more', 'He believes God will hide his face from him', 'He expects to be sent into exile', 'b', '"The eye of him that hath seen me shall see me no more...He shall return no more to his house, neither shall his place know him any more" (Job 7:8-10) — a meditation on the irreversibility of death.'),
('Job', 7, 'adults', 4, 'In Job 7:12 Job asks "Am I a sea, or a whale, that thou settest a watch over me?" What is the theological irony of this question?', 'Job is praising God for protecting creation from chaos', 'Job compares himself to the primordial chaos monsters (yam/tannin) that God must restrain — ironic since Job is a righteous man, not a chaos force', 'Job is asking to be given the power of the sea', 'Job believes God has confused him with a wicked nation', 'b', '"Am I a sea, or a whale, that thou settest a watch over me?" (Job 7:12) — Job uses the ancient image of God containing chaotic sea monsters to question why he is being treated like a cosmic enemy.'),
('Job', 7, 'adults', 5, 'What does Job say about dreams and visions in Job 7:13-15?', 'His dreams bring him comfort and rest', 'When his bed should comfort him, God scares him with dreams and visions so that his soul chooseth strangling and death rather than his life', 'He no longer dreams because God has taken that gift away', 'His visions show him the path to restoration', 'b', '"When I say, My bed shall comfort me, my couch shall ease my complaint; Then thou scarest me with dreams, and terrifiest me through visions" (Job 7:13-14).'),
('Job', 7, 'adults', 6, 'What does Job mean in Job 7:20 by calling himself a burden to God?', 'He believes he is too heavy for God to carry', 'He sarcastically asks why, if he has sinned, he should be a burden to God — who misses nothing — questioning the proportionality of the response', 'He confesses all his sins before God', 'He asks God to lighten his punishment', 'b', '"I have sinned; what shall I do unto thee, O thou preserver of men? why hast thou set me as a mark against thee, so that I am a burden to myself?" (Job 7:20).'),
('Job', 7, 'adults', 7, 'How does Job''s use of Psalm 8 language in Job 7:17-18 differ from the psalm''s original intent?', 'Both passages celebrate God''s care for mankind equally', 'Psalm 8 marvels with gratitude that God cares for small man; Job uses the same words to protest that God''s attention is overwhelming and relentless rather than gracious', 'Job quotes Psalm 8 to praise God for watching over him', 'Job is unaware of Psalm 8 and the parallel is coincidental', 'b', 'Psalm 8:4 celebrates divine attention as grace; Job 7:17-18 turns the same question into a protest: "what is man that thou...shouldest visit him every morning?"'),
('Job', 7, 'adults', 8, 'What urgent eschatological tone does Job strike in Job 7:21 by asking why God does not pardon his transgression?', 'Job expects a long future with many chances for restoration', 'Job says God must act soon because he will soon lie down in the dust and God will seek him diligently but he shall not be found — urging divine urgency before death ends the opportunity', 'Job believes God will forgive him in the next life', 'Job is threatening to stop worshipping if God does not act', 'b', '"Why dost thou not pardon my transgression...for now shall I sleep in the dust; and thou shalt seek me in the morning, but I shall not be" (Job 7:21).');

-- ═══ Job Chapter 8 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 8, 'kids', 1, 'Which of Job''s friends speaks in chapter 8?', 'Eliphaz', 'Zophar', 'Bildad', 'Elihu', 'c', 'Then answered Bildad the Shuhite (Job 8:1).'),
('Job', 8, 'kids', 2, 'What does Bildad say God will not do?', 'He will not listen to Job''s prayers', 'He will not pervert judgment or right', 'He will not restore Job''s wealth', 'He will not heal Job''s sores', 'b', 'Bildad says "Doth God pervert judgment? or doth the Almighty pervert justice?" (Job 8:3).'),
('Job', 8, 'kids', 3, 'What plant does Bildad use as an example of something that dies without water?', 'An oak tree', 'A vine in the desert', 'A rush without mire or flag without water', 'A flower in the field', 'c', 'Bildad asks "Can the rush grow up without mire? can the flag grow without water?" as a picture of those who forget God (Job 8:11).'),
-- Teens
('Job', 8, 'teens', 1, 'What does Bildad say happened to Job''s children and why?', 'They were taken by God as a blessing', 'If his children sinned, God cast them away for their transgression', 'They perished because Job was not faithful enough', 'They were taken to teach Job patience', 'b', '"If thy children have sinned against him, and he have cast them away for their transgression" (Job 8:4).'),
('Job', 8, 'teens', 2, 'What does Bildad promise Job if he is pure and upright?', 'That God will immediately heal his boils', 'That God will make the habitation of his righteousness prosperous', 'That his three friends will confess their error', 'That he will receive a vision explaining his suffering', 'b', '"If thou wert pure and upright; surely now he would awake for thee, and make the habitation of thy righteousness prosperous" (Job 8:6).'),
('Job', 8, 'teens', 3, 'Where does Bildad say his wisdom comes from?', 'His own long experience', 'The former age and the search of their fathers', 'The wisdom of Solomon', 'A dream from God', 'b', '"For enquire, I pray thee, of the former age, and prepare thyself to the search of their fathers" (Job 8:8).'),
('Job', 8, 'teens', 4, 'What does Bildad say the hypocrite''s hope is like?', 'A house built on sand', 'A spider''s house — a web that cannot stand', 'A ship in the storm', 'A candle in the wind', 'b', '"So are the paths of all that forget God; and the hypocrite''s hope shall perish: Whose hope shall be cut off, and whose trust shall be a spider''s web" (Job 8:13-14).'),
('Job', 8, 'teens', 5, 'What does Bildad say about Job''s beginning compared to his latter end?', 'His latter end will be worse than his beginning', 'Though his beginning was small, his latter end should greatly increase', 'His beginning and end will be the same', 'His latter end is known only to God', 'b', '"Though thy beginning was small, yet thy latter end should greatly increase" (Job 8:7).'),
-- Adults
('Job', 8, 'adults', 1, 'What does Bildad''s opening question "How long wilt thou speak these things?" reveal about his assessment of Job''s lament?', 'He is genuinely concerned for Job''s health', 'He dismisses Job''s lament as a great wind — implying it is empty, prolonged, and spiritually dangerous', 'He wants Job to speak more clearly', 'He is asking Job to be more theologically precise', 'b', '"How long wilt thou speak these things? and how long shall the words of thy mouth be like a strong wind?" (Job 8:2) — Bildad calls Job''s speeches empty as wind.'),
('Job', 8, 'adults', 2, 'What is the theological basis for Bildad''s argument in Job 8:3?', 'Divine omnipotence requires God to use suffering as a tool', 'Divine justice is immutable — God cannot pervert judgment, therefore suffering must prove guilt', 'God rewards only the richest and most prominent men', 'Human wisdom is sufficient to judge divine actions', 'b', '"Doth God pervert judgment? or doth the Almighty pervert justice?" (Job 8:3) — Bildad builds his case on the absolute justice of God, which to him logically requires Job''s guilt.'),
('Job', 8, 'adults', 3, 'What does Bildad imply about Job''s children in Job 8:4 and how does this differ from what the reader knows from the prologue?', 'He says they died innocently and God was wrong', 'He suggests they died for their own sins — but the reader knows from chapters 1-2 that Job''s integrity was tested, not punished', 'He says their deaths were a divine mystery', 'He blames Job for not praying enough for them', 'b', '"If thy children have sinned against him, and he have cast them away for their transgression" (Job 8:4) — the reader knows from ch. 1-2 that this is false.'),
('Job', 8, 'adults', 4, 'What does Bildad''s appeal to "the former age" and the "fathers" in Job 8:8-10 reveal about his epistemology?', 'He values personal spiritual experience above tradition', 'He grounds authoritative knowledge in the accumulated wisdom of earlier generations rather than individual experience', 'He believes the prophets hold all truth', 'He relies on divine revelation given directly to him', 'b', '"Enquire...of the former age, and prepare thyself to the search of their fathers...shall not they teach thee, and tell thee?" (Job 8:8-10).'),
('Job', 8, 'adults', 5, 'What three images does Bildad use in Job 8:11-19 to describe the fate of those who forget God?', 'Stars, rivers, and mountains', 'Rush without water, spider''s web, and a plant uprooted from stone', 'Salt, wind, and dust', 'Cloud, shadow, and night', 'b', 'Bildad uses: (1) rush/flag dying without water (8:11-12); (2) the hypocrite''s trust like a spider''s web (8:14); (3) a plant whose roots wrap stone but is pulled up and the soil denies him (8:16-19).'),
('Job', 8, 'adults', 6, 'What does the phrase "leaning upon his house" in Job 8:15 suggest about the hypocrite''s false security?', 'The hypocrite has built a very strong house', 'He shall lean upon his house but it shall not stand — the web and the house both crumble, showing false security collapses under weight', 'He must renovate his house to be saved', 'He is too lazy to build a real house', 'b', '"He shall lean upon his house, but it shall not stand: he shall hold it fast, but it shall not endure" (Job 8:15) — the spider''s web cannot bear weight.'),
('Job', 8, 'adults', 7, 'What does Bildad mean by "the joy of his way" being destroyed in Job 8:19?', 'The hypocrite was never truly joyful', 'Behold, this is the joy of his way — ironically the plant''s flourishing was its downfall, and out of the earth others shall grow — the wicked are replaced by others', 'God removes joy as the first sign of punishment', 'The wicked man''s path leads to a joyless end', 'b', '"Behold, this is the joy of his way, and out of the earth shall others grow" (Job 8:19) — the hypocrite''s prosperity is brief and soon replaced.'),
('Job', 8, 'adults', 8, 'What conditional promise does Bildad end with in Job 8:20-22, and what is its implicit accusation?', 'God will forgive Job if he confesses openly', 'God will not cast away a perfect man nor help evildoers — if Job were perfect he would be filled with laughing; since he suffers, he must be an evildoer', 'Job must offer a hundred burnt offerings', 'God will restore Job only after his death', 'b', '"Behold, God will not cast away a perfect man, neither will he help the evil doers" (Job 8:20) — the implication is that Job''s suffering proves he is not perfect.');

-- ═══ Job Chapter 9 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 9, 'kids', 1, 'Does Job think a man can be right before God in a legal argument?', 'Yes, easily', 'He wonders how a man can be just with God', 'He says God always agrees with man', 'He says he will argue his case before God', 'b', 'Job says "But how should man be just with God?" (Job 9:2).'),
('Job', 9, 'kids', 2, 'What does Job say God does to great things in creation?', 'God made them long ago and forgot them', 'God doeth great things past finding out, marvellous things without number', 'God shows them only to the righteous', 'God destroys them when they grow too large', 'b', 'Job says God "doeth great things past finding out; yea, and wonders without number" (Job 9:10).'),
('Job', 9, 'kids', 3, 'What does Job say he needs to face God in a legal court?', 'A great sacrifice', 'Someone to argue his case — a daysman or mediator', 'A wiser friend than Eliphaz', 'A dream or vision from God', 'b', 'Job says "Neither is there any daysman betwixt us, that might lay his hand upon us both" (Job 9:33).'),
-- Teens
('Job', 9, 'teens', 1, 'What does Job say about trying to argue with God — how many of a thousand questions could a man answer?', 'A thousand out of a thousand', 'He could not answer one in a thousand', 'Perhaps half of them', 'Only the wisest could answer three', 'b', '"If he will contend with him, he cannot answer him one of a thousand" (Job 9:3).'),
('Job', 9, 'teens', 2, 'Name two constellations that Job attributes to God''s creation in chapter 9.', 'Orion and the Pleiades', 'Arcturus and Orion', 'Arcturus, Orion, and Pleiades', 'The Bear and the Dragon', 'c', '"Which maketh Arcturus, Orion, and Pleiades, and the chambers of the south" (Job 9:9).'),
('Job', 9, 'teens', 3, 'What does Job say happens if God passes by and takes something?', 'He will restore it later', 'He passeth on, taketh away, and there is none that can hinder him or say What doest thou?', 'He explains his reasons to the prophets', 'He shows it to the angels first', 'b', '"If he pass through, or shut up, or gather together, then who can hinder him? Who will say unto him, What doest thou?" (Job 9:12).'),
('Job', 9, 'teens', 4, 'How does Job describe himself when he tries to speak to God?', 'Bold and confident of his innocence', 'Even if he were righteous his own mouth would condemn him', 'Full of wise arguments that God must hear', 'Silent and unable to form any words', 'b', '"If I justify myself, mine own mouth shall condemn me: if I say, I am perfect, it shall also prove me perverse" (Job 9:20).'),
('Job', 9, 'teens', 5, 'What does Job say in Job 9:33 that he lacks in his dispute with God?', 'Enough sacrifices to offer', 'A daysman — a mediator who could lay his hand upon them both', 'A wise friend to speak for him', 'The law written on stone', 'b', '"Neither is there any daysman betwixt us, that might lay his hand upon us both" (Job 9:33).'),
-- Adults
('Job', 9, 'adults', 1, 'What is the significance of Job''s opening words "I know it is so of a truth" in Job 9:2?', 'He is agreeing that he has sinned greatly', 'He concedes Bildad''s theological premise that God is just, but turns it to show the problem: no human can be just enough before such a God', 'He is praising Bildad''s speech as the best argument', 'He is announcing that he will stop complaining', 'b', '"I know it is so of a truth: but how should man be just with God?" (Job 9:2) — Job accepts divine justice in principle but shows it creates an impossible situation for humans.'),
('Job', 9, 'adults', 2, 'What cosmic and geographical acts does Job list in Job 9:5-9 to describe God''s overwhelming power?', 'Feeding the poor and healing the sick', 'Removing mountains, shaking the earth, darkening the sun, sealing up stars, treading on sea waves, and making Arcturus, Orion, and Pleiades', 'Creating the rivers and setting the boundaries of nations', 'Sending rain and making the seasons change', 'b', 'Job lists: removing mountains (9:5), shaking earth (9:6), commanding the sun and sealing stars (9:7), walking on sea waves (9:8), making the constellations (9:9).'),
('Job', 9, 'adults', 3, 'What is the theological tension in Job''s statement in Job 9:15: "Whom, though I were righteous, yet would I not answer, but I would make supplication to my judge"?', 'Job believes he must earn the right to speak by more sacrifice', 'Even if Job were righteous he could not effectively argue with God — the power asymmetry is so vast he can only plead, not argue', 'Job admits his own guilt and asks for leniency', 'Job is satisfied that God will hear his prayer', 'b', '"Whom, though I were righteous, yet would I not answer, but I would make supplication to my judge" (Job 9:15) — righteousness is insufficient leverage against God''s overwhelming power.'),
('Job', 9, 'adults', 4, 'What does Job say about the earth in Job 9:24 that represents his most bitter accusation?', 'The earth is cursed and shall pass away', 'The earth is given into the hand of the wicked and God covereth the faces of its judges — if not he, who then is it?', 'The earth belongs to God alone and cannot be contested', 'The earth rewards the righteous with increase', 'b', '"The earth is given into the hand of the wicked: he covereth the faces of the judges thereof; if not, where and who is he?" (Job 9:24).'),
('Job', 9, 'adults', 5, 'How does Job use the metaphors of swift days — a post, swift ships, and an eagle — in Job 9:25-26?', 'To praise God for the beauty of creation', 'To lament the speed with which his brief, already joyless life is passing with no hope of recovery', 'To urge his friends to act quickly on his behalf', 'To describe the swiftness of God''s judgment', 'b', '"Now my days are swifter than a post: they flee away...They are passed away as the swift ships: as the eagle that hasteth to the prey" (Job 9:25-26).'),
('Job', 9, 'adults', 6, 'What problem does Job raise in Job 9:28-31 about trying to make himself clean before God?', 'He does not have access to water for ritual washing', 'Even if he washed himself with snow water and made his hands ever so clean, God would plunge him in the ditch making his own clothes abhor him', 'He needs a priest to declare him clean first', 'He has no white garments to wear in God''s presence', 'b', '"If I wash myself with snow water, and make my hands never so clean; Yet shalt thou plunge me in the ditch, and mine own clothes shall abhor me" (Job 9:30-31).'),
('Job', 9, 'adults', 7, 'What does Job mean in Job 9:32-33 when he says "He is not a man, as I am, that I should answer him"?', 'God speaks a different language that Job cannot understand', 'The total disparity between God and man makes legal contest impossible — hence the need for a mediator who shares both natures', 'God has no interest in human legal proceedings', 'Job is too weak physically to stand before God', 'b', '"He is not a man, as I am, that I should answer him, and we should come together in judgment. Neither is there any daysman betwixt us" (Job 9:32-33) — the need for a divine-human mediator.'),
('Job', 9, 'adults', 8, 'How does Job''s concept of a "daysman" in Job 9:33 relate to the New Testament doctrine of Christ as mediator?', 'It has no connection to New Testament theology', 'Job''s cry for a daysman who can lay his hand on both God and man anticipates the incarnation of Christ, the one mediator between God and men (1 Tim 2:5)', 'The daysman is merely a legal concept with no spiritual meaning', 'Job is asking for a human priest to represent him', 'b', 'Job''s longing for "any daysman betwixt us, that might lay his hand upon us both" (Job 9:33) is one of the most remarkable Messianic anticipations in the OT, fulfilled in Christ the God-man mediator.');

-- ═══ Job Chapter 10 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Job', 10, 'kids', 1, 'What does Job say his soul is weary of?', 'Listening to his friends argue', 'His life', 'Sitting in the ashes', 'Waiting for God to speak', 'b', 'Job says "My soul is weary of my life; I will leave my complaint upon myself" (Job 10:1).'),
('Job', 10, 'kids', 2, 'What does Job say God made him out of?', 'Stone and dust', 'Clay', 'Wood from the cedar tree', 'Water from the deep', 'b', 'Job says "Thou hast made me as the clay" (Job 10:9).'),
('Job', 10, 'kids', 3, 'What does Job ask God to remember about him?', 'That he has offered many sacrifices', 'That God made him like milk curdled into cheese — he is God''s own creation', 'That he has always prayed morning and evening', 'That he is wiser than his three friends', 'b', 'Job asks God to remember that "thou hast made me as the clay...Hast thou not poured me out as milk, and curdled me like cheese?" (Job 10:9, 10).'),
-- Teens
('Job', 10, 'teens', 1, 'What bold request does Job make of God at the start of chapter 10?', 'That God would heal his boils immediately', 'That God would tell him why he contends with him and show him wherefore he afflicts him', 'That God would restore his children', 'That God would silence his three friends', 'b', '"I will say unto God, Do not condemn me; shew me wherefore thou contendest with me" (Job 10:2).'),
('Job', 10, 'teens', 2, 'What rhetorical questions does Job ask to challenge the logic of God''s treatment of him in Job 10:3-5?', 'Dost thou delight in oppression? dost thou see as man sees?', 'Is it good unto thee that thou shouldest oppress, that thou shouldest despise the work of thine hands...hast thou eyes of flesh?', 'Why dost thou create if thou wilt only destroy?', 'Art thou not the God who made me from the beginning?', 'b', '"Is it good unto thee that thou shouldest oppress, that thou shouldest despise the work of thine hands...Hast thou eyes of flesh? or seest thou as man seeth?" (Job 10:3-4).'),
('Job', 10, 'teens', 3, 'What does Job say God''s hands did for him in Job 10:8?', 'They wrote his name in the book of life', 'They fashioned and made him together round about — yet now destroy him', 'They shielded him from the Sabeans', 'They placed him in the land of Uz', 'b', '"Thine hands have made me and fashioned me together round about; yet thou dost destroy me" (Job 10:8).'),
('Job', 10, 'teens', 4, 'How does Job describe God''s knowledge of his innocence in Job 10:7?', 'God does not know whether Job is innocent', 'Thou knowest that I am not wicked, yet there is none that can deliver him out of God''s hand', 'God will discover Job''s innocence eventually', 'God knew Job was innocent from before his birth', 'b', '"Thou knowest that I am not wicked; and there is none that can deliver out of thine hand" (Job 10:7).'),
('Job', 10, 'teens', 5, 'What two contrasting things does Job say God gave him in Job 10:12?', 'Sorrow and joy', 'Life and favour, and visitation of his spirit preserved him', 'Wealth and then poverty', 'A family and then took them away', 'b', '"Thou hast granted me life and favour, and thy visitation hath preserved my spirit" (Job 10:12).'),
-- Adults
('Job', 10, 'adults', 1, 'What is the theological audacity of Job''s speech in Job 10:1-2 where he refuses to restrain his complaint?', 'Job is sinning in his bitterness and must repent', 'Job models honest lament prayer — he speaks to God directly rather than about him, trusting that God can receive raw human anguish', 'Job is losing his faith and must be corrected', 'Job is performing a formal legal procedure', 'b', '"I will leave my complaint upon myself; I will speak in the bitterness of my soul. I will say unto God, Do not condemn me" (Job 10:1-2) — Job addresses God directly, a mark of authentic faith.'),
('Job', 10, 'adults', 2, 'What does Job mean in Job 10:3 when he asks whether it seems good to God to oppress and despise the work of his hands?', 'Job thinks God is evil', 'Job challenges God''s internal consistency — a craftsman who takes pride in his work would not destroy it, so God''s destruction of Job contradicts his own creative investment', 'Job is trying to flatter God into releasing him', 'Job is quoting the theology of the wicked nations', 'b', '"Is it good unto thee that thou shouldest oppress, that thou shouldest despise the work of thine hands?" (Job 10:3) — the creator-creature relationship becomes Job''s argument.'),
('Job', 10, 'adults', 3, 'What does Job''s embryological description in Job 10:10-11 reveal about his view of God as creator?', 'God only created the soul, not the body', 'God is intimately involved in forming human life from conception — pouring out as milk, curdling like cheese, clothing with skin and flesh, fencing with bones and sinews', 'Life comes from the earth alone and God observes it', 'The body is created by angels and the soul by God', 'b', '"Hast thou not poured me out as milk, and curdled me like cheese? Clothed me with skin and flesh, and fenced me with bones and sinews?" (Job 10:10-11).'),
('Job', 10, 'adults', 4, 'What dark reversal does Job describe in Job 10:13-17 between God''s past care and present pursuit?', 'God blessed him in youth but now ignores him', 'The same God who formed and preserved him has hidden purposes to watch for his sin, not acquit him, and now hunts him like a lion', 'God is testing him to make him stronger', 'God has given his case to the angels to judge', 'b', '"And these things hast thou hid in thine heart: I know that this is with thee...If I be wicked, woe unto me; and if I be righteous, yet will I not lift up my head...Thou huntest me as a fierce lion" (Job 10:13-16).'),
('Job', 10, 'adults', 5, 'What does the phrase "witnesses against me" in Job 10:17 indicate about Job''s legal metaphor?', 'His friends are witnessing against him in a human court', 'God produces fresh hosts of witnesses against Job, renewing his indignation, as if bringing new charges in a legal proceeding that never ends', 'Job''s past sins are now being revealed publicly', 'The angels of God testify against Job before the heavenly court', 'b', '"Thou renewest thy witnesses against me, and increasest thine indignation upon me; changes and war are against me" (Job 10:17).'),
('Job', 10, 'adults', 6, 'What question does Job return to in Job 10:18 that echoes his lament in chapter 3?', 'Why did God not listen to his prayers', 'Wherefore then hast thou brought me forth out of the womb — why was he not simply carried from womb to grave without any existence', 'Why did God take away his children first', 'Why did God choose him for this test', 'b', '"Wherefore then hast thou brought me forth out of the womb? Oh that I had given up the ghost, and no eye had seen me!" (Job 10:18) — echoing the death-wish of ch. 3.'),
('Job', 10, 'adults', 7, 'What does Job request of God in Job 10:20 before death comes?', 'That God would explain all the reasons for his suffering', 'That God would cease from him for a little while so he can take comfort before he goes to the land of darkness', 'That God would restore his family immediately', 'That God would let his friends go free from blame', 'b', '"Are not my days few? cease then, and let me alone, that I may take comfort a little, Before I go whence I shall not return" (Job 10:20-21).'),
('Job', 10, 'adults', 8, 'How does Job describe the realm of the dead in Job 10:21-22, and what does this reveal about OT eschatology?', 'A paradise where the righteous dwell with God in light', 'A land of darkness, shadow of death, land of darkness as darkness itself, where the light is as darkness — a realm of complete and total absence', 'A place of temporary waiting before resurrection', 'A land ruled by angels who keep the dead in order', 'b', '"A land of darkness, as darkness itself; and of the shadow of death, without any order, and where the light is as darkness" (Job 10:22) — reflecting the OT Sheol as a shadowy, undifferentiated realm of the dead.');
