-- ============================================================================
-- Quiz Seed: Luke — Part 4 (Chapters 19–24)
-- 3 difficulties × 6 chapters = 96 total questions
--   kids:   3 per chapter  = 18
--   teens:  5 per chapter  = 30
--   adults: 8 per chapter  = 48
-- ============================================================================

-- ═══════════════ CHAPTERS 19–21 ═══════════════

-- ═══ Luke Chapter 19 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Luke', 19, 'kids', 1, 'What did the short tax collector Zacchaeus climb to see Jesus?', 'A sycamore tree', 'A tall ladder', 'The city wall', 'A rooftop', 'a', 'Luke 19:4 — "And he ran before, and climbed up into a sycomore tree to see him: for he was to pass that way."'),
('Luke', 19, 'kids', 2, 'What did Jesus say to Zacchaeus when He saw him in the tree?', 'Zacchaeus, make haste, and come down; for to day I must abide at thy house', 'Zacchaeus, you are in trouble', 'Zacchaeus, stay up there', 'Zacchaeus, go away from me', 'a', 'Luke 19:5 — "And when Jesus came to the place, he looked up, and saw him, and said unto him, Zacchaeus, make haste, and come down; for to day I must abide at thy house."'),
('Luke', 19, 'kids', 3, 'What did the people shout when Jesus rode into Jerusalem?', 'Blessed be the King that cometh in the name of the Lord: peace in heaven, and glory in the highest', 'Go away, we do not want you', 'We want a different king', 'Long live Caesar', 'a', 'Luke 19:38 — "Saying, Blessed be the King that cometh in the name of the Lord: peace in heaven, and glory in the highest."'),
-- Teens
('Luke', 19, 'teens', 1, 'How did Zacchaeus show that his heart had truly changed?', 'He said he would give half his goods to the poor and restore fourfold to anyone he had cheated', 'He promised to stop collecting taxes', 'He gave Jesus a large bag of gold', 'He invited all the Pharisees to dinner', 'a', 'Luke 19:8 — "And Zacchaeus stood, and said unto the Lord; Behold, Lord, the half of my goods I give to the poor; and if I have taken any thing from any man by false accusation, I restore him fourfold."'),
('Luke', 19, 'teens', 2, 'What did Jesus say was the purpose of His coming, after meeting Zacchaeus?', 'The Son of man is come to seek and to save that which was lost', 'The Son of man came to judge the world', 'The Son of man came to rule as an earthly king', 'The Son of man came to destroy the wicked', 'a', 'Luke 19:10 — "For the Son of man is come to seek and to save that which was lost."'),
('Luke', 19, 'teens', 3, 'In the parable of the pounds (minas), what did the nobleman say to the faithful servant?', 'Well, thou good servant: because thou hast been faithful in a very little, have thou authority over ten cities', 'You should have done even more', 'Take a long rest and enjoy yourself', 'Give your cities to someone else', 'a', 'Luke 19:17 — "And he said unto him, Well, thou good servant: because thou hast been faithful in a very little, have thou authority over ten cities."'),
('Luke', 19, 'teens', 4, 'What did Jesus do when He saw Jerusalem from a distance?', 'He wept over it, saying if only they had known the things that belong to their peace', 'He smiled and celebrated', 'He turned back and went another way', 'He praised the city for its faithfulness', 'a', 'Luke 19:41-42 — "And when he was come near, he beheld the city, and wept over it, Saying, If thou hadst known, even thou, at least in this thy day, the things which belong unto thy peace! but now they are hid from thine eyes."'),
('Luke', 19, 'teens', 5, 'What did Jesus say about the temple when He drove out the merchants?', 'It is written, My house is the house of prayer: but ye have made it a den of thieves', 'The temple should be a marketplace', 'Merchants are welcome in the temple', 'The temple does not matter anymore', 'a', 'Luke 19:46 — "Saying unto them, It is written, My house is the house of prayer: but ye have made it a den of thieves."'),
-- Adults
('Luke', 19, 'adults', 1, 'What does Zacchaeus'' fourfold restitution signify about the genuineness of his conversion?', 'Fourfold restitution exceeds the Old Testament requirement (Exodus 22:1 for stealing a sheep; Numbers 5:7 requires principal plus one-fifth) — Zacchaeus'' generosity goes beyond legal obligation, demonstrating genuine repentance through costly action', 'He was simply following the minimum legal requirement', 'He was trying to buy salvation', 'Zacchaeus was exaggerating his promise', 'a', 'Luke 19:8 — Zacchaeus offers half his goods to the poor and fourfold restitution — the maximum penalty for theft (Exodus 22:1). His spontaneous generosity (not commanded by Jesus) is fruit of repentance, not its cause.'),
('Luke', 19, 'adults', 2, 'What does Jesus'' declaration "This day is salvation come to this house, forsomuch as he also is a son of Abraham" mean?', 'Salvation came to Zacchaeus not because of ethnic heritage but because he displayed the faith of Abraham — Jesus redefines Abrahamic sonship as faith-based, not merely genealogical, vindicating His ministry to "sinners"', 'Only ethnic Jews can be saved', 'Salvation was physical healing in this case', 'Zacchaeus was saved because he was already righteous', 'a', 'Luke 19:9 — "This day is salvation come to this house, forsomuch as he also is a son of Abraham." Tax collectors were treated as covenant outsiders, but Jesus declares Zacchaeus a true son of Abraham — one who, like Abraham, believed and was counted righteous.'),
('Luke', 19, 'adults', 3, 'How does the parable of the ten pounds (minas) differ from the talents parable in Matthew 25?', 'In Luke each servant receives the same amount (one mina) but produces different results, while in Matthew different amounts are given — Luke emphasises equal opportunity with differing faithfulness, and adds the subplot of citizens who rejected the nobleman''s reign', 'They are identical parables', 'Luke''s version has more money given', 'Matthew''s version includes hostile citizens', 'a', 'Luke 19:12-27 — The citizens'' protest ("We will not have this man to reign over us," v.14) is unique to Luke and represents Israel''s rejection of Jesus as King. The parable teaches both faithful stewardship and the consequences of rejecting Christ''s sovereignty.'),
('Luke', 19, 'adults', 4, 'What does the servant who hid his pound in a napkin represent?', 'Those who know their master''s character but respond with fear-based inaction rather than faithful service — he misrepresented the master as harsh, using this as an excuse for doing nothing, and is judged by his own words', 'A wise and cautious investor', 'Someone who was too poor to invest', 'A faithful servant who preserved capital', 'a', 'Luke 19:20-22 — "Lord, behold, here is thy pound, which I have kept laid up in a napkin: For I feared thee... Out of thine own mouth will I judge thee, thou wicked servant." His excuse condemns him: if the master were truly austere, all the more reason to invest, not less.'),
('Luke', 19, 'adults', 5, 'What does Jesus'' weeping over Jerusalem reveal about divine emotion and human responsibility?', 'Jesus expresses genuine grief over Jerusalem''s coming destruction, which He attributes to their failure to recognise the time of God''s visitation — divine sorrow over human rejection shows that judgment is not God''s delight but humanity''s choice', 'Jesus was simply tired from the journey', 'The tears were for dramatic effect', 'Jesus wept because He feared the Romans', 'a', 'Luke 19:41-44 — "If thou hadst known... the things which belong unto thy peace! but now they are hid from thine eyes." Jesus weeps because Jerusalem''s destruction (AD 70) was avoidable — had they received their Messiah. The tears are prophetic grief.'),
('Luke', 19, 'adults', 6, 'What does the prophecy "thine enemies shall cast a trench about thee... and shall lay thee even with the ground" specifically predict?', 'The Roman siege and destruction of Jerusalem in AD 70 under Titus — the Romans built a siege wall (circumvallation), starved the city, destroyed the temple, and left not one stone upon another, exactly as Jesus prophesied', 'A minor skirmish with neighbouring tribes', 'An earthquake that would damage Jerusalem', 'A peaceful transition of power', 'a', 'Luke 19:43-44 — "Thine enemies shall cast a trench about thee, and compass thee round, and keep thee in on every side, And shall lay thee even with the ground, and thy children within thee; and they shall not leave in thee one stone upon another." Josephus'' account of AD 70 confirms every detail.'),
('Luke', 19, 'adults', 7, 'What is the significance of the phrase "because thou knewest not the time of thy visitation"?', 'Jerusalem failed to recognise the kairos — the decisive moment when God visited His people in the person of Jesus Christ. This "visitation" echoes Old Testament language (Exodus 3:16, Jeremiah 29:10) for God''s redemptive intervention', 'The people simply lacked calendars', 'Visitation refers to a Roman census', 'This was about temple visiting hours', 'a', 'Luke 19:44 — "Because thou knewest not the time of thy visitation." The Greek "episkope" (visitation) carries both salvific and judicial meaning. God visited in grace; rejection turns that visit into judgment.'),
('Luke', 19, 'adults', 8, 'What does the Triumphal Entry in Luke uniquely emphasise compared to the other Gospels?', 'Luke''s account uniquely includes the Pharisees asking Jesus to rebuke His disciples and Jesus'' response: "If these should hold their peace, the stones would immediately cry out" — and Luke alone records Jesus weeping over the city, emphasising the tragedy of rejection', 'Luke''s account is identical to the others', 'Luke omits the Triumphal Entry entirely', 'Luke focuses only on the donkey', 'a', 'Luke 19:39-40 — "Master, rebuke thy disciples. And he answered and said unto them, I tell you that, if these should hold their peace, the stones would immediately cry out." Jesus declares that praise is inevitable — creation itself will cry out if humans fall silent.');

-- ═══ Luke Chapter 20 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Luke', 20, 'kids', 1, 'What did Jesus say about paying taxes to Caesar?', 'Render unto Caesar the things which be Caesar''s, and unto God the things which be God''s', 'Never pay any taxes at all', 'Only pay taxes to the temple', 'Caesar deserves everything you have', 'a', 'Luke 20:25 — "And he said unto them, Render therefore unto Caesar the things which be Caesar''s, and unto God the things which be God''s."'),
('Luke', 20, 'kids', 2, 'In the parable of the wicked vineyard workers, what did they do to the owner''s son?', 'They cast him out of the vineyard and killed him', 'They welcomed him warmly', 'They gave him all the fruit', 'They asked him to stay forever', 'a', 'Luke 20:15 — "So they cast him out of the vineyard, and killed him."'),
('Luke', 20, 'kids', 3, 'What does Jesus say about God — is He a God of the dead or the living?', 'He is not a God of the dead, but of the living: for all live unto Him', 'He is God of the dead only', 'He is God of both equally the same way', 'He does not care about people after they die', 'a', 'Luke 20:38 — "For he is not a God of the dead, but of the living: for all live unto him."'),
-- Teens
('Luke', 20, 'teens', 1, 'Why did the religious leaders question Jesus'' authority?', 'He was teaching and preaching the gospel in the temple and had cleansed it — they wanted to trap Him by making Him either claim divine authority or deny it', 'They genuinely wanted to learn from Him', 'They wanted to invite Him to be a Pharisee', 'They were praising His teaching', 'a', 'Luke 20:1-2 — "The chief priests and the scribes came upon him with the elders, And spake unto him, saying, Tell us, by what authority doest thou these things? or who is he that gave thee this authority?"'),
('Luke', 20, 'teens', 2, 'How did Jesus turn the authority question back on the religious leaders?', 'He asked them whether John''s baptism was from heaven or from men — they could not answer without either validating John (and thus Jesus) or angering the people', 'He simply refused to speak', 'He answered their question directly', 'He asked them about Roman law', 'a', 'Luke 20:3-7 — "I will also ask you one thing... The baptism of John, was it from heaven, or of men? And they reasoned with themselves... they could not tell whence it was."'),
('Luke', 20, 'teens', 3, 'In the parable of the vineyard, what does the stone the builders rejected become?', 'The head of the corner — the cornerstone. Whoever falls on that stone will be broken, and whoever it falls on will be crushed', 'A stepping stone on the road', 'A decoration for the temple', 'A wall around the vineyard', 'a', 'Luke 20:17-18 — "The stone which the builders rejected, the same is become the head of the corner... Whosoever shall fall upon that stone shall be broken; but on whomsoever it shall fall, it will grind him to powder."'),
('Luke', 20, 'teens', 4, 'How did Jesus prove that the dead are raised using the account of Moses and the burning bush?', 'God said to Moses "I am the God of Abraham, Isaac, and Jacob" — using the present tense, showing they are still alive. He is not a God of the dead but of the living', 'Jesus quoted a psalm about resurrection', 'Jesus told a new parable about death', 'Jesus showed them a miracle', 'a', 'Luke 20:37-38 — "Now that the dead are raised, even Moses shewed at the bush, when he calleth the Lord the God of Abraham, and the God of Isaac, and the God of Jacob. For he is not a God of the dead, but of the living: for all live unto him."'),
('Luke', 20, 'teens', 5, 'What warning did Jesus give about the scribes?', 'Beware of the scribes who desire to walk in long robes, love greetings in the markets, seek the highest seats, and devour widows'' houses while making long prayers for a show', 'The scribes are the holiest people in Israel', 'The scribes always help the poor', 'The scribes are humble servants', 'a', 'Luke 20:46-47 — "Beware of the scribes, which desire to walk in long robes, and love greetings in the markets, and the highest seats in the synagogues, and the chief rooms at feasts; Which devour widows'' houses, and for a shew make long prayers: the same shall receive greater damnation."'),
-- Adults
('Luke', 20, 'adults', 1, 'How does the parable of the wicked husbandmen allegorically present Israel''s history of rejecting God''s messengers?', 'The vineyard is Israel, the owner is God, the husbandmen are Israel''s leaders, the servants are the prophets who were beaten and rejected, and the beloved son is Jesus — whose murder leads to the vineyard being given to others (Gentile inclusion)', 'The parable is about agricultural practices', 'The vineyard represents Rome', 'The son represents John the Baptist', 'a', 'Luke 20:9-16 — The progression from servants (prophets) to the beloved son (Christ) traces Israel''s escalating rejection. "He shall come and destroy these husbandmen, and shall give the vineyard to others" anticipates the transfer of kingdom privileges.'),
('Luke', 20, 'adults', 2, 'What does "the stone which the builders rejected is become the head of the corner" (Psalm 118:22) mean christologically?', 'Jesus, rejected by Israel''s religious leaders (the builders), becomes the foundation and cornerstone of God''s new building (the church) — the very one they discarded becomes the most important element of God''s redemptive plan', 'The stone refers to the temple building', 'The builders are the Romans', 'This psalm has no messianic meaning', 'a', 'Luke 20:17 — Jesus applies Psalm 118:22 to Himself. The "builders" (scribes, priests, elders) rejected the stone (Jesus) that God made the capstone. Peter later expands this in Acts 4:11 and 1 Peter 2:7.'),
('Luke', 20, 'adults', 3, 'What is the brilliance of Jesus'' answer about paying tribute to Caesar?', 'By asking whose image is on the coin, Jesus establishes a principle that transcends the trap: render to Caesar what bears his image (taxes), and to God what bears His image (your entire self, since humans are made in God''s image) — neither endorsing nor rejecting Roman authority', 'Jesus simply avoided the question', 'Jesus endorsed full support of Rome', 'Jesus told them not to pay taxes', 'a', 'Luke 20:24-25 — "Whose image and superscription hath it?... Render therefore unto Caesar the things which be Caesar''s, and unto God the things which be God''s." The deeper implication: if coins bearing Caesar''s image belong to Caesar, then people bearing God''s image belong to God.'),
('Luke', 20, 'adults', 4, 'How does Jesus'' argument from Exodus 3:6 prove the resurrection to the Sadducees?', 'God identifies Himself to Moses as "I am" (present tense) the God of Abraham, Isaac, and Jacob — long dead patriarchs. If God is the God of the living, not the dead, then the patriarchs must still be alive, implying resurrection. The argument rests on the tense of God''s self-revelation', 'Jesus quoted a passage the Sadducees did not accept', 'The argument depends on a Greek translation error', 'Jesus used a passage about death, not life', 'a', 'Luke 20:37-38 — Jesus strategically quotes from the Pentateuch (the only Scripture Sadducees accepted). The present-tense "I am" rather than "I was" their God implies the patriarchs'' ongoing existence and future resurrection.'),
('Luke', 20, 'adults', 5, 'What does Jesus'' question about David calling the Messiah "Lord" (Psalm 110:1) challenge?', 'It challenges the assumption that the Messiah is merely David''s descendant — if David calls Him "Lord," the Messiah must be greater than David, implying divine nature. The Messiah is both David''s son (human) and David''s Lord (divine)', 'Jesus was denying Davidic descent', 'Jesus was confused about the psalm', 'David never wrote Psalm 110', 'a', 'Luke 20:41-44 — "David himself calleth him Lord, how is he then his son?" Jesus does not deny Davidic descent but reveals it is insufficient — the Messiah transcends David. The answer: He is both human descendant and divine Lord.'),
('Luke', 20, 'adults', 6, 'What does "devouring widows'' houses" reveal about the scribes'' corruption?', 'They exploited vulnerable women — possibly through excessive legal fees for managing estates, manipulating widows into donating property to the temple (which the scribes controlled), or demanding hospitality. Their long prayers provided religious cover for economic exploitation', 'They literally ate at widows'' homes', 'This was a common and accepted practice', 'Only one scribe was guilty of this', 'a', 'Luke 20:47 — "Which devour widows'' houses, and for a shew make long prayers." The juxtaposition of devouring and praying is devastating: religious performance masking financial predation. This context sets up the widow''s mite story (21:1-4).'),
('Luke', 20, 'adults', 7, 'What is the significance of the spies being described as those who "feigned themselves just men" in verse 20?', 'It exposes the calculated dishonesty of Jesus'' opponents — they pretended to be sincere truth-seekers to trap Him in His words, planning to deliver Him to the governor''s authority. Their hypocrisy mirrors the very sin Jesus consistently condemned', 'The spies were genuinely righteous men', 'They were Roman soldiers in disguise', 'They were disciples of John the Baptist', 'a', 'Luke 20:20 — "And they watched him, and sent forth spies, which should feign themselves just men, that they might take hold of his words, that so they might deliver him unto the power and authority of the governor."'),
('Luke', 20, 'adults', 8, 'What does "whosoever shall fall upon that stone shall be broken; but on whomsoever it shall fall, it will grind him to powder" teach about responses to Christ?', 'There are two ways to encounter Christ: falling on the stone in humble brokenness (repentance and faith), or having the stone fall on you in judgment (destruction). Either way, no one can ignore or avoid Him — He is inescapable', 'The stone is literally dangerous', 'This only applies to builders', 'There is a third neutral option', 'a', 'Luke 20:18 — Drawing from Isaiah 8:14-15 (stone of stumbling) and Daniel 2:34-35 (stone that crushes kingdoms), Jesus presents Himself as the unavoidable rock: either you break yourself upon Him in repentance, or He breaks you in judgment.');

-- ═══ Luke Chapter 21 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Luke', 21, 'kids', 1, 'Who did Jesus say gave more than all the rich people at the temple?', 'A poor widow who put in two small mites — all the money she had to live on', 'The richest man in Jerusalem', 'The high priest', 'A Roman centurion', 'a', 'Luke 21:3-4 — "Of a truth I say unto you, that this poor widow hath cast in more than they all: For all these have of their abundance cast in unto the offerings of God: but she of her penury hath cast in all the living that she had."'),
('Luke', 21, 'kids', 2, 'What did Jesus say would happen to the beautiful temple?', 'Not one stone would be left on top of another — it would all be thrown down', 'It would become even bigger and more beautiful', 'It would last forever', 'It would be turned into a palace', 'a', 'Luke 21:6 — "As for these things which ye behold, the days will come, in the which there shall not be left one stone upon another, that shall not be thrown down."'),
('Luke', 21, 'kids', 3, 'What did Jesus promise about His words?', 'Heaven and earth shall pass away: but my words shall not pass away', 'His words are only for now', 'His words will change over time', 'His words apply only to Israel', 'a', 'Luke 21:33 — "Heaven and earth shall pass away: but my words shall not pass away."'),
-- Teens
('Luke', 21, 'teens', 1, 'Why did Jesus say the widow''s two mites were worth more than all the rich people''s gifts?', 'Because the rich gave out of their abundance, but she gave all the living that she had — God measures giving by sacrifice, not amount', 'Because two mites were worth more money', 'Because the widow was more famous', 'Because God only accepts small gifts', 'a', 'Luke 21:4 — "For all these have of their abundance cast in unto the offerings of God: but she of her penury hath cast in all the living that she had."'),
('Luke', 21, 'teens', 2, 'What signs did Jesus say would precede the destruction of Jerusalem?', 'Wars, rumours of wars, earthquakes, famines, pestilences, and fearful sights — but the end is not immediately', 'There would be no signs at all', 'Only one sign would appear', 'Jerusalem would become more peaceful', 'a', 'Luke 21:10-11 — "Nation shall rise against nation, and kingdom against kingdom: And great earthquakes shall be in divers places, and famines, and pestilences; and fearful sights and great signs shall there be from heaven."'),
('Luke', 21, 'teens', 3, 'What did Jesus promise His followers about persecution?', 'I will give you a mouth and wisdom, which all your adversaries shall not be able to gainsay nor resist', 'You will never face any persecution', 'You must prepare your own defence', 'Only educated followers will know what to say', 'a', 'Luke 21:15 — "For I will give you a mouth and wisdom, which all your adversaries shall not be able to gainsay nor resist."'),
('Luke', 21, 'teens', 4, 'What did Jesus say about Jerusalem being surrounded by armies?', 'When ye shall see Jerusalem compassed with armies, then know that the desolation thereof is nigh — those in Judaea should flee to the mountains', 'Fight against the armies and you will win', 'The armies are there to protect Jerusalem', 'Jerusalem will never be surrounded', 'a', 'Luke 21:20-21 — "And when ye shall see Jerusalem compassed with armies, then know that the desolation thereof is nigh. Then let them which are in Judaea flee to the mountains."'),
('Luke', 21, 'teens', 5, 'What instruction did Jesus give about watching and praying?', 'Watch ye therefore, and pray always, that ye may be accounted worthy to escape all these things that shall come to pass, and to stand before the Son of man', 'Watching and praying are optional', 'Only pray when things go wrong', 'Watch for signs but do not pray', 'a', 'Luke 21:36 — "Watch ye therefore, and pray always, that ye may be accounted worthy to escape all these things that shall come to pass, and to stand before the Son of man."'),
-- Adults
('Luke', 21, 'adults', 1, 'How does the widow''s mite story function as a commentary on the preceding condemnation of the scribes?', 'The widow exemplifies the victim of scribal exploitation (20:47 "devour widows'' houses") — she gives her last two coins to a corrupt temple system. Jesus does not praise the system but the widow''s heart, while implicitly condemning the institution that impoverished her', 'The two stories are completely unrelated', 'Jesus approved of the temple''s fundraising', 'The widow was wealthy despite appearances', 'a', 'Luke 21:1-4 — Read in context of 20:47, the widow''s gift is both beautiful (total devotion) and tragic (the temple devours her living). Jesus highlights her sacrificial faith while the reader sees the systemic injustice.'),
('Luke', 21, 'adults', 2, 'How does Luke''s Olivet Discourse differ from Matthew''s and Mark''s, particularly regarding Jerusalem?', 'Luke uniquely specifies "Jerusalem shall be trodden down of the Gentiles, until the times of the Gentiles be fulfilled" (v.24), explicitly describing the AD 70 destruction and subsequent Gentile domination — Luke separates the fall of Jerusalem from the end times more clearly than Matthew or Mark', 'All three accounts are identical', 'Luke omits the Olivet Discourse', 'Luke focuses only on end times, not Jerusalem', 'a', 'Luke 21:24 — Luke''s addition of "times of the Gentiles" introduces a distinct historical period between Jerusalem''s fall and Christ''s return, providing a clearer two-stage eschatology: near (AD 70) and far (second coming).'),
('Luke', 21, 'adults', 3, 'What does "this generation shall not pass away, till all be fulfilled" mean?', 'Most likely "this generation" refers to the generation alive during Jesus'' ministry that would witness the fall of Jerusalem in AD 70 — all the signs related to the temple''s destruction were fulfilled within approximately forty years', 'No generation will ever pass away', 'It refers to the final generation only', 'Jesus was wrong about the timing', 'a', 'Luke 21:32 — "This generation shall not pass away, till all be fulfilled." The most natural reading: the generation Jesus addressed (c. AD 30) would live to see Jerusalem''s destruction (AD 70) — within forty years. The second coming discourse extends beyond this.'),
('Luke', 21, 'adults', 4, 'What practical significance did Jesus'' warning about fleeing to the mountains have for the early church?', 'According to Eusebius (Church History 3.5.3), the Jerusalem Christians heeded this warning and fled to Pella in Transjordan before the Roman siege in AD 66-70, thereby escaping the destruction — demonstrating the prophetic accuracy and practical value of Jesus'' words', 'No Christians escaped Jerusalem', 'The warning was purely symbolic', 'Christians fought alongside the Romans', 'a', 'Luke 21:21 — "Then let them which are in Judaea flee to the mountains." The early church historian Eusebius records that the Jerusalem church, remembering this prophecy, fled across the Jordan to Pella when the Roman armies first appeared.'),
('Luke', 21, 'adults', 5, 'What does "the times of the Gentiles" refer to in salvation history?', 'The period during which Gentile nations exercise dominion over Jerusalem and Gentiles are the primary focus of gospel expansion — this era began with the temple''s destruction in AD 70 and continues until God''s purposes for the Gentile mission are complete', 'A specific three-year period', 'The time when Gentiles ruled before Christ', 'A reference to the Babylonian captivity only', 'a', 'Luke 21:24 — "Jerusalem shall be trodden down of the Gentiles, until the times of the Gentiles be fulfilled." This phrase, unique to Luke, marks a redemptive-historical epoch. Paul may reference the same concept in Romans 11:25 ("the fulness of the Gentiles").'),
('Luke', 21, 'adults', 6, 'What does "heaven and earth shall pass away: but my words shall not pass away" claim about Jesus'' teaching?', 'It claims eternal, absolute authority for Jesus'' words — placing them above the permanence of the created order itself. This is a claim that only God can make, since only God''s word endures forever (Isaiah 40:8)', 'Jesus was exaggerating for effect', 'Only some of His words will endure', 'Heaven and earth will never pass away', 'a', 'Luke 21:33 — "Heaven and earth shall pass away: but my words shall not pass away." This echoes Isaiah 40:8 ("The word of our God shall stand for ever"). By applying this to His own words, Jesus claims divine authority for His teaching.'),
('Luke', 21, 'adults', 7, 'What does "there shall not be left one stone upon another" predict about the temple?', 'Total destruction of the Jerusalem temple — fulfilled in AD 70 when Roman soldiers under Titus demolished the temple so thoroughly (partly to extract melted gold between stones) that the prophecy was literally fulfilled', 'Minor damage that would be repaired quickly', 'The stones would be rearranged', 'The temple would become stronger', 'a', 'Luke 21:6 — "There shall not be left one stone upon another, that shall not be thrown down." Josephus (Wars 7.1.1) confirms that Titus ordered the city and temple razed, with only three towers left standing as testimony to Roman conquest.'),
('Luke', 21, 'adults', 8, 'What does the fig tree parable in verses 29-31 teach about reading the signs?', 'Just as budding trees signal that summer is near, so the prophesied signs signal that the kingdom of God is near — believers should be watchful interpreters of events, recognising God''s unfolding plan without setting dates', 'Believers should plant fig trees', 'Only botanists can understand prophecy', 'Signs are meaningless and should be ignored', 'a', 'Luke 21:29-31 — "Behold the fig tree, and all the trees; When they now shoot forth, ye see and know of your own selves that summer is now nigh at hand. So likewise ye, when ye see these things come to pass, know ye that the kingdom of God is nigh at hand."');

-- ═══════════════ CHAPTERS 22–24 ═══════════════

-- ═══ Luke Chapter 22 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Luke', 22, 'kids', 1, 'What special meal did Jesus share with His disciples before He died?', 'The Last Supper — the Passover meal', 'A birthday party', 'A wedding feast', 'A harvest celebration', 'a', 'Luke 22:14-15 — "And when the hour was come, he sat down, and the twelve apostles with him. And he said unto them, With desire I have desired to eat this passover with you before I suffer."'),
('Luke', 22, 'kids', 2, 'Who betrayed Jesus with a kiss?', 'Judas', 'Peter', 'John', 'Thomas', 'a', 'Luke 22:47-48 — "And while he yet spake, behold a multitude, and he that was called Judas, one of the twelve, went before them, and drew near unto Jesus to kiss him. But Jesus said unto him, Judas, betrayest thou the Son of man with a kiss?"'),
('Luke', 22, 'kids', 3, 'What did Peter do when a girl said she recognised him as one of Jesus'' followers?', 'He denied knowing Jesus three times, just as Jesus had predicted', 'He proudly said yes', 'He ran away immediately', 'He asked her to be quiet', 'a', 'Luke 22:57 — "And he denied him, saying, Woman, I know him not." Peter denied Jesus three times before the cock crew (v.60-61).'),
-- Teens
('Luke', 22, 'teens', 1, 'What did Jesus say the bread and the cup represent at the Last Supper?', 'The bread is His body given for them, and the cup is the new testament (covenant) in His blood shed for them', 'The bread represents manna and the cup represents water from the rock', 'The bread is for the poor and the cup for the rich', 'They were simply a normal meal with no special meaning', 'a', 'Luke 22:19-20 — "This is my body which is given for you: this do in remembrance of me. Likewise also the cup after supper, saying, This cup is the new testament in my blood, which is shed for you."'),
('Luke', 22, 'teens', 2, 'What did Jesus pray in the Garden of Gethsemane?', 'Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done', 'Father, save me from my enemies', 'Father, make me the king of Israel', 'Father, destroy the Romans', 'a', 'Luke 22:42 — "Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done."'),
('Luke', 22, 'teens', 3, 'What happened to Jesus while He prayed in intense agony?', 'His sweat was as it were great drops of blood falling down to the ground', 'He fell asleep from exhaustion', 'He heard an audible voice from heaven', 'A strong wind blew through the garden', 'a', 'Luke 22:44 — "And being in an agony he prayed more earnestly: and his sweat was as it were great drops of blood falling down to the ground."'),
('Luke', 22, 'teens', 4, 'What did Jesus do when one of His followers cut off the ear of the high priest''s servant?', 'He touched the man''s ear and healed him — even while being arrested, Jesus showed mercy', 'He praised the disciple for defending Him', 'He told the soldiers to leave', 'He did nothing about the injury', 'a', 'Luke 22:51 — "And Jesus answered and said, Suffer ye thus far. And he touched his ear, and healed him."'),
('Luke', 22, 'teens', 5, 'What happened after Peter denied Jesus the third time?', 'The cock crew, and the Lord turned and looked upon Peter — and Peter went out and wept bitterly', 'Peter fell asleep', 'Peter ran to the temple to pray', 'Nothing happened at all', 'a', 'Luke 22:60-62 — "And immediately, while he yet spake, the cock crew. And the Lord turned, and looked upon Peter. And Peter remembered the word of the Lord... And Peter went out, and wept bitterly."'),
-- Adults
('Luke', 22, 'adults', 1, 'What is the significance of Jesus saying "This cup is the new testament in my blood"?', 'Jesus establishes the New Covenant prophesied by Jeremiah 31:31-34 — His blood ratifies a new covenantal relationship between God and humanity, replacing the old covenant sealed at Sinai with animal blood. The Lord''s Supper is the ongoing sign of this covenant', 'Jesus was simply being poetic', 'The cup had no theological significance', 'This was a standard Passover blessing', 'a', 'Luke 22:20 — "This cup is the new testament in my blood, which is shed for you." The word "testament" (diatheke) means covenant. Just as the Mosaic covenant was sealed with blood (Exodus 24:8), the new covenant is sealed with Christ''s blood.'),
('Luke', 22, 'adults', 2, 'What does Jesus'' statement "I have desired with desire to eat this passover with you before I suffer" reveal?', 'The emphatic Hebraism ("desired with desire") shows intense longing — Jesus approached the cross deliberately and willingly, and saw this Passover meal as the fulfilment of all previous Passovers, connecting His death to the Exodus deliverance', 'Jesus simply enjoyed the food', 'He was uncertain about what would happen', 'This was His first Passover celebration', 'a', 'Luke 22:15 — The Hebraic construction "epithumia epethumesa" (desired with desire) is intensely emphatic. Jesus eagerly anticipated this meal because it was the hinge of salvation history: the true Paschal lamb about to be slain.'),
('Luke', 22, 'adults', 3, 'What does the dispute about which disciple would be greatest (vv. 24-27) reveal, and how does Jesus redefine greatness?', 'Even at the Last Supper, the disciples disputed precedence — Jesus redefines greatness as servanthood: "he that is greatest among you, let him be as the younger; and he that is chief, as he that doth serve. I am among you as he that serveth"', 'Jesus endorsed their competition', 'Greatness means having the most power', 'The dispute never actually happened', 'a', 'Luke 22:26-27 — "He that is greatest among you, let him be as the younger; and he that is chief, as he that doth serve... I am among you as he that serveth." Jesus uses His own servanthood (cf. John 13 foot-washing) as the model for all leadership.'),
('Luke', 22, 'adults', 4, 'What is the theological significance of Jesus'' prayer "not my will, but thine, be done"?', 'It reveals the genuine human will of Jesus recoiling from the cross while His divine submission to the Father''s plan remained resolute — the Gethsemane prayer affirms both the reality of Jesus'' human suffering and the triumph of obedient surrender', 'Jesus was undecided about His mission', 'The Father forced Jesus against His will', 'Jesus felt no real anguish about the cross', 'a', 'Luke 22:42 — "Father, if thou be willing, remove this cup from me: nevertheless not my will, but thine, be done." The prayer holds together genuine human dread and willing divine obedience, making it the ultimate model of submission to God''s will.'),
('Luke', 22, 'adults', 5, 'What is "hematohidrosis" (sweating blood), and what does Luke 22:44 indicate about Jesus'' suffering?', 'Hematohidrosis is a rare medical condition where extreme stress causes blood to seep through sweat glands — Luke the physician uniquely records this detail, emphasising the intensity of Jesus'' spiritual anguish as He bore the weight of humanity''s sin in anticipation of the cross', 'Jesus was not actually sweating blood', 'This is a common occurrence in prayer', 'Luke was using a figure of speech only', 'a', 'Luke 22:44 — "His sweat was as it were great drops of blood." The phrase "as it were" (hosei) could be simile, but the medical phenomenon (hematohidrosis) is documented under extreme stress. Luke the physician (Colossians 4:14) may be recording clinical observation.'),
('Luke', 22, 'adults', 6, 'What is the significance of "the Lord turned, and looked upon Peter" after the third denial?', 'This detail, unique to Luke, shows Jesus'' awareness even during His own trial — the look was not of condemnation but of sorrow and love, breaking Peter''s heart and fulfilling the prediction. It is a wordless exchange that speaks volumes about Christ''s compassion toward failing disciples', 'Jesus was angry at Peter', 'Jesus did not notice Peter''s denial', 'Peter was not affected by the look', 'a', 'Luke 22:61 — "And the Lord turned, and looked upon Peter." Only Luke records this devastating, tender detail. In the midst of His own suffering, Jesus looks at Peter — triggering Peter''s memory and bitter repentance. The look saved Peter.'),
('Luke', 22, 'adults', 7, 'What does Jesus'' warning "Simon, Simon, behold, Satan hath desired to have you, that he may sift you as wheat" reveal about spiritual warfare?', 'Satan actively seeks to test and destroy believers'' faith, but Jesus intercedes for them — "I have prayed for thee, that thy faith fail not." Peter would fall (deny Jesus) but not fall away permanently because of Christ''s intercessory prayer', 'Satan has no interest in believers', 'Jesus did not pray for Peter', 'Peter''s faith was never in danger', 'a', 'Luke 22:31-32 — "Satan hath desired to have you, that he may sift you as wheat: But I have prayed for thee, that thy faith fail not: and when thou art converted, strengthen thy brethren." Christ''s intercession is the guarantee that failure is not final for His own.'),
('Luke', 22, 'adults', 8, 'How does Jesus'' healing of Malchus'' ear during His arrest demonstrate His character?', 'It is His last miracle before the cross — performed for an enemy who came to arrest Him. Even in the moment of betrayal and violence, Jesus demonstrates the love for enemies He preached (6:27-35), showing that His teaching and His life were perfectly consistent', 'It was an accidental healing', 'Jesus healed the ear to avoid trouble', 'This miracle is not recorded in Luke', 'a', 'Luke 22:51 — "And he touched his ear, and healed him." Only Luke records this healing, fitting his physician''s interest and his theme of Jesus'' compassion. Jesus'' final pre-passion miracle heals a wound caused by a disciple''s violence — undoing harm and showing mercy to an enemy.');

-- ═══ Luke Chapter 23 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Luke', 23, 'kids', 1, 'What did Jesus pray for the soldiers who nailed Him to the cross?', 'Father, forgive them; for they know not what they do', 'Father, punish them for hurting me', 'Father, send angels to save me', 'Father, let me come home now', 'a', 'Luke 23:34 — "Then said Jesus, Father, forgive them; for they know not what they do."'),
('Luke', 23, 'kids', 2, 'What did Jesus promise the thief on the cross who believed in Him?', 'To day shalt thou be with me in paradise', 'You will be king one day', 'You will escape from the cross', 'I cannot help you now', 'a', 'Luke 23:43 — "And Jesus said unto him, Verily I say unto thee, To day shalt thou be with me in paradise."'),
('Luke', 23, 'kids', 3, 'What happened in the sky while Jesus was on the cross?', 'Darkness covered the whole land for three hours, from noon until three o''clock', 'A bright rainbow appeared', 'The sun became very hot', 'Stars appeared during the daytime', 'a', 'Luke 23:44-45 — "And it was about the sixth hour, and there was a darkness over all the earth until the ninth hour. And the sun was darkened."'),
-- Teens
('Luke', 23, 'teens', 1, 'What did Pilate say about Jesus after examining Him?', 'I find no fault in this man — Pilate declared Jesus innocent three times', 'He is guilty of everything they say', 'He deserves to die', 'He is a dangerous criminal', 'a', 'Luke 23:4 — "Then said Pilate to the chief priests and to the people, I find no fault in this man." Pilate declares Jesus innocent three times (vv. 4, 14, 22).'),
('Luke', 23, 'teens', 2, 'How did the two thieves on the cross respond differently to Jesus?', 'One mocked Him saying "save thyself and us," but the other rebuked the first and asked Jesus to remember him in His kingdom — showing faith even at the point of death', 'Both thieves mocked Jesus', 'Both thieves believed in Jesus', 'Neither thief spoke to Jesus', 'a', 'Luke 23:39-42 — One thief railed on Him, but the other said, "Lord, remember me when thou comest into thy kingdom." The contrast between the two thieves represents the two responses all humanity makes to Christ.'),
('Luke', 23, 'teens', 3, 'What were Jesus'' last words on the cross according to Luke?', 'Father, into thy hands I commend my spirit', 'It is finished', 'My God, why hast thou forsaken me', 'I am thirsty', 'a', 'Luke 23:46 — "And when Jesus had cried with a loud voice, he said, Father, into thy hands I commend my spirit: and having said thus, he gave up the ghost."'),
('Luke', 23, 'teens', 4, 'What did the Roman centurion say after watching Jesus die?', 'Certainly this was a righteous man — even a Roman soldier recognised Jesus'' innocence', 'This man was a criminal', 'We did the right thing', 'Nothing significant happened here', 'a', 'Luke 23:47 — "Now when the centurion saw what was done, he glorified God, saying, Certainly this was a righteous man."'),
('Luke', 23, 'teens', 5, 'Who took Jesus'' body down from the cross and placed it in a tomb?', 'Joseph of Arimathaea — a good and just man who was a member of the council but had not consented to their decision', 'The Roman soldiers', 'The disciples Peter and John', 'Mary Magdalene', 'a', 'Luke 23:50-53 — "And, behold, there was a man named Joseph, a counsellor; and he was a good man, and a just... he went unto Pilate, and begged the body of Jesus. And he took it down, and wrapped it in linen, and laid it in a sepulchre."'),
-- Adults
('Luke', 23, 'adults', 1, 'What is the theological significance of Jesus'' prayer "Father, forgive them; for they know not what they do"?', 'Unique to Luke, this prayer fulfils Isaiah 53:12 ("made intercession for the transgressors") and embodies Jesus'' own teaching to love enemies and pray for persecutors (Luke 6:27-28). Jesus practises on the cross what He preached in His ministry', 'Jesus was confused about what was happening', 'This prayer was only for the Roman soldiers', 'The prayer has been added by later editors', 'a', 'Luke 23:34 — "Father, forgive them; for they know not what they do." This is the ultimate fulfilment of His own command (6:28: "pray for them which despitefully use you") and Isaiah 53:12 (intercessor for transgressors).'),
('Luke', 23, 'adults', 2, 'What does Pilate''s threefold declaration of Jesus'' innocence (vv. 4, 14, 22) accomplish in Luke''s narrative?', 'It establishes beyond doubt that Jesus was legally innocent — His death was not for His own crimes but a miscarriage of justice, supporting the theological truth that He died as the sinless substitute. Luke, writing for a Roman audience, also shows Christianity was not founded by a criminal', 'Pilate was an unreliable witness', 'It shows Pilate was secretly a Christian', 'The declarations are contradictory', 'a', 'Luke 23:4,14,22 — Three declarations of innocence from the Roman governor — the highest legal authority — constitute an official legal verdict. For Luke''s Gentile readers, this clears Christianity of the charge that its founder was a justly executed criminal.'),
('Luke', 23, 'adults', 3, 'What does the repentant thief''s faith reveal about the nature of salvation?', 'Salvation is by grace through faith alone, even at the last moment — the thief had no works, no baptism, no church membership, and no time to prove his faith, yet Jesus guaranteed him paradise. This is the purest example of justification by faith', 'The thief earned salvation through suffering', 'The thief had been secretly righteous', 'Deathbed conversions are never genuine', 'a', 'Luke 23:42-43 — "Lord, remember me when thou comest into thy kingdom. And Jesus said unto him, Verily I say unto thee, To day shalt thou be with me in paradise." The thief demonstrates saving faith: acknowledging his own guilt, recognising Jesus'' innocence and kingship, and trusting Him for mercy.'),
('Luke', 23, 'adults', 4, 'What does "To day shalt thou be with me in paradise" teach about the intermediate state?', 'Immediately after death, the believer is consciously present with Christ in paradise — ruling out soul sleep, purgatory, and annihilationism. "Today" means that very day, and "with me" means conscious fellowship with Christ', 'The soul sleeps until the final resurrection', 'Paradise is on earth', 'Today means sometime in the distant future', 'a', 'Luke 23:43 — "Today" (semeron) is emphatic: not eventually, not after a waiting period, but that same day. "With me" ensures personal, conscious presence with Christ. Paradise (from the Persian for "garden/park") denotes the blessed abode of the righteous dead.'),
('Luke', 23, 'adults', 5, 'What does the three-hour darkness (noon to 3 PM) during the crucifixion signify?', 'Supernatural darkness signals divine judgment — echoing the plague of darkness in Egypt (Exodus 10:22) and prophesied in Amos 8:9 ("I will cause the sun to go down at noon, and I will darken the earth in the clear day"). Creation itself mourns as the Creator dies', 'It was a natural solar eclipse', 'The darkness had no significance', 'It was simply cloudy weather', 'a', 'Luke 23:44-45 — "There was a darkness over all the earth... And the sun was darkened." A solar eclipse is impossible during Passover (full moon). This is supernatural darkness, recalling Joel 2:31 and Amos 8:9, marking cosmic significance.'),
('Luke', 23, 'adults', 6, 'What is the significance of the temple veil being rent in two?', 'The veil separating the Holy of Holies from the outer temple was torn from top to bottom, signifying that through Christ''s death, access to God''s presence is opened for all people — the barrier between God and humanity is removed', 'The veil was old and simply fell apart', 'The earthquake caused the tear', 'The priests tore it during mourning', 'a', 'Luke 23:45 — "And the veil of the temple was rent in the midst." The veil (60 feet tall, according to Josephus) being torn "from the top to the bottom" (Matthew 27:51) indicates divine action. Hebrews 10:19-20 interprets this: Christ''s flesh is the new way into God''s presence.'),
('Luke', 23, 'adults', 7, 'What does Jesus'' final words "Father, into thy hands I commend my spirit" (Psalm 31:5) reveal about His death?', 'Jesus dies in perfect trust and voluntary surrender — He quotes Psalm 31:5 (adding "Father" to the psalm), showing His death is not a defeat but a deliberate, faith-filled act of entrusting Himself to God. He dies as He lived: in communion with the Father', 'Jesus died against His will', 'These were words of despair', 'Jesus was quoting a secular poem', 'a', 'Luke 23:46 — "Father, into thy hands I commend my spirit." Luke''s final word from the cross differs from Matthew/Mark ("My God, why...") and John ("It is finished"). Luke''s choice emphasises trusting surrender, consistent with his portrait of Jesus as the model of faith.'),
('Luke', 23, 'adults', 8, 'How does Luke''s centurion declaration ("Certainly this was a righteous man") differ from Matthew/Mark ("the Son of God"), and what is its significance?', 'Luke uses "righteous" (dikaios) rather than "Son of God" — fitting Luke''s theme of Jesus as the innocent sufferer (Isaiah''s righteous servant). A Roman soldier''s testimony of innocence carries legal weight and anticipates the Gentile acceptance of the gospel in Acts', 'The centurion said the same thing in all Gospels', 'Luke''s version is less significant', 'The centurion did not mean what he said', 'a', 'Luke 23:47 — "Certainly this was a righteous man." Luke''s word choice fits his consistent emphasis on Jesus'' innocence (three Pilate declarations + centurion). "Righteous" connects to Isaiah''s Suffering Servant (Isaiah 53:11: "my righteous servant") and previews Gentile faith.');

-- ═══ Luke Chapter 24 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Luke', 24, 'kids', 1, 'What did the angels at the empty tomb say to the women?', 'Why seek ye the living among the dead? He is not here, but is risen', 'The body has been stolen', 'Come back tomorrow', 'You have come to the wrong place', 'a', 'Luke 24:5-6 — "Why seek ye the living among the dead? He is not here, but is risen."'),
('Luke', 24, 'kids', 2, 'What happened when the risen Jesus walked with two people on the road to Emmaus?', 'They did not recognise Him at first, but their hearts burned within them as He explained the Scriptures', 'They recognised Him immediately', 'They were afraid and ran away', 'Jesus was invisible the whole time', 'a', 'Luke 24:16,32 — "But their eyes were holden that they should not know him... Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures?"'),
('Luke', 24, 'kids', 3, 'What did Jesus do at the very end of Luke''s Gospel?', 'He blessed His disciples and was carried up into heaven', 'He stayed with the disciples forever', 'He went on a long journey', 'He went to sleep in a garden', 'a', 'Luke 24:50-51 — "And he led them out as far as to Bethany, and he lifted up his hands, and blessed them. And it came to pass, while he blessed them, he was parted from them, and carried up into heaven."'),
-- Teens
('Luke', 24, 'teens', 1, 'Who were the first to discover the empty tomb?', 'Women — including Mary Magdalene, Joanna, Mary the mother of James, and others who had followed Jesus from Galilee', 'Peter and John', 'The Roman guards', 'The chief priests', 'a', 'Luke 24:1,10 — "Now upon the first day of the week, very early in the morning, they came unto the sepulchre... It was Mary Magdalene, and Joanna, and Mary the mother of James, and other women that were with them."'),
('Luke', 24, 'teens', 2, 'How did the apostles initially react to the women''s report of the resurrection?', 'Their words seemed to them as idle tales, and they believed them not', 'They immediately believed and celebrated', 'They went to the tomb together', 'They wrote down everything carefully', 'a', 'Luke 24:11 — "And their words seemed to them as idle tales, and they believed them not."'),
('Luke', 24, 'teens', 3, 'What did Jesus do to prove He was real and not a ghost?', 'He showed them His hands and feet, and ate a piece of broiled fish in front of them', 'He walked through walls repeatedly', 'He made Himself invisible', 'He turned water into wine', 'a', 'Luke 24:39-43 — "Behold my hands and my feet, that it is I myself: handle me, and see; for a spirit hath not flesh and bones, as ye see me have... And he took it, and did eat before them."'),
('Luke', 24, 'teens', 4, 'What did Jesus say must be preached to all nations?', 'Repentance and remission of sins should be preached in His name among all nations, beginning at Jerusalem', 'A new set of laws for every country', 'The destruction of all temples', 'That everyone should come to Jerusalem', 'a', 'Luke 24:47 — "And that repentance and remission of sins should be preached in his name among all nations, beginning at Jerusalem."'),
('Luke', 24, 'teens', 5, 'What did Jesus tell the disciples to wait for in Jerusalem?', 'The promise of the Father — power from on high (the Holy Spirit)', 'A new temple to be built', 'A political leader to help them', 'More money for their mission', 'a', 'Luke 24:49 — "And, behold, I send the promise of my Father upon you: but tarry ye in the city of Jerusalem, until ye be endued with power from on high."'),
-- Adults
('Luke', 24, 'adults', 1, 'What is the theological significance of the angel''s question "Why seek ye the living among the dead?"', 'It reframes the resurrection as the fundamental reality — Jesus does not belong to the realm of the dead. The question gently rebukes the women''s expectation of finding a corpse and announces that death could not contain the Author of life', 'It was a standard greeting at tombs', 'The angel was confused about the location', 'This question was meant only for the women', 'a', 'Luke 24:5 — "Why seek ye the living among the dead?" The question implies a category error: seeking Jesus among the dead misunderstands who He is. He is "the living" (ho zon) — a title that echoes "the living God" throughout the OT.'),
('Luke', 24, 'adults', 2, 'What does the Emmaus road account reveal about how Jesus interpreted the Old Testament?', 'Beginning at Moses and all the prophets, Jesus expounded in all the Scriptures the things concerning Himself — showing that the entire Old Testament is Christocentric. The Law, Prophets, and Psalms all point to Christ''s suffering and glorification', 'Jesus only discussed a few passages', 'The Old Testament is not about Jesus', 'Jesus was teaching geography, not theology', 'a', 'Luke 24:27 — "And beginning at Moses and all the prophets, he expounded unto them in all the scriptures the things concerning himself." This is the hermeneutical key: all Scripture converges on Christ. His suffering and glory are the unifying theme.'),
('Luke', 24, 'adults', 3, 'What does "their eyes were holden that they should not know him" and later "their eyes were opened" suggest about recognising the risen Christ?', 'Recognition of the risen Christ is divinely mediated — God both restrains and opens eyes. The Emmaus disciples could not recognise Jesus through physical sight alone; their eyes were opened during the breaking of bread, suggesting that Christ is known through Scripture and sacrament', 'Jesus was wearing a disguise', 'The disciples had poor eyesight', 'It was too dark to see clearly', 'a', 'Luke 24:16,31 — "Their eyes were holden" (divine passive) and "their eyes were opened" — both are divine actions. Recognition came at the breaking of bread (v.30-31), combining word (v.27) and sacrament. This pattern shapes Christian worship.'),
('Luke', 24, 'adults', 4, 'What does "Did not our heart burn within us" tell us about the effect of Christ-centred Scripture exposition?', 'When Scripture is expounded with Christ as the centre, hearts burn with conviction, understanding, and worship — the emotional response ("burning hearts") is the fruit of illuminated minds encountering living truth. True preaching produces both heat (affection) and light (understanding)', 'They had indigestion', 'The burning was physical from the sun', 'Heart-burning is a negative sign', 'a', 'Luke 24:32 — "Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures?" The burning heart is the Spirit-wrought response to Christ revealed in Scripture — the standard for all Christian preaching and Bible study.'),
('Luke', 24, 'adults', 5, 'What does Jesus'' physical resurrection body — showing wounds, eating fish — teach about the nature of the resurrection?', 'The resurrection is physical and bodily, not merely spiritual — Jesus has "flesh and bones" (v.39), bears recognisable scars, and eats food, yet can also appear and vanish. The resurrection body is continuous with the earthly body but transformed and glorified', 'The resurrection was purely spiritual', 'Jesus was a ghost or apparition', 'The body had no connection to His earthly form', 'a', 'Luke 24:39-43 — "A spirit hath not flesh and bones, as ye see me have... And he took it, and did eat before them." Jesus explicitly refutes a purely spiritual resurrection. His body is real, tangible, and continuous with the crucified body (wounds visible), yet glorified.'),
('Luke', 24, 'adults', 6, 'What does "then opened he their understanding, that they might understand the scriptures" reveal about biblical interpretation?', 'Understanding Scripture ultimately requires divine illumination — even those who had walked with Jesus for years needed their minds opened by Christ to comprehend how Moses, the Prophets, and the Psalms all pointed to His death and resurrection', 'Human intelligence alone is sufficient', 'Only scholars can understand the Bible', 'Scripture is deliberately obscure', 'a', 'Luke 24:45 — "Then opened he their understanding, that they might understand the scriptures." The divine passive confirms that comprehension of Scripture is a gift. The same Christ who opened the Scriptures on the Emmaus road opens minds to receive them.'),
('Luke', 24, 'adults', 7, 'How does Luke''s Gospel end, and how does this ending set up the book of Acts?', 'Luke ends with Jesus'' ascension from Bethany and the disciples'' great joy and continual worship in the temple — this ending is simultaneously the beginning of Acts, where the ascension is retold (Acts 1:9) and the promise of the Spirit (Luke 24:49) is fulfilled at Pentecost (Acts 2)', 'Luke''s Gospel has no clear ending', 'Acts is unrelated to Luke''s Gospel', 'The ascension only appears in Acts', 'a', 'Luke 24:49-53 — "Tarry ye in the city of Jerusalem, until ye be endued with power from on high... they were continually in the temple, praising and blessing God." This creates a narrative bridge to Acts 1-2, making Luke-Acts a unified two-volume work.'),
('Luke', 24, 'adults', 8, 'What is the complete Christological hermeneutic Jesus establishes in verses 44-47?', 'All three divisions of the Hebrew Bible — the Law of Moses, the Prophets, and the Psalms (Writings) — must be fulfilled in Christ: His suffering, resurrection on the third day, and the preaching of repentance and remission of sins to all nations. This is the definitive framework for interpreting the Old Testament', 'Only the Prophets point to Christ', 'The Old Testament is purely historical', 'Jesus only referenced the Psalms', 'a', 'Luke 24:44-47 — "All things must be fulfilled, which were written in the law of Moses, and in the prophets, and in the psalms, concerning me... Thus it is written, and thus it behoved Christ to suffer, and to rise from the dead the third day." Jesus establishes the threefold OT as a Christological witness.');
