-- Acts 27 — The Voyage to Rome and the Shipwreck at Malta
-- Theme: Be of Good Cheer — God Keeps His Word Through the Storm

INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 27,
  'Acts 27 is Scripture''s most sustained nautical narrative — Luke''s eye-witness log of Paul''s sea voyage from Caesarea toward Rome (autumn AD 59/60). Under the centurion Julius of the Augustan band, the party boards an Adramyttian coaster, touches Sidon, sails under the lee of Cyprus against contrary winds, crosses the Cilician and Pamphylian sea, and at Myra in Lycia transships to an Alexandrian grain freighter bound for Italy. Slow progress past Cnidus forces them under Crete to Fair Havens. The fast (Day of Atonement) has passed; sailing is now dangerous. Paul warns of loss to cargo, ship, and life, but the centurion trusts the master and owner; the majority vote to press on to Phenice. A soft south wind deceives them — and then Euroclydon, a typhoon from the north-east, seizes the ship. They undergird the hull with cables, fear the Syrtis, strike sail, jettison cargo and tackle; for fourteen days neither sun nor stars appear in Adria and all hope is abandoned. Then Paul stands forth: an angel of the God whom he serves has stood by him in the night, saying, "Fear not, Paul; thou must be brought before Caesar; and, lo, God hath given thee all them that sail with thee." The promise governs the chapter. Near midnight the soundings drop from twenty to fifteen fathoms; four anchors are cast from the stern; the sailors attempt to escape by the boat and Paul''s warning saves them — "Except these abide in the ship, ye cannot be saved." At dawn Paul breaks bread before them all — two hundred threescore and sixteen souls — gives thanks, and they eat. They cut anchors, loose the rudder-bands, hoist the foresail, and strike a place where two seas meet. The forepart wedges fast; the stern breaks up in the surf. The soldiers would kill the prisoners, but Julius, willing to save Paul, keeps them back; swimmers lead, the rest cling to boards and broken timbers — "and so it came to pass, that they escaped all safe to land."',
  'Be of Good Cheer — God Keeps His Word Through the Storm',
  'εὐθυμεῖν',
  'to be of good cheer (euthymein) — the apostolic courage that holds when sun and stars are hid (v.22, v.25, v.36).',
  '[{"range":"vv.1-8","title":"Caesarea to Fair Havens: a Slow Voyage Against the Wind"},{"range":"vv.9-12","title":"Paul''s First Warning; the Majority Votes for Phenice"},{"range":"vv.13-20","title":"Euroclydon: the Storm Strips Ship and Hope"},{"range":"vv.21-26","title":"Paul''s Angelic Vision: the Promise of Caesar and Salvage"},{"range":"vv.27-32","title":"Soundings in Adria; the Sailors'' Escape Foiled"},{"range":"vv.33-38","title":"Dawn Breakfast: Thanksgiving Before Two Hundred Seventy-Six Souls"},{"range":"vv.39-44","title":"Shipwreck on Malta: All Safe to Land"}]'::jsonb
FROM books b WHERE b.name = 'Acts'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  overview = EXCLUDED.overview,
  theme = EXCLUDED.theme,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'And when it was determined that we should sail into Italy, they delivered Paul and certain other prisoners unto one named Julius, a centurion of Augustus'' band.',
      'Ὡς δὲ ἐκρίθη τοῦ ἀποπλεῖν ἡμᾶς εἰς τὴν Ἰταλίαν, παρεδίδουν τόν τε Παῦλον καί τινας ἑτέρους δεσμώτας ἑκατοντάρχῃ ὀνόματι Ἰουλίῳ σπείρης Σεβαστῆς.',
      'Hōs de ekrithē tou apoplein hēmas eis tēn Italian, paredidoun ton te Paulon kai tinas heterous desmōtas hekatontarchē onomati Iouliō speirēs Sebastēs.',
      'The "we" narrative resumes after a two-year Caesarean gap (24:27). "Augustus'' band" (σπείρα Σεβαστή) was a cohort named for the emperor, probably the Cohors I Augusta attested by inscription in Syria. Julius is the fourth centurion Luke commends (cf. 10:1; 22:26; 23:17).',
      'God moves His servant toward Caesar through a Roman officer. Even prisoner transport is a divinely-ordained stage of apostolic ministry.'),
  (2, 'And entering into a ship of Adramyttium, we launched, meaning to sail by the coasts of Asia; one Aristarchus, a Macedonian of Thessalonica, being with us.',
      'Ἐπιβάντες δὲ πλοίῳ Ἀδραμυττηνῷ, μέλλοντες πλεῖν τοὺς κατὰ τὴν Ἀσίαν τόπους, ἀνήχθημεν, ὄντος σὺν ἡμῖν Ἀριστάρχου Μακεδόνος Θεσσαλονικέως.',
      'Epibantes de ploiō Adramyttēnō, mellontes plein tous kata tēn Asian topous, anēchthēmen, ontos syn hēmin Aristarchou Makedonos Thessalonikeōs.',
      'Adramyttium was a port of Mysia on the Aegean; its ship was a coaster returning home. Aristarchus (19:29; 20:4; Col 4:10; Philem 24) travels as Paul''s "fellowprisoner" — likely having indentured himself as Paul''s slave-companion to gain boarding rights.',
      'True brotherhood endures chains. Aristarchus'' name in the roll calls is a monument to love that remains when ministry grows costly.'),
  (3, 'And the next day we touched at Sidon. And Julius courteously entreated Paul, and gave him liberty to go unto his friends to refresh himself.',
      'Τῇ τε ἑτέρᾳ κατήχθημεν εἰς Σιδῶνα· φιλανθρώπως τε ὁ Ἰούλιος τῷ Παύλῳ χρησάμενος ἐπέτρεψε πρὸς τοὺς φίλους πορευθέντα ἐπιμελείας τυχεῖν.',
      'Tē te hetera katēchthēmen eis Sidōna; philanthrōpōs te ho Ioulios tō Paulō chrēsamenos epetrepsen pros tous philous poreuthenta epimeleias tychein.',
      'Sidon lay ~70 miles north of Caesarea — a day''s sail with favourable wind. "Courteously" (φιλανθρώπως) renders the Greek ideal of humane treatment. A Sidonian church is presumed, probably founded by the scattering of Acts 11:19.',
      'God gives His servants shepherds in officers'' uniforms. Christian friendship and pagan courtesy combine to refresh the weary apostle.'),
  (4, 'And when we had launched from thence, we sailed under Cyprus, because the winds were contrary.',
      'Κἀκεῖθεν ἀναχθέντες ὑπεπλεύσαμεν τὴν Κύπρον, διὰ τὸ τοὺς ἀνέμους εἶναι ἐναντίους.',
      'Kakeithen anachthentes hypepleusamen tēn Kypron, dia to tous anemous einai enantious.',
      '"Sailed under" (ὑπεπλεύσαμεν) = tracked along the lee. Prevailing Etesian north-westerlies forced them east of Cyprus rather than the open route west of it.',
      'The same Lord who once calmed wind and sea now ordains a contrary wind that lengthens the voyage. Providence uses headwinds as surely as tailwinds.'),
  (5, 'And when we had sailed over the sea of Cilicia and Pamphylia, we came to Myra, a city of Lycia.',
      'Τό τε πέλαγος τὸ κατὰ τὴν Κιλικίαν καὶ Παμφυλίαν διαπλεύσαντες, κατήλθομεν εἰς Μύρα τῆς Λυκίας.',
      'To te pelagos to kata tēn Kilikian kai Pamphylian diapleusantes, katēlthomen eis Myra tēs Lykias.',
      'Myra (modern Demre) was a principal harbour for the Alexandrian grain fleet. Its landlocked port at Andriake was the transshipment centre for the Rome run.',
      'The stages of every voyage are measured in the counsel of God. The Lord charts the coastline even when His servants do not see it.'),
  (6, 'And there the centurion found a ship of Alexandria sailing into Italy; and he put us therein.',
      'Κἀκεῖ εὑρὼν ὁ ἑκατόνταρχος πλοῖον Ἀλεξανδρινὸν πλέον εἰς τὴν Ἰταλίαν, ἐνεβίβασεν ἡμᾶς εἰς αὐτό.',
      'Kakei heurōn ho hekatontarchos ploion Alexandrinon pleon eis tēn Italian, enebibasen hēmas eis auto.',
      'Alexandrian vessels were the massive Egyptian grain ships supplying Rome — some 180 feet long, 270 tons. The Roman government chartered these private freighters; Julius had authority to requisition passage.',
      'God uses commercial infrastructure to move His messengers. The grain ship of empire becomes the carrier of the gospel to Caesar''s capital.'),
  (7, 'And when we had sailed slowly many days, and scarce were come over against Cnidus, the wind not suffering us, we sailed under Crete, over against Salmone;',
      'Ἐν ἱκαναῖς δὲ ἡμέραις βραδυπλοοῦντες καὶ μόλις γενόμενοι κατὰ τὴν Κνίδον, μὴ προσεῶντος ἡμᾶς τοῦ ἀνέμου, ὑπεπλεύσαμεν τὴν Κρήτην κατὰ Σαλμώνην·',
      'En hikanais de hēmerais bradyploountes kai molis genomenoi kata tēn Knidon, mē proseōntos hēmas tou anemou, hypepleusamen tēn Krētēn kata Salmōnēn;',
      'Cnidus was a peninsula at the south-west corner of Asia Minor; from there westbound ships expected an open run to Greece. The wind''s refusal forced them south under Crete at Salmone (Cape Sidero).',
      'Delay and detour are the Lord''s pedagogy. Slow voyages teach waiting on God as surely as swift ones teach gratitude.'),
  (8, 'And, hardly passing it, came unto a place which is called The fair havens; nigh whereunto was the city of Lasea.',
      'Μόλις τε παραλεγόμενοι αὐτὴν ἤλθομεν εἰς τόπον τινὰ καλούμενον Καλοὺς Λιμένας, ᾧ ἐγγὺς ἦν πόλις Λασαία.',
      'Molis te paralegomenoi autēn ēlthomen eis topon tina kaloumenon Kalous Limenas, hō engys ēn polis Lasaia.',
      'Fair Havens (Καλοὶ Λιμένες, still so named today) lies on Crete''s south coast near Cape Matala. Lasea is attested on early-19th-century ruins east of Fair Havens — a small town, not a chief port.',
      'God provides sheltered bays along every stormy voyage. Wisdom learns to winter where He sets the anchor, even if the port is small.'),
  (9, 'Now when much time was spent, and when sailing was now dangerous, because the fast was now already past, Paul admonished them,',
      'Ἱκανοῦ δὲ χρόνου διαγενομένου, καὶ ὄντος ἤδη ἐπισφαλοῦς τοῦ πλοὸς διὰ τὸ καὶ τὴν νηστείαν ἤδη παρεληλυθέναι, παρῄνει ὁ Παῦλος',
      'Hikanou de chronou diagenomenou, kai ontos ēdē episphalous tou ploos dia to kai tēn nēsteian ēdē parelēlythenai, parēnei ho Paulos',
      '"The fast" = the Day of Atonement (Yom Kippur, Lev 16:29-31), falling in late September/early October. Ancient seafaring held mid-September–mid-November as "doubtful" and after 11 November as "closed" (Vegetius, De Re Militari 4.39).',
      'The apostle speaks out of Scripture''s calendar and seafarer''s wisdom. Prophetic counsel does not despise practical knowledge, but sanctifies it.'),
  (10, 'And said unto them, Sirs, I perceive that this voyage will be with hurt and much damage, not only of the lading and ship, but also of our lives.',
      'λέγων αὐτοῖς, Ἄνδρες, θεωρῶ ὅτι μετὰ ὕβρεως καὶ πολλῆς ζημίας, οὐ μόνον τοῦ φόρτου καὶ τοῦ πλοίου, ἀλλὰ καὶ τῶν ψυχῶν ἡμῶν μέλλειν ἔσεσθαι τὸν πλοῦν.',
      'legōn autois, Andres, theōrō hoti meta hybreōs kai pollēs zēmias, ou monon tou phortou kai tou ploiou, alla kai tōn psychōn hēmōn mellein esesthai ton ploun.',
      '"Hurt" (ὕβρις) = violence, outrage — here personified of the storm. "Lading" (φόρτος) = cargo of grain. Paul speaks by sanctified perception (θεωρῶ), not yet by direct revelation (that comes at v.23).',
      'The believer''s tested spiritual discernment has weight in public counsel. Paul does not yet say "God told me" — but his perception, shaped by prayer and Scripture, is already prophetic.'),
  (11, 'Nevertheless the centurion believed the master and the owner of the ship, more than those things which were spoken by Paul.',
      'Ὁ δὲ ἑκατοντάρχης τῷ κυβερνήτῃ καὶ τῷ ναυκλήρῳ ἐπείθετο μᾶλλον ἢ τοῖς ὑπὸ τοῦ Παύλου λεγομένοις.',
      'Ho de hekatontarchēs tō kybernētē kai tō nauklērō epeitheto mallon ē tois hypo tou Paulou legomenois.',
      '"Master" (κυβερνήτης) = helmsman/captain. "Owner" (ναύκληρος) = shipmaster or shipping contractor. Julius defers to the professionals — a sensible choice that proves catastrophically wrong.',
      'Expert opinion is not infallible. When the seasoned voice of the Spirit speaks through a prisoner, officers ought not overrule it with professional credentials.'),
  (12, 'And because the haven was not commodious to winter in, the more part advised to depart thence also, if by any means they might attain to Phenice, and there to winter; which is an haven of Crete, and lieth toward the south west and north west.',
      'Ἀνευθέτου δὲ τοῦ λιμένος ὑπάρχοντος πρὸς παραχειμασίαν, οἱ πλείους ἔθεντο βουλὴν ἀναχθῆναι κἀκεῖθεν, εἴπως δύναιντο καταντήσαντες εἰς Φοίνικα παραχειμάσαι, λιμένα τῆς Κρήτης βλέποντα κατὰ λίβα καὶ κατὰ χῶρον.',
      'Aneuthetou de tou limenos hyparchontos pros paracheimasian, hoi pleious ethento boulēn anachthēnai kakeithen, eipōs dynainto katantēsantes eis Phoinika paracheimasai, limena tēs Krētēs bleponta kata liba kai kata chōron.',
      'Phenice (Phoinix, probably modern Loutro) lay some 40 miles west. "Toward the south-west and north-west" (κατὰ λίβα καὶ κατὰ χῶρον) describes the harbour''s openings — a sheltered haven.',
      'Majority vote is not divine guidance. When the counsel of God is in the minority, faith pleads it still, even if it loses the poll.'),
  (13, 'And when the south wind blew softly, supposing that they had obtained their purpose, loosing thence, they sailed close by Crete.',
      'Ὑποπνεύσαντος δὲ νότου, δόξαντες τῆς προθέσεως κεκρατηκέναι, ἄραντες ἆσσον παρελέγοντο τὴν Κρήτην.',
      'Hypopneusantos de notou, doxantes tēs protheseōs kekratēkenai, arantes asson parelegonto tēn Krētēn.',
      'A soft southerly was the ideal wind for the western run. "Close by" (ἆσσον) = near the shore. The gentle breeze was a snare.',
      'Beware the soft south wind of misread providence. Circumstances bending your way are not always confirmation you are walking in God''s.'),
  (14, 'But not long after there arose against it a tempestuous wind, called Euroclydon.',
      'Μετ᾽ οὐ πολὺ δὲ ἔβαλε κατ᾽ αὐτῆς ἄνεμος τυφωνικός, ὁ καλούμενος Εὐροκλύδων·',
      'Met'' ou poly de ebale kat'' autēs anemos typhōnikos, ho kaloumenos Eurokludōn;',
      '"Euroclydon" (Εὐροκλύδων) = east-wind-wave, a north-easterly gale that still bedevils the southern Cretan coast (modern "gregale"). "Typhonic" (τυφωνικός) = whirlwind-like — a katabatic fall from the White Mountains.',
      'The Lord commands even the typhoon. No storm rises against His servant without first passing the threshold of His throne.'),
  (15, 'And when the ship was caught, and could not bear up into the wind, we let her drive.',
      'συναρπασθέντος δὲ τοῦ πλοίου, καὶ μὴ δυναμένου ἀντοφθαλμεῖν τῷ ἀνέμῳ, ἐπιδόντες ἐφερόμεθα.',
      'synarpasthentos de tou ploiou, kai mē dynamenou antophthalmein tō anemō, epidontes epherometha.',
      '"Bear up into the wind" (ἀντοφθαλμεῖν) literally "to look eye-to-eye" with the wind — nautical idiom for sailing into the eye. The ship cannot; they surrender her to the gale.',
      'There are storms too strong for human steering. Wisdom sometimes relinquishes the wheel, commits to the wind, and looks to the anchor of heaven.'),
  (16, 'And running under a certain island which is called Clauda, we had much work to come by the boat:',
      'νησίον δέ τι ὑποδραμόντες καλούμενον Κλαύδην, μόλις ἰσχύσαμεν περικρατεῖς γενέσθαι τῆς σκάφης·',
      'nēsion de ti hypodramontes kaloumenon Klaudēn, molis ischysamen perikrateis genesthai tēs skaphēs;',
      'Clauda (modern Gavdos) lies 23 miles south of Crete. In the lee they struggled to haul aboard the ship''s boat (σκάφη) — the trailing lifeboat swamped by rain and waves.',
      'The Lord provides brief islands of relief in the long storm — moments to secure what must not be lost before the next gust strikes.'),
  (17, 'Which when they had taken up, they used helps, undergirding the ship; and, fearing lest they should fall into the quicksands, strake sail, and so were driven.',
      'ἣν ἄραντες, βοηθείαις ἐχρῶντο, ὑποζωννύντες τὸ πλοῖον· φοβούμενοί τε μὴ εἰς τὴν Σύρτιν ἐκπέσωσι, χαλάσαντες τὸ σκεῦος, οὕτως ἐφέροντο.',
      'hēn arantes, boētheiais echrōnto, hypozōnnyntes to ploion; phoboumenoi te mē eis tēn Syrtin ekpesōsi, chalasantes to skeuos, houtōs epheronto.',
      '"Undergirding" (ὑποζωννύντες) = hypozoma — cables passed under the hull and tightened on deck to prevent seams parting; attested in Plato (Rep. 10.616c) and ancient admiralty inventories. Syrtis = the treacherous sandbanks off Libya, dreaded ship-killer of the Mediterranean. "Strake sail" = lowered gear (main yard or sea-anchor).',
      'Faithful helps bind the soul that would otherwise spring her planks. Prayer, Scripture, and brotherhood are the undergirding cables of the storm-struck church.'),
  (18, 'And we being exceedingly tossed with a tempest, the next day they lightened the ship;',
      'Σφοδρῶς δὲ χειμαζομένων ἡμῶν, τῇ ἑξῆς ἐκβολὴν ἐποιοῦντο·',
      'Sphodrōs de cheimazomenōn hēmōn, tē hexēs ekbolēn epoiounto;',
      '"Lightened" (ἐκβολὴν ἐποιοῦντο) = Jonah-like jettison (Jonah 1:5). They threw over part of the cargo — though grain was too valuable to dump wholesale until v.38.',
      'The storm calls for shedding what we once prized. Sanctified lightening begins with the outward cargo and ends at the treasures of the heart.'),
  (19, 'And the third day we cast out with our own hands the tackling of the ship.',
      'καὶ τῇ τρίτῃ αὐτόχειρες τὴν σκευὴν τοῦ πλοίου ἐρρίψαμεν.',
      'kai tē tritē autocheires tēn skeuēn tou ploiou erripsamen.',
      '"With our own hands" (αὐτόχειρες) — even the passengers heave. "Tackling" (σκευή) = rigging, spare gear, furniture. Luke''s "we" makes the reader grip the rope.',
      'When the ship of life groans, the believer works beside the crew. No spectator-faith survives Euroclydon.'),
  (20, 'And when neither sun nor stars in many days appeared, and no small tempest lay on us, all hope that we should be saved was then taken away.',
      'Μήτε δὲ ἡλίου μήτε ἄστρων ἐπιφαινόντων ἐπὶ πλείονας ἡμέρας, χειμῶνός τε οὐκ ὀλίγου ἐπικειμένου, λοιπὸν περιῃρεῖτο πᾶσα ἐλπὶς τοῦ σῴζεσθαι ἡμᾶς.',
      'Mēte de hēliou mēte astrōn epiphainontōn epi pleionas hēmeras, cheimōnos te ouk oligou epikeimenou, loipon periēreito pasa elpis tou sōzesthai hēmas.',
      'Ancient navigation required sun by day, stars by night; with cloud-cover a ship could only guess position. "All hope... taken away" (περιῃρεῖτο) is imperfect — hope was being peeled off day by day.',
      'When every creaturely light fails, faith alone holds the watch. The dark sky becomes the school of divine trust.'),
  (21, 'But after long abstinence Paul stood forth in the midst of them, and said, Sirs, ye should have hearkened unto me, and not have loosed from Crete, and to have gained this harm and loss.',
      'Πολλῆς δὲ ἀσιτίας ὑπαρχούσης, τότε σταθεὶς ὁ Παῦλος ἐν μέσῳ αὐτῶν εἶπεν, Ἔδει μέν, ὦ ἄνδρες, πειθαρχήσαντάς μοι μὴ ἀνάγεσθαι ἀπὸ τῆς Κρήτης, κερδῆσαί τε τὴν ὕβριν ταύτην καὶ τὴν ζημίαν.',
      'Pollēs de asitias hyparchousēs, tote statheis ho Paulos en mesō autōn eipen, Edei men, ō andres, peitharchēsantas moi mē anagesthai apo tēs Krētēs, kerdēsai te tēn hybrin tautēn kai tēn zēmian.',
      '"Long abstinence" — the storm made cooking impossible, seasickness made food loathsome; hull salt-water contaminated stores. "Should have hearkened" is the apostle''s tender rebuke, not vindictive but pastoral.',
      'The servant of God gains the right to be heard by first bearing the storm with those who refused his counsel. Rebuke from a fellow-sufferer heals where accusation from a spectator wounds.'),
  (22, 'And now I exhort you to be of good cheer: for there shall be no loss of any man''s life among you, but of the ship.',
      'Καὶ τανῦν παραινῶ ὑμᾶς εὐθυμεῖν· ἀποβολὴ γὰρ ψυχῆς οὐδεμία ἔσται ἐξ ὑμῶν, πλὴν τοῦ πλοίου.',
      'Kai tanyn parainō hymas euthymein; apobolē gar psychēs oudemia estai ex hymōn, plēn tou ploiou.',
      '"Be of good cheer" (εὐθυμεῖν) = to be cheerful in soul. Paul announces what the angel has yet to say openly (v.23) — so sure is he of God''s word that he declares outcome first.',
      'Christian cheer is not optimism; it is the echo of heaven''s verdict spoken before the storm breaks. Joy flows from promise, not from weather.'),
  (23, 'For there stood by me this night the angel of God, whose I am, and whom I serve,',
      'Παρέστη γάρ μοι τῇ νυκτὶ ταύτῃ ἄγγελος τοῦ Θεοῦ, οὗ εἰμι, ᾧ καὶ λατρεύω,',
      'Parestē gar moi tē nykti tautē angelos tou Theou, hou eimi, hō kai latreuō,',
      '"Whose I am, and whom I serve" — twofold identity: possession ("I belong to Him") and service (λατρεύω, priestly worship). Paul declares his Lord even before he declares his message.',
      'Before announcing the promise, the apostle announces the Master. The gospel is always spoken out of belonging and worship, never as a merely professional vocation.'),
  (24, 'Saying, Fear not, Paul; thou must be brought before Caesar: and, lo, God hath given thee all them that sail with thee.',
      'λέγων, Μὴ φοβοῦ, Παῦλε· Καίσαρί σε δεῖ παραστῆναι· καὶ ἰδού, κεχάρισταί σοι ὁ Θεὸς πάντας τοὺς πλέοντας μετὰ σοῦ.',
      'legōn, Mē phobou, Paule; Kaisari se dei parastēnai; kai idou, kecharistai soi ho Theos pantas tous pleontas meta sou.',
      '"Must" (δεῖ) = divine necessity (cf. 9:16; 19:21; 23:11). "Hath given" (κεχάρισται) = hath graciously granted — the same verb of free bestowal as in forgiveness and gospel gift (Rom 8:32). God answers intercession we do not even see.',
      'The righteous man''s intercession saves the shipload. God grants unsaved passengers to the prayers of His apostle — a pattern repeating from Genesis 18 to Revelation.'),
  (25, 'Wherefore, sirs, be of good cheer: for I believe God, that it shall be even as it was told me.',
      'Διὸ εὐθυμεῖτε, ἄνδρες· πιστεύω γὰρ τῷ Θεῷ ὅτι οὕτως ἔσται καθ᾽ ὃν τρόπον λελάληταί μοι.',
      'Dio euthymeite, andres; pisteuō gar tō Theō hoti houtōs estai kath'' hon tropon lelalētai moi.',
      '"I believe God" (πιστεύω τῷ Θεῷ) echoes Abraham''s faith (Gen 15:6; Rom 4:3). Paul stakes all on the bare word of the God who cannot lie.',
      'Faith speaks in the indicative: it shall be. The Christian does not hedge God''s promise with "perhaps" — he orders his life around the certainty of what God has said.'),
  (26, 'Howbeit we must be cast upon a certain island.',
      'Εἰς νῆσον δέ τινα δεῖ ἡμᾶς ἐκπεσεῖν.',
      'Eis nēson de tina dei hēmas ekpesein.',
      '"A certain island" = Paul does not yet know it is Malta (28:1). Revelation is sufficient, not exhaustive.',
      'God gives His servants light enough for the next step, not a map of every shore. Obedience walks by word, not by atlas.'),
  (27, 'But when the fourteenth night was come, as we were driven up and down in Adria, about midnight the shipmen deemed that they drew near to some country;',
      'Ὡς δὲ τεσσαρεσκαιδεκάτη νὺξ ἐγένετο, διαφερομένων ἡμῶν ἐν τῷ Ἀδρίᾳ, κατὰ μέσον τῆς νυκτὸς ὑπενόουν οἱ ναῦται προσάγειν τινὰ αὐτοῖς χώραν·',
      'Hōs de tessareskaidekatē nyx egeneto, diapheromenōn hēmōn en tō Adria, kata meson tēs nyktos hypenooun hoi nautai prosagein tina autois chōran;',
      '"Adria" to the ancients included the whole central Mediterranean south of Italy and west of Greece — not only the modern Adriatic. 14 days from Clauda at the normal 36-mile drift fits precisely the passage to Malta.',
      'Fourteen nights of unrelenting dark end at the sound of surf. The Lord lets faith run out the long night to its hour of rescue.'),
  (28, 'And sounded, and found it twenty fathoms: and when they had gone a little further, they sounded again, and found it fifteen fathoms.',
      'καὶ βολίσαντες εὗρον ὀργυιὰς εἴκοσι· βραχὺ δὲ διαστήσαντες, καὶ πάλιν βολίσαντες, εὗρον ὀργυιὰς δεκαπέντε·',
      'kai bolisantes heuron orguias eikosi; brachy de diastēsantes, kai palin bolisantes, heuron orguias dekapente;',
      'Sounding lead (βολίς) was dropped to measure depth. An "orguia" = fathom, ~6 feet. 20 → 15 fathoms (120 → 90 feet) confirms approach to land. Captain Smith (Voyage and Shipwreck of St Paul, 1848) matches this precisely to the approach of Koura Point, Malta.',
      'God honours careful seamanship even as He fulfils angelic prophecy. Faith and the sounding line are not rivals.'),
  (29, 'Then fearing lest we should have fallen upon rocks, they cast four anchors out of the stern, and wished for the day.',
      'φοβούμενοί τε μήπως εἰς τραχεῖς τόπους ἐκπέσωμεν, ἐκ πρύμνης ῥίψαντες ἀγκύρας τέσσαρας, ηὔχοντο ἡμέραν γενέσθαι.',
      'phoboumenoi te mēpōs eis tracheis topous ekpesōmen, ek prymnēs rhipsantes ankuras tessaras, ēuchonto hēmeran genesthai.',
      'Stern-anchoring (unusual; bow-anchors were the norm) kept the ship''s head toward the expected shore so that daylight would permit a controlled beaching. Four anchors testify to the ferocity of the gale.',
      'Hope has anchors; faith wishes for the day. The night of trial is endured by fastenings behind and longings ahead.'),
  (30, 'And as the shipmen were about to flee out of the ship, when they had let down the boat into the sea, under colour as though they would have cast anchors out of the foreship,',
      'Τῶν δὲ ναυτῶν ζητούντων φυγεῖν ἐκ τοῦ πλοίου, καὶ χαλασάντων τὴν σκάφην εἰς τὴν θάλασσαν, προφάσει ὡς ἐκ πρῴρας μελλόντων ἀγκύρας ἐκτείνειν,',
      'Tōn de nautōn zētountōn phygein ek tou ploiou, kai chalasantōn tēn skaphēn eis tēn thalassan, prophasei hōs ek prōras mellontōn ankuras ekteinein,',
      '"Under colour" (προφάσει) = pretext — classical Greek for deceitful appearance. The sailors, knowing the ship must break up, tried to smuggle themselves off in the lifeboat while passengers still trusted them.',
      'Spiritual betrayal often wears the costume of duty. Watch for those who "lower the boat" of the church while pretending to strengthen her anchors.'),
  (31, 'Paul said to the centurion and to the soldiers, Except these abide in the ship, ye cannot be saved.',
      'εἶπεν ὁ Παῦλος τῷ ἑκατοντάρχῃ καὶ τοῖς στρατιώταις, Ἐὰν μὴ οὗτοι μείνωσιν ἐν τῷ πλοίῳ, ὑμεῖς σωθῆναι οὐ δύνασθε.',
      'eipen ho Paulos tō hekatontarchē kai tois stratiōtais, Ean mē houtoi meinōsin en tō ploiō, hymeis sōthēnai ou dynasthe.',
      'Tension with v.24: God has promised salvation to all aboard, yet Paul says "except these abide... ye cannot be saved." Sovereign promise does not dissolve ordained means; God fulfils His word through human faithfulness.',
      'Predestination establishes, not abolishes, responsibility. The elect must use the means, for the very means are elected with the end.'),
  (32, 'Then the soldiers cut off the ropes of the boat, and let her fall off.',
      'Τότε οἱ στρατιῶται ἀπέκοψαν τὰ σχοινία τῆς σκάφης, καὶ εἴασαν αὐτὴν ἐκπεσεῖν.',
      'Tote hoi stratiōtai apekopsan ta schoinia tēs skaphēs, kai eiasan autēn ekpesein.',
      'Drastic: by cutting the boat loose, the soldiers have burned their own last escape. They stake their survival on Paul''s word rather than their own contingency.',
      'Faith cuts loose the lifeboat that belongs to unbelief. When God has spoken, the believer commits to the vessel of promise and will not hedge the outcome.'),
  (33, 'And while the day was coming on, Paul besought them all to take meat, saying, This day is the fourteenth day that ye have tarried and continued fasting, having taken nothing.',
      'Ἄχρι δὲ οὗ ἔμελλεν ἡμέρα γίνεσθαι, παρεκάλει ὁ Παῦλος ἅπαντας μεταλαβεῖν τροφῆς, λέγων, Τεσσαρεσκαιδεκάτην σήμερον ἡμέραν προσδοκῶντες, ἄσιτοι διατελεῖτε, μηδὲν προσλαβόμενοι.',
      'Achri de hou emellen hēmera ginesthai, parekalei ho Paulos hapantas metalabein trophēs, legōn, Tessareskaidekatēn sēmeron hēmeran prosdokōntes, asitoi diateleite, mēden proslabomenoi.',
      '"Fasting" (ἄσιτοι) here is involuntary — storm-sickness and inability to prepare food. Paul turns into a pastoral father, urging the crew to eat before exertion.',
      'Spiritual leaders care for bodies as well as souls. The servant of the Word also commends breakfast, for the whole man must face the surf.'),
  (34, 'Wherefore I pray you to take some meat: for this is for your health: for there shall not an hair fall from the head of any of you.',
      'Διὸ παρακαλῶ ὑμᾶς προσλαβεῖν τροφῆς· τοῦτο γὰρ πρὸς τῆς ὑμετέρας σωτηρίας ὑπάρχει· οὐδενὸς γὰρ ὑμῶν θρὶξ ἐκ τῆς κεφαλῆς πεσεῖται.',
      'Dio parakalō hymas proslabein trophēs; touto gar pros tēs hymeteras sōtērias hyparchei; oudenos gar hymōn thrix ek tēs kephalēs peseitai.',
      '"Not an hair... fall" echoes 1 Sam 14:45; 2 Sam 14:11; 1 Kgs 1:52; Luke 21:18 — the familiar Hebrew figure of total preservation. Paul quotes the Lord''s own Olivet phrase.',
      'The God of resurrection numbers every hair. Total preservation is the promise, and perfect confidence the sinner''s proper response.'),
  (35, 'And when he had thus spoken, he took bread, and gave thanks to God in presence of them all: and when he had broken it, he began to eat.',
      'Εἰπὼν δὲ ταῦτα, καὶ λαβὼν ἄρτον, εὐχαρίστησε τῷ Θεῷ ἐνώπιον πάντων, καὶ κλάσας ἤρξατο ἐσθίειν.',
      'Eipōn de tauta, kai labōn arton, eucharistēse tō Theō enōpion pantōn, kai klasas ērxato esthiein.',
      'The fourfold gesture — took, gave thanks, broke, began to eat — mirrors the feedings and the Last Supper (Luke 22:19; 24:30). On a heathen ship, Paul''s Jewish table-grace becomes an evangelistic act.',
      'A believer''s grace at meat is sermon and witness. The simplest public thanksgiving can lift a trembling crew from despair to strength.'),
  (36, 'Then were they all of good cheer, and they also took some meat.',
      'Εὔθυμοι δὲ γενόμενοι πάντες καὶ αὐτοὶ προσελάβοντο τροφῆς.',
      'Euthymoi de genomenoi pantes kai autoi proselabonto trophēs.',
      '"All of good cheer" (εὔθυμοι) — the third and climactic use of the keyword (v.22, v.25, v.36). One courageous saint has leavened the whole ship.',
      'Courage is contagious. One soul that believes God enough to give thanks can lift two hundred and seventy-six despairing ones.'),
  (37, 'And we were in all in the ship two hundred threescore and sixteen souls.',
      'Ἦμεν δὲ ἐν τῷ πλοίῳ αἱ πᾶσαι ψυχαί, διακόσιαι ἑβδομηκονταέξ.',
      'Ēmen de en tō ploiō hai pasai psychai, diakosiai hebdomēkontaex.',
      '276 souls — Luke the physician counts heads precisely. Josephus (Life 15) likewise tallies 600 on a grain ship, confirming the plausibility of the figure.',
      'Every soul matters in the register of God. The Spirit bothers to inspire the exact number because each person counted was dear to the Lord who saved them.'),
  (38, 'And when they had eaten enough, they lightened the ship, and cast out the wheat into the sea.',
      'Κορεσθέντες δὲ τροφῆς ἐκούφιζον τὸ πλοῖον, ἐκβαλλόμενοι τὸν σῖτον εἰς τὴν θάλασσαν.',
      'Koresthentes de trophēs ekouphizon to ploion, ekballomenoi ton siton eis tēn thalassan.',
      'The wheat — the grain ship''s whole cargo and the crew''s livelihood — goes last. With full stomachs they empty the hold, preparing the hull to ride higher on the surf-beach.',
      'There is a final jettison: the prized cargo surrendered that the soul may reach the shore. Faith learns to part with what it came to carry when the voyage becomes the rescue.'),
  (39, 'And when it was day, they knew not the land: but they discovered a certain creek with a shore, into the which they were minded, if it were possible, to thrust in the ship.',
      'Ὅτε δὲ ἡμέρα ἐγένετο, τὴν γῆν οὐκ ἐπεγίνωσκον· κόλπον δέ τινα κατενόουν ἔχοντα αἰγιαλόν, εἰς ὃν ἐβουλεύσαντο, εἰ δύναιντο, ἐξῶσαι τὸ πλοῖον.',
      'Hote de hēmera egeneto, tēn gēn ouk epeginōskon; kolpon de tina katenooun echonta aigialon, eis hon ebouleusanto, ei dynainto, exōsai to ploion.',
      'The seasoned Alexandrian sailors did not recognise Malta — the north-east coast of the island was outside their usual routes. The creek (κόλπος) is traditionally St Paul''s Bay with its sandy beach.',
      'Even to a faithless world, God''s deliverance arrives on ground unknown. Salvation often lands where the experienced never expected a harbour.'),
  (40, 'And when they had taken up the anchors, they committed themselves unto the sea, and loosed the rudder bands, and hoised up the mainsail to the wind, and made toward shore.',
      'Καὶ τὰς ἀγκύρας περιελόντες εἴων εἰς τὴν θάλασσαν, ἅμα ἀνέντες τὰς ζευκτηρίας τῶν πηδαλίων· καὶ ἐπάραντες τὸν ἀρτέμονα τῇ πνεούσῃ κατεῖχον εἰς τὸν αἰγιαλόν.',
      'Kai tas ankyras perielontes eiōn eis tēn thalassan, hama anentes tas zeuktērias tōn pēdaliōn; kai eparantes ton artemona tē pneousē kateichon eis ton aigialon.',
      '"Rudder bands" (ζευκτηρίας τῶν πηδαλίων) = lashings securing the twin steering-paddles (raised during anchoring). "Mainsail" here is ἀρτέμων = foresail — the small sail forward, ideal for beaching.',
      'Loosed bands, lifted sail, committed course. Salvation at the last hour requires active faith — trust that looses what was tied and raises what was furled.'),
  (41, 'And falling into a place where two seas met, they ran the ship aground; and the forepart stuck fast, and remained unmoveable, but the hinder part was broken with the violence of the waves.',
      'Περιπεσόντες δὲ εἰς τόπον διθάλασσον ἐπώκειλαν τὴν ναῦν· καὶ ἡ μὲν πρῷρα ἐρείσασα ἔμεινεν ἀσάλευτος, ἡ δὲ πρύμνα ἐλύετο ὑπὸ τῆς βίας τῶν κυμάτων.',
      'Peripesontes de eis topon dithalasson epōkeilan tēn naun; kai hē men prōra ereisasa emeinen asaleutos, hē de prymna elyeto hypo tēs bias tōn kymatōn.',
      '"Two seas met" (διθάλασσος) = sandbar or mud-bank where currents collide. Modern survey at Malta''s Mellieha Bay identifies such a shoal. The bow beached; the stern, exposed to surf, broke apart.',
      'The ship fails; the souls are spared. The cross is the place where two seas meet — wrath and mercy — and out of its breaking up the redeemed are delivered whole.'),
  (42, 'And the soldiers'' counsel was to kill the prisoners, lest any of them should swim out, and escape.',
      'Τῶν δὲ στρατιωτῶν βουλὴ ἐγένετο ἵνα τοὺς δεσμώτας ἀποκτείνωσιν, μή τις ἐκκολυμβήσας διαφύγοι.',
      'Tōn de stratiōtōn boulē egeneto hina tous desmōtas apokteinōsin, mē tis ekkolymbēsas diaphygoi.',
      'Under Roman custodial law a soldier suffered the prisoner''s own penalty if his charge escaped (cf. 12:19; 16:27). Self-preservation counselled murder.',
      'The world''s last counsel for the believer is the sword. But the Lord who ordained the promise also ordains the protector who refuses it.'),
  (43, 'But the centurion, willing to save Paul, kept them from their purpose; and commanded that they which could swim should cast themselves first into the sea, and get to land:',
      'Ὁ δὲ ἑκατοντάρχης, βουλόμενος διασῶσαι τὸν Παῦλον, ἐκώλυσεν αὐτοὺς τοῦ βουλήματος, ἐκέλευσέ τε τοὺς δυναμένους κολυμβᾷν, ἀπορρίψαντας πρώτους, ἐπὶ τὴν γῆν ἐξιέναι·',
      'Ho de hekatontarchēs, boulomenos diasōsai ton Paulon, ekōlysen autous tou boulēmatos, ekeleuse te tous dynamenous kolymban, aporripsantas prōtous, epi tēn gēn exienai;',
      'Julius'' favour toward Paul (v.3) now saves every prisoner on board. One righteous man''s favour with the governor spreads salvation to the entire company of condemned.',
      'Favour resting on Christ rests on His people. Because the Father is pleased with the Son, the sons and daughters are preserved when the world calls for their death.'),
  (44, 'And the rest, some on boards, and some on broken pieces of the ship. And so it came to pass, that they escaped all safe to land.',
      'καὶ τοὺς λοιπούς, οὓς μὲν ἐπὶ σανίσιν, οὓς δὲ ἐπί τινων τῶν ἀπὸ τοῦ πλοίου. Καὶ οὕτως ἐγένετο πάντας διασωθῆναι ἐπὶ τὴν γῆν.',
      'kai tous loipous, hous men epi sanisin, hous de epi tinōn tōn apo tou ploiou. Kai houtōs egeneto pantas diasōthēnai epi tēn gēn.',
      '"Escaped all safe" (πάντας διασωθῆναι) — the exact verb promised in v.43 ("save") fulfils what was spoken in v.24. Every one of the 276 reaches land.',
      'God''s word returns fulfilled to the last syllable. On splintered planks, on broken timbers, the whole company comes safely home — a parable of the church brought through tribulation to the eternal shore.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Acts' AND c.chapter_number = 27
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'ἀποπλεῖν', 'apoplein', 'G636', 'To sail away — nautical departure verb.', 1),
  (1, 'σπείρης Σεβαστῆς', 'speirēs Sebastēs', 'G4686/G4575', 'Augustus'' band — a cohort bearing the emperor''s name.', 2),
  (3, 'φιλανθρώπως', 'philanthrōpōs', 'G5364', 'Humanely, courteously — kindness toward fellow man.', 3),
  (4, 'ὑπεπλεύσαμεν', 'hypepleusamen', 'G5284', 'We sailed under the lee — tracking the sheltered side of an island.', 4),
  (6, 'πλοῖον Ἀλεξανδρινόν', 'ploion Alexandrinon', 'G4143/G222', 'Alexandrian ship — the grain freighter of Rome''s corn supply.', 5),
  (7, 'βραδυπλοοῦντες', 'bradyploountes', 'G1020', 'Sailing slowly — a single compound verb for tedious voyage.', 6),
  (9, 'νηστείαν', 'nēsteian', 'G3521', 'The fast — Day of Atonement, Yom Kippur, early October.', 7),
  (9, 'παρῄνει', 'parēnei', 'G3867', 'Admonished — counselled with authority.', 8),
  (10, 'ὕβρεως', 'hybreōs', 'G5196', 'Hurt, insolence — violence of the storm personified.', 9),
  (10, 'ζημίας', 'zēmias', 'G2209', 'Loss, damage — commercial and personal forfeit.', 10),
  (11, 'κυβερνήτῃ', 'kybernētē', 'G2942', 'Helmsman, pilot — root of English "governor".', 11),
  (11, 'ναυκλήρῳ', 'nauklērō', 'G3490', 'Shipowner/master — the commercial principal.', 12),
  (12, 'παραχειμασίαν', 'paracheimasian', 'G3915', 'Wintering — to spend the closed sailing season in harbour.', 13),
  (14, 'τυφωνικός', 'typhōnikos', 'G5189', 'Typhonic — whirlwind-like, from which English "typhoon".', 14),
  (14, 'Εὐροκλύδων', 'Eurokludōn', 'G2148', 'East-wind-wave — the north-east gale of Mediterranean seamen.', 15),
  (15, 'ἀντοφθαλμεῖν', 'antophthalmein', 'G503', 'To look eye-to-eye — idiom for sailing head-to-wind.', 16),
  (17, 'βοηθείαις', 'boētheiais', 'G996', 'Helps — bracing tackle applied in emergency.', 17),
  (17, 'ὑποζωννύντες', 'hypozōnnyntes', 'G5269', 'Undergirding — passing cables beneath the hull.', 18),
  (17, 'Σύρτιν', 'Syrtin', 'G4950', 'Syrtis — deadly sandbanks off Libya.', 19),
  (18, 'ἐκβολήν', 'ekbolēn', 'G1546', 'Jettison — the casting out of cargo.', 20),
  (19, 'αὐτόχειρες', 'autocheires', 'G849', 'With our own hands — passengers labouring alongside the crew.', 21),
  (19, 'σκευήν', 'skeuēn', 'G4631', 'Tackling, rigging — ship''s movable gear.', 22),
  (20, 'περιῃρεῖτο', 'periēreito', 'G4014', 'Was being stripped away — continuous erosion of hope.', 23),
  (21, 'ἀσιτίας', 'asitias', 'G776', 'Abstinence from food — involuntary storm-fast.', 24),
  (22, 'εὐθυμεῖν', 'euthymein', 'G2114', 'To be of good cheer — key word; echoes in vv.25, 36.', 25),
  (23, 'λατρεύω', 'latreuō', 'G3000', 'I serve — priestly, worship-service.', 26),
  (24, 'κεχάρισται', 'kecharistai', 'G5483', 'Hath graciously granted — the verb of gospel gift.', 27),
  (25, 'πιστεύω τῷ Θεῷ', 'pisteuō tō Theō', 'G4100/G2316', 'I believe God — Abrahamic faith-confession.', 28),
  (27, 'Ἀδρίᾳ', 'Adria', 'G99', 'Adria — the central Mediterranean, not merely the modern Adriatic.', 29),
  (27, 'ναῦται', 'nautai', 'G3492', 'Sailors, seamen.', 30),
  (28, 'βολίσαντες', 'bolisantes', 'G1001', 'Having sounded — casting the lead-line.', 31),
  (28, 'ὀργυιάς', 'orguias', 'G3712', 'Fathoms — six-foot measure of depth.', 32),
  (29, 'ἀγκύρας τέσσαρας', 'ankyras tessaras', 'G45/G5064', 'Four anchors — stern-cast, securing for dawn.', 33),
  (30, 'προφάσει', 'prophasei', 'G4392', 'Pretext, false show — deceitful appearance of duty.', 34),
  (31, 'σωθῆναι', 'sōthēnai', 'G4982', 'To be saved — physical salvation echoing spiritual.', 35),
  (33, 'μεταλαβεῖν τροφῆς', 'metalabein trophēs', 'G3335/G5160', 'To partake of food — participate in a common meal.', 36),
  (35, 'εὐχαρίστησε', 'eucharistēse', 'G2168', 'He gave thanks — public blessing of food; root of eucharist.', 37),
  (36, 'εὔθυμοι', 'euthymoi', 'G2115', 'Of good cheer — the contagious climax of courage.', 38),
  (37, 'ψυχαί', 'psychai', 'G5590', 'Souls — persons in their living totality.', 39),
  (40, 'ἀρτέμονα', 'artemona', 'G736', 'Foresail — the small headsail for beaching.', 40),
  (40, 'πηδαλίων', 'pēdaliōn', 'G4079', 'Rudder-paddles — twin steering oars of ancient ships.', 41),
  (41, 'διθάλασσον', 'dithalasson', 'G1337', 'Two-sea place — sandbar or spit where currents meet.', 42),
  (43, 'διασῶσαι', 'diasōsai', 'G1295', 'To save through — bring safely through peril.', 43),
  (44, 'διασωθῆναι', 'diasōthēnai', 'G1295', 'To be brought safely through — fulfilment of the angelic word.', 44)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Acts' AND c.chapter_number = 27 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Acts 25:12', 1),
  (1, 'Acts 25:25', 2),
  (1, 'Acts 10:1', 3),
  (2, 'Acts 19:29', 4),
  (2, 'Acts 20:4', 5),
  (2, 'Col 4:10', 6),
  (2, 'Philem 24', 7),
  (3, 'Acts 24:23', 8),
  (3, 'Acts 28:16', 9),
  (3, 'Acts 11:19', 10),
  (4, 'Acts 4:36', 11),
  (4, 'Acts 13:4', 12),
  (6, 'Acts 28:11', 13),
  (9, 'Lev 16:29-31', 14),
  (9, 'Lev 23:27-32', 15),
  (10, 'Prov 22:3', 16),
  (10, '2 Cor 11:25-26', 17),
  (11, 'Prov 12:15', 18),
  (11, 'Prov 27:12', 19),
  (13, 'Prov 14:16', 20),
  (13, 'Jer 17:5', 21),
  (14, 'Ps 107:25-27', 22),
  (14, 'Jonah 1:4', 23),
  (17, 'Ps 107:27', 24),
  (20, 'Ps 107:26', 25),
  (20, 'Jonah 1:14', 26),
  (22, 'Acts 23:11', 27),
  (22, 'Matt 14:27', 28),
  (23, 'Rom 1:9', 29),
  (23, '2 Tim 1:3', 30),
  (23, 'Dan 6:22', 31),
  (23, 'Ps 91:11', 32),
  (24, 'Acts 9:15', 33),
  (24, 'Acts 23:11', 34),
  (24, 'Gen 19:21-22', 35),
  (24, 'Isa 43:4', 36),
  (25, 'Rom 4:20-21', 37),
  (25, 'Gen 15:6', 38),
  (25, 'Num 23:19', 39),
  (25, '2 Tim 1:12', 40),
  (26, 'Acts 28:1', 41),
  (27, 'Acts 28:11', 42),
  (29, 'Heb 6:19', 43),
  (31, 'Matt 24:22', 44),
  (31, '2 Thess 2:13-14', 45),
  (31, 'Phil 2:12-13', 46),
  (32, 'Matt 10:39', 47),
  (33, '1 Tim 4:8', 48),
  (34, '1 Sam 14:45', 49),
  (34, '2 Sam 14:11', 50),
  (34, '1 Kgs 1:52', 51),
  (34, 'Luke 21:18', 52),
  (34, 'Matt 10:30', 53),
  (35, 'Luke 22:19', 54),
  (35, 'Luke 24:30', 55),
  (35, '1 Tim 4:3-5', 56),
  (35, 'John 6:11', 57),
  (36, 'Acts 27:22', 58),
  (36, 'Acts 27:25', 59),
  (37, 'Acts 2:41', 60),
  (38, 'Jonah 1:5', 61),
  (38, 'Heb 12:1', 62),
  (41, '2 Cor 11:25', 63),
  (42, 'Acts 12:19', 64),
  (42, 'Acts 16:27', 65),
  (43, 'Acts 27:3', 66),
  (43, 'Gen 39:21', 67),
  (43, 'Ps 106:46', 68),
  (44, 'Acts 27:22', 69),
  (44, 'Acts 27:24', 70),
  (44, 'Ps 107:28-30', 71),
  (44, '2 Tim 4:17-18', 72)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Acts' AND c.chapter_number = 27 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
