-- Acts 28 — Malta, Rome, and the Gospel Unhindered
-- Theme: To the Ends of the Earth — the Gospel Reaches Rome Without Hindrance

INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 28,
  'Acts 28 brings Luke''s double-volume to its great open-ended close. Cast ashore on Melita (modern Malta), the shipwrecked company is welcomed by the barbaroi who build a fire against the rain and cold. A viper, roused from the sticks, fastens on Paul''s hand; the islanders conclude he must be a murderer whom Justice will not spare — but he shakes the serpent into the fire without harm and they change their minds, calling him a god. The chief man of the island, Publius, lodges the party three days; his father, suffering fever and dysentery, is healed under Paul''s prayer and laying on of hands, and healings follow throughout the island. After three months, an Alexandrian vessel bearing the sign of Castor and Pollux carries them to Syracuse, Rhegium, and Puteoli, where brethren receive them for seven days. At Appii Forum and the Three Taverns, Roman believers come out to meet them; Paul thanks God and takes courage. In Rome the centurion delivers the prisoners to the stratopedarch, but Paul is allowed his own lodging under a soldier''s watch. Three days later he calls the Jewish leaders, recounts why he is in chains "for the hope of Israel," and invites a further hearing. From morning till evening he expounds the kingdom of God and persuades concerning Jesus from Moses and the Prophets; some believe, others will not. He closes with Isaiah 6:9-10 — the prophetic sentence that authorises the turning to the Gentiles — and announces, "the salvation of God is sent unto the Gentiles, and that they will hear it." The book ends with Paul dwelling two whole years in his own hired house, receiving all who come, "preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him." The Greek closes on a single adverb — ἀκωλύτως — "unhindered." The Word has reached the capital of the empire, and the march from Jerusalem to the ends of the earth (1:8) continues beyond the last sentence.',
  'To the Ends of the Earth — the Gospel Unhindered',
  'ἀκωλύτως',
  'without hindrance, unhinderedly (akōlytōs) — the triumphant last word of Acts (v.31): nothing and no one can shut the mouth of the kingdom.',
  '[{"range":"vv.1-6","title":"Melita: the Kindness of Barbarians and the Viper on Paul''s Hand"},{"range":"vv.7-10","title":"Publius and the Healings Across the Island"},{"range":"vv.11-16","title":"From Malta to Rome via Syracuse, Rhegium, and Puteoli; the Brethren Meet Him"},{"range":"vv.17-22","title":"Paul Summons the Jewish Leaders: Defense and Invitation"},{"range":"vv.23-28","title":"A Day''s Preaching from Moses and the Prophets; Isaiah 6 and the Turn to the Gentiles"},{"range":"vv.29-31","title":"Two Whole Years in Rome: Preaching Unhindered"}]'::jsonb
FROM books b WHERE b.name = 'Acts'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  overview = EXCLUDED.overview,
  theme = EXCLUDED.theme,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'And when they were escaped, then they knew that the island was called Melita.',
      'Καὶ διασωθέντες, τότε ἐπέγνωσαν ὅτι Μελίτη ἡ νῆσος καλεῖται.',
      'Kai diasōthentes, tote epegnōsan hoti Melitē hē nēsos kaleitai.',
      'Melita = Malta, about 58 miles south of Sicily. The tradition locates the wreck in St Paul''s Bay on the north-east coast. "Escaped" (διασωθέντες) is the cognate verb that fulfils the angel''s promise of 27:24.',
      'Deliverance is recognised only after dry ground is under the feet. Faith often learns the name of its island only when the storm has receded.'),
  (2, 'And the barbarous people shewed us no little kindness: for they kindled a fire, and received us every one, because of the present rain, and because of the cold.',
      'Οἱ δὲ βάρβαροι παρεῖχον οὐ τὴν τυχοῦσαν φιλανθρωπίαν ἡμῖν· ἀνάψαντες γὰρ πυράν, προσελάβοντο πάντας ἡμᾶς, διὰ τὸν ὑετὸν τὸν ἐφεστῶτα, καὶ διὰ τὸ ψῦχος.',
      'Hoi de barbaroi pareichon ou tēn tychousan philanthrōpian hēmin; anapsantes gar pyran, proselabonto pantas hēmas, dia ton hyeton ton ephestōta, kai dia to psychos.',
      '"Barbarous" (βάρβαροι) is Luke''s non-pejorative Greek label for non-Greek-speakers — the Maltese spoke a Punic dialect descended from their Phoenician founders. "No little kindness" (litotes) = extraordinary humanity.',
      'Grace is often met first at the hands of those the world calls uncultured. The Lord has strangers whom He has prepared to receive His servants.'),
  (3, 'And when Paul had gathered a bundle of sticks, and laid them on the fire, there came a viper out of the heat, and fastened on his hand.',
      'Συστρέψαντος δὲ τοῦ Παύλου φρυγάνων πλῆθος, καὶ ἐπιθέντος ἐπὶ τὴν πυράν, ἔχιδνα ἐκ τῆς θέρμης ἐξελθοῦσα καθῆψε τῆς χειρὸς αὐτοῦ.',
      'Systrepsantos de tou Paulou phryganōn plēthos, kai epithentos epi tēn pyran, echidna ek tēs thermēs exelthousa kathēpse tēs cheiros autou.',
      'The apostle serves alongside the shipwrecked — no aristocratic aloofness from menial firewood. "Viper" (ἔχιδνα) likely the Vipera palaestinae, though vipers are unknown on Malta today (perhaps extinct since deforestation).',
      'No task of servanthood is beneath an apostle. The chiefest steward of mysteries gathers sticks for the common fire, and there receives the attack of the enemy.'),
  (4, 'And when the barbarians saw the venomous beast hang on his hand, they said among themselves, No doubt this man is a murderer, whom, though he hath escaped the sea, yet vengeance suffereth not to live.',
      'Ὡς δὲ εἶδον οἱ βάρβαροι κρεμάμενον τὸ θηρίον ἐκ τῆς χειρὸς αὐτοῦ, ἔλεγον πρὸς ἀλλήλους, Πάντως φονεύς ἐστιν ὁ ἄνθρωπος οὗτος, ὃν διασωθέντα ἐκ τῆς θαλάσσης ἡ δίκη ζῆν οὐκ εἴασεν.',
      'Hōs de eidon hoi barbaroi kremamenon to thērion ek tēs cheiros autou, elegon pros allēlous, Pantōs phoneus estin ho anthrōpos houtos, hon diasōthenta ek tēs thalassēs hē Dikē zēn ouk eiasen.',
      '"Vengeance" (ἡ Δίκη) = Dike, Greek goddess of retribution, daughter of Zeus. The Maltese interpret through their Hellenic religious vocabulary — the serpent must be divine justice pursuing a fugitive.',
      'Suffering is commonly (mis)read as proof of divine judgment. The world interprets the believer''s trial through its own theology of retribution and misses the purposes of grace.'),
  (5, 'And he shook off the beast into the fire, and felt no harm.',
      'Ὁ μὲν οὖν, ἀποτινάξας τὸ θηρίον εἰς τὸ πῦρ, ἔπαθεν οὐδὲν κακόν.',
      'Ho men oun, apotinaxas to thērion eis to pyr, epathen ouden kakon.',
      'The Lord''s promise in Mark 16:18 ("they shall take up serpents") is enacted in the apostle commissioned for Caesar. "Shook off" (ἀποτινάξας) echoes the gesture of Acts 13:51.',
      'The servant of Christ is immortal till his work is done. No venom can hurry the dismissal the Lord has not yet written.'),
  (6, 'Howbeit they looked when he should have swollen, or fallen down dead suddenly: but after they had looked a great while, and saw no harm come to him, they changed their minds, and said that he was a god.',
      'Οἱ δὲ προσεδόκων αὐτὸν μέλλειν πίμπρασθαι ἢ καταπίπτειν ἄφνω νεκρόν· ἐπὶ πολὺ δὲ αὐτῶν προσδοκώντων, καὶ θεωρούντων μηδὲν ἄτοπον εἰς αὐτὸν γινόμενον, μεταβαλλόμενοι ἔλεγον θεὸν αὐτὸν εἶναι.',
      'Hoi de prosedokōn auton mellein pimprasthai ē katapiptein aphnō nekron; epi poly de autōn prosdokōntōn, kai theōrountōn mēden atopon eis auton ginomenon, metaballomenoi elegon theon auton einai.',
      'The crowd swings from "murderer" to "god" — the same reversal as Lystra (14:11-19) but in the opposite direction. Luke records no protest from Paul, perhaps because language barriers prevented immediate correction.',
      'Human opinion lurches between extremes. The man of God rests neither on the accusation of the crowd nor on its applause, but on the verdict of his Lord.'),
  (7, 'In the same quarters were possessions of the chief man of the island, whose name was Publius; who received us, and lodged us three days courteously.',
      'Ἐν δὲ τοῖς περὶ τὸν τόπον ἐκεῖνον ὑπῆρχε χωρία τῷ πρώτῳ τῆς νήσου, ὀνόματι Ποπλίῳ, ὃς ἀναδεξάμενος ἡμᾶς τρεῖς ἡμέρας φιλοφρόνως ἐξένισεν.',
      'En de tois peri ton topon ekeinon hypērche chōria tō prōtō tēs nēsou, onomati Popliō, hos anadexamenos hēmas treis hēmeras philophronōs exenisen.',
      '"The chief man" (τῷ πρώτῳ) = an official title attested on Maltese inscriptions ("protos Melitaiōn"), designating the Roman-appointed governor. Publius is the Latin praenomen.',
      'Hospitality to storm-tossed strangers opens a home to the kingdom. The one who receives three unknown travellers may find his father healed by their God.'),
  (8, 'And it came to pass, that the father of Publius lay sick of a fever and of a bloody flux: to whom Paul entered in, and prayed, and laid his hands on him, and healed him.',
      'Ἐγένετο δὲ τὸν πατέρα τοῦ Ποπλίου πυρετοῖς καὶ δυσεντερίᾳ συνεχόμενον κατακεῖσθαι· πρὸς ὃν ὁ Παῦλος εἰσελθών, καὶ προσευξάμενος, ἐπιθεὶς τὰς χεῖρας αὐτῷ, ἰάσατο αὐτόν.',
      'Egeneto de ton patera tou Popliou pyretois kai dysenteria synechomenon katakeisthai; pros hon ho Paulos eiselthōn, kai proseuxamenos, epitheis tas cheiras autō, iasato auton.',
      'Luke the physician diagnoses precisely: "fevers" (plural, recurrent) and dysentery — the Maltese fever (now known as undulant fever, Brucella melitensis) endemic to the island. Paul''s threefold method: enter, pray, lay on hands.',
      'The gospel of healing is modelled on the Master: presence with the sufferer, prevailing prayer, and the apostolic touch. Ministry is neither only word nor only sacrament, but Spirit-empowered personal love.'),
  (9, 'So when this was done, others also, which had diseases in the island, came, and were healed:',
      'Τούτου οὖν γενομένου, καὶ οἱ λοιποὶ οἱ ἔχοντες ἀσθενείας ἐν τῇ νήσῳ προσήρχοντο καὶ ἐθεραπεύοντο·',
      'Toutou oun genomenou, kai hoi loipoi hoi echontes astheneias en tē nēsō prosērchonto kai etherapeuonto;',
      '"Were healed" (ἐθεραπεύοντο, imperfect) = "kept being cured" — an extended healing ministry across three winter months.',
      'One remarkable healing opens the door to the crowds. The Lord uses the public miracle as a summons to bring the sick at home.'),
  (10, 'Who also honoured us with many honours; and when we departed, they laded us with such things as were necessary.',
      'οἳ καὶ πολλαῖς τιμαῖς ἐτίμησαν ἡμᾶς, καὶ ἀναγομένοις ἐπέθεντο τὰ πρὸς τὴν χρείαν.',
      'hoi kai pollais timais etimēsan hēmas, kai anagomenois epethento ta pros tēn chreian.',
      '"Honours" (τιμαῖς) need not be cultic reverence; the word covers honoraria, gifts, and public respect. "Such things as were necessary" — provisioning for the onward voyage.',
      'The Lord pays His servants on the route. What was lost at sea is restored on the shore by hearts the gospel has touched.'),
  (11, 'And after three months we departed in a ship of Alexandria, which had wintered in the isle, whose sign was Castor and Pollux.',
      'Μετὰ δὲ τρεῖς μῆνας ἀνήχθημεν ἐν πλοίῳ παρακεχειμακότι ἐν τῇ νήσῳ, Ἀλεξανδρίνῳ, παρασήμῳ Διοσκούροις.',
      'Meta de treis mēnas anēchthēmen en ploiō parakecheimakoti en tē nēsō, Alexandrinō, parasēmō Dioskourois.',
      '"Castor and Pollux" (Διόσκουροι) = the twin sons of Zeus, patrons of sailors — their constellation (Gemini) is said to appear during storms as St Elmo''s fire. Another grain ship of Alexandria, this one wintered at Malta since the closed season began. Departure c. February AD 60.',
      'God uses pagan vessels bearing pagan figureheads for His providential itineraries. Idolatrous imagery on the prow does not prevent the work of the living God at the helm.'),
  (12, 'And landing at Syracuse, we tarried there three days.',
      'Καὶ καταχθέντες εἰς Συρακούσας ἐπεμείναμεν ἡμέρας τρεῖς·',
      'Kai katachthentes eis Syrakousas epemeinamen hēmeras treis;',
      'Syracuse on Sicily was a major Greek/Roman city with a Jewish community and early Christian congregation (later bishopric). 90-mile hop from Malta.',
      'The church''s geography already extended to the great Mediterranean ports. Paul travels a route already prepared by unknown saints of the dispersion.'),
  (13, 'And from thence we fetched a compass, and came to Rhegium: and after one day the south wind blew, and we came the next day to Puteoli:',
      'ὅθεν περιελθόντες κατηντήσαμεν εἰς Ῥήγιον, καὶ μετὰ μίαν ἡμέραν ἐπιγενομένου νότου, δευτεραῖοι ἤλθομεν εἰς Ποτιόλους·',
      'hothen perielthontes katēntēsamen eis Rhēgion, kai meta mian hēmeran epigenomenou notou, deuteraioi ēlthomen eis Potiolous;',
      '"Fetched a compass" (περιελθόντες) = tacked, sailed a circular course. Rhegium (modern Reggio Calabria) is at the toe of Italy. Puteoli (modern Pozzuoli near Naples) was Rome''s principal port for Egyptian grain — 180 miles in 48 hours, an excellent run.',
      'The Lord who ordered Euroclydon now grants the south wind. When God''s servant has been tested by the adverse gale, He sends the fair breeze to speed the completion.'),
  (14, 'Where we found brethren, and were desired to tarry with them seven days: and so we went toward Rome.',
      'οὗ εὑρόντες ἀδελφούς, παρεκλήθημεν ἐπ᾽ αὐτοῖς ἐπιμεῖναι ἡμέρας ἑπτά· καὶ οὕτως εἰς τὴν Ῥώμην ἤλθομεν.',
      'hou heurontes adelphous, pareklēthēmen ep'' autois epimeinai hēmeras hepta; kai houtōs eis tēn Rhōmēn ēlthomen.',
      'A church existed at Puteoli before Paul''s arrival — established by the scattering of Jewish-Christian traders along the grain route (cf. 2:10 "strangers of Rome"). Paul''s week-long Sabbath stay evidences Julius'' continuing favour.',
      'The gospel runs ahead of the apostles. Where God''s servants arrive they commonly find brothers they have never met, and rest in the presence of grace already at work.'),
  (15, 'And from thence, when the brethren heard of us, they came to meet us as far as Appii forum, and The three taverns: whom when Paul saw, he thanked God, and took courage.',
      'Κἀκεῖθεν οἱ ἀδελφοὶ ἀκούσαντες τὰ περὶ ἡμῶν, ἐξῆλθον εἰς ἀπάντησιν ἡμῖν ἄχρις Ἀππίου φόρου καὶ Τριῶν ταβερνῶν· οὓς ἰδὼν ὁ Παῦλος, εὐχαριστήσας τῷ Θεῷ, ἔλαβε θάρσος.',
      'Kakeithen hoi adelphoi akousantes ta peri hēmōn, exēlthon eis apantēsin hēmin achris Appiou phorou kai Triōn tabernōn; hous idōn ho Paulos, eucharistēsas tō Theō, elabe tharsos.',
      'Appii Forum was 43 miles from Rome on the Appian Way; The Three Taverns 33 miles out — two separate greeting parties. Paul had written Romans three years earlier (c. AD 57); now those he had never seen run out to meet him on the imperial highway. "Took courage" — the prisoner-apostle is ministered to by the faces he had longed to see (Rom 1:11-12).',
      'Even apostles need the sight of brothers. Christian courage is not self-manufactured; it is rekindled by the gathered face of the body of Christ.'),
  (16, 'And when we came to Rome, the centurion delivered the prisoners to the captain of the guard: but Paul was suffered to dwell by himself with a soldier that kept him.',
      'Ὅτε δὲ ἤλθομεν εἰς Ῥώμην, ὁ ἑκατόνταρχος παρέδωκε τοὺς δεσμίους τῷ στρατοπεδάρχῃ· τῷ δὲ Παύλῳ ἐπετράπη μένειν καθ᾽ ἑαυτόν, σὺν τῷ φυλάσσοντι αὐτὸν στρατιώτῃ.',
      'Hote de ēlthomen eis Rhōmēn, ho hekatontarchos paredōke tous desmious tō stratopedarchē; tō de Paulō epetrapē menein kath'' heauton, syn tō phylassonti auton stratiōtē.',
      '"Captain of the guard" (στρατοπεδάρχης) = Praetorian Prefect, at that date Afranius Burrus (until his death in AD 62). The "custodia libera" arrangement permitted a private apartment with one soldier attached by the chain (v.20).',
      'God grants His servant both chains and a door. The prison is real, but from within it the gospel goes out to the praetorium (Phil 1:13) and the household of Caesar (Phil 4:22).'),
  (17, 'And it came to pass, that after three days Paul called the chief of the Jews together: and when they were come together, he said unto them, Men and brethren, though I have committed nothing against the people, or customs of our fathers, yet was I delivered prisoner from Jerusalem into the hands of the Romans.',
      'Ἐγένετο δὲ μετὰ ἡμέρας τρεῖς συγκαλέσασθαι τὸν Παῦλον τοὺς ὄντας τῶν Ἰουδαίων πρώτους· συνελθόντων δὲ αὐτῶν, ἔλεγε πρὸς αὐτούς, Ἄνδρες ἀδελφοί, ἐγὼ οὐδὲν ἐναντίον ποιήσας τῷ λαῷ ἢ τοῖς ἔθεσι τοῖς πατρῴοις, δέσμιος ἐξ Ἱεροσολύμων παρεδόθην εἰς τὰς χεῖρας τῶν Ῥωμαίων.',
      'Egeneto de meta hēmeras treis sygkalesasthai ton Paulon tous ontas tōn Ioudaiōn prōtous; synelthontōn de autōn, elege pros autous, Andres adelphoi, egō ouden enantion poiēsas tō laō ē tois ethesi tois patrōois, desmios ex Hierosolymōn paredothēn eis tas cheiras tōn Rhōmaiōn.',
      'The Roman Jewish community had synagogues and elders (the "chief" = archontes). Claudius had expelled Jews from Rome c. AD 49 (18:2) but Nero permitted return. Paul maintains his apostolic priority: "to the Jew first" (Rom 1:16).',
      'The gospel begins with reconciliation to one''s own people. The missionary to the Gentiles still opens his mouth in Rome with "Men and brethren."'),
  (18, 'Who, when they had examined me, would have let me go, because there was no cause of death in me.',
      'Οἵτινες ἀνακρίναντές με ἐβούλοντο ἀπολῦσαι, διὰ τὸ μηδεμίαν αἰτίαν θανάτου ὑπάρχειν ἐν ἐμοί.',
      'Hoitines anakrinantes me eboulonto apolysai, dia to mēdemian aitian thanatou hyparchein en emoi.',
      'The repeated Roman verdict of innocence (23:29; 25:25; 26:31-32) is Luke''s apologia for the Roman reader — the Christian faith is not seditious.',
      'The purer the servant, the clearer the magistrate''s verdict of innocence. Righteousness leaves an ever-clearer legal record through trial after trial.'),
  (19, 'But when the Jews spake against it, I was constrained to appeal unto Caesar; not that I had ought to accuse my nation of.',
      'Ἀντιλεγόντων δὲ τῶν Ἰουδαίων, ἠναγκάσθην ἐπικαλέσασθαι Καίσαρα, οὐχ ὡς τοῦ ἔθνους μου ἔχων τι κατηγορῆσαι.',
      'Antilegontōn de tōn Ioudaiōn, ēnankasthēn epikalesasthai Kaisara, ouch hōs tou ethnous mou echōn ti katēgorēsai.',
      'Paul sets the Roman Jews at ease: his appeal to Caesar was defensive, not counter-prosecutory. He loves his nation still (Rom 9:1-5); the chain is not vengeance on his kin but the shelter of law.',
      'The believer does not weaponise the state against unbelieving family and nation. Legal rights are used to preserve the gospel''s going forth, not to punish its opponents.'),
  (20, 'For this cause therefore have I called for you, to see you, and to speak with you: because that for the hope of Israel I am bound with this chain.',
      'Διὰ ταύτην οὖν τὴν αἰτίαν παρεκάλεσα ὑμᾶς ἰδεῖν καὶ προσλαλῆσαι· ἕνεκεν γὰρ τῆς ἐλπίδος τοῦ Ἰσραὴλ τὴν ἅλυσιν ταύτην περίκειμαι.',
      'Dia tautēn oun tēn aitian parekalesa hymas idein kai proslalēsai; heneken gar tēs elpidos tou Israēl tēn halysin tautēn perikeimai.',
      '"Hope of Israel" = the resurrection hope centred in Messiah (23:6; 24:15; 26:6-7). "This chain" (τὴν ἅλυσιν ταύτην) — Paul probably gestures to the chain linking his right hand to the soldier''s left.',
      'The cross and resurrection are not the innovation of a sect but the fulfilment of Israel''s ancient hope. Christ crucified is the one anchor of Abraham''s sons and daughters.'),
  (21, 'And they said unto him, We neither received letters out of Judaea concerning thee, neither any of the brethren that came shewed or spake any harm of thee.',
      'Οἱ δὲ πρὸς αὐτὸν εἶπον, Ἡμεῖς οὔτε γράμματα περὶ σοῦ ἐδεξάμεθα ἀπὸ τῆς Ἰουδαίας, οὔτε παραγενόμενός τις τῶν ἀδελφῶν ἀπήγγειλεν ἢ ἐλάλησέ τι περὶ σοῦ πονηρόν.',
      'Hoi de pros auton eipon, Hēmeis oute grammata peri sou edexametha apo tēs Ioudaias, oute paragenomenos tis tōn adelphōn apēngeilen ē elalēse ti peri sou ponēron.',
      'The Sanhedrin had evidently made no formal attempt to prosecute in Rome — perhaps because Jerusalem was by now increasingly absorbed with local tensions that would erupt in the war of AD 66.',
      'God stills the mouth of the accuser in the imperial capital. Evil reports do not always reach their targets; providence allows a clean hearing where the servant most needs it.'),
  (22, 'But we desire to hear of thee what thou thinkest: for as concerning this sect, we know that every where it is spoken against.',
      'Ἀξιοῦμεν δὲ παρὰ σοῦ ἀκοῦσαι ἃ φρονεῖς· περὶ μὲν γὰρ τῆς αἱρέσεως ταύτης γνωστὸν ἡμῖν ἐστίν ὅτι πανταχοῦ ἀντιλέγεται.',
      'Axioumen de para sou akousai ha phroneis; peri men gar tēs haireseōs tautēs gnōston hēmin estin hoti pantachou antilegetai.',
      '"This sect" (τῆς αἱρέσεως ταύτης) — they know the Christian movement by reputation (a Christian church already existed in Rome). "Every where spoken against" confirms persecution, but curiosity prevails over dismissal.',
      'Opposition is no argument against truth. Where the gospel is everywhere contradicted, its honest hearer is compelled to weigh it carefully rather than shrug it off.'),
  (23, 'And when they had appointed him a day, there came many to him into his lodging; to whom he expounded and testified the kingdom of God, persuading them concerning Jesus, both out of the law of Moses, and out of the prophets, from morning till evening.',
      'Ταξάμενοι δὲ αὐτῷ ἡμέραν, ἧκον πρὸς αὐτὸν εἰς τὴν ξενίαν πλείονες· οἷς ἐξετίθετο διαμαρτυρόμενος τὴν βασιλείαν τοῦ Θεοῦ, πείθων τε αὐτοὺς τὰ περὶ τοῦ Ἰησοῦ, ἀπό τε τοῦ νόμου Μωσέως καὶ τῶν προφητῶν, ἀπὸ πρωὶ ἕως ἑσπέρας.',
      'Taxamenoi de autō hēmeran, hēkon pros auton eis tēn xenian pleiones; hois exetitheto diamartyromenos tēn basileian tou Theou, peithōn te autous ta peri tou Iēsou, apo te tou nomou Mōseōs kai tōn prophētōn, apo prōi heōs hesperas.',
      '"From morning till evening" — a full day''s exposition. The method: kingdom of God as framework, Jesus as fulfilment, Moses and the Prophets as canonical proof. "Expounded" (ἐξετίθετο) and "testified" (διαμαρτυρόμενος) are Paul''s two signature verbs of apostolic preaching.',
      'All Scripture speaks of Christ. A faithful sermon links Moses, prophets, and Jesus in one continuous testimony — never truncating the story, never severing kingdom from king.'),
  (24, 'And some believed the things which were spoken, and some believed not.',
      'Καὶ οἱ μὲν ἐπείθοντο τοῖς λεγομένοις, οἱ δὲ ἠπίστουν.',
      'Kai hoi men epeithonto tois legomenois, hoi de ēpistoun.',
      'The perennial division of the Word (cf. 14:4; 17:4-5, 32; 19:9). Paul''s exposition is neither unclear nor unpersuasive — yet faith is a gift, not a conclusion.',
      'The same sermon produces faith in some hearts and unbelief in others. The Word is a savour of life or of death (2 Cor 2:15-16), and the hearer''s response reveals the ground beneath him.'),
  (25, 'And when they agreed not among themselves, they departed, after that Paul had spoken one word, Well spake the Holy Ghost by Esaias the prophet unto our fathers,',
      'Ἀσύμφωνοι δὲ ὄντες πρὸς ἀλλήλους ἀπελύοντο, εἰπόντος τοῦ Παύλου ῥῆμα ἕν, Ὅτι καλῶς τὸ Πνεῦμα τὸ Ἅγιον ἐλάλησε διὰ Ἠσαΐου τοῦ προφήτου πρὸς τοὺς πατέρας ἡμῶν,',
      'Asymphōnoi de ontes pros allēlous apelyonto, eipontos tou Paulou rhēma hen, Hoti kalōs to Pneuma to Hagion elalēse dia Ēsaiou tou prophētou pros tous pateras hēmōn,',
      '"Well spake the Holy Ghost" — Paul affirms the verbal inspiration of Isaiah. The prophet did not merely write about God, but God spoke through him to the fathers, and still speaks now through the same text.',
      'The inspiration of Scripture is present-tense. When the Spirit spake by Isaiah, He spake to every generation that would open the scroll — including ours.'),
  (26, 'Saying, Go unto this people, and say, Hearing ye shall hear, and shall not understand; and seeing ye shall see, and not perceive:',
      'λέγον, Πορεύθητι πρὸς τὸν λαὸν τοῦτον καὶ εἰπέ, Ἀκοῇ ἀκούσετε, καὶ οὐ μὴ συνῆτε· καὶ βλέποντες βλέψετε, καὶ οὐ μὴ ἴδητε·',
      'legon, Poreuthēti pros ton laon touton kai eipe, Akoē akousete, kai ou mē synēte; kai blepontes blepsete, kai ou mē idēte;',
      'Isaiah 6:9, LXX. This text is the only one quoted in all four Gospels (Matt 13:14-15; Mark 4:12; Luke 8:10; John 12:40) and Acts — a sombre keystone to New Testament theology of unbelief.',
      'Persistent rejection of the Word incurs judicial hardening. The God who speaks to His people also seals up those who despise the speech, and His verdict is executed through their own continued refusal.'),
  (27, 'For the heart of this people is waxed gross, and their ears are dull of hearing, and their eyes have they closed; lest they should see with their eyes, and hear with their ears, and understand with their heart, and should be converted, and I should heal them.',
      'ἐπαχύνθη γὰρ ἡ καρδία τοῦ λαοῦ τούτου, καὶ τοῖς ὠσὶ βαρέως ἤκουσαν, καὶ τοὺς ὀφθαλμοὺς αὐτῶν ἐκάμμυσαν· μήποτε ἴδωσι τοῖς ὀφθαλμοῖς, καὶ τοῖς ὠσὶν ἀκούσωσι, καὶ τῇ καρδίᾳ συνῶσι, καὶ ἐπιστρέψωσι, καὶ ἰάσωμαι αὐτούς.',
      'epachynthē gar hē kardia tou laou toutou, kai tois ōsi bareōs ēkousan, kai tous ophthalmous autōn ekammysan; mēpote idōsi tois ophthalmois, kai tois ōsin akousōsi, kai tē kardia synōsi, kai epistrepsōsi, kai iasōmai autous.',
      '"Waxed gross" (ἐπαχύνθη) — fattened dull; "eyes they closed" (ἐκάμμυσαν) — they shut their own eyes. The hardening has a human side: the people are not passive victims but active closers.',
      'Spiritual blindness is always self-inflicted as well as divinely imposed. Whoever refuses to open the eye at last cannot open it, and the mercy that would have healed him is withdrawn.'),
  (28, 'Be it known therefore unto you, that the salvation of God is sent unto the Gentiles, and that they will hear it.',
      'Γνωστὸν οὖν ἔστω ὑμῖν, ὅτι τοῖς ἔθνεσιν ἀπεστάλη τὸ σωτήριον τοῦ Θεοῦ, αὐτοὶ καὶ ἀκούσονται.',
      'Gnōston oun estō hymin, hoti tois ethnesin apestalē to sōtērion tou Theou, autoi kai akousontai.',
      'The third formal pivot to the Gentiles in Acts (13:46; 18:6; now 28:28) — and Luke''s climactic declaration. "They will hear" ends the verse on a prophetic certainty: the Gentile mission will succeed.',
      'The gospel''s refusal by unbelieving Israel does not defeat the plan of God but releases it. What one nation declines, the nations will receive.'),
  (29, 'And when he had said these words, the Jews departed, and had great reasoning among themselves.',
      'Καὶ ταῦτα αὐτοῦ εἰπόντος, ἀπῆλθον οἱ Ἰουδαῖοι, πολλὴν ἔχοντες ἐν ἑαυτοῖς συζήτησιν.',
      'Kai tauta autou eipontos, apēlthon hoi Ioudaioi, pollēn echontes en heautois syzētēsin.',
      '"Great reasoning" (πολλὴν συζήτησιν) = intense debate. The departing group continues the conversation — the seed, though rejected by some, stirs more among others.',
      'The Word never returns void. Even where hearers depart unconvinced, the Spirit may yet work through disputation to ripen the quiet seed.'),
  (30, 'And Paul dwelt two whole years in his own hired house, and received all that came in unto him,',
      'Ἔμεινε δὲ ὁ Παῦλος διετίαν ὅλην ἐν ἰδίῳ μισθώματι, καὶ ἀπεδέχετο πάντας τοὺς εἰσπορευομένους πρὸς αὐτόν,',
      'Emeine de ho Paulos dietian holēn en idiō misthōmati, kai apedecheto pantas tous eisporeuomenous pros auton,',
      'Two years (c. AD 60-62) in "his own hired house" (μίσθωμα) — a rented apartment funded perhaps by Philippian gifts (Phil 4:10-18). Prison Epistles (Ephesians, Philippians, Colossians, Philemon) written here.',
      'An apostle chained to a soldier is still a door open to the city. The gospel does not require freedom to flourish; it requires a faithful servant and a welcoming home.'),
  (31, 'Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him.',
      'κηρύσσων τὴν βασιλείαν τοῦ Θεοῦ, καὶ διδάσκων τὰ περὶ τοῦ Κυρίου Ἰησοῦ Χριστοῦ, μετὰ πάσης παρρησίας, ἀκωλύτως.',
      'kēryssōn tēn basileian tou Theou, kai didaskōn ta peri tou Kyriou Iēsou Christou, meta pasēs parrēsias, akōlytōs.',
      'The Greek ends on a single adverb — ἀκωλύτως, "unhinderedly" — Luke''s magnificent final word. Kingdom preached (κηρύσσων), Christ taught (διδάσκων), boldness fulfilled (παρρησίας), hindrance excluded (ἀκωλύτως). The book opens in Jerusalem and closes with the unstoppable Word in Rome.',
      'The Word of God is not bound (2 Tim 2:9). Earthly power may chain the messenger, but no human authority can imprison the gospel. The Acts of the Apostles is a book without a final chapter — because the mission continues unhindered until the King returns.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Acts' AND c.chapter_number = 28
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'διασωθέντες', 'diasōthentes', 'G1295', 'Having been brought safely through — the fulfilment of 27:24.', 1),
  (1, 'Μελίτη', 'Melitē', 'G3194', 'Malta — strategic island south of Sicily.', 2),
  (2, 'βάρβαροι', 'barbaroi', 'G915', 'Non-Greek-speakers — Punic-tongued Maltese.', 3),
  (2, 'φιλανθρωπίαν', 'philanthrōpian', 'G5363', 'Kindness toward man — humane hospitality.', 4),
  (3, 'φρυγάνων', 'phryganōn', 'G5434', 'Sticks, brushwood — dry kindling.', 5),
  (3, 'ἔχιδνα', 'echidna', 'G2191', 'Viper — venomous serpent.', 6),
  (3, 'καθῆψε', 'kathēpse', 'G2510', 'Fastened on — the viper''s strike.', 7),
  (4, 'ἡ Δίκη', 'hē Dikē', 'G1349', 'Justice/Dike — Greek goddess of retribution, personified vengeance.', 8),
  (5, 'ἀποτινάξας', 'apotinaxas', 'G660', 'Having shaken off — same gesture as 13:51.', 9),
  (6, 'πίμπρασθαι', 'pimprasthai', 'G4092', 'To be inflamed/swollen — medical term for envenomation.', 10),
  (6, 'μεταβαλλόμενοι', 'metaballomenoi', 'G3328', 'Changing their minds — a reversal of verdict.', 11),
  (7, 'πρώτῳ τῆς νήσου', 'prōtō tēs nēsou', 'G4413/G3520', 'Chief of the island — Maltese official title confirmed by inscription.', 12),
  (7, 'φιλοφρόνως', 'philophronōs', 'G5390', 'Courteously, friendlily — hospitably minded.', 13),
  (8, 'πυρετοῖς', 'pyretois', 'G4446', 'Fevers — plural, recurring (Maltese fever).', 14),
  (8, 'δυσεντερίᾳ', 'dysenteria', 'G1420', 'Dysentery — root of the English term.', 15),
  (8, 'ἰάσατο', 'iasato', 'G2390', 'He healed — the physician''s own verb of cure.', 16),
  (9, 'ἐθεραπεύοντο', 'etherapeuonto', 'G2323', 'Were being healed/cared for — imperfect of extended ministry.', 17),
  (11, 'Διοσκούροις', 'Dioskourois', 'G1359', 'Dioskouroi/Castor and Pollux — twin sons of Zeus, patrons of sailors.', 18),
  (13, 'περιελθόντες', 'perielthontes', 'G4022', 'Having gone around — tacked in a circular course.', 19),
  (13, 'δευτεραῖοι', 'deuteraioi', 'G1206', 'On the second day — two-day fast passage.', 20),
  (14, 'ἀδελφούς', 'adelphous', 'G80', 'Brethren — the church already at Puteoli.', 21),
  (15, 'ἀπάντησιν', 'apantēsin', 'G529', 'Meeting — official welcome of a dignitary.', 22),
  (15, 'θάρσος', 'tharsos', 'G2294', 'Courage, good cheer — the sight of brothers renews apostolic resolve.', 23),
  (16, 'στρατοπεδάρχῃ', 'stratopedarchē', 'G4759', 'Praetorian Prefect — commander of the imperial guard.', 24),
  (20, 'ἐλπίδος τοῦ Ἰσραήλ', 'elpidos tou Israēl', 'G1680/G2474', 'Hope of Israel — the resurrection-Messiah hope.', 25),
  (20, 'ἅλυσιν', 'halysin', 'G254', 'Chain — the iron bond linking prisoner to soldier.', 26),
  (22, 'αἱρέσεως', 'haireseōs', 'G139', 'Sect, party — here applied to the Christian movement.', 27),
  (23, 'ἐξετίθετο', 'exetitheto', 'G1620', 'Expounded, set forth — orderly scriptural exposition.', 28),
  (23, 'διαμαρτυρόμενος', 'diamartyromenos', 'G1263', 'Solemnly testifying — earnest witness-bearing.', 29),
  (23, 'βασιλείαν τοῦ Θεοῦ', 'basileian tou Theou', 'G932/G2316', 'Kingdom of God — Paul''s central preaching theme (v.31).', 30),
  (25, 'καλῶς τὸ Πνεῦμα τὸ Ἅγιον ἐλάλησε', 'kalōs to Pneuma to Hagion elalēse', 'G2573/G4151/G40/G2980', 'Well spake the Holy Spirit — verbal inspiration of Isaiah.', 31),
  (27, 'ἐπαχύνθη', 'epachynthē', 'G3975', 'Was made fat/dull — judicial hardening of the heart.', 32),
  (27, 'ἐκάμμυσαν', 'ekammysan', 'G2576', 'They closed — self-shutting of the eyes.', 33),
  (27, 'ἐπιστρέψωσι', 'epistrepsōsi', 'G1994', 'They should turn/be converted — same verb as 26:18, 20.', 34),
  (28, 'σωτήριον τοῦ Θεοῦ', 'sōtērion tou Theou', 'G4992/G2316', 'Salvation of God — the saving act brought to the nations.', 35),
  (28, 'ἔθνεσιν', 'ethnesin', 'G1484', 'Gentiles, nations — now primary recipients of the kingdom.', 36),
  (30, 'μισθώματι', 'misthōmati', 'G3410', 'Hired house/rented dwelling — Paul''s Roman apartment.', 37),
  (31, 'κηρύσσων', 'kēryssōn', 'G2784', 'Preaching — public herald''s proclamation.', 38),
  (31, 'διδάσκων', 'didaskōn', 'G1321', 'Teaching — systematic instruction in the things of Christ.', 39),
  (31, 'παρρησίας', 'parrēsias', 'G3954', 'All confidence/boldness — Spirit-given free speech.', 40),
  (31, 'ἀκωλύτως', 'akōlytōs', 'G209', 'Without hindrance — the triumphant last word of Acts; the gospel cannot be silenced.', 41)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Acts' AND c.chapter_number = 28 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Acts 27:24', 1),
  (1, 'Acts 27:44', 2),
  (2, 'Rom 2:14-15', 3),
  (2, 'Matt 10:42', 4),
  (3, 'Mark 16:18', 5),
  (3, 'Luke 10:19', 6),
  (4, 'John 9:2', 7),
  (4, 'Job 4:7', 8),
  (5, 'Mark 16:18', 9),
  (5, 'Ps 91:13', 10),
  (5, 'Isa 43:2', 11),
  (6, 'Acts 14:11-13', 12),
  (6, 'Acts 14:19', 13),
  (7, 'Heb 13:2', 14),
  (7, 'Matt 10:41', 15),
  (8, 'Luke 4:38-39', 16),
  (8, 'Mark 16:18', 17),
  (8, 'James 5:14-15', 18),
  (9, 'Matt 4:24', 19),
  (9, 'Acts 5:15-16', 20),
  (10, 'Matt 10:8-10', 21),
  (10, '1 Tim 5:17', 22),
  (11, 'Acts 27:6', 23),
  (13, 'Acts 27:13', 24),
  (14, 'Rom 1:7', 25),
  (14, 'Acts 2:10', 26),
  (15, 'Rom 1:11-12', 27),
  (15, '2 Cor 7:5-7', 28),
  (15, 'Heb 10:25', 29),
  (16, 'Phil 1:13', 30),
  (16, 'Phil 4:22', 31),
  (16, 'Acts 24:23', 32),
  (17, 'Acts 24:12-13', 33),
  (17, 'Acts 25:8', 34),
  (17, 'Rom 1:16', 35),
  (18, 'Acts 23:29', 36),
  (18, 'Acts 25:25', 37),
  (18, 'Acts 26:31-32', 38),
  (19, 'Acts 25:11', 39),
  (19, 'Rom 9:1-5', 40),
  (19, 'Rom 10:1', 41),
  (20, 'Acts 23:6', 42),
  (20, 'Acts 24:15', 43),
  (20, 'Acts 26:6-7', 44),
  (20, 'Eph 6:20', 45),
  (20, '2 Tim 1:16', 46),
  (22, '1 Pet 2:12', 47),
  (22, 'Luke 2:34', 48),
  (23, 'Luke 24:27', 49),
  (23, 'Luke 24:44', 50),
  (23, 'John 5:39', 51),
  (23, 'Acts 17:2-3', 52),
  (23, 'Acts 19:8', 53),
  (24, 'Acts 14:4', 54),
  (24, 'Acts 17:4-5', 55),
  (24, 'Acts 19:9', 56),
  (25, '2 Pet 1:21', 57),
  (25, '2 Tim 3:16', 58),
  (26, 'Isa 6:9-10', 59),
  (26, 'Matt 13:14-15', 60),
  (26, 'Mark 4:12', 61),
  (26, 'Luke 8:10', 62),
  (26, 'John 12:40', 63),
  (27, 'Deut 29:4', 64),
  (27, 'Rom 11:8', 65),
  (27, 'Zech 7:11-12', 66),
  (28, 'Acts 13:46', 67),
  (28, 'Acts 18:6', 68),
  (28, 'Rom 11:11', 69),
  (28, 'Ps 67:2', 70),
  (28, 'Isa 49:6', 71),
  (30, 'Phil 1:12-14', 72),
  (30, 'Eph 6:19-20', 73),
  (30, 'Phil 4:18', 74),
  (31, 'Eph 3:12', 75),
  (31, '2 Tim 2:9', 76),
  (31, '2 Tim 4:17', 77),
  (31, 'Col 4:3-4', 78),
  (31, 'Phil 1:20', 79)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Acts' AND c.chapter_number = 28 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
