-- Acts 24 — Paul Before Felix: The Governor Who Trembled and Delayed
-- Theme: Righteousness, Temperance, Judgment to Come

INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 24,
  'Acts 24 stages Paul''s first formal trial before a Roman governor. Five days after his transfer to Caesarea, the high priest Ananias arrives with elders and a hired orator named Tertullus. Tertullus opens with the obligatory flattery of Felix, then files a three-fold charge: that Paul is a pestilence (loimon) stirring sedition among all the Jews in the world, a ringleader of the sect of the Nazarenes, and a profaner of the temple. Paul replies point by point without rhetorical trick: he has been in Jerusalem only twelve days, no one caught him disputing anywhere, the "sect" called heresy is in fact the way in which he worships the God of his fathers, believing all things written in the law and prophets and holding the same resurrection hope his accusers themselves confess. Felix, "having more perfect knowledge of that way," defers a verdict until Lysias arrives and grants Paul liberty. Later Felix brings his Jewish wife Drusilla — whom he had enticed from King Azizus — to hear Paul, and Paul reasons with them of righteousness, temperance, and judgment to come. Felix trembles (emphobos genomenos) and dismisses the apostle to a more convenient season that never comes. For two years he keeps Paul in soft custody, hoping for a bribe. At the end of the term Porcius Festus succeeds him, and Felix, departing, leaves Paul bound to show favour to the Jews.',
  'Righteousness, Temperance, Judgment to Come',
  'ἔμφοβος',
  'terrified, in fear (emphobos) — Felix''s own reaction in v.25 when Paul reasoned of righteousness, temperance, and judgment.',
  '[{"range":"vv.1-9","title":"Tertullus and the Three-Fold Charge"},{"range":"vv.10-13","title":"Paul''s Denial: ''They Neither Found Me in the Temple Disputing''"},{"range":"vv.14-21","title":"Paul''s Confession: The Way, the Hope, the Resurrection"},{"range":"vv.22-23","title":"Felix Defers and Grants Liberty"},{"range":"vv.24-25","title":"Felix Trembles — The Convenient Season That Never Came"},{"range":"vv.26-27","title":"Two Years of Delay and the Arrival of Festus"}]'::jsonb
FROM books b WHERE b.name = 'Acts'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  overview = EXCLUDED.overview,
  theme = EXCLUDED.theme,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'And after five days Ananias the high priest descended with the elders, and with a certain orator named Tertullus, who informed the governor against Paul.',
      'Μετὰ δὲ πέντε ἡμέρας κατέβη ὁ ἀρχιερεὺς Ἀνανίας μετὰ τῶν πρεσβυτέρων καὶ ῥήτορος Τερτύλλου τινός, οἵτινες ἐνεφάνισαν τῷ ἡγεμόνι κατὰ τοῦ Παύλου.',
      'Meta de pente hēmeras katebē ho archiereus Ananias meta tōn presbyterōn kai rhētoros Tertyllou tinos, hoitines enephanisan tō hēgemoni kata tou Paulou.',
      'Ananias travels the 65 miles to Caesarea — indicating the seriousness the Sanhedrin attached to Paul''s case. Tertullus is a professional forensic rhetor, hired because such formal advocacy was required in Roman provincial courts.',
      'The world hires its best tongues against the gospel. But the Lord''s Advocate pleads the apostle''s cause in a higher court.'),
  (2, 'And when he was called forth, Tertullus began to accuse him, saying, Seeing that by thee we enjoy great quietness, and that very worthy deeds are done unto this nation by thy providence,',
      'κληθέντος δὲ αὐτοῦ, ἤρξατο κατηγορεῖν ὁ Τέρτυλλος λέγων, Πολλῆς εἰρήνης τυγχάνοντες διὰ σοῦ, καὶ κατορθωμάτων γινομένων τῷ ἔθνει τούτῳ διὰ τῆς σῆς προνοίας,',
      'klēthentos de autou, ērxato katēgorein ho Tertyllos legōn, Pollēs eirēnēs tynchanontes dia sou, kai katorthōmatōn ginomenōn tō ethnei toutō dia tēs sēs pronoias,',
      'Tertullus opens with the standard captatio benevolentiae — flattery to court the judge. The flattery is outrageous: Felix had actually crushed Jewish revolts with great cruelty (Josephus, War 2.13.2).',
      'Flattery is the customary currency of worldly courts. The apostle''s integrity exposes its falsity by refusing to trade in it.'),
  (3, 'We accept it always, and in all places, most noble Felix, with all thankfulness.',
      'πάντῃ τε καὶ πανταχοῦ ἀποδεχόμεθα, κράτιστε Φῆλιξ, μετὰ πάσης εὐχαριστίας.',
      'pantē te kai pantachou apodechometha, kratiste Phēlix, meta pasēs eucharistias.',
      'Kratiste ("most noble/excellent") is the imperial honorific, repeated by Paul himself for Festus in 26:25.',
      'Right titles do not mask wrong character. Flowery honorifics cannot dignify what is essentially oppressive.'),
  (4, 'Notwithstanding, that I be not further tedious unto thee, I pray thee that thou wouldest hear us of thy clemency a few words.',
      'ἵνα δὲ μὴ ἐπὶ πλεῖόν σε ἐγκόπτω, παρακαλῶ ἀκοῦσαί σε ἡμῶν συντόμως τῇ σῇ ἐπιεικείᾳ.',
      'hina de mē epi pleion se enkoptō, parakalō akousai se hēmōn syntomōs tē sē epieikeia.',
      'Epieikeia ("clemency, forbearance") — another captatio term. The rhetor is asking for a brief hearing in the judge''s kindness.',
      'The rhetorician''s syrup does not soften a just Judge. Only the truth of the case can stand before God.'),
  (5, 'For we have found this man a pestilent fellow, and a mover of sedition among all the Jews throughout the world, and a ringleader of the sect of the Nazarenes:',
      'εὑρόντες γὰρ τὸν ἄνδρα τοῦτον λοιμόν, καὶ κινοῦντα στάσιν πᾶσι τοῖς Ἰουδαίοις τοῖς κατὰ τὴν οἰκουμένην, πρωτοστάτην τε τῆς τῶν Ναζωραίων αἱρέσεως·',
      'heurontes gar ton andra touton loimon, kai kinounta stasin pasi tois Ioudaiois tois kata tēn oikoumenēn, prōtostatēn te tēs tōn Nazōraiōn haireseōs;',
      'Loimon — "a plague, pestilence" — the strongest term of social disdain. Stasis (sedition) is a political charge Rome took seriously. "Sect of the Nazarenes" — the only NT use of this designation — links Christians to Jesus of Nazareth.',
      'The early Christians were first called "Nazarenes" — a Jesus-branded identity. The stigma of the despised Galilean became the glory of the universal church.'),
  (6, 'Who also hath gone about to profane the temple: whom we took, and would have judged according to our law.',
      'ὃς καὶ τὸ ἱερὸν ἐπείρασε βεβηλῶσαι· ὃν καὶ ἐκρατήσαμεν, καὶ κατὰ τὸν ἡμέτερον νόμον ἠθελήσαμεν κρῖνειν.',
      'hos kai to hieron epeirase bebēlōsai; hon kai ekratēsamen, kai kata ton hēmeteron nomon ēthelēsamen krinein.',
      'The third charge — temple profanation — carried the death penalty under both Jewish and Roman law (the temple inscription authorising execution has been archaeologically recovered).',
      'False accusations dress themselves in the gravest legal robes. What cannot be proved in truth can still be pressed with sincere fury.'),
  (7, 'But the chief captain Lysias came upon us, and with great violence took him away out of our hands,',
      'παρελθὼν δὲ Λυσίας ὁ χιλίαρχος μετὰ πολλῆς βίας ἐκ τῶν χειρῶν ἡμῶν ἀπήγαγε,',
      'parelthōn de Lysias ho chiliarchos meta pollēs bias ek tōn cheirōn hēmōn apēgage,',
      'Tertullus imputes "great violence" to Lysias — an attempt to discredit the Roman officer whose report contradicted their story.',
      'When the gospel is opposed, the helpers of the gospel are slandered next. Every defender of the truth must expect share in the church''s reproach.'),
  (8, 'Commanding his accusers to come unto thee: by examining of whom thyself mayest take knowledge of all these things, whereof we accuse him.',
      'κελεύσας τοὺς κατηγόρους αὐτοῦ ἔρχεσθαι ἐπὶ σέ· παρ᾽ οὗ δυνήσῃ αὐτὸς ἀνακρίνας περὶ πάντων τούτων ἐπιγνῶναι, ὧν ἡμεῖς κατηγοροῦμεν αὐτοῦ.',
      'keleusas tous katēgorous autou erchesthai epi se; par hou dynēsē autos anakrinas peri pantōn toutōn epignōnai, hōn hēmeis katēgoroumen autou.',
      'Tertullus closes — Felix can verify by examining Paul himself.',
      'Men are confident in their case until the light of truth shines. The gospel''s cause needs no rhetorician — only honest examination.'),
  (9, 'And the Jews also assented, saying that these things were so.',
      'συνεπέθεντο δὲ καὶ οἱ Ἰουδαῖοι, φάσκοντες ταῦτα οὕτως ἔχειν.',
      'synepethento de kai hoi Ioudaioi, phaskontes tauta houtōs echein.',
      'The delegation chimes in to endorse the charges — unanimity as intimidation.',
      'Consensus can still be false. Many voices in chorus do not equal one voice of truth.'),
  (10, 'Then Paul, after that the governor had beckoned unto him to speak, answered, Forasmuch as I know that thou hast been of many years a judge unto this nation, I do the more cheerfully answer for myself:',
      'Ἀπεκρίθη δὲ ὁ Παῦλος, νεύσαντος αὐτῷ τοῦ ἡγεμόνος λέγειν, Ἐκ πολλῶν ἐτῶν ὄντα σε κριτὴν τῷ ἔθνει τούτῳ ἐπιστάμενος, εὐθυμότερον τὰ περὶ ἐμαυτοῦ ἀπολογοῦμαι,',
      'Apekrithē de ho Paulos, neusantos autō tou hēgemonos legein, Ek pollōn etōn onta se kritēn tō ethnei toutō epistamenos, euthymoteron ta peri emautou apologoumai,',
      'Paul offers a sober, factual compliment (not flattery): Felix''s long experience qualifies him as informed judge. Felix had been in various Judean posts since c. AD 52 — by AD 57 some five or six years.',
      'Truth can acknowledge experience without exaggerating virtue. Honest speech refuses to bend either toward flattery or contempt.'),
  (11, 'Because that thou mayest understand, that there are yet but twelve days since I went up to Jerusalem for to worship.',
      'δυναμένου σου γνῶναι, ὅτι οὐ πλείους εἰσίν μοι ἡμέραι δεκαδύο ἀφ᾽ ἧς ἀνέβην προσκυνήσων ἐν Ἱερουσαλήμ·',
      'dynamenou sou gnōnai, hoti ou pleious eisin moi hēmerai dekadyo aph hēs anebēn proskynēsōn en Ierousalēm;',
      'Twelve days leaves hardly time for mass sedition. Paul makes his case factually, by verifiable dates.',
      'Truth thrives on calendars. The gospel has nothing to fear from the ordinary facts of dates and places.'),
  (12, 'And they neither found me in the temple disputing with any man, neither raising up the people, neither in the synagogues, nor in the city:',
      'καὶ οὔτε ἐν τῷ ἱερῷ εὗρόν με πρός τινα διαλεγόμενον ἢ ἐπισύστασιν ποιοῦντα ὄχλου, οὔτε ἐν ταῖς συναγωγαῖς, οὔτε κατὰ τὴν πόλιν·',
      'kai oute en tō hierō heuron me pros tina dialegomenon ē episystasin poiounta ochlou, oute en tais synagōgais, oute kata tēn polin;',
      'Three venues checked: temple, synagogues, city. Paul has done nothing in any of them that would constitute the political charge.',
      'The specific denial refutes the general slander. A patient inventory of facts dismantles the rhetoric of enemies.'),
  (13, 'Neither can they prove the things whereof they now accuse me.',
      'οὔτε παραστῆσαι δύναταί με περὶ ὧν νῦν κατηγοροῦσί μου.',
      'oute parastēsai dynatai me peri hōn nyn katēgorousi mou.',
      'Parastēsai — "establish, prove" — the technical legal demand. Paul challenges the accusers to produce evidence.',
      'Truth welcomes the burden of proof. Accusation without evidence is slander; the gospel asks only to be weighed honestly.'),
  (14, 'But this I confess unto thee, that after the way which they call heresy, so worship I the God of my fathers, believing all things which are written in the law and in the prophets:',
      'ὁμολογῶ δὲ τοῦτό σοι, ὅτι κατὰ τὴν ὁδὸν ἣν λέγουσιν αἵρεσιν, οὕτω λατρεύω τῷ πατρῴῳ Θεῷ, πιστεύων πᾶσι τοῖς κατὰ τὸν νόμον καὶ τοῖς ἐν τοῖς προφήταις γεγραμμένοις·',
      'homologō de touto soi, hoti kata tēn hodon hēn legousin hairesin, houtō latreuō tō patrōō Theō, pisteuōn pasi tois kata ton nomon kai tois en tois prophētais gegrammenois;',
      '"The Way" — the self-designation of early Christianity — is dismissed by opponents as hairesis (sect, faction). Paul claims continuity with the patriarchs: the God of his fathers is the God of Jesus Christ.',
      'Christianity is not a new religion but the fulfilment of the old. The gospel stands in continuous covenant with the God of Abraham, Isaac, and Jacob.'),
  (15, 'And have hope toward God, which they themselves also allow, that there shall be a resurrection of the dead, both of the just and unjust.',
      'ἐλπίδα ἔχων εἰς τὸν Θεόν, ἣν καὶ αὐτοὶ οὗτοι προσδέχονται, ἀνάστασιν μέλλειν ἔσεσθαι νεκρῶν, δικαίων τε καὶ ἀδίκων.',
      'elpida echōn eis ton Theon, hēn kai autoi houtoi prosdechontai, anastasin mellein esesthai nekrōn, dikaiōn te kai adikōn.',
      'One of the clearest NT affirmations of a general resurrection — of both just and unjust (cf. John 5:28-29; Rev 20:12-15). Pharisees shared this hope; Paul appeals to their own creed.',
      'The gospel confesses resurrection for all — the just to life, the unjust to judgment. No one will miss the court of God.'),
  (16, 'And herein do I exercise myself, to have always a conscience void of offence toward God, and toward men.',
      'ἐν τούτῳ δὲ αὐτὸς ἀσκῶ, ἀπρόσκοπον συνείδησιν ἔχειν πρὸς τὸν Θεὸν καὶ τοὺς ἀνθρώπους διὰ παντός.',
      'en toutō de autos askō, aproskopon syneidēsin echein pros ton Theon kai tous anthrōpous dia pantos.',
      'Askō ("I discipline myself" — athletic term, root of "ascetic"). Aproskopon — "without stumbling, offence." Paul strives daily to keep his conscience clean Godward and manward.',
      'Hope of resurrection trains present conscience. Those who expect to stand before God cultivate lives that can stand before men.'),
  (17, 'Now after many years I came to bring alms to my nation, and offerings.',
      'δι᾽ ἐτῶν δὲ πλειόνων παρεγενόμην ἐλεημοσύνας ποιήσων εἰς τὸ ἔθνος μου καὶ προσφοράς·',
      'di etōn de pleionōn paregenomēn eleēmosynas poiēsōn eis to ethnos mou kai prosphoras;',
      'This is Paul''s only Acts reference to the Gentile collection (Rom 15:25-28; 2 Cor 8-9). "Offerings" refers to the Nazirite sacrifices he paid for the four men (21:26).',
      'The apostle who preaches grace also administers benevolence. Gospel ministry carries material love for the suffering brethren in its pockets.'),
  (18, 'Whereupon certain Jews from Asia found me purified in the temple, neither with multitude, nor with tumult.',
      'ἐν οἷς εὗρόν με ἡγνισμένον ἐν τῷ ἱερῷ, οὐ μετὰ ὄχλου οὐδὲ μετὰ θορύβου, τινὲς ἀπὸ τῆς Ἀσίας Ἰουδαῖοι·',
      'en hois heuron me hēgnismenon en tō hierō, ou meta ochlou oude meta thorybou, tines apo tēs Asias Ioudaioi;',
      'Paul''s counter: he was purified, not profaning; alone, not with a mob. The Asian Jews who accused him have not shown up — a fatal gap in Roman law, which required accusers to face the accused.',
      'The gospel''s opponents fall silent when called to bring real evidence. Truth waits patiently for the noise of slander to reveal its own emptiness.'),
  (19, 'Who ought to have been here before thee, and object, if they had ought against me.',
      'οὓς δεῖ ἐπὶ σοῦ παρεῖναι, καὶ κατηγορεῖν εἴ τι ἔχοιεν πρός με.',
      'hous dei epi sou pareinai, kai katēgorein ei ti echoien pros me.',
      'Roman law (explicitly under Trajan, Pliny, Ep. 10.96.3) forbade condemnation in absentia of accusers.',
      'God''s providence writes procedural safeguards into pagan law. The very absence of accusers exposes the baseless charge.'),
  (20, 'Or else let these same here say, if they have found any evil doing in me, while I stood before the council,',
      'ἢ αὐτοὶ οὗτοι εἰπάτωσαν εἴ τι εὗρον ἐν ἐμοὶ ἀδίκημα, στάντος μου ἐπὶ τοῦ συνεδρίου,',
      'ē autoi houtoi eipatōsan ei ti heuron en emoi adikēma, stantos mou epi tou synedriou,',
      'Challenge to the men present. They cannot produce the original charge; only the Asian phantom accusers could.',
      'Let the men who are present testify to what they know. When present accusers have nothing, absent charges have less.'),
  (21, 'Except it be for this one voice, that I cried standing among them, Touching the resurrection of the dead I am called in question by you this day.',
      'ἢ περὶ μιᾶς ταύτης φωνῆς, ἧς ἔκραξα ἑστὼς ἐν αὐτοῖς, ὅτι Περὶ ἀναστάσεως νεκρῶν ἐγὼ κρίνομαι σήμερον ὑφ᾽ ὑμῶν.',
      'ē peri mias tautēs phōnēs, hēs ekraxa hestōs en autois, hoti Peri anastaseōs nekrōn egō krinomai sēmeron hyph hymōn.',
      'Paul returns to the resurrection flag of 23:6. The only "offense" they can allege is his confession of a Pharisaic hope.',
      'The gospel''s real offence is always the empty tomb. Remove the resurrection and the Christian has no quarrel with the world; confess it, and every power trembles.'),
  (22, 'And when Felix heard these things, having more perfect knowledge of that way, he deferred them, and said, When Lysias the chief captain shall come down, I will know the uttermost of your matter.',
      'Ἀκούσας δὲ ταῦτα ὁ Φῆλιξ ἀνεβάλετο αὐτούς, ἀκριβέστερον εἰδὼς τὰ περὶ τῆς ὁδοῦ, εἰπών, Ὅταν Λυσίας ὁ χιλίαρχος καταβῇ, διαγνώσομαι τὰ καθ᾽ ὑμᾶς·',
      'Akousas de tauta ho Phēlix anebaleto autous, akribesteron eidōs ta peri tēs hodou, eipōn, Hotan Lysias ho chiliarchos katabē, diagnōsomai ta kath hymas;',
      'Felix has "more perfect knowledge of the Way" — probably through Drusilla or his long tenure in Judaea. "Deferred" (anebaleto) — a procedural delay, technically legal but convenient cover.',
      'Governors educated in Christianity are more dangerous than ignorant ones. To know the Way and still delay is the beginning of Felix''s tragedy.'),
  (23, 'And he commanded a centurion to keep Paul, and to let him have liberty, and that he should forbid none of his acquaintance to minister or come unto him.',
      'διαταξάμενός τε τῷ ἑκατοντάρχῃ τηρεῖσθαι τὸν Παῦλον, ἔχειν τε ἄνεσιν, καὶ μηδένα κωλύειν τῶν ἰδίων αὐτοῦ ὑπηρετεῖν ἢ προσέρχεσθαι αὐτῷ.',
      'diataxamenos te tō hekatontarchē tēreisthai ton Paulon, echein te anesin, kai mēdena kōlyein tōn idiōn autou hypēretein ē proserchesthai autō.',
      'Anesin — "relaxation" — a mild form of custody libera allowing friends to come and go. Paul''s chains are civil but his ministry continues.',
      'Even under guard the apostle''s mission continues. The Lord softens custody for His servants so that the gospel may not be bound.'),
  (24, 'And after certain days, when Felix came with his wife Drusilla, which was a Jewess, he sent for Paul, and heard him concerning the faith in Christ.',
      'Μετὰ δὲ ἡμέρας τινάς, παραγενόμενος ὁ Φῆλιξ σὺν Δρουσίλλῃ τῇ γυναικὶ αὐτοῦ οὔσῃ Ἰουδαίᾳ, μετεπέμψατο τὸν Παῦλον, καὶ ἤκουσεν αὐτοῦ περὶ τῆς εἰς Χριστὸν πίστεως.',
      'Meta de hēmeras tinas, paragenomenos ho Phēlix syn Drousillē tē gynaiki autou ousē Ioudaia, metepempsato ton Paulon, kai ēkousen autou peri tēs eis Christon pisteōs.',
      'Drusilla, youngest daughter of Herod Agrippa I (cf. 12:1), was only 20. Felix seduced her from her husband Azizus of Emesa through a Cypriot magician (Josephus, Ant. 20.7.2). "Faith in Christ" is Paul''s theme.',
      'The governor and his adulterous consort receive a private exposition of the gospel. God brings the word to the proudest marriage; none are too high for the call to repent.'),
  (25, 'And as he reasoned of righteousness, temperance, and judgment to come, Felix trembled, and answered, Go thy way for this time; when I have a convenient season, I will call for thee.',
      'διαλεγομένου δὲ αὐτοῦ περὶ δικαιοσύνης καὶ ἐγκρατείας καὶ τοῦ κρίματος τοῦ μέλλοντος ἔσεσθαι, ἔμφοβος γενόμενος ὁ Φῆλιξ ἀπεκρίθη, Τὸ νῦν ἔχον πορεύου· καιρὸν δὲ μεταλαβών μετακαλέσομαί σε·',
      'dialegomenou de autou peri dikaiosynēs kai enkrateias kai tou krimatos tou mellontos esesthai, emphobos genomenos ho Phēlix apekrithē, To nyn echon poreuou; kairon de metalabōn metakalesomai se;',
      'Three words pierced the governor: dikaiosynē (righteousness — Felix was corrupt), enkrateia (temperance/self-control — his marriage was adulterous), krima to mellon (coming judgment — he had murdered and stolen for years). "Convenient season" (kairon) — a moment that, as far as Scripture records, never comes.',
      'Felix''s tragedy is the tragedy of every delayed repentance. Conviction trembles and still says, "another time" — and the convenient season never arrives this side of the grave.'),
  (26, 'He hoped also that money should have been given him of Paul, that he might loose him: wherefore he sent for him the oftener, and communed with him.',
      'ἅμα δὲ καὶ ἐλπίζων ὅτι χρήματα δοθήσεται αὐτῷ ὑπὸ τοῦ Παύλου, ὅπως λύσῃ αὐτόν· διὸ καὶ πυκνότερον αὐτὸν μεταπεμπόμενος ὡμίλει αὐτῷ.',
      'hama de kai elpizōn hoti chrēmata dothēsetai autō hypo tou Paulou, hopōs lysē auton; dio kai pyknoteron auton metapempomenos hōmilei autō.',
      'Felix is notorious in Roman records for corruption. The Lex Julia de repetundis forbade bribes but was routinely broken. Paul, with the Gentile collection fresh in mind, would have seemed a man with access to funds.',
      'The same ear that trembles under preaching can still calculate for bribes. Human hearts hold reverence and greed in neighbouring chambers, unless grace evict the latter.'),
  (27, 'But after two years Porcius Festus came into Felix'' room: and Felix, willing to shew the Jews a pleasure, left Paul bound.',
      'Διετίας δὲ πληρωθείσης ἔλαβε διάδοχον ὁ Φῆλιξ Πόρκιον Φῆστον· θέλων τε χάριτας καταθέσθαι τοῖς Ἰουδαίοις ὁ Φῆλιξ κατέλιπε τὸν Παῦλον δεδεμένον.',
      'Dietias de plērōtheisēs elabe diadochon ho Phēlix Porkion Phēston; thelōn te charitas katathesthai tois Ioudaiois ho Phēlix katelipe ton Paulon dedemenon.',
      'Two full years (AD 57-59) of "convenient seasons" come and go. Porcius Festus arrives c. AD 59 and will die in office in 62. Felix leaves Paul in chains to buy favour against the Jewish complaints waiting for him in Rome (Josephus, Ant. 20.8.9 — Felix was indeed indicted by the Jerusalem Jews before Nero).',
      'The servant of Christ writes Ephesians and Colossians from a two-year "convenient season." What looked like delay was the Lord''s appointed quiet for the church''s richest epistles.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Acts' AND c.chapter_number = 24
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'ῥήτορος', 'rhētoros', 'G4489', 'Orator — professional forensic advocate.', 1),
  (1, 'Τερτύλλου', 'Tertyllou', 'G5061', 'Tertullus — Latin-named rhetor hired for the case.', 2),
  (2, 'εἰρήνης', 'eirēnēs', 'G1515', 'Peace — Tertullus'' false flattery of Felix.', 3),
  (2, 'προνοίας', 'pronoias', 'G4307', 'Forethought, providence — a term applied to Felix''s "care."', 4),
  (3, 'ἀποδεχόμεθα', 'apodechometha', 'G588', 'We welcome/accept — captatio benevolentiae.', 5),
  (4, 'ἐπιεικείᾳ', 'epieikeia', 'G1932', 'Clemency, forbearance — judge''s kindness.', 6),
  (5, 'λοιμόν', 'loimon', 'G3061', 'Pestilence, plague — strongest term of contempt.', 7),
  (5, 'στάσιν', 'stasin', 'G4714', 'Sedition, insurrection — serious political charge.', 8),
  (5, 'πρωτοστάτην', 'prōtostatēn', 'G4414', 'Ringleader — front-rank man.', 9),
  (5, 'Ναζωραίων αἱρέσεως', 'Nazōraiōn haireseōs', 'G3480/G139', 'Sect of the Nazarenes — earliest formal Christian label.', 10),
  (6, 'βεβηλῶσαι', 'bebēlōsai', 'G953', 'To profane, desecrate — capital charge re: temple.', 11),
  (10, 'ἀπολογοῦμαι', 'apologoumai', 'G626', 'I defend myself — formal judicial reply.', 12),
  (14, 'ὁμολογῶ', 'homologō', 'G3670', 'I confess openly — public testimony.', 13),
  (14, 'ὁδὸν', 'hodon', 'G3598', 'The Way — Christian self-designation.', 14),
  (14, 'αἵρεσιν', 'hairesin', 'G139', 'Sect, party — "heresy" (neutral in classical usage).', 15),
  (14, 'πατρῴῳ Θεῷ', 'patrōō Theō', 'G3971/G2316', 'The God of the fathers — covenant continuity.', 16),
  (15, 'ἐλπίδα', 'elpida', 'G1680', 'Hope — resurrection hope of the patriarchs.', 17),
  (15, 'ἀνάστασιν', 'anastasin', 'G386', 'Resurrection — of just and unjust.', 18),
  (16, 'ἀσκῶ', 'askō', 'G778', 'I discipline, exercise — athletic training (root of ascetic).', 19),
  (16, 'ἀπρόσκοπον', 'aproskopon', 'G677', 'Without offence, unstumbling — cleanness of conscience.', 20),
  (17, 'ἐλεημοσύνας', 'eleēmosynas', 'G1654', 'Alms — benevolence offerings.', 21),
  (17, 'προσφοράς', 'prosphoras', 'G4376', 'Offerings — Nazirite sacrifices (21:26).', 22),
  (22, 'ἀνεβάλετο', 'anebaleto', 'G306', 'Deferred, postponed — procedural delay.', 23),
  (23, 'ἄνεσιν', 'anesin', 'G425', 'Relaxation, easing — custodia libera.', 24),
  (24, 'Δρουσίλλῃ', 'Drousillē', 'G1409', 'Drusilla — Jewess, youngest daughter of Herod Agrippa I.', 25),
  (25, 'δικαιοσύνης', 'dikaiosynēs', 'G1343', 'Righteousness — Paul''s first theme.', 26),
  (25, 'ἐγκρατείας', 'enkrateias', 'G1466', 'Temperance, self-control — second theme; indicts Felix''s marriage.', 27),
  (25, 'κρίματος', 'krimatos', 'G2917', 'Judgment — the coming divine assize.', 28),
  (25, 'ἔμφοβος γενόμενος', 'emphobos genomenos', 'G1719', 'Having become terrified — Felix''s trembling.', 29),
  (25, 'καιρὸν', 'kairon', 'G2540', 'Opportune moment — the convenient season that never comes.', 30),
  (26, 'χρήματα', 'chrēmata', 'G5536', 'Money — hoped-for bribe.', 31),
  (27, 'διετίας', 'dietias', 'G1333', 'Two-year period — Paul''s Caesarean imprisonment.', 32),
  (27, 'Φῆστον', 'Phēston', 'G5347', 'Festus — Porcius Festus, successor procurator (AD 59-62).', 33)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Acts' AND c.chapter_number = 24 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Acts 23:2', 1),
  (2, 'Prov 29:5', 2),
  (3, 'Luke 1:3', 3),
  (3, 'Acts 26:25', 4),
  (5, 'Luke 23:2', 5),
  (5, '1 Pet 2:12', 6),
  (5, 'Matt 2:23', 7),
  (5, 'Acts 28:22', 8),
  (6, 'Acts 21:28-29', 9),
  (7, 'Acts 21:31-32', 10),
  (11, 'Acts 21:17', 11),
  (11, 'Acts 21:27', 12),
  (14, 'Acts 9:2', 13),
  (14, 'Acts 19:9', 14),
  (14, 'Acts 22:4', 15),
  (14, '2 Tim 1:3', 16),
  (14, 'Luke 24:27', 17),
  (14, 'John 5:46', 18),
  (15, 'John 5:28-29', 19),
  (15, 'Dan 12:2', 20),
  (15, 'Rev 20:12-15', 21),
  (15, '1 Cor 15:12-22', 22),
  (16, '1 Cor 9:27', 23),
  (16, '2 Cor 1:12', 24),
  (16, '2 Cor 4:2', 25),
  (16, 'Heb 13:18', 26),
  (17, 'Rom 15:25-28', 27),
  (17, '1 Cor 16:1-4', 28),
  (17, '2 Cor 8:1-15', 29),
  (17, '2 Cor 9:1-15', 30),
  (17, 'Gal 2:10', 31),
  (18, 'Acts 21:26-27', 32),
  (19, 'Acts 25:16', 33),
  (21, 'Acts 23:6', 34),
  (21, 'Acts 26:6-8', 35),
  (23, 'Acts 27:3', 36),
  (23, 'Acts 28:16', 37),
  (24, 'Acts 16:31', 38),
  (24, '1 Tim 1:15', 39),
  (25, '2 Cor 5:10-11', 40),
  (25, 'Rev 20:11-15', 41),
  (25, 'Heb 9:27', 42),
  (25, 'Gal 5:22-23', 43),
  (25, '2 Cor 6:2', 44),
  (25, 'Prov 29:1', 45),
  (26, 'Exod 23:8', 46),
  (26, 'Deut 16:19', 47),
  (27, 'Exod 23:2', 48),
  (27, 'Prov 29:25', 49),
  (27, 'Eph 1:1', 50),
  (27, 'Col 1:1', 51),
  (27, 'Phil 1:12-14', 52)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Acts' AND c.chapter_number = 24 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
