-- Acts 15 — The Jerusalem Council
-- Theme: Saved by the Grace of the Lord Jesus — the Gospel Defined and Defended

INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 15,
  'Acts 15 stands as the theological watershed of the book. Men from Judea come down to Antioch teaching that Gentiles must be circumcised and keep the Law of Moses to be saved. Paul and Barnabas are sent up to Jerusalem with the question. In council the apostles and elders hear Peter recount the Spirit-wrought conversion of Cornelius, receive the missionary report of Paul and Barnabas, and hear James adjudicate by Amos 9 that God is taking out of the Gentiles a people for His name. The council issues a decree refusing the yoke of circumcision and specifying four abstinences that preserve table-fellowship with Jewish brethren. The letter is carried to Antioch by Judas and Silas, who confirm and exhort the church. A sharp contention then arises between Paul and Barnabas over John Mark, leading to their separation: Barnabas takes Mark to Cyprus, while Paul chooses Silas and is commended to the grace of God for the second missionary journey.',
  'Saved by the Grace of the Lord Jesus — the Gospel Defined and Defended',
  'χάριτος',
  'grace (charis) — the unmerited saving favour of the Lord Jesus, by which both Jew and Gentile alike are saved (v.11).',
  '[{"range":"vv.1-5","title":"The Controversy at Antioch and the Journey to Jerusalem"},{"range":"vv.6-11","title":"Peter''s Testimony: Saved by Grace, Not by the Yoke"},{"range":"vv.12-21","title":"Barnabas, Paul, and James''s Judgment from Amos 9"},{"range":"vv.22-29","title":"The Apostolic Letter and Decree"},{"range":"vv.30-35","title":"Reception at Antioch: Joy and Exhortation"},{"range":"vv.36-41","title":"Paul and Barnabas Part; the Second Journey Begins"}]'::jsonb
FROM books b WHERE b.name = 'Acts'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  overview = EXCLUDED.overview,
  theme = EXCLUDED.theme,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'And certain men which came down from Judaea taught the brethren, and said, Except ye be circumcised after the manner of Moses, ye cannot be saved.',
      'Καί τινες κατελθόντες ἀπὸ τῆς Ἰουδαίας ἐδίδασκον τοὺς ἀδελφοὺς ὅτι Ἐὰν μὴ περιτμηθῆτε τῷ ἔθει τῷ Μωϋσέως, οὐ δύνασθε σωθῆναι.',
      'Kai tines katelthontes apo tēs Ioudaias edidaskon tous adelphous hoti Ean mē peritmēthēte tō ethei tō Mōuseōs, ou dynasthe sōthēnai.',
      '"Certain men" — unauthorised teachers (cf. v.24, "we gave no such commandment"). Their error adds a legal condition to faith in Christ, turning grace into debt. This is the Galatian heresy (Gal 1:6-9; 5:2-4).',
      'Any addition to the gospel — circumcision, ritual, law-keeping — destroys the gospel. Salvation is "through the grace of the Lord Jesus Christ" (v.11) plus nothing.'),
  (2, 'When therefore Paul and Barnabas had no small dissension and disputation with them, they determined that Paul and Barnabas, and certain other of them, should go up to Jerusalem unto the apostles and elders about this question.',
      'γενομένης δὲ στάσεως καὶ ζητήσεως οὐκ ὀλίγης τῷ Παύλῳ καὶ τῷ Βαρναβᾷ πρὸς αὐτοὺς ἔταξαν ἀναβαίνειν Παῦλον καὶ Βαρναβᾶν καί τινας ἄλλους ἐξ αὐτῶν πρὸς τοὺς ἀποστόλους καὶ πρεσβυτέρους εἰς Ἰερουσαλὴμ περὶ τοῦ ζητήματος τούτου.',
      'genomenēs de staseōs kai zētēseōs ouk oligēs tō Paulō kai tō Barnaba pros autous etaxan anabainein Paulon kai Barnaban kai tinas allous ex autōn pros tous apostolous kai presbyterous eis Ierousalēm peri tou zētēmatos toutou.',
      '"No small dissension" — Paul defended the gospel publicly (cf. Gal 2:5, "to whom we gave place by subjection, no, not for an hour"). The Antioch church then sends a delegation to Jerusalem — the proper pattern for resolving doctrinal disputes through recognised apostolic authority.',
      'Doctrinal controversy is sometimes a duty, not a sin. The gospel must be contended for (Jude 3); silence where the truth is at stake is treason.'),
  (3, 'And being brought on their way by the church, they passed through Phenice and Samaria, declaring the conversion of the Gentiles: and they caused great joy unto all the brethren.',
      'οἱ μὲν οὖν προπεμφθέντες ὑπὸ τῆς ἐκκλησίας διήρχοντο τήν τε Φοινίκην καὶ Σαμάρειαν ἐκδιηγούμενοι τὴν ἐπιστροφὴν τῶν ἐθνῶν, καὶ ἐποίουν χαρὰν μεγάλην πᾶσιν τοῖς ἀδελφοῖς.',
      'hoi men oun propemphthentes hypo tēs ekklēsias diērchonto tēn te Phoinikēn kai Samareian ekdiēgoumenoi tēn epistrophēn tōn ethnōn, kai epoioun charan megalēn pasin tois adelphois.',
      '"Conversion" is epistrophēn — turning, the same word as 14:15. The Samaritan churches (8:14-17) and Phoenician (11:19) had themselves begun in a mixed Jewish-Gentile setting; they rejoice in confirmation of God''s wider work.',
      'Gentile conversion is not a problem to be lamented but a cause of joy to spiritually healthy saints. The gospel''s worldwide triumph stirs every true believer to gladness.'),
  (4, 'And when they were come to Jerusalem, they were received of the church, and of the apostles and elders, and they declared all things that God had done with them.',
      'παραγενόμενοι δὲ εἰς Ἰερουσαλὴμ παρεδέχθησαν ἀπὸ τῆς ἐκκλησίας καὶ τῶν ἀποστόλων καὶ τῶν πρεσβυτέρων, ἀνήγγειλάν τε ὅσα ὁ θεὸς ἐποίησεν μετ᾽ αὐτῶν.',
      'paragenomenoi de eis Ierousalēm paredechthēsan apo tēs ekklēsias kai tōn apostolōn kai tōn presbyterōn, anēngeilan te hosa ho theos epoiēsen met autōn.',
      'The Antioch delegation is welcomed. Note Luke''s recurrent phrase — "all that God did with them" (cf. 14:27) — the mission report always glorifies the Lord who works, not the workers.',
      'The honour of ministry belongs to God alone; true apostolic reports lift men''s eyes from instruments to the sovereign Worker behind them.'),
  (5, 'But there rose up certain of the sect of the Pharisees which believed, saying, That it was needful to circumcise them, and to command them to keep the law of Moses.',
      'ἐξανέστησαν δέ τινες τῶν ἀπὸ τῆς αἱρέσεως τῶν Φαρισαίων πεπιστευκότες, λέγοντες ὅτι δεῖ περιτέμνειν αὐτοὺς παραγγέλλειν τε τηρεῖν τὸν νόμον Μωϋσέως.',
      'exanestēsan de tines tōn apo tēs haireseōs tōn Pharisaiōn pepisteukotes, legontes hoti dei peritemnein autous parangellein te tērein ton nomon Mōuseōs.',
      '"Believed Pharisees" — a real but still Law-entangled group. They think the Gentiles must be "Jew-ized" before they can be "Christianised." The apostolic church must now distinguish the gospel from its Jewish cultural matrix.',
      'Even true believers may bring with them deep cultural assumptions that distort the gospel. The Spirit purifies the church''s self-understanding by repeated doctrinal crises.'),
  (6, 'And the apostles and elders came together for to consider of this matter.',
      'Συνήχθησάν τε οἱ ἀπόστολοι καὶ οἱ πρεσβύτεροι ἰδεῖν περὶ τοῦ λόγου τούτου.',
      'Synēchthēsan te hoi apostoloi kai hoi presbyteroi idein peri tou logou toutou.',
      'The decision is made by apostles together with elders, not by apostles alone — the pattern for conciliar deliberation. "To consider" (idein) means "to see into, examine."',
      'Christ governs His church through Spirit-gifted leaders meeting in counsel, weighing Scripture and providence together under the Word.'),
  (7, 'And when there had been much disputing, Peter rose up, and said unto them, Men and brethren, ye know how that a good while ago God made choice among us, that the Gentiles by my mouth should hear the word of the gospel, and believe.',
      'πολλῆς δὲ ζητήσεως γενομένης ἀναστὰς Πέτρος εἶπεν πρὸς αὐτούς· Ἄνδρες ἀδελφοί, ὑμεῖς ἐπίστασθε ὅτι ἀφ᾽ ἡμερῶν ἀρχαίων ἐν ὑμῖν ἐξελέξατο ὁ θεὸς διὰ τοῦ στόματός μου ἀκοῦσαι τὰ ἔθνη τὸν λόγον τοῦ εὐαγγελίου καὶ πιστεῦσαι.',
      'pollēs de zētēseōs genomenēs anastas Petros eipen pros autous; Andres adelphoi, hymeis epistasthe hoti aph hēmerōn archaiōn en hymin exelexato ho theos dia tou stomatos mou akousai ta ethnē ton logon tou euangeliou kai pisteusai.',
      'Peter invokes the Cornelius precedent (Acts 10-11) — God''s sovereign election "chose out" (exelexato) that Peter''s mouth would open the Gentile door.',
      'God''s election stands behind every step of mission. The one who chooses the end also chooses the instruments, the time, and the hearers.'),
  (8, 'And God, which knoweth the hearts, bare them witness, giving them the Holy Ghost, even as he did unto us;',
      'καὶ ὁ καρδιογνώστης θεὸς ἐμαρτύρησεν αὐτοῖς δοὺς τὸ πνεῦμα τὸ ἅγιον καθὼς καὶ ἡμῖν,',
      'kai ho kardiognōstēs theos emartyrēsen autois dous to pneuma to hagion kathōs kai hēmin,',
      'Kardiognōstēs ("heart-knower") also appears in 1:24, of the Lord choosing an apostle. God reads hearts, and His witness is the giving of the Spirit to Cornelius''s household (10:44-47), equally as to the apostles at Pentecost.',
      'The gift of the Spirit, not external conformity to Law, is the authentic mark of saving faith. What God equally bestows the church cannot unequally treat.'),
  (9, 'And put no difference between us and them, purifying their hearts by faith.',
      'καὶ οὐδὲν διέκρινεν μεταξὺ ἡμῶν τε καὶ αὐτῶν, τῇ πίστει καθαρίσας τὰς καρδίας αὐτῶν.',
      'kai ouden diekrinen metaxy hēmōn te kai autōn, tē pistei katharisas tas kardias autōn.',
      '"No difference" (ouden diekrinen) nullifies every ceremonial barrier. The heart is cleansed "by faith" (dative of means), not by circumcision. This is the doctrine that will saturate Rom 3-4, Gal 2-3, and Eph 2.',
      'Justification is by faith alone; heart-cleansing is by faith alone. Ceremonies cannot purify what only the blood of Christ, received by faith, makes clean.'),
  (10, 'Now therefore why tempt ye God, to put a yoke upon the neck of the disciples, which neither our fathers nor we were able to bear?',
      'νῦν οὖν τί πειράζετε τὸν θεόν, ἐπιθεῖναι ζυγὸν ἐπὶ τὸν τράχηλον τῶν μαθητῶν ὃν οὔτε οἱ πατέρες ἡμῶν οὔτε ἡμεῖς ἰσχύσαμεν βαστάσαι;',
      'nyn oun ti peirazete ton theon, epitheinai zygon epi ton trachēlon tōn mathētōn hon oute hoi pateres hēmōn oute hēmeis ischysamen bastasai?',
      'To add the Law to the gospel is "tempting God" (peirazete) — testing His patience by contradicting His own revealed work. "Yoke" is Jesus'' own word for the Pharisaic burden (Matt 23:4). No Israelite could bear it; why impose it on Gentiles?',
      'Legalism is not strictness but blasphemy — it demands what God does not, and implicitly accuses God of laying an unbearable yoke on His own people. Christ''s yoke alone is easy (Matt 11:30).'),
  (11, 'But we believe that through the grace of the Lord Jesus Christ we shall be saved, even as they.',
      'ἀλλὰ διὰ τῆς χάριτος τοῦ κυρίου Ἰησοῦ πιστεύομεν σωθῆναι καθ᾽ ὃν τρόπον κἀκεῖνοι.',
      'alla dia tēs charitos tou kyriou Iēsou pisteuomen sōthēnai kath hon tropon kakeinoi.',
      'The key verse — "through the grace of the Lord Jesus" (dia tēs charitos) — is the theological core of Acts 15. Peter declares that Jews are saved in the same way as Gentiles — not Gentiles like Jews, but Jews like Gentiles, by sheer grace through faith.',
      'There is one gospel, one way of salvation, for all sinners in every age: by grace, through faith, in Christ alone. The whole Reformation stands on the ground Peter takes here.'),
  (12, 'Then all the multitude kept silence, and gave audience to Barnabas and Paul, declaring what miracles and wonders God had wrought among the Gentiles by them.',
      'ἐσίγησεν δὲ πᾶν τὸ πλῆθος, καὶ ἤκουον Βαρναβᾶ καὶ Παύλου ἐξηγουμένων ὅσα ἐποίησεν ὁ θεὸς σημεῖα καὶ τέρατα ἐν τοῖς ἔθνεσιν δι᾽ αὐτῶν.',
      'esigēsen de pan to plēthos, kai ēkouon Barnaba kai Paulou exēgoumenōn hosa epoiēsen ho theos sēmeia kai terata en tois ethnesin di autōn.',
      'Silence (esigēsen) signals settled conviction. Peter''s argument is reinforced by the missionary report — God has authenticated the Gentile mission by the same "signs and wonders" that attested the Twelve.',
      'Providential confirmation and apostolic teaching together yield assurance. God vindicates His truth by deed as well as word.'),
  (13, 'And after they had held their peace, James answered, saying, Men and brethren, hearken unto me:',
      'Μετὰ δὲ τὸ σιγῆσαι αὐτοὺς ἀπεκρίθη Ἰάκωβος λέγων· Ἄνδρες ἀδελφοί, ἀκούσατέ μου.',
      'Meta de to sigēsai autous apekrithē Iakōbos legōn; Andres adelphoi, akousate mou.',
      'James, the Lord''s brother (Gal 1:19), presides as moderator — a man universally respected among Jewish believers. He speaks last because he is to render the decisive judgment.',
      'Godly order places strongest voices at decisive moments. The one who will pronounce judgment listens longest.'),
  (14, 'Simeon hath declared how God at the first did visit the Gentiles, to take out of them a people for his name.',
      'Συμεὼν ἐξηγήσατο καθὼς πρῶτον ὁ θεὸς ἐπεσκέψατο λαβεῖν ἐξ ἐθνῶν λαὸν τῷ ὀνόματι αὐτοῦ.',
      'Symeōn exēgēsato kathōs prōton ho theos epeskepsato labein ex ethnōn laon tō onomati autou.',
      '"Simeon" is the Hebrew form of Peter''s original name. "Visited" (epeskepsato) is the OT covenant verb (Gen 21:1; Luke 1:68). "A people for his name" — Gentiles are now gathered into covenant peoplehood not as proselytes to Judaism but directly to God.',
      'God''s purpose from the foundation is to form one people from every nation, called by His name. The Gentile mission is not an afterthought but the fulfilment of ancient promise.'),
  (15, 'And to this agree the words of the prophets; as it is written,',
      'καὶ τούτῳ συμφωνοῦσιν οἱ λόγοι τῶν προφητῶν, καθὼς γέγραπται·',
      'kai toutō symphōnousin hoi logoi tōn prophētōn, kathōs gegraptai;',
      '"Agree" (symphōnousin) — harmonize, sound together. James subordinates present experience to written Scripture; the prophets must verify what Peter has recounted.',
      'Providence is interpreted by Scripture, not Scripture by providence. The written Word is the final court of appeal.'),
  (16, 'After this I will return, and will build again the tabernacle of David, which is fallen down; and I will build again the ruins thereof, and I will set it up:',
      'Μετὰ ταῦτα ἀναστρέψω καὶ ἀνοικοδομήσω τὴν σκηνὴν Δαυὶδ τὴν πεπτωκυῖαν, καὶ τὰ κατεσκαμμένα αὐτῆς ἀνοικοδομήσω καὶ ἀνορθώσω αὐτήν,',
      'Meta tauta anastrepsō kai anoikodomēsō tēn skēnēn Dauid tēn peptōkuian, kai ta kateskammena autēs anoikodomēsō kai anorthōsō autēn,',
      'Amos 9:11-12 (LXX). "Tabernacle of David" = Davidic kingdom-house; its rebuilding is fulfilled in the risen Christ enthroned (13:34) and in the gathering of Gentiles into David''s reconstituted kingdom.',
      'Christ the Son of David is now building His kingdom. Gentile conversion is Davidic restoration — the true Israel renewed around its King.'),
  (17, 'That the residue of men might seek after the Lord, and all the Gentiles, upon whom my name is called, saith the Lord, who doeth all these things.',
      'ὅπως ἂν ἐκζητήσωσιν οἱ κατάλοιποι τῶν ἀνθρώπων τὸν κύριον, καὶ πάντα τὰ ἔθνη ἐφ᾽ οὓς ἐπικέκληται τὸ ὄνομά μου ἐπ᾽ αὐτούς, λέγει κύριος ποιῶν ταῦτα',
      'hopōs an ekzētēsōsin hoi kataloipoi tōn anthrōpōn ton kyrion, kai panta ta ethnē eph hous epikeklētai to onoma mou ep autous, legei kyrios poiōn tauta',
      '"All the Gentiles upon whom my name is called" — God''s name is now placed on the nations, formerly placed only on Israel (Deut 28:10). The Gentile inclusion fulfils prophecy, not frustrates it.',
      'The name-bearing people of God now embraces every nation under heaven. Christ''s church is the true heir of the covenant promises to Israel.'),
  (18, 'Known unto God are all his works from the beginning of the world.',
      'γνωστὰ ἀπ᾽ αἰῶνος.',
      'gnōsta ap aiōnos.',
      '"Known from the ages" — God''s purpose to save Gentiles through Messiah is not a reaction to events but His eternal design.',
      'Nothing the church faces is new to God. Every surprise in history is an unfolding of His eternal counsel.'),
  (19, 'Wherefore my sentence is, that we trouble not them, which from among the Gentiles are turned to God:',
      'διὸ ἐγὼ κρίνω μὴ παρενοχλεῖν τοῖς ἀπὸ τῶν ἐθνῶν ἐπιστρέφουσιν ἐπὶ τὸν θεόν,',
      'dio egō krinō mē parenochlein tois apo tōn ethnōn epistrephousin epi ton theon,',
      '"My sentence" (egō krinō) — James''s authoritative verdict. "Trouble not" (parenochlein) — "add further trouble to." The Gentiles already have enough to bear in forsaking their idols; do not add Mosaic ceremony.',
      'Pastoral wisdom refuses to heap upon new converts burdens God has not imposed. The church must preserve the simplicity that is in Christ.'),
  (20, 'But that we write unto them, that they abstain from pollutions of idols, and from fornication, and from things strangled, and from blood.',
      'ἀλλὰ ἐπιστεῖλαι αὐτοῖς τοῦ ἀπέχεσθαι τῶν ἀλισγημάτων τῶν εἰδώλων καὶ τῆς πορνείας καὶ τοῦ πνικτοῦ καὶ τοῦ αἵματος.',
      'alla episteilai autois tou apechesthai tōn alisgēmatōn tōn eidōlōn kai tēs porneias kai tou pniktou kai tou haimatos.',
      'Four abstinences: (1) pollutions of idols = meat sacrificed and eaten in idol temples (cf. 1 Cor 8-10); (2) fornication = pagan sexual immorality often linked to temple cults; (3) strangled things = animals not bled properly; (4) blood = consumption of blood. The list echoes Lev 17-18 obligations on the "stranger in the land," preserving table-fellowship between Jewish and Gentile believers.',
      'Christian liberty is never license. Love curbs liberty for the sake of the brother''s conscience and the church''s unity.'),
  (21, 'For Moses of old time hath in every city them that preach him, being read in the synagogues every sabbath day.',
      'Μωϋσῆς γὰρ ἐκ γενεῶν ἀρχαίων κατὰ πόλιν τοὺς κηρύσσοντας αὐτὸν ἔχει, ἐν ταῖς συναγωγαῖς κατὰ πᾶν σάββατον ἀναγινωσκόμενος.',
      'Mōusēs gar ek geneōn archaiōn kata polin tous kēryssontas auton echei, en tais synagōgais kata pan sabbaton anaginōskomenos.',
      'Justification for the decree: Jewish sensibilities are widely represented in every city with a synagogue; these four abstinences preserve fellowship with Jewish brethren without imposing circumcision.',
      'Christian freedom is exercised with awareness of one''s neighbour. Wisdom voluntarily limits what faith enjoys for the sake of the weaker brother.'),
  (22, 'Then pleased it the apostles and elders, with the whole church, to send chosen men of their own company to Antioch with Paul and Barnabas; namely, Judas surnamed Barsabas, and Silas, chief men among the brethren:',
      'Τότε ἔδοξε τοῖς ἀποστόλοις καὶ τοῖς πρεσβυτέροις σὺν ὅλῃ τῇ ἐκκλησίᾳ ἐκλεξαμένους ἄνδρας ἐξ αὐτῶν πέμψαι εἰς Ἀντιόχειαν σὺν τῷ Παύλῳ καὶ Βαρναβᾷ, Ἰούδαν τὸν καλούμενον Βαρσαββᾶν καὶ Σιλᾶν, ἄνδρας ἡγουμένους ἐν τοῖς ἀδελφοῖς,',
      'Tote edoxe tois apostolois kai tois presbyterois syn holē tē ekklēsia eklexamenous andras ex autōn pempsai eis Antiocheian syn tō Paulō kai Barnaba, Ioudan ton kaloumenon Barsabban kai Silan, andras hēgoumenous en tois adelphois,',
      '"Pleased" (edoxe) — the council''s decision receives congregational concurrence. Silas (Silvanus) will become Paul''s companion on the second journey (v.40) and co-author of Thessalonians; Judas Barsabbas (perhaps brother of Joseph Barsabbas, 1:23) is otherwise unknown.',
      'Apostolic decisions are received by the whole church. Leaders decide, but the body consents — mutual confirmation safeguards the truth.'),
  (23, 'And they wrote letters by them after this manner; The apostles and elders and brethren send greeting unto the brethren which are of the Gentiles in Antioch and Syria and Cilicia:',
      'γράψαντες διὰ χειρὸς αὐτῶν· Οἱ ἀπόστολοι καὶ οἱ πρεσβύτεροι ἀδελφοὶ τοῖς κατὰ τὴν Ἀντιόχειαν καὶ Συρίαν καὶ Κιλικίαν ἀδελφοῖς τοῖς ἐξ ἐθνῶν χαίρειν.',
      'grapsantes dia cheiros autōn; Hoi apostoloi kai hoi presbyteroi adelphoi tois kata tēn Antiocheian kai Syrian kai Kilikian adelphois tois ex ethnōn chairein.',
      'The conciliar letter is the NT''s first extant synod document. "Brethren of the Gentiles" — the Gentiles are fully embraced as brothers.',
      'Kinship in Christ crosses every ethnic line. The church''s documents and salutations must assume and promote this unity.'),
  (24, 'Forasmuch as we have heard, that certain which went out from us have troubled you with words, subverting your souls, saying, Ye must be circumcised, and keep the law: to whom we gave no such commandment:',
      'Ἐπειδὴ ἠκούσαμεν ὅτι τινὲς ἐξ ἡμῶν ἐτάραξαν ὑμᾶς λόγοις ἀνασκευάζοντες τὰς ψυχὰς ὑμῶν οἷς οὐ διεστειλάμεθα,',
      'Epeidē ēkousamen hoti tines ex hēmōn etaraxan hymas logois anaskeuazontes tas psychas hymōn hois ou diesteilametha,',
      '"Subverting" (anaskeuazontes) — a military term for ransacking or unsettling. The Jerusalem church repudiates the Judaizers: they went out "from us" but carried "no such commandment" from the apostles.',
      'Self-appointed teachers, claiming apostolic backing, can devastate young churches. The true apostolic witness must expose and disown false authority.'),
  (25, 'It seemed good unto us, being assembled with one accord, to send chosen men unto you with our beloved Barnabas and Paul,',
      'ἔδοξεν ἡμῖν γενομένοις ὁμοθυμαδὸν ἐκλεξαμένοις ἄνδρας πέμψαι πρὸς ὑμᾶς σὺν τοῖς ἀγαπητοῖς ἡμῶν Βαρναβᾷ καὶ Παύλῳ,',
      'edoxen hēmin genomenois homothymadon eklexamenois andras pempsai pros hymas syn tois agapētois hēmōn Barnaba kai Paulō,',
      'Homothymadon ("with one accord") is Luke''s favourite church-unity word (1:14; 2:46; 4:24). "Beloved" endorses Paul and Barnabas against the slander that they preached a discount gospel.',
      'The Spirit produces unanimity in the church where Scripture is rightly weighed. Unanimity is the sweet fruit of truth settled.'),
  (26, 'Men that have hazarded their lives for the name of our Lord Jesus Christ.',
      'ἀνθρώποις παραδεδωκόσι τὰς ψυχὰς αὐτῶν ὑπὲρ τοῦ ὀνόματος τοῦ κυρίου ἡμῶν Ἰησοῦ Χριστοῦ.',
      'anthrōpois paradedōkosi tas psychas autōn hyper tou onomatos tou kyriou hēmōn Iēsou Christou.',
      '"Hazarded" (paradedōkosi) — "having handed over" their lives. Paul had been stoned at Lystra (14:19); Barnabas had stood with him throughout.',
      'Faithful ministers have already staked their lives on the Name. Their testimony of suffering is itself credential of their fidelity.'),
  (27, 'We have sent therefore Judas and Silas, who shall also tell you the same things by mouth.',
      'ἀπεστάλκαμεν οὖν Ἰούδαν καὶ Σιλᾶν, καὶ αὐτοὺς διὰ λόγου ἀπαγγέλλοντας τὰ αὐτά.',
      'apestalkamen oun Ioudan kai Silan, kai autous dia logou apangellontas ta auta.',
      'Letter and oral witness together — the decree arrives by both written and spoken confirmation, Judas and Silas voicing in person what the church has written.',
      'God-given truth is safest when borne by tested messengers who can vocally confirm the written word. Letter alone can be misread; mouth without letter can be disputed.'),
  (28, 'For it seemed good to the Holy Ghost, and to us, to lay upon you no greater burden than these necessary things;',
      'ἔδοξεν γὰρ τῷ πνεύματι τῷ ἁγίῳ καὶ ἡμῖν μηδὲν πλέον ἐπιτίθεσθαι ὑμῖν βάρος πλὴν τῶν ἐπάναγκες τούτων,',
      'edoxen gar tō pneumati tō hagiō kai hēmin mēden pleon epitithesthai hymin baros plēn tōn epanankes toutōn,',
      '"Seemed good to the Holy Ghost and to us" — a staggering claim of conciliar confidence, yet properly qualified: the Spirit guides genuine councils in genuine submission to Scripture.',
      'The Spirit works through, not apart from, the ordained assembly of Christ''s church. When Scripture is honoured, the Spirit vindicates the verdict.'),
  (29, 'That ye abstain from meats offered to idols, and from blood, and from things strangled, and from fornication: from which if ye keep yourselves, ye shall do well. Fare ye well.',
      'ἀπέχεσθαι εἰδωλοθύτων καὶ αἵματος καὶ πνικτῶν καὶ πορνείας· ἐξ ὧν διατηροῦντες ἑαυτοὺς εὖ πράξετε. Ἔρρωσθε.',
      'apechesthai eidōlothytōn kai haimatos kai pniktōn kai porneias; ex hōn diatērountes heautous eu praxete. Errōsthe.',
      'The four abstinences repeated as the operative decree. "Fare ye well" (errōsthe) is the conventional letter closing — but here it carries real weight: obedience to the decree will bring welfare.',
      'Loving restraint on Christian liberty yields the church''s long-term welfare. Obedient limits make durable unity.'),
  (30, 'So when they were dismissed, they came to Antioch: and when they had gathered the multitude together, they delivered the epistle:',
      'Οἱ μὲν οὖν ἀπολυθέντες κατῆλθον εἰς Ἀντιόχειαν, καὶ συναγαγόντες τὸ πλῆθος ἐπέδωκαν τὴν ἐπιστολήν·',
      'Hoi men oun apolythentes katēlthon eis Antiocheian, kai synagagontes to plēthos epedōkan tēn epistolēn;',
      'The full Antiochian assembly receives the decree — a congregational meeting, not a private delivery. The church''s peace is restored publicly.',
      'What has disturbed the whole church must be settled before the whole church. Transparent restoration is the Spirit''s way.'),
  (31, 'Which when they had read, they rejoiced for the consolation.',
      'ἀναγνόντες δὲ ἐχάρησαν ἐπὶ τῇ παρακλήσει.',
      'anagnontes de echarēsan epi tē paraklēsei.',
      '"Consolation" (paraklēsis) — literally "calling alongside, encouragement." The decree lifted the burden and relieved anxious consciences.',
      'Biblical liberty produces joy. Where grace is rightly preserved, the church sings.'),
  (32, 'And Judas and Silas, being prophets also themselves, exhorted the brethren with many words, and confirmed them.',
      'Ἰούδας δὲ καὶ Σιλᾶς, καὶ αὐτοὶ προφῆται ὄντες, διὰ λόγου πολλοῦ παρεκάλεσαν τοὺς ἀδελφοὺς καὶ ἐπεστήριξαν·',
      'Ioudas de kai Silas, kai autoi prophētai ontes, dia logou pollou parekalesan tous adelphous kai epestērixan;',
      'Silas''s prophetic gift (cf. 13:1) suits him for apostolic companionship. Parekalesan ("exhorted") + epestērixan ("confirmed") is the classic pastoral pair.',
      'Prophetic exhortation strengthens saints. Settled doctrine yields durable courage only when personally applied to conscience.'),
  (33, 'And after they had tarried there a space, they were let go in peace from the brethren unto the apostles.',
      'ποιήσαντες δὲ χρόνον ἀπελύθησαν μετ᾽ εἰρήνης ἀπὸ τῶν ἀδελφῶν πρὸς τοὺς ἀποστόλους.',
      'poiēsantes de chronon apelythēsan met eirēnēs apo tōn adelphōn pros tous apostolous.',
      'The dispatch "in peace" signals restored fellowship. The crisis born of error has become an occasion of strengthened unity.',
      'Rightly handled controversy binds churches closer in love. Truth and peace go together (Zech 8:19).'),
  (35, 'Paul also and Barnabas continued in Antioch, teaching and preaching the word of the Lord, with many others also.',
      'Παῦλος δὲ καὶ Βαρναβᾶς διέτριβον ἐν Ἀντιοχείᾳ διδάσκοντες καὶ εὐαγγελιζόμενοι μετὰ καὶ ἑτέρων πολλῶν τὸν λόγον τοῦ κυρίου.',
      'Paulos de kai Barnabas dietribon en Antiocheia didaskontes kai euangelizomenoi meta kai heterōn pollōn ton logon tou kyriou.',
      'Antioch continues as a robust teaching center with many workers. The settled church is the seedbed of new missions.',
      'Mature teaching churches naturally produce missionaries. Where the Word is richly taught, feet are shod to carry it further.'),
  (36, 'And some days after Paul said unto Barnabas, Let us go again and visit our brethren in every city where we have preached the word of the Lord, and see how they do.',
      'Μετὰ δέ τινας ἡμέρας εἶπεν πρὸς Βαρναβᾶν Παῦλος· Ἐπιστρέψαντες δὴ ἐπισκεψώμεθα τοὺς ἀδελφοὺς κατὰ πόλιν πᾶσαν ἐν αἷς κατηγγείλαμεν τὸν λόγον τοῦ κυρίου, πῶς ἔχουσιν.',
      'Meta de tinas hēmeras eipen pros Barnaban Paulos; Epistrepsantes dē episkepsōmetha tous adelphous kata polin pasan en hais katēngeilamen ton logon tou kyriou, pōs echousin.',
      'Episkepsōmetha ("let us visit/oversee") — the root of "bishop." Paul''s missionary vision includes follow-up of converted believers, not merely conversion.',
      'True gospel labour does not end at conversion. The shepherd''s heart returns to see how the sheep fare.'),
  (37, 'And Barnabas determined to take with them John, whose surname was Mark.',
      'Βαρναβᾶς δὲ ἐβούλετο συμπαραλαβεῖν καὶ τὸν Ἰωάννην τὸν καλούμενον Μᾶρκον·',
      'Barnabas de ebouleto symparalabein kai ton Iōannēn ton kaloumenon Markon;',
      'Barnabas ("son of consolation") acts as his name: a mentor willing to restore the failed. Mark is his cousin (Col 4:10).',
      'Restoration of stumbled servants is the church''s work. Where a man has fallen, grace-filled mentors must stoop to lift him.'),
  (38, 'But Paul thought not good to take him with them, who departed from them from Pamphylia, and went not with them to the work.',
      'Παῦλος δὲ ἠξίου, τὸν ἀποστάντα ἀπ᾽ αὐτῶν ἀπὸ Παμφυλίας καὶ μὴ συνελθόντα αὐτοῖς εἰς τὸ ἔργον, μὴ συμπαραλαμβάνειν τοῦτον.',
      'Paulos de ēxiou, ton apostanta ap autōn apo Pamphylias kai mē synelthonta autois eis to ergon, mē symparalambanein touton.',
      'Paul remembered Mark''s desertion at Pamphylia (13:13). The two honorable concerns — Barnabas''s tender restoration and Paul''s rigorous standard for tried workers — collide.',
      'Sincere servants may honourably differ on judgment calls. Both mercy and prudence are virtues; neither may absolutize itself.'),
  (39, 'And the contention was so sharp between them, that they departed asunder one from the other: and so Barnabas took Mark, and sailed unto Cyprus;',
      'ἐγένετο δὲ παροξυσμὸς ὥστε ἀποχωρισθῆναι αὐτοὺς ἀπ᾽ ἀλλήλων, τόν τε Βαρναβᾶν παραλαβόντα τὸν Μᾶρκον ἐκπλεῦσαι εἰς Κύπρον.',
      'egeneto de paroxysmos hōste apochōristhēnai autous ap allēlōn, ton te Barnaban paralabonta ton Markon ekpleusai eis Kypron.',
      'Paroxysmos ("sharp contention") — a strong word, honest about the heat of the disagreement. Yet both men continue faithful in separate labour; Mark is later fully restored (2 Tim 4:11 — "profitable to me for the ministry") and writes the Gospel bearing his name.',
      'Even separations among the saints are overruled by Providence to multiply mission. God makes even disagreement bear fruit when both parties remain true to the gospel.'),
  (40, 'And Paul chose Silas, and departed, being recommended by the brethren unto the grace of God.',
      'Παῦλος δὲ ἐπιλεξάμενος Σιλᾶν ἐξῆλθεν παραδοθεὶς τῇ χάριτι τοῦ κυρίου ὑπὸ τῶν ἀδελφῶν,',
      'Paulos de epilexamenos Silan exēlthen paradotheis tē chariti tou kyriou hypo tōn adelphōn,',
      '"Recommended to the grace of God" — the same phrase as 14:26, framing the second journey as another grace-enterprise. Silas brings prophetic gift and Roman citizenship (16:37) to the team.',
      'Every new apostolic venture begins and ends in grace. The church''s commendation is simply to place workers in God''s hand.'),
  (41, 'And he went through Syria and Cilicia, confirming the churches.',
      'διήρχετο δὲ τὴν Συρίαν καὶ Κιλικίαν ἐπιστηρίζων τὰς ἐκκλησίας.',
      'diērcheto de tēn Syrian kai Kilikian epistērizōn tas ekklēsias.',
      'Paul begins the second journey by strengthening the churches of his home region — Cilicia (around Tarsus) had been evangelised during his earlier Tarsus years (9:30).',
      'True mission strengthens before it expands. The apostolic mind cares for the churches already planted even while opening new fields.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Acts' AND c.chapter_number = 15
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'περιτμηθῆτε', 'peritmēthēte', 'G4059', 'Be circumcised — OT covenant sign (Gen 17); here wrongly required for salvation of Gentiles.', 1),
  (1, 'σωθῆναι', 'sōthēnai', 'G4982', 'To be saved — the deliverance from sin and wrath accomplished by Christ, here falsely conditioned on Mosaic obedience.', 2),
  (2, 'στάσεως', 'staseōs', 'G4714', 'Dissension, standing-off — heated public disagreement; the gospel sometimes requires confrontation.', 3),
  (2, 'ζητήσεως', 'zētēseōs', 'G2214', 'Debate, inquiry — formal theological disputation, not mere quarrelling.', 4),
  (2, 'πρεσβυτέρους', 'presbyterous', 'G4245', 'Elders — the governing body alongside the apostles; conciliar authority already present.', 5),
  (3, 'ἐπιστροφὴν', 'epistrophēn', 'G1995', 'Conversion, turning — the radical Godward reorientation of pagan lives.', 6),
  (4, 'παρεδέχθησαν', 'paredechthēsan', 'G3858', 'Were welcomed — received with approval and fellowship.', 7),
  (5, 'αἱρέσεως', 'haireseōs', 'G139', 'Sect, party — here the Pharisee party within the believing community; not yet pejorative.', 8),
  (6, 'ἰδεῖν', 'idein', 'G1492', 'To examine, consider — the council''s mandate is investigation before pronouncement.', 9),
  (7, 'ἐξελέξατο', 'exelexato', 'G1586', 'Chose out, elected — God''s sovereign selection of Peter as the Gentile-door-opener.', 10),
  (8, 'καρδιογνώστης', 'kardiognōstēs', 'G2589', 'Heart-knower — a divine title; God reads hearts and needs no external rites to judge them.', 11),
  (9, 'διέκρινεν', 'diekrinen', 'G1252', 'Distinguished, made a difference — God refused to separate Jew from Gentile in grace.', 12),
  (9, 'καθαρίσας', 'katharisas', 'G2511', 'Having cleansed — moral/spiritual purification; the heart cleansed by faith needs no ritual.', 13),
  (10, 'πειράζετε', 'peirazete', 'G3985', 'Test, tempt — provoke God by contradicting His revealed grace.', 14),
  (10, 'ζυγὸν', 'zygon', 'G2218', 'Yoke — the Pharisaic Law-burden (Matt 23:4); Christ''s yoke is easy (Matt 11:30).', 15),
  (11, 'χάριτος', 'charitos', 'G5485', 'Grace — the chapter''s keyword; God''s unmerited saving favor received through faith alone.', 16),
  (11, 'πιστεύομεν', 'pisteuomen', 'G4100', 'We believe — personal trust; the universal means of saving appropriation for all peoples alike.', 17),
  (12, 'σημεῖα καὶ τέρατα', 'sēmeia kai terata', 'G4592/G5059', 'Signs and wonders — God''s public authentication of the Gentile mission (Heb 2:4).', 18),
  (13, 'Ἰάκωβος', 'Iakōbos', 'G2385', 'James (the Lord''s brother) — respected elder who presides as council moderator (Gal 1:19).', 19),
  (14, 'Συμεὼν', 'Symeōn', 'G4826', 'Simeon — Hebrew form of Peter''s original name, honouring him as Jewish apostle.', 20),
  (14, 'ἐπεσκέψατο', 'epeskepsato', 'G1980', 'Visited — OT covenant verb (Gen 21:1; Luke 1:68); God has visited the Gentiles in grace.', 21),
  (14, 'λαὸν', 'laon', 'G2992', 'A people — covenant-people language formerly reserved for Israel, now extended to Gentiles.', 22),
  (15, 'συμφωνοῦσιν', 'symphōnousin', 'G4856', 'Agree, harmonize — prophetic Scripture sounds together with Spirit-given providence.', 23),
  (16, 'σκηνὴν Δαυὶδ', 'skēnēn Dauid', 'G4633/G1138', 'Tabernacle/tent of David — the fallen Davidic kingdom-house, rebuilt in Christ the Son of David.', 24),
  (16, 'ἀνοικοδομήσω', 'anoikodomēsō', 'G456', 'Rebuild, restore — Christ is restoring David''s kingdom by gathering the nations into His rule.', 25),
  (17, 'ἐκζητήσωσιν', 'ekzētēsōsin', 'G1567', 'Earnestly seek out — the Godward seeking of the nations prophesied by Amos.', 26),
  (18, 'γνωστὰ', 'gnōsta', 'G1110', 'Known things — God''s purposes have been eternally known to Him; nothing is improvised.', 27),
  (19, 'κρίνω', 'krinō', 'G2919', 'I judge — James''s authoritative verdict as council chair.', 28),
  (19, 'παρενοχλεῖν', 'parenochlein', 'G3926', 'Trouble further, harass — James will not pile additional burdens on Gentile converts.', 29),
  (20, 'ἀπέχεσθαι', 'apechesthai', 'G567', 'Abstain, hold oneself away from — the positive command of the decree.', 30),
  (20, 'ἀλισγημάτων εἰδώλων', 'alisgēmatōn eidōlōn', 'G234/G1497', 'Pollutions of idols — meat sacrificed and eaten in temple-feasts.', 31),
  (20, 'πορνείας', 'porneias', 'G4202', 'Fornication — every form of sexual immorality, especially the cultic prostitution endemic to pagan shrines.', 32),
  (20, 'πνικτοῦ', 'pniktou', 'G4156', 'Strangled — animals killed without draining blood, forbidden from Lev 17.', 33),
  (20, 'αἵματος', 'haimatos', 'G129', 'Blood — consumption of blood forbidden in Gen 9:4 and Lev 17:10-14.', 34),
  (22, 'ὁμοθυμαδὸν', 'homothymadon', 'G3661', 'With one accord — Luke''s signature word for Spirit-wrought church unity.', 35),
  (24, 'ἀνασκευάζοντες', 'anaskeuazontes', 'G384', 'Subverting, ransacking — violently unsettling souls with false teaching.', 36),
  (26, 'παραδεδωκόσι τὰς ψυχὰς', 'paradedōkosi tas psychas', 'G3860/G5590', 'Having handed over their lives — a phrase of consecrated risk for Christ''s name.', 37),
  (28, 'ἐπάναγκες', 'epanankes', 'G1876', 'Necessary, indispensable — the four abstinences are the irreducible minimum for fellowship.', 38),
  (31, 'παρακλήσει', 'paraklēsei', 'G3874', 'Consolation, encouragement — the decree lifted anxious consciences into joy.', 39),
  (32, 'ἐπεστήριξαν', 'epestērixan', 'G1991', 'Confirmed, strengthened upon — pastoral fortification of faith.', 40),
  (36, 'ἐπισκεψώμεθα', 'episkepsōmetha', 'G1980', 'Let us visit/oversee — root of episkopos (bishop); missionary oversight.', 41),
  (39, 'παροξυσμὸς', 'paroxysmos', 'G3948', 'Sharp contention — a "paroxysm" of disagreement, strong but not deadly to either servant.', 42),
  (40, 'χάριτι', 'chariti', 'G5485', 'Grace — the commendation formula framing apostolic mission.', 43),
  (41, 'ἐπιστηρίζων', 'epistērizōn', 'G1991', 'Strengthening upon — the recurrent Lukan pastoral verb for follow-up ministry.', 44)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Acts' AND c.chapter_number = 15 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Gal 1:6-9', 1),
  (1, 'Gal 2:4-5', 2),
  (1, 'Gal 5:2-4', 3),
  (1, 'Gen 17:10', 4),
  (1, 'Rom 3:28', 5),
  (1, 'Eph 2:8-9', 6),
  (2, 'Gal 2:1-2', 7),
  (2, 'Jude 1:3', 8),
  (2, '2 Tim 4:7', 9),
  (3, 'Acts 14:27', 10),
  (3, '1 Thess 1:9', 11),
  (3, 'Luke 15:7', 12),
  (4, 'Acts 14:27', 13),
  (4, 'Acts 21:19', 14),
  (5, 'Acts 23:6', 15),
  (5, 'Phil 3:5-6', 16),
  (7, 'Acts 10:44-48', 17),
  (7, 'Acts 11:15-17', 18),
  (7, 'Eph 1:4-5', 19),
  (8, 'Acts 1:24', 20),
  (8, '1 Chr 28:9', 21),
  (8, 'Jer 17:10', 22),
  (8, 'Rom 8:27', 23),
  (8, 'Acts 10:44', 24),
  (9, 'Rom 10:12', 25),
  (9, 'Gal 3:28', 26),
  (9, 'Eph 2:14', 27),
  (9, 'Titus 2:14', 28),
  (9, '1 Pet 1:22', 29),
  (10, 'Matt 11:30', 30),
  (10, 'Matt 23:4', 31),
  (10, 'Gal 5:1', 32),
  (10, 'Rom 7:9-11', 33),
  (10, 'Deut 6:16', 34),
  (11, 'Eph 2:5-8', 35),
  (11, 'Rom 3:24', 36),
  (11, 'Titus 2:11', 37),
  (11, '2 Tim 1:9', 38),
  (11, 'Gal 2:16', 39),
  (11, 'Rom 4:16', 40),
  (12, 'Acts 14:27', 41),
  (12, 'Heb 2:4', 42),
  (13, 'Gal 1:19', 43),
  (13, 'Gal 2:9', 44),
  (13, 'Acts 12:17', 45),
  (14, '1 Pet 2:9-10', 46),
  (14, 'Deut 14:2', 47),
  (14, 'Rom 9:24-25', 48),
  (15, '2 Pet 1:19', 49),
  (15, 'Rom 3:21', 50),
  (16, 'Amos 9:11-12', 51),
  (16, 'Isa 9:7', 52),
  (16, '2 Sam 7:12-13', 53),
  (16, 'Acts 13:34', 54),
  (17, 'Isa 2:2-3', 55),
  (17, 'Isa 42:6', 56),
  (17, 'Zech 8:22', 57),
  (17, 'Rev 7:9', 58),
  (17, 'Deut 28:10', 59),
  (18, 'Isa 46:10', 60),
  (18, 'Eph 1:11', 61),
  (18, 'Rom 8:29', 62),
  (19, 'Matt 23:4', 63),
  (19, 'Gal 5:1', 64),
  (20, 'Lev 17:10-14', 65),
  (20, 'Lev 18:26', 66),
  (20, 'Gen 9:4', 67),
  (20, '1 Cor 8:1-13', 68),
  (20, '1 Cor 10:14-22', 69),
  (20, 'Rev 2:14', 70),
  (20, 'Rev 2:20', 71),
  (20, '1 Thess 4:3', 72),
  (21, 'Acts 13:15', 73),
  (21, 'Acts 13:27', 74),
  (22, 'Acts 1:23', 75),
  (22, '2 Cor 1:19', 76),
  (22, '1 Thess 1:1', 77),
  (24, 'Gal 1:7', 78),
  (24, 'Acts 15:1', 79),
  (25, 'Acts 1:14', 80),
  (25, 'Acts 2:46', 81),
  (26, 'Acts 14:19', 82),
  (26, '2 Cor 11:23-27', 83),
  (27, '1 Pet 5:12', 84),
  (28, 'John 16:13', 85),
  (28, '1 Cor 7:40', 86),
  (29, 'Lev 17:10-14', 87),
  (29, '1 Cor 8:7-13', 88),
  (30, 'Acts 13:1', 89),
  (31, 'Rom 15:4', 90),
  (31, '2 Cor 1:3-4', 91),
  (32, 'Acts 13:1', 92),
  (32, '1 Cor 14:3', 93),
  (32, '1 Thess 3:2', 94),
  (33, 'Zech 8:19', 95),
  (33, 'Heb 13:20-21', 96),
  (35, 'Acts 13:1', 97),
  (35, 'Acts 18:11', 98),
  (36, '1 Thess 3:5', 99),
  (36, '2 Cor 11:28', 100),
  (37, 'Col 4:10', 101),
  (37, 'Acts 13:5', 102),
  (38, 'Acts 13:13', 103),
  (39, '2 Tim 4:11', 104),
  (39, 'Phm 1:24', 105),
  (39, '1 Pet 5:13', 106),
  (40, 'Acts 14:26', 107),
  (40, '1 Pet 5:12', 108),
  (40, 'Acts 16:37', 109),
  (41, 'Acts 9:30', 110),
  (41, 'Gal 1:21', 111)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Acts' AND c.chapter_number = 15 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
