-- Acts 22 — Paul's Defense in Hebrew: The Testimony of a Transformed Jew
-- Theme: A Hebrew of Hebrews Sent to the Gentiles

INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 22,
  'Acts 22 is Paul''s first of five defences — the Hebrew-spoken apologia delivered from the Antonia stairs to the Jerusalem mob. Opening in Aramaic to gain their ear, Paul rehearses his impeccable Jewish credentials: a Tarsian Jew raised in Jerusalem, trained at the feet of Gamaliel, once as zealous a persecutor of the Way as any present. He recounts the Damascus road in first-person detail — noonday light, heavenly voice, blindness, and the commissioning words of Jesus. The devout Ananias, "a man according to the law, having a good report of all the Jews," baptises him and reveals the Lord''s purpose: "Thou shalt be his witness unto all men." Paul then narrates a temple vision he has never recounted elsewhere — the Lord warning him to flee Jerusalem and commissioning him explicitly to the Gentiles. At the word "Gentiles" (v.21) the mob erupts, casting off their garments and flinging dust. The chief captain orders Paul scourged to extract the truth; Paul halts the stretcher with the question that stops Rome: "Is it lawful for you to scourge a man that is a Roman, and uncondemned?" Claudius Lysias, startled, discovers his prisoner is a citizen by birth. Scourging cancelled, Lysias convenes the Sanhedrin the next day to determine the Jewish charge.',
  'A Hebrew of Hebrews Sent to the Gentiles',
  'μάρτυς',
  'witness (martys) — from the noun comes "martyr"; the Lord has chosen Paul to be His witness to all men (v.15).',
  '[{"range":"vv.1-5","title":"Pharisee, Gamaliel''s Pupil, Persecutor of the Way"},{"range":"vv.6-11","title":"The Damascus Road: Light, Voice, Blindness"},{"range":"vv.12-16","title":"Ananias, the Just Man: Baptism and the Call to Witness"},{"range":"vv.17-21","title":"The Temple Trance and Commission to the Gentiles"},{"range":"vv.22-24","title":"The Mob Breaks at ''Gentiles''; Lysias Orders Scourging"},{"range":"vv.25-29","title":"Roman Citizenship Halts the Lash"},{"range":"v.30","title":"The Sanhedrin Summoned"}]'::jsonb
FROM books b WHERE b.name = 'Acts'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  overview = EXCLUDED.overview,
  theme = EXCLUDED.theme,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Men, brethren, and fathers, hear ye my defence which I make now unto you.',
      'Ἄνδρες ἀδελφοὶ καὶ πατέρες, ἀκούσατέ μου τῆς πρὸς ὑμᾶς νυνὶ ἀπολογίας.',
      'Andres adelphoi kai pateres, akousate mou tēs pros hymas nyni apologias.',
      'Identical opening to Stephen''s (Acts 7:2). "Apologia" is the technical Greek term for a formal judicial defence — root of "apologetics."',
      'The gospel answers in the courts of men with reverent address and reasoned defence. "Apologia" is the Christian''s birthright whenever truth is assailed.'),
  (2, '(And when they heard that he spake in the Hebrew tongue to them, they kept the more silence: and he saith,)',
      'Ἀκούσαντες δὲ ὅτι τῇ Ἑβραΐδι διαλέκτῳ προσεφώνει αὐτοῖς, μᾶλλον παρέσχον ἡσυχίαν. καί φησιν,',
      'Akousantes de hoti tē Hebraïdi dialektō prosephōnei autois, mallon pareschon hēsychian. kai phēsin,',
      'Aramaic ("Hebrew tongue") signalled he was no Hellenistic outsider. The mob hushes further — Paul is one of their own.',
      'Speaking the mother-tongue wins a hearing the lingua franca cannot. Incarnational ministry meets men where they think and pray.'),
  (3, 'I am verily a man which am a Jew, born in Tarsus, a city in Cilicia, yet brought up in this city at the feet of Gamaliel, and taught according to the perfect manner of the law of the fathers, and was zealous toward God, as ye all are this day.',
      'Ἐγὼ μέν εἰμι ἀνὴρ Ἰουδαῖος, γεγεννημένος ἐν Ταρσῷ τῆς Κιλικίας, ἀνατεθραμμένος δὲ ἐν τῇ πόλει ταύτῃ παρὰ τοὺς πόδας Γαμαλιήλ, πεπαιδευμένος κατὰ ἀκρίβειαν τοῦ πατρῴου νόμου, ζηλωτὴς ὑπάρχων τοῦ Θεοῦ, καθὼς πάντες ὑμεῖς ἐστε σήμερον.',
      'Egō men eimi anēr Ioudaios, gegennēmenos en Tarsō tēs Kilikias, anatethrammenos de en tē polei tautē para tous podas Gamaliēl, pepaideumenos kata akribeian tou patrōou nomou, zēlōtēs hyparchōn tou Theou, kathōs pantes hymeis este sēmeron.',
      'Three verbs: "born" (gegennēmenos) in Tarsus, "brought up" (anatethrammenos) in Jerusalem, "taught" (pepaideumenos) by Gamaliel (cf. 5:34). Gamaliel I was grandson of Hillel, foremost Pharisee of his era. "At the feet" is rabbinic posture of the disciple.',
      'Rabbinic training, scriptural precision, and native zeal are no substitute for grace, but they prepare a vessel. God often fashions His apostles through the very orthodoxy they later preach to.'),
  (4, 'And I persecuted this way unto the death, binding and delivering into prisons both men and women.',
      'ὃς ταύτην τὴν Ὁδὸν ἐδίωξα ἄχρι θανάτου, δεσμεύων καὶ παραδιδοὺς εἰς φυλακὰς ἄνδρας τε καὶ γυναῖκας.',
      'hos tautēn tēn Hodon ediōxa achri thanatou, desmeuōn kai paradidous eis phylakas andras te kai gynaikas.',
      '"This Way" (hodos) is the earliest designation for Christianity (cf. 9:2; 19:9; 24:14). "Unto death" confirms Paul''s complicity in capital proceedings (cf. 26:10-11).',
      'The man who once bound others is now bound himself. Grace writes the convert''s biography with the poetic justice of mercy.'),
  (5, 'As also the high priest doth bear me witness, and all the estate of the elders: from whom also I received letters unto the brethren, and went to Damascus, to bring them which were there bound unto Jerusalem, for to be punished.',
      'Ὡς καὶ ὁ ἀρχιερεὺς μαρτυρεῖ μοι, καὶ πᾶν τὸ πρεσβυτέριον· παρ᾽ ὧν καὶ ἐπιστολὰς δεξάμενος πρὸς τοὺς ἀδελφούς, εἰς Δαμασκὸν ἐπορευόμην, ἄξων καὶ τοὺς ἐκεῖσε ὄντας δεδεμένους εἰς Ἱερουσαλήμ, ἵνα τιμωρηθῶσιν.',
      'Hōs kai ho archiereus martyrei moi, kai pan to presbyterion; par hōn kai epistolas dexamenos pros tous adelphous, eis Damaskon eporeuomēn, axōn kai tous ekeise ontas dedemenous eis Ierousalēm, hina timōrēthōsin.',
      'The presbyterion is the Sanhedrin''s council of elders. Living witnesses to Paul''s former zeal are still available to confirm his story.',
      'Conversion stories stand or fall on verifiable history. Paul invites his accusers themselves to confirm the facts of his former life.'),
  (6, 'And it came to pass, that, as I made my journey, and was come nigh unto Damascus about noon, suddenly there shone from heaven a great light round about me.',
      'Ἐγένετο δέ μοι πορευομένῳ καὶ ἐγγίζοντι τῇ Δαμασκῷ, περὶ μεσημβρίαν, ἐξαίφνης ἐκ τοῦ οὐρανοῦ περιαστράψαι φῶς ἱκανὸν περὶ ἐμέ.',
      'Egeneto de moi poreuomenō kai engizonti tē Damaskō, peri mesēmbrian, exaiphnēs ek tou ouranou periastrapsai phōs hikanon peri eme.',
      '"About noon" intensifies the miracle — the light outshines the Syrian midday sun (cf. 26:13 "above the brightness of the sun"). This detail, absent in ch.9, is added here for a Jewish audience acquainted with Shekinah imagery.',
      'The glorified Christ outshines the noonday sun. His apocalypse to Paul is not borrowed dream but scorching divine self-disclosure.'),
  (7, 'And I fell unto the ground, and heard a voice saying unto me, Saul, Saul, why persecutest thou me?',
      'ἔπεσόν τε εἰς τὸ ἔδαφος, καὶ ἤκουσα φωνῆς λεγούσης μοι, Σαοὺλ Σαούλ, τί με διώκεις;',
      'epeson te eis to edaphos, kai ēkousa phōnēs legousēs moi, Saoul Saoul, ti me diōkeis?',
      'The name is doubled in Hebrew form ("Saoul Saoul") — the address of intimacy and summons (Gen 22:11; Exod 3:4; 1 Sam 3:10).',
      'The Lord names His persecutors by name before calling them. The voice that stops Saul is the voice of covenant love — terrible in mercy.'),
  (8, 'And I answered, Who art thou, Lord? And he said unto me, I am Jesus of Nazareth, whom thou persecutest.',
      'ἐγὼ δὲ ἀπεκρίθην, Τίς εἶ, Κύριε; εἶπέ τε πρός με, Ἐγώ εἰμι Ἰησοῦς ὁ Ναζωραῖος ὃν σὺ διώκεις.',
      'egō de apekrithēn, Tis ei, Kyrie? eipe te pros me, Egō eimi Iēsous ho Nazōraios hon sy diōkeis.',
      '"Jesus of Nazareth" — the crucified Galilean — is the exalted Lord. The title that had been scorn (Mark 14:67) is now glory.',
      'To persecute Christ''s people is to persecute Christ Himself. The head in heaven feels every wound inflicted on His body on earth.'),
  (9, 'And they that were with me saw indeed the light, and were afraid; but they heard not the voice of him that spake to me.',
      'οἱ δὲ σὺν ἐμοὶ ὄντες τὸ μὲν φῶς ἐθεάσαντο, καὶ ἔμφοβοι ἐγένοντο· τὴν δὲ φωνὴν οὐκ ἤκουσαν τοῦ λαλοῦντός μοι.',
      'hoi de syn emoi ontes to men phōs etheasanto, kai emphoboi egenonto; tēn de phōnēn ouk ēkousan tou lalountos moi.',
      'Acts 9:7 says they "heard the voice" (akouontes) but saw no one; 22:9 says they "heard not the voice" (ouk ēkousan). Resolved by the accusative vs. genitive case: they heard sound (9:7) but not intelligible speech (22:9). Paul alone received the message.',
      'The same voice may be sound to onlookers and word to the called. God addresses His chosen in the midst of crowds, who hear nothing articulate.'),
  (10, 'And I said, What shall I do, Lord? And the Lord said unto me, Arise, and go into Damascus; and there it shall be told thee of all things which are appointed for thee to do.',
      'εἶπον δέ, Τί ποιήσω, Κύριε; ὁ δὲ Κύριος εἶπε πρός με, Ἀναστὰς πορεύου εἰς Δαμασκόν· κἀκεῖ σοι λαληθήσεται περὶ πάντων ὧν τέτακταί σοι ποιῆσαι.',
      'eipon de, Ti poiēsō, Kyrie? ho de Kyrios eipe pros me, Anastas poreuou eis Damaskon; kakei soi lalēthēsetai peri pantōn hōn tetaktai soi poiēsai.',
      'Tetaktai (perfect passive) — "has been appointed." Paul''s life-work is already fixed in heaven''s books before he is told what it is.',
      'Conversion yields instant obedience — "What shall I do, Lord?" The service of Christ begins with the surrender of one''s doings to His command.'),
  (11, 'And when I could not see for the glory of that light, being led by the hand of them that were with me, I came into Damascus.',
      'ὡς δὲ οὐκ ἐνέβλεπον ἀπὸ τῆς δόξης τοῦ φωτὸς ἐκείνου, χειραγωγούμενος ὑπὸ τῶν συνόντων μοι, ἦλθον εἰς Δαμασκόν.',
      'hōs de ouk eneblepon apo tēs doxēs tou phōtos ekeinou, cheiragōgoumenos hypo tōn synontōn moi, ēlthon eis Damaskon.',
      'The inquisitor who came to lead others bound now stumbles through Damascus led by others. The glory that blinded Saul was the glory of the Christ he had denied.',
      'The light of Christ''s glory first blinds the proud eye before opening the new one. Self-sufficiency must collapse before grace can be received.'),
  (12, 'And one Ananias, a devout man according to the law, having a good report of all the Jews which dwelt there,',
      'Ἀνανίας δέ τις, ἀνὴρ εὐσεβὴς κατὰ τὸν νόμον, μαρτυρούμενος ὑπὸ πάντων τῶν κατοικούντων ἐν Δαμασκῷ Ἰουδαίων,',
      'Ananias de tis, anēr eusebēs kata ton nomon, martyroumenos hypo pantōn tōn katoikountōn en Damaskō Ioudaiōn,',
      'Paul stresses Ananias''s Jewish piety — crucial for this Jerusalem audience. A Torah-observant Jew in good standing with the Damascus synagogue is Saul''s first Christian teacher.',
      'Christianity is not the repudiation of Moses but his fulfilment. The law-observant Jew is fit instrument to announce Messiah''s salvation to the rabbinic zealot.'),
  (13, 'Came unto me, and stood, and said unto me, Brother Saul, receive thy sight. And the same hour I looked up upon him.',
      'ἐλθὼν πρός με καὶ ἐπιστὰς εἶπέ μοι, Σαοὺλ ἀδελφέ, ἀνάβλεψον. κἀγὼ αὐτῇ τῇ ὥρᾳ ἀνέβλεψα εἰς αὐτόν.',
      'elthōn pros me kai epistas eipe moi, Saoul adelphe, anablepson. kagō autē tē hōra aneblepsa eis auton.',
      '"Brother Saul" — the first word a Christian spoke to Paul was "brother." The man who hunted disciples is embraced as kin.',
      'The gospel''s first word to the convert is "brother." Where once there was persecution, fellowship now reigns.'),
  (14, 'And he said, The God of our fathers hath chosen thee, that thou shouldest know his will, and see that Just One, and shouldest hear the voice of his mouth.',
      'ὁ δὲ εἶπεν, Ὁ Θεὸς τῶν πατέρων ἡμῶν προεχειρίσατό σε γνῶναι τὸ θέλημα αὐτοῦ, καὶ ἰδεῖν τὸν Δίκαιον, καὶ ἀκοῦσαι φωνὴν ἐκ τοῦ στόματος αὐτοῦ.',
      'ho de eipen, Ho Theos tōn paterōn hēmōn proecheirisato se gnōnai to thelēma autou, kai idein ton Dikaion, kai akousai phōnēn ek tou stomatos autou.',
      '"The God of our fathers" — Abraham''s God, not a new deity. "The Just One" (ho Dikaios) — a messianic title from Isa 53:11 (cf. Acts 3:14; 7:52). Proecheirisato — "foreordained, chose beforehand."',
      'Conversion is the outworking of prior election. The God of the patriarchs foreordained Paul to see His righteous One, as He foreordains every saint to behold the glory of His Son.'),
  (15, 'For thou shalt be his witness unto all men of what thou hast seen and heard.',
      'ὅτι ἔσῃ μάρτυς αὐτῷ πρὸς πάντας ἀνθρώπους ὧν ἑώρακας καὶ ἤκουσας.',
      'hoti esē martys autō pros pantas anthrōpous hōn heōrakas kai ēkousas.',
      'Martys — a juridical witness testifying to what he himself has seen and heard. The English "martyr" derives directly.',
      'The Christian witness testifies only to what he has experienced of Christ. Personal encounter with the risen Lord is the bedrock of evangelical proclamation.'),
  (16, 'And now why tarriest thou? arise, and be baptized, and wash away thy sins, calling on the name of the Lord.',
      'καὶ νῦν τί μέλλεις; ἀναστὰς βάπτισαι καὶ ἀπόλουσαι τὰς ἁμαρτίας σου, ἐπικαλεσάμενος τὸ ὄνομα τοῦ Κυρίου.',
      'kai nyn ti melleis? anastas baptisai kai apolousai tas hamartias sou, epikalesamenos to onoma tou Kyriou.',
      '"Wash away" (apolousai) is middle voice: "have thy sins washed away." Baptism is the sign of the cleansing; the name of the Lord, invoked in faith, is the instrument.',
      'Baptism signifies but faith effects the washing. The call on the name of the Lord is the heart''s confession that the sign portrays outwardly.'),
  (17, 'And it came to pass, that, when I was come again to Jerusalem, even while I prayed in the temple, I was in a trance;',
      'ἐγένετο δέ μοι ὑποστρέψαντι εἰς Ἱερουσαλήμ, καὶ προσευχομένου μου ἐν τῷ ἱερῷ, γενέσθαι με ἐν ἐκστάσει,',
      'egeneto de moi hypostrepsanti eis Ierousalēm, kai proseuchomenou mou en tō hierō, genesthai me en ekstasei,',
      '"Trance" (ekstasis) is the same state Peter experienced at Joppa (10:10). This temple vision of Paul''s is recorded only here — unpublished till this moment.',
      'The Spirit speaks in extraordinary ways to ordinary prayer. Even the apostle''s visions arise from the posture of kneeling prayer in God''s house.'),
  (18, 'And saw him saying unto me, Make haste, and get thee quickly out of Jerusalem: for they will not receive thy testimony concerning me.',
      'καὶ ἰδεῖν αὐτὸν λέγοντά μοι, Σπεῦσον καὶ ἔξελθε ἐν τάχει ἐξ Ἱερουσαλήμ· διότι οὐ παραδέξονταί σου τὴν μαρτυρίαν περὶ ἐμοῦ.',
      'kai idein auton legonta moi, Speuson kai exelthe en tachei ex Ierousalēm; dioti ou paradexontai sou tēn martyrian peri emou.',
      'The Lord Jesus Himself appears in the vision. His command foreshadows the present crowd''s rejection — "they will not receive thy testimony."',
      'The risen Christ directs His apostles personally. Even painful redeployments — "get thee quickly out" — are His tender orders of love.'),
  (19, 'And I said, Lord, they know that I imprisoned and beat in every synagogue them that believed on thee:',
      'κἀγὼ εἶπον, Κύριε, αὐτοὶ ἐπίστανται ὅτι ἐγὼ ἤμην φυλακίζων καὶ δέρων κατὰ τὰς συναγωγὰς τοὺς πιστεύοντας ἐπὶ σέ·',
      'kagō eipon, Kyrie, autoi epistantai hoti egō ēmēn phylakizōn kai derōn kata tas synagōgas tous pisteuontas epi se;',
      'Paul himself had reasoned that his former zeal would lend his new testimony credibility. His assumption is overruled.',
      'Our best reasoning about gospel strategy must yield to the Lord''s wisdom. The logic of heaven is not always the logic of our plans.'),
  (20, 'And when the blood of thy martyr Stephen was shed, I also was standing by, and consenting unto his death, and kept the raiment of them that slew him.',
      'καὶ ὅτε ἐξεχεῖτο τὸ αἷμα Στεφάνου τοῦ μάρτυρός σου, καὶ αὐτὸς ἤμην ἐφεστὼς καὶ συνευδοκῶν τῇ ἀναιρέσει αὐτοῦ, καὶ φυλάσσων τὰ ἱμάτια τῶν ἀναιρούντων αὐτόν.',
      'kai hote exechein to haima Stephanou tou martyros sou, kai autos ēmēn ephestōs kai syneudokōn tē anairesei autou, kai phylassōn ta himatia tōn anairountōn auton.',
      'Stephen is here called "thy martys" — "thy witness" — the same word (v.15) that Christ used of Paul. The first Christian martyr''s blood shaped the future apostle.',
      'The church''s first martyr was a teacher to the apostle who buried his coat. Even persecutors stand watch over the garments of saints whose deaths will later convert them.'),
  (21, 'And he said unto me, Depart: for I will send thee far hence unto the Gentiles.',
      'καὶ εἶπε πρός με, Πορεύου· ὅτι ἐγὼ εἰς ἔθνη μακρὰν ἐξαποστελῶ σε.',
      'kai eipe pros me, Poreuou; hoti egō eis ethnē makran exapostelō se.',
      'The word that detonates the mob (v.22). "Far hence unto the Gentiles" offends Jewish particularism. Yet this was Christ''s explicit commission (cf. Gal 1:15-16; 2:2).',
      'The Lord who died for "all men" (1 Tim 2:5-6) sends His heralds "far hence" to every people. Gentile mission is not a concession but a commission of the risen Christ.'),
  (22, 'And they gave him audience unto this word, and then lifted up their voices, and said, Away with such a fellow from the earth: for it is not fit that he should live.',
      'ἤκουον δὲ αὐτοῦ ἄχρι τούτου τοῦ λόγου, καὶ ἐπῆραν τὴν φωνὴν αὐτῶν λέγοντες, Αἶρε ἀπὸ τῆς γῆς τὸν τοιοῦτον· οὐ γὰρ καθῆκον αὐτὸν ζῆν.',
      'ēkouon de autou achri toutou tou logou, kai epēran tēn phōnēn autōn legontes, Aire apo tēs gēs ton toiouton; ou gar kathēkon auton zēn.',
      'The single word "Gentiles" is the flashpoint. "Away from the earth" — the same verb (airō) used against Jesus (John 19:15; Luke 23:18). The Jonah-scandal of grace for all nations outrages the zealot mob.',
      'The scandal of the gospel is its welcome of the outsider. Religious nationalism would rather execute the preacher than make room for the despised.'),
  (23, 'And as they cried out, and cast off their clothes, and threw dust into the air,',
      'κραυγαζόντων δὲ αὐτῶν, καὶ ῥιπτούντων τὰ ἱμάτια, καὶ κονιορτὸν βαλλόντων εἰς τὸν ἀέρα,',
      'kraugazontōn de autōn, kai rhiptountōn ta himatia, kai koniorton ballontōn eis ton aera,',
      'Ritualized rage. Shaking off clothing and flinging dust are Eastern signs of outrage and mourning, as at an execution — tantamount to "blasphemy, worthy of death" (cf. 2 Sam 16:13).',
      'Fury puts on the gestures of religion. Dust and torn garments can mask a heart closed to the truth they pretend to mourn.'),
  (24, 'The chief captain commanded him to be brought into the castle, and bade that he should be examined by scourging; that he might know wherefore they cried so against him.',
      'ἐκέλευσεν αὐτὸν ὁ χιλίαρχος ἄγεσθαι εἰς τὴν παρεμβολήν, εἰπὼν μάστιξιν ἀνετάζεσθαι αὐτόν, ἵνα ἐπιγνῷ δι᾽ ἣν αἰτίαν οὕτως ἐπεφώνουν αὐτῷ.',
      'ekeleusen auton ho chiliarchos agesthai eis tēn parembolēn, eipōn mastixin anetazesthai auton, hina epignō di hēn aitian houtōs epephōnoun autō.',
      'Roman judicial torture (quaestio) extracted confessions from slaves and foreigners. The scourge (mastix) was the leather-and-bone flagellum, often fatal.',
      'Pagan justice strikes first and asks afterward. Without revealed law no governor has the wisdom even to know what questions to ask.'),
  (25, 'And as they bound him with thongs, Paul said unto the centurion that stood by, Is it lawful for you to scourge a man that is a Roman, and uncondemned?',
      'ὡς δὲ προέτειναν αὐτὸν τοῖς ἱμᾶσιν, εἶπε πρὸς τὸν ἑστῶτα ἑκατόνταρχον ὁ Παῦλος, Εἰ ἄνθρωπον Ῥωμαῖον καὶ ἀκατάκριτον ἔξεστιν ὑμῖν μαστίζειν;',
      'hōs de proeteinan auton tois himasin, eipe pros ton hestōta hekatontarchon ho Paulos, Ei anthrōpon Rhōmaion kai akatakriton exestin hymin mastizein?',
      'The Lex Porcia and Lex Julia forbade scourging or chaining a Roman citizen without trial. Cicero called it a grave crime. "Uncondemned" (akatakriton) doubles the illegality.',
      'The apostle uses lawful means in lawful causes. Invoking civil rights to serve the gospel is not unbelief but prudence.'),
  (26, 'When the centurion heard that, he went and told the chief captain, saying, Take heed what thou doest: for this man is a Roman.',
      'ἀκούσας δὲ ὁ ἑκατόνταρχος, προσελθὼν ἀπήγγειλε τῷ χιλιάρχῳ λέγων, Ὅρα τί μέλλεις ποιεῖν· ὁ γὰρ ἄνθρωπος οὗτος Ῥωμαῖός ἐστι.',
      'akousas de ho hekatontarchos, proselthōn apēngeile tō chiliarchō legōn, Hora ti melleis poiein; ho gar anthrōpos houtos Rhōmaios esti.',
      'The centurion breaks off to warn his superior. Roman ranks are scrupulous about citizen rights; a wrong here could cost careers.',
      'Imperial law shelters God''s servant in the moment of crisis. Providence uses even the empire''s self-interest to guard the preacher.'),
  (27, 'Then the chief captain came, and said unto him, Tell me, art thou a Roman? He said, Yea.',
      'προσελθὼν δὲ ὁ χιλίαρχος εἶπεν αὐτῷ, Λέγε μοι, εἰ σὺ Ῥωμαῖος εἶ; Ὁ δὲ ἔφη, Ναί.',
      'proselthōn de ho chiliarchos eipen autō, Lege moi, ei sy Rhōmaios ei? Ho de ephē, Nai.',
      'The tribune''s terse question gets Paul''s terse answer — nai ("Yes"). No theatricality; the fact settles the case.',
      'Truth, plainly spoken, can in a moment deliver from unjust violence. One firm word turns the machinery of empire.'),
  (28, 'And the chief captain answered, With a great sum obtained I this freedom. And Paul said, But I was free born.',
      'ἀπεκρίθη τε ὁ χιλίαρχος, Ἐγὼ πολλοῦ κεφαλαίου τὴν πολιτείαν ταύτην ἐκτησάμην. Ὁ δὲ Παῦλος ἔφη, Ἐγὼ δὲ καὶ γεγέννημαι.',
      'apekrithē te ho chiliarchos, Egō pollou kephalaiou tēn politeian tautēn ektēsamēn. Ho de Paulos ephē, Egō de kai gegennēmai.',
      'Under Claudius, citizenship was sometimes for sale (Dio Cassius 60.17). Lysias bought his; Paul inherited his — a still higher standing. Paul''s father or ancestor must have been enfranchised before him.',
      'Inherited privileges may serve kingdom purposes when laid at Christ''s feet. What is providentially given is providentially used.'),
  (29, 'Then straightway they departed from him which should have examined him: and the chief captain also was afraid, after he knew that he was a Roman, and because he had bound him.',
      'εὐθέως οὖν ἀπέστησαν ἀπ᾽ αὐτοῦ οἱ μέλλοντες αὐτὸν ἀνετάζειν· καὶ ὁ χιλίαρχος δὲ ἐφοβήθη, ἐπιγνοὺς ὅτι Ῥωμαῖός ἐστι, καὶ ὅτι ἦν αὐτὸν δεδεκώς.',
      'eutheōs oun apestēsan ap autou hoi mellontes auton anetazein; kai ho chiliarchos de ephobēthē, epignous hoti Rhōmaios esti, kai hoti ēn auton dedekōs.',
      'Lysias himself had bound Paul (21:33); this was another illegality. Now he is frightened — an imperial inquiry could cost him his rank.',
      'Those who use unjust force fear the judgment of higher powers. God uses earthly hierarchies to restrain earthly cruelties.'),
  (30, 'On the morrow, because he would have known the certainty wherefore he was accused of the Jews, he loosed him from his bands, and commanded the chief priests and all their council to appear, and brought Paul down, and set him before them.',
      'Τῇ δὲ ἐπαύριον βουλόμενος γνῶναι τὸ ἀσφαλές, τὸ τί κατηγορεῖται παρὰ τῶν Ἰουδαίων, ἔλυσεν αὐτὸν ἀπὸ τῶν δεσμῶν, καὶ ἐκέλευσεν ἐλθεῖν τοὺς ἀρχιερεῖς καὶ ὅλον τὸ συνέδριον αὐτῶν, καὶ καταγαγὼν τὸν Παῦλον ἔστησεν εἰς αὐτούς.',
      'Tē de epaurion boulomenos gnōnai to asphales, to ti katēgoreitai para tōn Ioudaiōn, elysen auton apo tōn desmōn, kai ekeleusen elthein tous archiereis kai holon to synedrion autōn, kai katagagōn ton Paulon estēsen eis autous.',
      'The Roman tribune summons the Sanhedrin — remarkable, for the high priest''s council normally convened on its own authority. Lysias needed an explanation of the charge; Paul becomes the occasion for Rome and Jerusalem to meet.',
      'God stages unusual courtrooms for His servants. Civil and religious authorities alike convene at the Lord''s direction to hear the gospel.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Acts' AND c.chapter_number = 22
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'ἀπολογίας', 'apologias', 'G627', 'Defence — formal judicial reply; root of "apologetics."', 1),
  (3, 'ἀνατεθραμμένος', 'anatethrammenos', 'G397', 'Brought up, nurtured — formal upbringing in Jerusalem.', 2),
  (3, 'Γαμαλιήλ', 'Gamaliēl', 'G1059', 'Gamaliel — grandson of Hillel, foremost Pharisee teacher.', 3),
  (3, 'ἀκρίβειαν', 'akribeian', 'G195', 'Exactness, strictness — perfectionistic rabbinic training.', 4),
  (3, 'ζηλωτὴς', 'zēlōtēs', 'G2207', 'Zealot — passionate for God''s law.', 5),
  (4, 'τὴν Ὁδὸν', 'tēn Hodon', 'G3598', 'The Way — earliest name for Christianity.', 6),
  (5, 'πρεσβυτέριον', 'presbyterion', 'G4244', 'Presbytery, council of elders — the Sanhedrin.', 7),
  (6, 'μεσημβρίαν', 'mesēmbrian', 'G3314', 'Midday, noon — when the light outshone the sun.', 8),
  (6, 'περιαστράψαι', 'periastrapsai', 'G4015', 'To flash around — sudden lightning-like brilliance.', 9),
  (8, 'Ναζωραῖος', 'Nazōraios', 'G3480', 'Nazarene — contemptuous title now glorified.', 10),
  (10, 'τέτακταί', 'tetaktai', 'G5021', 'Has been appointed — perfect passive of divine ordination.', 11),
  (11, 'χειραγωγούμενος', 'cheiragōgoumenos', 'G5496', 'Being led by the hand — helpless as a child.', 12),
  (12, 'εὐσεβὴς', 'eusebēs', 'G2152', 'Devout, pious — Torah-observant.', 13),
  (14, 'προεχειρίσατό', 'proecheirisato', 'G4400', 'Foreordained, chose beforehand — divine election.', 14),
  (14, 'τὸν Δίκαιον', 'ton Dikaion', 'G1342', 'The Just One — messianic title (Isa 53:11; Acts 3:14).', 15),
  (15, 'μάρτυς', 'martys', 'G3144', 'Witness — juridical eyewitness; source of "martyr."', 16),
  (16, 'ἀπόλουσαι', 'apolousai', 'G628', 'Wash thyself — middle voice; baptismal cleansing by faith.', 17),
  (16, 'ἐπικαλεσάμενος', 'epikalesamenos', 'G1941', 'Having called upon — invoking the name in faith.', 18),
  (17, 'ἐκστάσει', 'ekstasei', 'G1611', 'Trance, ecstasy — same state as Peter at Joppa (10:10).', 19),
  (18, 'σπεῦσον', 'speuson', 'G4692', 'Make haste — urgent imperatival command.', 20),
  (20, 'Στεφάνου', 'Stephanou', 'G4736', 'Stephen — first Christian martyr (Acts 7).', 21),
  (20, 'συνευδοκῶν', 'syneudokōn', 'G4909', 'Consenting with, approving — Paul''s guilt at Stephen''s death.', 22),
  (21, 'ἔθνη μακρὰν', 'ethnē makran', 'G1484/G3112', 'Gentiles far off — Eph 2:13, the Gentile mission flashpoint.', 23),
  (22, 'καθῆκον', 'kathēkon', 'G2520', 'Fitting — "not fit that he should live."', 24),
  (23, 'κονιορτὸν', 'koniorton', 'G2868', 'Dust — flung in rage; Eastern gesture of outrage.', 25),
  (24, 'μάστιξιν', 'mastixin', 'G3148', 'Scourges — Roman flagellum, often fatal.', 26),
  (24, 'ἀνετάζεσθαι', 'anetazesthai', 'G426', 'To examine judicially — here, under torture.', 27),
  (25, 'Ῥωμαῖον', 'Rhōmaion', 'G4514', 'Roman — citizen of the empire.', 28),
  (25, 'ἀκατάκριτον', 'akatakriton', 'G178', 'Uncondemned — without trial.', 29),
  (28, 'πολιτείαν', 'politeian', 'G4174', 'Citizenship — the franchise of Rome.', 30),
  (28, 'γεγέννημαι', 'gegennēmai', 'G1080', 'Have been born — free by birth, not by purchase.', 31),
  (30, 'συνέδριον', 'synedrion', 'G4892', 'Sanhedrin — the Jewish supreme court of 71 elders.', 32)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Acts' AND c.chapter_number = 22 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Acts 7:2', 1),
  (1, '1 Pet 3:15', 2),
  (3, 'Acts 5:34', 3),
  (3, 'Phil 3:5-6', 4),
  (3, 'Gal 1:14', 5),
  (4, 'Acts 8:3', 6),
  (4, 'Acts 9:1-2', 7),
  (4, 'Acts 26:10-11', 8),
  (4, '1 Tim 1:13', 9),
  (6, 'Acts 9:3', 10),
  (6, 'Acts 26:13', 11),
  (7, 'Gen 22:11', 12),
  (7, 'Exod 3:4', 13),
  (7, '1 Sam 3:10', 14),
  (8, 'Matt 25:40', 15),
  (8, 'Matt 25:45', 16),
  (9, 'Acts 9:7', 17),
  (10, 'Acts 9:6', 18),
  (10, 'Eph 2:10', 19),
  (12, 'Acts 9:10', 20),
  (13, 'Acts 9:17', 21),
  (14, 'Acts 3:14', 22),
  (14, 'Acts 7:52', 23),
  (14, 'Isa 53:11', 24),
  (14, '1 Pet 1:19', 25),
  (15, 'Acts 1:8', 26),
  (15, 'Acts 23:11', 27),
  (15, 'Acts 26:16', 28),
  (16, 'Acts 2:38', 29),
  (16, '1 Cor 6:11', 30),
  (16, 'Heb 10:22', 31),
  (16, 'Rom 10:13', 32),
  (17, 'Acts 10:10', 33),
  (17, '2 Cor 12:1-4', 34),
  (18, 'Matt 10:14', 35),
  (18, 'Matt 10:23', 36),
  (20, 'Acts 7:58-60', 37),
  (20, 'Acts 8:1', 38),
  (21, 'Acts 9:15', 39),
  (21, 'Acts 13:46-47', 40),
  (21, 'Gal 1:15-16', 41),
  (21, 'Gal 2:7-8', 42),
  (21, 'Eph 3:8', 43),
  (22, 'John 19:15', 44),
  (22, 'Luke 23:18', 45),
  (22, 'Acts 21:36', 46),
  (23, '2 Sam 16:13', 47),
  (25, 'Acts 16:37', 48),
  (25, 'Acts 25:16', 49),
  (28, 'Acts 16:37-38', 50),
  (28, 'Phil 3:20', 51),
  (29, 'Acts 21:33', 52),
  (30, 'Matt 10:17-18', 53),
  (30, 'Luke 21:12-13', 54)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Acts' AND c.chapter_number = 22 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
