-- Acts 18 — Corinth, Priscilla and Aquila, and Apollos
-- Theme: The Lord''s Many People in a Hard City

INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 18,
  'Acts 18 tells of Paul''s eighteen-month ministry at Corinth — a wealthy, immoral port city where he lodges with Aquila and Priscilla, tentmakers exiled from Rome by Claudius. Reasoning weekly in the synagogue, he is opposed and blasphemed; he shakes his raiment and turns to the Gentiles, dwelling next door at the house of Justus. Crispus, ruler of the synagogue, believes with his household, and many Corinthians are converted and baptized. The Lord speaks to Paul by night: "Be not afraid, for I have much people in this city." After eighteen months, the Jews drag Paul before Gallio, proconsul of Achaia, who refuses to judge a religious dispute. Paul then sails for Syria with Priscilla and Aquila, leaves them at Ephesus, keeps a vow at Cenchrea, visits Jerusalem, and returns to Antioch, ending the second journey. The chapter closes by introducing Apollos, the eloquent Alexandrian Jew whose partial knowledge is completed by Priscilla and Aquila, opening the third journey.',
  'The Lord''s Many People in a Hard City',
  'λαός',
  'people (laos) — the chosen covenant-people of God, elect from every city including Corinth, guaranteed by the Lord''s own promise (v.10).',
  '[{"range":"vv.1-4","title":"Corinth: Paul with Aquila and Priscilla, Tentmaking and Reasoning"},{"range":"vv.5-11","title":"Turning to the Gentiles; the Lord''s Promise by Night"},{"range":"vv.12-17","title":"Gallio''s Refusal: the Religious Charge Dismissed"},{"range":"vv.18-22","title":"Return Journey: Cenchrea, Ephesus, Jerusalem, Antioch"},{"range":"vv.23-28","title":"Third Journey Begins; Apollos Taught the Way More Perfectly"}]'::jsonb
FROM books b WHERE b.name = 'Acts'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  overview = EXCLUDED.overview,
  theme = EXCLUDED.theme,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'After these things Paul departed from Athens, and came to Corinth;',
      'Μετὰ ταῦτα χωρισθεὶς ἐκ τῶν Ἀθηνῶν ἦλθεν εἰς Κόρινθον.',
      'Meta tauta chōristheis ek tōn Athēnōn ēlthen eis Korinthon.',
      'From Athens — city of philosophers — to Corinth — city of commerce and lust. Corinth, a seaport of 200,000, hosted the temple of Aphrodite with its 1,000 cult prostitutes. Paul arrived "in weakness, and in fear, and in much trembling" (1 Cor 2:3).',
      'God sends His servants not only to intellectual strongholds but to sensual ones. No city is beyond the reach of the gospel, though every city has its own fortress.'),
  (2, 'And found a certain Jew named Aquila, born in Pontus, lately come from Italy, with his wife Priscilla; (because that Claudius had commanded all Jews to depart from Rome) and came unto them.',
      'καὶ εὑρών τινα Ἰουδαῖον ὀνόματι Ἀκύλαν, Ποντικὸν τῷ γένει, προσφάτως ἐληλυθότα ἀπὸ τῆς Ἰταλίας καὶ Πρίσκιλλαν γυναῖκα αὐτοῦ, διὰ τὸ διατεταχέναι Κλαύδιον χωρίζεσθαι πάντας τοὺς Ἰουδαίους ἀπὸ τῆς Ῥώμης, προσῆλθεν αὐτοῖς·',
      'kai heurōn tina Ioudaion onomati Akylan, Pontikon tō genei, prosphatōs elēlythota apo tēs Italias kai Priskillan gynaika autou, dia to diatetachenai Klaudion chōrizesthai pantas tous Ioudaious apo tēs Rhōmēs, prosēlthen autois;',
      'Suetonius (Claudius 25.4) records Claudius expelled Jews from Rome c. AD 49 because of riots "at the instigation of Chrestus" — probably synagogue disputes about Christ. Priscilla is always named first in three of six NT references, suggesting prominence.',
      'Imperial edicts serve God''s providential purposes. The very expulsion that displaced Aquila and Priscilla placed them beside Paul in Corinth, then in Ephesus, then in Rome — strategic fruit no emperor intended.'),
  (3, 'And because he was of the same craft, he abode with them, and wrought: for by their occupation they were tentmakers.',
      'καὶ διὰ τὸ ὁμότεχνον εἶναι ἔμενεν παρ᾽ αὐτοῖς καὶ ἠργάζετο· ἦσαν γὰρ σκηνοποιοὶ τῇ τέχνῃ.',
      'kai dia to homotechnon einai emenen par autois kai ērgazeto; ēsan gar skēnopoioi tē technē.',
      'Skēnopoioi, "tentmakers," likely worked in cilicium (goat-hair cloth from Cilicia) for tents, sails, and cloaks. Rabbis traditionally supported themselves by a trade. Paul later points to this manual labour (1 Cor 4:12; 9:6; 1 Thess 2:9; 2 Thess 3:8).',
      'The apostle labours with his own hands that he might not burden his hearers. Honest craft is no dishonour to ministry; bivocational mission preserves integrity where patrons could corrupt it.'),
  (4, 'And he reasoned in the synagogue every sabbath, and persuaded the Jews and the Greeks.',
      'διελέγετο δὲ ἐν τῇ συναγωγῇ κατὰ πᾶν σάββατον, ἔπειθέν τε Ἰουδαίους καὶ Ἕλληνας.',
      'dielegeto de en tē synagōgē kata pan sabbaton, epeithen te Ioudaious kai Hellēnas.',
      'The same word "reasoned" (dielegeto) and weekly pattern as Thessalonica and Athens. "Persuaded" (epeithen) is imperfect — ongoing effort.',
      'The preacher''s task is not merely to state but to persuade. Week by week the Word must press upon both Jew and Greek until conscience yields to Christ.'),
  (5, 'And when Silas and Timotheus were come from Macedonia, Paul was pressed in the spirit, and testified to the Jews that Jesus was Christ.',
      'Ὡς δὲ κατῆλθον ἀπὸ τῆς Μακεδονίας ὅ τε Σιλᾶς καὶ ὁ Τιμόθεος, συνείχετο τῷ λόγῳ ὁ Παῦλος, διαμαρτυρόμενος τοῖς Ἰουδαίοις εἶναι τὸν χριστὸν Ἰησοῦν.',
      'Hōs de katēlthon apo tēs Makedonias ho te Silas kai ho Timotheos, syneicheto tō logō ho Paulos, diamartyromenos tois Ioudaiois einai ton christon Iēsoun.',
      'Syneicheto, "was constrained/gripped," by the word. The Macedonian gift (2 Cor 11:9; Phil 4:15) allowed Paul to lay aside tentmaking and preach full-time.',
      'Gospel labour deserves gospel support. Gifts from faithful churches release apostles from secular toil and multiply their gospel output.'),
  (6, 'And when they opposed themselves, and blasphemed, he shook his raiment, and said unto them, Your blood be upon your own heads; I am clean: from henceforth I will go unto the Gentiles.',
      'ἀντιτασσομένων δὲ αὐτῶν καὶ βλασφημούντων ἐκτιναξάμενος τὰ ἱμάτια εἶπεν πρὸς αὐτούς· Τὸ αἷμα ὑμῶν ἐπὶ τὴν κεφαλὴν ὑμῶν· καθαρὸς ἐγώ· ἀπὸ τοῦ νῦν εἰς τὰ ἔθνη πορεύσομαι.',
      'antitassomenōn de autōn kai blasphēmountōn ektinaxamenos ta himatia eipen pros autous; To haima hymōn epi tēn kephalēn hymōn; katharos egō; apo tou nyn eis ta ethnē poreusomai.',
      'Shaking garments — the prophetic sign of disassociation and judgment (cf. Neh 5:13). "Your blood be upon your own heads" — watchman-language from Ezek 33:4. Paul had discharged his responsibility.',
      'The preacher is a watchman. When he has faithfully warned and is rejected, responsibility falls on the hearer. The blood of souls is on apostate lips that refuse the gospel.'),
  (7, 'And he departed thence, and entered into a certain man''s house, named Justus, one that worshipped God, whose house joined hard to the synagogue.',
      'καὶ μεταβὰς ἐκεῖθεν ἦλθεν εἰς οἰκίαν τινὸς ὀνόματι Τιτίου Ἰούστου σεβομένου τὸν θεόν, οὗ ἡ οἰκία ἦν συνομοροῦσα τῇ συναγωγῇ.',
      'kai metabas ekeithen ēlthen eis oikian tinos onomati Titiou Ioustou sebomenou ton theon, hou hē oikia ēn synomorousa tē synagōgē.',
      'Poetic judgment: the new Christian meeting-place is right next door to the synagogue. Titius Justus (Roman name, God-fearer) opens his home.',
      'When one door closes, the Lord opens another directly adjacent. Household hospitality is often the first infrastructure of a new church plant.'),
  (8, 'And Crispus, the chief ruler of the synagogue, believed on the Lord with all his house; and many of the Corinthians hearing believed, and were baptized.',
      'Κρίσπος δὲ ὁ ἀρχισυνάγωγος ἐπίστευσεν τῷ κυρίῳ σὺν ὅλῳ τῷ οἴκῳ αὐτοῦ, καὶ πολλοὶ τῶν Κορινθίων ἀκούοντες ἐπίστευον καὶ ἐβαπτίζοντο.',
      'Krispos de ho archisynagōgos episteusen tō kyriō syn holō tō oikō autou, kai polloi tōn Korinthiōn akouontes episteuon kai ebaptizonto.',
      'Crispus — the synagogue ruler! — converts with his whole household. Paul baptized him personally (1 Cor 1:14). Many Corinthians follow.',
      'Grace reaches the very top of synagogue hierarchy. When a ruler''s heart bows, household salvation often follows, and the influence ripples through the whole city.'),
  (9, 'Then spake the Lord to Paul in the night by a vision, Be not afraid, but speak, and hold not thy peace:',
      'Εἶπεν δὲ ὁ κύριος ἐν νυκτὶ δι᾽ ὁράματος τῷ Παύλῳ· Μὴ φοβοῦ, ἀλλὰ λάλει καὶ μὴ σιωπήσῃς,',
      'Eipen de ho kyrios en nykti di horamatos tō Paulō; Mē phobou, alla lalei kai mē siōpēsēs,',
      'Fear is a real temptation even to apostles. The Lord''s "fear not" comes in a night-vision — the same format as the Macedonian call (16:9).',
      'The Lord does not shame His servants'' fears; He meets them with His presence and a renewed command. Courage is not the absence of fear but the obedience that outlasts it.'),
  (10, 'For I am with thee, and no man shall set on thee to hurt thee: for I have much people in this city.',
      'διότι ἐγώ εἰμι μετὰ σοῦ καὶ οὐδεὶς ἐπιθήσεταί σοι τοῦ κακῶσαί σε, διότι λαός ἐστίν μοι πολὺς ἐν τῇ πόλει ταύτῃ.',
      'dioti egō eimi meta sou kai oudeis epithēsetai soi tou kakōsai se, dioti laos estin moi polys en tē polei tautē.',
      'Three promises: (1) "I am with thee" — divine presence; (2) personal protection; (3) "I have much people" — the elect, already named as His before they believe. Laos is OT covenant-people language (Exod 6:7), now applied to elect Corinthians.',
      'Election guarantees mission. Before a soul comes to Christ, Christ already calls them His. The preacher is not trying to make God''s people; he is gathering those already chosen.'),
  (11, 'And he continued there a year and six months, teaching the word of God among them.',
      'Ἐκάθισεν δὲ ἐνιαυτὸν καὶ μῆνας ἓξ διδάσκων ἐν αὐτοῖς τὸν λόγον τοῦ θεοῦ.',
      'Ekathisen de eniauton kai mēnas hex didaskōn en autois ton logon tou theou.',
      'Eighteen months — Paul''s longest settled ministry apart from Ephesus (three years) and Rome. Out of this labour came the Corinthian church, a future pastoral epistle, and the start of Romans.',
      'Long patient teaching yields lasting churches. Roots must go deep before fruit can hang heavy.'),
  (12, 'And when Gallio was the deputy of Achaia, the Jews made insurrection with one accord against Paul, and brought him to the judgment seat,',
      'Γαλλίωνος δὲ ἀνθυπάτου ὄντος τῆς Ἀχαΐας κατεπέστησαν ὁμοθυμαδὸν οἱ Ἰουδαῖοι τῷ Παύλῳ καὶ ἤγαγον αὐτὸν ἐπὶ τὸ βῆμα,',
      'Galliōnos de anthypatou ontos tēs Achaias katepestēsan homothymadon hoi Ioudaioi tō Paulō kai ēgagon auton epi to bēma,',
      'Gallio (L. Junius Annaeus Gallio, brother of Seneca) served as proconsul of Achaia July 51–52 AD — the Delphi inscription (Claudius letter) fixes this date, anchoring Pauline chronology. The bēma (judgment seat) still stands visible at Corinth today.',
      'Providence positions just the right magistrate for the right moment. Gallio''s even-handed ruling effectively made Christianity a legal religion throughout Achaia.'),
  (13, 'Saying, This fellow persuadeth men to worship God contrary to the law.',
      'λέγοντες ὅτι Παρὰ τὸν νόμον ἀναπείθει οὗτος τοὺς ἀνθρώπους σέβεσθαι τὸν θεόν.',
      'legontes hoti Para ton nomon anapeithei houtos tous anthrōpous sebesthai ton theon.',
      '"Law" is deliberately ambiguous — Roman law (where Judaism was protected) or Mosaic law? The accusers hope Gallio will treat Christianity as an unlicensed new religion.',
      'Ambiguous legal charges against Christians are ancient. The gospel must be defended before magistrates with wisdom as well as courage.'),
  (14, 'And when Paul was now about to open his mouth, Gallio said unto the Jews, If it were a matter of wrong or wicked lewdness, O ye Jews, reason would that I should bear with you:',
      'μέλλοντος δὲ τοῦ Παύλου ἀνοίγειν τὸ στόμα εἶπεν ὁ Γαλλίων πρὸς τοὺς Ἰουδαίους· Εἰ μὲν ἦν ἀδίκημά τι ἢ ῥᾳδιούργημα πονηρόν, ὦ Ἰουδαῖοι, κατὰ λόγον ἂν ἀνεσχόμην ὑμῶν·',
      'mellontos de tou Paulou anoigein to stoma eipen ho Galliōn pros tous Ioudaious; Ei men ēn adikēma ti ē rhadiourgēma ponēron, ō Ioudaioi, kata logon an aneschomēn hymōn;',
      'Gallio intervenes before Paul can speak, perceiving the charge as religious, not criminal. "Wrong" (adikēma) vs. "mere words" — the Roman distinction between actionable crime and religious squabble.',
      'When the world accidentally defends the gospel, the Christian may quietly benefit. God turns even pagan indifference into protective shield for His church.'),
  (15, 'But if it be a question of words and names, and of your law, look ye to it; for I will be no judge of such matters.',
      'εἰ δὲ ζητήματά ἐστιν περὶ λόγου καὶ ὀνομάτων καὶ νόμου τοῦ καθ᾽ ὑμᾶς, ὄψεσθε αὐτοί· κριτὴς ἐγὼ τούτων οὐ βούλομαι εἶναι.',
      'ei de zētēmata estin peri logou kai onomatōn kai nomou tou kath hymas, opsesthe autoi; kritēs egō toutōn ou boulomai einai.',
      'Gallio dismisses the matter as internal Jewish dispute. "Look ye to it" — handle it yourselves. A magistrate who refuses to arbitrate theology frees the apostolate to teach.',
      'Separation of the civil and the religious courts, when well-kept, is a friend to the gospel. Where Caesar declines to judge Christ, Christ''s subjects enjoy liberty to preach.'),
  (16, 'And he drave them from the judgment seat.',
      'καὶ ἀπήλασεν αὐτοὺς ἀπὸ τοῦ βήματος.',
      'kai apēlasen autous apo tou bēmatos.',
      'Apēlasen — "drove off." A definitive dismissal. The precedent holds for subsequent governors in Achaia.',
      'The Lord''s word "no man shall set on thee to hurt thee" (v.10) is kept by an indifferent Roman judge.'),
  (17, 'Then all the Greeks took Sosthenes, the chief ruler of the synagogue, and beat him before the judgment seat. And Gallio cared for none of those things.',
      'ἐπιλαβόμενοι δὲ πάντες Σωσθένην τὸν ἀρχισυνάγωγον ἔτυπτον ἔμπροσθεν τοῦ βήματος· καὶ οὐδὲν τούτων τῷ Γαλλίωνι ἔμελεν.',
      'epilabomenoi de pantes Sōsthenēn ton archisynagōgon etypton emprosthen tou bēmatos; kai ouden toutōn tō Galliōni emelen.',
      'A Greek mob beats Sosthenes — Crispus''s successor as synagogue ruler — and Gallio ignores the anti-Semitic violence. Likely this is the same Sosthenes later found beside Paul as "our brother" (1 Cor 1:1) — evidence that trials purify, and that the gospel reaches even persecutors.',
      'Even persecutors become brethren. The one who beats the synagogue ruler today may find him kneeling at Christ''s feet tomorrow.'),
  (18, 'And Paul after this tarried there yet a good while, and then took his leave of the brethren, and sailed thence into Syria, and with him Priscilla and Aquila; having shorn his head in Cenchrea: for he had a vow.',
      'Ὁ δὲ Παῦλος ἔτι προσμείνας ἡμέρας ἱκανὰς τοῖς ἀδελφοῖς ἀποταξάμενος ἐξέπλει εἰς τὴν Συρίαν, καὶ σὺν αὐτῷ Πρίσκιλλα καὶ Ἀκύλας, κειράμενος ἐν Κεγχρεαῖς τὴν κεφαλήν, εἶχεν γὰρ εὐχήν.',
      'Ho de Paulos eti prosmeinas hēmeras hikanas tois adelphois apotaxamenos exeplei eis tēn Syrian, kai syn autō Priskilla kai Akylas, keiramenos en Kenchreais tēn kephalēn, eichen gar euchēn.',
      'Cenchrea is Corinth''s east port. The vow (possibly a Nazirite-type, Num 6) was likely taken in thanksgiving for the Lord''s preservation at Corinth. Head-shaving marked the vow''s completion.',
      'The apostle who taught liberty from the Law used Jewish pious customs voluntarily when they served gratitude. Freedom includes the freedom to fulfil vows.'),
  (19, 'And he came to Ephesus, and left them there: but he himself entered into the synagogue, and reasoned with the Jews.',
      'κατήντησαν δὲ εἰς Ἔφεσον, κἀκείνους κατέλιπεν αὐτοῦ, αὐτὸς δὲ εἰσελθὼν εἰς τὴν συναγωγὴν διελέξατο τοῖς Ἰουδαίοις.',
      'katēntēsan de eis Epheson, kakeinous katelipen autou, autos de eiselthōn eis tēn synagōgēn dielexato tois Ioudaiois.',
      'Ephesus — future field of Paul''s third journey. He leaves Priscilla and Aquila there to prepare the way, himself stopping only briefly.',
      'Strategic advance work by lay-workers prepares the ground for later apostolic labour. Not every founder plants the whole field personally.'),
  (20, 'When they desired him to tarry longer time with them, he consented not;',
      'ἐρωτώντων δὲ αὐτῶν ἐπὶ πλείονα χρόνον μεῖναι οὐκ ἐπένευσεν,',
      'erōtōntōn de autōn epi pleiona chronon meinai ouk epeneusen,',
      'Paul refuses the Ephesian invitation now but will return for three years (19:10). Strategic patience — the harvest is Ephesian but the time is not yet.',
      'The servant of God is timed to the Master''s calendar. Saying "no" now is sometimes how one says "yes" later.'),
  (21, 'But bade them farewell, saying, I must by all means keep this feast that cometh in Jerusalem: but I will return again unto you, if God will. And he sailed from Ephesus.',
      'ἀλλὰ ἀποταξάμενος καὶ εἰπών· Πάλιν ἀνακάμψω πρὸς ὑμᾶς τοῦ θεοῦ θέλοντος ἀνήχθη ἀπὸ τῆς Ἐφέσου·',
      'alla apotaxamenos kai eipōn; Palin anakampsō pros hymas tou theou thelontos anēchthē apo tēs Ephesou;',
      '"If God will" (tou theou thelontos) — the Pauline surrender to divine planning (cf. Jas 4:15). Subsequent plans are always contingent on God''s decree.',
      'Every servant of God must hold his plans loosely. "If the Lord will" is not pious politeness but honest creaturely dependence.'),
  (22, 'And when he had landed at Caesarea, and gone up, and saluted the church, he went down to Antioch.',
      'καὶ κατελθὼν εἰς Καισάρειαν, ἀναβὰς καὶ ἀσπασάμενος τὴν ἐκκλησίαν, κατέβη εἰς Ἀντιόχειαν.',
      'kai katelthōn eis Kaisareian, anabas kai aspasamenos tēn ekklēsian, katebē eis Antiocheian.',
      '"Went up" implies Jerusalem — the mother church is greeted before Paul descends to Antioch. The second journey ends where it began (15:40).',
      'Missionary journeys begin and end in accountability to the sending church. Apostolic autonomy is not independence; it is ordered connection.'),
  (23, 'And after he had spent some time there, he departed, and went over all the country of Galatia and Phrygia in order, strengthening all the disciples.',
      'Καὶ ποιήσας χρόνον τινὰ ἐξῆλθεν, διερχόμενος καθεξῆς τὴν Γαλατικὴν χώραν καὶ Φρυγίαν, ἐπιστηρίζων πάντας τοὺς μαθητάς.',
      'Kai poiēsas chronon tina exēlthen, dierchomenos kathexēs tēn Galatikēn chōran kai Phrygian, epistērizōn pantas tous mathētas.',
      'The third journey begins. "Strengthening" (epistērizōn) — pastoral follow-up through the same regions evangelised earlier.',
      'The apostle never forgets a flock he has planted. Gospel mission is not merely opening doors but strengthening those who have entered.'),
  (24, 'And a certain Jew named Apollos, born at Alexandria, an eloquent man, and mighty in the scriptures, came to Ephesus.',
      'Ἰουδαῖος δέ τις Ἀπολλὼς ὀνόματι, Ἀλεξανδρεὺς τῷ γένει, ἀνὴρ λόγιος, κατήντησεν εἰς Ἔφεσον, δυνατὸς ὢν ἐν ταῖς γραφαῖς.',
      'Ioudaios de tis Apollōs onomati, Alexandreus tō genei, anēr logios, katēntēsen eis Epheson, dynatos ōn en tais graphais.',
      'Alexandria was home to a massive Jewish community and the LXX. "Eloquent" (logios) + "mighty in the Scriptures" — a rare combination of rhetorical skill and biblical mastery. Apollos later labours in Corinth (1 Cor 1:12; 3:6).',
      'God equips His church with varied gifts. Eloquence joined to Scripture is a formidable instrument; neither alone will do.'),
  (25, 'This man was instructed in the way of the Lord; and being fervent in the spirit, he spake and taught diligently the things of the Lord, knowing only the baptism of John.',
      'οὗτος ἦν κατηχημένος τὴν ὁδὸν τοῦ κυρίου, καὶ ζέων τῷ πνεύματι ἐλάλει καὶ ἐδίδασκεν ἀκριβῶς τὰ περὶ τοῦ Ἰησοῦ, ἐπιστάμενος μόνον τὸ βάπτισμα Ἰωάννου.',
      'houtos ēn katēchēmenos tēn hodon tou kyriou, kai zeōn tō pneumati elalei kai edidasken akribōs ta peri tou Iēsou, epistamenos monon to baptisma Iōannou.',
      'Katēchēmenos, "catechised" (root of "catechism"). Zeōn, "boiling hot," of spiritual fervour (cf. Rom 12:11). His message was true as far as it went — centred on Jesus — but he knew only John''s baptism (repentance), lacking the full revelation of the Spirit''s coming at Pentecost.',
      'Partial truth, fervently taught, may accomplish much; fuller truth, humbly received, accomplishes more. Spiritual zeal with theological gaps must be corrected, not quenched.'),
  (26, 'And he began to speak boldly in the synagogue: whom when Aquila and Priscilla had heard, they took him unto them, and expounded unto him the way of God more perfectly.',
      'οὗτός τε ἤρξατο παρρησιάζεσθαι ἐν τῇ συναγωγῇ· ἀκούσαντες δὲ αὐτοῦ Πρίσκιλλα καὶ Ἀκύλας προσελάβοντο αὐτὸν καὶ ἀκριβέστερον αὐτῷ ἐξέθεντο τὴν ὁδὸν τοῦ θεοῦ.',
      'houtos te ērxato parrēsiazesthai en tē synagōgē; akousantes de autou Priskilla kai Akylas proselabonto auton kai akribesteron autō exethento tēn hodon tou theou.',
      'Priscilla and Aquila, tentmakers and laypeople, instruct a man "mighty in the Scriptures." Private, gracious correction — not public rebuke. "More perfectly" (akribesteron) — more accurately.',
      'Gifted teachers need humble mentors. A great preacher can sit under a laywoman''s instruction without shame when gospel fidelity is at stake.'),
  (27, 'And when he was disposed to pass into Achaia, the brethren wrote, exhorting the disciples to receive him: who, when he was come, helped them much which had believed through grace:',
      'βουλομένου δὲ αὐτοῦ διελθεῖν εἰς τὴν Ἀχαΐαν προτρεψάμενοι οἱ ἀδελφοὶ ἔγραψαν τοῖς μαθηταῖς ἀποδέξασθαι αὐτόν· ὃς παραγενόμενος συνεβάλετο πολὺ τοῖς πεπιστευκόσιν διὰ τῆς χάριτος·',
      'boulomenou de autou dielthein eis tēn Achaian protrepsamenoi hoi adelphoi egrapsan tois mathētais apodexasthai auton; hos paragenomenos synebaleto poly tois pepisteukosin dia tēs charitos;',
      'Letter of commendation (cf. Rom 16:1; 2 Cor 3:1) — the NT pattern for inter-church ministry recognition. "Through grace" (dia tēs charitos) — the Corinthians'' faith and Apollos''s help are both gifts of grace.',
      'Commended ministers build up what God has already established by grace. The church''s health depends on recognizable, accountable movement of gifted teachers between congregations.'),
  (28, 'For he mightily convinced the Jews, and that publickly, shewing by the scriptures that Jesus was Christ.',
      'εὐτόνως γὰρ τοῖς Ἰουδαίοις διακατηλέγχετο δημοσίᾳ ἐπιδεικνὺς διὰ τῶν γραφῶν εἶναι τὸν χριστὸν Ἰησοῦν.',
      'eutonōs gar tois Ioudaiois diakatēlencheto dēmosia epideiknys dia tōn graphōn einai ton christon Iēsoun.',
      'Eutonōs, "with tension/intensity." Diakatēlencheto is a doubly-intensified verb — "thoroughly refuted." Apollos''s scriptural demonstration that Jesus is the Christ leaves no Jewish argument standing.',
      'Rightly handled Scripture is unanswerable to the candid conscience. The Christ of the prophets defends Himself when His servants simply open the Book.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Acts' AND c.chapter_number = 18
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Κόρινθον', 'Korinthon', 'G2882', 'Corinth — wealthy Achaian seaport, infamous for immorality and commerce.', 1),
  (2, 'Ἀκύλαν', 'Akylan', 'G207', 'Aquila — Pontian Jew, tentmaker, co-labourer with Paul in three cities.', 2),
  (2, 'Πρίσκιλλαν', 'Priskillan', 'G4252', 'Priscilla — wife of Aquila, often named first, denoting prominence in ministry.', 3),
  (3, 'σκηνοποιοὶ', 'skēnopoioi', 'G4635', 'Tentmakers — probably leather or cilicium workers; Paul''s bivocational trade.', 4),
  (4, 'ἔπειθέν', 'epeithen', 'G3982', 'Was persuading — ongoing rational argument until conviction.', 5),
  (5, 'συνείχετο', 'syneicheto', 'G4912', 'Was gripped/constrained — by the urgency of the preached word.', 6),
  (5, 'διαμαρτυρόμενος', 'diamartyromenos', 'G1263', 'Testifying solemnly — full weight of a divine witness.', 7),
  (6, 'ἐκτιναξάμενος', 'ektinaxamenos', 'G1621', 'Having shaken out — prophetic sign of disassociation from guilt (Neh 5:13).', 8),
  (6, 'καθαρὸς', 'katharos', 'G2513', 'Clean — watchman free of bloodguilt (Ezek 33:4-6).', 9),
  (8, 'ἀρχισυνάγωγος', 'archisynagōgos', 'G752', 'Ruler of the synagogue — chief administrative officer; Crispus (1 Cor 1:14).', 10),
  (9, 'Μὴ φοβοῦ', 'Mē phobou', 'G5399', 'Do not fear — Christ''s reassurance in the face of opposition.', 11),
  (10, 'λαός', 'laos', 'G2992', 'People — OT covenant term (Exod 6:7); elect converts not yet gathered.', 12),
  (11, 'ἐκάθισεν', 'ekathisen', 'G2523', 'Settled, sat down — long-term ministry rather than transit.', 13),
  (12, 'ἀνθυπάτου', 'anthypatou', 'G446', 'Proconsul — senatorial governor of Achaia; Gallio in AD 51-52.', 14),
  (12, 'βῆμα', 'bēma', 'G968', 'Judgment seat — elevated platform from which the proconsul ruled.', 15),
  (14, 'ἀδίκημά', 'adikēma', 'G92', 'Wrong, crime — actionable offense versus mere religious dispute.', 16),
  (15, 'ζητήματά', 'zētēmata', 'G2213', 'Questions, disputes — matters of internal religious debate.', 17),
  (16, 'ἀπήλασεν', 'apēlasen', 'G556', 'Drove away — decisive dismissal from court.', 18),
  (17, 'Σωσθένην', 'Sōsthenēn', 'G4988', 'Sosthenes — synagogue ruler, likely later converted (1 Cor 1:1).', 19),
  (18, 'Κεγχρεαῖς', 'Kenchreais', 'G2747', 'Cenchrea — eastern port of Corinth; site of local church (Rom 16:1).', 20),
  (18, 'εὐχήν', 'euchēn', 'G2171', 'Vow — likely Nazirite-style in thanksgiving (Num 6).', 21),
  (21, 'τοῦ θεοῦ θέλοντος', 'tou theou thelontos', 'G2316/G2309', 'God willing — Pauline surrender to divine sovereignty in planning.', 22),
  (23, 'ἐπιστηρίζων', 'epistērizōn', 'G1991', 'Strengthening — recurrent Lukan verb for pastoral follow-up.', 23),
  (24, 'Ἀλεξανδρεὺς', 'Alexandreus', 'G221', 'Alexandrian — from Alexandria, center of Hellenistic Jewish learning.', 24),
  (24, 'λόγιος', 'logios', 'G3052', 'Eloquent, learned — skilled in speech and argument.', 25),
  (24, 'δυνατὸς ἐν ταῖς γραφαῖς', 'dynatos en tais graphais', 'G1415/G1124', 'Mighty in the Scriptures — rare combination of rhetoric and exegesis.', 26),
  (25, 'κατηχημένος', 'katēchēmenos', 'G2727', 'Catechised, orally instructed — systematic discipleship rooted in the Way.', 27),
  (25, 'ζέων τῷ πνεύματι', 'zeōn tō pneumati', 'G2204/G4151', 'Boiling/fervent in spirit — the zealous heart for Christ.', 28),
  (25, 'ἀκριβῶς', 'akribōs', 'G199', 'Accurately, diligently — careful teaching of Jesus as far as he knew.', 29),
  (26, 'παρρησιάζεσθαι', 'parrēsiazesthai', 'G3955', 'To speak boldly — with Spirit-given freedom of speech.', 30),
  (26, 'προσελάβοντο', 'proselabonto', 'G4355', 'They took to themselves — welcomed into private instruction.', 31),
  (26, 'ἀκριβέστερον', 'akribesteron', 'G199', 'More accurately — fuller clarity added to an already-true foundation.', 32),
  (27, 'ἀποδέξασθαι', 'apodexasthai', 'G588', 'To welcome, receive fully — inter-church hospitality by letter.', 33),
  (27, 'διὰ τῆς χάριτος', 'dia tēs charitos', 'G5485', 'Through grace — divine enabling of both converts and teachers.', 34),
  (28, 'εὐτόνως', 'eutonōs', 'G2159', 'Vigorously, with intensity — Apollos''s powerful public argument.', 35),
  (28, 'διακατηλέγχετο', 'diakatēlencheto', 'G1246', 'Thoroughly refuted — doubly-intensified demonstration.', 36)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Acts' AND c.chapter_number = 18 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, '1 Cor 2:1-5', 1),
  (1, '1 Cor 1:2', 2),
  (2, 'Rom 16:3', 3),
  (2, '2 Tim 4:19', 4),
  (2, '1 Cor 16:19', 5),
  (3, '1 Cor 4:12', 6),
  (3, '1 Cor 9:6-15', 7),
  (3, '1 Thess 2:9', 8),
  (3, '2 Thess 3:7-9', 9),
  (4, 'Acts 17:2', 10),
  (5, '2 Cor 11:9', 11),
  (5, 'Phil 4:15', 12),
  (5, 'Acts 17:3', 13),
  (6, 'Neh 5:13', 14),
  (6, 'Ezek 33:4-6', 15),
  (6, 'Matt 10:14', 16),
  (6, 'Acts 13:46', 17),
  (6, 'Acts 28:28', 18),
  (7, 'Col 4:15', 19),
  (8, '1 Cor 1:14', 20),
  (8, 'Acts 16:31-34', 21),
  (9, 'Isa 41:10', 22),
  (9, 'Josh 1:9', 23),
  (9, 'Jer 1:7-8', 24),
  (9, 'Matt 28:20', 25),
  (10, 'Exod 3:12', 26),
  (10, 'Jer 1:19', 27),
  (10, 'Rom 8:31', 28),
  (10, 'John 10:16', 29),
  (10, 'John 10:27-29', 30),
  (10, 'Eph 1:4', 31),
  (10, '2 Tim 2:10', 32),
  (11, '1 Cor 3:6', 33),
  (12, '2 Cor 5:10', 34),
  (12, 'Matt 27:19', 35),
  (13, 'Acts 17:7', 36),
  (14, 'Acts 23:29', 37),
  (14, 'Acts 25:18-19', 38),
  (15, 'John 18:31', 39),
  (15, 'Acts 25:19', 40),
  (17, '1 Cor 1:1', 41),
  (18, 'Num 6:2-21', 42),
  (18, 'Acts 21:23-24', 43),
  (18, 'Rom 16:1', 44),
  (19, 'Acts 19:1', 45),
  (20, 'Acts 19:10', 46),
  (21, 'Jas 4:15', 47),
  (21, 'Rom 1:10', 48),
  (21, '1 Cor 4:19', 49),
  (22, 'Acts 11:22', 50),
  (22, 'Acts 14:26', 51),
  (23, 'Gal 1:2', 52),
  (23, '1 Cor 16:1', 53),
  (23, 'Acts 14:22', 54),
  (24, '1 Cor 1:12', 55),
  (24, '1 Cor 3:4-6', 56),
  (24, 'Titus 3:13', 57),
  (25, 'Matt 3:11', 58),
  (25, 'Acts 19:3', 59),
  (25, 'Rom 12:11', 60),
  (26, 'Rom 16:3-4', 61),
  (26, '2 Tim 1:5', 62),
  (26, '2 Tim 2:15', 63),
  (27, 'Rom 16:1-2', 64),
  (27, '2 Cor 3:1', 65),
  (27, '1 Cor 3:6', 66),
  (27, 'Eph 2:8', 67),
  (27, 'Phil 1:29', 68),
  (28, 'Luke 24:27', 69),
  (28, 'Acts 17:3', 70),
  (28, 'John 5:39', 71)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Acts' AND c.chapter_number = 18 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
