-- ═══════════════════════════════════════════════════
-- HEBREWS CHAPTER 11 — The Faith Hall of Fame
-- 40 verses · Greek text · Word studies · Cross-refs
-- ═══════════════════════════════════════════════════

-- Step 1: Insert chapter metadata
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 11,
  'Hebrews 11 is the great ''faith chapter'' — the most celebrated catalogue of faithful witnesses in all of Scripture. It opens with the classic definition: ''Now faith is the substance of things hoped for, the evidence of things not seen'' (v.1). ''By faith'' (pistei) is the refrain that structures the entire chapter — appearing 18 times as the key to each person''s story. The chapter moves chronologically through salvation history: Abel offered a better sacrifice (v.4); Enoch was translated without death (v.5); Noah built an ark (v.7); Abraham obeyed God''s call to leave his homeland (vv.8-10); Sarah conceived beyond natural possibility (v.11); Abraham offered Isaac (vv.17-19); Isaac, Jacob, and Joseph each spoke of the future by faith (vv.20-22); Moses'' parents defied Pharaoh (v.23); Moses himself chose ''the reproach of Christ'' over Egypt''s treasures (vv.24-26); Israel crossed the Red Sea and the walls of Jericho fell (vv.29-30); Rahab the harlot was saved by faith (v.31). The chapter then accelerates into a rapid-fire summary of judges, kings, and prophets who ''through faith subdued kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions'' (v.33). Others ''were tortured, not accepting deliverance'' (v.35), ''had trial of cruel mockings and scourgings … were stoned … were sawn asunder'' (vv.36-37). The chapter concludes with a stunning paradox: ''these all, having obtained a good report through faith, received not the promise: God having provided some better thing for us, that they without us should not be made perfect'' (vv.39-40).',
  'The Heroes of Faith: Substance, Evidence, and Endurance',
  'πίστις (pistis)',
  'Faith, trust, faithfulness, firm persuasion — from peithō (to persuade, to be convinced). The word appears 24 times in this chapter alone. In Hebrews 11, pistis is not mere belief or intellectual assent but active trust that transforms behavior — each person named in this chapter acted on what they believed about God''s unseen promises. Faith is simultaneously backward-looking (trusting God''s character) and forward-looking (trusting God''s promises). It is ''the substance of things hoped for'' — it gives present reality to future promises.',
  '["The Definition and Power of Faith (vv.1-3): Now faith is the substance of things hoped for the evidence of things not seen; for by it the elders obtained a good report; through faith we understand that the worlds were framed by the word of God so that things which are seen were not made of things which do appear","Faith from Abel to Noah (vv.4-7): By faith Abel offered unto God a more excellent sacrifice than Cain; by faith Enoch was translated that he should not see death; but without faith it is impossible to please him for he that cometh to God must believe that he is and that he is a rewarder of them that diligently seek him; by faith Noah being warned of God of things not seen as yet moved with fear prepared an ark to the saving of his house","Faith of Abraham and Sarah (vv.8-19): By faith Abraham when he was called to go out into a place which he should after receive for an inheritance obeyed and he went out not knowing whither he went; by faith he sojourned in the land of promise as in a strange country; for he looked for a city which hath foundations whose builder and maker is God; through faith also Sara herself received strength to conceive seed and was delivered of a child when she was past age; these all died in faith not having received the promises but having seen them afar off; by faith Abraham when he was tried offered up Isaac","Faith of Isaac Jacob Joseph and Moses (vv.20-28): By faith Isaac blessed Jacob and Esau concerning things to come; by faith Jacob when he was a dying blessed both the sons of Joseph; by faith Joseph when he died made mention of the departing of the children of Israel and gave commandment concerning his bones; by faith Moses when he was born was hid three months of his parents; by faith Moses when he was come to years refused to be called the son of Pharaohs daughter choosing rather to suffer affliction with the people of God than to enjoy the pleasures of sin for a season; esteeming the reproach of Christ greater riches than the treasures in Egypt for he had respect unto the recompence of the reward; by faith he forsook Egypt not fearing the wrath of the king for he endured as seeing him who is invisible; through faith he kept the passover and the sprinkling of blood lest he that destroyed the firstborn should touch them","Faith''s Triumphs and Sufferings (vv.29-40): By faith they passed through the Red sea as by dry land; by faith the walls of Jericho fell down; by faith the harlot Rahab perished not; and what shall I more say for the time would fail me to tell of Gedeon and of Barak and of Samson and of Jephthae of David also and Samuel and of the prophets who through faith subdued kingdoms wrought righteousness obtained promises stopped the mouths of lions; women received their dead raised to life again and others were tortured not accepting deliverance; they wandered in deserts and in mountains and in dens and caves of the earth; and these all having obtained a good report through faith received not the promise God having provided some better thing for us that they without us should not be made perfect"]'
FROM books b WHERE b.name = 'Hebrews';

-- Step 2: Insert all 40 verses (key verses with study/doctrinal notes, others with study notes)
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Now faith is the substance of things hoped for, the evidence of things not seen.',
   'ἔστιν δὲ πίστις ἐλπιζομένων ὑπόστασις πραγμάτων ἔλεγχος οὐ βλεπομένων',
   'estin de pistis elpizomenōn hypostasis pragmatōn elenchos ou blepomenōn',
   '''Faith is the substance'' (pistis elpizomenōn hypostasis — faith is the hypostasis of things hoped for). Hypostasis here means ''foundation,'' ''assurance,'' ''reality'' — faith gives present substance to future hopes, making them as real as if already possessed. ''The evidence of things not seen'' (pragmatōn elenchos ou blepomenōn — the proof/conviction of things not being seen). Elenchos means proof, evidence, that which convinces — faith is the faculty that perceives invisible realities. Faith is not wishful thinking but the conviction that produces action based on the certainty of God''s unseen promises.',
   'This verse defines faith not as a subjective feeling but as an objective reality: the ''substance'' (hypostasis — underlying reality) and ''evidence'' (elenchos — proof) of the unseen world. Faith is the means by which believers access the invisible realm of God''s promises and make them operative in the present. It is both the foundation on which hope rests and the evidence that convicts the believer of unseen truth.'),
  (2, 'For by it the elders obtained a good report.',
   'ἐν ταύτῃ γὰρ ἐμαρτυρήθησαν οἱ πρεσβύτεροι',
   'en tautē gar emartyrēthēsan hoi presbyteroi',
   '''By it'' (en tautē — by this faith). ''The elders'' (hoi presbyteroi — the ancestors, the old ones, the patriarchs). ''Obtained a good report'' (emartyrēthēsan — were testified about, received a witness; they were attested, approved by God through their faith). The rest of the chapter provides the evidence: these are the specific people who were commended by God because of their faith.',
   NULL),
  (3, 'Through faith we understand that the worlds were framed by the word of God, so that things which are seen were not made of things which do appear.',
   'πίστει νοοῦμεν κατηρτίσθαι τοὺς αἰῶνας ῥήματι θεοῦ εἰς τὸ μὴ ἐκ φαινομένων τὰ βλεπόμενα γεγονέναι',
   'pistei nooumen katērtisthai tous aiōnas rhēmati theou eis to mē ek phainomenōn ta blepomena gegonenai',
   '''Through faith we understand'' (pistei nooumen — by faith we comprehend). ''The worlds were framed by the word of God'' (katērtisthai tous aiōnas rhēmati theou — the ages/worlds were prepared/fitted together by God''s spoken word). ''Things which are seen were not made of things which do appear'' — the visible universe was created from the invisible; creation ex nihilo (from nothing) is perceived by faith. This is the first ''by faith'' — and it applies to every believer: we all exercise faith in accepting creation by God''s word.',
   'Creation by divine fiat (God''s word) is the foundational act of faith: believing that the visible world originated from the invisible God. This is not anti-scientific but meta-scientific — faith perceives the ultimate cause behind all physical causes. The doctrine of creation ex nihilo is a faith-conviction: the seen came from the unseen.'),
  (4, 'By faith Abel offered unto God a more excellent sacrifice than Cain, by which he obtained witness that he was righteous, God testifying of his gifts: and he being dead yet speaketh.',
   'πίστει πλείονα θυσίαν Ἅβελ παρὰ Κάϊν προσήνεγκεν τῷ θεῷ δι᾽ ἧς ἐμαρτυρήθη εἶναι δίκαιος μαρτυροῦντος ἐπὶ τοῖς δώροις αὐτοῦ τοῦ θεοῦ καὶ δι᾽ αὐτῆς ἀποθανὼν ἔτι λαλεῖ',
   'pistei pleiona thysian Habel para Kain prosēnenken tō theō di hēs emartyrēthē einai dikaios martyrountos epi tois dōrois autou tou theou kai di autēs apothanōn eti lalei',
   '''A more excellent sacrifice'' (pleiona thysian — a fuller, richer sacrifice). Abel''s sacrifice was ''more excellent'' not because of what he offered (a lamb vs. grain) but because of the faith with which he offered it. ''Obtained witness that he was righteous'' — God testified to Abel''s righteousness through his offering (Gen 4:4). ''He being dead yet speaketh'' — Abel''s faith speaks beyond the grave; his example continues to testify across the millennia. He is the first martyr and the first example of righteous faith.',
   NULL),
  (5, 'By faith Enoch was translated that he should not see death; and was not found, because God had translated him: for before his translation he had this testimony, that he pleased God.',
   'πίστει Ἑνὼχ μετετέθη τοῦ μὴ ἰδεῖν θάνατον καὶ οὐχ εὑρίσκετο διότι μετέθηκεν αὐτὸν ὁ θεός πρὸ γὰρ τῆς μεταθέσεως αὐτοῦ μεμαρτύρηται εὐηρεστηκέναι τῷ θεῷ',
   'pistei Henōch metetethē tou mē idein thanaton kai ouch heurisketo dioti metethēken auton ho theos pro gar tēs metatheseōs autou memartyrētai euaresthēkenai tō theō',
   '''Translated'' (metetethē — transferred, removed, transported; from metatithēmi). Enoch was ''translated'' — taken directly to God without dying (Gen 5:24). ''He pleased God'' (euaresthēkenai tō theō — to have pleased, to have been well-pleasing to God). The LXX of Genesis 5:24 says Enoch ''pleased God'' where the Hebrew says he ''walked with God.'' Walking with God is the OT expression; pleasing God is the NT interpretation — and both require faith.',
   NULL),
  (6, 'But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.',
   'χωρὶς δὲ πίστεως ἀδύνατον εὐαρεστῆσαι πιστεῦσαι γὰρ δεῖ τὸν προσερχόμενον τῷ θεῷ ὅτι ἔστιν καὶ τοῖς ἐκζητοῦσιν αὐτὸν μισθαποδότης γίνεται',
   'chōris de pisteōs adynaton euarestēsai pisteusai gar dei ton proserchomenon tō theō hoti estin kai tois ekzētousin auton misthapodotēs ginetai',
   '''Without faith it is impossible'' (chōris pisteōs adynaton — apart from faith, unable). ''To please him'' (euarestēsai — to be well-pleasing). Two essential beliefs: (1) ''that he is'' (hoti estin — that God exists; the foundation of all faith); (2) ''that he is a rewarder of them that diligently seek him'' (misthapodotēs ginetai — He becomes a reward-giver to those who seek Him earnestly). Faith requires both convictions: God''s existence and God''s goodness — that He is there and that He cares.',
   'This verse establishes the absolute necessity of faith for any relationship with God. Without faith, no human act — however moral, sacrificial, or impressive — can please God. The two minimum requirements of faith are: (1) belief in God''s existence, and (2) belief in God''s character as one who rewards those who seek Him. These are not abstract doctrines but the motivating convictions behind all faithful action.'),
  (7, 'By faith Noah, being warned of God of things not seen as yet, moved with fear, prepared an ark to the saving of his house; by the which he condemned the world, and became heir of the righteousness which is by faith.',
   'πίστει χρηματισθεὶς Νῶε περὶ τῶν μηδέπω βλεπομένων εὐλαβηθεὶς κατεσκεύασεν κιβωτὸν εἰς σωτηρίαν τοῦ οἴκου αὐτοῦ δι᾽ ἧς κατέκρινεν τὸν κόσμον καὶ τῆς κατὰ πίστιν δικαιοσύνης ἐγένετο κληρονόμος',
   'pistei chrēmatistheis Nōe peri tōn mēdepō blepomenōn eulabētheis kateskeuasen kibōton eis sōtērian tou oikou autou di hēs katekrinen ton kosmon kai tēs kata pistin dikaiosynēs egeneto klēronomos',
   '''Warned of God'' (chrēmatistheis — divinely instructed, received a divine oracle). ''Things not seen as yet'' (tōn mēdepō blepomenōn — things not yet visible; a flood was unprecedented). ''Moved with fear'' (eulabētheis — with reverent caution; the same eulabeia from 5:7). Noah acted on a divine warning about something that had never happened before. He built the ark — a massive, years-long project — based solely on God''s word. ''Condemned the world'' — not by preaching judgment but by his obedient action, which implicitly judged the world''s unbelief. ''Heir of the righteousness which is by faith'' — Noah is the first person called ''righteous'' (tsaddiq) in Scripture (Gen 6:9).',
   NULL),
  (8, 'By faith Abraham, when he was called to go out into a place which he should after receive for an inheritance, obeyed; and he went out, not knowing whither he went.',
   'πίστει καλούμενος Ἀβραὰμ ὑπήκουσεν ἐξελθεῖν εἰς τὸν τόπον ὃν ἤμελλεν λαμβάνειν εἰς κληρονομίαν καὶ ἐξῆλθεν μὴ ἐπιστάμενος ποῦ ἔρχεται',
   'pistei kaloumenos Abraam hypēkousen exelthein eis ton topon hon ēmellen lambanein eis klēronomian kai exēlthen mē epistamenos pou erchetai',
   '''When he was called'' (kaloumenos — being called; present participle: he obeyed in the very act of being called — immediate response). ''Obeyed'' (hypēkousen — he listened under, he submitted; from hypo + akouō). ''Not knowing whither he went'' (mē epistamenos pou erchetai — not knowing where he was going). Abraham left everything familiar — homeland, family, culture — for an unknown destination based solely on God''s word. Faith and obedience are inseparable: Abraham obeyed because he believed, and his obedience demonstrated his belief.',
   NULL),
  (9, 'By faith he sojourned in the land of promise, as in a strange country, dwelling in tabernacles with Isaac and Jacob, the heirs with him of the same promise:',
   'πίστει παρῴκησεν εἰς τὴν γῆν τῆς ἐπαγγελίας ὡς ἀλλοτρίαν ἐν σκηναῖς κατοικήσας μετὰ Ἰσαὰκ καὶ Ἰακὼβ τῶν συγκληρονόμων τῆς ἐπαγγελίας τῆς αὐτῆς',
   'pistei parōkēsen eis tēn gēn tēs epangelias hōs allotrian en skēnais katoikēsas meta Isaak kai Iakōb tōn synklēronomōn tēs epangelias tēs autēs',
   '''Sojourned'' (parōkēsen — dwelt as a stranger, lived as a foreigner; the root of paroikos, a resident alien). ''As in a strange country'' (hōs allotrian — as though it were foreign). ''Dwelling in tabernacles'' (en skēnais — in tents). Abraham was in the promised land but lived as a foreigner — owning nothing, dwelling in tents, not buildings. Three generations (Abraham, Isaac, Jacob) lived this way, ''heirs … of the same promise'' but not yet possessing it. Faith enabled them to live as strangers in the land they were promised to own.',
   NULL),
  (10, 'For he looked for a city which hath foundations, whose builder and maker is God.',
   'ἐξεδέχετο γὰρ τὴν τοὺς θεμελίους ἔχουσαν πόλιν ἧς τεχνίτης καὶ δημιουργὸς ὁ θεός',
   'exedecheto gar tēn tous themelious echousan polin hēs technitēs kai dēmiourgos ho theos',
   '''He looked for'' (exedecheto — he was waiting for, he was expecting). ''A city which hath foundations'' (tēn tous themelious echousan polin — the city that has foundations; in contrast to his tent-dwelling). ''Builder and maker'' (technitēs kai dēmiourgos — architect and constructor). Abraham lived in tents precisely because he was looking beyond earthly real estate to a heavenly city — the true ''promised land'' that no earthly territory could fulfill. This heavenly city reappears in 12:22 and 13:14.',
   'Abraham''s faith transcended the earthly promised land. He was not ultimately looking for a piece of real estate in Canaan but for ''a city with foundations'' built by God — the heavenly Jerusalem. This shows that OT faith was not merely earthly; the patriarchs had a heavenly hope, a vision of the eternal city that God was preparing for them.'),
  (11, 'Through faith also Sara herself received strength to conceive seed, and was delivered of a child when she was past age, because she judged him faithful who had promised.',
   'πίστει καὶ αὐτὴ Σάρρα δύναμιν εἰς καταβολὴν σπέρματος ἔλαβεν καὶ παρὰ καιρὸν ἡλικίας ἔτεκεν ἐπεὶ πιστὸν ἡγήσατο τὸν ἐπαγγειλάμενον',
   'pistei kai autē Sarra dynamin eis katabolēn spermatos elaben kai para kairon hēlikias eteken epei piston hēgēsato ton epangeilamenon',
   '''Sara herself'' — despite her initial laughter (Gen 18:12). ''Past age'' (para kairon hēlikias — beyond the season of life). ''She judged him faithful who had promised'' (piston hēgēsato ton epangeilamenon — she considered the Promiser faithful). The ground of Sarah''s faith was not her own ability but God''s faithfulness. When the promise seemed biologically impossible, she trusted the character of the Promiser. Faith''s object matters more than faith''s strength.',
   NULL),
  (12, 'Therefore sprang there even of one, and him as good as dead, so many as the stars of the sky in multitude, and as the sand which is by the sea shore innumerable.',
   'διὸ καὶ ἀφ᾽ ἑνὸς ἐγεννήθησαν καὶ ταῦτα νενεκρωμένου καθὼς τὰ ἄστρα τοῦ οὐρανοῦ τῷ πλήθει καὶ ὡσεὶ ἄμμος ἡ παρὰ τὸ χεῖλος τῆς θαλάσσης ἡ ἀναρίθμητος',
   'dio kai aph henos egennēthēsan kai tauta nenekrōmenou kathōs ta astra tou ouranou tō plēthei kai hōsei ammos hē para to cheilos tēs thalassēs hē anarithmētos',
   '''Of one, and him as good as dead'' (aph henos kai tauta nenekrōmenou — from one person, and that one having been made dead/impotent; Abraham''s body was past natural ability, Rom 4:19). ''Stars of the sky … sand … innumerable'' — echoing Genesis 15:5 and 22:17. From one dead body came an innumerable multitude. The impossibility of the origin magnifies the miracle of the result — and the power of the faith that believed it possible.',
   NULL),
  (13, 'These all died in faith, not having received the promises, but having seen them afar off, and were persuaded of them, and embraced them, and confessed that they were strangers and pilgrims on the earth.',
   'κατὰ πίστιν ἀπέθανον οὗτοι πάντες μὴ λαβόντες τὰς ἐπαγγελίας ἀλλὰ πόρρωθεν αὐτὰς ἰδόντες καὶ ἀσπασάμενοι καὶ ὁμολογήσαντες ὅτι ξένοι καὶ παρεπίδημοί εἰσιν ἐπὶ τῆς γῆς',
   'kata pistin apethanon houtoi pantes mē labontes tas epangelias alla porrōthen autas idontes kai aspasamenoi kai homologēsantes hoti xenoi kai parepidēmoi eisin epi tēs gēs',
   '''Died in faith'' (kata pistin apethanon — according to faith they died). ''Not having received the promises'' (mē labontes — not having obtained). ''Seen them afar off'' (porrōthen idontes — having seen from a distance). ''Embraced them'' (aspasamenoi — having greeted/welcomed them, as one greets a friend from far away). ''Strangers and pilgrims'' (xenoi kai parepidēmoi — foreigners and temporary residents). The patriarchs died without seeing the fulfillment — yet they died in faith, not in disappointment. They saw the promises ''afar off'' — telescopic faith that perceives distant realities — and welcomed them like long-awaited friends. They declared themselves ''strangers'' on earth because they knew their true home was elsewhere.',
   'This verse captures the essence of pilgrim faith: living as strangers on earth because one''s true citizenship is in heaven. The patriarchs died ''in faith'' — faith was not just how they lived but how they died. They did not receive the promises in their lifetimes but were content to see them from afar, because they trusted the Promiser. This is the paradigm of Christian existence: already citizens of heaven, not yet at home.'),
  (14, 'For they that say such things declare plainly that they seek a country.',
   'οἱ γὰρ τοιαῦτα λέγοντες ἐμφανίζουσιν ὅτι πατρίδα ἐπιζητοῦσιν',
   'hoi gar toiauta legontes emphanizousin hoti patrida epizētousin',
   '''Declare plainly'' (emphanizousin — make visible, make clear). ''Seek a country'' (patrida epizētousin — seek a homeland, a fatherland). By calling themselves strangers, they revealed they were looking for something beyond this earth.',
   NULL),
  (15, 'And truly, if they had been mindful of that country from whence they came out, they might have had opportunity to have returned.',
   'καὶ εἰ μὲν ἐκείνης ἐμνημόνευον ἀφ᾽ ἧς ἐξῆλθον εἶχον ἂν καιρὸν ἀνακάμψαι',
   'kai ei men ekeinēs emnēmoneuon aph hēs exēlthon eichon an kairon anakampsai',
   '''If they had been mindful'' (ei emnēmoneuon — if they had kept remembering). Abraham could have returned to Mesopotamia — the road was always open. But he didn''t. This is faith''s commitment: not looking back to what was left behind but pressing forward to what God promises. The application to Hebrews'' readers is clear: don''t go back to Judaism; don''t retreat to what you left.',
   NULL),
  (16, 'But now they desire a better country, that is, an heavenly: wherefore God is not ashamed to be called their God: for he hath prepared for them a city.',
   'νῦν δὲ κρείττονος ὀρέγονται τοῦτ᾽ ἔστιν ἐπουρανίου διὸ οὐκ ἐπαισχύνεται αὐτοὺς ὁ θεὸς θεὸς ἐπικαλεῖσθαι αὐτῶν ἡτοίμασεν γὰρ αὐτοῖς πόλιν',
   'nyn de kreittonos oregontai tout estin epouraniou dio ouk epaischynetai autous ho theos theos epikaleisthai autōn hētoimasen gar autois polin',
   '''A better country'' (kreittonos — the kreittōn keyword again). ''An heavenly'' (epouraniou). ''God is not ashamed to be called their God'' (ouk epaischynetai theos epikaleisthai autōn — God is not embarrassed to be identified as their God). ''He hath prepared for them a city'' (hētoimasen autois polin — He has made ready a city). The patriarchs'' pilgrim faith honored God so deeply that He proudly identifies Himself with them: ''I am the God of Abraham, Isaac, and Jacob'' (Exod 3:6). The city God has prepared is the New Jerusalem (Rev 21:2) — the ultimate fulfillment of every promise of homeland and rest.',
   NULL),
  (17, 'By faith Abraham, when he was tried, offered up Isaac: and he that had received the promises offered up his only begotten son,',
   'πίστει προσενήνοχεν Ἀβραὰμ τὸν Ἰσαὰκ πειραζόμενος καὶ τὸν μονογενῆ προσέφερεν ὁ τὰς ἐπαγγελίας ἀναδεξάμενος',
   'pistei prosenēnochen Abraam ton Isaak peirazomenos kai ton monogenē prospheren ho tas epangelias anadexamenos',
   '''When he was tried'' (peirazomenos — being tested; Genesis 22 is the supreme test of faith in the OT). ''Offered up Isaac'' (prosenēnochen ton Isaak — has offered, perfect tense: the offering stands as a permanent act of faith). ''His only begotten son'' (ton monogenē — his one-of-a-kind, his uniquely beloved son; the same word used of Christ in John 3:16). ''He that had received the promises'' — the paradox: God had promised Abraham''s descendants through Isaac, yet God commanded Isaac''s sacrifice. How can both be true? Only faith could hold the contradiction together.',
   NULL),
  (18, 'Of whom it was said, That in Isaac shall thy seed be called:',
   'πρὸς ὃν ἐλαλήθη ὅτι ἐν Ἰσαὰκ κληθήσεταί σοι σπέρμα',
   'pros hon elalēthē hoti en Isaak klēthēsetai soi sperma',
   'Quoting Genesis 21:12. The promise was specifically through Isaac — not Ishmael, not any other son. If Isaac dies without offspring, the promise dies. Abraham''s faith was tested at its most fundamental point: the very channel through which God''s promise would flow was being demanded back.',
   NULL),
  (19, 'Accounting that God was able to raise him up, even from the dead; from whence also he received him in a figure.',
   'λογισάμενος ὅτι καὶ ἐκ νεκρῶν ἐγείρειν δυνατὸς ὁ θεός ὅθεν αὐτὸν καὶ ἐν παραβολῇ ἐκομίσατο',
   'logisamenos hoti kai ek nekrōn egeirein dynatos ho theos hothen auton kai en parabolē ekomisato',
   '''Accounting'' (logisamenos — having reckoned, having calculated). ''God was able to raise him up, even from the dead'' (ek nekrōn egeirein dynatos ho theos — God is able to raise from the dead). Abraham reasoned: God promised through Isaac; God commands Isaac''s death; therefore God must raise Isaac from the dead. This is the logic of faith — it trusts God''s power to resolve what appears impossible. ''In a figure'' (en parabolē — in a parable, as a type). Abraham received Isaac back from the dead figuratively — a type of Christ''s actual resurrection. The binding of Isaac (Aqedah) is the OT''s most powerful foreshadowing of the Father offering His only Son.',
   'Abraham''s reasoning about resurrection (logisamenos) shows that faith is not irrational but deeply rational — it reasons from God''s character and promises to conclusions that transcend human experience. Abraham believed in resurrection before any resurrection had occurred, simply because the logic of God''s faithfulness required it.'),
  (20, 'By faith Isaac blessed Jacob and Esau concerning things to come.',
   'πίστει καὶ περὶ μελλόντων εὐλόγησεν Ἰσαὰκ τὸν Ἰακὼβ καὶ τὸν Ἠσαῦ',
   'pistei kai peri mellontōn eulogēsen Isaak ton Iakōb kai ton Ēsau',
   'Isaac''s faith was forward-looking: he blessed ''concerning things to come'' (peri mellontōn). His blessing of Jacob and Esau (Gen 27) was prophetic — he spoke by faith about a future he would not see. Even the mistaken identity (Jacob deceiving Isaac) was overruled by God''s sovereign plan, and Isaac''s faith-blessing stood.',
   NULL),
  (21, 'By faith Jacob, when he was a dying, blessed both the sons of Joseph; and worshipped, leaning upon the top of his staff.',
   'πίστει Ἰακὼβ ἀποθνῄσκων ἕκαστον τῶν υἱῶν Ἰωσὴφ εὐλόγησεν καὶ προσεκύνησεν ἐπὶ τὸ ἄκρον τῆς ῥάβδου αὐτοῦ',
   'pistei Iakōb apothnēskōn hekaston tōn hyiōn Iōsēph eulogēsen kai prosekynēsen epi to akron tēs rhabdou autou',
   'Jacob''s faith was expressed at the point of death: he blessed Ephraim and Manasseh (Gen 48), deliberately placing the younger above the elder (the faith pattern: God''s choice overrides human convention). ''Worshipped, leaning upon the top of his staff'' — an old man''s body failing, but his faith strong enough to worship.',
   NULL),
  (22, 'By faith Joseph, when he died, made mention of the departing of the children of Israel; and gave commandment concerning his bones.',
   'πίστει Ἰωσὴφ τελευτῶν περὶ τῆς ἐξόδου τῶν υἱῶν Ἰσραὴλ ἐμνημόνευσεν καὶ περὶ τῶν ὀστέων αὐτοῦ ἐνετείλατο',
   'pistei Iōsēph teleutōn peri tēs exodou tōn hyiōn Israēl emnēmoneusen kai peri tōn osteōn autou eneteilato',
   '''Made mention of the departing'' (peri tēs exodou emnēmoneusen — he remembered/mentioned the exodus). Joseph, the most powerful man in Egypt, died not trusting in Egypt but in God''s promise to bring Israel out. ''Gave commandment concerning his bones'' (Gen 50:25) — ''Carry my bones out of here.'' His bones were a statement of faith: Egypt is not home; the promised land is. His body was his final testimony.',
   NULL),
  (23, 'By faith Moses, when he was born, was hid three months of his parents, because they saw he was a proper child; and they were not afraid of the king''s commandment.',
   'πίστει Μωϋσῆς γεννηθεὶς ἐκρύβη τρίμηνον ὑπὸ τῶν πατέρων αὐτοῦ διότι εἶδον ἀστεῖον τὸ παιδίον καὶ οὐκ ἐφοβήθησαν τὸ διάταγμα τοῦ βασιλέως',
   'pistei Mōysēs gennētheis ekrybē trimēnon hypo tōn paterōn autou dioti eidon asteion to paidion kai ouk ephobēthēsan to diatagma tou basileōs',
   '''His parents'' (tōn paterōn — Amram and Jochebed, Exod 2:1-2). ''Proper child'' (asteion to paidion — a beautiful/fine child; asteios means elegant, well-formed). ''Not afraid of the king''s commandment'' (ouk ephobēthēsan to diatagma — they did not fear Pharaoh''s decree to kill Hebrew male infants). Their faith in God overcame their fear of the most powerful ruler on earth. Faith enabled civil disobedience when human authority contradicted divine purpose.',
   NULL),
  (24, 'By faith Moses, when he was come to years, refused to be called the son of Pharaoh''s daughter;',
   'πίστει Μωϋσῆς μέγας γενόμενος ἠρνήσατο λέγεσθαι υἱὸς θυγατρὸς Φαραώ',
   'pistei Mōysēs megas genomenos ērnēsato legesthai hyios thygatros Pharaō',
   '''Come to years'' (megas genomenos — having become great/grown up). ''Refused'' (ērnēsato — denied, rejected, renounced). Moses renounced his royal Egyptian identity — the privilege, the power, the wealth, the future. This was not ignorance (he knew what he was giving up) but deliberate, faith-driven choice. Faith enables the sacrifice of present advantage for future promise.',
   NULL),
  (25, 'Choosing rather to suffer affliction with the people of God, than to enjoy the pleasures of sin for a season;',
   'μᾶλλον ἑλόμενος συγκακουχεῖσθαι τῷ λαῷ τοῦ θεοῦ ἢ πρόσκαιρον ἔχειν ἁμαρτίας ἀπόλαυσιν',
   'mallon helomenos synkakoucheisthai tō laō tou theou ē proskairon echein hamartias apolausin',
   '''Choosing rather'' (mallon helomenos — preferring, deliberately selecting). ''To suffer affliction with'' (synkakoucheisthai — to be ill-treated together with). ''The people of God'' — slaves, not royalty. ''Pleasures of sin for a season'' (proskairon hamartias apolausin — temporary enjoyment of sin). The contrast: temporary pleasure vs. eternal reward; royal comfort vs. shared suffering; Egypt''s sin vs. God''s people. Moses chose suffering over pleasure because he calculated on a different time scale — faith sees beyond ''a season'' to eternity.',
   NULL),
  (26, 'Esteeming the reproach of Christ greater riches than the treasures in Egypt: for he had respect unto the recompence of the reward.',
   'μείζονα πλοῦτον ἡγησάμενος τῶν Αἰγύπτου θησαυρῶν τὸν ὀνειδισμὸν τοῦ Χριστοῦ ἀπέβλεπεν γὰρ εἰς τὴν μισθαποδοσίαν',
   'meizona plouton hēgēsamenos tōn Aigyptou thēsaurōn ton oneidismon tou Christou apeblepen gar eis tēn misthapodosian',
   '''The reproach of Christ'' (ton oneidismon tou Christou — the reproach/insult that belongs to Christ). Remarkably, Moses'' suffering is called ''the reproach of Christ'' — he bore the same kind of shame that Christ would later bear. Those who suffer for God''s people share in Christ''s reproach. ''Greater riches than the treasures in Egypt'' — Moses'' value system was inverted by faith: reproach was richer than Egypt''s treasures. ''He had respect unto the recompence'' (apeblepen eis tēn misthapodosian — he was looking away from Egypt, looking toward the reward). Faith redirects the gaze — from the visible and immediate to the invisible and eternal.',
   NULL),
  (27, 'By faith he forsook Egypt, not fearing the wrath of the king: for he endured, as seeing him who is invisible.',
   'πίστει κατέλιπεν Αἴγυπτον μὴ φοβηθεὶς τὸν θυμὸν τοῦ βασιλέως τὸν γὰρ ἀόρατον ὡς ὁρῶν ἐκαρτέρησεν',
   'pistei katelipen Aigypton mē phobētheis ton thymon tou basileōs ton gar aoraton hōs horōn ekarterēsen',
   '''He endured, as seeing him who is invisible'' (ton aoraton hōs horōn ekarterēsen — he persevered as though seeing the Invisible One). This is the quintessence of faith: seeing the Unseen. Moses exchanged the visible power of Pharaoh for the invisible power of God — and found the invisible more real than the visible. ''Endured'' (ekarterēsen — he was strong, he held firm, he persevered). Faith''s endurance comes from perceiving what is invisible to unbelief.',
   NULL),
  (28, 'Through faith he kept the passover, and the sprinkling of blood, lest he that destroyed the firstborn should touch them.',
   'πίστει πεποίηκεν τὸ πάσχα καὶ τὴν πρόσχυσιν τοῦ αἵματος ἵνα μὴ ὁ ὀλοθρεύων τὰ πρωτότοκα θίγῃ αὐτῶν',
   'pistei pepoiēken to pascha kai tēn proschusin tou haimatos hina mē ho olothreuōn ta prōtotoka thigē autōn',
   '''Kept the passover'' (pepoiēken to pascha — instituted/performed the Passover). ''The sprinkling of blood'' (tēn proschusin tou haimatos — the pouring/sprinkling of blood on the doorframes). Moses believed that blood applied to wood would protect from divine judgment. The Passover is the supreme OT type of Christ: the lamb slain, the blood applied, the firstborn spared, the people freed. ''He that destroyed'' (ho olothreuōn — the Destroyer; the death angel).',
   NULL),
  (29, 'By faith they passed through the Red sea as by dry land: which the Egyptians assaying to do were drowned.',
   'πίστει διέβησαν τὴν ἐρυθρὰν θάλασσαν ὡς διὰ ξηρᾶς ἧς πεῖραν λαβόντες οἱ Αἰγύπτιοι κατεπόθησαν',
   'pistei diebēsan tēn erythran thalassan hōs dia xēras hēs peiran labontes hoi Aigyptioi katepothēsan',
   '''Passed through the Red sea as by dry land'' — the same water that saved Israel destroyed Egypt. Faith made the difference: Israel walked through in trust; Egypt charged through in presumption. ''Were drowned'' (katepothēsan — were swallowed up). The event that demonstrated faith simultaneously demonstrated the consequences of unbelief.',
   NULL),
  (30, 'By faith the walls of Jericho fell down, after they were compassed about seven days.',
   'πίστει τὰ τείχη Ἰεριχὼ ἔπεσεν κυκλωθέντα ἐπὶ ἑπτὰ ἡμέρας',
   'pistei ta teichē Ierichō epesen kyklōthenta epi hepta hēmeras',
   'The walls of Jericho fell — not by military siege but by obedient faith. Israel marched around the city seven days as God commanded (Josh 6). From a military perspective, this was absurd; from a faith perspective, it was the only strategy that made sense. God''s methods often appear foolish to human wisdom but are vindicated by divine power (1 Cor 1:25).',
   NULL),
  (31, 'By faith the harlot Rahab perished not with them that believed not, when she had received the spies with peace.',
   'πίστει Ῥαὰβ ἡ πόρνη οὐ συναπώλετο τοῖς ἀπειθήσασιν δεξαμένη τοὺς κατασκόπους μετ᾽ εἰρήνης',
   'pistei Rhaab hē pornē ou synapōleto tois apeithēsasin dexamenē tous kataskopous met eirēnēs',
   '''The harlot Rahab'' (Rhaab hē pornē — Rahab the prostitute; her shameful past is mentioned, not to shame but to magnify grace). ''Perished not with them that believed not'' (ou synapōleto tois apeithēsasin — she was not destroyed along with the disobedient). Rahab — a Canaanite prostitute — is included in the faith hall of fame alongside Abraham and Moses. Her faith was expressed in action: she hid the spies, trusting Israel''s God (Josh 2:9-11). She is also in the genealogy of Christ (Matt 1:5). No background disqualifies someone from the life of faith.',
   NULL),
  (32, 'And what shall I more say? for the time would fail me to tell of Gedeon, and of Barak, and of Samson, and of Jephthae; of David also, and Samuel, and of the prophets:',
   'καὶ τί ἔτι λέγω ἐπιλείψει γάρ με διηγούμενον ὁ χρόνος περὶ Γεδεών Βαράκ τε καὶ Σαμψὼν καὶ Ἰεφθάε Δαυίδ τε καὶ Σαμουὴλ καὶ τῶν προφητῶν',
   'kai ti eti legō epileipsei gar me diēgoumenon ho chronos peri Gedeōn Barak te kai Sampsōn kai Iephthae Dauid te kai Samouēl kai tōn prophētōn',
   '''What shall I more say?'' — the author shifts from detailed narratives to a rapid-fire catalogue. Six individuals (Gideon, Barak, Samson, Jephthae, David, Samuel) plus ''the prophets'' — covering the entire period from the Judges to the monarchy and beyond. The pace accelerates, as though faith''s examples are too numerous to recount in full. Notably, these are imperfect heroes — Gideon doubted, Samson fell, Jephthae made a rash vow — yet all are commended for faith.',
   NULL),
  (33, 'Who through faith subdued kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions,',
   'οἳ διὰ πίστεως κατηγωνίσαντο βασιλείας εἰργάσαντο δικαιοσύνην ἐπέτυχον ἐπαγγελιῶν ἔφραξαν στόματα λεόντων',
   'hoi dia pisteōs katēgōnisanto basileias eirgasanto dikaiosynēn epetychon epangeliōn ephraxan stomata leontōn',
   'A cascade of faith''s achievements: ''subdued kingdoms'' (David, Joshua, the judges). ''Wrought righteousness'' (established justice). ''Obtained promises'' (received specific fulfillments). ''Stopped the mouths of lions'' (Daniel in the lions'' den, Dan 6:22; Samson, Judg 14:6; David, 1 Sam 17:34-36).',
   NULL),
  (34, 'Quenched the violence of fire, escaped the edge of the sword, out of weakness were made strong, waxed valiant in fight, turned to flight the armies of the aliens.',
   'ἔσβεσαν δύναμιν πυρός ἔφυγον στόματα μαχαίρας ἐνεδυναμώθησαν ἀπὸ ἀσθενείας ἐγενήθησαν ἰσχυροὶ ἐν πολέμῳ παρεμβολὰς ἔκλιναν ἀλλοτρίων',
   'esbesan dynamin pyros ephygon stomata machairas enedynamōthēsan apo astheneias egenēthēsan ischyroi en polemō parembolas eklinan allotriōn',
   '''Quenched the violence of fire'' (Shadrach, Meshach, Abednego, Dan 3). ''Escaped the edge of the sword'' (David from Saul; Elijah from Jezebel). ''Out of weakness were made strong'' (Samson''s final act; Hezekiah''s recovery; the Maccabean revolt). ''Waxed valiant in fight'' (became mighty in warfare). ''Turned to flight the armies of the aliens'' (repelled foreign invaders). Each phrase compresses an entire story of faith into a few words.',
   NULL),
  (35, 'Women received their dead raised to life again: and others were tortured, not accepting deliverance; that they might obtain a better resurrection:',
   'ἔλαβον γυναῖκες ἐξ ἀναστάσεως τοὺς νεκροὺς αὐτῶν ἄλλοι δὲ ἐτυμπανίσθησαν οὐ προσδεξάμενοι τὴν ἀπολύτρωσιν ἵνα κρείττονος ἀναστάσεως τύχωσιν',
   'elabon gynaikes ex anastaseōs tous nekrous autōn alloi de etympanisthēsan ou prosdexamenoi tēn apolytrōsin hina kreittonos anastaseōs tychōsin',
   '''Women received their dead raised'' (the widow of Zarephath, 1 Kings 17:22; the Shunammite woman, 2 Kings 4:36). The tone now shifts to suffering: ''others were tortured'' (etympanisthēsan — were beaten to death, broken on the wheel; tympanon was an instrument of torture). ''Not accepting deliverance'' — they could have been released by renouncing their faith, but they refused. ''A better resurrection'' (kreittonos anastaseōs — a superior resurrection; better than mere resuscitation like the widows'' children — eternal resurrection glory). Faith that chooses death over apostasy is the ultimate expression of trust in God''s promises.',
   'The pivot from faith''s triumphs (vv.33-35a) to faith''s sufferings (vv.35b-38) is deliberate and crucial. Faith does not always lead to visible victory; sometimes it leads to torture and death. But the faithful who suffer do so for a ''better resurrection'' — a resurrection that surpasses even the temporary raising of the dead. This prevents a ''prosperity gospel'' reading of faith.'),
  (36, 'And others had trial of cruel mockings and scourgings, yea, moreover of bonds and imprisonment:',
   'ἕτεροι δὲ ἐμπαιγμῶν καὶ μαστίγων πεῖραν ἔλαβον ἔτι δὲ δεσμῶν καὶ φυλακῆς',
   'heteroi de empaigmōn kai mastigōn peiran elabon eti de desmōn kai phylakēs',
   '''Cruel mockings'' (empaigmōn — scornful ridicule). ''Scourgings'' (mastigōn — whippings). ''Bonds and imprisonment'' (desmōn kai phylakēs — chains and prison). Jeremiah was mocked and imprisoned (Jer 20:2; 37:15); Micaiah was slapped and jailed (1 Kings 22:24-27). The catalog of suffering intensifies.',
   NULL),
  (37, 'They were stoned, they were sawn asunder, were tempted, were slain with the sword: they wandered about in sheepskins and goatskins; being destitute, afflicted, tormented;',
   'ἐλιθάσθησαν ἐπρίσθησαν ἐπειράσθησαν ἐν φόνῳ μαχαίρας ἀπέθανον περιῆλθον ἐν μηλωταῖς ἐν αἰγείοις δέρμασιν ὑστερούμενοι θλιβόμενοι κακουχούμενοι',
   'elithasthēsan epristhēsan epeirasthēsan en phonō machairas apethanon periēlthon en mēlōtais en aigeiois dermasin hysteremenoi thlibomenoi kakouchoumenoi',
   '''Stoned'' (Zechariah, 2 Chr 24:20-21; Naboth, 1 Kings 21; tradition says Jeremiah was stoned). ''Sawn asunder'' (epristhēsan — sawn in two; Jewish tradition says Isaiah was sawn in half by Manasseh inside a hollow tree). ''Slain with the sword'' (many prophets, 1 Kings 19:10). ''Sheepskins and goatskins'' — rough clothing of the prophets (Elijah, 2 Kings 1:8). ''Destitute, afflicted, tormented'' — three words describing the life of the faithful who had nothing but God.',
   NULL),
  (38, '(Of whom the world was not worthy:) they wandered in deserts, and in mountains, and in dens and caves of the earth.',
   'ὧν οὐκ ἦν ἄξιος ὁ κόσμος ἐν ἐρημίαις πλανώμενοι καὶ ὄρεσιν καὶ σπηλαίοις καὶ ταῖς ὀπαῖς τῆς γῆς',
   'hōn ouk ēn axios ho kosmos en erēmiais planōmenoi kai oresin kai spēlaiois kai tais opais tēs gēs',
   '''Of whom the world was not worthy'' (hōn ouk ēn axios ho kosmos — a breathtaking parenthetical). The world judged them as worthless outcasts; God''s verdict is the opposite — the world was unworthy of them. ''Deserts … mountains … dens and caves'' — the faithful lived as fugitives, hunted by the very world they blessed. This inverts all worldly values: the homeless fugitive is more precious in God''s sight than the entire civilization that rejects them.',
   'This is one of the most powerful parenthetical statements in all of Scripture. The world rejected these faithful ones; God declares the world unworthy of them. The supreme inversion of values: what the world discards, God treasures; what the world honors, God dismisses. This is the perspective of faith — and the encouragement for every suffering believer.'),
  (39, 'And these all, having obtained a good report through faith, received not the promise:',
   'καὶ οὗτοι πάντες μαρτυρηθέντες διὰ τῆς πίστεως οὐκ ἐκομίσαντο τὴν ἐπαγγελίαν',
   'kai houtoi pantes martyrēthentes dia tēs pisteōs ouk ekomisanto tēn epangelian',
   '''These all'' (houtoi pantes — every single one named in this chapter). ''Having obtained a good report through faith'' (martyrēthentes dia tēs pisteōs — having been witnessed about through faith; God commended them all). ''Received not the promise'' (ouk ekomisanto tēn epangelian — they did not receive the ultimate promise). Despite all their faith, they died without seeing the final fulfillment — the coming of Christ, the new covenant, the heavenly city. They lived and died ''in faith'' (v.13) without seeing the full realization of what they believed.',
   NULL),
  (40, 'God having provided some better thing for us, that they without us should not be made perfect.',
   'τοῦ θεοῦ περὶ ἡμῶν κρεῖττόν τι προβλεψαμένου ἵνα μὴ χωρὶς ἡμῶν τελειωθῶσιν',
   'tou theou peri hēmōn kreitton ti problepsamnou hina mē chōris hēmōn teleiōthōsin',
   '''God having provided some better thing for us'' (tou theou peri hēmōn kreitton ti problepsamnou — God having foreseen/planned something better concerning us). ''That they without us should not be made perfect'' (hina mē chōris hēmōn teleiōthōsin — so that they would not be perfected apart from us). The ''better thing'' is Christ''s completed work — the sacrifice, the new covenant, the heavenly priesthood. The OT saints could not be ''perfected'' (brought to their final goal) until Christ came. Their faith looked forward to what our faith looks back on. They and we form one people, one faith, one salvation — separated in time but united in Christ.',
   'This remarkable final verse binds the OT saints and NT believers into one redeemed community. God''s plan was always unified: the OT faithful are not perfected without us, and we are not complete without them. The ''better thing'' is Christ''s finished work, which retroactively validates all OT faith and prospectively secures all NT faith. One Savior, one sacrifice, one people of God across all ages.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Hebrews' AND c.chapter_number = 11;

-- Step 3: Insert word studies
INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, ws.original_word, ws.transliteration, ws.strongs_number, ws.meaning, ws.word_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  ('ὑπόστασις', 'hypostasis', 'G5287', 'Substance, foundation, assurance, reality, underlying essence — from hypo (under) + stasis (standing). In v.1 faith is the hypostasis of things hoped for — the underlying reality, the foundation on which hope stands. Faith gives substance to the invisible; it makes future promises present realities. In 1:3 the same word described God''s ''person'' (essential being); here it describes faith''s function as the ground of hope.', 1),
  ('ἔλεγχος', 'elenchos', 'G1650', 'Proof, evidence, conviction, demonstration — from elenchō (to convict, to reprove, to prove). In v.1 faith is the elenchos of things not seen — the proof, the convincing evidence of invisible realities. Just as a legal proof establishes a fact beyond reasonable doubt, so faith establishes the reality of the unseen world. Faith is not blind; it is the faculty that perceives what physical senses cannot.', 2),
  ('μισθαποδότης', 'misthapodotēs', 'G3406', 'Rewarder, one who pays wages — from misthos (wage, reward) + apodidōmi (to pay back, to give). A NT hapax (only in v.6). God is the misthapodotēs — the faithful Rewarder of those who diligently seek Him. Faith in God''s existence alone is not sufficient; one must also believe He rewards seekers. This dual conviction — that God is and that God rewards — is the foundation of all the faithful action described in this chapter.', 3),
  ('παρεπίδημος', 'parepidēmos', 'G3927', 'Stranger, temporary resident, sojourner, pilgrim — from para (beside) + epidēmeō (to reside as a foreigner). In v.13 the patriarchs confessed they were ''strangers and pilgrims'' — people whose true homeland was elsewhere. A parepidēmos lives in a place but does not belong to it; their citizenship is elsewhere. This captures the essential posture of the faithful: present in the world but belonging to heaven, living here but heading there.', 4),
  ('ὀνειδισμός', 'oneidismos', 'G3680', 'Reproach, insult, disgrace, abuse suffered for a cause — from oneidizō (to reproach, to revile). In v.26 Moses esteemed ''the reproach of Christ'' greater riches than Egypt. The word describes the specific kind of suffering endured for association with God''s people and God''s cause. Christ Himself bore the ultimate oneidismos (reproach) at the cross. Those who share in His reproach share in His eventual glory (Rom 8:17).', 5),
  ('ἀόρατος', 'aoratos', 'G517', 'Invisible, unseen, unable to be seen — from a (not) + horaō (to see). In v.27 Moses endured ''as seeing him who is invisible'' (ton aoraton hōs horōn). Faith perceives the invisible God with a clarity that surpasses physical sight. Moses traded the visible splendor of Pharaoh''s court for the invisible reality of God''s presence — and found the invisible more real, more powerful, and more enduring than anything Egypt could offer.', 6)
) AS ws(original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Hebrews' AND c.chapter_number = 11
  AND v.verse_number = CASE ws.word_order
    WHEN 1 THEN 1
    WHEN 2 THEN 1
    WHEN 3 THEN 6
    WHEN 4 THEN 13
    WHEN 5 THEN 26
    WHEN 6 THEN 27
  END;

-- Step 4: Insert cross-references
INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, cr.reference, cr.ref_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Romans 8:24-25', 1),
  (1, '2 Corinthians 4:18', 2),
  (3, 'Genesis 1:1', 3),
  (3, 'Psalm 33:6', 4),
  (3, 'John 1:3', 5),
  (4, 'Genesis 4:3-5', 6),
  (4, '1 John 3:12', 7),
  (5, 'Genesis 5:24', 8),
  (6, 'Romans 11:6', 9),
  (7, 'Genesis 6:13-22', 10),
  (7, '1 Peter 3:20', 11),
  (8, 'Genesis 12:1-4', 12),
  (8, 'Acts 7:2-4', 13),
  (10, 'Hebrews 12:22', 14),
  (10, 'Hebrews 13:14', 15),
  (10, 'Revelation 21:2', 16),
  (11, 'Genesis 17:19', 17),
  (11, 'Genesis 21:1-2', 18),
  (11, 'Romans 4:19-21', 19),
  (13, '1 Peter 2:11', 20),
  (13, 'Philippians 3:20', 21),
  (16, 'Exodus 3:6', 22),
  (16, 'Matthew 22:32', 23),
  (17, 'Genesis 22:1-14', 24),
  (17, 'James 2:21-23', 25),
  (19, 'Romans 4:17', 26),
  (22, 'Genesis 50:24-25', 27),
  (22, 'Exodus 13:19', 28),
  (24, 'Exodus 2:10-11', 29),
  (26, 'Hebrews 13:13', 30),
  (26, 'Philippians 3:8', 31),
  (27, '2 Corinthians 4:18', 32),
  (28, 'Exodus 12:21-30', 33),
  (29, 'Exodus 14:21-31', 34),
  (31, 'Joshua 2:1-21', 35),
  (31, 'James 2:25', 36),
  (31, 'Matthew 1:5', 37),
  (37, '2 Chronicles 24:20-21', 38),
  (38, '1 Kings 19:9-10', 39),
  (40, 'Hebrews 12:23', 40)
) AS cr(verse_number, reference, ref_order)
WHERE b.name = 'Hebrews' AND c.chapter_number = 11
  AND v.verse_number = cr.verse_number;
