-- ═══════════════════════════════════════════════════
-- JOHN CHAPTER 19 — The Crucifixion, Death, and Burial of Jesus
-- 42 verses · Greek text · Word studies · Cross-refs
-- ═══════════════════════════════════════════════════

-- Step 1: Insert chapter metadata
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 19,
  'John 19 is the crucifixion chapter — the climax of the Gospel. It falls into three movements: (1) the final stages of the Roman trial (vv.1-16a), including the scourging, the mocking with crown of thorns and purple robe, Pilate''s ''Ecce Homo'' (Behold the Man, v.5), the Jewish accusation of blasphemy (''he made himself the Son of God'', v.7), and the final condemnation; (2) the crucifixion itself (vv.16b-37), including the carrying of the cross, the titulus (the placard: ''Jesus of Nazareth the King of the Jews'' in three languages, vv.19-22), the casting of lots for his garments (fulfilling Psalm 22:18), the care of his mother (the Beloved Disciple commissioned as her son, vv.25-27), the cry ''I thirst'' (fulfilling Psalm 69:21, v.28), the completion of the work (''It is finished,'' tetelestai, v.30), the death by voluntary giving up of the spirit, the soldiers'' decision not to break his legs (fulfilling Psalm 34:20 and Zechariah 12:10), the blood and water from the pierced side (vv.31-37); (3) the burial (vv.38-42), by Joseph of Arimathaea and Nicodemus with a royal quantity of spices. John''s crucifixion narrative is the most theologically interpreted of the four Gospels: every detail is understood as fulfilment of Scripture (Psalm 22; 34; 69; Zechariah 12:10; Numbers 9:12), and the cross is presented not as defeat but as enthronement — Jesus reigns from the cross as King of the Jews.',
  'It Is Finished — The Cross as Throne and Victory',
  'τελέω (teleō)',
  'To complete, finish, bring to its end, fulfil, accomplish — from telos (end, goal, completion). The climactic word of the crucifixion narrative is ''Tetelestai'' (v.30: ''It is finished'') — perfect passive indicative: It has been completed and the completion stands. The same root appears in v.28 (''that the scripture might be fulfilled'', hina teleiōthē hē graphē). Tetelestai was used in ancient papyri as a commercial term stamped on receipts: ''Paid in full.'' The debt of sin is completely paid; nothing remains to be added. The cross is not the prelude to the real work; it IS the completed work. Jesus does not say ''I am dying'' but ''It is finished'' — the work is done, not the worker.',
  '["The Scourging and Mocking (vv.1-7): Then Pilate therefore took Jesus and scourged him. And the soldiers platted a crown of thorns and put it on his head and they put on him a purple robe and said Hail King of the Jews and they smote him with their hands. Pilate therefore went forth again and saith unto them Behold I bring him forth to you that ye may know that I find no fault in him. Then came Jesus forth wearing the crown of thorns and the purple robe. And Pilate saith unto them Behold the man. When the chief priests therefore and officers saw him they cried out saying Crucify him crucify him. Pilate saith unto them Take ye him and crucify him for I find no fault in him. The Jews answered him We have a law and by our law he ought to die because he made himself the Son of God","The Final Verdict (vv.8-16): When Pilate therefore heard that saying he was the more afraid and went again into the judgment hall and saith unto Jesus Whence art thou? But Jesus gave him no answer. Then saith Pilate unto him Speakest thou not unto me? knowest thou not that I have power to crucify thee and have power to release thee? Jesus answered Thou couldest have no power at all against me except it were given thee from above therefore he that delivered me unto thee hath the greater sin. And from thenceforth Pilate sought to release him but the Jews cried out saying If thou let this man go thou art not Caesar''s friend whosoever maketh himself a king speaketh against Caesar. When Pilate therefore heard that saying he brought Jesus forth and sat down in the judgment seat in a place that is called the Pavement but in the Hebrew Gabbatha. And it was the preparation of the passover and about the sixth hour and he saith unto the Jews Behold your King. But they cried out Away with him away with him crucify him. Pilate saith unto them Shall I crucify your King? The chief priests answered We have no king but Caesar. Then delivered he him therefore unto them to be crucified","The Crucifixion (vv.16-27): And they took Jesus and led him away. And he bearing his cross went forth into a place called the place of a skull which is called in the Hebrew Golgotha where they crucified him and two other with him on either side one and Jesus in the midst. And Pilate wrote a title and put it on the cross. And the writing was JESUS OF NAZARETH THE KING OF THE JEWS. This title then read many of the Jews for the place where Jesus was crucified was nigh to the city and it was written in Hebrew and Greek and Latin. Then said the chief priests of the Jews to Pilate Write not The King of the Jews but that he said I am King of the Jews. Pilate answered What I have written I have written. Then the soldiers when they had crucified Jesus took his garments and made four parts to every soldier a part and also his coat now the coat was without seam woven from the top throughout. They said therefore among themselves Let us not rend it but cast lots for it whose it shall be that the scripture might be fulfilled which saith They parted my raiment among them and for my vesture they did cast lots. These things therefore the soldiers did. Now there stood by the cross of Jesus his mother and his mother''s sister Mary the wife of Cleophas and Mary Magdalene. When Jesus therefore saw his mother and the disciple standing by whom he loved he saith unto his mother Woman behold thy son. Then saith he to the disciple Behold thy mother. And from that hour that disciple took her unto his own home","The Death of Jesus (vv.28-37): After this Jesus knowing that all things were now accomplished that the scripture might be fulfilled saith I thirst. Now there was set a vessel full of vinegar and they filled a spunge with vinegar and put it upon hyssop and put it to his mouth. When Jesus therefore had received the vinegar he said It is finished and he bowed his head and gave up the ghost. The Jews therefore because it was the preparation that the bodies should not remain upon the cross on the sabbath day for that sabbath day was an high day besought Pilate that their legs might be broken and that they might be taken away. Then came the soldiers and brake the legs of the first and of the other which was crucified with him. But when they came to Jesus and saw that he was dead already they brake not his legs but one of the soldiers with a spear pierced his side and forthwith came there out blood and water. And he that saw it bare record and his record is true and he knoweth that he saith true that ye might believe. For these things were done that the scripture should be fulfilled A bone of him shall not be broken. And again another scripture saith They shall look on him whom they pierced","The Burial (vv.38-42): And after this Joseph of Arimathaea being a disciple of Jesus but secretly for fear of the Jews besought Pilate that he might take away the body of Jesus and Pilate gave him leave. He came therefore and took the body of Jesus. And there came also Nicodemus which at the first came to Jesus by night and brought a mixture of myrrh and aloes about an hundred pound weight. Then took they the body of Jesus and wound it in linen clothes with the spices as the manner of the Jews is to bury. Now in the place where he was crucified there was a garden and in the garden a new sepulchre wherein was never man yet laid. There laid they Jesus therefore because of the Jews'' preparation day for the sepulchre was nigh at hand"]'
FROM books b WHERE b.name = 'John';

-- Step 2: Insert all 42 verses
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Then Pilate therefore took Jesus, and scourged him.',
   'τότε οὖν ἔλαβεν ὁ Πιλᾶτος τὸν Ἰησοῦν καὶ ἐμαστίγωσεν',
   'tote oun elaben ho Pilatos ton Iēsoun kai emastigōsen',
   '''Scourged him'' (emastigōsen — flogged him; mastigōo: to flog with a whip; mastigoō refers to the Jewish scourging of 40 lashes minus one; phragelloō [used in Matthew 27:26] refers to Roman flogging, the flagellum). Roman scourging (verberatio) was severe: a leather whip embedded with bone or metal fragments, tearing flesh to the bone, sometimes fatal in itself. Pilate''s intention seems to be to satisfy the crowd with a lesser punishment and release Jesus (cf. Luke 23:16,22). Instead, the scourging only escalates the demand for crucifixion.',
   NULL),
  (2, 'And the soldiers platted a crown of thorns, and put it on his head, and they put on him a purple robe,',
   'καὶ οἱ στρατιῶται πλέξαντες στέφανον ἐξ ἀκανθῶν ἐπέθηκαν αὐτοῦ τῇ κεφαλῇ καὶ ἱμάτιον πορφυροῦν περιέβαλον αὐτόν',
   'kai hoi stratiōtai plexantes stephanon ex akanthōn epethēkan autou tē kephalē kai himation porphyroun periebalon auton',
   '''A crown of thorns'' (stephanon ex akanthōn — a wreath/crown woven from thorns). The crown (stephanon — a victor''s wreath, not a royal diadem [diadēma]) is a mock-crown, but it is also unknowingly a true crown: the King of Glory crowned with the thorns of the curse (Genesis 3:18). ''Purple robe'' (himation porphyroun — a garment of purple; porphyra: purple dye from the murex shellfish, the colour of royalty). The mockery is simultaneously a proclamation: they dress him as a king precisely when he is being enthroned on the cross.',
   NULL),
  (3, 'And said, Hail, King of the Jews! and they smote him with their hands.',
   'καὶ ἤρχοντο πρὸς αὐτὸν καὶ ἔλεγον Χαῖρε ὁ βασιλεὺς τῶν Ἰουδαίων καὶ ἐδίδουν αὐτῷ ῥαπίσματα',
   'kai ērchonto pros auton kai elegon Chaire ho basileus tōn Ioudaiōn kai edidoun autō rhaismata',
   '''Hail, King of the Jews!'' (Chaire ho basileus tōn Ioudaiōn — Hail [greeting], the King of the Jews). ''Chaire'' (from chairō: to rejoice) was the standard Greek greeting, equivalent to ''Ave'' in Latin — ironically the same word used by the angel to Mary (Luke 1:28: ''Hail, thou that art highly favoured''). The soldiers parody the imperial salute (''Ave Caesar''). Yet their mockery is truer than they know: he is the King not just of the Jews but of the universe.',
   NULL),
  (4, 'Pilate therefore went forth again, and saith unto them, Behold, I bring him forth to you, that ye may know that I find no fault in him.',
   'καὶ ἐξῆλθεν πάλιν ἔξω ὁ Πιλᾶτος καὶ λέγει αὐτοῖς Ἴδε ἄγω ὑμῖν αὐτὸν ἔξω ἵνα γνῶτε ὅτι ἐν αὐτῷ οὐδεμίαν αἰτίαν εὑρίσκω',
   'kai exēlthen palin exō ho Pilatos kai legei autois Ide agō hymin auton exō hina gnōte hoti en autō oudemian aitian heuriskō',
   'Pilate''s second declaration of innocence (cf. 18:38; 19:6). He brings the scourged, mocked Jesus out as a pathetic figure — perhaps hoping that the sight of his suffering will satisfy the crowd and allow release. ''That ye may know that I find no fault in him'' — the public declaration is important: Rome officially declares Jesus innocent even as it prepares to execute him. The injustice is public, deliberate, and officially recorded.',
   NULL),
  (5, 'Then came Jesus forth, wearing the crown of thorns, and the purple robe. And Pilate saith unto them, Behold the man!',
   'ἐξῆλθεν οὖν ὁ Ἰησοῦς ἔξω φορῶν τὸν ἀκάνθινον στέφανον καὶ τὸ πορφυροῦν ἱμάτιον καὶ λέγει αὐτοῖς Ἰδοὺ ὁ ἄνθρωπος',
   'exēlthen oun ho Iēsous exō phorōn ton akanthinon stephanon kai to porphyroun himation kai legei autois Idou ho anthrōpos',
   '''Behold the man!'' (Idou ho anthrōpos — Behold the man; ''Ecce Homo'' in Latin). One of the most famous utterances in history. Pilate intends a display of pitiable humanity to move the crowd to mercy: look at this broken man, surely this is enough? But John''s readers hear more: this is THE Man — the Son of Man (Daniel 7:13), the representative human, the second Adam, the one in whom humanity finds its destiny. ''Behold the man'' is simultaneously Pilate''s plea for mercy and John''s theological declaration.',
   NULL),
  (6, 'When the chief priests therefore and officers saw him, they cried out, saying, Crucify him, crucify him. Pilate saith unto them, Take ye him, and crucify him: for I find no fault in him.',
   'ὅτε οὖν εἶδον αὐτὸν οἱ ἀρχιερεῖς καὶ οἱ ὑπηρέται ἐκραύγασαν λέγοντες Σταύρωσον σταύρωσον αὐτόν λέγει αὐτοῖς ὁ Πιλᾶτος Λάβετε αὐτὸν ὑμεῖς καὶ σταυρώσατε ἐγὼ γὰρ οὐχ εὑρίσκω ἐν αὐτῷ αἰτίαν',
   'hote oun eidon auton hoi archiereis kai hoi hypēretai ekraugasan legontes Stauroson stauroson auton legei autois ho Pilatos Labete auton hymeis kai staurōsate egō gar ouch heuriskō en autō aitian',
   '''Crucify him, crucify him'' (Stauroson, stauroson auton — crucify, crucify him; the verb stauróō: to affix to a cross). The repetition is frenzy. Pilate''s third declaration of innocence: ''I find no fault in him.'' Three times ''no fault'' (18:38; 19:4; 19:6) — a threefold legal acquittal that makes the subsequent condemnation the most unjust verdict in history. Yet it is simultaneously the fulfilment of God''s saving purpose.',
   NULL),
  (7, 'The Jews answered him, We have a law, and by our law he ought to die, because he made himself the Son of God.',
   'ἀπεκρίθησαν αὐτῷ οἱ Ἰουδαῖοι Ἡμεῖς νόμον ἔχομεν καὶ κατὰ τὸν νόμον ὀφείλει ἀποθανεῖν ὅτι ἑαυτὸν υἱὸν θεοῦ ἐποίησεν',
   'apekrithēsan autō hoi Ioudaioi Hēmeis nomon echomen kai kata ton nomon opheilei apothanein hoti heauton huion theou epoiēsen',
   '''He made himself the Son of God'' (heauton huion theou epoiēsen — he made himself Son of God). The real charge is now disclosed: not political rebellion but blasphemy. Leviticus 24:16: ''He that blasphemeth the name of the LORD, he shall surely be put to death.'' The Jewish authorities understood Jesus''s claim to divine sonship as blasphemy because they did not believe it was true. The irony is complete: he was executed as a blasphemer precisely because his claim was TRUE — and because it was true, the death he died became the atoning sacrifice for the world.',
   NULL),
  (8, 'When Pilate therefore heard that saying, he was the more afraid;',
   'ὅτε οὖν ἤκουσεν ὁ Πιλᾶτος τοῦτον τὸν λόγον μᾶλλον ἐφοβήθη',
   'hote oun ēkousen ho Pilatos touton ton logon mallon ephobēthē',
   '''He was the more afraid'' (mallon ephobēthē — he became more afraid; the comparative: his existing fear deepened). Pilate is already unsettled by this prisoner (his wife''s dream, Matthew 27:19; Jesus''s answers about kingship). Now the charge is ''Son of God'' — in Roman polytheistic religion, the son of a god (divi filius) was a real category; the emperors claimed divine sonship. Pilate is afraid of what he might be doing if this is actually true.',
   NULL),
  (9, 'And went again into the judgment hall, and saith unto Jesus, Whence art thou? But Jesus gave him no answer.',
   'καὶ εἰσῆλθεν εἰς τὸ πραιτώριον πάλιν καὶ λέγει τῷ Ἰησοῦ Πόθεν εἶ σύ ὁ δὲ Ἰησοῦς ἀπόκρισιν οὐκ ἔδωκεν αὐτῷ',
   'kai eisēlthen eis to praitōrion palin kai legei tō Iēsou Pothen ei sy ho de Iēsous apokrisin ouk edōken autō',
   '''Whence art thou?'' (Pothen ei sy? — Where are you from? What is your origin?). This is the deepest question in the Gospel of John — the question of Jesus''s origin. It has been asked before (7:27-28; 8:14; 9:29-30). Pilate now asks it with genuine anxiety. ''But Jesus gave him no answer'' (apokrisin ouk edōken autō — he gave him no answer). The silence fulfils Isaiah 53:7: ''He is brought as a lamb to the slaughter, and as a sheep before her shearers is dumb, so he openeth not his mouth.'' The moment for dialogue with Pilate has passed; the Governor had his chance (18:37-38) and walked away from truth.',
   NULL),
  (10, 'Then saith Pilate unto him, Speakest thou not unto me? knowest thou not that I have power to crucify thee, and have power to release thee?',
   'λέγει οὖν αὐτῷ ὁ Πιλᾶτος Ἐμοὶ οὐ λαλεῖς οὐκ οἶδας ὅτι ἐξουσίαν ἔχω ἀπολῦσαί σε καὶ ἐξουσίαν ἔχω σταυρῶσαί σε',
   'legei oun autō ho Pilatos Emoi ou laleis ouk oidas hoti exousian echō apolusai se kai exousian echō staurōsai se',
   '''I have power to crucify thee, and have power to release thee'' (exousian echō apolusai se kai exousian echō staurōsai se — I have authority to release you and authority to crucify you). Pilate''s boast of power triggers Jesus''s correction. The word ''exousia'' (authority, power) is used throughout John for the authority given by the Father to the Son (1:12; 5:27; 17:2). Pilate thinks he holds the ultimate power; Jesus reveals who actually controls the situation.',
   NULL),
  (11, 'Jesus answered, Thou couldest have no power at all against me, except it were given thee from above: therefore he that delivered me unto thee hath the greater sin.',
   'ἀπεκρίθη αὐτῷ Ἰησοῦς Οὐκ εἶχες ἐξουσίαν οὐδεμίαν κατ᾽ ἐμοῦ εἰ μὴ ἦν δεδομένον σοι ἄνωθεν διὰ τοῦτο ὁ παραδιδούς μέ σοι μείζονα ἁμαρτίαν ἔχει',
   'apekrithē autō Iēsous Ouk eiches exousian oudemian kat emou ei mē ēn dedomenon soi anōthen dia touto ho paradidous me soi meizona hamartian echei',
   '''No power at all against me, except it were given thee from above'' (ei mē ēn dedomenon soi anōthen — unless it had been given to you from above; anōthen: from above, the same word as ''born again'' in 3:3). All human authority is derived authority — it comes from God (Romans 13:1). Pilate exercises a delegated authority over Jesus only because the Father has ordained this moment. ''He that delivered me'' (ho paradidous me — the one handing me over) — probably referring primarily to Caiaphas or the Jewish leadership, though Judas is included. ''Greater sin'' — comparative culpability: both are guilty, but the one who used religious authority to demand the execution has greater sin than the pagan who executes under political pressure.',
   NULL),
  (12, 'And from thenceforth Pilate sought to release him: but the Jews cried out, saying, If thou let this man go, thou art not Caesar''s friend: whosoever maketh himself a king speaketh against Caesar.',
   'ἐκ τούτου ὁ Πιλᾶτος ἐζήτει ἀπολῦσαι αὐτόν οἱ δὲ Ἰουδαῖοι ἔκραζον λέγοντες Ἐὰν τοῦτον ἀπολύσῃς οὐκ εἶ φίλος τοῦ Καίσαρος πᾶς ὁ βασιλέα ἑαυτὸν ποιῶν ἀντιλέγει τῷ Καίσαρι',
   'ek toutou ho Pilatos ezētei apolusai auton hoi de Ioudaioi ekrazon legontes Ean touton apolusēs ouk ei philos tou Kaisaros pas ho basilea heauton poiōn antilegei tō Kaisari',
   '''Thou art not Caesar''s friend'' (ouk ei philos tou Kaisaros — you are not the friend of Caesar). ''Amicus Caesaris'' (Friend of Caesar) was a specific honorific title in Rome — an official position of favour and trust. The threat is direct: release Jesus and we will report you to Rome as a man who released a rival king. Pilate is in a politically impossible position. His desire for justice is trumped by his desire for self-preservation. The politics of fear produces the greatest injustice.',
   NULL),
  (13, 'When Pilate therefore heard that saying, he brought Jesus forth, and sat down in the judgment seat in a place that is called the Pavement, but in the Hebrew, Gabbatha.',
   'ὁ οὖν Πιλᾶτος ἀκούσας τούτων τῶν λόγων ἤγαγεν ἔξω τὸν Ἰησοῦν καὶ ἐκάθισεν ἐπὶ βήματος εἰς τόπον λεγόμενον Λιθόστρωτον Ἑβραϊστὶ δὲ Γαββαθα',
   'ho oun Pilatos akousōn toutōn tōn logōn ēgagen exō ton Iēsoun kai ekathisen epi bēmatos eis topon legomenon Lithostroton Hebraisti de Gabbatha',
   '''The Pavement'' (Lithostroton — the Stone Pavement; from lithos: stone + strōnnymi: to spread, pave). The Greek word describes an ornate stone mosaic floor; ''Gabbatha'' in Aramaic means ''elevated place, raised platform.'' The bēma (judgment seat) — the official raised platform from which judgments were pronounced. This is the moment of formal sentencing. John''s detail about the location is historically significant — archaeological excavations have uncovered such pavement stones near the site of the Antonia Fortress or Herod''s Palace.',
   NULL),
  (14, 'And it was the preparation of the passover, and about the sixth hour: and he saith unto the Jews, Behold your King!',
   'ἦν δὲ παρασκευὴ τοῦ πάσχα ὥρα δὲ ὡσεὶ ἕκτη καὶ λέγει τοῖς Ἰουδαίοις Ἴδε ὁ βασιλεὺς ὑμῶν',
   'ēn de paraskeuē tou pascha hōra de hōsei hektē kai legei tois Ioudaiois Ide ho basileus hymōn',
   '''The preparation of the passover'' (paraskeuē tou pascha — the Preparation [Friday before the Passover meal]). John places the crucifixion on Nisan 14, the day the Passover lambs were slaughtered (12-3 PM), making Jesus the true Passover Lamb (1 Corinthians 5:7). ''About the sixth hour'' — noon by Roman reckoning (though Mark 15:25 says ''the third hour,'' 9 AM; the discrepancy has various explanations: different reckoning, rounded hours, or textual issues). ''Behold your King!'' (Ide ho basileus hymōn) — Pilate''s final, ironic, contemptuous offer: this pathetic scourged figure is your king.',
   NULL),
  (15, 'But they cried out, Away with him, away with him, crucify him. Pilate saith unto them, Shall I crucify your King? The chief priests answered, We have no king but Caesar.',
   'οἱ δὲ ἐκραύγασαν Ἆρον ἆρον σταύρωσον αὐτόν λέγει αὐτοῖς ὁ Πιλᾶτος Τὸν βασιλέα ὑμῶν σταυρώσω ἀπεκρίθησαν οἱ ἀρχιερεῖς Οὐκ ἔχομεν βασιλέα εἰ μὴ Καίσαρα',
   'hoi de ekraugasan Aron aron staurōson auton legei autois ho Pilatos Ton basilea hymōn staurōsō apekrithēsan hoi archiereis Ouk echomen basilea ei mē Kaisara',
   '''We have no king but Caesar'' (Ouk echomen basilea ei mē Kaisara — We have no king except Caesar). The chief priests'' blasphemous declaration. In Israel''s theology, God alone was King (1 Samuel 8:7; Psalm 47:7; Isaiah 43:15). By declaring Caesar their only king, the high priests formally renounced the sovereignty of God over Israel — apostasy expressed in political terms. The nation that was to have no king but Yahweh now chooses the Roman Emperor. The irony is historically crushing: within 40 years, the city and Temple would be destroyed by this Caesar''s armies.',
   NULL),
  (16, 'Then delivered he him therefore unto them to be crucified. And they took Jesus, and led him away.',
   'τότε οὖν παρέδωκεν αὐτὸν αὐτοῖς ἵνα σταυρωθῇ Παρέλαβον δὲ τὸν Ἰησοῦν καὶ ἤγαγον',
   'tote oun paredōken auton autois hina staurōthē Parelabon de ton Iēsoun kai ēgagon',
   '''Then delivered he him therefore unto them to be crucified'' (paredōken auton autois hina staurōthē — he handed him over to them to be crucified). ''Paredōken'' (handed over, delivered up) — the same verb used for Judas''s betrayal (paradidōmi: 13:2,11; 18:2,5). Pilate, Judas, the chief priests — all hand Jesus over. Yet behind all of them is the Father, who ''spared not his own Son, but delivered him up for us all'' (Romans 8:32). The chain of betrayal leads back to divine love.',
   NULL),
  (17, 'And he bearing his cross went forth into a place called the place of a skull, which is called in the Hebrew Golgotha:',
   'καὶ βαστάζων αὐτῷ τὸν σταυρὸν ἐξῆλθεν εἰς τὸν λεγόμενον Κρανίου Τόπον ὃ λέγεται Ἑβραϊστὶ Γολγοθᾶ',
   'kai bastazōn autō ton stauron exēlthen eis ton legomenon Kraniou Topon ho legetai Hebraisti Golgotha',
   '''He bearing his cross'' (bastazōn auton ton stauron — bearing his cross). John omits the detail of Simon of Cyrene being compelled to carry the cross (Mark 15:21; Luke 23:26), emphasising Jesus''s own bearing. In 10:18 Jesus said ''I lay down my life of myself'' — he goes to the cross under his own power and will. ''Golgotha'' (Aramaic: gulgoltha, skull) — probably named for its skull-like appearance, an elevated rocky outcrop outside the city wall (Hebrews 13:12). The traditional site is within the present Church of the Holy Sepulchre, inside what was then outside the city walls.',
   NULL),
  (18, 'Where they crucified him, and two other with him, on either side one, and Jesus in the midst.',
   'ὅπου αὐτὸν ἐσταύρωσαν καὶ μετ᾽ αὐτοῦ ἄλλους δύο ἐντεῦθεν καὶ ἐντεῦθεν μέσον δὲ τὸν Ἰησοῦν',
   'hopou auton estaurōsan kai met autou allous dyo enteuthen kai enteuthen meson de ton Iēsoun',
   '''Jesus in the midst'' (meson de ton Iēsoun — Jesus in the middle). Between two criminals, Jesus occupies the central position — the place of supreme shame becomes the place of supreme honour. Isaiah 53:12: ''He was numbered with the transgressors.'' The two criminals represent the division that Christ brings (Luke 23:39-43: one mocks, one believes) — the division that will continue throughout history as all men encounter the crucified Christ.',
   NULL),
  (19, 'And Pilate wrote a title, and put it on the cross. And the writing was, JESUS OF NAZARETH THE KING OF THE JEWS.',
   'ἔγραψεν δὲ καὶ τίτλον ὁ Πιλᾶτος καὶ ἔθηκεν ἐπὶ τοῦ σταυροῦ ἦν δὲ γεγραμμένον ΙΗΣΟΥΣ Ο ΝΑΖΩΡΑΙΟΣ Ο ΒΑΣΙΛΕΥΣ ΤΩΝ ΙΟΥΔΑΙΩΝ',
   'egrapsen de kai titlon ho Pilatos kai ethēken epi tou staurou ēn de gegrammenon IĒSOUS HO NAZŌRAIOS HO BASILEUS TŌN IOUDAIŌN',
   '''JESUS OF NAZARETH THE KING OF THE JEWS'' (IĒSOUS HO NAZŌRAIOS HO BASILEUS TŌN IOUDAIŌN) — the titulus (Latin inscription giving the name and charge). In Roman crucifixion, the charge was written on a placard carried before the condemned or affixed to the cross. Pilate''s inscription is the most theologically accurate statement in the Passion narrative — he who intended contempt proclaimed truth. ''The King of the Jews'' is the title the Magi sought (Matthew 2:2), that Pilate wrote, that the soldiers mocked — and that is eternally true. The cross is the throne.',
   NULL),
  (20, 'This title then read many of the Jews: for the place where Jesus was crucified was nigh to the city: and it was written in Hebrew, and Greek, and Latin.',
   'τοῦτον οὖν τὸν τίτλον πολλοὶ ἀνέγνωσαν τῶν Ἰουδαίων ὅτι ἐγγὺς ἦν ὁ τόπος τῆς πόλεως ὅπου ἐσταυρώθη ὁ Ἰησοῦς καὶ ἦν γεγραμμένον Ἑβραϊστί Ῥωμαϊστί Ἑλληνιστί',
   'touton oun ton titlon polloi anegnōsan tōn Ioudaiōn hoti engys ēn ho topos tēs poleōs hopou estaurōthē ho Iēsous kai ēn gegrammenon Hebraisti Rōmaisti Hellēnisti',
   '''Written in Hebrew, and Greek, and Latin'' — the three great languages of the ancient world: Hebrew (the language of religion), Latin (the language of law and empire), Greek (the language of commerce and culture). The universal proclamation of the King of kings in the three universal languages of the day. This is the original ''international'' Gospel declaration, proclaimed from the cross before the first missionary journey.',
   NULL),
  (21, 'Then said the chief priests of the Jews to Pilate, Write not, The King of the Jews; but that he said, I am King of the Jews.',
   'ἔλεγον οὖν τῷ Πιλάτῳ οἱ ἀρχιερεῖς τῶν Ἰουδαίων Μὴ γράφε ὁ βασιλεὺς τῶν Ἰουδαίων ἀλλ᾽ ὅτι ἐκεῖνος εἶπεν Βασιλεύς εἰμι τῶν Ἰουδαίων',
   'elegon oun tō Pilatō hoi archiereis tōn Ioudaiōn Mē graphe ho basileus tōn Ioudaiōn all hoti ekeinos eipen Basileus eimi tōn Ioudaiōn',
   'The chief priests want a correction: change ''The King'' to ''He claimed to be king'' — a difference between proclamation and allegation. They are uncomfortable with the title as a statement of fact. Their discomfort confirms that Pilate''s inscription, however unintentionally, is a truthful declaration.',
   NULL),
  (22, 'Pilate answered, What I have written I have written.',
   'ἀπεκρίθη ὁ Πιλᾶτος Ὃ γέγραφα γέγραφα',
   'apekrithē ho Pilatos Ho gegrafa gegrafa',
   '''What I have written I have written'' (Ho gegrafa, gegrafa — What I have written, I have written; perfect tense: a done thing that stands). Pilate''s most famous and most stubborn statement. In all his weakness throughout the trial, here he is immovable. The words stand — permanently, in three languages, in all four Gospels — as the most widely distributed theological statement of the crucifixion. Divine providence used a stubborn Roman governor to write the eternal truth about the cross.',
   NULL),
  (23, 'Then the soldiers, when they had crucified Jesus, took his garments, and made four parts, to every soldier a part; and also his coat: now the coat was without seam, woven from the top throughout.',
   'οἱ οὖν στρατιῶται ὅτε ἐσταύρωσαν τὸν Ἰησοῦν ἔλαβον τὰ ἱμάτια αὐτοῦ καὶ ἐποίησαν τέσσαρα μέρη ἑκάστῳ στρατιώτῃ μέρος καὶ τὸν χιτῶνα ἦν δὲ ὁ χιτὼν ἄραφος ἐκ τῶν ἄνωθεν ὑφαντὸς δι᾽ ὅλου',
   'hoi oun stratiōtai hote estaurōsan ton Iēsoun elabon ta himatia autou kai epoiēsan tessara merē hekastō stratiōtē meros kai ton chitōna ēn de ho chitōn araphos ek tōn anōthen hyphantos di holou',
   '''Without seam, woven from the top throughout'' (araphos — seamless; a-: without + rhaptō: to sew; ek tōn anōthen hyphantos di holou: woven from the top all the way through). The undergarment (chitōn) is a single woven piece — a valuable, unusual garment. The Talmud (Yoma 71b-72a) describes the high priest''s tunic as seamless. Jesus, the true High Priest, wears a seamless garment. Its integrity mirrors the unity of his body, the Church (17:21-23; 1 Corinthians 1:13: ''Is Christ divided?'').',
   NULL),
  (24, 'They said therefore among themselves, Let us not rend it, but cast lots for it, whose it shall be: that the scripture might be fulfilled, which saith, They parted my raiment among them, and for my vesture they did cast lots. These things therefore the soldiers did.',
   'εἶπαν οὖν πρὸς ἀλλήλους Μὴ σχίσωμεν αὐτόν ἀλλὰ λάχωμεν περὶ αὐτοῦ τίνος ἔσται ἵνα ἡ γραφὴ πληρωθῇ ἡ λέγουσα Διεμερίσαντο τὰ ἱμάτιά μου ἑαυτοῖς καὶ ἐπὶ τὸν ἱματισμόν μου ἔβαλον κλῆρον οἱ μὲν οὖν στρατιῶται ταῦτα ἐποίησαν',
   'eipon oun pros allēlous Mē schisōmen auton alla lachōmen peri autou tinos estai hina hē graphē plērōthē hē legousa Diemerisanto ta himatia mou heautois kai epi ton himatismon mou ebalon klēron hoi men oun stratiōtai tauta epoiēsan',
   'Quoting Psalm 22:18 — the great Psalm of the crucifixion. The soldiers'' practical decision (don''t tear the seamless garment; cast lots instead) fulfils Scripture written 1000 years earlier. The detail of the garments — four soldiers, four parts, one seamless robe — fits the pattern of a Roman execution squad of four (quaternion, Acts 12:4). The fulfilment of Scripture in the most mundane detail (who gets a piece of cloth?) demonstrates that the cross is under divine supervision at every level.',
   NULL),
  (25, 'Now there stood by the cross of Jesus his mother, and his mother''s sister, Mary the wife of Cleophas, and Mary Magdalene.',
   'εἱστήκεισαν δὲ παρὰ τῷ σταυρῷ τοῦ Ἰησοῦ ἡ μήτηρ αὐτοῦ καὶ ἡ ἀδελφὴ τῆς μητρὸς αὐτοῦ Μαρία ἡ τοῦ Κλωπᾶ καὶ Μαρία ἡ Μαγδαληνή',
   'heistēkeisan de para tō staurō tou Iēsou hē mētēr autou kai hē adelphē tēs mētros autou Maria hē tou Klōpa kai Maria hē Magdalēnē',
   '''There stood by the cross of Jesus his mother'' (heistēkeisan de para tō staurō tou Iēsou hē mētēr autou — they were standing beside the cross of Jesus, his mother). Four women at the cross: (1) his mother (Mary, though unnamed in John); (2) his mother''s sister — possibly Salome, mother of James and John (Mark 15:40), which would make John a cousin of Jesus; (3) Mary wife of Cleophas — possibly mother of James the Less; (4) Mary Magdalene. The women of the Passion stand where the disciples (mostly) fled. Their courage and love are the primary testimony to the death.',
   NULL),
  (26, 'When Jesus therefore saw his mother, and the disciple standing by, whom he loved, he saith unto his mother, Woman, behold thy son!',
   'Ἰησοῦς οὖν ἰδὼν τὴν μητέρα καὶ τὸν μαθητὴν παρεστῶτα ὃν ἠγάπα λέγει τῇ μητρί Γύναι ἴδε ὁ υἱός σου',
   'Iēsous oun idōn tēn mētera kai ton mathētēn parestōta hon ēgapa legei tē mētri Gynai ide ho huios sou',
   '''Woman, behold thy son!'' (Gynai, ide ho huios sou — Woman, behold your son). Even on the cross, Jesus fulfils his filial duty. ''Woman'' (gynai) — not disrespectful but formal and solemn (cf. 2:4; 20:15). From the cross, with diminishing breath, Jesus makes legal provision for his mother''s care. He commits her to the Beloved Disciple — the one he loves as a son — creating a new family relationship. This is one of the seven words from the cross.',
   NULL),
  (27, 'Then saith he to the disciple, Behold thy mother! And from that hour that disciple took her unto his own home.',
   'εἶτα λέγει τῷ μαθητῇ Ἴδε ἡ μήτηρ σου καὶ ἀπ᾽ ἐκείνης τῆς ὥρας ἔλαβεν ὁ μαθητὴς αὐτὴν εἰς τὰ ἴδια',
   'eita legei tō mathētē Ide hē mētēr sou kai ap ekeinēs tēs hōras elaben ho mathētēs autēn eis ta idia',
   '''From that hour that disciple took her unto his own home'' (ap ekeinēs tēs hōras elaben ho mathētēs autēn eis ta idia — from that hour the disciple took her into his own). ''Eis ta idia'' (into his own things/home) — the same phrase used in 1:11 (''he came unto his own''). The Beloved Disciple becomes the new ''beloved son'' of Mary; Mary becomes his mother. The cross creates a new family — the family of faith. James (Jesus''s brother) was not yet a believer (7:5); after the resurrection he became a pillar of the church (Acts 15:13; Galatians 1:19).',
   NULL),
  (28, 'After this, Jesus knowing that all things were now accomplished, that the scripture might be fulfilled, saith, I thirst.',
   'Μετὰ τοῦτο εἰδὼς ὁ Ἰησοῦς ὅτι πάντα ἤδη τετέλεσται ἵνα τελειωθῇ ἡ γραφή λέγει Διψῶ',
   'Meta touto eidōs ho Iēsous hoti panta ēdē tetelestai hina teleiōthē hē graphē legei Dipsō',
   '''I thirst'' (Dipsō — I am thirsty; present: I thirst now, actively). ''Knowing that all things were now accomplished'' (eidōs hoti panta ēdē tetelestai — knowing that everything had already been completed; perfect passive: was in a state of completion). Jesus speaks the thirst because he knows the work is complete — this is the final fulfilment of Scripture before the death. Fulfilling Psalm 69:21: ''In my thirst they gave me vinegar to drink.'' The one who promised living water (4:10-14; 7:37-38) thirsts on the cross — bearing the full human condition.',
   NULL),
  (29, 'Now there was set a vessel full of vinegar: and they filled a spunge with vinegar, and put it upon hyssop, and put it to his mouth.',
   'σκεῦος οὖν ἔκειτο ὄξους μεστόν σπόγγον οὖν μεστὸν τοῦ ὄξους ὑσσώπῳ περιθέντες προσήνεγκαν αὐτοῦ τῷ στόματι',
   'skeuos oun ekeito oxous meston spongon oun meston tou oxous hyssōpō perithentes prosēnenkan autou tō stomati',
   '''Upon hyssop'' (hyssōpō — hyssop; a bushy plant). John uniquely specifies hyssop — a plant used in the Passover ritual (Exodus 12:22: the hyssop dipped in the lamb''s blood to mark the doorposts). The hyssop connects the dying Jesus to the Passover lamb. The sponge of vinegar (posca — the common sour wine drink of Roman soldiers) offered on hyssop is both practical relief and fulfilment of Psalm 69:21.',
   NULL),
  (30, 'When Jesus therefore had received the vinegar, he said, It is finished: and he bowed his head, and gave up the ghost.',
   'ὅτε οὖν ἔλαβεν τὸ ὄξος ὁ Ἰησοῦς εἶπεν Τετέλεσται καὶ κλίνας τὴν κεφαλὴν παρέδωκεν τὸ πνεῦμα',
   'hote oun elaben to oxos ho Iēsous eipen Tetelestai kai klinas tēn kephalēn paredōken to pneuma',
   '''It is finished'' (Tetelestai — It has been completed and remains complete; perfect passive indicative of teleō). The single word in Greek that is the climax of the entire Gospel. ''Tetelestai'' was written on papyri receipts in the ancient world to mean ''paid in full.'' The debt of sin — every transgression, every rebellion, the entire weight of human guilt — is ''paid in full'' by the atoning death of the Son of God. Nothing can be added to it; nothing needs to be added. ''He bowed his head, and gave up the ghost'' (klinas tēn kephalēn, paredōken to pneuma — having bowed his head, he handed over the spirit). ''Gave up'' (paredōken — handed over, delivered up; as a free, deliberate act). John uses the language of volition: Jesus does not have his life taken; he hands it over (10:18).',
   NULL),
  (31, 'The Jews therefore, because it was the preparation, that the bodies should not remain upon the cross on the sabbath day, (for that sabbath day was an high day,) besought Pilate that their legs might be broken, and that they might be taken away.',
   'οἱ οὖν Ἰουδαῖοι ἐπεὶ παρασκευὴ ἦν ἵνα μὴ μείνῃ ἐπὶ τοῦ σταυροῦ τὰ σώματα ἐν τῷ σαββάτῳ ἦν γὰρ μεγάλη ἡ ἡμέρα ἐκείνου τοῦ σαββάτου ἠρώτησαν τὸν Πιλᾶτον ἵνα κατεαγῶσιν αὐτῶν τὰ σκέλη καὶ ἀρθῶσιν',
   'hoi oun Ioudaioi epei paraskeuē ēn hina mē meinē epi tou staurou ta sōmata en tō sabbatō ēn gar megalē hē hēmera ekeinou tou sabbatou ērōtēsan ton Pilaton hina kateagōsin autōn ta skelē kai arthōsin',
   '''Legs might be broken'' (kateagōsin ta skelē — that their legs might be broken; crurifragium). Breaking the legs (with a heavy mallet) accelerated death by preventing the crucified from pushing himself up to breathe. Roman law permitted bodies to remain on crosses; Jewish law required burial before sunset on the Sabbath (Deuteronomy 21:23). The fact that Jesus was dead before crurifragium was necessary preserves the fulfilment of Psalm 34:20 and Numbers 9:12.',
   NULL),
  (32, 'Then came the soldiers, and brake the legs of the first, and of the other which was crucified with him.',
   'ἦλθον οὖν οἱ στρατιῶται καὶ τοῦ μὲν πρώτου κατέαξαν τὰ σκέλη καὶ τοῦ ἄλλου τοῦ συσταυρωθέντος αὐτῷ',
   'ēlthon oun hoi stratiōtai kai tou men prōtou kateaxan ta skelē kai tou allou tou systaurōthentos autō',
   'The two criminals'' legs are broken — they are still alive, still struggling to breathe. Jesus is approached next (v.33). The order of events confirms the timeline: Jesus died before the others, earlier than expected. This is medically plausible: the severity of the scourging, the loss of blood, the physical agony — Jesus''s body may have given out before the others who were perhaps less weakened before the crucifixion.',
   NULL),
  (33, 'But when they came to Jesus, and saw that he was dead already, they brake not his legs:',
   'ἐπὶ δὲ τὸν Ἰησοῦν ἐλθόντες ὡς εἶδον αὐτὸν ἤδη τεθνηκότα οὐ κατέαξαν αὐτοῦ τὰ σκέλη',
   'epi de ton Iēsoun elthontes hōs eidon auton ēdē tethnēkota ou kateaxan autou ta skelē',
   '''They saw that he was dead already'' (eidon auton ēdē tethnēkota — they saw that he was already dead; perfect active participle: a dead man in a state of death). Professional executioners who have seen many deaths confirm that Jesus was dead. No crurifragium needed. The preservation of his bones is providentially secured by the soldiers'' own professional assessment. Scripture is fulfilled not by miraculous intervention but by the natural outworking of events under divine oversight.',
   NULL),
  (34, 'But one of the soldiers with a spear pierced his side, and forthwith came there out blood and water.',
   'ἀλλ᾽ εἷς τῶν στρατιωτῶν λόγχῃ αὐτοῦ τὴν πλευρὰν ἔνυξεν καὶ εὐθέως ἐξῆλθεν αἷμα καὶ ὕδωρ',
   'all heis tōn stratiōtōn lonchē autou tēn pleuran enuxen kai eutheōs exēlthen haima kai hydōr',
   '''Blood and water'' (haima kai hydōr — blood and water). The medical phenomenon: the separation of dark clots and clear serum from the pericardial sac or pleural cavity, a sign of death by cardiac failure or hemothorax. John emphasises this as an eyewitness testimony (v.35). Theologically, 1 John 5:6-8 uses the blood and water as testimony to the reality of the incarnation and death: ''This is he that came by water and blood.'' The Fathers also saw sacramental significance: the blood of the Eucharist and the water of baptism flowing from the pierced side of Christ.',
   NULL),
  (35, 'And he that saw it bare record, and his record is true: and he knoweth that he saith true, that ye might believe.',
   'καὶ ὁ ἑωρακὼς μεμαρτύρηκεν καὶ ἀληθινὴ αὐτοῦ ἐστιν ἡ μαρτυρία καὶ ἐκεῖνος οἶδεν ὅτι ἀληθῆ λέγει ἵνα καὶ ὑμεῖς πιστεύσητε',
   'kai ho heōrakōs memartyrēken kai alēthinē autou estin hē martyria kai ekeinos oiden hoti alēthē legei hina kai hymeis pisteusēte',
   '''He that saw it bare record'' (ho heōrakōs memartyrēken — the one who has seen has borne witness; both perfects: the seeing and the witnessing remain). The Beloved Disciple breaks through his own narrative anonymity to insist on his personal eyewitness testimony. ''His record is true'' (alēthinē autou estin hē martyria — his testimony is genuine). The repetition of ''true'' (alēthinē... alēthē) is emphatic: this is not pious legend but eyewitness fact. The historical reality of the death of Jesus is the foundation of the entire Christian gospel (1 Corinthians 15:3-4).',
   NULL),
  (36, 'For these things were done, that the scripture should be fulfilled, A bone of him shall not be broken.',
   'ἐγένετο γὰρ ταῦτα ἵνα ἡ γραφὴ πληρωθῇ Ὀστοῦν οὐ συντριβήσεται αὐτοῦ',
   'egeneto gar tauta hina hē graphē plērōthē Ostoun ou syntribēsetai autou',
   '''A bone of him shall not be broken'' — fulfilling Exodus 12:46 and Numbers 9:12 (''neither shall ye break a bone thereof'' — of the Passover lamb); also Psalm 34:20 (''He keepeth all his bones: not one of them is broken''). Jesus is the true Passover Lamb (1 Corinthians 5:7; John 1:29). The Passover instructions about the lamb''s bones, given to Moses 1,500 years earlier, are fulfilled precisely in the crucifixion of the Son of God.',
   NULL),
  (37, 'And again another scripture saith, They shall look on him whom they pierced.',
   'καὶ πάλιν ἑτέρα γραφὴ λέγει Ὄψονται εἰς ὃν ἐξεκέντησαν',
   'kai palin hetera graphē legei Opsontai eis hon exekentēsan',
   'Quoting Zechariah 12:10: ''They shall look upon me whom they have pierced, and they shall mourn for him.'' In Zechariah, it is Yahweh who is pierced. John quotes this of Jesus — another implicit identification of Jesus with Yahweh. The piercing is both historical (at the cross) and eschatological: Revelation 1:7 applies the same verse to the second coming: ''Behold, he cometh with clouds; and every eye shall see him, and they also which pierced him.'' The wound that proved his death also becomes the sign by which he will be recognised at his return.',
   NULL),
  (38, 'And after this Joseph of Arimathaea, being a disciple of Jesus, but secretly for fear of the Jews, besought Pilate that he might take away the body of Jesus: and Pilate gave him leave. He came therefore, and took the body of Jesus.',
   'Μετὰ δὲ ταῦτα ἠρώτησεν τὸν Πιλᾶτον Ἰωσὴφ ἀπὸ Ἁριμαθαίας ὢν μαθητὴς τοῦ Ἰησοῦ κεκρυμμένος δὲ διὰ τὸν φόβον τῶν Ἰουδαίων ἵνα ἄρῃ τὸ σῶμα τοῦ Ἰησοῦ καὶ ἐπέτρεψεν ὁ Πιλᾶτος ἦλθεν οὖν καὶ ἦρεν τὸ σῶμα αὐτοῦ',
   'Meta de tauta ērōtēsen ton Pilaton Iōsēph apo Harimathaias ōn mathētēs tou Iēsou kekrymenos de dia ton phobon tōn Ioudaiōn hina arē to sōma tou Iēsou kai epetrepsen ho Pilatos ēlthen oun kai ēren to sōma autou',
   '''Joseph of Arimathaea, being a disciple of Jesus, but secretly'' (ōn mathētēs tou Iēsou kekrymenos — being a disciple of Jesus having been hidden; perfect participle: a secret disciple up to this point). The cross brings out what life concealed: Joseph''s secret faith becomes public courage at the moment of greatest danger. He goes to Pilate — a senior member of the Sanhedrin voluntarily identifying himself as a disciple of the executed man. This is bold. Isaiah 53:9: ''And he made his grave... with the rich in his death'' — Joseph was a wealthy man who provided the tomb.',
   NULL),
  (39, 'And there came also Nicodemus, which at the first came to Jesus by night, and brought a mixture of myrrh and aloes, about an hundred pound weight.',
   'ἦλθεν δὲ καὶ Νικόδημος ὁ ἐλθὼν πρὸς τὸν Ἰησοῦν νυκτὸς τὸ πρῶτον φέρων μίγμα σμύρνης καὶ ἀλόης ὡσεὶ λίτρας ἑκατόν',
   'ēlthen de kai Nikodēmos ho elthōn pros ton Iēsoun nyktos to prōton pherōn migma smyrnēs kai aloēs hōsei litras hekaton',
   '''Nicodemus, which at the first came to Jesus by night'' (ho elthōn pros ton Iēsoun nyktos to prōton — the one who had come to Jesus at night, at the first; cf. 3:1-2; 7:50-51). The arc of Nicodemus: from secret nighttime enquiry (ch.3) to cautious procedural defence (7:51) to public, costly burial service. ''About an hundred pound weight'' (hōsei litras hekaton — about 100 Roman pounds, approximately 33 kg/75 lbs of spices). A royal quantity — kings were buried with enormous amounts of fragrant spices (cf. 2 Chronicles 16:14). Nicodemus anoints Jesus as a king in burial, unwittingly confirming Pilate''s title on the cross.',
   NULL),
  (40, 'Then took they the body of Jesus, and wound it in linen clothes with the spices, as the manner of the Jews is to bury.',
   'ἔλαβον οὖν τὸ σῶμα τοῦ Ἰησοῦ καὶ ἔδησαν αὐτὸ ὀθονίοις μετὰ τῶν ἀρωμάτων καθὼς ἔθος ἐστὶν τοῖς Ἰουδαίοις ἐνταφιάζειν',
   'elabon oun to sōma tou Iēsou kai edēsan auto othoniois meta tōn arōmatōn kathōs ethos estin tois Ioudaiois entaphiazein',
   '''Wound it in linen clothes'' (edēsan auto othoniois — they bound it in linen strips; othonion: a linen strip, bandage). Jewish burial practice involved wrapping the body in linen with spices placed in the wrappings. The Shroud of Turin is a linen cloth claimed to be the burial cloth of Jesus. Whatever one''s view of the relic, the burial was real, physical, and careful — these details emphasise the reality of the death. The same linen wrappings will be found in the tomb on resurrection morning (20:5-7).',
   NULL),
  (41, 'Now in the place where he was crucified there was a garden; and in the garden a new sepulchre, wherein was never man yet laid.',
   'ἦν δὲ ἐν τῷ τόπῳ ὅπου ἐσταυρώθη κῆπος καὶ ἐν τῷ κήπῳ μνημεῖον καινόν ἐν ᾧ οὐδέπω οὐδεὶς ἐτέθη',
   'ēn de en tō topō hopou estaurōthē kēpos kai en tō kēpō mnēmeion kainon en hō oudepō oudeis etethē',
   '''A garden'' (kēpos — a garden). John uniquely calls the area around Golgotha a garden — the same word used for the garden of the arrest (18:1) and of the resurrection (20:15). The death occurs in a garden; the resurrection will occur in a garden — echoing Eden: in the garden, death entered through sin; in the garden, life returns through the sacrifice of the sinless one. ''A new sepulchre, wherein was never man yet laid'' (mnēmeion kainon en hō oudepō oudeis etethē — a new tomb in which no one had yet been placed). The unused tomb is significant: Jesus would be the first and last occupant — no confusion possible about whether the resurrection appearances were someone else.',
   NULL),
  (42, 'There laid they Jesus therefore because of the Jews'' preparation day; for the sepulchre was nigh at hand.',
   'ἐκεῖ οὖν διὰ τὴν παρασκευὴν τῶν Ἰουδαίων ὅτι ἐγγὺς ἦν τὸ μνημεῖον ἔθηκαν τὸν Ἰησοῦν',
   'ekei oun dia tēn paraskeuēn tōn Ioudaiōn hoti engys ēn to mnēmeion ethēkan ton Iēsoun',
   '''There laid they Jesus'' (ethēkan ton Iēsoun — they laid Jesus there). The body of the Lord is placed in the tomb as evening approaches, the Sabbath begins, and all is still. The Gospel of John''s narrative of the life, death, and ministry of the Son of God comes to its apparent end in a garden tomb on the eve of the Jewish Sabbath. What seems like the end of the story is the beginning of the new creation. As God rested on the seventh day after the first creation (Genesis 2:2-3), the Son of God rests in the tomb on the Sabbath before the resurrection morning — the first day of the new creation.',
   NULL)
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'John' AND c.chapter_number = 19;

-- JOHN CHAPTER 19 — BACKFILL (word_studies + cross_references)

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'ἐμαστίγωσεν', 'emastigōsen', 'G3146', 'Scourged (aorist) — Roman flagellation with the flagrum, lead-tipped leather thongs; intended to bring near death.', 1),
  (2, 'στέφανον ἐξ ἀκανθῶν', 'stephanon ex akanthōn', 'G4735/G173', 'Crown of thorns — mockery of royal diadem; thorns first appear in Gen 3:18 as fruit of the curse Christ now bears.', 2),
  (2, 'ἱμάτιον πορφυροῦν', 'himation porphyroun', 'G2440/G4210', 'Purple robe — color of royalty; the soldiers'' mockery becomes unconscious testimony.', 3),
  (5, 'ἰδοὺ ὁ ἄνθρωπος', 'idou ho anthrōpos', 'G2400/G444', '"Behold the Man" — Latin Ecce Homo; Pilate''s words echo Zech 6:12 ("behold the man whose name is the Branch").', 4),
  (6, 'σταύρωσον', 'staurōson', 'G4717', 'Crucify (aorist imperative) — repeated cry; the most shameful death (Deut 21:23; Gal 3:13).', 5),
  (7, 'υἱὸν θεοῦ', 'huion theou', 'G5207/G2316', 'Son of God — the Jewish charge under Lev 24:16; from his own lips testified deity.', 6),
  (9, 'πόθεν εἶ σύ', 'pothen ei sy', 'G4159/G1510', '"Where are you from?" — Pilate now asks the Johannine question (cf. 7:27-28; 8:14); Jesus is silent (Isa 53:7).', 7),
  (11, 'ἐξουσίαν', 'exousian', 'G1849', 'Authority — Pilate''s authority is derivative, given "from above" (anōthen); divine providence governs even pagan power.', 8),
  (11, 'μείζονα ἁμαρτίαν', 'meizona hamartian', 'G3187/G266', 'Greater sin — degrees of culpability; Caiaphas with greater knowledge bears greater guilt.', 9),
  (12, 'φίλος Καίσαρος', 'philos Kaisaros', 'G5384/G2541', 'Friend of Caesar — formal title (amicus Caesaris); political threat that breaks Pilate''s resistance.', 10),
  (13, 'Λιθόστρωτον', 'Lithostrōton', 'G3038', 'Stone Pavement — paved tribunal area; possibly the Antonia fortress courtyard.', 11),
  (13, 'Γαββαθᾶ', 'Gabbatha', 'G1042', 'Gabbatha — Aramaic for "raised place"; the elevated judgment seat.', 12),
  (14, 'παρασκευὴ', 'paraskeuē', 'G3904', 'Preparation Day — Friday before Sabbath; here Preparation of Passover.', 13),
  (14, 'ὥρα ἕκτη', 'hōra hektē', 'G5610/G1623', 'Sixth hour — John''s Roman reckoning (early morning) vs Mark''s Jewish (noon); time of trial.', 14),
  (14, 'ὁ βασιλεὺς ὑμῶν', 'ho basileus hymōn', 'G935', '"Your King" — Pilate ironically presents Jesus as Israel''s king; theological truth in mocking lips.', 15),
  (15, 'οὐκ ἔχομεν βασιλέα εἰ μὴ Καίσαρα', 'ouk echomen basilea ei mē Kaisara', 'G3756/G2192/G935/G2541', '"We have no king but Caesar" — at Passover (commemorating freedom from Egypt) the priests renounce Yahweh''s kingship.', 16),
  (16, 'παρέδωκεν', 'paredōken', 'G3860', 'Handed over — the verb of betrayal; Pilate hands him over to be crucified, completing the chain of paradosis.', 17),
  (17, 'βαστάζων ἑαυτῷ τὸν σταυρὸν', 'bastazōn heautō ton stauron', 'G941/G4716', 'Bearing his own cross — the patibulum (crossbeam); Isaac typology (Gen 22:6).', 18),
  (17, 'Κρανίου Τόπον', 'Kraniou Topon', 'G2898/G5117', 'Place of a Skull — Calvary (Latin); Aramaic Golgotha; possibly skull-shaped rock.', 19),
  (17, 'Γολγοθᾶ', 'Golgotha', 'G1115', 'Golgotha — from Aramaic gulgolta; the execution site outside the city wall (Heb 13:12).', 20),
  (18, 'ἐσταύρωσαν', 'estaurōsan', 'G4717', 'They crucified — the bare verb; John refuses to dramatize the brutality.', 21),
  (19, 'τίτλον', 'titlon', 'G5102', 'Titulus — placard stating the crime; Latin loan-word.', 22),
  (20, 'Ἑβραϊστί Ῥωμαϊστί Ἑλληνιστί', 'Hebraisti Rhōmaisti Hellēnisti', 'G1447/G4515/G1676', 'In Hebrew, Latin, Greek — three universal languages: religion, law, culture; the universal claim of Christ.', 23),
  (23, 'χιτὼν ἄρραφος', 'chitōn arraphos', 'G5509/G729', 'Seamless tunic — woven from top in one piece; high priest''s ephod was similarly woven (Exod 28:32; Josephus).', 24),
  (24, 'διεμερίσαντο τὰ ἱμάτιά μου', 'diemerisanto ta himatia mou', 'G1266/G2440', 'They divided my garments — direct quotation of Ps 22:18 LXX; lot-casting fulfills detail.', 25),
  (25, 'παρὰ τῷ σταυρῷ', 'para tō staurō', 'G3844/G4716', 'By the cross — Mary stands; Stabat Mater; the sword of Simeon''s prophecy (Luke 2:35) now pierces.', 26),
  (26, 'ἰδοὺ ὁ υἱός σου', 'idou ho huios sou', 'G2400/G5207', '"Behold your son" — Jesus entrusts Mary to the beloved disciple, fulfilling fifth commandment from the cross.', 27),
  (28, 'διψῶ', 'dipsō', 'G1372', '"I thirst" — fulfilling Ps 22:15; 69:21; the Living Water (4:10) thirsts for our salvation.', 28),
  (29, 'ὑσσώπῳ', 'hyssōpō', 'G5301', 'Hyssop — same plant used to apply Passover blood (Exod 12:22); deliberate Paschal symbolism.', 29),
  (29, 'ὄξους', 'oxous', 'G3690', 'Sour wine — posca, the soldier''s drink; not the drugged wine he refused earlier (Mark 15:23).', 30),
  (30, 'τετέλεσται', 'tetelestai', 'G5055', '"It is finished" — perfect passive; complete and abiding completion. Found on Greco-Roman receipts: "paid in full".', 31),
  (30, 'παρέδωκεν τὸ πνεῦμα', 'paredōken to pneuma', 'G3860/G4151', 'Yielded up the spirit — voluntarily gave up; Jesus dies as he lived, in sovereign control (10:18).', 32),
  (31, 'σκέλη', 'skelē', 'G4628', 'Legs — crurifragium broke legs to hasten death by suffocation; Jesus already dead, so spared.', 33),
  (33, 'οὐ κατέαξαν', 'ou kateaxan', 'G3756/G2608', 'They did not break — fulfills Exod 12:46 (Passover lamb); Ps 34:20 (righteous sufferer).', 34),
  (34, 'λόγχῃ', 'lonchē', 'G3057', 'Spear/lance — soldier''s pilum; pierced side certifies death.', 35),
  (34, 'ἔνυξεν', 'enyxen', 'G3572', 'Pierced — same verb in LXX Zech 12:10 ("they shall look on me whom they pierced").', 36),
  (34, 'αἷμα καὶ ὕδωρ', 'haima kai hydōr', 'G129/G5204', 'Blood and water — physical proof of death (pericardial fluid); theological symbol of atonement and cleansing (1 John 5:6-8).', 37),
  (35, 'μεμαρτύρηκεν', 'memartyrēken', 'G3140', 'Has borne witness (perfect) — eyewitness testimony certified; the basis of belief.', 38),
  (37, 'ὄψονται εἰς ὃν ἐξεκέντησαν', 'opsontai eis hon exekentēsan', 'G3700/G1574', '"They shall look on him whom they pierced" — Zech 12:10; eschatological recognition (Rev 1:7).', 39),
  (38, 'κρυπτὸς δὲ διὰ τὸν φόβον', 'kryptos de dia ton phobon', 'G2928/G5401', 'Secret because of fear — Joseph of Arimathea''s hidden discipleship now openly declared at the cross.', 40),
  (39, 'σμύρνης καὶ ἀλόης', 'smyrnēs kai aloēs', 'G4666/G250', 'Myrrh and aloes — burial spices; Nicodemus brings ~75 lbs, a king''s burial.', 41),
  (40, 'ὀθονίοις', 'othoniois', 'G3608', 'Linen wrappings — strips of fine linen; same word recurs at the empty tomb (20:5-7).', 42),
  (41, 'κῆπος', 'kēpos', 'G2779', 'Garden — death and resurrection in a garden, reversing Eden; same word as 18:1 and 20:15.', 43),
  (41, 'μνημεῖον καινὸν', 'mnēmeion kainon', 'G3419/G2537', 'New tomb — kainos (qualitatively new); never used; no possible body-confusion.', 44)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'John' AND c.chapter_number = 19 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Isaiah 50:6', 1),
  (1, 'Isaiah 53:5', 2),
  (1, 'Matthew 27:26', 3),
  (1, 'Mark 15:15', 4),
  (1, '1 Peter 2:24', 5),
  (2, 'Genesis 3:18', 1),
  (2, 'Matthew 27:29', 2),
  (2, 'Mark 15:17', 3),
  (2, 'Hebrews 2:9', 4),
  (3, 'Isaiah 50:6', 1),
  (3, 'Micah 5:1', 2),
  (3, 'Matthew 27:30', 3),
  (4, 'Luke 23:4', 1),
  (4, 'Luke 23:14-15', 2),
  (4, '1 Peter 2:22', 3),
  (5, 'Zechariah 6:12', 1),
  (5, 'Isaiah 53:2-3', 2),
  (5, 'Philippians 2:7-8', 3),
  (6, 'Acts 3:13-15', 1),
  (6, 'Matthew 27:23', 2),
  (6, 'Luke 23:21', 3),
  (7, 'Leviticus 24:16', 1),
  (7, 'John 5:18', 2),
  (7, 'John 10:33', 3),
  (7, 'Matthew 26:63-66', 4),
  (9, 'Isaiah 53:7', 1),
  (9, 'Matthew 27:12-14', 2),
  (9, '1 Peter 2:23', 3),
  (10, 'Daniel 3:14-15', 1),
  (11, 'John 3:27', 1),
  (11, 'Romans 13:1', 2),
  (11, 'Daniel 4:25', 3),
  (11, 'Acts 2:23', 4),
  (11, 'Acts 4:27-28', 5),
  (12, 'Luke 23:2', 1),
  (12, 'Acts 17:7', 2),
  (13, 'Matthew 27:19', 1),
  (14, 'Matthew 27:62', 1),
  (14, 'John 19:42', 2),
  (14, '1 Corinthians 5:7', 3),
  (15, '1 Samuel 8:7', 1),
  (15, 'Hosea 13:10-11', 2),
  (15, 'Genesis 49:10', 3),
  (16, 'Matthew 27:26', 1),
  (16, 'Mark 15:15', 2),
  (16, 'Luke 23:25', 3),
  (16, 'Isaiah 53:6', 4),
  (17, 'Genesis 22:6', 1),
  (17, 'Hebrews 13:12-13', 2),
  (17, 'Matthew 27:33', 3),
  (17, 'Luke 23:33', 4),
  (18, 'Isaiah 53:12', 1),
  (18, 'Luke 23:33', 2),
  (18, 'Matthew 27:38', 3),
  (19, 'Matthew 27:37', 1),
  (19, 'Mark 15:26', 2),
  (19, 'Luke 23:38', 3),
  (20, 'Luke 23:38', 1),
  (20, 'Hebrews 13:12', 2),
  (23, 'Exodus 28:31-32', 1),
  (23, 'Psalm 22:18', 2),
  (24, 'Psalm 22:18', 1),
  (24, 'Matthew 27:35', 2),
  (25, 'Matthew 27:55-56', 1),
  (25, 'Mark 15:40-41', 2),
  (25, 'Luke 2:35', 3),
  (25, 'Luke 23:49', 4),
  (26, 'John 13:23', 1),
  (26, 'John 20:2', 2),
  (26, 'Exodus 20:12', 3),
  (27, '1 Timothy 5:4', 1),
  (28, 'Psalm 22:15', 1),
  (28, 'Psalm 69:21', 2),
  (28, 'John 4:10', 3),
  (28, 'John 7:37-38', 4),
  (29, 'Exodus 12:22', 1),
  (29, 'Numbers 19:6', 2),
  (29, 'Psalm 69:21', 3),
  (29, 'Hebrews 9:19', 4),
  (30, 'John 4:34', 1),
  (30, 'John 17:4', 2),
  (30, 'Luke 23:46', 3),
  (30, 'Hebrews 10:12-14', 4),
  (30, 'Hebrews 9:12', 5),
  (30, 'Colossians 2:14', 6),
  (31, 'Deuteronomy 21:22-23', 1),
  (31, 'Joshua 8:29', 2),
  (33, 'Exodus 12:46', 1),
  (33, 'Numbers 9:12', 2),
  (33, 'Psalm 34:20', 3),
  (33, '1 Corinthians 5:7', 4),
  (34, 'Zechariah 12:10', 1),
  (34, '1 John 5:6-8', 2),
  (34, 'Hebrews 9:22', 3),
  (34, '1 Peter 1:2', 4),
  (34, 'Revelation 1:7', 5),
  (35, 'John 21:24', 1),
  (35, '1 John 1:1-3', 2),
  (35, '1 John 5:6-8', 3),
  (36, 'Exodus 12:46', 1),
  (36, 'Numbers 9:12', 2),
  (36, 'Psalm 34:20', 3),
  (37, 'Zechariah 12:10', 1),
  (37, 'Revelation 1:7', 2),
  (37, 'Matthew 24:30', 3),
  (38, 'Matthew 27:57-60', 1),
  (38, 'Mark 15:42-46', 2),
  (38, 'Luke 23:50-53', 3),
  (38, 'Isaiah 53:9', 4),
  (39, 'John 3:1-2', 1),
  (39, 'John 7:50-52', 2),
  (39, '2 Chronicles 16:14', 3),
  (40, 'John 11:44', 1),
  (40, 'Luke 24:12', 2),
  (41, 'Genesis 2:8-9', 1),
  (41, 'John 18:1', 2),
  (41, 'John 20:15', 3),
  (42, 'Isaiah 53:9', 1),
  (42, 'Luke 23:54', 2)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'John' AND c.chapter_number = 19 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
