-- ═══════════════════════════════════════════════════
-- JOHN CHAPTER 18 — The Arrest, Peter's Denial, and Trial Before Pilate
-- 40 verses · Greek text · Word studies · Cross-refs
-- ═══════════════════════════════════════════════════

-- Step 1: Insert chapter metadata
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 18,
  'John 18 opens the Passion narrative proper. After the High Priestly Prayer (ch.17), Jesus and the disciples cross the Kidron Valley to a garden (Gethsemane, named only in the Synoptics). There Judas comes with a cohort of Roman soldiers and Jewish officers to arrest him. Jesus steps forward — ''I am he'' (egō eimi) — and the soldiers ''went backward, and fell to the ground'' (v.6), a display of sovereign power that proves Jesus is not a victim but a willing sacrifice. He negotiates the release of the disciples (''that the saying might be fulfilled... of them which thou gavest me have I lost none,'' vv.8-9). Peter draws his sword and cuts off Malchus''s ear; Jesus rebukes him (vv.10-11). Jesus is led first to Annas (the former high priest and father-in-law of Caiaphas, vv.12-14), then to Caiaphas (mentioned briefly, v.24), then to the Roman Praetorium and Pilate (vv.28-40). John''s account of the Jewish trial is abbreviated; his account of the Roman trial is the most detailed in any Gospel. Peter''s three denials are interwoven with the Jewish trial (vv.15-18, 25-27) — three questions, three denials, one crowing cock, just as Jesus predicted. Before Pilate, the great exchange on the nature of kingship and truth takes place: ''My kingdom is not of this world'' (v.36); ''To this end was I born, and for this cause came I into the world, that I should bear witness unto the truth'' (v.37); ''What is truth?'' (v.38). Pilate finds no fault in him but offers Barabbas and Jesus to the crowd — the crowd chooses Barabbas (v.40).',
  'The Sovereign Prisoner — Jesus in Control of His Own Arrest and Trial',
  'βασιλεία (basileia)',
  'Kingdom, reign, royal dominion — from basileus (king). The central theme of the Pilate trial (vv.33-38) is the nature of Jesus''s kingdom. ''Art thou the King of the Jews?'' (v.33); ''My kingdom is not of this world'' (v.36); ''Thou sayest that I am a king'' (v.37). John''s Passion narrative is pervasively royal: Jesus enters Jerusalem as king (12:13-15), is arrested like a sovereign granting terms (vv.4-9), is mocked with a crown of thorns and a purple robe (19:2-3), is crucified with the title ''The King of the Jews'' (19:19-22), and reigns from the cross. The paradox of the Gospel is that the ''King of kings'' is crucified — and in the crucifixion reveals the nature of his kingdom: not coercive power but self-giving truth and love.',
  '["The Arrest in the Garden (vv.1-11): When Jesus had spoken these words he went forth with his disciples over the brook Cedron where was a garden into the which he entered and his disciples. And Judas also which betrayed him knew the place for Jesus ofttimes resorted thither with his disciples. Judas then having received a band of men and officers from the chief priests and Pharisees cometh thither with lanterns and torches and weapons. Jesus therefore knowing all things that should come upon him went forth and said unto them Whom seek ye? They answered him Jesus of Nazareth. Jesus saith unto them I am he and Judas also which betrayed him stood with them. As soon then as he had said unto them I am he they went backward and fell to the ground. Then asked he them again Whom seek ye? and they said Jesus of Nazareth. Jesus answered I have told you that I am he if therefore ye seek me let these go their way. That the saying might be fulfilled which he spake Of them which thou gavest me have I lost none. Then Simon Peter having a sword drew it and smote the high priest''s servant and cut off his right ear. The servant''s name was Malchus. Then said Jesus unto Peter Put up thy sword into the sheath the cup which my Father hath given me shall I not drink it?","Before Annas and Peter''s Denial (vv.12-27): Then the band and the captain and officers of the Jews took Jesus and bound him and led him away to Annas first for he was father in law to Caiaphas which was the high priest that same year. Now Caiaphas was he which gave counsel to the Jews that it was expedient that one man should die for the people. And Simon Peter followed Jesus and so did another disciple that disciple was known unto the high priest and went in with Jesus into the palace of the high priest. But Peter stood at the door without. Then went out that other disciple which was known unto the high priest and spake unto her that kept the door and brought in Peter. Then saith the damsel that kept the door unto Peter Art not thou also one of this man''s disciples? He saith I am not. And the servants and officers stood there who had made a fire of coals for it was cold and they warmed themselves and Peter stood with them and warmed himself. The high priest then asked Jesus of his disciples and of his doctrine. Jesus answered him I spake openly to the world I ever taught in the synagogue and in the temple whither the Jews always resort and in secret have I said nothing. Why askest thou me? ask them which heard me what I have said unto them behold they know what I said. And when he had thus spoken one of the officers which stood by struck Jesus with the palm of his hand saying Answerest thou the high priest so? Jesus answered him If I have spoken evil bear witness of the evil but if well why smitest thou me? Now Annas had sent him bound unto Caiaphas the high priest. And Simon Peter stood and warmed himself. They said therefore unto him Art not thou also one of his disciples? He denied it and said I am not. One of the servants of the high priest being his kinsman whose ear Peter cut off saith Did not I see thee in the garden with him? Peter then denied again and immediately the cock crew","The Trial Before Pilate (vv.28-40): Then led they Jesus from Caiaphas unto the hall of judgment and it was early and they themselves went not into the judgment hall lest they should be defiled but that they might eat the passover. Pilate then went out unto them and said What accusation bring ye against this man? They answered and said unto him If he were not a malefactor we would not have delivered him up unto thee. Then said Pilate unto them Take ye him and judge him according to your law. The Jews therefore said unto him It is not lawful for us to put any man to death that the saying of Jesus might be fulfilled which he spake signifying what death he should die. Then Pilate entered into the judgment hall again and called Jesus and said unto him Art thou the King of the Jews? Jesus answered him Sayest thou this thing of thyself or did others tell it thee of me? Pilate answered Am I a Jew? Thine own nation and the chief priests have delivered thee unto me what hast thou done? Jesus answered My kingdom is not of this world if my kingdom were of this world then would my servants fight that I should not be delivered to the Jews but now is my kingdom not from hence. Pilate therefore said unto him Art thou a king then? Jesus answered Thou sayest that I am a king. To this end was I born and for this cause came I into the world that I should bear witness unto the truth. Every one that is of the truth heareth my voice. Pilate saith unto him What is truth? And when he had said this he went out again unto the Jews and saith unto them I find in him no fault at all. But ye have a custom that I should release unto you one at the passover will ye therefore that I release unto you the King of the Jews? Then cried they all again saying Not this man but Barabbas. Now Barabbas was a robber"]'
FROM books b WHERE b.name = 'John';

-- Step 2: Insert all 40 verses
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'When Jesus had spoken these words, he went forth with his disciples over the brook Cedron, where was a garden, into the which he entered, and his disciples.',
   'Ταῦτα εἰπὼν Ἰησοῦς ἐξῆλθεν σὺν τοῖς μαθηταῖς αὐτοῦ πέραν τοῦ χειμάρρου τῶν Κέδρων ὅπου ἦν κῆπος εἰς ὃν εἰσῆλθεν αὐτὸς καὶ οἱ μαθηταὶ αὐτοῦ',
   'Tauta eipōn Iēsous exēlthen syn tois mathētais autou peran tou cheimarrou tōn Kedrōn hopou ēn kēpos eis hon eisēlthen autos kai hoi mathētai autou',
   '''The brook Cedron'' (tou cheimarrou tōn Kedrōn — the winter torrent of Cedron; cheimarrous: a seasonal stream, a wadi). The Kidron Valley runs between Jerusalem and the Mount of Olives. In spring, the brook flows with rainwater; in summer, it is dry. Jesus crosses from the city to the eastern garden — symbolically significant: David fled across the Kidron when Absalom conspired against him (2 Samuel 15:23). The Second David crosses the Kidron before his greater betrayal. ''A garden'' (kēpos) — John uniquely uses this word for Gethsemane (the Synoptics say ''a place''), and will use it again for the tomb and resurrection garden (19:41; 20:15). The garden recalls Eden: the first Adam sinned in a garden; the second Adam conquers in a garden.',
   NULL),
  (2, 'And Judas also, which betrayed him, knew the place: for Jesus ofttimes resorted thither with his disciples.',
   'ᾔδει δὲ καὶ Ἰούδας ὁ παραδιδοὺς αὐτὸν τὸν τόπον ὅτι πολλάκις συνήχθη Ἰησοῦς ἐκεῖ μετὰ τῶν μαθητῶν αὐτοῦ',
   'ēdei de kai Ioudas ho paradidous auton ton topon hoti pollakis synēchthē Iēsous ekei meta tōn mathētōn autou',
   '''Jesus ofttimes resorted thither'' (pollakis synēchthē Iēsous ekei — Jesus often assembled/gathered there). Gethsemane was a regular meeting place — Jesus did not choose an obscure spot but his habitual retreat, known to all. There is nothing secretive about his movements; he is not hiding. Judas''s knowledge of the location means Jesus could not have evaded him if he chose. He did not choose to evade — he went to his accustomed place and waited.',
   NULL),
  (3, 'Judas then, having received a band of men and officers from the chief priests and Pharisees, cometh thither with lanterns and torches and weapons.',
   'ὁ οὖν Ἰούδας λαβὼν τὴν σπεῖραν καὶ ἐκ τῶν ἀρχιερέων καὶ ἐκ τῶν Φαρισαίων ὑπηρέτας ἔρχεται ἐκεῖ μετὰ φανῶν καὶ λαμπάδων καὶ ὅπλων',
   'ho oun Ioudas labōn tēn speiran kai ek tōn archiereon kai ek tōn Pharisaiōn hypēretas erchetai ekei meta phanōn kai lampadōn kai hoplōn',
   '''A band of men'' (tēn speiran — the cohort; a Roman military unit of 600 men, though sometimes as few as 200; a significant detachment). The word ''speiran'' (Latin: cohors) is a Roman military term — Roman soldiers accompanied by Jewish temple officers (hypēretas). The size of the force reflects the authorities'' expectation of resistance — Jesus has a following among the common people and has recently disrupted the Temple commerce. ''Lanterns and torches'' (phanōn kai lampadōn) — it was spring (Passover, full moon), but they bring artificial light, perhaps to search in shadows. Ironically, they come with lights to arrest the Light of the World.',
   NULL),
  (4, 'Jesus therefore, knowing all things that should come upon him, went forth, and said unto them, Whom seek ye?',
   'Ἰησοῦς οὖν εἰδὼς πάντα τὰ ἐρχόμενα ἐπ᾽ αὐτόν ἐξῆλθεν καὶ λέγει αὐτοῖς Τίνα ζητεῖτε',
   'Iēsous oun eidōs panta ta erchomena ep auton exēlthen kai legei autois Tina zēteite',
   '''Knowing all things that should come upon him, went forth'' (eidōs panta ta erchomena ep auton, exēlthen — knowing all things coming upon him, he went out). Jesus is not surprised; he is in control. He steps forward — not backward, not hiding — to meet the arresting party. This is the posture of a sovereign, not a victim. The question ''Whom seek ye?'' (Tina zēteite — whom are you seeking?) echoes the first question Jesus asks in this Gospel (1:38: ''What seek ye?''). The entire Gospel is framed by this question of seeking.',
   NULL),
  (5, 'They answered him, Jesus of Nazareth. Jesus saith unto them, I am he. And Judas also, which betrayed him, stood with them.',
   'ἀπεκρίθησαν αὐτῷ Ἰησοῦν τὸν Ναζωραῖον λέγει αὐτοῖς Ἰησοῦς Ἐγώ εἰμι καὶ εἱστήκει καὶ Ἰούδας ὁ παραδιδοὺς αὐτὸν μετ᾽ αὐτῶν',
   'apekrithēsan autō Iēsoun ton Nazōraion legei autois Iēsous Egō eimi kai heistēkei kai Ioudas ho paradidous auton met autōn',
   '''I am he'' (Egō eimi — I AM; the Greek has no ''he''; it is the absolute ''I AM'' of divine self-disclosure). This is John''s most dramatic use of egō eimi. In the garden of darkness and arrest, Jesus speaks the divine name — the same words by which God identified himself to Moses (Exodus 3:14). The effect in v.6 is immediate and supernatural. ''And Judas also, which betrayed him, stood with them'' (heistēkei kai Ioudas — Judas also stood; imperfect: was standing there). John places Judas on the opposite side — with them, not with Jesus.',
   NULL),
  (6, 'As soon then as he had said unto them, I am he, they went backward, and fell to the ground.',
   'ὡς οὖν εἶπεν αὐτοῖς ὅτι Ἐγώ εἰμι ἀπῆλθον εἰς τὰ ὀπίσω καὶ ἔπεσον χαμαί',
   'hōs oun eipen autois hoti Egō eimi apēlthon eis ta opisō kai epesan chamai',
   '''They went backward, and fell to the ground'' (apēlthon eis ta opisō kai epesan chamai — they went back and fell to the ground). Six hundred armed soldiers are knocked off their feet by two words. This is a demonstration of divine power — the same power that will raise Jesus from the dead. Jesus allows himself to be arrested only because he chooses to. He is not overcome by superior force; he voluntarily gives himself. ''That no man could bind him'' (cf. Psalm 78:65; the language of supernatural restraint) — yet he goes willingly. The cross is not defeat; it is sovereign choice.',
   NULL),
  (7, 'Then asked he them again, Whom seek ye? And they said, Jesus of Nazareth.',
   'πάλιν οὖν ἐπηρώτησεν αὐτούς Τίνα ζητεῖτε οἱ δὲ εἶπον Ἰησοῦν τὸν Ναζωραῖον',
   'palin oun epērōtēsen autous Tina zēteite hoi de eipon Iēsoun ton Nazōraion',
   'After the display of power, Jesus asks the same question again — giving the soldiers a second chance, allowing them to regroup and answer deliberately. He is in no hurry; he controls the pace of events. The repetition of ''Jesus of Nazareth'' is their identification — and Jesus will satisfy it precisely, while securing the freedom of his disciples.',
   NULL),
  (8, 'Jesus answered, I have told you that I am he: if therefore ye seek me, let these go their way:',
   'ἀπεκρίθη Ἰησοῦς Εἶπον ὑμῖν ὅτι ἐγώ εἰμι εἰ οὖν ἐμὲ ζητεῖτε ἄφετε τούτους ὑπάγειν',
   'apekrithē Iēsous Eipon hymin hoti egō eimi ei oun eme zēteite aphete toutous hypagein',
   '''Let these go their way'' (aphete toutous hypagein — let these go; release these). Jesus negotiates the release of the disciples as a condition of his surrender. The Good Shepherd gives himself for the sheep (10:11). He does not merely allow them to flee — he actively secures their departure. This is shepherd-love in action: interposing himself between the wolf and the flock.',
   NULL),
  (9, 'That the saying might be fulfilled, which he spake, Of them which thou gavest me have I lost none.',
   'ἵνα πληρωθῇ ὁ λόγος ὃν εἶπεν ὅτι Οὓς δέδωκάς μοι οὐκ ἀπώλεσα ἐξ αὐτῶν οὐδένα',
   'hina plērōthē ho logos hon eipen hoti Hous dedōkas moi ouk apōlesa ex autōn oudena',
   'John uniquely applies the fulfilment of 17:12 (''none of them is lost'') to the physical deliverance of the disciples in Gethsemane. The words about spiritual keeping (17:12) are here extended to physical protection. The divine word that promised preservation of those given to the Son is fulfilled at every level: spiritual, physical, and eschatological. Jesus''s word does not fail.',
   NULL),
  (10, 'Then Simon Peter having a sword drew it, and smote the high priest''s servant, and cut off his right ear. The servant''s name was Malchus.',
   'Σίμων οὖν Πέτρος ἔχων μάχαιραν εἵλκυσεν αὐτὴν καὶ ἔπαισεν τὸν τοῦ ἀρχιερέως δοῦλον καὶ ἀπέκοψεν αὐτοῦ τὸ ὠτάριον τὸ δεξιόν ἦν δὲ ὄνομα τῷ δούλῳ Μάλχος',
   'Simōn oun Petros echōn machairan heilkysen autēn kai epaisen ton tou archiereon doulon kai apekopsen autou to ōtarion to dexion ēn de onoma tō doulō Malchos',
   '''Simon Peter having a sword'' (echōn machairan — having a dagger/sword; machaira: a short sword). Peter acts with characteristic impulsive courage — he had promised to die for Jesus (13:37) and now attempts to start the fight. ''Malchus'' — only John names the servant. Luke 22:51 records that Jesus healed the ear immediately. The servant''s name may have been known to John''s community through subsequent conversion (cf. Romans 16:11 mentions a Narcissus household). The injury is to the ''right ear'' (to dexion) — a specific detail of an eyewitness.',
   NULL),
  (11, 'Then said Jesus unto Peter, Put up thy sword into the sheath: the cup which my Father hath given me, shall I not drink it?',
   'εἶπεν οὖν ὁ Ἰησοῦς τῷ Πέτρῳ Βάλε τὴν μάχαιραν εἰς τὴν θήκην τὸ ποτήριον ὃ δέδωκέν μοι ὁ πατήρ οὐ μὴ πίω αὐτό',
   'eipen oun ho Iēsous tō Petrō Bale tēn machairan eis tēn thēkēn to potērion ho dedōken moi ho patēr ou mē piō auto',
   '''The cup which my Father hath given me, shall I not drink it?'' (to potērion ho dedōken moi ho patēr, ou mē piō auto?) — the cup of suffering (cf. Matthew 26:39: ''let this cup pass from me''). The Gethsemane prayer (not recorded in John) is resolved; the cup is accepted. ''Shall I not drink it?'' (ou mē piō auto — shall I certainly not drink it? — emphatic double negative: I will certainly drink it). The arrest is the beginning of drinking the cup. Peter''s sword would have replaced the cup with a violent rescue — which is not God''s plan. The Kingdom does not advance by human violence.',
   NULL),
  (12, 'Then the band and the captain and officers of the Jews took Jesus, and bound him,',
   'Ἡ οὖν σπεῖρα καὶ ὁ χιλίαρχος καὶ οἱ ὑπηρέται τῶν Ἰουδαίων συνέλαβον τὸν Ἰησοῦν καὶ ἔδησαν αὐτόν',
   'Hē oun speira kai ho chiliarchos kai hoi hypēretai tōn Ioudaiōn synelabon ton Iēsoun kai edēsan auton',
   '''The band and the captain'' (hē speira kai ho chiliarchos — the cohort and the commander of a thousand; chiliarchos: military tribune). Roman military authority is combined with Jewish religious authority in the arrest — the two powers that will be united in the execution. ''Bound him'' (edēsan auton — they bound him). The binding of the Son of God — he who could have called twelve legions of angels (Matthew 26:53) — is the most astonishing condescension. ''He came unto his own, and his own received him not'' (1:11).',
   NULL),
  (13, 'And led him away to Annas first; for he was father in law to Caiaphas, which was the high priest that same year.',
   'καὶ ἤγαγον αὐτὸν πρὸς Ἄνναν πρῶτον ἦν γὰρ πενθερὸς τοῦ Καϊάφα ὃς ἦν ἀρχιερεὺς τοῦ ἐνιαυτοῦ ἐκείνου',
   'kai ēgagon auton pros Annan prōton ēn gar pentheros tou Kaiapa hos ēn archiereus tou eniautou ekeinou',
   '''Led him away to Annas first'' (pros Annan prōton — to Annas first). Annas (Hanan) had been high priest AD 6-15, deposed by the Romans; five of his sons and his son-in-law Caiaphas held the office after him. He remained the power behind the high priesthood. The preliminary hearing before Annas is unique to John; the Synoptics focus on Caiaphas. John shows that the real power-broker is the elder statesman Annas.',
   NULL),
  (14, 'Now Caiaphas was he, which gave counsel to the Jews, that it was expedient that one man should die for the people.',
   'ἦν δὲ Καϊάφας ὁ συμβουλεύσας τοῖς Ἰουδαίοις ὅτι συμφέρει ἕνα ἄνθρωπον ἀπολέσθαι ὑπὲρ τοῦ λαοῦ',
   'ēn de Kaiaphas ho symbouleusos tois Ioudaiois hoti sympherei hena anthrōpon apolesthai hyper tou laou',
   'John reminds the reader of Caiaphas''s earlier pronouncement (11:50-51) — the unknowing prophecy that one man should die for the people. The irony is supreme: the man who planned Jesus''s death for cynical political reasons uttered the deepest truth of the atonement. God overrules the calculations of ungodly men to accomplish his saving purpose. ''Expedient that one man should die'' — substitutionary atonement declared by the high priest, not the apostle.',
   NULL),
  (15, 'And Simon Peter followed Jesus, and so did another disciple: that disciple was known unto the high priest, and went in with Jesus into the palace of the high priest.',
   'Ἠκολούθει δὲ τῷ Ἰησοῦ Σίμων Πέτρος καὶ ἄλλος μαθητής ἐκεῖνος δὲ ὁ μαθητὴς ἦν γνωστὸς τῷ ἀρχιερεῖ καὶ συνεισῆλθεν τῷ Ἰησοῦ εἰς τὴν αὐλὴν τοῦ ἀρχιερέως',
   'Ēkolouthei de tō Iēsou Simōn Petros kai allos mathētēs ekeinos de ho mathētēs ēn gnōstos tō archiersei kai syneisēlthen tō Iēsou eis tēn aulēn tou archiereos',
   '''Another disciple... known unto the high priest'' (allos mathētēs... gnōstos tō archiersei — another disciple known to the high priest). Traditionally identified as John (the Beloved Disciple), whose family (as fishermen supplying the Jerusalem market) may have had connections with the high priest''s household. His access enables Peter to enter — and puts Peter in the dangerous position that produces the denial.',
   NULL),
  (16, 'But Peter stood at the door without. Then went out that other disciple, which was known unto the high priest, and spake unto her that kept the door, and brought in Peter.',
   'ὁ δὲ Πέτρος εἱστήκει πρὸς τῇ θύρᾳ ἔξω ἐξῆλθεν οὖν ὁ ἄλλος μαθητὴς ὁ γνωστὸς τοῦ ἀρχιερέως καὶ εἶπεν τῇ θυρωρῷ καὶ εἰσήγαγεν τὸν Πέτρον',
   'ho de Petros heistēkei pros tē thyra exō exēlthen oun ho allos mathētēs ho gnōstos tou archiereos kai eipen tē thyrōrō kai eisēgagen ton Petron',
   'Peter stands outside — excluded by lack of connection, exposed in the cold. The other disciple''s mediation brings Peter in. But being brought into the high priest''s courtyard puts Peter in the most dangerous position: surrounded by the servants and officers of the men who want Jesus dead, a fire burning in the cold night, and his Galilean accent soon to give him away.',
   NULL),
  (17, 'Then saith the damsel that kept the door unto Peter, Art not thou also one of this man''s disciples? He saith, I am not.',
   'λέγει οὖν τῷ Πέτρῳ ἡ παιδίσκη ἡ θυρωρός Μὴ καὶ σὺ ἐκ τῶν μαθητῶν εἶ τοῦ ἀνθρώπου τούτου λέγει ἐκεῖνος Οὐκ εἰμί',
   'legei oun tō Petrō hē paidiskē hē thyrōros Mē kai sy ek tōn mathētōn ei tou anthrōpou toutou legei ekeinos Ouk eimi',
   '''Art not thou also one of this man''s disciples?'' (Mē kai sy ek tōn mathētōn ei — you are not also one of the disciples, are you?). The question expects the answer ''no'' (mē: the negative particle). The door-girl''s question is almost casual; it is not an official interrogation. Peter''s denial is therefore without immediate compulsion — he denies out of fear of what might happen, not under duress. ''I am not'' (Ouk eimi — I am not) — the exact negation of ''I AM.'' Peter''s ''I am not'' contrasts starkly with Jesus''s ''I AM'' in v.5.',
   NULL),
  (18, 'And the servants and officers stood there, who had made a fire of coals; for it was cold: and they warmed themselves: and Peter stood with them, and warmed himself.',
   'εἱστήκεισαν δὲ οἱ δοῦλοι καὶ οἱ ὑπηρέται ἀνθρακιὰν πεποιηκότες ὅτι ψῦχος ἦν καὶ ἐθερμαίνοντο ἦν δὲ καὶ ὁ Πέτρος μετ᾽ αὐτῶν ἑστὼς καὶ θερμαινόμενος',
   'heistēkeisan de hoi douloi kai hoi hypēretai anthrakia pepoiēkotes hoti psychos ēn kai ethermainonto ēn de kai ho Petros met autōn estōs kai thermainomenos',
   '''A fire of coals'' (anthrakia — a charcoal fire; anthrax: coal). The word ''anthrakia'' appears only twice in John''s Gospel: here (18:18) and in 21:9, where Jesus makes a charcoal fire for the restoration breakfast with Peter. The two fires bracket Peter''s denial and restoration — a deliberate and moving literary connection. ''Peter stood with them'' (ēn kai ho Petros met autōn — Peter also was with them) — with the servants of the high priest, warming himself beside the enemy''s fire. The progressive identification with the wrong group leads to the denial.',
   NULL),
  (19, 'The high priest then asked Jesus of his disciples, and of his doctrine.',
   'ὁ οὖν ἀρχιερεὺς ἠρώτησεν τὸν Ἰησοῦν περὶ τῶν μαθητῶν αὐτοῦ καὶ περὶ τῆς διδαχῆς αὐτοῦ',
   'ho oun archiereus ērōtēsen ton Iēsoun peri tōn mathētōn autou kai peri tēs didachēs autou',
   'Annas interrogates Jesus on two fronts: his followers (seeking to assess the movement''s size and danger) and his teaching (seeking material for a charge). The questions are politically motivated: can the movement be contained, and is there blasphemy or sedition to work with? Jesus''s response (vv.20-21) is a masterpiece of legal self-defence: he points to the public nature of his ministry, refusing to incriminate himself or his disciples.',
   NULL),
  (20, 'Jesus answered him, I spake openly to the world; I ever taught in the synagogue, and in the temple, whither the Jews always resort; and in secret have I said nothing.',
   'ἀπεκρίθη αὐτῷ Ἰησοῦς Ἐγὼ παρρησίᾳ λελάληκα τῷ κόσμῳ ἐγὼ πάντοτε ἐδίδαξα ἐν τῇ συναγωγῇ καὶ ἐν τῷ ἱερῷ ὅπου πάντοτε οἱ Ἰουδαῖοι συνέρχονται καὶ ἐν κρυπτῷ ἐλάλησα οὐδέν',
   'apekrithē autō Iēsous Egō parrēsia lelalēka tō kosmō egō pantote edidaxa en tē synagōgē kai en tō hierō hopou pantote hoi Ioudaioi synerchontai kai en kryptō elalēsa ouden',
   '''In secret have I said nothing'' (en kryptō elalēsa ouden — in secret I said nothing). Jesus''s ministry was entirely public and transparent. His teaching was in synagogues, in the Temple, in the open air — places of public assembly. No secret society, no hidden agenda, no esoteric inner doctrine. This makes the night arrest particularly conspicuous: why arrest in the night a teacher who speaks only in the day? (cf. Luke 22:52-53).',
   NULL),
  (21, 'Why askest thou me? ask them which heard me, what I have said unto them: behold, they know what I said.',
   'τί με ἐρωτᾷς ἐρώτησον τοὺς ἀκηκοότας τί ἐλάλησα αὐτοῖς ἴδε οὗτοι οἴδασιν ἃ εἶπον ἐγώ',
   'ti me erōtas erōtēson tous akēkootas ti elalēsa autois ide houtoi oidasin ha eipon egō',
   '''Ask them which heard me'' (erōtēson tous akēkootas — ask those who have heard; perfect participle: those who have heard and the hearing remains). Jesus invokes the legal principle of due process: witnesses must be heard (Deuteronomy 17:6; 19:15). He refuses to be his own accuser. His boldness before the high priest contrasts with Peter''s timidity before a servant girl — the sovereign bearing of the Son of God in the face of unjust power.',
   NULL),
  (22, 'And when he had thus spoken, one of the officers which stood by struck Jesus with the palm of his hand, saying, Answerest thou the high priest so?',
   'ταῦτα δὲ αὐτοῦ εἰπόντος εἷς τῶν ὑπηρετῶν παρεστηκὼς ἔδωκεν ῥάπισμα τῷ Ἰησοῦ εἰπών Οὕτως ἀποκρίνῃ τῷ ἀρχιερεῖ',
   'tauta de autou eipontos heis tōn hypēretōn parestēkōs edōken rhapisma tō Iēsou eipōn Houtōs apoarinē tō archiersei',
   '''Struck Jesus with the palm of his hand'' (edōken rhapisma — gave a slap; rhapisma: a blow with a rod or the open hand). This is the first physical abuse of Jesus in John''s Passion — an officer striking him for speaking too directly. The contrast with Peter''s sword-stroke on Malchus''s ear is pointed: the bold swordsman is now warming himself by a fire and denying his Lord, while the Lord himself receives blows in silence.',
   NULL),
  (23, 'Jesus answered him, If I have spoken evil, bear witness of the evil: but if well, why smitest thou me?',
   'ἀπεκρίθη αὐτῷ Ἰησοῦς Εἰ κακῶς ἐλάλησα μαρτύρησον περὶ τοῦ κακοῦ εἰ δὲ καλῶς τί με δέρεις',
   'apekrithē autō Iēsous Ei kakōs elalēsa martyrēson peri tou kakou ei de kalōs ti me dereis',
   '''If I have spoken evil, bear witness of the evil'' (ei kakōs elalēsa, martyrēson peri tou kakou — if I spoke wrongly, testify about the wrong). Jesus does not return evil for evil but insists on legal justice: prove the charge or acknowledge the injustice of the blow. This is consistent with his teaching (''turn the other cheek'', Matthew 5:39) and Paul''s principle (Romans 12:17-19). The challenge is not aggression but legal/moral accountability.',
   NULL),
  (24, 'Now Annas had sent him bound unto Caiaphas the high priest.',
   'ἀπέστειλεν οὖν αὐτὸν ὁ Ἄννας δεδεμένον πρὸς Καϊάφαν τὸν ἀρχιερέα',
   'apesteilen oun auton ho Annas dedemenon pros Kaiphan ton archiersa',
   'The abbreviated note about Caiaphas — John does not describe the trial before Caiaphas (the Sanhedrin session with false witnesses and the high priest tearing his garments, recorded in Matthew 26:57-68 and Mark 14:53-65). John focuses on Annas and Pilate. The transfer from Annas to Caiaphas is noted briefly as a transitional step toward the Pilate trial.',
   NULL),
  (25, 'And Simon Peter stood and warmed himself. They said therefore unto him, Art not thou also one of his disciples? He denied it, and said, I am not.',
   'ἦν δὲ Σίμων Πέτρος ἑστὼς καὶ θερμαινόμενος εἶπον οὖν αὐτῷ Μὴ καὶ σὺ ἐκ τῶν μαθητῶν αὐτοῦ εἶ ἠρνήσατο ἐκεῖνος καὶ εἶπεν Οὐκ εἰμί',
   'ēn de Simōn Petros hestōs kai thermainomenos eipon oun autō Mē kai sy ek tōn mathētōn autou ei ērnēsato ekeinos kai eipen Ouk eimi',
   'Peter''s second denial — ''I am not'' again. The question is from the group warming themselves by the fire. The setting is the same as vv.17-18: the charcoal fire, the cold night, Peter standing in the wrong company. His denial is escalating: the first was to the door-girl; the second to the group; the third (v.26) to a kinsman of the man whose ear he cut off — an increasingly dangerous questioner.',
   NULL),
  (26, 'One of the servants of the high priest, being his kinsman whose ear Peter cut off, saith, Did not I see thee in the garden with him?',
   'λέγει εἷς ἐκ τῶν δούλων τοῦ ἀρχιερέως συγγενὴς ὢν οὗ ἀπέκοψεν Πέτρος τὸ ὠτίον Οὐκ ἐγώ σε εἶδον ἐν τῷ κήπῳ μετ᾽ αὐτοῦ',
   'legei heis ek tōn doulōn tou archiereos synggenēs ōn hou apekopsen Petros to ōtion Ouk egō se eidon en tō kēpō met autou',
   '''Being his kinsman whose ear Peter cut off'' (synggenēs ōn hou apekopsen Petros to ōtion — being a relative of the one whose ear Peter cut off). This questioner has a personal reason to press Peter: his cousin was wounded. ''Did not I see thee in the garden with him?'' — an eyewitness identification. Peter cannot deny being at the garden (the man saw him) without the eyewitness testimony being put directly against him. The trap tightens.',
   NULL),
  (27, 'Peter then denied again: and immediately the cock crew.',
   'πάλιν οὖν ἠρνήσατο Πέτρος καὶ εὐθέως ἀλέκτωρ ἐφώνησεν',
   'palin oun ērnēsato Petros kai eutheōs alektōr ephōnēsen',
   '''Immediately the cock crew'' (eutheōs alektōr ephōnēsen — immediately a cock crowed). Three denials, one crowing — exactly as Jesus predicted (13:38). Luke 22:61 records that at this moment ''the Lord turned, and looked upon Peter'' — Jesus was in the courtyard, saw Peter''s face, and the eye-contact broke Peter''s heart. He ''went out, and wept bitterly'' (Matthew 26:75; Luke 22:62). The prophecy fulfilled is both judgment and mercy: Peter had been warned; the warning comes to fruition with pastoral precision.',
   NULL),
  (28, 'Then led they Jesus from Caiaphas unto the hall of judgment: and it was early; and they themselves went not into the judgment hall, lest they should be defiled; but that they might eat the passover.',
   'Ἄγουσιν οὖν τὸν Ἰησοῦν ἀπὸ τοῦ Καϊάφα εἰς τὸ πραιτώριον ἦν δὲ πρωΐ καὶ αὐτοὶ οὐκ εἰσῆλθον εἰς τὸ πραιτώριον ἵνα μὴ μιανθῶσιν ἀλλ᾽ ἵνα φάγωσιν τὸ πάσχα',
   'Agousin oun ton Iēsoun apo tou Kaipha eis to praitōrion ēn de prōi kai autoi ouk eisēlthon eis to praitōrion hina mē mianthōsin all hina phagōsin to pascha',
   '''The hall of judgment'' (to praitōrion — the Praetorium; the governor''s official residence). ''It was early'' (prōi — early morning; the sixth watch, 3-6 AM by Roman reckoning, or dawn). ''They themselves went not into the judgment hall, lest they should be defiled'' (hina mē mianthōsin — lest they be polluted; contact with Gentile space on the eve of Passover would render them ritually unclean). The supreme irony: the men who are orchestrating an unjust execution are scrupulously careful about ritual purity. They strain out the gnat of Gentile defilement while swallowing the camel of judicial murder (Matthew 23:24).',
   NULL),
  (29, 'Pilate then went out unto them, and said, What accusation bring ye against this man?',
   'ἐξῆλθεν οὖν ὁ Πιλᾶτος πρὸς αὐτοὺς καὶ εἶπεν Τίνα κατηγορίαν φέρετε κατὰ τοῦ ἀνθρώπου τούτου',
   'exēlthen oun ho Pilatos pros autous kai eipen Tina katēgorian pherete kata tou anthrōpou toutou',
   'Pilate accommodates their ritual scruple by coming out to them — the first of many such accommodations that end in a miscarriage of justice. ''What accusation bring ye?'' (Tina katēgorian pherete — what charge do you bring?). Pilate the Roman judge follows proper legal procedure: a charge must be specified before a trial can begin. The Jewish authorities had conducted a religious trial; now they need a political conviction from the Romans (who alone had the authority to execute, v.31).',
   NULL),
  (30, 'They answered and said unto him, If he were not a malefactor, we would not have delivered him up unto thee.',
   'ἀπεκρίθησαν καὶ εἶπαν αὐτῷ Εἰ μὴ ἦν οὗτος κακοποιός οὐκ ἄν σοι παρεδώκαμεν αὐτόν',
   'apekrithēsan kai eipan autō Ei mē ēn houtos kakopoios ouk an soi paredōkamen auton',
   '''If he were not a malefactor, we would not have delivered him up'' — they do not specify a charge but appeal to their own authority and reputation: trust our verdict. This is an argument from institutional credibility, not evidence. Pilate sees through it immediately and tries to pass the case back to them (v.31). The circular argument reveals the weakness of their case.',
   NULL),
  (31, 'Then said Pilate unto them, Take ye him, and judge him according to your law. The Jews therefore said unto him, It is not lawful for us to put any man to death:',
   'εἶπεν οὖν αὐτοῖς ὁ Πιλᾶτος Λάβετε αὐτὸν ὑμεῖς καὶ κατὰ τὸν νόμον ὑμῶν κρίνατε αὐτόν εἶπον οὖν αὐτῷ οἱ Ἰουδαῖοι Ἡμῖν οὐκ ἔξεστιν ἀποκτεῖναι οὐδένα',
   'eipen oun autois ho Pilatos Labete auton hymeis kai kata ton nomon hymōn krinate auton eipon oun autō hoi Ioudaioi Hēmin ouk exestin apokteinai oudena',
   '''It is not lawful for us to put any man to death'' (Hēmin ouk exestin apokteinai oudena — It is not lawful for us to kill anyone). By AD 30, the Romans had removed the Sanhedrin''s authority to carry out capital punishment (ius gladii — the right of the sword). Jesus must be executed by Roman authority. This is providentially significant: Roman crucifixion fulfils the ''lifted up'' prophecy (3:14; 12:32-33). Jewish stoning would not have lifted him up from the earth.',
   NULL),
  (32, 'That the saying of Jesus might be fulfilled, which he spake, signifying what death he should die.',
   'ἵνα ὁ λόγος τοῦ Ἰησοῦ πληρωθῇ ὃν εἶπεν σημαίνων ποίῳ θανάτῳ ἤμελλεν ἀποθνῄσκειν',
   'hina ho logos tou Iēsou plērōthē hon eipen sēmainōn poiō thanatō ēmellen apothnēiskein',
   'John connects the legal/political circumstance with divine prophecy: the Roman legal limitation on Jewish capital punishment is the instrument by which Jesus''s prediction of being ''lifted up'' (12:32-33) is fulfilled. Behind the manoeuvres of priests and governors, the word of Jesus is being precisely fulfilled. Providence moves through human plans, even unjust ones.',
   NULL),
  (33, 'Then Pilate entered into the judgment hall again, and called Jesus, and said unto him, Art thou the King of the Jews?',
   'Εἰσῆλθεν οὖν εἰς τὸ πραιτώριον πάλιν ὁ Πιλᾶτος καὶ ἐφώνησεν τὸν Ἰησοῦν καὶ εἶπεν αὐτῷ Σὺ εἶ ὁ βασιλεὺς τῶν Ἰουδαίων',
   'Eisēlthen oun eis to praitōrion palin ho Pilatos kai ephōnēsen ton Iēsoun kai eipen autō Sy ei ho basileus tōn Ioudaiōn',
   '''Art thou the King of the Jews?'' (Sy ei ho basileus tōn Ioudaiōn?) — the charge has apparently been brought in political terms: Jesus claims to be a king, which would be treason against Rome. Pilate''s question is partly official (is this a political threat?) and partly curious (what kind of king is this?). The private interview that follows is one of the most remarkable conversations in history: the Roman governor and the Son of God, alone in the Praetorium, discussing the nature of kingship and truth.',
   NULL),
  (34, 'Jesus answered him, Sayest thou this thing of thyself, or did others tell it thee of me?',
   'ἀπεκρίθη αὐτῷ ὁ Ἰησοῦς Ἀφ᾽ ἑαυτοῦ σὺ τοῦτο λέγεις ἢ ἄλλοι εἶπόν σοι περὶ ἐμοῦ',
   'apekrithē autō ho Iēsous Aph heautou sy touto legeis ē alloi eipon soi peri emou',
   'Jesus''s counter-question is diagnostic: is Pilate asking as a Roman official investigating a political charge, or as a man genuinely wondering about the identity of this prisoner? The two types of ''king'' question require different answers. Pilate''s answer (v.35: ''Am I a Jew?'') reveals he is asking officially, as a Roman — which allows Jesus to explain the nature of his kingdom.',
   NULL),
  (35, 'Pilate answered, Am I a Jew? Thine own nation and the chief priests have delivered thee unto me: what hast thou done?',
   'ἀπεκρίθη ὁ Πιλᾶτος Μήτι ἐγὼ Ἰουδαῖός εἰμι τὸ ἔθνος τὸ σὸν καὶ οἱ ἀρχιερεῖς παρέδωκάν σε ἐμοί τί ἐποίησας',
   'apekrithē ho Pilatos Mēti egō Ioudaios eimi to ethnos to son kai hoi archiereis paredōkan se emoi ti epoiēsas',
   '''Am I a Jew?'' — with contempt for Jewish affairs. Pilate is not personally invested in the messianic question; he is a Roman administrator dealing with a Jewish religious dispute. ''What hast thou done?'' — a practical question: what act has led to this arrest? Pilate is trying to assess whether there is a real Roman law issue here.',
   NULL),
  (36, 'Jesus answered, My kingdom is not of this world: if my kingdom were of this world, then would my servants fight, that I should not be delivered to the Jews: but now is my kingdom not from hence.',
   'ἀπεκρίθη Ἰησοῦς Ἡ βασιλεία ἡ ἐμὴ οὐκ ἔστιν ἐκ τοῦ κόσμου τούτου εἰ ἐκ τοῦ κόσμου τούτου ἦν ἡ βασιλεία ἡ ἐμή οἱ ὑπηρέται ἄν οἱ ἐμοὶ ἠγωνίζοντο ἵνα μὴ παραδοθῶ τοῖς Ἰουδαίοις νῦν δὲ ἡ βασιλεία ἡ ἐμὴ οὐκ ἔστιν ἐντεῦθεν',
   'apekrithē Iēsous Hē basileia hē emē ouk estin ek tou kosmou toutou ei ek tou kosmou toutou ēn hē basileia hē emē hoi hypēretai an hoi emoi ēgōnizonto hina mē paradothō tois Ioudaiois nyn de hē basileia hē emē ouk estin enteuthen',
   '''My kingdom is not of this world'' (hē basileia hē emē ouk estin ek tou kosmou toutou — my kingdom is not from this world). Not ''not in this world'' but ''not of/from this world'' — its origin and nature are not of the world-order. Its power is not coercive, its borders are not military, its advancement is not by violence. ''Then would my servants fight'' — the proof of the kingdom''s nature: Jesus''s followers are not fighting. Peter has been rebuked (v.11). The pacifism of the arrest is the evidence. The kingdom of God is not advanced by the sword but by the word and the Spirit.',
   NULL),
  (37, 'Pilate therefore said unto him, Art thou a king then? Jesus answered, Thou sayest that I am a king. To this end was I born, and for this cause came I into the world, that I should bear witness unto the truth. Every one that is of the truth heareth my voice.',
   'εἶπεν οὖν αὐτῷ ὁ Πιλᾶτος Οὐκοῦν βασιλεὺς εἶ σύ ἀπεκρίθη ὁ Ἰησοῦς Σὺ λέγεις ὅτι βασιλεύς εἰμι ἐγὼ εἰς τοῦτο γεγέννημαι καὶ εἰς τοῦτο ἐλήλυθα εἰς τὸν κόσμον ἵνα μαρτυρήσω τῇ ἀληθείᾳ πᾶς ὁ ὢν ἐκ τῆς ἀληθείας ἀκούει μου τῆς φωνῆς',
   'eipen oun autō ho Pilatos Oukoun basileus ei sy apekrithē ho Iēsous Sy legeis hoti basileus eimi egō eis touto gegennēmai kai eis touto elēlytha eis ton kosmon hina martyrēsō tē alētheia pas ho ōn ek tēs alētheias akouei mou tēs phōnēs',
   '''To this end was I born, and for this cause came I into the world, that I should bear witness unto the truth'' (eis touto gegennēmai kai eis touto elēlytha eis ton kosmon hina martyrēsō tē alētheia — for this I have been born and for this I have come into the world: that I may bear witness to the truth). The purpose of the incarnation: testimony to truth. ''Every one that is of the truth heareth my voice'' (pas ho ōn ek tēs alētheias akouei mou tēs phōnēs) — echoing 10:27 (''My sheep hear my voice''). Pilate is being tested: is he of the truth? His response (v.38) reveals he is not.',
   NULL),
  (38, 'Pilate saith unto him, What is truth? And when he had said this, he went out again unto the Jews, and saith unto them, I find in him no fault at all.',
   'λέγει αὐτῷ ὁ Πιλᾶτος Τί ἐστιν ἀλήθεια καὶ τοῦτο εἰπὼν πάλιν ἐξῆλθεν πρὸς τοὺς Ἰουδαίους καὶ λέγει αὐτοῖς Ἐγὼ οὐδεμίαν αἰτίαν εὑρίσκω ἐν αὐτῷ',
   'legei autō ho Pilatos Ti estin alētheia kai touto eipōn palin exēlthen pros tous Ioudaious kai legei autois Egō oudemian aitian heuriskō en autō',
   '''What is truth?'' (Ti estin alētheia?) — Pilate''s question is immediately followed by his exit: he does not wait for an answer. The question is either cynical (the postmodern sceptic: there is no truth) or rhetorical (a politician''s dismissal). The irony: Truth himself is standing before Pilate, and Pilate walks away. ''I find in him no fault at all'' (oudemian aitian heuriskō en autō — I find no charge/cause in him at all). The Roman governor declares Jesus innocent — the first of three such declarations (19:4, 6). Justice demands release; politics will produce condemnation.',
   NULL),
  (39, 'But ye have a custom, that I should release unto you one at the passover: will ye therefore that I release unto you the King of the Jews?',
   'ἔστιν δὲ συνήθεια ὑμῖν ἵνα ἕνα ὑμῖν ἀπολύσω ἐν τῷ πάσχα βούλεσθε οὖν ἀπολύσω ὑμῖν τὸν βασιλέα τῶν Ἰουδαίων',
   'estin de synētheia hymin hina hena hymin apolyso en tō pascha boulesthe oun apolyso hymin ton basilea tōn Ioudaiōn',
   'The Passover amnesty (''apolusis'') is attested by the Gospels but not by other historical sources — though the practice of releasing prisoners at religious festivals is paralleled in the Roman world. Pilate offers ''the King of the Jews'' — using the title he now knows they hate, perhaps to shame them into accepting Jesus''s release. The plan backfires: they prefer Barabbas.',
   NULL),
  (40, 'Then cried they all again, saying, Not this man, but Barabbas. Now Barabbas was a robber.',
   'ἐκραύγασαν οὖν πάλιν πάντες λέγοντες Μὴ τοῦτον ἀλλὰ τὸν Βαραββᾶν ἦν δὲ ὁ Βαραββᾶς λῃστής',
   'ekraugasan oun palin pantes legontes Mē touton alla ton Barabban ēn de ho Barabbas lēstēs',
   '''Barabbas was a robber'' (ho Barabbas lēstēs — a bandit, robber; lēstēs: a highway robber; the same word used in 10:1,8 for those who climb over the sheepfold wall). The Synoptics add that Barabbas was involved in insurrection and murder (Mark 15:7; Luke 23:18-19). ''Barabbas'' (bar-Abba) in Aramaic means ''son of the father.'' The crowd chooses the violent ''son of the father'' over the true Son of the Father. And in choosing so, they unwittingly demonstrate the theology of substitution: the guilty man goes free, the innocent man dies.',
   NULL)
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'John' AND c.chapter_number = 18;

-- JOHN CHAPTER 18 — BACKFILL (word_studies + cross_references)

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'πέραν', 'peran', 'G4008', 'Across/beyond — Jesus crosses the Kidron ravine, echoing David''s flight from Absalom (2 Sam 15:23).', 1),
  (1, 'χειμάρρου', 'cheimarrou', 'G5493', 'Winter-flowing brook/wadi — the Kidron, dry most of the year, a ravine east of Jerusalem.', 2),
  (1, 'Κέδρων', 'Kedrōn', 'G2748', 'Kidron — "the dark/turbid one"; the ravine blood from temple sacrifices drained into.', 3),
  (1, 'κῆπος', 'kēpos', 'G2779', 'Garden — deliberate echo of Eden; the second Adam''s obedience in a garden reverses Adam''s disobedience.', 4),
  (3, 'σπεῖραν', 'speiran', 'G4686', 'Cohort — Roman military unit of 600 (or maniple of 200); a large force for a single arrest.', 5),
  (3, 'ὑπηρέτας', 'hypēretas', 'G5257', 'Officers/attendants — temple police dispatched by the chief priests.', 6),
  (3, 'λαμπάδων', 'lampadōn', 'G2985', 'Torches — they come with lights seeking the Light of the world in the dark (cf. 1:5).', 7),
  (4, 'εἰδὼς πάντα', 'eidōs panta', 'G1492/G3956', 'Knowing all things — Jesus''s sovereign foreknowledge; he steps forward voluntarily, not caught.', 8),
  (5, 'ἐγώ εἰμι', 'egō eimi', 'G1473/G1510', 'I AM — the divine name (Exod 3:14); the soldiers fall backward at the name.', 9),
  (6, 'ἔπεσαν χαμαί', 'epesan chamai', 'G4098/G5476', 'Fell to the ground — involuntary prostration at the divine Name (cf. Rev 1:17; Dan 10:9).', 10),
  (10, 'μάχαιραν', 'machairan', 'G3162', 'Sword/short blade — a dagger, not a long sword; standard sidearm of the period.', 11),
  (10, 'ὠτάριον', 'ōtarion', 'G5621', 'Little ear/earlobe — diminutive form; John alone names Peter (Petros) and Malchus.', 12),
  (11, 'θήκην', 'thēkēn', 'G2336', 'Sheath/scabbard — "put up your sword into the sheath"; Jesus rejects armed defense.', 13),
  (11, 'ποτήριον', 'potērion', 'G4221', 'Cup — the cup of wrath/suffering the Father has given him to drink (Mark 14:36; Ps 75:8).', 14),
  (13, 'πενθεροῦ', 'pentherou', 'G3995', 'Father-in-law — Annas was father-in-law of Caiaphas; though deposed, still power-broker.', 15),
  (14, 'συμβουλεύσας', 'symbouleusas', 'G4823', 'Having counseled/advised — backward reference to 11:49-52 (better one man die).', 16),
  (15, 'ἄλλος μαθητής', 'allos mathētēs', 'G243/G3101', 'Another disciple — traditionally the Beloved Disciple (John); known to the high priest.', 17),
  (17, 'οὐκ εἰμί', 'ouk eimi', 'G3756/G1510', '"I am not" — Peter''s denial is the anti-egō-eimi; he refuses to identify himself as the Lord identifies himself.', 18),
  (18, 'ἀνθρακιάν', 'anthrakian', 'G439', 'Charcoal fire — only here and 21:9 in the NT; John uses it to link Peter''s denial with his restoration.', 19),
  (20, 'παρρησίᾳ', 'parrēsia', 'G3954', 'Openly/boldly — Jesus''s public ministry contrasts with secret plotting of his accusers.', 20),
  (20, 'συναγωγῇ', 'synagōgē', 'G4864', 'Synagogue — Jewish assembly for teaching; Jesus taught there openly.', 21),
  (22, 'ῥάπισμα', 'rhapisma', 'G4475', 'Slap/blow with the hand — the first physical abuse; fulfills Isa 50:6.', 22),
  (23, 'κακῶς', 'kakōs', 'G2560', 'Wrongly/evilly — Jesus appeals to evidence: "if I spoke evil, bear witness to the evil."', 23),
  (26, 'συγγενὴς', 'syngenēs', 'G4773', 'Kinsman — relative of Malchus, witnessed the ear-cutting; Peter''s lie unravels.', 24),
  (27, 'ἀλέκτωρ', 'alektōr', 'G220', 'Cock/rooster — fulfilled prediction of 13:38; the bird of remembrance.', 25),
  (28, 'πραιτώριον', 'praitōrion', 'G4232', 'Praetorium — governor''s residence, probably Herod''s palace or Antonia fortress.', 26),
  (28, 'μιανθῶσιν', 'mianthōsin', 'G3392', 'Be defiled — Gentile dwellings ceremonially unclean; tragic irony: they avoid ritual defilement while committing murder.', 27),
  (29, 'κατηγορίαν', 'katēgorian', 'G2724', 'Accusation/formal charge — Pilate demands legal basis; Romans required formal cognitio.', 28),
  (31, 'οὐκ ἔξεστιν', 'ouk exestin', 'G3756/G1832', 'It is not lawful — Sanhedrin had no jus gladii (right of capital punishment) under Roman rule.', 29),
  (32, 'ποίῳ θανάτῳ', 'poiō thanatō', 'G4169/G2288', 'By what kind of death — cross was Roman execution; Jesus predicted being "lifted up" (12:32-33).', 30),
  (33, 'βασιλεὺς τῶν Ἰουδαίων', 'basileus tōn Ioudaiōn', 'G935/G2453', 'King of the Jews — Gentile phrasing; Jesus is "King of Israel" in Jewish lips.', 31),
  (36, 'ἡ βασιλεία ἡ ἐμὴ', 'hē basileia hē emē', 'G932', 'My kingdom — possessive emphatic; "mine, uniquely mine" — in contrast to any earthly realm.', 32),
  (36, 'ἐκ τοῦ κόσμου τούτου', 'ek tou kosmou toutou', 'G1537/G2889', 'Of this world — origin, not location; Christ''s rule is from above though exercised in the world.', 33),
  (36, 'ὑπηρέται', 'hypēretai', 'G5257', 'Servants — if an earthly kingdom, his servants would fight; but they do not, revealing its nature.', 34),
  (37, 'ἀλήθεια', 'alētheia', 'G225', 'Truth — Jesus''s mission is witness to the truth; all who are of the truth hear his voice.', 35),
  (37, 'γεγέννημαι', 'gegennēmai', 'G1080', 'I have been born (perfect) — the incarnation stated at the Roman tribunal.', 36),
  (37, 'ἐλήλυθα', 'elēlytha', 'G2064', 'I have come (perfect) — mission-language; come into the world for this purpose.', 37),
  (38, 'τί ἐστιν ἀλήθεια', 'ti estin alētheia', 'G5101/G1510/G225', '"What is truth?" — Pilate''s cynical dismissal; stands face-to-face with Truth incarnate (14:6) and walks away.', 38),
  (40, 'λῃστής', 'lēstēs', 'G3027', 'Bandit/insurrectionist — more than common thief; possibly Zealot revolutionary.', 39),
  (40, 'Βαραββᾶν', 'Barabban', 'G912', 'Barabbas — Aramaic "son of the father"; ironic substitution: false son released, true Son condemned.', 40)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'John' AND c.chapter_number = 18 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, '2 Samuel 15:23', 1),
  (1, '2 Samuel 15:30', 2),
  (1, 'Matthew 26:36', 3),
  (1, 'Mark 14:32', 4),
  (1, 'Luke 22:39', 5),
  (1, 'Genesis 3:8', 6),
  (2, 'Luke 22:39', 1),
  (2, 'John 13:2', 2),
  (3, 'Matthew 26:47', 1),
  (3, 'Mark 14:43', 2),
  (3, 'Luke 22:47', 3),
  (3, 'Acts 1:16', 4),
  (4, 'John 10:17-18', 1),
  (4, 'John 13:1', 2),
  (5, 'Exodus 3:14', 1),
  (5, 'John 8:58', 2),
  (5, 'John 13:19', 3),
  (5, 'Isaiah 41:4', 4),
  (6, 'Psalm 27:2', 1),
  (6, 'Psalm 35:4', 2),
  (6, 'Daniel 10:9', 3),
  (6, 'Revelation 1:17', 4),
  (8, 'John 6:39', 1),
  (8, 'John 10:28', 2),
  (8, 'John 17:12', 3),
  (9, 'John 17:12', 1),
  (9, 'John 6:39', 2),
  (10, 'Matthew 26:51', 1),
  (10, 'Mark 14:47', 2),
  (10, 'Luke 22:50', 3),
  (11, 'Matthew 26:39', 1),
  (11, 'Mark 14:36', 2),
  (11, 'Luke 22:42', 3),
  (11, 'Isaiah 51:17', 4),
  (11, 'Jeremiah 25:15', 5),
  (11, 'Matthew 26:52', 6),
  (13, 'Luke 3:2', 1),
  (13, 'Acts 4:6', 2),
  (14, 'John 11:49-52', 1),
  (15, 'John 13:23', 1),
  (15, 'John 19:26', 2),
  (15, 'John 20:2', 3),
  (16, 'Matthew 26:58', 1),
  (17, 'Matthew 26:69-70', 1),
  (17, 'Mark 14:66-68', 2),
  (17, 'Luke 22:56-57', 3),
  (18, 'John 21:9', 1),
  (18, 'Mark 14:54', 2),
  (19, 'Matthew 26:59-60', 1),
  (20, 'John 7:26', 1),
  (20, 'Matthew 26:55', 2),
  (20, 'Isaiah 45:19', 3),
  (20, 'John 7:14', 4),
  (22, 'Isaiah 50:6', 1),
  (22, 'Micah 5:1', 2),
  (22, 'John 19:3', 3),
  (23, 'Acts 23:2-5', 1),
  (23, '1 Peter 2:23', 2),
  (24, 'Matthew 26:57', 1),
  (25, 'Matthew 26:71-72', 1),
  (25, 'Mark 14:69-70', 2),
  (25, 'Luke 22:58', 3),
  (26, 'John 18:10', 1),
  (27, 'John 13:38', 1),
  (27, 'Matthew 26:74-75', 2),
  (27, 'Mark 14:72', 3),
  (27, 'Luke 22:60-62', 4),
  (28, 'Matthew 27:1-2', 1),
  (28, 'Mark 15:1', 2),
  (28, 'Luke 23:1', 3),
  (28, 'Acts 10:28', 4),
  (28, 'Deuteronomy 16:4', 5),
  (29, 'Acts 25:16', 1),
  (31, 'Ezekiel 21:26-27', 1),
  (31, 'Genesis 49:10', 2),
  (32, 'John 3:14', 1),
  (32, 'John 8:28', 2),
  (32, 'John 12:32-33', 3),
  (32, 'Deuteronomy 21:22-23', 4),
  (33, 'Matthew 27:11', 1),
  (33, 'Mark 15:2', 2),
  (33, 'Luke 23:3', 3),
  (33, '1 Timothy 6:13', 4),
  (36, 'Daniel 7:14', 1),
  (36, 'Luke 17:20-21', 2),
  (36, 'Romans 14:17', 3),
  (36, 'Colossians 1:13', 4),
  (36, '2 Corinthians 10:3-4', 5),
  (36, 'Matthew 26:53', 6),
  (37, 'John 14:6', 1),
  (37, 'John 8:47', 2),
  (37, '1 John 4:6', 3),
  (37, '1 Timothy 6:13', 4),
  (37, 'Revelation 1:5', 5),
  (37, 'Revelation 3:14', 6),
  (38, 'John 14:6', 1),
  (38, 'Psalm 85:10-11', 2),
  (38, 'Matthew 27:24', 3),
  (38, 'Luke 23:4', 4),
  (39, 'Matthew 27:15', 1),
  (39, 'Mark 15:6', 2),
  (39, 'Luke 23:17', 3),
  (40, 'Acts 3:14', 1),
  (40, 'Matthew 27:20-21', 2),
  (40, 'Mark 15:7', 3),
  (40, 'Luke 23:18-19', 4),
  (40, 'Isaiah 53:6', 5),
  (40, '1 Peter 3:18', 6)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'John' AND c.chapter_number = 18 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
