-- ═══════════════════════════════════════════════════
-- JOHN CHAPTER 17 — The High Priestly Prayer
-- 26 verses · Greek text · Word studies · Cross-refs
-- ═══════════════════════════════════════════════════

-- Step 1: Insert chapter metadata
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 17,
  'John 17 is the longest recorded prayer of Jesus and one of the most profound theological documents in Scripture. Often called the ''High Priestly Prayer'' (a title used by David Chytraeus in 1583), it is Jesus''s prayer of consecration before the Passion — the eternal Son presenting himself and his people to the Father on the eve of the cross. It has been described as ''the most important chapter in the Bible'' and ''the Holy of Holies of the New Testament.'' The prayer falls into three distinct sections: (1) Jesus prays for himself (vv.1-5), asking the Father to glorify the Son so that the Son may glorify the Father, and to restore the pre-incarnate glory he had before the world was; (2) Jesus prays for the eleven disciples (vv.6-19), asking that they be kept in the Father''s name, protected from the evil one, sanctified through the truth, and unified; (3) Jesus prays for all future believers (vv.20-26), asking that all who believe through the apostolic word may be one as the Father and Son are one, so that the world may believe, and that they may ultimately behold Christ''s glory in eternity. The dominant themes are glory (doxa/doxazō — 8 times), sanctification/truth, unity/oneness, and the love between Father, Son, and believers. This prayer bridges heaven and earth: Jesus speaks to the Father but in the disciples'' hearing (''these things I speak in the world'', v.13), so that his joy may be fulfilled in them. Every believer is named in this prayer — ''neither pray I for these alone, but for them also which shall believe on me through their word'' (v.20).',
  'The High Priestly Prayer — Glory, Unity, and Sanctification',
  'ἁγιάζω (hagiazō)',
  'To sanctify, consecrate, set apart as holy — from hagios (holy). Sanctification in John 17 has both a positional and a moral dimension. Jesus consecrates himself (''I sanctify myself'' v.19) — not because he needs purification but as a sacrificial offering, setting himself apart for the work of atonement. He prays that the disciples be sanctified through the truth (v.17) — set apart from the world by the transforming power of the word of God. Sanctification is the process by which believers are made holy in character (conformity to Christ) as well as position (set apart for God). The instrument is ''thy word'' (ho logos — the written and living word of God). This distinguishes Christian holiness from asceticism or ritualism: it is truth-shaped, not merely practice-shaped.',
  '["Jesus Prays for Himself (vv.1-5): These words spake Jesus and lifted up his eyes to heaven and said Father the hour is come glorify thy Son that thy Son also may glorify thee as thou hast given him power over all flesh that he should give eternal life to as many as thou hast given him. And this is life eternal that they might know thee the only true God and Jesus Christ whom thou hast sent. I have glorified thee on the earth I have finished the work which thou gavest me to do. And now O Father glorify thou me with thine own self with the glory which I had with thee before the world was","Jesus Prays for the Disciples (vv.6-19): I have manifested thy name unto the men which thou gavest me out of the world thine they were and thou gavest them me and they have kept thy word. Now they have known that all things whatsoever thou hast given me are of thee. For I have given unto them the words which thou gavest me and they have received them and have known surely that I came out from thee and they have believed that thou didst send me. I pray for them I pray not for the world but for them which thou hast given me for they are thine. And all mine are thine and thine are mine and I am glorified in them. And now I am no more in the world but these are in the world and I come to thee. Holy Father keep through thine own name those whom thou hast given me that they may be one as we are. While I was with them in the world I kept them in thy name those that thou gavest me I have kept and none of them is lost but the son of perdition that the scripture might be fulfilled. And now come I to thee and these things I speak in the world that they might have my joy fulfilled in themselves. I have given them thy word and the world hath hated them because they are not of the world even as I am not of the world. I pray not that thou shouldest take them out of the world but that thou shouldest keep them from the evil. They are not of the world even as I am not of the world. Sanctify them through thy truth thy word is truth. As thou hast sent me into the world even so have I also sent them into the world. And for their sakes I sanctify myself that they also might be sanctified through the truth","Jesus Prays for All Believers (vv.20-26): Neither pray I for these alone but for them also which shall believe on me through their word That they all may be one as thou Father art in me and I in thee that they also may be one in us that the world may believe that thou hast sent me. And the glory which thou gavest me I have given them that they may be one even as we are one I in them and thou in me that they may be made perfect in one and that the world may know that thou hast sent me and hast loved them as thou hast loved me. Father I will that they also whom thou hast given me be with me where I am that they may behold my glory which thou hast given me for thou lovedst me before the foundation of the world. O righteous Father the world hath not known thee but I have known thee and these have known that thou hast sent me. And I have declared unto them thy name and will declare it that the love wherewith thou hast loved me may be in them and I in them"]'
FROM books b WHERE b.name = 'John';

-- Step 2: Insert all 26 verses
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'These words spake Jesus, and lifted up his eyes to heaven, and said, Father, the hour is come; glorify thy Son, that thy Son also may glorify thee:',
   'Ταῦτα ἐλάλησεν Ἰησοῦς καὶ ἐπάρας τοὺς ὀφθαλμοὺς αὐτοῦ εἰς τὸν οὐρανὸν εἶπεν Πάτερ ἐλήλυθεν ἡ ὥρα δόξασόν σου τὸν υἱόν ἵνα καὶ ὁ υἱὸς δοξάσῃ σέ',
   'Tauta elalēsen Iēsous kai eparas tous ophthalmous autou eis ton ouranon eipen Pater elēlythen hē hōra doxason sou ton huion hina kai ho huios doxasē se',
   '''Lifted up his eyes to heaven'' (eparas tous ophthalmous autou eis ton ouranon — lifting up his eyes to heaven). This is the posture of ancient prayer — eyes open, face upward, not bowed (cf. 11:41; Luke 18:13). The high priest on the Day of Atonement lifted his voice to God on behalf of the people; Jesus now lifts his eyes on behalf of his people. ''The hour is come'' (elēlythen hē hōra — the hour has come; perfect: has arrived). The hour that has been approaching throughout the Gospel (2:4; 7:30; 8:20; 12:23,27; 13:1) has now arrived. ''Glorify thy Son, that thy Son also may glorify thee'' — the mutual glorification of Father and Son through the cross: the Father glorifies the Son by raising him from the dead; the Son glorifies the Father by his obedient self-offering. Glory comes through death.',
   NULL),
  (2, 'As thou hast given him power over all flesh, that he should give eternal life to as many as thou hast given him.',
   'καθὼς ἔδωκας αὐτῷ ἐξουσίαν πάσης σαρκός ἵνα πᾶν ὃ δέδωκας αὐτῷ δώσῃ αὐτοῖς ζωὴν αἰώνιον',
   'kathōs edōkas autō exousian pasēs sarkos hina pan ho dedōkas autō dōsē autois zōēn aiōnion',
   '''Power over all flesh'' (exousian pasēs sarkos — authority over all flesh). ''Exousia'' (authority, right, delegated power). The scope is universal — ''all flesh'' (all humanity), yet the gift of eternal life is particular: ''as many as thou hast given him'' (pan ho dedōkas autō — all [the whole] that you have given him). The universal authority serves a particular mission: giving eternal life to the elect given to the Son by the Father. Both the universal scope of Christ''s authority and the particular gift of salvation to those given to him are affirmed.',
   NULL),
  (3, 'And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent.',
   'αὕτη δέ ἐστιν ἡ αἰώνιος ζωή ἵνα γινώσκωσίν σε τὸν μόνον ἀληθινὸν θεὸν καὶ ὃν ἀπέστειλας Ἰησοῦν Χριστόν',
   'hautē de estin hē aiōnios zōē hina ginōskōsin se ton monon alēthinon theon kai hon apesteiles Iēsoun Christon',
   '''This is life eternal, that they might know thee'' (hautē estin hē aiōnios zōē hina ginōskōsin se — this is eternal life: that they know you). Eternal life is not primarily duration (living forever) but relationship (knowing God). ''Ginōskōsin'' (present subjunctive: that they may keep knowing — an ongoing, progressive, deepening knowledge). This is knowledge in the Hebrew sense (yada''): intimate, experiential, relational knowing. ''The only true God'' (ton monon alēthinon theon — the only genuine/authentic God) — monotheistic and exclusive. ''And Jesus Christ, whom thou hast sent'' — the only way to know the only true God is through Jesus Christ. The combination of these two clauses is crucial: eternal life requires knowledge of both the Father and the Son — they cannot be separated.',
   NULL),
  (4, 'I have glorified thee on the earth: I have finished the work which thou gavest me to do.',
   'ἐγώ σε ἐδόξασα ἐπὶ τῆς γῆς τὸ ἔργον τελειώσας ὃ δέδωκάς μοι ἵνα ποιήσω',
   'egō se edoxasa epi tēs gēs to ergon teleiōsas ho dedōkas moi hina poiēsō',
   '''I have finished the work'' (to ergon teleiōsas — having completed the work; teleiōsas from teleioō: to bring to completion, to perfect). The same root as ''tetelestai'' (''It is finished'', 19:30). Jesus speaks on the eve of the cross as if the work is already complete — such is the certainty of his will and the Father''s plan. The three years of public ministry are complete; only the cross remains, and its completion is treated as a foregone conclusion. ''Which thou gavest me to do'' — the work is the Father''s assignment, faithfully executed.',
   NULL),
  (5, 'And now, O Father, glorify thou me with thine own self with the glory which I had with thee before the world was.',
   'καὶ νῦν δόξασόν με σύ πάτερ παρὰ σεαυτῷ τῇ δόξῃ ᾗ εἶχον πρὸ τοῦ τὸν κόσμον εἶναι παρὰ σοί',
   'kai nyn doxason me sy pater para seautō tē doxē hē eichon pro tou ton kosmon einai para soi',
   '''The glory which I had with thee before the world was'' (tē doxē hē eichon pro tou ton kosmon einai para soi — the glory which I had alongside you before the world existed). One of the clearest statements of Christ''s pre-existence and pre-incarnate glory in Scripture. The incarnation involved a voluntary laying aside of the visible glory (''made himself of no reputation'', Philippians 2:7; ''became flesh'', 1:14). Now Jesus prays for the restoration of that glory — fulfilled in the ascension and the glorified state of the risen Christ (Acts 3:13; 7:55-56; Revelation 1:13-16).',
   NULL),
  (6, 'I have manifested thy name unto the men which thou gavest me out of the world: thine they were, and thou gavest them me; and they have kept thy word.',
   'Ἐφανέρωσά σου τὸ ὄνομα τοῖς ἀνθρώποις οὓς ἔδωκάς μοι ἐκ τοῦ κόσμου σοὶ ἦσαν καὶ ἐμοὶ αὐτοὺς ἔδωκας καὶ τὸν λόγον σου τετήρηκαν',
   'Ephanerōsa sou to onoma tois anthrōpois hous edōkas moi ek tou kosmou soi ēsan kai emoi autous edōkas kai ton logon sou tetērēkan',
   '''I have manifested thy name'' (ephanerōsa sou to onoma — I revealed/made visible your name). ''Name'' (onoma) — not merely a verbal label but the character and nature of God as expressed through Jesus''s life, teaching, and miracles. ''Thine they were, and thou gavest them me'' (soi ēsan kai emoi autous edōkas — they were yours and you gave them to me) — the sovereignty of the Father''s gift: the disciples belong first to the Father, then are given to the Son. Election is the Father''s act; discipleship is the Son''s keeping.',
   NULL),
  (7, 'Now they have known that all things whatsoever thou hast given me are of thee.',
   'νῦν ἐγνώκασιν ὅτι πάντα ὅσα δέδωκάς μοι παρὰ σοῦ ἐστιν',
   'nyn egnōkasin hoti panta hosa dedōkas moi para sou estin',
   '''Now they have known'' (nyn egnōkasin — now they have come to know; perfect: the knowledge has arrived and stands). The disciples'' understanding has progressively deepened through three years with Jesus. By the eve of the Passion, they have come to know that everything Jesus has — his words, his works, his authority, his nature — all comes from the Father. This is the Trinitarian insight at the heart of discipleship.',
   NULL),
  (8, 'For I have given unto them the words which thou gavest me; and they have received them, and have known surely that I came out from thee, and they have believed that thou didst send me.',
   'ὅτι τὰ ῥήματα ἃ ἔδωκάς μοι δέδωκα αὐτοῖς καὶ αὐτοὶ ἔλαβον καὶ ἔγνωσαν ἀληθῶς ὅτι παρὰ σοῦ ἐξῆλθον καὶ ἐπίστευσαν ὅτι σύ με ἀπέστειλας',
   'hoti ta rhēmata ha edōkas moi dedōka autois kai autoi elabon kai egnōsan alēthōs hoti para sou exēlthon kai episteusan hoti sy me apesteiles',
   '''I have given unto them the words which thou gavest me'' (ta rhēmata ha edōkas moi dedōka autois — the words which you gave me I have given them). The chain of revelation: Father → Son → disciples. ''They have received them'' (autoi elabon — they themselves received them; emphatic: as distinct from those who rejected them). ''Known surely'' (egnōsan alēthōs — knew truly, genuinely). ''Believed that thou didst send me'' — faith in the divine mission of the Son is the mark of true discipleship.',
   NULL),
  (9, 'I pray for them: I pray not for the world, but for them which thou hast given me; for they are thine.',
   'ἐγὼ περὶ αὐτῶν ἐρωτῶ οὐ περὶ τοῦ κόσμου ἐρωτῶ ἀλλὰ περὶ ὧν δέδωκάς μοι ὅτι σοί εἰσιν',
   'egō peri autōn erōtō ou peri tou kosmou erōtō alla peri hōn dedōkas moi hoti soi eisin',
   '''I pray not for the world'' (ou peri tou kosmou erōtō — I do not pray for the world). This is not indifference to the world (3:16 shows God''s love for the world) but a focused intercession: in this prayer, Jesus prays specifically for his own. He prays elsewhere for the salvation of the world implicitly (v.21: ''that the world may believe''); here the immediate concern is for those already given to him. The High Priest''s intercession is particularly for his people.',
   NULL),
  (10, 'And all mine are thine, and thine are mine; and I am glorified in them.',
   'καὶ τὰ ἐμὰ πάντα σά ἐστιν καὶ τὰ σὰ ἐμά καὶ δεδόξασμαι ἐν αὐτοῖς',
   'kai ta ema panta sa estin kai ta sa ema kai dedoxasmai en autois',
   '''All mine are thine, and thine are mine'' (ta ema panta sa estin kai ta sa ema) — the complete mutual possession of Father and Son. Nothing the Son has is his alone; nothing the Father has excludes the Son. The disciples are thus simultaneously the Father''s possession and the Son''s. ''I am glorified in them'' (dedoxasmai en autois — I have been glorified in them; perfect: the glorification is a present, standing reality). The disciples, imperfect as they are, are the medium through which Christ''s glory is expressed in the world.',
   NULL),
  (11, 'And now I am no more in the world, but these are in the world, and I come to thee. Holy Father, keep through thine own name those whom thou hast given me, that they may be one, as we are.',
   'καὶ οὐκέτι εἰμὶ ἐν τῷ κόσμῳ καὶ οὗτοι ἐν τῷ κόσμῳ εἰσίν καὶ ἐγὼ πρὸς σὲ ἔρχομαι Πάτερ ἅγιε τήρησον αὐτοὺς ἐν τῷ ὀνόματί σου ᾧ δέδωκάς μοι ἵνα ὦσιν ἓν καθὼς ἡμεῖς',
   'kai ouketi eimi en tō kosmō kai houtoi en tō kosmō eisin kai egō pros se erchomai Pater hagie tērēson autous en tō onomati sou hō dedōkas moi hina ōsin hen kathōs hēmeis',
   '''Holy Father'' (Pater hagie — Holy Father) — a unique address in the NT; ''Father'' expresses intimacy, ''Holy'' expresses the divine character that is the ground of the keeping. ''Keep through thine own name'' (tērēson autous en tō onomati sou — keep them in your name). The keeping is by the power and character of God himself — his name is his nature. ''That they may be one, as we are'' (hina ōsin hen kathōs hēmeis — so that they may be one just as we are). The unity of the disciples is modelled on the unity of the Trinity — not uniformity but profound oneness of will, love, and purpose.',
   NULL),
  (12, 'While I was with them in the world, I kept them in thy name: those that thou gavest me I have kept, and none of them is lost, but the son of perdition; that the scripture might be fulfilled.',
   'ὅτε ἤμην μετ᾽ αὐτῶν ἐν τῷ κόσμῳ ἐγὼ ἐτήρουν αὐτοὺς ἐν τῷ ὀνόματί σου οὓς δέδωκάς μοι ἐφύλαξα καὶ οὐδεὶς ἐξ αὐτῶν ἀπώλετο εἰ μὴ ὁ υἱὸς τῆς ἀπωλείας ἵνα ἡ γραφὴ πληρωθῇ',
   'hote ēmēn met autōn en tō kosmō egō etēroun autous en tō onomati sou hous dedōkas moi ephylaxa kai oudeis ex autōn apōleto ei mē ho huios tēs apōleias hina hē graphē plērōthē',
   '''None of them is lost, but the son of perdition'' (oudeis ex autōn apōleto ei mē ho huios tēs apōleias — none of them perished except the son of perdition). ''Son of perdition'' (ho huios tēs apōleias — the son of destruction/ruin; the same phrase is used of the Antichrist in 2 Thessalonians 2:3). ''Apōleia'' (destruction, perdition) is from apollymi — the same verb used throughout John for ''perishing'' (3:16; 6:39; 10:28; 17:12). The exception of Judas is stated plainly but ''that the scripture might be fulfilled'' (hina hē graphē plērōthē) — his perdition was predicted, not caused, by divine foreknowledge (Psalm 41:9; 109:8).',
   NULL),
  (13, 'And now come I to thee; and these things I speak in the world, that they might have my joy fulfilled in themselves.',
   'νῦν δὲ πρὸς σὲ ἔρχομαι καὶ ταῦτα λαλῶ ἐν τῷ κόσμῳ ἵνα ἔχωσιν τὴν χαρὰν τὴν ἐμὴν πεπληρωμένην ἐν ἑαυτοῖς',
   'nyn de pros se erchomai kai tauta lalō en tō kosmō hina echōsin tēn charan tēn emēn peplērōmenēn en heautois',
   '''I speak in the world'' (lalō en tō kosmō) — Jesus prays audibly, in the presence of the disciples. He could have prayed silently; he speaks aloud so that the disciples overhear and are strengthened. ''My joy fulfilled in themselves'' (tēn charan tēn emēn peplērōmenēn — my joy, having been filled up in them; the perfect passive participle indicates completeness). The purpose of the prayer is the disciples'' joy — the Son''s prayer for the disciples is pastoral as well as priestly.',
   NULL),
  (14, 'I have given them thy word; and the world hath hated them, because they are not of the world, even as I am not of the world.',
   'ἐγὼ δέδωκα αὐτοῖς τὸν λόγον σου καὶ ὁ κόσμος ἐμίσησεν αὐτούς ὅτι οὐκ εἰσὶν ἐκ τοῦ κόσμου καθὼς ἐγὼ οὐκ εἰμὶ ἐκ τοῦ κόσμου',
   'egō dedōka autois ton logon sou kai ho kosmos emisēsen autous hoti ouk eisin ek tou kosmou kathōs egō ouk eimi ek tou kosmou',
   '''I have given them thy word'' (dedōka autois ton logon sou — I have given them your word; perfect: the giving is complete and the word remains with them). The word of God is the source of the disciples'' non-conformity to the world, and therefore the cause of the world''s hatred. ''They are not of the world, even as I am not of the world'' — the disciples'' ''otherness'' is not their own achievement but a reflection of their union with Christ.',
   NULL),
  (15, 'I pray not that thou shouldest take them out of the world, but that thou shouldest keep them from the evil.',
   'οὐκ ἐρωτῶ ἵνα ἄρῃς αὐτοὺς ἐκ τοῦ κόσμου ἀλλ᾽ ἵνα τηρήσῃς αὐτοὺς ἐκ τοῦ πονηροῦ',
   'ouk erōtō hina arēs autous ek tou kosmou all hina tērēsēs autous ek tou ponērou',
   '''Not that thou shouldest take them out of the world'' (ouk erōtō hina arēs autous ek tou kosmou — I do not ask that you take them out of the world). The Christian calling is not withdrawal from the world (cf. 1 Corinthians 5:10) but engagement with it. The world is the mission field. ''But that thou shouldest keep them from the evil'' (alla hina tērēsēs autous ek tou ponērou — but that you keep them from the evil one; ho ponēros: the evil one = Satan, cf. 1 John 2:13-14; 3:12; 5:18-19; Matthew 6:13). Protection from the evil one is the content of the petition — not immunity from suffering but preservation from Satanic assault on their faith.',
   NULL),
  (16, 'They are not of the world, even as I am not of the world.',
   'ἐκ τοῦ κόσμου οὐκ εἰσὶν καθὼς ἐγὼ ἐκ τοῦ κόσμου οὐκ εἰμί',
   'ek tou kosmou ouk eisin kathōs egō ek tou kosmou ouk eimi',
   'Repetition of v.14b — emphasis by reiteration. The disciples'' non-worldliness is not a matter of temperament or choice but of nature: they are born from above (3:3), children of God (1:12-13), citizens of heaven (Philippians 3:20). Their primary identity is not in any earthly category but in Christ.',
   NULL),
  (17, 'Sanctify them through thy truth: thy word is truth.',
   'ἁγίασον αὐτοὺς ἐν τῇ ἀληθείᾳ ὁ λόγος ὁ σὸς ἀλήθειά ἐστιν',
   'hagiason autous en tē alētheia ho logos ho sos alētheia estin',
   '''Sanctify them through thy truth'' (hagiason autous en tē alētheia — consecrate/set apart them in the truth). ''Hagiazō'' (to make holy, set apart): the disciples are to be consecrated for mission, set apart from the world by the truth. ''Thy word is truth'' (ho logos ho sos alētheia estin — your word is truth; not merely contains truth but IS truth). This is a profound epistemological claim: the word of God is the standard and source of all truth. Sanctification is truth-mediated: the word of God renews the mind (Romans 12:2), cleanses (15:3; Ephesians 5:26), and sets apart. The instrument of sanctification is Scripture.',
   NULL),
  (18, 'As thou hast sent me into the world, even so have I also sent them into the world.',
   'καθὼς ἐμὲ ἀπέστειλας εἰς τὸν κόσμον κἀγὼ ἀπέστειλα αὐτοὺς εἰς τὸν κόσμον',
   'kathōs eme apesteiles eis ton kosmon kagō apesteila autous eis ton kosmon',
   '''As thou hast sent me... even so have I also sent them'' (kathōs eme apesteiles... kagō apesteila autous — just as you sent me... I also sent them). The mission of the church is modelled on and grounded in the mission of the Son. The disciples are ''apostles'' (sent ones) as Jesus is the supreme Apostle (Hebrews 3:1). This verse is the missional basis for John''s version of the Great Commission (20:21). The sending-by-the-Father authorises the sending-by-the-Son.',
   NULL),
  (19, 'And for their sakes I sanctify myself, that they also might be sanctified through the truth.',
   'καὶ ὑπὲρ αὐτῶν ἐγὼ ἁγιάζω ἐμαυτόν ἵνα ὦσιν καὶ αὐτοὶ ἡγιασμένοι ἐν ἀληθείᾳ',
   'kai hyper autōn egō hagiazō emauton hina ōsin kai autoi hēgiasmenoi en alētheia',
   '''I sanctify myself'' (egō hagiazō emauton — I consecrate/set apart myself). Jesus does not sanctify himself because he is unholy — he is absolutely holy. He consecrates himself as a sacrificial offering: as the priest set apart the sacrifice for the altar, Jesus sets himself apart for the cross. ''For their sakes'' (hyper autōn — on their behalf). ''That they also might be sanctified through the truth'' (hina ōsin kai autoi hēgiasmenoi en alētheia — so that they also may be sanctified in truth; perfect passive participle: completely and permanently set apart). The cross of Christ is the foundation of the sanctification of his people.',
   NULL),
  (20, 'Neither pray I for these alone, but for them also which shall believe on me through their word;',
   'Οὐ περὶ τούτων δὲ ἐρωτῶ μόνον ἀλλὰ καὶ περὶ τῶν πιστευόντων διὰ τοῦ λόγου αὐτῶν εἰς ἐμέ',
   'Ou peri toutōn de erōtō monon alla kai peri tōn pisteuontōn dia tou logou autōn eis eme',
   '''For them also which shall believe on me through their word'' (peri tōn pisteuontōn dia tou logou autōn eis eme — concerning those believing through their word into me; the present participle in a future sense: those who will believe). This verse is the most personal verse in the Bible for every Christian: Jesus names you in his prayer. The prayer of John 17:20-26 is prayed for every person who will ever come to faith through the apostolic gospel. Jesus prayed for you before you existed.',
   NULL),
  (21, 'That they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us: that the world may believe that thou hast sent me.',
   'ἵνα πάντες ἓν ὦσιν καθὼς σύ πάτερ ἐν ἐμοὶ κἀγὼ ἐν σοί ἵνα καὶ αὐτοὶ ἐν ἡμῖν ἓν ὦσιν ἵνα ὁ κόσμος πιστεύῃ ὅτι σύ με ἀπέστειλας',
   'hina pantes hen ōsin kathōs sy pater en emoi kagō en soi hina kai autoi en hēmin hen ōsin hina ho kosmos pisteuē hoti sy me apesteiles',
   '''That they all may be one'' (hina pantes hen ōsin — so that all may be one). The scope is universal: all believers of all times and places. ''One'' (hen — neuter: one thing, one reality; not heis/mia: one person). The unity is not organisational uniformity but spiritual oneness — the same kind of oneness that exists between Father and Son. ''That the world may believe'' (hina ho kosmos pisteuē) — the unity of the church is the apologetic argument for the truth of the gospel. A divided, unloving church denies what it proclaims; a unified, loving church validates it.',
   NULL),
  (22, 'And the glory which thou gavest me I have given them; that they may be one, even as we are one:',
   'κἀγὼ τὴν δόξαν ἣν δέδωκάς μοι δέδωκα αὐτοῖς ἵνα ὦσιν ἓν καθὼς ἡμεῖς ἕν ἐσμεν',
   'kagō tēn doxan hēn dedōkas moi dedōka autois hina ōsin hen kathōs hēmeis hen esmen',
   '''The glory which thou gavest me I have given them'' (tēn doxan hēn dedōkas moi dedōka autois — the glory which you have given me I have given them; both perfects: given and remain given). The doxa (glory) given to the disciples is the Spirit-given participation in the divine nature (2 Peter 1:4), the indwelling of Christ (Colossians 1:27: ''Christ in you, the hope of glory''), the transforming presence that makes them one. Glory is not a future possession only but a present reality that produces present unity.',
   NULL),
  (23, 'I in them, and thou in me, that they may be made perfect in one; and that the world may know that thou hast sent me, and hast loved them, as thou hast loved me.',
   'ἐγὼ ἐν αὐτοῖς καὶ σὺ ἐν ἐμοί ἵνα ὦσιν τετελειωμένοι εἰς ἕν καὶ ἵνα γινώσκῃ ὁ κόσμος ὅτι σύ με ἀπέστειλας καὶ ἠγάπησας αὐτοὺς καθὼς ἐμὲ ἠγάπησας',
   'egō en autois kai sy en emoi hina ōsin teteleōmenoi eis hen kai hina ginōskē ho kosmos hoti sy me apesteiles kai ēgapēsas autous kathōs eme ēgapēsas',
   '''Hast loved them, as thou hast loved me'' (ēgapēsas autous kathōs eme ēgapēsas — you have loved them just as you loved me). The staggering claim: the Father''s love for individual believers is the same in quality as his love for the eternal Son. This does not mean the Father''s love for us equals his love for the Son in degree (the Son is the eternal image of the invisible God); but it means the same agapē that binds Father and Son in eternal communion is extended to us through union with the Son (Romans 8:38-39; Ephesians 1:4-6).',
   NULL),
  (24, 'Father, I will that they also, whom thou hast given me, be with me where I am; that they may behold my glory, which thou hast given me: for thou lovedst me before the foundation of the world.',
   'Πάτερ ὃ δέδωκάς μοι θέλω ἵνα ὅπου εἰμὶ ἐγὼ κἀκεῖνοι ὦσιν μετ᾽ ἐμοῦ ἵνα θεωρῶσιν τὴν δόξαν τὴν ἐμήν ἣν δέδωκάς μοι ὅτι ἠγάπησάς με πρὸ καταβολῆς κόσμου',
   'Pater ho dedōkas moi thelō hina hopou eimi egō kakeinoi ōsin met emou hina theōrōsin tēn doxan tēn emēn hēn dedōkas moi hoti ēgapēsas me pro katabolēs kosmou',
   '''Father, I will'' (Pater, thelō — Father, I wish/I will; thelō expresses desire and will). Jesus does not say ''I ask'' (erōtō) here but ''I will'' — the language of co-equal will with the Father. ''That they may behold my glory'' (hina theōrōsin tēn doxan tēn emēn — so that they may behold/gaze upon my glory; theōreō: sustained, contemplative seeing). The ultimate purpose of salvation is the beholding and participation in Christ''s glory — not merely forgiveness but glorification (Romans 8:30; 1 John 3:2). ''Before the foundation of the world'' (pro katabolēs kosmou — before the laying down/founding of the world) — the love of the Father for the Son precedes creation, is eternal.',
   NULL),
  (25, 'O righteous Father, the world hath not known thee: but I have known thee, and these have known that thou hast sent me.',
   'Πάτερ δίκαιε καὶ ὁ κόσμος σε οὐκ ἔγνω ἐγὼ δέ σε ἔγνων καὶ οὗτοι ἔγνωσαν ὅτι σύ με ἀπέστειλας',
   'Pater dikaie kai ho kosmos se ouk egnō egō de se egnōn kai houtoi egnōsan hoti sy me apesteiles',
   '''O righteous Father'' (Pater dikaie — Righteous Father). The address appeals to the Father''s righteousness/justice as the ground for what follows — it is right that those who know the Son should receive the Father''s love. ''The world hath not known thee'' (ho kosmos se ouk egnō — the world did not know you; aorist: at the time of Christ''s coming, the world as a whole had not known God). The three-way distinction: the world (does not know the Father), Jesus (has known the Father perfectly), the disciples (have known that the Father sent the Son).',
   NULL),
  (26, 'And I have declared unto them thy name, and will declare it: that the love wherewith thou hast loved me may be in them, and I in them.',
   'καὶ ἐγνώρισα αὐτοῖς τὸ ὄνομά σου καὶ γνωρίσω ἵνα ἡ ἀγάπη ἣν ἠγάπησάς με ἐν αὐτοῖς ᾖ κἀγὼ ἐν αὐτοῖς',
   'kai egnōrisa autois to onoma sou kai gnōrisō hina hē agapē hēn ēgapēsas me en autois ē kagō en autois',
   '''I have declared... and will declare'' (egnōrisa... kai gnōrisō — I made known and will make known; past and future: the revelation of the Father''s name is both complete in the incarnation and continuing through the Spirit). The final clause of the High Priestly Prayer — the goal of everything: ''that the love wherewith thou hast loved me may be in them, and I in them'' (hina hē agapē hēn ēgapēsas me en autois ē kagō en autois). The destination of the prayer is the indwelling of divine love and the indwelling of Christ himself in every believer. The Trinity''s eternal love becomes the interior life of the redeemed. This is the telos of salvation: not merely pardon but participation — the love of the Father for the Son becomes the love circulating in the community of believers through the indwelling Christ.',
   NULL)
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'John' AND c.chapter_number = 17;

-- JOHN CHAPTER 17 — BACKFILL (word_studies + cross_references)

INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'ὥρα', 'hōra', 'G5610', 'Hour — in John, the appointed hour of the passion, glorification, and return to the Father (cf. 2:4; 7:30; 12:23; 13:1). The whole Gospel has been driving toward this hour.', 1),
  (1, 'δόξασον', 'doxason', 'G1392', 'Glorify (aorist imperative of doxazō) — the prayer that opens the High Priestly Prayer; mutual glorification of Father and Son through the cross.', 2),
  (1, 'υἱόν', 'huion', 'G5207', 'Son — the relational title central to the prayer: Son speaks to Father.', 3),
  (2, 'ἐξουσίαν', 'exousian', 'G1849', 'Authority — delegated sovereign right over all flesh (pasēs sarkos); echoes Daniel 7:14.', 4),
  (2, 'ζωὴν αἰώνιον', 'zōēn aiōnion', 'G2222/G166', 'Eternal life — in John, qualitative life of the age to come, possessed now by the believer (cf. v.3 definition).', 5),
  (3, 'γινώσκωσιν', 'ginōskōsin', 'G1097', 'May know (present subjunctive) — ongoing, experiential, relational knowing; John''s definition of eternal life.', 6),
  (3, 'μόνον ἀληθινὸν', 'monon alēthinon', 'G3441/G228', 'Only true — exclusive monotheism; alēthinos = real/genuine as opposed to false or shadowy.', 7),
  (3, 'ἀπέστειλας', 'apesteilas', 'G649', 'You sent (aorist of apostellō) — the sending formula that runs through John (4:34; 5:24; 20:21).', 8),
  (4, 'ἐδόξασα', 'edoxasa', 'G1392', 'I glorified (aorist) — Jesus speaks of the earthly mission as already accomplished; proleptic perfect tense of completion.', 9),
  (4, 'τελειώσας', 'teleiōsas', 'G5048', 'Having finished/completed — cognate to tetelestai (19:30); the work (ergon) is brought to its telos.', 10),
  (5, 'πρὸ τοῦ τὸν κόσμον εἶναι', 'pro tou ton kosmon einai', 'G4253/G2889', 'Before the world existed — pre-existent glory with the Father; affirms eternal personal pre-existence (cf. 1:1; Phil 2:6).', 11),
  (6, 'ἐφανέρωσα', 'ephanerōsa', 'G5319', 'I manifested/revealed — made the Father''s name (character, nature) visible through incarnation and ministry.', 12),
  (6, 'ὄνομά', 'onoma', 'G3686', 'Name — in Hebrew idiom, the self-revelation of God; Jesus reveals the Father''s very identity.', 13),
  (6, 'τετήρηκαν', 'tetērēkan', 'G5083', 'They have kept (perfect) — abiding obedience; tēreō is the prayer''s key verb (vv.11, 12, 15).', 14),
  (8, 'ῥήματα', 'rhēmata', 'G4487', 'Words/sayings — the spoken utterances Jesus has given; the disciples have received them.', 15),
  (9, 'ἐρωτῶ', 'erōtō', 'G2065', 'I ask/pray — the intercessory request; specifically for those given to him, not for the world at this point.', 16),
  (11, 'τήρησον αὐτοὺς ἐν τῷ ὀνόματί σου', 'tērēson autous en tō onomati sou', 'G5083/G3686', 'Keep them in your name — guard, watch over, preserve within the sphere of the Father''s revealed character.', 17),
  (11, 'ἓν', 'hen', 'G1520', 'One — the prayer for unity (hina ōsin hen, that they may be one) modeled on Father-Son oneness.', 18),
  (12, 'ἐτήρουν', 'etēroun', 'G5083', 'I was keeping (imperfect) — continuous guarding during the earthly ministry.', 19),
  (12, 'ἐφύλαξα', 'ephylaxa', 'G5442', 'I guarded (aorist of phylassō) — watchful protection; paired with tēreō.', 20),
  (12, 'υἱὸς τῆς ἀπωλείας', 'huios tēs apōleias', 'G5207/G684', 'Son of perdition/destruction — Semitic idiom for one belonging to ruin; applied to Judas here and to antichrist in 2 Thess 2:3.', 21),
  (13, 'χαράν', 'charan', 'G5479', 'Joy — the fullness of messianic joy imparted to the disciples even as Jesus departs.', 22),
  (14, 'κόσμος', 'kosmos', 'G2889', 'World — the fallen order in opposition to God; disciples are in it but not of it.', 23),
  (15, 'τοῦ πονηροῦ', 'tou ponērou', 'G4190', 'The evil one — personal evil, the devil (cf. Matt 6:13; 1 John 5:19); Jesus does not pray for removal but for protection.', 24),
  (17, 'ἁγίασον', 'hagiason', 'G37', 'Sanctify (aorist imperative of hagiazō) — set apart, consecrate; same root as hagios (holy).', 25),
  (17, 'ἀληθείᾳ', 'alētheia', 'G225', 'Truth — the sphere and instrument of sanctification; in John, truth is personal (14:6) and verbal (your word is truth).', 26),
  (17, 'λόγος', 'logos', 'G3056', 'Word — the Father''s revelation; the sanctifying agent.', 27),
  (18, 'ἀπέστειλα', 'apesteila', 'G649', 'I sent (aorist) — the apostolic commission prefigured; as the Father sent the Son, the Son sends them.', 28),
  (19, 'ἁγιάζω ἐμαυτόν', 'hagiazō emauton', 'G37/G1683', 'I sanctify myself — Jesus consecrates himself as the priestly sacrifice; OT cultic language applied to the cross.', 29),
  (19, 'ἡγιασμένοι', 'hēgiasmenoi', 'G37', 'Having been sanctified (perfect passive) — result state; disciples are set apart in truth through Christ''s self-consecration.', 30),
  (20, 'διὰ τοῦ λόγου αὐτῶν', 'dia tou logou autōn', 'G3056', 'Through their word — future believers will come to faith through the apostolic testimony; Jesus prays for the whole church.', 31),
  (21, 'ἓν ὦσιν', 'hen ōsin', 'G1520/G1510', 'May be one — subjunctive; the prayer''s central petition for ecclesial unity grounded in Trinitarian unity.', 32),
  (21, 'ἐν ἡμῖν', 'en hēmin', 'G1722', 'In us — believers'' oneness is participation in the Father-Son communion, not mere social unity.', 33),
  (22, 'δόξαν ἣν δέδωκάς μοι', 'doxan hēn dedōkas moi', 'G1391/G1325', 'The glory you have given me (perfect) — the glory of sonship shared with believers as enabling ground of unity.', 34),
  (23, 'τετελειωμένοι εἰς ἕν', 'teteleiōmenoi eis hen', 'G5048/G1520', 'Perfected into one (perfect passive) — brought to completion in unity; telic consummation of the church.', 35),
  (23, 'ἠγάπησας', 'ēgapēsas', 'G25', 'You loved (aorist) — the Father''s love for believers is identical in kind with his love for the Son.', 36),
  (24, 'θέλω', 'thelō', 'G2309', 'I will — not erōtō (ask) but thelō (will); co-equal volitional language of Son with Father.', 37),
  (24, 'θεωρῶσιν', 'theōrōsin', 'G2334', 'May behold (present subjunctive of theōreō) — sustained, contemplative seeing; the beatific vision of glory.', 38),
  (24, 'πρὸ καταβολῆς κόσμου', 'pro katabolēs kosmou', 'G2602/G2889', 'Before the foundation of the world — eternal intra-Trinitarian love preceding creation (cf. 1 Pet 1:20; Eph 1:4).', 39),
  (25, 'Πάτερ δίκαιε', 'Pater dikaie', 'G3962/G1342', 'Righteous Father — appeal to the Father''s justice as ground for the final petition; unique in NT.', 40),
  (26, 'ἐγνώρισα', 'egnōrisa', 'G1107', 'I made known — revealed, disclosed the Father''s name through the incarnation.', 41),
  (26, 'γνωρίσω', 'gnōrisō', 'G1107', 'I will make known (future) — continuing revelation of the Father through the Spirit and the church.', 42),
  (26, 'ἵνα ἡ ἀγάπη', 'hina hē agapē', 'G2443/G26', 'That the love — final purpose clause; Father''s love for Son becomes interior life of believers.', 43)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'John' AND c.chapter_number = 17 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'John 12:23', 1),
  (1, 'John 13:1', 2),
  (1, 'John 13:31-32', 3),
  (1, 'John 7:30', 4),
  (1, 'John 2:4', 5),
  (1, 'Philippians 2:9-11', 6),
  (2, 'Matthew 28:18', 1),
  (2, 'Daniel 7:14', 2),
  (2, 'John 5:27', 3),
  (2, 'John 6:37', 4),
  (2, 'John 10:28-29', 5),
  (3, 'John 3:15-16', 1),
  (3, '1 John 5:20', 2),
  (3, 'Jeremiah 31:34', 3),
  (3, 'Hosea 6:3', 4),
  (3, '1 Thessalonians 1:9', 5),
  (3, 'Philippians 3:8-10', 6),
  (4, 'John 19:30', 1),
  (4, 'John 4:34', 2),
  (4, 'John 5:36', 3),
  (4, 'Hebrews 10:7', 4),
  (5, 'John 1:1-2', 1),
  (5, 'John 1:14', 2),
  (5, 'Philippians 2:6-11', 3),
  (5, 'Colossians 1:15-17', 4),
  (5, 'Hebrews 1:3', 5),
  (5, 'Proverbs 8:22-31', 6),
  (6, 'John 17:26', 1),
  (6, 'Psalm 22:22', 2),
  (6, 'Hebrews 2:12', 3),
  (6, 'Exodus 3:13-15', 4),
  (7, 'John 16:30', 1),
  (8, 'John 3:34', 1),
  (8, 'John 12:49-50', 2),
  (8, 'John 16:27-30', 3),
  (9, '1 John 2:2', 1),
  (9, 'John 10:14-15', 2),
  (10, 'John 16:15', 1),
  (10, 'John 10:30', 2),
  (11, 'John 17:21-23', 1),
  (11, 'Ephesians 4:3-6', 2),
  (11, 'Romans 12:5', 3),
  (11, '1 Corinthians 12:12-13', 4),
  (11, 'Psalm 133:1', 5),
  (12, 'John 6:39', 1),
  (12, 'John 10:28-29', 2),
  (12, 'John 18:9', 3),
  (12, '2 Thessalonians 2:3', 4),
  (12, 'Psalm 41:9', 5),
  (12, 'John 13:18', 6),
  (13, 'John 15:11', 1),
  (13, 'John 16:24', 2),
  (13, '1 John 1:4', 3),
  (14, 'John 15:18-19', 1),
  (14, '1 John 3:13', 2),
  (14, 'John 8:23', 3),
  (15, 'Matthew 6:13', 1),
  (15, '2 Thessalonians 3:3', 2),
  (15, '1 John 5:18-19', 3),
  (15, 'Luke 22:31-32', 4),
  (16, 'John 15:19', 1),
  (16, 'John 8:23', 2),
  (17, 'Psalm 119:142', 1),
  (17, 'Psalm 119:160', 2),
  (17, 'Ephesians 5:26', 3),
  (17, '2 Timothy 3:16-17', 4),
  (17, 'James 1:18', 5),
  (17, '1 Peter 1:22-23', 6),
  (18, 'John 20:21', 1),
  (18, 'Matthew 28:18-20', 2),
  (18, 'John 4:38', 3),
  (19, 'Hebrews 10:10', 1),
  (19, 'Hebrews 10:14', 2),
  (19, 'Hebrews 9:12-14', 3),
  (19, 'Hebrews 2:11', 4),
  (19, '1 Corinthians 1:30', 5),
  (20, 'Romans 10:14-17', 1),
  (20, '1 Corinthians 3:5-7', 2),
  (20, 'Acts 2:41', 3),
  (20, 'Ephesians 2:20', 4),
  (21, 'John 10:38', 1),
  (21, 'John 14:10-11', 2),
  (21, '1 John 1:3', 3),
  (21, 'Ephesians 4:4-6', 4),
  (22, 'John 1:14', 1),
  (22, '2 Corinthians 3:18', 2),
  (22, 'Romans 8:29-30', 3),
  (23, 'Colossians 3:14', 1),
  (23, 'Ephesians 4:13', 2),
  (23, '1 John 4:17', 3),
  (23, 'John 13:35', 4),
  (24, 'John 12:26', 1),
  (24, 'John 14:3', 2),
  (24, '1 John 3:2', 3),
  (24, '1 Peter 1:20', 4),
  (24, 'Ephesians 1:4', 5),
  (24, '2 Corinthians 4:17', 6),
  (25, 'John 7:28-29', 1),
  (25, 'John 8:55', 2),
  (25, '1 John 3:1', 3),
  (25, '1 Corinthians 1:21', 4),
  (26, 'John 15:9', 1),
  (26, 'Romans 5:5', 2),
  (26, 'Romans 8:35-39', 3),
  (26, 'Ephesians 3:17-19', 4),
  (26, 'Colossians 1:27', 5),
  (26, 'Galatians 2:20', 6)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'John' AND c.chapter_number = 17 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
