-- John Chapter 21: The Appearance at the Sea of Tiberias; Peter's Restoration
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 21,
  'John 21 is an epilogue to the Gospel, set beside the Sea of Tiberias after the Resurrection. Seven disciples go fishing and toil all night without success. The risen Jesus appears on the shore unrecognised, directs a miraculous catch of 153 fish, and provides a breakfast of bread and fish at a charcoal fire — deliberately echoing the courtyard fire of Peter''s denials. After the meal Jesus puts three questions of love to Peter, matching his three denials, and commissions him to shepherd the flock. Jesus foretells Peter''s martyrdom and corrects a misunderstanding about the Beloved Disciple. The chapter closes with a testimony of the Beloved Disciple''s authorship and the famous hyperbole that the world itself could not contain all the books that might be written about Jesus.',
  'Restoration, commission, and the inexhaustible testimony of Jesus Christ. The risen Lord transforms failure into fruitfulness, replaces shame with love, and renews calling through gracious encounter. The epilogue grounds apostolic ministry in the experience of resurrection grace and anchors the Gospel in eyewitness testimony.',
  'ἀγαπάω / φιλέω (agapaō / phileō)',
  'To love (unconditional/covenantal love vs. warm affection) — the two Greek words at the heart of Jesus''s threefold question to Peter illuminate the depth, cost, and transforming power of love as the foundation of all pastoral ministry.',
  '["21:1–3 — Seven disciples return to fishing on the Sea of Tiberias", "21:4–8 — Jesus unrecognised on the shore; the miraculous catch", "21:9–14 — Breakfast at the charcoal fire; the third resurrection appearance", "21:15–17 — Threefold restoration of Peter: ''Feed my sheep''", "21:18–19 — Prophecy of Peter''s martyrdom; ''Follow me''", "21:20–23 — Peter asks about the Beloved Disciple; Jesus corrects the rumour", "21:24–25 — Authorial testimony and the world-filling testimony of Jesus"]'
FROM books b WHERE b.name = 'John';

INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1,
   'After these things Jesus shewed himself again to the disciples at the sea of Tiberias; and on this wise shewed he himself.',
   'Μετὰ ταῦτα ἐφανέρωσεν ἑαυτὸν πάλιν ὁ Ἰησοῦς τοῖς μαθηταῖς ἐπὶ τῆς θαλάσσης τῆς Τιβεριάδος· ἐφανέρωσεν δὲ οὕτως.',
   'Meta tauta ephanerōsen heauton palin ho Iēsous tois mathētais epi tēs thalassēs tēs Tiberiados; ephanerōsen de houtōs.',
   'The Sea of Tiberias is another name for the Sea of Galilee (6:1). Ephanerōsen (he manifested) is the same verb used in 1:31; 2:11 — each post-resurrection appearance is an act of divine self-disclosure, not merely a coincidence. The disciples have returned to Galilee as instructed (Mark 16:7), yet in the waiting they have resumed their former trade.',
   NULL),
  (2,
   'There were together Simon Peter, and Thomas called Didymus, and Nathanael of Cana in Galilee, and the sons of Zebedee, and two other of his disciples.',
   'ἦσαν ὁμοῦ Σίμων Πέτρος καὶ Θωμᾶς ὁ λεγόμενος Δίδυμος καὶ Ναθαναὴλ ὁ ἀπὸ Κανὰ τῆς Γαλιλαίας καὶ οἱ τοῦ Ζεβεδαίου καὶ ἄλλοι ἐκ τῶν μαθητῶν αὐτοῦ δύο.',
   'ēsan homou Simōn Petros kai Thōmas ho legomenos Didymos kai Nathanaēl ho apo Kana tēs Galilaias kai hoi tou Zebedaiou kai alloi ek tōn mathētōn autou dyo.',
   'Seven disciples are named — a symbolically complete number. Thomas, who had confessed "My Lord and my God" (20:28), is present; his doubt has been replaced with faith. Nathanael, the man "without guile" (1:47) who first confessed Jesus as Son of God and King of Israel, appears only here and in chapter 1, forming a literary bracket around the Gospel.',
   NULL),
  (3,
   'Simon Peter saith unto them, I go a fishing. They say unto him, We also go with thee. They went forth, and entered into a ship immediately; and that night they caught nothing.',
   'λέγει αὐτοῖς Σίμων Πέτρος· Ὑπάγω ἁλιεύειν. λέγουσιν αὐτῷ· Ἐρχόμεθα καὶ ἡμεῖς σύν σοι. ἐξῆλθον καὶ ἐνέβησαν εἰς τὸ πλοῖον, καὶ ἐν ἐκείνῃ τῇ νυκτὶ ἐπίασαν οὐδέν.',
   'legei autois Simōn Petros: Hypagō halieuein. legousin autō: Erchometha kai hēmeis syn soi. exēlthon kai enebēsan eis to ploion, kai en ekeinē tē nykti epiasen ouden.',
   'The return to fishing may reflect uncertainty about their future, not apostasy. Fishing was the natural livelihood of Galilean disciples. The fruitless night (epiasen ouden — they caught nothing) mirrors Luke 5:5, where Peter''s night of empty nets preceded his first miraculous call. The darkness of failure always precedes the dawn of resurrection grace.',
   NULL),
  (4,
   'But when the morning was now come, Jesus stood on the shore: but the disciples knew not that it was Jesus.',
   'Πρωΐας δὲ ἤδη γενομένης ἔστη Ἰησοῦς εἰς τὸν αἰγιαλόν· οὐ μέντοι ᾔδεισαν οἱ μαθηταὶ ὅτι Ἰησοῦς ἐστιν.',
   'Prōias de ēdē genomenēs estē Iēsous eis ton aigialon; ou mentoi ēdeisan hoi mathētai hoti Iēsous estin.',
   'Morning (prōias) — dawn light after a night of failure is a resurrection motif: Mary came "when it was yet dark" (20:1) and Jesus appeared at dawn. The disciples'' failure to recognise Jesus is consistent with other resurrection accounts (Luke 24:16; Matt. 28:17) and may reflect the transformed glory of the resurrection body, distance, or providential withholding.',
   NULL),
  (5,
   'Then Jesus saith unto them, Children, have ye any meat? They answered him, No.',
   'λέγει οὖν αὐτοῖς ὁ Ἰησοῦς· Παιδία, μή τι προσφάγιον ἔχετε; ἀπεκρίθησαν αὐτῷ· Οὔ.',
   'legei oun autois ho Iēsous: Paidia, mē ti prosphagion echete? apekrithēsan autō: Ou.',
   'Paidia (children/lads) is an affectionate address, used also in 1 John 2:14. Prosphagion (fish/meat — literally "something eaten with bread") is a colloquial fishing term. The one-word answer Ou (No) captures the blunt honesty of exhausted fishermen. Jesus asks knowing the answer, just as he asked Philip about bread before the feeding of the five thousand (6:5-6) — he tests to reveal.',
   NULL),
  (6,
   'And he said unto them, Cast the net on the right side of the ship, and ye shall find. They cast therefore, and now they were not able to draw it for the multitude of fishes.',
   'ὁ δὲ εἶπεν αὐτοῖς· Βάλετε εἰς τὰ δεξιὰ μέρη τοῦ πλοίου τὸ δίκτυον, καὶ εὑρήσετε. ἔβαλον οὖν, καὶ οὐκέτι αὐτὸ ἑλκύσαι ἴσχυον ἀπὸ τοῦ πλήθους τῶν ἰχθύων.',
   'ho de eipen autois: Balete eis ta dexia merē tou ploiou to diktyon, kai heurēsete. ebalon oun, kai ouketi auto helkysai ischyon apo tou plēthous tōn ichthyōn.',
   'Obedience to the stranger''s word produces miraculous abundance. The right side was conventionally the side of blessing in Jewish symbolism. Helkysai ischyon — they were not strong enough to haul it — the net full of great fish is a visible parable: apart from Christ, nothing; in obedience to his word, inexhaustible fruitfulness. Compare Luke 5:6 where the nets began to break — here the net holds (see v.11).',
   NULL),
  (7,
   'Therefore that disciple whom Jesus loved saith unto Peter, It is the Lord. Now when Simon Peter heard that it was the Lord, he girt his fisher''s coat unto him, (for he was naked,) and did cast himself into the sea.',
   'λέγει οὖν ὁ μαθητὴς ἐκεῖνος ὃν ἠγάπα ὁ Ἰησοῦς τῷ Πέτρῳ· Ὁ κύριός ἐστιν. Σίμων οὖν Πέτρος, ἀκούσας ὅτι ὁ κύριός ἐστιν, τὸν ἐπενδύτην διεζώσατο, ἦν γὰρ γυμνός, καὶ ἔβαλεν ἑαυτὸν εἰς τὴν θάλασσαν.',
   'legei oun ho mathētēs ekeinos hon ēgapa ho Iēsous tō Petrō: Ho kyrios estin. Simōn oun Petros, akousas hoti ho kyrios estin, ton ependytēn diezōsato, ēn gar gymnos, kai ebalen heauton eis tēn thalassan.',
   'The Beloved Disciple perceives first (as at the empty tomb, 20:8); Peter acts first — the two men embody complementary gifts of insight and impulsive love. Peter''s eagerness to reach Jesus at once — plunging into the sea rather than waiting for the boat — stands in poignant contrast to his denial. The man who once warmed himself at a fire while denying Jesus now cannot reach him fast enough.',
   NULL),
  (8,
   'And the other disciples came in a little ship; (for they were not far from land, but as it were two hundred cubits,) dragging the net with fishes.',
   'οἱ δὲ ἄλλοι μαθηταὶ τῷ πλοιαρίῳ ἦλθον, οὐ γὰρ ἦσαν μακρὰν ἀπὸ τῆς γῆς ἀλλὰ ὡς ἀπὸ πηχῶν διακοσίων, σύροντες τὸ δίκτυον τῶν ἰχθύων.',
   'hoi de alloi mathētai tō ploiariō ēlthon, ou gar ēsan makran apo tēs gēs alla hōs apo pēchōn diakosiōn, syrontes to diktyon tōn ichthyōn.',
   'Two hundred cubits is approximately 100 metres — close enough for the disciples to see Jesus clearly once Peter recognised him. Syrontes (dragging) emphasises the weight and abundance of the catch. The detail of the distance is the kind of eyewitness precision characteristic of the Beloved Disciple''s testimony throughout the Gospel.',
   NULL),
  (9,
   'As soon then as they were come to land, they saw a fire of coals there, and fish laid thereon, and bread.',
   'ὡς οὖν ἀπέβησαν εἰς τὴν γῆν, βλέπουσιν ἀνθρακιὰν κειμένην καὶ ὀψάριον ἐπικείμενον καὶ ἄρτον.',
   'hōs oun apebēsan eis tēn gēn, blepousin anthrakia n keimenen kai opsarion epikelmenon kai arton.',
   'Anthrakian (a charcoal fire) — this precise word appears only twice in the NT: here and in 18:18, where Peter warmed himself at a charcoal fire while denying Jesus. The deliberate echo is unmistakable: the same kind of fire now becomes the setting not of denial but of restoration. Jesus the Good Shepherd has already provided the meal — he does not need the disciples'' fish, but he graciously includes them.',
   NULL),
  (10,
   'Jesus saith unto them, Bring of the fish which ye have now caught.',
   'λέγει αὐτοῖς ὁ Ἰησοῦς· Ἐνέγκατε ἀπὸ τῶν ὀψαρίων ὧν ἐπιάσατε νῦν.',
   'legei autois ho Iēsous:Enegkate apo tōn opsariōn hōn epiasthe nyn.',
   'Although Jesus already has fish on the fire, he invites the disciples to bring their catch — incorporating their labour into his provision. This is the pattern of divine-human co-operation: God''s grace is not a substitute for human effort but its fulfilment and completion. The miracle of the full net and the meal at the fire together declare resurrection abundance.',
   NULL),
  (11,
   'Simon Peter went up, and drew the net to land full of great fishes, an hundred and fifty and three: and for all there were so many, yet was not the net broken.',
   'ἀνέβη οὖν Σίμων Πέτρος καὶ εἵλκυσεν τὸ δίκτυον εἰς τὴν γῆν μεστὸν ἰχθύων μεγάλων ἑκατὸν πεντήκοντα τριῶν· καὶ τοσούτων ὄντων οὐκ ἐσχίσθη τὸ δίκτυον.',
   'anebē oun Simōn Petros kai heilkysen to diktyon eis tēn gēn meston ichthyōn megalōn hekaton pentēkonta triōn; kai tosoutōn ontōn ouk eschisthē to diktyon.',
   '153 fish — the precise number has generated much theological reflection. Jerome noted that ancient naturalists counted 153 species of fish, suggesting the universal scope of the Gospel catch. Others see gematria (the number of "the sons of God" in Hebrew). Most importantly: the specificity is the mark of eyewitness testimony, and the unbroken net (ouk eschisthē) contrasts with Luke 5:6 — the resurrection community will hold together all whom Christ draws (compare 6:39; 10:28).',
   NULL),
  (12,
   'Jesus saith unto them, Come and dine. And none of the disciples durst ask him, Who art thou? knowing that it was the Lord.',
   'λέγει αὐτοῖς ὁ Ἰησοῦς· Δεῦτε ἀριστήσατε. οὐδεὶς δὲ ἐτόλμα τῶν μαθητῶν ἐξετάσαι αὐτόν· Σὺ τίς εἶ; εἰδότες ὅτι ὁ κύριός ἐστιν.',
   'legei autois ho Iēsous: Deute aristēsate. oudeis de etolma tōn mathētōn exetasai auton: Sy tis ei? eidotes hoti ho kyrios estin.',
   'Deute aristēsate — "Come, eat breakfast." The risen Lord hosts a meal: bread and fish by the sea, echoing the feeding of the multitude (6:11). Oudeis etolma — no one dared ask, "Who are you?" They knew, yet the knowledge defied articulation. The risen Christ inhabits a mode of being that is real and tangible (he has fish; he has bread) yet beyond full comprehension — known in the breaking of bread, as at Emmaus.',
   NULL),
  (13,
   'Jesus then cometh, and taketh bread, and giveth them; and fish likewise.',
   'ἔρχεται Ἰησοῦς καὶ λαμβάνει τὸν ἄρτον καὶ δίδωσιν αὐτοῖς, καὶ τὸ ὀψάριον ὁμοίως.',
   'erchetai Iēsous kai lambanei ton arton kai didōsin autois, kai to opsarion homoiōs.',
   'The action — taking bread and giving — mirrors 6:11 (the feeding of the five thousand) and the Last Supper. Every meal Jesus hosts is an acted parable of the Eucharist and of his role as the Bread of Life. The resurrection breakfast on the shore is both intimate and cosmic: the Lord of all creation serving breakfast to seven tired fishermen.',
   NULL),
  (14,
   'This is now the third time that Jesus shewed himself to his disciples, after that he was risen from the dead.',
   'τοῦτο ἤδη τρίτον ἐφανερώθη Ἰησοῦς τοῖς μαθηταῖς ἐγερθεὶς ἐκ νεκρῶν.',
   'touto ēdē triton ephanerōthē Iēsous tois mathētais egertheis ek nekrōn.',
   'The third appearance: to Mary (20:14-17), to the ten on the evening of Resurrection Day (20:19-23), and now to the seven at the sea. The number establishes the pattern and credibility of resurrection appearances. Egertheis ek nekrōn (having been raised from the dead) is the Pauline formula for resurrection, grounding the appearance in bodily resurrection.',
   NULL),
  (15,
   'So when they had dined, Jesus saith to Simon Peter, Simon, son of Jonas, lovest thou me more than these? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my lambs.',
   'Ὅτε οὖν ἠρίστησαν, λέγει τῷ Σίμωνι Πέτρῳ ὁ Ἰησοῦς· Σίμων Ἰωάννου, ἀγαπᾷς με πλέον τούτων; λέγει αὐτῷ· Ναί, κύριε, σὺ οἶδας ὅτι φιλῶ σε. λέγει αὐτῷ· Βόσκε τὰ ἀρνία μου.',
   'Hote oun ēristēsan, legei tō Simōni Petrō ho Iēsous: Simōn Iōannou, agapas me pleon toutōn? legei autō: Nai, kyrie, sy oidas hoti philō se. legei autō: Boske ta arnia mou.',
   'Jesus reverts to Peter''s pre-discipleship name Simon bar Jonah (Matt. 16:17) — the name of the man before the calling. Agapas me pleon toutōn — do you love me more than these? (more than the other disciples, or more than your nets/livelihood?) Peter had boasted superiority in love (13:37; Mark 14:29). Now he answers only with phileō — warm affection, not daring to claim the higher agapaō. Jesus accepts it and commissions: Boske ta arnia mou — Feed (tend, nourish) my lambs. The shepherd''s first duty is to the young and vulnerable.',
   NULL),
  (16,
   'He saith to him again the second time, Simon, son of Jonas, lovest thou me? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my sheep.',
   'λέγει αὐτῷ πάλιν δεύτερον· Σίμων Ἰωάννου, ἀγαπᾷς με; λέγει αὐτῷ· Ναί, κύριε, σὺ οἶδας ὅτι φιλῶ σε. λέγει αὐτῷ· Ποίμαινε τὰ πρόβατά μου.',
   'legei autō palin deuteron: Simōn Iōannou, agapas me? legei autō: Nai, kyrie, sy oidas hoti philō se. legei autō: Poimaine ta probata mou.',
   'The second question drops "more than these" — the comparison is removed. Agapas me still asks for the higher love. Peter''s answer is unchanged: phileō. The commission now is Poimaine ta probata — shepherd (govern, guide, protect) my sheep — a broader and more demanding role than simply feeding lambs. Each affirmation of love corresponds to a commission: pastoral leadership is grounded in love, not authority or achievement.',
   NULL),
  (17,
   'He saith unto him the third time, Simon, son of Jonas, lovest thou me? Peter was grieved because he said unto him the third time, Lovest thou me? And he said unto him, Lord, thou knowest all things; thou knowest that I love thee. Jesus saith unto him, Feed my sheep.',
   'λέγει αὐτῷ τὸ τρίτον· Σίμων Ἰωάννου, φιλεῖς με; ἐλυπήθη ὁ Πέτρος ὅτι εἶπεν αὐτῷ τὸ τρίτον· Φιλεῖς με; καὶ εἶπεν αὐτῷ· Κύριε, πάντα σὺ οἶδας, σὺ γινώσκεις ὅτι φιλῶ σε. λέγει αὐτῷ ὁ Ἰησοῦς· Βόσκε τὰ πρόβατά μου.',
   'legei autō to triton: Simōn Iōannou, phileis me? elypēthē ho Petros hoti eipen autō to triton: Phileis me? kai eipen autō: Kyrie, panta sy oidas, sy ginōskeis hoti philō se. legei autō ho Iēsous: Boske ta probata mou.',
   'The third question descends to Peter''s own word phileō — do you even love me in this lesser sense? Three questions for three denials. Peter is grieved (elypēthē) — the grief is itself the healing, the same grief that led him to weep bitterly (Luke 22:62). His answer now is surrender not self-assertion: Kyrie, panta sy oidas — Lord, you know all things. He appeals to the omniscience of Christ (who knows the heart) rather than his own protestations. The triple commission — feed/shepherd/feed — restores Peter to apostolic leadership through the surgery of love.',
   NULL),
  (18,
   'Verily, verily, I say unto thee, When thou wast young, thou girdedst thyself, and walkedst whither thou wouldest: but when thou shalt be old, thou shalt stretch forth thy hands, and another shall gird thee, and carry thee whither thou wouldest not.',
   'ἀμὴν ἀμὴν λέγω σοι, ὅτε ἦς νεώτερος, ἐζώννυες σεαυτὸν καὶ περιεπάτεις ὅπου ἤθελες· ὅταν δὲ γηράσῃς, ἐκτενεῖς τὰς χεῖράς σου, καὶ ἄλλος σε ζώσει καὶ οἴσει ὅπου οὐ θέλεις.',
   'amēn amēn legō soi, hote ēs neōteros, ezōnnyes seauton kai periepateis hopou ētheles; hotan de gērasēs, ekteneis tas cheiras sou, kai allos se zōsei kai oisei hopou ou theleis.',
   'The amen-amen formula introduces a solemn prophetic word. Young freedom versus old constraint is a proverb of life. But ekteneis tas cheiras sou — you will stretch out your hands — is the posture of crucifixion. Tradition uniformly records that Peter was crucified in Rome (under Nero, c. AD 64-68), reportedly upside down at his own request, to distinguish his death from his Lord''s. The prophecy transforms Peter''s martyrdom into the ultimate expression of the love he had just confessed.',
   NULL),
  (19,
   'This spake he, signifying by what death he should glorify God. And when he had spoken this, he saith unto him, Follow me.',
   'τοῦτο δὲ εἶπεν σημαίνων ποίῳ θανάτῳ δοξάσει τὸν θεόν. καὶ τοῦτο εἰπὼν λέγει αὐτῷ· Ἀκολούθει μοι.',
   'touto de eipen sēmainōn poiō thanatō doxasei ton theon. kai touto eipōn legei autō: Akolouthei moi.',
   'The narrator''s comment sēmainōn (signifying) is the same verb used to interpret the manner of Jesus'' own death (12:33; 18:32). Peter''s martyrdom will be a doxological act — glorifying God. Then comes the simplest and most profound of all commands: Akolouthei moi — Follow me. These were Jesus'' first words to Peter on the shore of the same sea (Mark 1:17; Matt. 4:19). Now they are his last. The entire arc of discipleship is contained in this call: follow me, even to the cross.',
   NULL),
  (20,
   'Then Peter, turning about, seeth the disciple whom Jesus loved following; which also leaned on his breast at supper, and said, Lord, which is he that betrayeth thee?',
   'Ἐπιστραφεὶς δὲ ὁ Πέτρος βλέπει τὸν μαθητὴν ὃν ἠγάπα ὁ Ἰησοῦς ἀκολουθοῦντα, ὃς καὶ ἀνέπεσεν ἐν τῷ δείπνῳ ἐπὶ τὸ στῆθος αὐτοῦ καὶ εἶπεν· Κύριε, τίς ἐστιν ὁ παραδιδούς σε;',
   'Epistrepheis de ho Petros blepei ton mathētēn hon ēgapa ho Iēsous akolouthounta, hos kai anepesen en tō deipnō epi to stēthos autou kai eipen: Kyrie, tis estin ho paradidous se?',
   'Peter turns and sees the Beloved Disciple — already following Jesus, without being commanded. The identification by reference to 13:23-25 (leaning on Jesus'' breast at the supper, asking about the betrayer) is the evangelist''s self-identification signature. The question Peter is about to ask arises from a perfectly human impulse: if my path leads to the cross, what about his?',
   NULL),
  (21,
   'Peter seeing him saith to Jesus, Lord, and what shall this man do?',
   'τοῦτον οὖν ἰδὼν ὁ Πέτρος λέγει τῷ Ἰησοῦ· Κύριε, οὗτος δὲ τί;',
   'touton oun idōn ho Petros legei tō Iēsou: Kyrie, houtos de ti?',
   'Kyrie, houtos de ti? — Lord, but what about this man? The question is entirely natural and entirely beside the point. Jesus had just given Peter his entire calling and destiny; Peter''s first instinct is to look sideways at another disciple''s path. The question represents the perennial human temptation to compare our calling and cost with another''s rather than simply following.',
   NULL),
  (22,
   'Jesus saith unto him, If I will that he tarry till I come, what is that to thee? follow thou me.',
   'λέγει αὐτῷ ὁ Ἰησοῦς· Ἐὰν αὐτὸν θέλω μένειν ἕως ἔρχομαι, τί πρὸς σέ; σύ μοι ἀκολούθει.',
   'legei autō ho Iēsous: Ean auton thelō menein heōs erchomai, ti pros se? sy moi akolouthei.',
   'Jesus'' answer is gently decisive: "What is that to you?" (ti pros se — what is it to you?) Each disciple''s calling is sovereign and particular. The conditional — if I will that he remain until I come — is not a promise but a hypothetical. The emphasis falls on the repeated command: sy moi akolouthei — you, follow me. The second person pronoun is emphatic: whatever others'' paths, yours is simply to follow. This is the charter of individual Christian vocation.',
   NULL),
  (23,
   'Then went this saying abroad among the brethren, that that disciple should not die: yet Jesus said not unto him, He shall not die; but, If I will that he tarry till I come, what is that to thee?',
   'ἐξῆλθεν οὖν οὗτος ὁ λόγος εἰς τοὺς ἀδελφοὺς ὅτι ὁ μαθητὴς ἐκεῖνος οὐκ ἀποθνῄσκει· οὐκ εἶπεν δὲ αὐτῷ ὁ Ἰησοῦς ὅτι οὐκ ἀποθνῄσκει, ἀλλ''· Ἐὰν αὐτὸν θέλω μένειν ἕως ἔρχομαι, τί πρὸς σέ;',
   'exēlthen oun houtos ho logos eis tous adelphous hoti ho mathētēs ekeinos ouk apothnēskei; ouk eipen de autō ho Iēsous hoti ouk apothnēskei, all'': Ean auton thelō menein heōs erchomai, ti pros se?',
   'The narrator corrects a misunderstanding that had circulated in the early church. This pastoral clarification suggests that the Beloved Disciple had by the time of writing reached extreme old age (or had died), making the correction urgent. The narrator''s care to distinguish what Jesus said from what was inferred demonstrates the Gospel''s commitment to accurate testimony over comforting legend.',
   NULL),
  (24,
   'This is the disciple which testifieth of these things, and wrote these things: and we know that his testimony is true.',
   'Οὗτός ἐστιν ὁ μαθητὴς ὁ μαρτυρῶν περὶ τούτων καὶ ὁ γράψας ταῦτα, καὶ οἴδαμεν ὅτι ἀληθὴς αὐτοῦ ἡ μαρτυρία ἐστίν.',
   'Houtos estin ho mathētēs ho martyrōn peri toutōn kai ho grapsas tauta, kai oidamen hoti alēthēs autou hē martyria estin.',
   'The colophon of the Gospel. Ho martyrōn — the one who testifies — is present tense, suggesting ongoing living witness or the enduring authority of written testimony. Ho grapsas tauta — who wrote these things — identifies the Beloved Disciple as the author. The we (oidamen — we know) may be the Johannine community or elders who attest the testimony. Alēthēs hē martyria — the testimony is true — is the community''s imprimatur, echoing Pilate''s unwitting "What is truth?" (18:38) with the answer: this.',
   NULL),
  (25,
   'And there are also many other things which Jesus did, the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written. Amen.',
   'Ἔστιν δὲ καὶ ἄλλα πολλὰ ἃ ἐποίησεν ὁ Ἰησοῦς, ἅτινα ἐὰν γράφηται καθ'' ἕν, οὐδ'' αὐτὸν οἶμαι τὸν κόσμον χωρῆσαι τὰ γραφόμενα βιβλία. ἀμήν.',
   'Estin de kai alla polla ha epoiēsen ho Iēsous, hatina ean graphētai kath'' hen, oud'' auton oimai ton kosmon chōrēsai ta graphomena biblia. amēn.',
   'The Gospel''s final word is an extravagant hyperbole worthy of its subject. Chōrēsai — contain, hold — the world itself could not hold the books. This is not bibliographic claim but theological doxology: the life of the eternal Word made flesh is inexhaustible, beyond all human capacity to record or comprehend. Every generation''s meditation on Christ fills more volumes; yet he exceeds them all. The closing Amen is the reader''s response — so let it be — to the testimony of the one who is the way, the truth, and the life.',
   NULL)
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'John' AND c.chapter_number = 21;
