-- ═══════════════════════════════════════════════════
-- JOHN CHAPTER 15 — The True Vine, Abiding, and the World's Hatred
-- 27 verses · Greek text · Word studies · Cross-refs
-- ═══════════════════════════════════════════════════

-- Step 1: Insert chapter metadata
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 15,
  'John 15 continues the Upper Room Discourse, possibly spoken as Jesus and the disciples walked toward Gethsemane (14:31). It opens with the seventh and final ''I AM'' declaration: ''I am the true vine, and my Father is the husbandman'' (v.1). The vine was a central symbol of Israel in the Old Testament (Psalm 80:8-16; Isaiah 5:1-7; Jeremiah 2:21; Ezekiel 15; Hosea 10:1) — Israel was God''s vine, called to bear fruit but consistently failing. Jesus now declares himself the true (alēthinos — genuine, authentic) vine, the fulfilment of all that Israel was meant to be. The disciples are the branches: apart from Christ they can do nothing (v.5); connected to him, they bear much fruit (v.5). The key word of the passage is ''abide'' (menō — to remain, dwell, continue) — appearing 11 times in vv.1-11. Branches that do not bear fruit are removed; those that bear fruit are pruned to bear more (vv.2-3). The Father is glorified by much fruit (v.8). Jesus then deepens the relationship: no longer servants but friends, chosen by him, appointed to bear fruit that remains (vv.15-16). The second half of the chapter (vv.18-27) warns about the world''s hatred: as the world hated Christ, it will hate his disciples (v.18). The disciples are not of the world (v.19); the servant is not greater than the master (v.20). This hatred fulfils Scripture: ''They hated me without a cause'' (Psalm 35:19; 69:4). The Paraclete (the Spirit of truth) will testify about Christ, and so will the disciples (vv.26-27).',
  'Abide in Me — Union with Christ as the Source of Fruitfulness',
  'μένω (menō)',
  'To remain, abide, dwell, stay — the central verb of John 15, appearing 11 times in vv.1-11. It describes the continuous, settled, vital union between the branch and the vine, the disciple and Christ. ''Menō'' in John consistently denotes a permanent, relational, life-giving connection: the Son abides in the Father''s love (v.10), the disciples are to abide in the Son (v.4), the Son abides in the disciples (v.5), the word abides in them (v.7), they abide in his love (v.9). Abiding is not passive but active: it involves keeping his commandments (v.10), being cleansed by his word (v.3), and bearing fruit. The alternative to abiding is withering — the branch cut off dries up (v.6). Christian life is not an event but an abiding relationship.',
  '["The True Vine (vv.1-3): I am the true vine and my Father is the husbandman. Every branch in me that beareth not fruit he taketh away and every branch that beareth fruit he purgeth it that it may bring forth more fruit. Now ye are clean through the word which I have spoken unto you","Abide in Me (vv.4-8): Abide in me and I in you. As the branch cannot bear fruit of itself except it abide in the vine no more can ye except ye abide in me. I am the vine ye are the branches He that abideth in me and I in him the same bringeth forth much fruit for without me ye can do nothing. If a man abide not in me he is cast forth as a branch and is withered and men gather them and cast them into the fire and they are burned. If ye abide in me and my words abide in you ye shall ask what ye will and it shall be done unto you. Herein is my Father glorified that ye bear much fruit so shall ye be my disciples","Love One Another (vv.9-17): As the Father hath loved me so have I loved you continue ye in my love. If ye keep my commandments ye shall abide in my love even as I have kept my Father''s commandments and abide in his love. These things have I spoken unto you that my joy might remain in you and that your joy might be full. This is my commandment That ye love one another as I have loved you. Greater love hath no man than this that a man lay down his life for his friends. Ye are my friends if ye do whatsoever I command you. Henceforth I call you not servants for the servant knoweth not what his lord doeth but I have called you friends for all things that I have heard of my Father I have made known unto you. Ye have not chosen me but I have chosen you and ordained you that ye should go and bring forth fruit and that your fruit should remain that whatsoever ye shall ask of the Father in my name he may give it you. These things I command you that ye love one another","The World''s Hatred (vv.18-27): If the world hate you ye know that it hated me before it hated you. If ye were of the world the world would love his own but because ye are not of the world but I have chosen you out of the world therefore the world hateth you. Remember the word that I said unto you The servant is not greater than his lord. If they have persecuted me they will also persecute you if they have kept my saying they will keep yours also. But all these things will they do unto you for my name''s sake because they know not him that sent me. If I had not come and spoken unto them they had not had sin but now they have no cloke for their sin. He that hateth me hateth my Father also. If I had not done among them the works which none other man did they had not had sin but now have they both seen and hated both me and my Father. But this cometh to pass that the word might be fulfilled that is written in their law They hated me without a cause. But when the Comforter is come whom I will send unto you from the Father even the Spirit of truth which proceedeth from the Father he shall testify of me and ye also shall bear witness because ye have been with me from the beginning"]'
FROM books b WHERE b.name = 'John';

-- Step 2: Insert all 27 verses
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'I am the true vine, and my Father is the husbandman.',
   'Ἐγώ εἰμι ἡ ἄμπελος ἡ ἀληθινή καὶ ὁ πατήρ μου ὁ γεωργός ἐστιν',
   'Egō eimi hē ampelos hē alēthinē kai ho patēr mou ho geōrgos estin',
   '''I am the true vine'' (Egō eimi hē ampelos hē alēthinē) — the seventh and final of John''s great ''I AM'' declarations. ''True'' (alēthinē — genuine, authentic, real, as opposed to shadow or type). The vine was the pre-eminent symbol of Israel: Psalm 80:8 (''Thou hast brought a vine out of Egypt''); Isaiah 5:1-7 (the song of the vineyard); Jeremiah 2:21 (''I had planted thee a noble vine, wholly a right seed: how then art thou turned into the degenerate plant of a strange vine?''). Israel was God''s vine but failed to bear fruit. Jesus is the true vine — what Israel was called to be, now perfectly embodied. ''The husbandman'' (ho geōrgos — the farmer, vinedresser, one who works the earth). God the Father tends the vine with the same care and purpose as a devoted vinedresser.',
   NULL),
  (2, 'Every branch in me that beareth not fruit he taketh away: and every branch that beareth fruit, he purgeth it, that it may bring forth more fruit.',
   'πᾶν κλῆμα ἐν ἐμοὶ μὴ φέρον καρπόν αἴρει αὐτό καὶ πᾶν τὸ καρπὸν φέρον καθαίρει αὐτό ἵνα καρπὸν πλείονα φέρῃ',
   'pan klēma en emoi mē pheron karpon airei auto kai pan to karpon pheron kathairei auto hina karpon pleiona pherē',
   '''Every branch in me that beareth not fruit he taketh away'' (airei auto — lifts it away/removes it). ''Airei'' can mean ''lifts up'' (as a vinedresser lifts trailing branches off the ground to expose them to sun, a common viticulture practice) or ''takes away/removes.'' In context, the contrast with the fruitful branch that is ''purged'' (kept but cleaned) suggests ''removes'' is the primary meaning. The fruitless branch faces removal; the fruitful branch faces pruning (kathairo — to cleanse, purify, prune). The same Greek root as ''clean'' (katharos, v.3; 13:10). Pruning is a sign of being in the vine, not of rejection.',
   NULL),
  (3, 'Now ye are clean through the word which I have spoken unto you.',
   'ἤδη ὑμεῖς καθαροί ἐστε διὰ τὸν λόγον ὃν λελάληκα ὑμῖν',
   'ēdē hymeis katharoi este dia ton logon hon lelalēka hymin',
   '''Ye are clean'' (katharoi este — you are already clean; the same root as ''purgeth/prunes'': kathairo). Jesus is playing on the double meaning: the disciples are already pruned/cleansed through the word. The word of Christ is the pruning agent — it cuts away false ideas, sinful patterns, misplaced loyalties. ''Through the word which I have spoken unto you'' (dia ton logon hon lelalēka hymin — through the word I have spoken; perfect tense: word already spoken with ongoing effect). The scripture, the teaching of Jesus, cleanses (Ephesians 5:26; Psalm 119:9).',
   NULL),
  (4, 'Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in me.',
   'μείνατε ἐν ἐμοί κἀγὼ ἐν ὑμῖν καθὼς τὸ κλῆμα οὐ δύναται καρπὸν φέρειν ἀφ᾽ ἑαυτοῦ ἐὰν μὴ μένῃ ἐν τῇ ἀμπέλῳ οὕτως οὐδὲ ὑμεῖς ἐὰν μὴ ἐν ἐμοὶ μένητε',
   'meinate en emoi kagō en hymin kathōs to klēma ou dynatai karpon pherein aph heautou ean mē menē en tē ampelō houtōs oude hymeis ean mē en emoi menēte',
   '''Abide in me'' (meinate en emoi — remain in me; aorist imperative: a decisive act of settling into union with Christ). The branch does not remain in the vine by striving; it remains by not separating itself. The metaphor describes organic union: the branch''s life-sap comes entirely from the vine. Severed, it cannot function. So the disciple''s spiritual fruitfulness comes entirely from union with Christ — not from human effort, education, or willpower. ''No more can ye, except ye abide in me'' — the impossibility is absolute. Fruitfulness without connection to Christ is as impossible as a branch bearing grapes without the vine.',
   NULL),
  (5, 'I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.',
   'ἐγώ εἰμι ἡ ἄμπελος ὑμεῖς τὰ κλήματα ὁ μένων ἐν ἐμοὶ κἀγὼ ἐν αὐτῷ οὗτος φέρει καρπὸν πολύν ὅτι χωρὶς ἐμοῦ οὐ δύνασθε ποιεῖν οὐδέν',
   'egō eimi hē ampelos hymeis ta klēmata ho menōn en emoi kagō en autō houtos pherei karpon polun hoti chōris emou ou dynasthe poiein ouden',
   '''Without me ye can do nothing'' (chōris emou ou dynasthe poiein ouden — apart from me you are able to do nothing). ''Chōris'' (apart from, separate from) — not ''without my help'' but ''severed from me, disconnected from me.'' ''Nothing'' (ouden) — absolute zero. This is one of the most radical statements of spiritual dependence in all of Scripture. Paul echoes it: ''I can do all things through Christ which strengtheneth me'' (Philippians 4:13) — the other side of the same coin. Human effort without vital union with Christ produces, spiritually speaking, nothing of eternal value (1 Corinthians 3:12-15).',
   NULL),
  (6, 'If a man abide not in me, he is cast forth as a branch, and is withered; and men gather them, and cast them into the fire, and they are burned.',
   'ἐὰν μή τις μένῃ ἐν ἐμοί ἐβλήθη ἔξω ὡς τὸ κλῆμα καὶ ἐξηράνθη καὶ συνάγουσιν αὐτὰ καὶ εἰς τὸ πῦρ βάλλουσιν καὶ καίεται',
   'ean mē tis menē en emoi eblēthē exō hōs to klēma kai exēranthē kai synagousin auta kai eis to pyr ballousin kai kainetai',
   '''Cast forth as a branch, and is withered'' (eblēthē exō hōs to klēma kai exēranthē — was cast outside as the branch and withered; the aorist ''was cast'' treats the future event as already accomplished). ''Cast into the fire'' (eis to pyr ballousin) — the image of judgment echoes Matthew 3:10; 7:19 (''cut down and cast into the fire''). The withered branch is useless for any purpose except burning. The warning is solemn: persistent non-abiding leads to judgment. The passage raises difficult questions about whether ''branches in me'' can ultimately be lost — the pastoral context is a warning to persevere, not a theological treatise on perseverance.',
   NULL),
  (7, 'If ye abide in me, and my words abide in you, ye shall ask what ye will, and it shall be done unto you.',
   'ἐὰν μείνητε ἐν ἐμοὶ καὶ τὰ ῥήματά μου ἐν ὑμῖν μείνῃ ὃ ἐὰν θέλητε αἰτήσασθε καὶ γενήσεται ὑμῖν',
   'ean meinēte en emoi kai ta rhēmata mou en hymin meinē ho ean thelēte aitēsasthe kai genēsetai hymin',
   '''Ask what ye will, and it shall be done unto you'' (ho ean thelēte aitēsasthe kai genēsetai hymin — whatever you wish, ask and it will happen for you). The promise of answered prayer here has two conditions: abiding in Christ, and his words abiding in us. When the words of Christ dwell richly in us (Colossians 3:16), our desires are shaped by his desires; what we ''will'' aligns with what he wills. This is not a blank cheque for selfish prayer but the promise of effective prayer for those deeply formed by Christ''s word.',
   NULL),
  (8, 'Herein is my Father glorified, that ye bear much fruit; so shall ye be my disciples.',
   'ἐν τούτῳ ἐδοξάσθη ὁ πατήρ μου ἵνα καρπὸν πολὺν φέρητε καὶ γενήσεσθε ἐμοὶ μαθηταί',
   'en toutō edoxasthē ho patēr mou hina karpon polun phērēte kai genēsesthe emoi mathētai',
   '''My Father is glorified that ye bear much fruit'' (edoxasthē ho patēr mou — my Father was/is glorified; aorist of certainty). God''s glory — his visible splendour — is displayed in fruitful disciples. The fruitful life is a theophany: it shows the world what God is like. ''So shall ye be my disciples'' (genēsesthe emoi mathētai — you will become/prove to be my disciples). Fruit is not the condition of discipleship but its evidence and proof. As in 13:35 (love is the mark), here fruit is the mark.',
   NULL),
  (9, 'As the Father hath loved me, so have I loved you: continue ye in my love.',
   'καθὼς ἠγάπησέν με ὁ πατήρ κἀγὼ ὑμᾶς ἠγάπησα μείνατε ἐν τῇ ἀγάπῃ τῇ ἐμῇ',
   'kathōs ēgapēsen me ho patēr kagō hymas ēgapēsa meinate en tē agapē tē emē',
   '''As the Father hath loved me, so have I loved you'' (kathōs ēgapēsen me ho patēr, kagō hymas ēgapēsa) — the love between Father and Son is the measure and model of Christ''s love for the disciples. ''Continue ye in my love'' (meinate en tē agapē tē emē — remain in my love; the imperative form of menō). The disciple does not generate love for Christ from their own resources but remains in the love already extended to them by Christ. Love is the atmosphere of abiding.',
   NULL),
  (10, 'If ye keep my commandments, ye shall abide in my love; even as I have kept my Father''s commandments, and abide in his love.',
   'ἐὰν τὰς ἐντολάς μου τηρήσητε μενεῖτε ἐν τῇ ἀγάπῃ μου καθὼς ἐγὼ τοῦ πατρός μου τὰς ἐντολὰς τετήρηκα καὶ μένω αὐτοῦ ἐν τῇ ἀγάπῃ',
   'ean tas entolas mou tērēsēte meneite en tē agapē mou kathōs egō tou patros mou tas entolas tetērēka kai menō autou en tē agapē',
   '''Even as I have kept my Father''s commandments, and abide in his love'' — Jesus''s own obedience to the Father is the pattern for the disciples'' obedience to him. The Son modelled perfect filial obedience; the disciples are called to the same. The connection between commandment-keeping and abiding in love is not legalistic but relational: obedience is the expression of love, and love is the context of obedience. The Father''s love for the Son did not depend on the Son''s obedience but found its expression through it.',
   NULL),
  (11, 'These things have I spoken unto you, that my joy might remain in you, and that your joy might be full.',
   'ταῦτα λελάληκα ὑμῖν ἵνα ἡ χαρὰ ἡ ἐμὴ ἐν ὑμῖν μείνῃ καὶ ἡ χαρὰ ὑμῶν πληρωθῇ',
   'tauta lelalēka hymin hina hē chara hē emē en hymin meinē kai hē chara hymōn plērōthē',
   '''That my joy might remain in you'' (hē chara hē emē en hymin meinē — my joy may remain in you). Jesus speaks of his joy (hē chara hē emē — the definite, emphatic ''my'' joy) — the joy of the Son in his relationship with the Father, the joy of obedient love, the joy of doing the Father''s will even through suffering (Hebrews 12:2: ''who for the joy that was set before him endured the cross''). ''That your joy might be full'' (plērōthē — might be filled up completely). Christ''s joy transmitted into the disciples produces joy that is full — not partial, not occasional, but complete (cf. 16:24; 1 John 1:4; 2 John 12).',
   NULL),
  (12, 'This is my commandment, That ye love one another, as I have loved you.',
   'αὕτη ἐστὶν ἡ ἐντολὴ ἡ ἐμή ἵνα ἀγαπᾶτε ἀλλήλους καθὼς ἠγάπησα ὑμᾶς',
   'hautē estin hē entolē hē emē hina agapate allēlous kathōs ēgapēsa hymas',
   '''This is my commandment'' (hautē estin hē entolē hē emē — this is the commandment, my commandment; the definite article and possessive make it singular and supreme). The one commandment that encompasses all others is mutual love after the pattern of Christ''s love. Repeated from 13:34 but now deepened: there the standard was ''as I have loved you''; here in context the standard is immediately defined as the greatest love — laying down one''s life (v.13).',
   NULL),
  (13, 'Greater love hath no man than this, that a man lay down his life for his friends.',
   'μείζονα ταύτης ἀγάπην οὐδεὶς ἔχει ἵνα τις τὴν ψυχὴν αὐτοῦ θῇ ὑπὲρ τῶν φίλων αὐτοῦ',
   'meizona tautēs agapēn oudeis echei hina tis tēn psychēn autou thē hyper tōn philōn autou',
   '''Greater love hath no man than this, that a man lay down his life for his friends'' (meizona tautēs agapēn oudeis echei — no one has greater love than this). ''Lay down his life'' (tēn psychēn autou thē — put down his soul/life; the same verb as 10:11,17,18: the Good Shepherd laying down his life). The superlative of love is self-sacrifice for another. Jesus is both defining the ultimate love and announcing what he is about to do — he is the one who lays down his life for his friends. Paul extends the wonder: ''God commendeth his love toward us, in that, while we were yet sinners, Christ died for us'' (Romans 5:8) — not even for friends, but for enemies.',
   NULL),
  (14, 'Ye are my friends, if ye do whatsoever I command you.',
   'ὑμεῖς φίλοι μού ἐστε ἐὰν ποιῆτε ἃ ἐγὼ ἐντέλλομαι ὑμῖν',
   'hymeis philoi mou este ean poiēte ha egō entellomai hymin',
   '''Ye are my friends'' (hymeis philoi mou este — you are my friends). Abraham was called ''the Friend of God'' (Isaiah 41:8; James 2:23) — now the disciples are given that same title. ''If ye do whatsoever I command you'' — the condition is not the cause of friendship (Jesus has already chosen them, v.16) but the expression and evidence of it. Friends of Jesus are distinguished from servants (v.15) not by absence of obedience but by having been taken into his confidence.',
   NULL),
  (15, 'Henceforth I call you not servants; for the servant knoweth not what his lord doeth: but I have called you friends; for all things that I have heard of my Father I have made known unto you.',
   'οὐκέτι λέγω ὑμᾶς δούλους ὅτι ὁ δοῦλος οὐκ οἶδεν τί ποιεῖ αὐτοῦ ὁ κύριος ὑμᾶς δὲ εἴρηκα φίλους ὅτι πάντα ἃ ἤκουσα παρὰ τοῦ πατρός μου ἐγνώρισα ὑμῖν',
   'ouketi legō hymas doulous hoti ho doulos ouk oiden ti poiei autou ho kyrios hymas de eirēka philous hoti panta ha ēkousa para tou patros mou egnōrisa hymin',
   '''Henceforth I call you not servants'' (ouketi legō hymas doulous — no longer do I call you slaves). A slave obeys without knowing the master''s plans; a friend is taken into confidence. ''I have made known unto you'' (egnōrisa hymin — I made known to you; aorist: the disclosure is complete). The disciples have been given access to the Father''s purposes — the mystery hidden through ages is now revealed (Ephesians 3:3-6; Colossians 1:26-27). This is unprecedented intimacy: the eternal Son sharing the Father''s counsels with mortal friends.',
   NULL),
  (16, 'Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain: that whatsoever ye shall ask of the Father in my name, he may give it you.',
   'οὐχ ὑμεῖς με ἐξελέξασθε ἀλλ᾽ ἐγὼ ἐξελεξάμην ὑμᾶς καὶ ἔθηκα ὑμᾶς ἵνα ὑμεῖς ὑπάγητε καὶ καρπὸν φέρητε καὶ ὁ καρπὸς ὑμῶν μένῃ ἵνα ὅ τι ἂν αἰτήσητε τὸν πατέρα ἐν τῷ ὀνόματί μου δῷ ὑμῖν',
   'ouch hymeis me exelexasthe all egō exelexamēn hymas kai ethēka hymas hina hymeis hypagēte kai karpon phērēte kai ho karpos hymōn menē hina ho ti an aitēsēte ton patera en tō onomati mou dō hymin',
   '''Ye have not chosen me, but I have chosen you'' (ouch hymeis me exelexasthe, all egō exelexamēn hymas) — the priority of divine election. In the Jewish world, disciples chose their rabbi; here the Rabbi chose his disciples. ''Ordained you'' (ethēka hymas — appointed/placed you; ethēka: I placed, set). The purpose: ''that your fruit should remain'' (ho karpos hymōn menē — your fruit may remain; eternal fruit, fruit of lasting significance). The word menē (remain) ties back to the abiding theme of vv.4-11: fruit that remains is fruit produced by abiding.',
   NULL),
  (17, 'These things I command you, that ye love one another.',
   'ταῦτα ἐντέλλομαι ὑμῖν ἵνα ἀγαπᾶτε ἀλλήλους',
   'tauta entellomai hymin hina agapate allēlous',
   'The love commandment is repeated for the third time in the Upper Room Discourse (13:34; 15:12; 15:17) — marking it as the central, defining obligation of the Christian community. Three repetitions bracket the section on friendship (vv.14-16): love is the context in which friendship with Christ is expressed and maintained. The repetition is not redundancy but emphasis — this is the foundational command from which all other aspects of Christian community life flow.',
   NULL),
  (18, 'If the world hate you, ye know that it hated me before it hated you.',
   'Εἰ ὁ κόσμος ὑμᾶς μισεῖ γινώσκετε ὅτι ἐμὲ πρῶτον ὑμῶν μεμίσηκεν',
   'Ei ho kosmos hymas misei ginōskete hoti eme prōton hymōn memisēken',
   '''If the world hate you'' (ei ho kosmos hymas misei — if the world hates you; and it does). The abrupt shift from love within the community to hatred from the world marks the beginning of the second section (vv.18-27). ''It hated me before it hated you'' (eme prōton hymōn memisēken — it has hated me before [hating] you; perfect tense: the hatred of Jesus is an established fact that precedes the disciples'' experience). The disciples'' experience of hostility is not surprising or anomalous — it is the continuation of the world''s response to Christ.',
   NULL),
  (19, 'If ye were of the world, the world would love his own: but because ye are not of the world, but I have chosen you out of the world, therefore the world hateth you.',
   'εἰ ἐκ τοῦ κόσμου ἦτε ὁ κόσμος ἂν τὸ ἴδιον ἐφίλει ὅτι δὲ ἐκ τοῦ κόσμου οὐκ ἐστέ ἀλλ᾽ ἐγὼ ἐξελεξάμην ὑμᾶς ἐκ τοῦ κόσμου διὰ τοῦτο μισεῖ ὑμᾶς ὁ κόσμος',
   'ei ek tou kosmou ēte ho kosmos an to idion ephilei hoti de ek tou kosmou ouk este all egō exelexamēn hymas ek tou kosmou dia touto misei hymas ho kosmos',
   '''The world would love his own'' (ho kosmos an to idion ephilei — the world would love its own; to idion: its own people, its own kind). The world system is self-referential — it loves those who belong to it and reflect its values. The disciples have been ''chosen out of the world'' (exelexamēn hymas ek tou kosmou) — extracted from the world-system by divine election. The hostility of the world is therefore structural: the disciples are, by their transformed nature and allegiance, a standing rebuke to the world''s values.',
   NULL),
  (20, 'Remember the word that I said unto you, The servant is not greater than his lord. If they have persecuted me, they will also persecute you; if they have kept my saying, they will keep yours also.',
   'μνημονεύετε τοῦ λόγου οὗ ἐγὼ εἶπον ὑμῖν Οὐκ ἔστιν δοῦλος μείζων τοῦ κυρίου αὐτοῦ εἰ ἐμὲ ἐδίωξαν καὶ ὑμᾶς διώξουσιν εἰ τὸν λόγον μου ἐτήρησαν καὶ τὸν ὑμέτερον τηρήσουσιν',
   'mnēmoneuete tou logou hou egō eipon hymin Ouk estin doulos meizōn tou kyriou autou ei eme ediōxan kai hymas diōxousin ei ton logon mou etērēsan kai ton hymeteron tērēsousin',
   '''If they have persecuted me, they will also persecute you'' (ei eme ediōxan, kai hymas diōxousin — if they persecuted me, they will also persecute you). The logic of persecution: those who hate the master will hate the servant (cf. Matthew 10:24-25; Luke 6:40). The converse is also true: ''if they have kept my saying, they will keep yours also'' — but this is the minority response. Jesus prepares the disciples not for ease but for hardship, not for popularity but for rejection, explaining it so they are not caught off guard (16:1-4).',
   NULL),
  (21, 'But all these things will they do unto you for my name''s sake, because they know not him that sent me.',
   'ἀλλὰ ταῦτα πάντα ποιήσουσιν εἰς ὑμᾶς διὰ τὸ ὄνομά μου ὅτι οὐκ οἴδασιν τὸν πέμψαντά με',
   'alla tauta panta poiēsousin eis hymas dia to onoma mou hoti ouk oidasin ton pempsanta me',
   '''For my name''s sake'' (dia to onoma mou — on account of my name). The disciples suffer not for their own sins or provocations but because of their identification with Christ. ''Because they know not him that sent me'' (ouk oidasin ton pempsanta me) — the root of all rejection of Jesus and his followers is ignorance of the Father. Those who truly know God recognise the Son. Rejection of Christ is simultaneously ignorance of and rejection of God (cf. 8:19,42,55; 16:3).',
   NULL),
  (22, 'If I had not come and spoken unto them, they had not had sin: but now they have no cloke for their sin.',
   'εἰ μὴ ἦλθον καὶ ἐλάλησα αὐτοῖς ἁμαρτίαν οὐκ εἴχοσαν νῦν δὲ πρόφασιν οὐκ ἔχουσιν περὶ τῆς ἁμαρτίας αὐτῶν',
   'ei mē ēlthon kai elalēsa autois hamartian ouk eichosan nyn de prophasisin ouk echousin peri tēs hamartias autōn',
   '''They had not had sin'' (hamartian ouk eichosan — they would not have had sin; not absolute sinlessness, but specifically the sin of rejecting the light). The coming of Jesus created a new category of accountability. Before his coming, the Jews sinned in ignorance; now they have heard his words and seen his works, and yet reject him. Their rejection is therefore ''without cloke'' (prophasisin ouk echousin — without excuse; prophasis: a pretext, cover, excuse). Greater light creates greater accountability (cf. Luke 12:47-48; Romans 2:12-16; Hebrews 10:26-31).',
   NULL),
  (23, 'He that hateth me hateth my Father also.',
   'ὁ ἐμὲ μισῶν καὶ τὸν πατέρα μου μισεῖ',
   'ho eme misōn kai ton patera mou misei',
   'The unity of Father and Son means that hatred of one is hatred of the other — just as love of one is love of the other (14:9; Matthew 10:40). There is no path to the Father that bypasses the Son (14:6); correspondingly, there is no rejection of the Son that does not implicate rejection of the Father. Anti-Christian hostility is, at its root, enmity against God.',
   NULL),
  (24, 'If I had not done among them the works which none other man did, they had not had sin: but now have they both seen and hated both me and my Father.',
   'εἰ τὰ ἔργα μὴ ἐποίησα ἐν αὐτοῖς ἃ οὐδεὶς ἄλλος πεποίηκεν ἁμαρτίαν οὐκ εἴχοσαν νῦν δὲ καὶ ἑωράκασιν καὶ μεμισήκασιν καὶ ἐμὲ καὶ τὸν πατέρα μου',
   'ei ta erga mē epoiēsa en autois ha oudeis allos pepoiēken hamartian ouk eichosan nyn de kai heōrakusin kai memisēkasin kai eme kai ton patera mou',
   '''The works which none other man did'' (ha oudeis allos pepoiēken — which no one else has done; perfect tense: unique and without parallel). The miracles of Jesus are a second ground of accountability (alongside his words, v.22). They are unprecedented in scale, consistency, compassion, and divine authority. To have seen these works and still reject the one who performed them is to be ''without excuse.'' ''Seen and hated'' — the hatred is inexplicable except by the category of sin: irrational, willful, heart-rooted rejection of the light.',
   NULL),
  (25, 'But this cometh to pass, that the word might be fulfilled that is written in their law, They hated me without a cause.',
   'ἀλλ᾽ ἵνα πληρωθῇ ὁ λόγος ὁ γεγραμμένος ἐν τῷ νόμῳ αὐτῶν ὅτι Ἐμίσησάν με δωρεάν',
   'all hina plērōthē ho logos ho gegrammenos en tō nomō autōn hoti Emisēsan me dōrean',
   '''They hated me without a cause'' (Emisēsan me dōrean — they hated me freely/without reason). Quoting Psalm 35:19 and 69:4. ''Dōrean'' (freely, as a gift, without cause) — the hatred has no moral justification, no legitimate grounds. David wrote of his persecutors; the Holy Spirit intended this as a prophecy of Christ. ''Their law'' (tō nomō autōn) — Jesus refers to the Psalms as ''their law'' (Torah in its broader sense), ironically noting that their own scriptures predict this irrational hatred.',
   NULL),
  (26, 'But when the Comforter is come, whom I will send unto you from the Father, even the Spirit of truth, which proceedeth from the Father, he shall testify of me:',
   'ὅταν δὲ ἔλθῃ ὁ παράκλητος ὃν ἐγὼ πέμψω ὑμῖν παρὰ τοῦ πατρός τὸ πνεῦμα τῆς ἀληθείας ὃ παρὰ τοῦ πατρὸς ἐκπορεύεται ἐκεῖνος μαρτυρήσει περὶ ἐμοῦ',
   'hotan de elthē ho paraklētos hon egō pempsō hymin para tou patros to pneuma tēs alētheias ho para tou patros ekporeuetai ekeinos martyrēsei peri emou',
   '''Which proceedeth from the Father'' (ho para tou patros ekporeuetai — who goes out/proceeds from alongside the Father). ''Ekporeuetai'' (present tense: continually proceeds, goes forth). This verse is the key text in the historic filioque controversy: Western Christianity added to the Nicene Creed that the Spirit proceeds from the Father ''and the Son'' (filioque); Eastern Orthodoxy insists he proceeds from the Father alone. Here, Jesus says the Spirit ''proceeds from the Father'' but also that Jesus ''will send'' him — both are true. The Spirit''s eternal procession is from the Father; his temporal mission is by the Son. ''He shall testify of me'' (martyrēsei peri emou) — the Spirit''s primary ministry is bearing witness to Christ, not to himself.',
   NULL),
  (27, 'And ye also shall bear witness, because ye have been with me from the beginning.',
   'καὶ ὑμεῖς δὲ μαρτυρεῖτε ὅτι ἀπ᾽ ἀρχῆς μετ᾽ ἐμοῦ ἐστε',
   'kai hymeis de martyreite hoti ap archēs met emou este',
   '''Ye also shall bear witness'' (kai hymeis de martyreite — and you also are witnessing/bear witness; present tense: ongoing). The apostolic witness runs alongside the Spirit''s witness — they are distinct but inseparable. The Spirit testifies through and with the apostles. ''Because ye have been with me from the beginning'' (oti ap archēs met emou este — because from the beginning you have been with me; the beginning of Jesus''s ministry). This is the apostolic qualification: eyewitness presence throughout Jesus''s ministry (Acts 1:21-22; 1 John 1:1-3). The disciples'' witness is rooted in direct experience; the Spirit''s witness is divine authentication.',
   NULL)
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'John' AND c.chapter_number = 15;
