-- Matthew Chapter 21 — The King Enters, Judges, and Is Rejected
-- Triumphal Entry, Temple Cleansing, Fig Tree, Authority, Two Sons, Wicked Husbandmen

-- =====================================================================
-- 1. CHAPTER METADATA
-- =====================================================================
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 21,
  'Matthew 21 begins Passion Week. Jesus enters Jerusalem as the meek Messianic King riding a donkey (vv.1-11), cleanses the temple of commerce (vv.12-17), curses the fruitless fig tree as a sign of judgment on Israel''s religious system (vv.18-22), confronts the chief priests over His authority (vv.23-27), and tells three parables of judgment: the Two Sons (vv.28-32), the Wicked Husbandmen (vv.33-44), and concludes with the leaders'' resolve to seize Him (vv.45-46). The chapter pivots Matthew from Galilean ministry to Jerusalem confrontation, fulfilling Zechariah 9:9 and Psalm 118:22-23.',
  'The Rejected Stone Becomes the Head of the Corner',
  'λίθος',
  'Stone — the rejected cornerstone of Psalm 118:22 which Jesus applies to Himself, becoming both the foundation of the new people of God and the stone of stumbling that crushes its enemies (Mt 21:42, 44).',
  '["1-11 The King enters Zion — fulfillment of Zechariah 9:9; Hosanna acclamation", "12-17 The King cleanses His house — fulfilling Isaiah 56:7 / Jeremiah 7:11", "18-22 The fruitless fig tree cursed — enacted parable and faith lesson", "23-27 The authority question trapped — counter-question on John''s baptism", "28-32 Parable of the two sons — publicans believe; leaders do not", "33-44 Parable of the wicked husbandmen — Israel''s leaders judged; kingdom transferred", "45-46 The plot tightens — chief priests perceive but fear the multitude"]'::jsonb
FROM books b WHERE b.name = 'Matthew'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  theme = EXCLUDED.theme,
  overview = EXCLUDED.overview,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

-- =====================================================================
-- 2. VERSES (1-46)
-- =====================================================================
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'And when they drew nigh unto Jerusalem, and were come to Bethphage, unto the mount of Olives, then sent Jesus two disciples,',
   'Καὶ ὅτε ἤγγισαν εἰς Ἱεροσόλυμα καὶ ἦλθον εἰς Βηθφαγῆ εἰς τὸ Ὄρος τῶν Ἐλαιῶν, τότε Ἰησοῦς ἀπέστειλεν δύο μαθητάς',
   'Kai hote ēngisan eis Hierosolyma kai ēlthon eis Bēthphagē eis to Oros tōn Elaiōn, tote Iēsous apesteilen dyo mathētas',
   'Bethphage ("house of unripe figs") sat on the eastern slope of Olivet, just outside the Sabbath-day boundary of Jerusalem. The Mount of Olives is the very place from which Zechariah 14:4 prophesies the LORD will return; Jesus stages His entry from this prophetic site.',
   'Jesus initiates and orchestrates His own arrival at the cross. The Triumphal Entry is no spontaneous outburst of crowd enthusiasm but a deliberate, prophetically scripted self-presentation as Messianic King.'),
  (2, 'Saying unto them, Go into the village over against you, and straightway ye shall find an ass tied, and a colt with her: loose them, and bring them unto me.',
   'λέγων αὐτοῖς· Πορεύεσθε εἰς τὴν κώμην τὴν κατέναντι ὑμῶν, καὶ εὐθέως εὑρήσετε ὄνον δεδεμένην καὶ πῶλον μετ᾽ αὐτῆς· λύσαντες ἀγάγετέ μοι',
   'legōn autois: Poreuesthe eis tēn kōmēn tēn katenanti hymōn, kai eutheōs heurēsete onon dedemenēn kai pōlon met'' autēs: lysantes agagete moi',
   'Matthew alone mentions both donkey and colt, drawing tighter the link to Zechariah 9:9''s Hebrew parallelism. Jesus'' supernatural foreknowledge mirrors 1 Samuel 10:2-7 where Samuel directs Saul to find specific persons and animals.',
   'Christ''s omniscience extends to the location and condition of an unridden colt in a village He has not visited. This is the foreknowledge of a divine King.'),
  (3, 'And if any man say ought unto you, ye shall say, The Lord hath need of them; and straightway he will send them.',
   'καὶ ἐάν τις ὑμῖν εἴπῃ τι, ἐρεῖτε ὅτι Ὁ κύριος αὐτῶν χρείαν ἔχει· εὐθὺς δὲ ἀποστελεῖ αὐτούς',
   'kai ean tis hymin eipē ti, ereite hoti Ho kyrios autōn chreian echei: euthys de apostelei autous',
   '"The Lord (ho kyrios) hath need" — likely a pre-arranged signal with the owner, who recognized Jesus'' authority. The same word "Lord" picks up Psalm 118:26 quoted in v.9.',
   'The King who created all things condescends to "need" a borrowed colt. Yet His word commandeers creation; even owners surrender at His request.'),
  (4, 'All this was done, that it might be fulfilled which was spoken by the prophet, saying,',
   'Τοῦτο δὲ γέγονεν ἵνα πληρωθῇ τὸ ῥηθὲν διὰ τοῦ προφήτου λέγοντος',
   'Touto de gegonen hina plērōthē to rhēthen dia tou prophētou legontos',
   'Matthew''s eleventh formula citation. The prophetic word is the engine of the narrative; events occur "in order that" (hina) Scripture be fulfilled.',
   'Scripture''s authority is not retrospective decoration but the determining cause of historical events. The Bible drives history; history does not edit the Bible.'),
  (5, 'Tell ye the daughter of Sion, Behold, thy King cometh unto thee, meek, and sitting upon an ass, and a colt the foal of an ass.',
   'Εἴπατε τῇ θυγατρὶ Σιών· Ἰδοὺ ὁ βασιλεύς σου ἔρχεταί σοι, πραῢς καὶ ἐπιβεβηκὼς ἐπὶ ὄνον καὶ ἐπὶ πῶλον υἱὸν ὑποζυγίου',
   'Eipate tē thygatri Siōn: Idou ho basileus sou erchetai soi, praus kai epibebēkōs epi onon kai epi pōlon hyion hypozygiou',
   'Composite citation of Isaiah 62:11 + Zechariah 9:9. The donkey is a beast of peace and royal humility (cf. 1 Kgs 1:33), unlike the warhorse (Rev 19:11) of the Second Advent.',
   'Two advents are encoded in this image: First Coming on a donkey of meekness for atonement; Second Coming on a white horse for conquest. Jesus chose the donkey first because He came first to bear sin.'),
  (6, 'And the disciples went, and did as Jesus commanded them,',
   'πορευθέντες δὲ οἱ μαθηταὶ καὶ ποιήσαντες καθὼς συνέταξεν αὐτοῖς ὁ Ἰησοῦς',
   'poreuthentes de hoi mathētai kai poiēsantes kathōs synetaxen autois ho Iēsous',
   'Plain obedience without recorded question. The disciples have learned that Jesus'' apparently odd commands (cf. Mt 17:27) prove true.',
   'Mature discipleship obeys before it understands. Faith acts on the bare word of Christ.'),
  (7, 'And brought the ass, and the colt, and put on them their clothes, and they set him thereon.',
   'ἤγαγον τὴν ὄνον καὶ τὸν πῶλον, καὶ ἐπέθηκαν ἐπ᾽ αὐτῶν τὰ ἱμάτια, καὶ ἐπεκάθισεν ἐπάνω αὐτῶν',
   'ēgagon tēn onon kai ton pōlon, kai epethēkan ep'' autōn ta himatia, kai epekathisen epanō autōn',
   '"On them" (ep'' autōn) refers to the garments, not both animals — Jesus rode the colt (Mark 11:7); the mother walked alongside to keep the unbroken colt calm.',
   'The disciples'' garments become the saddle of the King; what we have, He uses. Service to Christ is the surrender of personal cover for His use.'),
  (8, 'And a very great multitude spread their garments in the way; others cut down branches from the trees, and strawed them in the way.',
   'ὁ δὲ πλεῖστος ὄχλος ἔστρωσαν ἑαυτῶν τὰ ἱμάτια ἐν τῇ ὁδῷ, ἄλλοι δὲ ἔκοπτον κλάδους ἀπὸ τῶν δένδρων καὶ ἐστρώννυον ἐν τῇ ὁδῷ',
   'ho de pleistos ochlos estrōsan heautōn ta himatia en tē hodō, alloi de ekopton kladous apo tōn dendrōn kai estrōnnyon en tē hodō',
   'Spreading garments echoes the coronation of Jehu (2 Kgs 9:13). Branches recall Tabernacles (Lev 23:40) and the Maccabean victory entrance (1 Macc 13:51; 2 Macc 10:7).',
   'The crowds enact a coronation liturgy. Whatever they understood, the Holy Spirit choreographed the scene as a public proclamation of Messianic kingship.'),
  (9, 'And the multitudes that went before, and that followed, cried, saying, Hosanna to the Son of David: Blessed is he that cometh in the name of the Lord; Hosanna in the highest.',
   'οἱ δὲ ὄχλοι οἱ προάγοντες αὐτὸν καὶ οἱ ἀκολουθοῦντες ἔκραζον λέγοντες· Ὡσαννὰ τῷ υἱῷ Δαυίδ· εὐλογημένος ὁ ἐρχόμενος ἐν ὀνόματι Κυρίου· Ὡσαννὰ ἐν τοῖς ὑψίστοις',
   'hoi de ochloi hoi proagontes auton kai hoi akolouthountes ekrazon legontes: Hōsanna tō hyiō David: eulogēmenos ho erchomenos en onomati Kyriou: Hōsanna en tois hypsistois',
   '"Hosanna" (Heb. hoshi''ah-na, Ps 118:25) literally means "Save now!" — but had become a festal acclamation. The Hallel (Pss 113-118) was sung at every Passover, making this welcome both messianic and liturgical.',
   'The crowd unwittingly cries the very salvation prayer Jesus is about to answer at Calvary. He saves "now" — not from Rome, but from sin.'),
  (10, 'And when he was come into Jerusalem, all the city was moved, saying, Who is this?',
   'καὶ εἰσελθόντος αὐτοῦ εἰς Ἱεροσόλυμα ἐσείσθη πᾶσα ἡ πόλις λέγουσα· Τίς ἐστιν οὗτος',
   'kai eiselthontos autou eis Hierosolyma eseisthē pasa hē polis legousa: Tis estin houtos',
   '"Was moved" (eseisthē) is the verb for an earthquake — the same root as seismos. Jerusalem was shaken at His birth (Mt 2:3) and shaken now at His arrival; it will be shaken again at His death (Mt 27:51) and resurrection (Mt 28:2).',
   'Christ shakes every city He enters. The question "Who is this?" is the unavoidable question every soul must answer.'),
  (11, 'And the multitude said, This is Jesus the prophet of Nazareth of Galilee.',
   'οἱ δὲ ὄχλοι ἔλεγον· Οὗτός ἐστιν ὁ προφήτης Ἰησοῦς ὁ ἀπὸ Ναζαρὲθ τῆς Γαλιλαίας',
   'hoi de ochloi elegon: Houtos estin ho prophētēs Iēsous ho apo Nazareth tēs Galilaias',
   'The crowds answer with a partial truth: prophet, Galilean, Nazarene. They miss the deeper title "Son of David" they themselves had just sung — public acclamation does not always equal personal confession.',
   'Many will praise Christ as a great prophet who refuse Him as crucified Lord. The cheering crowd of v.9 will become the condemning crowd of Mt 27:22 within five days.'),
  (12, 'And Jesus went into the temple of God, and cast out all them that sold and bought in the temple, and overthrew the tables of the moneychangers, and the seats of them that sold doves,',
   'Καὶ εἰσῆλθεν Ἰησοῦς εἰς τὸ ἱερόν, καὶ ἐξέβαλεν πάντας τοὺς πωλοῦντας καὶ ἀγοράζοντας ἐν τῷ ἱερῷ, καὶ τὰς τραπέζας τῶν κολλυβιστῶν κατέστρεψεν καὶ τὰς καθέδρας τῶν πωλούντων τὰς περιστεράς',
   'Kai eisēlthen Iēsous eis to hieron, kai exebalen pantas tous pōlountas kai agorazontas en tō hierō, kai tas trapezas tōn kollybistōn katestrepsen kai tas kathedras tōn pōlountōn tas peristeras',
   'The trade occupied the Court of the Gentiles, the only space where non-Jews could pray. Doves were the offering of the poor (Lev 12:8) — Jesus overturns the seats of those who exploited the poorest worshipers.',
   'Christ''s zeal for true worship is fierce. He is meek toward sinners but militant against the corruption of His Father''s house.'),
  (13, 'And said unto them, It is written, My house shall be called the house of prayer; but ye have made it a den of thieves.',
   'καὶ λέγει αὐτοῖς· Γέγραπται· Ὁ οἶκός μου οἶκος προσευχῆς κληθήσεται· ὑμεῖς δὲ αὐτὸν ποιεῖτε σπήλαιον λῃστῶν',
   'kai legei autois: Gegraptai: Ho oikos mou oikos proseuchēs klēthēsetai: hymeis de auton poieite spēlaion lēstōn',
   'Quotes Isaiah 56:7 + Jeremiah 7:11. "Den of thieves" alludes to Jeremiah''s temple sermon — the very oracle threatening Solomon''s temple with destruction. Jesus invokes a judgment text.',
   'God''s house is defined by its purpose: prayer. When religion becomes commerce, judgment is at the door. The temple''s destruction (AD 70) was already inscribed in this rebuke.'),
  (14, 'And the blind and the lame came to him in the temple; and he healed them.',
   'Καὶ προσῆλθον αὐτῷ τυφλοὶ καὶ χωλοὶ ἐν τῷ ἱερῷ, καὶ ἐθεράπευσεν αὐτούς',
   'Kai prosēlthon autō typhloi kai chōloi en tō hierō, kai etherapeusen autous',
   'Reverses 2 Samuel 5:8 where the blind and lame were barred from the "house." Jesus undoes the Davidic exclusion and welcomes the very people Jewish tradition kept distant.',
   'After the cleansing comes the healing. Christ removes commerce to make room for compassion. True worship issues in mercy to the broken.'),
  (15, 'And when the chief priests and scribes saw the wonderful things that he did, and the children crying in the temple, and saying, Hosanna to the Son of David; they were sore displeased,',
   'ἰδόντες δὲ οἱ ἀρχιερεῖς καὶ οἱ γραμματεῖς τὰ θαυμάσια ἃ ἐποίησεν καὶ τοὺς παῖδας τοὺς κράζοντας ἐν τῷ ἱερῷ καὶ λέγοντας· Ὡσαννὰ τῷ υἱῷ Δαυίδ ἠγανάκτησαν',
   'idontes de hoi archiereis kai hoi grammateis ta thaumasia ha epoiēsen kai tous paidas tous krazontas en tō hierō kai legontas: Hōsanna tō hyiō David ēganaktēsan',
   '"Sore displeased" (ēganaktēsan) — the same indignation Jesus had at the disciples for hindering children (Mt 19:14). The leaders are angered by the very thing that delighted Christ.',
   'Spiritual blindness is exposed by what offends a person. The leaders were grieved by children praising Jesus, not by money-changers defiling the temple.'),
  (16, 'And said unto him, Hearest thou what these say? And Jesus saith unto them, Yea; have ye never read, Out of the mouth of babes and sucklings thou hast perfected praise?',
   'καὶ εἶπαν αὐτῷ· Ἀκούεις τί οὗτοι λέγουσιν; ὁ δὲ Ἰησοῦς λέγει αὐτοῖς· Ναί· οὐδέποτε ἀνέγνωτε ὅτι Ἐκ στόματος νηπίων καὶ θηλαζόντων κατηρτίσω αἶνον',
   'kai eipan autō: Akoueis ti houtoi legousin? ho de Iēsous legei autois: Nai: oudepote anegnōte hoti Ek stomatos nēpiōn kai thēlazontōn katērtisō ainon',
   'Quotes Psalm 8:2 (LXX). In Psalm 8 the praise is directed to YHWH; Jesus applies it to praise of Himself, an implicit claim to deity.',
   'Christ accepts what only God may accept: worship. By citing Psalm 8 He claims that the praise rightly given to YHWH is rightly given to Him.'),
  (17, 'And he left them, and went out of the city into Bethany; and he lodged there.',
   'καὶ καταλιπὼν αὐτοὺς ἐξῆλθεν ἔξω τῆς πόλεως εἰς Βηθανίαν, καὶ ηὐλίσθη ἐκεῖ',
   'kai katalipōn autous exēlthen exō tēs poleōs eis Bēthanian, kai ēulisthē ekei',
   'Bethany was the home of Mary, Martha, and Lazarus (Jn 11). Jesus, the rightful King of Jerusalem, sleeps outside its walls — a quiet judgment on the city that has no room for Him.',
   'The city that rejects Christ is left in its emptiness. He withdraws to those who love Him; communion is found in Bethany, not in the temple courts now in revolt.'),
  (18, 'Now in the morning as he returned into the city, he hungered.',
   'Πρωῒ δὲ ἐπανάγων εἰς τὴν πόλιν ἐπείνασεν',
   'Prōi de epanagōn eis tēn polin epeinasen',
   'Jesus'' real humanity surfaces: hunger. The same Lord who feeds 5,000 here goes hungry. The fig tree is about to be examined for fruit.',
   'The incarnation is not pretense. The Son of God hungered, thirsted, wept. He bears our humanity fully so He may redeem it fully (Heb 4:15).'),
  (19, 'And when he saw a fig tree in the way, he came to it, and found nothing thereon, but leaves only, and said unto it, Let no fruit grow on thee henceforward for ever. And presently the fig tree withered away.',
   'καὶ ἰδὼν συκῆν μίαν ἐπὶ τῆς ὁδοῦ ἦλθεν ἐπ᾽ αὐτήν, καὶ οὐδὲν εὗρεν ἐν αὐτῇ εἰ μὴ φύλλα μόνον, καὶ λέγει αὐτῇ· Μηκέτι ἐκ σοῦ καρπὸς γένηται εἰς τὸν αἰῶνα. καὶ ἐξηράνθη παραχρῆμα ἡ συκῆ',
   'kai idōn sykēn mian epi tēs hodou ēlthen ep'' autēn, kai ouden heuren en autē ei mē phylla monon, kai legei autē: Mēketi ek sou karpos genētai eis ton aiōna. kai exēranthē parachrēma hē sykē',
   'The fig tree in leaf normally bears edible early figs (paggim). Leaves without fruit = pretense without substance. The fig tree is Israel''s national symbol (Hos 9:10; Joel 1:7) — leafy religion without righteous fruit.',
   'God curses the religion of leaves. Profession without performance is intolerable to Christ. The fig tree''s sudden withering foreshadowed Israel''s temple destruction within forty years.'),
  (20, 'And when the disciples saw it, they marvelled, saying, How soon is the fig tree withered away!',
   'καὶ ἰδόντες οἱ μαθηταὶ ἐθαύμασαν λέγοντες· Πῶς παραχρῆμα ἐξηράνθη ἡ συκῆ',
   'kai idontes hoi mathētai ethaumasan legontes: Pōs parachrēma exēranthē hē sykē',
   'Mark spreads this over two days; Matthew telescopes for thematic compression. The disciples'' astonishment shifts the focus from the tree''s symbolism to the power of Jesus'' word.',
   'Christ''s curse is as instantaneous as His blessing. A single word from Him orders the natural world.'),
  (21, 'Jesus answered and said unto them, Verily I say unto you, If ye have faith, and doubt not, ye shall not only do this which is done to the fig tree, but also if ye shall say unto this mountain, Be thou removed, and be thou cast into the sea; it shall be done.',
   'ἀποκριθεὶς δὲ ὁ Ἰησοῦς εἶπεν αὐτοῖς· Ἀμὴν λέγω ὑμῖν, ἐὰν ἔχητε πίστιν καὶ μὴ διακριθῆτε, οὐ μόνον τὸ τῆς συκῆς ποιήσετε, ἀλλὰ κἂν τῷ ὄρει τούτῳ εἴπητε· Ἄρθητι καὶ βλήθητι εἰς τὴν θάλασσαν, γενήσεται',
   'apokritheis de ho Iēsous eipen autois: Amēn legō hymin, ean echēte pistin kai mē diakrithēte, ou monon to tēs sykēs poiēsete, alla kan tō orei toutō eipēte: Arthēti kai blēthēti eis tēn thalassan, genēsetai',
   '"This mountain" likely refers to the Mount of Olives where they stood, with the Dead Sea visible eastward. The hyperbole means: nothing is impossible to faith aligned with God''s will.',
   'Faith does not move mountains by its quantity but by its object: the omnipotent God. Doubt (diakrinō, "to be divided") is faith fractured against itself.'),
  (22, 'And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.',
   'καὶ πάντα ὅσα ἂν αἰτήσητε ἐν τῇ προσευχῇ πιστεύοντες λήμψεσθε',
   'kai panta hosa an aitēsēte en tē proseuchē pisteuontes lēmpsesthe',
   'The promise must be read with all of Scripture: prayer in His name (Jn 14:13), according to His will (1 Jn 5:14), in righteousness (Jas 5:16). It is no blank check for selfish ambition.',
   'Believing prayer is the channel through which divine omnipotence flows into history. God invites His people into governance through intercession.'),
  (23, 'And when he was come into the temple, the chief priests and the elders of the people came unto him as he was teaching, and said, By what authority doest thou these things? and who gave thee this authority?',
   'Καὶ ἐλθόντος αὐτοῦ εἰς τὸ ἱερὸν προσῆλθον αὐτῷ διδάσκοντι οἱ ἀρχιερεῖς καὶ οἱ πρεσβύτεροι τοῦ λαοῦ λέγοντες· Ἐν ποίᾳ ἐξουσίᾳ ταῦτα ποιεῖς, καὶ τίς σοι ἔδωκεν τὴν ἐξουσίαν ταύτην',
   'Kai elthontos autou eis to hieron prosēlthon autō didaskonti hoi archiereis kai hoi presbyteroi tou laou legontes: En poia exousia tauta poieis, kai tis soi edōken tēn exousian tautēn',
   'The Sanhedrin formally challenges Jesus'' actions of the previous day. "These things" = the temple cleansing, the messianic acclamation, the healings.',
   'Religious authority that has rejected God will always question the authority of those sent by God. The Sanhedrin claimed jurisdiction over the One whose temple it was.'),
  (24, 'And Jesus answered and said unto them, I also will ask you one thing, which if ye tell me, I in like wise will tell you by what authority I do these things.',
   'ἀποκριθεὶς δὲ ὁ Ἰησοῦς εἶπεν αὐτοῖς· Ἐρωτήσω ὑμᾶς κἀγὼ λόγον ἕνα, ὃν ἐὰν εἴπητέ μοι, κἀγὼ ὑμῖν ἐρῶ ἐν ποίᾳ ἐξουσίᾳ ταῦτα ποιῶ',
   'apokritheis de ho Iēsous eipen autois: Erōtēsō hymas kagō logon hena, hon ean eipēte moi, kagō hymin erō en poia exousia tauta poiō',
   'A counter-question was a standard rabbinic technique. Jesus'' question is no evasion — it exposes the leaders'' bad faith and provides them the answer if they were honest.',
   'Christ refuses to scatter pearls before swine (Mt 7:6). Truth withheld from hardened hearts is itself a mercy and a judgment.'),
  (25, 'The baptism of John, whence was it? from heaven, or of men? And they reasoned with themselves, saying, If we shall say, From heaven; he will say unto us, Why did ye not then believe him?',
   'τὸ βάπτισμα τὸ Ἰωάννου πόθεν ἦν, ἐξ οὐρανοῦ ἢ ἐξ ἀνθρώπων; οἱ δὲ διελογίζοντο ἐν ἑαυτοῖς λέγοντες· Ἐὰν εἴπωμεν Ἐξ οὐρανοῦ, ἐρεῖ ἡμῖν· Διὰ τί οὖν οὐκ ἐπιστεύσατε αὐτῷ',
   'to baptisma to Iōannou pothen ēn, ex ouranou ē ex anthrōpōn? hoi de dielogizonto en heautois legontes: Ean eipōmen Ex ouranou, erei hymin: Dia ti oun ouk episteusate autō',
   'John pointed to Jesus as the Lamb of God (Jn 1:29). Settling John''s authority settles Jesus''. The leaders deliberate not for truth but for political safety.',
   'When men weigh truth by political consequence rather than by evidence, they have already chosen against truth. Calculation has replaced conviction.'),
  (26, 'But if we shall say, Of men; we fear the people; for all hold John as a prophet.',
   'ἐὰν δὲ εἴπωμεν Ἐξ ἀνθρώπων, φοβούμεθα τὸν ὄχλον· πάντες γὰρ ὡς προφήτην ἔχουσιν τὸν Ἰωάννην',
   'ean de eipōmen Ex anthrōpōn, phoboumetha ton ochlon: pantes gar hōs prophētēn echousin ton Iōannēn',
   'Fear of the crowd, not love of God, controls them. Their leadership is a hollow performance preserved by managing public opinion.',
   'The fear of man is a snare (Pr 29:25). Religious leaders enslaved to public approval cannot serve the One who was crucified outside the camp.'),
  (27, 'And they answered Jesus, and said, We cannot tell. And he said unto them, Neither tell I you by what authority I do these things.',
   'καὶ ἀποκριθέντες τῷ Ἰησοῦ εἶπαν· Οὐκ οἴδαμεν. ἔφη αὐτοῖς καὶ αὐτός· Οὐδὲ ἐγὼ λέγω ὑμῖν ἐν ποίᾳ ἐξουσίᾳ ταῦτα ποιῶ',
   'kai apokrithentes tō Iēsou eipan: Ouk oidamen. ephē autois kai autos: Oude egō legō hymin en poia exousia tauta poiō',
   '"We do not know" — a public confession of theological incompetence from Israel''s highest court. Jesus exposes that those who claim authority over religion cannot even adjudicate a prophet.',
   'When religious leaders abandon honesty for political safety, they forfeit the moral right to teach. Jesus refuses to honor a tribunal that has dishonored truth.'),
  (28, 'But what think ye? A certain man had two sons; and he came to the first, and said, Son, go work to day in my vineyard.',
   'Τί δὲ ὑμῖν δοκεῖ; ἄνθρωπος εἶχεν τέκνα δύο. προσελθὼν τῷ πρώτῳ εἶπεν· Τέκνον, ὕπαγε σήμερον ἐργάζου ἐν τῷ ἀμπελῶνι',
   'Ti de hymin dokei? anthrōpos eichen tekna dyo. proselthōn tō prōtō eipen: Teknon, hypage sēmeron ergazou en tō ampelōni',
   'The vineyard is Israel (Isa 5:1-7). The father is God; the sons represent two responses to His call. "Today" stresses the immediacy of obedience.',
   'God''s call is always "today." Tomorrow''s obedience is no obedience; faith is dated to the moment of summons.'),
  (29, 'He answered and said, I will not: but afterward he repented, and went.',
   'ὁ δὲ ἀποκριθεὶς εἶπεν· Οὐ θέλω, ὕστερον δὲ μεταμεληθεὶς ἀπῆλθεν',
   'ho de apokritheis eipen: Ou thelō, hysteron de metamelētheis apēlthen',
   '"Repented" (metamelētheis) = changed his mind with regret. The first son represents tax collectors and harlots — open sinners who later believed John''s message.',
   'True repentance is measured by change of action, not change of mood. The son who refused yet went is justified above the son who promised yet stayed.'),
  (30, 'And he came to the second, and said likewise. And he answered and said, I go, sir: and went not.',
   'προσελθὼν δὲ τῷ δευτέρῳ εἶπεν ὡσαύτως. ὁ δὲ ἀποκριθεὶς εἶπεν· Ἐγώ, κύριε· καὶ οὐκ ἀπῆλθεν',
   'proselthōn de tō deuterō eipen hōsautōs. ho de apokritheis eipen: Egō, kyrie: kai ouk apēlthen',
   '"I go, sir" — polite, prompt, pious. But no work follows. The second son represents the religious leaders who say all the right liturgical words but produce no fruit.',
   'A respectful "Yes, Lord" is empty without obedience. Christ''s sharpest indictments fall not on the openly disobedient but on the religiously deceptive.'),
  (31, 'Whether of them twain did the will of his father? They say unto him, The first. Jesus saith unto them, Verily I say unto you, That the publicans and the harlots go into the kingdom of God before you.',
   'τίς ἐκ τῶν δύο ἐποίησεν τὸ θέλημα τοῦ πατρός; λέγουσιν· Ὁ πρῶτος. λέγει αὐτοῖς ὁ Ἰησοῦς· Ἀμὴν λέγω ὑμῖν ὅτι οἱ τελῶναι καὶ αἱ πόρναι προάγουσιν ὑμᾶς εἰς τὴν βασιλείαν τοῦ Θεοῦ',
   'tis ek tōn dyo epoiēsen to thelēma tou patros? legousin: Ho prōtos. legei autois ho Iēsous: Amēn legō hymin hoti hoi telōnai kai hai pornai proagousin hymas eis tēn basileian tou Theou',
   '"Go before you" (proagousin) — present tense; the publicans and harlots are entering the kingdom right now while the leaders stand outside. A devastating verdict from the King they will judge.',
   'The kingdom is entered by repentance, not by religious pedigree. The most despised classes precede the most respected because they alone have admitted their need.'),
  (32, 'For John came unto you in the way of righteousness, and ye believed him not: but the publicans and the harlots believed him: and ye, when ye had seen it, repented not afterward, that ye might believe him.',
   'ἦλθεν γὰρ Ἰωάννης πρὸς ὑμᾶς ἐν ὁδῷ δικαιοσύνης, καὶ οὐκ ἐπιστεύσατε αὐτῷ· οἱ δὲ τελῶναι καὶ αἱ πόρναι ἐπίστευσαν αὐτῷ· ὑμεῖς δὲ ἰδόντες οὐδὲ μετεμελήθητε ὕστερον τοῦ πιστεῦσαι αὐτῷ',
   'ēlthen gar Iōannēs pros hymas en hodō dikaiosynēs, kai ouk episteusate autō: hoi de telōnai kai hai pornai episteusan autō: hymeis de idontes oude metemelēthēte hysteron tou pisteusai autō',
   'The leaders observed sinners repenting under John''s preaching but were not even moved by such evidence. Hard hearts are not softened by the testimony of converts they despise.',
   'A religion that watches sinners be saved without rejoicing has lost the heart of God (Lk 15:7). To witness grace and remain unmoved is the deepest hardness.'),
  (33, 'Hear another parable: There was a certain householder, which planted a vineyard, and hedged it round about, and digged a winepress in it, and built a tower, and let it out to husbandmen, and went into a far country:',
   'Ἄλλην παραβολὴν ἀκούσατε. Ἄνθρωπος ἦν οἰκοδεσπότης ὅστις ἐφύτευσεν ἀμπελῶνα καὶ φραγμὸν αὐτῷ περιέθηκεν καὶ ὤρυξεν ἐν αὐτῷ ληνὸν καὶ ᾠκοδόμησεν πύργον, καὶ ἐξέδοτο αὐτὸν γεωργοῖς, καὶ ἀπεδήμησεν',
   'Allēn parabolēn akousate. Anthrōpos ēn oikodespotēs hostis ephyteusen ampelōna kai phragmon autō periethēken kai ōryxen en autō lēnon kai ōkodomēsen pyrgon, kai exedoto auton geōrgois, kai apedēmēsen',
   'Direct allusion to Isaiah 5:1-7. Hedge, winepress, tower were all in the Isaiah parable; the listening leaders would recognize the imagery instantly. The tenants are Israel''s leaders entrusted with the vineyard of God''s people.',
   'God invests fully in His people: protection (hedge), provision (winepress), oversight (tower). Stewardship presupposes generous trust on the owner''s part.'),
  (34, 'And when the time of the fruit drew near, he sent his servants to the husbandmen, that they might receive the fruits of it.',
   'ὅτε δὲ ἤγγισεν ὁ καιρὸς τῶν καρπῶν, ἀπέστειλεν τοὺς δούλους αὐτοῦ πρὸς τοὺς γεωργοὺς λαβεῖν τοὺς καρποὺς αὐτοῦ',
   'hote de ēngisen ho kairos tōn karpōn, apesteilen tous doulous autou pros tous geōrgous labein tous karpous autou',
   'The "servants" are the OT prophets sent successively by God to Israel''s leaders. The "fruit" is righteousness, justice, and faithfulness (Isa 5:7).',
   'God''s patience sends repeated messengers before judgment. Every prophet is a renewed appeal of mercy.'),
  (35, 'And the husbandmen took his servants, and beat one, and killed another, and stoned another.',
   'καὶ λαβόντες οἱ γεωργοὶ τοὺς δούλους αὐτοῦ, ὃν μὲν ἔδειραν, ὃν δὲ ἀπέκτειναν, ὃν δὲ ἐλιθοβόλησαν',
   'kai labontes hoi geōrgoi tous doulous autou, hon men edeiran, hon de apekteinan, hon de elithobolēsan',
   'Compare Jeremiah''s beatings, Zechariah''s stoning (2 Chr 24:21), Isaiah''s tradition of being sawn asunder (Heb 11:37). Israel''s history is a graveyard of prophets.',
   'Resistance to revelation escalates. Hearts refusing the lighter call must reject the heavier; first they ignore, then they injure, then they kill.'),
  (36, 'Again, he sent other servants more than the first: and they did unto them likewise.',
   'πάλιν ἀπέστειλεν ἄλλους δούλους πλείονας τῶν πρώτων, καὶ ἐποίησαν αὐτοῖς ὡσαύτως',
   'palin apesteilen allous doulous pleionas tōn prōtōn, kai epoiēsan autois hōsautōs',
   'God sends "more" — His mercy intensifies even as their wickedness intensifies. Where sin abounds, grace is sent more abundantly first (Rom 5:20).',
   'God''s patience is no proof of His indifference. Repeated mercy is itself an escalating indictment when ignored.'),
  (37, 'But last of all he sent unto them his son, saying, They will reverence my son.',
   'ὕστερον δὲ ἀπέστειλεν πρὸς αὐτοὺς τὸν υἱὸν αὐτοῦ λέγων· Ἐντραπήσονται τὸν υἱόν μου',
   'hysteron de apesteilen pros autous ton hyion autou legōn: Entrapēsontai ton hyion mou',
   '"His Son" is set apart from "the servants" — Jesus distinguishes Himself qualitatively from the prophets. He is not one more in the line; He is the only-begotten.',
   'The Trinity is sketched: the Father sends His Son, who is uniquely His own (cf. Mk 12:6 "beloved son"). Christ is no mere prophet but the Heir.'),
  (38, 'But when the husbandmen saw the son, they said among themselves, This is the heir; come, let us kill him, and let us seize on his inheritance.',
   'οἱ δὲ γεωργοὶ ἰδόντες τὸν υἱὸν εἶπον ἐν ἑαυτοῖς· Οὗτός ἐστιν ὁ κληρονόμος· δεῦτε ἀποκτείνωμεν αὐτὸν καὶ σχῶμεν τὴν κληρονομίαν αὐτοῦ',
   'hoi de geōrgoi idontes ton hyion eipon en heautois: Houtos estin ho klēronomos: deute apokteinōmen auton kai schōmen tēn klēronomian autou',
   'The leaders'' plot is unwittingly confessed in advance through Jesus'' parable. "Let us kill" — the Sanhedrin will say the same words within days (Jn 11:53).',
   'Sin recognizes the rightful Heir and kills Him precisely because He is rightful. The cross is not an accident; it is the deliberate rebellion of creature against Creator.'),
  (39, 'And they caught him, and cast him out of the vineyard, and slew him.',
   'καὶ λαβόντες αὐτὸν ἐξέβαλον ἔξω τοῦ ἀμπελῶνος καὶ ἀπέκτειναν',
   'kai labontes auton exebalon exō tou ampelōnos kai apekteinan',
   '"Cast out... slew" — Jesus would be crucified outside Jerusalem''s walls (Heb 13:12). The order (cast out first, then killed) precisely matches the historical sequence.',
   'Christ predicts His own crucifixion outside the city. The parable becomes prophecy enacted in flesh within the week.'),
  (40, 'When the lord therefore of the vineyard cometh, what will he do unto those husbandmen?',
   'ὅταν οὖν ἔλθῃ ὁ κύριος τοῦ ἀμπελῶνος, τί ποιήσει τοῖς γεωργοῖς ἐκείνοις',
   'hotan oun elthē ho kyrios tou ampelōnos, ti poiēsei tois geōrgois ekeinois',
   'Jesus invites the leaders to pronounce sentence on themselves, as Nathan did with David (2 Sam 12:5-7). They convict their own consciences before they grasp the trap.',
   'God often lets the wicked render verdict on themselves. Conscience confirms judgment before judgment falls.'),
  (41, 'They say unto him, He will miserably destroy those wicked men, and will let out his vineyard unto other husbandmen, which shall render him the fruits in their seasons.',
   'λέγουσιν αὐτῷ· Κακοὺς κακῶς ἀπολέσει αὐτούς, καὶ τὸν ἀμπελῶνα ἐκδώσεται ἄλλοις γεωργοῖς, οἵτινες ἀποδώσουσιν αὐτῷ τοὺς καρποὺς ἐν τοῖς καιροῖς αὐτῶν',
   'legousin autō: Kakous kakōs apolesei autous, kai ton ampelōna ekdōsetai allois geōrgois, hoitines apodōsousin autō tous karpous en tois kairois autōn',
   '"Miserably destroy the wicked" (kakous kakōs apolesei) — a forceful Greek wordplay: "evilly destroy the evil ones." The leaders pronounce their own sentence.',
   'God transfers stewardship from those who refuse to bear fruit to those who will. The kingdom is not promised to a bloodline but to a fruit-bearing community (v.43).'),
  (42, 'Jesus saith unto them, Did ye never read in the scriptures, The stone which the builders rejected, the same is become the head of the corner: this is the Lord''s doing, and it is marvellous in our eyes?',
   'λέγει αὐτοῖς ὁ Ἰησοῦς· Οὐδέποτε ἀνέγνωτε ἐν ταῖς γραφαῖς· Λίθον ὃν ἀπεδοκίμασαν οἱ οἰκοδομοῦντες, οὗτος ἐγενήθη εἰς κεφαλὴν γωνίας· παρὰ Κυρίου ἐγένετο αὕτη, καὶ ἔστιν θαυμαστὴ ἐν ὀφθαλμοῖς ἡμῶν',
   'legei autois ho Iēsous: Oudepote anegnōte en tais graphais: Lithon hon apedokimasan hoi oikodomountes, houtos egenēthē eis kephalēn gōnias: para Kyriou egeneto hautē, kai estin thaumastē en ophthalmois hēmōn',
   'Quotes Psalm 118:22-23 — the very Hallel psalm the crowds had just sung at His entry. The "head of the corner" (kephalē gōnias) is the most important stone, either the cornerstone or capstone, securing the whole structure.',
   'Christ''s rejection by Israel''s builders becomes the foundation of God''s new building, the Church. What men reject God exalts; the cross becomes the cornerstone.'),
  (43, 'Therefore say I unto you, The kingdom of God shall be taken from you, and given to a nation bringing forth the fruits thereof.',
   'διὰ τοῦτο λέγω ὑμῖν ὅτι ἀρθήσεται ἀφ᾽ ὑμῶν ἡ βασιλεία τοῦ Θεοῦ καὶ δοθήσεται ἔθνει ποιοῦντι τοὺς καρποὺς αὐτῆς',
   'dia touto legō hymin hoti arthēsetai aph'' hymōn hē basileia tou Theou kai dothēsetai ethnei poiounti tous karpous autēs',
   '"Nation" (ethnos, singular) refers to the Church (1 Pet 2:9 — "a holy nation"), not to a particular Gentile state. The defining mark is fruit-bearing, not ethnicity.',
   'The kingdom''s administration is taken from the unfruitful leaders of Israel and given to the multi-ethnic Church which bears the fruit of the Spirit. Stewardship is conditional; covenant electing love endures (Rom 11).'),
  (44, 'And whosoever shall fall on this stone shall be broken: but on whomsoever it shall fall, it will grind him to powder.',
   'καὶ ὁ πεσὼν ἐπὶ τὸν λίθον τοῦτον συνθλασθήσεται· ἐφ᾽ ὃν δ᾽ ἂν πέσῃ λικμήσει αὐτόν',
   'kai ho pesōn epi ton lithon touton synthlasthēsetai: eph'' hon d'' an pesē likmēsei auton',
   'Two judgments encoded: those who stumble in unbelief are broken (Isa 8:14-15); those on whom the stone falls in final judgment are pulverized (Dan 2:34-35, 44-45). Christ is both stumbling-stone and crushing-stone.',
   'There is no neutral relation to Christ. Either He breaks our pride in repentance now, or He breaks our being in judgment then. The same stone saves and destroys.'),
  (45, 'And when the chief priests and Pharisees had heard his parables, they perceived that he spake of them.',
   'καὶ ἀκούσαντες οἱ ἀρχιερεῖς καὶ οἱ Φαρισαῖοι τὰς παραβολὰς αὐτοῦ ἔγνωσαν ὅτι περὶ αὐτῶν λέγει',
   'kai akousantes hoi archiereis kai hoi Pharisaioi tas parabolas autou egnōsan hoti peri autōn legei',
   'They understood the parable yet did not repent. Comprehension without conversion is the most damning state of all.',
   'Light without obedience darkens the soul further. To know the truth and reject it is to seal one''s judgment, not avert it.'),
  (46, 'But when they sought to lay hands on him, they feared the multitude, because they took him for a prophet.',
   'καὶ ζητοῦντες αὐτὸν κρατῆσαι ἐφοβήθησαν τοὺς ὄχλους, ἐπεὶ εἰς προφήτην αὐτὸν εἶχον',
   'kai zētountes auton kratēsai ephobēthēsan tous ochlous, epei eis prophētēn auton eichon',
   'The same fear of the people that prevented an honest answer in v.26 now prevents an immediate arrest. They will arrest Him at night by Judas''s treachery (Mt 26:47-50).',
   'God restrains the wicked until His appointed hour. Christ would die not when men decided but when the Father appointed (Acts 2:23).')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Matthew' AND c.chapter_number = 21
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

-- =====================================================================
-- 3. WORD STUDIES
-- =====================================================================
INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (2, 'πῶλος', 'pōlos', 'G4454', 'Colt — a young, unbroken animal. Mark adds "whereon never man sat" (Mk 11:2), marking it as fit for sacred use, as unyoked animals were used in OT consecrated tasks (Num 19:2; 1 Sam 6:7).', 1),
  (5, 'πραΰς', 'praus', 'G4239', 'Meek — gentle, mild, the strength of restrained power. Same word in Mt 5:5 ("Blessed are the meek") and Mt 11:29 ("I am meek and lowly in heart"). The royal virtue Jesus embodies.', 1),
  (5, 'βασιλεύς', 'basileus', 'G935', 'King — Jesus enters Jerusalem in the explicit role of king, the Son of David. The first time in Matthew Jesus publicly accepts a kingly demonstration in the holy city.', 2),
  (8, 'ἱμάτια', 'himatia', 'G2440', 'Garments — outer cloaks. Spread on the road as a carpet of honor, the same gesture used at Jehu''s coronation (2 Kgs 9:13).', 1),
  (9, 'Ὡσαννά', 'Hōsanna', 'G5614', 'Hosanna — from Hebrew hoshi''ah-na ("save now," Ps 118:25). Originally a prayer cry, evolved into a festal acclamation of joy. The crowd unwittingly cries the salvation prayer Jesus is about to fulfill at Calvary.', 1),
  (9, 'υἱός Δαυίδ', 'hyios David', 'G5207/G1138', 'Son of David — the Messianic title par excellence (2 Sam 7:12-16). Public acknowledgment of Jesus as Davidic King.', 2),
  (10, 'ἐσείσθη', 'eseisthē', 'G4579', 'Was shaken / was moved — from seiō, the verb behind "seismic." The whole city shook as it had at His birth (Mt 2:3) and would at His death (Mt 27:51) and resurrection (Mt 28:2).', 1),
  (12, 'ἐξέβαλεν', 'exebalen', 'G1544', 'Cast out — a forceful expulsion, the same verb used for casting out demons. Jesus treats the temple corruption as a quasi-demonic infestation requiring expulsion.', 1),
  (12, 'κολλυβιστῶν', 'kollybistōn', 'G2855', 'Moneychangers — those who exchanged Greek and Roman coinage for the Tyrian half-shekel required for the temple tax (Mt 17:24), often at exorbitant rates exploiting pilgrims.', 2),
  (13, 'σπήλαιον λῃστῶν', 'spēlaion lēstōn', 'G4693/G3027', 'Den of robbers / brigands — quoting Jeremiah 7:11. Lēstēs is not a petty thief but a violent insurrectionist (the same word for the two crucified with Jesus). The temple has become a hideout for spiritual outlaws.', 3),
  (16, 'κατηρτίσω', 'katērtisō', 'G2675', 'Hast perfected / hast prepared — to put in order, complete, fit together. God ordains and equips the praise of children. From Psalm 8:2 LXX, here applied by Jesus to praise of Himself, an implicit deity claim.', 1),
  (19, 'συκῆ', 'sykē', 'G4808', 'Fig tree — symbol of Israel (Hos 9:10; Joel 1:7; Mic 7:1). The leafy but fruitless tree is an enacted parable of pretentious religion without righteousness.', 1),
  (19, 'παραχρῆμα', 'parachrēma', 'G3916', 'Immediately / on the spot — a Lukan favorite, used by Matthew only here and v.20. Highlights the instantaneous power of Christ''s word over creation.', 2),
  (21, 'διακριθῆτε', 'diakrithēte', 'G1252', 'Doubt — literally "be divided" or "be at odds with oneself." Doubt is faith fractured, the soul in civil war (cf. Jas 1:6-8).', 1),
  (23, 'ἐξουσία', 'exousia', 'G1849', 'Authority — legitimate, delegated right to act. The leaders correctly perceive the issue is not power but right; they question whether Jesus has the divine warrant.', 1),
  (25, 'βάπτισμα', 'baptisma', 'G908', 'Baptism — John''s baptism was the symbol of his prophetic ministry calling for repentance. To accept John''s baptism is to accept John''s authority and his testimony to Jesus.', 1),
  (29, 'μεταμεληθεὶς', 'metamelētheis', 'G3338', 'Repented / changed his mind with regret — a related but distinct word from metanoia. Here it carries the weight of authentic change resulting in obedient action.', 1),
  (33, 'οἰκοδεσπότης', 'oikodespotēs', 'G3617', 'Householder / master of the house — a compound of oikos (house) and despotēs (lord). Emphasizes God''s absolute proprietorship of the vineyard of Israel.', 1),
  (33, 'ἀμπελῶνα', 'ampelōna', 'G290', 'Vineyard — Israel as the vineyard of YHWH (Isa 5:1-7; Ps 80:8-16). The leaders would recognize the Isaianic backdrop instantly; Jesus is announcing himself as the prophet of Isaiah''s judgment song.', 2),
  (37, 'υἱόν', 'hyion', 'G5207', 'Son — distinguished sharply from "the servants" (the prophets). Christ asserts a unique sonship, qualitatively different from prophetic servanthood. Mark adds "beloved" (Mk 12:6).', 1),
  (38, 'κληρονόμος', 'klēronomos', 'G2818', 'Heir — the one entitled to inherit. By killing the heir the tenants would (in their faulty logic) claim possession. Jesus is the rightful Heir of all things (Heb 1:2).', 1),
  (42, 'λίθον', 'lithon', 'G3037', 'Stone — quoting Psalm 118:22. The chapter''s key word. Christ is both rejected by builders and chosen by God as the cornerstone of the new temple, the Church.', 1),
  (42, 'κεφαλὴν γωνίας', 'kephalēn gōnias', 'G2776/G1137', 'Head of the corner — the most important stone in a building, securing two walls together. Whether read as cornerstone (foundation) or capstone (apex), Christ is the structural key of God''s new edifice.', 2),
  (43, 'ἔθνει', 'ethnei', 'G1484', 'Nation — singular noun denoting the Church as a new corporate people of God (1 Pet 2:9). Not a particular Gentile state but the multi-ethnic body bearing kingdom fruit.', 1),
  (44, 'συνθλασθήσεται', 'synthlasthēsetai', 'G4917', 'Shall be broken — shattered into pieces. Those who stumble at Christ in unbelief now are mercifully broken; better broken in repentance now than crushed in judgment then.', 1),
  (44, 'λικμήσει', 'likmēsei', 'G3039', 'Shall grind to powder / scatter as chaff — winnowing imagery. The fate of those on whom the stone falls in final judgment, echoing Daniel 2:34-35 where the stone smashes the empires of man.', 2)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Matthew' AND c.chapter_number = 21 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

-- =====================================================================
-- 4. CROSS REFERENCES
-- =====================================================================
INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Zechariah 14:4', 1),
  (1, 'Mark 11:1', 2),
  (1, 'Luke 19:29', 3),
  (1, 'John 12:12-15', 4),
  (2, '1 Samuel 10:2-7', 1),
  (2, 'Numbers 19:2', 2),
  (2, 'John 12:14-15', 3),
  (4, 'Matthew 1:22', 1),
  (4, 'Matthew 2:15', 2),
  (4, 'John 19:36', 3),
  (5, 'Isaiah 62:11', 1),
  (5, 'Zechariah 9:9', 2),
  (5, 'Matthew 11:29', 3),
  (5, 'Revelation 19:11', 4),
  (8, '2 Kings 9:13', 1),
  (8, '1 Maccabees 13:51', 2),
  (8, 'Leviticus 23:40', 3),
  (9, 'Psalm 118:25-26', 1),
  (9, 'Matthew 23:39', 2),
  (9, 'Luke 19:38', 3),
  (10, 'Matthew 2:3', 1),
  (10, 'Matthew 27:51', 2),
  (10, 'Matthew 28:2', 3),
  (11, 'Deuteronomy 18:15', 1),
  (11, 'Matthew 16:14', 2),
  (11, 'John 6:14', 3),
  (12, 'Mark 11:15-17', 1),
  (12, 'Luke 19:45-46', 2),
  (12, 'John 2:13-17', 3),
  (12, 'Leviticus 12:8', 4),
  (13, 'Isaiah 56:7', 1),
  (13, 'Jeremiah 7:11', 2),
  (13, 'Malachi 3:1-3', 3),
  (14, '2 Samuel 5:8', 1),
  (14, 'Isaiah 35:5-6', 2),
  (15, 'Matthew 19:14', 1),
  (15, 'Luke 19:39-40', 2),
  (16, 'Psalm 8:2', 1),
  (16, '1 Corinthians 1:27', 2),
  (17, 'John 11:1', 1),
  (17, 'Matthew 26:6', 2),
  (18, 'Hebrews 4:15', 1),
  (18, 'Mark 11:12-14', 2),
  (19, 'Hosea 9:10', 1),
  (19, 'Joel 1:7', 2),
  (19, 'Micah 7:1', 3),
  (19, 'Luke 13:6-9', 4),
  (21, 'Matthew 17:20', 1),
  (21, '1 Corinthians 13:2', 2),
  (21, 'James 1:6', 3),
  (22, 'John 14:13', 1),
  (22, '1 John 5:14', 2),
  (22, 'James 5:16', 3),
  (23, 'Acts 4:7', 1),
  (23, 'John 2:18', 2),
  (25, 'Matthew 3:1-12', 1),
  (25, 'John 1:29-34', 2),
  (26, 'Proverbs 29:25', 1),
  (26, 'Matthew 14:5', 2),
  (28, 'Isaiah 5:1-7', 1),
  (28, 'Matthew 20:1', 2),
  (29, '2 Corinthians 7:10', 1),
  (29, 'Ezekiel 18:21', 2),
  (31, 'Matthew 9:10-13', 1),
  (31, 'Luke 7:29-30', 2),
  (31, 'Luke 18:13-14', 3),
  (32, 'Matthew 3:7-10', 1),
  (32, '2 Peter 2:21', 2),
  (33, 'Isaiah 5:1-7', 1),
  (33, 'Psalm 80:8-16', 2),
  (33, 'Jeremiah 2:21', 3),
  (35, '2 Chronicles 24:21', 1),
  (35, 'Hebrews 11:36-37', 2),
  (35, 'Acts 7:52', 3),
  (37, 'Hebrews 1:1-2', 1),
  (37, 'John 3:16', 2),
  (37, 'Mark 12:6', 3),
  (38, 'John 11:53', 1),
  (38, 'Acts 4:25-28', 2),
  (39, 'Hebrews 13:12', 1),
  (39, 'Acts 7:58', 2),
  (40, '2 Samuel 12:5-7', 1),
  (42, 'Psalm 118:22-23', 1),
  (42, 'Isaiah 28:16', 2),
  (42, 'Acts 4:11', 3),
  (42, '1 Peter 2:6-8', 4),
  (42, 'Ephesians 2:20', 5),
  (43, 'Romans 11:11-25', 1),
  (43, '1 Peter 2:9', 2),
  (43, 'Acts 13:46', 3),
  (44, 'Isaiah 8:14-15', 1),
  (44, 'Daniel 2:34-35', 2),
  (44, 'Daniel 2:44-45', 3),
  (44, 'Luke 20:18', 4),
  (45, 'John 11:47-50', 1),
  (45, 'Luke 20:19', 2),
  (46, 'Matthew 26:3-5', 1),
  (46, 'John 7:30', 2),
  (46, 'Acts 2:23', 3)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Matthew' AND c.chapter_number = 21 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
