-- Matthew Chapter 23 — The Seven Woes and Lament Over Jerusalem
-- Final public discourse before the Olivet Discourse — judgment on the religious leaders

-- =====================================================================
-- 1. CHAPTER METADATA
-- =====================================================================
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id, 23,
  'Matthew 23 is Christ''s final and most withering public denunciation, delivered in the temple courts the same day as ch. 21-22. He warns the multitude and disciples against the Pharisees'' hypocrisy (vv.1-12), then directs seven prophetic "woes" against the scribes and Pharisees (vv.13-36) — exposing their refusal to enter the kingdom, predatory exploitation, missionary corruption, casuistic oath-evasion, tithing trivialities while neglecting justice, polished exteriors over inward death, and prophet-killing pretensions of righteousness. The chapter closes with a heart-rending lament over Jerusalem (vv.37-39) — the very voice of divine sorrow grieving the city that murders His messengers. Matthew''s "woes" parallel the Lukan "blesseds" (Lk 6:20-26) and stand as the dark obverse of the Beatitudes (Mt 5:3-12).',
  'Woe Unto You: The Judgment of Hypocrisy',
  'οὐαί',
  'Woe — a prophetic interjection of grief and warning combined. Not mere curse but the lament of a holy God over willful self-destruction. Repeated seven (or eight) times in this chapter, evoking the woes of Isaiah 5 and the prophetic tradition.',
  '["1-12 Warning to multitudes and disciples — practice not their works; humility not titles", "13 Woe 1: Shutting up the kingdom", "14 Woe (KJV): Devouring widows'' houses under cover of long prayer", "15 Woe 2: Predatory proselytism", "16-22 Woe 3: Casuistic oath-evasion", "23-24 Woe 4: Tithing trifles, neglecting weightier matters", "25-26 Woe 5: Outwardly clean, inwardly extortionate", "27-28 Woe 6: Whitewashed tombs", "29-36 Woe 7: Prophet-killers'' children", "37-39 Lament over Jerusalem"]'::jsonb
FROM books b WHERE b.name = 'Matthew'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  theme = EXCLUDED.theme,
  overview = EXCLUDED.overview,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

-- =====================================================================
-- 2. VERSES (1-39)
-- =====================================================================
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Then spake Jesus to the multitude, and to his disciples,',
   'Τότε ὁ Ἰησοῦς ἐλάλησεν τοῖς ὄχλοις καὶ τοῖς μαθηταῖς αὐτοῦ',
   'Tote ho Iēsous elalēsen tois ochlois kai tois mathētais autou',
   'Address shifts from the leaders (ch. 22) to the people, but the leaders are still in earshot. The discourse is public and prophetic, with the religious establishment as its subject.',
   'Christ''s warnings against false teachers are spoken openly to the people, not whispered in private. Truth that protects the flock must be spoken loud enough for the wolves to hear.'),
  (2, 'Saying, The scribes and the Pharisees sit in Moses'' seat:',
   'λέγων· Ἐπὶ τῆς Μωϋσέως καθέδρας ἐκάθισαν οἱ γραμματεῖς καὶ οἱ Φαρισαῖοι',
   'legōn: Epi tēs Mōuseōs kathedras ekathisan hoi grammateis kai hoi Pharisaioi',
   '"Moses'' seat" was a literal stone chair in synagogues from which the law was read; figuratively, the teaching authority of the Mosaic tradition. Scribes and Pharisees occupied this teaching role.',
   'Office and personal worthiness can be separate. A teaching position carries authority insofar as it conveys God''s Word, even if the office-holder is unworthy.'),
  (3, 'All therefore whatsoever they bid you observe, that observe and do; but do not ye after their works: for they say, and do not.',
   'πάντα οὖν ὅσα ἐὰν εἴπωσιν ὑμῖν ποιήσατε καὶ τηρεῖτε, κατὰ δὲ τὰ ἔργα αὐτῶν μὴ ποιεῖτε· λέγουσιν γὰρ καὶ οὐ ποιοῦσιν',
   'panta oun hosa ean eipōsin hymin poiēsate kai tēreite, kata de ta erga autōn mē poieite: legousin gar kai ou poiousin',
   'Observe their teaching insofar as it accurately transmits Moses; do not imitate their lives. Jesus elsewhere disputes their additions to the law (ch. 15), so this is not blanket endorsement of their doctrine but recognition of their teaching role.',
   'Hypocrisy''s essence: profession without practice. The hardest temptation in religion is to settle for accurate words while bypassing transformed living.'),
  (4, 'For they bind heavy burdens and grievous to be borne, and lay them on men''s shoulders; but they themselves will not move them with one of their fingers.',
   'δεσμεύουσιν δὲ φορτία βαρέα καὶ δυσβάστακτα καὶ ἐπιτιθέασιν ἐπὶ τοὺς ὤμους τῶν ἀνθρώπων, αὐτοὶ δὲ τῷ δακτύλῳ αὐτῶν οὐ θέλουσιν κινῆσαι αὐτά',
   'desmeuousin de phortia barea kai dysbastakta kai epititheasin epi tous ōmous tōn anthrōpōn, autoi de tō daktylō autōn ou thelousin kinēsai auta',
   'The Pharisees'' oral tradition built fences around the law to "protect" it, but the cumulative burden was crushing — over 600 specific regulations on Sabbath alone. Contrast Jesus'' "my yoke is easy" (Mt 11:30).',
   'Legalism always burdens. Grace lifts the load Christ''s law could not lift; legalism multiplies it. The mark of true ministry is that it lightens, not burdens, the conscience.'),
  (5, 'But all their works they do for to be seen of men: they make broad their phylacteries, and enlarge the borders of their garments,',
   'πάντα δὲ τὰ ἔργα αὐτῶν ποιοῦσιν πρὸς τὸ θεαθῆναι τοῖς ἀνθρώποις· πλατύνουσιν γὰρ τὰ φυλακτήρια αὐτῶν καὶ μεγαλύνουσιν τὰ κράσπεδα',
   'panta de ta erga autōn poiousin pros to theathēnai tois anthrōpois: platynousin gar ta phylaktēria autōn kai megalynousin ta kraspeda',
   'Phylacteries (Heb. tefillin) — leather boxes containing Scripture portions worn on forehead and arm (Deut 6:8). Borders (kraspeda) = tassels mandated in Num 15:38. Wider boxes and larger tassels were ostentatious displays of supposed piety.',
   'Religion practiced for human applause forfeits divine reward (Mt 6:1). Visible piety must spring from invisible communion, not the reverse.'),
  (6, 'And love the uppermost rooms at feasts, and the chief seats in the synagogues,',
   'φιλοῦσιν δὲ τὴν πρωτοκλισίαν ἐν τοῖς δείπνοις καὶ τὰς πρωτοκαθεδρίας ἐν ταῖς συναγωγαῖς',
   'philousin de tēn prōtoklisian en tois deipnois kai tas prōtokathedrias en tais synagōgais',
   '"Uppermost rooms" (prōtoklisian) = the place of honor at the head of the dining couch. "Chief seats" (prōtokathedrias) = the bench facing the congregation. Love of preeminence is a recurring sin of religious leaders.',
   'The thirst for status is incompatible with servant leadership. Christ''s church is led by foot-washers, not throne-claimants.'),
  (7, 'And greetings in the markets, and to be called of men, Rabbi, Rabbi.',
   'καὶ τοὺς ἀσπασμοὺς ἐν ταῖς ἀγοραῖς καὶ καλεῖσθαι ὑπὸ τῶν ἀνθρώπων Ῥαββί',
   'kai tous aspasmous en tais agorais kai kaleisthai hypo tōn anthrōpōn Rhabbi',
   '"Rabbi" (Heb. "my great one"). Public deference in marketplace greetings was considered a status marker. The repeated "Rabbi, Rabbi" emphasizes their craving for honorific titles.',
   'Hunger for titles signals a heart not satisfied with God''s approval. Where men seek titles, they have already lost the reward.'),
  (8, 'But be not ye called Rabbi: for one is your Master, even Christ; and all ye are brethren.',
   'ὑμεῖς δὲ μὴ κληθῆτε Ῥαββί· εἷς γάρ ἐστιν ὑμῶν ὁ διδάσκαλος, πάντες δὲ ὑμεῖς ἀδελφοί ἐστε',
   'hymeis de mē klēthēte Rhabbi: heis gar estin hymōn ho didaskalos, pantes de hymeis adelphoi este',
   'The principle is not against teaching titles per se but against authoritative deference that displaces Christ. The early church had didaskaloi (teachers) as a recognized gift (Eph 4:11) but always under the singular Lordship of Christ.',
   'Christ alone is the supreme Teacher. All Christian leaders are fellow-students of His. Brotherhood under one Master is the structure of the Church.'),
  (9, 'And call no man your father upon the earth: for one is your Father, which is in heaven.',
   'καὶ πατέρα μὴ καλέσητε ὑμῶν ἐπὶ τῆς γῆς· εἷς γάρ ἐστιν ὑμῶν ὁ Πατὴρ ὁ οὐράνιος',
   'kai patera mē kalesēte hymōn epi tēs gēs: heis gar estin hymōn ho Patēr ho ouranios',
   'Not against natural fatherhood (cf. Eph 6:2) but against giving spiritual leaders the deference owed to God the Father. The Hebrew use of "Abba" or "Father" as a title for revered rabbis is being challenged.',
   'God alone is the source of spiritual life and authority. No earthly figure may stand between the believer and the Father.'),
  (10, 'Neither be ye called masters: for one is your Master, even Christ.',
   'μηδὲ κληθῆτε καθηγηταί· εἷς γάρ ὑμῶν ἐστιν ὁ καθηγητής, ὁ Χριστός',
   'mēde klēthēte kathēgētai: heis gar hymōn estin ho kathēgētēs, ho Christos',
   '"Master" (kathēgētai) = guide, leader, instructor. Christ is the singular Guide of His people, the One who leads them in the way.',
   'Christ alone is the believer''s ultimate Guide. No human leader, however gifted, may usurp the place of the Lord in directing souls.'),
  (11, 'But he that is greatest among you shall be your servant.',
   'ὁ δὲ μείζων ὑμῶν ἔσται ὑμῶν διάκονος',
   'ho de meizōn hymōn estai hymōn diakonos',
   'Echoes Mt 20:26-27. The kingdom inverts worldly hierarchy: greatness is measured by service, not by position served.',
   'Christ''s economy reckons greatness downward. The greatest is the one who stoops lowest in service to others.'),
  (12, 'And whosoever shall exalt himself shall be abased; and he that shall humble himself shall be exalted.',
   'ὅστις δὲ ὑψώσει ἑαυτὸν ταπεινωθήσεται, καὶ ὅστις ταπεινώσει ἑαυτὸν ὑψωθήσεται',
   'hostis de hypsōsei heauton tapeinōthēsetai, kai hostis tapeinōsei heauton hypsōthēsetai',
   'A repeated kingdom principle (Lk 14:11; 18:14; 1 Pet 5:6). The future passive ("shall be abased / exalted") indicates God Himself is the agent.',
   'Self-exaltation invites divine humbling; self-humbling invites divine exaltation. The trajectory of Christ Himself (Phil 2:5-11) is the pattern for all His disciples.'),
  (13, 'But woe unto you, scribes and Pharisees, hypocrites! for ye shut up the kingdom of heaven against men: for ye neither go in yourselves, neither suffer ye them that are entering to go in.',
   'Οὐαὶ δὲ ὑμῖν, γραμματεῖς καὶ Φαρισαῖοι ὑποκριταί, ὅτι κλείετε τὴν βασιλείαν τῶν οὐρανῶν ἔμπροσθεν τῶν ἀνθρώπων· ὑμεῖς γὰρ οὐκ εἰσέρχεσθε, οὐδὲ τοὺς εἰσερχομένους ἀφίετε εἰσελθεῖν',
   'Ouai de hymin, grammateis kai Pharisaioi hypokritai, hoti kleiete tēn basileian tōn ouranōn emprosthen tōn anthrōpōn: hymeis gar ouk eiserchesthe, oude tous eiserchomenous aphiete eiselthein',
   'First woe — the gravest: blocking access to the kingdom. By rejecting John''s baptism (21:25-32) and rejecting Christ Himself, they barred the door for those they taught.',
   'False teachers do not merely err privately; they obstruct the salvation of others. The greatest crime against humanity is to stand in the way of the gospel.'),
  (14, 'Woe unto you, scribes and Pharisees, hypocrites! for ye devour widows'' houses, and for a pretence make long prayer: therefore ye shall receive the greater damnation.',
   'Οὐαὶ ὑμῖν, γραμματεῖς καὶ Φαρισαῖοι ὑποκριταί, ὅτι κατεσθίετε τὰς οἰκίας τῶν χηρῶν καὶ προφάσει μακρὰ προσευχόμενοι· διὰ τοῦτο λήψεσθε περισσότερον κρίμα',
   'Ouai hymin, grammateis kai Pharisaioi hypokritai, hoti katesthiete tas oikias tōn chērōn kai prophasei makra proseuchomenoi: dia touto lēpsesthe perissoteron krima',
   'This verse is omitted in the earliest manuscripts (Aleph, B, D) but included in the KJV from later witnesses; it parallels Mark 12:40 and Luke 20:47. Pharisees as legal trustees often preyed on widows'' estates while masking exploitation with showy prayer.',
   'Religious cover for economic exploitation incurs heavier judgment, not lighter. God reserves His severest condemnation for those who use spiritual authority to oppress the vulnerable.'),
  (15, 'Woe unto you, scribes and Pharisees, hypocrites! for ye compass sea and land to make one proselyte, and when he is made, ye make him twofold more the child of hell than yourselves.',
   'Οὐαὶ ὑμῖν, γραμματεῖς καὶ Φαρισαῖοι ὑποκριταί, ὅτι περιάγετε τὴν θάλασσαν καὶ τὴν ξηρὰν ποιῆσαι ἕνα προσήλυτον, καὶ ὅταν γένηται, ποιεῖτε αὐτὸν υἱὸν γεέννης διπλότερον ὑμῶν',
   'Ouai hymin, grammateis kai Pharisaioi hypokritai, hoti periagete tēn thalassan kai tēn xēran poiēsai hena prosēlyton, kai hotan genētai, poieite auton hyion geennēs diploteron hymōn',
   '"Proselyte" (prosēlytos) = a Gentile convert to Judaism. Pharisees did missionary travel to win converts, but the converts often outdid them in zealous legalism. "Child of Gehenna" = destined for hell.',
   'False conversion is worse than no conversion. To be discipled into legalistic religion makes one doubly damned, for the convert has now embraced false security in works.'),
  (16, 'Woe unto you, ye blind guides, which say, Whosoever shall swear by the temple, it is nothing; but whosoever shall swear by the gold of the temple, he is a debtor!',
   'Οὐαὶ ὑμῖν, ὁδηγοὶ τυφλοὶ οἱ λέγοντες· Ὃς ἂν ὀμόσῃ ἐν τῷ ναῷ, οὐδέν ἐστιν· ὃς δ᾽ ἂν ὀμόσῃ ἐν τῷ χρυσῷ τοῦ ναοῦ, ὀφείλει',
   'Ouai hymin, hodēgoi typhloi hoi legontes: Hos an omosē en tō naō, ouden estin: hos d'' an omosē en tō chrysō tou naou, opheilei',
   '"Blind guides" — sharper than "hypocrites." The Pharisees'' casuistry distinguished binding from non-binding oaths, allowing dishonest people to swear by lesser things and escape obligation. Jesus had earlier forbidden oath-evasion (Mt 5:33-37).',
   'Casuistic distinctions in ethics that allow evasion of plain truth are spiritual blindness. God demands integrity that needs no clever loopholes.'),
  (17, 'Ye fools and blind: for whether is greater, the gold, or the temple that sanctifieth the gold?',
   'μωροὶ καὶ τυφλοί· τίς γὰρ μείζων ἐστίν, ὁ χρυσὸς ἢ ὁ ναὸς ὁ ἁγιάσας τὸν χρυσόν',
   'mōroi kai typhloi: tis gar meizōn estin, ho chrysos ē ho naos ho hagiasas ton chryson',
   'The temple sanctifies the gold, not vice versa. The Pharisees inverted sacred order, prizing the lesser as binding while treating the greater as ceremonial. (On "fools" cf. Mt 5:22 — the issue is angry insult, not honest assessment.)',
   'God''s holy order cannot be inverted by human casuistry. What sanctifies cannot be subordinated to what is sanctified.'),
  (18, 'And, Whosoever shall swear by the altar, it is nothing; but whosoever sweareth by the gift that is upon it, he is guilty.',
   'καί· Ὃς ἂν ὀμόσῃ ἐν τῷ θυσιαστηρίῳ, οὐδέν ἐστιν· ὃς δ᾽ ἂν ὀμόσῃ ἐν τῷ δώρῳ τῷ ἐπάνω αὐτοῦ, ὀφείλει',
   'kai: Hos an omosē en tō thysiastēriō, ouden estin: hos d'' an omosē en tō dōrō tō epanō autou, opheilei',
   'Same casuistic split: altar is a non-binding swear, the offering on it is binding. Yet without the altar, the offering has no sacred status.',
   'Distinctions invented by men to evade truth pile up like cobwebs across the plain commands of God. Sin proliferates language to escape obedience.'),
  (19, 'Ye fools and blind: for whether is greater, the gift, or the altar that sanctifieth the gift?',
   'τυφλοί· τί γὰρ μεῖζον, τὸ δῶρον ἢ τὸ θυσιαστήριον τὸ ἁγιάζον τὸ δῶρον',
   'typhloi: ti gar meizon, to dōron ē to thysiastērion to hagiazon to dōron',
   'Same logical move as v.17. The altar (as the place of God''s appointed worship) sanctifies the gift; therefore the altar carries greater weight.',
   'Blindness to the priority of God''s consecrated means is the hallmark of legalistic religion. Where God has spoken first, men must not weight the secondary above the primary.'),
  (20, 'Whoso therefore shall swear by the altar, sweareth by it, and by all things thereon.',
   'ὁ οὖν ὀμόσας ἐν τῷ θυσιαστηρίῳ ὀμνύει ἐν αὐτῷ καὶ ἐν πᾶσιν τοῖς ἐπάνω αὐτοῦ',
   'ho oun omosas en tō thysiastēriō omnyei en autō kai en pasin tois epanō autou',
   'Jesus collapses the false distinction. To swear by any sacred object is implicitly to swear by all the holiness it represents — and ultimately by God Himself.',
   'God cannot be excluded from any oath the soul takes. All speech is implicitly under His witness.'),
  (21, 'And whoso shall swear by the temple, sweareth by it, and by him that dwelleth therein.',
   'καὶ ὁ ὀμόσας ἐν τῷ ναῷ ὀμνύει ἐν αὐτῷ καὶ ἐν τῷ κατοικοῦντι αὐτόν',
   'kai ho omosas en tō naō omnyei en autō kai en tō katoikounti auton',
   'The temple''s sanctity derives from God''s presence. To swear by the temple invokes God who indwells it.',
   'God''s indwelling presence is what makes any place sacred. Apart from Him no stone is holier than another.'),
  (22, 'And he that shall swear by heaven, sweareth by the throne of God, and by him that sitteth thereon.',
   'καὶ ὁ ὀμόσας ἐν τῷ οὐρανῷ ὀμνύει ἐν τῷ θρόνῳ τοῦ Θεοῦ καὶ ἐν τῷ καθημένῳ ἐπάνω αὐτοῦ',
   'kai ho omosas en tō ouranō omnyei en tō thronō tou Theou kai en tō kathēmenō epanō autou',
   'Even the most "indirect" swear by heaven implicates God''s throne. There is no neutral oath. Best, therefore, to speak simply (Mt 5:37).',
   'Speech is sacred because it occurs in God''s presence. Every word is offered up to the One who hears all.'),
  (23, 'Woe unto you, scribes and Pharisees, hypocrites! for ye pay tithe of mint and anise and cummin, and have omitted the weightier matters of the law, judgment, mercy, and faith: these ought ye to have done, and not to leave the other undone.',
   'Οὐαὶ ὑμῖν, γραμματεῖς καὶ Φαρισαῖοι ὑποκριταί, ὅτι ἀποδεκατοῦτε τὸ ἡδύοσμον καὶ τὸ ἄνηθον καὶ τὸ κύμινον, καὶ ἀφήκατε τὰ βαρύτερα τοῦ νόμου, τὴν κρίσιν καὶ τὸ ἔλεος καὶ τὴν πίστιν· ταῦτα δὲ ἔδει ποιῆσαι κἀκεῖνα μὴ ἀφιέναι',
   'Ouai hymin, grammateis kai Pharisaioi hypokritai, hoti apodekatoute to hēdyosmon kai to anēthon kai to kyminon, kai aphēkate ta barytera tou nomou, tēn krisin kai to eleos kai tēn pistin: tauta de edei poiēsai kakeina mē aphienai',
   'Mint, anise (dill), cummin — minor garden herbs, not even strictly required by the tithing law. The Pharisees scrupled tiny details while ignoring the weightier (barytera) matters: justice (krisis), mercy (eleos), faithfulness (pistis) — the substance of Micah 6:8.',
   'Christ does not abolish the small obediences but refuses to let them displace the great. Religious meticulousness in the tiny is no substitute for justice and mercy in the major.'),
  (24, 'Ye blind guides, which strain at a gnat, and swallow a camel.',
   'ὁδηγοὶ τυφλοί, οἱ διϋλίζοντες τὸν κώνωπα τὴν δὲ κάμηλον καταπίνοντες',
   'hodēgoi typhloi, hoi diylizontes ton kōnōpa tēn de kamēlon katapinontes',
   'Both gnat (kōnōps) and camel (kamēlos) were ceremonially unclean (Lev 11:4, 41). Pharisees strained their drink through cloth to remove tiny gnats but figuratively swallowed camels — gross moral compromises. The KJV "strain at" should be "strain out" (an old printer''s error).',
   'A microscope on minor sin and a blindfold over major sin — this is religious hypocrisy''s eyesight. Christ teaches us to see by their proper proportion.'),
  (25, 'Woe unto you, scribes and Pharisees, hypocrites! for ye make clean the outside of the cup and of the platter, but within they are full of extortion and excess.',
   'Οὐαὶ ὑμῖν, γραμματεῖς καὶ Φαρισαῖοι ὑποκριταί, ὅτι καθαρίζετε τὸ ἔξωθεν τοῦ ποτηρίου καὶ τῆς παροψίδος, ἔσωθεν δὲ γέμουσιν ἐξ ἁρπαγῆς καὶ ἀκρασίας',
   'Ouai hymin, grammateis kai Pharisaioi hypokritai, hoti katharizete to exōthen tou potēriou kai tēs paropsidos, esōthen de gemousin ex harpagēs kai akrasias',
   '"Extortion" (harpagēs, lit. "plunder") + "excess" (akrasias, "lack of self-control"). The vessels were ritually clean, but the contents — symbolizing the user''s soul — were filled with greed and self-indulgence.',
   'God examines first the inside. Ceremonial purity that masks moral corruption is more obnoxious than overt sin, for it adds religious deception to the offense.'),
  (26, 'Thou blind Pharisee, cleanse first that which is within the cup and platter, that the outside of them may be clean also.',
   'Φαρισαῖε τυφλέ, καθάρισον πρῶτον τὸ ἐντὸς τοῦ ποτηρίου καὶ τῆς παροψίδος, ἵνα γένηται καὶ τὸ ἐκτὸς αὐτῶν καθαρόν',
   'Pharisaie typhle, katharison prōton to entos tou potēriou kai tēs paropsidos, hina genētai kai to ektos autōn katharon',
   'True purity is from inside out. When the heart is cleansed, outward life follows; the reverse never holds. The new covenant promise of Jeremiah 31:33 — "I will write my law on their hearts" — is the only adequate cleansing.',
   'The gospel''s priority: regeneration before reformation. Inner cleansing by the Spirit (Tit 3:5) accomplishes what no outward conformity could ever produce.'),
  (27, 'Woe unto you, scribes and Pharisees, hypocrites! for ye are like unto whited sepulchres, which indeed appear beautiful outward, but are within full of dead men''s bones, and of all uncleanness.',
   'Οὐαὶ ὑμῖν, γραμματεῖς καὶ Φαρισαῖοι ὑποκριταί, ὅτι παρομοιάζετε τάφοις κεκονιαμένοις, οἵτινες ἔξωθεν μὲν φαίνονται ὡραῖοι, ἔσωθεν δὲ γέμουσιν ὀστέων νεκρῶν καὶ πάσης ἀκαθαρσίας',
   'Ouai hymin, grammateis kai Pharisaioi hypokritai, hoti paromoiazete taphois kekoniamenois, hoitines exōthen men phainontai hōraioi, esōthen de gemousin osteōn nekrōn kai pasēs akatharsias',
   'Tombs were whitewashed with lime before Passover so pilgrims would not contract ritual defilement by accidentally touching them (Num 19:16). Beautiful exterior, decay within — the perfect image of pretentious religion.',
   'Spiritual death can hide behind aesthetic beauty. Christ unmasks the polished tomb to expose the rot beneath, calling for resurrection from inside, not paint on the outside.'),
  (28, 'Even so ye also outwardly appear righteous unto men, but within ye are full of hypocrisy and iniquity.',
   'οὕτως καὶ ὑμεῖς ἔξωθεν μὲν φαίνεσθε τοῖς ἀνθρώποις δίκαιοι, ἔσωθεν δέ ἐστε μεστοὶ ὑποκρίσεως καὶ ἀνομίας',
   'houtōs kai hymeis exōthen men phainesthe tois anthrōpois dikaioi, esōthen de este mestoi hypokriseōs kai anomias',
   '"Iniquity" (anomias) = lawlessness — the very thing the Pharisees claimed to oppose. Their outward law-keeping concealed inner law-breaking; they were lawless under a veneer of legalism.',
   'God measures righteousness inwardly. Outward conformity that masks inner rebellion is in fact lawlessness, twice condemned for its deception.'),
  (29, 'Woe unto you, scribes and Pharisees, hypocrites! because ye build the tombs of the prophets, and garnish the sepulchres of the righteous,',
   'Οὐαὶ ὑμῖν, γραμματεῖς καὶ Φαρισαῖοι ὑποκριταί, ὅτι οἰκοδομεῖτε τοὺς τάφους τῶν προφητῶν καὶ κοσμεῖτε τὰ μνημεῖα τῶν δικαίων',
   'Ouai hymin, grammateis kai Pharisaioi hypokritai, hoti oikodomeite tous taphous tōn prophētōn kai kosmeite ta mnēmeia tōn dikaiōn',
   'In Jesus'' day a wave of monument-building honored OT prophets — Herod''s reconstruction of the patriarchs'' tombs at Hebron, etc. The leaders venerated dead prophets while plotting to kill the living Prophet standing before them.',
   'It is easier to honor dead prophets than to obey living ones. Religion built on the bones of past saints often opposes the work of the present Spirit.'),
  (30, 'And say, If we had been in the days of our fathers, we would not have been partakers with them in the blood of the prophets.',
   'καὶ λέγετε· Εἰ ἤμεθα ἐν ταῖς ἡμέραις τῶν πατέρων ἡμῶν, οὐκ ἂν ἤμεθα κοινωνοὶ αὐτῶν ἐν τῷ αἵματι τῶν προφητῶν',
   'kai legete: Ei ēmetha en tais hēmerais tōn paterōn hēmōn, ouk an ēmetha koinōnoi autōn en tō aimati tōn prophētōn',
   'Self-righteous distance from past sins while preparing to commit the climactic sin. The very generation about to crucify the Messiah claims it would never have done what their fathers did.',
   'Self-deception about one''s capacity for evil is the soul''s most dangerous condition. Those who say "I would never" are usually about to.'),
  (31, 'Wherefore ye be witnesses unto yourselves, that ye are the children of them which killed the prophets.',
   'ὥστε μαρτυρεῖτε ἑαυτοῖς ὅτι υἱοί ἐστε τῶν φονευσάντων τοὺς προφήτας',
   'hōste martyreite heautois hoti hyioi este tōn phoneusantōn tous prophētas',
   '"Children" (hyioi) — sons not by genealogy alone but by sharing the same heart. To call those killers "fathers" while planning the same crime is to confess kinship in murderous unbelief.',
   'Spiritual lineage matters more than genetic. Whom we resemble in heart determines our true ancestry before God.'),
  (32, 'Fill ye up then the measure of your fathers.',
   'καὶ ὑμεῖς πληρώσατε τὸ μέτρον τῶν πατέρων ὑμῶν',
   'kai hymeis plērōsate to metron tōn paterōn hymōn',
   'A bitter prophetic irony — like Isaiah 6''s "make their hearts fat." God permits the leaders to fill the cup of iniquity to the brim with the climactic sin of crucifying His Son. Cf. Gen 15:16.',
   'God''s patience with persistent sin culminates in handing over the wicked to their chosen course (Rom 1:24-28). The full cup invites the full judgment.'),
  (33, 'Ye serpents, ye generation of vipers, how can ye escape the damnation of hell?',
   'ὄφεις, γεννήματα ἐχιδνῶν, πῶς φύγητε ἀπὸ τῆς κρίσεως τῆς γεέννης',
   'opheis, gennēmata echidnōn, pōs phygēte apo tēs kriseōs tēs geennēs',
   'Echoes John the Baptist''s opening words (Mt 3:7) — Jesus closes His public ministry with the same indictment with which the Forerunner opened. "Generation of vipers" = offspring of the serpent (Gen 3:15; Jn 8:44).',
   'Genuine spiritual lineage is from God or from the serpent. Christ''s severity exposes a kinship of evil that no religious veneer can disguise.'),
  (34, 'Wherefore, behold, I send unto you prophets, and wise men, and scribes: and some of them ye shall kill and crucify; and some of them shall ye scourge in your synagogues, and persecute them from city to city:',
   'διὰ τοῦτο ἰδοὺ ἐγὼ ἀποστέλλω πρὸς ὑμᾶς προφήτας καὶ σοφοὺς καὶ γραμματεῖς· ἐξ αὐτῶν ἀποκτενεῖτε καὶ σταυρώσετε, καὶ ἐξ αὐτῶν μαστιγώσετε ἐν ταῖς συναγωγαῖς ὑμῶν καὶ διώξετε ἀπὸ πόλεως εἰς πόλιν',
   'dia touto idou egō apostellō pros hymas prophētas kai sophous kai grammateis: ex autōn apokteneite kai staurōsete, kai ex autōn mastigōsete en tais synagōgais hymōn kai diōxete apo poleōs eis polin',
   '"I send" — Jesus speaks as the divine Sender, sovereign Lord of the prophets. "Crucify" foretells the apostolic martyrdoms (Peter, etc.). Synagogue scourgings echoed in Acts (5:40; 22:19) and Paul''s own confession (2 Cor 11:24).',
   'Christ Himself is the Sender of all true messengers. To reject His apostles is to reject Him. The pattern of suffering for the gospel was foretold by the Lord, not improvised by His servants.'),
  (35, 'That upon you may come all the righteous blood shed upon the earth, from the blood of righteous Abel unto the blood of Zacharias son of Barachias, whom ye slew between the temple and the altar.',
   'ὅπως ἔλθῃ ἐφ᾽ ὑμᾶς πᾶν αἷμα δίκαιον ἐκχυννόμενον ἐπὶ τῆς γῆς ἀπὸ τοῦ αἵματος Ἄβελ τοῦ δικαίου ἕως τοῦ αἵματος Ζαχαρίου υἱοῦ Βαραχίου, ὃν ἐφονεύσατε μεταξὺ τοῦ ναοῦ καὶ τοῦ θυσιαστηρίου',
   'hopōs elthē eph'' hymas pan haima dikaion ekchynnomenon epi tēs gēs apo tou haimatos Abel tou dikaiou heōs tou haimatos Zachariou hyiou Barachiou, hon ephoneusate metaxy tou naou kai tou thysiastēriou',
   'Abel = first martyr (Gen 4); Zechariah son of Jehoiada = last martyr in the Hebrew Bible''s order, killed between the temple and altar (2 Chr 24:20-22). The arc spans the whole OT canon. (The patronymic "son of Barachias" may follow an alternate naming tradition.)',
   'God holds generations corporately accountable for persistent unrepentance. The full weight of historical guilt falls on the generation that rejects the climactic revelation.'),
  (36, 'Verily I say unto you, All these things shall come upon this generation.',
   'ἀμὴν λέγω ὑμῖν, ἥξει ταῦτα πάντα ἐπὶ τὴν γενεὰν ταύτην',
   'amēn legō hymin, hēxei tauta panta epi tēn geneian tautēn',
   'A specific prophecy fulfilled in AD 70 when Roman armies destroyed Jerusalem and the temple — within forty years (a "generation"). Hist. Josephus describes the carnage in vivid detail.',
   'Christ''s prophetic word is precise. The destruction of Jerusalem in AD 70 is the historical seal of His authority and the visible judgment on covenant rejection.'),
  (37, 'O Jerusalem, Jerusalem, thou that killest the prophets, and stonest them which are sent unto thee, how often would I have gathered thy children together, even as a hen gathereth her chickens under her wings, and ye would not!',
   'Ἰερουσαλήμ, Ἰερουσαλήμ, ἡ ἀποκτείνουσα τοὺς προφήτας καὶ λιθοβολοῦσα τοὺς ἀπεσταλμένους πρὸς αὐτήν, ποσάκις ἠθέλησα ἐπισυναγαγεῖν τὰ τέκνα σου, ὃν τρόπον ὄρνις ἐπισυνάγει τὰ νοσσία αὐτῆς ὑπὸ τὰς πτέρυγας, καὶ οὐκ ἠθελήσατε',
   'Ierousalēm, Ierousalēm, hē apokteinousa tous prophētas kai lithobolousa tous apestalmenous pros autēn, posakis ēthelēsa episynagagein ta tekna sou, hon tropon ornis episynagei ta nossia autēs hypo tas pterygas, kai ouk ēthelēsate',
   '"How often I would have" — Christ claims to be the Yahweh of OT history who repeatedly sent the prophets to Israel. Hen-and-chicks imagery from Deut 32:11; Ps 17:8; 91:4 — the LORD as protective mother of His people.',
   'Behind every OT prophet stood the pre-incarnate Christ, longing to gather His people. The deity of Christ shines in this lament: He is the One whose love has been refused throughout the ages.'),
  (38, 'Behold, your house is left unto you desolate.',
   'ἰδοὺ ἀφίεται ὑμῖν ὁ οἶκος ὑμῶν ἔρημος',
   'idou aphietai hymin ho oikos hymōn erēmos',
   '"Your house" — no longer "My Father''s house" (21:13). The temple is now disowned. "Desolate" (erēmos) — laid waste, deserted. The Shekinah glory is about to depart, as it had in Ezekiel''s vision.',
   'When Christ withdraws, holy places become empty buildings. The temple''s outward grandeur could not survive the exit of its King.'),
  (39, 'For I say unto you, Ye shall not see me henceforth, till ye shall say, Blessed is he that cometh in the name of the Lord.',
   'λέγω γὰρ ὑμῖν, οὐ μή με ἴδητε ἀπ᾽ ἄρτι ἕως ἂν εἴπητε· Εὐλογημένος ὁ ἐρχόμενος ἐν ὀνόματι Κυρίου',
   'legō gar hymin, ou mē me idēte ap'' arti heōs an eipēte: Eulogēmenos ho erchomenos en onomati Kyriou',
   'Quotes Psalm 118:26, the same cry of v.21:9 but inverted in time: now they refuse it; one day they will utter it in faith. Many see this as a future national turning of Israel to Christ (cf. Rom 11:25-26; Zech 12:10).',
   'Israel''s present hardness is not final. A future "fullness" of Israel''s repentance and welcome of Messiah is foretold. Until then the King is hidden from those who refused Him.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Matthew' AND c.chapter_number = 23
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

-- =====================================================================
-- 3. WORD STUDIES
-- =====================================================================
INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (2, 'καθέδρας', 'kathedras', 'G2515', 'Seat / chair — the official seat of teaching authority. The Latin cathedra preserves this sense (cf. ex cathedra). A literal stone chair existed in synagogues for the Torah reader.', 1),
  (4, 'φορτία βαρέα', 'phortia barea', 'G5413/G926', 'Heavy burdens — bundles too heavy to carry. Contrast with Christ''s "burden is light" (Mt 11:30). Legalism multiplies what grace lifts.', 1),
  (5, 'φυλακτήρια', 'phylaktēria', 'G5440', 'Phylacteries (Heb. tefillin) — small leather boxes with parchment Scripture passages worn on forehead and arm in literal compliance with Deut 6:8. Ostentatiously wide ones marked claim to special piety.', 1),
  (5, 'κράσπεδα', 'kraspeda', 'G2899', 'Borders / tassels — the tzitzit fringes commanded in Num 15:38-39 to remind Israel of God''s commandments. Enlarging them was a way to display superior religious zeal.', 2),
  (8, 'Ῥαββί', 'Rhabbi', 'G4461', 'Rabbi — Hebrew "my great one," "my master." A title of honor for Torah scholars. Jesus forbids its competitive use among His disciples; one Master remains.', 1),
  (10, 'καθηγηταί', 'kathēgētai', 'G2519', 'Master / guide / instructor — "one who leads down a path." Used uniquely here in NT. Christ alone is the believer''s Guide-Teacher.', 1),
  (12, 'ταπεινωθήσεται / ὑψωθήσεται', 'tapeinōthēsetai / hypsōthēsetai', 'G5013/G5312', 'Shall be humbled / shall be exalted — both passives indicate God Himself as agent. The kingdom''s economy reverses worldly ascent.', 1),
  (13, 'Οὐαί', 'Ouai', 'G3759', 'Woe — a prophetic interjection combining grief and warning, judgment and lament. Not mere curse but holy sorrow over willful destruction. Repeated as a rhythmic refrain throughout the chapter.', 1),
  (15, 'προσήλυτον', 'prosēlyton', 'G4339', 'Proselyte — a Gentile fully converted to Judaism (circumcision, immersion, sacrifice). Pharisaic missionary effort was real but produced converts harder than themselves.', 1),
  (15, 'γεέννης', 'geennēs', 'G1067', 'Gehenna — the Valley of Hinnom outside Jerusalem, scene of child-sacrifice to Molech (2 Kgs 23:10), later a smoldering refuse pit. Used in NT as imagery of final punishment.', 2),
  (16, 'ὁδηγοὶ τυφλοί', 'hodēgoi typhloi', 'G3595/G5185', 'Blind guides — leaders without sight leading the sightless. The same image Jesus used in Mt 15:14 of the Pharisees. Both teacher and taught fall in the ditch together.', 1),
  (23, 'βαρύτερα', 'barytera', 'G926', 'Weightier matters — comparative of barys, heavy. Some commands carry more weight than others. Justice, mercy, faithfulness outweigh herb-tithes.', 1),
  (23, 'κρίσιν / ἔλεος / πίστιν', 'krisin / eleos / pistin', 'G2920/G1656/G4102', 'Justice / mercy / faithfulness — the triad echoing Micah 6:8. The substance of true religion: rendering right judgments, extending mercy to the weak, walking faithfully with God.', 2),
  (24, 'διϋλίζοντες κώνωπα', 'diylizontes kōnōpa', 'G1368/G2971', 'Strain out a gnat — to filter wine through cloth to remove tiny insects. The Pharisees did this literally for ritual purity. The KJV "at" reflects an old printing convention; the sense is "out."', 1),
  (24, 'κάμηλον καταπίνοντες', 'kamēlon katapinontes', 'G2574/G2666', 'Swallowing a camel — both gnat and camel were ceremonially unclean (Lev 11). The largest unclean animal swallowed while the smallest was strained out — the perfect picture of moral perspective lost.', 2),
  (25, 'ἁρπαγῆς', 'harpagēs', 'G724', 'Plundering / extortion — violent seizure, robbery. The contents of Pharisaic life were morally what extortioners take from victims.', 1),
  (25, 'ἀκρασίας', 'akrasias', 'G192', 'Self-indulgence / lack of self-control — the opposite of egkrateia (self-control). Inner unrestraint contrasted with outer ritual restraint.', 2),
  (27, 'τάφοις κεκονιαμένοις', 'taphois kekoniamenois', 'G5028/G2867', 'Whitewashed tombs — coated with lime before Passover so pilgrims would not contract ritual defilement by accidentally touching them. Beautiful in appearance, full of decay within.', 1),
  (28, 'ἀνομίας', 'anomias', 'G458', 'Lawlessness / iniquity — literally "no-law-ness." The Pharisees claimed to defend the law yet inwardly violated it. The same word describes the eschatological "man of lawlessness" (2 Th 2:3).', 1),
  (33, 'γεννήματα ἐχιδνῶν', 'gennēmata echidnōn', 'G1081/G2191', 'Generation / brood of vipers — offspring of the serpent. Same indictment as John the Baptist (Mt 3:7) and Jesus earlier (Mt 12:34). Identifies the spiritual lineage as that of the serpent of Gen 3:15.', 1),
  (34, 'ἀποστέλλω', 'apostellō', 'G649', 'I send forth — Jesus speaks with divine authority as the Sender of prophets and apostles. The verb is the root of apostolos ("sent one"). Christ is the originator of all true mission.', 1),
  (37, 'ἐπισυναγαγεῖν', 'episynagagein', 'G1996', 'To gather together — used of God''s gathering of His scattered people (cf. Mt 24:31). The mother-hen image expresses Christ''s pre-incarnate care for Israel throughout her history.', 1),
  (37, 'ὄρνις', 'ornis', 'G3733', 'Hen / mother bird — protective imagery from Deut 32:11; Ps 17:8; 91:4 where YHWH shelters His people under His wings. Christ identifies Himself with the LORD of these texts.', 2),
  (38, 'ἔρημος', 'erēmos', 'G2048', 'Desolate / deserted / abandoned — the same root as "wilderness." When the divine presence withdraws, the holy place becomes a wasteland. Echoes Ezekiel''s vision of glory departing (Ezek 10).', 1),
  (39, 'Εὐλογημένος', 'Eulogēmenos', 'G2127', 'Blessed — perfect passive participle, "having been blessed and remaining so." From Psalm 118:26. The future cry of repentant Israel welcoming her returning Messiah.', 1)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Matthew' AND c.chapter_number = 23 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

-- =====================================================================
-- 4. CROSS REFERENCES
-- =====================================================================
INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (2, 'Nehemiah 8:4-8', 1),
  (2, 'Malachi 2:7', 2),
  (3, 'Romans 2:21-23', 1),
  (3, 'Titus 1:16', 2),
  (4, 'Luke 11:46', 1),
  (4, 'Matthew 11:28-30', 2),
  (4, 'Acts 15:10', 3),
  (5, 'Matthew 6:1-5', 1),
  (5, 'Deuteronomy 6:8', 2),
  (5, 'Numbers 15:37-41', 3),
  (6, 'Mark 12:38-39', 1),
  (6, 'Luke 14:7-11', 2),
  (8, 'James 3:1', 1),
  (8, '1 Corinthians 3:5-7', 2),
  (9, 'Malachi 2:10', 1),
  (9, 'Ephesians 4:6', 2),
  (11, 'Matthew 20:26-27', 1),
  (11, 'Mark 10:43-44', 2),
  (12, 'Luke 14:11', 1),
  (12, 'Luke 18:14', 2),
  (12, 'James 4:10', 3),
  (12, '1 Peter 5:6', 4),
  (13, 'Luke 11:52', 1),
  (13, 'Matthew 21:31-32', 2),
  (14, 'Mark 12:40', 1),
  (14, 'Luke 20:47', 2),
  (15, 'Acts 13:10', 1),
  (15, 'Galatians 4:17', 2),
  (16, 'Matthew 5:33-37', 1),
  (16, 'Matthew 15:14', 2),
  (17, 'Exodus 30:29', 1),
  (21, '1 Kings 8:13', 1),
  (21, 'Psalm 26:8', 2),
  (22, 'Isaiah 66:1', 1),
  (22, 'Matthew 5:34', 2),
  (23, 'Micah 6:8', 1),
  (23, 'Hosea 6:6', 2),
  (23, 'Luke 11:42', 3),
  (23, '1 Samuel 15:22', 4),
  (24, 'Leviticus 11:4', 1),
  (24, 'Leviticus 11:41-42', 2),
  (25, 'Mark 7:4', 1),
  (25, 'Luke 11:39', 2),
  (26, 'Jeremiah 4:14', 1),
  (26, 'Psalm 51:6-10', 2),
  (26, 'Titus 3:5', 3),
  (27, 'Acts 23:3', 1),
  (27, 'Numbers 19:16', 2),
  (28, 'Luke 16:15', 1),
  (28, '2 Timothy 3:5', 2),
  (29, 'Luke 11:47-48', 1),
  (30, '2 Chronicles 36:15-16', 1),
  (32, 'Genesis 15:16', 1),
  (32, '1 Thessalonians 2:15-16', 2),
  (33, 'Matthew 3:7', 1),
  (33, 'Matthew 12:34', 2),
  (33, 'John 8:44', 3),
  (34, '2 Chronicles 36:15', 1),
  (34, 'Acts 5:40', 2),
  (34, 'Acts 7:52', 3),
  (34, '2 Corinthians 11:24-25', 4),
  (35, 'Genesis 4:8-10', 1),
  (35, '2 Chronicles 24:20-22', 2),
  (35, 'Hebrews 11:4', 3),
  (35, 'Revelation 18:24', 4),
  (36, 'Matthew 24:34', 1),
  (36, '1 Thessalonians 2:16', 2),
  (37, 'Deuteronomy 32:11', 1),
  (37, 'Psalm 17:8', 2),
  (37, 'Psalm 91:4', 3),
  (37, 'Luke 13:34', 4),
  (37, '2 Peter 3:9', 5),
  (38, 'Jeremiah 22:5', 1),
  (38, 'Ezekiel 10:18-19', 2),
  (38, 'Acts 6:13-14', 3),
  (39, 'Psalm 118:26', 1),
  (39, 'Romans 11:25-27', 2),
  (39, 'Zechariah 12:10', 3),
  (39, 'Hosea 3:4-5', 4)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Matthew' AND c.chapter_number = 23 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
