-- Revelation Chapter 21: The New Heaven, the New Earth, and the New Jerusalem
-- Step 1: Chapter metadata
INSERT INTO chapters (book_id, chapter_number, overview, theme, key_word_original, key_word_meaning, outline)
SELECT b.id,
  21,
  'After the dissolution of the first creation, John sees a new heaven and a new earth, and the holy city, New Jerusalem, descending from God. God Himself dwells with His people. Tears, death, sorrow, crying, and pain are abolished. The Bride-City is measured: a luminous cube of jasper and gold, twelve gates of pearl named for the tribes of Israel, twelve foundations named for the apostles of the Lamb. There is no temple, for the Lord God Almighty and the Lamb are its temple; no sun, for the glory of God is its light. Nothing unclean enters; only those whose names are written in the Lamb''s book of life.',
  'All Things New: The Bride-City Comes Down from God',
  'καινός',
  'New (kainos) — qualitatively new, not merely chronologically more recent. A renewed creation of unprecedented kind.',
  '["1-8 New heaven and new earth; God dwells with men", "9-14 The holy city — its wall, gates, and foundations", "15-21 Measurements and materials of New Jerusalem", "22-27 No temple, no sun, no night, no defilement"]'::jsonb
FROM books b WHERE b.name = 'Revelation'
ON CONFLICT (book_id, chapter_number) DO UPDATE SET
  overview = EXCLUDED.overview,
  theme = EXCLUDED.theme,
  key_word_original = EXCLUDED.key_word_original,
  key_word_meaning = EXCLUDED.key_word_meaning,
  outline = EXCLUDED.outline;

-- Step 2: Verses
INSERT INTO verses (chapter_id, verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
SELECT c.id, v.verse_number, v.kjv_text, v.original_text, v.transliteration, v.study_note, v.doctrinal_note
FROM chapters c
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1,
   'And I saw a new heaven and a new earth: for the first heaven and the first earth were passed away; and there was no more sea.',
   'Καὶ εἶδον οὐρανὸν καινὸν καὶ γῆν καινήν· ὁ γὰρ πρῶτος οὐρανὸς καὶ ἡ πρώτη γῆ ἀπῆλθαν, καὶ ἡ θάλασσα οὐκ ἔστιν ἔτι.',
   'Kai eidon ouranon kainon kai gēn kainēn; ho gar prōtos ouranos kai hē prōtē gē apēlthan, kai hē thalassa ouk estin eti.',
   'καινός (qualitatively new), not νέος (chronologically new). The vision echoes Isa 65:17; 66:22. The "no more sea" recalls Revelation''s sea as origin of the beast (13:1) and reservoir of the dead (20:13).',
   'Creation is not annihilated but renewed — paralleling the resurrection of the body. The Christian hope is not escape from matter but its glorification.'),
  (2,
   'And I John saw the holy city, new Jerusalem, coming down from God out of heaven, prepared as a bride adorned for her husband.',
   'καὶ τὴν πόλιν τὴν ἁγίαν Ἰερουσαλὴμ καινὴν εἶδον καταβαίνουσαν ἐκ τοῦ οὐρανοῦ ἀπὸ τοῦ Θεοῦ, ἡτοιμασμένην ὡς νύμφην κεκοσμημένην τῷ ἀνδρὶ αὐτῆς.',
   'kai tēn polin tēn hagian Ierousalēm kainēn eidon katabainousan ek tou ouranou apo tou Theou, hētoimasmenēn hōs nymphēn kekosmēmenēn tō andri autēs.',
   'The city descends — heaven comes to earth, not vice versa. Two metaphors fuse: city (πόλις, civic order) and bride (νύμφη, intimate love). Both are perfectly prepared (ἡτοιμασμένην).',
   'The dwelling of God with man is not a private mystic union but a corporate, public, civic reality — a city. Salvation is communal, not solitary.'),
  (3,
   'And I heard a great voice out of heaven saying, Behold, the tabernacle of God is with men, and he will dwell with them, and they shall be his people, and God himself shall be with them, and be their God.',
   'καὶ ἤκουσα φωνῆς μεγάλης ἐκ τοῦ θρόνου λεγούσης, Ἰδοὺ ἡ σκηνὴ τοῦ Θεοῦ μετὰ τῶν ἀνθρώπων, καὶ σκηνώσει μετ᾽ αὐτῶν, καὶ αὐτοὶ λαοὶ αὐτοῦ ἔσονται, καὶ αὐτὸς ὁ Θεὸς μετ᾽ αὐτῶν ἔσται, αὐτῶν Θεός.',
   'kai ēkousa phōnēs megalēs ek tou thronou legousēs, Idou hē skēnē tou Theou meta tōn anthrōpōn, kai skēnōsei met'' autōn, kai autoi laoi autou esontai, kai autos ho Theos met'' autōn estai, autōn Theos.',
   'σκηνή ("tabernacle") and σκηνώσει ("shall dwell") evoke the wilderness tent and John 1:14 ("the Word became flesh and tabernacled"). The covenant formula "they shall be my people, I will be their God" (Ex 6:7; Jer 31:33) reaches its zenith.',
   'Every covenant from Eden to Sinai to Calvary aimed at this one goal: God with us. Immanuel is not only Christ''s name but the consummation of redemption.'),
  (4,
   'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.',
   'καὶ ἐξαλείψει πᾶν δάκρυον ἐκ τῶν ὀφθαλμῶν αὐτῶν, καὶ ὁ θάνατος οὐκ ἔσται ἔτι, οὔτε πένθος οὔτε κραυγὴ οὔτε πόνος οὐκ ἔσται ἔτι, ὅτι τὰ πρῶτα ἀπῆλθαν.',
   'kai exaleipsei pan dakryon ek tōn ophthalmōn autōn, kai ho thanatos ouk estai eti, oute penthos oute kraugē oute ponos ouk estai eti, hoti ta prōta apēlthan.',
   'Five "no mores": tears, death, mourning, crying, pain. The verb ἐξαλείψει ("shall wipe out") is tender and personal — God''s own hand. πένθος is the grief of bereavement; κραυγή is the cry of distress; πόνος is the labor of pain.',
   'Heaven includes the wiping away of tears — implying that some tears arrive there with us. The Comforter completes His ministry face to face.'),
  (5,
   'And he that sat upon the throne said, Behold, I make all things new. And he said unto me, Write: for these words are true and faithful.',
   'καὶ εἶπεν ὁ καθήμενος ἐπὶ τῷ θρόνῳ, Ἰδοὺ καινὰ ποιῶ πάντα. καὶ λέγει, Γράψον, ὅτι οὗτοι οἱ λόγοι πιστοὶ καὶ ἀληθινοί εἰσιν.',
   'kai eipen ho kathēmenos epi tō thronō, Idou kaina poiō panta. kai legei, Grapson, hoti houtoi hoi logoi pistoi kai alēthinoi eisin.',
   'God speaks directly in Revelation only twice (1:8; here). καινὰ ποιῶ πάντα — "I make all things new" — is the divine slogan of restoration. πιστοὶ καὶ ἀληθινοί ("faithful and true") are also Christ''s titles (19:11).',
   'God does not make all new things; He makes all things new. Redemption restores and elevates the original creation rather than discarding it.'),
  (6,
   'And he said unto me, It is done. I am Alpha and Omega, the beginning and the end. I will give unto him that is athirst of the fountain of the water of life freely.',
   'καὶ εἶπέν μοι, Γέγοναν. ἐγώ εἰμι τὸ Ἄλφα καὶ τὸ Ὦ, ἡ ἀρχὴ καὶ τὸ τέλος. ἐγὼ τῷ διψῶντι δώσω ἐκ τῆς πηγῆς τοῦ ὕδατος τῆς ζωῆς δωρεάν.',
   'kai eipen moi, Gegonan. egō eimi to Alpha kai to Ō, hē archē kai to telos. egō tō dipsōnti dōsō ek tēs pēgēs tou hydatos tēs zōēs dōrean.',
   'γέγοναν — perfect tense, "they have come to pass." The Alpha and Omega title ties this to the opening of the book (1:8). δωρεάν ("freely") closes the gap between thirst and supply: the gift is purely of grace.',
   'The gospel offer is not retracted at the end. The very last picture of God in the Bible is of One offering free water to thirsty souls.'),
  (7,
   'He that overcometh shall inherit all things; and I will be his God, and he shall be my son.',
   'ὁ νικῶν κληρονομήσει ταῦτα, καὶ ἔσομαι αὐτῷ Θεὸς καὶ αὐτὸς ἔσται μοι υἱός.',
   'ho nikōn klēronomēsei tauta, kai esomai autō Theos kai autos estai moi huios.',
   'ὁ νικῶν ("the one overcoming") — the recurring promise from chapters 2–3, finally redeemed. The Davidic adoption formula (2 Sam 7:14) is here universalized to every believer.',
   'Justification by faith and adoption are inseparable: those declared righteous are also made sons, with full inheritance rights (Rom 8:17).'),
  (8,
   'But the fearful, and unbelieving, and the abominable, and murderers, and whoremongers, and sorcerers, and idolaters, and all liars, shall have their part in the lake which burneth with fire and brimstone: which is the second death.',
   'τοῖς δὲ δειλοῖς καὶ ἀπίστοις καὶ ἐβδελυγμένοις καὶ φονεῦσιν καὶ πόρνοις καὶ φαρμάκοις καὶ εἰδωλολάτραις καὶ πᾶσιν τοῖς ψευδέσιν, τὸ μέρος αὐτῶν ἐν τῇ λίμνῃ τῇ καιομένῃ πυρὶ καὶ θείῳ, ὅ ἐστιν ὁ θάνατος ὁ δεύτερος.',
   'tois de deilois kai apistois kai ebdelygmenois kai phoneusin kai pornois kai pharmakois kai eidōlolatrais kai pasin tois pseudesin, to meros autōn en tē limnē tē kaiomenē pyri kai theiō, ho estin ho thanatos ho deuteros.',
   'Eight categories of the excluded. δειλοί ("cowards") leads — the apostates who denied Christ under pressure. φάρμακος (sorcerer) gives English "pharmacy" — the dark arts of pagan religion.',
   'The reverse side of beatitude is solemn warning. Those who continue unrepentantly in these sins prove that they are not new creations and therefore have no place in the new creation.'),
  (9,
   'And there came unto me one of the seven angels which had the seven vials full of the seven last plagues, and talked with me, saying, Come hither, I will shew thee the bride, the Lamb''s wife.',
   'Καὶ ἦλθεν εἷς ἐκ τῶν ἑπτὰ ἀγγέλων τῶν ἐχόντων τὰς ἑπτὰ φιάλας τῶν γεμόντων τῶν ἑπτὰ πληγῶν τῶν ἐσχάτων, καὶ ἐλάλησεν μετ᾽ ἐμοῦ λέγων, Δεῦρο, δείξω σοι τὴν νύμφην τὴν γυναῖκα τοῦ Ἀρνίου.',
   'Kai ēlthen heis ek tōn hepta angelōn tōn echontōn tas hepta phialas tōn gemontōn tōn hepta plēgōn tōn eschatōn, kai elalēsen met'' emou legōn, Deuro, deixō soi tēn nymphēn tēn gynaika tou Arniou.',
   'Deliberate parallel with 17:1: a bowl-angel showed John the harlot; a bowl-angel now shows him the bride. Two cities, two women, two destinies.',
   'God''s purpose for the redeemed community is intimate union with Christ — not service alone, but marriage.'),
  (10,
   'And he carried me away in the spirit to a great and high mountain, and shewed me that great city, the holy Jerusalem, descending out of heaven from God,',
   'καὶ ἀπήνεγκέν με ἐν πνεύματι ἐπὶ ὄρος μέγα καὶ ὑψηλόν, καὶ ἔδειξέν μοι τὴν πόλιν τὴν ἁγίαν Ἰερουσαλὴμ καταβαίνουσαν ἐκ τοῦ οὐρανοῦ ἀπὸ τοῦ Θεοῦ,',
   'kai apēnenken me en pneumati epi oros mega kai hypsēlon, kai edeixen moi tēn polin tēn hagian Ierousalēm katabainousan ek tou ouranou apo tou Theou,',
   'Mountain visions echo Ezek 40:2. ἐν πνεύματι ("in the Spirit") marks Revelation''s great vision-points (1:10; 4:2; 17:3; 21:10).',
   'Revelation, the most pneumatic book of the canon, comes to those who are themselves "in the Spirit." Spiritual sight is the indispensable pre-condition of theological vision.'),
  (11,
   'Having the glory of God: and her light was like unto a stone most precious, even like a jasper stone, clear as crystal;',
   'ἔχουσαν τὴν δόξαν τοῦ Θεοῦ· ὁ φωστὴρ αὐτῆς ὅμοιος λίθῳ τιμιωτάτῳ, ὡς λίθῳ ἰάσπιδι κρυσταλλίζοντι·',
   'echousan tēn doxan tou Theou; ho phōstēr autēs homoios lithō timiōtatō, hōs lithō iaspidi krystallizonti;',
   'φωστήρ — luminary, lamp; cf. Gen 1:14 (LXX) of sun and moon. The city''s light is not its own; it shines because God''s glory is in it. ἴασπις (jasper) was the first stone in 4:3, around the throne.',
   'The church is light only as it reflects God''s glory (cf. 2 Cor 3:18). The brightness of the new creation is borrowed light, but no less real for that.'),
  (12,
   'And had a wall great and high, and had twelve gates, and at the gates twelve angels, and names written thereon, which are the names of the twelve tribes of the children of Israel:',
   'ἔχουσα τεῖχος μέγα καὶ ὑψηλόν, ἔχουσα πυλῶνας δώδεκα, καὶ ἐπὶ τοῖς πυλῶσιν ἀγγέλους δώδεκα, καὶ ὀνόματα ἐπιγεγραμμένα, ἅ ἐστιν τὰ ὀνόματα τῶν δώδεκα φυλῶν τῶν υἱῶν Ἰσραήλ.',
   'echousa teichos mega kai hypsēlon, echousa pylōnas dōdeka, kai epi tois pylōsin angelous dōdeka, kai onomata epigegrammena, ha estin ta onomata tōn dōdeka phylōn tōn huiōn Israēl.',
   'Twelve gates, twelve angel-guardians, twelve tribal names. The gates are not for defense but for ceremony; in v. 25 they are never shut.',
   'The promises to Israel are not erased in the eschaton; they are inscribed on the very gates of the city. There is one people of God, and Israel''s tribes are foundational to its access.'),
  (13,
   'On the east three gates; on the north three gates; on the south three gates; and on the west three gates.',
   'ἀπὸ ἀνατολῆς πυλῶνες τρεῖς, καὶ ἀπὸ βορρᾶ πυλῶνες τρεῖς, καὶ ἀπὸ νότου πυλῶνες τρεῖς, καὶ ἀπὸ δυσμῶν πυλῶνες τρεῖς.',
   'apo anatolēs pylōnes treis, kai apo borra pylōnes treis, kai apo notou pylōnes treis, kai apo dysmōn pylōnes treis.',
   'The arrangement matches the wilderness camp (Num 2) and Ezekiel''s ideal city (Ezek 48:30–34). Access from every direction signals a worldwide gathering.',
   'No quarter of the world is too distant. From east, north, south, and west the redeemed enter (Luke 13:29).'),
  (14,
   'And the wall of the city had twelve foundations, and in them the names of the twelve apostles of the Lamb.',
   'καὶ τὸ τεῖχος τῆς πόλεως ἔχων θεμελίους δώδεκα, καὶ ἐπ᾽ αὐτῶν δώδεκα ὀνόματα τῶν δώδεκα ἀποστόλων τοῦ Ἀρνίου.',
   'kai to teichos tēs poleōs echōn themelious dōdeka, kai ep'' autōn dōdeka onomata tōn dōdeka apostolōn tou Arniou.',
   'Twelve apostles — the New Testament counterpart of the twelve tribes. Together they witness one continuous people of God across both covenants (cf. Eph 2:20).',
   'The church is built on apostolic foundation — that is, on the apostles'' Christ-given testimony, now fixed for all time in the New Testament Scriptures.'),
  (15,
   'And he that talked with me had a golden reed to measure the city, and the gates thereof, and the wall thereof.',
   'Καὶ ὁ λαλῶν μετ᾽ ἐμοῦ εἶχεν μέτρον κάλαμον χρυσοῦν, ἵνα μετρήσῃ τὴν πόλιν καὶ τοὺς πυλῶνας αὐτῆς καὶ τὸ τεῖχος αὐτῆς.',
   'Kai ho lalōn met'' emou eichen metron kalamon chrysoun, hina metrēsē tēn polin kai tous pylōnas autēs kai to teichos autēs.',
   'A golden reed (κάλαμος) — measurement is an act of consecration (cf. Ezek 40:3; Rev 11:1). The reed is gold to match the city.',
   'God measures what He owns. The new Jerusalem is precise, not vague — every dimension is divinely fixed.'),
  (16,
   'And the city lieth foursquare, and the length is as large as the breadth: and he measured the city with the reed, twelve thousand furlongs. The length and the breadth and the height of it are equal.',
   'καὶ ἡ πόλις τετράγωνος κεῖται, καὶ τὸ μῆκος αὐτῆς ὅσον τὸ πλάτος. καὶ ἐμέτρησεν τὴν πόλιν τῷ καλάμῳ ἐπὶ σταδίων δώδεκα χιλιάδων· τὸ μῆκος καὶ τὸ πλάτος καὶ τὸ ὕψος αὐτῆς ἴσα ἐστίν.',
   'kai hē polis tetragōnos keitai, kai to mēkos autēs hoson to platos. kai emetrēsen tēn polin tō kalamō epi stadiōn dōdeka chiliadōn; to mēkos kai to platos kai to hypsos autēs isa estin.',
   'τετράγωνος ("four-square"); the cube shape (length = width = height) was the form of the holy of holies in the temple (1 Kgs 6:20). The whole city is now most-holy place. 12,000 furlongs (στάδιον) ≈ 1,400 miles per side.',
   'The whole redeemed community lives in the immediate presence of God. The veil is gone; the holy of holies is everywhere.'),
  (17,
   'And he measured the wall thereof, an hundred and forty and four cubits, according to the measure of a man, that is, of the angel.',
   'καὶ ἐμέτρησεν τὸ τεῖχος αὐτῆς ἑκατὸν τεσσεράκοντα τεσσάρων πηχῶν, μέτρον ἀνθρώπου, ὅ ἐστιν ἀγγέλου.',
   'kai emetrēsen to teichos autēs hekaton tesserakonta tessarōn pēchōn, metron anthrōpou, ho estin angelou.',
   '144 (= 12 × 12) cubits — a symbolic number embracing both Israel''s tribes and Christ''s apostles. "Of a man, that is, of the angel" — human measurement is also angelic in this realm; the wall, by city standards, is modest.',
   'Symbolism speaks where literal proportion fails. The wall is for identity (insiders/outsiders) more than defense.'),
  (18,
   'And the building of the wall of it was of jasper: and the city was pure gold, like unto clear glass.',
   'καὶ ἡ ἐνδώμησις τοῦ τείχους αὐτῆς ἴασπις, καὶ ἡ πόλις χρυσίον καθαρὸν ὅμοιον ὑάλῳ καθαρῷ.',
   'kai hē endōmēsis tou teichous autēs iaspis, kai hē polis chrysion katharon homoion hyalō katharō.',
   'ἐνδώμησις ("building material," masonry). Gold "like clear glass" — refined to translucency, no longer opaque. Glory fills every street.',
   'Earthly riches reach their highest use as building material for God''s presence. What men hoard, God paves with.'),
  (19,
   'And the foundations of the wall of the city were garnished with all manner of precious stones. The first foundation was jasper; the second, sapphire; the third, a chalcedony; the fourth, an emerald;',
   'οἱ θεμέλιοι τοῦ τείχους τῆς πόλεως παντὶ λίθῳ τιμίῳ κεκοσμημένοι· ὁ θεμέλιος ὁ πρῶτος ἴασπις, ὁ δεύτερος σάπφειρος, ὁ τρίτος χαλκηδών, ὁ τέταρτος σμάραγδος,',
   'hoi themelioi tou teichous tēs poleōs panti lithō timiō kekosmēmenoi; ho themelios ho prōtos iaspis, ho deuteros sappheiros, ho tritos chalkēdōn, ho tetartos smaragdos,',
   'The list parallels the high priest''s breastplate (Ex 28:17–20), declaring the city itself a priestly garment. Twelve gemstones for twelve apostles.',
   'The church carries on the priestly representation of God''s people, mediating worship in the new creation.'),
  (20,
   'The fifth, sardonyx; the sixth, sardius; the seventh, chrysolyte; the eighth, beryl; the ninth, a topaz; the tenth, a chrysoprasus; the eleventh, a jacinth; the twelfth, an amethyst.',
   'ὁ πέμπτος σαρδόνυξ, ὁ ἕκτος σάρδιον, ὁ ἕβδομος χρυσόλιθος, ὁ ὄγδοος βήρυλλος, ὁ ἔνατος τοπάζιον, ὁ δέκατος χρυσόπρασος, ὁ ἑνδέκατος ὑάκινθος, ὁ δωδέκατος ἀμέθυστος.',
   'ho pemptos sardonyx, ho hektos sardion, ho hebdomos chrysolithos, ho ogdoos bēryllos, ho enatos topazion, ho dekatos chrysoprasos, ho hendekatos hyakinthos, ho dōdekatos amethystos.',
   'The twelve gems span the spectrum of color and refraction — green, blue, red, gold, violet — making the city a prismatic kaleidoscope of glory.',
   'Beauty is a divine attribute. The new creation is not utilitarian but stunningly aesthetic; the redeemed live in artistry as well as truth.'),
  (21,
   'And the twelve gates were twelve pearls; every several gate was of one pearl: and the street of the city was pure gold, as it were transparent glass.',
   'καὶ οἱ δώδεκα πυλῶνες δώδεκα μαργαρῖται, ἀνὰ εἷς ἕκαστος τῶν πυλώνων ἦν ἐξ ἑνὸς μαργαρίτου. καὶ ἡ πλατεῖα τῆς πόλεως χρυσίον καθαρὸν ὡς ὕαλος διαυγής.',
   'kai hoi dōdeka pylōnes dōdeka margaritai, ana heis hekastos tōn pylōnōn ēn ex henos margaritou. kai hē plateia tēs poleōs chrysion katharon hōs hyalos diaugēs.',
   'A single pearl per gate — pearls of impossible scale. Pearls form by an oyster''s response to wounding; the gates of glory bear the marks of suffering transformed.',
   'Entry to the kingdom is through pearl — through wounds, ultimately Christ''s wounds (Isa 53:5). There is no other gate.'),
  (22,
   'And I saw no temple therein: for the Lord God Almighty and the Lamb are the temple of it.',
   'Καὶ ναὸν οὐκ εἶδον ἐν αὐτῇ, ὁ γὰρ Κύριος ὁ Θεὸς ὁ παντοκράτωρ ναὸς αὐτῆς ἐστιν, καὶ τὸ Ἀρνίον.',
   'Kai naon ouk eidon en autē, ho gar Kyrios ho Theos ho pantokratōr naos autēs estin, kai to Arnion.',
   'A startling absence: no temple. ναός (sanctuary, holy place) is not needed because the city''s entire reality is communion with God. Father and Lamb are spoken of with a single noun ναός — a profound affirmation of the deity of Christ.',
   'All temples — Solomonic, Herodian, even the church''s building — are scaffolding. When God dwells with His people unmediated, scaffolding falls away.'),
  (23,
   'And the city had no need of the sun, neither of the moon, to shine in it: for the glory of God did lighten it, and the Lamb is the light thereof.',
   'καὶ ἡ πόλις οὐ χρείαν ἔχει τοῦ ἡλίου οὐδὲ τῆς σελήνης, ἵνα φαίνωσιν αὐτῇ· ἡ γὰρ δόξα τοῦ Θεοῦ ἐφώτισεν αὐτήν, καὶ ὁ λύχνος αὐτῆς τὸ Ἀρνίον.',
   'kai hē polis ou chreian echei tou hēliou oude tēs selēnēs, hina phainōsin autē; hē gar doxa tou Theou ephōtisen autēn, kai ho lychnos autēs to Arnion.',
   'Echoes Isa 60:19. The Lamb is the λύχνος (lamp) holding the divine light. Christ does not compete with the Father''s glory; He embodies and irradiates it.',
   'Christ is presented as the divine Lamp — the chosen and proper bearer of God''s glory. The Trinitarian relations are shown in the very architecture of light.'),
  (24,
   'And the nations of them which are saved shall walk in the light of it: and the kings of the earth do bring their glory and honour into it.',
   'καὶ περιπατήσουσιν τὰ ἔθνη διὰ τοῦ φωτὸς αὐτῆς· καὶ οἱ βασιλεῖς τῆς γῆς φέρουσιν τὴν δόξαν αὐτῶν εἰς αὐτήν.',
   'kai peripatēsousin ta ethnē dia tou phōtos autēs; kai hoi basileis tēs gēs pherousin tēn doxan autōn eis autēn.',
   'Nations (ἔθνη) and their kings — categories that throughout Revelation oppose the Lamb — here process in worship (Isa 60:3). The redeemed cultural achievements of humanity are brought in.',
   'Heaven includes culture redeemed. The genuine "glory" of the nations — art, science, music, justice — is purified and offered to God, not destroyed.'),
  (25,
   'And the gates of it shall not be shut at all by day: for there shall be no night there.',
   'καὶ οἱ πυλῶνες αὐτῆς οὐ μὴ κλεισθῶσιν ἡμέρας, νὺξ γὰρ οὐκ ἔσται ἐκεῖ.',
   'kai hoi pylōnes autēs ou mē kleisthōsin hēmeras, nyx gar ouk estai ekei.',
   'Open gates would have signaled an unimaginable peace in the ancient city; the absence of night makes them open continuously. Cf. Isa 60:11.',
   'Perfect security and perfect access coexist. The kingdom is not a fortress against love.'),
  (26,
   'And they shall bring the glory and honour of the nations into it.',
   'καὶ οἴσουσιν τὴν δόξαν καὶ τὴν τιμὴν τῶν ἐθνῶν εἰς αὐτήν.',
   'kai oisousin tēn doxan kai tēn timēn tōn ethnōn eis autēn.',
   'Repetition for emphasis. δόξαν καὶ τιμὴν (glory and honour) is a hendiadys for "all that is most precious." All earthly tribute is now Godward.',
   'Mission''s ultimate end is doxology — every nation bringing its best to the throne (Ps 22:27).'),
  (27,
   'And there shall in no wise enter into it any thing that defileth, neither whatsoever worketh abomination, or maketh a lie: but they which are written in the Lamb''s book of life.',
   'καὶ οὐ μὴ εἰσέλθῃ εἰς αὐτὴν πᾶν κοινὸν καὶ ποιῶν βδέλυγμα καὶ ψεῦδος, εἰ μὴ οἱ γεγραμμένοι ἐν τῷ βιβλίῳ τῆς ζωῆς τοῦ Ἀρνίου.',
   'kai ou mē eiselthē eis autēn pan koinon kai poiōn bdelygma kai pseudos, ei mē hoi gegrammenoi en tō bibliō tēs zōēs tou Arniou.',
   'Triple exclusion: the common (κοινόν), the abominable (βδέλυγμα), the false (ψεῦδος). Triple double negative (οὐ μὴ … εἰ μὴ) — strongest form of denial. Entry is restricted to those in the Lamb''s book.',
   'Holiness is not optional in glory. The new Jerusalem is a holy city (v. 2); only those clothed in Christ''s righteousness — recorded in His book — enter.')
) AS v(verse_number, kjv_text, original_text, transliteration, study_note, doctrinal_note)
WHERE b.name = 'Revelation' AND c.chapter_number = 21
ON CONFLICT (chapter_id, verse_number) DO UPDATE SET
  kjv_text = EXCLUDED.kjv_text,
  original_text = EXCLUDED.original_text,
  transliteration = EXCLUDED.transliteration,
  study_note = EXCLUDED.study_note,
  doctrinal_note = EXCLUDED.doctrinal_note;

-- Step 3: Word studies
INSERT INTO word_studies (verse_id, original_word, transliteration, strongs_number, meaning, word_order)
SELECT v.id, w.original_word, w.transliteration, w.strongs_number, w.meaning, w.word_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'καινός', 'kainos', 'G2537', 'New in kind, qualitatively unprecedented (vs. νέος, merely new in time). Used of the new covenant, new commandment, new creation.', 1),
  (2, 'νύμφη', 'nymphē', 'G3565', 'Bride; the church as the corporate Bride of Christ (cf. 19:7; Eph 5:25–27).', 1),
  (3, 'σκηνή', 'skēnē', 'G4633', 'Tent, tabernacle — the wilderness dwelling of God; the same root as the verb in John 1:14 ("the Word was made flesh and dwelt").', 1),
  (4, 'ἐξαλείφω', 'exaleiphō', 'G1813', 'To wipe out, blot out; used of God blotting out sins (Acts 3:19) and now of wiping every tear.', 1),
  (5, 'πιστός', 'pistos', 'G4103', 'Faithful, trustworthy — Christ''s own title (3:14; 19:11) and the warrant for our hope.', 1),
  (6, 'δωρεάν', 'dōrean', 'G1432', 'Freely, as a gift, without cost — emphatic adverb for grace; cf. Rom 3:24 ("justified freely").', 1),
  (7, 'κληρονομέω', 'klēronomeō', 'G2816', 'To inherit; the legal language of full sonship (Rom 8:17).', 1),
  (8, 'δειλός', 'deilos', 'G1169', 'Cowardly, timid — those who shrink back from confessing Christ (Mark 4:40; 2 Tim 1:7).', 1),
  (8, 'φάρμακος', 'pharmakos', 'G5333', 'Sorcerer, dealer in magical drugs — the dark arts of pagan religion.', 2),
  (10, 'πνεῦμα', 'pneuma', 'G4151', 'Spirit; "in the Spirit" marks Revelation''s major vision-points (1:10; 4:2; 17:3; 21:10).', 1),
  (11, 'φωστήρ', 'phōstēr', 'G5458', 'Luminary, source of light — used in Gen 1:14 LXX of sun and moon; here applied to the city.', 1),
  (16, 'τετράγωνος', 'tetragōnos', 'G5068', 'Four-square; combined with equal height makes a perfect cube — the shape of the holy of holies (1 Kgs 6:20).', 1),
  (19, 'θεμέλιος', 'themelios', 'G2310', 'Foundation — Christ Himself is foundation (1 Cor 3:11), and the apostles are foundation in derivative sense (Eph 2:20).', 1),
  (21, 'μαργαρίτης', 'margaritēs', 'G3135', 'Pearl — the costly pearl of the kingdom (Matt 13:46); formed by suffering, here become a gate of glory.', 1),
  (22, 'ναός', 'naos', 'G3485', 'Sanctuary, inner shrine — distinguished from ἱερόν (temple precinct). The Lord and the Lamb together are this inner shrine.', 1),
  (22, 'παντοκράτωρ', 'pantokratōr', 'G3841', 'Almighty, ruler of all — Revelation''s favorite title for God (used 9 times).', 2),
  (23, 'λύχνος', 'lychnos', 'G3088', 'Lamp — a vessel that holds and dispenses light. The Lamb holds and dispenses the Father''s glory.', 1),
  (27, 'βδέλυγμα', 'bdelygma', 'G946', 'Abomination, detestable thing — what is utterly repugnant to God (cf. Daniel''s "abomination of desolation").', 1)
) AS w(verse_number, original_word, transliteration, strongs_number, meaning, word_order)
WHERE b.name = 'Revelation' AND c.chapter_number = 21 AND v.verse_number = w.verse_number
ON CONFLICT DO NOTHING;

-- Step 4: Cross references
INSERT INTO cross_references (verse_id, reference, ref_order)
SELECT v.id, x.reference, x.ref_order
FROM verses v
JOIN chapters c ON v.chapter_id = c.id
JOIN books b ON c.book_id = b.id
CROSS JOIN (VALUES
  (1, 'Isaiah 65:17', 1),
  (1, 'Isaiah 66:22', 2),
  (1, '2 Peter 3:13', 3),
  (1, 'Romans 8:21', 4),
  (2, 'Revelation 19:7', 1),
  (2, 'Galatians 4:26', 2),
  (2, 'Hebrews 12:22', 3),
  (2, 'Ephesians 5:27', 4),
  (3, 'Leviticus 26:11-12', 1),
  (3, 'Ezekiel 37:27', 2),
  (3, '2 Corinthians 6:16', 3),
  (3, 'John 1:14', 4),
  (4, 'Isaiah 25:8', 1),
  (4, 'Isaiah 35:10', 2),
  (4, 'Revelation 7:17', 3),
  (4, '1 Corinthians 15:54', 4),
  (5, 'Isaiah 43:19', 1),
  (5, '2 Corinthians 5:17', 2),
  (5, 'Revelation 19:11', 3),
  (6, 'Revelation 1:8', 1),
  (6, 'Isaiah 55:1', 2),
  (6, 'John 4:14', 3),
  (6, 'John 7:37', 4),
  (7, 'Revelation 2:7', 1),
  (7, '2 Samuel 7:14', 2),
  (7, 'Romans 8:17', 3),
  (8, 'Revelation 22:15', 1),
  (8, '1 Corinthians 6:9-10', 2),
  (8, 'Galatians 5:19-21', 3),
  (8, 'Revelation 20:14', 4),
  (9, 'Revelation 17:1', 1),
  (9, 'Revelation 19:7', 2),
  (10, 'Ezekiel 40:2', 1),
  (10, 'Revelation 1:10', 2),
  (10, 'Revelation 4:2', 3),
  (11, 'Revelation 4:3', 1),
  (11, 'Isaiah 60:1-2', 2),
  (12, 'Ezekiel 48:31-34', 1),
  (12, 'Numbers 2:1-31', 2),
  (13, 'Ezekiel 48:30-34', 1),
  (13, 'Luke 13:29', 2),
  (14, 'Ephesians 2:20', 1),
  (14, 'Matthew 16:18', 2),
  (14, 'Hebrews 11:10', 3),
  (15, 'Ezekiel 40:3', 1),
  (15, 'Revelation 11:1', 2),
  (16, '1 Kings 6:20', 1),
  (16, 'Ezekiel 48:16', 2),
  (18, 'Revelation 21:21', 1),
  (19, 'Exodus 28:17-20', 1),
  (19, 'Isaiah 54:11-12', 2),
  (20, 'Exodus 28:17-20', 1),
  (21, 'Matthew 13:46', 1),
  (21, 'Isaiah 54:12', 2),
  (22, 'John 2:19-21', 1),
  (22, 'John 4:21-23', 2),
  (22, 'Hebrews 8:1-2', 3),
  (23, 'Isaiah 60:19-20', 1),
  (23, 'John 8:12', 2),
  (23, 'Revelation 22:5', 3),
  (24, 'Isaiah 60:3', 1),
  (24, 'Psalm 72:10-11', 2),
  (25, 'Isaiah 60:11', 1),
  (25, 'Zechariah 14:7', 2),
  (26, 'Isaiah 60:5', 1),
  (26, 'Psalm 22:27', 2),
  (27, 'Revelation 22:14-15', 1),
  (27, 'Isaiah 52:1', 2),
  (27, 'Revelation 13:8', 3),
  (27, 'Philippians 4:3', 4)
) AS x(verse_number, reference, ref_order)
WHERE b.name = 'Revelation' AND c.chapter_number = 21 AND v.verse_number = x.verse_number
ON CONFLICT DO NOTHING;
