-- ============================================================================
-- Quiz Seed: James (Chapters 1–5)
-- 3 difficulties × 5 chapters = 80 total questions
--   kids:   3 per chapter  = 15
--   teens:  5 per chapter  = 25
--   adults: 8 per chapter  = 40
-- ============================================================================

-- ═══ James Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('James', 1, 'kids', 1, 'What does James say we should feel when we face troubles?', 'Count it all joy', 'Count it all sadness', 'Count it all anger', 'Count it all fear', 'a', 'James 1:2 — "My brethren, count it all joy when ye fall into divers temptations."'),
('James', 1, 'kids', 2, 'If you need wisdom, what should you do?', 'Ask God for it', 'Read a fortune cookie', 'Ask a magician', 'Guess the answer', 'a', 'James 1:5 — "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not."'),
('James', 1, 'kids', 3, 'James says we should not just hear God''s word but also do what?', 'Be doers of the word', 'Forget about it', 'Argue about it', 'Write it on paper only', 'a', 'James 1:22 — "But be ye doers of the word, and not hearers only, deceiving your own selves."'),
-- Teens
('James', 1, 'teens', 1, 'What does the trying of your faith produce?', 'Patience', 'Wealth', 'Popularity', 'Magical power', 'a', 'James 1:3 — "Knowing this, that the trying of your faith worketh patience."'),
('James', 1, 'teens', 2, 'What is a double minded man compared to?', 'A wave of the sea driven with the wind and tossed', 'A strong oak tree', 'A solid rock', 'A mighty eagle', 'a', 'James 1:6 — "He that wavereth is like a wave of the sea driven with the wind and tossed."'),
('James', 1, 'teens', 3, 'What does lust bring forth when it is finished?', 'Sin, and sin when finished bringeth forth death', 'Happiness and wealth', 'Wisdom and understanding', 'Strength and power', 'a', 'James 1:15 — "Then when lust hath conceived, it bringeth forth sin: and sin, when it is finished, bringeth forth death."'),
('James', 1, 'teens', 4, 'What three things does James say every man should be?', 'Swift to hear, slow to speak, slow to wrath', 'Slow to hear, swift to speak, quick to anger', 'Quick to judge, slow to forgive, fast to act', 'First to speak, last to listen, quick to fight', 'a', 'James 1:19 — "Let every man be swift to hear, slow to speak, slow to wrath."'),
('James', 1, 'teens', 5, 'What is pure religion before God the Father?', 'To visit the fatherless and widows, and keep himself unspotted from the world', 'To attend church every day', 'To give all your money away', 'To fast and pray at all times', 'a', 'James 1:27 — "Pure religion and undefiled before God and the Father is this, To visit the fatherless and widows in their affliction, and to keep himself unspotted from the world."'),
-- Adults
('James', 1, 'adults', 1, 'Who does James identify himself as and who does he address?', 'A servant of God and of the Lord Jesus Christ, to the twelve tribes scattered abroad', 'The brother of Jesus, to the church in Jerusalem', 'An apostle of Christ, to the Gentiles', 'A prophet of Israel, to the Jewish leaders', 'a', 'James 1:1 — "James, a servant of God and of the Lord Jesus Christ, to the twelve tribes which are scattered abroad, greeting."'),
('James', 1, 'adults', 2, 'What does James say about God and temptation in verse 13?', 'God cannot be tempted with evil, neither tempteth he any man', 'God tempts people to test their strength', 'God allows temptation only for the righteous', 'God and evil are in constant battle over temptation', 'a', 'James 1:13 — "Let no man say when he is tempted, I am tempted of God: for God cannot be tempted with evil, neither tempteth he any man."'),
('James', 1, 'adults', 3, 'What does James say about every good and perfect gift?', 'It comes down from the Father of lights, with whom is no variableness, neither shadow of turning', 'It comes from human effort and hard work', 'It is earned through religious rituals', 'It comes from the angels who serve God', 'a', 'James 1:17 — "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning."'),
('James', 1, 'adults', 4, 'What does James call believers in verse 18?', 'A kind of firstfruits of his creatures', 'The final harvest of God''s plan', 'The remnant of Israel', 'The chosen elite of heaven', 'a', 'James 1:18 — "Of his own will begat he us with the word of truth, that we should be a kind of firstfruits of his creatures."'),
('James', 1, 'adults', 5, 'What does James compare the hearer who is not a doer to?', 'A man beholding his natural face in a glass who goes away and straightway forgetteth what manner of man he was', 'A wise builder who lays a strong foundation', 'A shepherd who tends his sheep carefully', 'A farmer who plants and waters diligently', 'a', 'James 1:23-24 — "He is like unto a man beholding his natural face in a glass: For he beholdeth himself, and goeth his way, and straightway forgetteth what manner of man he was."'),
('James', 1, 'adults', 6, 'What does James call the law that brings blessing to the doer?', 'The perfect law of liberty', 'The law of Moses', 'The law of the prophets', 'The law of circumcision', 'a', 'James 1:25 — "But whoso looketh into the perfect law of liberty, and continueth therein, he being not a forgetful hearer, but a doer of the work, this man shall be blessed in his deed."'),
('James', 1, 'adults', 7, 'What does James say about the low brother and the rich in verses 9-10?', 'The brother of low degree should rejoice that he is exalted; the rich that he is made low', 'The low should envy the rich; the rich should boast', 'The low should serve the rich; the rich should command', 'The low should hide; the rich should display their glory', 'a', 'James 1:9-10 — "Let the brother of low degree rejoice in that he is exalted: But the rich, in that he is made low: because as the flower of the grass he shall pass away."'),
('James', 1, 'adults', 8, 'What crown is promised to the man who endures temptation?', 'The crown of life, which the Lord hath promised to them that love him', 'The crown of thorns shared with Christ', 'The crown of righteousness for all believers', 'The crown of gold for the wealthy faithful', 'a', 'James 1:12 — "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him."');

-- ═══ James Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('James', 2, 'kids', 1, 'If a rich man and a poor man come to church, how should you treat them?', 'Treat them both the same', 'Give the rich man the best seat', 'Tell the poor man to leave', 'Only talk to the rich man', 'a', 'James 2:1-4 — James warns against showing favouritism, telling the poor man "Stand thou there" while giving the rich man a good place.'),
('James', 2, 'kids', 2, 'What does James call the commandment "Love thy neighbour as thyself"?', 'The royal law', 'The golden rule', 'The first commandment', 'The last commandment', 'a', 'James 2:8 — "If ye fulfil the royal law according to the scripture, Thou shalt love thy neighbour as thyself, ye do well."'),
('James', 2, 'kids', 3, 'What does James say about faith without doing good deeds?', 'It is dead', 'It is strong', 'It is the best kind', 'It does not matter', 'a', 'James 2:26 — "For as the body without the spirit is dead, so faith without works is dead also."'),
-- Teens
('James', 2, 'teens', 1, 'What does James say about showing respect of persons (favouritism)?', 'It is sin and transgression of the law', 'It is wise and practical', 'It is acceptable in church', 'It is a minor issue', 'a', 'James 2:9 — "But if ye have respect to persons, ye commit sin, and are convinced of the law as transgressors."'),
('James', 2, 'teens', 2, 'What happens if you keep the whole law but offend in one point?', 'You are guilty of all', 'You are still mostly righteous', 'God overlooks one mistake', 'That one point does not count', 'a', 'James 2:10 — "For whosoever shall keep the whole law, and yet offend in one point, he is guilty of all."'),
('James', 2, 'teens', 3, 'Who is the Old Testament example James uses for faith shown by works?', 'Abraham, when he offered Isaac his son upon the altar', 'Moses, when he parted the Red Sea', 'David, when he killed Goliath', 'Elijah, when he called down fire', 'a', 'James 2:21 — "Was not Abraham our father justified by works, when he had offered Isaac his son upon the altar?"'),
('James', 2, 'teens', 4, 'What other person besides Abraham showed faith by works?', 'Rahab the harlot, when she received the messengers', 'Ruth, when she followed Naomi', 'Esther, when she saved her people', 'Deborah, when she judged Israel', 'a', 'James 2:25 — "Likewise also was not Rahab the harlot justified by works, when she had received the messengers, and had sent them out another way?"'),
('James', 2, 'teens', 5, 'What does James compare faith without works to?', 'A body without the spirit', 'A sword without a handle', 'A ship without a sail', 'A crown without jewels', 'a', 'James 2:26 — "For as the body without the spirit is dead, so faith without works is dead also."'),
-- Adults
('James', 2, 'adults', 1, 'How does James describe the treatment of the poor man in the assembly?', 'Told to stand there or sit under the footstool while the rich man gets the good place', 'Given food and drink before the rich man', 'Asked to lead the congregation in prayer', 'Welcomed warmly by all the members', 'a', 'James 2:3 — "And ye say to the poor, Stand thou there, or sit here under my footstool."'),
('James', 2, 'adults', 2, 'What did God choose the poor of this world to be?', 'Rich in faith and heirs of the kingdom which he hath promised to them that love him', 'Leaders of the synagogues', 'Missionaries to foreign lands', 'Temple servants in Jerusalem', 'a', 'James 2:5 — "Hath not God chosen the poor of this world rich in faith, and heirs of the kingdom which he hath promised to them that love him?"'),
('James', 2, 'adults', 3, 'What does James say the rich do to believers?', 'They oppress you and draw you before the judgment seats', 'They help and support the church', 'They build synagogues for believers', 'They send gifts to the apostles', 'a', 'James 2:6 — "Do not rich men oppress you, and draw you before the judgment seats?"'),
('James', 2, 'adults', 4, 'What does James say about mercy and judgment?', 'Mercy rejoiceth against judgment', 'Judgment always triumphs over mercy', 'Mercy and judgment are equal', 'Judgment is unnecessary where mercy exists', 'a', 'James 2:13 — "For he shall have judgment without mercy, that hath shewed no mercy; and mercy rejoiceth against judgment."'),
('James', 2, 'adults', 5, 'What illustration shows that faith without works is dead?', 'Saying to a naked and hungry brother "be ye warmed and filled" without giving them things needful', 'Building a house on a strong foundation', 'Planting a vineyard and tending it carefully', 'Lighting a candle and placing it on a candlestick', 'a', 'James 2:15-16 — "If a brother or sister be naked, and destitute of daily food, And one of you say unto them, Depart in peace, be ye warmed and filled; notwithstanding ye give them not those things which are needful to the body; what doth it profit?"'),
('James', 2, 'adults', 6, 'What does James say the devils do regarding belief in God?', 'The devils also believe and tremble', 'The devils deny God exists', 'The devils worship God willingly', 'The devils are indifferent to God', 'a', 'James 2:19 — "Thou believest that there is one God; thou doest well: the devils also believe, and tremble."'),
('James', 2, 'adults', 7, 'How does James describe the relationship between faith and works in Abraham?', 'Faith wrought with his works, and by works was faith made perfect', 'Faith replaced his works entirely', 'Works were unnecessary alongside his faith', 'Faith and works were in conflict', 'a', 'James 2:22 — "Seest thou how faith wrought with his works, and by works was faith made perfect?"'),
('James', 2, 'adults', 8, 'What was Abraham called because of his faith?', 'The Friend of God', 'The Father of Nations', 'The Patriarch of Israel', 'The Servant of the Lord', 'a', 'James 2:23 — "And the scripture was fulfilled which saith, Abraham believed God, and it was imputed unto him for righteousness: and he was called the Friend of God."');

-- ═══ James Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('James', 3, 'kids', 1, 'What small body part can cause big trouble?', 'The tongue', 'The thumb', 'The ear', 'The nose', 'a', 'James 3:5-6 — "Even so the tongue is a little member, and boasteth great things. Behold, how great a matter a little fire kindleth!"'),
('James', 3, 'kids', 2, 'What does James compare the tongue to?', 'A fire', 'A flower', 'A river', 'A mountain', 'a', 'James 3:6 — "And the tongue is a fire, a world of iniquity."'),
('James', 3, 'kids', 3, 'Can a fountain send out both sweet and bitter water?', 'No, it cannot', 'Yes, all the time', 'Only on special days', 'Only in the summer', 'a', 'James 3:11 — "Doth a fountain send forth at the same place sweet water and bitter?"'),
-- Teens
('James', 3, 'teens', 1, 'Why does James warn against many becoming masters (teachers)?', 'Because they shall receive the greater condemnation', 'Because teachers earn less money', 'Because teachers are always lonely', 'Because there are already too many teachers', 'a', 'James 3:1 — "My brethren, be not many masters, knowing that we shall receive the greater condemnation."'),
('James', 3, 'teens', 2, 'What two small things does James say control bigger things, like the tongue?', 'A bit in a horse''s mouth and a small helm (rudder) on a ship', 'A key in a lock and a button on a coat', 'A seed in the ground and a drop in the ocean', 'A needle in a haystack and a star in the sky', 'a', 'James 3:3-4 — "We put bits in the horses'' mouths... Behold also the ships, which though they be so great... are turned about with a very small helm."'),
('James', 3, 'teens', 3, 'What does James say no man can tame?', 'The tongue', 'A wild lion', 'The wind', 'The sea', 'a', 'James 3:8 — "But the tongue can no man tame; it is an unruly evil, full of deadly poison."'),
('James', 3, 'teens', 4, 'What is the tongue full of according to James?', 'Deadly poison', 'Sweet honey', 'Living water', 'Golden words', 'a', 'James 3:8 — "It is an unruly evil, full of deadly poison."'),
('James', 3, 'teens', 5, 'How does James describe the wisdom that is from above?', 'Pure, peaceable, gentle, easy to be intreated, full of mercy and good fruits', 'Bold, commanding, authoritative, and powerful', 'Secretive, mysterious, hidden, and rare', 'Loud, forceful, aggressive, and dominating', 'a', 'James 3:17 — "But the wisdom that is from above is first pure, then peaceable, gentle, and easy to be intreated, full of mercy and good fruits, without partiality, and without hypocrisy."'),
-- Adults
('James', 3, 'adults', 1, 'What does James call the tongue in verse 6?', 'A world of iniquity that defileth the whole body and is set on fire of hell', 'A lamp that gives light to the body', 'A tool for building up the church', 'A weapon of warfare against enemies', 'a', 'James 3:6 — "And the tongue is a fire, a world of iniquity: so is the tongue among our members, that it defileth the whole body, and setteth on fire the course of nature; and it is set on fire of hell."'),
('James', 3, 'adults', 2, 'What contradiction does James point out about the tongue?', 'With it we bless God and curse men which are made after the similitude of God', 'With it we teach truth and learn lies', 'With it we sing praises and speak languages', 'With it we pray loudly and whisper softly', 'a', 'James 3:9 — "Therewith bless we God, even the Father; and therewith curse we men, which are made after the similitude of God."'),
('James', 3, 'adults', 3, 'What does James say about the fig tree bearing olive berries?', 'The fig tree cannot bear olive berries, neither can a vine yield figs', 'The fig tree sometimes bears olive berries in good seasons', 'The fig tree and olive tree are the same', 'Fig trees and vines can bear any fruit', 'a', 'James 3:12 — "Can the fig tree, my brethren, bear olive berries? either a vine, figs? so can no fountain both yield salt water and fresh."'),
('James', 3, 'adults', 4, 'How does James describe wisdom that is not from above?', 'Earthly, sensual, devilish', 'Heavenly, spiritual, divine', 'Simple, humble, gentle', 'Powerful, mighty, victorious', 'a', 'James 3:15 — "This wisdom descendeth not from above, but is earthly, sensual, devilish."'),
('James', 3, 'adults', 5, 'Where envying and strife exist, what does James say is found?', 'Confusion and every evil work', 'Peace and righteousness', 'Growth and prosperity', 'Wisdom and understanding', 'a', 'James 3:16 — "For where envying and strife is, there is confusion and every evil work."'),
('James', 3, 'adults', 6, 'In what is the fruit of righteousness sown?', 'In peace of them that make peace', 'In conflict of those who fight for justice', 'In solitude of those who meditate', 'In power of those who rule', 'a', 'James 3:18 — "And the fruit of righteousness is sown in peace of them that make peace."'),
('James', 3, 'adults', 7, 'Who should show his works with meekness of wisdom?', 'A wise man who is endued with knowledge', 'A strong warrior who wins battles', 'A wealthy merchant who earns profits', 'A king who governs his nation', 'a', 'James 3:13 — "Who is a wise man and endued with knowledge among you? let him shew out of a good conversation his works with meekness of wisdom."'),
('James', 3, 'adults', 8, 'What does James say those with bitter envying should not do?', 'Glory not and lie not against the truth', 'Leave the church immediately', 'Fast and pray for three days', 'Seek counsel from the elders', 'a', 'James 3:14 — "But if ye have bitter envying and strife in your hearts, glory not, and lie not against the truth."');

-- ═══ James Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('James', 4, 'kids', 1, 'What does James say to do when the devil comes?', 'Resist him and he will flee from you', 'Run away and hide', 'Ignore him completely', 'Try to be his friend', 'a', 'James 4:7 — "Resist the devil, and he will flee from you."'),
('James', 4, 'kids', 2, 'What happens when you draw near to God?', 'He will draw near to you', 'He will test you more', 'Nothing will change', 'He will hide from you', 'a', 'James 4:8 — "Draw nigh to God, and he will draw nigh to you."'),
('James', 4, 'kids', 3, 'Does James say we know what will happen tomorrow?', 'No, we do not know what tomorrow will bring', 'Yes, we can predict the future', 'Yes, if we pray hard enough', 'Only wise people know the future', 'a', 'James 4:14 — "Whereas ye know not what shall be on the morrow."'),
-- Teens
('James', 4, 'teens', 1, 'Where do wars and fightings come from according to James?', 'From your lusts that war in your members', 'From disagreements about the law', 'From other nations attacking', 'From misunderstandings between friends', 'a', 'James 4:1 — "From whence come wars and fightings among you? come they not hence, even of your lusts that war in your members?"'),
('James', 4, 'teens', 2, 'Why do people not receive what they ask God for?', 'Because they ask amiss, that they may consume it upon their lusts', 'Because God does not hear them', 'Because they did not ask loudly enough', 'Because God wants them to figure it out alone', 'a', 'James 4:3 — "Ye ask, and receive not, because ye ask amiss, that ye may consume it upon your lusts."'),
('James', 4, 'teens', 3, 'What does James call friendship with the world?', 'Enmity with God', 'A path to wisdom', 'A good way to witness', 'A necessary compromise', 'a', 'James 4:4 — "Know ye not that the friendship of the world is enmity with God? whosoever therefore will be a friend of the world is the enemy of God."'),
('James', 4, 'teens', 4, 'What does James say our life is like?', 'A vapour that appeareth for a little time and then vanisheth away', 'A mighty river that flows forever', 'A strong mountain that never moves', 'A bright star that always shines', 'a', 'James 4:14 — "For what is your life? It is even a vapour, that appeareth for a little time, and then vanisheth away."'),
('James', 4, 'teens', 5, 'What does God give to the humble?', 'Grace — God resisteth the proud but giveth grace unto the humble', 'Wealth and riches beyond measure', 'Political power and authority', 'Freedom from all suffering', 'a', 'James 4:6 — "God resisteth the proud, but giveth grace unto the humble."'),
-- Adults
('James', 4, 'adults', 1, 'What does James say the spirit that dwelleth in us lusteth to?', 'Envy', 'Righteousness', 'Charity', 'Purity', 'a', 'James 4:5 — "The spirit that dwelleth in us lusteth to envy."'),
('James', 4, 'adults', 2, 'What does James say about speaking evil of a brother?', 'He that speaketh evil of his brother speaketh evil of the law and judgeth the law', 'It is acceptable if the brother has sinned', 'It is only wrong if done in public', 'It does not affect one''s standing before God', 'a', 'James 4:11 — "He that speaketh evil of his brother, and judgeth his brother, speaketh evil of the law, and judgeth the law."'),
('James', 4, 'adults', 3, 'Who is the one lawgiver who is able to save and to destroy?', 'God alone', 'Moses', 'The high priest', 'The king of Israel', 'a', 'James 4:12 — "There is one lawgiver, who is able to save and to destroy: who art thou that judgest another?"'),
('James', 4, 'adults', 4, 'What should believers say instead of boasting about their plans?', 'If the Lord will, we shall live, and do this, or that', 'We will certainly accomplish our goals', 'Our plans will surely succeed', 'Nothing can stop our plans', 'a', 'James 4:15 — "For that ye ought to say, If the Lord will, we shall live, and do this, or that."'),
('James', 4, 'adults', 5, 'What does James say about all such rejoicing in one''s boastings?', 'All such rejoicing is evil', 'Such rejoicing is acceptable', 'Such rejoicing shows strong faith', 'Such rejoicing glorifies God', 'a', 'James 4:16 — "But now ye rejoice in your boastings: all such rejoicing is evil."'),
('James', 4, 'adults', 6, 'What is sin according to James 4:17?', 'To him that knoweth to do good, and doeth it not, to him it is sin', 'Only breaking the Ten Commandments', 'Only actions that harm other people', 'Only things done with evil intent', 'a', 'James 4:17 — "Therefore to him that knoweth to do good, and doeth it not, to him it is sin."'),
('James', 4, 'adults', 7, 'What does James mean by "ye adulterers and adulteresses" in verse 4?', 'Spiritual unfaithfulness to God through love of the world', 'Literal marital unfaithfulness', 'Worshipping in pagan temples', 'Breaking business agreements', 'a', 'James 4:4 — "Ye adulterers and adulteresses, know ye not that the friendship of the world is enmity with God?" This refers to spiritual adultery — unfaithfulness to God.'),
('James', 4, 'adults', 8, 'What series of imperatives does James give in verses 7-10 for drawing near to God?', 'Submit to God, resist the devil, draw nigh to God, cleanse your hands, purify your hearts, be afflicted, mourn, weep, humble yourselves', 'Pray more, give more, attend synagogue, fast weekly', 'Study the Torah, memorize the prophets, recite the psalms, teach the children', 'Travel to Jerusalem, offer sacrifices, consult the priests, observe the feasts', 'a', 'James 4:7-10 — "Submit yourselves therefore to God. Resist the devil... Draw nigh to God... Cleanse your hands, ye sinners; and purify your hearts, ye double minded. Be afflicted, and mourn, and weep... Humble yourselves in the sight of the Lord, and he shall lift you up."');

-- ═══ James Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('James', 5, 'kids', 1, 'Who does James tell to be patient, like a farmer waiting for rain?', 'The brethren (fellow believers)', 'The rich people', 'The kings and rulers', 'The young children', 'a', 'James 5:7 — "Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth."'),
('James', 5, 'kids', 2, 'What should you do if you are sick?', 'Call for the elders of the church to pray for you', 'Hide it from everyone', 'Try to heal yourself', 'Wait and hope it goes away', 'a', 'James 5:14 — "Is any sick among you? let him call for the elders of the church; and let them pray over him."'),
('James', 5, 'kids', 3, 'Whose prayer does James say is very powerful?', 'The prayer of a righteous man', 'The prayer of a king', 'The prayer of the richest person', 'The prayer of the oldest person', 'a', 'James 5:16 — "The effectual fervent prayer of a righteous man availeth much."'),
-- Teens
('James', 5, 'teens', 1, 'What does James warn the rich about?', 'Their riches are corrupted and their gold and silver is cankered', 'Their wealth will double in the last days', 'Their money will buy them salvation', 'Their riches will protect them from judgment', 'a', 'James 5:2-3 — "Your riches are corrupted, and your garments are motheaten. Your gold and silver is cankered."'),
('James', 5, 'teens', 2, 'Who does James use as examples of suffering and patience?', 'The prophets who spoke in the name of the Lord, and Job', 'The kings and princes of Israel', 'The Roman soldiers and generals', 'The Greek philosophers and teachers', 'a', 'James 5:10-11 — "Take, my brethren, the prophets, who have spoken in the name of the Lord, for an example of suffering affliction, and of patience. Ye have heard of the patience of Job."'),
('James', 5, 'teens', 3, 'What does James say about swearing oaths?', 'Let your yea be yea and your nay, nay', 'Swear by heaven for important promises', 'Always make oaths to show sincerity', 'Oaths are required for all agreements', 'a', 'James 5:12 — "But above all things, my brethren, swear not, neither by heaven, neither by the earth, neither by any other oath: but let your yea be yea; and your nay, nay."'),
('James', 5, 'teens', 4, 'What will the prayer of faith do for the sick?', 'Save the sick, and the Lord shall raise him up', 'Guarantee instant physical healing', 'Ensure the sick person becomes wealthy', 'Remove all future illness forever', 'a', 'James 5:15 — "And the prayer of faith shall save the sick, and the Lord shall raise him up."'),
('James', 5, 'teens', 5, 'How long did Elijah pray for no rain, and it did not rain?', 'Three years and six months', 'One year', 'Seven years', 'Forty days and nights', 'a', 'James 5:17 — "He prayed earnestly that it might not rain: and it rained not on the earth by the space of three years and six months."'),
-- Adults
('James', 5, 'adults', 1, 'Whose cries have entered into the ears of the Lord of sabaoth?', 'The labourers whose hire (wages) was kept back by fraud', 'The priests who served in the temple', 'The prophets who were rejected', 'The widows who lost their husbands', 'a', 'James 5:4 — "Behold, the hire of the labourers who have reaped down your fields, which is of you kept back by fraud, crieth: and the cries of them which have reaped are entered into the ears of the Lord of sabaoth."'),
('James', 5, 'adults', 2, 'How does James describe the lifestyle of the rich in verse 5?', 'They lived in pleasure on the earth and been wanton, nourishing their hearts as in a day of slaughter', 'They lived humbly and gave to the poor', 'They worked harder than anyone else', 'They faithfully served God with their wealth', 'a', 'James 5:5 — "Ye have lived in pleasure on the earth, and been wanton; ye have nourished your hearts, as in a day of slaughter."'),
('James', 5, 'adults', 3, 'What does James say about the coming of the Lord?', 'The coming of the Lord draweth nigh', 'The coming of the Lord is far away', 'The coming of the Lord is uncertain', 'The coming of the Lord has already happened', 'a', 'James 5:8 — "Be ye also patient; stablish your hearts: for the coming of the Lord draweth nigh."'),
('James', 5, 'adults', 4, 'What end of the Lord does James say we see through Job?', 'That the Lord is very pitiful, and of tender mercy', 'That the Lord is harsh and demanding', 'That the Lord is distant and uninvolved', 'That the Lord tests without purpose', 'a', 'James 5:11 — "Ye have heard of the patience of Job, and have seen the end of the Lord; that the Lord is very pitiful, and of tender mercy."'),
('James', 5, 'adults', 5, 'What should be done along with prayer for the sick?', 'Anointing him with oil in the name of the Lord', 'Offering burnt sacrifices at the altar', 'Fasting for seven days', 'Making a pilgrimage to Jerusalem', 'a', 'James 5:14 — "Let them pray over him, anointing him with oil in the name of the Lord."'),
('James', 5, 'adults', 6, 'What connection does James make between confession and healing?', 'Confess your faults one to another and pray one for another, that ye may be healed', 'Confession is only for the priest to hear', 'Healing comes without any confession', 'Confession should be private and never shared', 'a', 'James 5:16 — "Confess your faults one to another, and pray one for another, that ye may be healed."'),
('James', 5, 'adults', 7, 'What does James say Elijah was?', 'A man subject to like passions as we are', 'A supernatural being from heaven', 'An angel in human form', 'A man without any human weakness', 'a', 'James 5:17 — "Elias was a man subject to like passions as we are, and he prayed earnestly that it might not rain."'),
('James', 5, 'adults', 8, 'What does James say about the one who converts a sinner from the error of his way?', 'He shall save a soul from death, and shall hide a multitude of sins', 'He shall receive a prophet''s reward', 'He shall be given authority over ten cities', 'He shall be first in the kingdom of heaven', 'a', 'James 5:20 — "Let him know, that he which converteth the sinner from the error of his way shall save a soul from death, and shall hide a multitude of sins."');
