-- ============================================================================
-- Quiz Seed: Colossians (Chapters 1–4)
-- 3 difficulties × 4 chapters = 64 total questions
--   kids:   3 per chapter  = 12
--   teens:  5 per chapter  = 20
--   adults: 8 per chapter  = 32
-- ============================================================================

-- ═══ Colossians Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Colossians', 1, 'kids', 1, 'Who wrote the letter to the Colossians?', 'Paul', 'Peter', 'James', 'John', 'a', 'Colossians 1:1 — "Paul, an apostle of Jesus Christ by the will of God."'),
('Colossians', 1, 'kids', 2, 'What did Paul say the Colossians had in Christ Jesus?', 'Faith', 'Money', 'A big house', 'Many animals', 'a', 'Colossians 1:4 — "Since we heard of your faith in Christ Jesus."'),
('Colossians', 1, 'kids', 3, 'What did Paul pray the Colossians would be filled with?', 'Knowledge of God''s will', 'Gold and silver', 'Fancy clothes', 'Great power to rule', 'a', 'Colossians 1:9 — "That ye might be filled with the knowledge of his will."'),
-- Teens
('Colossians', 1, 'teens', 1, 'According to Colossians 1:13, from what has God delivered believers?', 'The power of darkness', 'The power of Rome', 'The power of the Pharisees', 'The power of nature', 'a', 'Colossians 1:13 — "Who hath delivered us from the power of darkness."'),
('Colossians', 1, 'teens', 2, 'What does Colossians 1:15 say about Jesus in relation to the invisible God?', 'He is the image of the invisible God', 'He is a prophet of God', 'He is an angel of God', 'He is a servant of God', 'a', 'Colossians 1:15 — "Who is the image of the invisible God, the firstborn of every creature."'),
('Colossians', 1, 'teens', 3, 'According to verse 16, what was created by Jesus?', 'All things in heaven and earth', 'Only the earth', 'Only angels', 'Only mankind', 'a', 'Colossians 1:16 — "For by him were all things created, that are in heaven, and that are in earth."'),
('Colossians', 1, 'teens', 4, 'What does Paul say holds all things together?', 'Christ', 'The law', 'The temple', 'Human effort', 'a', 'Colossians 1:17 — "And he is before all things, and by him all things consist."'),
('Colossians', 1, 'teens', 5, 'What is Christ called in relation to the church in verse 18?', 'The head of the body', 'The foundation stone', 'The cornerstone', 'The vine', 'a', 'Colossians 1:18 — "And he is the head of the body, the church."'),
-- Adults
('Colossians', 1, 'adults', 1, 'In Colossians 1:14, what do believers have through Christ''s blood?', 'Redemption through his blood, even the forgiveness of sins', 'Eternal wealth and prosperity', 'Freedom from all earthly obligations', 'Authority over all nations', 'a', 'Colossians 1:14 — "In whom we have redemption through his blood, even the forgiveness of sins."'),
('Colossians', 1, 'adults', 2, 'What phrase does Paul use in verse 15 to describe Christ''s relation to creation?', 'The firstborn of every creature', 'The last of every creature', 'The ruler of every creature', 'The servant of every creature', 'a', 'Colossians 1:15 — "The firstborn of every creature." This denotes supremacy and preeminence, not that Christ was created.'),
('Colossians', 1, 'adults', 3, 'According to verse 19, what was the Father''s pleasure regarding Christ?', 'That in him should all fulness dwell', 'That he should serve as a prophet only', 'That he should reign on earth immediately', 'That he should remain hidden from mankind', 'a', 'Colossians 1:19 — "For it pleased the Father that in him should all fulness dwell."'),
('Colossians', 1, 'adults', 4, 'How does verse 20 say peace was made between God and creation?', 'Through the blood of his cross', 'Through the keeping of the law', 'Through animal sacrifices', 'Through angelic mediation', 'a', 'Colossians 1:20 — "Having made peace through the blood of his cross."'),
('Colossians', 1, 'adults', 5, 'What does Paul say the gospel was preached to in verse 23?', 'Every creature which is under heaven', 'Only the Jews in Jerusalem', 'Only the Greeks in Athens', 'Only the Roman citizens', 'a', 'Colossians 1:23 — "Which was preached to every creature which is under heaven."'),
('Colossians', 1, 'adults', 6, 'What does Paul say he fills up in verse 24?', 'That which is behind of the afflictions of Christ in his flesh', 'The treasury of the church', 'The positions of leadership', 'The scrolls of prophecy', 'a', 'Colossians 1:24 — "Fill up that which is behind of the afflictions of Christ in my flesh."'),
('Colossians', 1, 'adults', 7, 'What is the mystery hidden from ages and generations according to verse 26-27?', 'Christ in you, the hope of glory', 'The timing of Christ''s return', 'The identity of the Antichrist', 'The location of the Garden of Eden', 'a', 'Colossians 1:27 — "Which is Christ in you, the hope of glory."'),
('Colossians', 1, 'adults', 8, 'What is Paul''s stated goal in preaching Christ according to verse 28?', 'To present every man perfect in Christ Jesus', 'To build the largest church possible', 'To defeat the Roman government', 'To replace the Jewish priesthood', 'a', 'Colossians 1:28 — "That we may present every man perfect in Christ Jesus.");

-- ═══ Colossians Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Colossians', 2, 'kids', 1, 'Where does Paul say all treasures of wisdom and knowledge are hidden?', 'In Christ', 'In a cave', 'In the temple', 'In a book', 'a', 'Colossians 2:3 — "In whom are hid all the treasures of wisdom and knowledge."'),
('Colossians', 2, 'kids', 2, 'What did Paul warn the Colossians not to be tricked by?', 'Enticing words', 'Magic tricks', 'Wild animals', 'Bad weather', 'a', 'Colossians 2:4 — "Lest any man should beguile you with enticing words."'),
('Colossians', 2, 'kids', 3, 'How does Paul say believers should walk?', 'As they received Christ, walk in him', 'Very slowly', 'Only at night', 'Without shoes', 'a', 'Colossians 2:6 — "As ye have therefore received Christ Jesus the Lord, so walk ye in him."'),
-- Teens
('Colossians', 2, 'teens', 1, 'What does Paul warn the Colossians to beware of in verse 8?', 'Philosophy and vain deceit', 'Roman soldiers', 'Dangerous animals', 'Natural disasters', 'a', 'Colossians 2:8 — "Beware lest any man spoil you through philosophy and vain deceit."'),
('Colossians', 2, 'teens', 2, 'What dwells in Christ bodily according to verse 9?', 'All the fulness of the Godhead', 'Only wisdom', 'Only power', 'Only love', 'a', 'Colossians 2:9 — "For in him dwelleth all the fulness of the Godhead bodily."'),
('Colossians', 2, 'teens', 3, 'What did Christ do with the handwriting of ordinances against us?', 'Nailed it to his cross', 'Hid it in the temple', 'Gave it to Moses', 'Burned it in fire', 'a', 'Colossians 2:14 — "Blotting out the handwriting of ordinances that was against us... nailing it to his cross."'),
('Colossians', 2, 'teens', 4, 'What should no man judge believers about according to verse 16?', 'Meat, drink, holy days, new moon, or sabbath days', 'Their wealth or poverty', 'Their nationality', 'Their occupation', 'a', 'Colossians 2:16 — "Let no man therefore judge you in meat, or in drink, or in respect of an holyday."'),
('Colossians', 2, 'teens', 5, 'What does Paul call these Jewish observances in verse 17?', 'A shadow of things to come', 'The most important rules', 'Eternal commandments', 'The path to salvation', 'a', 'Colossians 2:17 — "Which are a shadow of things to come; but the body is of Christ."'),
-- Adults
('Colossians', 2, 'adults', 1, 'What does Paul describe as the "circumcision of Christ" in verse 11?', 'Putting off the body of the sins of the flesh', 'Physical circumcision of the body', 'Baptism by water immersion', 'Keeping the Mosaic law perfectly', 'a', 'Colossians 2:11 — "In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh."'),
('Colossians', 2, 'adults', 2, 'According to verse 12, with what are believers buried with Christ?', 'Baptism', 'Fasting', 'Prayer', 'Sacrifice', 'a', 'Colossians 2:12 — "Buried with him in baptism, wherein also ye are risen with him."'),
('Colossians', 2, 'adults', 3, 'What did God do to principalities and powers according to verse 15?', 'Spoiled them and made a shew of them openly, triumphing over them', 'Gave them more power and authority', 'Made a treaty with them', 'Ignored them entirely', 'a', 'Colossians 2:15 — "Having spoiled principalities and powers, he made a shew of them openly, triumphing over them in it."'),
('Colossians', 2, 'adults', 4, 'What does Paul say about voluntary humility and worshipping of angels in verse 18?', 'Let no man beguile you of your reward through such things', 'These are acceptable forms of worship', 'They should be practiced weekly', 'They are the highest form of devotion', 'a', 'Colossians 2:18 — "Let no man beguile you of your reward in a voluntary humility and worshipping of angels."'),
('Colossians', 2, 'adults', 5, 'According to verse 19, what happens when believers do not hold the Head (Christ)?', 'The body cannot grow with the increase of God', 'They become more spiritual', 'They gain greater wisdom', 'They receive more visions', 'a', 'Colossians 2:19 — "Not holding the Head, from which all the body... increaseth with the increase of God."'),
('Colossians', 2, 'adults', 6, 'If believers are dead with Christ from the rudiments of the world, what should they not do (v. 20)?', 'Be subject to ordinances as though living in the world', 'Avoid all contact with unbelievers', 'Stop praying and fasting', 'Leave the church immediately', 'a', 'Colossians 2:20 — "If ye be dead with Christ from the rudiments of the world, why... are ye subject to ordinances."'),
('Colossians', 2, 'adults', 7, 'What are the "touch not; taste not; handle not" rules described as in verse 22?', 'Commandments and doctrines of men that perish with the using', 'God''s eternal commandments', 'The heart of the gospel', 'Essential rules for salvation', 'a', 'Colossians 2:22 — "Which all are to perish with the using; after the commandments and doctrines of men."'),
('Colossians', 2, 'adults', 8, 'Despite having a show of wisdom, what do man-made rules fail to do according to verse 23?', 'Honour the body or restrain the indulgence of the flesh', 'Bring people to church', 'Create unity among believers', 'Please God in any way', 'a', 'Colossians 2:23 — "Which things have indeed a shew of wisdom... not in any honour to the satisfying of the flesh.");

-- ═══ Colossians Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Colossians', 3, 'kids', 1, 'What does Paul say believers should seek?', 'Things which are above, where Christ sits', 'Treasure on earth', 'Fame and glory', 'Fancy clothes', 'a', 'Colossians 3:1 — "Seek those things which are above, where Christ sitteth on the right hand of God."'),
('Colossians', 3, 'kids', 2, 'What does Paul tell the Colossians to put on?', 'Kindness and love', 'Armor and weapons', 'Fancy jewelry', 'Running shoes', 'a', 'Colossians 3:12,14 — "Put on therefore... kindness... And above all these things put on charity."'),
('Colossians', 3, 'kids', 3, 'What should children do according to this chapter?', 'Obey their parents in all things', 'Play all day', 'Argue with their parents', 'Do whatever they want', 'a', 'Colossians 3:20 — "Children, obey your parents in all things: for this is well pleasing unto the Lord."'),
-- Teens
('Colossians', 3, 'teens', 1, 'What does Paul say believers should set their affection on?', 'Things above, not on things on the earth', 'Things of the earth for daily living', 'Their own desires and goals', 'Worldly success and wealth', 'a', 'Colossians 3:2 — "Set your affection on things above, not on things on the earth."'),
('Colossians', 3, 'teens', 2, 'What five sins does Paul list first to "mortify" (put to death) in verse 5?', 'Fornication, uncleanness, inordinate affection, evil concupiscence, and covetousness', 'Lying, stealing, murder, slander, and gossip', 'Pride, envy, gluttony, sloth, and greed', 'Anger, bitterness, malice, wrath, and revenge', 'a', 'Colossians 3:5 — "Mortify therefore your members which are upon the earth; fornication, uncleanness, inordinate affection, evil concupiscence, and covetousness."'),
('Colossians', 3, 'teens', 3, 'According to verse 11, in the new man there is neither what?', 'Greek nor Jew, circumcision nor uncircumcision, Barbarian, Scythian, bond nor free', 'Rich nor poor', 'Young nor old', 'Educated nor uneducated', 'a', 'Colossians 3:11 — "Where there is neither Greek nor Jew, circumcision nor uncircumcision, Barbarian, Scythian, bond nor free: but Christ is all, and in all."'),
('Colossians', 3, 'teens', 4, 'What is called "the bond of perfectness" in verse 14?', 'Charity (love)', 'Faith', 'Hope', 'Patience', 'a', 'Colossians 3:14 — "And above all these things put on charity, which is the bond of perfectness."'),
('Colossians', 3, 'teens', 5, 'How does Paul say believers should do everything according to verse 17?', 'In the name of the Lord Jesus, giving thanks to God', 'In their own strength and wisdom', 'In secret without anyone knowing', 'In fear and trembling always', 'a', 'Colossians 3:17 — "Whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God."'),
-- Adults
('Colossians', 3, 'adults', 1, 'What does Paul say about believers'' life being hid in verse 3?', 'Your life is hid with Christ in God', 'Your life is displayed for all to see', 'Your life belongs to the church leadership', 'Your life is controlled by the law', 'a', 'Colossians 3:3 — "For ye are dead, and your life is hid with Christ in God."'),
('Colossians', 3, 'adults', 2, 'When Christ who is our life shall appear, what happens according to verse 4?', 'Believers shall also appear with him in glory', 'The earth will be destroyed', 'All unbelievers will perish instantly', 'The temple will be rebuilt', 'a', 'Colossians 3:4 — "When Christ, who is our life, shall appear, then shall ye also appear with him in glory."'),
('Colossians', 3, 'adults', 3, 'What does Paul equate covetousness with in verse 5?', 'Idolatry', 'Adultery', 'Murder', 'Theft', 'a', 'Colossians 3:5 — "And covetousness, which is idolatry."'),
('Colossians', 3, 'adults', 4, 'What does Paul say about the "old man" and the "new man" in verses 9-10?', 'Put off the old man with his deeds and put on the new man renewed in knowledge', 'The old man and new man coexist permanently', 'The old man was never truly sinful', 'The new man is achieved through the law', 'a', 'Colossians 3:9-10 — "Ye have put off the old man with his deeds; And have put on the new man, which is renewed in knowledge after the image of him that created him."'),
('Colossians', 3, 'adults', 5, 'What should rule in believers'' hearts according to verse 15?', 'The peace of God', 'The fear of judgment', 'The desire for wealth', 'Human reason and logic', 'a', 'Colossians 3:15 — "And let the peace of God rule in your hearts."'),
('Colossians', 3, 'adults', 6, 'How should the word of Christ dwell in believers according to verse 16?', 'Richly in all wisdom', 'Sparingly and carefully', 'Only on the sabbath', 'Through priestly teaching alone', 'a', 'Colossians 3:16 — "Let the word of Christ dwell in you richly in all wisdom."'),
('Colossians', 3, 'adults', 7, 'What instruction does Paul give to fathers in verse 21?', 'Provoke not your children to anger, lest they be discouraged', 'Discipline your children harshly', 'Keep your children away from the church', 'Let your children do as they please', 'a', 'Colossians 3:21 — "Fathers, provoke not your children to anger, lest they be discouraged."'),
('Colossians', 3, 'adults', 8, 'What does Paul say servants are truly serving in verse 24?', 'The Lord Christ', 'Their earthly masters only', 'The Roman government', 'Their own interests', 'a', 'Colossians 3:24 — "For ye serve the Lord Christ.");

-- ═══ Colossians Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Colossians', 4, 'kids', 1, 'What does Paul ask the Colossians to keep doing?', 'Praying', 'Sleeping', 'Running', 'Fighting', 'a', 'Colossians 4:2 — "Continue in prayer, and watch in the same with thanksgiving."'),
('Colossians', 4, 'kids', 2, 'Who did Paul call a "faithful minister" in this chapter?', 'Tychicus', 'Timothy', 'Barnabas', 'Silas', 'a', 'Colossians 4:7 — "All my state shall Tychicus declare unto you, who is a beloved brother, and a faithful minister."'),
('Colossians', 4, 'kids', 3, 'Who does Paul say sends greetings — a fellow worker who was a doctor?', 'Luke', 'Mark', 'Peter', 'James', 'a', 'Colossians 4:14 — "Luke, the beloved physician... greet you."'),
-- Teens
('Colossians', 4, 'teens', 1, 'How does Paul say believers should walk toward those outside the faith?', 'In wisdom, redeeming the time', 'In fear and avoidance', 'In judgment and condemnation', 'In indifference', 'a', 'Colossians 4:5 — "Walk in wisdom toward them that are without, redeeming the time."'),
('Colossians', 4, 'teens', 2, 'How should believers'' speech always be according to verse 6?', 'With grace, seasoned with salt', 'Loud and forceful', 'Quiet and timid', 'Harsh and direct', 'a', 'Colossians 4:6 — "Let your speech be alway with grace, seasoned with salt."'),
('Colossians', 4, 'teens', 3, 'Who does Paul describe as a fellowprisoner in verse 10?', 'Aristarchus', 'Timothy', 'Titus', 'Barnabas', 'a', 'Colossians 4:10 — "Aristarchus my fellowprisoner saluteth you."'),
('Colossians', 4, 'teens', 4, 'What does Paul say about Epaphras in verse 12?', 'He is always labouring fervently in prayers for them', 'He is traveling to Rome', 'He is building a new church', 'He is writing a gospel', 'a', 'Colossians 4:12 — "Epaphras, who is one of you, a servant of Christ, saluteth you, always labouring fervently for you in prayers."'),
('Colossians', 4, 'teens', 5, 'What does Paul instruct regarding this epistle and the one from Laodicea?', 'Exchange and read both letters', 'Keep this letter secret', 'Destroy the letter from Laodicea', 'Send both letters to Jerusalem', 'a', 'Colossians 4:16 — "When this epistle is read among you, cause that it be read also in the church of the Laodiceans; and that ye likewise read the epistle from Laodicea."'),
-- Adults
('Colossians', 4, 'adults', 1, 'What does Paul ask the Colossians to pray for regarding his ministry in verse 3?', 'That God would open a door of utterance to speak the mystery of Christ', 'That he would be released from prison immediately', 'That he would receive financial support', 'That he would be given political authority', 'a', 'Colossians 4:3 — "Praying also for us, that God would open unto us a door of utterance, to speak the mystery of Christ."'),
('Colossians', 4, 'adults', 2, 'Who is described as "Marcus, sister''s son to Barnabas" in verse 10?', 'John Mark, about whom the Colossians received commandments', 'A Roman centurion', 'A Greek philosopher', 'A Jewish high priest', 'a', 'Colossians 4:10 — "Marcus, sister''s son to Barnabas, (touching whom ye received commandments: if he come unto you, receive him.)"'),
('Colossians', 4, 'adults', 3, 'Which three men does Paul identify as being "of the circumcision" (Jewish Christians) who were his only fellowworkers?', 'Aristarchus, Marcus, and Jesus called Justus', 'Luke, Demas, and Epaphras', 'Timothy, Titus, and Silas', 'Barnabas, Peter, and James', 'a', 'Colossians 4:10-11 — "Aristarchus... and Marcus... And Jesus, which is called Justus, who are of the circumcision. These only are my fellowworkers."'),
('Colossians', 4, 'adults', 4, 'What does Paul say Epaphras has a great zeal for according to verse 13?', 'Those in Colossae, Laodicea, and Hierapolis', 'Only those in Jerusalem', 'Only those in Rome', 'Only the Jewish believers', 'a', 'Colossians 4:13 — "For I bear him record, that he hath a great zeal for you, and them that are in Laodicea, and them in Hierapolis."'),
('Colossians', 4, 'adults', 5, 'What instruction does Paul give to Archippus in verse 17?', 'Take heed to the ministry which thou hast received in the Lord, that thou fulfil it', 'Come to Rome immediately', 'Stop preaching and return home', 'Give the leadership to someone else', 'a', 'Colossians 4:17 — "Say to Archippus, Take heed to the ministry which thou hast received in the Lord, that thou fulfil it."'),
('Colossians', 4, 'adults', 6, 'How does Paul sign off the letter in verse 18?', 'With his own hand, asking them to remember his bonds', 'Through a secretary without personal touch', 'With a long theological discourse', 'By sending a representative', 'a', 'Colossians 4:18 — "The salutation by the hand of me Paul. Remember my bonds."'),
('Colossians', 4, 'adults', 7, 'Which companion of Paul is mentioned who would later forsake him (cf. 2 Timothy 4:10)?', 'Demas', 'Luke', 'Tychicus', 'Epaphras', 'a', 'Colossians 4:14 — "Luke, the beloved physician, and Demas, greet you." In 2 Timothy 4:10, Paul writes that Demas forsook him, "having loved this present world."'),
('Colossians', 4, 'adults', 8, 'What is the reference to "the church which is in his house" about in verse 15?', 'Nymphas hosted a house church in Laodicea', 'Paul had his own church building in Rome', 'The Jerusalem temple was called a house', 'Peter''s home was the first cathedral', 'a', 'Colossians 4:15 — "Salute... Nymphas, and the church which is in his house.");
