-- ============================================================================
-- Quiz Seed: Matthew — Part 5 (Chapters 25–28)
-- 3 difficulties × 4 chapters = 64 total questions
--   kids:   3 per chapter  = 12
--   teens:  5 per chapter  = 20
--   adults: 8 per chapter  = 32
-- ============================================================================

-- ═══════════════ CHAPTERS 25–26 ═══════════════

-- ═══ Matthew Chapter 25 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 25, 'kids', 1, 'In the story of the ten virgins, what did the five wise virgins bring that the foolish ones did not?', 'Extra oil for their lamps', 'Extra food and water', 'More money for the wedding', 'Extra blankets for sleeping', 'a', 'Matthew 25:4 — "But the wise took oil in their vessels with their lamps."'),
('Matthew', 25, 'kids', 2, 'In the parable of the talents, what did the master say to the servants who used their talents well?', 'Well done, thou good and faithful servant: thou hast been faithful over a few things, I will make thee ruler over many things: enter thou into the joy of thy lord', 'You should have done more', 'Give me back what I gave you', 'You wasted your time', 'a', 'Matthew 25:21 — "His lord said unto him, Well done, thou good and faithful servant: thou hast been faithful over a few things, I will make thee ruler over many things: enter thou into the joy of thy lord."'),
('Matthew', 25, 'kids', 3, 'What did Jesus say about helping hungry, thirsty, and lonely people?', 'Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me', 'Only help people you know well', 'Do not bother helping strangers', 'Wait until you are rich to help others', 'a', 'Matthew 25:40 — "And the King shall answer and say unto them, Verily I say unto you, Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me."'),
-- Teens
('Matthew', 25, 'teens', 1, 'What happened when the foolish virgins went to buy oil?', 'The bridegroom came, and they were shut out. When they knocked and said "Lord, Lord, open to us," he said "I know you not"', 'The bridegroom waited for them to return', 'They found oil quickly and came back in time', 'The other virgins shared their oil', 'a', 'Matthew 25:10-12 — "And while they went to buy, the bridegroom came; and they that were ready went in with him to the marriage: and the door was shut... he answered and said, Verily I say unto you, I know you not."'),
('Matthew', 25, 'teens', 2, 'What did the servant who received one talent do with it?', 'He went and digged in the earth, and hid his lord''s money', 'He invested it and doubled it', 'He gave it to another servant', 'He spent it on himself', 'a', 'Matthew 25:18 — "But he that had received one went and digged in the earth, and hid his lord''s money."'),
('Matthew', 25, 'teens', 3, 'What excuse did the one-talent servant give for hiding his money?', 'He said he was afraid because he knew the master was a hard man — reaping where he had not sown', 'He said someone stole it', 'He said the bank was closed', 'He said he lost it on the way', 'a', 'Matthew 25:24-25 — "Lord, I knew thee that thou art an hard man, reaping where thou hast not sown... And I was afraid, and went and hid thy talent in the earth."'),
('Matthew', 25, 'teens', 4, 'In the judgment of the sheep and the goats, what separates the two groups?', 'How they treated the hungry, thirsty, strangers, naked, sick, and imprisoned — the sheep served them and the goats did not', 'How much money they had', 'How many times they went to the temple', 'How many books they read', 'a', 'Matthew 25:35-36,42-43 — "For I was an hungred, and ye gave me meat: I was thirsty, and ye gave me drink: I was a stranger, and ye took me in: Naked, and ye clothed me: I was sick, and ye visited me: I was in prison, and ye came unto me."'),
('Matthew', 25, 'teens', 5, 'Where did Jesus say the goats would go?', 'Into everlasting punishment — but the righteous into life eternal', 'Into a second chance opportunity', 'Back to their homes unchanged', 'Into a temporary time-out', 'a', 'Matthew 25:46 — "And these shall go away into everlasting punishment: but the righteous into life eternal."'),
-- Adults
('Matthew', 25, 'adults', 1, 'What does the oil in the parable of the ten virgins represent?', 'The oil most likely represents genuine spiritual preparedness — the inner life of faith, the Holy Spirit''s presence, or authentic relationship with Christ that cannot be borrowed or transferred. The five foolish virgins had outward form (lamps) but lacked inward reality (oil). Readiness for Christ''s return is personal and non-transferable', 'Oil represents material wealth', 'Oil represents knowledge of Scripture only', 'Oil has no symbolic meaning', 'a', 'Matthew 25:3-4 — "They that were foolish took their lamps, and took no oil with them: But the wise took oil in their vessels with their lamps." The key detail is that oil cannot be shared (v.9). True spiritual preparedness is personal — no one can be ready for Christ on another''s behalf.'),
('Matthew', 25, 'adults', 2, 'How does the parable of the talents define faithfulness?', 'Faithfulness is measured not by the amount produced but by proportional stewardship — the five-talent and two-talent servants both doubled their investment and received identical commendation. The one-talent servant failed not by producing little but by producing nothing. God judges stewardship relative to capacity, not absolute results', 'Only the five-talent servant was faithful', 'Faithfulness requires extraordinary results', 'The one-talent servant was treated unfairly', 'a', 'Matthew 25:21,23 — Both servants hear identical words: "Well done, thou good and faithful servant." The five-talent servant is not praised more than the two-talent servant. Faithfulness is proportional to opportunity: 2 from 2 = 5 from 5. The crime is not having less but doing nothing with what you have.'),
('Matthew', 25, 'adults', 3, 'What does the one-talent servant''s excuse reveal about his relationship with the master?', 'His claim that the master is "a hard man, reaping where thou hast not sown" reveals a distorted view of God — seeing Him as harsh, exploitative, and demanding rather than generous and trustworthy. Fear of a misperceived God produces paralysis. The master judges him "out of thine own mouth" — even by his own warped logic, he should have at least deposited the money with bankers', 'His understanding of the master was correct', 'Fear is a legitimate excuse for inaction', 'The master was genuinely unfair', 'a', 'Matthew 25:24-27 — "I knew thee that thou art an hard man." The servant''s theology produces his behaviour: if God is harsh, hide. If God is generous, invest. The tragedy: his false image of God led to the very judgment he feared. Wrong theology → wrong behaviour → genuine judgment.'),
('Matthew', 25, 'adults', 4, 'What does the sheep and goats judgment teach about the relationship between faith and works?', 'The judgment is based on deeds (feeding, clothing, visiting), but these are the fruit of genuine faith, not a works-based salvation. The righteous are surprised by their reward ("When saw we thee?") — showing their service was unconscious, habitual, flowing from transformed character. The goats'' surprise ("When saw we thee not?") reveals they would have served if they had known — but love serves without calculation', 'Salvation is earned by good deeds alone', 'Faith without works is sufficient', 'This parable contradicts justification by faith', 'a', 'Matthew 25:37-40 — "When saw we thee an hungred, and fed thee?" The sheep''s surprise is crucial: they did not serve strategically to earn reward but naturally as an overflow of character. Works are evidence of saving faith (James 2:17), not the ground of justification. The goats'' failure was not deliberate cruelty but chronic indifference.'),
('Matthew', 25, 'adults', 5, 'What does "inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me" teach about Christ''s identification with the suffering?', 'Jesus identifies Himself with the poor, hungry, imprisoned, and marginalized — service to them IS service to Christ. This is not metaphor but mystical reality: Christ is present in the suffering. This doctrine (found also in Proverbs 19:17, "He that hath pity upon the poor lendeth unto the LORD") transforms every act of mercy into an encounter with Christ', 'Jesus was speaking only about the twelve apostles', 'This identification is purely figurative', 'Only ministry to Christians counts', 'a', 'Matthew 25:40 — "Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me." Jesus'' identification with "the least" is the most radical statement of incarnational solidarity: the King of the universe hides Himself in the faces of the hungry, naked, and imprisoned.'),
('Matthew', 25, 'adults', 6, 'What does "everlasting punishment" versus "life eternal" (25:46) teach about the duration of both destinies?', 'The same Greek word "aionios" (eternal/everlasting) describes both punishment and life. If "everlasting" means unending for life, it must mean unending for punishment — the durations are parallel and inseparable. To deny eternal punishment while affirming eternal life is linguistically inconsistent', 'Punishment is temporary while life is eternal', 'The Greek words are different for each destiny', 'Neither state is permanent', 'a', 'Matthew 25:46 — "Everlasting punishment... life eternal." Both use "aionios." The parallel construction makes them mutually defining: if eternal life is unending (which all Christians affirm), then eternal punishment is equally unending. The destinies are final, irreversible, and commensurate in duration.'),
('Matthew', 25, 'adults', 7, 'How do the three parables of chapter 25 together address readiness for Christ''s return?', 'The three parables address readiness from three angles: (1) the virgins — personal spiritual preparedness (inner life with God); (2) the talents — faithful stewardship of gifts and opportunities (active service); (3) the sheep/goats — compassionate action toward the needy (practical love). Together: be spiritually ready, actively faithful, and practically compassionate', 'The three parables teach the same lesson identically', 'Only the talents parable matters', 'The parables are randomly arranged', 'a', 'Matthew 25 — Three parables, three dimensions of readiness: virgins = being (spiritual condition); talents = doing (stewardship of abilities); sheep/goats = loving (practical compassion). A person ready for Christ''s return is inwardly prepared (oil), outwardly productive (investment), and practically compassionate (serving "the least").'),
('Matthew', 25, 'adults', 8, 'What does "outer darkness" and "weeping and gnashing of teeth" (25:30) signify eschatologically?', '"Outer darkness" contrasts with the "joy" and "light" of the master''s feast — exclusion from God''s presence and the community of the blessed. "Weeping" suggests grief; "gnashing of teeth" suggests rage or anguish. Together they describe not annihilation but conscious, ongoing experience of loss, regret, and separation from God', 'Outer darkness is a temporary state', 'Gnashing of teeth is a sign of cold weather', 'The terms are purely metaphorical with no real consequence', 'a', 'Matthew 25:30 — "Cast ye the unprofitable servant into outer darkness: there shall be weeping and gnashing of teeth." This phrase appears six times in Matthew (8:12, 13:42,50, 22:13, 24:51, 25:30), always describing the final state of the rejected. The repetition establishes it as a consistent, serious reality.');

-- ═══ Matthew Chapter 26 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 26, 'kids', 1, 'What did a woman pour on Jesus'' head at Simon the leper''s house?', 'Very precious ointment (perfume)', 'Water from a well', 'Olive oil for cooking', 'Juice from grapes', 'a', 'Matthew 26:7 — "There came unto him a woman having an alabaster box of very precious ointment, and poured it on his head, as he sat at meat."'),
('Matthew', 26, 'kids', 2, 'How much money did Judas receive for betraying Jesus?', 'Thirty pieces of silver', 'One hundred gold coins', 'Ten pieces of bronze', 'Five bags of jewels', 'a', 'Matthew 26:15 — "And said unto them, What will ye give me, and I will deliver him unto you? And they covenanted with him for thirty pieces of silver."'),
('Matthew', 26, 'kids', 3, 'What did Jesus pray in the Garden of Gethsemane?', 'O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt', 'Father, send me an army', 'Father, make me king right now', 'Father, let me go home', 'a', 'Matthew 26:39 — "And he went a little further, and fell on his face, and prayed, saying, O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt."'),
-- Teens
('Matthew', 26, 'teens', 1, 'What did Jesus say about the woman who anointed Him with expensive ointment?', 'She hath wrought a good work upon me — she did it for my burial. Wheresoever this gospel shall be preached in the whole world, there shall also this be told as a memorial of her', 'She wasted the ointment foolishly', 'She should have sold it for the poor', 'Her action was insignificant', 'a', 'Matthew 26:10-13 — "Why trouble ye the woman? for she hath wrought a good work upon me... she did it for my burial. Verily I say unto you, Wheresoever this gospel shall be preached in the whole world, there shall also this, that this woman hath done, be told for a memorial of her."'),
('Matthew', 26, 'teens', 2, 'What did Jesus say at the Last Supper about the bread and the cup?', 'He said the bread was His body and the cup was His blood of the new testament, shed for many for the remission of sins', 'The bread was just ordinary food', 'The cup represented the Red Sea crossing', 'They were symbols of earthly kingdom', 'a', 'Matthew 26:26-28 — "Take, eat; this is my body... Drink ye all of it; For this is my blood of the new testament, which is shed for many for the remission of sins."'),
('Matthew', 26, 'teens', 3, 'What did Jesus predict about all His disciples that night?', 'All ye shall be offended because of me this night — they would all forsake Him and flee', 'They would all stay brave and fight', 'They would all pray through the night', 'They would remain calm and united', 'a', 'Matthew 26:31 — "Then saith Jesus unto them, All ye shall be offended because of me this night: for it is written, I will smite the shepherd, and the sheep of the flock shall be scattered abroad."'),
('Matthew', 26, 'teens', 4, 'What happened when the high priest asked Jesus if He was the Christ?', 'Jesus said "Thou hast said" (yes) and added that they would see the Son of man sitting on the right hand of power and coming in the clouds of heaven', 'Jesus denied being the Christ', 'Jesus refused to answer', 'Jesus asked for a lawyer', 'a', 'Matthew 26:63-64 — "The high priest answered and said unto him, I adjure thee by the living God, that thou tell us whether thou be the Christ, the Son of God. Jesus saith unto him, Thou hast said: nevertheless I say unto you, Hereafter shall ye see the Son of man sitting on the right hand of power, and coming in the clouds of heaven."'),
('Matthew', 26, 'teens', 5, 'What did Peter do after denying Jesus three times?', 'He went out and wept bitterly', 'He went back to fishing', 'He fell asleep', 'He pretended nothing happened', 'a', 'Matthew 26:75 — "And Peter remembered the word of Jesus, which said unto him, Before the cock crow, thou shalt deny me thrice. And he went out, and wept bitterly."'),
-- Adults
('Matthew', 26, 'adults', 1, 'What is the significance of the thirty pieces of silver paid for Jesus?', 'Thirty pieces of silver was the price of a slave gored by an ox (Exodus 21:32) and the contemptuous wage of the rejected shepherd in Zechariah 11:12-13. By accepting this price, Judas values Jesus at slave-price, and Zechariah''s prophecy is fulfilled — the money is later thrown into the temple and used to buy the potter''s field (27:3-10)', 'Thirty pieces was an enormous fortune', 'The amount was chosen randomly', 'Judas negotiated a higher price', 'a', 'Matthew 26:15 — "They covenanted with him for thirty pieces of silver." Zechariah 11:12: "They weighed for my price thirty pieces of silver." The prophetic irony: the Good Shepherd is valued at slave-price. Matthew 27:9-10 explicitly connects the potter''s field purchase to prophetic fulfilment.'),
('Matthew', 26, 'adults', 2, 'What does "this is my blood of the new testament, which is shed for many for the remission of sins" establish?', 'Jesus institutes the New Covenant (Jeremiah 31:31-34), sealed not with animal blood (Exodus 24:8) but with His own blood. "Remission of sins" (aphesis hamartion) identifies the cross as the definitive atonement. The Lord''s Supper is the covenant meal that commemorates and participates in Christ''s sacrifice', 'The cup was symbolic only with no theological meaning', 'The new testament refers to a new book', 'Blood sacrifice was unnecessary', 'a', 'Matthew 26:28 — "My blood of the new testament" echoes Exodus 24:8 ("the blood of the covenant") and Jeremiah 31:31 ("I will make a new covenant"). Jesus'' blood ratifies the new covenant, providing what the old covenant could only anticipate: actual forgiveness of sins through a perfect sacrifice.'),
('Matthew', 26, 'adults', 3, 'What does Jesus'' Gethsemane prayer reveal about the relationship between His human and divine wills?', 'Gethsemane reveals the genuine human will of Jesus recoiling from the cup (divine wrath) while voluntarily submitting to the Father''s will. The three prayers show intensifying agony but consistent submission: "not as I will, but as thou wilt." This affirms that Jesus had a real human will that could desire otherwise, yet He freely chose obedience — the supreme act of love', 'Jesus had no human will', 'The Father forced Jesus against His will', 'Jesus felt no real anguish', 'a', 'Matthew 26:39,42,44 — Three prayers, same conclusion: "Thy will be done." The struggle is real (human will recoiling from the cup), but submission is free and final. Hebrews 5:7-8: "He learned obedience by the things which he suffered." Gethsemane is the victory before the cross.'),
('Matthew', 26, 'adults', 4, 'What does Jesus'' response to the high priest ("Thou hast said... Hereafter shall ye see the Son of man sitting on the right hand of power") combine?', 'Jesus affirms His messiahship ("Thou hast said" = yes) and then combines Daniel 7:13 (Son of man coming with clouds) with Psalm 110:1 (sitting at God''s right hand) — claiming both heavenly enthronement and eschatological authority. This fusion of two supreme divine texts is the statement the Sanhedrin calls blasphemy', 'Jesus denied being the Messiah', 'He quoted only one Old Testament passage', 'The high priest accepted Jesus'' answer', 'a', 'Matthew 26:64 — "Thou hast said" (affirmative) + Daniel 7:13 ("coming in the clouds of heaven") + Psalm 110:1 ("sitting on the right hand of power"). By combining these texts, Jesus claims to be the divine figure who shares God''s throne and comes in eschatological judgment. The high priest understood perfectly — and called it blasphemy.'),
('Matthew', 26, 'adults', 5, 'What does "the spirit indeed is willing, but the flesh is weak" (26:41) teach about human nature?', 'Jesus acknowledges the genuine but limited nature of human resolve — the disciples sincerely wanted to watch and pray (willing spirit) but their physical and emotional exhaustion overwhelmed their intention (weak flesh). This is not an excuse for failure but a diagnosis: without prayerful dependence on God, even good intentions collapse under pressure', 'The spirit and flesh are equally strong', 'Jesus was criticising the disciples for sleeping', 'Flesh weakness is a permanent excuse for sin', 'a', 'Matthew 26:41 — "Watch and pray, that ye enter not into temptation: the spirit indeed is willing, but the flesh is weak." The command ("watch and pray") precedes the diagnosis ("flesh is weak"). Prayer is the remedy for the weakness Jesus diagnoses. Without it, good intentions become failed intentions.'),
('Matthew', 26, 'adults', 6, 'What does Jesus'' statement "all they that take the sword shall perish with the sword" (26:52) teach about the nature of His kingdom?', 'Jesus refuses violent defence even when His life is at stake — His kingdom does not advance by force. He could summon "twelve legions of angels" (v.53) but chooses suffering. This is not pacifism as political strategy but a theological statement: the kingdom of God conquers through the cross, not the sword', 'Jesus endorsed military action in other situations', 'Jesus was afraid of the soldiers', 'This command was only for that specific night', 'a', 'Matthew 26:52-54 — "Put up again thy sword... thinkest thou that I cannot now pray to my Father, and he shall presently give me more than twelve legions of angels? But how then shall the scriptures be fulfilled?" Jesus'' power (72,000 angels) makes His restraint all the more significant. He chooses the cross not from weakness but from sovereign obedience.'),
('Matthew', 26, 'adults', 7, 'How does Peter''s denial fulfil Jesus'' prediction and reveal the nature of spiritual failure?', 'Peter''s three denials escalate: simple denial → denial with an oath → cursing and swearing. The progression shows how quickly compromise deepens — each denial requires more effort to sustain the lie. Peter''s failure came despite his sincere boast (v.35 "Though I should die with thee, yet will I not deny thee") — revealing that self-confidence without divine strengthening collapses under pressure', 'Peter only denied Jesus once', 'The denial was planned and deliberate', 'Jesus was surprised by Peter''s failure', 'a', 'Matthew 26:70,72,74 — Denial 1: "I know not what thou sayest" (simple deflection). Denial 2: "with an oath, I do not know the man" (sworn lie). Denial 3: "began he to curse and to swear" (emphatic, profane denial). The escalation mirrors the pattern of sin: compromise → habituation → entrenchment.'),
('Matthew', 26, 'adults', 8, 'What is the significance of the woman''s anointing being memorialised "wheresoever this gospel shall be preached in the whole world" (26:13)?', 'Jesus elevates an anonymous woman''s act of devotion to the same level as the gospel proclamation itself — wherever the cross is preached, her extravagant love will be remembered. This teaches that sacrificial worship and gospel proclamation are inseparable. Her anointing, misunderstood by the disciples, was the most theologically perceptive act in the room: she anointed Jesus for burial before He died', 'The memorial was limited to that village', 'Jesus was exaggerating her importance', 'Only the disciples'' actions would be remembered', 'a', 'Matthew 26:12-13 — "She did it for my burial... told for a memorial of her." The disciples thought it was waste; she understood it was worship. While they debated economics (v.9), she performed Christology — anointing the Messiah (Christ = "anointed one") for His sacrificial death. Her act is the gospel in miniature.');

-- ═══════════════ CHAPTERS 27–28 ═══════════════

-- ═══ Matthew Chapter 27 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 27, 'kids', 1, 'What did Judas do after he realised what he had done in betraying Jesus?', 'He brought back the thirty pieces of silver, threw them down in the temple, and went and hanged himself', 'He asked for more money', 'He ran away to another country', 'He joined the disciples again', 'a', 'Matthew 27:3-5 — "Then Judas... repented himself, and brought again the thirty pieces of silver to the chief priests and elders... And he cast down the pieces of silver in the temple, and departed, and went and hanged himself."'),
('Matthew', 27, 'kids', 2, 'What was written on the sign above Jesus'' cross?', 'THIS IS JESUS THE KING OF THE JEWS', 'This man is a criminal', 'Do not come near', 'This man is dangerous', 'a', 'Matthew 27:37 — "And set up over his head his accusation written, THIS IS JESUS THE KING OF THE JEWS."'),
('Matthew', 27, 'kids', 3, 'What amazing things happened when Jesus died on the cross?', 'The veil of the temple was torn in two, the earth quaked, and rocks split apart', 'Nothing unusual happened', 'It started to rain', 'A rainbow appeared in the sky', 'a', 'Matthew 27:51 — "And, behold, the veil of the temple was rent in twain from the top to the bottom; and the earth did quake, and the rocks rent."'),
-- Teens
('Matthew', 27, 'teens', 1, 'What did Pilate''s wife warn him about Jesus?', 'Have thou nothing to do with that just man: for I have suffered many things this day in a dream because of him', 'Jesus is guilty and should be punished', 'Release Barabbas instead', 'Jesus is a dangerous revolutionary', 'a', 'Matthew 27:19 — "When he was set down on the judgment seat, his wife sent unto him, saying, Have thou nothing to do with that just man: for I have suffered many things this day in a dream because of him."'),
('Matthew', 27, 'teens', 2, 'What did Pilate do to show he was not responsible for Jesus'' death?', 'He washed his hands before the multitude, saying "I am innocent of the blood of this just person: see ye to it"', 'He apologised to Jesus publicly', 'He refused to be involved at all', 'He wrote a letter of protest to Rome', 'a', 'Matthew 27:24 — "When Pilate saw that he could prevail nothing, but that rather a tumult was made, he took water, and washed his hands before the multitude, saying, I am innocent of the blood of this just person: see ye to it."'),
('Matthew', 27, 'teens', 3, 'What did Jesus cry out on the cross?', 'My God, my God, why hast thou forsaken me? — quoting Psalm 22:1', 'Save me from the cross', 'I cannot bear this pain', 'Send an army to rescue me', 'a', 'Matthew 27:46 — "And about the ninth hour Jesus cried with a loud voice, saying, Eli, Eli, lama sabachthani? that is to say, My God, my God, why hast thou forsaken me?"'),
('Matthew', 27, 'teens', 4, 'What did the Roman centurion say when he saw how Jesus died?', 'Truly this was the Son of God', 'He was just an ordinary criminal', 'We should not have done this', 'Nothing special happened here', 'a', 'Matthew 27:54 — "Now when the centurion, and they that were with him, watching Jesus, saw the earthquake, and those things that were done, they feared greatly, saying, Truly this was the Son of God."'),
('Matthew', 27, 'teens', 5, 'Who buried Jesus'' body?', 'Joseph of Arimathaea, a rich man and disciple of Jesus, who laid it in his own new tomb cut from rock', 'The Roman soldiers buried Him', 'The disciples buried Him secretly', 'No one buried Him', 'a', 'Matthew 27:57-60 — "There came a rich man of Arimathaea, named Joseph, who also himself was Jesus'' disciple: He went to Pilate, and begged the body of Jesus... and laid it in his own new tomb, which he had hewn out in the rock."'),
-- Adults
('Matthew', 27, 'adults', 1, 'What does Jesus'' cry "My God, my God, why hast thou forsaken me?" reveal about the nature of the atonement?', 'Jesus experienced genuine separation from the Father as He bore the sins of humanity — the cry quotes Psalm 22:1 and expresses the reality of penal substitutionary atonement: the sinless one endures the God-forsakenness that sin deserves. This is not abandonment in fact (the Father''s plan is being fulfilled) but experienced abandonment as Jesus bears divine wrath', 'Jesus lost faith on the cross', 'God literally abandoned Jesus permanently', 'The cry was purely theatrical', 'a', 'Matthew 27:46 — "Eli, Eli, lama sabachthani?" This is the most agonising cry in Scripture. Jesus experiences what sin deserves — separation from God. 2 Corinthians 5:21: "He hath made him to be sin for us, who knew no sin." The forsakenness is real (He truly bears wrath) but purposeful (it accomplishes redemption).'),
('Matthew', 27, 'adults', 2, 'What does the tearing of the temple veil signify theologically?', 'The veil separated the Holy of Holies (God''s presence) from all humanity — only the high priest could enter once a year. Its tearing "from the top to the bottom" (divine action, not human) signifies that through Christ''s death, access to God is opened for all people. The entire temple system of mediation is fulfilled and superseded by Christ the true mediator', 'The veil was old and simply deteriorated', 'The earthquake caused a structural crack', 'Only priests noticed the tear', 'a', 'Matthew 27:51 — "The veil of the temple was rent in twain from the top to the bottom." "From the top" indicates divine initiative. Hebrews 10:19-20 interprets: "Having therefore, brethren, boldness to enter into the holiest by the blood of Jesus, By a new and living way, which he hath consecrated for us, through the veil, that is to say, his flesh."'),
('Matthew', 27, 'adults', 3, 'What is the significance of the saints being raised when Jesus died (27:52-53)?', 'This resurrection of OT saints (unique to Matthew) previews the general resurrection and demonstrates that Jesus'' death has power over death itself. They appeared "after his resurrection" — Christ is the firstfruits (1 Corinthians 15:20), and these saints are an anticipatory wave. His death breaks death''s grip; His resurrection validates the breakthrough', 'These were zombies with no theological meaning', 'This event was a myth added later', 'Only one person was raised', 'a', 'Matthew 27:52-53 — "And the graves were opened; and many bodies of the saints which slept arose, And came out of the graves after his resurrection, and went into the holy city, and appeared unto many." The timing ("after his resurrection") ensures Christ''s priority as "the firstborn from the dead" (Colossians 1:18). His death inaugurates the resurrection of the dead.'),
('Matthew', 27, 'adults', 4, 'How does Pilate''s hand-washing (27:24) fail to absolve him of guilt?', 'Pilate''s gesture is an empty ritual — a physical act that cannot cleanse moral guilt. He acknowledges Jesus'' innocence ("this just person") yet delivers Him to be crucified. His authority means his responsibility. Washing hands while wielding power to save but choosing not to is the epitome of moral cowardice — appearance of innocence while perpetrating injustice', 'Pilate was truly innocent after washing his hands', 'Hand-washing was a valid legal ritual in Roman law', 'Pilate had no choice in the matter', 'a', 'Matthew 27:24 — "I am innocent of the blood of this just person." Pilate calls Jesus "just" (dikaios) — legally innocent — then surrenders Him to execution. The hand-washing echoes Deuteronomy 21:6-7 (elders washing hands over unsolved murder), but Pilate''s murder is not unsolved — he is the perpetrator. The ritual mocks itself.'),
('Matthew', 27, 'adults', 5, 'What does the inscription "THIS IS JESUS THE KING OF THE JEWS" signify ironically?', 'Written as mockery, the inscription proclaims profound truth: Jesus IS the King of the Jews, reigning from the cross. The cross is His throne; the crown of thorns is His crown; the inscription is His royal declaration. What Rome intended as ridicule, God intended as revelation — the deepest irony of the passion narrative', 'The inscription was legally required and theologically irrelevant', 'Pilate was making a political statement against Rome', 'Jesus was literally made king at that moment', 'a', 'Matthew 27:37 — "THIS IS JESUS THE KING OF THE JEWS." Every element of the crucifixion mocks kingship: purple robe (v.28), crown of thorns (v.29), reed-sceptre (v.29), genuflection (v.29). Yet each detail is ironically true. The King reigns by dying; the throne is a cross; the kingdom is established through sacrifice.'),
('Matthew', 27, 'adults', 6, 'What does the centurion''s confession "Truly this was the Son of God" signify in Matthew''s narrative?', 'A Roman soldier — the least likely person to recognise Israel''s Messiah — makes the climactic Christological confession of the Gospel. This mirrors the Magi (ch. 2, Gentiles recognising the king) and anticipates the Great Commission (ch. 28, all nations). Matthew''s theological arc: those closest (Israel''s leaders) reject; those farthest (Gentile centurion) confess', 'The centurion was already a Christian', 'His statement was sarcastic', 'Only Jewish people could recognise the Son of God', 'a', 'Matthew 27:54 — "Truly this was the Son of God." The centurion''s confession bookends Peter''s confession (16:16). Peter confessed in response to miracles; the centurion confesses in response to death. The cross — not miracles — is the ultimate revelation of Jesus'' identity as God''s Son.'),
('Matthew', 27, 'adults', 7, 'What is the theological significance of Barabbas being released instead of Jesus?', 'Barabbas ("son of the father") — a guilty insurrectionist — goes free while Jesus (the true Son of the Father) — the innocent one — is condemned. This is substitutionary atonement enacted dramatically: the guilty is released because the innocent takes his place. Every believer is Barabbas — set free because Christ took their cross', 'Barabbas'' release was a routine legal procedure', 'The name Barabbas has no significance', 'Jesus and Barabbas had nothing in common', 'a', 'Matthew 27:26 — "Then released he Barabbas unto them: and when he had scourged Jesus, he delivered him to be crucified." The name Bar-Abbas ("son of the father") creates a profound irony: the false "son of the father" walks free while the true Son of the Father is executed. Barabbas is the living illustration of substitution.'),
('Matthew', 27, 'adults', 8, 'How does Judas'' remorse (27:3-10) differ from genuine repentance?', 'Judas "repented himself" (metamelomai — felt regret/remorse) not "repented" (metanoeo — changed mind/direction toward God). His remorse led to despair and self-destruction rather than to God. He confessed guilt ("I have sinned in that I have betrayed the innocent blood") but sought resolution through his own action (returning money, suicide) rather than through divine mercy', 'Judas genuinely repented and was forgiven', 'There is no difference between remorse and repentance', 'Judas never felt any guilt', 'a', 'Matthew 27:3-5 — "Metamelomai" (Judas''s remorse) vs. "metanoeo" (gospel repentance). Peter also failed (denied Jesus) but was restored through weeping (26:75) that led him back to Christ (John 21). Judas''s remorse turned inward (self-destruction); Peter''s sorrow turned toward Christ (restoration). The destination of grief determines whether it saves or destroys.');

-- ═══ Matthew Chapter 28 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 28, 'kids', 1, 'What did the angel say to the women who came to Jesus'' tomb?', 'He is not here: for he is risen, as he said. Come, see the place where the Lord lay', 'He is still sleeping inside', 'The tomb has been moved somewhere else', 'You are at the wrong tomb', 'a', 'Matthew 28:6 — "He is not here: for he is risen, as he said. Come, see the place where the Lord lay."'),
('Matthew', 28, 'kids', 2, 'What did the risen Jesus say when He met the women?', 'All hail! — and they came and held him by the feet, and worshipped him', 'Go away and do not tell anyone', 'I am only a spirit', 'You are dreaming', 'a', 'Matthew 28:9 — "And as they went to tell his disciples, behold, Jesus met them, saying, All hail. And they came and held him by the feet, and worshipped him."'),
('Matthew', 28, 'kids', 3, 'What did Jesus tell His disciples to do before He went to heaven?', 'Go and teach all nations, baptising them in the name of the Father, and of the Son, and of the Holy Ghost', 'Stay in Jerusalem and never leave', 'Build a big church building', 'Only teach people in Israel', 'a', 'Matthew 28:19 — "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost."'),
-- Teens
('Matthew', 28, 'teens', 1, 'What did the chief priests do when they heard about the empty tomb?', 'They gave the soldiers large money and told them to say "His disciples came by night, and stole him away while we slept"', 'They believed in Jesus and repented', 'They went to the tomb to see for themselves', 'They praised God for the miracle', 'a', 'Matthew 28:12-13 — "And when they were assembled with the elders, and had taken counsel, they gave large money unto the soldiers, Saying, Say ye, His disciples came by night, and stole him away while we slept."'),
('Matthew', 28, 'teens', 2, 'What authority did Jesus claim after His resurrection?', 'All power is given unto me in heaven and in earth', 'Some authority in certain areas', 'Authority only over Israel', 'Authority only over the disciples', 'a', 'Matthew 28:18 — "And Jesus came and spake unto them, saying, All power is given unto me in heaven and in earth."'),
('Matthew', 28, 'teens', 3, 'What promise did Jesus make at the very end of the Gospel of Matthew?', 'Lo, I am with you alway, even unto the end of the world', 'I will come back next year', 'I will send someone else to help you', 'You are on your own from now on', 'a', 'Matthew 28:20 — "Lo, I am with you alway, even unto the end of the world. Amen."'),
('Matthew', 28, 'teens', 4, 'What three things did Jesus command His disciples to do in the Great Commission?', 'Go and make disciples of all nations, baptise them, and teach them to observe all things He commanded', 'Build temples, collect tithes, and establish governments', 'Write books, start schools, and create armies', 'Stay in Jerusalem, pray daily, and avoid Gentiles', 'a', 'Matthew 28:19-20 — "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: Teaching them to observe all things whatsoever I have commanded you."'),
('Matthew', 28, 'teens', 5, 'What happened when the angel appeared at the tomb?', 'There was a great earthquake, the angel rolled back the stone and sat upon it — his countenance was like lightning and his raiment white as snow. The guards shook and became as dead men from fear', 'Nothing unusual happened at the tomb', 'The stone simply fell away on its own', 'The disciples moved the stone', 'a', 'Matthew 28:2-4 — "And, behold, there was a great earthquake: for the angel of the Lord descended from heaven, and came and rolled back the stone from the door, and sat upon it. His countenance was like lightning, and his raiment white as snow: And for fear of him the keepers did shake, and became as dead men."'),
-- Adults
('Matthew', 28, 'adults', 1, 'What does the Great Commission''s Trinitarian baptismal formula ("in the name of the Father, and of the Son, and of the Holy Ghost") establish doctrinally?', 'The singular "name" (onoma, not "names") with three persons establishes the unity of the Godhead in three distinct persons — one name, three persons. This is the most explicit Trinitarian formula in Scripture, placing the Son and Spirit on equal footing with the Father and establishing baptism as entrance into a relationship with the triune God', 'Father, Son, and Spirit are three separate gods', 'The formula is a later addition to Matthew', 'Only the Father''s name matters', 'a', 'Matthew 28:19 — "In the name (singular) of the Father, and of the Son, and of the Holy Ghost." One name (eis to onoma), three persons. The singular "name" with three referents is the grammatical foundation of Trinitarian doctrine: three persons sharing one divine identity, coequal in authority and worthy of worship.'),
('Matthew', 28, 'adults', 2, 'How does "All power is given unto me in heaven and in earth" (28:18) connect to Daniel 7:13-14?', 'Daniel 7:13-14 prophesies the Son of Man receiving "dominion, and glory, and a kingdom, that all people, nations, and languages, should serve him." Jesus claims this prophecy is now fulfilled — His death and resurrection have secured universal authority. The Great Commission flows from this: because Jesus has all authority, disciples can go to all nations', 'This claim was temporary', 'Jesus was quoting a different prophecy', 'All authority was limited to Israel', 'a', 'Matthew 28:18 — "All power (pasa exousia) is given unto me in heaven and in earth." Daniel 7:14: "There was given him dominion, and glory, and a kingdom." The resurrection is Jesus'' enthronement — the transfer of cosmic authority. The imperative "go" (v.19) rests on the indicative "all power is given" (v.18). Authority precedes mission.'),
('Matthew', 28, 'adults', 3, 'What does the guard''s bribery (28:11-15) inadvertently confirm about the resurrection?', 'The bribe-story is self-refuting: if the guards were asleep, they could not know what happened (sleeping witnesses are no witnesses). The very need to fabricate an alternative explanation confirms that the tomb was indisputably empty — the question was never whether the tomb was empty but how it became empty. The leaders'' cover-up is evidence for the resurrection', 'The bribery successfully explained the empty tomb', 'The guards were telling the truth about the theft', 'There was no guard posted', 'a', 'Matthew 28:13-15 — "Say ye, His disciples came by night, and stole him away while we slept." The absurdity: (1) sleeping soldiers = capital offence in Rome; (2) sleeping witnesses cannot testify to what happened; (3) the disciples had no motive (they were hiding in fear). The cover story''s weakness strengthens the resurrection claim.'),
('Matthew', 28, 'adults', 4, 'What does "teaching them to observe all things whatsoever I have commanded you" establish about the content of discipleship?', 'Discipleship is not merely conversion (baptism) but ongoing instruction in obedience to everything Jesus taught. "All things" (panta) includes the Sermon on the Mount, kingdom parables, community ethics, and the cross-shaped life. The Great Commission produces not merely believers but obedient followers who embody Jesus'' teaching in all of life', 'Only the Ten Commandments need to be taught', 'Baptism alone is sufficient for discipleship', 'Teaching is optional after conversion', 'a', 'Matthew 28:20 — "Teaching them to observe all things whatsoever I have commanded you." The verbs create a process: go → make disciples → baptise → teach to obey. Discipleship is comprehensive ("all things"), ethical ("observe/obey"), and Christocentric ("whatsoever I have commanded"). The five discourses of Matthew provide the curriculum.'),
('Matthew', 28, 'adults', 5, 'How does "Lo, I am with you alway, even unto the end of the world" bookend the entire Gospel of Matthew?', 'Matthew begins with "Emmanuel... God with us" (1:23) and ends with "I am with you alway" (28:20). The entire Gospel is framed by divine presence. The incarnation promise (God with us in Christ) is now universalised: the risen Christ is with all disciples, in all places, until the end of the age. The presence that began in a manger continues through the church', 'The two promises are unrelated', 'Emmanuel only referred to a political title', 'Jesus'' presence ended at the ascension', 'a', 'Matthew 28:20 — "Lo, I am with you alway, even unto the end of the world." The inclusio (literary bookend): Emmanuel (1:23) → "I am with you" (28:20). The Gospel begins and ends with the same promise: God''s presence with His people. The risen Christ fulfils the Emmanuel promise permanently and universally.'),
('Matthew', 28, 'adults', 6, 'What does the women''s response to the risen Jesus (holding His feet and worshipping Him) confirm about the resurrection?', 'Physical touch (holding His feet) confirms a bodily resurrection — not a vision, hallucination, or spiritual appearance. Their worship (proskunesan) is appropriate only for deity — the resurrection vindicates all of Jesus'' divine claims. The combination of physical contact and worship establishes both the reality of the resurrection body and the propriety of worshipping the risen Christ', 'They were touching a spirit', 'The women were hallucinating', 'Worship was premature at this point', 'a', 'Matthew 28:9 — "They came and held him by the feet, and worshipped him." Physical grasp (feet = tangible body) + worship (proskunesan = divine honour). The bodily resurrection is not a metaphor: the same body that was crucified is now risen, touchable, and rightly worshipped. Thomas later makes the same discovery (John 20:28).'),
('Matthew', 28, 'adults', 7, 'How does the Great Commission reverse the initial restriction of chapter 10?', 'In Matthew 10:5-6, Jesus restricted the mission to "the lost sheep of the house of Israel." In 28:19, the restriction is removed: "all nations" (panta ta ethne). The death and resurrection have changed the salvation-historical situation — the gospel is no longer limited by ethnic or geographical boundaries. What was strategically restricted is now universally released', 'The restriction was never real', 'The Great Commission only applies to the apostles', 'Chapter 10 and 28 contradict each other', 'a', 'Matthew 28:19 vs. 10:5-6 — The contrast is deliberate: "Go not into the way of the Gentiles" (10:5) → "Go... teach all nations" (28:19). The cross and resurrection break down the dividing wall (Ephesians 2:14). Israel''s priority (10:5-6) was not exclusion but sequence: Israel first, then all nations.'),
('Matthew', 28, 'adults', 8, 'How does Matthew 28 function as the climax and summary of Matthew''s entire Gospel?', 'Chapter 28 resolves every major theme: (1) Jesus is the risen King (fulfilling the Davidic promise of ch. 1); (2) He has universal authority (fulfilling "all power," Daniel 7:14); (3) the mission extends to all nations (fulfilling the Abrahamic promise, Genesis 12:3); (4) Trinitarian baptism reveals the fullness of God; (5) "I am with you" fulfils Emmanuel (1:23). Matthew''s Gospel moves from promise to fulfilment, from Israel to all nations, from incarnation to cosmic lordship', 'Chapter 28 is a simple ending with no connections to earlier chapters', 'Only the resurrection matters, not the commission', 'The chapter was added by a later editor', 'a', 'Matthew 28:16-20 — Every element connects backward: "all authority" ← Daniel 7 (referenced in 26:64); "all nations" ← Abraham (1:1) and the Magi (2:1-12); "baptizing... teaching" ← Jesus'' own baptism (3:13-17) and five discourses; "I am with you" ← Emmanuel (1:23). The Great Commission is the Gospel of Matthew in miniature.');
