-- ============================================================================
-- Quiz Seed: 1 John (Chapters 1–5)
-- 3 difficulties × 5 chapters = 80 total questions
--   kids:   3 per chapter  = 15
--   teens:  5 per chapter  = 25
--   adults: 8 per chapter  = 40
-- ============================================================================

-- ═══ 1 John Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 John', 1, 'kids', 1, 'What does John say God is?', 'God is light, and in him is no darkness at all', 'God is a great king on a throne', 'God is like the wind that blows', 'God is a burning fire', 'a', '1 John 1:5 — "God is light, and in him is no darkness at all."'),
('1 John', 1, 'kids', 2, 'What does the blood of Jesus do for us?', 'Cleanseth us from all sin', 'Makes us rich', 'Gives us superpowers', 'Makes us famous', 'a', '1 John 1:7 — "The blood of Jesus Christ his Son cleanseth us from all sin."'),
('1 John', 1, 'kids', 3, 'What should we do when we sin?', 'Confess our sins to God', 'Hide from God', 'Pretend we didn''t do it', 'Blame someone else', 'a', '1 John 1:9 — "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness."'),
-- Teens
('1 John', 1, 'teens', 1, 'What does John say he and the apostles have seen, heard, and handled?', 'The Word of life — that which was from the beginning', 'A vision of angels', 'The temple in Jerusalem', 'The writings of Moses', 'a', '1 John 1:1 — "That which was from the beginning, which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the Word of life."'),
('1 John', 1, 'teens', 2, 'Why is John writing about what he has witnessed?', 'That his readers may have fellowship with them and with the Father and the Son', 'To prove he is a real apostle', 'To write a history book', 'To become a famous author', 'a', '1 John 1:3 — "That which we have seen and heard declare we unto you, that ye also may have fellowship with us: and truly our fellowship is with the Father, and with his Son Jesus Christ."'),
('1 John', 1, 'teens', 3, 'What happens if we walk in the light as God is in the light?', 'We have fellowship one with another, and the blood of Jesus cleanseth us from all sin', 'We become perfect and never sin again', 'We receive earthly rewards and riches', 'We are protected from all suffering', 'a', '1 John 1:7 — "But if we walk in the light, as he is in the light, we have fellowship one with another, and the blood of Jesus Christ his Son cleanseth us from all sin."'),
('1 John', 1, 'teens', 4, 'What does John say about claiming to have no sin?', 'We deceive ourselves and the truth is not in us', 'It means we have reached perfection', 'It is the goal of every believer', 'It shows strong faith', 'a', '1 John 1:8 — "If we say that we have no sin, we deceive ourselves, and the truth is not in us."'),
('1 John', 1, 'teens', 5, 'What two things does God do when we confess our sins?', 'He is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness', 'He punishes us and then forgives', 'He forgives but remembers forever', 'He forgives only once', 'a', '1 John 1:9 — "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness."'),
-- Adults
('1 John', 1, 'adults', 1, 'What does John''s opening phrase "That which was from the beginning" echo?', 'The opening of John''s Gospel — "In the beginning was the Word" — affirming Christ''s eternal preexistence', 'The creation account in Genesis 1', 'The call of Abraham', 'The giving of the law at Sinai', 'a', '1 John 1:1 — "That which was from the beginning" parallels John 1:1, affirming the eternal nature of the Word of life.'),
('1 John', 1, 'adults', 2, 'What does John mean by "the eternal life, which was with the Father, and was manifested unto us"?', 'Christ himself is the eternal life who existed with the Father and became incarnate', 'Eternal life is a concept taught by the prophets', 'Eternal life began when believers first believed', 'Eternal life is a future promise not yet realized', 'a', '1 John 1:2 — "For the life was manifested, and we have seen it, and bear witness, and shew unto you that eternal life, which was with the Father, and was manifested unto us."'),
('1 John', 1, 'adults', 3, 'Why does John write these things according to verse 4?', 'That your joy may be full', 'That you may fear God more', 'That you may escape persecution', 'That you may gain wisdom', 'a', '1 John 1:4 — "And these things write we unto you, that your joy may be full."'),
('1 John', 1, 'adults', 4, 'What does John say about claiming fellowship with God while walking in darkness?', 'We lie and do not the truth', 'We are still saved but immature', 'We are being tested by God', 'We are in a normal phase of growth', 'a', '1 John 1:6 — "If we say that we have fellowship with him, and walk in darkness, we lie, and do not the truth."'),
('1 John', 1, 'adults', 5, 'What does the statement "God is light, and in him is no darkness at all" teach about God''s nature?', 'God is absolutely holy, pure, and without any moral imperfection whatsoever', 'God is a physical source of visible light', 'God sometimes permits darkness for good purposes', 'God''s light only shines on the righteous', 'a', '1 John 1:5 — "God is light, and in him is no darkness at all." The emphatic double negative in Greek stresses absolute moral purity.'),
('1 John', 1, 'adults', 6, 'What does "faithful and just" in verse 9 reveal about forgiveness?', 'God''s forgiveness is rooted in his faithfulness to his covenant and the justice satisfied by Christ''s atonement', 'God forgives because he overlooks sin', 'God forgives arbitrarily based on feelings', 'God forgives only those who earn it through works', 'a', '1 John 1:9 — "He is faithful and just to forgive us." God''s forgiveness flows from his covenant faithfulness and the just satisfaction of Christ''s sacrifice.'),
('1 John', 1, 'adults', 7, 'What does John say we make God if we say we have not sinned?', 'We make him a liar, and his word is not in us', 'We make him proud of us', 'We make him our judge', 'We make him irrelevant', 'a', '1 John 1:10 — "If we say that we have not sinned, we make him a liar, and his word is not in us."'),
('1 John', 1, 'adults', 8, 'What four sensory verbs does John use in verse 1 to establish apostolic witness?', 'Heard, seen, looked upon, and handled — emphasizing the physical reality of Christ''s incarnation', 'Read, studied, memorized, and taught', 'Dreamed, envisioned, prophesied, and imagined', 'Believed, hoped, trusted, and obeyed', 'a', '1 John 1:1 — "Which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled." These verbs counter Gnostic denial of Christ''s physical body.');

-- ═══ 1 John Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 John', 2, 'kids', 1, 'If we sin, who speaks to the Father for us?', 'Jesus Christ the righteous, our advocate', 'An angel in heaven', 'Moses', 'A priest in the temple', 'a', '1 John 2:1 — "If any man sin, we have an advocate with the Father, Jesus Christ the righteous."'),
('1 John', 2, 'kids', 2, 'What does John say about loving your brother?', 'He that loveth his brother abideth in the light', 'Loving your brother is optional', 'You only need to love your close friends', 'Loving others is too hard', 'a', '1 John 2:10 — "He that loveth his brother abideth in the light, and there is none occasion of stumbling in him."'),
('1 John', 2, 'kids', 3, 'What does John say we should NOT love?', 'The world, neither the things that are in the world', 'Our parents and family', 'Our church and neighbours', 'Good food and nice clothes', 'a', '1 John 2:15 — "Love not the world, neither the things that are in the world."'),
-- Teens
('1 John', 2, 'teens', 1, 'How do we know that we know Christ?', 'If we keep his commandments', 'If we attend church every week', 'If we feel happy all the time', 'If we have visions and dreams', 'a', '1 John 2:3 — "And hereby we do know that we know him, if we keep his commandments."'),
('1 John', 2, 'teens', 2, 'What three things of the world does John warn against?', 'The lust of the flesh, the lust of the eyes, and the pride of life', 'Money, fame, and power', 'Food, clothing, and shelter', 'Knowledge, beauty, and strength', 'a', '1 John 2:16 — "For all that is in the world, the lust of the flesh, and the lust of the eyes, and the pride of life, is not of the Father, but is of the world."'),
('1 John', 2, 'teens', 3, 'What does John say about the world and its lusts?', 'The world passeth away, and the lust thereof, but he that doeth the will of God abideth for ever', 'The world will last forever', 'The world''s pleasures are from God', 'The lusts of the world are harmless', 'a', '1 John 2:17 — "And the world passeth away, and the lust thereof: but he that doeth the will of God abideth for ever."'),
('1 John', 2, 'teens', 4, 'What does John call those who deny that Jesus is the Christ?', 'Antichrist — he that denieth the Father and the Son', 'A false prophet only', 'A confused believer', 'A harmless sceptic', 'a', '1 John 2:22 — "Who is a liar but he that denieth that Jesus is the Christ? He is antichrist, that denieth the Father and the Son."'),
('1 John', 2, 'teens', 5, 'What anointing have believers received?', 'An unction (anointing) from the Holy One, and ye know all things', 'An anointing with oil by the elders', 'A special blessing from the apostles', 'A physical mark on their foreheads', 'a', '1 John 2:20 — "But ye have an unction from the Holy One, and ye know all things."'),
-- Adults
('1 John', 2, 'adults', 1, 'What does John call Jesus in his role before the Father?', 'An advocate with the Father — Jesus Christ the righteous', 'A judge who condemns the guilty', 'A prophet who reveals the future', 'A priest who offers sacrifices', 'a', '1 John 2:1 — "We have an advocate with the Father, Jesus Christ the righteous." The Greek "parakletos" means one called alongside to help.'),
('1 John', 2, 'adults', 2, 'What is the scope of Christ''s propitiation according to verse 2?', 'Not for our sins only, but also for the sins of the whole world', 'Only for the sins of the apostles', 'Only for the sins of Israel', 'Only for sins committed before conversion', 'a', '1 John 2:2 — "And he is the propitiation for our sins: and not for ours only, but also for the sins of the whole world."'),
('1 John', 2, 'adults', 3, 'What does John say about one who claims to know God but does not keep his commandments?', 'He is a liar, and the truth is not in him', 'He is a new believer who needs patience', 'He is struggling but still faithful', 'He is under grace and free from the law', 'a', '1 John 2:4 — "He that saith, I know him, and keepeth not his commandments, is a liar, and the truth is not in him."'),
('1 John', 2, 'adults', 4, 'What does John say about the new commandment he writes?', 'It is not new but old, yet also new — because the darkness is past and the true light now shineth', 'It completely replaces the Old Testament law', 'It was never taught before', 'It applies only to church leaders', 'a', '1 John 2:7-8 — "Brethren, I write no new commandment unto you, but an old commandment... Again, a new commandment I write unto you... because the darkness is past, and the true light now shineth."'),
('1 John', 2, 'adults', 5, 'What does John say about those who went out from the believers?', 'They went out from us because they were not of us — if they had been of us, they would have continued with us', 'They left to start better churches', 'They were sent on missionary journeys', 'They were promoted to higher positions', 'a', '1 John 2:19 — "They went out from us, but they were not of us; for if they had been of us, they would no doubt have continued with us."'),
('1 John', 2, 'adults', 6, 'Who is the liar according to verse 22?', 'He that denieth that Jesus is the Christ — he is antichrist, that denieth the Father and the Son', 'He who tells falsehoods to neighbours', 'He who breaks business contracts', 'He who exaggerates his accomplishments', 'a', '1 John 2:22 — "Who is a liar but he that denieth that Jesus is the Christ? He is antichrist, that denieth the Father and the Son."'),
('1 John', 2, 'adults', 7, 'What does John say about the anointing believers received?', 'The anointing which ye have received of him abideth in you, and ye need not that any man teach you', 'It must be renewed every year by church elders', 'It was a one-time physical ceremony', 'It only applies to ordained ministers', 'a', '1 John 2:27 — "But the anointing which ye have received of him abideth in you, and ye need not that any man teach you: but as the same anointing teacheth you of all things."'),
('1 John', 2, 'adults', 8, 'What three groups does John address in verses 12-14 and what characterizes each?', 'Little children (sins forgiven, know the Father), young men (overcome the wicked one, strong, word abideth), fathers (known him from the beginning)', 'Infants, teenagers, and senior citizens', 'New converts, deacons, and elders', 'Students, teachers, and prophets', 'a', '1 John 2:12-14 — John addresses "little children" (sins forgiven), "fathers" (known him from the beginning), and "young men" (overcome the wicked one, strong, word of God abideth in you).');

-- ═══ 1 John Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 John', 3, 'kids', 1, 'What does God call us?', 'The sons (children) of God', 'Servants of the temple', 'Soldiers of the army', 'Students of the law', 'a', '1 John 3:1 — "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God."'),
('1 John', 3, 'kids', 2, 'What does John say we should do for each other?', 'Love one another', 'Fight with each other', 'Ignore each other', 'Compete with each other', 'a', '1 John 3:11 — "For this is the message that ye heard from the beginning, that we should love one another."'),
('1 John', 3, 'kids', 3, 'How should we love — just with words, or with actions too?', 'Not in word only, but in deed and in truth', 'Only with nice words', 'Only in our thoughts', 'Only on special days', 'a', '1 John 3:18 — "My little children, let us not love in word, neither in tongue; but in deed and in truth."'),
-- Teens
('1 John', 3, 'teens', 1, 'What will we be like when Christ appears?', 'We shall be like him, for we shall see him as he is', 'We will become invisible spirits', 'We will remain exactly as we are now', 'We will become angels', 'a', '1 John 3:2 — "We know that, when he shall appear, we shall be like him; for we shall see him as he is."'),
('1 John', 3, 'teens', 2, 'What is sin according to 1 John 3:4?', 'Sin is the transgression of the law', 'Sin is only harming other people', 'Sin is whatever society disapproves of', 'Sin is only what you do on purpose', 'a', '1 John 3:4 — "Whosoever committeth sin transgresseth also the law: for sin is the transgression of the law."'),
('1 John', 3, 'teens', 3, 'Why did Cain slay his brother Abel?', 'Because his own works were evil, and his brother''s righteous', 'Because Abel stole from him', 'Because their father told him to', 'Because Abel insulted him', 'a', '1 John 3:12 — "Not as Cain, who was of that wicked one, and slew his brother. And wherefore slew he him? Because his own works were evil, and his brother''s righteous."'),
('1 John', 3, 'teens', 4, 'How do we know we have passed from death to life?', 'Because we love the brethren', 'Because we attend church regularly', 'Because we have been baptized', 'Because we can quote Scripture', 'a', '1 John 3:14 — "We know that we have passed from death unto life, because we love the brethren."'),
('1 John', 3, 'teens', 5, 'How did we come to know love?', 'Because Christ laid down his life for us, and we ought to lay down our lives for the brethren', 'Through reading books about love', 'Through romantic relationships', 'Through our parents'' example only', 'a', '1 John 3:16 — "Hereby perceive we the love of God, because he laid down his life for us: and we ought to lay down our lives for the brethren."'),
-- Adults
('1 John', 3, 'adults', 1, 'What manner of love has the Father bestowed upon believers?', 'That we should be called the sons of God — and the reason the world knoweth us not is because it knew him not', 'That we should become wealthy and powerful', 'That we should rule over the nations', 'That we should be free from all suffering', 'a', '1 John 3:1 — "Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God: therefore the world knoweth us not, because it knew him not."'),
('1 John', 3, 'adults', 2, 'What does John say about everyone who has the hope of Christ''s appearing?', 'Every man that hath this hope in him purifieth himself, even as he is pure', 'He may live however he pleases', 'He need not worry about holiness', 'He is already perfected', 'a', '1 John 3:3 — "And every man that hath this hope in him purifieth himself, even as he is pure."'),
('1 John', 3, 'adults', 3, 'Why was the Son of God manifested according to verse 8?', 'That he might destroy the works of the devil', 'That he might establish an earthly kingdom', 'That he might write new scriptures', 'That he might train twelve apostles', 'a', '1 John 3:8 — "For this purpose the Son of God was manifested, that he might destroy the works of the devil."'),
('1 John', 3, 'adults', 4, 'What does John say about whosoever is born of God in verse 9?', 'He doth not commit sin, for his seed remaineth in him, and he cannot sin because he is born of God', 'He never makes any mistakes at all', 'He immediately becomes sinlessly perfect', 'He is free to sin without consequences', 'a', '1 John 3:9 — "Whosoever is born of God doth not commit sin; for his seed remaineth in him: and he cannot sin, because he is born of God." This describes the habitual practice of sin being incompatible with the new birth.'),
('1 John', 3, 'adults', 5, 'What does John say about the one who hates his brother?', 'He is a murderer, and no murderer hath eternal life abiding in him', 'He is just having a bad day', 'He needs counselling but is still saved', 'He is exercising righteous judgment', 'a', '1 John 3:15 — "Whosoever hateth his brother is a murderer: and ye know that no murderer hath eternal life abiding in him."'),
('1 John', 3, 'adults', 6, 'How does John define the failure to love practically?', 'Whoso hath this world''s good and seeth his brother have need and shutteth up his bowels of compassion — how dwelleth the love of God in him?', 'Failing to pray for someone daily', 'Not attending every church meeting', 'Not giving to the temple treasury', 'a', '1 John 3:17 — "But whoso hath this world''s good, and seeth his brother have need, and shutteth up his bowels of compassion from him, how dwelleth the love of God in him?"'),
('1 John', 3, 'adults', 7, 'How can believers have confidence before God?', 'If our heart condemn us not, then have we confidence toward God, and whatsoever we ask we receive because we keep his commandments', 'Through elaborate rituals and sacrifices', 'Through the intercession of church leaders', 'Through accumulating good works', 'a', '1 John 3:21-22 — "If our heart condemn us not, then have we confidence toward God. And whatsoever we ask, we receive of him, because we keep his commandments."'),
('1 John', 3, 'adults', 8, 'What is God''s commandment according to verse 23?', 'That we should believe on the name of his Son Jesus Christ, and love one another', 'That we keep the Sabbath and the feasts', 'That we tithe and give offerings', 'That we fast twice a week', 'a', '1 John 3:23 — "And this is his commandment, That we should believe on the name of his Son Jesus Christ, and love one another, as he gave us commandment."');

-- ═══ 1 John Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 John', 4, 'kids', 1, 'What does John say God is?', 'God is love', 'God is a warrior', 'God is a mystery', 'God is a storm', 'a', '1 John 4:8 — "He that loveth not knoweth not God; for God is love."'),
('1 John', 4, 'kids', 2, 'Why did God send his Son into the world?', 'That we might live through him', 'So the world would be destroyed', 'To build a new temple', 'To create a new law', 'a', '1 John 4:9 — "In this was manifested the love of God toward us, because that God sent his only begotten Son into the world, that we might live through him."'),
('1 John', 4, 'kids', 3, 'Why do we love God?', 'Because he first loved us', 'Because we are very smart', 'Because we are very good', 'Because someone told us to', 'a', '1 John 4:19 — "We love him, because he first loved us."'),
-- Teens
('1 John', 4, 'teens', 1, 'What should believers do with every spirit?', 'Try the spirits whether they are of God, because many false prophets are gone out into the world', 'Accept all spirits as from God', 'Ignore all spiritual matters', 'Fear all spirits equally', 'a', '1 John 4:1 — "Beloved, believe not every spirit, but try the spirits whether they are of God: because many false prophets are gone out into the world."'),
('1 John', 4, 'teens', 2, 'How can you know the Spirit of God?', 'Every spirit that confesseth that Jesus Christ is come in the flesh is of God', 'Every spirit that performs miracles', 'Every spirit that makes you feel good', 'Every spirit that predicts the future', 'a', '1 John 4:2 — "Hereby know ye the Spirit of God: Every spirit that confesseth that Jesus Christ is come in the flesh is of God."'),
('1 John', 4, 'teens', 3, 'Who is greater — the Spirit in believers or the spirit in the world?', 'Greater is he that is in you, than he that is in the world', 'The spirit in the world is stronger', 'They are equal in power', 'Neither has any real power', 'a', '1 John 4:4 — "Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world."'),
('1 John', 4, 'teens', 4, 'What does perfect love do to fear?', 'Perfect love casteth out fear', 'Perfect love increases fear of God', 'Perfect love ignores fear', 'Perfect love creates a new kind of fear', 'a', '1 John 4:18 — "There is no fear in love; but perfect love casteth out fear: because fear hath torment."'),
('1 John', 4, 'teens', 5, 'What does John say about someone who claims to love God but hates his brother?', 'He is a liar, for he that loveth not his brother whom he hath seen cannot love God whom he hath not seen', 'He is just struggling with a difficult relationship', 'He can still love God even while hating his brother', 'He needs to work harder at both', 'a', '1 John 4:20 — "If a man say, I love God, and hateth his brother, he is a liar: for he that loveth not his brother whom he hath seen, how can he love God whom he hath not seen?"'),
-- Adults
('1 John', 4, 'adults', 1, 'What is the spirit of antichrist according to verse 3?', 'Every spirit that confesseth not that Jesus Christ is come in the flesh is not of God — this is that spirit of antichrist', 'Any spirit that opposes the Roman government', 'Any spirit that disagrees with the apostles on minor points', 'Any spirit that refuses to join a local church', 'a', '1 John 4:3 — "And every spirit that confesseth not that Jesus Christ is come in the flesh is not of God: and this is that spirit of antichrist."'),
('1 John', 4, 'adults', 2, 'What does "herein is love" mean in verse 10?', 'Not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins', 'That we loved God first and he responded', 'That we earned God''s love through obedience', 'That love is a mutual exchange between equals', 'a', '1 John 4:10 — "Herein is love, not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins."'),
('1 John', 4, 'adults', 3, 'What does John say about seeing God in verse 12?', 'No man hath seen God at any time; if we love one another, God dwelleth in us, and his love is perfected in us', 'Many prophets have seen God face to face', 'Only Moses and Elijah have seen God', 'God is visible to anyone with faith', 'a', '1 John 4:12 — "No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us."'),
('1 John', 4, 'adults', 4, 'What confession does John say leads to God dwelling in a person?', 'Whosoever shall confess that Jesus is the Son of God, God dwelleth in him, and he in God', 'Whoever confesses belief in one God', 'Whoever confesses all sins publicly', 'Whoever confesses allegiance to the church', 'a', '1 John 4:15 — "Whosoever shall confess that Jesus is the Son of God, God dwelleth in him, and he in God."'),
('1 John', 4, 'adults', 5, 'What does John say about God''s love being perfected in believers?', 'Herein is our love made perfect, that we may have boldness in the day of judgment: because as he is, so are we in this world', 'God''s love makes us sinlessly perfect in this life', 'God''s love removes the day of judgment entirely', 'God''s love is only perfected in heaven', 'a', '1 John 4:17 — "Herein is our love made perfect, that we may have boldness in the day of judgment: because as he is, so are we in this world."'),
('1 John', 4, 'adults', 6, 'Why does fear have torment according to verse 18?', 'Because fear hath torment, and he that feareth is not made perfect in love', 'Because fear is a sign of unbelief', 'Because fear leads to physical illness', 'Because fear causes poverty', 'a', '1 John 4:18 — "There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love."'),
('1 John', 4, 'adults', 7, 'How do we know that we dwell in God and he in us?', 'Because he hath given us of his Spirit', 'Because we feel emotions during worship', 'Because we have been baptized in water', 'Because we belong to a church', 'a', '1 John 4:13 — "Hereby know we that we dwell in him, and he in us, because he hath given us of his Spirit."'),
('1 John', 4, 'adults', 8, 'What commandment has he who loves God also received?', 'That he who loveth God love his brother also', 'That he who loves God must fast twice weekly', 'That he who loves God must give all possessions away', 'That he who loves God must preach in public', 'a', '1 John 4:21 — "And this commandment have we from him, That he who loveth God love his brother also."');

-- ═══ 1 John Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('1 John', 5, 'kids', 1, 'What overcomes the world?', 'Our faith', 'Our strength', 'Our money', 'Our army', 'a', '1 John 5:4 — "And this is the victory that overcometh the world, even our faith."'),
('1 John', 5, 'kids', 2, 'What has God given to us through his Son?', 'Eternal life', 'A big house', 'A crown of gold', 'A magic power', 'a', '1 John 5:11 — "And this is the record, that God hath given to us eternal life, and this life is in his Son."'),
('1 John', 5, 'kids', 3, 'Why did John write this letter?', 'That ye may know that ye have eternal life', 'To tell a fun story', 'To teach math and reading', 'To sell books', 'a', '1 John 5:13 — "These things have I written unto you that believe on the name of the Son of God; that ye may know that ye have eternal life."'),
-- Teens
('1 John', 5, 'teens', 1, 'What is the victory that overcometh the world?', 'Even our faith', 'Our military might', 'Our political power', 'Our accumulated wealth', 'a', '1 John 5:4 — "And this is the victory that overcometh the world, even our faith."'),
('1 John', 5, 'teens', 2, 'What three things bear witness in the earth?', 'The Spirit, the water, and the blood — and these three agree in one', 'The sun, the moon, and the stars', 'The prophets, the priests, and the kings', 'The Father, the Son, and the Holy Ghost', 'a', '1 John 5:8 — "And there are three that bear witness in earth, the Spirit, and the water, and the blood: and these three agree in one."'),
('1 John', 5, 'teens', 3, 'What confidence do believers have according to verse 14?', 'If we ask any thing according to his will, he heareth us', 'God will give us whatever we want', 'God only hears prayers on certain days', 'God hears only the prayers of the elders', 'a', '1 John 5:14 — "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us."'),
('1 John', 5, 'teens', 4, 'What does John say about sin unto death?', 'There is a sin unto death; I do not say that he shall pray for it', 'Every sin leads to physical death', 'There is no sin that leads to death', 'Only murder is a sin unto death', 'a', '1 John 5:16 — "There is a sin unto death: I do not say that he shall pray for it."'),
('1 John', 5, 'teens', 5, 'What does John tell believers to keep themselves from?', 'Idols', 'All food offered to idols', 'All Gentile friends', 'All Roman customs', 'a', '1 John 5:21 — "Little children, keep yourselves from idols. Amen."'),
-- Adults
('1 John', 5, 'adults', 1, 'Who is it that overcometh the world according to verse 5?', 'He that believeth that Jesus is the Son of God', 'He that keeps all the commandments perfectly', 'He that performs the most miracles', 'He that has the most Bible knowledge', 'a', '1 John 5:5 — "Who is he that overcometh the world, but he that believeth that Jesus is the Son of God?"'),
('1 John', 5, 'adults', 2, 'What does John say about Jesus coming by water and blood?', 'This is he that came by water and blood, even Jesus Christ; not by water only, but by water and blood', 'Christ came only by water baptism', 'Christ came only by the blood of the covenant', 'Christ came by neither water nor blood', 'a', '1 John 5:6 — "This is he that came by water and blood, even Jesus Christ; not by water only, but by water and blood. And it is the Spirit that beareth witness, because the Spirit is truth."'),
('1 John', 5, 'adults', 3, 'What does John say about the witness of God versus the witness of men?', 'If we receive the witness of men, the witness of God is greater — for this is the witness of God which he hath testified of his Son', 'The witness of men is more reliable', 'Both witnesses are equally valid', 'God does not give witness to men', 'a', '1 John 5:9 — "If we receive the witness of men, the witness of God is greater: for this is the witness of God which he hath testified of his Son."'),
('1 John', 5, 'adults', 4, 'What does John say about the one who does not believe God?', 'He hath made him a liar, because he believeth not the record that God gave of his Son', 'He simply needs more time to understand', 'He is being cautious and wise', 'He has not heard the truth yet', 'a', '1 John 5:10 — "He that believeth not God hath made him a liar; because he believeth not the record that God gave of his Son."'),
('1 John', 5, 'adults', 5, 'What is the explicit purpose of 1 John according to verse 13?', 'That ye may know that ye have eternal life, and that ye may believe on the name of the Son of God', 'To provide a systematic theology', 'To give a history of the early church', 'To prophesy about future events', 'a', '1 John 5:13 — "These things have I written unto you that believe on the name of the Son of God; that ye may know that ye have eternal life."'),
('1 John', 5, 'adults', 6, 'What does John say about whosoever is born of God and sin?', 'He that is born of God keepeth himself, and that wicked one toucheth him not', 'He is immune to all forms of temptation', 'He can sin freely because grace abounds', 'He must rely on church leaders for protection', 'a', '1 John 5:18 — "We know that whosoever is born of God sinneth not; but he that is begotten of God keepeth himself, and that wicked one toucheth him not."'),
('1 John', 5, 'adults', 7, 'What does John say about the whole world in verse 19?', 'The whole world lieth in wickedness (or, in the wicked one)', 'The whole world is gradually getting better', 'The whole world belongs to believers', 'The whole world has been redeemed', 'a', '1 John 5:19 — "And we know that we are of God, and the whole world lieth in wickedness."'),
('1 John', 5, 'adults', 8, 'What Christological affirmation does John make in verse 20?', 'This is the true God, and eternal life — affirming that Jesus Christ is the true God', 'Jesus is only a great teacher', 'Jesus is the highest created being', 'Jesus is a prophet like Moses', 'a', '1 John 5:20 — "And we know that the Son of God is come, and hath given us an understanding, that we may know him that is true, and we are in him that is true, even in his Son Jesus Christ. This is the true God, and eternal life."');
