-- ============================================================================
-- Quiz Seed: Epistle to the Philippians (Chapters 1–4)
-- 3 difficulties × 4 chapters = 64 total questions
--   kids:   3 per chapter  = 12
--   teens:  5 per chapter  = 20
--   adults: 8 per chapter  = 32
-- ============================================================================

-- ═══ Philippians Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Philippians', 1, 'kids', 1, 'Who wrote the letter to the Philippians?', 'Paul and Timothy', 'Peter and John', 'James and Jude', 'Luke and Mark', 'a', 'Philippians 1:1 — "Paul and Timotheus, the servants of Jesus Christ, to all the saints in Christ Jesus which are at Philippi."'),
('Philippians', 1, 'kids', 2, 'Where was Paul when he wrote this letter?', 'In prison', 'At home', 'On a boat', 'In the temple', 'a', 'Philippians 1:13 — "my bonds in Christ are manifest in all the palace."'),
('Philippians', 1, 'kids', 3, 'What does Paul say is better than living?', 'To depart and be with Christ', 'To be rich', 'To be famous', 'To travel the world', 'a', 'Philippians 1:23 — "having a desire to depart, and to be with Christ; which is far better."'),
-- Teens
('Philippians', 1, 'teens', 1, 'What does Paul say about the good work God began in the Philippians?', 'He who began it will perform (complete) it until the day of Jesus Christ', 'He started it but they must finish it', 'He might abandon it if they don''t cooperate', 'He only started it in some of them', 'a', 'Philippians 1:6 — "he which hath begun a good work in you will perform it until the day of Jesus Christ."'),
('Philippians', 1, 'teens', 2, 'What happened because of Paul''s imprisonment?', 'The gospel spread even further — his bonds became known throughout the palace and others were emboldened to preach', 'The church fell apart', 'Everyone stopped preaching', 'The Romans became Christians', 'a', 'Philippians 1:12-14 — "the things which happened unto me have fallen out rather unto the furtherance of the gospel."'),
('Philippians', 1, 'teens', 3, 'What does Paul say about those who preach Christ out of envy?', 'Whether in pretence or truth, Christ is preached — and he rejoices in that', 'They should be silenced immediately', 'They will be punished by God', 'Their preaching is ineffective', 'a', 'Philippians 1:18 — "whether in pretence, or in truth, Christ is preached; and I therein do rejoice."'),
('Philippians', 1, 'teens', 4, 'What does Paul say is given to believers on behalf of Christ?', 'Not only to believe on Him but also to suffer for His sake', 'Only to believe and be happy', 'To rule over the nations', 'To accumulate earthly treasures', 'a', 'Philippians 1:29 — "unto you it is given in the behalf of Christ, not only to believe on him, but also to suffer for his sake."'),
('Philippians', 1, 'teens', 5, 'What famous statement does Paul make about living and dying?', '"For to me to live is Christ, and to die is gain"', '"I will live forever in this body"', '"Death is the end of everything"', '"Life is meaningless without wealth"', 'a', 'Philippians 1:21 — "For to me to live is Christ, and to die is gain."'),
-- Adults
('Philippians', 1, 'adults', 1, 'What does Paul pray the Philippians'' love would do?', 'Abound yet more and more in knowledge and in all judgment (discernment)', 'Simply increase in emotion', 'Focus exclusively on fellow believers', 'Lead them to abandon critical thinking', 'a', 'Philippians 1:9 — "that your love may abound yet more and more in knowledge and in all judgment."'),
('Philippians', 1, 'adults', 2, 'What does Paul pray they would be until the day of Christ?', 'Sincere and without offence, filled with the fruits of righteousness by Jesus Christ', 'Wealthy and influential', 'Free from all persecution', 'Leaders of the Roman Empire', 'a', 'Philippians 1:10-11 — "that ye may be sincere and without offence till the day of Christ; Being filled with the fruits of righteousness."'),
('Philippians', 1, 'adults', 3, 'What is Paul''s dilemma between living and dying?', 'He is in a strait betwixt two — desiring to depart and be with Christ (far better) but knowing it is more needful for the Philippians that he remain in the flesh', 'He fears death and wants to live longer', 'He is tired of life and wants to die', 'He is indifferent to both options', 'a', 'Philippians 1:23-24 — "I am in a strait betwixt two, having a desire to depart, and to be with Christ; which is far better: Nevertheless to abide in the flesh is more needful for you."'),
('Philippians', 1, 'adults', 4, 'What does Paul exhort the Philippians to do regarding their conversation (conduct)?', 'Let it be as it becometh the gospel of Christ — standing fast in one spirit, striving together for the faith of the gospel', 'Follow Roman customs to avoid persecution', 'Keep their faith private and hidden', 'Separate into smaller house churches', 'a', 'Philippians 1:27 — "let your conversation be as it becometh the gospel of Christ."'),
('Philippians', 1, 'adults', 5, 'What does Paul say about the adversaries of the Philippians?', 'Their unity and fearlessness is to them an evident token of perdition, but to the Philippians of salvation, from God', 'They will soon be converted', 'They are secretly on the Philippians'' side', 'They are powerless against believers', 'a', 'Philippians 1:28 — "in nothing terrified by your adversaries: which is to them an evident token of perdition, but to you of salvation, and that of God."'),
('Philippians', 1, 'adults', 6, 'How does Paul describe his affection for the Philippians?', 'He longs after them all in the bowels (deep affection) of Jesus Christ', 'He remembers them occasionally in prayer', 'He is grateful for their financial support only', 'He considers them one of many churches', 'a', 'Philippians 1:8 — "God is my record, how greatly I long after you all in the bowels of Jesus Christ."'),
('Philippians', 1, 'adults', 7, 'What do the words "the praetorium" and "Caesar''s household" tell us about Paul''s imprisonment?', 'He was imprisoned in Rome, and the gospel had reached even the imperial guard and household of Caesar', 'He was in a local Philippian jail', 'He was under house arrest in Corinth', 'He was in a provincial prison in Greece', 'a', 'Philippians 1:13 — "my bonds in Christ are manifest in all the palace (praetorium)." Also 4:22 mentions Caesar''s household.'),
('Philippians', 1, 'adults', 8, 'What two motives does Paul identify among those who preach Christ?', 'Some preach out of love knowing Paul is set for the defence of the gospel; others out of contention/envy, supposing to add affliction to Paul''s bonds', 'All preach from pure motives', 'Some preach for money, others for fame', 'Some preach from the Old Testament, others from the New', 'a', 'Philippians 1:15-17 — "Some indeed preach Christ even of envy and strife; and some also of good will… The one preach Christ of contention… the other of love."');

-- ═══ Philippians Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Philippians', 2, 'kids', 1, 'Who does Paul say we should think of as more important than ourselves?', 'Others', 'Only ourselves', 'Only rich people', 'Only pastors', 'a', 'Philippians 2:3 — "let each esteem other better than themselves."'),
('Philippians', 2, 'kids', 2, 'What did Jesus do even though He was God?', 'He became a servant and humbled Himself', 'He demanded to be treated as a king', 'He refused to help anyone', 'He stayed in heaven', 'a', 'Philippians 2:7 — "made himself of no reputation, and took upon him the form of a servant."'),
('Philippians', 2, 'kids', 3, 'What will every knee do and every tongue confess?', 'Every knee shall bow and every tongue confess that Jesus Christ is Lord', 'Every person will sing a song', 'Every nation will build a church', 'Every child will learn to read', 'a', 'Philippians 2:10-11 — "at the name of Jesus every knee should bow… and every tongue should confess that Jesus Christ is Lord."'),
-- Teens
('Philippians', 2, 'teens', 1, 'What mind should believers have?', 'The same mind that was in Christ Jesus', 'The mind of a philosopher', 'The mind of a wealthy businessman', 'The mind of a Roman senator', 'a', 'Philippians 2:5 — "Let this mind be in you, which was also in Christ Jesus."'),
('Philippians', 2, 'teens', 2, 'What does Paul say about doing things without murmuring?', 'Do all things without murmurings and disputings, that ye may be blameless and harmless', 'Some complaining is acceptable', 'Only leaders need to avoid murmuring', 'Murmuring is a sign of passion', 'a', 'Philippians 2:14-15 — "Do all things without murmurings and disputings: That ye may be blameless and harmless, the sons of God."'),
('Philippians', 2, 'teens', 3, 'How far did Jesus humble Himself?', 'He became obedient unto death, even the death of the cross', 'He humbled Himself only for a short time', 'He humbled Himself only in appearance', 'He humbled Himself only before the disciples', 'a', 'Philippians 2:8 — "he humbled himself, and became obedient unto death, even the death of the cross."'),
('Philippians', 2, 'teens', 4, 'Who does Paul send to the Philippians and call a fellow worker?', 'Timothy and Epaphroditus', 'Barnabas and Silas', 'Peter and John', 'Apollos and Titus', 'a', 'Philippians 2:19,25 — Paul plans to send Timothy and sends Epaphroditus back.'),
('Philippians', 2, 'teens', 5, 'What happened to Epaphroditus that caused concern?', 'He was sick, nigh unto death, but God had mercy on him', 'He was arrested by the Romans', 'He lost his faith temporarily', 'He was robbed on the road', 'a', 'Philippians 2:27 — "he was sick nigh unto death: but God had mercy on him."'),
-- Adults
('Philippians', 2, 'adults', 1, 'What does the Greek word "kenosis" (from verse 7) mean in the Christological hymn?', 'Christ "emptied himself" (made himself of no reputation) — not by losing deity but by adding humanity, taking the form of a servant', 'Christ temporarily ceased being God', 'Christ lost His divine attributes', 'Christ gave up His throne permanently', 'a', 'Philippians 2:7 — "made himself of no reputation (ekenōsen)" — He emptied Himself by taking servant form, not by losing divine nature.'),
('Philippians', 2, 'adults', 2, 'What does "being in the form of God" establish about Christ''s pre-existence?', 'The word "morphe" (form) indicates the essential nature/being of God — Christ existed in the very nature of God before the incarnation', 'It means He looked like God but wasn''t actually God', 'It refers only to His appearance after baptism', 'It means He was created in God''s image like Adam', 'a', 'Philippians 2:6 — "Who, being in the form (morphe) of God, thought it not robbery to be equal with God."'),
('Philippians', 2, 'adults', 3, 'What is the result of Christ''s exaltation?', 'God highly exalted Him and gave Him a name above every name, that at His name every knee should bow in heaven, earth, and under the earth', 'He returned to His previous state unchanged', 'He became a powerful angel', 'He received a new divine attribute', 'a', 'Philippians 2:9-10 — "God also hath highly exalted him, and given him a name which is above every name."'),
('Philippians', 2, 'adults', 4, 'What does Paul say about working out salvation?', '"Work out your own salvation with fear and trembling, for it is God which worketh in you both to will and to do of his good pleasure"', '"Work to earn your salvation through obedience"', '"Your salvation depends entirely on your efforts"', '"Once saved, no effort is needed"', 'a', 'Philippians 2:12-13 — "work out your own salvation with fear and trembling. For it is God which worketh in you both to will and to do of his good pleasure."'),
('Philippians', 2, 'adults', 5, 'What imagery does Paul use about the Philippians shining?', 'They should shine as lights in the world, holding forth the word of life, in the midst of a crooked and perverse nation', 'They should hide their faith like a candle under a bushel', 'They should only share their light with fellow believers', 'They should wait until the world improves to show their light', 'a', 'Philippians 2:15-16 — "ye shine as lights in the world; Holding forth the word of life."'),
('Philippians', 2, 'adults', 6, 'What sacrificial language does Paul use about his ministry?', 'He says even if he is "poured out as a drink offering" upon the sacrifice and service of their faith, he rejoices', 'He compares himself to the high priest', 'He describes his work as building a temple', 'He likens his ministry to farming', 'a', 'Philippians 2:17 — "if I be offered upon the sacrifice and service of your faith, I joy, and rejoice with you all."'),
('Philippians', 2, 'adults', 7, 'What does Paul say about Timothy compared to others?', 'He has no one like-minded who will naturally care for their state — all others seek their own things, not the things of Jesus Christ', 'Timothy is the youngest and least experienced', 'Timothy is equal to all others in devotion', 'Timothy needs more training before he can serve', 'a', 'Philippians 2:20-21 — "I have no man likeminded, who will naturally care for your state. For all seek their own, not the things which are Jesus Christ''s."'),
('Philippians', 2, 'adults', 8, 'Why does Paul send Epaphroditus back to Philippi?', 'Because Epaphroditus longed for them and was full of heaviness because they heard he was sick — Paul sends him so they may rejoice and he may be less sorrowful', 'Because Epaphroditus was disobedient', 'Because Paul didn''t need him anymore', 'Because the Philippians demanded his return', 'a', 'Philippians 2:26-28 — "he longed after you all, and was full of heaviness, because that ye had heard that he had been sick… I sent him therefore the more carefully, that, when ye see him again, ye may rejoice."');

-- ═══ Philippians Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Philippians', 3, 'kids', 1, 'What does Paul say he counts as loss compared to knowing Christ?', 'All things', 'Only his money', 'Only his old clothes', 'Only his house', 'a', 'Philippians 3:8 — "I count all things but loss for the excellency of the knowledge of Christ Jesus my Lord."'),
('Philippians', 3, 'kids', 2, 'Where is the citizenship of believers?', 'In heaven', 'In Rome', 'In Jerusalem', 'In Greece', 'a', 'Philippians 3:20 — "our conversation (citizenship) is in heaven."'),
('Philippians', 3, 'kids', 3, 'What does Paul say he does — forgetting the past and reaching forward?', 'He presses toward the mark for the prize of the high calling of God in Christ', 'He runs backward', 'He stands still', 'He gives up', 'a', 'Philippians 3:14 — "I press toward the mark for the prize of the high calling of God in Christ Jesus."'),
-- Teens
('Philippians', 3, 'teens', 1, 'What credentials did Paul list that he counted as loss?', 'Circumcised the eighth day, of Israel, tribe of Benjamin, a Hebrew of Hebrews, a Pharisee, blameless in the law', 'Roman citizenship and military rank', 'Wealth, land, and slaves', 'A degree from the university and published writings', 'a', 'Philippians 3:5-6 — "Circumcised the eighth day, of the stock of Israel, of the tribe of Benjamin, an Hebrew of the Hebrews; as touching the law, a Pharisee."'),
('Philippians', 3, 'teens', 2, 'What does Paul want to gain instead of his own righteousness?', 'The righteousness which is of God by faith in Christ', 'The admiration of other apostles', 'A high position in the church', 'Legal approval from Rome', 'a', 'Philippians 3:9 — "not having mine own righteousness, which is of the law, but that which is through the faith of Christ, the righteousness which is of God by faith."'),
('Philippians', 3, 'teens', 3, 'What does Paul want to know about Christ?', 'The power of His resurrection and the fellowship of His sufferings', 'How to perform more miracles', 'When Christ will return', 'How to build bigger churches', 'a', 'Philippians 3:10 — "That I may know him, and the power of his resurrection, and the fellowship of his sufferings."'),
('Philippians', 3, 'teens', 4, 'Has Paul already reached perfection?', 'No — he says he has not already attained or been made perfect, but he presses on', 'Yes, he reached perfection years ago', 'He claims to be close to perfection', 'He says perfection is impossible', 'a', 'Philippians 3:12 — "Not as though I had already attained, either were already perfect: but I follow after."'),
('Philippians', 3, 'teens', 5, 'Who does Paul warn about as enemies of the cross?', 'Those whose god is their belly, whose glory is in their shame, who mind earthly things', 'Roman soldiers who persecute Christians', 'Jewish priests in the temple', 'Philosophers in Athens', 'a', 'Philippians 3:18-19 — "many walk, of whom I have told you often… that they are the enemies of the cross of Christ: Whose end is destruction, whose God is their belly, and whose glory is in their shame, who mind earthly things."'),
-- Adults
('Philippians', 3, 'adults', 1, 'What does Paul mean by "the concision" versus "the circumcision"?', 'He uses "concision" (cutting/mutilation) dismissively for those who demand circumcision, saying believers are the true circumcision who worship God in the spirit', 'He distinguishes between two types of surgical procedures', 'He refers to a geographical division between churches', 'He describes a doctrinal debate about fasting', 'a', 'Philippians 3:2-3 — "Beware of the concision. For we are the circumcision, which worship God in the spirit, and rejoice in Christ Jesus, and have no confidence in the flesh."'),
('Philippians', 3, 'adults', 2, 'What does Paul call his former religious accomplishments?', 'Dung (refuse/rubbish) — that he may win Christ and be found in Him', 'A good foundation that Christ built upon', 'Stepping stones toward salvation', 'Valuable experiences he treasures', 'a', 'Philippians 3:8 — "I count all things but loss… and do count them but dung, that I may win Christ."'),
('Philippians', 3, 'adults', 3, 'What does "being made conformable unto his death" mean?', 'Paul desires to be so identified with Christ that he shares in Christ''s pattern of suffering and death — dying to self and the world', 'Paul wants to die on a cross literally', 'Paul wants to experience physical death soon', 'Paul plans to fast until death', 'a', 'Philippians 3:10 — "being made conformable unto his death."'),
('Philippians', 3, 'adults', 4, 'What does "if by any means I might attain unto the resurrection of the dead" express?', 'Not doubt about salvation but Paul''s earnest desire and determined pursuit of the full experience of resurrection glory', 'Uncertainty about whether he is truly saved', 'A conditional statement about earning resurrection', 'Doubt about the doctrine of resurrection', 'a', 'Philippians 3:11 — "If by any means I might attain unto the resurrection of the dead."'),
('Philippians', 3, 'adults', 5, 'What athletic metaphor does Paul use for the Christian life?', 'Forgetting the things behind and reaching forward, pressing toward the mark (goal line) for the prize of the high calling', 'Swimming across a wide river', 'Climbing a tall mountain', 'Wrestling with an opponent', 'a', 'Philippians 3:13-14 — "forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark."'),
('Philippians', 3, 'adults', 6, 'What does Paul say about those who are "otherwise minded"?', 'God shall reveal even this unto them — showing confidence that God will correct their thinking', 'They should be excommunicated', 'They are lost and beyond hope', 'They should start their own church', 'a', 'Philippians 3:15 — "if in any thing ye be otherwise minded, God shall reveal even this unto you."'),
('Philippians', 3, 'adults', 7, 'What does Paul say the Saviour will do to believers'' bodies?', 'He shall change our vile body, that it may be fashioned like unto His glorious body, according to the working whereby He is able to subdue all things', 'He will preserve them from all sickness', 'He will make them invisible to enemies', 'He will translate them immediately to heaven', 'a', 'Philippians 3:21 — "Who shall change our vile body, that it may be fashioned like unto his glorious body, according to the working whereby he is able even to subdue all things unto himself."'),
('Philippians', 3, 'adults', 8, 'What rule does Paul give for spiritual progress in verse 16?', '"Whereto we have already attained, let us walk by the same rule, let us mind the same thing" — maintain unity and consistency in what has been achieved', '"Run as fast as possible to the goal"', '"Compete with one another for the highest prize"', '"Start over from the beginning with each new revelation"', 'a', 'Philippians 3:16 — "whereto we have already attained, let us walk by the same rule, let us mind the same thing."');

-- ═══ Philippians Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Philippians', 4, 'kids', 1, 'What does Paul say we should do instead of worrying?', 'Pray and give thanks to God', 'Worry more', 'Complain to friends', 'Hide under the bed', 'a', 'Philippians 4:6 — "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God."'),
('Philippians', 4, 'kids', 2, 'What does Paul say he can do through Christ?', 'All things', 'Only easy things', 'Nothing at all', 'Only a few things', 'a', 'Philippians 4:13 — "I can do all things through Christ which strengtheneth me."'),
('Philippians', 4, 'kids', 3, 'What should we think about?', 'Things that are true, honest, just, pure, lovely, and of good report', 'Scary stories', 'Mean thoughts about others', 'How to get more toys', 'a', 'Philippians 4:8 — "whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report… think on these things."'),
-- Teens
('Philippians', 4, 'teens', 1, 'What does Paul say the peace of God does?', 'It passes all understanding and shall keep your hearts and minds through Christ Jesus', 'It makes all problems disappear', 'It comes only after all trials end', 'It is available only to church leaders', 'a', 'Philippians 4:7 — "the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus."'),
('Philippians', 4, 'teens', 2, 'What has Paul learned in whatever state he is in?', 'To be content — he knows how to be abased and how to abound', 'To always seek better circumstances', 'To complain until things improve', 'To demand what he deserves', 'a', 'Philippians 4:11-12 — "I have learned, in whatsoever state I am, therewith to be content."'),
('Philippians', 4, 'teens', 3, 'What does Paul say God will supply?', 'All your need according to His riches in glory by Christ Jesus', 'Only your spiritual needs', 'Only food and clothing', 'Whatever you want', 'a', 'Philippians 4:19 — "my God shall supply all your need according to his riches in glory by Christ Jesus."'),
('Philippians', 4, 'teens', 4, 'Who does Paul ask to help Euodias and Syntyche?', 'His true yokefellow (companion), to help them be of the same mind in the Lord', 'Timothy', 'The Roman governor', 'The high priest', 'a', 'Philippians 4:2-3 — "I beseech Euodias, and beseech Syntyche, that they be of the same mind in the Lord. And I intreat thee also, true yokefellow, help those women."'),
('Philippians', 4, 'teens', 5, 'What does Paul say about the Philippians'' giving?', 'No other church communicated with him concerning giving and receiving except the Philippians', 'Every church gave generously', 'Only the wealthy churches gave', 'He never accepted gifts from any church', 'a', 'Philippians 4:15 — "no church communicated with me as concerning giving and receiving, but ye only."'),
-- Adults
('Philippians', 4, 'adults', 1, 'What does "Be careful for nothing" mean in Philippians 4:6?', 'Be anxious about nothing — instead bring everything to God in prayer with thanksgiving', 'Don''t be careful about anything', 'Don''t worry about making mistakes', 'Don''t care about anything at all', 'a', 'Philippians 4:6 — "Be careful (anxious) for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God."'),
('Philippians', 4, 'adults', 2, 'What six virtues does Paul list for the Philippians to think on?', 'Things true, honest, just, pure, lovely, and of good report — plus virtue and praise', 'Faith, hope, love, mercy, grace, and peace', 'Strength, courage, wisdom, knowledge, power, and glory', 'Prayer, fasting, giving, preaching, teaching, and healing', 'a', 'Philippians 4:8 — "whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things."'),
('Philippians', 4, 'adults', 3, 'What is the "secret" Paul has learned?', '"I know both how to be abased, and I know how to abound: every where and in all things I am instructed both to be full and to be hungry, both to abound and to suffer need"', 'A hidden mystery about the end times', 'A special prayer technique', 'The location of a hidden treasure', 'a', 'Philippians 4:12 — "I know both how to be abased, and I know how to abound: every where and in all things I am instructed."'),
('Philippians', 4, 'adults', 4, 'What does "I can do all things through Christ" mean in context?', 'Through Christ, Paul can endure any circumstance — abundance or need, fullness or hunger — it''s about contentment in all conditions, not unlimited ability', 'Believers can do literally anything they wish', 'Christ gives supernatural powers to all believers', 'It applies only to miracle-working apostles', 'a', 'Philippians 4:13 in context of 4:11-12 — "I can do all things through Christ which strengtheneth me" refers to contentment in all circumstances.'),
('Philippians', 4, 'adults', 5, 'What sacrificial language does Paul use for the Philippians'' gift?', '"An odour of a sweet smell, a sacrifice acceptable, wellpleasing to God" — using Old Testament sacrificial terminology for their financial gift', 'A tithe according to the law of Moses', 'A tax paid to the Roman government', 'A simple donation without spiritual significance', 'a', 'Philippians 4:18 — "an odour of a sweet smell, a sacrifice acceptable, wellpleasing to God."'),
('Philippians', 4, 'adults', 6, 'What does Paul mean by "the God of peace shall be with you"?', 'If they practice what Paul taught, God''s presence (not just His peace, but He Himself) will be with them', 'They will never face any conflict', 'They will achieve inner tranquility through meditation', 'Peace is guaranteed regardless of their behavior', 'a', 'Philippians 4:9 — "Those things, which ye have both learned, and received, and heard, and seen in me, do: and the God of peace shall be with you."'),
('Philippians', 4, 'adults', 7, 'What does Philippians 4:19 promise and on what basis?', 'God will supply all their need according to HIS riches in glory — not out of their resources but out of God''s inexhaustible heavenly wealth, in response to their generous giving', 'God will make them rich', 'They will never lack anything material', 'All prayers will be answered exactly as requested', 'a', 'Philippians 4:19 — "my God shall supply all your need according to his riches in glory by Christ Jesus."'),
('Philippians', 4, 'adults', 8, 'What final greeting does Paul include that reveals the reach of the gospel?', '"All the saints salute you, chiefly they that are of Caesar''s household" — the gospel had penetrated even the Roman imperial household', 'All the saints in Jerusalem send greetings', 'All the churches in Asia greet them', 'Only Jewish believers send their regards', 'a', 'Philippians 4:22 — "All the saints salute you, chiefly they that are of Caesar''s household."');
