-- ============================================================================
-- Quiz Seed: Gospel of Matthew (Chapters 1–28)
-- 3 difficulties × 28 chapters = 448 total questions
--   kids:   3 per chapter  =  84
--   teens:  5 per chapter  = 140
--   adults: 8 per chapter  = 224
-- ============================================================================

-- ═══════════════════════════════════════════════════════════════════════════
-- CHAPTERS 1 – 5
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══ Matthew Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 1, 'kids', 1, 'What is the name of Mary''s husband?', 'Joseph', 'Zacharias', 'Simeon', 'Herod', 'a', 'Matthew 1:16 — "And Jacob begat Joseph the husband of Mary, of whom was born Jesus."'),
('Matthew', 1, 'kids', 2, 'What name means "God with us"?', 'Emmanuel', 'Jesus', 'Joshua', 'Isaac', 'a', 'Matthew 1:23 — "they shall call his name Emmanuel, which being interpreted is, God with us."'),
('Matthew', 1, 'kids', 3, 'Who told Joseph that Mary would have a baby?', 'An angel of the Lord', 'A prophet', 'A priest', 'His father Jacob', 'a', 'Matthew 1:20 — "the angel of the Lord appeared unto him in a dream."'),
-- Teens
('Matthew', 1, 'teens', 1, 'How many generations are listed from Abraham to David in Matthew 1?', 'Fourteen', 'Twelve', 'Sixteen', 'Ten', 'a', 'Matthew 1:17 — "So all the generations from Abraham to David are fourteen generations."'),
('Matthew', 1, 'teens', 2, 'What were Joseph''s plans for Mary before the angel appeared to him?', 'To put her away privily', 'To marry her immediately', 'To take her to the temple', 'To send her to her parents', 'a', 'Matthew 1:19 — "Joseph her husband, being a just man, and not willing to make her a publick example, was minded to put her away privily."'),
('Matthew', 1, 'teens', 3, 'What was Jesus'' primary mission according to the angel''s message to Joseph?', 'To save his people from their sins', 'To overthrow Roman rule', 'To restore the temple', 'To teach the law of Moses', 'a', 'Matthew 1:21 — "thou shalt call his name JESUS: for he shall save his people from their sins."'),
('Matthew', 1, 'teens', 4, 'Which prophet''s words are fulfilled in the virgin birth narrative of Matthew 1?', 'Isaiah', 'Micah', 'Jeremiah', 'Daniel', 'a', 'Matthew 1:22-23 — "Now all this was done, that it might be fulfilled which was spoken of the Lord by the prophet" — citing Isaiah 7:14.'),
('Matthew', 1, 'teens', 5, 'Who is listed as a Gentile woman in the genealogy of Jesus in Matthew 1?', 'Rahab', 'Sarah', 'Rebekah', 'Miriam', 'a', 'Matthew 1:5 — "And Salmon begat Booz of Rachab" — Rahab was a Canaanite woman from Jericho.'),
-- Adults
('Matthew', 1, 'adults', 1, 'The genealogy in Matthew 1 is structured around three sets of how many generations each?', 'Fourteen', 'Seven', 'Ten', 'Twelve', 'a', 'Matthew 1:17 — "So all the generations from Abraham to David are fourteen generations; and from David until the carrying away into Babylon are fourteen generations; and from the carrying away into Babylon unto Christ are fourteen generations."'),
('Matthew', 1, 'adults', 2, 'Which woman in the genealogy of Matthew 1 was the wife of Uriah the Hittite?', 'Bathsheba (she that had been the wife of Urias)', 'Ruth', 'Tamar', 'Rahab', 'a', 'Matthew 1:6 — "And David the king begat Solomon of her that had been the wife of Urias."'),
('Matthew', 1, 'adults', 3, 'What theological significance does the title "Christ" carry in Matthew 1:1?', 'It is the Greek equivalent of the Hebrew Messiah, meaning Anointed One', 'It is a Roman honorific title', 'It means Son of God exclusively', 'It refers only to his priestly role', 'a', 'Matthew 1:1 — "The book of the generation of Jesus Christ, the son of David, the son of Abraham." Christ (Christos) is the Greek translation of the Hebrew Mashiach, meaning Anointed One.'),
('Matthew', 1, 'adults', 4, 'Why does Matthew open with the genealogy tracing Jesus to both Abraham and David?', 'To establish Jesus as fulfillment of both the Abrahamic covenant and the Davidic covenant', 'To prove Roman citizenship', 'To show priestly lineage through Levi', 'To satisfy Roman census requirements', 'a', 'Matthew 1:1 — "Jesus Christ, the son of David, the son of Abraham." God promised Abraham all nations would be blessed (Gen 12:3) and promised David an eternal throne (2 Sam 7:12-13).'),
('Matthew', 1, 'adults', 5, 'In what state did Joseph find Mary when he took her as his wife, according to Matthew 1:24-25?', 'He knew her not till she had brought forth her firstborn son', 'He immediately consummated the marriage', 'He waited seven years before living with her', 'The text does not specify', 'a', 'Matthew 1:24-25 — "Then Joseph being raised from sleep did as the angel of the Lord had bidden him, and took unto him his wife: And knew her not till she had brought forth her firstborn son."'),
('Matthew', 1, 'adults', 6, 'Which of the four women in the genealogy (besides Mary) is associated with a story of social irregularity or sin?', 'All three — Tamar, Rahab, and Ruth — are associated with irregular circumstances', 'Only Rahab, as a harlot', 'Only Tamar, through Judah', 'None; all were righteous women', 'a', 'Matthew 1:3-5 — Tamar (incest with Judah), Rahab (harlot of Jericho), Ruth (Moabitess foreigner), and Bathsheba (adultery situation). All point to God''s grace including unlikely people in redemptive history.'),
('Matthew', 1, 'adults', 7, 'What does Matthew''s phrase "that it might be fulfilled" (v.22) indicate about his theological method?', 'He employs a fulfillment formula to demonstrate that Jesus'' life enacts Old Testament prophecy', 'He is writing a legal document', 'He is quoting from the Septuagint only for historical interest', 'He is correcting errors in earlier accounts', 'a', 'Matthew 1:22 — "Now all this was done, that it might be fulfilled which was spoken of the Lord by the prophet." This fulfillment formula appears ~12 times in Matthew, forming his distinctive apologetic that Jesus is the promised Messiah.'),
('Matthew', 1, 'adults', 8, 'What is the significance of the name "Jesus" as explained in Matthew 1:21?', 'The name Yeshua (Joshua) means "the LORD saves" and points to his salvific mission', 'It was a common name with no special meaning in this context', 'It honors the high priest Joshua of the post-exilic period', 'It is purely a family name passed down from ancestors', 'a', 'Matthew 1:21 — "thou shalt call his name JESUS: for he shall save his people from their sins." The Hebrew Yeshua derives from Yahweh + yasha (to save/deliver), directly explaining the mission stated in the same verse.');

-- ═══ Matthew Chapter 2 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 2, 'kids', 1, 'What did the wise men follow to find Jesus?', 'A star', 'An angel', 'A cloud', 'A rainbow', 'a', 'Matthew 2:2 — "Where is he that is born King of the Jews? for we have seen his star in the east, and are come to worship him."'),
('Matthew', 2, 'kids', 2, 'What gifts did the wise men bring to Jesus?', 'Gold, frankincense, and myrrh', 'Silver, oil, and spices', 'Money, bread, and wine', 'Cloth, perfume, and coins', 'a', 'Matthew 2:11 — "they presented unto him gifts; gold, and frankincense, and myrrh."'),
('Matthew', 2, 'kids', 3, 'Where did Joseph take Mary and Jesus to escape King Herod?', 'Egypt', 'Babylon', 'Rome', 'Nazareth', 'a', 'Matthew 2:14 — "he took the young child and his mother by night, and departed into Egypt."'),
-- Teens
('Matthew', 2, 'teens', 1, 'Where did the chief priests and scribes tell Herod that Christ was to be born?', 'Bethlehem of Judaea', 'Jerusalem', 'Nazareth', 'Galilee', 'a', 'Matthew 2:5 — "And they said unto him, In Bethlehem of Judaea: for thus it is written by the prophet."'),
('Matthew', 2, 'teens', 2, 'What did Herod secretly want when he asked the wise men to find the child?', 'To kill him', 'To worship him also', 'To arrest his parents', 'To tax his family', 'a', 'Matthew 2:13 — "for Herod will seek the young child to destroy him."'),
('Matthew', 2, 'teens', 3, 'How were the wise men warned not to return to Herod?', 'By God in a dream', 'By an angel appearing visibly', 'By a message from Joseph', 'By a priest in Jerusalem', 'a', 'Matthew 2:12 — "being warned of God in a dream that they should not return to Herod, they departed into their own country another way."'),
('Matthew', 2, 'teens', 4, 'What was the age range of children Herod ordered to be killed in Bethlehem?', 'Two years old and under', 'Under one year old', 'Under five years old', 'All male infants', 'a', 'Matthew 2:16 — "slew all the children that were in Bethlehem...from two years old and under, according to the time which he had diligently enquired of the wise men."'),
('Matthew', 2, 'teens', 5, 'In what city did Joseph settle after returning from Egypt?', 'Nazareth', 'Bethlehem', 'Jerusalem', 'Capernaum', 'a', 'Matthew 2:23 — "And he came and dwelt in a city called Nazareth: that it might be fulfilled which was spoken by the prophets, He shall be called a Nazarene."'),
-- Adults
('Matthew', 2, 'adults', 1, 'Which Old Testament prophet is quoted in Matthew 2:6 regarding Bethlehem?', 'Micah', 'Isaiah', 'Jeremiah', 'Zechariah', 'a', 'Matthew 2:6 quotes Micah 5:2 — "And thou Bethlehem, in the land of Juda, art not the least among the princes of Juda: for out of thee shall come a Governor, that shall rule my people Israel."'),
('Matthew', 2, 'adults', 2, 'What Old Testament event does Matthew parallel with the flight to Egypt by citing Hosea 11:1?', 'The Exodus of Israel from Egypt', 'The captivity of Joseph in Egypt', 'The plagues of Egypt', 'The sojourn of Abraham in Egypt', 'a', 'Matthew 2:15 — "Out of Egypt have I called my son." Originally spoken of Israel''s Exodus (Hos 11:1), Matthew applies it typologically to Jesus as the true Israel who recapitulates Israel''s history.'),
('Matthew', 2, 'adults', 3, 'The slaughter of the innocents is connected to which prophet''s lament in Matthew 2:17-18?', 'Jeremiah', 'Isaiah', 'Ezekiel', 'Amos', 'a', 'Matthew 2:17-18 — "Then was fulfilled that which was spoken by Jeremy the prophet, saying, In Rama was there a voice heard, lamentation, and weeping, and great mourning, Rachel weeping for her children."'),
('Matthew', 2, 'adults', 4, 'What is the theological significance of the Magi being Gentiles who worship the Jewish Messiah?', 'It foreshadows the universal scope of the Great Commission and inclusion of all nations', 'It proves astrology was acceptable in Jewish law', 'It shows Herod''s failure as king', 'It demonstrates the superiority of eastern wisdom', 'a', 'Matthew 2:1-2 — The Gentile Magi coming to worship prefigures Matthew 28:19 — "Go ye therefore, and teach all nations." The gospel is for all peoples, not Israel alone.'),
('Matthew', 2, 'adults', 5, 'How many times does an angel of the Lord appear in dreams in Matthew chapters 1-2?', 'Four', 'Two', 'Three', 'Five', 'a', 'Matthew records four divine dreams: 1:20 (Joseph told to take Mary), 2:12 (Magi warned), 2:13 (flee to Egypt), 2:19-20 (return from Egypt), 2:22 (go to Galilee) — actually five, showing divine providence guiding every step.'),
('Matthew', 2, 'adults', 6, 'What phrase from Numbers 24:17 may underlie the star narrative — "There shall come a Star out of Jacob"?', 'The messianic Star prophecy of Balaam', 'The sign of the covenant to Abraham', 'The pillar of fire in the wilderness', 'The lights created on the fourth day', 'a', 'Matthew 2:2 — "we have seen his star in the east." Numbers 24:17 — "there shall come a Star out of Jacob, and a Sceptre shall rise out of Israel." The Magi''s star is linked to this messianic prophecy.'),
('Matthew', 2, 'adults', 7, 'What does Matthew''s repeated fulfillment formula in chapter 2 demonstrate about his literary purpose?', 'That Jesus systematically fulfills OT prophecy, legitimizing his messianic identity to a Jewish audience', 'That Matthew was primarily writing for Roman readers', 'That he copied from earlier Greek historians', 'That prophecy in the OT had already been fulfilled before Jesus', 'a', 'Matthew 2 contains four fulfillment citations (vv.5-6, 15, 17-18, 23), each introduced by "that it might be fulfilled." This dense apologetic pattern is unique to Matthew and serves his primary Jewish audience.'),
('Matthew', 2, 'adults', 8, 'What does the phrase "He shall be called a Nazarene" (2:23) indicate, since it cannot be found verbatim in the OT?', 'Matthew uses "the prophets" (plural) to indicate a general prophetic theme rather than one specific text', 'It is a scribal error', 'It comes from the lost book of Jasher', 'It is a direct quote from Isaiah', 'a', 'Matthew 2:23 — "that it might be fulfilled which was spoken by the prophets, He shall be called a Nazarene." The plural "prophets" signals a thematic allusion (possibly to the Nazarite branch/nezer of Isaiah 11:1 or the despised origins of Messiah) rather than a single text.');

-- ═══ Matthew Chapter 3 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 3, 'kids', 1, 'Who baptized Jesus in the river Jordan?', 'John the Baptist', 'Peter', 'Andrew', 'Philip', 'a', 'Matthew 3:13 — "Then cometh Jesus from Galilee to Jordan unto John, to be baptized of him."'),
('Matthew', 3, 'kids', 2, 'What did John the Baptist eat in the wilderness?', 'Locusts and wild honey', 'Bread and fish', 'Figs and grapes', 'Manna and water', 'a', 'Matthew 3:4 — "And his meat was locusts and wild honey."'),
('Matthew', 3, 'kids', 3, 'What came down like a dove when Jesus was baptized?', 'The Holy Ghost', 'An angel', 'A cloud', 'A bird', 'a', 'Matthew 3:16 — "and he saw the Spirit of God descending like a dove, and lighting upon him."'),
-- Teens
('Matthew', 3, 'teens', 1, 'What was John the Baptist''s main message in the wilderness?', 'Repent: for the kingdom of heaven is at hand', 'Believe on the Lord Jesus Christ', 'Keep the law of Moses', 'Pay your tithes', 'a', 'Matthew 3:2 — "And saying, Repent ye: for the kingdom of heaven is at hand."'),
('Matthew', 3, 'teens', 2, 'What did John call the Pharisees and Sadducees who came to his baptism?', 'O generation of vipers', 'Hypocrites', 'Wolves in sheep''s clothing', 'Blind guides', 'a', 'Matthew 3:7 — "O generation of vipers, who hath warned you to flee from the wrath to come?"'),
('Matthew', 3, 'teens', 3, 'What did John say he was not worthy to do for the one coming after him?', 'Bear his shoes', 'Touch his garment', 'Wash his feet', 'Carry his cross', 'a', 'Matthew 3:11 — "whose shoes I am not worthy to bear: he shall baptize you with the Holy Ghost, and with fire."'),
('Matthew', 3, 'teens', 4, 'What did Jesus say was the reason he needed to be baptized by John?', 'To fulfil all righteousness', 'To set an example for sinners', 'Because he had sinned', 'To receive power for his ministry', 'a', 'Matthew 3:15 — "Suffer it to be so now: for thus it becometh us to fulfil all righteousness."'),
('Matthew', 3, 'teens', 5, 'What voice was heard from heaven at Jesus'' baptism?', '"This is my beloved Son, in whom I am well pleased"', '"This is the Christ, the Saviour of the world"', '"Arise, my servant, and go into all the world"', '"Behold the Lamb of God which taketh away the sin"', 'a', 'Matthew 3:17 — "And lo a voice from heaven, saying, This is my beloved Son, in whom I am well pleased."'),
-- Adults
('Matthew', 3, 'adults', 1, 'Which prophet''s words does Matthew cite as being fulfilled in John the Baptist''s ministry?', 'Isaiah', 'Malachi', 'Ezekiel', 'Joel', 'a', 'Matthew 3:3 — "For this is he that was spoken of by the prophet Esaias, saying, The voice of one crying in the wilderness, Prepare ye the way of the Lord." This quotes Isaiah 40:3.'),
('Matthew', 3, 'adults', 2, 'What is the theological significance of the trinitarian manifestation at Jesus'' baptism?', 'The Father speaks, the Son is baptized, and the Spirit descends — revealing the three persons of the Trinity simultaneously', 'It shows only the divinity of Jesus', 'It proves baptism is essential for salvation', 'It is purely symbolic with no theological content', 'a', 'Matthew 3:16-17 — The Spirit descends as a dove, the Father''s voice speaks, and the Son is present. This is one of the clearest NT trinitarian theophanies.'),
('Matthew', 3, 'adults', 3, 'What metaphor does John use to describe the coming judgment of the Messiah in Matthew 3:12?', 'Winnowing fan, threshing floor, wheat and chaff burned with unquenchable fire', 'A sword dividing bone and marrow', 'A flood covering the earth', 'A lion devouring the wicked', 'a', 'Matthew 3:12 — "Whose fan is in his hand, and he will throughly purge his floor, and gather his wheat into the garner; but he will burn up the chaff with unquenchable fire."'),
('Matthew', 3, 'adults', 4, 'Why did John initially refuse to baptize Jesus, and what does this reveal about John''s understanding?', 'John recognized Jesus'' superior righteousness and his own unworthiness to baptize the sinless one', 'John was afraid of the Roman authorities', 'John thought baptism was only for Gentile converts', 'John had already baptized Jesus privately', 'a', 'Matthew 3:14 — "But John forbad him, saying, I have need to be baptized of thee, and comest thou to me?" John understood Jesus was the greater one who baptizes with the Holy Ghost and fire (v.11).'),
('Matthew', 3, 'adults', 5, 'What does the command to "bring forth fruits meet for repentance" (3:8) indicate about John''s theology?', 'Genuine repentance must be evidenced by transformed conduct, not merely religious profession', 'Salvation comes through good works alone', 'Water baptism automatically produces spiritual fruit', 'The Pharisees were already saved by ancestry', 'a', 'Matthew 3:8-9 — "Bring forth therefore fruits meet for repentance: And think not to say within yourselves, We have Abraham to our father." John rejects works-less faith and ethnic entitlement equally.'),
('Matthew', 3, 'adults', 6, 'What axe imagery does John use in Matthew 3:10, and what does it signify?', '"And now also the axe is laid unto the root of the trees" — imminent judgment on fruitless religion', '"The axe of the Lord has already fallen on the wicked"', '"Every tree that beareth good fruit shall be hewn down"', '"The axe spares those who repent but destroys the rest"', 'a', 'Matthew 3:10 — "And now also the axe is laid unto the root of the trees: therefore every tree which bringeth not forth good fruit is hewn down, and cast into the fire." The present tense "is laid" signals urgency.'),
('Matthew', 3, 'adults', 7, 'How does John contrast his water baptism with the baptism of the coming Messiah?', 'John baptizes with water unto repentance; Messiah will baptize with the Holy Ghost and with fire', 'John baptizes only Jews; Messiah will baptize Gentiles', 'John''s baptism is temporary; Messiah''s baptism replaces it', 'John baptizes in rivers; Messiah baptizes in the sea', 'a', 'Matthew 3:11 — "I indeed baptize you with water unto repentance: but he that cometh after me is mightier than I...he shall baptize you with the Holy Ghost, and with fire."'),
('Matthew', 3, 'adults', 8, 'The phrase "the kingdom of heaven is at hand" appears first here in Matthew. What is distinctive about Matthew''s use of "heaven" versus "God" in this phrase?', 'Matthew uses "kingdom of heaven" (a Jewish circumlocution for God) to respect Jewish sensitivities about pronouncing God''s name', 'Matthew''s kingdom is limited to the afterlife, unlike Mark''s earthly kingdom', 'Matthew copied from a Roman document that used "heaven" as a legal term', 'The two phrases refer to entirely different kingdoms', 'a', 'Matthew 3:2 — "the kingdom of heaven." Matthew''s Gospel (written primarily for Jews) uses "heaven" approximately 32 times as a reverential circumlocution for God, while Mark and Luke typically use "kingdom of God."');

-- ═══ Matthew Chapter 4 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 4, 'kids', 1, 'Who tempted Jesus in the wilderness?', 'The devil', 'King Herod', 'The Pharisees', 'A serpent', 'a', 'Matthew 4:1 — "Then was Jesus led up of the Spirit into the wilderness to be tempted of the devil."'),
('Matthew', 4, 'kids', 2, 'How many days did Jesus fast in the wilderness?', 'Forty days and forty nights', 'Seven days', 'Three days', 'Thirty days', 'a', 'Matthew 4:2 — "And when he had fasted forty days and forty nights, he was afterward an hungred."'),
('Matthew', 4, 'kids', 3, 'What did Jesus say when the devil told him to turn stones into bread?', 'Man shall not live by bread alone', 'Get thee behind me, Satan', 'I am the bread of life', 'Thou shalt not tempt the Lord', 'a', 'Matthew 4:4 — "But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God."'),
-- Teens
('Matthew', 4, 'teens', 1, 'What were the three temptations the devil presented to Jesus?', 'Turn stones to bread; jump from the temple; receive all kingdoms for worship', 'Deny God; kill himself; marry a queen', 'Steal food; claim to be king; destroy the temple', 'Fast longer; pray less; avoid suffering', 'a', 'Matthew 4:3-9 — The three temptations involve physical appetite (bread), presuming on God''s protection (temple), and worshipping Satan for worldly power (kingdoms).'),
('Matthew', 4, 'teens', 2, 'What region did Jesus go to begin his preaching ministry after John was arrested?', 'Galilee, in the area of Zabulon and Nephthalim', 'Jerusalem near the temple', 'Bethlehem where he was born', 'The wilderness of Judaea', 'a', 'Matthew 4:12-13 — "Now when Jesus had heard that John was cast into prison, he departed into Galilee...in the borders of Zabulon and Nephthalim."'),
('Matthew', 4, 'teens', 3, 'What were Simon Peter and Andrew doing when Jesus called them to follow him?', 'Casting a net into the sea', 'Mending their nets', 'Selling fish at the market', 'Praying at the synagogue', 'a', 'Matthew 4:18 — "And Jesus, walking by the sea of Galilee, saw two brethren, Simon called Peter, and Andrew his brother, casting a net into the sea: for they were fishers."'),
('Matthew', 4, 'teens', 4, 'What did Jesus promise Simon and Andrew he would make them?', 'Fishers of men', 'Teachers of Israel', 'Rulers over the twelve tribes', 'Priests of the new covenant', 'a', 'Matthew 4:19 — "And he saith unto them, Follow me, and I will make you fishers of men."'),
('Matthew', 4, 'teens', 5, 'What was James and John doing when Jesus called them?', 'Mending their nets with their father Zebedee', 'Praying in the synagogue', 'Fishing with Simon Peter', 'Buying supplies at the market', 'a', 'Matthew 4:21 — "And going on from thence, he saw other two brethren, James the son of Zebedee, and John his brother, in a ship with Zebedee their father, mending their nets."'),
-- Adults
('Matthew', 4, 'adults', 1, 'What is the typological significance of Jesus'' forty-day fast paralleling Israel''s forty years in the wilderness?', 'Jesus as the true Israel passes the tests Israel failed, demonstrating perfect obedience where the nation failed', 'It shows Jesus had superhuman physical endurance', 'It mirrors Moses'' fast before receiving the Law', 'It symbolizes the forty-year reign of David', 'a', 'Matthew 4:1-2 — Jesus'' forty days recapitulate Israel''s forty years of wilderness testing (Deut 8:2-3). Each rebuttal quotes Deuteronomy, the book summarizing Israel''s wilderness lessons, showing Jesus as the faithful Son where Israel was unfaithful.'),
('Matthew', 4, 'adults', 2, 'From which book does Jesus quote in each of his three responses to the devil?', 'Deuteronomy (chapters 6 and 8)', 'Psalms and Isaiah', 'Exodus and Numbers', 'Leviticus and Genesis', 'a', 'Matthew 4:4 (Deut 8:3), 4:7 (Deut 6:16), 4:10 (Deut 6:13). All three responses come from Deuteronomy, the book of covenant fidelity that Israel should have obeyed in the wilderness.'),
('Matthew', 4, 'adults', 3, 'The devil quotes Psalm 91:11-12 during the temple temptation. What hermeneutical error does this represent?', 'Wresting Scripture from its covenantal context to justify presumption rather than trust', 'Quoting an uninspired psalm', 'Using the Hebrew text instead of the Septuagint', 'Applying a royal psalm to a prophet', 'a', 'Matthew 4:6 — The devil cites Scripture but strips the covenantal promise of its context of faithful obedience, turning a promise of protection into a license for reckless testing of God. Jesus counters with Deut 6:16 — "Thou shalt not tempt the Lord thy God."'),
('Matthew', 4, 'adults', 4, 'What OT prophet''s words does Matthew cite in 4:15-16 about "Galilee of the Gentiles"?', 'Isaiah', 'Amos', 'Hosea', 'Micah', 'a', 'Matthew 4:14-16 quotes Isaiah 9:1-2 — "The land of Zabulon, and the land of Nephthalim...Galilee of the Gentiles; The people which sat in darkness saw great light." This is another fulfillment formula establishing Jesus'' Galilean ministry.'),
('Matthew', 4, 'adults', 5, 'What phrase begins both John''s and Jesus'' proclamation in Matthew, showing continuity of message?', '"Repent: for the kingdom of heaven is at hand"', '"Blessed are the poor in spirit"', '"The time is fulfilled and the kingdom of God is at hand"', '"Thus saith the Lord God of Israel"', 'a', 'Matthew 3:2 (John) and 4:17 (Jesus) — "Repent: for the kingdom of heaven is at hand." The identical proclamation shows Jesus as the one whose coming John announced, with seamless continuity in the message.'),
('Matthew', 4, 'adults', 6, 'What does the immediate response of Peter, Andrew, James, and John to Jesus'' call indicate about the nature of discipleship in Matthew?', 'Radical, immediate abandonment of vocation and family ties in response to Jesus'' authoritative call', 'A gradual, considered decision after much deliberation', 'Partial following while maintaining their fishing business', 'Following Jesus only for economic benefit', 'a', 'Matthew 4:20 — "And they straightway left their nets, and followed him." Matthew 4:22 — "And they immediately left the ship and their father, and followed him." The word "straightway/immediately" and the leaving of family and livelihood signify total discipleship.'),
('Matthew', 4, 'adults', 7, 'Jesus'' summary of ministry in 4:23 mentions three activities. What are they?', 'Teaching in synagogues, preaching the gospel of the kingdom, healing all manner of sickness', 'Preaching, baptizing, and casting out demons', 'Reading Scripture, explaining prophecy, and performing miracles', 'Praying, fasting, and teaching the Beatitudes', 'a', 'Matthew 4:23 — "And Jesus went about all Galilee, teaching in their synagogues, and preaching the gospel of the kingdom, and healing all manner of sickness and all manner of disease among the people."'),
('Matthew', 4, 'adults', 8, 'What is the significance of the geographical progression in Matthew 4 — wilderness, temple, high mountain, Galilee — for understanding Jesus'' mission?', 'It moves from private testing to public proclamation, showing the Spirit-led transition from preparation to ministry', 'It follows the route of the Roman census', 'It mirrors the exodus route from Egypt to Canaan', 'It has no particular theological significance', 'a', 'Matthew 4:1-23 — The wilderness testing prepares Jesus; the temple and mountain represent Satan''s domain being rejected; Galilee of the Gentiles (v.15) launches the public ministry. The movement demonstrates that the kingdom advances from suffering and rejection of worldly power to servant proclamation.');

-- ═══ Matthew Chapter 5 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('Matthew', 5, 'kids', 1, 'What are the special blessings Jesus gives at the beginning of his famous sermon called?', 'The Beatitudes', 'The Ten Commandments', 'The Lord''s Prayer', 'The Golden Rule', 'a', 'Matthew 5:3-11 — Jesus begins the Sermon on the Mount with eight blessings, each starting with "Blessed are..." These are called the Beatitudes.'),
('Matthew', 5, 'kids', 2, 'Jesus says his followers are the light of the ___.', 'World', 'Temple', 'Sky', 'Synagogue', 'a', 'Matthew 5:14 — "Ye are the light of the world. A city that is set on an hill cannot be hid."'),
('Matthew', 5, 'kids', 3, 'Jesus says you should do what to your enemies?', 'Love them and pray for them', 'Ignore them', 'Report them to the rulers', 'Avoid them always', 'a', 'Matthew 5:44 — "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you."'),
-- Teens
('Matthew', 5, 'teens', 1, 'What did Jesus say about the Law — did he come to destroy it?', 'He came to fulfil it, not destroy it', 'He came to replace it with a new law', 'He came to make it easier to follow', 'He came to end the need for sacrifice', 'a', 'Matthew 5:17 — "Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil."'),
('Matthew', 5, 'teens', 2, 'What does Jesus say about anger in Matthew 5?', 'Being angry with a brother without cause makes one liable to judgment', 'Anger is only wrong when it leads to violence', 'Righteous anger is always acceptable', 'Only murder, not anger, is sin', 'a', 'Matthew 5:22 — "But I say unto you, That whosoever is angry with his brother without a cause shall be in danger of the judgment."'),
('Matthew', 5, 'teens', 3, 'What does Jesus teach about looking at a woman with lust?', 'It is adultery in the heart', 'It is a minor sin requiring no repentance', 'It is only sin if acted upon physically', 'It is forbidden only for married men', 'a', 'Matthew 5:28 — "But I say unto you, That whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart."'),
('Matthew', 5, 'teens', 4, 'What does Jesus teach about oaths in Matthew 5?', 'Simply let your yes be yes and your no be no', 'Swear only by the temple', 'Always swear by heaven to confirm truth', 'Oaths are required when speaking before rulers', 'a', 'Matthew 5:37 — "But let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these cometh of evil."'),
('Matthew', 5, 'teens', 5, 'What does Jesus say about being "salt of the earth"?', 'Salt that has lost its savour is good for nothing and is cast out', 'Salt makes everything better automatically', 'Being salty means being bold in speech', 'The more salt the better for the kingdom', 'a', 'Matthew 5:13 — "Ye are the salt of the earth: but if the salt have lost his savour, wherewith shall it be salted? it is thenceforth good for nothing, but to be cast out, and to be trodden under foot of men."'),
-- Adults
('Matthew', 5, 'adults', 1, 'What is the structural pattern Jesus uses in Matthew 5 to deepen the Mosaic Law?', '"Ye have heard that it was said...but I say unto you" — the Antithesis formula', '"It is written...therefore go and do likewise"', '"Moses said...but the prophets taught"', '"The law commands...but grace permits"', 'a', 'Matthew 5:21-48 contains six antitheses where Jesus intensifies the law''s demand from external conduct to inner disposition — murder→anger, adultery→lust, divorce, oaths, retaliation, and love of enemies.'),
('Matthew', 5, 'adults', 2, 'What is the standard of righteousness Jesus sets in Matthew 5:20 as a threshold for entering the kingdom?', 'Righteousness exceeding that of the scribes and Pharisees', 'Perfect keeping of all 613 commandments', 'Righteousness equivalent to John the Baptist', 'Righteousness measured by ritual purity', 'a', 'Matthew 5:20 — "For I say unto you, That except your righteousness shall exceed the righteousness of the scribes and Pharisees, ye shall in no case enter into the kingdom of heaven." This sets up the six antitheses that follow.'),
('Matthew', 5, 'adults', 3, 'What does the first Beatitude — "Blessed are the poor in spirit" — mean theologically?', 'Those who recognize their spiritual bankruptcy and total dependence on God are recipients of the kingdom', 'Those who are materially poor are automatically saved', 'Those who speak humbly in public worship are blessed', 'Those who fast regularly will receive the kingdom', 'a', 'Matthew 5:3 — "Blessed are the poor in spirit: for theirs is the kingdom of heaven." "Poor in spirit" (ptochos tō pneumati) means spiritually destitute — those who make no claims on God but come as beggars, contrasted with the self-sufficient Pharisees.'),
('Matthew', 5, 'adults', 4, 'How does Jesus'' command "Be ye therefore perfect" (5:48) relate to the preceding antitheses?', 'It summarizes the call to wholehearted, undivided love — as God''s love is complete (teleios) — not sinless perfection', 'It demands sinless perfection as a condition of salvation', 'It refers only to ritual cleanliness', 'It is hyperbolic language not meant literally', 'a', 'Matthew 5:48 — "Be ye therefore perfect, even as your Father which is in heaven is perfect." Teleios means complete/mature/whole. The context (love enemies, v.44-47) shows the perfection is undivided love modeled on the Father''s impartial grace.'),
('Matthew', 5, 'adults', 5, 'What is the theological tension in Jesus'' treatment of divorce in Matthew 5:31-32 compared to Deuteronomy 24:1?', 'Moses permitted divorce as a concession to hardness of heart; Jesus restricts it to adultery (porneia), elevating the creational ideal', 'Jesus abolishes all divorce law as part of the new covenant', 'Moses only permitted divorce for priests; Jesus extends this to all', 'There is no tension — Jesus simply reaffirms Mosaic law', 'a', 'Matthew 5:31-32 — "It hath been said, Whosoever shall put away his wife, let him give her a writing of divorcement: But I say unto you, That whosoever shall put away his wife, saving for the cause of fornication, causeth her to commit adultery." Jesus exposes Moses'' concession (Deut 24:1) and restores God''s original design.'),
('Matthew', 5, 'adults', 6, 'What is the significance of the phrase "iota or tittle" (jot and tittle) in Matthew 5:18?', 'The yod (smallest Hebrew letter) and tittle (smallest stroke) signal the inviolability of every detail of Scripture until its purposes are fulfilled', 'It means only the ceremonial law will pass away', 'It refers to the importance of proper scribal calligraphy', 'It means the NT supersedes the OT entirely', 'a', 'Matthew 5:18 — "For verily I say unto you, Till heaven and earth pass, one jot or one tittle shall in no wise pass from the law, till all be fulfilled." Yod (jot) is the smallest Hebrew letter; the tittle is the smallest distinguishing stroke, emphasizing the complete authority of Scripture.'),
('Matthew', 5, 'adults', 7, 'How does Jesus reframe the lex talionis ("eye for eye") in Matthew 5:38-39?', 'He replaces retributive justice with non-resistance and enemy love, calling his disciples to absorb evil rather than perpetuate it', 'He endorses strict equal punishment as the highest justice', 'He limits the law to capital crimes only', 'He teaches that civil courts should enforce the lex talionis', 'a', 'Matthew 5:38-39 — "Ye have heard that it hath been said, An eye for an eye, and a tooth for a tooth: But I say unto you, That ye resist not evil: but whosoever shall smite thee on thy right cheek, turn to him the other also." Jesus replaces retribution with redemptive suffering.'),
('Matthew', 5, 'adults', 8, 'What does Jesus mean by letting your light "shine before men, that they may see your good works, and glorify your Father which is in heaven" (5:16)?', 'Visible kingdom ethics should point observers to God''s glory, not the disciple''s personal reputation', 'Christians should perform miracles publicly to prove their faith', 'Good works are the basis of one''s own salvation', 'Public religion is always superior to private devotion', 'a', 'Matthew 5:16 — The purpose of public good works is doxological — "glorify your Father which is in heaven." This contrasts with the hypocrites (6:1-2) who do good works to be seen by men for their own glory.');
