-- ============================================================================
-- Quiz Seed: 3 John (Chapter 1)
-- 3 difficulties × 1 chapter = 16 total questions
--   kids:   3 per chapter  =  3
--   teens:  5 per chapter  =  5
--   adults: 8 per chapter  =  8
-- ============================================================================

-- ═══ 3 John Chapter 1 ═══
INSERT INTO chapter_quizzes (book_name, chapter_number, difficulty, question_number, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
-- Kids
('3 John', 1, 'kids', 1, 'Who did John write this letter to?', 'Gaius', 'Timothy', 'Peter', 'Titus', 'a', '3 John 1:1 — "The elder unto the wellbeloved Gaius, whom I love in the truth."'),
('3 John', 1, 'kids', 2, 'What did John say he had no greater joy than?', 'Hearing that his children walk in truth', 'Receiving gifts', 'Building churches', 'Traveling to new places', 'a', '3 John 1:4 — "I have no greater joy than to hear that my children walk in truth."'),
('3 John', 1, 'kids', 3, 'Who was a bad example in this letter because he loved to be first?', 'Diotrephes', 'Gaius', 'Demetrius', 'John', 'a', '3 John 1:9 — "Diotrephes, who loveth to have the preeminence among them."'),
-- Teens
('3 John', 1, 'teens', 1, 'What good thing did John praise Gaius for?', 'Showing hospitality to travelling brethren and strangers', 'Building a large church', 'Writing many letters', 'Performing miracles', 'a', '3 John 1:5 — "thou doest faithfully whatsoever thou doest to the brethren, and to strangers."'),
('3 John', 1, 'teens', 2, 'What did Diotrephes do to those who wanted to welcome the brethren?', 'He cast them out of the church', 'He congratulated them', 'He ignored them', 'He sent them money', 'a', '3 John 1:10 — "neither doth he himself receive the brethren, and forbiddeth them that would, and casteth them out of the church."'),
('3 John', 1, 'teens', 3, 'What did John say about Demetrius?', 'He had a good report from all men and from the truth itself', 'He was a wealthy merchant', 'He was a new convert', 'He was a Roman official', 'a', '3 John 1:12 — "Demetrius hath good report of all men, and of the truth itself."'),
('3 John', 1, 'teens', 4, 'What does John say about imitating?', 'Follow not that which is evil, but that which is good', 'Imitate the leaders of the synagogue', 'Follow the customs of the Romans', 'Imitate only the apostles', 'a', '3 John 1:11 — "Beloved, follow not that which is evil, but that which is good."'),
('3 John', 1, 'teens', 5, 'Why did the travelling brethren go forth?', 'For the sake of the Name (of Jesus), taking nothing of the Gentiles', 'To earn money from preaching', 'To escape persecution in Jerusalem', 'To find new trade routes', 'a', '3 John 1:7 — "Because that for his name''s sake they went forth, taking nothing of the Gentiles."'),
-- Adults
('3 John', 1, 'adults', 1, 'What does John''s opening wish for Gaius reveal about his pastoral concern?', 'He wishes that Gaius may prosper and be in health, even as his soul prospereth — showing concern for whole-person wellbeing', 'He wishes Gaius financial success', 'He commands Gaius to fast and pray', 'He asks Gaius to send money', 'a', '3 John 1:2 — "I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth."'),
('3 John', 1, 'adults', 2, 'What does John say is the duty of believers toward travelling missionaries?', 'We ought to receive and support such, that we might be fellowhelpers to the truth', 'We should test them for a year before helping', 'We should send them to the synagogue for support', 'We should only support those from our own church', 'a', '3 John 1:8 — "We therefore ought to receive such, that we might be fellowhelpers to the truth."'),
('3 John', 1, 'adults', 3, 'What three specific charges does John level against Diotrephes?', 'He loves preeminence, speaks malicious words against the apostles, and refuses to receive the brethren while casting out those who do', 'He steals money, lies about his credentials, and worships idols', 'He denies the resurrection, rejects baptism, and forsakes the assembly', 'He teaches false doctrine, forbids prayer, and burns Scripture', 'a', '3 John 1:9-10 — "Diotrephes, who loveth to have the preeminence… prating against us with malicious words: and not content therewith, neither doth he himself receive the brethren, and forbiddeth them that would, and casteth them out."'),
('3 John', 1, 'adults', 4, 'What theological principle does John state about doing good and doing evil?', '"He that doeth good is of God: but he that doeth evil hath not seen God"', '"Good and evil are equal paths to knowledge"', '"Evil is merely the absence of good"', '"Only God can truly distinguish good from evil"', 'a', '3 John 1:11 — "He that doeth good is of God: but he that doeth evil hath not seen God."'),
('3 John', 1, 'adults', 5, 'What is significant about Demetrius having testimony from "the truth itself"?', 'It means his life and doctrine are validated not only by human witnesses but by the objective standard of divine truth', 'The truth is a person who wrote a letter about him', 'He passed a written examination on Scripture', 'He was recognized by the Roman senate', 'a', '3 John 1:12 — "Demetrius hath good report of all men, and of the truth itself: yea, and we also bear record."'),
('3 John', 1, 'adults', 6, 'What does John say he wrote to the church, and what happened?', 'He wrote to the church, but Diotrephes would not receive them (the letter/messengers)', 'He wrote asking for money but was refused', 'He wrote to schedule a visit but weather delayed him', 'He wrote a doctrinal treatise that was lost', 'a', '3 John 1:9 — "I wrote unto the church: but Diotrephes, who loveth to have the preeminence among them, receiveth us not."'),
('3 John', 1, 'adults', 7, 'How does John plan to address the situation with Diotrephes?', '"If I come, I will remember his deeds which he doeth" — indicating personal apostolic confrontation', 'He will write a stronger letter', 'He will send Peter to deal with it', 'He will excommunicate him from afar', 'a', '3 John 1:10 — "if I come, I will remember his deeds which he doeth, prating against us with malicious words."'),
('3 John', 1, 'adults', 8, 'How does John close this letter, and what does it reveal about early church communication?', 'He prefers face-to-face conversation over writing, showing the importance of personal presence in apostolic ministry', 'He asks Gaius to burn the letter for safety', 'He sends a formal blessing through the bishop', 'He attaches a creedal statement for the church to sign', 'a', '3 John 1:13-14 — "I had many things to write, but I will not with ink and pen write unto thee: But I trust I shall shortly see thee, and we shall speak face to face."');
